### ISSUE TITLE
CPYTON TO DLL?

### ISSUE THREAD

**Issue by Nicolasbougon** [eirannejad/pyRevit#1002]
Hello,
I would like to know if it is possible to convert CPython3 programs to dll in order to create plugins without installing python or ironpython on the computer. The goal would be to do the same as the revit python shell "Deploy RpsAddin" but with CPython3 and not ironpython.
Otherwise in order to bypass this, we can create an exe instead of the dll, if so is there any domantation on the methodology. The problem is, I am not fluent in C #.

**Comment by eirannejad** [comment]
Not at the moment. CPython runtime is about 15MB in size so it needs to be shipped with every compiled script you create which doesn't make sense. There is also the problem of conflicting cpython versions across many compiled scripts.

**Comment by Nicolasbougon** [comment]
OK, thanks
