### ISSUE TITLE
Basic Script Parameters for a Dynamo Script

### ISSUE THREAD

**Issue by DrLicor** [eirannejad/pyRevit#1003]
Whenever making a custom extension containing dynamo scripts, I ran into an issue regarding the basic parameters.
I would like to add a description, name, author etc to my Pushbuttons like documented here: https://pyrevit1.readthedocs.io/en/latest/scriptanatomy.html

So for instance, placing * __doc__ = 'This is the text for the button tooltip associated with this script.' * at the top of a dynamoscript, it won't show that on the Pushbutton.

I assume that's because dynamoscripts are C++ and the basic commands are for python. Is there a way to get those basic parameters and command availability in the dynamo scripts?

**Comment by eirannejad** [comment]
Take a look at the documentation of Bundle Metadata file: https://www.notion.so/Bundle-Metadata-9fa4911c14fa49c48e715421400f1427
