### ISSUE TITLE
Failed to Load - Revit 2021 21.1.10.26

### ISSUE THREAD

**Issue by Fozibehr** [eirannejad/pyRevit#1005]
Message that's received after installing the latest patch from Autodesk for Revit 2021:

![pyREVIT](https://user-images.githubusercontent.com/59780562/93871347-7ec29300-fc9c-11ea-9652-e9729061d811.jpg)

**Comment by eirannejad** [comment]
https://github.com/eirannejad/pyRevit/issues/890#issuecomment-696962169

**Comment by eirannejad** [comment]
Related to #890
