### ISSUE TITLE
pyRevit can not attach to a Revit that it does not know its build number

### ISSUE THREAD

**Issue by sotomangel** [eirannejad/pyRevit#1007]
Hello.

Thanks for the plugin it works perfectly, but I have a inconvenient. I want to install pyRevit in two version of Revit (2020,2021) but I couldn't do, because the installer only install in one version.

Is there any procedure to install in more than one version?

I'll appreciate your answer.

**Comment by eirannejad** [comment]
pyRevit attaches itself to all the installed Revit versions. But after installation you can [use the pyRevit Settings](https://www.notion.so/pyrevitlabs/Configure-pyRevit-461d8f564ba743d0ad7e843a7b3b2afe#c284a285c3584fadbadef32ba1b3a5bc) on the [pyRevit CLI to attach to other Revit versions](https://www.notion.so/pyrevitlabs/Attach-pyRevit-to-Installed-Revits-abf190044ffc4ac29671152ec9b91335)

**Comment by sotomangel** [comment]
Thanks for reply, but in this option it shows that Revit 2021 is not installed, but I have Revit 2021 Also.

**Comment by sotomangel** [comment]
![pyrevit](https://user-images.githubusercontent.com/71778364/94039508-d133aa80-fd95-11ea-99fc-589de4626981.PNG)
I have the last version of Revit 2021.1.1

**Comment by eirannejad** [comment]
Hmm okay. Open a command line and run `pyrevit update` to grab the latest list of Revit version info. Then try this again. I'll open this issue as a bug

**Comment by sotomangel** [comment]
Thanks, it worked perfectly.

**Comment by eirannejad** [comment]
Fixed and will be published with next release

**Comment by sotomangel** [comment]
Amazing. Thanks again.
