### ISSUE TITLE
PyRevit Update not responding

### ISSUE THREAD

**Issue by Architectuur** [eirannejad/pyRevit#1008]
**Describe the bug**
When I click on the update button the command does not seem to finish. 

**To Reproduce**
1. Go to pyRevit and click on update

**Expected behavior**
Your update video suggests that a window will come up and provide feedback saying that updates were downloaded. When I click on the update button a wheel spins for a second and then nothing else.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version v4.8.1
 - pyRevit Environment: Super novice, I don't know how to retrieve this.

**Comment by eirannejad** [comment]
Currently, pyRevit update only updates the third-party extensions. To get a new version of pyRevit, download the installer and install the new version. The Update button however can update the pyRevit clone if it is a git repository clone.
