### ISSUE TITLE
Implement Refreshing CPython engine

### ISSUE THREAD

**Issue by Nicolasbougon** [eirannejad/pyRevit#1009]
Hello,
When creating a script with! # Python3, the button only works once. I have to restart revit for it to work again. Is there a solution?

**Comment by eirannejad** [comment]
What happens when you click on the button the second time? What's the script?

**Comment by Nicolasbougon** [comment]
The modules of the script.py are .pyd files. During the second click nothing happens.

![ex](https://user-images.githubusercontent.com/31243530/94058840-dd455980-fde1-11ea-8194-eea7fc561fe5.png)


The script file calls the "main" file. The "main" file calls "OK" (print ("ok")), "BONSOIR" (print ("good evening")), "HELLO" (print ("hello")).

**Comment by eirannejad** [comment]
Those modules are only imported once on the first run. So if the print statement is inside the modules it's going to be printed only once

**Comment by Nicolasbougon** [comment]
Is there a way to re-import them manually in order to rerun?

**Comment by eirannejad** [comment]
Try CTRL+SHIFT+ALT and click on the tool. This will discard the existing engine and will use a new engine. Need to test this more with the cpython as it works very different from the IronPython

**Comment by Nicolasbougon** [comment]
I had already tested this manipulation but it does not work. I have an error message then REVIT does not respond.

![Capture](https://user-images.githubusercontent.com/31243530/94190639-aab46300-feac-11ea-8151-ee05e13e7fd4.PNG)

Thanks anyway.

**Comment by mrjoneskod** [comment]
Hey, @eirannejad is there an ETA for this? How can I help? If you point the way I can spend some time on this as well.
I am looking forward to have CPython, ---NEED FOR SPEED --- 🚀
