### ISSUE TITLE
Pyrevit not loading in Revit although installed in Addins folder

### ISSUE THREAD

**Issue by carolinejanetdunn** [eirannejad/pyRevit#1013]
_Disclaimer: I have read all through this forum but I don't understand how to accomplish any of the solutions you have suggested since I don't know how to program computers._

**1.** I have run the installer with no errors, opened Revit, and was never asked to load the new plug in. It does not show up in my AddIns tab.

**2.** I have uninstalled and re-installed Pyrevit in the AddIns folder within my Revit folder. Still doesn't load.

**3.** I have run this in Terminal (watched a Youtube video about how to run a command in Terminal)

`pyrevit attach master 277 --installed`

But I only get this message:

'pyrevit' is not recognized as an internal or external command,
operable program or batch file.

How do I install your program correctly? And can you explain it the process to someone at my level?

Thank you so so much!

**Comment by eirannejad** [comment]
@carolinejanetdunn I'm really sorry for the troubles this has caused you. If you are getting the `'pyrevit' is not recognized ...` error, it means that the console can not find the `pyrevit.exe` utility that is under the `bin/` directory inside the pyRevit installation path. Let's make sure that is fixed first. Follow the steps below to add the path to your system:

1) Open
![Screen Shot 2020-10-05 at 12 18 14](https://user-images.githubusercontent.com/8197916/95122222-04b2f500-0705-11eb-92be-172db1eb769d.png)

2) Edit environment variables
![explorer_PIxVJPav1N](https://user-images.githubusercontent.com/8197916/95122388-49d72700-0705-11eb-87d0-6e93de63ed3a.png)

3) Edit `PATH`
![explorer_Nu3Sq7EGnP](https://user-images.githubusercontent.com/8197916/95122411-4f347180-0705-11eb-9d9e-8d959ae4da46.png)

4) Add the path (preferable towards the top of the list. The path shown in the image is different from yours. After installing pyRevit your path should be under `%APPDATA%/pyRevit-Master/bin/` unless you install pyRevit somewhere else
![explorer_5wNCaEpszD](https://user-images.githubusercontent.com/8197916/95122418-50fe3500-0705-11eb-9db5-2d1dae77c35e.png)

Now open a new command line (`powershell` or `cmd`) and run `pyrevit env` and share the results

**Comment by carolinejanetdunn** [comment]
Thank you! Here are the results:

Microsoft Windows [Version 10.0.19041.508]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\Caroline>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.2" | Path:
"C:\Users\Caroline\AppData\Roaming\Autodesk\Revit\Addins\2020"
==> Attachments
master | Product: "2020 First Customer Ship" | Engine: 277 | Path:
"C:\Users\Caroline\AppData\Roaming\Autodesk\Revit\Addins\2020" | Manifest:
"C:\Users\Caroline\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Caroline\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2020 First Customer Ship | Version: 20.0.0.377 | Build: 20190327_2315(x64)
| Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19041]
Executing User: DESKTOP-0HER881\Caroline
Active User: DESKTOP-0HER881\Caroline
Admin Access: No
%APPDATA%: "C:\Users\Caroline\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.2.0

C:\Users\Caroline>


Cal Poly San Luis Obispo
*Architecture | Environmental Design*
512.449.2424

**Comment by eirannejad** [comment]
Okay so now run the `pyrevit attach master 277 --installed` and it should attach pyRevit.

**Comment by carolinejanetdunn** [comment]
Dear Ehsan -

The plug-in is installed but I have one last question for you. When using
the Make Pattern tool, I am getting an extra line that applies to the
pattern when it's tiled... (When I manually copy the pattern this line
doesn't appear...)  Can you explain why this is happening and how to get
rid of it? I have attached a screenshot so you can see what's going on. The
Filled Region on the left has the Hatch applied, the pattern on the right
is the reference I used for the Pyrevit tool.

[image: image.png]

Best,
Caroline


Cal Poly San Luis Obispo
*Architecture | Environmental Design*
512.449.2424

**Comment by eirannejad** [comment]
@carolinejanetdunn Not sure. Would you mind sharing the pattern so I can test?

**Comment by paola1001** [comment]
Hi @eirannejad ! 
I'm in the same boat than Caroline, I'm no programmer and can't seem to resolve the problem of pyrevit not loading into revit. I downloaded the lastest version, it didn't work, than tried it with the previous one, same problem. For information, I use revit 2020. 

However, I was able to get results for the pyrevit env in the command prompt : 

C:\Users\paola>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.8" | Path: "C:\Users\paola\AppData\Roaming\pyRevit-Master"
==> Attachments
==> Installed Extensions
==> Default Extension Search Path
C:\Users\paola\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19044]
Executing User: LAPTOP-4SU8TQHU\paola
Active User: LAPTOP-4SU8TQHU\paola
Admin Access: No
%APPDATA%: "C:\Users\paola\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.10.22040+1743

Do you think you can help me ? 
Thank you so much for your attention !
