### ISSUE TITLE
Print Sheets not included in schedule

### ISSUE THREAD

**Issue by Architectuur** [eirannejad/pyRevit#1017]
**Is your feature request related to a problem? Please describe.**
I would like to print sheets that are not included in a schedule

**Describe the solution you'd like**
Under the Sheet index (Schedule) drop down could there be an All Sheets option?

**Additional context**
![image](https://user-images.githubusercontent.com/69218770/94749313-c43c2b80-0340-11eb-9a86-514a7ceeea6d.png)

**Comment by eirannejad** [comment]
The list shows all the drawing index schedules in your model. Create a simple drawing index that sorts and shows all your sheets and it will listed on the dropdown as well

**Comment by eirannejad** [comment]
@Architectuur Oh yeah good point. I'll reopen this

**Comment by eirannejad** [comment]
Fixed and will be published with next release 

![Screen Shot 2021-03-22 at 2 04 22 PM](https://user-images.githubusercontent.com/8197916/112058210-89f55f00-8b17-11eb-99e2-d0186791d7d5.png)
