### ISSUE TITLE
After I updated my Revit2021, pyRevit stopped loading.

### ISSUE THREAD

**Issue by Siojie** [eirannejad/pyRevit#1019]
![pyRevit Error](https://user-images.githubusercontent.com/72231295/94865719-979c2700-049a-11eb-93e1-b4c9ec80e3b3.jpg)

**Comment by eirannejad** [comment]
Please run `pyrevit caches clear --all` on the console and launch Revit again

**Comment by eirannejad** [comment]
- [ ] Include the complete semantic Revit version in caching so the cache is discarded when Revit has a new service pack

**Comment by Siojie** [comment]
Thank you!
