### ISSUE TITLE
Can't exit "Find Referring Views" with esc key - regen graphics for every view in revit??

### ISSUE THREAD

**Issue by ariccb** [eirannejad/pyRevit#1020]
**Describe the bug**
Using the "Find referring views" tool, it starts to run and there's no way to exit it, and it's an extremely long running tool. It is going through every single view in my revit file and "Generating graphics for {insert view here}."

I'm not sure what the utility is supposed to be for this tool, because when it finishes, nothing is listed, and nothing happens. It's just completely disabling revit for me while it tries to go through the whole script. 

**To Reproduce**
1. Go to 'DrawingSet>Sheets>Find Referring Views'
2. Watch pyrevit struggle to get through hundreds of views
3. pressing escape, trying to close the pyrevit logger window, etc. doesn't stop the process.

**Expected behavior**
I think the script is supposed to run very quickly.... and not need to regenerate views - no views are supposed to be opened and displayed to the user for this command. I think....

**Screenshots**
![image](https://user-images.githubusercontent.com/48956351/94870130-067a7100-0404-11eb-80b9-62034f03a80f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
![image](https://user-images.githubusercontent.com/48956351/94870177-29a52080-0404-11eb-8766-2d126fbb5684.png)

 - pyRevit Version [e.g. 22]
 - pyRevit Environment:
'''
H:\>`pyrevit env`   '`pyrevit' is not recognized as an internal or external command,  operable program or batch file.                                                                                                                                 
'''
**Additional context**

**Comment by eirannejad** [comment]
So that's how the tool is designed to work at the moment. The underlying Revit API needs to generate the graphics for each view, so this tool can find all the view references (e.g. sections, elevations, ...) on that view and report that as a referencing view.

**Comment by ariccb** [comment]
> So that's how the tool is designed to work at the moment. The underlying Revit API needs to generate the graphics for each view, so this tool can find all the view references (e.g. sections, elevations, ...) on that view and report that as a referencing view.

isn't there supposed to be some sort of output of the resulting views that refer to the one i ran the tool on?

**Comment by eirannejad** [comment]
There is not?! Okay let me test this tool again.

**Comment by ClaytonKimball** [comment]
I think this tool should show a warning before running.  "This process could take hours to run and cannot be cancelled."
