### ISSUE TITLE
Linkify enhancement

### ISSUE THREAD

**Issue by tamder** [eirannejad/pyRevit#1021]
**Describe the solution you'd like**
The linkify function is great, and works pretty well with views, and annotation elements, but Revit's built-in Show function (which linkify is using I believe) can behave quite funky with 3D elements. Even if I have a view active which clearly shows the element referenced in the hyperlink Revit often opens another view (most of the time the oldest 3D View, which is usually quite heavy in actual projects, for us it is even perspective), and that makes the user jump between views, and that ruins the experience. I've found that sometimes only selecting the element is more than enough, and the user still has a chance to hit BX, and in this case the users Default View will show the element with a section box. 
What I would suggest is to have an option for the linkify function that instead of "Showing" the element only selects it. The default behaviour can stay as it is, only an additional argument would be great.

**Describe alternatives you've considered**
The element id can be copied from the hyperlink, and can be selected via the Revit UI but thats kinda meh.

**Comment by eirannejad** [comment]
Makes a lot of sense! I'm putting this on the priority stack.

**Comment by Robbo1234** [comment]
Hi Ehsan, what's Linkify called in PyRevit because I can't seem to find it.

Rob

**Comment by eirannejad** [comment]
@Robbo1234 https://www.notion.so/pyrevitlabs/Effective-Output-43baf34d2ca247ada8e040bcb86613a2#483fafe483044956addee6a129a7032d

**Comment by eirannejad** [comment]
@tamder How's this implementation? (The new arrow only selects the elements and does not attempt to show)

![DE43xUpkkh](https://user-images.githubusercontent.com/8197916/95109254-35892f00-06f1-11eb-98da-ee652adb5420.gif)

**Comment by tamder** [comment]
It seems perfect, even better than what I imagined! ;)

**Comment by eirannejad** [comment]
@tamder Final version. Decided to switch the functions and add a search icon instead of select. It's more intuitive this way I think.

![ZAbIhr9jDQ](https://user-images.githubusercontent.com/8197916/95121028-4e024500-0703-11eb-87c7-4e22a4c2a41d.gif)

**Comment by eirannejad** [comment]
Fixed and will be published with next release

**Comment by tamder** [comment]
Agree. This is the way it should work.

**Comment by Robbo1234** [comment]
> @Robbo1234 https://www.notion.so/pyrevitlabs/Effective-Output-43baf34d2ca247ada8e040bcb86613a2#483fafe483044956addee6a129a7032d

Thanks Ehsan

Btw, seems to be some broken hyperlinks to PyRevit documentation.  Rob
![image](https://user-images.githubusercontent.com/8776947/95196645-4197ee00-07d0-11eb-9b79-e6bceb27a097.png)
