### ISSUE TITLE
PyRevitLoader - Failure to load PyRevit when launching Revit 2021, 2019

### ISSUE THREAD

**Issue by tes2ube** [eirannejad/pyRevit#1022]
**Describe the bug**
Hello,

I am currently trying to load PyRevit and am running into this issue on both Revit 2021 and Revit 2019 (this error is from 2021).

![PyRevit 1](https://user-images.githubusercontent.com/72454836/95215464-fe814f00-07be-11eb-8e4d-7cf76318fe55.PNG)
![PyRevit 2](https://user-images.githubusercontent.com/72454836/95215478-03460300-07bf-11eb-82d1-2610a6a3c960.PNG)

I used command prompt to apply the following commands (from reading another person's issues that seemed similar):

```pyrevit attach master 277 --installed```

```pyrevit attach master 277 2021```

I tried runnnig separately each time. They did not change anything. PyRevit has certainly worked in the past, and I am not sure what has changed. I have installed recent updates to Revit 2021 so perhaps that has affected it.

Note that I have also used the AddInManager (pulled from the debug bin of Rhino Inside) to disable every other plugin. No dice. Restarting doesn't change anything, nor does reinstallation.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro, 10.0.18363 Build 18363
 - pyRevit Version [4.8.2_signed]
 - pyRevit Environment:

```==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.2" | Path: "C:\Users\fberg\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2020.2.1 (New Install)" | Engine: 277 | Path: "C:\Users\fberg\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\fberg\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
master | Product: "2019.2.2 Hotfix" | Engine: 277 | Path: "C:\Users\fberg\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\fberg\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\fberg\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2020.2.1 (New Install) | Version: 20.2.12.1 | Build: 20200210_1400(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "E:\Program Files\Autodesk\Revit 2019"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages```

Thanks in advance!

**Comment by mahdibau** [comment]
Having the same issue here with Revit 2020, can anyone please help solve this issue?

**Comment by eirannejad** [comment]
Working on a fix

**Comment by eirannejad** [comment]
Fixed and will be published with next release

**Comment by Thekinghn** [comment]
I am having a similar issue, have revit 2019.2 and revit 2021 installed and pyrevit its just working on the 2019, the installed version of pyrevit is 4.8.5.0

Thanks in Advance

**Comment by eirannejad** [comment]
What errors do you get on 2020/21?

**Comment by Thekinghn** [comment]
no errors, simply the menu it's not there or the option to load the program.

**Comment by Thekinghn** [comment]
I'm sorry, but noiw, after a Bios update and startin revit 2021 I got this:

[image: image.png]

Thanks for your help


Elvis

**Comment by eirannejad** [comment]
Would you mind sharing the report from `pyrevit env` command?

**Comment by Thekinghn** [comment]
Good morning and thanks...

As you can see, it's running with no problem in 2019, but in 2021 it does
not.


Microsoft Windows [Version 10.0.18363.1316]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\ealandaverde>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.5" | Path:
"C:\Users\ealandaverde\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2019.2.2 Hotfix" | Engine: IPY277 (277) | Path:
"C:\Users\ealandaverde\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\ealandaverde\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) |
Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
PID: 13840 | 2019.2.2 Hotfix | Version: 19.2.20.24 | Build:
20190808_0900(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit
2019"
==> User Environment
Microsoft Windows 10 [Version 10.0.18363]
Executing User: GARVERINC\EALandaverde
Active User: GARVERINC\EALandaverde
Admin Access: No
%APPDATA%: "C:\Users\ealandaverde\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.5.0

**Comment by Thekinghn** [comment]
Microsoft Windows [Version 10.0.18363.1316]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\ealandaverde>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.5" | Path: "C:\Users\ealandaverde\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2019.2.2 Hotfix" | Engine: IPY277 (277) | Path: "C:\Users\ealandaverde\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\ealandaverde\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
PID: 13840 | 2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> User Environment

looks like pyrevit is not "seeing" the revit 2021 install
