### ISSUE TITLE
Allow search engines on Notion pages

### ISSUE THREAD

**Issue by sanzoghenzo** [eirannejad/pyRevit#1023]
I find it hard to find pyrevit documentation when searching with google;
in fact, only github issues and (old) read the docs pages show up.
To get notion docs pages I have to remember the URL or come here and click the link in the main page.

It seems that there is [an option to enable search engines](https://www.notion.vip/notion-sharing-hierarchy/#AllowSearchEngines) on public notion pages, that it [disabled by default](https://twitter.com/notionhq/status/1224458901023682560).

Please enable that for your doc pages.

**Comment by eirannejad** [comment]
@sanzoghenzo You know "bookmarks" have been invented right? 🤣 Just kidding. I checked the notion settings and the google indexing is allowed

<img width="434" alt="Screen Shot 2020-10-07 at 08 56 52" src="https://user-images.githubusercontent.com/8197916/95356149-38179000-087b-11eb-8c01-f0da2201630b.png">

**Comment by sanzoghenzo** [comment]
> @sanzoghenzo You know "bookmarks" have been invented right? 🤣 Just kidding. 

🤣🤣

Thanks for taking the time to look at this.
Indeed, the pages show up in the search results, but they are way in the second page or so.
If I try the search in an incognito (just to avoid any bias) window they are at least in the second page; the more keyword I use, the less the chance to find something.

Restricting the search to `site:notion.so` works ok. I added a custom search engine to chrome, no need for bookmarks now 😆 

It seems a problem with notion.so in general, at list [to my findings](https://www.indiehackers.com/post/do-you-use-notion-as-a-website-be80f75ced?commentId=-MCqDXbPVxaR3T5NLPtC).

Thanks again,
keep up the good work!
