### ISSUE TITLE
UI Error Slideout panel is already added to the current panel.

### ISSUE THREAD

**Issue by Kassicus** [eirannejad/pyRevit#1024]
I am getting this error while loading into Revit, all of the tools are still working and the slideout is fully functional.

INFO [pyrevit.loader.sessioninfo] pyRevit version: 4.7.6 - </> with  in ['pdx', 'hio', 'rno', 'sea']
INFO [pyrevit.loader.sessioninfo] pyRevit Rocket Mode enabled. 
INFO [pyrevit.loader.sessioninfo] Host is Autodesk Revit 2020.0 build: 20190327_2315(x64) pid: 17376
INFO [pyrevit.loader.sessioninfo] Running on: 2.7.7 (IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (64-bit))
INFO [pyrevit.loader.sessioninfo] User is: ksuchow
INFO [pyrevit.loader.sessioninfo] Home Directory is: C:\Users\ksuchow\AppData\Roaming\pyRevit-Master
INFO [pyrevit.loader.sessioninfo] Session uuid is: 32d539ee-b35f-4ab8-84c2-3e4b48fdfb02
INFO [pyrevit.loader.sessioninfo] Runtime assembly is: pyRevit_2020_ad6ae441c89b1da8_PyRevitLabs.PyRevit.Runtime
INFO [pyrevit.loader.sessioninfo] Config file is (User): C:\Users\ksuchow\AppData\Roaming\pyRevit\pyRevit_config.ini
INFO [pyrevit.loader.sessionmgr] Extension assembly created: NexusExtension
INFO [pyrevit.loader.sessionmgr] Extension assembly created: pyRevitCore
INFO [pyrevit.loader.sessionmgr] Extension assembly created: pyRevitCore
INFO [pyrevit.loader.sessionmgr] Running startup tasks for NexusExtension
INFO [pyrevit.loader.sessionmgr] Running startup tasks for pyRevitCore
INFO [pyrevit.loader.sessionmgr] Running startup tasks for pyRevitCore
INFO [pyrevit.loader.sessionmgr] UI created for extension: NexusExtension
INFO [pyrevit.loader.sessionmgr] UI created for extension: pyRevitCore

ERROR [pyrevit.loader.uimaker] UI error: Error adding slide out: Slideout panel is already added to the current panel.

INFO [pyrevit.loader.sessionmgr] UI created for extension: pyRevitCore
INFO [pyrevit.loader.sessionmgr] Load time: 10.4796905518 seconds

**Comment by eirannejad** [comment]
Check the layout definitions in your `NexusExtension` extension. At least one has more than one `>>>>>` defined. This creates a slideout but each panel can only have one slideout. [See Wiki](https://www.notion.so/pyrevitlabs/Bundle-Layout-39f1491439d44343896fe0adc4270129)
