### ISSUE TITLE
Updated Dynamo and getting an error

### ISSUE THREAD

**Issue by BJozi** [eirannejad/pyRevit#1026]
I had Dynamo updated to 2.0.4 (Revit 2019) and now when opening Revit I get the error below (PyRevit v4.7.4)

![image](https://user-images.githubusercontent.com/41693573/95454951-07ac2080-0965-11eb-858a-39d66786c14f.png)

I'm sure I had this same issue in the past, I can't find where I may have asked before? What I have tried so far is:

`pyrevit detach --all`
And then 
`pyrevit attach master 277 --installed`

This is probably something simple and doesn't warrant a post but I can't find a solution. 

I'm unable to uninstal/reinstal PyRevit as that requires admin to do it.

**Comment by eirannejad** [comment]
try `pyrevit caches clear --all` and run Revit again

**Comment by BJozi** [comment]
That resolved it! 

Would I face issues if I ran that command in future?

**Comment by eirannejad** [comment]
Nope. That command basically clears the pyRevit caches. So next time you launch Revit, pyRevit recompiles itself again. Glad this solved the issue. I'm going to close this but feel free to open again if the issue persists.
