### ISSUE TITLE
CLI env --json

### ISSUE THREAD

**Issue by thumDer** [eirannejad/pyRevit#1031]
**Describe the bug**
On some of our computers the `pyrevit env --json` command fails with the following output:
```
Error: Nem található a következő elérési út egy része.: "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework".
Run with "--debug" option to see debug messages 
```
`--debug` not seem to help here.
The hungarian part means cannot find part of path. Those computers have .net 4.8 installed, so it wont let me install 4.7.1, only net runtime 2.0.7..

The normal text `pyrevit env` provides the flollowing:
```
Microsoft Windows 10 [Version 10.0.18363]
Executing User: IN-EX\inex.VR
Active User: 
Admin Access: No
%APPDATA%: "C:\Users\inex.vr\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.2.0
```

I don't get why it says No .Net Target Packs are installed. and No .Ne-Core Target Packs are installed. I guess that should be the issue but I can't find a way to fix it.

**Comment by eirannejad** [comment]
Missing target packs is not an issue. Does this path `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework` exist on your machine?

**Comment by eirannejad** [comment]
Fixed and will be published with next release

**Comment by thumDer** [comment]
Yes it does, and it looks like below. Thanks for the efforts!
```
PS C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework> ls


    Directory: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----     2020. 09. 01.     15:50                v3.5
d-----     2020. 09. 01.     15:50                v4.0
d-----     2020. 09. 01.     15:50                v4.5
d-----     2020. 09. 01.     15:50                v4.5.1
d-----     2020. 09. 01.     15:50                v4.5.2
d-----     2020. 09. 01.     15:50                v4.6
d-----     2020. 09. 01.     15:49                v4.6.1
d-----     2020. 09. 01.     16:49                v4.7
d-----     2020. 09. 01.     15:50                v4.7.1
d-----     2020. 09. 01.     15:49                v4.7.2
d-----     2020. 09. 01.     15:49                v4.X
```

**Comment by thumDer** [comment]
Sorry for the confusion, but it did work on my computer where I have the .NETFramework folder, but you were right, it didn't work where that folder did not exist, even with v4.8 installed.

**Comment by eirannejad** [comment]
Okay I fixed the hardcoded paths to a smart path so windows can return the correct user path. I think this will fix the issue
