### ISSUE TITLE
Custom Extension Path not being added via CLI

### ISSUE THREAD

**Issue by fabioloretti** [eirannejad/pyRevit#1032]
**Describe the bug**
I've installed CLI successfully, went through all the documentation, searched through everyone else's issues in github or other websites, tried all the command options below in powershell but I could not update the INI file with a network path for a custom extension. In fact, even a local path didn't work either.
I've tried all of these syntax options but nothing updated my Extension Search Paths. My core clone and attachment seem to be working ok.

- pyrevit configs userextensions C:\Temp\Toolbar\Extensions

- pyrevit extensions sources add C:\Temp\Toolbar\Extensions

- pyrevit extensions sources add C:\Temp\Toolbar\Extensions\Extension.json

- pyrevit extensions paths add C:\Temp\Toolbar\Extensions

Any help would be greatly appreciated as I ran out of options. Thank you.

**Comment by eirannejad** [comment]
`pyrevit extensions paths add C:\Temp\Toolbar\Extensions` this should work if the `C:\Temp\Toolbar\Extensions` path actually exist. Do you get an error? Run `pyrevit extensions paths add C:\Temp\Toolbar\Extensions --debug` and share the debug log

**Comment by fabioloretti** [comment]
Yep, for some reason it's working now, thank you.  👍
