### ISSUE TITLE
Sheet sorted issues

### ISSUE THREAD

**Issue by chiaoweiyu** [eirannejad/pyRevit#1035]
Hello there,

First of all, thank you all for developing such a great tool, I pretty much use this tool every 5 minutes, seriously can't live without this tool.

Recently our team has been having issues when we create the sheets using batch sheets creation, and then after a while, we decided to add more sheets that in between the sheets. We noticed the sheets organize is not sorted by the numbers (we checked on the sheet organization setting already ) 

the only solution I could find is to find those ones that not having the sorting issues, copy the sheet number and then paste to the sheet numbers that having issues. This is the weirdest thing ever, even it is the same sheet number, but after I paste to replace the number, it's sorting fine again.

I can't find any resource to see if that's a Revit 2019 bug, so then I tried to create a sheet with the manual way, and it didn't have the same issues.

Thank you all in advance, hopefully, this feedback is helpful!

**Comment by eirannejad** [comment]
I tested this and everything is working fine. Take a look at your model and make sure there are no invisible characters in the sheet numbers that forces them to be sorted differently. pyRevit batch sheet tool only creates these sheets and has nothing to do with how they are sorted
