### ISSUE TITLE
Issue while installing new (any) version on previous one (yet uninstalled) ...

### ISSUE THREAD

**Issue by cityinterface** [eirannejad/pyRevit#1036]
Hello,

I'm experiencing some issues while installing new version of Pyrevit saying previous version can't be uninstalled...
Any idea?
I pasted log and printscreen for you to help me passing through this problem.

Thank you per advance,

AC

![Pyrevit issue installing](https://user-images.githubusercontent.com/13923044/96424097-86714b00-11fa-11eb-9734-19117fbb51b9.jpg)
[MSIBCA6.LOG](https://github.com/eirannejad/pyRevit/files/5400474/MSIBCA6.LOG)

**Comment by eirannejad** [comment]
So the previous version is already uninstalled?

**Comment by cityinterface** [comment]
Yes, i uninstalled it in the proper way then delete roaming folder and
other files it lasts by performing pyrevit search.
I do not understand why installer prompt for error.
Any Idea or 3rd party unstaller available?
Just look at least for initial version reinstall.
Thx ;)

AC

Le lun. 19 oct. 2020 à 23:24, Ehsan Iran-Nejad <notifications@github.com> a
écrit :

**Comment by eirannejad** [comment]
@cityinterface See this post https://github.com/eirannejad/pyRevit/issues/1045#issuecomment-724922950
