### ISSUE TITLE
Manual Install 

### ISSUE THREAD

**Issue by pyhop** [eirannejad/pyRevit#1037]
I followed this video to clone the depository:  

https://www.youtube.com/watch?v=hrlkPRoUfXc 

There is no batch files in the release folder. Is there reference on how to proceed somewhere?

**Comment by davidvadkerti** [comment]
I think these references should be the latest:
- [pyRevit CLI - wiki article](https://www.notion.so/pyRevit-CLI-c50de95259114db795db5bd3f19f8e2a)
- [Deploying pyRevit - youtube video](https://www.youtube.com/watch?v=hnlAEEfzhok)
- [pyRevit CLI - youtube video](https://youtu.be/PMc02W-oAo4)
