### ISSUE TITLE
Cannot load custom extension into existing tab 

### ISSUE THREAD

**Issue by max-sun-hongyi** [eirannejad/pyRevit#1038]
**Describe the bug**
I want to load custom extension into existing tab, I followed the [instructions ](https://www.youtube.com/watch?v=zERdPh1vNBQ) on creating custom add-ins and managed to load tools in Revit. However, I'd like to minimize the number of tabs in my Revit, I tried to load the same add-ins to a tab named "Add-Ins", it failed with the below error message

ERROR [pyrevit.loader.uimaker] UI error: Can not de/activate native item: Name: Add-Ins RevitAPIObject: <UIFramework.RvtRibbonTab object at 0x00000000000011A9 [UIFramework.RvtRibbonTab]>

**To Reproduce**
1. Create folder structure with python source file.
...\MyExtensions\CustomExtension.extension\Add-Ins.tab\CustomTool.panel\Print Something.pushbutton
2. Click on pyRevit -> Settings -> Custom Extension Directories -> Load -> Select the above folder 
3. Click "Save settings and reload"

**Expected behavior**
A panal named "Custom Tool" with a pushbutton named "Print Something" will appear in the "Add-Ins" tab

**Screenshots**
![image](https://user-images.githubusercontent.com/30208620/96823972-3e119180-1475-11eb-9897-7ac733ad2a01.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - pyRevit Version [2020]
 - pyRevit Environment: NA

**Additional context**
NA

**Comment by eirannejad** [comment]
You can't load tools into existing Revit tabs. Sorry :/

**Comment by max-sun-hongyi** [comment]
Many thanks for your quick response! 
Will this feature be considered in the future release of pyRevit?

**Comment by eirannejad** [comment]
Probably not. It's better for pyRevit not to mess with the existing Revit layout because most probably it would be a massive source of bugs and unknown behaviours
