### ISSUE TITLE
Pyrevit 4.8.2 getting error on load when opening Revit 2021

### ISSUE THREAD

**Issue by oddman80** [eirannejad/pyRevit#1039]
**Describe the bug**
I have installed pyRevit using Install as Admin. It seems to work properly in Revit 2019 & 2020, but did not load in 2021. the addins folder in %appdata%\Autodesk\Revit\Addins\2021 did not have a pyRevit.addin file like the other version years did. I copied the pyRevit.addin file from the 2020 folder into %appdata%\Autodesk\Revit\Addins\2021, and then rebooted. When i relaunched revit, it seemed to try and load pyRevit, but gave an enormous error message (see linked images)
[https://i.imgur.com/5bsk7HS.png](https://i.imgur.com/5bsk7HS.png)
[https://i.imgur.com/sb66fAv.png](https://i.imgur.com/sb66fAv.png)

**When I run "pyrevit attach master 277 --installed"** 
I get:
> Error: Can not find clone "master"
> Run with "--debug" option to see debug messages

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (Version 1909)
 - pyRevit Version 4.8.2
 - pyRevit Environment: 
>==> Registered Clones (full git repos)
>==> Registered Clones (deployed from archive/image)
>==> Attachments
>==> Installed Extensions
>==> Default Extension Search Path
>C:\Users\Administrator.MININT-MK0FQPC\AppData\Roaming\pyRevit\Extensions
>==> Extension Search Paths
>==> Extension Sources - Default
>https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
>==> Extension Sources - Additional
>==> Installed Revits
>2020.2.2 (Full Install) | Version: 20.2.11.3 | Build: 20200206_0915(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
>2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
>2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018"
>2017.2.5 Security Fix | Version: 17.0.1169.0 | Build: 20190508_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
>==> Running Revit Instances
>Error: Object reference not set to an instance of an object.
>Run with "--debug" option to see debug messages

**Additional context**
None that i can think of.

**Comment by jimgoodman9168** [comment]
I am having the same issue, except I can't get it to load in either Revit 2020 or 2021. This is my first installation. 

![image](https://user-images.githubusercontent.com/73618550/97519288-3f9bf780-1956-11eb-851c-c4035095062b.png)

**Comment by eirannejad** [comment]
@jimgoodman9168 Seems like the `master` clone is not registered. Try this:

`pyrevit clones add master <pyrevit installation path>`

This will register the clone installed at the given location. Then you can attach to Revits

**Comment by jimgoodman9168** [comment]
Thanks for the reply.

Is this the correct syntax for the command?
pyrevit clones add master C:\Users\James Goodman\AppData\Roaming\pyRevit-Master

**Comment by oddman80** [comment]
pyrevit was installed as admin, so the path where the master folder was located was in an admin user path. 

I attempted following command:
**_pyrevit clones add master C:\Users\Administrator.MININT-MK0FQPC\AppData\Roaming\pyRevit-Master_**

and it seems like nothing happens, it just gives me a new command line. So I then ran the **_pyrevit attach master 277 --installed_**  command and  _**pyrevit env**_  reported it was now attached to Revit 2021. So i closed the command prompt and opened Revit 2021 again, and got the same pop up error message. 

**Current pyRevit Environment:**

==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.2" | Path: "C:\Users\Administrator.MININT-MK0FQPC\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2020.1.1" | Engine: 277 | Path: "C:\Users\Administrator.MININT-MK0FQPC\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\Administrator.MININT-MK0FQPC\AppData\Roaming\Autodesk\Revit\Addins\2021\pyRevit.addin"
master | Product: "2020.2.2 (Full Install)" | Engine: 277 | Path: "C:\Users\Administrator.MININT-MK0FQPC\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\Administrator.MININT-MK0FQPC\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
master | Product: "2019.2.2 Hotfix" | Engine: 277 | Path: "C:\Users\Administrator.MININT-MK0FQPC\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\Administrator.MININT-MK0FQPC\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
master | Product: "2018.3.3 Security Fix" | Engine: 277 | Path: "C:\Users\Administrator.MININT-MK0FQPC\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\Administrator.MININT-MK0FQPC\AppData\Roaming\Autodesk\Revit\Addins\2018\pyRevit.addin"
master | Product: "2017.2.5 Security Fix" | Engine: 277 | Path: "C:\Users\Administrator.MININT-MK0FQPC\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\Administrator.MININT-MK0FQPC\AppData\Roaming\Autodesk\Revit\Addins\2017\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Administrator.MININT-MK0FQPC\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2020.1.1 | Version: 21.1.10.26 | Build: 20200909_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021"
2020.2.2 (Full Install) | Version: 20.2.11.3 | Build: 20200206_0915(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018"
2017.2.5 Security Fix | Version: 17.0.1169.0 | Build: 20190508_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> Running Revit Instances
PID: 76068 | 2020.1.1 | Version: 21.1.10.26 | Build: 20200909_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2021"
PID: 77684 | 2020.1.1 | Version: 21.1.10.26 | Build: 20200909_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2021"
PID: 74500 | 2020.1.1 | Version: 21.1.10.26 | Build: 20200909_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2021"
PID: 77240 | 2020.1.1 | Version: 21.1.10.26 | Build: 20200909_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2021"
PID: 29856 | 2020.2.2 (Full Install) | Version: 20.2.11.3 | Build: 20200206_0915(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2020"
==> User Environment
Microsoft Windows 10 [Version 10.0.18363]
Executing User: NHARBURG-LT2020\Administrator
Active User: ASG\nharburger
Admin Access: Yes
%APPDATA%: "C:\Users\Administrator.MININT-MK0FQPC\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.2.0

**Comment by jimgoodman9168** [comment]
After uninstalling both prRevit and IronPython, I installed V4.7.6 and it opened in Revit 2021 successfully. 
I did notice I dialogue when Iinstalling V4.7.6 asking that I install MS.net core runtime - 2.0.7 (x64). I didn't see that message when I installed V4.8.2 Beta.

**Comment by oddman80** [comment]
I am still having the original problem. I followed the above directions - but it is still giving me the huge error message when i open Revit 2021 (but not any other version of Revit).

**Comment by eirannejad** [comment]
Fixed and will be published with next release very soon
