### ISSUE TITLE
All scripts that include "&" in the name fail

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#104]
![image](https://cloud.githubusercontent.com/assets/9513968/16166569/58d05cda-34ba-11e6-8c82-5c081dca6847.png)

PS: the name is part of a standard naming scheme I have to adhere to.

**Comment by eirannejad** [comment]
Special characters can not be used in defining command names for Revit. Avoid using them please.

**Comment by gtalarico** [comment]
I have a python script that batch generates scripts for pyrevit, so the file name is coming from a predefined naming scheme. 
I guess will just have to add a step to replace the &.
Do you know if there any other symbols that are not allowed? (+ for example) Is it only alphanumerical, -, _ ?

thanks for clarifying this @eirannejad (and for your work on pyrevit, which is amazing btw!).

**Comment by eirannejad** [comment]
Absolutely. Thanks for using it.
The reason behind this is that I'm using the script names to generate the necessary class names for the Revit External Command class and that's why we can't use any special characters.

Send me a couple of the name examples that you have and let me see if I can edit the class generator to remove the special characters at runtime.

**Comment by gtalarico** [comment]
Makes sense.

Maybe instead or besides of replacing it, you could add a warning during
loading, so the user knows something went wrong. (character X not allowed)

I had thought all my 30 something buttons had loaded properly, and only
later i realized some were not working.

The only non alphanumerical characters are &  and "space"

I should be able to patch my code to fix it on my end.

Gui Talarico
[ mobile ]

**Comment by eirannejad** [comment]
Resolved. `__init__.py` now cleans up the file names before making the C# classname. Special chars will be removed for class name but will be kept for the button and command names.

specialcharacters = ' ~!@#$%^&*()+;:,\"{}[]-=<>?\/\\'
