### ISSUE TITLE
Option to hide the Reload button warning

### ISSUE THREAD

**Issue by sanzoghenzo** [eirannejad/pyRevit#1040]
**Is your feature request related to a problem? Please describe.**
This is just a minor annoyance.
During a develop session, it happens to me to use the reload button multiple times to spawn new buttons/controls in my ribbon.
Every time i click the reload button the warning message is displayed.

**Describe the solution you'd like**
A "Don't show this message again" checkbox in the message dialog to mute the message.

**Comment by davidvadkerti** [comment]
If you use default keyboard shortcut Ctrl+F for pyRevit Search and type reload you won't see the warning.
But you are right, it would be nice to have the checkbox :)
