### ISSUE TITLE
SearchPrompt captures a return key stroke from previous dialog

### ISSUE THREAD

**Issue by martinservold** [eirannejad/pyRevit#1044]
pyrevit Version 4.7.4

I have a script that has you make a selection (Electrical Equipment/Mechanical Equipment/etc) prior to starting the searchprompt for that category. On this prerequisite dialog if I select the option with the mouse the searchprompt works fine, but if I press Enter (return), the searchprompt captures that keystroke and immediately closes returning nothing. 

**To Reproduce**
```
prereq = forms.alert('Select Option', options=['Electrical','Mechanical'])
if prereq is None:
    script.exit()
if prereq == 'Electrical':
    eq = LIST1
elif prereq == 'Mechanical':
    eq = LIST2
searched_eq = forms.SearchPrompt.show(eq, switches=[], search_tip=tip_info)
if searched_eq is None:
    script.exit()
```

My suggestion is:
In Pyrevit>Forms>__init__.py>SearchPrompt>handle_kb_key
```
elif args.Key == Input.Key.Enter:
    if self.search_tb.Text != '':
        self._setup_response(response=self._search_res)
        self.Close()
```

**Comment by eirannejad** [comment]
Fixed and will be published with next release
