### ISSUE TITLE
Bug while installing new version (old unisnstalled)

### ISSUE THREAD

**Issue by cityinterface** [eirannejad/pyRevit#1045]
Hello,

I still experiencing an issue while installing Pyrevit last stable version **V4.7.6.**
By performing automatic exe install it says previous version can't be installed (please contact technical support). Are you ? ;)

Sooo well, as I was in rage, I tried **manually** install through GitKraken but some files don't come with downlaod "install.bat" file from repository... By the way I saw last version don't come anymore with install.bat ??

By the way, any idea of developping a **great Pyrevit uninstaller** erasing reg keys and old files to perform a fresh start?
That should help a lot.

Pyrevit is really amazing stuff guy and I'm so sad I can't use anymore.

Please light me up,

Best,

Antoine C.

![Pyrevit issue installing](https://user-images.githubusercontent.com/13923044/97691556-cbb93680-1a9e-11eb-8c20-91d13e6cdc44.jpg)
![PyRevit 4 4 install bat missing](https://user-images.githubusercontent.com/13923044/97691769-15a21c80-1a9f-11eb-953b-b9c1087753a0.jpg)
![PyRevit 4 7 6 install bat](https://user-images.githubusercontent.com/13923044/97691777-176be000-1a9f-11eb-8064-c7d1d973e258.jpg)

**Comment by eirannejad** [comment]
As you might have notices the installation video is a couple of years old and doesn't apply anymore.

Take a look at this post please and see if this fixes the uninstall issue: https://github.com/eirannejad/pyRevit/issues/491#issuecomment-456997657

**Comment by eirannejad** [comment]
I'm going to add something to the pyRevit CLI to cleanup these uninstall bugs in registry for the next version

**Comment by cityinterface** [comment]
Thanks a lot!
As you mentioned, I tried to search for "Pyrevit" entries that lasts in reg, looks clean. However bad luck, still stuck during install...
Waiting to hear from you with these cleaning lines.

Have a good day.

**Comment by eirannejad** [comment]
Hey @cityinterface . I have the first draft of the fixer ready for testing:

- [Download `pyrevit-doctor.exe` from here](https://github.com/eirannejad/pyRevit/blob/develop/bin/pyrevit-doctor.exe)
- Right-Click and select "Run as Administrator"
- In the opened console, type `1` (for the first doctor command listed) and hit Enter
- The tool will attempt to cleanup registry and remove the left over keys

Take a screenshot of the result window and share with me please

Let me know if this fixes the issue

**Comment by cityinterface** [comment]
Hello Ehsan,

It's kind of MAGICAL, your tool PyRevit Doctor finally deleted residual reg
entries and be able to install new version.
Great work, big thanks!
Antoine C.



Le mar. 10 nov. 2020 à 20:39, Ehsan Iran-Nejad <notifications@github.com> a
écrit :

**Comment by eirannejad** [comment]
Sweet! Thanks for testing. I'm gonna ship this tool with pyRevit from now on

**Comment by cityinterface** [comment]
Amazing, thanks!

Le mer. 11 nov. 2020 à 17:41, Ehsan Iran-Nejad <notifications@github.com> a
écrit :
