### ISSUE TITLE
Print sheet causes Revit 2018 to crash when clicked.

### ISSUE THREAD

**Issue by Web-CW** [eirannejad/pyRevit#1047]
Pyrevit addin used to work perfectly, however recently after a reinstallation of pyrevit, when I click the print sheet button, my entire revit 2018 session crashes. I have tried to reinstall both pyrevit and revit but had no luck with either.

The only work around I was able to find was by temporarily removing the addin from the folder where it is located and moving it back. This only works if I have the model fully loaded into revit, then I would remove the addin and re-add it again. After pyrevit loads back into revit, no crashing behaviour is observer. However, if I close revit and reopen again, my revit crashes as soon as I click the "print sheet" button. The only was is if I remove and re-add the plugin each time I use revit.

This is folder where I am in removing and re-adding the plugin: C:\Users\cwei\AppData\Roaming\Autodesk\Revit\Addins\2018

The workaround is not such a big problem, but I can only have 1 revit session open at a time for this to work. We often have many revit models open and the add and re-adding of the plugin only works for 1 revit session that is currently open.

Any advice or help would be greatly appreciated. Thanks in advance!

**Comment by eirannejad** [comment]
I have done a few bug fixes and changes to the print tool that will be published with v4.8.4 very soon. I'll let you know when it is out to test

**Comment by DuncanLithgow** [comment]
I can't recreate this in 4.8.3 ... I can't _find_ the drawings though ( issue #988 )

**Comment by eirannejad** [comment]
Tested and works in 4.8.6 with 2018
