### ISSUE TITLE
pyRevit 4.8.2 not loading in Revit 2021.1.1

### ISSUE THREAD

**Issue by felipervt** [eirannejad/pyRevit#1048]
Hi,

The installation of pyRevit completed with no errors, however pyRevit doesn't load in Revit 2021.1.1.

Error message:
![Capture1_1](https://user-images.githubusercontent.com/73870575/97953707-ff030a80-1da9-11eb-93f4-6a33a1f5a995.JPG)
![Capture1_2](https://user-images.githubusercontent.com/73870575/97953827-573a0c80-1daa-11eb-95a7-b68fba1fd374.JPG)
![Capture1_3](https://user-images.githubusercontent.com/73870575/97953884-80f33380-1daa-11eb-92a6-bc78dc2da610.JPG)

Desktop:
 - OS: Window 10 pro
 - pyRevit Version: 4.8.2

Additional context:
The issue arises after the latest hotfix for revit has been installed. (hotfix 2021.1.1)

**Comment by eirannejad** [comment]
Already fixed and will be published with v4.8.4
