### ISSUE TITLE
pyrevitloader does not handle multiple ironpython.dll

### ISSUE THREAD

**Issue by kollyboi** [eirannejad/pyRevit#1049]
pyRevit_4.8.2 for Revit 2021.1

There seems to be some trouble if more than one addin tries to cast ironpython.dll to runtime? Something like that?
I'm not skilled enough to pinpoint how to handle this.
![image](https://user-images.githubusercontent.com/44774905/97993693-b452b400-1de4-11eb-9d0b-27b587aaf3ec.png)

**Comment by kollyboi** [comment]
If there is a way to tell pyRevit which version of IPY-engine to assemble, that would probably solve it? pyRevit_config.ini does not contain that option as far as I can see.

**Comment by eirannejad** [comment]
You need to set the pyRevit's IronPython engine to match the engine loaded by other addons (seems like 2.7.9 in this case)
See here https://www.notion.so/pyrevitlabs/Configure-pyRevit-461d8f564ba743d0ad7e843a7b3b2afe#f9d423c1e6864ab2b64b8d60a685162a

**Comment by kollyboi** [comment]
I realise this, but is this possible without opening revit, pyrevit settings? Is the setting available in a file somewhere?

**Comment by eirannejad** [comment]
Yes. You can reattach pyRevit with a different engine version for example:
`pyrevit attach master 277 --installed` will attach using the 2.7.7 engine. [See the help here](https://www.notion.so/pyrevitlabs/Attach-pyRevit-to-Installed-Revits-abf190044ffc4ac29671152ec9b91335)

**Comment by kollyboi** [comment]
Perfect. Thank you!
