### ISSUE TITLE
purge unused family parameters need to check for all types especially visibility params

### ISSUE THREAD

**Issue by eirannejad** [eirannejad/pyRevit#105]

**Comment by eirannejad** [comment]
Fixed under 2.43.47

**Comment by CHBIV007** [comment]
Don't you ever take a break??? Lol

Sent from Charr Berteaux's Outlook Mobile<https://aka.ms/qtex0l>




On Sat, Jun 25, 2016 at 2:04 PM -0700, "Ehsan Iran-Nejad" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #105<https://github.com/eirannejad/pyRevit/issues/105>.

-

**Comment by eirannejad** [comment]
Haha hardly! 😜
