### ISSUE TITLE
Print - variable paper size doesn't set paper size

### ISSUE THREAD

**Issue by david939david** [eirannejad/pyRevit#1050]
**Describe the bug**
I've read how to print and there is:

"## Per-Page Print Settings / Variable Paper Size

The print tool, under **Print Settings** option, allows you to define a custom print setting for each sheet by choosing `<Variable Paper Size>`. Once this option is selected, the print tool reviews the sheets and tries to determine the best print option for that sheet based on its titleblock size."

**Expected behavior**
So as I understand that, when I choose Variable Paper Size it should set best print size to all of the sheets, right? - if so, nothing happen when I do that.

**Screenshots**
![image](https://user-images.githubusercontent.com/23181474/98092415-efa5bf00-1e86-11eb-9703-47e4c6b5af13.png)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - pyRevit Version: 4.7.6
 - pyRevit Environment: I haven't install Python yet.
- Revit 2020.2

Now I'm searching in Print script where there's a command about matching paper size to figure it out.

**Comment by eirannejad** [comment]
This is already fixed and will be published with 4.8.4 very soon

**Comment by david939david** [comment]
Great info!
