### ISSUE TITLE
[Question] How does pyRevit determine REFEDASSMS?

### ISSUE THREAD

**Issue by htlcnn** [eirannejad/pyRevit#1051]
Hi @eirannejad
May I ask how pyRevit sets the environment variable `PYREVIT_REFEDASSMS`? If I use IronPython 2.7.3 core, it load `IronPython*.dll` from `GAC_MSIL` instead of pyRevit engines if I use other cores. I think this might be related to IronPython Compile test button, which succeeded with 2.7.3 core but failed for other cores.
Thanks.

**Comment by eirannejad** [comment]
If it loads the DLLs from GAC_MSIL, it is because they have been installed there by another application (most probably Dynamo). I usually suggest removing all the independent IronPython installations

[This is where pyRevit sets the generated assemblies on this env var](https://github.com/eirannejad/pyRevit/blob/4319ff011c36f24b26b2394d6862e685e566f26b/pyrevitlib/pyrevit/loader/sessionmgr.py#L185)

**Comment by eirannejad** [comment]
Closing this since it is a question but keep the conversation going. I still see the messages

**Comment by htlcnn** [comment]
@eirannejad 
I'm confused and don't know how IronPython works to load compiled dll files. All began with using [Test IronPython Compile command](https://github.com/eirannejad/pyRevit/blob/4afd56ccb4d77e4e0228b8e64d80d1f541bc791e/extensions/pyRevitDevTools.extension/pyRevitDev.tab/Debug.panel/Engine%20Tests.pulldown/Test%20IronPython%20Compile.pushbutton/script.py).

pyRevit's behaviours were not stable. With 2.7.9 core on any Revit version, pyRevit could not use compiled dll files. Sometimes it succeeded with 2.7.3 & Revit 2018 only.

On one of my PC it succeeded with both Revit 2020 & Revit 2018, all running 2.7.3 core. On the other PC, most of the time Revit 2020 failed to load 2.7.3 with exception `No module named _wpf`.

That led me to the issue https://github.com/eirannejad/pyRevit/issues/1053. I just wanted to find a stable way to run pyRevit for all Revit versions and be able to use compiled dll files.

Thanks for your time!

**Comment by eirannejad** [comment]
Okay let me take a look at this tomorrow. Do you use any WPF stuff in your compiled scripts?

**Comment by htlcnn** [comment]
No, I used your `ipycompiletest.py` to test.
