### ISSUE TITLE
pyRevit run // load external Addin

### ISSUE THREAD

**Issue by timbart3ls** [eirannejad/pyRevit#1052]
Hi,

I set up a script to automatically export my models to IFC and it works well. Now I also want to export to NWC but it seems like the NWC Export plugin doesent get loaded when Revit is launched by the pyRevit run command. ( `IsNavisworksExporterAvailable()` Method returns False)

Is there any way to load Addins when launching Revit from the command line?

Cheers 
Tim

**Comment by eirannejad** [comment]
pyRevit run command has an option to specify the extra addins directory to be loaded. See `pyrevit run --help` for `--import=<import_path>` option

**Comment by baaswietse** [comment]
> Hi,
> 
> I set up a script to automatically export my models to IFC and it works well. Now I also want to export to NWC but it seems like the NWC Export plugin doesent get loaded when Revit is launched by the pyRevit run command. ( `IsNavisworksExporterAvailable()` Method returns False)
> 
> Is there any way to load Addins when launching Revit from the command line?
> 
> Cheers Tim

Hello sir, do you mind giving some insight into how you managed to create a IFC exporter using Pyrevit? I've been searching all internet for this and don't seem to find any answers. Particularly for exporting certain 3D views with given export options.
