### ISSUE TITLE
Pandas Import Error

### ISSUE THREAD

**Issue by tatarczakowna** [eirannejad/pyRevit#1056]
It seems I cannot import pandas properly on pyRevit version 4.7.6 with CPython 3.7.2.  Any pandas method I'm trying to use is causing the same error: module 'pandas' has no attribute...

Here's the code I'm using:

#! python3
import sys
sys.path.append("C:\\Users\\name.surname\\Miniconda3\\Lib\\site-packages")
import pandas as pd
pd.core.config

![Capture](https://user-images.githubusercontent.com/74110465/98452448-bfdd0c80-214f-11eb-9369-d5739cd9b08e.PNG)

**Comment by eirannejad** [comment]
Which version of python3 have you installed with miniconda?

**Comment by tatarczakowna** [comment]
3.8.5

**Comment by tatarczakowna** [comment]
I've reinstalled Pandas and it worked
