### ISSUE TITLE
Telemetry server fails with sqlite3 database

### ISSUE THREAD

**Issue by fabioloretti** [eirannejad/pyRevit#1059]
**Describe the bug**
I've created an sqlite3 database file from scratch and created a table inside it called "scripts" (please refer to screenshot below). The table has only one column of data at this point as I'm not sure how pyRevit pushes the data into it.

![Sqlite3_usage db](https://user-images.githubusercontent.com/72789603/98637683-d916d080-237c-11eb-82d3-42f51285ff3f.png)

Then I started the telemetry server in powershell and setup pyRevit telemetry with my local IP address, which seemed to connect to Revit ok however, when I run one of our scripts I get the below error "no such table: scripts" and nothing gets recorded. (screenshots below)

![RevitTelemetrySettings](https://user-images.githubusercontent.com/72789603/98637824-19764e80-237d-11eb-9c5f-2909b38b0c4b.png)

![Error_NoSuchTable](https://user-images.githubusercontent.com/72789603/98637837-1e3b0280-237d-11eb-898a-141537e758a0.png)

I've already done lots of research to see if I can find a solution without success. Any suggestions are very welcome. Thank you.

**Desktop (please complete the following information):**
 - OS: Windows 10

**PS C:\Users\nflab> pyrevit env**
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.6" | Path: "C:\Users\nflab\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2019.2.1" | Engine: 277 | Path: "C:\Users\nflab\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\nflab\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
master | Product: "2017.2.5 Security Fix" | Engine: 277 | Path: "C:\Users\nflab\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\nflab\AppData\Roaming\Autodesk\Revit\Addins\2017\pyRevit.addin"
==> Installed Extensions
Woolworths | Type: Unknown | Repo: "" | Installed: "\\ncdwnsdasp0001\BIM\01_BIM Content\Library Development\PYTHON\Woolworths Toolbar\Extensions\Woolworths.extension"
==> Default Extension Search Path
C:\Users\nflab\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
\\ncdwnsdasp0001\BIM\01_BIM Content\Library Development\PYTHON\Woolworths Toolbar\Extensions
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2019.2.1 | Version: 19.2.10.7 | Build: 20190225_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
2017.2.5 Security Fix | Version: 17.0.1169.0 | Build: 20190508_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.18363]
Executing User: NSWRO\nflab
Active User: NSWRO\nflab
Admin Access: No
%APPDATA%: "C:\Users\nflab\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.25.0.0

**Comment by eirannejad** [comment]
Read this please
https://www.notion.so/pyrevitlabs/Telemetry-System-992d72659457447f86b79cf1c9034541#581ac80934854a6c8f610641283bb80e

**Comment by eirannejad** [comment]
You also need to specify the port to the server. See the example below the telemetry url in pyRevit settings. If the telemetry system in pyRevit can connect to the server, the dark-blue bar below the url box will turn into yellow

**Comment by eirannejad** [comment]
I'm closing this since it is a question, but please continue the conversation

**Comment by fabioloretti** [comment]
Thanks for responding, Ehsan. Yeah, no worries, that's fine.

I ended up covering my IP address and the port too (my bad!) but below is an up to date screenshot showing what happens when I click on the dark blue bar as a test. I get the "no such function: version" error and my telemetry server stops.

![RevitTelemetrySettings_2](https://user-images.githubusercontent.com/72789603/98802809-f2487b80-2467-11eb-91f2-86f952696334.png)

I went through the documentation in the link you shared but I'm not making the connection, sorry. I don't know much about DDL but after some research it looks like a DDL script is for the tables to be created but if I setup the table first do I still need a DDL script?

Thanks again. I appreciate you taking the time to respond.

**Comment by eirannejad** [comment]
Oh that's bad. Okay great let me test it. I haven't tested it with a sqlite database in a while

**Comment by fabioloretti** [comment]
Not a problem. Let me know if you need any more information to be able to reproduce it.

**Comment by GertjanVDBVK** [comment]
Just something I picked up when testing the telemetry server. Hope this helps point us in the right direction.
I was trying to connect to a non-existant sqlite3 database and also got that same error.
