### ISSUE TITLE
Icon Size Issue

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#106]
I have multiple icons (all 32x32), .png files.
All but one of the icons are displayed at the wrong scale as a button
(looks fine when used for drop-down icon)

Sample icons below.

I took the original one (blue) from https://icons8.com/ (shows correctly)
and the others I just adjusted the color in photoshop and re-saved same size.

![image](https://cloud.githubusercontent.com/assets/9513968/16279579/942637aa-3889-11e6-8f75-7186ef2b6ecd.png)

![0000_wwrooms_pulldownbutton_work](https://cloud.githubusercontent.com/assets/9513968/16279559/7b834260-3889-11e6-9bec-dc09022aadd7.png)
![0001_wwrooms_pulldownbutton_serve](https://cloud.githubusercontent.com/assets/9513968/16279560/7b857238-3889-11e6-84a3-6acc2ed69030.png)

**Comment by eirannejad** [comment]
This is not a Revit issue. It's a PNG file format issue as far as I have tested. Usually if you open the icon and save it with windows paint, it'll show correctly.

**Comment by gtalarico** [comment]
@eirannejad  
Found a fix for icon size issue. In Photoshop, just use Save For Web, Legacy PNG-8 and it works as expected.

![image](https://cloud.githubusercontent.com/assets/9513968/16527102/d2230646-3f82-11e6-9028-b3e499f00060.png)

**Comment by eirannejad** [comment]
Well done!! I'll add this to the readme file.
