### ISSUE TITLE
Add folder window disappears in Custom Extension Directories 

### ISSUE THREAD

**Issue by yzhang10** [eirannejad/pyRevit#1061]
**Describe the bug**
Open pyRevit Setting -> Go to Custom Extension Directories -> Click on Add folder -> Select Folder window opens. If now you click anywhere outside this Select Folder window, this Select Folder window will disappear. Yet, you can still close pyRevit Setting window. This Select Folder window will appear if you minimize current opening applications one by one on your desktop. When it appears, you can close this Select Folder window.

**To Reproduce**
1. Go to pyRevit Setting
2. Click on Custom Extension Directories
3. Click on Add folder button
4. Now Select Folder window will come up.

**Expected behavior**
After click on Add folder button under Custom Extension Direction in pyRevit Setting, this Select Folder window should stay on top until a folder is selected, and the Select Folder button is clicked.

**Screenshots**
 
![image](https://user-images.githubusercontent.com/42006065/98982872-09ca4780-24ee-11eb-80a0-6a4854ef4806.png)

![image](https://user-images.githubusercontent.com/42006065/98982935-18b0fa00-24ee-11eb-8119-ab77fd542321.png)

 
**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 2020
 - pyRevit Version pyRevit v4.8.2

**Additional context**

**Comment by eirannejad** [comment]
Fixed and will be published with next release
