### ISSUE TITLE
PyRevit Highlight and Wipe Element Constraints in a Revit view

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#1062]
**Is your feature request related to a problem? Please describe.**
It would be great if you could highlight all the Revit Elements in a Revit view that is constrained and then have an option to select which ones to unconstrain.

**Describe the solution you'd like**
Click a PyRevit button that highlights all the constraint Revit elements in a Revit view or maybe this could be incorporated into the PyRevit Pick tool i.e. Select constraint Revit elements.

**Additional context**
PyApex has a great Disable Contraint tools which unconstrains all the Revit elements in a model which would be great if this useful tool could be incorporated into PyRevit suite of tools.

![image](https://user-images.githubusercontent.com/8776947/99093520-7c105a00-25ca-11eb-9f51-642068348c8e.png)

**Comment by eirannejad** [comment]
@melnikovalex Someone loves your "Disable Constraints" tool :D

**Comment by Robbo1234** [comment]
Could we open this issue? Thanks
