### ISSUE TITLE
pyRevit error on startup

### ISSUE THREAD

**Issue by KovalevDenis** [eirannejad/pyRevit#1064]
Can't load pyRevit anymore
![image](https://user-images.githubusercontent.com/53397095/99147161-b0018300-268f-11eb-96e1-6a6b2f34bf4c.png)

**Comment by eirannejad** [comment]
Open a command line and run `pyrevit caches clean --all`

Run Revit again and see if you still see the failure

**Comment by KovalevDenis** [comment]
It didn't help. I have the same error.
![image](https://user-images.githubusercontent.com/53397095/103167985-d2ff8500-4840-11eb-9827-85b19d0a183a.png)

**Comment by eirannejad** [comment]
v4.8.5 is published. Would you mind testing this? If it didn't work try attaching pyRevit using the custom IronPython engine `pyrevit attach master default --installed`
