### ISSUE TITLE
Edit Keynote Key

### ISSUE THREAD

**Issue by alexdaversa** [eirannejad/pyRevit#1066]
Add button in Keynote Manager to change a keynote key or keys. I imagine it would involve saving a list of type IDs for elements with that keynote already assigned and user keynotes to be updated when the keynote dialogue is closed (or when the change key window is closed?) Not sure how to deal with changing keynote A to B, then B to C since once changed from A to B and before hitting update, the keynote file and model are no longer in sync.

**Comment by eirannejad** [comment]
Related to https://github.com/eirannejad/pyRevit/issues/701

**Comment by alexdaversa** [comment]
Sorry didn't catch that it was already in the #701 thread!
