### ISSUE TITLE
I've tryed many ways, but still unable to load pyRevit...

### ISSUE THREAD

**Issue by jfrgagnon** [eirannejad/pyRevit#1068]
![printscreen](https://user-images.githubusercontent.com/74669377/99558933-3e2c8080-2992-11eb-9afd-abf74f216c16.jpg)

**Comment by eirannejad** [comment]
Open a command line and run `pyrevit attach master 273 --installed` and let's see if this is an IronPython conflict with other addons

**Comment by jfrgagnon** [comment]
Nop...
Still doesn't work... :(
![image](https://user-images.githubusercontent.com/74669377/99695118-308efd80-2a5b-11eb-9f28-157e603c1f3c.png)

**Comment by jfrgagnon** [comment]
pyrevit env : 
==> Installed Extensions
pyRevitCore | Type: Unknown | Repo: "" | Installed: "C:\Users\B-LIV Architecture\AppData\Roaming\pyRevit-master\Extensions\pyRevitCore.extension"
pyRevitRun | Type: RunnerExtension | Repo: "" | Installed: "C:\Users\B-LIV Architecture\AppData\Roaming\pyRevit-master\Extensions\pyRevitRun.run"
pyRevitTags | Type: UIExtension | Repo: "" | Installed: "C:\Users\B-LIV Architecture\AppData\Roaming\pyRevit-master\Extensions\pyRevitTags.extension"
pyRevitTools | Type: UIExtension | Repo: "" | Installed: "C:\Users\B-LIV Architecture\AppData\Roaming\pyRevit-master\Extensions\pyRevitTools.extension"
pyRevitTutor | Type: UIExtension | Repo: "" | Installed: "C:\Users\B-LIV Architecture\AppData\Roaming\pyRevit-master\Extensions\pyRevitTutor.extension"
==> Default Extension Search Path
C:\Users\B-LIV Architecture\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\Program Files\pyRevit
C:\Users\B-LIV Architecture\AppData\Roaming\pyRevit-master\Extensions

**Comment by jfrgagnon** [comment]
==> User Environment
Microsoft Windows 10 [Version 10.0.19042]
Executing User: DESKTOP-FGT6NCP\B-LIV Architecture
Active User: DESKTOP-FGT6NCP\B-LIV Architecture
Admin Access: Yes
%APPDATA%: "C:\Users\B-LIV Architecture\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v3.0 v3.5
Installed .Net-Core Target Packs: v2.1.811 v3.1.404 v5.0.100
pyRevit CLI 4.8.3.0

**Comment by eirannejad** [comment]
Everything seems to be very normal. Usually these import issues are related to dll conflicts with other IronPython versions. What if you attach with the `2.7.7` or higher engines?

**Comment by eirannejad** [comment]
v4.8.5 is published. Would you mind testing this? If it didn't work try attaching pyRevit using the custom IronPython engine `pyrevit attach master default --installed`
