### ISSUE TITLE
Tracking Elements Edited by User

### ISSUE THREAD

**Issue by ThubanPDX** [eirannejad/pyRevit#107]
2 Scripts, 1 gives a list of all elements that were last edited by the user. 

The other, gives a list of all elements currently owned by the user.

With view/sheet name included on the elements if possible for both.

**Comment by eirannejad** [comment]
added:
WorkSharing_listSheetsWithElementsOwnedByMe.py
WorkSharing_selectLastEditedByMeInCurrentView.py
WorkSharing_selectOwnedByMeInCurrentView.py
