### ISSUE TITLE
deploy Pyrevit for teams in a multisession VDI environment

### ISSUE THREAD

**Issue by jessiepurcey** [eirannejad/pyRevit#1072]
We're having trouble deploying Pyrevit (using the teams method via cli) on multisession virtual desktops. Is it possible to install for one user while another user is logged into the machine and currently using Revit?

**Comment by eirannejad** [comment]
@jessiepurcey As you know pyRevit CLI stores the environment configuration in `%APPDATA%/pyRevit`. But [there is a method to seed this configuration](https://www.notion.so/pyrevitlabs/Configure-pyRevit-07446b4e07b7429091c89f472ef39136#cc1635325110443e9aa402586092e146) to the `%PROGRAMDATA%/pyRevit`. When other users start Revit, pyRevit automatically inits their configs from this master file. You can also `--lock` the seed file and other users can not make changes to it

**Comment by eirannejad** [comment]
closing this since it is a question but please keep the conversation going
