### ISSUE TITLE
Create Revised Sheet Set from Revision_Error

### ISSUE THREAD

**Issue by sam-romero** [eirannejad/pyRevit#1073]
I'm trying to run the Create Revised Sheet Set from Revision, and recently get the following. 

ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:In session views setting failed.
![image](https://user-images.githubusercontent.com/74996217/100167895-20798280-2e8e-11eb-9f01-13ca21a64eed.png)

I found a workaround for what I needed, but wanted to bring attention to it.

Thanks,

**Comment by eirannejad** [comment]
Great. Seems like a conflict with the active printer and print settings. I'll look into it.

**Comment by eirannejad** [comment]
Hmm. I can't get to replicate this error. Closing it for now as pyRevit seems to be working correctly. Feel free to open it back up if you have more info. This is most probably related to other settings in Revit print. I tested with `in-session` and multiple settings and printers with no errors.
