### ISSUE TITLE
Installation still not working after serveral trys

### ISSUE THREAD

**Issue by NmCAD** [eirannejad/pyRevit#1075]
Hello Everyone!
First of all thanks for pyRevit i love it!
I want to start Python programming myself and I really need the installation.
I also tried to install from a full git repsoritory... look:

```
_PS C:\Users\Jose De Jesus> pyrevit clones
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)_
```

But sorry I gave it up.

1. For the installation i used the .exe pyRevit_4.8.4_signed. This went well.
2. I installed the .exe pyRevit.CLI_4.8.4_signed too.
3. I use an MSI Laptop, 64 bit and my Windows 10 Home is in German. Also Revit is installed in German.
4. I use Revit 2020 and 2019.
5. I run the command

**pyrevit attach master 277 --installed**

and this happens:

```
_PS C:\Users\Jose De Jesus> pyrevit attach master 277 --installed
Error: Can not find clone "master"
Run with "--debug" option to see debug messages_ 
```

I can do this from cmd or powershell...i get the same results:

```
_C:\Users\Jose De Jesus>pyrevit attach master 277 --installed
Error: Can not find clone "master"
Run with "--debug" option to see debug messages_
```

6. I created my own .addin file on %ProgramData% and pyRevit was avaliable on the UI of my both Revits.
I was a little bit unsure because of the GUID of the addin File. I was able to use pyRevit and also i have installed pyRevit MEP.
But Revit ended crushing, depending on the tools that i used. I was very unsure using my own addinfiles. So i ended uf deleting them, and deinstalling the software. On the Log Time Load Report were 5 red messages pointing to None.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - pyRevit Version pyRevit_4.8.4
 - pyRevit Environment: 

```
PS C:\Users\Jose De Jesus> pyrevit attach master 277 --installed
Error: Can not find clone "master"
Run with "--debug" option to see debug messages 

PS C:\Users\Jose De Jesus> pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Jose De Jesus\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2020.2.3 | Version: 20.2.30.42 | Build: 20200826_1250(x64) | Language: 1033 | Path: "C:\Program
 Files\Autodesk\Revit 2020\"
2019 Update for Trial Build | Version: 19.0.1.1 | Build: 20180328_1600(x64) | Language: 1033 | 
Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19041]
Executing User: MSI\Jose De Jesus
Active User: MSI\Jose De Jesus
Admin Access: No
%APPDATA%: "C:\Users\Jose De Jesus\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.4.0
```

I would be very happy if i can run pyRevit. I thank you very much for the support.
Regards
Jose

**Comment by eirannejad** [comment]
Hello @NmCAD
`pyrevit clones` lists the installed pyRevit clones. For some reason the installer fails to register the `master` clone. The clone is installed by default under `%APPDATA%/pyRevit-Master`. You'd need to register this clone first:

``` shell
pyrevit clones add master "C:\Users\Jose De Jesus\AppData\Roaming\pyRevit-Master"
```

After the clone is registered, then you can

```shell
pyrevit attach master 277 --installed
```

**Comment by NmCAD** [comment]
Hello Eirannejad...Thanks for the Help it worked...Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Ehsan Iran-Nejad <notifications@github.com> Datum: 27.11.20  19:43  (GMT+01:00) An: eirannejad/pyRevit <pyRevit@noreply.github.com> Cc: NmCAD <jdj@jdj.ch>, Mention <mention@noreply.github.com> Betreff: Re: [eirannejad/pyRevit] Installation still not working after
  serveral trys (#1075) 
Hello @NmCAD
pyrevit clones lists the installed pyRevit clones. For some reason the installer fails to register the master clone. The clone is installed by default under %APPDATA%/pyRevit-Master. You'd need to register this clone first:
pyrevit clones add master "C:\Users\Jose De Jesus\AppData\Roaming\pyRevit-Master"
After the clone is registered, then you can
pyrevit attach master 277 --installed

**Comment by wangtie** [comment]
hello @eirannejad   
when i input this command: pyrevit clones add master "C:\Users\i3yoo\AppData\Roaming\pyRevit-Master"
I have the issue. Is there any solution?

C:\Users\i3yoo>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.8" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
master | Product: "2018 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\i3yoo\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2018 First Customer Ship | Version: 18.0.0.420 | Build: 20170223_1515(x64) | Language: 1033 | Path: "d:\Program Files\Autodesk\Revit 2018\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19042]
Executing User: DESKTOP-N8QO3RH\i3yoo
Active User: DESKTOP-N8QO3RH\i3yoo
Admin Access: Yes
%APPDATA%: "C:\Users\i3yoo\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.7.2 v4.X
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.8.0

C:\Users\i3yoo>pyrevit clones add master "C:\Users\i3yoo\AppData\Roaming\pyRevit-Master"
Error: 未能找到路径“C:\Users\i3yoo\AppData\Roaming\pyRevit-Master”的一部分。
Run with "--debug" option to see debug messages

**Comment by wangtie** [comment]
@eirannejad   and when i open revit ,then report error
![image](https://user-images.githubusercontent.com/2143623/122529191-c7528580-d04f-11eb-8e78-b816833d043a.png)

**Comment by WisdomBalance** [comment]
> @eirannejad and when i open revit ,then report error
> ![image](https://user-images.githubusercontent.com/2143623/122529191-c7528580-d04f-11eb-8e78-b816833d043a.png)

我也是这样，请问您解决了吗

**Comment by ExCanMan** [comment]
I had different errors and this line into CMD helped me out, now it works perfectly 
`pyrevit attach master 2711 --installed --allusers`

**Comment by clay-m-smith** [comment]
I am getting a similar bug after trying all of the fixes. See attached
![image_2022-08-16_202249841](https://user-images.githubusercontent.com/111399177/185013917-4efc1bcc-4cd1-4597-bc27-e97a6d0992dd.png)

**Comment by bizfamo** [comment]
Hello! I am trying to install the Tesla Toolbar version of pyRevit on my machine and I cannot seem to get it to work. Any chance I could get some help with this? The installation instructions I have tell me to copy the pyRevit files into my AppData folder, copy the addin file with my replaced username, and then I get the error the error below:
![image](https://user-images.githubusercontent.com/114432351/192344378-f53a9272-df4f-4a58-8f32-79703b12b33e.png)
 
 Any help is greatly appreciated!

**Comment by dago50** [comment]
please see attached 

![Screenshot 2022-11-04 111500](https://user-images.githubusercontent.com/117465165/200010299-897b3be4-bf2e-4c48-8099-e7810be4bdfe.jpg)

**Comment by Tonny013** [comment]
Py revit with 2022 does not load?
