### ISSUE TITLE
Installation Issue 

### ISSUE THREAD

**Issue by wlburks** [eirannejad/pyRevit#1078]
Love this tool! I use it every day at work it is a huge timesaver.  I'm at home now because Covid and was attempting to install the latest version on my home computer but I am having issues getting the tool to install at home.  After I finish installing I launch Revit 2020.2 expecting to see the pop-up to always load the plugin.  However, it doesn't show up, and as such the tool doesn't show up in the tab.

So I try the fix recommended on the website of running:

pyrevit attach master 277 --installed

However, when I run that command I get the following error:
Error: Can not find clone "master"
Run with "--debug" option to see debug messages

Below is what the command line returns:

C:\Users\William Burks>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
==> Installed Extensions
==> Default Extension Search Path
C:\Users\William Burks\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2020.2.3 | Version: 20.2.30.42 | Build: 20200826_1250(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.18363]
Executing User: THOR\William Burks
Active User: THOR\William Burks
Admin Access: No
%APPDATA%: "C:\Users\William Burks\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.4.0

C:\Users\William Burks>pyrevit attach master 277 --installed
Error: Can not find clone "master"
Run with "--debug" option to see debug messages

 - OS: Windows 10 
 - pyRevit Version 4.8.4

Love this tool can't thank you enough for your generosity.  I'm sure I'm missing something obvious here.

**Comment by wlburks** [comment]
![pyrevit](https://user-images.githubusercontent.com/75380089/100893844-ce39f200-3489-11eb-9cfc-864c1d61c2d5.PNG)

**Comment by eirannejad** [comment]
Thank you @wlburks and sorry for the trouble. [See this comment please](https://github.com/eirannejad/pyRevit/issues/1075#issuecomment-734950066)

**Comment by wlburks** [comment]
That did it thanks so much for your response!
