### ISSUE TITLE
.urlbutton not working

### ISSUE THREAD

**Issue by bmoreawesom3** [eirannejad/pyRevit#1081]
When using the .urlbutton folder I get an error when starting revit and pyrevit loads. Error is "does not specify target url." Based on the example under the devtools the .url button only has a bundle.yaml and icon file. I have mimiced the test panel color.panel

I am not getting any error in VSC in any of the creations of the yaml files.

**Expected behavior**
.urlbutton when pressed to open link to website.

**Screenshots**

[image](https://user-images.githubusercontent.com/75343901/101033552-364f0d80-3548-11eb-908e-08bc5d3ed689.png)

**Desktop (please complete the following information):**
 - OS: W10
 - pyRevit Version 4.7.4:277:2020.2

**Comment by eirannejad** [comment]
Would you mind showing me the contents of the url button bundle.yaml file?

**Comment by bmoreawesom3** [comment]
Certainly.

tooltip: Opens Google
hyperlink: "https://www.google.com"
context: zero-doc

**Comment by eirannejad** [comment]
Hmmm 🤔 And this is placed in a file named `bundle.yaml`? Very odd

**Comment by bmoreawesom3** [comment]
Yes. This is in a file called bundle.yaml that is in a folder called
test.urlbutton. the error I am getting is that it can not find the target.
I made this an issue on the github with a screen shot. Is it possible to
create code using a .pushbutton py script.

**Comment by eirannejad** [comment]
Baffles me. Ok let me test this. I might have messed up something in there

**Comment by bmoreawesom3** [comment]
I think this error was on my side. A simple restart of the computer fixed this issue. My apologies.

**Comment by Pestano** [comment]
Hi there, I have the same situation. I´m trying to fix it for more than four hours with no result. I even copy the PyRevit original Bundle from the icon8 link , restarted my computer several times, I also test it in Revit 2021 and Revit 2023, same result every time: "Can not find the target file. Maybe deleted?"
This is the file structure:
D:\15_REVIT\Revit_MyTools\VPTools.extension\VPTools.tab\Link.Panel\Tool.urlbutton
This is the two files I have in the .urlbutton
![capture1](https://github.com/eirannejad/pyRevit/assets/52104811/e55cd7aa-1536-48eb-8a7e-fa9df65b34cf)
What I have in the .yaml file is copied directly from PyRevit as I said. 

And this is the file structure with the bundle for divide the two icons:
![image](https://github.com/eirannejad/pyRevit/assets/52104811/89194cd9-fba3-4178-9c87-3269ebdb3566)

Any idea where the mistake is ?

Thanks.
