### ISSUE TITLE
Empty Print List

### ISSUE THREAD

**Issue by andygiang** [eirannejad/pyRevit#1083]
**Describe the bug**
Testing the Print Sheets Tool. Sheet List is empty.

**To Reproduce**
1. Create Sheets
2. Create Sheet List in schedules
3. Click Print Sheets

**Expected behavior**
I expect a sheet list to populate. 

**Screenshots**
![image](https://user-images.githubusercontent.com/19696126/101099709-10daf780-357a-11eb-8888-ef5a6186c39e.png)

**Desktop (please complete the following information):**
 - pyRevit Version 4.7.6
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.
Microsoft Windows [Version 10.0.19041.630]
(c) 2020 Microsoft Corporation. All rights reserved.

U:\>'pyrevit env'
''pyrevit' is not recognized as an internal or external command,
operable program or batch file.

U:\>"pyrevit env"
'"pyrevit env"' is not recognized as an internal or external command,
operable program or batch file.

U:\>
**Additional context**

**Comment by eirannejad** [comment]
This issue has already been fixed in newer pyRevit versions. [The latest stable beta is here](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.4)
