### ISSUE TITLE
Pyrevit ; Autodesk Revit 2021 | Version: 21.1.11.27

### ISSUE THREAD

**Issue by shafiq2wo** [eirannejad/pyRevit#1084]
Hi, new user here,

I have successfully installed but unable to run Pyrevit version 4.8.4 for Revit 2021 version: 21.1.11.27.
![Capture](https://user-images.githubusercontent.com/75459298/101110739-9ad79e80-3614-11eb-9b18-ba464abab346.PNG)

Any help would be much appreciated.
Thank You,

Regards
Shafiq

**Comment by eirannejad** [comment]
Hmm okay. Take a look at this: https://github.com/eirannejad/pyRevit/issues/1075#issuecomment-734950066

**Comment by eirannejad** [comment]
Did use this installer? Make sure it is not the CLI installer

https://github.com/eirannejad/pyRevit/releases/tag/v4.8.4

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists
