### ISSUE TITLE
I think I installed it but it doesn't show up on Revit 2020 or 2021

### ISSUE THREAD

**Issue by hanksteinhardt** [eirannejad/pyRevit#1085]
**Describe the bug**
Hi Ehsan,
I downloaded the 4.8.4 signed exe like you showed tonight and went through the installer process but it doesn't like the attachment happened. Here is the power shell screen grab, it doesn't look like the one you showed on the TheRevitKid.

![image](https://user-images.githubusercontent.com/75463754/101120292-19dfbf00-35a2-11eb-87bd-bb78c52b963a.png)

Any suggestions would be appreciated. I read the stuff below but I don't understand it. I'm a residential designer not a computer coder type. How you do this, I cannot imagine. Looks like a great tool and I hope to use it.
Thanks, Hank

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - pyRevit Version [e.g. 22]
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

**Additional context**

**Comment by eirannejad** [comment]
Hey sorry for the trouble. See this comment please and hopefully this will fix the issue. https://github.com/eirannejad/pyRevit/issues/1075#issuecomment-734950066

**Comment by hanksteinhardt** [comment]
Thanks, it was worth a try, but I have no idea what that #1075 comment was referring to.

**Comment by Hangman-of-the-galos** [comment]
Not wanting to hi-jack this thread but I am having the exact same issue with pyRevit.CLI_4.8.4_signed.exe install.
@eirannejad , In the posted #1075 (comment) , you mention the master clone 

> is installed by default under %APPDATA%/pyRevit-Master.

By turning on the "Hidden files & folders" in the Windows directory, I can traverse to the 'AppData/Roaming' folder & all I see there is a "pyRevit" folder.  Doing a search across my machine, I cannot find any "pyRevit-Master" anything. 

On another note, correct me if I'm mistaken please but again, when referring to the #1075 , the quoted lines; 

> pyrevit clones add master "C:\Users\<enter username here>\AppData\Roaming\pyRevit-Master"

&

> pyrevit attach master 277 --installed 

Are to be typed into the Command Prompt ?

**Comment by eirannejad** [comment]
Do you know where did you install pyRevit? Would you mind searching for `pyrevit.exe` and see where you installed?

**Comment by Hangman-of-the-galos** [comment]
> 
> 
> Oh you need the `pyRevit_4.8.4_signed.exe` NOT the CLI installer
> 
> Download from here https://github.com/eirannejad/pyRevit/releases/tag/v4.8.4

That did it for me.  I don't know how I ended up on the CLI download page but uninstalling the CLI, rebooting, & then installing the 'pyRevit_4.8.4_signed.exe' did the trick.   I now have a 'pyRevit-Master' folder in the 'AppData/Roaming' directory.  The pyRevit Tab is showing up in all of the Revit versions installed.  Excellent, Thank you for the proper link. 

Now we just need to get Hank updated.  I feel I really hi-jacked his thread now so I need to make amends.

**Comment by eirannejad** [comment]
No worries. I think @hanksteinhardt has a similar issue

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists
