### ISSUE TITLE
pyRevit Error: name _author_ is not defined

### ISSUE THREAD

**Issue by thrbjrn** [eirannejad/pyRevit#1087]
Hi,

We are not able to run PyRevit on a virtualized environment. The VMs are running on ESXi with Win10.
PyRevit 4.8.2 is installed.

Please review attachment.

Any fix or workaround for this issue?

**Comment by thrbjrn** [comment]
![pyreviterror](https://user-images.githubusercontent.com/38289714/101349075-07f56900-388d-11eb-8639-22123d487139.PNG)

**Comment by eirannejad** [comment]
This issue is not related to the ESXi VM environment. It's a bug inside the script that has already been resolved. Please install the more recent 4.8.4
