### ISSUE TITLE
Document Opened Notification setting

### ISSUE THREAD

**Issue by ThomasMoody2015** [eirannejad/pyRevit#1088]
**Describe the bug**

Is there a setting to turn off the Document Opened notification? I have some scripts that open and close a lot of files and I am having to hit ok each time because of it.

**Comment by eirannejad** [comment]
Do you have the pyRevitDev extension loaded? If yes, turn that off. pyRevitDev is a development extension and doesn't have any tools. It's there for me to make sure I don't break things

**Comment by ThomasMoody2015** [comment]
I noticed that It said "PyRevitDevTools" at the top of the window so I unloaded that Extension. Now the same notification comes up but it only says "PyRevit" instead of "PyRevitDevTools". I ended up detaching PyRevit altogether while I'm working on this script.

**Comment by eirannejad** [comment]
You have to restart Revit after unloading the extension since the event listeners are already registered. Glad you found a workaround
