### ISSUE TITLE
Revit 2021 crashes [due new hotfix?]

### ISSUE THREAD

**Issue by jorisvdmeulen** [eirannejad/pyRevit#1089]
**Describe the bug**
I updated my revit 2021 with the released hotfix which makes the latest build. Now Pyrevit won't load on 2021 but pyrevit does load on 2019 (also installed on same machine).

![image](https://user-images.githubusercontent.com/58419455/101766366-f73e3080-3ae2-11eb-98e2-d298fa6216be.png)

**To Reproduce**
1. start Revit.

**Expected behavior**
That pyrevit loads / starts up as it does on 2019 and 2021 prior releases.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - pyRevit Version 2.7.18
 - pyRevit Environment: 

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.2" | Path: "C:\Users\JM\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2019.2.2 Hotfix" | Engine: 277 | Path: "C:\Users\JM\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\JM\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\JM\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> Running Revit Instances
Error: De objectverwijzing is niet op een exemplaar van een object ingesteld.
Run with "--debug" option to see debug messages
```

**Additional context**

![image](https://user-images.githubusercontent.com/58419455/101766280-dc6bbc00-3ae2-11eb-93e0-9d90b564e7e6.png)

**Comment by eirannejad** [comment]
Send a `pyrevit env` report please as the issue template requested. There is a reason for the comments on the template. Ignoring and deleting them doesn't really make our job easier

**Comment by jorisvdmeulen** [comment]
> Send a `pyrevit env` report please as the issue template requested. There is a reason for the comments on the template. Ignoring and deleting them doesn't really make our job easier

I'm sorry Eirannejad, I'm unsure what went wrong, but I for sure didn't deleted a whole bug template. I guess I clicked on a blank issue, my bad, sorry. I updated my original post. 

The env. shows an error and says I should run pyrevit env --debug. Want me to post that too?

**Comment by eirannejad** [comment]
v4.8.5 is published. Would you mind testing this? If it didn't work try attaching pyRevit using the custom IronPython engine `pyrevit attach master default --installed`
