### ISSUE TITLE
Can't install extensions

### ISSUE THREAD

**Issue by jgraciar** [eirannejad/pyRevit#1090]
Hi, I've install successfully pyrevit but I can't install any extension automatically.
I've provide my GitHub credentias but when I click on "Install extension" any occurs

Thanks in advance

**Comment by eirannejad** [comment]
What extension are you trying to install?

**Comment by jgraciar** [comment]
pyRevitPlus
pyRevitMep
pyApex
Revitron
Revitron UI

**Comment by eirannejad** [comment]
Extensions have been added to the Extension Manager in 4.8.9 release
