### ISSUE TITLE
Print dialogue missing page sizes available to printer

### ISSUE THREAD

**Issue by DuncanLithgow** [eirannejad/pyRevit#1092]
**Is your feature request related to a problem? Please describe.**
The 'Page Settings' spin menu does not include the the paper sizes as the printer has configured. Instead it includes the configurations saved from Revits Print Setup dialogue. This means I have drawings I can't print with this tool even though I have paper sizes set up for them. I have to go back inside Revit to set them up.

**Describe the solution you'd like**
The selection of paper sizes should be the same as the printer has access to.

**Describe alternatives you've considered**
A workaround would simply be to make this more obvious by renaming the spin menu 'Saved Print Setups'. Calling it 'Page Settings' is unclear.

**Additional context**
![PPhm0Pj9BL](https://user-images.githubusercontent.com/3223028/102470813-b8fdbf80-4054-11eb-8f93-965f7a02436d.png)
![P6ITiCVilW](https://user-images.githubusercontent.com/3223028/102470834-bf8c3700-4054-11eb-9ef5-e4eb1349f2a3.png)
![image](https://user-images.githubusercontent.com/3223028/102475928-c9b13400-405a-11eb-9f3a-e2f7788437f7.png)

**Comment by eirannejad** [comment]
@DuncanLithgow So this is kinda a limitation of Revit API. The print mechanism wants a **Revit Print Setting** to print a sheet. It doesn't make sense for me to replicate all the options and settings of the Revit Print Settings inside the pyRevit print window again. It's safer for the Revit user to define these print settings and pick them when printing using pyRevit. It also blends nicely into the `Various Paper Size` feature that allows selecting a specific Revit Print Setting for each sheet.

Let me know if this helps. I hope I have understood the problem correctly.

**Comment by DuncanLithgow** [comment]
If this is tricky then I suggest just renaming the spin menu to 'Saved Print Setups' to make it clearer. I feel like an idiot not noticing that they are a list of the print setups. But I know from experience that if I can be that thick then a lot of other people would also trip over that as a problem.
