### ISSUE TITLE
pyRevit won't install

### ISSUE THREAD

**Issue by teflaherty67** [eirannejad/pyRevit#1094]
**Describe the bug**
I downloaded pyrevit & the first time I ran the .exe pyRevit installed, but didn't load into Revit. I read some information on this site & realized I had downloaded the CLI version. I uninstalled that, removed all files & folder for pyRevit and then downloaded the pyrevit_4.8.4_signed.exe file and ran that. However, the installer detected something on my machine and rather than install a new clean copy of pyRevit, it thinks I have pyRevit already installed and gives me the Modify/Repair/Remove screen.

I first tried Remove and got an error and then I tried the Modify option and got the same error:

![pyRevit error](https://user-images.githubusercontent.com/67797311/102656274-369afb80-4139-11eb-8735-ad5237941429.png)

Then I tried the Repair option and got this error:

![pyRevit repair error](https://user-images.githubusercontent.com/67797311/102656368-62b67c80-4139-11eb-9393-6bddb1a6db2c.png)

_If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below._

I tried running this command and the 'pyrevit env' command and got this message:  "pyrevit is not reconized as an internal or external command, operable program or batch file"

I'm running Windows 10 Home and trying to install pyRevit 4.8.4 and attach it to Revit 2021.1.2

**Comment by eirannejad** [comment]
Ok. Take a look at this. Let's see if this fixes the issue https://github.com/eirannejad/pyRevit/issues/1045#issuecomment-724922950

**Comment by teflaherty67** [comment]
I was able to get pyRevit installed and working; thanks! Now to address the issue with Dynamo; hope it's as easy as a fix.

**Comment by natalbomb** [comment]
For reasons, I had to delete all of my Revit files and plug-ins from my computer.  After redownloading everything, pyrevit seems to be having trouble reinstalling.  I checked the forum and have used the pyrevit_doctor tool as recommended in previous comments, but its still giving me the same messages.  Can you please help?  I have attached the error message as well as the .txt log it gave me when it cancelled the download.
![PyRevit Error Message](https://user-images.githubusercontent.com/42562285/120955872-fac01680-c717-11eb-8eb0-75d8afa79b49.jpg)

[MSIA81.LOG](https://github.com/eirannejad/pyRevit/files/6605689/MSIA81.LOG)

**Comment by SalmanGhanem** [comment]
Same issue for me also - I tried to run pyrevit doctor and it did not solve the issue - Can you please help?
![image](https://user-images.githubusercontent.com/40688768/121473079-2b7fa480-c9d3-11eb-99c9-1258c34b4928.png)
[MSI91F1.LOG](https://github.com/eirannejad/pyRevit/files/6628742/MSI91F1.LOG)
