### ISSUE TITLE
'Remove Revision From Sheets' button should be 'UNset Revision'

### ISSUE THREAD

**Issue by RevitIRL** [eirannejad/pyRevit#1095]
**Is your feature request related to a problem? Please describe.**
It's a little confusing that it says "Set Revision" instead of "Unset Revision". I suppose that it could be interpreted as "Set the status of Revision to unchecked", but it's makes me wonder if I accidentally chose "Set Revision On Sheets" instead (since the dialogs are identical, so I keep canceling and re-selecting).

**Describe the solution you'd like**
Rename the button to "Unset Revision", "Uncheck Revision", "Set Revision to Unchecked", or similar.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by eirannejad** [comment]
I can see the confusion. Ok. This is an easy change.

**Comment by eirannejad** [comment]
Fixed and will be published with next release
