### ISSUE TITLE
BCF support 

### ISSUE THREAD

**Issue by DuncanLithgow** [eirannejad/pyRevit#1097]
**Is your feature request related to a problem? Please describe.**
The problem is just that the only opensource bcf plugin for Revit, bcfier, is not actively maintained and not built on a cross platform library. 

**Describe the solution you'd like**
BCF support built with Python. There's a brand new bcf python library in the https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src/bcf which might integrate well with pyRevit to add this important functionality. All development on IfcOpenShell bcf support also supports BlenderBIM Add-on and (probably soon) FreeCAD

**Describe alternatives you've considered**
BCFier, but it can only ever realistically support windows based programs 

**Additional context**

**Comment by eirannejad** [comment]
Nice! this is great! Thanks @DuncanLithgow

**Comment by eirannejad** [comment]
@htlcnn Hello! I see you are working on this BCF repo. Is this something we can ship with pyRevit?

**Comment by htlcnn** [comment]
@eirannejad Hi :) please continue discussing the features, user interface (some mockups) and how you want to ship the bcf module with pyRevit. I'll be more than happy to implement it :)

**Comment by eirannejad** [comment]
Per @DuncanLithgow comment, I'm thinking of including the `bcf` module under `pyrevit/interop` so developers can use it in their scripts

```python
from pyrevit.interop import bcf
```

**Comment by htlcnn** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/blob/977df60f05d34e57a94158b9537bbc1dda03d87b/src/bcf/bcf/bcfxml.py#L10

This line makes use of `xmlschema` lib which supports Python 3.6+. I have to ask @Moult whether he wants to support older Python, then we'll find a solution.

**Comment by Moult** [comment]
@htlcnn I personally have no interest in supporting Python 2, which was end of life in April last year. However, if somebody wants to support it and will write the code to do it, I'm happy to merge PRs. If the code change is significant, then I would prefer it be maintained in a fork, if it is not significant, it can live alongside Python 3, but I won't personally take any effort to maintain it :) Go for it!

Is PyRevit still Python 2 for some reason?

**Comment by htlcnn** [comment]
@Moult for Revit, I find the most stable implementation is IronPython which is based on Python 2.7. pyRevit was developed mostly based on IronPython and have supported CPython recently, yet not very stable because of the maturity of the pythonnet lib that it uses. Sure I'll try not to break anything.

**Comment by eirannejad** [comment]
@DuncanLithgow I'm going to mark this as Enhancement for now, since you can always download the bcf python module and add it to `lib/` directory of your pyRevit extension. We'll revisit this when there are more requests I geuss
