### ISSUE TITLE
I ve installed pyRevit_4.8.4_signed but i don't have Py revit on REVIT

### ISSUE THREAD

**Issue by AlphaT23** [eirannejad/pyRevit#1099]
i downloaded this version on git hub pyRevit_4.8.4_signed

it installed on appdata/roaming/
but when i saw in revit addins folder there isn't pyrevit addin.

How i can do ?

**Comment by eirannejad** [comment]
Open a command line and run `pyrevit env` and share the results here please

**Comment by joaoluisbrasil** [comment]
same problem here...
PS H:\> pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Joao Lopes\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2020.2 (Full Install) | Version: 20.2.1.1 | Build: 20191106_1200(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
2017.2.5 Security Fix | Version: 17.0.1169.0 | Build: 20190508_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
2016 Release 2 (R2) | Version: 16.0.1063 | Build: 20151007_0715(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.18362]
Executing User: LYMOCONS\Joao Lopes
Active User: LYMOCONS\Joao Lopes
Admin Access: No
%APPDATA%: "C:\Users\Joao Lopes\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.4.0
PS H:\> pyrevit attach master 277 --installed
Error: Can not find clone "master"
Run with "--debug" option to see debug messages

**Comment by eirannejad** [comment]
Okay. See this please. https://github.com/eirannejad/pyRevit/issues/1075#issuecomment-734950066

**Comment by joaoluisbrasil** [comment]
Thanks...it's easy when you know!
________________________________
De: Ehsan Iran-Nejad <notifications@github.com>
Enviado: terça-feira, 29 de dezembro de 2020 14:29
Para: eirannejad/pyRevit <pyRevit@noreply.github.com>
Cc: joaoluisbrasil <joaoluis_brasil@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [eirannejad/pyRevit] I ve installed pyRevit_4.8.4_signed but i don't have Py revit on REVIT (#1099)


Okay. See this please. #1075 (comment)<https://github.com/eirannejad/pyRevit/issues/1075#issuecomment-734950066>

**Comment by AlphaT23** [comment]
Hi !

C:\Users\Ant On>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Ant On\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.3 | Version: 20.2.30.42 | Build: 20200826_1250(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2 (Full Install) | Version: 19.2.1.1 | Build: 20190108_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19041]
Executing User: ANTON-X10\Ant On
Active User: ANTON-X10\Ant On
Admin Access: No
%APPDATA%: "C:\Users\Ant On\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.4.0

**Comment by AlphaT23** [comment]
I do what you say in #1075 (comment) and it's ok
