### ISSUE TITLE
Installation error in Revit 2017. Missing files during process: libintl-8.dll, libcurl-4.dll, libpcre-1.dll and libiconu-2.dll

### ISSUE THREAD

**Issue by JuanCalvoFerrandiz** [eirannejad/pyRevit#110]
First of all, great work!
During installation it appear 4 error windows informing of these missing files.
After that, no contextual tab is install.
I don't know if I did something wrong or is the compatibility with Revit 2017.
Thanks.
![screenshot 33](https://cloud.githubusercontent.com/assets/20303036/16615465/345d27fe-4377-11e6-94f2-844e1024fb0e.png)

**Comment by eirannejad** [comment]
Juan, this is actually the portable git software trying to clone the pyRevit repository on your machine and showing these errors. What version of windows are you running this on?

**Comment by JuanCalvoFerrandiz** [comment]
Hello.

I'm trying to do the installation in windows 10.

Thanks for your time.

**Comment by eirannejad** [comment]
I'm not sure what's wrong with the portable git tool. Another way to get the tools is to use RevitPythonShell to load the tools. Manually download the scripts from the repository. Also install the RevitPythonShell (RPS) if you don't have it already. Then go under RPS settings and under the last tab, click on the startup script and direct to the `__init__.py` file in the pyRevit repository. Then reload revit and RPS will load the library at startup

**Comment by JuanCalvoFerrandiz** [comment]
Hi,

I have changed the startup script as you suggest 
from:
...AppData\Roaming\RevitPythonShell2017\startup.py
to:
...PYTHON\pyRevit-master\pyRevit-master\__init__.py

and when I open REVIT RevitPythonShell shows he isworking:

![screenshot 35](https://cloud.githubusercontent.com/assets/20303036/16651941/6282aa48-4447-11e6-984d-d9d9f4fb21c1.png)

and it ends with this final window:

![screenshot 34](https://cloud.githubusercontent.com/assets/20303036/16651950/7010940e-4447-11e6-807a-b04f6c5a53a3.png)

But no contextual tab appears:

![screenshot 36](https://cloud.githubusercontent.com/assets/20303036/16651980/b621c2d8-4447-11e6-9e05-ecd2c09b5eca.png)

QUESTION: RevitPythonShell is leaving of doing something when I change of StartupScript from startup.py to  __init__.py? 

Thanks!!

**Comment by JuanCalvoFerrandiz** [comment]
This is an image of the last part of the RevitPythonShell - Output. It seems it is not getting the icons.  Although it puts the tab has been found, right?
![screenshot 38](https://cloud.githubusercontent.com/assets/20303036/16652600/e4cb31ec-444b-11e6-8c48-476347677e88.png)

**Comment by eirannejad** [comment]
Juan, This might be an issue with DLL file name method that includes the username in the file naming and it seems like your username is a full email address and has a dot in it before the file extension. Let me revise the startup script and I'll update the repo.

**Comment by eirannejad** [comment]
Okay. `__init__.py` updated. Download the latest and give it a try.

**Comment by JuanCalvoFerrandiz** [comment]
Great. Problem solved with the new "_init_.py". Thanks.

If it's possible I will like to understand what we are doing by changing the startup file:

- I understood with the reading of "Scripting Autodesk Revit with RevitPythonShell" that this is a file that loads at the beginning,  just after the RevitPythonShell, which loads the tab.

- But what happens if I want to create my own tab that loads at the beginning? I will need to use the "Adding your own tabs" method, putting my scripts in other folders alongside?

- There is some inconvenience of not loading the original "starup.py"?

If possible I would like to make a more general question , which is based on my limited knowledge of programming : My intention is to make a learning process with Python and all these great tools which I'm finding, to finish developing apps that can be distribute by the Autodesk App Store. Do you consider this process the way to reach my goal ? And it is possible to develop an App for distribution in the App Store with Python? Or I need to program at C#? Thanks again for your time and work.

**Comment by eirannejad** [comment]
Juan,
See answers below:

**Comment by eirannejad** [comment]
Installation package updated with the latest version of Portable Git. Tests under windows 10 are successful.

**Comment by JuanCalvoFerrandiz** [comment]
Thanks for your answers. I will start trying making some basic addings with RevitPythonShell following Cyril Waechter and Daren Thomas instructions.

In my case, I continue having .dll missing files during installation with Portable Git. But it works fine with the RPS way.
