### ISSUE TITLE
Generating QR/Barcodes in Revit Environment using Revit Schedules

### ISSUE THREAD

**Issue by karthi1015** [eirannejad/pyRevit#1102]
Ability to create QR codes via Revit Schedules and link these images to the corresponding elements/sheets.

Posted an Example workflow in pyRevit forums. [](https://discourse.pyrevitlabs.io/t/pyrevit-qr-barcode-maker/158)

**Comment by karthi1015** [comment]
https://discourse.pyrevitlabs.io/t/pyrevit-qr-barcode-maker/158

**Comment by eirannejad** [comment]
This seems to be very specific to your workflow. Would you mind writing up how this can be a generic tool and what would the steps to use be?

**Comment by karthi1015** [comment]
Hi Ehsan
This QR process could be useful for field tracking inventory, status etc..(User will decide which parameter is used to generate depending on their need.) Most common use cases are for inhouse inventory tracking or using BIM 360 Asset management from Revit (from design phase)
Steps based on my experience:
Ability to generate a QR code from any Revit parameters and add it to a sheet.
Adding to sheet will be basically a UI dictating X and Y in a sheet location and place QR image/View in that location single or batch. 
Alternate workflow is creating drafting/legend views with QR patterns as a hatch or filled region this will help with revit performance with less images in the file. (In my case I had to create 1200 images in one revit file). This is not possible by dynamo or any other workflow as of now.
I understand this is really limited or specific requirement underlying problem is there is no workflow that’s supported using Revit API or Revit addin to create QR with parameter info for anyone to leverage. Just wanted to try using Pyrevit UI will make workflow really efficient. 
Please let me know if you want me to explain further for any of these steps.

**Comment by karthi1015** [comment]
I understand this is really limited or specific requirement underlying problem is there is no workflow that’s supported using Revit API or Revit addin to create QR with parameter info for anyone to leverage. Just wanted to try using Pyrevit UI will make workflow really efficient.  For now I am looking a way generate QR from revit without dynamo. It would be great if you could have sample for generating QR in your Pyrevit template tab. I could figure out the rest depending on my need.

**Comment by karthi1015** [comment]
@eirannejad any updates on this?
