### ISSUE TITLE
Cancel Print Option

### ISSUE THREAD

**Issue by alexbrunette** [eirannejad/pyRevit#1105]
**Is your feature request related to a problem? Please describe.**
Can't cancel a print job

**Describe the solution you'd like**
a dialogue open while printing with the option to cancel the current print job

**Describe alternatives you've considered**
End Task 

**Additional context**

**Comment by eirannejad** [comment]
Revit does not support cancelling print jobs. Once it starts printing you have to wait or kill the Revit process
