### ISSUE TITLE
Error loading pyRevit - Revit 2021.1.2

### ISSUE THREAD

**Issue by wafkthompson** [eirannejad/pyRevit#1106]
Recently updated to Revit 2021.1.2, and installed pyRevit 4.8.4 afterwards.

pyRevit seemed to install without issue. When I initially opened Revit afterwards, I got the typical security pop up asking me if I want the add-in to "Always Load" or "Do Not Load". After selecting "Always Load", I got the attached popup error window. I get the same popup error window every time I open Revit now. The pyRevit tab in the Revit ribbon does not load.   

I tried `pyrevit attach master 277 --installed` in the command prompt, but it did not resolve the issue.

**To Reproduce**
1. Open "Revit 2021",
2. Popup window "PyRevitLoader - Error Loading pyRevit" appears,
3. Close popup window,
4. pyRevit tab not loaded in Revit ribbon.

**Expected behavior**
Revit opens (without popup error window). pyRevit tab available from Revit ribbon.

**Screenshots**
![image](https://user-images.githubusercontent.com/76666837/103181374-b0c83000-485d-11eb-867e-4616810baeff.png)

**Desktop:**
 - OS: Windows 10 Version 20H2 (OS Build 19042.685)
 - pyRevit Version: 4.8.4
 - pyRevit Environment: 
```
C:\Users\wafkt>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.4" | Path: "C:\Users\wafkt\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2021" | Engine: 277 | Path: "C:\Users\wafkt\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\wafkt\AppData\Roaming\Autodesk\Revit\Addins\2021\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\wafkt\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2021 | Version: 21.1.20.44 | Build: 20201109_1530(x64) | Language: 1033 | Path: "Revit 2021\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

**Comment by kollyboi** [comment]
I have a similar issue but I have attached ironpython engine 2.7.10 due to compatibility issues with another addin. If I downgrade to 279, the WPF issue does not show, but then I get a warning about different ironpython engines trying to load.

![image](https://user-images.githubusercontent.com/44774905/103211051-731fe180-4907-11eb-9a4e-7dc54cd29b02.png)

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.4" | Path: "C:\Users\kyko\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2021.1" | Engine: 2710 | Path: "C:\Users\kyko\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\kyko\AppData\Roaming\Autodesk\Revit\Addins\2021\pyRevit.addin"
master | Product: "2020.2.3" | Engine: 2710 | Path: "C:\Users\kyko\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\kyko\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\kyko\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021.1 | Version: 21.1.0.108 | Build: 20200708_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.3 | Version: 20.2.30.42 | Build: 20200826_1250(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
PID: 21600 | 2020.2.3 | Version: 20.2.30.42 | Build: 20200826_1250(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2020"
==> User Environment
Microsoft Windows 10 [Version 10.0.18363]
Executing User: COWI\kyko
Active User:
Admin Access: No
%APPDATA%: "C:\Users\kyko\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
Installed .Net-Core Target Packs: v5.0.101
pyRevit CLI 4.8.4.0
```

**Comment by eirannejad** [comment]
Okay. Seems like pyRevit can not find its own runtime for some reason.
Close all revits and run `pyrevit caches clear --all` on the command line. This should clear all the caches. Run 2021 again and see if it loads.

**Comment by wafkthompson** [comment]
Didn't fix the issue for me. I tried rolling back to 4.7.6, and it doesn't seem to work either. Nothing happens at all. No error messages.

**Comment by eirannejad** [comment]
@wafkthompson Okay launch pyRevit and let it crash. Then go to `%appdata%/pyRevit/20XX` and grab the `pyRevit_20XX_***_PyRevitLabs.PyRevit.Runtime.log` file and send to me please

**Comment by eirannejad** [comment]
v4.8.5 is published. Would you mind testing this? If it didn't work try attaching pyRevit using the custom IronPython engine `pyrevit attach master default --installed`

**Comment by kollyboi** [comment]
Hi.

I'm getting the old wpf error on ipy 2710, but it works with the default
277, but then I can't use the corporate addin which uses 2710.
[image: image.png]

**Comment by eirannejad** [comment]
@kollyboi Go to pyRevit settings and under Core, switch to "Custom Engine (2.7.11)" This should avoid all ipy conflicts

**Comment by kollyboi** [comment]
YES! ❤

**Comment by eirannejad** [comment]
OMG that makes me soo happy!!! Closing this for now

**Comment by wafkthompson** [comment]
Sorry for the late reply. I'm a college instructor. Busy times.

The log file has nothing in it - 0 KB.

I have a lot of add-ins installed - I know sometime they don't play nice
with each other.

[image: image.png]

**Comment by Luis-B-A** [comment]
I'm struggling with this issue as well. I have read that it is often fixed by uninstalling other add-ins but I am really hoping to keep them since I use all of my add-ins regularly

**Comment by HArchitekt** [comment]
Has anybody found a solution yet?

**Comment by ajayholland** [comment]
We are a design firm with more than one hundred Revit users. We use VPN, VDI and local processing.
With the latest version of pyRevit (pyRevit_4.8.12.22247_signed), the program will crash upon opening. Usually, a re-install will correct the problem, but we have some unsolved cases in Revit version 2022.
Is there a solution that does not require coding?
~Allen Holland
Boulder Associates

**Comment by Avinash-Verma-26** [comment]
> @wafkthompson Okay launch pyRevit and let it crash. Then go to `%appdata%/pyRevit/20XX` and grab the `pyRevit_20XX_***_PyRevitLabs.PyRevit.Runtime.log` file and send to me please
[pyRevit_2024_df2eec3d0c4a50a5_PyRevitLabs.PyRevit.Runtime.log](https://github.com/eirannejad/pyRevit/files/12475825/pyRevit_2024_df2eec3d0c4a50a5_PyRevitLabs.PyRevit.Runtime.log)
