### ISSUE TITLE
Error loading pyRevit, can't find IronPython modules

### ISSUE THREAD

**Issue by kollyboi** [eirannejad/pyRevit#1107]
I have attached ironpython engine 2.7.10 due to compatibility issues with another addin. If I downgrade to 279, the WPF issue does not show, but then I get a warning about different ironpython engines trying to load.
Is there a setting I could set to let pyRevit see my IronPython install?

![image](https://user-images.githubusercontent.com/44774905/103211051-731fe180-4907-11eb-9a4e-7dc54cd29b02.png)

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.4" | Path: "C:\Users\kyko\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2021.1" | Engine: 2710 | Path: "C:\Users\kyko\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\kyko\AppData\Roaming\Autodesk\Revit\Addins\2021\pyRevit.addin"
master | Product: "2020.2.3" | Engine: 2710 | Path: "C:\Users\kyko\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\kyko\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\kyko\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021.1 | Version: 21.1.0.108 | Build: 20200708_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.3 | Version: 20.2.30.42 | Build: 20200826_1250(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
PID: 21600 | 2020.2.3 | Version: 20.2.30.42 | Build: 20200826_1250(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2020"
==> User Environment
Microsoft Windows 10 [Version 10.0.18363]
Executing User: COWI\kyko
Active User:
Admin Access: No
%APPDATA%: "C:\Users\kyko\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
Installed .Net-Core Target Packs: v5.0.101
pyRevit CLI 4.8.4.0
```

I have set the PYTHONPATH environment variable.

![image](https://user-images.githubusercontent.com/44774905/103213377-c4cb6a80-490d-11eb-8303-94e815b9c92e.png)

**Comment by eirannejad** [comment]
pyRevit ships with all the IronPython versions that it supports. It doesn't load IronPython from an independent installation. All the binaries are located under `bin/engines/` directory inside the pyRevit installation

**Comment by kollyboi** [comment]
Then why do I get the error message that it can't find the wpf module?

**Comment by eirannejad** [comment]
Great question. Would you mind switching to 2.7.7? run this command in command line:

`pyrevit attach master 277 --installed`

**Comment by kollyboi** [comment]
Unfortunately, I cannot. I have an addin that uses IronPython 2710 and I'll get an error message about the version collision. If I try to disable the addin, revit will not start at all. I do not know why that is the case. I will investigate this after new years. But I have been running pyRevit before on 2710 side by side with this addin on an earlier version.

**Comment by kollyboi** [comment]
I tried installing pyRevit differently with pyRevit CLI with these lines. Still the same _wpf-module error. I'm thinking that since that other addin loads IronPython, the _wpf module is missing from that DLL-load. Maybe the problem then, lies with that addin and how it loads ipy.

```
path %PATH%;%PROGRAMFILES%\pyRevit CLI
pyrevit detach --all
pyrevit clones forget --all
pyrevit clones delete --all --clearconfigs
pyrevit clone master  --dest="C:\Programdata\pyRevit"
pyrevit configs logs verbose
pyrevit configs checkupdates enable
pyrevit configs autoupdate enable
pyrevit configs rocketmode enable
pyrevit configs filelogging disable
pyrevit configs loadbeta enable
pyrevit configs usercanupdate yes
pyrevit configs usercanextend yes
pyrevit configs usercanconfig yes
pyrevit configs colordocs enable
pyrevit attach master 2710 --installed --allusers
```

**Comment by eirannejad** [comment]
Check to see if the other addin has `IronPython.Wpf.dll` included and loaded.

**Comment by kollyboi** [comment]
`pyRevitLoader.py` leads to else statment in `framework.py` on line 85 and finds wpf in my ironpython folder on my harddrive which tries to load the _wpf module, which I do not have on my hd. The `IronPython.Wpf.dll` file was in fact included in the other addin, but that does not seem to lead to the error.

![image](https://user-images.githubusercontent.com/44774905/103507557-c641e900-4e5f-11eb-8e31-91875456748d.png)

![image](https://user-images.githubusercontent.com/44774905/103507562-cb069d00-4e5f-11eb-8441-4708e715e5de.png)

**Comment by eirannejad** [comment]
Applied a big change to attempt at resolving this issue and so far it is showing promising results. Will publish with 4.8.5 soon
