### ISSUE TITLE
Can't Convert .sat file to FreeForm elements?

### ISSUE THREAD

**Issue by gokermu** [eirannejad/pyRevit#1108]
Hey there,

I have a rhino model which i export as an .sat file and import into Revit 2017. I want to convert it into freeform element and apply parameters, materials etc. but I keep getting the same error.

You can find Rhino model and .sat file down below. Am I doing something wrong?

Thanks.

M.

![Screenshot_1](https://user-images.githubusercontent.com/51519350/103227243-e98c0600-493e-11eb-824b-d23649ac7905.png)

[toplar_error.zip](https://github.com/eirannejad/pyRevit/files/5747937/toplar_error.zip)

**Comment by eirannejad** [comment]
I haven't tested this in 2017. Works in 2020


https://user-images.githubusercontent.com/8197916/103251254-e5ef8380-492c-11eb-8d3c-9687b116433b.mp4

**Comment by gokermu** [comment]
> I haven't tested this in 2017. Works in 2020
> 
>  6M9P4HwbNo.mp4

hey ehsan,

that's the thing actually. i have more than one version of revit and it works just fine in 2020. I am creating manufacturer models in revit and I have ton of rhino models. i have simplified them and since i am creating families, the older the version, the better. that's why i have to use 2017 :( 

i hope you can solve this issue for 2017. thanks

Mucahid.

**Comment by eirannejad** [comment]
Fixed and will be published with next release
