### ISSUE TITLE
Load More Types doesn't list the location if it can't find the family

### ISSUE THREAD

**Issue by RevitIRL** [eirannejad/pyRevit#1109]
**Describe the bug**
pyRevit > [Project] > Load More Types
When it can't find the family, it doesn't seem to have a path.
At first I thought it had to do with an upgraded model/template, because the families seem to be in the right place (or where I would expect), but then I noticed that it worked properly with some other families, so it seems like it's looking in the wrong location, but I don't know where that location is...

**To Reproduce**
1. select a family that's no longer where it was loaded from?
2. pyRevit > [Project] > Load More Types
3. See error

**Expected behavior**
the path should be shown

**Screenshots**
I didn't see a button to upload an image, so:
[https://static.miraheze.org/revitwiki/5/50/PyRevit_4.7.6_-_Load_More_Types_-_Can_not_find_original_family_file_at.png](url)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.7.6
 - pyRevit Environment:
```C:\Users\lionel>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.6" | Path: "C:\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2021" | Engine: 277 | Path: "C:\pyRevit-Master" | Manifest: "C:\Users\lionel\AppData\Roaming\Autodesk\Revit\Addins\2021\pyRevit.addin"
master | Product: "Autodesk Revit 2020" | Engine: 277 | Path: "C:\pyRevit-Master" | Manifest: "C:\Users\lionel\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
master | Product: "2019.2.1" | Engine: 277 | Path: "C:\pyRevit-Master" | Manifest: "C:\Users\lionel\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
master | Product: "2018.3.2" | Engine: 277 | Path: "C:\pyRevit-Master" | Manifest: "C:\Users\lionel\AppData\Roaming\Autodesk\Revit\Addins\2018\pyRevit.addin"
master | Product: "2017.2.3" | Engine: 277 | Path: "C:\pyRevit-Master" | Manifest: "C:\Users\lionel\AppData\Roaming\Autodesk\Revit\Addins\2017\pyRevit.addin"
master | Product: "2016 Update 7 for R2" | Engine: 277 | Path: "C:\pyRevit-Master" | Manifest: "C:\Users\lionel\AppData\Roaming\Autodesk\Revit\Addins\2016\pyRevit.addin"
master | Product: "2015 Release 2 Update Release 14  (Subscription only release)" | Engine: 277 | Path: "C:\pyRevit-Master" | Manifest: "C:\Users\lionel\AppData\Roaming\Autodesk\Revit\Addins\2015\pyRevit.addin"
master | Product: "2014 Update Release 3" | Engine: 277 | Path: "C:\pyRevit-Master" | Manifest: "C:\Users\lionel\AppData\Roaming\Autodesk\Revit\Addins\2014\pyRevit.addin"
master | Product: "2013 Update Release 3" | Engine: 277 | Path: "C:\pyRevit-Master" | Manifest: "C:\Users\lionel\AppData\Roaming\Autodesk\Revit\Addins\2013\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\lionel\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2021 | Version: 21.1.10.26 | Build: 20200909_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021"
Autodesk Revit 2020 | Version: 20.2.30.42 | Build: 20200826_1250(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
2019.2.1 | Version: 19.2.10.7 | Build: 20190225_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
2018.3.2 | Version: 18.3.2.7 | Build: 20181011_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018"
2017.2.3 | Version: 17.0.1150.0 | Build: 20171027_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
2016 Update 7 for R2 | Version: 16.0.1185.0 | Build: 20161004_0715(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016"
2015 Release 2 Update Release 14  (Subscription only release) | Version: 15.0.1259.0 | Build: 20160512_0715(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2015"
2014 Update Release 3 | Version: 13.11.4 | Build: 20140709_2115(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2014"
2013 Update Release 3 | Version: 12.11.10090 | Build: 20130531_2115(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit Structure 2013"
==> Running Revit Instances
PID: 2144 | 2018.3.2 | Version: 18.3.2.7 | Build: 20181011_1500(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2018"
==> User Environment
Microsoft Windows 10 [Version 10.0.18363]
Executing User: KAI-HAWAII\lionel
Active User:
Admin Access: No
%APPDATA%: "C:\Users\lionel\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v4.5.1 v4.6.1
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.25.0.0```

**Additional context**
Add any other context about the problem here.

**Comment by eirannejad** [comment]
@RevitIRL The tool looks in the Family that is loaded into the model to find the original path. Then tries to reload it from the path to grab the other types. Sometimes the families don't have the original path stored in them. In this case the tool doesn't know where to get the family from.

Any suggestions on how to make this work for you?

**Comment by RevitIRL** [comment]
If the family doesn't have the original path, change the message from "Can not find original family file at" to "No path found in family." (or something similar). Do you know what causes it? Maybe including a tip on how to fix, or even a Browse... button (for convenience).

If you really want to go all-out, you could setup properties for where to search for families that don't have paths (for each version of Revit, we have one folder for our custom families, and another folder for OOTB families).

I created a separate #1110 for other requests not related to this error dialog.

**Comment by ariccb** [comment]
> If the family doesn't have the original path, change the message from "Can not find original family file at" to "No path found in family." (or something similar). Do you know what causes it? Maybe including a tip on how to fix, or even a Browse... button (for convenience).
> 
> If you really want to go all-out, you could setup properties for where to search for families that don't have paths (for each version of Revit, we have one folder for our custom families, and another folder for OOTB families).
> 
> I created a separate #1110 for other requests not related to this error dialog.

This suggestion is really good. I think most companies have their standard libraries broken up by revit version year, so each version could have a default path folder to search for the revit family if it's not found in the original family file. I'm running into this issue a lot lately, and it's one of my favourite (of many) PyRevit features. Any ideas of what causes the family instance not to have the original file path stored?
