### ISSUE TITLE
Clarification about Instructions for push buttons

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#111]
As per instructions (pasted below),  
 **Icon:** 
_1005_Revit_PushButton_BIM.png_  
 Generates a button labeled "BIM" in the a panel section named Revit. 

**Script** 
_BIM_getCentralPath.py_
Attaches this script to the button above, as a pushButton, labeled BIM. 

Below, it states that this button _will be labeled "get_CentraPath"_
Is that correct? Seems like the 2 statements contradict each other. 

--------
Step 1: Create a .png file, with this naming pattern: __PushButton_.png 
Example: 1005_Revit_PushButton_BIM.png defines a sub-panel under pyRevit named Revit, and a simple Push Buttons in this panel named BIM.

 The startup script will expect to find only one script with name pattern similar to Method 1, and will assign it to this push button. 

Step 2: All .py script under the home directory should have the below name pattern: _.py. For the example above, BIM_getCentralPath.pywill be assigned to the push button described above. The button name will be getCentralPath

**Comment by gtalarico** [comment]
After review this again, seems like for push buttons, the last argument is not used:
XXXX_PANELSECTION_PushButton_BUTTONNAME.png
BUTTONNAME_SCRIPTNAME.py
SCRIPTNAME can be anything, and only shows up on the tooltip.
Seems like for push buttons, you would only need:
BUTTON NAME.py

Like in the example below, it could be ReloadScrips.py instead of 
ReloadScripts_ReloadSCripts.py since the second part is unecessary/

Suggestion 1:
Revise README:
Step 2:
The button name will be getCentralPath >
The Buttom Name will be **BIM.**  (not getCentralPath)

Alternative:
PushButton scrips are named 
BUTTONNAME.py instead of BUTTONNAME_anything.py

Thoughts? See image below.

![image](https://cloud.githubusercontent.com/assets/9513968/16667729/f6014e32-445b-11e6-84f8-5a6d03256816.png)

**Comment by eirannejad** [comment]
Yes. The push button disregards the actual script name. I'll update the readme file this weekend. Thanks for catching it!

**Comment by eirannejad** [comment]
Readme file corrected
