### ISSUE TITLE
Installer should detect previous install (and/or allow side-by-side for Revit 2016 support?)

### ISSUE THREAD

**Issue by RevitIRL** [eirannejad/pyRevit#1112]
**Is your feature request related to a problem? Please describe.**
1. When I install pyRevit, I usually change the install path from the default user-specific one to C:\pyRevit-Master\ (so it's available to other users, JIC, and I don't have to mess with permissions). I noticed that when I installed 4.7.6 on a machine with 4.7.4 recently, it didn't change the default to match the previously-installed location. That made me wonder what would happen if I installed to a different directory - would there be 2 tabs?
2. I also just noticed that the 4.8 beta is dropping Revit 2016 support. I just started a 2016 project for the USACE (don't even get me going on why we have to do that, since all our other USACE jobs are in 2018).

**Describe the solution you'd like**
1. The installer should detect the previous install and use the same folder by default.
2. Also, it would be nice if 4.8 would run on 2016, or if we could have 4.7.6 on 2016 with 2017 using 4.8+... For example, I'd like to gain the "list titleblocks" function in 4.8.4, but not have to lose everything in 2016 to get it (I'd be fine if newer stuff didn't work in 2016).

**Describe alternatives you've considered**
I haven't tried testing two side-by-side installs. I also haven't tried installing 4.8.4 (or copying whatever files are needed to make it load in 2016).

**Additional context**
n/a

**Comment by eirannejad** [comment]
You can still attach pyRevit to 2016 using the command line `pyrevit attach master 277 2016`
- [ ] I'll test the installer for custom paths

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists
