### ISSUE TITLE
Sorting open views

### ISSUE THREAD

**Issue by djdarkstream** [eirannejad/pyRevit#1113]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I've got multiple views open from multiple projects, which I didn't open in a specific order. 
eg. I open a project and a few views, after which I open another project, then I switch back to the first and open a new view, then the order of views in Revit is not as I would like it to be. See screenshot below

**Describe the solution you'd like**
I would like a button/command to switch the order in which the views are displayed, so that it is a logical order on a project by project bases. See screenshot below

**Describe alternatives you've considered**
I have not been able to think of another solution for this :)

**Additional context**

![image](https://user-images.githubusercontent.com/5404802/103539481-759ab200-4e98-11eb-8940-86b48fbbca9c.png)
This is how it end up.

This is how I would like it to be:
![image](https://user-images.githubusercontent.com/5404802/103539535-919e5380-4e98-11eb-83ba-385c4baa755e.png)

**Comment by GertjanVDBVK** [comment]
I'm not on the developer team on pyrevit, but this does however seems like something that's not immediatly possible using anything inside the revit API. (and thus pyrevit as well).
I mean ... it could technically be done, but the way to implement it would be anything but fast or responsive.
Best thing I can imagine (scriptwise) is that you'll need to close nearly all projects, and re-open them one by one, opening all the views right after loading a project. And that would take a lot of time.. hence, unpractical.

Good descriptions though!
