### ISSUE TITLE
Error Loading Pyrevit

### ISSUE THREAD

**Issue by mcb-cadbim** [eirannejad/pyRevit#1114]
**Describe the bug**
Getting and error message on some computers when loading pyRevit, very similar to many other posts that I have read and tried whatever solutions have been offered.  The error message occurs for all versions of Revit installed and only occurs on a couple of machines out of the 30+ computers that installed it on.

**Screenshots**
See attached screen shot below.

**Desktop (please complete the following information):**
 - OS: Windows 10 64
 - pyRevit Version: 4.8 beta5

**Additional context**
If I try to do a "clean" install, the addins are not installed and the the pyRevit command line returns the following:

```
C:\>pyrevit attach master 277 --installed
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messagesEnv returns the following:
```

Thanks.

![python load error](https://user-images.githubusercontent.com/76958709/103558018-a61f2380-4e79-11eb-8afe-236902d859ec.png)

**Comment by eirannejad** [comment]
What does the `pyrevit env` report look like? does it show any clones?

**Comment by mcb-cadbim** [comment]
Here are the steps and results as an user with ADMIN rights.

```
C:\>pyrevit clone SHEA base --dest "C:\ProgramData\pyRevit\SHEA"

C:\>pyrevit attach SHEA 277 --installed --allusers
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages

C:\>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
SHEA | Deploy: "base" | Branch: "master" | Version: "4.8.4" | Path: "C:\ProgramData\pyRevit\SHEA"
==> Attachments
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```
Let me know what other information I can provide.

Thanks.

**Comment by eirannejad** [comment]
Ok try `pyrevit detach --all` and then `pyrevit attach SHEA 277 --installed --allusers` again

**Comment by mcb-cadbim** [comment]
Results of the first suggestion:

```
C:\WINDOWS\system32>pyrevit detach --all
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages

C:\WINDOWS\system32>pyrevit attach SHEA 277 --installed --allusers
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

**Comment by mcb-cadbim** [comment]
Looks like from the debug report is crashing on Revit 2015, which isn't installed.

```
Debug: Analysing registered app: Revit Architecture 2015 @ HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{7346B4A0-1500-0110-0000-705C0D862004}
Debug: App is a Revit product: Revit Architecture 2015
Debug: Can not verify install path: ""
Error: Object reference not set to an instance of an object. (System.NullReferenceException)
   at pyRevitLabs.TargetApps.Revit.RevitProduct.ListInstalledProducts()
   at pyRevitLabs.PyRevit.PyRevitAttachments.GetAttachments()
   at pyRevitCLI.PyRevitCLICloneCmds.PrintAttachments(Int32 revitYear)
   at pyRevitCLI.PyRevitCLICloneCmds.ListAttachments(String revitYear)
   at pyRevitCLI.PyRevitCLI.ProcessArguments()
   at pyRevitCLI.PyRevitCLI.Main(String[] args)
```

Will see if I can clean up this past installation and see if that helps.
Otherwise, can I email or send you the entire debug log vs posting here?

**Comment by mcb-cadbim** [comment]
UPDATE:
After searching for "leftovers" of Revit Architecture 2015 in the windows registry, which only existed on the two machines I had trouble with, was able to get things up and running and learned a little more about pyRevit.

Thanks for your support and this amazing tool!

**Comment by eirannejad** [comment]
Of course. Thanks for digging deeper into the registry and cleaning those up. The CLI is fairly a new addition so it wasn't really tested for anything before 2017
