### ISSUE TITLE
pyRevit run can't load Revit 21 model

### ISSUE THREAD

**Issue by timbart3ls** [eirannejad/pyRevit#1115]
Hi,

I am trying to load a Revit 21 model with the pyRevit run command. But I get the following error:

`Error: File is not a valid Revit file`

I am running

- pyRevit 4.8.4
- Revit 21.1.1

It was working as expected before I upgraded my models to Revit 21.

Thanks 
Tim

**Comment by eirannejad** [comment]
Please give me a bit more info. What command are you running? What's your run command doing? The results from the run command would be very helpful

**Comment by timbart3ls** [comment]
Hi Ehsan,

my script was running fine in Revit 19 but after I upgraded the model to Revit 21 my script does not work anymore. 
I attached a minimal script, revit model and the output.

Thanks 
Tim

[r21_test.zip](https://github.com/eirannejad/pyRevit/files/5796785/r21_test.zip)

**Comment by eirannejad** [comment]
@timbart3ls Okay seems like pyRevit doesn't know anything about your Revit version and is failing to get the version of the Revit file. I have fixed this and will publish with the next release

Would you mind giving me the info for your Revit so I can add to pyRevit's database?

Here is an example of what I need
```
"product": "Autodesk Revit",
"release": "2021.1.2",
"version": "21.1.20.44",
"build": "20201109_1530",
```
