### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by nathanburkholder** [eirannejad/pyRevit#1116]
Followed Install Error instructions and typed in

'pyrevit attach master 277 --installed'

Received the following 

'Error: Can not find clone "master"
Run with "--debug" option to see debug messages'

**To Reproduce**
1. Installed pyRevit with no Errors
2. Run command prompt: pyrevit env
3. ==>Attachments didn't show anything so ran: pyrevit attach master 277 --installed
4. Returned: Error: can not find clone "master"

**Expected behavior**
Fix install error

**Screenshots**
![image](https://user-images.githubusercontent.com/77116622/103918198-1aed9a00-50d4-11eb-89bd-b23a2cad848d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.8.4
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

**Additional context**

**Comment by eirannejad** [comment]
Hi @nathanburkholder Would you mind taking a look at this comment? https://github.com/eirannejad/pyRevit/issues/1075#issuecomment-734950066

**Comment by nathanburkholder** [comment]
It worked. Thank you.

[Paragon Architecture]<http://paragon-architecture.com/>BE THE SHERPA.







Nathan Burkholder | NCARB, AIA

637 W. College Street

Springfield, Missouri 65806

Phone: (417) 885-0002 ext. 1004

[cid:image006.png@01D6E4FB.40330CE0]<https://www.linkedin.com/company/paragon-architecture-inc/>  [cid:image007.png@01D6E4FB.40330CE0] <https://www.facebook.com/ParagonArchitecture>   [cid:image008.png@01D6E4FB.40330CE0] <https://twitter.com/ParagonArchMO>   [cid:image009.png@01D6E4FB.40330CE0] <https://www.instagram.com/paragon_architecture/>    website <https://www.paragonarchitecture.com/> | map<http://goo.gl/maps/PiMhz>
