### ISSUE TITLE
missing tooltips when using CPython

### ISSUE THREAD

**Issue by amastrobera** [eirannejad/pyRevit#1119]
Hi Ehsan, 

I am using Revit 2020, `pyRevit 4.7.6`. 

I started creating scripts beginning with `#! python3` to use CPython libs like you showed us [here](https://www.youtube.com/watch?v=PbdhVJRfca0&feature=youtu.be). I have `Python 3.7.2` installed.

Despite the `_script.py` modules can print variables such as `__title__`, or ` __doc__` once executed, the tooltips disappear from the buttons. 

I think that's all. if you need more information just ask me.

**Comment by eirannejad** [comment]
Take a look at using the `bundle.yaml` metadata files 👉 https://www.notion.so/Bundle-Metadata-9fa4911c14fa49c48e715421400f1427
