### ISSUE TITLE
wipeModelComponents backslashes missing from line 20 to 24.

### ISSUE THREAD

**Issue by epeter-** [eirannejad/pyRevit#112]
following changes are necessary:
#----------------------------

__doc__ = 'This tools helps you to remove extra unnecessary information in the model when sending to a ' \
          'contractor or consultant. Run the tools and select the categories that you\'d like to be removed '\
          'from the model. Then hit \"Wipe Model\" and the process will go through each category and will '\
          'remove them. You might see some errors or warnings from Revit (since this is a very distructive) '\
          'process but generally they should not crash the script.'

**Comment by eirannejad** [comment]
Resolved. Thanks!
