### ISSUE TITLE
Add Views to sheets not working like version 4.5

### ISSUE THREAD

**Issue by phanx046** [eirannejad/pyRevit#1124]
I finally updated from version 4.5 but i feel the updated version is not as good as version 4.5.  Version 4.5, I was able to select multiple callouts, sections, elevations views and then the "add views to sheet" would ask what sheets i wanted to place those views on.  The updated version would ignore my selection and make me find the views from a large list.  This method would require me to know all the names of the callouts, sections, elevations etc in order to select multiple and place them on the sheet. Is there a way to make the way version 4.5 handle add views to sheet work on the latest pyrevit version? Or is there an exe version of 4.5 so that i can reinstall?

**Comment by eirannejad** [comment]
Version 4.5? that's pretty old. Would you mind sharing a screenshot of the pyRevit about window?

**Comment by phanx046** [comment]
![image](https://user-images.githubusercontent.com/62063281/104958822-bfa68c00-599e-11eb-8f92-cce3892910cb.png)

**Comment by eirannejad** [comment]
Tested and works. Please test with 4.8.6 that is published soon and report any errors you might see
