### ISSUE TITLE
Exporting to CSV broken?

### ISSUE THREAD

**Issue by PBnJSandwich** [eirannejad/pyRevit#1130]
I'm using Pyrevit in Revit 2021 and am experiencing some exporting issues.
I'm currently using Pyrevit version: 4.8.4.

When I export schedules, and open them up it will show up as in the image attached.
I've tried to uninstall and reinstall Pyrevit on multiple machines and the problem still persists. How could I fix this?

![TEST](https://user-images.githubusercontent.com/77765032/105274463-1dc7a080-5b52-11eb-83b1-b6b2d46405c3.PNG)

**Comment by eirannejad** [comment]
already fixed and will be pushed with the next release
