### ISSUE TITLE
Preflight: default selection in selector + expand description

### ISSUE THREAD

**Issue by jmcouffin** [eirannejad/pyRevit#1132]
![image](https://user-images.githubusercontent.com/7872003/105324883-442a2200-5bcc-11eb-8b37-8815762349c5.png)

**Describe the solution you'd like**
Would it be possible (I know it is I just don't know how to do it ;p ) to: 

1. get the first check selected by default
2. get an expand arrow for the description so that the window does not extend too much
3.  make the 'hover' color much more different from the 'selected' one

**Comment by eirannejad** [comment]
Yes I tried it but don't like how large the buttons get. The expander also interferes with item selection clicks and makes selecting items awkward.

You don't like the side panel I added?

<img width="822" alt="Screen Shot 2021-01-21 at 7 04 36 AM" src="https://user-images.githubusercontent.com/8197916/105368993-f1923b00-5bb6-11eb-96d2-9fd942b8d986.png">

**Comment by jmcouffin** [comment]
I like it, 
Can it take **md** or basic formating for text especially for bullet points on the description to make it more readable
also I could not see it in my working version, I need to refork it.

**Comment by eirannejad** [comment]
Not at the moment but we can certainly make it so. I think it would create another dotnet dependency so it has to be chosen carefully.

**Comment by jmcouffin** [comment]
Nice to have only.
