### ISSUE TITLE
output: not able to save the js part of the output windows as html + js dependencies

### ISSUE THREAD

**Issue by jmcouffin** [eirannejad/pyRevit#1133]
**Describe the bug**
When using preflight to generate the report we use the chart.js module to print doughnut charts in the output window. When using the save button of the window, it saves it as html but does not take into account the chart part.

**To Reproduce**
1. run preflight checks
2. Click on 'save' in the output window
3. Open the saved file in chrome
4. no js charts displaying

**Expected behavior**
saving the full content of the output window

**Screenshots**
missing chart in yellow
![image](https://user-images.githubusercontent.com/7872003/105330300-6b83ed80-5bd2-11eb-9323-8eae8f0ec187.png)

**Desktop (please complete the following information):**
 - develop branch

**Comment by eirannejad** [comment]
Huh! Seems like the combination of `defer` and `async` are causing issues. Removing them runs the chart code properly. I'll fix this

`<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" defer="" async="true"></script>`
