### ISSUE TITLE
Shift-Clicking Printing Tool

### ISSUE THREAD

**Issue by onila1987** [eirannejad/pyRevit#1134]
A mysterious arrow (Special Character) suddenly showed up in all my sheet number.  I try doing the Shift-clicking hoping this will remove it but no luck. 

Error Messege:
ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:Sheet number is already in use. 
Parameter name: sheetNumber

![image](https://user-images.githubusercontent.com/55870849/105447866-f2b08000-5c29-11eb-9142-baeec4e87a79.png)

**Comment by eirannejad** [comment]
Do you have duplicate sheet numbers in the model?

**Comment by onila1987** [comment]
No duplicate sheets

**Comment by onila1987** [comment]
It seems like this problem is happing with other too. See the link below. Thank you 

https://forums.autodesk.com/t5/revit-architecture-forum/sheet-order-problem-after-printing-with-pyrevit/td-p/9284101

**Comment by casquatch** [comment]
@eirannejad  - We are also having this error, we do have duplicate sheets. Some of our users don't have the issue though, while others do. Anything I can do to help solve this?
