### ISSUE TITLE
Print to AutoDesk Design Review format Dwf and Dwfx using PyRevit Print Sheets.

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#1138]
I would like to be able to print to Autodesk Design Review formats Dwf and Dwfx using PyRevit Print Sheets.

Note: You could add a tick box option to print multiple formats at once i.e.  PDF and Dwfx

Thanking you in advance

Rob

**Comment by eirannejad** [comment]
Does Revit have this functionality in the print tool already? Or the sheets need to be exported?

**Comment by Robbo1234** [comment]
I need the dwfs sheets exported to match the exact parameter
naming convention as the PDFs.

**Comment by Robbo1234** [comment]
Hi Eshan, just wondering has there been any progress on this PyRevit Print Sheet Enhancement?

Thanking you in advance.

Rob

**Comment by Robbo1234** [comment]
Could we open this issue? Thanks
