### ISSUE TITLE
New Keynote Slow to Create

### ISSUE THREAD

**Issue by pushgraphite** [eirannejad/pyRevit#1139]
**Describe the bug**
Hi there,

I've recently started using the pyRevit KN manager and it's fantastic, love the user interface and search functions. However, there's a large problem I'm encountering. When I click on any of the below:

'Edit keynote'
'Add new keynote'
'Create Keynote Key'

...there is a delay of about 5 minutes, give or take ( I haven't timed it, but it's significant enough to disturb workflow and warrant getting up for a cup of tea etc.). Just blue circle spinning. It's bad enough to force me to go back to the old .txt file way of managing keynotes, as every new keynote takes ages to create. Sorry this is my first time posting here, I've had a look through current open and closed issues and couldn't see one similar to this using the search bar.

Cheers

John

```
**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.7.6
 - pyRevit Environment: (I think this is the text expected?)
"==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.6" | Path: "C:\Users\john\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2019.2.2 Hotfix" | Engine: 277 | Path: "C:\Users\john\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\john\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\john\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages"
```

**Comment by eirannejad** [comment]
Hey John. There has been massive bug fixes applied to pyRevit in version 4.8. There is a 4.8-beta5 listed on the Releases section that you can download and try (it's stable). It'd be great of you can test and see if this issue still happens. The new keynote manager also support BIM360

**Comment by pushgraphite** [comment]
Thanks Ehsan! Have updated to 4.8.4, and have tested to see if the issue remains.

It's interesting, the issue repeats the first time I create a new keynote, then after that it appears to run smoothly / as expected? Not sure what to make of that.

**Comment by pushgraphite** [comment]
Ehsan to add to that: I've just been able to 'Create New Keynote' smoothly, but then had a large delay when clicking on 'Create Keynote Key'. I've attached the keynote file in case this helps in any way.
[016 (28 YSA) Project Keynotes.txt](https://github.com/eirannejad/pyRevit/files/5869892/016.28.YSA.Project.Keynotes.txt)

**Comment by pushgraphite** [comment]
OK scratch all the above, the behavior seems to be random as far as I can see. Sometimes a smooth run, then slows down. NO pattern that I can see so far. Apologies for the multiple updates!

**Comment by eirannejad** [comment]
No worries. I'm gonna make a few unrelated changes to the keynote manager this week and will look into the code. My hunch is that it is related to IO speeds. Is the keynote file somewhere on the network drives?

**Comment by pushgraphite** [comment]
Thanks Ehsan. Yes it is, I am using Google Drive File Stream.

**Comment by eirannejad** [comment]
Oh interesting. So you are using GD to sync files between teams. I gotta test this out. I really think this might be IO related. pyRevit creates and deletes a `.lock` file at the same location as the keynote file to this might be triggering the slowness

**Comment by pushgraphite** [comment]
It definitely sounds like GD is the likely culprit. I have issues every now and then using Enscape and as far as the developers can see based on feedback it's also *probably* GD related.

It's possible I could sync between teams in future but currently I'm a sole practitioner, however it's really handy to be able to pick up work wherever I go (eg. on a laptop). I do spend most of my time on my main rig as Revit is a hungry beast, but the flexibility is nice (despite some hiccups every now and then). And I don't have to stress if my hard drive just bricks itself (which has happened in the past).

It would be great if you could test it out, maybe for now I'll use a keynote file that's local.

As an aside, I've started exploring options around running Revit through AWS or Azure (Workspot and Frame are examples, Daas IaaS and so on, it's a real rabbit hole) to avoid the need for large investments in future hardware should the need to expand arise, but it seems at this point cloud based workflows are more suited to larger corporations and not small companies. Would keynoting using pyRevit work in this environment?

**Comment by pushgraphite** [comment]
Hi Ehsan,

Update: is there any way I can ensure that the Revit -> Keynote Manager -> Revit process is fully local and completely separated from Google Drive File Stream? I ask as I believe I'm working fully locally, but the delays are still happening.

**Comment by eirannejad** [comment]
@pushgraphite Just make sure the keynote text file is somewhere on your local drive. Drop it inside C: drive or somewhere that is not being synchronized to another place

**Comment by eirannejad** [comment]
Closing this for now since the slowness seems to be an IO issue with where the file is stored

**Comment by pushgraphite** [comment]
All good, thanks Ehsan.

Keep up the good work
On 23/03/2021 10:07:57 am, Ehsan Iran-Nejad ***@***.***> wrote:
Closing this for now since the slowness seems to be an IO issue with where the file is stored
