### ISSUE TITLE
Keynote Manager sticky lock file

### ISSUE THREAD

**Issue by martinservold** [eirannejad/pyRevit#1141]
**Describe the bug**
If a user has the keynote file open in Microsoft Word and a user tries to access the Keynote Manager at the same time it will give you a Read timeout (expected), but will also create a .lock file even though it failed to read. 

**To Reproduce**
Open .txt file in Word. 
Try to open with Keynote Manager
Creates .lock file
Close Word
Lock file still exists

**Expected behavior**
It should not create (or remove the created) lock file if it gets a Read Timeout.

**Desktop (please complete the following information):**
Windows 10
Word 2016
Pyrevit 4.7.6

**Comment by martinservold** [comment]
Exception is here:
pyRevitLabs/pyRevitLabs.DeffrelDB/DataStore.cs
Line 440

Maybe a release call before this exception is thrown?

**Comment by martinservold** [comment]
The lock file doesn't seem to show up if the file is successfully opened via Keynote Manager.
The lock file does not prevent someone from opening the file in Word while it exists (if I leave the sticky version it creates). 
If someone does open the file in word after you've opened in in Keynote Manager, it will create the sticky lock file if you try to close the Keynote manager (with the red X or the Update Model button).

As it stands if we were going to use this the whole team would have need to be on board.

**Comment by eirannejad** [comment]
Ok great find. I can get this fixed. But just to be clear, the whole point of having a keynote manager was to stop using Word for editing keynotes. Is this still a thing?

**Comment by martinservold** [comment]
Right now 100% of our users are using Word for editing the keynote file, we even have a script to open up the keynote file in word so you don't have to go find it (and I'm sure not 100% of our users use this). So there would definitely be a transition period where we would run into issues like these.
On a side note, our keynote files are saved in ANSI so in order to upgrade them I have to manually save them to UTF-8 before converting them.

**Comment by eirannejad** [comment]
Okay great points. I'll work on these:
- [ ] Be able to read ANSI keynote files and automatically convert to UTF-8
- [ ] Fix orphaned lock file issue

**Comment by eirannejad** [comment]
Fixed the ANSI convert issue but the lock file is gonna take time. I need to redesign the storage system. It is mostly an issue of file sync systems and when other apps are used to edit the keynote file.
