### ISSUE TITLE
Keynote Manager icons disappear while in Revit in French

### ISSUE THREAD

**Issue by jmcouffin** [eirannejad/pyRevit#1142]
**Describe the bug**
Icons are missing in the keynote manager add cat and add keynote windows when in French Revit

**To Reproduce**
1. Launch revit in French
2. try adding category and keynote in the keynote manager

**Screenshots**
french
![image](https://user-images.githubusercontent.com/7872003/105872478-c1a1c800-5ffa-11eb-840e-89b654bff1b8.png)
english
![image](https://user-images.githubusercontent.com/7872003/105872485-c49cb880-5ffa-11eb-97dc-5d093423d538.png)

**Additional context**
develop branch

**Comment by eirannejad** [comment]
Can not replicate this issue. Closing for now until we have more info

![Screen Shot 2021-03-22 at 2 13 43 PM](https://user-images.githubusercontent.com/8197916/112059238-d2f9e300-8b18-11eb-9cf0-58c8ff859da7.png)
