### ISSUE TITLE
Keynote Manager setup issue BIM 360

### ISSUE THREAD

**Issue by cattaca248** [eirannejad/pyRevit#1143]
Our office went to test the Keynote Manager in BIM 360. 
First I opened the BIM 360 hosted Revit file.
Then I clicked the Keynote Manager button.
I was able to see and alter keynotes as expected. ![2021-01-26_09h16_13](https://user-images.githubusercontent.com/78040384/105880638-71a21180-5fb8-11eb-8f3d-82f987452926.png)
Then I had a colleague open the same BIM 360 hosted Revit file.
Then I synchronized my version of the BIM 360 hosted Revit file.
Then my colleague did the same.
Initially, he could see all the keynotes in the Keynote Manager but then when reopening the Keynote Manager he could no longer see the project user keynotes and instead saw a blank sent of 10 misc. keynotes.
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/78040384/105880627-6b139a00-5fb8-11eb-8a56-402b3089748f.png)

I know there is a working file created by Keynote Manager and maybe this is just user error, I believe there was possibly some instruction I overlooked when the Keynote Manager was first initialized. 

Thanks in advance.

**Comment by eirannejad** [comment]
Fixed and will be published with next release

**Comment by eirannejad** [comment]
@cattaca248 Make sure the category selector says "All Categories" if you want to see all the keynotes. The screenshot is showing `00-Misc...` so only the keynotes under that category are shown

**Comment by cattaca248** [comment]
Thank you, that was the issue! Working great now.

**Comment by eirannejad** [comment]
Thank you!
