### ISSUE TITLE
Pyrevit fails to install with error 0, only half installations takes place 

### ISSUE THREAD

**Issue by rry858** [eirannejad/pyRevit#1145]
While creating Application Package for Pyrevit Software, its getting only partial installed through DSM Console tool (script). It fails with error 0. 
![image](https://user-images.githubusercontent.com/71002352/106445792-775e9200-64a5-11eb-8607-229e72ad374d.png)
Above command is used, where only pyrevit folder gets installed and not the main exe's folder as shown in the next image 
![image](https://user-images.githubusercontent.com/71002352/106446579-6cf0c800-64a6-11eb-8d77-82f17dabaf92.png). is there any way this issue can be solved?

**Comment by eirannejad** [comment]
Checkout this guide please

https://www.notion.so/pyRevit-For-Teams-ddc6c312d6f6488691eed2ec7704fd97

pyRevit uses AdvancedInstaller to generate the installer. See more info about the command line options here

https://www.advancedinstaller.com/user-guide/exe-setup-file.html

**Comment by eirannejad** [comment]
4.7.6 installer has Powershell scripts embedded inside it. So if the target machine has security switches that prevents running scripts, the install is going to fail. This has been removed in the 4.8 version

**Comment by eirannejad** [comment]
Closing this since it is more of a question than a bug but please continue the thread

**Comment by rry858** [comment]
Where can I get  4.8 ver installer?

**Comment by eirannejad** [comment]
https://github.com/eirannejad/pyRevit/releases/tag/v4.8.5
