### ISSUE TITLE
CPython does not let me use multiple inheritance

### ISSUE THREAD

**Issue by amastrobera** [eirannejad/pyRevit#1146]
#### Describe the bug

The same set up, and module structure we used in [Issue 1144](https://github.com/eirannejad/pyRevit/issues/1144).

In `generic_utils` I override the `IFailurePreProcessor` - mostly to be able to use the `object` in python and pass a logger to it via the constructor. 

```
class OvrFailHandler(DB.IFailuresPreprocessor, object):
    def __init__(self, logger=generic.get_logger()):
        self.logger = logger
    def PreprocessFailures(self, failuresAccessor):
        self.logger.debug("> PreprocessFailures")
        ... etc etc 

```

Apparently this CPython+IronPython coexistence doesn't like it. I get this error: `failed generic_utils import : cannot use multiple inheritance with managed classes`. 

What should I do ?

**Comment by eirannejad** [comment]
@amastrobera This is not a bug. Seems like you are trying to use python like it is another language. You do not need to set `object` as a class parent. ALL types in Cpython are automatically derived from `object`

**Comment by eirannejad** [comment]
See this for example
https://github.com/eirannejad/pyRevit/blob/92cb346eece706db810468984b3fa8564f14b16c/pyrevitlib/pyrevit/revit/db/failure.py#L29

**Comment by amastrobera** [comment]
I too tried single inheritance, and that does the trick. 

I don't know why with IronPy interpreter it was also working with multiple inheritance .... but for now it's ok.

**Comment by eirannejad** [comment]
IronPython uses python specification v2.* Under this older python, not all objects are `object` unless specifically classified
