### ISSUE TITLE
CPython does not understand Revit API classes

### ISSUE THREAD

**Issue by amastrobera** [eirannejad/pyRevit#1147]
**Describe the bug**

I have this set up `using Revit 2021.2, pyrevit 2.7.7, cpython 3.7.2, IronPython 2.7.3`.

I think that `_script.py` modules loaded with `#! python3` make us lose the properties of RevitAPI elements in IronPython.

***Bug 1: .GetType() vs isinstance()***

I used to be able to compare elements like this in IronPython: 
```
ref = uidoc.Selection.PickObject(UI.Selection.ObjectType.Face, "Select a planar face")
face = elem.GetGeometryObjectFromReference(ref)
if face.GetType() != DB.PlanarFace:
    raise Exception("%s (%d) is not a planar face" % (ref.Name, ref.Id.IntegerValue))
```
If this module (or the launching `_script.py`) is run with `#! python3` I must check with isinstance:
```
# ... same as above
if not isinstance(face, DB.PlanarFace):
    raise Exception("%s (%d) is not a planar face" % (ref.Name, ref.Id.IntegerValue))
```

***Bug 2:  \_\_enter\_\_ not defined for DB.Transaction element***
I am making a transation in a `_script.py` run with `#! python3`. 

```
try:
        with DB.Transaction(doc, "do something") as t:
            t.Start()
            try:
               # my actions 
                t.Commit()
            except Exception as ex:
                print("failed transaction because of '%s'" % ex)
                t.RollBack()
except Exception ex2:
    print("hell raised by: %s")
```

getting `hell raised by: __enter__` error. 

If I remove the with-statement all goes well. 

```
try:
     t = DB.Transaction(doc, "do something")
     t.Start()
     try:
         # my actions 
         t.Commit()
     except Exception as ex:
         print("failed transaction because of %s" % ex)
         t.RollBack()
except Exception ex2:
    print("hell raised by: %s")
```
I wouldn't like to change my code completely, because `with` gave me a good flow control.

***Bug 3: operator- in DB.XYZ***

Same situation: my `_script.py` launched with `#! python3`. 

My code is this:
```
try:
    a = DB.XYZ(1.0, 2.0, 0.0) # notice that the CPython / IronPython coexistence 
                                           # forces me to pass doubles to the constructor or the point will be null
    b = DB.XYZ(2.0, 1.0, 0.0)
    c = b - a
    print("b-a = %s" % c)
except Exception as ex:
   print("hell raised by %s" % ex)
```
The error is `hell raised by TypeError : unsupported operand type(s) for -: 'XYZ' and 'XYZ'`

**Comment by eirannejad** [comment]
@amastrobera `with` is a python construct. It expects the type in front of it, `DB.Transaction` in your example, to implement the `__enter__` and `__exit__` magic methods. But `DB.Transaction` is a type from Revit API and is not designed to work specifically with python so it does not implement these methods.

This is the correct approach:

```python
 t = DB.Transaction(doc, "do something")
 try:
     t.Start()
     # my actions 
     t.Commit()
 except Exception as ex:
     print("failed transaction because of %s" % ex)
     t.RollBack()
```

In IronPython I use a python type that I have created that wraps the `DB.Transaction`. [See code here](https://github.com/eirannejad/pyRevit/blob/92cb346eece706db810468984b3fa8564f14b16c/pyrevitlib/pyrevit/revit/db/transaction.py#L18)

**Comment by amastrobera** [comment]
I tried `from pyrevit.revit import db` and I got this error on execution of that plugin.

```
CPython Traceback:
TypeError : object does not implement IExternalEventHandler
 File "C:\Users\angel\developement\revit-plugins\pyRevit\extensions\pyRevit.extension\pyRevit.tab\Creator.panel\Road.pulldown\StraightRoad.pushbutton\create_road_straight_script.py", line 23, in <module>
from pyrevit.revit import db
 File "C:\Users\angel\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\revit\__init__.py", line 24, in <module>
 from pyrevit.revit import events
 File "C:\Users\angel\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\revit\events.py", line 101, in <module>
 FuncAsEventHandler(unregister_exec_handlers, purge=False)
```

**Comment by eirannejad** [comment]
The intent has always been to modify the existing python code to run on cpython as well. The issue is that the cpython engine connecting the cpython runtime to dotnet environment is also under development and is not as advanced as IronPython. I'd highly suggest sticking with IronPython and use cpython Only when you need cpython packages. for now. I'm actively working on the pythonnet implementation so we'll hopefully see improvements in the future
