### ISSUE TITLE
Doc string search pattern too gready

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#115]
![reportthisbug](https://cloud.githubusercontent.com/assets/9513968/16930844/f41f939a-4d0b-11e6-8ea1-1bac2ab819f2.png)

.py looks like this. author and version is getting pulled as shown on image.
__doc__ = "Apply Correct Tag for Rooms Depending on Plan Type"
__author__ = 'gtalarico@gmail.com'
__version__ = '0.0.1'

**Comment by eirannejad** [comment]
Auo! Interesting. Okay I'll fix this soon. Thanks!

**Comment by eirannejad** [comment]
Resolved. I think this was the easiest bug ever resolved in any software!!! Just added one single character and bug is gone! :)))

**Comment by gtalarico** [comment]
What did you add?
$  to catch the end of the line?
I tried to fix it for you but I couldn't understand what was going on...
Hehe

Usually regex is not multiline unless you explicitly want that...

Gui Talarico
[ mobile ]

**Comment by eirannejad** [comment]
^ to catch the start. So if there is nothing between the start of the line and the ' character other than spaces, then it'll treat this line as the docstring continuation
