### ISSUE TITLE
pyRevit Tab Coloring - More contrasting color scheme

### ISSUE THREAD

**Issue by wfinley87** [eirannejad/pyRevit#1150]
The current colors baked into this tool are too similar to immediately differentiate....

![image](https://user-images.githubusercontent.com/67510339/106667489-98d78080-656e-11eb-9276-3ca68b918481.png)
Some ideas:

1.	Change the colors to be more contrasting and unique. Perhaps the first 5 colors are Blue, Yellow, Red, Green, then Purple.
2.	Ideally, **Color the whole tab.** Right now it is only a single pixel width line at the top of the tab. If this was implemented, the current colors may not need to change at all.
3.	Give users the option to select their own colors from the settings dialogue.

![image](https://user-images.githubusercontent.com/67510339/106667313-629a0100-656e-11eb-843c-18046af16fec.png)
- Grey [808080], barely noticeable on the background of the default Revit tab color which is also grey.
- Yellow [f39c12], this one is ok, it stands out.
- Brown [8b4513], difficult next to the yellow from the default grey tab.
- Navy [2c3e50], difficult next to the grey.

**Comment by eirannejad** [comment]
@wfinley87 Coming on the next release

![Screen Shot 2021-03-18 at 5 04 07 PM](https://user-images.githubusercontent.com/8197916/111713013-fb799880-880b-11eb-92d1-6f268e73daba.png)

Here are the styling options. Let me know if you can think of more

![Screen Shot 2021-03-18 at 5 04 44 PM](https://user-images.githubusercontent.com/8197916/111713066-177d3a00-880c-11eb-859c-4dd726d2ada4.png)

**Comment by CHBIV007** [comment]
Dope! Cant wait for this update!!!

**Comment by wfinley87** [comment]
@eirannejad This is amazing! Thank you so much for your dedication to this project.

**Comment by eirannejad** [comment]
Implemented and will be published with next release

**Comment by apsis0215** [comment]
@eirannejad  - is there a way to color the whole tab instead of just the edge? (Like what parallax team did https://www.parallaxteam.com/tabbed-views/ ?)

**Comment by eirannejad** [comment]
Yeah use the Background Fill option 🧐

**Comment by RevitIRL** [comment]
I notice the "Keep Open Tabs Sorted By Document" checkbox is disabled. **Is this for a future feature?** or is there a different way to set it?

**Do you have documentation/examples on how the "By Filter" option is supposed to be used?** I was thinking to use it to make our Project Template tabs red by using \w+.rte for the filter. I tried .rte and just rte. I noticed the default was Project 1 (with a space) so I also tried Project1 (which is actually Revit's first new project name), but nothing worked...

**Comment by eirannejad** [comment]
The filter works based on the tab title not the project file name but that something I can certainly add.

**Comment by c4m7m6** [comment]
@eirannejad did you ever end up adding a way to filter by model/file name? That would be super helpful.
