### ISSUE TITLE
CPython error

### ISSUE THREAD

**Issue by arielsemik-warbud** [eirannejad/pyRevit#1153]
**Describe the bug**
Hi I would like to use CPython but I have problems. I use comand "pyrevit caches clear --all" and it fixed error but on a moment only. Now it come back :(
When I start my script is error as below
![obraz](https://user-images.githubusercontent.com/75621549/106860812-32b14180-66c5-11eb-9253-50373b90b914.png)

my code for import:

```python
#! python3

from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *
from System.Collections.Generic import List
from Autodesk.Revit.UI import TaskDialog
doc = __revit__.ActiveUIDocument.Document
uidoc = __revit__.ActiveUIDocument
selected 	= 	uidoc.Selection.GetElementIds()
currView 	=	uidoc.ActiveView
```

Im using win10 pyrefit 4.8.4

**Comment by eirannejad** [comment]
Try this code and see if it still breaks

```python
#! python3

from Autodesk.Revit import DB
from Autodesk.Revit.DB import Structure as ST
from System.Collections.Generic import List
from Autodesk.Revit.UI import TaskDialog
uidoc = __revit__.ActiveUIDocument
doc = None
if uidoc:
    doc = __revit__.ActiveUIDocument.Document

selected 	= 	uidoc.Selection.GetElementIds()
currView 	=	uidoc.ActiveView
```

**Comment by arielsemik-warbud** [comment]
Thank you for respnse but still the same. Issue is irregularly :(
