### ISSUE TITLE
Install Fails

### ISSUE THREAD

**Issue by timry** [eirannejad/pyRevit#1157]
When running the installer it runs into Modify mode: when running any of the options it fails and rollsback:

![image](https://user-images.githubusercontent.com/50882655/106944238-56d84700-66f4-11eb-8a1a-087ef4c07725.png)

Action ended 14:08:03: ProgressDlg. Return value 1.
MSI (c) (44:E4) [14:08:03:412]: Note: 1: 2262 2: AI_AppSearchEx 3: -2147287038 
MSI (c) (44:E4) [14:08:03:412]: Note: 1: 2205 2:  3: AI_TempFile 
MSI (c) (44:E4) [14:08:03:412]: Note: 1: 2228 2:  3: AI_TempFile 4: SELECT `Property` FROM `AI_TempFile` 
MSI (c) (44:E4) [14:08:03:412]: Note: 1: 2262 2: AI_PreRequisite 3: -2147287038 
MSI (c) (44:E4) [14:08:03:412]: Note: 1: 2205 2:  3: AI_XmlLocator 
MSI (c) (44:E4) [14:08:03:412]: Note: 1: 2228 2:  3: AI_XmlLocator 4: SELECT `Property` FROM `AI_XmlLocator` 
MSI (c) (44:E4) [14:08:03:419]: Note: 1: 2205 2:  3: AI_ChainedPackage 
MSI (c) (44:E4) [14:08:03:419]: Note: 1: 2228 2:  3: AI_ChainedPackage 4: SELECT `ChainedPackage` FROM `AI_ChainedPackage` 
MSI (c) (44:E4) [14:08:32:575]: Doing action: FatalError
Action start 14:08:32: FatalError.
Action ended 14:08:33: FatalError. Return value 1.
MSI (c) (44:E4) [14:08:33:853]: Doing action: AI_SHOW_LOG
Action start 14:08:33: AI_SHOW_LOG.
MSI (c) (44:38) [14:08:33:857]: Invoking remote custom action. DLL: C:\Users\tr\AppData\Local\Temp\MSI4BEE.tmp, Entrypoint: LaunchLogFile
Action ended 14:08:33: AI_SHOW_LOG. Return value 1.
MSI (c) (44:E4) [14:08:33:952]: Doing action: FatalError
Action start 14:08:33: FatalError.
Action ended 14:08:33: FatalError. Return value 2.
MSI (c) (44:28) [14:08:33:961]: Destroying RemoteAPI object.
MSI (c) (44:B4) [14:08:33:964]: Custom Action Manager thread ending.
=== Verbose logging stopped: 04-Feb-21  14:08:33 ===

**Comment by eirannejad** [comment]
Ok. Try uninstalling all previous versions and then use the `pyrevit-doctor` to fix the left over stuff. See this https://github.com/eirannejad/pyRevit/issues/1045#issuecomment-724922950

**Comment by eirannejad** [comment]
Fixed and will be published with next release
