### ISSUE TITLE
Install Issue with Revit 2016

### ISSUE THREAD

**Issue by deivand** [eirannejad/pyRevit#1158]
**Describe the bug**
Ran installer and repaired installation. All work on Revit 2018 but not Revit 2016. 

Ran the below command and issue persists.

`pyrevit attach master 277 --installed`

**To Reproduce**
Ran installer and repaired installation. All work on Revit 2018 but not Revit 2016

**Expected behavior**
Installed pyRevit 4.8.5.0. Revit 2018 is able to load pyRevit but 2016 shows the below error (screenshot below)

**Screenshots**
![image](https://user-images.githubusercontent.com/78567601/106964119-e08d1200-66fe-11eb-975e-2f166c029ac6.png)

**Desktop :**
Microsoft Windows 10 [Version 10.0.19041]
%APPDATA%: "C:\Users\user\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.5.0

**Comment by eirannejad** [comment]
Ok. Try replacing `pyrevit/loader/sessioninfo.py` with this one and load in 2016. Seems like it can't find the attachment.

[sessioninfo.py.zip](https://github.com/eirannejad/pyRevit/files/5934549/sessioninfo.py.zip)

**Comment by deivand** [comment]
That worked. Thanks!
