### ISSUE TITLE
Close all views except selected

### ISSUE THREAD

**Issue by monsieurhannes** [eirannejad/pyRevit#1160]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a workflow-improvement. To be honest I thought I saw it somewhere, but I can't find it now. I often have tons of tabs open and the only way to close them quickly is to close ALL tabs at once, including tabs of families or other projects.

**Describe the solution you'd like**
It would be great if there is a button which closes all view-tabs of the current project, except the major views that are specified in either a list, schedule or a classic pyrevit-list that pops up.
One "problem" I can see with that solution is that there are different users with different priority views. I don't know how to solve that problem...

**Describe alternatives you've considered**
I thought I saw it somewhere and maybe it's already implemented, if so you can delete this issue.

Currently I'm not able to investigate a solution, but generally I'm interested in helping with coding!

**Comment by thumDer** [comment]
What I can think of is a SelectListItem form, that shows the currently open views for  the project, and the user can check the ones that should be kept, and all the unchecked will be closed. It is quite easy to implement.

**Comment by thumDer** [comment]
Here you go:

```
from pyrevit import script, forms, revit, DB

output = script.get_output()
logger = script.get_logger()


doc = revit.doc
uidoc = revit.uidoc

uiviews = uidoc.GetOpenUIViews()
views = [doc.GetElement(uidoc.ViewId) for uidoc in uiviews]

list_items = [forms.ViewOption(view) for view in views]

views_to_keep = forms.SelectFromList.show(list_items,
                                          multiselect=True,
                                          title='Select views to keep open')

if not views_to_keep:
    script.exit()

views_to_close = filter(
    lambda x: x.ViewId.IntegerValue not in \
    [view.Id.IntegerValue for view in views_to_keep],
    uiviews)

for uiview in views_to_close:
    uiview.Close()
```

**Comment by monsieurhannes** [comment]
Hej, 
Thank you for the fast reply and even providing the code @thumDer!
I took you code and created a PR with a (temporary) icon and so on.
One thing that I stumbled upon is that it only takes the current project and not the tabs of all open projects/families. I'm quite new to pyRevit and Revits API, but happy to investigate further. I could even imagine having a dropdown icon with the option to close ALL tabs of the **current** project, leaving the others open, one that only closes sheets, one that only closes views and so on. I just wanted to share my progress, there is more to come.

**Comment by thumDer** [comment]
I don't wanna upset you, but unfortunately it is currently not possible, to get the open views for all open projects, only for the active uiDoc. You are also not able to close all views of a project, because the last one will throw an exceptions, but that would be equivalent to close the doc itself, which is only possible for background uidocs. You can only get the currently active uiDoc from the uiApp, so thats another deadend. You would need a lot of event handlers, or hooks in pyRevit to track all the opened and closed documents (uiDocs) to achieve such thing but thats quite a pain in the ass IMHO.

**Comment by eirannejad** [comment]
Merged and will be published with next version. Thank you @monsieurhannes !
