### ISSUE TITLE
pyRevit Python Shell?

### ISSUE THREAD

**Issue by GertjanVDBVK** [eirannejad/pyRevit#1161]
**Is your feature request related to a problem? Please describe.**
Just learned that the maintainer of revit python shell is throwing in the towel. Reasons not entirely clear, but as of right now, it seems that RPS is on its way out.
It's also slightly annoying that the RPS doesn't work with pyrevit internally.

**Describe the solution you'd like**
Could be a great opportunity to interweave pyrevit with a shell window? Could be great for library & code testing as well.

**Describe alternatives you've considered**
Yeah I've considered doing this myself, still am, might take it up somewhere in the future, but time constraints and whatnot..

**Comment by jeremytammik** [comment]
Yes, I would love this feature. Does any other Revit Python read-eval-print loop exist at all? 

Cf. also [RPS issue #111](https://github.com/architecture-building-systems/revitpythonshell/issues/111) and the [RevitRubyShell](https://github.com/hakonhc/RevitRubyShell).

**Comment by eirannejad** [comment]
Not for Revit AFAIK. I'm working on it :D

**Comment by jeremytammik** [comment]
yay, good news!

**Comment by ivan-modelical** [comment]
Very good news Ehsan!

**Comment by GertjanVDBVK** [comment]
In the meantime, I'm trying to help daren get a RPS out for 2021 to fill the void and as a bit of a sendoff.
So perhaps, in the meantime that could be a short-term solution.

**Comment by jeremytammik** [comment]
quo vadis RPS? or pyRevit Python Shell? 

https://forums.autodesk.com/t5/revit-api-forum/2022-revit-python-shell/m-p/10348780

**Comment by eirannejad** [comment]
Built and released RPS for Revit 2022
https://github.com/architecture-building-systems/revitpythonshell/blob/master/Output/2021.06.20_Setup_RevitPythonShell_2022.exe

**Comment by jeremytammik** [comment]
Brilliant, thank you! I tried to add a link to execute it in the README, but it is not complete yet: https://github.com/architecture-building-systems/revitpythonshell/pull/116.
