### ISSUE TITLE
Extension missing tabs 

### ISSUE THREAD

**Issue by Alan-TEECOM** [eirannejad/pyRevit#1164]
I recently upgraded pyRevit to 4.8.5 and notice some pyApex/pyRevitPlus extension tabs are no longer visible from Revit.

I'm pretty sure I didn't disable those tabs myself and I tried reinstall pyRevit and reinstall these extensions, still missing. 

Is there a reason those tabs are no longer available, is there a way to bring them back? I believe they were available and working fine in 4.5 or 4.6.

missing selection panel from pyApex
![image](https://user-images.githubusercontent.com/25993229/107417569-9b842980-6aca-11eb-809c-03d519fc9cd7.png)

missing smart align from pyRevitPlus
![image](https://user-images.githubusercontent.com/25993229/107417405-68419a80-6aca-11eb-90a3-8a712ec14736.png)

thanks a lot!

**Comment by eirannejad** [comment]
Interesting. Do you get any errors or warning on the load time? I'll test out these two

**Comment by Alan-TEECOM** [comment]
No errors of any kind.

**Comment by eirannejad** [comment]
Ok found the issue. The new pyRevit versions have deprecated the `.stack2` and `.stack3` bundles in favor of simpler `.stack` bundles. There has been a lot of deprecation messages about this but seems like these two extensions haven't updated yet. Go through the extension files and rename any bundle that ends in `.stack3` to `.stack`

I will send a PR to these repos for this change

**Comment by Alan-TEECOM** [comment]
Yes it worked, now I see it in 4.7 release note, thanks for the explanation. 👍

**Comment by eirannejad** [comment]
Created PRs to both these extensions with the fix
- https://github.com/apex-project/pyApex/pull/9
- https://github.com/gtalarico/pyrevitplus/pull/27

**Comment by mawdesign** [comment]
Can this page also be updated? I made the same mistake by working through the instructions there.
https://pyrevit1.readthedocs.io/en/latest/creatingexts.html
