### ISSUE TITLE
/exenoui showing ui

### ISSUE THREAD

**Issue by MabTheOne** [eirannejad/pyRevit#1166]
**Describe the bug**
Trying to install pyRevit from Windows 10 command line interface: 
pyRevit_4.8.5_signed.exe \exenoui

The switch doesn't work as I'm still receiving the installation window requiring user interaction (Next, EULA, etc.). 

**To Reproduce**
1. run the following command from an elevated command prompt: pyRevit_4.8.5_signed.exe \exenoui

**Expected behavior**
Running the command should install pyRevit 4.8.5 silently on my Windows computer. An all user switch would be awesome!

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - pyRevit 4.8.5
 - pyRevit Environment: pyRevit wasn't installed on my test machine. 

**Additional context**

**Comment by GertjanVDBVK** [comment]
Just out of curiosity, are you using the pyRevitCLI installer?

**Comment by eirannejad** [comment]
Try using these switches `/exenoui /qn`

**Comment by MabTheOne** [comment]
Gertjan, I am currently not using the pyRevti CLI installer but might have to. 

Thanks Ehsan, using /exenoui /qn actually installed pyRevit within the current user account. 
Is it possible using the pyRevit_4.8.5_signed.exe installer to install machine wide for all users as well?

**Comment by eirannejad** [comment]
@MabTheOne Are you running the installer as a system user? Doesn't it automatically install under %PROGRAMDATA%?
