### ISSUE TITLE
Re-Categorize Keynote

### ISSUE THREAD

**Issue by Architectuur** [eirannejad/pyRevit#1168]
We can re-categorize a category and re-key a keynote, but can we re-categorize a keynote? I want to change the keynote parent.

In the snip below I have changed a 03.xx keynote to 04.xx. I want to change this keynote's category to 040000 DIVISION 04 - MASONRY.

![Recategorize Keynote](https://user-images.githubusercontent.com/69218770/107835438-bc60af00-6d56-11eb-99bb-61cb4c9a0fee.JPG)

This Keynote Manager is becoming above and away the best keynote manager available.

**Comment by eirannejad** [comment]
- [ ] Add option to **Move** keynote

**Comment by eirannejad** [comment]
Fixed and will be published with next release 

![Revit_XJwEZrgulh](https://user-images.githubusercontent.com/8197916/112034160-6de3c480-8afb-11eb-8640-3599327b782f.png)

**Comment by richardvjr** [comment]
Ehsan thanks for this update been testing it out with the new 4.8.7. This is helping folks trust this more. 

I think the OP was asking about moving the keynote parent , which is what I'm looking for as well.
In the screenshot below you'll see there's a 08 80 00 child keynote in the 08 44 23 parent that we want to move to the 08 80 00 Parent below (not in screenshot).
![image](https://user-images.githubusercontent.com/53799098/113617021-dfeff980-9623-11eb-8ed7-70f4add62f49.png)

After this screenshot was taken we used the "Change Category" within the same Category and it moved it out of the parent and placed it in the Overall Category.

**Comment by eirannejad** [comment]
@richardvjr So when you click on "Change Category", it should give you a list of categories to choose right?

**Comment by eirannejad** [comment]
Oh got it! You want to move a sub-keynote to another keynote. OK I'll add this

**Comment by eirannejad** [comment]
- [ ] Allow changing any keynote parent type: Figure out how the UI should work. A whole new keynote tree should be shown to allow user to select the parent category or keynote. Some restrictions need to apply for keynotes that are locked, etc.

**Comment by Architectuur** [comment]
So this isn't working for some reason. I get an error (figure 1) when I rekey the keynote. It will then change the keynote to the new key but not update the existing keynotes that are placed in the model. I then have to go find all of the existing keynotes and update them to the new rekeyed keynote number. I haven't changed anything that I am aware of. 

Figure 1:
![image](https://user-images.githubusercontent.com/69218770/126538290-29d6bf31-1a04-4beb-b98d-62f27a49857c.png)
