### ISSUE TITLE
Discussion: scripts organization and subfolders

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#117]
Sometimes it's nice to be able to organize scripts into subfolders to contain all related files.
(DB, Project, Selection, etc) 
Subfolder would make it easier to view/manage related files by grouping into folders instead of filename-association.

I wanted to proposed possible potential ideas for discussion:
**Idea 1**
 __init__.py searches TABDIR recursively (os.walk instead of os.listdir), files within any subfolder are found recursively, but the folder structure/name is ignored in terms of how files are interpreted.

>     for root, subfolders, files in os.walk(dir):
>        # returns tubple (root_fullpath, list of subfolders, list of files)
>         for file in files:
>             if file.endswith('.py') or file.endswith('.png'):
>                     #process file as usual

**Idea 2*
File discovery is reworked to take subfolder into consideration for how to organize.
This would be more work to implement as would require larger code revision, 
IMHO but make it easier to create/manage script names. You can just move scripts around to move them between panels or buttons like you do with Tabs.

+ PyRevit/
+++0000_Modify/

++++ 0000_PullDownPutton_Dimension/
+++++ icon.png
+++++ addPlusMinuesToDim.py
+++++ otherscripts.py

++++ 0001_PullDownPutton_Draft
+++++ icon.png
+++++ bringToFrontSelected.py

+++0001_OtherSubPanelName/
++++ 0000_ButtonNameOrPullDownName/
+++++icon.png
+++++nameofscript

![image](https://cloud.githubusercontent.com/assets/9513968/16957026/b88d9ece-4da8-11e6-8206-f0b47a1249ff.png)

Idea 2:
![image](https://cloud.githubusercontent.com/assets/9513968/16957129/37c06d5c-4da9-11e6-99f3-c4436f40270f.png)

**Comment by gtalarico** [comment]
Sorry, mean to name issue :
Discussion: scripts organization and subfolders

**Comment by eirannejad** [comment]
Coming up in version 3.0.0
