### ISSUE TITLE
Print name issue

### ISSUE THREAD

**Issue by david939david** [eirannejad/pyRevit#1170]
**Describe the bug**
I want to set name rule to pdf's, but there is an issue. As I understand it when I use: {name}-{tblock_param:Print Setting}_{rev_number}.pdf it should read Print Setting (which was created for variable sizes print and works fine) from the titleblock but for every sheet, it is empty. 

I've checked and it reads something from parameter "szerokość" which is the width, and "wysokość" which is the height, but I don't know what. Width is 500mm and it reads it as 1.64041994751, but for some other sheet sizes it seems to be proportional, so maybe it's a different unit.

BTW. Thank you for guide after choosing variable sizes - it's very handy! ;)

**Desktop:**
 - OS: Windows 10
 - pyRevit Version 4.8.4

**Comment by eirannejad** [comment]
Yeah this is potentially a bug. I'll take a look. Thanks for reporting this

**Comment by eirannejad** [comment]
Fixed and will be published with next release

**Comment by david939david** [comment]
Great!
