### ISSUE TITLE
A template in a DB entry is not getting created 

### ISSUE THREAD

**Issue by RonenEvenTzur** [eirannejad/pyRevit#1171]
See information in this Notion link: 
https://www.notion.so/Bug-report-Notion-A-template-in-a-DB-entry-is-not-getting-created-3732f3da3f5a4ec5bddadb0e9b386249

**Comment by eirannejad** [comment]
@RonenEvenTzur Would you mind pasting the bug report here? Not everyone has access to a notion page. This is important for others to be able to search and find similar bugs. Thanks

**Comment by RonenEvenTzur** [comment]
Sory, I made the page public for everyone now.

**Comment by eirannejad** [comment]
@RonenEvenTzur This seems to be related to Notion itself. Why are you posting it here? How's this related to pyRevit?
