### ISSUE TITLE
Can't install pyRevit 4.8.5_signed on Revit 2019

### ISSUE THREAD

**Issue by MoT1004** [eirannejad/pyRevit#1174]
When i run the installation file the installation abbort and i become the following log

[MSIE268.LOG](https://github.com/eirannejad/pyRevit/files/6002047/MSIE268.LOG)

I've tried it also with admin rights with the same result.

I am working on a windows10 machine normaly no admin rights.

**Comment by Muhammedingo** [comment]
Try running the installation file with admin rights that did it for me.

**Comment by MoT1004** [comment]
Tried to install it with admin but still the same error.

**Comment by eirannejad** [comment]
Okay seems like the installer is creating a bad path internally. Does it roll back and remove the installed files or you have stuff left under `C:\Users\Tom *******\AppData\Roaming\pyRevit-Master\`?

**Comment by kkoens** [comment]
`I don't know if this is a related issue, but every time I try opening Revit, Revit won't open past the splash screen, and shuts down.
[pyRevit_2019_e4d3bdc91c6f9557_PyRevitLabs.PyRevit.Runtime.log](https://github.com/eirannejad/pyRevit/files/6109170/pyRevit_2019_e4d3bdc91c6f9557_PyRevitLabs.PyRevit.Runtime.log)
`

**Comment by NielBenade** [comment]
I am having a similar problem.

I have tried to run as and not as administrator
I have tried to uninstall previous version (4.6.19) thru add/remove programs but it does not go past the allow changes popup.
I have tried running pyrevit-doctor
When I install I receive the following popup and log:
[MSIA7B9.LOG](https://github.com/eirannejad/pyRevit/files/6115392/MSIA7B9.LOG)
![2021-03-10_13h23_17](https://user-images.githubusercontent.com/80394053/110622394-0f862000-81a4-11eb-9571-e5b64e0b93fa.png)

**Comment by eirannejad** [comment]
Check out this guide please : https://www.notion.so/pyrevitlabs/Can-Not-Uninstall-pyRevit-or-pyRevit-CLI-24978bb1aa3f4e419f61272bd1b19ffb

**Comment by NielBenade** [comment]
> Check out this guide please : https://www.notion.so/pyrevitlabs/Can-Not-Uninstall-pyRevit-or-pyRevit-CLI-24978bb1aa3f4e419f61272bd1b19ffb

No success unfortunately?

![2021-03-19_07h43_49](https://user-images.githubusercontent.com/80394053/111736614-db3aef80-8886-11eb-8110-b0140b3f491a.png)

Tried to uninstall after running pyrevit-doctor thru add/remove programs
Trien to uninstall thru running the new installation after pyrevit-doctor

Still receive the same message in both cases where the old version cannot be removed.

[MSI36CA.LOG](https://github.com/eirannejad/pyRevit/files/6168855/MSI36CA.LOG)

Should I perhaps consider doing a complete revit uninstall?
Regards

**Comment by eirannejad** [comment]
Fixed and will be published with next release
