### ISSUE TITLE
Unable to use comtypes library - object has no attribute '_IUnknown__com_QueryInterface'

### ISSUE THREAD

**Issue by dagz214** [eirannejad/pyRevit#1175]
**Description**
I'm trying to write a scripts that manipulates dwg files before linking to Revit model.
In order to do that I'm trying to use pyautocad library (which seems to load just fine) but it's depending on the comtypes library.
and when running gives the following error:
```
File "C:\Users\...lib\comtypes\client\__init__.py", line 188, in _manage
 File "C:\Users\...\lib\comtypes\__init__.py", line 1153, in QueryInterface
 File "C:\Users\...\lib\comtypes\client\__init__.py", line 183, in GetActiveObject
 File "C:\...\lib\comtypes\client\__init__.py", line 62, in GetBestInterface
AttributeError: 'POINTER(IUnknown)' object has no attribute '_IUnknown__com_QueryInterface'
```
I also tried using different engines in pyrevit without luck.

The thing is, when I run the same script with an ironpython engine **outside** of pyrevit it seems to run just fine.

**To Reproduce**
1. Load comtypes and pyautocad libraries inside a pyrevit extensoin
2. Use in script

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version [e.g. 22]
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.
```
==> Installed Revits
2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020 First Customer Ship | Version: 20.0.0.377 | Build: 20190327_2315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
PID: 6408 | 2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2021"
==> User Environment
Microsoft Windows 10 [Version 10.0.19042]
Executing User: LAPTOP-KTFOGH5Q\dan56
Active User: LAPTOP-KTFOGH5Q\dan56
Admin Access: No
%APPDATA%: "C:\Users\dan56\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.7 v4.7.1 v4.7.2 v4.8 v4.X
Installed .Net-Core Target Packs: v2.1.805 v5.0.102
pyRevit CLI 4.8.5.0
```

**Additional context**

**Comment by eirannejad** [comment]
Interesting . Try setting `__fullframeengine__ = True` somewhere at the top of your script. This pushed pyRevit to use a full-frame engine which is a bit closer to python specification. Let me know if it helps. Otherwise I'd appreciate if you can share a test script that causes the error so I can test.
