### ISSUE TITLE
Prints missing in action

### ISSUE THREAD

**Issue by DuncanLithgow** [eirannejad/pyRevit#1177]
**Describe the bug**
When I try and make a combined PDF it appears to work and the PDFs do spool - but the file is now where to be found. The spooling dialogue claims it's going to C:\\\

( for single pages it saves to C:\Users\dli\Desktop which is also a problem ... but that's an issue to be fixed with #988 )

**To Reproduce**
plot a pdf folder combining several sheets/views

**Expected behavior**
It should be obvious to me where the files go.

**Screenshots**
It seems to be sending them to C:\\\ - which doesn't exist
![billede](https://user-images.githubusercontent.com/3223028/109180591-50853a00-778b-11eb-82ab-c9324889a9d7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
![billede](https://user-images.githubusercontent.com/3223028/109180770-84605f80-778b-11eb-9158-ed4bf63cfcd1.png)

 - pyRevit Version 4.8.5
 - pyRevit Environment: 
```Microsoft Windows [Version 10.0.17763.1757]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\dli>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.5" | Path: "C:\Users\dli\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2021.1.1" | Engine: IPY277 (277) | Path: "C:\Users\dli\AppData\Roaming\pyRevit-Master"
master | Product: "2020.2.3" | Engine: IPY277 (277) | Path: "C:\Users\dli\AppData\Roaming\pyRevit-Master"
master | Product: "2019.2.2 Hotfix" | Engine: IPY277 (277) | Path: "C:\Users\dli\AppData\Roaming\pyRevit-Master"
master | Product: "2018.3.3 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\dli\AppData\Roaming\pyRevit-Master"
master | Product: "2017.2.5 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\dli\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\dli\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021.1.1 | Version: 21.1.10.26 | Build: 20200909_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.3 | Version: 20.2.30.42 | Build: 20200826_1250(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
2017.2.5 Security Fix | Version: 17.0.1169.0 | Build: 20190508_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
==> Running Revit Instances
PID: 9452 | 2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> User Environment
Microsoft Windows 10 [Version 10.0.17763]
Executing User: RAMBOLL\DLI
Active User: RAMBOLL\DLI
Admin Access: No
%APPDATA%: "C:\Users\dli\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.5.0

C:\Users\dli>```

**Additional context**
Add any other context about the problem here.

**Comment by DuncanLithgow** [comment]
This might be a problem for this PDF printer
![billede](https://user-images.githubusercontent.com/3223028/109182231-12891580-778d-11eb-901e-6b99203de6ae.png)

When I use the "Microsoft Print to PDF" printer it asks for a destination and then uses it correctly.

Also works fine for this one which also asks for a destination and then uses it correctly.
![billede](https://user-images.githubusercontent.com/3223028/109183129-ecb04080-778d-11eb-80da-be758c6056e1.png)

So that's odd ...

**Comment by DuncanLithgow** [comment]
I have written to the https://www.cadzation.com helpdesk, it's their virtual printer

**Comment by azhouseboater** [comment]
I take it you are trying to print without the SaveAs Dialog box.

What it the code in the C:\Program Files\AcroPlot\PDF-XChange 5.0 AcroPlot\titrules.js file?  This is the file that is responsible for parsing the filenames sent out by various different programs since there is no standard in Windows on how the filename is sent to the printer driver. By default we do not have any Revit specific code and 90% of all programs just send the filename and not the full path and filename out so for most programs the titrules.js really isn't used.

Also what it the location of the Revit file you are printing from?  I'm wondering if it's a shared drive and it's not properly getting parsed our from how Revit sends it out to the driver.

And what are the settings on the Save Tab of the PDF-XChange for AcroPlot Pro Printing Preferences.

**Comment by eirannejad** [comment]
@DuncanLithgow Yeah pyRevit basically asks Revit to print the PDFs. It's the Revit print settings, and the printer that decide where and how to store the files. pyRevit's only control on this process is hacking the sheet order, and providing the filenames. Thanks for tracking down! :D

**Comment by azhouseboater** [comment]
I'm guessing you made a change in the titrules.js file then.  If so what command did you use and we can look at adding it in for future releases if it doesn't effect any existing users.

**Comment by DuncanLithgow** [comment]
@azhouseboater thanks so much for lookign into this issue

I haven't personally made any changes to the titrules.js file. Shall I send it to you at a cadzation email address so you can take a look?

The Revit project is "in" Autodesk BIM360 cloud platform with a cached file on the local C drive.

Here is the Save Tab:

![billede](https://user-images.githubusercontent.com/3223028/110145007-41306d00-7dd9-11eb-9bf3-79ace903dd10.png)

**Comment by eirannejad** [comment]
I'm marking this issue as closed since it doesn't seem to need an action from me. But please keep the conversation going and feel free to re-open and @ me anytime

**Comment by DuncanLithgow** [comment]
sure @eirannejad I'll let you know if @azhouseboater and I find something helpful pyRevit could do.
