### ISSUE TITLE
pyRevit addin does not load after installation

### ISSUE THREAD

**Issue by BatMads** [eirannejad/pyRevit#1178]
Hey PYrevit

I am a student from Denmark and I use revit 2021 and I have just installed pyrivit (pyRevit_4.8.5_signed.exe) and there were no problems, but it does not appear when I open my revit program? 

Best regards Mads Mikkelsen
![Udklip](https://user-images.githubusercontent.com/79788827/109415467-2e70ff00-79b9-11eb-8289-3fd756fbe1b1.PNG)

**Comment by eirannejad** [comment]
Hello @BatMads ! Sorry for the troubles. See this please https://github.com/eirannejad/pyRevit/issues/1075#issuecomment-734950066

**Comment by BatMads** [comment]
Hi Eirannejad

It is okay 
I can not really make it work, otherwise I have not fully understood how to do it ??? 
![2](https://user-images.githubusercontent.com/79788827/109497999-271e2400-7a93-11eb-89e7-f28e861634ab.PNG)

**Comment by BatMads** [comment]
I made it work: D

**Comment by linjac** [comment]
Hi! How did you resolve this? I followed my installation path too, but I was not able to find clone "master".
Thanks in advance!

![image](https://user-images.githubusercontent.com/49277237/115908087-eef9e880-a426-11eb-841f-7acecd383e8a.png)
