### ISSUE TITLE
pyrevit cli showing help info when running attach command

### ISSUE THREAD

**Issue by jrostarHED** [eirannejad/pyRevit#1180]
**Describe the bug**
When running the pyRevit cli command to attach to Revit, pyRevit responds with the normal help response.

command running:
`pyrevit attach main --installed`

result of above command:

> C:\WINDOWS\system32>pyrevit attach main --installed
> Usage: pyrevit COMMAND [OPTIONS]
> 
> pyRevit environment and clones manager
> 
>     Options:
>         -h --help                Show this help
>         -V --version             Show version
>         --usage                  Print all usage patterns
>         --verbose                Print info messages
>         --debug                  Print docopt options and logger debug messages
>         --log=<log_file>         Output log messages to external log file
> 
>     Management Commands:
>         env                      Print environment information
>         update                   Update remote resources used by this utility
>         clones                   Manage pyRevit clones
>         extensions               Manage pyRevit extensions
>         attached                 Manage pyRevit attachments to installed Revit
>         releases                 Info about pyRevit releases
>         revits                   Manage installed Revits
>         caches                   Manage pyRevit caches
>         configs                  Manage pyRevit configurations
> 
>     Commands:
>         clone                    Create a clone of pyRevit on this machine
>         extend                   Create a clone of a third-party pyRevit extension on this machine
>         attach                   Attach pyRevit clone to installed Revit
>         switch                   Switch active pyRevit clone
>         detach                   Detach pyRevit clone from installed Revit
>         config                   Configure pyRevit for current user
>         run                      Run python script in Revit
>         doctor                   Fix potential or real problems
> 
>     Help Commands:
>         wiki                     Open pyRevit Wiki
>         blog                     Open pyRevit blog
>         docs                     Open pyRevit docs
>         source                   Open pyRevit source repo
>         youtube                  Open pyRevit on YouTube
>         support                  Open pyRevit support page
> 
> Run 'pyrevit COMMAND --help' for more information on a command.
> 
> 
> C:\WINDOWS\system32>

even occurs when adding `--debug` to the end of the command

result:

> C:\WINDOWS\system32>pyrevit attach main --installed --debug
> Debug: Arg processing failed. | Usage:

**Environment Data**

> C:\WINDOWS\system32>pyrevit env
> ==> Registered Clones (full git repos)
> main | Branch: "master" | Version: "4.8.5:6f3e004" | Path: "C:\pyrevit\main"
> ==> Registered Clones (deployed from archive/image)
> ==> Attachments
> ==> Installed Extensions
> ==> Default Extension Search Path
> C:\Users\jr_admin\AppData\Roaming\pyRevit\Extensions
> ==> Extension Search Paths
> ==> Extension Sources - Default
> https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
> ==> Extension Sources - Additional
> ==> Installed Revits
> 2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
> 2018.3.2 | Version: 18.3.2.7 | Build: 20181011_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
> 2017.2.4 | Version: 17.0.1158.0 | Build: 20181011_1645(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
> 2015 Release 2 Update Release 14  (Subscription only release) | Version: 15.0.1259.0 | Build: 20160512_0715(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2015\"
> ==> Running Revit Instances
> ==> User Environment
> Microsoft Windows 10 [Version 10.0.19041]
> Executing User: HED\JR_Admin
> Active User: HED\MHironaka
> Admin Access: Yes
> %APPDATA%: "C:\Users\jr_admin\AppData\Roaming"
> Latest Installed .Net Framework: 4.8
> No .Net Target Packs are installed.
> No .Ne-Core Target Packs are installed.
> pyRevit CLI 4.8.5.0

**Expected behavior**
I would expect pyrevit cli to attach to the installed revit versions

**Comment by eirannejad** [comment]
`pyrevit attach main 277 --installed`

See `pyrevit attach --help`
