### ISSUE TITLE
error in save_excel_file()

### ISSUE THREAD

**Issue by max-bold** [eirannejad/pyRevit#1182]
Good time of the day!

I foun an error in \pyrevitlib\pyrevit\forms\__init__.py

![изображение](https://user-images.githubusercontent.com/77934776/110202130-cff3c700-7e77-11eb-9a99-cdbb88be7fdd.png)

so when pyrevit.forms.save_excel_file() is called, an error is thrown that 'title' is not defined.

**Comment by eirannejad** [comment]
Merged the PR. Thank you!
