### ISSUE TITLE
Font error while publishing in PDF in Revit 2020

### ISSUE THREAD

**Issue by nghesi** [eirannejad/pyRevit#1186]
**Describe the bug**
We got the problem with Revit 2020 where drawing printed out to PDF with messy font, even though it looks right on preview

![image](https://user-images.githubusercontent.com/37094515/111127730-b99be880-85a6-11eb-8ef9-ecae98f63aae.png)
While it should be
![image](https://user-images.githubusercontent.com/37094515/111127887-e3550f80-85a6-11eb-81fd-9385a300f8da.png)

I can disable pyRevit and restart the PC to fix the problem but this will have the same issue if I turned on the pyRevit again

**Comment by eirannejad** [comment]
Are you printing using pyRevit?

**Comment by nghesi** [comment]
I'm using both revit and pyRevit and that both cause the problem. I tried to uninstall pdfcreator and use bluebeam PDF instead, I don't know what's going on but the errors seems to be removed then a moment later it happened again.

The problem happens also the all my colleagues who is using pyRevit

**Comment by alexdaversa** [comment]
@nghesi can you confirm that this problem is not related to the windows updates listed here: https://www.reddit.com/r/Revit/comments/m5mlrv/revit_text_not_working_after_windows_10_update/

Can you also confirm that your monitor(s) are set to their default/native resolution?

**Comment by nghesi** [comment]
So many thanks @alexdaversa, @eirannejad , I removed some new window update dated on March 2021 then I don't experience the problem ever again.
