### ISSUE TITLE
Can not find clone master

### ISSUE THREAD

**Issue by jogilec** [eirannejad/pyRevit#1187]
Hey Ehsan,

I am running into a problem: installed pyrevit and everything went smoothly. Unfortunately, I could not see an add-on in Revit, so I tried reading around here and finding a solution, but I can not get around it. Sorry, if it was already explained and I missed it. Attaching command prompt below:

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
main | Deploy: "basepublic" | Branch: "master" | Version: "4.8.5" | Path: "C:\Users\Jogile Cibulskyte\AppData\Roaming\pyRevit-Master"
==> Attachments
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Jogile Cibulskyte\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020 First Customer Ship | Version: 20.0.0.377 | Build: 20190327_2315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019 Update for Trial Build | Version: 19.0.1.1 | Build: 20180328_1600(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19042]
Executing User: *\Jogile Cibulskyte
Active User: *\Jogile Cibulskyte
Admin Access: No
%APPDATA%: "C:\Users\*\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.5.0
```

**Comment by eirannejad** [comment]
Take a look at this please and let me know if it helps

https://www.notion.so/pyrevitlabs/pyRevit-Is-Installed-But-Does-Not-Load-f6495adb56254e9e8021f8a68e3b2ab7

**Comment by jogilec** [comment]
Thanks for the reply! I am quite a noob in this but seems I am doing everything fine and it does not work... Getting an error that it can not find a master.

C:\Users\Jogile Cibulskyte> pyrevit attached
==> Attachments

C:\Users\Jogile Cibulskyte> pyrevit clones
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
main | Deploy: "basepublic" | Branch: "master" | Version: "4.8.5" | Path: "C:\Users\Jogile Cibulskyte\AppData\Roaming\pyRevit-Master"

C:\Users\Jogile Cibulskyte> pyrevit attach master 277 --installed
Error: Can not find clone "master"
Run with "--debug" option to see debug messages

C:\Users\Jogile Cibulskyte> pyrevit clones add master "C:\Users\Jogile Cibulskyte\AppData\Roaming\pyRevit-Master"
Error: Clone with repo path "C:\Users\Jogile Cibulskyte\AppData\Roaming\pyRevit-Master" already exists.
Run with "--debug" option to see debug messages

C:\Users\Jogile Cibulskyte> pyrevit "--debug"
Debug: Arg processing failed. | Usage:
        pyrevit (-h | --help)
        pyrevit (-V | --version)
        pyrevit --usage
        pyrevit (wiki | blog | docs | source | youtube | support)
        pyrevit env [--json] [(-h | --help)] [--log=<log_file>]
        pyrevit update [--help] [--log=<log_file>]
        pyrevit clone (-h | --help)
        pyrevit clone <clone_name> <deployment_name> [--dest=<dest_path>] [--branch=<branch_name>] [--log=<log_file>]
        pyrevit clone <clone_name> --image=<image_url> [--dest=<dest_path>] [--log=<log_file>]
        pyrevit clone <clone_name> [--dest=<dest_path>] [--source=<repo_url>] [--branch=<branch_name>] [--log=<log_file>] [--username=<username>] [--password=<password>]
        pyrevit clones [(-h | --help)]
        pyrevit clones (info | open) <clone_name>
        pyrevit clones add <clone_name> <clone_path> [--force] [--log=<log_file>]
        pyrevit clones forget (--all | <clone_name>) [--log=<log_file>]
        pyrevit clones rename <clone_name> <clone_new_name> [--log=<log_file>]
        pyrevit clones delete [(--all | <clone_name>)] [--clearconfigs] [--log=<log_file>]
        pyrevit clones branch <clone_name> [<branch_name>] [--log=<log_file>]
        pyrevit clones version <clone_name> [<tag_name>] [--log=<log_file>]
        pyrevit clones commit <clone_name> [<commit_hash>] [--log=<log_file>]
        pyrevit clones origin <clone_name> --reset [--log=<log_file>]
        pyrevit clones origin <clone_name> [<origin_url>] [--log=<log_file>]
        pyrevit clones update (--all | <clone_name>) [--log=<log_file>] [--username=<username>] [--password=<password>]
        pyrevit clones deployments <clone_name>
        pyrevit clones engines <clone_name>
        pyrevit attach (-h | --help)
        pyrevit attach <clone_name> (default | <engine_version>) (<revit_year> | --installed | --attached) [--allusers] [--log=<log_file>]
        pyrevit attached [<revit_year>] [(-h | --help)]
        pyrevit switch (-h | --help)
        pyrevit switch <clone_name> [<revit_year>]
        pyrevit detach (-h | --help)
        pyrevit detach (--all | <revit_year>) [--log=<log_file>]
        pyrevit extend (-h | --help)
        pyrevit extend <extension_name> [--dest=<dest_path>] [--branch=<branch_name>] [--log=<log_file>]
        pyrevit extend (ui | lib) <extension_name> <repo_url> [--dest=<dest_path>] [--branch=<branch_name>] [--log=<log_file>] [--username=<username>] [--password=<password>]
        pyrevit extensions [(-h | --help)]
        pyrevit extensions search <search_pattern>
        pyrevit extensions (info | help ) <extension_name>
        pyrevit extensions open <extension_name>
        pyrevit extensions open <clone_name> <extension_name>
        pyrevit extensions delete <extension_name> [--log=<log_file>]
        pyrevit extensions origin <extension_name> --reset [--log=<log_file>]
        pyrevit extensions origin <extension_name> [<origin_url>] [--log=<log_file>]
        pyrevit extensions paths [(-h | --help)]
        pyrevit extensions paths forget --all [--log=<log_file>]
        pyrevit extensions paths (add | forget) <extensions_path> [--log=<log_file>]
        pyrevit extensions (enable | disable) <extension_name> [--log=<log_file>]
        pyrevit extensions (enable | disable) <clone_name> <extension_name> [--log=<log_file>]
        pyrevit extensions sources [(-h | --help)]
        pyrevit extensions sources forget --all [--log=<log_file>]
        pyrevit extensions sources (add | forget) <source_json_or_url> [--log=<log_file>]
        pyrevit extensions update (--all | <extension_name>) [--log=<log_file>] [--username=<username>] [--password=<password>]
        pyrevit releases (-h | --help)
        pyrevit releases [--pre] [--notes]
        pyrevit releases latest [--pre] [--notes]
        pyrevit releases <search_pattern> [--pre] [--notes]
        pyrevit releases open latest [--pre]
        pyrevit releases open <search_pattern> [--pre]
        pyrevit releases download (installer | archive) <search_pattern> [--dest=<dest_path>] [--pre]
        pyrevit revits
        pyrevit revits (-h | --help)
        pyrevit revits [--installed] [--log=<log_file>]
        pyrevit revits --supported [--csv=<output_file>]
        pyrevit revits killall [<revit_year>] [--log=<log_file>]
        pyrevit revits fileinfo <file_or_dir_path> [--csv=<output_file>] [--rvt] [--rte] [--rfa] [--rft]
        pyrevit run (-h | --help)
        pyrevit run commands
        pyrevit run <script_or_command_name> [--revit=<revit_year>] [--purge] [--import=<import_path>]
        pyrevit run <script_or_command_name> --models=<model_list_file> --revit=<revit_year> [--purge] [--import=<import_path>]
        pyrevit run <script_or_command_name> <model_file> [--revit=<revit_year>] [--purge] [--import=<import_path>]
        pyrevit caches (-h | --help)
        pyrevit caches [bim360] clear (--all | <revit_year>) [--log=<log_file>]
        pyrevit config (-h | --help)
        pyrevit config --from=<template_config_path> [--log=<log_file>]
        pyrevit configs (-h | --help)
        pyrevit configs bincache [(enable | disable)] [--log=<log_file>]
        pyrevit configs checkupdates [(enable | disable)] [--log=<log_file>]
        pyrevit configs autoupdate [(enable | disable)] [--log=<log_file>]
        pyrevit configs rocketmode [(enable | disable)] [--log=<log_file>]
        pyrevit configs logs [(none | verbose | debug)] [--log=<log_file>]
        pyrevit configs filelogging [(enable | disable)] [--log=<log_file>]
        pyrevit configs startuptimeout [<timeout>] [--log=<log_file>]
        pyrevit configs loadbeta [(enable | disable)] [--log=<log_file>]
        pyrevit configs cpyversion [<cpy_version>] [--log=<log_file>]
        pyrevit configs usercanupdate [(yes | no)] [--log=<log_file>]
        pyrevit configs usercanextend [(yes | no)] [--log=<log_file>]
        pyrevit configs usercanconfig [(yes | no)] [--log=<log_file>]
        pyrevit configs colordocs [(enable | disable)] [--log=<log_file>]
        pyrevit configs tooltipdebuginfo [(enable | disable)] [--log=<log_file>]
        pyrevit configs routes [(-h | --help)]
        pyrevit configs routes [(enable | disable)] [--log=<log_file>]
        pyrevit configs routes port [<port_number>] [--log=<log_file>]
        pyrevit configs routes coreapi [(enable | disable)] [--log=<log_file>]
        pyrevit configs telemetry [(-h | --help)]
        pyrevit configs telemetry [(enable | disable)] [--log=<log_file>]
        pyrevit configs telemetry utc [(yes | no)] [--log=<log_file>]
        pyrevit configs telemetry (file | server) [<dest_path>] [--log=<log_file>]
        pyrevit configs telemetry hooks [(yes | no)] [--log=<log_file>]
        pyrevit configs apptelemetry [(enable | disable)] [--log=<log_file>]
        pyrevit configs apptelemetry flags [<flags>] [--log=<log_file>]
        pyrevit configs apptelemetry server [<server_path>] [--log=<log_file>]
        pyrevit configs outputcss [<css_path>] [--log=<log_file>]
        pyrevit configs seed [--lock] [--log=<log_file>]
        pyrevit configs <option_path> [(enable | disable)] [--log=<log_file>]
        pyrevit configs <option_path> [<option_value>] [--log=<log_file>]
    pyrevit doctor (-h | --help)
    pyrevit doctor [--list]
    pyrevit doctor <doctor_command> [--dryrun]
Usage: pyrevit COMMAND [OPTIONS]

pyRevit environment and clones manager

    Options:
        -h --help                Show this help
        -V --version             Show version
        --usage                  Print all usage patterns
        --verbose                Print info messages
        --debug                  Print docopt options and logger debug messages
        --log=<log_file>         Output log messages to external log file

    Management Commands:
        env                      Print environment information
        update                   Update remote resources used by this utility
        clones                   Manage pyRevit clones
        extensions               Manage pyRevit extensions
        attached                 Manage pyRevit attachments to installed Revit
        releases                 Info about pyRevit releases
        revits                   Manage installed Revits
        caches                   Manage pyRevit caches
        configs                  Manage pyRevit configurations

    Commands:
        clone                    Create a clone of pyRevit on this machine
        extend                   Create a clone of a third-party pyRevit extension on this machine
        attach                   Attach pyRevit clone to installed Revit
        switch                   Switch active pyRevit clone
        detach                   Detach pyRevit clone from installed Revit
        config                   Configure pyRevit for current user
        run                      Run python script in Revit
        doctor                   Fix potential or real problems

    Help Commands:
        wiki                     Open pyRevit Wiki
        blog                     Open pyRevit blog
        docs                     Open pyRevit docs
        source                   Open pyRevit source repo
        youtube                  Open pyRevit on YouTube
        support                  Open pyRevit support page

Run 'pyrevit COMMAND --help' for more information on a command.

**Comment by eirannejad** [comment]
The clone is called `main` for some reason. Try `pyrevit attach main 277 --installed`

**Comment by jogilec** [comment]
Thank you Ehsan! That worked :)
