### ISSUE TITLE
Revit 2021.1.2 not showing as installed

### ISSUE THREAD

**Issue by Strider11** [eirannejad/pyRevit#1188]
**Describe the bug**
I've tried installing versions 4.8.5 (signed) today and previously had tried v4.84 (signed and CLI).  When I start Revit 2021, the pyRevit tab isn't there.  It works great on 2020.2.3 though.  I've tried multiple commands suggested in other issues and nothing has worked yet.  My guess is it's not finding the install path correctly 'D:\Program Files\Autodesk\Revit 2021', but I'm not a programmer, so just a guess.

**To Reproduce**
1. Install pyRevit_4.8.5_signed.exe
2. Launch Revit 2021
3. No pop-up, no pyRevit ribbon tab

**Expected behavior**
I expected the pyRevit tab to show in 2021, just as it does in 2020.

**Screenshots**
![image](https://user-images.githubusercontent.com/27226573/111500086-9b9ec700-8711-11eb-81f5-28e6177fd00f.png)
![image](https://user-images.githubusercontent.com/27226573/111500140-aa857980-8711-11eb-8bab-fbb2a963cfee.png)
![image](https://user-images.githubusercontent.com/27226573/111500213-bcffb300-8711-11eb-835c-c6cda9abc4f5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro v1909 build 18363.778
 - pyRevit Version: 4.8.5
 - pyRevit Environment: 
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.5" | Path: "C:\Users\isaac.hedberg\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2020.2.3" | Engine: IPY277 (277) | Path: "C:\Users\isaac.hedberg\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\isaac.hedberg\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2020.2.3 | Version: 20.2.30.42 | Build: 20200826_1250(x64) | Language: 1033 | Path: "D:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
PID: 18096 | 2021.1.2 | Version: 21.1.20.44 | Build: 20201109_1530(x64) | Language: 0 | Path: ""
==> User Environment
Microsoft Windows 10 [Version 10.0.18363]
Executing User: NOR-SON\isaac.hedberg
Active User: NOR-SON\isaac.hedberg
Admin Access: Yes
%APPDATA%: "C:\Users\isaac.hedberg\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.5.0

**Additional context**
Output.log file
[output.log](https://github.com/eirannejad/pyRevit/files/6157915/output.log)

**Comment by eirannejad** [comment]
Take a look at this please and let me know if it fixes the issue

https://www.notion.so/pyrevitlabs/pyRevit-Is-Installed-But-Does-Not-Load-f6495adb56254e9e8021f8a68e3b2ab7

pyRevit already knows Revit 2021.1.2 so it is very odd that it is not listing it. Would you mind exporting this key `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{7346B4A0-2100-0510-0000-705C0D862004}` from your registry and sending it to me? Thanks!

**Comment by Strider11** [comment]
Thank you, Ehsan.  I had already tried the suggestions in the link, prior
to posting, but ran it all again anyway.
[image: image.png]
Attached is the registry export.

Ike

**Comment by eirannejad** [comment]
I don't see attachments when you reply to a github notification. Please send that to my email :D thank you!

**Comment by teflaherty67** [comment]
I tried that as well, and it didn't work for me either.

**Comment by Strider11** [comment]
> I don't see attachments when you reply to a github notification. Please send that to my email :D thank you!

I did reply to your email, not on Github.  Should I send a new email?

**Comment by eirannejad** [comment]
Ok mine and your settings seem identical except for the build number

Last request. Would you mind running `pyrevit revits --installed --debug` and share the report log? This provides a detailed report of what pyrevit can see in the registry and what it is not seeing 2021

**Comment by Strider11** [comment]
Here is the current Log.
[debug.txt](https://github.com/eirannejad/pyRevit/files/6206928/debug.txt)

**Comment by eirannejad** [comment]
Debug tells me

`Debug: Product not found at expected path "C:\Program Files\Autodesk\Revit 2021"`

Where is the path to your 2021 Revit.exe ?!

**Comment by eirannejad** [comment]
Ok great. found the bug. To make it work for now just copy the `pyRevit.addin` file from 2020 into the `%APPDATA%\Autodesk\Revit\Addins\2021` folder and it should work. I'll publish the fix next week with 4.8.7

**Comment by eirannejad** [comment]
@Strider11 Okay I thought I had found a bug but Nope. Based on the log, it does not seem like your Revit is installed in a standard location

`Debug: Product not found at expected path "C:\Program Files\Autodesk\Revit 2021"`

Could you check the path to 2021 `Revit.exe`?

To make this work you can manually edit the `InstallLocation` key under the registry path `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{7346B4A0-2100-0510-0000-705C0D862004} ` to the actual installation path in my case `C:\Program Files\Autodesk\Revit 2021\`

**Comment by Strider11** [comment]
@eirannejad Correct, my Revit is installed on the D: drive (larger HDD) rather than the C: drive (smaller SSD.)
Changing the path in the registry and re-running **pyrevit attach master 277 --installed** seems to have fixed it.
Thank you so much!!

**Comment by jmcouffin** [comment]
It solved the issue for one of my colleagues as well, all revit installed on D drive, but just revit 2021 did not show up.
was installing with pyrevit 4.8.8, then tried the pyrevit cli approah. but the regedit did the trick @eirannejad
