### ISSUE TITLE
Package Manager Proposal Discussion

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#119]
Sketch of Package Manager Concept for discussion:
<br />
<br />### What does it do
<br />Allows pyrevit users to install/remove/update pyrevit extensions from within revit.
<br />
<br />### How it works
<br />1. A Package Index in json format is Stored on PyRevit Repo
<br />2. Package stores (name, version, url, and description).
<br />3. Pulls json from Repo using requests or .net webclient
<br />4. Find pyrevit local dir by package manager script location
<br />5. Check local folders and compare to name of packages in packages.json
<br />6. Determine if remote package is installed, and compare version to local packages 
<br />(use version variable insite package's __init__.py  or version.py file instead of opening files and re searching for __version__ for better performance and reliability)
<br />
<br />7. Render a Datagrid with action buttons for every row:
<br />Package name, remote version, local version, description, and actions:
<br />Not installed: Install
<br />Installed but not latest: Upgrate + Remove
<br />Installed and latest: Remove
<br />
<br />Actions:
<br />* Remove: Delete folder
<br />* On install/Upgrade: Clone remote repo from json: url path into folder 'packagename'
<br />
<br />
<br />### Implementation Details:
<br />PACKAGES.JSON (stored on pyrevit repo): item # 1/2/3 abovelist:
<br />example: 
<br />[
<br />{'name':'pyrevitplus','version':'1.0.0', 'url':'github.com/gtalarico/pyrevitplus, 'description': 'Tools for XXX'},
<br />{'name':'selectiontools', version':'1.0.0', 'url':'github.com/gtalarico/pyrevitplus, 'description': 'etc'},
<br />]
<br />
<br />Once packages is read and compared to local folders, a local_packages dictionary is created in memory, adding the following keys:
<br />'installed': True/False,
<br />'local_version': '0.2.0'' 
<br />
<br />local_packages is then used to render datagrid, and add appropriate actions.
<br />Note: If program cannot reach packages.json, TaskDialog warns user, and dialog is closed.
<br />UI:
<br />- Use WPF
<br />- Simple white window, with full-size data-grid as described above
<br />- Future Feature: Add button to manually install package by browsing to .zip file (version 2.0)

**Comment by gtalarico** [comment]
Correction
Use version = 'x.x.x'
Inside package init

**Comment by eirannejad** [comment]
Looks pretty good to me. One suggestion: Use `git rev-parse HEAD` to get the HEAD id of the extension git repo (since all extensions are git clones) and use that for version comparison. The json file in pyRevit repo should only contain extension name,url,desc for flexibility.

Package manager will compare git HEADs and will determine to Install/Update/Remove the extension.

**Comment by eirannejad** [comment]
git has a library for C# but I wasn't able to get it to work in IronPython [libgit2sharp](https://github.com/libgit2/libgit2sharp)

**Comment by eirannejad** [comment]
Also the json file is part of the pyRevit git repo so it gets cloned on the local folder. You might be able to use that instead of pulling from web.

**Comment by gtalarico** [comment]
Agree on head Vs manual version control.

What about using something like gitpython in conjunction with git portable?
I guess using subprocess and popen can achieve the same results, but it
would help make the code cleaner and more manageable.
I can give it a shot while testing the package manager if you think it's
worth pursuing.
http://gitpython.readthedocs.io/en/stable/tutorial.html#tutorial-label

Gui Talarico
[ mobile ]

**Comment by eirannejad** [comment]
Never used gitpython. is it properly maintained?

**Comment by gtalarico** [comment]
Gitpython: Looks like it's active:
Over 1k stars, 90+ contributors, 1.5k commits, latest commit is hours old.
https://github.com/gitpython-developers/GitPython

Either way, I want to wrap the clone/delete into functions, so later we can change method more easily.
I will probably start just copying the code from your settings_download updates.

**Comment by gtalarico** [comment]
UI test preview. build dynamically from packages JSON + compared data (ie: Installed)
Thoughts from a UI perspective?
(I will remove/clean up final visible columns) 
I think eventually it could be more sophisticated, with search (dynamo package manager, or sketchup extension warehouse) but I thought this could work for version 0.1 

![image](https://cloud.githubusercontent.com/assets/9513968/17760722/dda8d8de-64cf-11e6-9ec3-60606d848388.png)

**Comment by eirannejad** [comment]
I like it! I think it's simple and easy to use! Thanks pal!

**Comment by eirannejad** [comment]
***Question:*** How did u end up having a repo inside another repo? Isn't the package manager cloning the extension tabs in the root folder? (where __git__, __init__, and pyRevit clone exist)
Agree with you on the web hosted packages.json. It could be a newer version and the user might not update the local repo before running package manager. You knew better :+1:

**Comment by gtalarico** [comment]
I am actually just just working out of the latest commit on your master  : )
I was more focused on getting refactoring the prototype code base, getting the UI working and the clone/remove/cleanup functions.

Do you have a branch of the "new structure" you emailed me ?
Do we have a working loader for the new structure?

https://github.com/gtalarico/pyRevit/tree/manager

**Comment by eirannejad** [comment]
Yeah I'll email you a dropbox link. I have it in the private pyRevit master repo but I also have other company tools in there that has made the repo a bit big. I'll be cleaning that up later as the main development repo for pyRevit and will share with you. Till then I'll send you the folders in compressed archives.

**Comment by gtalarico** [comment]
@eirannejad do you know if it's possible to remove a tab without restarting revit?
Would be a nice touch to add to package manger>Remove Package

**Comment by eirannejad** [comment]
Nah. Revit doesn't return any objects when creating Ribbon Tabs

**Comment by gtalarico** [comment]
@eirannejad 
I have a semi stable version running here if you want to take a peak
This fork includes the full thing (core+scripts+git) but should work as a fresh clone.
https://github.com/gtalarico/pyRevit/tree/v3

Users this packages.json: https://github.com/gtalarico/pyRevit/blob/v3/pyRevit/pyRevit.tab/pkgManager/packages.json
Demo Package: https://github.com/gtalarico/pyrevitplus

**Comment by eirannejad** [comment]
Looks really good to me! Thanks so much!

**Comment by gtalarico** [comment]
@eirannejad I made a few revisions to the packages manager and I think it's ready for beta, most importantly, I updated the git commands to the use separate git directories (non-nested) and the correct folder structure.

The latest packages is in this branch:
https://github.com/gtalarico/pyrevit/tree/pyrevitv3

I can't do a pull request because the directory structure doesn't match the your master (ie. pyrevit.tab directory),

**Comment by eirannejad** [comment]
I get an error. The portable git is installed in `__git__` folder.

[image: Inline images 2]
[image: Inline images 1]

**Comment by gtalarico** [comment]
I belive this was fixed on commit bb53c652
And
a785a8a2

Gui Talarico
[ mobile ]

**Comment by gtalarico** [comment]
Just tested on my work computer, worked ok. Latest config file should look like this.
![image](https://cloud.githubusercontent.com/assets/9513968/18068987/3ab86b8e-6e12-11e6-920b-54c01c2217b9.png)

**Comment by gtalarico** [comment]
@eirannejad I think I figure out why yours was not working
Looks like when I rebuilt the pyrevit dir from the .zip you sent me 
I nested the pyrevit.tab one level deeper than I should have.
either way should an easy fix by just adjusting the config dir constants.
sorry about the confusion!
![image](https://cloud.githubusercontent.com/assets/9513968/18074042/b5809fba-6e37-11e6-9455-1bae54cb5812.png)

**Comment by eirannejad** [comment]
Gui,
Well done master!!! I edited the config file like this to get the correct folder address:
`PYREVIT_DIR = os.path.dirname(SCRIPTS_DIR)`

And it's working like a charm! Love the way it removes the extension tab being uninstalled. I'll cleanup everything else this weekend and publish v3 for the labour day.

Thanks again!!
