### ISSUE TITLE
pyRevit 4.8.2 Tool not working Revit 2017 & 2018

### ISSUE THREAD

**Issue by kuldeep3618x** [eirannejad/pyRevit#1190]
I recently wrote scripts for pyRevit for Revit 2019 & 2020. Now when I run the scripts on Revit 2017 & 2018 I get an error. as:

**IOError: System.IO.IOException: Could not add reference to assembly Revit Services**

Please note I donot have Dynamo installed on the system. Is there a walkaround for this to run my Tools on Revit 2017 & 2018.

![Error Message](https://user-images.githubusercontent.com/59068105/111650593-730af000-882b-11eb-9fd6-c740dc7fd1d3.jpg)

**Comment by eirannejad** [comment]
Seems like you need to provide the full path of the dll and load using `clr.AddReference` It seems the RevitServices dll might not be preloaded in Revit 2018, 2017

**Comment by eirannejad** [comment]
I'm closing this ticket since it is not a pyRevit issue but please continue the discussion here.
