### ISSUE TITLE
Uninstall of PyRevit 4.7.2 still not working.

### ISSUE THREAD

**Issue by FalconStarFighter** [eirannejad/pyRevit#1192]
**Describe the bug**
Attempted to uninstall PyRevit 4.7.2 in every way I've seen so far.  I may have screwed up the uninstall with my order of operations, so I will do my best to summarize.  
1. Tried Running 4.8.5 as administrator and got the "The older version of pyRevit cannot be removed.  Contact your technical support group."  Log file attached.
[MSI724F.LOG](https://github.com/eirannejad/pyRevit/files/6174313/MSI724F.LOG)

2. Attempted to uninstall through the add/remove apps.  The icon and 4.7.2
3. Deleted the pyRevit-Master folder and attempted a new install with the same results
4. went to the registry editor to try and find the subkey per another post. (can't find the post again to reference sorry).  I didn't see any pyRevit files and wasn't sure about the GUIDs 
5. Saw this post about using pyRevit doctor.  Ran it as an admin.  
6. Tried running 4.8.5.exe again.  Rinsed and repeated.
7. Tried finding another 4.7.2 install to attempt to repair something I may have broken, repeated all steps.

**Expected behavior**
4.8.5 to uninstall previous versions and install

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.7.2 uninstall to 4.8.5 install
 - pyRevit Environment: Unable to do so at this time.

**Additional context**
Add any other context    #1045

**Comment by eirannejad** [comment]
What happens after running `pyrevit-doctor`? Can you install 4.8.5? Do you get an error?

**Comment by FalconStarFighter** [comment]
I've run pyrevit-doctor a number of times and still have pyRevit 4.7.2 sticking around.  I don't see anything else in the registry editor or any folder structures.  I still cannot install 4.8.5 after running pyrevit-doctor.  I get the same install error.  I'm going to see if our IT can help me figure out where I went wrong and will keep you posted.

**Comment by eirannejad** [comment]
The product key for 4.72 was `{83110B68-9131-4D58-95AB-D05D785A22E1}`. Search for that under 
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\` in your registry. There might be keys remaining there still.

I'm sorry for the troubles :/

**Comment by FalconStarFighter** [comment]
Thanks for your quick replies!  I will see if I can find that key in my registry.  Might be the missing piece of the puzzle for me.  I will let you know if this resolves it.

**Comment by FalconStarFighter** [comment]
We were able to get it.  we restored some folders I had deleted and ran Revo uninstaller.  Thanks again for your help!

**Comment by McRyach** [comment]
I've had the same issue.
You need to install laser version of pyRevit as administrator to fix it.
I installed pyRevit 4.8.7 and that solved the problem.
