### ISSUE TITLE
pyRevit Emoji not fonctionning

### ISSUE THREAD

**Issue by IrishFriend** [eirannejad/pyRevit#1194]
Hello, just tried to launch Emoji fonction in pyRevit panel
tried to attach an image but it is not working
Windows 10 French

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\xxx\AppData\Roaming\pyRevit-Master\extensions\pyRevitCore.extension\pyRevit.tab\pyRevit.panel\rpwlinks.stack\emojis.pushbutton\script.py", line 2, in <module>
ImportError: Cannot import name ScriptConsoleEmojis

Script Executor Traceback:
IronPython.Runtime.Exceptions.ImportException: Cannot import name ScriptConsoleEmojis
 à IronPython.Runtime.Importer.ImportFrom(CodeContext context, Object from, String name)
 à Microsoft.Scripting.Interpreter.FuncCallInstruction`4.Run(InterpretedFrame frame)
 à Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 à Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 à IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 à PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by eirannejad** [comment]
Hmm. What's the script?!

**Comment by IrishFriend** [comment]
I accessed it from the pyRevit first tab on the left, where you access the settings

**Comment by eirannejad** [comment]
uh found it. Thanks a lot. Fixed and will be published with next release

**Comment by IrishFriend** [comment]
WOW that was quick, Many thanks

**Comment by mrjoneskod** [comment]
Hi, when is the next release coming out? Is there another documentation I can look at to get the emoji info?

**Comment by eirannejad** [comment]
Very soon (next week :D ) just finishing up some stuff

**Comment by mrjoneskod** [comment]
I know it has nothing to do with this post, but how is the CPython integration going on?
I am very interested in that. Also, I can contribute if you have any documentation on it.
