### ISSUE TITLE
add optional doc parameter to `query` functions

### ISSUE THREAD

**Issue by sanzoghenzo** [eirannejad/pyRevit#1195]
I see that some of the functions in the `pyrevit.revit.db.query` module don't have the usual `doc` keyword argument, even if they call or are called by functions that can handle this parameter.
These are the function I found so far:

- `get_project_parameter_id` 
- `get_schedule_categories`
- `get_key_schedule_categories`
- `get_takeoff_categories`

Currently I'm using only the first function, and I don't even need this feature, but it would be nice to futureproof your (and my) code.

**Comment by eirannejad** [comment]
Fixed and will be published with next release
