### ISSUE TITLE
Issue with number of Tab colors

### ISSUE THREAD

**Issue by robin-911** [eirannejad/pyRevit#1196]
For the new 4.8.6 version

When reducing the number of Tab colors to 3, PyRevit gives an error message. When clicking that away Revit give the "An unrecoverable error has occured" message en closes.

Tested in both 2020 and 2021 with the same result.

Work around so far is to add the colors you want first and then delete the ones you don't want, by selecting it and clicking the - button

**Comment by eirannejad** [comment]
Thank you for reporting this. Here are a few workaround and tips until I publish a fix:

1) You can double-click on the color swatches

![E1pzNwshoT](https://user-images.githubusercontent.com/8197916/112212199-ed47c580-8bd9-11eb-98d6-47d63976ec1b.gif)


2) If you somehow ended up with an empty color list that makes Revit crash on startup, make sure to clean the configs. Open the `%APPDATA%\pyRevit\pyRevit_config.ini` file and remove the `[tabcoloring]` section. So all of this:

```ini
[tabcoloring]
sort_colorize_docs = false
tabstyle_index = 2
family_tabstyle_index = 5
tab_colors = []
tab_filtercolors = {}
use_family_colorize_theme = false
family_colors = []
family_filtercolors = {}
```

**Comment by eirannejad** [comment]
Fixed and will be published with next release
