### ISSUE TITLE
Tab Colouring Question: Why is Keep Open Tabs Sorted By Document grayed out?

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#1197]
Tab Colouring Question: Why is Keep Open Tabs Sorted By Document grayed out?

![image](https://user-images.githubusercontent.com/8776947/112292083-a49b1580-8c88-11eb-97c5-11ba7d57d43e.png)

**Comment by eirannejad** [comment]
Feature in progress :D It's just a tease for now hahaaa

**Comment by dcdixon** [comment]
I had a good question from a new hire regarding grouping project tabs together so thought I'd look at this again ... is the "Keep Open Tabs Sorted by Document" still a future feature or something I need to do to enable it? I'm running pyRevit 4.8.9 at the moment.

**Comment by Angoose884** [comment]
Any updates on this? I know my coworker would be elated for a feature like this so they don't have to drag their tabs around anymore.
