### ISSUE TITLE
Hard crash Print Sheets tool

### ISSUE THREAD

**Issue by olalancette** [eirannejad/pyRevit#1198]
**Describe the bug**
While loading a sheet index in the "Print Sheets" tool, Revis crashes. The tool freezes while loading the second sheet for a couple of seconds, see screenshot below.
![image](https://user-images.githubusercontent.com/24980892/112311459-1d47a500-8c7c-11eb-9fa6-e87f79f1d492.png)

To reproduces
Only in **Revit 2018**. Fixed in later versions of Revit.

Possible cause :
The presence of a revision on the sheet seems to be the culprit.

**To Reproduce**
1. In Revit 2018 (tested on french and english), with an empty template, set a revision on two sheets : A101 and A102.
2. Have an empty sheet list schedule named "A" (use Sheet name greater than "B" to filter out all the sheets).
3. Have a full sheet list schedule named "B" (no filter).
3. Open Print Sheets tool.
4. Switch from Sheet List "A" to Sheet List "B"
5. Get an error

If using a blank template it gives you this window, instead of a full Revit Crash:
![image](https://user-images.githubusercontent.com/24980892/112313561-60a31300-8c7e-11eb-9cd2-840ac5652e1e.png)
![image](https://user-images.githubusercontent.com/24980892/112313593-6993e480-8c7e-11eb-96c4-3021f5785db1.png)

**Expected behavior**
Sheet list to load without a crash or error.

**Desktop (please complete the following information):**
 - OS: Windows 10 build 1909
 - pyRevit Version 4.8.6
 - pyRevit Environment: 
`==> Registered Clones (full git repos)
main | Branch: "master" | Version: "4.8.6:9eb5df2" | Path: "C:\pyRevit\main"
==> Registered Clones (deployed from archive/image)
==> Attachments
main | Product: "2021.1.2" | Engine: IPY277 (277) | Path: "C:\pyRevit\main" | AllUsers
main | Product: "2020.2.1 (New Install)" | Engine: IPY277 (277) | Path: "C:\pyRevit\main" | AllUsers
main | Product: "2019.2.2 Hotfix" | Engine: IPY277 (277) | Path: "C:\pyRevit\main" | AllUsers
main | Product: "2018.3.3 Security Fix" | Engine: IPY277 (277) | Path: "C:\pyRevit\main" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\olalancette\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021.1.2 | Version: 21.1.20.44 | Build: 20201109_1530(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.1 (New Install) | Version: 20.2.12.1 | Build: 20200210_1400(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
2017.2 | Version: 17.0.1117.0 | Build: 20170118_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
2016 Service Pack 1 | Version: 16.0.462.0 | Build: 20150506_1715(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016\"
==> Running Revit Instances
PID: 10524 | 2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2019"
PID: 25092 | 2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2018"
==> User Environment
Microsoft Windows 10 [Version 10.0.18363]
Executing User: RCAA\olalancette
Active User:
Admin Access: No
%APPDATA%: "C:\Users\olalancette\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.7 v4.8 v4.X
Installed .Net-Core Target Packs: v2.1.500 v2.1.507
pyRevit CLI 4.8.5.0`

**Comment by eirannejad** [comment]
Fixed and will be published with next release

ALT+CLICK on the print tool and replace the two files with the files shared here to fix this issue in place
[Updated script.zip](https://github.com/eirannejad/pyRevit/files/6200655/Updated.script.zip)

**Comment by olalancette** [comment]
@eirannejad Thanks a lot ! It works.
