### ISSUE TITLE
Copy Sheets to Open Documents: not copying the views 

### ISSUE THREAD

**Issue by jdiam0nd** [eirannejad/pyRevit#1203]
I'm trying to use the Copy Sheets to Open Documents command under Drawing Set>Sheets.  GREAT TOOL!!  I used it successfully a week ago, and it was copying the sheets with titleblock, views on the sheets, and the tags, dims, text, etc. within those views.  Today, me and another user tried and it will only copy the sheet with titleblock.  The views never transition over to the new file, and of course, don't get placed on the sheets in the new file.  

I'm using v4.7.6 on Revit 2020.2.  I'm testing with 2 really simple files that I used (successfully) last weekend.  The pyRevit dialog that opens after the command completes will show that it completed successfully without errors.  However, the view is not on the sheet and is not listed in the project browser.   

![image](https://user-images.githubusercontent.com/52168749/112687312-b1b53180-8e4d-11eb-9b5a-49ae9d1c70b9.png)

![image](https://user-images.githubusercontent.com/52168749/112687334-bda0f380-8e4d-11eb-8343-31d1ff1f70b0.png)

![image](https://user-images.githubusercontent.com/52168749/112687358-c4c80180-8e4d-11eb-97ca-48249aa3d60c.png)
![image](https://user-images.githubusercontent.com/52168749/112687376-ca254c00-8e4d-11eb-9570-105317cc83a3.png)
![image](https://user-images.githubusercontent.com/52168749/112687392-d0b3c380-8e4d-11eb-82f6-19b2d2c86190.png)
![image](https://user-images.githubusercontent.com/52168749/112687588-12dd0500-8e4e-11eb-8b83-75e62e44d748.png)

**Comment by eirannejad** [comment]
The tool does not copy model views. They're a lot more complex to generate.

**Comment by chuongmep** [comment]
Im using V4.8.5 in Revit 2021.1, it working for me, please try to update.

**Comment by OttoOrlando** [comment]
PLEAS HELP! I got the same oroblem over here. I tried the Tool once. Back then it worked flawlessly. Now it just doesnt work anymore. under the exact same cirumstances!?!?
![bug](https://github.com/user-attachments/assets/ec3c8c2e-8ede-4f16-8349-bbe3c5281739)#
but the views are not copied to the new project..
![original](https://github.com/user-attachments/assets/08ec214d-99de-4362-92b8-4e7d642086f1)
ORIGINAL SHEET
![new](https://github.com/user-attachments/assets/8645e19b-0a59-49a5-b239-b1d27a1c76f8)
NEW SHEET
