### ISSUE TITLE
Output Styling (CSS Stylesheet) path is empty by default and doesn't persist through Revit restart

### ISSUE THREAD

**Issue by gsruff** [eirannejad/pyRevit#1204]
**Describe the bug**
In Settings->UI / UX->Output Window->Output Styling (CSS Stylesheet), the configured path is empty by default. Selecting Reset restores the default path. "Just Save Settings" or "Save Settings and Reload" applies the setting and causes the CSS file to be used correctly, but this setting does not persist through restarting Revit.

**To Reproduce**
1. Open the pyRevit settings window and expand the UI / UX settings group.
2. Confirm that Output Styling (CSS Stylesheet) path is empty by default.
3. Click "Reset" to restore the default path or the ellipses button to specify a custom path.
4. Click "Just Save Settings" or "Save Settings and Reload".
5. Confirm CSS style is being applied to the output window.
6. Restart Revit.
7. See steps 1 & 2.

**Expected behavior**
The Output Styling file path setting is set to the included CSS file by default. Resetting this or configuring a custom path persists through restarts of Revit.

**Screenshots**
![image](https://user-images.githubusercontent.com/41163946/112688895-e629ed00-8e4f-11eb-8ddc-9ff66e1cd4ef.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2 19042.870
 - pyRevit v4.8.6.0

**Comment by eirannejad** [comment]
So I made a change for pyRevit to always use it's internal preset path by default and does not store this default path in the config file. This is mainly to support more than one pyRevit clones on the machine. Is the output window losing styling for you on restart?!

**Comment by gsruff** [comment]
Correct--the output window is losing styling on restart. Thanks for reviewing!

**Comment by eirannejad** [comment]
I think this is the fix that I already made. If I would change the styling to my custom, it would not save that change. It's fixed now :D fingers crossed 😅
