### ISSUE TITLE
Naming format: Custom date format

### ISSUE THREAD

**Issue by houkvanlake** [eirannejad/pyRevit#1205]
Hello,

for Dates inside the NAMING FORMATS (inside PRINT SHEETS) if would be great if we could customize the format of the Date. This uses by default the following format: %Y-%m-%d

I have researched on the documentation and couldn't find out if this was already possible. Each country has different standards in dating format and that would be useful if we could completely change the format of the date such as: %d/%m/%Y or %Y%m%d.
The customization of the year format YYYY vs YY as 2021 or 21 would be useful too, or the month such as 02 or February, as well as any other customization.
It would be good if that would be implemented in any Date related category such as Proj_issue_date or rev_date.

Thanks a lot

**Comment by eirannejad** [comment]
Great suggestion!
