### ISSUE TITLE
ASCII Keynote Conversion Failed

### ISSUE THREAD

**Issue by nghesi** [eirannejad/pyRevit#1206]
As title, latest 4.8.6 verision installed. Conversion fail lead to loosing all contents without any option to recover

**Comment by eirannejad** [comment]
@nghesi pyRevit backs up the original keynote file in the same directory with the `.bak` extension. Change that to `.txt` and you will have the original text file

**Comment by nghesi** [comment]
[Keynotefiles.txt](https://github.com/eirannejad/pyRevit/files/6233326/Keynotefiles.txt)
I have to save as the file using UTF-16 format then the conversion is successful. However the issue may destroy the file completely which is a disaster

**Comment by eirannejad** [comment]
Okay test and confirmed the issue. This is BAD. :D I'll fix for next release

**Comment by eirannejad** [comment]
Fixed and will be published with next release 
- [X] No longer leaves the keynote file empty if conversion crashes
- [X] Now reads ASCII files with characters from `Windows-1252` and `ISO-8859-1` codepages

**Comment by eirannejad** [comment]
For the record, the issue was reading an ASCII file with extended characters from other codepages (e.g. `Ø` from `ISO-8859-1` in this case) in strict `encoding=ascii` mode
