### ISSUE TITLE
How to determine if using CPython from script

### ISSUE THREAD

**Issue by JBloss1517** [eirannejad/pyRevit#1207]
I am needing to change which module gets imported based on if the script is using IronPython or Cpython. Is there is an environment variable that I can check to determine if using CPython or IronPython?

I.e.

```python
if using_cpython:
    import rollbar38
else:
    import rollbar27
````

**Comment by eirannejad** [comment]
```python
from pyrevit import compat

if compat.PY3:
    import rollbar38
else:
    import rollbar27
```

**Comment by JBloss1517** [comment]
Awesome, I was sure you built in something already. Thank you for your prompt reply and building pyRevit, It's amazing!
