### ISSUE TITLE
PyRevit 4.8.7 'External Tool - Availability Command Load Failure' and PyRevit Ribbon Adjustment

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#1208]
**Describe the bug**
I installed the latest version of PyRevit 4.8.7 and I get this 'External Tool - Availability Command Load Failure" message and when I close the message dialog, Revit crashes.

**To Reproduce**
Installed the latest version of PyRevit and launch Revit 2020, close the 'External Tool - Availability Command Load Failure' message, and Revit crashed.

**Expected behavior**
Open without the "External Tool - Availability Command Load Failure" and won't crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/8776947/113706956-24889d00-96d7-11eb-8855-0c86afd12436.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.8.7 
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.
Microsoft Windows [Version 10.0.19041.867]
(c) 2020 Microsoft Corporation. All rights reserved.

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.7" | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2021" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2020" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
master | Product: "2019.2.2 Hotfix" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
master | Product: "2018.3.3 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
master | Product: "2017.2.5 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
master | Product: "2016.1.9 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
master | Product: "2015 Release 2 (Subscription only release)" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
master | Product: "2014 Update Release 3" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\rob.cross\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2021 | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
Autodesk Revit 2020 | Version: 20.2.30.42 | Build: 20200826_1250(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
2017.2.5 Security Fix | Version: 17.0.1169.0 | Build: 20190508_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
2016.1.9 Security Fix | Version: 16.0.1218.0 | Build: 20190508_0715(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016\"
2015 Release 2 (Subscription only release) | Version: 15.0.1103.0 | Build: 20140905_0730(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2015\"
2014 Update Release 3 | Version: 13.11.4 | Build: 20140709_2115(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2014\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

**Additional context**
Btw, I noticed the PyRevit ribbon tools need adjusting.

![image](https://user-images.githubusercontent.com/8776947/113707823-5d754180-96d8-11eb-9a00-811fba4274a3.png)

**Comment by Robbo1234** [comment]
Revit crashes now when I click on the PyRevit Ribbon.

![image](https://user-images.githubusercontent.com/8776947/113728153-ba2f2700-96ed-11eb-9e94-db53eff83304.png)
[journal.0059.txt](https://github.com/eirannejad/pyRevit/files/6265410/journal.0059.txt)

**Comment by eirannejad** [comment]
run a `pyrevit caches clear --all` and launch again. See if the error shows up still. I don't get anything on my machine. Do you have any documents open at the time of error?

**Comment by eirannejad** [comment]
The UI text size seems to be related to the DPI settings on your machine. pyRevit doesn't render the ribbon. That's all the UI framework in Revit

**Comment by Robbo1234** [comment]
Thanks, that seems to have work (well it hasn't crashed Revit) but I'm now getting this message when I click on the PyRevit tab.
![image](https://user-images.githubusercontent.com/8776947/113750186-63801800-9702-11eb-934a-8f2703a0f2c5.png)

**Comment by eirannejad** [comment]
No idea why this is happening :/

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists
