### ISSUE TITLE
Pick specific filters not filter

### ISSUE THREAD

**Issue by channond** [eirannejad/pyRevit#1209]
I would like to be able to pre filter(exactly like the pick tool) for example lighting fixtures and lighting fixture tags. But I just want it to do those on the button, not ask for any other options or categories.

I used to have a py script to do these individually(lighting fixtures only, but sadly doesnt seem to work on the latest build), but could not work out how to have an "AND" statement in the ISelectionFilter

Is this possible, and if so could you please share the code as I would like to create a few tools like this

**Comment by eirannejad** [comment]
Here is the code for the pick tool https://github.com/eirannejad/pyRevit/blob/master/extensions/pyRevitTools.extension/pyRevit.tab/Selection.panel/Pick.splitpushbutton/Pick.pushbutton/script.py

You can also Shift+Click on the pick tool to configure which categories you want to see on the options

**Comment by channond** [comment]
Thanks Ehsan.

Not quite what I was after, but I have found another addin that does what I
need (Filtermore) I will see if I can configure this to do what I want.
Basically I want to bypass the config popup in general. So I just need to
know what to replace line 13 with.  import pick_config

So if I wanted lighting fixture for example, would I just delete line 13
and replace  line 17 with my_config = "Lighting Fixtures"
I cant really understand what the OSD_Category means.
