### ISSUE TITLE
PyRevitLoader- Error Loading pyRevit

### ISSUE THREAD

**Issue by Bbartron061** [eirannejad/pyRevit#1210]
**Describe the bug**
Upon starting Revit 2021, PyRevit asks to load, and upon selecting "always load" the error below is generated. 

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.
* returned "'pyrevit' is not recognized as an internal or external command,
operable program or batch file."

`pyrevit attach master 277 --installed` * returned "'pyrevit' is not recognized as an internal or external command,
operable program or batch file."

**To Reproduce**
Occurs every time Revit is initiated.

**Expected behavior**
Error to occur and message pop up.

**Screenshots**
![error1](https://user-images.githubusercontent.com/82108050/113894440-39bc0500-9785-11eb-97ce-44325fc702e8.PNG)
![error2](https://user-images.githubusercontent.com/82108050/113894463-3e80b900-9785-11eb-9691-7828d9a3b8c3.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - pyRevit Version [e.g. 4.8.7]
 - pyRevit Environment: "'pyrevit' is not recognized as an internal or external command, operable program or batch file."

**Additional context**
Am I entering your commands incorrectly in my prompt?
![image](https://user-images.githubusercontent.com/82108050/113895660-6cb2c880-9786-11eb-86db-51bc713443ef.png)

**Comment by eirannejad** [comment]
Ok I'll look into this. You can remove the config file at `C:\ProgramData\pyRevit\pyRevit_config.ini` and it should load after

**Comment by Bbartron061** [comment]
Thank you- this seems to have solved the issue.
