### ISSUE TITLE
Question: How do I start a simple http server from Revit without blocking the main thread?

### ISSUE THREAD

**Issue by JBloss1517** [eirannejad/pyRevit#1211]
I am trying to serve a static and local mkdocs website for documentation of the various buttons in our toolbar. The trouble I keep running into is either the server is running but Revit is blocked or the server gets started but (despite my best efforts) the server keeps getting killed once the script gets to the end. I am sure I am missing something obvious here, but I am running out of ideas of where I am going wrong. 

It looks like there might be something in the `pyrevit.routes` module that I can either use or borrow the approach, but I'm not quite sure how to adapt that module for my use case.

Here is what I have tried so far. . .

using ironpython and subprocess module (I tried this as both a button and a startup script). As a button it raises a 
`WindowsError: [Errno 13] Access is denied`  but as a startup script it starts the server but blocks the main process and locks up Revit until I close the server:
```python
import subprocess
import os

cwd = os.path.dirname(__file__)

subprocess.call("{}\lib\Python38\python.exe -m http.server 1600 --bind 127.0.0.1".format(cwd))
print("Documentation Server is running")
```

using Cpython and the threading module:
```python
#! python3
import http.server
import socketserver
import threading
import socket

# I've tried both True and False for these and get the same issue of the server being killed prematurely 
__persistentengine__ = True 
__cleanengine__ = True

def start_server():
# most of this was pulled directly from python documentation. 
    try:
        HOST, PORT = "localhost", 1600
        handler = http.server.SimpleHTTPRequestHandler
        print("Server is not running. Starting server...")
        with socketserver.TCPServer((HOST, PORT), handler) as server:
            print("serving at {} port: {}".format(HOST, PORT))
            server.serve_forever()
    except Exception as e:
        print("Error: {}".format(e))

if __name__ == "__main__":
    if server_running(): # simple function that checks if port 1600 is open or not. Not showing here for brevity, but does work as expected
        print("Server is running at {} port:{}".format("localhost", 1600))
    else:
        print("Server is not running")
        server_process = threading.Thread(target=start_server)
        print("Calling start_server()")
        server_process.start()
    print("Exiting script")
```

I have also tried using the .NET `System.Diagnostics.Process.Start()` to get the server to start but was getting the same thing as the Cpython + threading approach where the server would start but be killed as soon as the script ended.

**Comment by eirannejad** [comment]
So this is a big topic. The short answer is that you need to design the server to work with the Revit idle event handler. I have already done this for pyRevit and it is called the Routes module

see the source here
https://github.com/eirannejad/pyRevit/tree/master/pyrevitlib/pyrevit/routes

and notes here
https://www.notion.so/pyRevit-Routes-HTTP-API-79ef6d4a77b04aca9be6f4e46ffa728e

**Comment by eirannejad** [comment]
I'll close this since it is a question but continue the discussion please

**Comment by JBloss1517** [comment]
Thank you for your quick response and that's great to hear that you got a server running in Revit. Looking at the Routes module and the documentation more, it looks like I need to ensure I provide a `callbackURL` in the data sent by the HTTP request. What I'm still a little confused about, and Revit is still giving me issues with, is with trying to start the server. Even with going through the router API and using the callback option. 

The error that I get is a generic `urllib2.HTTPError: HTTP Error 500: Internal Server Error` which doesn't give much feedback. 

Am I using your server the way you intended? Or is there a better way?

Here is what I am trying...
```python
import socket
import urllib
import urllib2
import SimpleHTTPServer
import SocketServer 
import subprocess
import os

# putting all of the routes and route calls in a script.button to speed up the development process.
# I plan on moving the api and routes to a startup script once it is working.

from pyrevit import routes

api = routes.API("myapi")

# http://ip:port/myapi/home/
@api.route("/home/", methods=["GET", "POST"])
def welcome(request):
    if request.data:
        return routes.make_response(data=request.data)
    else:
        return routes.make_response(data="No Data")


# http://ip:port/myapi/start_doc_server/
@api.route("/start_doc_server/", methods=["GET", "POST"])
def start_doc_server(request):
    if request.data:
        try:
            cwd = os.path.dirname(__file__)
            # if I comment the next line out, the api works no problems and returns "Made it" to '/home/'
            subprocess.call(["cmd /c start http://127.0.0.1:1600 & python.exe -m http.server 1600 --bind 127.0.0.1"])
            return routes.make_response(data="Made it")
        except Exception as e:
            return routes.make_response(data=e)
    else:
        return routes.make_response(
            data="Did not find any data in request. Must send data with 'callbackUrl' in the data to start the server"
        )

# making the web request
ip = socket.gethostbyname(socket.gethostname())
url = "http://{}:48884/myapi/start_doc_server/".format(ip)
callback_url = "http://{}:48884/myapi/home/".format(ip)

values = {"callbackURL": callback_url}

data = urllib.urlencode(values)
req = urllib2.Request(url, data)
response = urllib2.urlopen(req)
print(response.read())
```
