### ISSUE TITLE
Load Error: Xceed.Wpf.AvalonDock is not found

### ISSUE THREAD

**Issue by jpascucci25** [eirannejad/pyRevit#1213]
![PyRevit Error in R19](https://user-images.githubusercontent.com/75704105/114085337-3c9b2080-987f-11eb-8000-3e3e7ad47252.jpg)

**Comment by jpascucci25** [comment]
This is Revit 2019

**Comment by lindstrom-hsuoffice** [comment]
Exact same thing here...not sure that it's important, but started after update to 2019 hotfix 2 (to try to fix other unrelated issues). 
![2021-04-12 22 05 23](https://user-images.githubusercontent.com/80073442/114495406-3be5ef80-9bdb-11eb-9403-9d1a48767b96.png)

**Comment by eirannejad** [comment]
Run a `pyrevit caches clear --all` on command line and open Revit again. This might help.

**Comment by eirannejad** [comment]
Also open the `%APPDATA%\pyRevit\2019` folder and send me the `pyRevit_2019_***_PyRevitLabs.PyRevit.Runtime.log` file. This shows which `Xceed.Wpf.AvalonDock.dll` is used by pyRevit
