### ISSUE TITLE
Error in Transaction Context

### ISSUE THREAD

**Issue by brzesiak** [eirannejad/pyRevit#1216]
Hello, i have this issue report:

> ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:Model lines can not be drawn in current view.

Don't know what happend. No updates since last use. Revit 2020

**Comment by eirannejad** [comment]
I need more info. Which tool is this?!

**Comment by eirannejad** [comment]
Not enough info
