### ISSUE TITLE
PyRevitLoader - Error Loading PyRevit

### ISSUE THREAD

**Issue by SeanKellyRJC** [eirannejad/pyRevit#1222]
Hi,
I have a user using PyRevit 4.8.5. This is the error they get when trying to load PyRevit. This is only this user, most users it works fine on. I have uninstalled and reinstalled a couple times to no result.
![image](https://user-images.githubusercontent.com/49038759/115268565-a1fcd600-a0f7-11eb-8338-97d6ee0a0987.png)

**Comment by SeanKellyRJC** [comment]
Its worth noting that when the user installs 4.8.7 the issue goes away. The user at one point had 4.8.7 installed and when we pushed out 4.8.5 via SCCM is when the issue cropped up.

**Comment by eirannejad** [comment]
@SeanKellyRJC So you reverted to an older version?

**Comment by SeanKellyRJC** [comment]
Correct the issue occurred when when the user reverted to the older version. We had started our deployment prior to 4.8.7 being released, then the user installed 4.8.7 on his own accord and then our SCCM deployment reinstalled the older version which brought about the issue. Eventually we will get everyone on 4.8.7 or newer as time and direction from stake holders permits

**Comment by eirannejad** [comment]
Run a `pyrevit caches clean --all` on the machine to clean all pyRevit caches and see if this fixes the issue

**Comment by SeanKellyRJC** [comment]
I'll do that if it happens again. For now this particular user can just use 4.8.7. Thanks for the help.
