### ISSUE TITLE
Create Pattern not working in Revit 2022?

### ISSUE THREAD

**Issue by sammartineau1001** [eirannejad/pyRevit#1224]
**I'm getting an error message while trying to creat pattern in Revit 2022:**

_IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\X\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Modify.panel\edit1.stack\Patterns.splitpushbutton\Make Pattern.pushbutton\script.py", line 38, in <module>
AttributeError: 'Autodesk.Revit.DB' object has no attribute 'DisplayUnitType'

Script Executor Traceback:
System.MissingMemberException: 'Autodesk.Revit.DB' object has no attribute 'DisplayUnitType'
 à IronPython.Runtime.Binding.PythonGetMemberBinder.NamespaceTrackerDelegate.Target(CallSite site, Object self, CodeContext context)
 à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 à Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 à Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 à Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 à IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 à PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)_

**Comment by eirannejad** [comment]
Fixed and will be published with next release

**Comment by sammartineau1001** [comment]
Has the fixed been released? I cant make pattern yet. Ty a lot!
