### ISSUE TITLE
Copy Sheets to Other Documents Issue

### ISSUE THREAD

**Issue by Kelei1982** [eirannejad/pyRevit#1226]
![image](https://user-images.githubusercontent.com/27847906/115542860-4e46e400-a2d3-11eb-969f-58fa7d165a35.png)

I found when my source file, if there are only elevation views in the sheet view,
or sometimes have Plan view + Elevation View in sheet.

That would not be able to copy all the views to the target file.

**Comment by Kelei1982** [comment]
![image](https://user-images.githubusercontent.com/27847906/115543874-75ea7c00-a2d4-11eb-8f08-40378d28c2c5.png)
It will appear the error message as captured, seems it have some miss understanding to the view names.

**Comment by eirannejad** [comment]
So just making sure you know this tool does not move model views right?

**Comment by Kelei1982** [comment]
> So just making sure you know this tool does not move model views right?

yes, the function doesn't move the model views, thanks !

**Comment by Akimyss** [comment]
Just trying to help. There is a free revit add-in called "Transfer Views" by Pomerleau to copy views from linked model. Perhaps, you can try copy the views first with this addin then run the PyRevit "Copy Sheets to Open Documents".
