### ISSUE TITLE
Installing pyRevit 4.8.7 as admin sets environment variables as user instead of system

### ISSUE THREAD

**Issue by guusgooskens** [eirannejad/pyRevit#1228]
**Describe the bug**
Installing pyRevit 4.8.7 as admin sets environment variables as user instead of system.

**To Replicate**
1. Install pyRevit as normal user with elevated admin rights
2. As a result, it sets a user variable for the admin account (ops) but not a system variable for all users on the machine.

Not sure if this is expected behaviour, but it is desired in our case.

**Screenshots**
![pyrevit-install-as-admin-error](https://user-images.githubusercontent.com/73542374/116059679-6034d800-a681-11eb-9de4-da34027f73be.png)

**Comment by eirannejad** [comment]
Ooops. Okay I'll fix this. Thanks for catching it!

**Comment by eirannejad** [comment]
Fixed and will be published with next release
