### ISSUE TITLE
Installation does not work: path does not point to valid clone

### ISSUE THREAD

**Issue by linjac** [eirannejad/pyRevit#1229]
**Describe the bug**
I downloaded pyRevit and it did not load. I attempted to follow the steps outlined in this Notion article: [pyRevit is Installed But Does Not Load](https://www.notion.so/pyRevit-Is-Installed-But-Does-Not-Load-f6495adb56254e9e8021f8a68e3b2ab7). However I got an error.

**Expected behavior**
I expect to be able to register the master clone by running:
'pyrevit clones add master <installation path>' However I get the following error message:
![image](https://user-images.githubusercontent.com/49277237/116125133-5d86b280-a682-11eb-9857-38c3b1efa1e6.png)

I'm quite sure I got the installation path name correct:
![image](https://user-images.githubusercontent.com/49277237/116124997-3a5c0300-a682-11eb-9e7d-826a1a5b949f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 
 - OS Build: 19042.928 
 - pyRevit Version:
![image](https://user-images.githubusercontent.com/49277237/116125507-cf5efc00-a682-11eb-8f33-662beeea86f4.png)

 - pyRevit Environment: 
![image](https://user-images.githubusercontent.com/49277237/116125590-ebfb3400-a682-11eb-8491-38a11578e88f.png)

**Comment by eirannejad** [comment]
I'm pretty sure you have installed the pyRevit CLI instead of pyRevit itself. Use the installer here
https://github.com/eirannejad/pyRevit/releases/tag/v4.8.7

**Comment by eirannejad** [comment]
Not enough info
