### ISSUE TITLE
Make Pattern 'Rotation (in Degrees)' will not 'Export PAT File' 

### ISSUE THREAD

**Issue by scottdurkee-sa** [eirannejad/pyRevit#1233]
**Describe the bug**
Make Pattern 'Rotation (in Degrees)' will not 'Export PAT File' without doing 'Create Pattern' first

Workaround: Create rotated Pattern first, then Export PAT file

**To Reproduce**
1. Select a Filled Region that uses a Model Fill Pattern
2. Go to 'pyRevit | Modify | Make Pattern'
3. Enter New Pattern Name
4. 'Pattern Type | Model Pattern'
5. 'Resolver Options | Rotation (in Degrees)' enter 90
6. Select 'Export PAT File'
7. Pick origin (bottom-left)
8. Pick top-right
9. Select 'OK'

resulting PAT file is not a rotated version of the pattern.

**Expected behavior**
Would expect 'Export PAT File' to use options in the dialog

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - pyRevit Version 4.8.4
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.4" | Path: "C:\Users\sdurkee\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2019.2.2 Hotfix" | Engine: 277 | Path: "C:\Users\sdurkee\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\sdurkee\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
master | Product: "2018.3.3 Security Fix" | Engine: 277 | Path: "C:\Users\sdurkee\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\sdurkee\AppData\Roaming\Autodesk\Revit\Addins\2018\pyRevit.addin"
master | Product: "2017.2.5 Security Fix" | Engine: 277 | Path: "C:\Users\sdurkee\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\sdurkee\AppData\Roaming\Autodesk\Revit\Addins\2017\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\sdurkee\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2021 | Version: 21.1.21.45 | Build: 20201116_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
2017.2.5 Security Fix | Version: 17.0.1169.0 | Build: 20190508_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
==> Running Revit Instances
PID: 4020 | 2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> User Environment
Microsoft Windows 10 [Version 10.0.19042]
Executing User: SA\sdurkee
Active User: SA\sdurkee
Admin Access: No
%APPDATA%: "C:\Users\sdurkee\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.4.0`

**Additional context**

**Comment by eirannejad** [comment]
That's how the tool is intended to be used for now :D It's just a quick step I guess unless you are rotating and exporting a lot of patterns
