### ISSUE TITLE
Remove Empty Tags - Internal error

### ISSUE THREAD

**Issue by gdemol** [eirannejad/pyRevit#1236]
When using the tool "Remove empty tags" I get this error:
![image](https://user-images.githubusercontent.com/17804567/117423029-89c2ee80-af20-11eb-927e-39a54799f8ca.png)

![image](https://user-images.githubusercontent.com/17804567/117422963-77e14b80-af20-11eb-88eb-9bd494c81580.png)

What could be wrong? I would love to use this tool again :)

**Comment by gdemol** [comment]
OS: Windows
pyRevit Version: 4.8.7

**Comment by eirannejad** [comment]
Internal errors are errors that happen inside Revit API itself. Would it be possible to share an example and simple Revit model that causes this issue? Also filling the requested into on the "new bug" template helps me ask fewer questions :D

**Comment by gdemol** [comment]
You are right! It only happens in this one project build with another 3th-party template than I normally use.

Excuse me! I will try create a simple Revit project where this problem is reproduced and fill in the Bug report.

**Comment by gdemol** [comment]
**Explain how to reproduce the error**
The problem only exists when I try to remove empty Tags from tagged elements in Linked models. I attached "project_R20" and the linked model "project_link_R20" in which the problem can be reproduced.
[Models to reproduce problem with remove empty tags_R20.zip](https://github.com/eirannejad/pyRevit/files/6603438/Models.to.reproduce.problem.with.remove.empty.tags_R20.zip)



**Explain the expected behaviour**
When I use the tool on this situation:
![image](https://user-images.githubusercontent.com/17804567/120908889-68643800-c66f-11eb-86a9-831967d1bfc3.png)

I get this error:
![image](https://user-images.githubusercontent.com/17804567/120908901-8b8ee780-c66f-11eb-86cf-d49d45749414.png)

When I remove the tag attached to the element from the linked model the tool runs without errors.
