### ISSUE TITLE
Install pyRevit 4.8.8 successfully but cannot run into Revit 2022

### ISSUE THREAD

**Issue by PymPhekasut** [eirannejad/pyRevit#1243]
My Revit version is 2022 and pyRevit version 4.8.8 latest version.

I install pyRevit on %AppData% successfully but when it load on Revit, I got error as shown below . It is pop-up when open Revit.

 Also I follow instruction through comment #1075 but it does not work. Could you please help me this issue? I appreciate that.

![error](https://user-images.githubusercontent.com/74609915/118490310-26775e80-b761-11eb-8af1-ae0098b78480.PNG)

`pyrevit clones add master "C:\Users\nphekasut\AppData\Roaming\pyRevit-Master"`

![1](https://user-images.githubusercontent.com/74609915/118490192-08116300-b761-11eb-9cb5-f9b3fc79d0f8.PNG)

`pyRevit env`

![2](https://user-images.githubusercontent.com/74609915/118490522-5de60b00-b761-11eb-8bae-3517b88c3c4a.PNG)

**Comment by eirannejad** [comment]
Are you opening multiple instances of Revit in a short time? They might be competing for access to the config file. Does this still happen if you open 2022 by itself?

**Comment by PymPhekasut** [comment]
I fix it by following instruction from another issue. Thank you so much

**Comment by eirannejad** [comment]
Closing this but please continue the discussion

**Comment by FB-JHowe** [comment]
@ob-bim [Here's what worked for me.](https://github.com/eirannejad/pyRevit/issues/1280) Basically- needed to nuke the existing pyrevit config file: "c:\programdata\pyrevit\pyrevit_config.ini" Then manually run the seed command again "pyrevit configs seed". Note that you can't just launch Revit after deleting the configs, the seed command has to be run before you launch revit. Hope that helps.
