### ISSUE TITLE
pyRevit won't load on my Revit 2020 - Can not create tab.

### ISSUE THREAD

**Issue by Fozibehr** [eirannejad/pyRevit#1244]
I get the following error when opening up pyRevit 4.8.8 my Revit 2020.  I see what it says but not sure how to follow it. Any suggestions?

ERROR [pyrevit.loader.uimaker] UI error: Can not create tab: Too many tabs have been created by the API. Instead, you may add your Ribbon Panels to the Add-Ins tab.

**Comment by eirannejad** [comment]
Probably have too many addons installed?

**Comment by Fozibehr** [comment]
@eirannejad ...Probably...the newer Revits don't seem to have that limitation, or at least I haven't hit that wall yet. It's not a huge deal as I don't do much in 2020 except for a few legacy jobs.
