### ISSUE TITLE
No attachment to existing Revit after reinstalling pyrevit v4.8.8

### ISSUE THREAD

**Issue by carlpach** [eirannejad/pyRevit#1245]
Hi @eirannejad , big congrats for your amazing work with pyrevit! Working with it for more than 2 years and this is my first question:

I have a problem now when installing pyrevit 4.8.8 and implementing deployment with pyrevit CLI:

After installing pyrevit with the installer there aren't attachments to existing Revit in my machine (Windows 10).
- I have run `pyrevit attach master 277 --installed` but .addin file is not pasted in Revit folder
- I don't have the Nlog module in \bin
- the outcome of  `pyrevit env` is this:
![image](https://user-images.githubusercontent.com/60277465/118846318-e2a16800-b8cc-11eb-9679-ade071cd2bbc.png)

Thank you for your support!
Carlos

**Comment by eirannejad** [comment]
Thank you. For some reason pyRevit is not finding any installed Revits on this machine.

**Comment by carlpach** [comment]
Yes, Revit 2019 is installed in `C:\Program Files\Autodesk\Revit 2019`

Thank you

**Comment by eirannejad** [comment]
Ok. Run `pyrevit revits --installed --debug` and share the debug report please :D

**Comment by carlpach** [comment]
Thank you:
![image](https://user-images.githubusercontent.com/60277465/119160160-40ae8680-ba58-11eb-8090-b301e8aa45f3.png)

**Comment by eirannejad** [comment]
Hmm. This is so odd. pyRevit CLI should be able to read your registry. Seems like it can't. Do you (or your IT)  have specific permissions on this machine that prevents that?

**Comment by carlpach** [comment]
No that I know. It's fine I will reinstall the whole thing,

Thanks for replying! ;)

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists
