### ISSUE TITLE
pyRevit.CLI_4.8.7 silent switches

### ISSUE THREAD

**Issue by eskonr** [eirannejad/pyRevit#1246]
Hi,
i am trying to install pyRevit.CLI_4.8.7_signed.exe silently on remote machines but i could not find any silent install switches that i can get it work. 
I have tried the following but it always prompt UI.
pyRevit.CLI_4.8.7_signed.exe /exenoui
I have got the above silent switches from -help function.

Is there any silent command line switches that i can perform on remote devices?

Appreciate your help on this.

Thanks,
Eswar

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists
