### ISSUE TITLE
PyRevit won't load

### ISSUE THREAD

**Issue by Luis-B-A** [eirannejad/pyRevit#1248]
![image](https://user-images.githubusercontent.com/84584272/119162809-17432a00-ba5b-11eb-8538-298893c38b77.png)
![image](https://user-images.githubusercontent.com/84584272/119162823-1ca07480-ba5b-11eb-870e-1d14ae589fdd.png)
Whenever I try to open PyRevit I get the error shown in the screenshots. I have found some similar issues online but the only solution that I could find was uninstalling other add-ins, and I can't really miss any of the ones I have installed. Wanted to check if there were other possibilities to fix this. Added a screenshot of the add-ins I use for reference.
![image](https://user-images.githubusercontent.com/84584272/119163088-5ffae300-ba5b-11eb-8d36-dc9465447f17.png)

**Comment by TatyanaFrolova** [comment]
I have the same problem, after installing pyRevit I also get this error.

**Comment by lrhammar** [comment]
I get the same problem, I put in an issue but i guess i just bump this one

**Comment by eirannejad** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/1280
Closing this to follow the linked issue for a fix
