### ISSUE TITLE
app-idling memory leak

### ISSUE THREAD

**Issue by alexdaversa** [eirannejad/pyRevit#1252]
Hi Ehsan,

I believe I have found a memory leak of sorts in the app-idling hook.

To reproduce, add an empty app-idling.py file to the hooks folder of a loaded extension and reload pyRevit/restart Revit. In task manager you can see the memory keep climbing. If left long enough (varies depending on your installed ram, from a few hours to a few days), this will cause windows to close applications to preserve itself--though it does not seem to close Revit.

I will be continuing to investigate through the code (although it unfortunately will not be my highest priority--the app-idling hook was emptied because I no longer need to use that hook). I would appreciate any insight you have and understand this may be something internal to Revit and thus not fixable on our end.

**Comment by eirannejad** [comment]
Okay I'll look at the code. I have a hunch this is the IronPython engine that is causing it but gotta figure out why
