### ISSUE TITLE
Pyrevit 4.8.8 Features not working.

### ISSUE THREAD

**Issue by kaykhanolkar** [eirannejad/pyRevit#1254]
I have installed Pyrevit 4.8.8 on Revit 2021. Everytime I open Revit, I get these dialogue boxes. Though Pyrevit is installed, some of the features aren't working. 

![Pyrevit - Hatch pattern](https://user-images.githubusercontent.com/76408936/119833900-6673d980-bef7-11eb-9b1e-eaa64c2bf6ae.JPG)
![Pyrevit - Hatch pattern_error](https://user-images.githubusercontent.com/76408936/119833906-67a50680-bef7-11eb-9321-050c5cf4c8e6.JPG)
![Pyrevit](https://user-images.githubusercontent.com/76408936/119833910-683d9d00-bef7-11eb-9edf-85cba5445fbe.JPG)

**Comment by kaykhanolkar** [comment]
Please could someone look at the issue urgently....

**Comment by melnikovalex** [comment]
Hi @kaykhanolkar! I had similar problem with other scripts and configurations recently. 

To wit, once any script which changes pyRevit_config startet I had an Error (same as on your screenshots):

`ERROR [pyrevit.userconfig] Can not save user config to: None ...`

The solution for me was: delete pyRevit_config.ini file in the installation folder (C:\ProgramData\pyRevit-master by default, admin rights needed)

It looks like pyRevit trying to write in a file, which was created and therefore locked by administrator. Looks like a bug, @eirannejad?

**Comment by kaykhanolkar** [comment]
Hi melnikovalex, 
Thank you very much for your response. 

For some reason, Pyrevit decided to install itself on C:/Users/AppData/Roaming/pyRevit and C:/Users/AppData/Roaming/pyRevit-Master. So I uninstalled it, deleted the folder from AppData location and reinstalled it on C:\ProgramData\pyRevit. 

Worked like a charm. No errors when I started Revit. 

Your help is much appreciated. 
Thank you.

**Comment by eirannejad** [comment]
Omg. Seems like I have messed up the config file reading mechanism this time.
Underlying issue seems to be related to https://github.com/eirannejad/pyRevit/issues/1280

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists
