### ISSUE TITLE
DLL error

### ISSUE THREAD

**Issue by gabec77** [eirannejad/pyRevit#1255]
Installed pyrevit 2.8.8 (the latest).  It works in Revit 2022 but now 2021, 2020, 2019 we get an error about the pyrevitloaader.DLL does not exist.  We tried to copy and paste from another pc and it didn't fix it.  Any ideas?

pyrevit attach master 277 --installed --debug
<clone_name> = master
attach = True
<engine_version> = 277
--installed = True
Debug: Checking for all: wiki
Debug: Missing: wiki
Debug: Checking for all: blog
Debug: Missing: blog
Debug: Checking for all: docs
Debug: Missing: docs
Debug: Checking for all: source
Debug: Missing: source
Debug: Checking for all: youtube
Debug: Missing: youtube
Debug: Checking for all: support
Debug: Missing: support
Debug: Checking for all: env
Debug: Missing: env
Debug: Checking for all: update
Debug: Missing: update
Debug: Checking for all: clone
Debug: Missing: clone
Debug: Checking for all: clones
Debug: Missing: clones
Debug: Checking for all: attach
Debug: Try getting config as dict "environment:clones"
Debug: Try getting config "environment:clones"
Debug: Config "environment:clones" = "{}"
Debug: Updating config "environment:clones = {}"
Debug: Saving config file "C:\Users\mcox\AppData\Roaming\pyRevit\pyRevit_config.ini"
Error: Can not find clone "master" (pyRevitLabs.Common.PyRevitException)
   at pyRevitLabs.PyRevit.PyRevitClones.GetRegisteredClone(String cloneNameOrRepoPath)
   at pyRevitCLI.PyRevitCLI.ProcessArguments()
   at pyRevitCLI.PyRevitCLI.Main(String[] args)

**Comment by eirannejad** [comment]
Please install pyRevit using the provided installer. Or use the pyRevit CLI. https://www.notion.so/pyRevit-CLI-c50de95259114db795db5bd3f19f8e2a
