### ISSUE TITLE
CLI pyrevit configs seed command not working as expected

### ISSUE THREAD

**Issue by lexiko80-LPA** [eirannejad/pyRevit#1266]
**Describe the bug**
Have recently upgraded from CLI 0.17.0.0 & PyRevit 4.7.4 to CLI 4.8.8 and PyRevit 4.8.8
Uppon running the configs seed command the following error message returns
`Error: Failed seeding config file. | The process cannot access the file ‘C:\ProgramData\pyRevit\pyRevit_config.ini’ because it is being used by another process.`

Have tried checking if config in is locked before and after command is run, it is not
Have tried deleting config.ini and running again, same error

**To Reproduce**

1. Uninstalled CLI and installed new CLI
2. Deleted old pyRevit folder and copied over new (4.8.8) folder
3. Run pyrevit configs commands
4. Run pyrevit seed command

**Expected behavior**
I expected the seed command to update the config file in %PROGRAMDATA%

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10.0.18363 Build 18363
 - pyRevit Version 4.8.8
 - pyRevit Environment: 

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
Error: Error reading deployment arguments from "C:\LPAID\pyLPA\pyRevit-LPA-488" | Could not find file 'C:\LPAID\pyLPA\pyRevit-LPA-488\.pyrevitargs'.
Run with "--debug" option to see debug messages
```

**Additional context**
I'm not using git to download the pyrevit folder to users' PC's. I use a deployer to copy the folder from a network location to the user c:\ drive.
See forum post: [https://discourse.pyrevitlabs.io/t/configs-seed-error/441](url)

**Comment by eirannejad** [comment]
Same underlying problem as https://github.com/eirannejad/pyRevit/issues/1280

**Comment by snowyweston** [comment]
I _think_ I'm seeing the same, or at least similar: 
![image](https://user-images.githubusercontent.com/46787513/130328507-f09ea7e9-50f5-4e14-bc49-3ab0950b88ce.png)
this after install, and again after a restart, of Windows 19042, running Revit 2021.1.4

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists

**Comment by FB-JHowe** [comment]
@snowyweston @lexiko80-LPA Not sure if you've run into continuing issues, I have been having problems even with the latest 4.8.9.21361+0320 admin (Programdata not appdata installer. This fix seems to do the trick for me: https://github.com/eirannejad/pyRevit/issues/1243#issuecomment-1022495668

**Comment by Thomas84** [comment]
I still have problem that the seed command doesn't work:

https://discourse.pyrevitlabs.io/t/cloning-pyrevit-and-our-extensions-for-deployment-with-powershell-doesnt-work/1013/7
