### ISSUE TITLE
Preflight Checks need to be more specific

### ISSUE THREAD

**Issue by jhafel** [eirannejad/pyRevit#1267]
The Preflight checks are an incredible way to keep the team following Revit best practices, but the preflight checks are too vague to really make any proper changes if an issue comes up.

An example of this would be the reference planes check which told us we had 44 unnamed reference planes in our project but did not tell us any locations or how to fetch them. we went through each view and found 40 of the 44, but 4 of them are eluding us.

Another example would be the schedule checker. the preflight says we have over 100 schedules and 103 are not even on sheets, but the schedules section within Revit only shows 30 schedules overall. It would be nice to see what the preflight is considering to be a schedule. (Even if it's just a static list of schedule names that I can right-click within the project browser and search for it)

This feature is such a good tool and can't wait to see it developed further!

**Comment by jmcouffin** [comment]
https://github.com/eirannejad/pyRevit/pull/1277
you could add this file to your checks folder:
https://github.com/eirannejad/pyRevit/blob/55b9d281cdef9de88a597e40958b049cfb5e5d24/extensions/pyRevitTools.extension/checks/refplanes_check.py

**Comment by jmcouffin** [comment]
and add this one to check schedules not on sheet: 
https://github.com/eirannejad/pyRevit/blob/e9f9c861ad45c855ed8bfcf0577811a51eb8430b/extensions/pyRevitTools.extension/checks/schedules_not_on_sheet_check.py
**note** I think there is a mistake in the modelchecker check in the schedule not on sheet section. The way it is handled and quantify seems wrong. Don't have time to modify it right now.
