### ISSUE TITLE
Change Level move objects

### ISSUE THREAD

**Issue by nnevynn** [eirannejad/pyRevit#1269]
**Describe the bug**
When using Change Level on air terminals, the object moves. This did not happen on earlier version on Revit 2019. Now on Revit 2021 with latest version this sadly happens. Ducts stays in place though. 

**To Reproduce**
1. Mark air terminals
2. Go to "pyrevit MEP"
3. Click on "change level"
4. Choose an level and press "ok"
5. object moves and error "the duct/pipe has been modified to be in the opposite direction causing the connections to be invalid". If change level to a level below the current, objects moves without error. 

**Expected behavior**
I expect the level parameter to change without moving the object. 

**Screenshots**
![image](https://user-images.githubusercontent.com/85562296/121311683-f0af3b00-c904-11eb-8c80-a58bbce7d182.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - pyRevit Version V4.8.8
 - pyRevit Environment: 
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.8" | Path: "C:\Users\sorerosb\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2021.1.3" | Engine: IPY277 (277) | Path: "C:\Users\sorerosb\AppData\Roaming\pyRevit-Master"
master | Product: "2020.2.4" | Engine: IPY277 (277) | Path: "C:\Users\sorerosb\AppData\Roaming\pyRevit-Master"
master | Product: "2019.2.3" | Engine: IPY277 (277) | Path: "C:\Users\sorerosb\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\sorerosb\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021.1.3 | Version: 21.1.30.74 | Build: 20210426_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.4 | Version: 20.2.40.65 | Build: 20210420_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.3 | Version: 19.2.30.41 | Build: 20210416_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
PID: 11440 | 2021.1.3 | Version: 21.1.30.74 | Build: 20210426_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2021"
==> User Environment
Microsoft Windows 10 [Version 10.0.19042]
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.8.0
`pyrevit env`

**Additional context**

**Comment by eirannejad** [comment]
This seems to be a question for pyApex addon. Please ask [here](https://github.com/apex-project/pyApex) or on the https://discourse.pyrevitlabs.io

**Comment by nnevynn** [comment]
How could it be pyApex when it's clearly pyRevit installed? Never used pyApex so don't know what that is even?

**Comment by eirannejad** [comment]
pyApex is an extension for pyRevit developed by https://github.com/apex-project/pyApex
