### ISSUE TITLE
Revit 2022 does not load 4.8.8

### ISSUE THREAD

**Issue by aksrocks54** [eirannejad/pyRevit#1270]
The plugin does not load. After clicking on always load, revit 2022 just hangs with no error messages at all. I have removed all other plugins to prevent any conflicts with other plugins but the result is the same. I've also followed the instructions below and master is attached. I've attached the log file for debugging the issue.

https://www.notion.so/pyRevit-Is-Installed-But-Does-Not-Load-f6495adb56254e9e8021f8a68e3b2ab7

[pyRevit_2022_45059bd20577062f_PyRevitLabs.PyRevit.Runtime.log](https://github.com/eirannejad/pyRevit/files/6628832/pyRevit_2022_45059bd20577062f_PyRevitLabs.PyRevit.Runtime.log)

**Comment by ArchTuan194** [comment]
I cannot load 4.8.8 in revit 2022. Please help me!
![image](https://user-images.githubusercontent.com/86091969/122504652-e687ed80-d024-11eb-8029-1ed6399068a2.png)
![image](https://user-images.githubusercontent.com/86091969/122504662-ea1b7480-d024-11eb-8884-9631a7c9b1ff.png)

**Comment by eirannejad** [comment]
Same as https://github.com/eirannejad/pyRevit/issues/1210
Closing this so please follow the other issue for the fix

**Comment by aksrocks54** [comment]
Hi. I'm sorry but I started this thread and the issue reported by me is different from ArchTuan194. Nonetheless, I have tried the resolution listed at #1280  as well as the instructions listed at
https://www.notion.so/pyRevit-Is-Installed-But-Does-Not-Load-f6495adb56254e9e8021f8a68e3b2ab7

The problem is the same as described in my original post and the debug log file was also attached with it.

**Comment by hvacengi** [comment]
I have a similar same issue as @aksrocks54.  In my specific case, Revit 2022 shows the splash screen at startup, the pyRevit dialog box never displays (I have verbose set to true), and after a short period Revit 2022 just closes with no error message (the splash screen is present up until revit closes).  If I detach pyRevit from 2022, it opens properly.  Revit 2022 worked with pyRevit as recently as last week.  I did recently install Revit 2022.0.1 Hotfix, however the initial report of this issue (assuming it is the same issue) predates that update (released 2021-06-23). 

I looked at my pyRevit log and it is very similar, with only actual installed paths appearing to be the difference.  I'm uploading here in case it helps.  I'm also happy to provide whatever assistance I can in testing.
[pyRevit_2022_c4f0faa00bd417af_PyRevitLabs.PyRevit.Runtime.log](https://github.com/eirannejad/pyRevit/files/6856173/pyRevit_2022_c4f0faa00bd417af_PyRevitLabs.PyRevit.Runtime.log)

**Comment by kendraanth** [comment]
I am having issues launching Revit 2020, 2021, and 2022 after installing pyRevit 4.8.8.

**Comment by ISR08** [comment]
Hi, I have the same issue, I don't know if pyrevitv4.8.8 is compatible with revit2022.0.1 hotfix and with NAVIATE RE 2022 help me please

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists

**Comment by alexdaversa** [comment]
confirming on my machine that with the new installer, and up-to-date Revit 2022, pyRevit loads.

**Comment by eirannejad** [comment]
@alexdaversa Thanks for testing!
