### ISSUE TITLE
Does anyone know how to use pyRevit with FastAPI in python

### ISSUE THREAD

**Issue by PymPhekasut** [eirannejad/pyRevit#1274]
Hi, 

I use pyRevit in my Revit project. Now I like to request CRUD to uvicorn server with FAST API. Does anyone know how to do it? Thank you

**Comment by htlcnn** [comment]
pyRevit comes with `requests` library, so you could conveniently execute any request to your FastAPI server.

**Comment by PymPhekasut** [comment]
> pyRevit comes with `requests` library, so you could conveniently execute any request to your FastAPI server.

Thank you so much. I am new in programming. Do you have sample like how to do it?

**Comment by eirannejad** [comment]
Let's switch this to https://discourse.pyrevitlabs.io
