### ISSUE TITLE
Speed of install

### ISSUE THREAD

**Issue by DavePlumb** [eirannejad/pyRevit#1275]
I've got an install Batch file created to install using the CLI. It is "Run as Administrator"
Here's the Batch file with the non-py stuff stripped out:
```
\\bwbr.com\echelon\software\Autodesk2020\AEC_Collection\RevitAddIns\Installs\pyRevit\pyRevit.CLI_4.8.8_signed.exe /exenoui /qn
PATH="C:\Program Files\pyRevit CLI"
pyrevit clones forget --all
pyrevit clone BWBRmain --dest=C:\ProgramData\pyRevit

pyrevit configs checkupdates disable
pyrevit configs autoupdate disable
pyrevit configs rocketmode enable
pyrevit configs filelogging disable
pyrevit configs colorize_docs enable

pyrevit configs seed

pyrevit attach BWBRmain 277 --installed --allusers

```
I have a couple of questions:
Most important, installing this remotely over PN takes about 15 minutes. Is there any way I can speed that up?
Is it downloading everything again? I though that's what the cloning was supposed to help with.
#2: I couldn't find any documentation on what option I need for colorize_docs. I'm getting unrecognized option
#3, The seed doesn't work. I'm getting a DOS notice that the file "is being used by another process" Do I need a wait or something?

TIA

**Comment by eirannejad** [comment]
the `pyrevit clone` command can also install from a ZIP file (it actually downloads the repo as a ZIP file and installs from there`. See `pyrevit clone --help` for more info on the command usage. Look for `--image`
