### ISSUE TITLE
Creating MultiSegmentGrid

### ISSUE THREAD

**Issue by Spoorstaaf1000000** [eirannejad/pyRevit#1278]
I am trying to create a MultiSegmentGrid (https://www.revitapidocs.com/2020/706e504e-20dd-e017-6bdf-e5265848d150.htm), but do not understand how or what to create for the ElementId. The API documentation for this is not very intuitive or helpful.

The extract from my script looks like this. However, I have tried an number of approaches to create msGrid - none working.

msGrid = ???
myMultiSegmentGrid = CurveLoop.Create(curveSetList)
plane = Plane.CreateByNormalAndOrigin(XYZ(0,0,1), XYZ(0,0,0))
sketchPlane = SketchPlane.Create(doc, plane)

myMultiSegmentGrid = MultiSegmentGrid.Create(doc, msGrid.Id, myMultiSegmentGrid, sketchPlane.Id)

Any suggestions?

**Comment by eirannejad** [comment]
`msGrid` should be the Grid Type that you want to assign to this element. You can get the default type from `Document.GetDefaultElementTypeId()` ([here](GetDefaultElementTypeId))
