### ISSUE TITLE
Pasting not working.

### ISSUE THREAD

**Issue by LordMartron94** [eirannejad/pyRevit#1279]
I am experiencing a bug. Whenever I copy a database block and paste it normally in a different location, it automatically synchronizes, annoying. I have a template to insert videos in my media vault, and now if I filter on the notes corresponding to that video for example 5 hindrances to self-mastery, it also puts that filter in the template, and in any other locations, I paste it whilst those are actually other videos.

It might have to do with the fact that I use save to Notion as a web clipper. But that extension has so many more features I like that more, besides whenever I import a website into Notion I want to do it from a template because that is so much faster than having to select the template manually.

**Comment by eirannejad** [comment]
This is not a notion issue tracker 🙄
