### ISSUE TITLE
PyRevitLoader- Error Loading pyRevit 

### ISSUE THREAD

**Issue by digitlam** [eirannejad/pyRevit#1283]
Hello Hello

I have installed pyRevit and clicked on the always load prompt

I'm getting the following error in the first screen shot

I tried running 'pyRevit attach master 277 --installed` (second screen shot) 

To Reproduce
Occurs every time I open Revit 

Expected behaviour
pyRevit should open 

**Screenshots**
![image](https://user-images.githubusercontent.com/74734825/122876435-6d8edb80-d32d-11eb-8307-36f12312374a.png)
![image](https://user-images.githubusercontent.com/74734825/122876511-80a1ab80-d32d-11eb-9199-0677249685a8.png)
![image](https://user-images.githubusercontent.com/74734825/122876871-e8f08d00-d32d-11eb-91d2-13af1ae8188f.png)

please hheellpp :)

**Comment by 3Pinter** [comment]
@eirannejad I a similar message. 

pyRevit v4.8.7

Revit 2019
ONLY got this message after updating my Revit to the latest build. 
Installed (latest) build: 2019.2.3 (19.2.30.41)
(after ok on that message pyrevit seems to load anyways)

Revit 2020
not installed

Revit 2021 latest build
no messages

Revit 2022
not installed

**Comment by digitlam** [comment]
@eirannejad I solved this. well not really solved but got a workaround.

I disable a few other plugins and discovered 1 that was causing the conflict. 

If you are interested to know which plugin was causing the clash its: 

hsbCLT - CLT for Autodesk Revit - Free trial

https://www.hsbcad.com/downloads/

**Comment by kenhogan26** [comment]
I do believe our issue is not a plugin.  Is there a way to subscribe or license so that we can get support?  I really need to get PyRevit installed on our Frame VDI running Server 2019 and Revit versions 2019-2022.

**Comment by kenhogan26** [comment]
Hi,

Any update on this or a version of Pyrevit that will install on versions 2019-2022?

**Comment by ISR08** [comment]
Hi, I have the same issue, I don't know if pyrevitv4.8.8 is compatible with revit2022.0.1 hotfix and with NAVIATE RE 2022

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists
