### ISSUE TITLE
Install pyRevit via script for all users

### ISSUE THREAD

**Issue by CompSuperAC** [eirannejad/pyRevit#1284]
Hi,

My team and I manage about 40 computers and we want to install the "Signed" version of PyRevit to all of them via a script from our management system (typically we'll configure this just like you would a .bat file).  One of our AntiVirus programs came up with a questionable file in the install directory of one of the computers and we figure if we can deploy installs to keep the program updated on a regular basis we can prevent any potential problems.  I came across this thread started 2017 and closed in 2019 (https://github.com/eirannejad/pyRevit/issues/234) and of course it references the Wiki (https://www.notion.so/pyRevit-For-Teams-ddc6c312d6f6488691eed2ec7704fd97) but this is way over my head and seems to not be what we want to achieve.

We simply need to accomplish what we could do by running the installer manually on each computer (which is what we do on all new computers, we have a lot of variations of PyRevit versions), below is a screenshot of what happens when look for command line flags in the windows cmd (Filepath of PyRevit installer followed by _/?_ and I'm not seeing anything like _/unattended_ or _/silent_ which normally I use to do this sort of thing for program installs (if it's supported).

![image](https://user-images.githubusercontent.com/86314153/122963330-6672c800-d343-11eb-96c1-ae4aacd6c3cf.png)

Can this be done?  If yes, can this also be installed for All Users (not as high priority as installing it for the logged on user)?  The other two links are all about "creating a deployment" or "Installing CLI dependencies", we just need to install it, nothing fancy.

Thanks!

**Comment by eirannejad** [comment]
It could be. Try the `/exenoui /qn` options. The installer, when executed with privilege, will automatically install as "All Users" and will create the addin manifest files in %PROGRAMDATA%

**Comment by CompSuperAC** [comment]
I finally got around to testing this and on the 1 computer I tried this on it seems to have worked with multiple users (I also tried _C:\My\FilePath\PyRevit.exe /quiet /norestart_ but that one didn't work when I ran it as system, I think I got it to work as the user in the Windows GUI but that doesn't help me a whole lot), I'll try it on a few new computers before deploying it to all of our existing computers and report back with the results.

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists

**Comment by CompSuperAC** [comment]
Anyone finding this thread in the future, if you do the /? thing mentioned above, there are new options listed.  One of them seems to work the way I want it which is the _/VerySilent_ flag.  I'm using the "Admin Signed" installer (the ones that says  _Admin / All Users / %PROGRAMDATA%_ on the installer page.

Thanks eirannejad!  Also thanks for adding Revit 2023 support!
