### ISSUE TITLE
PyRevit it doesn’t load correctly after installing 

### ISSUE THREAD

**Issue by asll94** [eirannejad/pyRevit#1285]
Hello I have experienced this error after installing Revit, see attached screenshot. I have try many Revit version, but every time I have the same error
![pyrevit](https://user-images.githubusercontent.com/86378626/123155150-bcc03380-d435-11eb-832e-d8492717e6ea.PNG)

**Comment by kenhogan26** [comment]
What version should I install to support Revit 2019-2022?  I got this same error.

**Comment by MatthewBoynton** [comment]
I've had the same issue on multiple machines with pyRevit_4.8.8_signed
![image](https://user-images.githubusercontent.com/44595738/123876606-f5ed2c00-d97e-11eb-9ed8-13db98c4ea39.png)

**Comment by MatthewBoynton** [comment]
Sorry, I had scrolled but if it helps, here's the top of the message:
![image](https://user-images.githubusercontent.com/44595738/123876846-6b58fc80-d97f-11eb-8a5d-140444aa1828.png)

**Comment by ISR08** [comment]
Hi, I have the same issue, I don't know if pyrevitv4.8.8 is compatible with revit2022.0.1 hotfix and with NAVIATE RE 2022

**Comment by eirannejad** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/1280
Closing this. Please follow conversation there.
