### ISSUE TITLE
CPython Issue with pathlib

### ISSUE THREAD

**Issue by CyrilWaechter** [eirannejad/pyRevit#1287]
**Describe the bug**
There is an issue with CPython engine inside Revit only. It looks like it uses an old version of pathlib where `exist_ok` did not exist. This feature was apparently introduced in python 3.5.

**To Reproduce**
1. Create a script containing following code:
```python
#! python3
from pathlib import Path

Path("test").mkdir(parents=True, exist_ok=True)
```
2. Execute this script
3. See error:
```python
CPython Traceback:
TypeError : mkdir() got an unexpected keyword argument 'exist_ok'
 File "<path_to_script_folder>\script.py", line 8, in <module>
Path("test").mkdir(parents=True, exist_ok=True)

pyRevitLabs.PythonNet
à Python.Runtime.Runtime.CheckExceptionOccurred()
 à Python.Runtime.PyScope.Exec(String code, IntPtr _globals, IntPtr _locals)
 à PyRevitLabs.PyRevit.Runtime.CPythonEngine.Execute(ScriptRuntime& runtime)
```

**Expected behavior**
This should work like when you run it in the python engine directly:
```python
<path_to_pyRevit>\pyRevit\bin\engines\CPY385 (master -> origin)
λ python
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
>>> from pathlib import Path
>>> Path("test").mkdir(parents=True, exist_ok=True)
>>>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/9622862/123220389-34da3800-d4ce-11eb-9c12-f70814ccb162.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version: 4.8.8

**Comment by CyrilWaechter** [comment]
I ran:
```python
import pathlib

print(pathlib)
```
and got:
```python
<module 'pathlib' from '<path_to_pyrevit>\\pyRevit\\site-packages\\pathlib.py'>
```
This explains why it does not use correct library as the engine ran separately:
```python
<path_to_pyrevit>\pyRevit\bin\engines\CPY385 (master -> origin)
λ python
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
>>> import pathlib
>>> pathlib
<module 'pathlib' from '<path_to_pyrevit>\\pyRevit\\bin\\engines\\CPY385\\python38.zip\\pathlib.pyc'>
>>>
```

**Comment by eirannejad** [comment]
so if you remove the `pyRevit\site-packages\pathlib.py` then it works? I need to separate these `site-packages` libraries for IronPython and Cpython

**Comment by CyrilWaechter** [comment]
> 
> 
> so if you remove the `pyRevit\site-packages\pathlib.py` then it works? I need to separate these `site-packages` libraries for IronPython and Cpython

As extension lib folder stands before pyrevit sites-packages in `sys.path` I put `pathlib.pyc` from `pyRevit\\bin\\engines\\CPY385\\python38.zip\\pathlib.pyc` in extension lib folder but result is the same. A solution could be to change `sys.path` order. I tried to found where all path are appended in pyRevit source code but did not figured all of it out.
___
```python
import sys; import pprint; pprint.pprint(sys.path)
```
![image](https://user-images.githubusercontent.com/9622862/123380837-3a985200-d590-11eb-8dcd-d5746cbf4891.png)
___
