### ISSUE TITLE
importing pyrevit.forms shows ImportError: No module named pyevent

### ISSUE THREAD

**Issue by tillbaum** [eirannejad/pyRevit#1291]
I cannot import pyrevit.forms 

>>> import pyrevit.forms
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tb\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\forms\__init__.py", line 43, in <module>
ImportError: No module named pyevent

**Comment by eirannejad** [comment]
Are you using the form in cpython? it is not compatible with cpython since it does not include the WPF implementation like IronPython does

**Comment by tillbaum** [comment]
Ehsan, I closed this issue, I found the problem, was a little to hasty opening up an issue, so I closed it. 
I am probably becoming a software engineer now, like you are. :-)

**Comment by Rhino1093** [comment]
I'm still having this issue in my file. I really can't figure it out. I know I'm relatively new to this but this one is throwing me for a loop. Any advice?
![image](https://user-images.githubusercontent.com/98354417/158886582-e4166519-e9b8-4226-81e0-60804c0af844.png)

**Comment by tillbaum** [comment]
http://gui-at.blogspot.com/2009/11/inotifypropertychanged-in-ironpython.html
