### ISSUE TITLE
Preflight checks: Schedule count misleading

### ISSUE THREAD

**Issue by rastermadre** [eirannejad/pyRevit#1293]
**Is your feature request related to a problem? Please describe.**

Noticed that currently the schedule count includes Revision Schedules on sheets which is (imo) less relevant to the model check than the actual number of schedules. 
Ex. in a model with 30 schedules, the number shown in check is 357. 

![Preflight checks schedules_LI](https://user-images.githubusercontent.com/43077096/126191622-8e3af71c-2aa2-4e49-b9a7-e865aa8123ea.jpg)

'Schedules not on sheets' number is also misleading, because revision schedules only exist on sheets, if i'm not mistaken.

**Describe the solution you'd like**
I'd say Remove Revision Schedules from 'Schedules' and 'Schedules not on sheets' count.

Thanks!

**Comment by eirannejad** [comment]
@jmcouffin Hey pal. Is this one fixed too in the PRs? Should this be closed?

**Comment by jmcouffin** [comment]
@eirannejad glad to see you back around here:

fixed by https://github.com/eirannejad/pyRevit/pull/1333
