### ISSUE TITLE
Error when starting custom script

### ISSUE THREAD

**Issue by TZwielehner** [eirannejad/pyRevit#1294]
**Describe the bug**

When I start a python 3 script that has recently still worked I get the error message below. I can more or less ignore it, however, when I try to start the script again it says "__future__" module not found (however, it is installed

**Screenshots**
![image](https://user-images.githubusercontent.com/9949323/126406011-739bc466-7214-430a-a8cf-6228e996745c.png)

**Desktop (please complete the following information):**
 - OS:Windows
 - pyRevit Version 4.8.8
 - pyRevit Environment: 

==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.8" | Path: "C:\Users\ABC\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2021" | Engine: IPY277 (277) | Path: "C:\Users\ABC\AppData\Roaming\pyRevit-Master"
master | Product: "2020.2.1 (New Install)" | Engine: IPY277 (277) | Path: "C:\Users\ABC\AppData\Roaming\pyRevit-Master" 
master | Product: "2019.2.2 Hotfix" | Engine: IPY277 (277) | Path: "C:\Users\ABC\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\ABC\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2021 | Version: 21.1.1.109 | Build: 20200715_1022(x64) | Language: 1033 | Path: "C:\Programme\Autodesk\\Revit 2021\"
2020.2.1 (New Install) | Version: 20.2.12.1 | Build: 20200210_1400(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
Error: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Run with "--debug" option to see debug messages

**Comment by eirannejad** [comment]
What's the script? Are any python3 scripts throwing this error?

**Comment by eirannejad** [comment]
Not enough info
