### ISSUE TITLE
Error when importing ifcopenshell

### ISSUE THREAD

**Issue by TZwielehner** [eirannejad/pyRevit#1295]
I try to import the ifcopenshell library (which worked I while ago, forgot how I did it...). When I use it in my script it throws an error "ImportError : IfcOpenShell not built for 'windows\64bit\python3.8". If I use the import command in the windows terminal it works fine. What am I missing?

Python version installed: 3.8.10
Pyrevit: 4.8.8

```
#!python3
try:
    import ifcopenshell
    from ifcopenshell import api
    print ("Success")
except:
    print ("Something went wrong")
```

**Comment by eirannejad** [comment]
Well seems like you are using a version of `IfcOpenShell` that is not build for python 3.8?!
