### ISSUE TITLE
Hebrew parameter names validation

### ISSUE THREAD

**Issue by yafimski** [eirannejad/pyRevit#1296]
Hi,
I have some family parameters that are named in Hebrew text, and I can print them out and see the correct Hebrew, but I cannot convert them to bytes or to some numeric values or anything that I can "validate" them with.
I have 4 such parameter names, and I want to know which one is which.

I also tried using the safe_strtype(word) but that only gave me back the same word that I started with...

For example I have the word 'לאישור' which I'd like to show in some other format of bytes for validation such as:

```
formatted = format(paramName)
if formatted == '\xb5\xb7\xb4\xb2\xb1\xb9\....' :
        print('you are correct, paramName is לאישור')
```

hopefully this question makes sense.
Thanks!

**Comment by eirannejad** [comment]
I'm not sure what you mean by validation? Could you provide a more specific example of how the script is working and where the error is?
