### ISSUE TITLE
Major issues with pyRevit installer!

### ISSUE THREAD

**Issue by mizukidavis** [eirannejad/pyRevit#1298]
Hello,
Can someone please help me successfully install and run pyRevit.

I downloaded the installer, but when I open I am only given options to "Modify" "Repair" or "Remove". 
There was never an actual "Install" step.
It sounds like it's already installed on my computer but I never installed it.

Further, when I go into 'Apps & Features' in windows settings to try to uninstall pyRevit, the following error occurs:
![image](https://user-images.githubusercontent.com/87829993/126695067-89d52dbf-4b0d-4638-9811-6cb798090a4b.png)

When I open revit (2020), this is the error I get before even opening a project:
![image](https://user-images.githubusercontent.com/87829993/126695554-32013b7e-1dae-4592-b8fa-ae9168dc48d2.png)

Please help!
Thanks in advance!

**Comment by dbaldacchino** [comment]
I am running into the same issue with the signed 4.8.8 executable (first image above when run as user). I get a different error if I run in an administrator prompt. there seems to be an issue with pathing..notice the double \\. I even tried forcing the installation to a different path with both methods but it continues to fail in the same way. Thanks. 
![image](https://user-images.githubusercontent.com/4656191/127527198-7b8f6884-7660-42a1-89c2-c63b8bf4f257.png)

**Comment by dbaldacchino** [comment]
Tried on a different machine and it worked. Not sure exactly why. Failed on a desktop, worked on a laptop (both company assets running the same Windows OS, same policies, etc.).

**Comment by DharmanGersch** [comment]
i'm having the same problem. 
![image](https://user-images.githubusercontent.com/10596012/127594373-86103643-e461-426d-a29d-9c6e54e7ac50.png)
I've tried uninstalling with the installer but it fails. I've deleted all the pyrevit files and folders i can find, however when i run the installer it still presents with the Modify, Repair or remove installation dialog 
![image](https://user-images.githubusercontent.com/10596012/127594493-eb7f00f0-774c-4e74-971e-e9912fc1c90f.png)
all three options give me this warning 
![image](https://user-images.githubusercontent.com/10596012/127594537-dc77e22b-9439-469e-8a23-05c361b5cd16.png)
I've watched your video on installing manually, but it appears the process has changed. https://www.youtube.com/watch?v=hrlkPRoUfXc

Is there an alternative method to install manually? what else do i need to delete to run a clean install?

**Comment by jmcouffin** [comment]
installing pyRevit CLI and then running from command line `pyrevit clone main base --dest="C:\pyRevit\main"` for example should get your there.
I can't remember if you need to run the `pyrevit attach`... command as well

see docs here

https://www.notion.so/Manage-pyRevit-clones-e9f789f9431346b482021f2a87a6dabf

**Comment by apsis0215** [comment]
Since the installer for  4.8.8 appears to be a CyPthoin? Installer - wrapped in an exe- I found we have to (1) unblock the exe to start. (Are there any direct MSI Installers?) 

Not sure - but next we will try to 

- install the CERTIFICATE to run first,  
- then try PDQ to make the Signed 8.8.80-EXE run _as the active user_

We ran into issues installing on any system than had 7.5.5/7.5.4?(I think) - Which we have tried to uninstalled with :

`SET UNINSTALLKEY=HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall
REM Uninstall PyRevit 4.7.5
SET GUID={40BE31F6-E27A-49D0-ABF5-67778407DD6F}
REG QUERY %UNINSTALLKEY%\%GUID%>nul 2>nul
IF "%ERRORLEVEL%"=="0" msiexec.exe /x %GUID% /qn `

But still are running into issues.

**Comment by apsis0215** [comment]
@eirannejad  Trying to us PDQ... The EXE installs but doesn't show in the Programs and features... Is there a way to force the register on successful install?

We will try 2nd round of trying  to install over old Pyrevit to see if it installs in that case.

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists
