### ISSUE TITLE
Export Schedules to CSV

### ISSUE THREAD

**Issue by HuyLe92** [eirannejad/pyRevit#1299]
First I would like to thank you for creating this tool. It has helped me a lot at work.
Currently I'm facing a small problem when exporting schedules to CSV. When outputting the information of the line ( Family and Type, CPL_ID, Cout, Comment, Description ) is not displayed in the CSV file. Can you guide me how to fix it?
Thank you so much.
![image](https://user-images.githubusercontent.com/80211983/127179838-32cbd031-9f69-4a76-a708-dbc1522aefc5.jpg)

**Comment by eirannejad** [comment]
The tool does not export the schedule headers. I'll look into adding that option there as well
