### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#130]
@eirannejad  First Thank you so much for this addin it's awesome and thanks to @gtalarico's presentation.  I'm rolling it out to a couple of members in our office as I edit the scripts and trim down the ones useful to our office. Not much a Python programmer, but will have to start digging in.

Is there a way to set a close to the splash screen dialog after a few seconds?

I tried:

import sys
import time
sys.exit()
for i in range(100):
    time.sleep(0.3)
    print i
    if i == 5:
      sys.exit()

but that didn't seem to work

**Comment by gtalarico** [comment]
Hi @thazell 
There is almost never a need to use sys.exit() in python.
Are you talking about the console window from one of your scripts?  Or from the pyrevit the loader?
To close the Console after running any scripts just add:
__window__.Close()

if you want to before closing, import time , and then add:

time.sleep(5)
__window__.Close()

if you are talking about the main __init__.py pyrevit loader, you can edit the end of it and add the same Close command.

**Comment by thazell** [comment]
Thanks!  I was talking about the init.py

time.sleep(5)
__window__.Close()

The above worked.  Are the underscores a common variable identifier?

Which now I see he hashed out .Close just a couple lines before the end of the code.

So I've done it to the code on my computer.  Now I have to figure out how to fork the code and do a pull request.  Even if it get's rejected it's a good learning experience

**Comment by gtalarico** [comment]
double score in python is called dunder (ie __init__ = dunder init)
and has a special meaning depending how it's used: Magic methods, and or as
a file name.
http://stackoverflow.com/questions/448271/what-is-init-py-for
http://www.rafekettler.com/magicmethods.html

this project uses in a slightly unusual way; it's used by the revit loader
to store some global variables/handlers (__revit__ , __window__ , etc)

**Comment by eirannejad** [comment]
Hi @thazel <https://github.com/thazell>
Thanks for the interest in pyRevit. I'd use the __window__.Close() as
@gtalarico suggested for now. In a week and thanks to @gtalarico's
suggestions and code contributions, I'm pushing a major update with a
completely re-written loader script that is much faster and easier to
understand. This new update will turn off the pop-up window completely. The
startup log will be saved in a log file for troubleshooting.

Good luck and let us know if you have any questions.

**Comment by thazell** [comment]
Great!  Looking forward to the new script.
