### ISSUE TITLE
pyRevit 4.8.8 - Deployment help - how to deploy silently?

### ISSUE THREAD

**Issue by kendraanth** [eirannejad/pyRevit#1300]
I was hoping that you could help me to deploy pyRevit 4.8.8. to our architecture staff. We use PDQ deploy but I am testing the install within command prompt.

I opened up the shared parameters in command prompt and saw one called /exenoui which “launches the EXE setup without UI.” I tried using this parameter to install pyRevit and the UI still came up:
 
![parameters](https://user-images.githubusercontent.com/88107531/127372805-d0297c54-a0ba-4d0d-8a6c-5c6c7df85822.png)
![exenoui](https://user-images.githubusercontent.com/88107531/127372815-7c9edc55-fa34-49e9-964b-e51526f702d3.png)

Any suggestions? Should I be using a different file format or command/executable?

**Comment by ArchitecturalNexus** [comment]
Kendraanth,

Did you find a solution to this? I am currently doing the same through PDQ

**Comment by kendraanth** [comment]
Take a look at this please https://www.notion.so/pyrevitlabs/pyRevit-For-Teams-ddc6c312d6f6488691eed2ec7704fd97<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.notion.so%2Fpyrevitlabs%2FpyRevit-For-Teams-ddc6c312d6f6488691eed2ec7704fd97&data=04%7C01%7Ckendra.anthony%40mg-aec.com%7Cccd0752fbc6044ce0ae508d952a94758%7Cb07986d5f67243cc9ebe131045c83337%7C0%7C0%7C637631710652174076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FyM%2Fx6j5%2BGmut0lNlxk%2ByCS567RJw%2FnGOFyFsskm%2BdQ%3D&reserved=0>

And try the /exenoui /qn options


[A picture containing text, clipart  Description automatically generated]KENDRA ANTHONY
DESIGN TECHNOLOGY TECHNICIAN - SUPPORT
MG AEC TECHNOLOGY PARTNERS
***@***.******@***.***>     d 720 657 2945
Newsletter<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.mg-aec.com%2Fcategory%2Fnewsletter%2F&data=04%7C01%7CKyle.White%40TeamD3.com%7Ced9abdca3f24462ac0d308d9161cd2f9%7Cb07986d5f67243cc9ebe131045c83337%7C0%7C0%7C637565135330057716%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xBODq1ZC0ZpJhydCRPtZRvfvAUtKEF9ZqhCtd3n3r30%3D&reserved=0>  Training<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.mg-aec.com%2Ftraining%2F&data=04%7C01%7CKyle.White%40TeamD3.com%7Ced9abdca3f24462ac0d308d9161cd2f9%7Cb07986d5f67243cc9ebe131045c83337%7C0%7C0%7C637565135330062688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gN33Yqt1wFUN%2BAOVtqkMG%2B%2F90A%2FUEyG%2BHFyCw4Urtf4%3D&reserved=0>  Webinars<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.mg-aec.com%2Four-events%2F&data=04%7C01%7CKyle.White%40TeamD3.com%7Ced9abdca3f24462ac0d308d9161cd2f9%7Cb07986d5f67243cc9ebe131045c83337%7C0%7C0%7C637565135330067667%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Fj4k2uKUvN2rTxfEhyHocRf0H7Y2InlqzVBXfsDynvg%3D&reserved=0>  YouTube<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Finitialaec%2F&data=04%7C01%7CKyle.White%40TeamD3.com%7Ced9abdca3f24462ac0d308d9161cd2f9%7Cb07986d5f67243cc9ebe131045c83337%7C0%7C0%7C637565135330072646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2B6g0OKX9Yomo7JIQsbXjiVaoIYQ4PX5%2Bqr6BQWMhK5I%3D&reserved=0>  LinkedIn<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fmg-aec%2F&data=04%7C01%7CKyle.White%40TeamD3.com%7Ced9abdca3f24462ac0d308d9161cd2f9%7Cb07986d5f67243cc9ebe131045c83337%7C0%7C0%7C637565135330077625%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qErVgZif76B04mrDI3KZNtY0dGi2DzTQty7pdFryfl0%3D&reserved=0>  Facebook<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FMG.aec%2F&data=04%7C01%7CKyle.White%40TeamD3.com%7Ced9abdca3f24462ac0d308d9161cd2f9%7Cb07986d5f67243cc9ebe131045c83337%7C0%7C0%7C637565135330082602%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rfzn7yolCu1lQJCpAWlt%2FjfGG7nCkBOwxaPxsOh%2FkAU%3D&reserved=0>  Twitter<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fmg_aec%2F&data=04%7C01%7CKyle.White%40TeamD3.com%7Ced9abdca3f24462ac0d308d9161cd2f9%7Cb07986d5f67243cc9ebe131045c83337%7C0%7C0%7C637565135330087583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=d61KKR%2FscenI0EDNZnFmk5rhg3XQXN7Q5Ir3x9AF0CI%3D&reserved=0>  Instagram<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.instagram.com%2Fmg.aec%2F&data=04%7C01%7CKyle.White%40TeamD3.com%7Ced9abdca3f24462ac0d308d9161cd2f9%7Cb07986d5f67243cc9ebe131045c83337%7C0%7C0%7C637565135330087583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SnW9jZ%2BRiaTWkhWk9SwUMtH73gk8XlgVfeXdc9bP9PI%3D&reserved=0>
