### ISSUE TITLE
Failed Uninstall

### ISSUE THREAD

**Issue by insanearchitect** [eirannejad/pyRevit#1306]
**Describe the bug**
Trying to uninstall to reinstall for later versions of revit. I get the following error "There is a problem with this windows installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package provider." It then rolls back the uninstall and finishes with a log:
[MSIA2EF.LOG](https://github.com/eirannejad/pyRevit/files/6919651/MSIA2EF.LOG)

I also tried to delete manually from all of the various folders in the uninstall video

**To Reproduce**
1. Uninstall programs or run the installer and remove or repair

**Expected behavior**
Uninstall/reinstall

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - pyRevit Version [4.8.8]

**Comment by Maxvn95** [comment]
Same problem. I have 0 skill in code. Be indulgent please :) 
![Capture d’écran 2021-08-24 164426](https://user-images.githubusercontent.com/89469963/130640786-cb2c10b4-d227-4cb0-a4f7-fccb62306c79.png)

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists
