### ISSUE TITLE
Pinning the Output window on top of others

### ISSUE THREAD

**Issue by fabioloretti** [eirannejad/pyRevit#1307]
Hi Ehsan, this is more of a question that could lead to a request for improvement. I can see the output window has a "Keep on top" pin, is there a way to access that via code? I've been through all the [Effective Output](https://www.notion.so/Effective-Output-43baf34d2ca247ada8e040bcb86613a2) documentation, [pyRevit.Output](https://pyrevit.readthedocs.io/en/latest/pyrevit/output.html) and this forum but I couldn't find any reference to it.

The reason I'm asking is because if my script triggers a Revit warning the console completely disappears behind the Revit window, which is not ideal.

Thank you.
Fabio L Oliveira

**Comment by eirannejad** [comment]
Hmm I don't think so but that could be easily added
- [ ] Add API to allow setting output window to "Always On Top"

**Comment by jmcouffin** [comment]
@eirannejad 
Could you point me in the direction to implement this? Not sure I am skilled enough, but that would be a must have for me. I am running a QAQC doc-opened hook and it bothers me that the output window always falls behind the revit one
