### ISSUE TITLE
Revit crash when Modeless Form tries to do TaskDialog.Show or Selection

### ISSUE THREAD

**Issue by yafimski** [eirannejad/pyRevit#1308]
Hi,

Goal: create a pyRevit-based script with a **Modeless Form** to display data and modify document while exploring data.

I'm trying to duplicate something similar to the simple **Modeless Form** here:
[http://pythoncvc.net/?p=247](url)

I'm using the script in `pyRevitCore.extension\pyRevit.tab\pyRevit.panel\Extensions.smartbutton` as a reference for how this works in **pyRevit**.

The **Modeless Form** shows up fine and displays the data I want, but if I use some `def function()` during this process to do some simple action such as `TaskDialog` or `set` the `Selection` to some element, Revit crashes.

Any ideas why?
Perhaps I'm not allowed to modify the document or access anything outside the **Modeless Form** while I'm displaying it?

Any insight would be appreciated :)
Thanks

**Comment by htlcnn** [comment]
You should wrap the call to your `main()` function around a big try/except to avoid crashing Revit.

**Comment by yafimski** [comment]
I always wrap it :)
I doesn't even hit the exception, it just crashes immediately.

I didn't put a `Transaction `anywhere so that might be the case, what do you think? when I tried to put it all in a transaction group, it gave me some weird warning I never saw before about the asset being 'not managed' or something like that. If that seems important I can try to reconstruct that warning msg.

So basically I run:
```
# MAIN
try:
    # do stuff ...

except Exception, e:
    TaskDialog.Show("Tools", str(e))
```


In any case, I looked at the Journal file from the crash, and the only error there is:
`' 0:< API_ERROR { Starting External Application: Model Review Events, Class: BIMStandardsManager.CommandEventsApp, Vendor : ADSK(Autodesk, subscription.autodesk.com), Assembly: C:\Program Files\Autodesk\Revit Model Review 2019\ModelReview.dll } `

**Comment by htlcnn** [comment]
I often wrap try/except around `customizable_event.raise_event(main, self)` call in the Form.

**Comment by yafimski** [comment]
hm... do you mean to wrap the actions in the def function() called by the form, or to wrap the call to the function() itself?
maybe you can write a foo example of this?

**Comment by htlcnn** [comment]
here's an example:
```
class YourForm(HTLWPFWindow):
    ...
    def button_OK_Click(self, sender, args):
        customizable_event.raise_event(main, self)

def main(form):
    try:
        anything_you_want_to_do_here
    except Exception as e:
        print(e)

if __name__ == "__main__":
    customizable_event = CustomizableEvent()
    form = YourForm("form.xaml")
    form.Show()
```

**Comment by yafimski** [comment]
Shouldn't CustomizableEvent() be a Class in this case? how will it know to call customizable_event.raise_event() on a button click if it isn't defined as a function or class...?

**Comment by htlcnn** [comment]
It's in the module level
```
if __name__ == "__main__":
    customizable_event = CustomizableEvent()
```

**Comment by yafimski** [comment]
Hmm... not sure I understand... If I use my own function instead of customizable_event then I can pop up a TaskDialog before the ModelessForm shows, but in order to raise something like what you say, CustomizableEvent() needs to be defined... Not sure I understand what you mean by "module" :/

**Comment by htlcnn** [comment]
customizable_event is an object that is initialized before the form is initialized, and it's in a name in module level so it is accessible in the form method. I use CustomizableEvent from @CyrilWaechter 's source code.

**Comment by yafimski** [comment]
you mean this?
[https://github.com/CyrilWaechter/pyRevitMEP/blob/master/lib/pyrevitmep/event.py](url)

i'll try to use that as a reference. Thanks.

**Comment by htlcnn** [comment]
Yes that's it.

**Comment by yafimski** [comment]
Thanks! :)

**Comment by yafimski** [comment]
Okay so I played with it a lot, using several reference functions from the MEP addin, but I think something isn't right there, maybe outdated. Revit keeps crashing whenever the action being performed requires in-Revit actions. So for example if I want to print out a log message on the backend of the script, I can do that, but if I want to select and element or delete it, it doesn't work.
The original script used as the 'sample' modeless dialog works but I'm interested in slightly more complex data exchange between the ModelessForm and the Revit interface...

**Comment by htlcnn** [comment]
Please jusy show the code that crashed Revit. That may help a lot.

**Comment by yafimski** [comment]
```
from Autodesk.Revit.DB import Transaction, BuiltInParameter, Element, Level, MEPCurve, ElementId, FamilyInstance\
    , FilteredElementCollector, BuiltInCategory, Category
from pyrevit import script, HOST_APP
from pyrevit.forms import WPFWindow, alert
import rpw
from rpw import revit
from event import CustomizableEvent

doc = revit.doc
uidoc = revit.uidoc

__persistentengine__ = True

# Simple function we want to run
def test_function(elemID):
    t = Transaction(doc, "Focus to Element")
    t.Start()
    print(elemID.ToString())

    t.Commit()

warning_ids = []
warning_texts = []

warnings = doc.GetWarnings()
for w in warnings:
    fail_elems = w.GetFailingElements()
    description = w.GetDescriptionText()    
    for elemID in fail_elems:
        warning_ids.append(elemID)
        warning_texts.append(description)

warning_dict = {}
for i in range(len(warning_ids)):
    warning_dict[warning_ids[i]] = warning_texts[i]

customizable_event = CustomizableEvent()

class PopulateListItem:
    def __init__(self, k,v):
        self.ID = k
        self.Text = v

class ModelessForm(WPFWindow):
    def __init__(self, xaml_file_name, itemsList):
        WPFWindow.__init__(self, xaml_file_name)
        self._item_init_list = []
        for k,v in itemsList.items():	
        	self._item_init_list.append(PopulateListItem(k,v))
        
        self.itemRef.ItemsSource = sorted(self._item_init_list, key=lambda x: x, reverse=True)     
        self.itemRef.SelectedIndex = 0
        self.Show()

    @property
    def selected_item(self):
        if len(list(self.itemRef.SelectedItems)) == 1:
            return self.itemRef.SelectedItem

    def from_list_click(self, sender, e):
        elemID = self.itemRef.SelectedItem.ID
        test_function(elemID)
        
        customizable_event.raise_event(elemID)


ModelessForm("ModelessForm.xaml",warning_dict).Show()
```


xaml is:
```
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="Delete things:" Height="600" Width="800" ShowInTaskbar="False" Topmost="True"
        WindowStartupLocation="CenterScreen" ScrollViewer.VerticalScrollBarVisibility="Disabled" HorizontalContentAlignment="Center">
    
    <Window.Resources>
		<Style x:Key="hcs" TargetType="{x:Type GridViewColumnHeader}">
			<Setter Property="HorizontalContentAlignment" Value="Left"></Setter>
		</Style>
    </Window.Resources>


    <Grid>
    <StackPanel Margin="10">
  
    <ListView x:Name="itemRef" SelectionMode="Extended" Margin="10" HorizontalAlignment="Left" HorizontalContentAlignment="Left">
        <ListView.View>
            <GridView>
                <GridViewColumn HeaderContainerStyle="{StaticResource hcs}" Header="Element ID" Width="70" DisplayMemberBinding="{Binding ID}"/>
                <GridViewColumn HeaderContainerStyle="{StaticResource hcs}" Header="Warning Description" Width="650" DisplayMemberBinding="{Binding Text}"/>
            </GridView>
        </ListView.View>
    </ListView>

    <Button Content="Focus to Element" Click="from_list_click" HorizontalAlignment="Left" Padding="5"/>
    </StackPanel>

	</Grid>

</Window>
```

**Comment by htlcnn** [comment]
customizable_event.raise_event should receive a **function** and then the form itself. If you want to pass parameters into the function, you should save it as an attribute of the form
Example:
``` customizable_event.raise_event(test_function, self)
```
Then
```
def test_function(form):
    print(form.element_id)
```

**Comment by yafimski** [comment]
yes but if I use it as an attribute, why do I even need a customizable_event? I can just call it from the xaml as a def() of the form.

**Comment by htlcnn** [comment]
You can keep the form open and raise a background event. That is handy when you need to change some inputs between runs. Otherwise, you do not need a modeless form I guess. Also, Transaction mechanism of Revit does not allow multi threading.

**Comment by yafimski** [comment]
> Transaction mechanism of Revit does not allow multi threading

pretty sure that this is what has been crashing / making this not a possible solution.

I'll go another route :)
Thanks

**Comment by eirannejad** [comment]
Hey guys is this issue still standing? Seems more like a question to me than a pyRevit issue. @htlcnn Should I keep this open?

**Comment by htlcnn** [comment]
Revit crashes when you make an exception inside the form and do not catch it. Please kindly review your code and add try/except to see where it crashes.

**Comment by htlcnn** [comment]
@eirannejad I think this issue is resolved.

**Comment by yafimski** [comment]
> 
> 
> Hey guys is this issue still standing? Seems more like a question to me than a pyRevit issue. @htlcnn Should I keep this open?

Close it 👍
