### ISSUE TITLE
same problem as this post pyRevit does not work when independent IronPython is installed #180

### ISSUE THREAD

**Issue by Claukopietz** [eirannejad/pyRevit#1309]
Hi There,

I'm having the same problem with pyRevit 4.8.8 as in the post bellow:

pyRevit does not work when independent IronPython is installed #180

Would you have any other suggestions as I have tried the whole workflow you gave and still having issues with it. 

is such a nice plugin and I would like to introduce in the company I work with.

Looking forward to hearing from you.

Best regards
Claudia

**Comment by eirannejad** [comment]
This is really odd since pyRevit loads IronPython from its own dlls. Which IronPython version do you have installed independently on your system?

**Comment by MrFunkie** [comment]
Hi there,

I am experiencing the same issue with PyRevit 4.8.8 and ironpython install version 2.7.11

Cheers,

Jesse
