### ISSUE TITLE
Problem with using Numpy in pyRevit

### ISSUE THREAD

**Issue by MrdBahram** [eirannejad/pyRevit#1312]
Hi,
I have a problem with running my code when using numpy.The dialog box shows the error:
_CPython Traceback:
ModuleNotFoundError : No module named 'numpy'_

I copied the numpy files in _AppData\Roaming\pyRevit-Master\bin\engines\CPY385\python38.zip\site-packages_  and still have this error.
What should i do?

**Comment by chuongmep** [comment]
You need install library numpy, use command :
`pip install numpy`

**Comment by eirannejad** [comment]
As @chuongmep said, you can install numpy on your system (make sure to have the same x64 python 3 as you are using in pyRevit) and add the site-packages path to `PYTHONPATH` environment variable. See the Python3 notes in pyRevit config window
