### ISSUE TITLE
Dynamo geometry kernel breaking after using PyRevit

### ISSUE THREAD

**Issue by cesarecaoduro** [eirannejad/pyRevit#1315]
I have been trying to use ProtoGeometry from PyRevit and it looks like it was working until, for no reason, it started to give throw me this error.
![image](https://user-images.githubusercontent.com/26373891/129150628-deb5659e-8739-4d84-9d2b-c6b6f48b492b.png)
I have tried everything including deleting manually all the folder on my laptop related to Revit and Dynamo and PyRevit and installed everything from scratch. Nothing!
The problem now is that it break completely Dynamo too
![image](https://user-images.githubusercontent.com/26373891/129150822-5309308b-ab5b-470d-911b-c77940bd787d.png)
Has anyone experienced the same problem?

The script is as easy as this
```
from pyrevit import coreutils
from pyrevit import revit, DB, UI
from pyrevit import forms
from pyrevit import script


import clr
clr.AddReference('ProtoGeometry')

import Autodesk.DesignScript.Geometry as DS

print(DS.Point.ByCoordinates(0,0,0))
```

but then I found that this may be the right way to do it
```
import clr
clr.AddReference("DynamoApplications")
from Dynamo.Applications import StartupUtils

def main():
    dynamo_model = StartupUtils.MakeModel(CLImode=True)
    dynamo_model.Start()
    clr.AddReference("ProtoGeometry")
    from Autodesk.DesignScript.Geometry import Point
    try:
        p = Point.ByCoordinates(1, 1, 1)
        print(p)
    finally:
        dynamo_model.ShutDown(shutdownHost=True)
```

Any suggestion on this? because we can really use the power of Dynamo geometry kernel but we are a bit concerned with performances.

**Comment by eirannejad** [comment]
Which Revit and Dynamo versions?
