### ISSUE TITLE
Unable to find "Tags Settings button"

### ISSUE THREAD

**Issue by yogihit** [eirannejad/pyRevit#1316]
_Revit 2020 - PyRevit 4.8.8 Win 10 Pro-i7-9700k-32GB_

Hello Ehsan,
Thank you very much for pyRevit tool. It really helpful.
While Click on "Manage Tag, Tag Selected, Match Tag Clear Tag, Export Tagged" from Package & Tags, following dialog box appeared.

```
[Window Title]
Manage Tags
[Main Instruction]
Tags tools need to be configured before using. Click on the Tags Settings button to setup.
[OK]
[Footer]
pyRevit 4.8.8
```

![Tags](https://user-images.githubusercontent.com/68890059/129162854-7b572741-c15e-4cb6-a245-7a278ea8f326.JPG)

I am unable to locate "Tags Settings button"
I did uninstall and reinstall pyRevit once.
 
Manage Package working fine as expected.

Thanks & Regards,
Yogesh

**Comment by eirannejad** [comment]
https://www.notion.so/Manage-Tags-0c0ec76535724d318f6fb3e04cdeae9a

**Comment by eirannejad** [comment]
and thank you :D

**Comment by yogihit** [comment]
Hello Ehsan, thank you help, unfortunately I am still unable to invoke appropriate command /dialog box. 
Please find attached images, as I have enabled loaded all extensions. error is reproduced

![PyR-1](https://user-images.githubusercontent.com/68890059/134496120-fa84ddd4-906e-47b6-9cea-8e4e59dbf27c.JPG)
![PyR-2](https://user-images.githubusercontent.com/68890059/134496115-cbd8ab52-a272-410a-932f-5a9a03423f5b.JPG)
.

**Comment by brunosoliveira1982** [comment]
Hello, just enabled the Tags on pyRevit and I'm also having that button problem. Running the pyRevit 5.3.1 and Revit 2025.
