### ISSUE TITLE
2019 Revit

### ISSUE THREAD

**Issue by longvo1234** [eirannejad/pyRevit#1318]
![Capture](https://user-images.githubusercontent.com/89473038/130649386-79a887a7-aa0f-4bc9-a082-1c7194630330.JPG)

[pyRevit_2019_01cc2981f17fa08f_PyRevitLabs.PyRevit.Runtime.log](https://github.com/eirannejad/pyRevit/files/7040495/pyRevit_2019_01cc2981f17fa08f_PyRevitLabs.PyRevit.Runtime.log)

helppp

**Comment by mrjoneskod** [comment]
I am getting a similar error after I updated to 2019.2.3

![image](https://user-images.githubusercontent.com/17713401/133645287-9c40267b-5fba-4ab7-bb35-225ffe4053d7.png)

**Comment by alexdaversa** [comment]
Try running `pyrevit caches clear 2019` and report back if that fixes the error.

**Comment by mrjoneskod** [comment]
It seems "pyrevit caches clear 2019" did it for me. Thanks @alexdaversa

**Comment by eirannejad** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/1217
Closing this. Please follow conversation there.
