### ISSUE TITLE
Revit 2019 Make Pattern not Working

### ISSUE THREAD

**Issue by adamjpoon** [eirannejad/pyRevit#1319]
Hi,
I can install pyRevit to Revit 2019.2, but the create hatch function dose not work.
After I select the lines, the create pattern window just close without creating the pattern.
Dose anybody has any solution?

Thanks,

**Comment by alexdaversa** [comment]
Are there any error messages that pop up? The tool should ask you for a name, and after you hit create, it will ask you for the opposite corners of the lines you've created. Once you select both corners, a popup will appear saying the pattern was created successfully.

**Comment by eirannejad** [comment]
not enough info
