### ISSUE TITLE
Revit2020 loading error, prevents pyRevit from loading

### ISSUE THREAD

**Issue by dnenov** [eirannejad/pyRevit#1320]
I have started getting this error when opening Revit 2020. pyRevit will not load after the issue, but it loads fine in other Revit versions (Revit 2021 tested).

**To Reproduce**
Local issue, not sure how to reproduce.

**Expected behavior**
Load normally

**Screenshots**
![image](https://user-images.githubusercontent.com/5354594/130949657-e04c1321-b68f-4d1c-8076-ce24fff273fe.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version: 4.8.8
 - pyRevit Environment: 
 -  ==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.8" | Path: "C:\Users\dneno\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2021 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Users\dneno\AppData\Roaming\pyRevit-Master"
master | Product: "2020.2.4" | Engine: IPY277 (277) | Path: "C:\Users\dneno\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\dneno\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.4 | Version: 20.2.40.65 | Build: 20210420_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
PID: 19052 | 2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2021"
PID: 21188 | 2020.2.4 | Version: 20.2.40.65 | Build: 20210420_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2020"
==> User Environment
Microsoft Windows 10 [Version 10.0.19042]
Executing User: WINDELL-FSGEGE8\dneno
Active User: WINDELL-FSGEGE8\dneno
Admin Access: No
%APPDATA%: "C:\Users\dneno\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.7.1 v4.7.2 v4.8 v4.X
Installed .Net-Core Target Packs: v2.1.202 v2.1.515 v3.1.301
pyRevit CLI 4.8.8.0

**Additional context**
Runs in Revit2021 with no problem

**Comment by cyonaraferreira** [comment]
Oi! Esse mesmo problema acontece no meu computador.
Alguma solução? Não consigo instalar nenhum pyRevit

**Comment by eirannejad** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/1217
Both are related to `out_window = runtime.types.ScriptConsole()` when setting up the output window for the first time
Closing this. Please follow conversation there.
