### ISSUE TITLE
Schedule Exporter - Diacritic Characters

### ISSUE THREAD

**Issue by f1pcs0** [eirannejad/pyRevit#1321]
Hello pyRevit,

Is it possible to make pyRevit export schedules with local diacritic carachters (in this case german)?
What I get in the exported schedule is this
![image](https://user-images.githubusercontent.com/42838855/131306045-02c0be36-470b-431a-8fd2-49d86d0bf5e2.png)
as opposed to this (which is what I get when I export the schedule "manually" through Revit):
![image](https://user-images.githubusercontent.com/42838855/131306473-69b6eaa5-b7cf-49cf-b4d9-522d9c5cac23.png)

I would really appreciate some feedback, if possible.
Thank you,

Filip

**Comment by FrancoTonutti** [comment]
Hello, in my case to work with latin characters I add `# -*- coding: utf-8 -*-` in the first line of each python file. In this way I can write data in Excel without problem.
