### ISSUE TITLE
Silent installer no longer works with 4.8.8

### ISSUE THREAD

**Issue by David-PLUS** [eirannejad/pyRevit#1322]
Hi,

Running a silent deployment of pyRevit within the 'current logged-on user' desktop session:
v4.7.6. and v4.8.5 this command line works: "c:\temp\pyRevit\pyRevit_4.8.5_signed.exe" /exenoui /exenoupdates /quiet
v4.8.8 the same command line stops with MSI fatal error 1603

Running the bootstrapper help on v4.8.8 EXE suggests that these switches should still work.

What changed? Any assistance would be appreciated, thank you.

Cheers!

David

**Comment by HandsomeKenFisher** [comment]
> Hi,
> 
> Running a silent deployment of pyRevit within the 'current logged-on user' desktop session:
> v4.7.6. and v4.8.5 this command line works: "c:\temp\pyRevit\pyRevit_4.8.5_signed.exe" /exenoui /exenoupdates /quiet
> v4.8.8 the same command line stops with MSI fatal error 1603
> 
> Running the bootstrapper help on v4.8.8 EXE suggests that these switches should still work.
> 
> What changed? Any assistance would be appreciated, thank you.
> 
> Cheers!
> 
> David

Same here David. I test with only the switch /exenoui and still get the install dialog.
(Great software Eshan)

Ken Fisher

**Comment by HandsomeKenFisher** [comment]
> > Hi,
> > Running a silent deployment of pyRevit within the 'current logged-on user' desktop session:
> > v4.7.6. and v4.8.5 this command line works: "c:\temp\pyRevit\pyRevit_4.8.5_signed.exe" /exenoui /exenoupdates /quiet
> > v4.8.8 the same command line stops with MSI fatal error 1603
> > Running the bootstrapper help on v4.8.8 EXE suggests that these switches should still work.
> > What changed? Any assistance would be appreciated, thank you.
> > Cheers!
> > David
> 
> Same here David. I test with only the switch /exenoui and still get the install dialog.
> (Great software Eshan)
> 
> Ken Fisher

Update: Good news. 4.8.8 DID in fact run silently in the System context of the SCCM apparatus. (The above visible UI condition happened running in an instance of cmd under an elevation to local admin) So we are good!  Thanks all.

**Comment by David-PLUS** [comment]
Are you sure it installed for the user/machine? And did you try to uninstall it via Apps?

When I ran the previous versions <4.8.8 as System the plug-in is almost impossible to uninstall, further it wasnt available to the current logged on user.


David Smith
Group IT Systems Engineer


Plus Architecture


P:  +61 7 3067 3599
W: www.plusarchitecture.com.au   <http://www.plusarchitecture.com.au>

IMPORTANT NOTICE:
This e-mail is intended only for the named person or entity to which it is addressed. If you have received this e-mail in error we apologise, please contact us,
delete the e-mail and any electronic/printed copies. All contents are the copyright property of Plus. We appreciate your cooperation.

NOMINATED ARCHITECT (NSW): DANILO JURIC 10397

P Please consider the environment before printing this e-mail.

________________________________

**Comment by apsis0215** [comment]
I wonder if the Installer is an extension of the  MSIexec.exe because /qn still works.

I am curious what /exenoui is supposed to do?

/_q_[_n_|b|r|f]
		Sets user interface level
		_n - No UI_
		b - Basic UI
		r - Reduced UI
		f - Full UI (default)

--

Windows ® Installer. V 5.0.19041.1 

msiexec /Option <Required Parameter> [Optional Parameter]

Install Options
	</package | /i> <Product.msi>
		Installs or configures a product
	/a <Product.msi>
		Administrative install - Installs a product on the network
	/j<u|m> <Product.msi> [/t <Transform List>] [/g <Language ID>]
		Advertises a product - m to all users, u to current user
	</uninstall | /x> <Product.msi | ProductCode>
		Uninstalls the product
Display Options
	/quiet
		Quiet mode, no user interaction
	/passive
		Unattended mode - progress bar only
	/q[n|b|r|f]
		Sets user interface level
		n - No UI
		b - Basic UI
		r - Reduced UI
		f - Full UI (default)
	/help
		Help information
Restart Options
	/norestart
		Do not restart after the installation is complete
	/promptrestart
		Prompts the user for restart if necessary
	/forcerestart
		Always restart the computer after installation
Logging Options
	/l[i|w|e|a|r|u|c|m|o|p|v|x|+|!|*] <LogFile>
		i - Status messages
		w - Nonfatal warnings
		e - All error messages
		a - Start up of actions
		r - Action-specific records
		u - User requests
		c - Initial UI parameters
		m - Out-of-memory or fatal exit information
		o - Out-of-disk-space messages
		p - Terminal properties
		v - Verbose output
		x - Extra debugging information
		+ - Append to existing log file
		! - Flush each line to the log
		* - Log all information, except for v and x options
	/log <LogFile>
		Equivalent of /l* <LogFile>
Update Options
	/update <Update1.msp>[;Update2.msp]
		Applies update(s)
	/uninstall <PatchCodeGuid>[;Update2.msp] /package <Product.msi | ProductCode>
		Remove update(s) for a product
Repair Options
	/f[p|e|c|m|s|o|d|a|u|v] <Product.msi | ProductCode>
		Repairs a product
		p - only if file is missing
		o - if file is missing or an older version is installed (default)
		e - if file is missing or an equal or older version is installed
		d - if file is missing or a different version is installed
		c - if file is missing or checksum does not match the calculated value
		a - forces all files to be reinstalled
		u - all required user-specific registry entries (default)
		m - all required computer-specific registry entries (default)
		s - all existing shortcuts (default)
		v - runs from source and recaches local package
Setting Public Properties
	[PROPERTY=PropertyValue]

Consult the Windows ® Installer SDK for additional documentation on the
command line syntax.

Copyright © Microsoft Corporation. All rights reserved.
Portions of this software are based in part on the work of the Independent JPEG Group.

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists
