### ISSUE TITLE
Revit cannot run availability command

### ISSUE THREAD

**Issue by RichardPinka** [eirannejad/pyRevit#1324]
**Describe the bug**
hello, 
i am not sure what is this about , just after installation of pyRevit  on both Revit installations (2019 and 2021.1.3) occured same window message 

![image](https://user-images.githubusercontent.com/8267708/132068013-17b5170a-747f-493d-a159-f3fe401e9bb9.png)

and after reopening Revit 2021 occured this:
![image](https://user-images.githubusercontent.com/8267708/132068115-5fc434a4-bed9-4027-8641-2283c080522e.png)

**Comment by RichardPinka** [comment]
Dear @eirannejad  what does this mean ?

**Comment by eirannejad** [comment]
That's me not reading the full information on this issue :D Sorry.

New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists

**Comment by RichardPinka** [comment]
Thank You wery much for the response Ehsan ! I am very grateful For Your tool and effort with You are doing it ..  I will study the notes You showed, and I will see what it is about,. . thank You. 

all the best for 2022 !

**Comment by eirannejad** [comment]
@RichardPinka thanks for the kind words and also for being patient 😅
