### ISSUE TITLE
Creating tags using pyrevit

### ISSUE THREAD

**Issue by uridah** [eirannejad/pyRevit#1326]
Hi Ehsan, I hope you're well

I want to be able to create tags for pipes. 
Some of my use cases are as follows:
- Creating elevation tags on fabrication pipes
- Creating tags describing the length of the pipe
- Labelling pipes (hot water etc.)

Based on my research so far, Revit API does allow you to create new tags. See this for instance: https://forums.autodesk.com/t5/revit-api-forum/tagging-fabricationpart-pipes/td-p/7820957
But I couldn't find any create new tag function in RPS or pyrevit. Can you guide me about this?

**Comment by skuibreaker** [comment]
I would love a utility that would copy tags & paste them to all elements in the view with the same leader & landing  configuration already done.  To create a more professional look to the tags.

**Comment by eirannejad** [comment]
I don't have a wrapper in pyRevit to create tags I believe but the Revit API method is here: https://apidocs.co/apps/revit/2022/9b5a74a0-f9bd-9892-23e0-9a344f514b02.htm
