### ISSUE TITLE
pyrevitloader.dll does not exist

### ISSUE THREAD

**Issue by jasongardner09** [eirannejad/pyRevit#1328]
during the upgrade of a new install we are getting the following error the pyrevitloader.dll does not exist.

![missing dll](https://user-images.githubusercontent.com/29188320/133659162-e0a0ce2d-b30f-4d4e-8610-aa9a37369a40.jpg)

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists

**Comment by agialanella** [comment]
Having the same issue, using Intune to package it and this error occurs on select machines. What do you recommend?
