### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by rbaggen** [eirannejad/pyRevit#133]
I'm new on Python, and I'm trying to get it work.
I executed the installer.
Getting error when opening Revit, 
Failed to initialize `..\AppData\Roaming\pyRevit\pyRevit-v3beta\__init__\RevitPythonLoader.dll`

If I have a look in the folder, `__init__` folder is not available, only `__git__`
`RevitPythonLoader.dll`, it's not in the `.\pyRevit\` folder at all?

Is there a specific Python version necessary?

Can you help me on this one?

**Comment by eirannejad** [comment]
Hi @rbaggen 
I just tested the installer and everything seems to be working fine. You know you need to have access to internet for the installer to work. The installer installs the git program and clones branches from the github repository.

**Comment by gtalarico** [comment]
@rbaggen 
Just a guess.

> Failed to initialize "..\AppData\Roaming\pyRevit\pyRevit-v3beta_init_\RevitPythonLoader.dll"

There is is missing a "*/*" before __init__.
Is the message missing the slash or was it just a mistake when you pasted? 
If so, it could be the path in the .addin is pointing to the wrong folder
\AppData\Roaming\pyRevit\pyRevit-v3beta_init_\RevitPythonLoader.dll

**Comment by eirannejad** [comment]
Nah. This comment system uses [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) langauge. I'll edit yours and see how it works.

**Comment by eirannejad** [comment]
Is the missing `/` is in the actual error window??

**Comment by gtalarico** [comment]
> Is the missing / is in the actual error window??
That's what am trying to figure out...
@rbaggen did you edit your original msg and add the _slash_
 😕

**Comment by eirannejad** [comment]
@gtalarico 
the original message had the slash but was taken out by the markdown engine. I fenced the directory address to make it look correct.

**Comment by rbaggen** [comment]
I managed to install, there where some Firewall issues on the internet connection I was using
