### ISSUE TITLE
Edit Content + menus for deployment

### ISSUE THREAD

**Issue by apsis0215** [eirannejad/pyRevit#1337]
**Is your feature request related to a problem? Please describe.**
A clear and concise way to package and edit the menus to add or remove elements and mock up the interface for deployment - and or centralized location for the PyRevit Menus (Is there a way to centralize the menus?)

**Describe the solution you'd like**
An editor that allows for click and drag like Form editing for the elements to be distributed with a package.

**Describe alternatives you've considered**
We have gone through and culled/manually edited the PyRevitMaster folder and replace the existing one at the local system's folder. Recently this method has broken menu items- looking into that next week.

**Additional context**
Could perhaps use a Visual Studio (free) Editor to manage the menus?

Anything we can do to help?
Thanks,
Ron

**Comment by eirannejad** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/1387
