### ISSUE TITLE
Command Line Arguments Cause Installation Error

### ISSUE THREAD

**Issue by peterson-m** [eirannejad/pyRevit#1338]
**Describe the bug**
When attempting to install pyRevit v4.8.8 with the command line arguments of '/qn' , '/norestart' or '/quiet' the installation Event Viewer logs generated report the following error message:

"Product pyRevit -- Error 1303. The installer has insufficient privileges to access this directory: C:\Program Files\pyRevit--Master. The installation cannot continue. Log on as administrator or contact your system administrator."

![image](https://user-images.githubusercontent.com/91550834/135110330-08ff363e-e1f5-4a58-8854-d2e8be2b4c6d.png)

The installation then reports "Product: pyRevit -- Installation failed."
![image](https://user-images.githubusercontent.com/91550834/135112426-1d3d64d9-bdcd-4ba6-bc91-cd3433b79c5a.png)

Lastly, the installation generates a 1603 error code in the application event viewer logs:
![image](https://user-images.githubusercontent.com/91550834/135112288-642e4b05-78e0-424c-b1e7-45319bf9c1f0.png)

**When running the installation by calling the .EXE without any command line arguments, the installation completes successfully.** Unfortunately, in our environment we cannot run this as a guided installation as a workaround.

Lastly, looking at the available command line arguments by calling '/?' result in the following options:
![image](https://user-images.githubusercontent.com/91550834/135111153-90cb4d4e-5713-4b88-8875-887a813e6993.png)

I was unable to install the application successfully using '/exenoui'.

**To Reproduce**
Call the .EXE file (while logged in with a standard user account) with the command line parameter '/quiet'
![image](https://user-images.githubusercontent.com/91550834/135113185-726932ed-7327-4907-b9c6-2bdaed9186b4.png)

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists
