### ISSUE TITLE
Revit stops working with pyRevit addin

### ISSUE THREAD

**Issue by rbaggen** [eirannejad/pyRevit#134]
Starting Revit after installing pyRevit,,hangs Revit and quits the application?
Some times it works, but most of the time not.
Can I bypass the updates on startup and perform them manually?

It happens on 2015, 2016 and 2017.
This are the Revit versions I'm using;

2015 - 20160512_1515(x64) Update Release 14
2016 - 16.0.1185.0 20161004_0715(x64) Update7 for R2
2017 - 17.0.1081.0 20161006_0315(x64) 2017.1

I'm using Windows10

![2016-10-31 09_59_38-settings](https://cloud.githubusercontent.com/assets/14872958/19848951/cd15545a-9f50-11e6-936f-23ba45593599.png)

**Comment by gtalarico** [comment]
same issue as:
https://github.com/eirannejad/pyRevit/issues/127

**Comment by eirannejad** [comment]
@rbaggen I apologize for the trouble. We've had this issue for a while and I'm in the process of rewriting the loader module that fixes this. It'll be out in a couple of weeks.
For now, please go to `%appdata%\pyRevit` and open the `usersettings.ini` file and set the verbose value to `True`...You'll see a lot more output at the startup but at least it won't crash.

**Comment by rbaggen** [comment]
Thanks for your e-mail.

No worries, this way it will work and I can use the tools.
I'm used to test Revit addins, most of the time there is a workaround and the fix will come later ;-)

I'm looking forward to the next version of pyRevit

With regards,

Rolph Baggen


On 31 Oct, 2016, at 04:37 PM, Ehsan Iran-Nejad <notifications@github.com> wrote:

@rbaggen I apologize for the trouble. We've had this issue for a while and I'm in the process of rewriting the loader module that fixes this. It'll be out in a couple of weeks.
For now, please go to %appdata%\pyRevit and open the usersettings.ini file and set the verbose value to True...You'll see a lot more output at the startup but at least it won't crash.

**Comment by thazell** [comment]
I know you are working on this, so here are some more comments if this is helpful for the new loader. Just upgraded my Revit 2016 to Update7 R2 (13.0.1185.0 20161004_0715(x64)) and additional issues were experienced (Revit wouldn't open even with the long loader).  My last build was 2016 (16.0.428.0 20150220_1215(x64)).

**Comment by eirannejad** [comment]
Resolved in new version

**Comment by thazell** [comment]
Thanks!  Can't wait to try the new loader :)

**Comment by eirannejad** [comment]
Thanks. You can download the new installer from github now. This new loader has its own tricks so let me know if you see any errors. It still needs some tweaking but I promise this one will be way better.
