### ISSUE TITLE
Help using CSV file import tool Pyrevit

### ISSUE THREAD

**Issue by Jariverag** [eirannejad/pyRevit#1345]
Hello , I'm new to Github and I'm using pyrevit and its been super helpful, however I'm having trouble using the Pyrevit tool: create schedule from .csv. I hope this is the right place to post this. 

 If someone can teach me how to use this tool I would be very grateful. I want to add values in excel to a text project paramameter called TASK and a parameter called STAGE. It's way faster to do this in excel.  

![RVT Schedule](https://user-images.githubusercontent.com/91268536/136089081-a04b2fc5-6a50-4c8d-ad8d-4e1833ef8174.png)

My .csv file is as follows: 

KEY NAME,TASK,C. STAGE 
1,A1,1
2,A2,1
3,A3,1
4,A4,1
5,A5,2
6,A6,2
7,A7,2
8,A8,2
9,A9,2
10,A10,3
11,A11,3
12,A12,3
13,A13,3

If there's a video or an example loaded into revit it would also help as well. 

When I try loading the csv file into revit after selecting the floors category I get this message 
![image](https://user-images.githubusercontent.com/91268536/136089553-d2af8ba5-dd5c-4c62-a10c-6c115781f873.png)

**Comment by eirannejad** [comment]
Would you mind asking this question on the [pyRevit Forums](https://discourse.pyrevitlabs.io)
There is a very high chance someone will respond much faster than here :D
