### ISSUE TITLE
Idea:  Create Print set from schedule

### ISSUE THREAD

**Issue by ThubanPDX** [eirannejad/pyRevit#135]
Hi Ehsan 
thought of a new idea.  So we have that script which creates print set list from revision clouds.   is it possible to do something similar where you select the sheet schedule/index you want and it could create a print set for it?

**Comment by eirannejad** [comment]
Yes Yes. Very nice. I'll work on it.

**Comment by eirannejad** [comment]
Okay so I added the print from schedule tool that think overrides this. Anyways, even when I create a Print set based on the schedule, Revit doesn't follow the sheet order! 👎
