### ISSUE TITLE
4.8.8 Crashes Revit

### ISSUE THREAD

**Issue by thelizardqwn** [eirannejad/pyRevit#1350]
**Describe the bug**
PyRevit doesn't load after first install ever of PyRevit. It then crashes Revit 2020 whenever I try to open it. I have no idea where to get you crash information. I've tried uninstalling and reinstalling many times. I still have the same issue. I tried it on a co-workers computer that has less add-ins that may conflict, but there was still the same problem.

**To Reproduce**

**Desktop (please complete the following information):**
 - pyRevit Version 4.8.8

**Additional context**

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists
