### ISSUE TITLE
Setup Parameters not being recognized

### ISSUE THREAD

**Issue by Boris-the-knive** [eirannejad/pyRevit#1353]
Hi,

there ist no way to setup pyrevit silently. I tried "pyRevit_4.8.8_signed.exe /exenoui" but the Setup dialog appears anyway.

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725)
