### ISSUE TITLE
Keynotes: need hard-return in keynote contents

### ISSUE THREAD

**Issue by eirannejad** [eirannejad/pyRevit#1357]
- [ ] Is this even possible?

**Comment by mawdesign** [comment]
This is possible, see http://akrimee.blogspot.com/2017/04/revit-4-creating-multiline-text-in.html
Basically the text gets wrapped in quotes and a linefeed (hex 0A) gets used as the hard return. I can manually create these but they currently break the keynote manager which reads these as 2 lines and writes back with a return and linefeed (hex 0D0A) which breaks Revits ability to load the keynotes. Really simple example attached.
[Keynote Multiline Test.txt](https://github.com/eirannejad/pyRevit/files/9834900/Keynote.Multiline.Test.txt)
