### ISSUE TITLE
Unable to re-install PyRevit - installer stops running halfway through and unusual install options

### ISSUE THREAD

**Issue by samevans25** [eirannejad/pyRevit#1361]
Hi - I'm trying to re-install PyRevit. I've removed all of the files - but every time I run the installer, two things that are weird happen:

First off - I get a "Modify, Repair or Remove installation" screen (see attachment), which makes me think my PC already thinks I have PyRevit installed (I don't have great knowledge on application installs etc on PCs - but I've all the uninstall steps so not sure why this is coming up). 

Second - when I try any of the options, I always run into an error that says there was a problem with the "Windows Installer package". 

I've attached copies of the error logs from each operation run. Please let me know if I'm doing something wrong on my end or what a potential fix might be. 

Thanks
S
[Uninstall.LOG](https://github.com/eirannejad/pyRevit/files/7391954/Uninstall.LOG)
[Repair.LOG](https://github.com/eirannejad/pyRevit/files/7391956/Repair.LOG)
[Modify.LOG](https://github.com/eirannejad/pyRevit/files/7391957/Modify.LOG)

![PyRevit_Issue2](https://user-images.githubusercontent.com/92946910/138333242-450e69d0-d716-43f0-bb49-940f97c5425b.jpg)
![PyRevit_Issue1](https://user-images.githubusercontent.com/92946910/138333243-532a3623-6e23-4f66-b81d-5ae5c46497ec.jpg)

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists
