### ISSUE TITLE
Packages and Tags extension is not working

### ISSUE THREAD

**Issue by danielderidder** [eirannejad/pyRevit#1364]
**Describe the bug**
when I want to use the 'Tag Selected' button after selecting some components I get a window with only codes instead of the window I see in the video to give a tag to the selected components

**To Reproduce**
1. Go to 'pyrevit tab'
2. Click on 'Tag Selected'

**Expected behavior**
I expected to see the Tag window so I could fill in a name for the DOCTAG parameter  linked to my selected components

**Screenshots**

**Desktop (please complete the following information):**
 - pyRevit Version [V4.8.8]
 - pyRevit Environment: ==> Running Revit Instances
Error: De objectverwijzing is niet op een exemplaar van een object ingesteld.

**Comment by bimgeek** [comment]
![image](https://user-images.githubusercontent.com/51519350/141780556-8e23922d-d239-437c-aec6-34383995cc8c.png)
This is the screenshot I get.

**Comment by operta** [comment]
+1 I am using Revit 2022

**Comment by jmcouffin** [comment]
Same issue as https://github.com/eirannejad/pyRevit/issues/1632
fixed already
uninstall previous version and try the latest installer https://github.com/eirannejad/pyRevit/actions/runs/3175784126
Please close the issue if fixed

**Comment by jmcouffin** [comment]
@danielderidder @bimgeek @operta

**Comment by jmcouffin** [comment]
should be fixed by PR https://github.com/eirannejad/pyRevit/pull/1634

**Comment by jmcouffin** [comment]
- you need to create a 'doctag' and apply it to the document categories before using the tag tools
