### ISSUE TITLE
Downloaded version 4.8.8 and the Keynotes Manager tab is not on the ribbon. 

### ISSUE THREAD

**Issue by woabessi** [eirannejad/pyRevit#1366]
I have downloaded Pyrevit 4.8.8 on Revit 2021 and the Keynotes Manager tab is not on the ribbon.
![pyrevit ribbon](https://user-images.githubusercontent.com/93010210/138515279-3fa8194c-bd04-4410-9ad9-4d65714bd425.PNG)

**Comment by eirannejad** [comment]
It does work with BIM360. Make sure you have the Autodesk drive installed and the keynote file is also hosted on BIM360
