### ISSUE TITLE
Revit 2021.1 and PyRevit 4.8.8 Eror

### ISSUE THREAD

**Issue by SantoDemi** [eirannejad/pyRevit#1367]
Recently updated to Revit 2021.1. and installed pyRevit 4.8.8 afterwards.

pyRevit seemed to install without issue. When I initially opened Revit afterwards, I got the typical security pop up asking me if I want the add-in to "Always Load" or "Do Not Load". After selecting "Always Load", I got the attached popup error window. I get the same popup error window every time I open Revit now. The pyRevit tab in the Revit ribbon does not load.

I tried pyrevit attach master 277 --installed in the command prompt, but it did not resolve the issue.

To Reproduce

Open "Revit 2021",
Popup window "PyRevitLoader - Error Loading pyRevit" appears,
Close popup window,
pyRevit tab not loaded in Revit ribbon.
Expected behavior
Revit opens (without popup error window). pyRevit tab available from Revit ribbon.
![1WjmqwCcRD0](https://user-images.githubusercontent.com/93122481/138664244-597083b3-caeb-4eb1-bad5-23e11e9e319d.jpg)

**Comment by ArchTuan194** [comment]
I had the same problem and my solution is delete file "pyRevit_config.ini" in the folder above, then I reopen Revit. It's okey- You can try.

**Comment by jmcouffin** [comment]
@SantoDemi answer by @ArchTuan194 should work
you might have a wrong character or path in your config file

**Comment by jmcouffin** [comment]
@SantoDemi please close the issue if solved
