### ISSUE TITLE
Schedule - ExportScheduleToTextOnDesktop is  not working for me

### ISSUE THREAD

**Issue by mdengusiak** [eirannejad/pyRevit#137]
I tried to export Schedules but always got this message,

![image](https://cloud.githubusercontent.com/assets/14005893/20707432/c04e4aaa-b62b-11e6-81bd-6206c0170155.png)

**Comment by eirannejad** [comment]
This happens because you have clicked on a schedule line and Revit is returning that object as the selected element. You must have the schedule selected in the project browser (Selected object must be a schedule). Try it out and let me know if it works

**Comment by gtalarico** [comment]
@eirannejad I have a similar version (open in excel) that has some improvements, I can do a PR if you would like:

1. when selected element is not a schedule, check if active view is a schedule, and use that.
2. Allows you to use a selected schedule instance selected on a sheet.

Basically this:
```
selected_schedules = [e for e in selected_elements
                                    if isinstance(e, (DB.ViewSchedule, DB.ScheduleSheetInstance))]

# If no view is selected, check if Active View is a schedule
if not selected_schedules and isinstance(uidoc.ActiveView, DB.ViewSchedule):
    selected_schedules = [uidoc.ActiveView]
```

**Comment by eirannejad** [comment]
@gtalarico  Pretty please if you have time. Much appreciated.

**Comment by mdengusiak** [comment]
I tested and no warning but no export just blank screen, but I guess  @gtalarico will try to implement his improvement :)

![schedule](https://cloud.githubusercontent.com/assets/14005893/20727915/9b16a7b4-b67b-11e6-916c-c63acf379f99.gif)

**Comment by eirannejad** [comment]
@mdengusiak Okay so I know this is silly but Revit sometimes loses focus of the project browser and doesn't return the selected elements. Try selecting the sckedule, rung the tool, select it again and run the tool again. The output window will pring the schedule name and the exported file name. Same happens with the Add and Move viewport tools under the Sheets pulldown button. I always have to select the sheets two times.
