### ISSUE TITLE
Error invoking .NET external command

### ISSUE THREAD

**Issue by gustavomsgusmao** [eirannejad/pyRevit#1373]
**Describe the bug**

I'm currently moving some DLLs addins to pyrevit using the .invokebutton since the deployment by PyRevit works better than creating installers for each addin. It was working just fine but I found an exception that I don't know if can be fixed without changing the DLL itself: Some DLLs that are working on Revit directly (Using Addins Folder or using the Add-ins Manager), but if I try to invoke using pyRevit it is returning "Error invoking .NET external command".

After a few tests, I found that the issue is because the DLL uses a Reflection to get the DLL path and then refers to //Images folder to create a WPF Form. The issue is: running the DLL directly in Revit returns a Path, but using this reflection within pyrevit returns an empty string

So I have two questions:
 - Is there any settings in pyRevit to fix it without changing the DLL?
 - If the option above is not possible: Is there a way to refer to the DLL path to get access to the Images Folder or any additional reference file?

**To Reproduce**
1. Create any DLL that uses some of the following methods:
     - Assembly.GetCallingAssembly().Location
     - Assembly.GetExecutingAssembly().Location
     - typeof(App).Assembly.Location
     - Assembly.GetEntryAssembly().Location
2. Invoke this DLL using pyrevit
3. It will fails when trying to use a path retrieved from the methods above

**Screenshots**
![image](https://user-images.githubusercontent.com/37643304/140081937-8f0ebaf1-5fd4-43c4-8c35-236e387195ae.png)

**Desktop**
 - OS: Windows 10
 - pyRevit Version: 4.8.8
 - pyRevit Environment: 

![image](https://user-images.githubusercontent.com/37643304/140082921-e508e192-9890-48d6-ac94-35faa70c669a.png)

**Comment by Blame4** [comment]
about this, the same exception thrown when using static or dynamic resources in WPF Xaml designing

**Comment by dosymep** [comment]
Hello, I think it isn't bug because this is a feature of how pyrevit works.

pyrevit loads .NET dlls without context uses method [Assembly.Load](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.load?view=net-6.0).

https://github.com/eirannejad/pyRevit/blob/master/pyrevitlib/pyrevit/runtime/InvokableDLLEngine.cs#L43

**Comment by eirannejad** [comment]
Fixed by https://github.com/eirannejad/pyRevit/pull/1797
