### ISSUE TITLE
ERROR [pyrevit.extensions.genericcomps] Folder*: Does not have a script file

### ISSUE THREAD

**Issue by cgofer** [eirannejad/pyRevit#1375]
**Describe the bug**
I've tried creating my own Revit Extensions after some "Interactive Python Shell" trials.

I did it following de tutorial bellow: https://www.youtube.com/watch?v=zERdPh1vNBQ

For some reason when I try to load the extension from pyRevit > Settings appears de following message: 
"ERROR [pyrevit.extensions.genericcomps] Command <type_id '.pushbutton' name 'hello' @ 'C:\Users\cgofer\Desktop\MyExtension\MyCostumeExtension.extension\My tools.tab\Basic Tools.panel\hello.pushbutton'>: Does not have script file."

**Screenshots**
Loading Error
![PyRevitError](https://user-images.githubusercontent.com/93708393/140294668-93b4613c-4a21-4623-8144-984042146722.JPG)

Panels and buttons are created
![Buttons](https://user-images.githubusercontent.com/93708393/140297299-6e1d556d-9f52-4984-85eb-94f0e47bc20d.JPG)

Buttons don't work
![RevitError](https://user-images.githubusercontent.com/93708393/140294687-0ed29212-4cc7-4bcf-9752-5130fef9c57c.JPG)

pyRevit Settings
![PyRevitSettings](https://user-images.githubusercontent.com/93708393/140294745-c775023d-e782-4b84-999d-92a88bec26ba.JPG)

Folder structure
![Folder](https://user-images.githubusercontent.com/93708393/140294708-f792875e-d6a3-46cc-b155-1d1237d708dd.JPG)

Example script
![Script](https://user-images.githubusercontent.com/93708393/140294930-397140cf-f5b3-4722-9582-fd9bb53343f5.JPG)

**Desktop:**
 - OS: Microsoft Windows 10 [Version 10.0.19043]
 - pyRevit Version 4.8.8

**Comment by cgofer** [comment]
And here's the solution!! The icon has to be named "icon" and de script has to be named "script".

Thanks anyway. 

![solution](https://user-images.githubusercontent.com/93708393/140314759-47918de2-fbaf-40c8-8b08-58da09b384d3.JPG)

**Comment by jmcouffin** [comment]
actually you can name the script:
"whatever you like_script.py"
"or like this.script.py"

**Comment by jmcouffin** [comment]
@cgofer you should close the issue

**Comment by cgofer** [comment]
Thanks @jmcouffin , it was my first github issue, in fact I opened this account for it.

**Comment by jmcouffin** [comment]
No worries @cgofer
I would have closed it but just Ehsan and you can do so in this repo. And
I'm sure that Ehsan is busy enough.
You can post other issues, no trouble. You could also post questions on the
pyrevit discourse forum.
Cheers to your first issue!
