### ISSUE TITLE
My scripts only work once I open Dynamo

### ISSUE THREAD

**Issue by cgofer** [eirannejad/pyRevit#1378]
**Describe the bug**
If I use any of the buttons configured thanks to pyRevit without having previously started Dynamo. Even though I close dynamo, the error no longer occurs and the script runs successfully. It happens with all my scripts, although I show the simplest one.

**Screenshots**
TraceBack
![TraceBack](https://user-images.githubusercontent.com/93708393/140749159-6ed35216-78c1-4a4c-8319-3aae23bdb210.png)

Script
![Scrpit](https://user-images.githubusercontent.com/93708393/140749169-8386d0ba-ac6f-45b3-bd69-2a40bdc7ebc5.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 [Version 10.0.19043]
 - pyRevit Version 4.8.8

**Comment by eirannejad** [comment]
You are using `RevitServices` to get the handle to current application and document. This module is part of Dynamo API and is available only when dynamo is loaded. See other pyRevit scripts to see how the `doc` and `uiapp` are collected.
