### ISSUE TITLE
Idea: Mode CreatOrientSection to Elemet

### ISSUE THREAD

**Issue by mdengusiak** [eirannejad/pyRevit#138]
Idea..
When we have any element wall, pipe, duct, that is tilted we could just select and a section will be open.
So we do not have to place section then rotate and then open again. 

![image](https://cloud.githubusercontent.com/assets/14005893/20708147/f108b902-b62e-11e6-88c1-7f2d525fce49.png)

**Comment by eirannejad** [comment]
Brilliant. Thanks @mdengusiak
