### ISSUE TITLE
Specific pattern, can make pattern even achieve this?!

### ISSUE THREAD

**Issue by jmqrsq** [eirannejad/pyRevit#1380]
I have tried for hours to make this particular pattern with pyRevit's Make Pattern tool. I am beginning if the tool simply can't do it for me. I am on a time crunch to get some floor finishes completed. Any immediate help would be fantastic and much appreciated!

Can this be achieved using the tool? Basically, we need the square to be centered and it cannot repeat. 

![image](https://user-images.githubusercontent.com/54898486/140965529-8f31d13a-25f9-4cb1-8139-81fef943dc09.png)

I have tried everything I cannot get it to work. This is an image of my current Revit detail lines I am trying to use as my pattern:

![image](https://user-images.githubusercontent.com/54898486/140965877-72297fd6-8173-4373-8e7f-a7ffe7ac3a6e.png)

The red remarks what the pattern wants to be in my finish plan in the end. I would center this square over an entry door in my project. Is this even possible?

TIA!

Jaysyn

PS: Please forgive me if this is not the place to ask for help. Kindly relay the correct place to ask this if this is not the correct place to ask such a question. Thank you.

**Comment by jmcouffin** [comment]
@jmqrsq hi, 
a more suited place: https://discourse.pyrevitlabs.io/

**Comment by eirannejad** [comment]
Asked here https://discourse.pyrevitlabs.io/t/specific-pattern-can-make-pattern-even-achieve-this/657
