### ISSUE TITLE
pyRevit: Failed to Initialize the add in "PyRevitLoader"

### ISSUE THREAD

**Issue by debbiech** [eirannejad/pyRevit#1381]
Hi,

There was an error upon loading the revit 2018, 2019 after I installed pyRevit 4.8.8.

I uninstalled the pyRevit, remove the folders in programfiles then restarted the computer then reinstalled but issue still persist.

The complete error message is: 
External Tools-Add-in Assembly Not Found
Failed to initialize the add-in "PyRevitLoader" because the assembly "C:\Users\___\AppData\Roaming\p..\pyRevitLoader.dll" does not exist.

Below is the screenshot of the above error message 

![pyrevitloader](https://user-images.githubusercontent.com/80445781/141026420-67d0ce68-9262-4bb2-bab5-0876b6da79f6.PNG)

![image](https://user-images.githubusercontent.com/80445781/141026485-64e8609c-066c-48f4-b900-1a02cb216a50.png)

Kindly assist us on how to fix the issue.

Thank you.

Regards,

**Comment by timakutsko** [comment]
I've this problem too. With version 4.6.24, that I used before - there were no problem like this. 

And some more - if I install like admin (creating folder in Program Files), it's work correctly. But if I install NOT like admin (creating folder in %appdata%), it's doesn't work.

Thank you

**Comment by eirannejad** [comment]
Does the `PyRevitLoader.dll` exist at the shown path? Please run `pyrevit env` on command line and share the results here

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists
