### ISSUE TITLE
Keynote Manager Generating Extra Files

### ISSUE THREAD

**Issue by alexdaversa** [eirannejad/pyRevit#1382]
Hi Ehsan,

The keynote manager is generating many extra text files in the keynote directory when converting from a standard keynote file. Screenshot is below. I will try to find time later this week to investigate and submit a PR. Project name redacted but not relevant to this issue.

![keynote error](https://user-images.githubusercontent.com/44062587/141133720-07e76111-dea2-495c-bb57-5312b0cc8623.png)

 - pyRevit Version 4.8.9.21298+0023
 - Revit Version 2020.2.6 (latest as of time of bug report)

**Comment by eirannejad** [comment]
Ya you are using a debug version `4.8.9.21298+0023`. Release builds don't do that.

**Comment by alexdaversa** [comment]
Huh, the more you know! I will keep that in mind for any other odd debug-looking behavior that I run into, and try not to put my foot in my mouth asking you about it next time too
