### ISSUE TITLE
Does PyRevit uninstall itself randomly

### ISSUE THREAD

**Issue by apsis0215** [eirannejad/pyRevit#1386]
Asking if there a feature that uninstalls it after a while? And if so under what conditions?

We have a few users who have PyRevit just go missing, thought I'd check here among other resources.

Thanks-
Ron

**Comment by eirannejad** [comment]
Nope. It does not. Always run `pyrevit env` on the machine to check pyrevit environment. This is most probably a problem of pyRevit being attached to installed Revit versions
