### ISSUE TITLE
output.update_progress doesn update output window

### ISSUE THREAD

**Issue by max-bold** [eirannejad/pyRevit#1388]
`output.update_progress(i, max)` doesn update output window so progress is updated only when some output is made

This is a sample code:
```
output = script.get_output()
print('hello')
for i in range(100):
    output.update_progress(i, 100)
    sleep(0.1)
    print(i)
```

If last `print(i)` is commented it's expected to see `'hello'` in output window and moving progress bar. But in fact we see only a blank output window until the loop ends. And only after that we see `'hello'` and 99% progress bar (and why 99? not 100?).

![изображение](https://user-images.githubusercontent.com/77934776/142362853-26bff06b-263b-4948-8a69-d3ee12aabd49.png)

==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.8" | Path: "D:\PyRevit"
==> Attachments
master | Product: "2021 First Customer Ship" | Engine: IPY277 (277) | Path: "D:\PyRevit"
master | Product: "2019.2 (Update)" | Engine: IPY277 (277) | Path: "D:\PyRevit"
==> Installed Extensions
LAB | Type: Unknown | Repo: "" | Installed: "C:\Users\user\Desktop\ForRevit\pyRevitScrips\LAB.extension"
==> Default Extension Search Path
C:\Users\user\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\Users\user\Desktop\ForRevit\pyRevitScrips
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2019.2 (Update) | Version: 19.2.0.65 | Build: 20181217_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
PID: 10328 | 2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2021"
==> User Environment
Microsoft Windows 10 [Version 10.0.19042]
Executing User: BOLDOREV\user
Active User: BOLDOREV\user
Admin Access: No
%APPDATA%: "C:\Users\user\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.7.2 v4.X
Installed .Net-Core Target Packs: v3.1.415 v5.0.301 v5.0.303
pyRevit CLI 4.8.8.0

**Comment by eirannejad** [comment]
In your loop, the variable `i` will never reach the intended `100`. So the progress was will never reach the end. Modify the script to `output.update_progress(i + 1, 100)`

**Comment by max-bold** [comment]
> In your loop, the variable `i` will never reach the intended `100`. So the progress was will never reach the end. Modify the script to `output.update_progress(i + 1, 100)`

Thanks a lot! You're right. It's my mistake. 

But what about the main issue? That progress bar is updated only when some output is made?

**Comment by eirannejad** [comment]
when you are looping very fast, the UI thread doesn't get a chance to update the progress bar. Adding a print statement in there would help.

If you only need a progress bar without any output you can use the progress bar that snaps on top of the window:

https://www.notion.so/pyrevitlabs/Effective-Output-43baf34d2ca247ada8e040bcb86613a2#68ad3e5f74464afda382e9948ae7468d

https://github.com/eirannejad/pyRevit/blob/decb9f71b86ef2d9350e71b0c04468a4ffbae24b/extensions/pyRevitDevTools.extension/pyRevitDev.tab/Debug.panel/Unit%20Tests.pulldown/Test%20Progressbar.pushbutton/script.py#L12

**Comment by max-bold** [comment]
Interesting note: if we `print('')` nothing is printed (no empty line) but the progress bar is updated. Now the code looks like:
```
output = script.get_output()
print('hello')
for i in range(100):
    output.update_progress(i, 99)
    sleep(0.1)
    print('')
print('End')
```
Thanks a lot @eirannejad !
