### ISSUE TITLE
Helper calss for Autodesk.Revit.DB.Transaction

### ISSUE THREAD

**Issue by max-bold** [eirannejad/pyRevit#1389]
It's much more convenient to run a revit transaction in `with` statement, but Autodesk.Revit.DB.Transaction doesn't have `__enter__` and `__exit__` methods. So i think, providing a `pyrevit.transaction` class would be a good idea.

This is implementation, i use everywhere:
```
class transaction(DB.Transaction):
    def __init__(self, doc, text):
        super(transaction, self).__init__(doc, text)
        self.cancelled = False

    def __enter__(self):
        super(transaction, self).Start()
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        if self.cancelled:
            super(transaction, self).RollBack()
        else:
            super(transaction, self).Commit()

    def cancell(self):
        self.cancelled = True
```
In code it looks like:
```
with transaction(doc, 'Test') as t:
    dosomething()
    if somethinggotwrong():
        t.cancell()
```
Some times i think, to get `doc` right in `transaction.__init__()` method. But it should be discussed. Then the `__init__` would look like:
```
def __init__(self, text):
    doc = __revit__.ActiveUIDocument.Document  # type:ignore
    super(transaction, self).__init__(doc, text)
    self.cancelled = False
```
Some times we need to make in intermediate commit (when working with thousands of elements). So one day i added `intcommit()` method to `transaction` class:
```
def intcommit(self):
    if not self.cancelled:
        super(transaction, self).Commit()
        super(transaction, self).Start()
    else:
        super(transaction, self).RollBack()
```

**Comment by chuongmep** [comment]
It will be difficult if we have many transactions to process together

**Comment by htlcnn** [comment]
rpw did it a while ago. But I find it more convenient and easier to maintain code when I use plain Revit API.

**Comment by thumDer** [comment]
what is the problem with the pyrevit wrapper?
[https://github.com/eirannejad/pyRevit/blob/master/pyrevitlib/pyrevit/revit/db/transaction.py](https://github.com/eirannejad/pyRevit/blob/master/pyrevitlib/pyrevit/revit/db/transaction.py)

**Comment by McBuff** [comment]
Have you tried this?
```
from pyrevit import script
with script.revit.Transaction("My changes"):
    do_stuff()
```
It also takes a document if you want.
You can find the implementation here
pyrevit/revit/db/transaction.py

**Comment by max-bold** [comment]
Some days ago found the RPW version of this code. Works peaty well. Thanks for your comments. Issue closed.
