### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by aumaco** [eirannejad/pyRevit#139]
Hello,
The repository of RevitPythonLoader informed in the installation guide of pyRevit need to be updated.
"Page not found!"

**Comment by eirannejad** [comment]
Thanks @aumaco 
I'll fix this. For your information the `RevitPythonLoader` has been placed under the `loader` branch of the `pyRevit` repository.

**Comment by eirannejad** [comment]
Easy installer provided in new version
