### ISSUE TITLE
Setting button not working

### ISSUE THREAD

**Issue by houkvanlake** [eirannejad/pyRevit#1390]
When I click on Settings (pyRevit/Settings) a command window opens with a text description starting with: 
IronPython Traceback
and including info about the: Script Executor Traceback.

But I have no possibility to see the Settings.

I have the v.4.8.8 installed and everything else works

**Comment by McBuff** [comment]
Can you provide a copy/paste of that revit Script Executor Traceback? The entire thing if you will, it contains important information on what went wrong.

It's also handy that you provide a copy of the output of "pyrevit env" on your command line.
You can do this as follows:
- Open a Command Prompt ( or Powershell) window
- Type: pyrevit env
- Select the output and paste it etc...

**Comment by eirannejad** [comment]
@houkvanlake Needs info. Closing this since it is stale. Please open the issue again when you have more info
