### ISSUE TITLE
UI Setting / User config setting to hide panels from users

### ISSUE THREAD

**Issue by jake1108** [eirannejad/pyRevit#1391]
**Is your feature request related to a problem? Please describe.**
The PyRevit plugin has become essential to my Revit workflow and is; I believe, an invaluable tool that all Revit users should have. HOWEVER - some Revit users are not yet 'qualified' to have access to some of the functions within the add-in (primarily the tools in the 'Project' Panel. 

**Describe the solution you'd like**
It would be great to have the option of hiding any panel/s from users either at installation or via password protection within the settings. 

**Describe alternatives you've considered**
Unfortunately, due to trust issues, the only other solution is not installing PyRevit for a number of users :( .

**Additional context**
It also means that custom extension deployment of personal Python scripts are also not yet possible to users on a company-wide basis (Something I would love to be able to do).

**Comment by Rocinante74** [comment]
FYI - I am not associated with pyRevit at all.

Something that our company has done is disable all the standard pyRevit extensions for everyone and added our own extensions. Perhaps a solution could be to make your own extension with everything minus the project panel (just copy the whole extension then delete the project.panel folder). 

This coupled with using pyRevit CLI to remove user's ability to change their extension settings (if needed) you can feel safe knowing they don't have those options.

**Comment by jake1108** [comment]
Hi @Rocinante74,

Thanks for sharing your companies approach to utilising PyRevit. 

It led me down a path into my C: drive to all of the extension files where I realised I can remove functionality by simply removing the files themselves from within the pyRevitTools.extension\pyRevit.tab. This way there is no need to create an extension containing a curated list of files for users as you suggested as they are simply gone from the primary tab. 

I will therefore close this issue as I believe the ability to have all of PyRevit's functionality on install is important. Any curation of specific tool access at user level can be managed by any capable IT team via the method stated above of simply removing files.
