### ISSUE TITLE
Load Error

### ISSUE THREAD

**Issue by Shepard713** [eirannejad/pyRevit#1392]
I've installed the PyRevit latest version.  Both as an admin and normal user.  Once done I open Revit, get the enable plug in message.  Once done, Revit just closes.  I try to open it, starts to open and then wont open.  Then when I go to uninstall it, it wont remove the system variable, and completely hoses the users profile.  Have tested this multiple times as admin and non admin and same thing.  Now I have to uninstall Revit and start from scratch.  And because it hoses the system variable, I have to recreate the usres AD account and start from scratch with a fresh login.

On another system the exe will not even install.  Starts to install then just fails and goes to a log file.  I haver run the DR. PyRevit, but does not work for me.

Any help on this would be great... Can demonstrate all errors.

Ben McDonald 
ben@isdsolutions.com

**Comment by eirannejad** [comment]
I pushed a fix and the WIP installers are here:
https://github.com/eirannejad/pyRevit/actions/runs/1669963623
Would you mind installing and see if it loads with Revit?

The problem seems to be related to `System.Web` dll that was being loaded for the x86 architecture. I had the same warning on my machine but it was not throwing any issues.

**Comment by Shepard713** [comment]
You got it... give me until Monday.  Thank you for the update, hopefully this works.

Have a good weekend.

Ben

**Comment by Shepard713** [comment]
Do you have time right now...

I just installed it and when launching the app it closed again.

**Comment by Shepard713** [comment]
I had to remove the PLUG IN.

Maybe I installed the wrong version... When I went to you link below that was no install file????

**Comment by Shepard713** [comment]
How about we do a remote session after the user goes home tonight... 4:30 PM??

**Comment by eirannejad** [comment]
Run `pyrevit env` on command line and share the results please. Also please upload all the *.log files from `%APPDATA%/pyRevit/XXXX` where `XXXX` is the Revit version that is crashing.

**Comment by jmcouffin** [comment]
Stale 
Closing the issue
