### ISSUE TITLE
Automatic pdf creating without asking for a destination for every single drawing

### ISSUE THREAD

**Issue by david939david** [eirannejad/pyRevit#1393]
**Is your feature request related to a problem? Please describe.**
Is there a way to get rid of clicking "save" for every plotted drawing? - it consumes a lot of unneeded attention.

**Describe the solution you'd like**
Just automatic creating of pdf's with asking only once per session about destination.

**Comment by colmnolan** [comment]
Why not just use the new builtin PDF exporter by Autodesk? It is available for Revit 2022 and is a pretty fast exporter. It does not request a destination for each drawing. You can do them in batches.

**Comment by david939david** [comment]
Ohh I'm still using 2021, didn't know that there is innovation in 2022. Is it also support variable sizes batch plot?

**Comment by colmnolan** [comment]
Yes, you can have varied sheet sizes, plus you can easily create sheet sets.

**Comment by Robbo1234** [comment]
Hi David, just us the free PDF Creator driver which facilitates batch
plotting using PyRevit Print Sheets.

https://www.pdfforge.org/pdfcreator/download

**Comment by david939david** [comment]
Thank you for answers! Robbo1234 I've tried PDF Creator in the past and I don't remember why, but it wasn't enough for me, so I use Adobe PDF.
