### ISSUE TITLE
Will pyrevit fully support cpython with pythonnet one day ? Is this on the current scope? --> some libs must be rewritten/corrected

### ISSUE THREAD

**Issue by tillbaum** [eirannejad/pyRevit#1396]
Will pyrevit fully support cpython with pythonnet one day ? Is this on the current scope?

 --> some libs must be rewritten/corrected

**Comment by eirannejad** [comment]
That is the goal.

**Comment by emilaz** [comment]
@eirannejad thanks for your amazing work on pyrevit! I wanted to ask whether there is a current timeline for this? Seems like this was the goal ever since the CPython engine was first introduced 3 years ago.
