### ISSUE TITLE
WSCommCntr4.exe

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#140]
Is it possible that the current loader is conflicting with WSCommCntr4.exe?
Incosistently the loader crashes during verbose loading and it seems to have an issue with this executable as well.  Typically restarting Revit will allow the load.  This might be in the works already with your rebuild, but thought I'd bring it up.

**Comment by gtalarico** [comment]
not sure what WSCommCntrl, is, but if crashes on loading, might be same as:
https://github.com/eirannejad/pyRevit/issues/134
and
https://github.com/eirannejad/pyRevit/issues/127

Either way, should be resolved on newer builds (as per comment on #127)

**Comment by thazell** [comment]
@gtalarico Yes, I think they may be related.

**Comment by eirannejad** [comment]
Fixed in new version
