### ISSUE TITLE
Copy Sheets To Open Documents

### ISSUE THREAD

**Issue by risaku80** [eirannejad/pyRevit#1400]
Love this tool.  It is incredibly useful.  There is one issue that I am running into.  On a sheet that has Views with CAD links, Pyrevit is not preserving the linking but rather converting them to CAD imports.  This is requiring us to go back and manually swap them out.  Is there a way to get Pyrevit to preserve the linking or is there a different way to duplicate the sheet between models that would?

Thank you

Roan

**Comment by eirannejad** [comment]
Great catch. This is probably a side effect of copying-pasting the CAD link between models.

- [ ] Revise the tool to be place and instance of linked CAD content instead of pasting it
