### ISSUE TITLE
Error opening selected keynote file

### ISSUE THREAD

**Issue by alexandra-nelson-shqevi** [eirannejad/pyRevit#1402]
We have pyRevit version 4.8.4

![image](https://user-images.githubusercontent.com/32757635/146986991-fce4a45b-cee7-4df0-9a80-d9c37a1f4a2a.png)

**To Reproduce**
1. Go to Keynote Manager and the following error message pops up. (Image Below)

![image](https://user-images.githubusercontent.com/32757635/146987074-afc11ea0-2e34-4fa2-9b99-87d0b45118fc.png)

2. Click on 'OK' to move forward.
3. Select a keynote ".txt" file and click to 'Open' the file. (Image Below)

![image](https://user-images.githubusercontent.com/32757635/146988845-13fd5666-64ba-4008-af49-8431c5a53450.png)

4. The file attempts to lead and then pops up with the following error message. (Image Below)

![image](https://user-images.githubusercontent.com/32757635/146987126-1faef86e-cedb-4e99-9be0-09a03e2fef1b.png)

**Additional Notes**
- Tried running pyRevit Keynote Manager in R2019 + R2021 - same issue in both.
- Other pyRevit tools are working fine.

**txt file**

![image](https://user-images.githubusercontent.com/32757635/146990152-c24d2227-d9f9-424e-80aa-500e1a8b7372.png)

**Computer specs are below**

![image](https://user-images.githubusercontent.com/32757635/147117817-6b618602-ac7e-488f-a665-6ba66c0f750f.png)

64-bit operating system

**pyRevit Environment**

'==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
Unknown | Product: "Autodesk Revit 2020" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2020\pyRevit.addin"
Unknown | Product: "2019.2.2 Hotfix" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2019\pyRevit.addin"
Unknown | Product: "2018.3.3 Security Fix" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2018\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\a.nelson\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2020 | Version: 20.2.50.77 | Build: 20210804_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
2017.2.5 Security Fix | Version: 17.0.1169.0 | Build: 20190508_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.18363]'

Thank you for your help on this!!

**Comment by eirannejad** [comment]
Where is `testimport.txt` located? is it on a BIM360 drive?

Would it be possible to upgrade your pyRevit to 4.8.8 (https://github.com/eirannejad/pyRevit/releases/tag/v4.8.8) and try with that? I'd suggest testing this on a separate machine to make sure it works for your environment. There have been a few reports of it not working with Revit 2022 although I can not replicate the errors myself

**Comment by eirannejad** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/1383
