### ISSUE TITLE
PyRevit does not appear in REvit 2019 but appears in REvit 2022. Both Revit Versions are installed

### ISSUE THREAD

**Issue by jeggieboyski** [eirannejad/pyRevit#1404]
PyRevit does not appear in REvit 2019 but appears in REvit 2022. Both Revit Versions are installed

**Comment by eirannejad** [comment]
Please run `pyrevit env` on command line and share the report here

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists
