### ISSUE TITLE
Pyrevit installed but not showing on Revit 

### ISSUE THREAD

**Issue by etovarBIM** [eirannejad/pyRevit#1405]
I have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load. I have completed most of the forum instructions including issue 1075 with no luck. 

![terminal shot ](https://user-images.githubusercontent.com/96589014/147269046-aedd467b-5443-49e5-8d2f-d9e7c9f30ea4.png)

 - OS: Windwos 10 
 - pyRevit Version 4.8.8
 - pyRevit Environment: 

"U:\>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.8" | Path: "C:\Users\etovar\AppData\Roaming\pyRevit-Master"
==> Attachments
Unnamed-3935161 | Product: "Autodesk Revit 2021" | Engine: IPY277 (277) | Path: "L:\+COmputational Design\CO Revit Addins\pyRevit-4.6.12" | AllUsers
Unnamed-3935161 | Product: "Autodesk Revit 2020" | Engine: IPY277 (277) | Path: "L:\+COmputational Design\CO Revit Addins\pyRevit-4.6.12" | AllUsers
Unnamed-3935161 | Product: "2019.2 (Update)" | Engine: IPY277 (277) | Path: "L:\+COmputational Design\CO Revit Addins\pyRevit-4.6.12" | AllUsers
Unnamed-3935161 | Product: "2018.3.2" | Engine: IPY277 (277) | Path: "L:\+COmputational Design\CO Revit Addins\pyRevit-4.6.12" | AllUsers
Unnamed-3935161 | Product: "2017.2.4" | Engine: IPY277 (277) | Path: "L:\+COmputational Design\CO Revit Addins\pyRevit-4.6.12" | AllUsers
master | Product: "2016 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Users\etovar\AppData\Roaming\pyRevit-Master"
master | Product: "2015 Update Release 14" | Engine: IPY277 (277) | Path: "C:\Users\etovar\AppData\Roaming\pyRevit-Master"
master | Product: "2014 Update Release 3" | Engine: IPY277 (277) | Path: "C:\Users\etovar\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\etovar\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2021 | Version: 21.1.21.45 | Build: 20201116_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
Autodesk Revit 2020 | Version: 20.2.60.15 | Build: 20211019_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2 (Update) | Version: 19.2.0.65 | Build: 20181217_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2018.3.2 | Version: 18.3.2.7 | Build: 20181011_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
2017.2.4 | Version: 17.0.1158.0 | Build: 20181011_1645(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
2016 First Customer Ship | Version: 16.0.428.0 | Build: 20150220_1215(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016\"
2015 Update Release 14 | Version: 15.0.421.0 | Build: 20160512_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2015\"
2014 Update Release 3 | Version: 13.11.4 | Build: 20140709_2115(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2014\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19042]
Executing User: COARCHITECTS\etovar
Active User:
Admin Access: No
%APPDATA%: "C:\Users\etovar\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.8.0"

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists
