### ISSUE TITLE
Porting Apps to V4

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#141]
Before I either manually port my V3 apps to the V4 folder structure or write a tool for it, thought I'd ask if you had one you used.

**Comment by thazell** [comment]
Uploading my working file just in case others find it helpful.

[RestructurePyRevitfolder.zip](https://github.com/eirannejad/pyRevit/files/697133/RestructurePyRevitfolder.zip)

**Comment by eirannejad** [comment]
I was just typing a response. Thanks a bunch!

**Comment by thazell** [comment]
Thanks!  It was a rough working file, but it helped me and might help others too. Since I don't do much coding, I made it in dynamo :)  (use the tool you can I guess)
