### ISSUE TITLE
Print Sheets from a Linked File

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#142]
Enhancement: 
Just found this on Harry's website https://boostyourbim.wordpress.com/2013/07/13/print-sheets-from-host-linked-rvt-files/

and thought, that would be a really nice feature to have in pyRevit, particularly if it popped up a dialog box of all the sheets and the user could select the sheets they wanted to print.  Might be beyond my ability to convert c# to Python, but could be really valuable.

**Comment by eirannejad** [comment]
Nice! I'll work on it this week. Thanks a bunch

**Comment by eirannejad** [comment]
Added.

**Comment by thazell** [comment]
WOW!!!  That was so fast and it's a great feature!  

I'll get back to you once I have been able to use it a few more times. The only issue I had so far is that the window after printing multiple sheets went behind Revit and we didn't know so it was a little odd, but nothing education can't overcome.

**Comment by eirannejad** [comment]
Good thinking. I'll work on it. And I'll fix it so it closes the window after print.

**Comment by eirannejad** [comment]
Hum. Okay. Seems like I can not set a list of views to be printed in a linked model unless I open the model, save and reload. I'm however going to provide a list of existing Sheet sets in the linked model to be printed.

**Comment by thazell** [comment]
Interesting.  I think that's ok.  They can always be stapled after print. How does the script select the print settings, i.e. Size of sheet, etc.?

**Comment by eirannejad** [comment]
I'm working on it but generally I can go by defaults only otherwise the print manager requires changes to the linked document. It's poorly designed IMHO. Could've been a lot better.

**Comment by thazell** [comment]
No Worries,  Thanks It's a huge improvement as is!

**Comment by eirannejad** [comment]
Absolutely. Thanks for sending the web link
