### ISSUE TITLE
Extra text files generated by Keynote Manager

### ISSUE THREAD

**Issue by aaronbergmann** [eirannejad/pyRevit#1440]
**Describe the bug**
Keynote Manager is leaving temp files in the directory of the keynote text file and not automatically cleaning them up.

**To Reproduce**
1. Launch Keynote Manager
2. Edit Keynotes
3. Note numerous time-stamp-named text files in the keynote file directory.

**Expected behavior**
No extra files should be remain after using the keynote manager.

**Screenshots**

![image](https://user-images.githubusercontent.com/48157575/148130945-9446472a-1dd4-406f-96d3-1a804a966ea8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.8.9.21361+0320
 - pyRevit Environment:

'==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.9.21361+0320" | Path: "C:\Users\abergmann\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2020.2.5" | Engine: IPY277 (277) | Path: "C:\Users\abergmann\AppData\Roaming\pyRevit-Master"
master | Product: "2019.2.2 Hotfix" | Engine: IPY277 (277) | Path: "C:\Users\abergmann\AppData\Roaming\pyRevit-Master"
master | Product: "2018.3.3 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\abergmann\AppData\Roaming\pyRevit-Master"
master | Product: "2016 Update 6 for R2" | Engine: IPY277 (277) | Path: "C:\Users\abergmann\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\abergmann\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2020.2.5 | Version: 20.2.50.77 | Build: 20210804_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
2016 Update 6 for R2 | Version: 16.0.1161.0 | Build: 20160720_0715(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016\"
==> Running Revit Instances
PID: 20028 | 2020.2.5 | Version: 20.2.50.77 | Build: 20210804_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2020"
PID: 2572 | 2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2018"
==> User Environment
Microsoft Windows 10 [Version 10.0.18363]
Executing User: ECPHFD\abergmann
Active User: ECPHFD\abergmann
Admin Access: No
%APPDATA%: "C:\Users\abergmann\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.9.21361+0320'

**Comment by eirannejad** [comment]
:package: New public release are available for [4.8.10.22040](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.10.22040)
