### ISSUE TITLE
Print Sheets Selections Printing Blue

### ISSUE THREAD

**Issue by kpfanny** [eirannejad/pyRevit#1442]
**Describe the bug**
When using the Print Sheets tool, if you have a Revit link or any element selected when you initiate/run the print sheets command, they print shaded (blue) as they are currently visible in the Revit window. 

**To Reproduce**
1. Select an element or Revit Link in the model.
2. Navigate to Print Sheets command in pyRevit.
3. Print sheets where you have the elements selected.
4. Element will show up shaded whether printing black & white OR in color.

**Expected behavior**
Prior to printing, or when initiating the "Print Sheets" command, all elements currently selected in the model should be un-selected.

**Screenshots**
Screenshots from printed PDF (showing up exactly how they are when selected in Revit):
![image](https://user-images.githubusercontent.com/78550039/148246576-1cdcc285-3280-45c3-85f1-35d5c06b95f2.png)
![image](https://user-images.githubusercontent.com/78550039/148246704-5911d319-a90f-4148-98bd-2b28ed132225.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 19044
 - pyRevit Version 4.8.9.21361+0320

**Comment by eirannejad** [comment]
:package: New public release are available for [4.8.10.22040](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.10.22040)
