### ISSUE TITLE
Tab Coloring doesn't work

### ISSUE THREAD

**Issue by gyulnaraf** [eirannejad/pyRevit#1447]
Revit 2020.2.6
pyRevit 4.8.9

Tab Coloring is on, but tabs in Revit are grey. When I try to use "Background Fill", active tab is white without any text. 

![image](https://user-images.githubusercontent.com/81077423/148761060-b1a538f1-c12b-4839-b2cd-8ad88a8138be.png)

**Comment by eirannejad** [comment]
Would you send me a screenshot of the tab coloring settings?

**Comment by gyulnaraf** [comment]
![image](https://user-images.githubusercontent.com/81077423/148910955-8b3dc903-c7d1-45fc-adb7-00e21a79869f.png)

**Comment by gyulnaraf** [comment]
It doesn't work only on Revit 2020, on 2022 it works fine 
Windows 10

**Comment by eirannejad** [comment]
Uh it might be a UI layout difference between the two. Thanks a lot for the screenshot and testing

**Comment by eirannejad** [comment]
I can _not_ replicate the issue on 2020.2.6. I can not see the color settings on your screenshot so make sure there are no white colors. See this 

<img width="1057" alt="Screen Shot 2022-02-01 at 08 39 04" src="https://user-images.githubusercontent.com/8197916/152010843-a807d452-ff79-4aa1-8dbd-2ce788affec7.png">

**Comment by kmo425** [comment]
I was having tab coloring issues and found this thread... my settings doesn't show that whole "coloring theme" section. Is there something I need to do to get that to show up? 
![image](https://user-images.githubusercontent.com/72625942/156430964-8f11f9c6-3311-4a65-b4af-f47a193561cf.png)

**Comment by OK-84** [comment]
All is set-up for Tab- Coloring and works just fine when Revit is active. 
But everything reverts back to default after restart of Revit. Need to grab settings again to set it up.
Works fine for some of my colleagues, but just can't get it to work for me and others... tried saving a separate CSS file as well, Reinstall PyRevit,... evrything except editing registry, nothing takes. Reset every time back to default. Any ideas?
