### ISSUE TITLE
python script ending "*.pyc" (python file compiled to byte code ) is not found by pyrevit engine. Can it be in a future release?

### ISSUE THREAD

**Issue by tillbaum** [eirannejad/pyRevit#1448]
I am trying to run a script.pyc file. 
pyrevit doesn't recognize script.pyc file-ending as a python-file. 
Can *.pyc files be supported?

**Comment by eirannejad** [comment]
Not at the moment. Are you trying to hide the source code this way?

**Comment by tillbaum** [comment]
Yes.
