### ISSUE TITLE
Find Unsheeted Views

### ISSUE THREAD

**Issue by rbaggen** [eirannejad/pyRevit#145]
Hi Ehsan,

I'm new to Python and just started a little bit of programming.
Using your addin gives me a lot more productivity within Revit and more understanding of Python.

I have a little bit of a problem with Find Unsheetd Views, using this function gives a list of every view in the model, minus 4? I'm using Revit 2016 16.0.1185.0 20161004_0715(x64) Update7 for R2.
I want to use the script to cleanup the model and deliver it to the customer.

Can you have a look what goes wrong?

With regards, 

Rolph Baggen

**Comment by eirannejad** [comment]
Which pyRevit version are you using?

**Comment by rbaggen** [comment]
Hi Ehsan,

Thanks for emailing me back.

I'm using the last version I think.
And I think it's a problem that resides in my project, it's a large worksharing project.
So I have to do some investigation why this happens.

In new not worksharing project it works, so I have to test it on the worksharing models.I have.
I'll come back to you later on.

With regards,


Rolph Baggen

 

On 17 Jan, 2017, at 06:07 PM, Ehsan Iran-Nejad <notifications@github.com> wrote:

Which pyRevit version are you using?

**Comment by eirannejad** [comment]
Perfect. Let me know then.
