### ISSUE TITLE
Toolbar Maker - share the "safer" tools with New Revit Users

### ISSUE THREAD

**Issue by LF-Hatches** [eirannejad/pyRevit#1450]
**Describe current issue**
I'd love to be able to share PyRevit functions with more people in my office.
BUT. 
I'm not a _script hero_, and my coworkers even less so.
Sharing the wipe(all) functions is the stuff of bad dreams. 

**Describe the solution you'd like**
I'd love to have a "make toolbar" feature.  
Select from the current features in PyRevit, and a custom toolbar package for sharing comes out the other end. 
Also one that can be flexible enough to get tweaked to add a menu for:
 "hey - also use these approved dynamo scripts" at <insert specific directory here>

**Describe current workflow**
Currently: every time someone wants a hatch, I do it for them.
Currently: every time someone wants to import an excel set of sheet placeholders, I do it for them using the jankiest dynamo script ever made - but it saves _a million hours_ and I want to clean it up and share it with them... safely.

**Describe alternatives you've considered Part 1**
I've considered that a custom toolbar is something really easy to do once you've looked under the hood and figured out the API etc.
Eventually I'll figure out how to do this by myself? - but it might take FOR. EV. AH. to get up to speed. 
Still worth it. 💯 

**Describe alternatives you've considered Part 2**
Yes - there are many wonderful places to start learning more: 
    https://www.notion.so/Developer-Docs-2c88f3ecccde422d9504e20b6b9e04f8
    https://www.notion.so/Create-Your-First-Command-2509b43e28bd498fba937f5c1be7f485
Even though it doesn't seem like sharing bundles is a real thing yet?
    https://www.notion.so/pyRevit-Bundles-12323e3090904d9aa7cdc3d82095d3e3

**Additional context**
I stumbled across PyRevit when it said "custom hatch pattern maker", but now that I've seen how much more there is to it.. I guess I want my own toolbars?! Posting here seemed like an ok place to start 🥇

**Comment by eirannejad** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/1387

**Comment by DuncanLithgow** [comment]
Is there an easy way to control which standard tools are available? Maybe a little file that is read at runtime that IT can push into the Revit path? That would make it easy to make local deployments without having to compile a custom installer with some tools hidden.

For example a default path IT can use and a custom path (in the settings) advanced users can point to so they can get past company wide IT settings.

I'm happy to set this idea up as a separate RFE if you'd like.
