### ISSUE TITLE
Load Error: Config file access

### ISSUE THREAD

**Issue by ajhonors** [eirannejad/pyRevit#1451]
**Describe the bug**
pyRevit failed to load when opening revit

**To Reproduce**
1. Download & install the latest version of pyrevit.
2. Open Revit

**Expected behavior**
Dialogue box to "always load pyrevit" never appeared,

**Screenshots**

![Capture](https://user-images.githubusercontent.com/69609027/149420447-cf5d08ea-4b28-4a7d-a65b-5c17923e37a5.PNG)
![Capture 2](https://user-images.githubusercontent.com/69609027/149420463-1ce61280-fa38-468a-8554-38bf385c1459.PNG)

**Comment by eirannejad** [comment]
Would you mind sharing the result of `pyrevit env` command? Thanks

**Comment by ajhonors** [comment]
C:\Users\User>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.9.21361+0320" | Path: "C:\Users\User\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2022 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Users\User\AppData\Roaming\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\User\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2022 First Customer Ship | Version: 22.0.2.392 | Build: 20210224_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19044]
Executing User: USER-PC\AlexHonors
Active User: USER-PC\AlexHonors
Admin Access: Yes
%APPDATA%: "C:\Users\User\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.9.21361+0320

**Comment by ajhonors** [comment]
> Would you mind sharing the result of `pyrevit env` command? Thanks

Any Word on a fix?

**Comment by eirannejad** [comment]
Note to dev:
See this comment as well (https://github.com/eirannejad/pyRevit/issues/1163#issuecomment-1025321825)

**Comment by eirannejad** [comment]
Working on getting this resolved. This has been a very annoying issue for so many.

**Comment by ajhonors** [comment]
Thanks I got it figured out by looking at some older posts

**Comment by eirannejad** [comment]
:package: New public release are available for [4.8.10.22040](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.10.22040)

**Comment by toddbeyer** [comment]
Experiencing this issue with 4.8.10.22040 in Revit 2023

**Comment by mppukas** [comment]
4.8.10.22040 will not load in Revit 2023, but will load in Revit 2022. 

I've tried to read and follow the previous posts related to this issue, but I cannot follow the suggested fixes - it's too cryptic for level of knowledge. 

I've uninstalled all previous versions, and reinstalled the latest version only, same result. I'm at a total loss as to what to do.

**Comment by SIYUGUO** [comment]
Experiencing this issue with 4.8.10.22040 in Revit 2023
Env:
Autodesk Revit 2023 | Version: 23.0.1.318 | Build: 20220304_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19044]
Executing User: SIYU\SIYU
Active User: SIYU\SIYU
Admin Access: No
%APPDATA%: "C:\Users\SIYU\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.7.2 v4.8 v4.X
Installed .Net-Core Target Packs: v2.1.801 v6.0.302
pyRevit CLI v4.8.10.22040+1743
