### ISSUE TITLE
Failed seeding config file

### ISSUE THREAD

**Issue by jcaarch** [eirannejad/pyRevit#1455]
Pyrevit will not load--'Error loading pyrevit'
Every singe time, no exceptions, single user.
Please help.

Here is the message;
![image](https://user-images.githubusercontent.com/97545754/149682817-d7726e1d-0f32-4e9b-a80f-4015f3c6c0bd.png)
![image](https://user-images.githubusercontent.com/97545754/149682821-b60ff9ab-d8aa-48d3-bf55-4c2c6ddbeced.png)

![image](https://user-images.githubusercontent.com/97545754/149682727-fc5831e2-27ee-4ceb-92d8-382843259c80.png)

**Comment by tarasyukv** [comment]
Got similar problem since v4.8.
![Capture](https://user-images.githubusercontent.com/90550904/149907777-a29107af-9195-42e5-9a32-b5c3b8cc9263.PNG)
7

**Comment by christopheralt** [comment]
me too.  i posted as a new issue before seeing this...

**Comment by FB-JHowe** [comment]
Having the same issue here, very frustrating here as we've been asked to do a more widescale deployment of this software.

**Comment by christopheralt** [comment]
FB-JHowe

this issue has been SOLVED.  see my issue #1461 with instructions

**Comment by eirannejad** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/1451
