### ISSUE TITLE
Manage Keynotes now creating backup files?

### ISSUE THREAD

**Issue by kpfanny** [eirannejad/pyRevit#1457]
**Describe the bug**
The Manage Keynotes tool has started creating a large number of backup and "merged" files whenever you Convert or make changes to the keynotes file with the Manage Keynotes tool. I don't believe that the previous version of pyRevit had this issue?

**To Reproduce**
1. Create a .txt file for keynotes.
2. Open & Convert text file with Manage Keynotes tool.
3. Watch all the backup files being created in the file browser.
4. (2) additional backup/merge files are created each time you make a change in the keynotes file through Manage Keynotes.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/78550039/149970479-8d0c8dbb-a39f-4952-908b-a49fbb2ad44d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 V21H2 Build 19044.1466
 - pyRevit Version 4.8.9.21361+0320

**Comment by alexdaversa** [comment]
Build 0320 seems to be a develop build (tagged that way on the actions page at least) and so will generate these additional text files. See also #1382 and #1440. Build 2208+0042 (called pyRevitCI under actions) doesn't generate these extra files.

**Comment by eirannejad** [comment]
Already fixed and will be pushed with next release. https://github.com/eirannejad/pyRevit/issues/1440
