### ISSUE TITLE
"Infinite" lines in pattern maker, vector offsets, dots and line patterns

### ISSUE THREAD

**Issue by apsis0215** [eirannejad/pyRevit#1458]
![image](https://user-images.githubusercontent.com/2146809/150034323-828c3126-09f5-4833-8c39-69762d781a84.png)

**Comment by eirannejad** [comment]
What is this? Please provide more info as what you are asking for

**Comment by apsis0215** [comment]
Hatch patter editor upgrades.

**Comment by eirannejad** [comment]
What kind of upgrades? Please list and explain what is exactly needed to change
