### ISSUE TITLE
Tool to Quickly Set Phase Created/Demolished of Selected Elements

### ISSUE THREAD

**Issue by kpfanny** [eirannejad/pyRevit#1460]
**Is your feature request related to a problem? Please describe.**
When demolishing existing elements, it is always a huge pain having to continuously scroll down in the properties window to the "Phasing" section to select the "Phase Demolished" parameter. 

**Describe the solution you'd like**
I propose a button that would bring up a popup of phase options which could then be hotkeyed for quick element phase setting. The popup could look something like this:
![image](https://user-images.githubusercontent.com/78550039/150541620-a7293060-7eb3-41a5-85ac-cbdd96a6e591.png)
These lists of Phases would automatically populate based on the Phases currently in your project, which you could then quickly set the "Phase Created" and "Phase Demolished" parameters for the selected elements.

**Comment by cvoight** [comment]
We are currently managing a model with 10 phases, 389 sheets, and approx. 69,565 model elements, and we have had no problems with the built-in tools for managing model element phasing. I don't see how this would improve existing workflows.

Phase Created & Phase Demolished are one of the few Built In Parameters common to all model elements, so you can select as many elements at once as you like and set the phasing. The more categories you select, the shorter the list of options in the Properties bar.

If the same model element category is being selected, the properties bar maintains its scroll position, which lets you set phase easily one-by-one, but this is extremely inefficient compared to mass selection.

If you need to set phasing one-by-one, the Modify > Geometry ribbon panel has a Demolish command that can be hotkeyed.

**Comment by monsieurhannes** [comment]
I agree that it would be useful, especially in case of multiple categories, like in this case:
![image](https://user-images.githubusercontent.com/20651440/202478764-ed93e7e1-bdfc-41d4-bb5a-20a94e74cdab.png)
I can not set the phasing for all elements at once, without going into each category.

One problem could be that changing different categories can lead to having an element without a host? E.g. a "demolished" wall and a window in "new".
But if that can get solved it would be great to have it across different categories, imho.

**Comment by cvoight** [comment]
> I agree that it would be useful, especially in case of multiple categories, like in this case: ![image](https://user-images.githubusercontent.com/20651440/202478764-ed93e7e1-bdfc-41d4-bb5a-20a94e74cdab.png) I can not set the phasing for all elements at once, without going into each category.

You can set the phasing for multiple categories at once; I have done so for elements across tens of MEP categories. If the option isn't present, it's because you've selected an item or category that cannot be phased. If you filter it out or deselect, you will be able to change the phasing.
