### ISSUE TITLE
Error Loading pyRevit - PyRevitLoader

### ISSUE THREAD

**Issue by christopheralt** [eirannejad/pyRevit#1461]
I have tried to install pyRevit but keep getting an error when launching Revit.  Report indicates an error accessing the INI file because it is in use.

I tried this command and verified that it is attached correctly.
`pyrevit attach master 277 --installed`

1. Install pyRevit
2. Lunch Revit
3. See error "Failed seeding config file | Process cannot access the file ... pyrevit_config.ini because it is being used by another process.

I expected Revit to load without errors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.8.8 and also tried 4.8.9.21361+0320
 - pyRevit Environment:

`==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.8" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
master | Product: "2020.2.1 (New Install)" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2019.2.2 Hotfix" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\XXX\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2020.2.1 (New Install) | Version: 20.2.12.1 | Build: 20200210_1400(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19041]
Executing User: AzureAD\XXX
Active User: AzureAD\XXX
Admin Access: Yes
%APPDATA%: "C:\Users\XXX\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.8.0`

**Additional context**
I have tried uninstalling, reinstalling, closing all other apps, re-installing, etc.  Always get same error.
![pyrevit INI error](https://user-images.githubusercontent.com/98269324/150683259-0e5a8180-1dfd-45a3-bb2b-fd2869fa8b51.JPG)

**Comment by christopheralt** [comment]
SOLVED

after reading previous posts here is what worked for me:

**>> find and rename the original INI files for both pyRevit and Revit.  launch revit. <<**

worked for me!

**Comment by Texmati** [comment]
After the install yesterday I was getting the INI file error and couldn't load.  I noticed that the pyRevit_config.ini file did not exist in the AppData\Roaming\pyRevit\ folder where the install page notes indicate that it should be. 
[ https://www.notion.so/Install-pyRevit-98ca4359920a42c3af5c12a7c99a196d ]

I copied the INI file from the C:\ProgramData\pyRevit  folder (where the box dialogue indicated it was throwing the error) to the folder noted above, and the ribbon loaded with no errors noted.  It also loaded without anything resembling the box that indicates the load status/time, though, so I'm not sure if everything is working as it should be,

**Comment by jmcouffin** [comment]
related https://discourse.pyrevitlabs.io/t/installation-issues/757/7

**Comment by ayue-kjw** [comment]
Still having this issue with Revit 2022.1 with the latest 4.8.9 build. I have tried deleting the .ini files in both locations to no success.

**Comment by eirannejad** [comment]
Same as https://github.com/eirannejad/pyRevit/issues/1451
