### ISSUE TITLE
pyRevit 4.8.9 incompatibility with Enscape 3.2

### ISSUE THREAD

**Issue by RuiCosta75** [eirannejad/pyRevit#1463]
Hi,

I have found an incompatibility between pyRevit 4.8.9 and Enscape 3.2.
When they are both installed, Revit takes 3-6 minutes to load (any version).
Revit loads fast with pyRevit 4.8.9 + Enscape 3.1

Thanks for your help.
Rui

 - OS: Windows 10 Pro
 - pyRevit Version 4.8.9
 - pyRevit Environment: 

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.9.21361+0320" | Path: "C:\Users\rui.costa\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2022 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Users\rui.costa\AppData\Roaming\pyRevit-Master" | AllUsers
master | Product: "2021.1.2" | Engine: IPY277 (277) | Path: "C:\Users\rui.costa\AppData\Roaming\pyRevit-Master" | AllUsers
master | Product: "2020.2.3" | Engine: IPY277 (277) | Path: "C:\Users\rui.costa\AppData\Roaming\pyRevit-Master" | AllUsers
master | Product: "2019.2.2 Hotfix" | Engine: IPY277 (277) | Path: "C:\Users\rui.costa\AppData\Roaming\pyRevit-Master" | AllUsers
master | Product: "2018.3.3 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\rui.costa\AppData\Roaming\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\rui.costa\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2022 First Customer Ship | Version: 22.0.2.392 | Build: 20210224_1515(x64) | Language: 1033 | Path: "D:\Program Files\Autodesk\Revit 2022\"
2021.1.2 | Version: 21.1.20.44 | Build: 20201109_1530(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.3 | Version: 20.2.30.42 | Build: 20200826_1250(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
==> Running Revit Instances
PID: 10740 | 2022 First Customer Ship | Version: 22.0.2.392 | Build: 20210224_1515(x64) | Language: 0 | Path: ""
==> User Environment
Microsoft Windows 10 [Version 10.0.19044]
Executing User: AS\Rui.Costa
Active User: AS\Rui.Costa
Admin Access: Yes
%APPDATA%: "C:\Users\rui.costa\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.9.21361+0320
```

[journal.0001.txt](https://github.com/eirannejad/pyRevit/files/7941205/journal.0001.txt)

**Comment by Dimension4** [comment]
Hey Enscape dev here,

a colleague and I were working on this bug today. Enscape subscribes to the `AppDomain.FirstChanceException` event which then logs almost all exceptions that occur in Revit. We do that to identify 3rd party issues like this one more quickly. Usually this doesn't cause any slow down, but in the case of pyRevit we receive ~15k exceptions that are all logged to disk. This causes the slow down that you observe. Although, I'm surprised that Enscape 3.1 didn't show the same behavior (I don't think we changed anything there between these two versions).

Anyhow, we're now discarding the pyRevit exceptions, which should solve your problem. The fix will be available in the next preview release of Enscape. 

@pyRevit in case you guys want to investigate further, [here is a log file](https://github.com/eirannejad/pyRevit/files/7951762/EnscapeRevitPlugin_2022-01-27_15-33-32_29960.zip) from us containing all the exceptions that we get when starting Revit with Enscape with pyRevit installed. None of these exceptions occur if pyRevit is not installed, so we're pretty sure they're all coming from you. If you have any further questions don't hesitate to ask, we're here to help :)

**Comment by eirannejad** [comment]
I had no idea `AppDomain.FirstChanceException` exists. Super cool. I'll investigate and will try to fix the exceptions. Thank you @Dimension4 for sharing the info 🙏
