### ISSUE TITLE
Silent Deployment of 4.8.8 Fails - CMD script

### ISSUE THREAD

**Issue by TJ-BCS** [eirannejad/pyRevit#1468]
**Describe the bug**
Silent-script installation of pyRevit seems to hang with invisible screen. It never officially completes. Manual installation of the software on the same workstation completes with no error/issues. 12 different workstations have encountered this exact issue.

**Comment by eirannejad** [comment]
So we shifted the installers to a completely different installer builder. [See this latest 4.8.10 release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.10.22040%2B1743) and let me know if you still see install issues
