### ISSUE TITLE
Keynote files in BIM360

### ISSUE THREAD

**Issue by PAYAM2000** [eirannejad/pyRevit#1469]
Hi there, just noticed a long list keynote files created in our BIM360 any idea what these are? started to happen with the latest pyRevit. 

![image](https://user-images.githubusercontent.com/98921052/152244050-af442841-6635-45e0-b613-609b782b49e0.png)

**Comment by eirannejad** [comment]
Already fixed on https://github.com/eirannejad/pyRevit/issues/1457. New release will be posted in a few days

**Comment by GJacob717** [comment]
@eirannejad this is still happening to me also. I have Version: 4.8.10.22040 Please help!
