### ISSUE TITLE
Selecting Revit Elements from highlighted Element Ids of pyRevit Message.

### ISSUE THREAD

**Issue by hdm-dt-fb** [eirannejad/pyRevit#148]
Common use case: 
A pyRevit script finds a problematic/interesting element and displays it's id in the pyRevit output window. 
I think it could be a great interactive enhancement, if the user would then be able to click on that id and trigger something like "select element by id" or show it in view.

**Comment by eirannejad** [comment]
Implemented. Work-in-Progress
See these commands:
`Inspect> Lines per View Counter`
`Links > List DWG`
