### ISSUE TITLE
Exporting with the Make Pattern tool will work with some patterns but not others

### ISSUE THREAD

**Issue by geistwolke** [eirannejad/pyRevit#1480]
I have some patterns that were lost over the years and I am trying to get back out of Revit.  any I am trying to get them back into Revit to make sure they work.  

SRP will work as a Drafting , But 3-Hour will not work.  Whenever I try to pull 3-Hour it will say there is not a DRAFTING pattern.  It will read:   ""No "Drafting" type patterns found.""

WORKS

;        Written by "Make Pattern" tool for pyRevit
;          http://eirannejad.github.io/pyRevit/
;-Date                                   : 2022-02-08
;-Time                                   : 16:04:29
;-pyRevit Version                        : 4.8.8
;---------------------------------------------------------------------
;%UNITS=INCH
*SRP,exported by pyRevit
;%TYPE=DRAFTING
89.9999999999999000, 0.0, 0.0, 1.0168350000000000, 0.2187500000000000, 1.0168362500000000, -0.0
89.9999999999999000, 0.0009765750000000, 0.0, 1.0168350000000000, 0.2187500000000000, 1.0168362500000000, -0.0
89.9999999999999000, 0.0019531250000004, 0.0, 1.0168350000000000, 0.2187500000000000, 1.0168362500000000, -0.0
89.9999999999999000, 0.0029297000000004, 0.0, 1.0168350000000000, 0.2187500000000000, 1.0168362500000000, -0.0
89.9999999999999000, 0.0039062499999996, 0.0, 1.0168350000000000, 0.2187500000000000, 1.0168362500000000, -0.0
89.9999999999999000, 0.0048828249999996, 0.0, 1.0168350000000000, 0.2187500000000000, 1.0168362500000000, -0.0

WILL NOT WORK

;        Written by "Make Pattern" tool for pyRevit
;          http://eirannejad.github.io/pyRevit/
;-Date                                   : 2022-02-09
;-Time                                   : 12:10:36
;-pyRevit Version                        : 4.8.8
;---------------------------------------------------------------------
;%UNITS=INCH
*3-HOUR RATED PARTITION,exported by pyRevit
;%TYPE=DRAFTING
89.9999999999999000, 0.0, 0.0, 0.0, 0.7000000000000000, 
89.9999999999999000, 0.0024999999999996, 0.0, 0.0, 0.7000000000000000, 
89.9999999999999000, 0.0050000000000004, 0.0, 0.0, 0.7000000000000000, 
89.9999999999999000, 0.0075000000000000, 0.0, 0.0, 0.7000000000000000, 
89.9999999999999000, 0.0099999999999996, 0.0, 0.0, 0.7000000000000000, 
89.9999999999999000, 0.0125000000000004, 0.0, 0.0, 0.7000000000000000,
<img width="182" alt="srp" src="https://user-images.githubusercontent.com/38895355/153268983-ff3c76e8-4f28-4b08-9904-0e5a68416c3e.png">
<img width="265" alt="3hour" src="https://user-images.githubusercontent.com/38895355/153268984-e76240a0-368d-4a7c-8675-a7136c0f8fdb.png">

**Comment by eirannejad** [comment]
Seems like the pattern file has extra commas at the end of the lines. Try this:

```
; Written by "Make Pattern" tool for pyRevit
; http://eirannejad.github.io/pyRevit/
;-Date : 2022-02-09
;-Time : 12:10:36
;-pyRevit Version : 4.8.8
;---------------------------------------------------------------------
;%UNITS=INCH
*3-HOUR RATED PARTITION,exported by pyRevit
;%TYPE=DRAFTING
89.9999999999999000, 0.0, 0.0, 0.0, 0.7000000000000000
89.9999999999999000, 0.0024999999999996, 0.0, 0.0, 0.7000000000000000
89.9999999999999000, 0.0050000000000004, 0.0, 0.0, 0.7000000000000000
89.9999999999999000, 0.0075000000000000, 0.0, 0.0, 0.7000000000000000
89.9999999999999000, 0.0099999999999996, 0.0, 0.0, 0.7000000000000000
89.9999999999999000, 0.0125000000000004, 0.0, 0.0, 0.7000000000000000
```

**Comment by eirannejad** [comment]
Example of a pattern that does not work. A pattern imported into Revit as:

```
; Written by "Make Pattern" tool for pyRevit
; http://eirannejad.github.io/pyRevit/
;-Date : 2022-02-09
;-Time : 12:10:36
;-pyRevit Version : 4.8.8
;---------------------------------------------------------------------
;%UNITS=INCH
*3-HOUR RATED PARTITION,exported by pyRevit
;%TYPE=DRAFTING
89.9999999999999000, 0.0, 0.0, 0.0, 0.7000000000000000
89.9999999999999000, 0.0024999999999996, 0.0, 0.0, 0.7000000000000000
89.9999999999999000, 0.0050000000000004, 0.0, 0.0, 0.7000000000000000
89.9999999999999000, 0.0075000000000000, 0.0, 0.0, 0.7000000000000000
89.9999999999999000, 0.0099999999999996, 0.0, 0.0, 0.7000000000000000
89.9999999999999000, 0.0125000000000004, 0.0, 0.0, 0.7000000000000000
```

will be exported from pyRevit as below with extra commas:

```
; Written by "Make Pattern" tool for pyRevit
; http://eirannejad.github.io/pyRevit/
;-Date : 2022-02-09
;-Time : 12:10:36
;-pyRevit Version : 4.8.8
;---------------------------------------------------------------------
;%UNITS=INCH
*3-HOUR RATED PARTITION,exported by pyRevit
;%TYPE=DRAFTING
89.9999999999999000, 0.0, 0.0, 0.0, 0.7000000000000000, 
89.9999999999999000, 0.0024999999999996, 0.0, 0.0, 0.7000000000000000, 
89.9999999999999000, 0.0050000000000004, 0.0, 0.0, 0.7000000000000000, 
89.9999999999999000, 0.0075000000000000, 0.0, 0.0, 0.7000000000000000, 
89.9999999999999000, 0.0099999999999996, 0.0, 0.0, 0.7000000000000000, 
89.9999999999999000, 0.0125000000000004, 0.0, 0.0, 0.7000000000000000, 
```
