### ISSUE TITLE
Load Error: IronPython Method Not Found

### ISSUE THREAD

**Issue by Sokieee** [eirannejad/pyRevit#1482]
Hello,

I tried to install pyRevit but seems to get error. Tried opening it with both Revit 2019 and 2021 but get the same error. The installer did run just fine without any problem, tried some of the cmd fixed but none of them worked. 

To Reproduce
1. Go to 'Revit 2021.1.6'
2. The popup error message shows up. 
3. Closed it. 
4. Cant see pyRevit in the tab.

Expected behavior
Open Revit and pyRevit shows up in the tab. 

Screenshots
![image](https://user-images.githubusercontent.com/99360589/153276275-211235c3-bb8a-46af-995f-31169b707d39.png)

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.9.21361+0320" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
master | Product: "2022 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master"
master | Product: "Autodesk Revit 2021" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master"
master | Product: "2020.2.6" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master"
master | Product: "2019.2.3" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\OSDJ\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2022 First Customer Ship | Version: 22.0.2.392 | Build: 20210224_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
Autodesk Revit 2021 | Version: 21.1.60.25 | Build: 20220123_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.6 | Version: 20.2.60.15 | Build: 20211019_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.3 | Version: 19.2.30.41 | Build: 20210416_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

**Comment by eirannejad** [comment]
Close all Revits, run `pyrevit caches clear --all` on command prompt and start Revit again.

**Comment by Sokieee** [comment]
> 

Thanks for the quick reply! 
Just ran the command and opened Revit 2021, still get the same error:
![image](https://user-images.githubusercontent.com/99360589/153277576-30236291-447d-47ab-a1c8-8f687fe650b3.png)

**Comment by eirannejad** [comment]
Do you have IronPython installed on your machine separately? If yes, uninstall that please

**Comment by Sokieee** [comment]
> Do you have IronPython installed on your machine separately? If yes, uninstall that please

Yes I had IronPython installed on my machine not separately though, tried an uninstall but still get the same error.

**Comment by eirannejad** [comment]
Try this on command line
`pyrevit attach master default --installed`

this should attached pyRevit with its builtin custom IronPython 2.7.11

**Comment by Sokieee** [comment]
> 

That actually fixed it! Thank you so much!!

**Comment by eirannejad** [comment]
Okay so it is most probably an IronPython conflict with the one installed on your machine's Global Assembly Cache. You are using pyRevit's custom IronPython 2.7.11 which is actually better.
