### ISSUE TITLE
Version 4.8.10 silent install issues

### ISSUE THREAD

**Issue by vincentmarkt** [eirannejad/pyRevit#1487]
**Describe the bug**
I'm attempting to deploy it silently to over 1000 devices via Microsoft Configuration Manager (MECM), however, the plugin doesn't prompt to load when opening Revit. It installs just fine, but doesn't load in Revit unless the it's installed under a user account that has admin access, which to have is against our firm's policy. I also ran the command line mentioned below in Powershell after the installation, still no go. 

Not sure if I'm doing something wrong or if there's anything else to try?

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - pyRevit Version [e.g. 22]
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

**Additional context**

**Comment by hfergus** [comment]
In our environment (also MECM), we use the PowerShell App Deploy Toolkit to install the pyRevit CLI as the SYSTEM user, but explicitly clone into the logged in user's roaming profile. That effectively means that the end user doesn't need admin access.

So using the pyRevit CLI...
pyrevit.exe clone main base --dest="C:\users\$($RunAsActiveUser.UserName)\appdata\Roaming\pyRevit"
pyrevit.exe attach main 277 --installed --allusers

One issue we have just discovered though is that the recent change to the pyRevit CLI handling of config file locations means that the CLI is currently writing a critical config file into C:\Windows\System32\config\systemprofile\AppData\Roaming\pyRevit (eg. the path %PROGRAMDATA% resolves to for the SYSTEM user), which in turn can't be read by ordinary users. So we'll be logging a bug for that... it should resolve to %ALLUSERSPROFILE%
