### ISSUE TITLE
Sheet Number Already Exists - error in modified code

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#149]
I tried to modify your Sheet Shifting code to handle two non numeric leading characters and eventually wanted to include a modification for a potential trailing character.  That's all good, but how did you get around the "Number is already in use" error in Revit? 

[Shift Sheets.txt](https://github.com/eirannejad/pyRevit/files/733198/Shift.Sheets.txt)

In addition, my modification: looks like the sheet number has been updated on the project browser, but is leaving the sheet number... odd.  (might be related)

![image](https://cloud.githubusercontent.com/assets/14113080/22344794/848787ca-e3cb-11e6-8603-56a4672f5646.png)

**Comment by eirannejad** [comment]
I'm really not error checking in my script. So you should get an error if you're shifting down let's say `A102` and there already is a `A101`; you'll get an error.

As far as the sheet update goes, I have seen that happening before with Title block information and Especially schedules on a sheet not reflecting the actual schedule. Usually this gets fixed by closing and reopening the view to push Revit to re-render the view.

**Comment by thazell** [comment]
But somehow, if you grab 100 and 101 your code can shift them both up so you get 102 and 101.  It appears that's not working in my case. Any thoughts on what's different?
 and thanks for your feedback.

**Comment by eirannejad** [comment]
Oh It shifts them up in order! So it first shifts 101 to 102 and then 100 to 101

**Comment by thazell** [comment]
However it's all happening in one transaction , right?  Isn't this the same?

[Shift Sheets.txt](https://github.com/eirannejad/pyRevit/files/733374/Shift.Sheets.txt)

**Comment by eirannejad** [comment]
Okay. I'll look into this now. Tell me exactly what it needs to achieve?

**Comment by thazell** [comment]
Your code as is does great if the sheets are. I was trying to make it work for sheets with the following conventions:
S100
S-100
S0100
SD-100
SD100
S100A
S101B
SD202B

**Comment by eirannejad** [comment]
@thazell 
I updated the increment/decrement tools to accept any sheet number type. It works on all the sheet numbers you provided here. See latest commits

https://github.com/eirannejad/pyRevit/commit/848cf501c901fc03073fa7003111de73019409ff

**Comment by thazell** [comment]
@eirannejad Thanks!  It works well for a variety of sheet numbers.  The sorting doesn't seem to always work. Note it tried the 001 before 002, but it sorted the rest of them.  (see image below)
![image](https://cloud.githubusercontent.com/assets/14113080/22521710/eba191a2-e886-11e6-99a2-c0be7111c2b2.png)

**Comment by eirannejad** [comment]
Fair. The sorting is super simple right now. Let me look into the sorting function

**Comment by eirannejad** [comment]
Fixed sorting by sheet number. Update and let me know

**Comment by thazell** [comment]
That seems to have worked!
