### ISSUE TITLE
pyRevit wont let Revit start or Run

### ISSUE THREAD

**Issue by JorgeFlorero76** [eirannejad/pyRevit#1491]
**Describe the bug**
Replace these lines with your description. Be as specific as possible and list steps to reproduce the issue. If you have any suggestions for the solution please list that as well.

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - pyRevit Version [e.g. 22]
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

**Additional context**

**Comment by JorgeFlorero76** [comment]
I am using Revit 2021.1.6 and had pyRevit_4.8.8 installed and working fine, however when I try opening Revit today, it will start loading and suddenly goes away and the program doesn't start.  After some google search found this topic "Revit Crashes to Desktop on Startup" they suggested going into this folder %APPDATA%\Autodesk\Revit\Addins\ and renaming the old folders like this old_2021.  I notice that this folder contained the pyRevit.addin but after renaming the folder and running Revit it worked fine but it doesnt load pyRevit.  I try reinstalling pyRevit and the problem comes back and when I remove the pyRevit.addin Revit work fine again.  Any help you can provide.

**Comment by jasontran8** [comment]
I have the same issue and same temporary solution of removing pyRevit.addin allowed Revit to open.  An uninstall and then fresh re-install of pyRevit with latest installer did not help.

**Comment by FalconStarFighter** [comment]
Office of 100.  Versions of Revit include 2019,2020,2021,2022.  All users with PyRevit 4.8.8 installed have been unable to open Revit.  I'm wondering if this has to do with a recent Autodesk Licensing update from 6 days ago.  Most users have not yet run that update, so we have a mix of licensing being updated/not updated.  The consistent solution however is to uninstall PyRevit.

**Comment by jasontran8** [comment]
@FalconStarFighter I looked at my Windows update history and it's showing my last update was 1/3/22 so doesn't appear to be the reason for me.  I thought I read somewhere that there was an Autodesk Licensing update that came out a couple weeks ago that may affect this, but I didn't do that update.  And lastly, I'm on Revit 2020.2.4 build, which I don't think affects anything, but putting it out there.  Checking about updating to the latest to see if it helps.

**Comment by jasontran8** [comment]
@FalconStarFighter ha! I just realized it was from your post that I read about the licensing thing!  Well same situation as you currently and no additional information.

**Comment by TigranDesigner** [comment]
Have the same issue. Installed pyRevit_4.8.10.22040 and Revit would not start. Open the loading screen and close.  I uninstall the  pyRevit and Revit works again .. install it, Revit doe not work ... did this back and forth a few times.  

- OS: Windows 10 Pro. 
- pyRevit Version: pyRevit_4.8.10.22040
- pyRevit Environment: Attched 
![PY Rev](https://user-images.githubusercontent.com/96996921/157123575-4aec682d-bb90-48c6-b77a-6af21d404ec5.PNG)

**Comment by Momberg68** [comment]
I had the same issue on Revit 2020, by disabling another plugin 'hsbCAD', pyRevit worked again.
The problem as far I can tell is that both plugins use Microsoft.CodeAnalysis.CSharp.dll and Microsoft.CodeAnalysis.dll. (version 1.1.0.51202)
When I enabled the hsbCAD plugin again, I got the same errors, disabling solved it again.

Hope this helps in finding what's going on.

**Comment by jasontran8** [comment]
@FalconStarFighter Any movement on your end?  I tried looking into the Microsoft.CodeAnalysis.dll thing that @Momberg68 alluded to, but I don't have enough knowledge to do anything with that insight.

**Comment by TigranDesigner** [comment]
Did it manually . Just typed the numbers :/

**Comment by FalconStarFighter** [comment]
@jasontran8, nothing yet concrete.  I have found that it seems to be a conflict with another plug in.  In our case it was TSS Revit Briefcase (formally PPI Revit Briefcase)  with the Content Admin Kit.  I don't know enough about the coding side of things to understand what conflicts the two plug-ins have or understand why it started to become an issue when it did.  My guess is maybe it was a combination of a few things.  All I know is having PyRevit and TSS Revit Briefcase both loaded prevented Revit from opening and removing PyRevit resolves this for all users who experience it.  @eirannejad if you have any further assistance, I know our team is itching to get PyRevit back on their machines.  I'm at a loss for how to manage that between the add-in conflicts.

**Comment by FalconStarFighter** [comment]
@jasontran8, Finally got it resolved with our IT.  It took a lot of digging, but it was our antivirus interfering with one of the Microsoft protocols.  I'll try to gather more information as it is relayed to me.

**Comment by jasontran8** [comment]
@FalconStarFighter Great timing.  I had recently found another post: https://github.com/eirannejad/pyRevit/issues/1444 with the same conclusion regarding antivirus software.  I've passed that onto our IT team since we are using the same service as that other post.  I will report back as well.

**Comment by jasontran8** [comment]
Final report:  It was the antivirus and providing an exclusion/whitelist for PyRevit was the solution.
