### ISSUE TITLE
Extra Text Files Generated by Keynote Manager

### ISSUE THREAD

**Issue by GJacob717** [eirannejad/pyRevit#1493]
Extra text files have been generated when using the pyrevit. Please tell me how to fix this. I have the latest version as of 03/07/2022 (Version: 4.8.10.22040) if there is a later version that doesn't create extra txt files please let me know.

![Capture](https://user-images.githubusercontent.com/101154122/157143422-bd855108-32a6-4c58-8797-76b89170d321.JPG)

**Comment by cvoight** [comment]
This was fixed for me by 4.8.10.22040. Try a fresh install if you still have the issue.

**Comment by GJacob717** [comment]
> 



> Same issue here, we're checking the version of pyrevit of all the team members

Un-installing all previous versions first and then installing new version after seems to be working so far. I will update if it changes.

**Comment by eirannejad** [comment]
Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists
