### ISSUE TITLE
CPython Traceback: AttributeError : module 'clr' has no attribute 'AddReferenceToFileAndPath'

### ISSUE THREAD

**Issue by jgunstone** [eirannejad/pyRevit#1500]
**Describe the bug**
I just updated my pyRevit version in Revit 2022 and tried to run a test python3 script but am getting the error below.

**To Reproduce**
1. Uninstalled old pyRevit version and deleted folder in %ProgramData
2. Ran the admin installer .exe from pyrevit releases
3. Tried to run the following script: 
```py
#! python3

from pyrevit import revit

```

![image](https://user-images.githubusercontent.com/21370980/160438943-a65aa2be-49aa-4380-a26b-5e0acdbd3a87.png)

**Expected behavior**
The script to import successfully

**Desktop (please complete the following information):**
 ```cmd
C:\Users\j.gunstone>ver

Microsoft Windows [Version 10.0.19044.1586]
```
 - pyRevit Version [e.g. 22]
```
C:\Users\j.gunstone>pyrevit --version
pyrevit v4.8.10.22040+1743
Missing authorization token. Set on GITHUBTOKEN env var
```
 - pyRevit Environment: 
```
C:\Users\j.gunstone>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
Unknown | Product: "2022.1.2" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2022\pyRevit.addin"
Unknown | Product: "2021.1.6" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2021\pyRevit.addin"
Unknown | Product: "2020.2.7" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2020\pyRevit.addin"
Unknown | Product: "2019.2.3" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2019\pyRevit.addin"
==> Installed Extensions
MFTools | Type: Unknown | Repo: "" | Installed: "C:\engDev\git_mf\pyRevit\MFTools.extension"
==> Default Extension Search Path
C:\Users\j.gunstone\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\engDev\git_mf\pyRevit
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2022.1.2 | Version: 22.1.21.13 | Build: 20220123_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021.1.6 | Version: 21.1.60.25 | Build: 20220123_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.7 | Version: 20.2.70.6 | Build: 20220112_1230(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.3 | Version: 19.2.30.41 | Build: 20210416_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
PID: 18472 | 2021.1.6 | Version: 21.1.60.25 | Build: 20220123_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2021"
==> User Environment
Microsoft Windows 10 [Version 10.0.19044]
Executing User: MAXFORDHAM\j.gunstone
Active User: MAXFORDHAM\j.gunstone
Admin Access: No
%APPDATA%: "C:\Users\j.gunstone\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.10.22040+1743
```

Thanks in advance!

**Comment by jgunstone** [comment]
to follow up on this - 
i used tried with the unit test examples in the pyRevitDev extension and had the same issue: 

![image](https://user-images.githubusercontent.com/21370980/160653802-443ae912-964a-445e-9ea9-34852f019d0f.png)

**Comment by JBloss1517** [comment]
I had to work around the `pyrevit` module entirely because the pythonnet library's `clr` module does not implement the `AddReferenceToFileAndPath` only `AddReference`. 
What I will traditionally do is look at what functionality I need from the pyrevit module (in your case the `pyrevit.revit` module) and see what is actually doing. In your sample case, it's just an easy way to import the `Autodesk.Revit` module.
So instead of using `from pyrevit import revit` you would use `from Autodesk import Revit` directly.

Now just in case you or others with a similar issue run into an issue trying to add a reference to a C# library, you do the following:

```python
import sys
import clr

sys.path.append("path\to\folder\containing\dll files needing to add") 
clr.AddReference("Something")
import Something
```
or to make it concrete, I use this quite a bit when needing to work with native dotnet lists:
```python
import clr
clr.AddReference("System")
from System.Collections.Generic import List
```
you'll note that I didn't add the sys.path part because pyrevit adds that path for us already when you simply use the `#! python3` tag at the top (in my case the path `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\` was added to the list of paths the clr module will search through.

**Comment by jgunstone** [comment]
hi there, 

Thanks for this - yes, this is what I ended up doing also (effectively bypassing the pyrevit module and using the functionality directly from the RevitAPI). 

To make numpy work i needed to do the following: 

```py
import pathlib
import sys
import os

# Load pyrevit3
sys.path.append(r"C:\Miniconda3\envs\pyrevit3\Lib\site-packages")  # Will have to change link to pyrevit3 environment
os.add_dll_directory(r"C:\Miniconda3\envs\pyrevit3\Library\bin")
```

perhaps the `os.add_dll_directory` bit is doing to same as adding the `dll`s to path. 

thanks for the explanation of the clr library - i hadn't realised that is how it worked!
