### ISSUE TITLE
pyRevit addin not appearing in all versions of Revit

### ISSUE THREAD

**Issue by amagioia** [eirannejad/pyRevit#1501]
I am trying to install pyRevit_4.8.10.22040_admin_signed, but it only appears in Revit 2019. Please see the error in other versions of Revit attached. I previously installed pyRevit_**CLI**_4.8.10.22040_admin_signed so there might be a conflict with previous installs. I tried detaching and deleting the clones but no luck. Any other suggestions would be appreciated. Thanks!

![pyrevit](https://user-images.githubusercontent.com/68915563/160673925-ebc7ff48-738d-40a3-9a6d-9279747c3404.jpg)

**Comment by jmcouffin** [comment]
@amagioia what does the `pyrevit env `command shows in the command line?

**Comment by amagioia** [comment]
Hi @jmcouffin please see the screenshot below. Thank you!
![image](https://user-images.githubusercontent.com/68915563/161781422-e5aa647d-373f-4259-96e6-80fa0029bd43.png)

**Comment by jmcouffin** [comment]
nothing very out of the ordinary here
you could try using a different engine with the command
`pyrevit attach master 2710 --allusers --installed`
and restart revit in the version you want see pyrevit in

**Comment by amagioia** [comment]
Thanks @jmcouffin
That didn't work. I also tried the steps listed here: https://www.notion.so/pyRevit-Is-Installed-But-Does-Not-Load-f6495adb56254e9e8021f8a68e3b2ab7 and I got the results in the 1st screenshot below. 

I noticed that my 2020 and 2021 folders were empty in %APPDATA%/pyRevit, so I copied all the files from the 2019 folder to the 2020 and 2021 folders and renamed the files to their corresponding version of Revit. (See 2nd screenshot below).

I'm not sure if this solution would help others, but it solved the issue for me!

Thanks again!

![image](https://user-images.githubusercontent.com/68915563/161823885-80971369-1924-4904-960d-c00b58d43e15.png)

![image](https://user-images.githubusercontent.com/68915563/161824395-542b2aaa-a651-46b4-94d8-b5cdce80d7d8.png)

**Comment by amagioia** [comment]
I just realized I should have used this file path instead when running pyrevit clones add master <installed path>: C:\Program Files\pyRevit-Master

**Comment by jmcouffin** [comment]
> Thanks @jmcouffin That didn't work. I also tried the steps listed here: https://www.notion.so/pyRevit-Is-Installed-But-Does-Not-Load-f6495adb56254e9e8021f8a68e3b2ab7 and I got the results in the 1st screenshot below.
> 
> I noticed that my 2020 and 2021 folders were empty in %APPDATA%/pyRevit, so I copied all the files from the 2019 folder to the 2020 and 2021 folders and renamed the files to their corresponding version of Revit. (See 2nd screenshot below).
> 
> I'm not sure if this solution would help others, but it solved the issue for me!
> 
> Thanks again!
> 
> ![image](https://user-images.githubusercontent.com/68915563/161823885-80971369-1924-4904-960d-c00b58d43e15.png)
> 
> ![image](https://user-images.githubusercontent.com/68915563/161824395-542b2aaa-a651-46b4-94d8-b5cdce80d7d8.png)

That should not be necessary, I don't thing there is a lot of Revit version specific files in the pyrevit regular install process.
