### ISSUE TITLE
'No module named pyevent'

### ISSUE THREAD

**Issue by Rhino1093** [eirannejad/pyRevit#1502]
I'm working on running some code inside of the python shell but I keep getting this error message and can't seem to solve it. Whenever I run the code I have (and I'm new at this so explain it to me like I'm 5), I get the error message, "Exception : IronPython.Runtime.Exceptions.ImportException: No module named pyevent". The whole error message is below.

From my google searching I found that I'm supposed to install padas inside of my python environment but I have no idea how to do this (like I said, I'm new and learning).

![image](https://user-images.githubusercontent.com/98354417/160699311-12412961-50b0-4dbf-9c13-fb8091ad0a6b.png)

**Desktop:**
 - Windows 10
 - pyRevit Version 4.8.9
 - pyRevit Environment: '''C:\Users\rjohnston>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.9.21361+0320" | Path: "C:\Users\rjohnston\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2021.1.5" | Engine: IPY277 (277) | Path: "C:\Users\rjohnston\AppData\Roaming\pyRevit-Master"
master | Product: "2018.3.3 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\rjohnston\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
Jools | Type: Unknown | Repo: "" | Installed: "C:\Users\rjohnston\Desktop\WIP\pyRevit\Jools\Jools.extension"
==> Default Extension Search Path
C:\Users\rjohnston\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\Users\rjohnston\Desktop\WIP\pyRevit\Jools
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021.1.5 | Version: 21.1.50.27 | Build: 20211018_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
==> Running Revit Instances
PID: 15052 | 2021.1.5 | Version: 21.1.50.27 | Build: 20211018_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2021"
==> User Environment
Microsoft Windows 10 [Version 10.0.19044]
Executing User:  @ERDMAN\RJohnston
Active User: ERDMAN\RJohnston
Admin Access: No
%APPDATA%: "C:\Users\rjohnston\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.9.21361+0320'''

**Comment by eirannejad** [comment]
Add the path of `site-packages` directory (inside pyRevit's installed folder) to your RPS

**Comment by onomou** [comment]
In case anyone else comes across this like I did, this will do what @eirannejad said:

```python
import sys
sys.path.append(r'C:\Users\<username>\AppData\Roaming\pyRevit-Master\pyrevitlib')
sys.path.append(r'C:\Users\<username>\source\repos\pyRevit\site-packages')
from pyrevit import forms
```
Just replace `<username>` and paste into RevitPythonShell, provided pyRevit is installed in the default location.
