### ISSUE TITLE
ERROR [pyrevit.extensions.extensionmgr] Parameter does not exist.

### ISSUE THREAD

**Issue by jfhrndz** [eirannejad/pyRevit#1505]
Revit2020 windows are already updated, add-ins fix updates are already installed. please help.
![pyRevit](https://user-images.githubusercontent.com/102817998/161298000-07c334c3-0e3b-4a24-a5c7-b5afc9f7d657.png)

**Comment by jmcouffin** [comment]
@jfhrndz you could try move your pyrevitconfig.ini file to another folder, and fire up revit again. Or see what this file has to say next to the 'pyRevitTags'

**Comment by jfhrndz** [comment]
Sorry for the late response @jmcouffin got caught in some Revit Issues with the latest MS update 2 weeks. The error is gone upon firing the revit2021, I saw the pyrevit on the tab but am not sure if the extension work, will have to wait for the user's response on this. Thank you so much will let you know if the error persists.
