### ISSUE TITLE
Color tabs are not working

### ISSUE THREAD

**Issue by Belyash1k** [eirannejad/pyRevit#1511]
Hi.
I have Revit 2022.1.2 and PyRevit v4.8.10.22040+1743. I want set color tabs - i go to Settings -> UI/UX -> Colorize Open Documents, choose background fill, then select Save Settings and Reload. PyRevit accept my wishes, tabs become colorize, but in 2 seconds Revit become loading and color is disappear. 

I have recorded [`screencast`](https://drive.google.com/file/d/1TKzClqROlQR4RuxObALB3o-JYdLlleCl/view?usp=sharing) for full understanding.

Pls help, this addon is very useful for me.

**Comment by Belyash1k** [comment]
P.S. if i select _Just save settings_ - tabs will be not colorize in next openong of Revit.

**Comment by dsellam** [comment]
We had the same issue with two users those two last days. 
We recreated the pyrevitconfig.ini file in installation folder and it solved the problem. Don't know if it can helps...

**Comment by Belyash1k** [comment]
> We had the same issue with two users those two last days. We recreated the pyrevitconfig.ini file in installation folder and it solved the problem. Don't know if it can helps...

Cannot find this .ini. Where is it way?
Installation folder is .....\Program Files\pyRevit-Master\?

**Comment by Belyash1k** [comment]
> We had the same issue with two users those two last days. We recreated the pyrevitconfig.ini file in installation folder and it solved the problem. Don't know if it can helps...

OMG it helps.

I have deleted pyRevit_config.ini %PROGRAMDATA%, rebooted Revit, tuned Settings, selected "Just save and reload" and color tabs are saved....

Thank you very much.

**Comment by ManFon-245** [comment]
I don't have the .ini file can someone help me ? I reinstalled and delete all the files multiple times but it's not there...
