### ISSUE TITLE
Revit 2023 Installer

### ISSUE THREAD

**Issue by scottofazphx** [eirannejad/pyRevit#1513]
ETA on Revit 2023 Installer?

**Comment by infeeeee** [comment]
You can already download a wip auto build from Actions. 4.8.11.22103 is the first version with 2023 support. 

Go to this link: https://github.com/eirannejad/pyRevit/actions/runs/2158206100 On the bottom of the page on the `Artifacts` section click on `pyrevit-installers`. Unzip, install.

![kép](https://user-images.githubusercontent.com/1271737/164785789-91d0e3e9-0849-452d-9052-a8dccd32b1c9.png)

This install method is documented here: https://www.notion.so/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725

**Comment by jburger316** [comment]
Any updates on this. The link in the above post has been removed.

**Comment by sechanbask** [comment]
Hello,

I can't download it too.

**Comment by sharkmullet** [comment]
would be great to get notified by email when it's available

**Comment by infeeeee** [comment]
I don't know why you can't download it, the link still works for me. Nevermind, I uploaded to mega, it's the downloaded zip without modifications, I just renamed the file: 

https://mega.nz/file/ShwVzb7L#1-mDO52lfkmCVrdj_CqgY4o5DgbaCgZAfAO-c2l_788

When a release will be available, I will delete this

**Comment by rabiadhikari** [comment]
Getting this error message in 2023.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/9669247/174862415-faee972f-19dd-47a6-a55a-e432853f310a.png">

**Comment by Yukicchi626** [comment]
Hi I have the same error with Revit2023.0.1. But it works fine with other versions.

**Comment by infeeeee** [comment]
> Getting this error message in 2023.
> 

This is expected, as it's removed from the 2023 revit api:

> [ObsoleteAttribute("This enumeration is deprecated in Revit 2022 and may be removed in a future version of Revit. Please use the `ForgeTypeId` class instead. Use properties of the `SpecTypeId` class and its nested classes to replace uses of specific values of this enumeration.")]
public enum ParameterType

https://www.revitapidocs.com/2022/f38d847e-207f-b59a-3bd6-ebea80d5be63.htm

I can't find a quick fix for this, and it affects the following commands:

- Analysis/Sum
- Drawing Set/Schedules/Create Schedule from CSV
- Project/Family/Export Family Config, Import Family Config
- Project/Wipe/Wipe All Project Parameters

Other removed apis can cause other problems, this is just about this api change.

**Comment by eirannejad** [comment]
Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists

**Comment by the-grim** [comment]
Revit 2023 crashes on startup (no error message) after installing pyRevit_4.8.12.22247_signed.exe

**Comment by yonkers92** [comment]
> Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists
Works perfectly. Thanks Ehsan.

**Comment by scottofazphx** [comment]
excellent, thank you very much
