### ISSUE TITLE
Undersore issue in User Name

### ISSUE THREAD

**Issue by dosymep** [eirannejad/pyRevit#1515]
My user name: biseuv_o, but shows biseuvo.

![Unfixed](https://user-images.githubusercontent.com/5417225/163581981-15c888c4-e17d-4f9f-9be3-6c94fbcfc181.png)

**Comment by eirannejad** [comment]
That seems to be the name that Windows API returns. I'll check

**Comment by dosymep** [comment]
@eirannejad, yep this name returns by Windows API.
Underscore is special symbol for [label](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.label?view=windowsdesktop-6.0) control in WPF. Underscore is used to set [access keys](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/how-to-create-a-control-that-has-an-access-key-and-text-wrapping?view=netframeworkdesktop-4.8). I have fixed it in PR https://github.com/eirannejad/pyRevit/pull/1516.
