### ISSUE TITLE
Upgradind from 4.6.6 to 4.8.10

### ISSUE THREAD

**Issue by bobbieqc** [eirannejad/pyRevit#1518]
After upgradind to latest, i get ths screen, see below

![pyrevit](https://user-images.githubusercontent.com/37275193/164713277-ee05bba5-218d-4153-ac9f-86ca8e0ff232.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version [e.g. 22]
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

C:\Users\adagenais>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.10.22040+1743" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
master | Product: "2020.2.2 (Full Install)" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2019.2.2 Hotfix" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2018.3.2" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2017.2.4" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\adagenais\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2020.2.2 (Full Install) | Version: 20.2.11.3 | Build: 20200206_0915(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2018.3.2 | Version: 18.3.2.7 | Build: 20181011_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
2017.2.4 | Version: 17.0.1158.0 | Build: 20181011_1645(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
==> Running Revit Instances
PID: 33436 | 2020.2.2 (Full Install) | Version: 20.2.11.3 | Build: 20200206_0915(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2020"
==> User Environment
Microsoft Windows 10 [Version 10.0.19044]
Executing User: AEDIFICA-MTL\adagenais
Active User: AEDIFICA-MTL\adagenais
Admin Access: No
%APPDATA%: "C:\Users\adagenais\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.10.22040+1743

Et voilà!

**Comment by alexdaversa** [comment]
It looks like perhaps the newest version was installed as admin/for all users, but the previous install was specifically for your user.

Make sure the `.addin` files are not present in that user's `Appdata\Roaming\Autodesk\Revit\Addins\` folders for each year of Revit the user runs, and make sure they are present in `C:\ProgramData\Autodesk\Revit\Addins\` again for each year of Revit.

**Comment by jmcouffin** [comment]
@bobbieqc 
try the steps of Alex and try the latest install the latest release/
Please close the issue if not relevant anymore
