### ISSUE TITLE
Revit 2023 Support

### ISSUE THREAD

**Issue by jburger316** [eirannejad/pyRevit#1521]
Is there support for Revit 2023 yet?

Great Add In - Keep up the great work.

**Comment by llancel** [comment]
I'm also looking for a 2023 install.  I followed the instructions on a previous post stating there is a WIP version, but it didn't seem to work.

**Comment by sechanbask** [comment]
I can't download installer too.
Nobody know how to make installer ?

**Comment by llancel** [comment]
That worked!  Thank you!

**Comment by sechanbask** [comment]
Hello, thank you form your answer. 

Perhaps, I can't download installer : 

![2022-05-09_08h53_40](https://user-images.githubusercontent.com/4959672/167356168-bf9d5c3e-3312-46bc-8303-179eed32a3d3.png)

**Comment by roygidali** [comment]
please need help too.... doesn't work on Revit 2023. can't download the installer

**Comment by roygidali** [comment]
worked for me too, just had to log in here :) thank you!

**Comment by Simo-Billy** [comment]
it works on revit 2023, but doesn't load on revit 2021 (where was Pyrevit 4.8.10)

**Comment by davian59** [comment]
Thank you very much it worked !

**Comment by JCY292** [comment]
Hello everyone. I installed it but it doesn't work in revit 2022 or 2023, I have windows 11. Any suggestions?. Thanks in advance.

**Comment by jmcouffin** [comment]
@JCY292 please review if there is another issue on that specific subject: windows 11 support and either create a new issue or comment on the existing one + add a copy of the result of the command `pyrevit env`

**Comment by eirannejad** [comment]
Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists
