### ISSUE TITLE
Pyrevit 4.8.11 doesn't load on revit 2021

### ISSUE THREAD

**Issue by Simo-Billy** [eirannejad/pyRevit#1529]
I've on my laptop revit 2021 and revit 2023 also, and loaded pyrevit 4.8.10.22040 (it worked perfectly on revit 2021) and pyrevit 4.8.11.22103 (that works only on revit 2023). 

Now, after loading 4.8.11.22103 pyrevit works only on revit 2023 but doesn't work (and doesn't load plugin too) on Revit 2021. 

How can I improve this on my revit 2021?

**Comment by jmcouffin** [comment]
first get the result of 'pyrevit env' command in the command line and report here. It will tell us more

**Comment by CharkBIM** [comment]
pyRevit is not loading in any version. Uninstall/reinstall does nothing. Have 4.8.10.22040 installed for <22 and 4.8.11.22103 for 23+.

can't get it to launch, so no idea how to run any CLI commands. Should I install the CLI version to do this?

**Comment by eirannejad** [comment]
Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists
