### ISSUE TITLE
Error placing accent Safari

### ISSUE THREAD

**Issue by samuelbrehm** [eirannejad/pyRevit#1531]
**Describe the bug**

When I use notion on safari it doesn't correctly accentuate the words. The letter is accented but creates an extra apostrophe.
My language is PT-BR.

`pyrevit attach master 277 --installed`

**To Reproduce**
1. Open any page on Safari
2. With language PT-BR digite "própria maçã"
3. See error before letter "o" the first word and letter "ç" the second word. 

**Expected behavior**
I hope so to be equal "própria maçã"

**Screenshots**
<img width="979" alt="Screen Shot 2022-05-14 at 10 35 31" src="https://user-images.githubusercontent.com/6319555/168428114-b86101b5-8f62-45c1-a5ef-5cfcde8e6e9e.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.3.1
 - Safari 15.4

**Comment by eirannejad** [comment]
This is an issue related to Notion.io not pyRevit :D Closing
