### ISSUE TITLE
pyRevit_4.8.10.22040_signed.exe doesn't load in Revit 2023

### ISSUE THREAD

**Issue by johanvanmol** [eirannejad/pyRevit#1536]
I downloaded and installed pyRevit.  It works in Revit 2022 and earlier.

In Revit 2023, it displays a PyRevitLoader error:
[pyRevit_2023_3bad931806aaec62_PyRevitLabs.PyRevit.Runtime.log](https://github.com/eirannejad/pyRevit/files/8772414/pyRevit_2023_3bad931806aaec62_PyRevitLabs.PyRevit.Runtime.log)
[pyRevit_2023_11268_runtime.log](https://github.com/eirannejad/pyRevit/files/8772415/pyRevit_2023_11268_runtime.log)

These are the other extensions that are loaded:
- Enscape
- BIM Interoperability Tools
- DiRootsOne

Revit version = 23.0.1.318

**Comment by mitchoatman** [comment]
No official release for 2023 yet.  It has been discussed in other threads.  You can download a WIP copy that will work in 2023.

"You can find the installers in this repository, by clicking "Actions". You will see a list of runs, and you can select any one of these that has occurred in the past ~10 weeks. In each, you will see at the bottom a section called "Artifacts" which contains the link to the installers."

You have to sign into github to download.

**Comment by FrancoTonutti** [comment]
You can see #1510, there they explain how to solve the problem, at least it worked for me.

**Comment by johanvanmol** [comment]
Thank you for clarifying this 👍

**Comment by jmcouffin** [comment]
also this https://github.com/eirannejad/pyRevit/issues/1539
Please close the issue if solved @johanvanmol

**Comment by johanvanmol** [comment]
Ok, this issue can be closed.
