### ISSUE TITLE
Bug when you copy a toggle heading to a new page

### ISSUE THREAD

**Issue by erickholu** [eirannejad/pyRevit#1538]
**Describe the bug**
Specifically when you copy the Toggle Heading element using the text selection through the cursor (and not using the mouse), all the content is copied to the clipboard and when paste it into a new page the entire element is pasted as simple text. So all elements nested within the parent element (Toggle Heading) remain hidden until you change the header to toggle format.

Happend in online version of Notion.

**To Reproduce**
1. Create a page with a Toggle heading
2. Nested to it, create a bullet list and put some values on it
3. User the text cursor to select the element and all text nested to it
4. User CTRL+C command
5. Create a new page and click in the blank section
6. When text cursor start to blink, use CTRL+V command
7. The element is pasted as Heading and all nested content is gone
8. Change de element from Heading to Toggle Heading
9. All nested content appears again!

**Expected behavior**
The element should be pasted in the same way as selecting by mouse, if it's a Toggle when copied still a Toggle when pasted.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Notion online 2.16.23.10.25.20

**Additional context**

**Comment by jmcouffin** [comment]
@erickholu You are reporting an issue about Notion on the pyRevit Github repository...
You can submit your issue somewhere here https://www.notion.so/help
Please close this issue
