### ISSUE TITLE
Error loading pyrevit for the first time on revit 2023

### ISSUE THREAD

**Issue by yonatanst** [eirannejad/pyRevit#1539]
**Describe the bug**
Replace these lines with your description. Be as specific as possible and list steps to reproduce the issue. If you have any suggestions for the solution please list that as well.

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - pyRevit Version [e.g. 22]
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

**Additional context**

**Comment by yonatanst** [comment]
![צמ](https://user-images.githubusercontent.com/105928820/171872308-e20cfd60-b760-4670-9b19-d54525bbebe3.png)

**Comment by jmcouffin** [comment]
Your version of pyRevit is not meant for 2023
Check this post on the pyRevit forum. That should fix it
https://discourse.pyrevitlabs.io/t/error-message-loading-pyrevit-in-2023/948

**Comment by jmcouffin** [comment]
If it is fixed, please close the issue @yonatanst

**Comment by yonatanst** [comment]
thanks it is fixed
