### ISSUE TITLE
Don't show again checkbox

### ISSUE THREAD

**Issue by clntnco** [eirannejad/pyRevit#1540]
**Is your feature request related to a problem? Please describe.**
It would be awesome to have a "Don't show again" check box on the reload dialog box that comes up every time you reload pyRevit . Ex. I'm slightly annoyed when I am creating or modifying a script and having to continue clicking yes I want to reload Pyreivt.

**Describe the solution you'd like**
Add a don't show check box or some other type of switch (maybe in the settings).

Thanks for your time.

**Comment by jmcouffin** [comment]
Alternatively you could make your own reload button like so, without the original message

```
# -*- coding=utf-8 -*-

from pyrevit import EXEC_PARAMS
from pyrevit import script
from pyrevit.loader import sessionmgr
from pyrevit.loader import sessioninfo

logger = script.get_logger()
results = script.get_results()

# re-load pyrevit session.
logger.info('Reloading....')
sessionmgr.reload_pyrevit()

results.newsession = sessioninfo.get_session_uuid()

```
