### ISSUE TITLE
docs: userconfig Examples use a non existent "get" method

### ISSUE THREAD

**Issue by sanzoghenzo** [eirannejad/pyRevit#1542]
**Describe the bug**
`userconfig.py`  docstrings have Examples - [like this line](https://github.com/eirannejad/pyRevit/blob/4b84aa1bf6608d9a5f6c023d4446006a7a5dbcfd/pyrevitlib/pyrevit/userconfig.py#L31) - that use a `get` method, but this method does not exist neither in `PyRevitConfig` nor in `PyRevitConfigSectionParser`.

The proper method should be `get_option`.

**Comment by jmcouffin** [comment]
it might be deprecated.
I use the following on a regular basis
```
# Grab data from config
my_config = script.get_config()
tests = getattr(my_config, "tests")
```
from the configparser module
![image](https://user-images.githubusercontent.com/7872003/174473703-8cb60c8e-0fb2-4c76-9943-b2cc08fd1497.png)

https://github.com/eirannejad/pyRevit/blob/4b84aa1bf6608d9a5f6c023d4446006a7a5dbcfd/pyrevitlib/pyrevit/coreutils/configparser.py#L32

**Comment by sanzoghenzo** [comment]
This is what `get_option` does a few lines below, calling `__gettatr__` and optionally handling a default value.
I don't think it should be deprecated, just updated. 
I'll put up a PR when I'll have the time!

**Comment by jmcouffin** [comment]
> Forgive me if I didn't do what I promised, but this is still relevant and hasn't been fixed by anyone.
Fine
Then let's get to it ;p  @sanzoghenzo 

I have been batch closing every single old issue.
Having 250+ issues to deal with does not make sense for a very small number of contributors

**Comment by jmcouffin** [comment]
Thanks for the contribution @sanzoghenzo 
Closing
