### ISSUE TITLE
Pyrevitloader doesn't work with windows 11 22h2

### ISSUE THREAD

**Issue by geistwolke** [eirannejad/pyRevit#1543]
Pyrevitloader doesn't work with windows 11 22h2. I have tested uninstall/re-install. I used the latest one:  4.8.10.22040.  It will just spin at  the loading screen.

' 0:< API_ERROR { : Assembly version conflict in some references in System.Reflection.Metadata assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.2.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.5.0 } 
' 0:< ::43:: Delta VM: Avail -10 -> 134211030 MB, Used +2 -> 567 MB, Peak +1 -> 567 MB; RAM: Avail -42 -> 17730 MB, Used +3 -> 955 MB, Peak +3 -> 955 MB 
' 0:< GUI Resource Usage GDI: Avail 9808, Used 192, User: Used 196 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis.CSharp assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.5.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in pyRevitLabs.Common assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.5.0
'Addin's module OpenMcdf of version 2.2.1.5 conflicts with same preloaded module of version 1.5.2.35413 } 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis.VisualBasic assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.5.0 }

**Comment by eirannejad** [comment]
Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists

**Comment by geistwolke** [comment]
thank you, it works now
