### ISSUE TITLE
Using Pyrevit extensions for Dynamo script with slider input

### ISSUE THREAD

**Issue by yonatanst** [eirannejad/pyRevit#1544]
Hi, I created a Dynamo script with number slider as input.
when using it through Pyrevit extensions the input doesnt exist and the script runs with the default number.
Is there a way to input data for a script using Pyrevit extension like in Dynamo player?
thanks

**Comment by jmcouffin** [comment]
Hi, If you mean using the OOTB slider, it won't work. You would need to use your own UI slider (WPF for example) to do so. 
If using the Data-Shapes nodes, it should work, you might have to be careful to change the runtype to Automatic.

**Comment by jmcouffin** [comment]
a screen capture of the graph and the graph itself vould help

**Comment by eirannejad** [comment]
There are [standard methods to ask for values](https://www.notion.so/pyrevitlabs/Effective-Input-ea95e95282a24ba9b154ef88f4f8d056#97918586a15a4723acab5624a826bfd5) in `pyrevit.forms`. Maybe we can add number sliders as well
