### ISSUE TITLE
Idea: Add systemfor beta tools

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#155]
Something like this: 

Bundles could get a beta property, create by a flag in the bundle name:
`Name.panel.beta` or `Name.panel_beta` or similar.

Settings get a check box:
"Include beta tools"

Parser will include or ignore bundles based on user settings (no beta by default)

**Comment by eirannejad** [comment]
Can I suggest using a script parameter like `__beta_script__ = True` for this? I like this better since the folder structure remains unchanged and avoids any possible git update errors

**Comment by gtalarico** [comment]
even better :)
maybe just `__beta__` ?

**Comment by eirannejad** [comment]
`__beta__` implemented. Please test and let me know of your comments and thanks for great ideas :+1:

**Comment by gtalarico** [comment]
Damn Ehsan, are you full time on this now?  :)

**Comment by eirannejad** [comment]
Haha nah. Just between projects so have a little bit more time
