### ISSUE TITLE
PyRevit fails to load

### ISSUE THREAD

**Issue by DMage27** [eirannejad/pyRevit#1551]
On opening Revit the following error message appears and PyRevit plug in fails to load

![image](https://user-images.githubusercontent.com/108065164/175281105-ae7d2291-b309-400e-863d-dd783f3aa797.png)

**To Reproduce**
1. Open Revit

**Expected behavior**
Revit opens with PyRevit plug in menu tab

**Comment by wrartes21** [comment]
I have the same issue in revit 2023
![2022-06-23 09_41_27-Window](https://user-images.githubusercontent.com/48325071/175313747-2089a320-7129-45d2-a51f-53c27964e60b.png)

**Comment by rayala30** [comment]
I have the same exact errors as OP for Revit 2022.1. PyRevit was working fine when I was using it last week but then started to give an error recently. I also had no updates to my computer or software. I tried using the command prompts in other posts but it did not work. 

![Loading Error Message](https://user-images.githubusercontent.com/108031113/175327965-c7ade1ca-3409-4d21-ba9f-d36af0e72149.PNG)

**Comment by MentorGashi** [comment]
![Screenshot 2022-06-23 200402](https://user-images.githubusercontent.com/107956938/175365084-28ecfabb-a77a-423c-9579-f8bff9a5a580.jpg)
What should i do ?

**Comment by fenyag7** [comment]
Looks like the same issue. Note: I am using a trial version of Revit 2023.

![image](https://user-images.githubusercontent.com/67780432/175793149-d6b52582-ca27-40d8-bd17-43a3f2737963.png)

**Comment by jnicho2408** [comment]
I'm getting the same issue for Revit 2023. Hope there is a solution soon.

**Comment by DMage27** [comment]
@jnicho2408 , I hope so too, no idea what caused it, I'm hoping someone cleverer than me can figure it out and help

**Comment by bhavikkhatri** [comment]
I'm getting the same message using Revit 2023.

**Comment by rayala30** [comment]
> 

Where can I download version 4.8.11? The latest release shown is 4.8.10. Thank you

**Comment by dvdgnz** [comment]
You are right, I don't know why the Release hasn't been created automatically. @eirannejad might have to help here, I am not too familiar with github actions.
In the meantime, you can download the installers from the automated build for this commit under Artifacts here:
https://github.com/eirannejad/pyRevit/actions/runs/2412393932

**Comment by conormacken** [comment]
I'm getting the same/similar errors:
![image](https://user-images.githubusercontent.com/6058285/176893003-b228fd40-57bc-4a51-b6a7-68d49a4c548b.png)
There's more to the screenshot, but it won't fit on the one screen.
Fresh install of v4.8.12 and get the same one with Revit 2023, 2022, 2021, 2020, 2019 & 2018.

**Comment by jerlisep** [comment]
I am also getting this error as is one of my coworkers. I have installed 4.8.11 and this did not solve the issue.
![image](https://user-images.githubusercontent.com/109243106/178813355-7451ac08-cabe-4a9c-a4ad-2d120598db83.png)

**Comment by bhavikkhatri** [comment]
I have the same issue as @jerlisep after installing 4.8.11. I'm running Revit 2023

**Comment by eirannejad** [comment]
Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists

**Comment by DMage27** [comment]
I tried the command prompts from previous posts too,  I'd thought it was
Microsoft update related as we'd had updates before it failed
