### ISSUE TITLE
Pyrevit is not installing

### ISSUE THREAD

**Issue by AbiyTekola** [eirannejad/pyRevit#1553]
While I am trying to install pyravit, I keep getting the following error. 
"pyrevit.PyRevitException: Define Revit2023;REVIT2023_0_1"
Does anyone know what this is and any idea on how to fix this please?

**Comment by eirannejad** [comment]
Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists
