### ISSUE TITLE
Sheet reorder not working

### ISSUE THREAD

**Issue by sakhyr** [eirannejad/pyRevit#1555]
The tool Sheet Reorder is not showing any sheet on my project to reorder, and parameters is empty.
Is there any solution for that?

![empty reorder](https://user-images.githubusercontent.com/108416046/176466041-bc3de996-d30a-4d8d-9beb-39b1eb3da457.jpg)
![empty parameters](https://user-images.githubusercontent.com/108416046/176466068-f409625f-721e-4e93-ba95-b6cb5a39b26e.jpg)

**Comment by Marcelo-Romero** [comment]
I think this issue happens because, most of the time, these parameters are created with the String type. Maybe if we just change "Integer" for "String" in line 101, the tool will work.
