### ISSUE TITLE
PyRevitLoader - Error Loading pyRevit.  It states AttributeError:  'NoneType' object has no attribute 'GetType'

### ISSUE THREAD

**Issue by superysdj1** [eirannejad/pyRevit#1557]
Ehsan, thank you in advance for help!

pyRevit is not getting added to my Revit 2023 (free trial version), with the message stating;

AttributeError:  'NoneType' object has no attribute 'GetType'

I saw similar issue https://github.com/eirannejad/pyRevit/issues/1401 where that user solved his error by running "pyrevit attach core 2711 --installed --allusers" in his CLI. Pasting this in my CLI didn't solve my problem. 

Is there a quick fix by modifying the script in line 98 as shown below?

![image](https://user-images.githubusercontent.com/60275973/177026709-d878cab0-37c2-4d46-8cd6-8f9662f12a19.png)

![image](https://user-images.githubusercontent.com/60275973/177025114-6e71b6cd-3773-445d-93ed-bacb21c7ef8b.png)

![image](https://user-images.githubusercontent.com/60275973/177025055-371fa294-8806-4123-8171-0d554b11440e.png)
![image](https://user-images.githubusercontent.com/60275973/177025073-5aa6e9c4-6369-464a-9bd0-f9c83a36754c.png)

**Comment by dvdgnz** [comment]
You need to install the latest version 4.8.11, see post in this issue
https://github.com/eirannejad/pyRevit/issues/1551

**Comment by eirannejad** [comment]
Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists
