### ISSUE TITLE
Pyrevit can not be installed

### ISSUE THREAD

**Issue by Bor3y94** [eirannejad/pyRevit#1559]
Hey there,
Whenever I try to install pyrevit for Revit 2019 a lot of errors are showing up.
Here are some screenshots to the issue.
![003](https://user-images.githubusercontent.com/108802066/177717820-daf9525a-7fcc-4a63-bca0-0a7d093d1e59.png)
![004](https://user-images.githubusercontent.com/108802066/177717827-2ed100b0-da31-4fa6-8070-97bd52a49cf3.png)
![001](https://user-images.githubusercontent.com/108802066/177717834-a7f644f4-4ea5-4e05-b679-8c7a8d6a8932.png)
![002](https://user-images.githubusercontent.com/108802066/177717839-886bb47a-6c5e-4ce8-b981-d29a1716eab9.png)
All the previous files are skippable , I know it's not the solution but it was  attempt to find the problem.

This last file can not be skipped and I have to cancel the installation.
![005](https://user-images.githubusercontent.com/108802066/177718083-38b5d2cc-1f9d-49f2-bb76-ca21dd97d835.png)

I tried this on 2 version 4.8.10.22040 and 4.8.12.22174 for both admin and normal user installation packages.
Any solution for this issue???

**Comment by eirannejad** [comment]
First time i'm seeing this. Most probably your security software is blocking changes
