### ISSUE TITLE
Error when selecting Variable Paper Size with sheet placeholders, Revit crash when clicking - Set Print Setting

### ISSUE THREAD

**Issue by HighLouie** [eirannejad/pyRevit#1560]
First, thank you for all the insane work you do Ehsan!

**Bug Description**
If there are sheet placeholders in the project, selecting Variable Paper Size in Print Sheets results in error.
It doesn't matter if "Show Non-Printable Sheets (Grayed Out)" or "Include Non-Printable Sheets in Indexing" are selected or not.
After error window pops up, if clicked on "Set Print Settings", Revit will have unrecoverable error and will crash into Error Report window.

**To Reproduce**
1. Create new project and a sheet
2. Create a new placeholder sheet
3. Click 'Print Sheets' in pyRevit
4. Select <Variable Paper Size>
5. See error

**Expected behavior**
I think it's logical to exclude placeholder sheets from the index when selecting <Variable Paper Size>. Everything else is expected to continue normally.

**Desktop:**
 - OS: Windows 11 21H2 (OS Build 22000.778)
 - pyRevit Version v4.8.10.22040+1743
 - pyRevit Environment: 
```
C:\Users\david>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\david\AppData\Roaming\pyRevit-Master"
master | Product: "2020.2.1 (New Install)" | Engine: IPY277 (277) | Path: "C:\Users\david\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\david\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2020.2.1 (New Install) | Version: 20.2.12.1 | Build: 20200210_1400(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.22000]
Executing User: HOME-PC\david
Active User: Home-PC\david
Admin Access: No
%APPDATA%: "C:\Users\david\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.10.22040+1743
```

**Additional context**
I'm attaching an error log below. Please let me know if there's anything else you need
[Variable Paper Size error log.txt](https://github.com/eirannejad/pyRevit/files/9063822/Variable.Paper.Size.error.log.txt)

**Comment by HighLouie** [comment]
Sorry I'm new to github. I can't seem to flag this thread with appropriate assignees and labels.

**Comment by Laurens-RB** [comment]
I have the same issue.
Revit crases on selecting variable paper size sheets
