### ISSUE TITLE
PyRevit Error message 

### ISSUE THREAD

**Issue by Momo4ever** [eirannejad/pyRevit#1561]
I am trying to download the latest version of PyRevit on Revit 2023. 

I keep getting this error message below * 

Any suggestions or anyone else having a similar problem? 

<img width="1421" alt="PyRevit issue " src="https://user-images.githubusercontent.com/108887503/177815464-2e7f3e16-919d-4137-8968-84b22d4a9c7f.png">

**Comment by pzyskowski42** [comment]
Similar issue, used SnagIt to grab the whole window:
![image](https://user-images.githubusercontent.com/44787108/178041348-5a090b20-4827-4a5f-beb2-ca5f87675219.png)

**Comment by Momo4ever** [comment]
@pzyskowski42 After you captured everything, how did you resolve the issue? Did you paste it somewhere?

**Comment by pzyskowski42** [comment]
Oh, it's not resolved... I just thought it would be helpful to see the
entire error message.

-Pete Zyskowski

**Comment by dvdgnz** [comment]
What version of pyRevit have you installed?

**Comment by Momo4ever** [comment]
@dvdgnz The most recent one. v4.8.10.22040 Installer

**Comment by pzyskowski42** [comment]
@dvdgnz same here.  Most current. [pyRevit 4.8.10.22040 Installer]

**Comment by dvdgnz** [comment]
Try download the latest installers for 4.8.11 from here:
https://github.com/eirannejad/pyRevit/actions/runs/2412393932

They don't show up in the Release section yet

**Comment by Momo4ever** [comment]
@dvdgnz @pzyskowski42 That worked! Thank you so much for your help👍

**Comment by clooz8** [comment]
> Try download the latest installers for 4.8.11 from here: https://github.com/eirannejad/pyRevit/actions/runs/2412393932
> 
> They don't show up in the Release section yet

I'm still running into issues. I'm at least able to see it in 2022 and 2023 now, but not 2020 or 2021.

**Comment by CharkBIM** [comment]
same issue. at least I'm getting the pyRevitLoader error message again. Not working in any version.

![image](https://user-images.githubusercontent.com/106173242/180024746-36d256cc-9de1-45da-a24f-a918cbb109d5.png)

**Comment by jhtacoma** [comment]
Just a comment for any other newbies like me ... While this may seem obvious to everyone else on github, you have to be a registered user to download the "pyrevit-installers" link -- or even for it to _appear_ as a link in the first place.  I was lost for quite awhile until a friend pointed it out.  I'm here because I'm a Revit user, not a github user, so this requirement was not evident to me.  

Just wanted to mention this in case it helps someone. :)

**Comment by nicinus** [comment]
> Just a comment for any other newbies like me ... While this may seem obvious to everyone else on github, you have to be a registered user to download the "pyrevit-installers" link -- or even for it to _appear_ as a link in the first place. I was lost for quite awhile until a friend pointed it out. I'm here because I'm a Revit user, not a github user, so this requirement was not evident to me.

Even though logged in these links shows up as expired. There are references to 4.8.12 but I can't find it.

**Comment by eirannejad** [comment]
Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists
