### ISSUE TITLE
Can't Uninstall 4.8.8_signed

### ISSUE THREAD

**Issue by pzyskowski42** [eirannejad/pyRevit#1562]
![image](https://user-images.githubusercontent.com/44787108/178040452-59c8b8d7-1bb5-4f8c-95b9-d606f5abd0b9.png)

[MSID325.LOG](https://github.com/eirannejad/pyRevit/files/9074010/MSID325.LOG)

**Comment by jmcouffin** [comment]
try using something like iobit uninstaller to uninstall.
you could also delete if present: 
- C:\Program Files\pyRevit-Master
- C:\Program Files\pyRevit
- %appdata%\pyRevit\
- %appdata%\pyRevit-Master\

**Comment by pzyskowski42** [comment]
used Revo and got it all uninstalled.
