### ISSUE TITLE
PyRevitLoader - Error Loading pyRevit in Revit 2023 and 2020

### ISSUE THREAD

**Issue by samatrix** [eirannejad/pyRevit#1567]
Since installing Revit 2023 I get the same error on opening the app.

I'm not able to copy the error message text. It begins with;
IronPython Traceback:
Traceback (most recent call last):
File: "C:\Users\....pyRevit-Master\bin\engines\pyRevitLoader.py", line 30, in <module>
...pyrevitlib\pyrevit\loader\sessionmgr.py", line 24, in <module>

TypeError: expected StrongBox[List[str]], got List[str]

(I'm typing this from a screencapture and providing only snippets.

Then about 30 lines under Script Executor Trackback:

This error message now also shows up for Revit 2020 which prior to Revit 2023 install did not have any issues. (I have since updated pyRevit install numerous times and also checked pyrevit attached using command prompt. All looks correct there.

Thanks for any guidance. A team user is have same issue.

**Comment by XisSoul** [comment]
Hello.
pyRevit dont work Revit 2023. Version pyRevit 4.8.10.22040.

**Comment by dvdgnz** [comment]
Use 4.8.11. see this https://github.com/eirannejad/pyRevit/issues/1561#issuecomment-1181847323

**Comment by CharkBIM** [comment]
I'm having this same issue and have narrowed it down to using the Environment plugin for site/landscape modeling. All other attempts with command line attachments, masters, etc. did not fix the problem. I'm working with the Environment developer to find a solution. Hope this helps.

**Comment by samatrix** [comment]
Thanks @dvdgnz  4.8.11 solved the issue for me.

**Comment by eirannejad** [comment]
Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists
