### ISSUE TITLE
Manage Packages Extension Error 

### ISSUE THREAD

**Issue by revitkon** [eirannejad/pyRevit#1568]
**Describe the bug**
I am relatively new to pyrevit and don't know anything about python. I'd like to use the package manager for a project and I am receiving an error. I followed the youtube tutorial and installed the extension and created the parameters per the tutorial. 

**To Reproduce**
1. Enable Tags extension
2. Create DOCPKG1 parameter and assign to sheets 
3. Click on Manage Packages

**Expected behavior**
The package manager window to appear showing the issuances and revisions for the sheet I have selected. 

**Screenshots**
![image](https://user-images.githubusercontent.com/109180536/178595686-a1b342e5-68fe-4ac4-8aaf-5c6630cf815f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.8.8
 - pyRevit Environment: RAD for autodesk Revit

`pyrevit env`

**Comment by eirannejad** [comment]
Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists

**Comment by revitkon** [comment]
Hi Ehsan, I'm not sure how to re-open this, this problem was solved. But I've since run into the same issue again this morning. I uninstalled pyrevit and installed the latest package but I'm still receiving the same errors.

**Comment by jmcouffin** [comment]
@revitkon uninstalling then installing one of the WIP version should solve it 
The WIP releases can be found in the actions tab in github, more details here https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725

**Comment by jmcouffin** [comment]
the unittype issue is related to the revit version your are using, there has been a drastic change in the API in the past 3 version of Revit and I know that not all of them were taken into account yet in every tool

**Comment by revitkon** [comment]
Ah thank you so much! I will give that a try.

**Comment by revitkon** [comment]
That worked!! thanks a ton.
