### ISSUE TITLE
All Revit Versions Crash Upon pyRevit install

### ISSUE THREAD

**Issue by jayteajay** [eirannejad/pyRevit#1569]
**Describe the bug**
After installing pyRevit, all versions of Revit (2019, 2020, 2021 etc) crash upon launching. This is happening on multiple computers and it happened after we installed Autodesk Desktop Connector onto the machines.

As soon as we uninstall pyRevit, it stops crashing and works as normal. There's no error messages when it crashes, it just loads up to the splash screen, freezes for 60 seconds and closes without warning.

**To Reproduce**
1. Install Autodesk Desktop Connector and pyRevit
2. Open up any Revit version
3. Freezes then crashes 60 seconds later

**Desktop (please complete the following information):**
 - Windows 10 (various versions, some fully updated while others slightly behind)
 - latest pyRevit version
 - Revit 2019, 2020, 2021

**Additional context**
I've gone through some basic troubleshooting with the commands like pyrevit env, pyrevit attach master 277 --installed etc but none have helped. Ran pyrevit doctor and nothing changed. I'll attach the information that appears from pyrevit env, as well as some info from the Revit Journal files. The issue could solely be on Autodesk Desktop Connector's end, but I'd appreciate it if you could read through the attached text files or give some guidance if you've seen this issue before.

[pyRevitenv.txt](https://github.com/eirannejad/pyRevit/files/9100643/pyRevitenv.txt)
[JournalpyRevit.txt](https://github.com/eirannejad/pyRevit/files/9100650/JournalpyRevit.txt)

Thank you

**Comment by jmcouffin** [comment]
from the journal file, It looks like dll hell, with assemblies mismatch.

Not sure it will help, 
Rough guess here: it seems you installed with signed admin installer in your latest install but it is pointing to a non admin install version for extensions
You could give it a try:
- unsinstall pyRevit et pyRevit CLI
- flush all data if any in C:\Users\admin2\AppData\Roaming\pyRevit\ and C:\Users\admin2\AppData\Roaming\pyRevit-Master\
- flush all data if any in C:\Program Files\pyRevit-Master
- install latest pyrevit
- run pyrevit env and report

**Comment by ray75228** [comment]
We are having the same issue. Tried the folder clearing suggested, but didn't help.  Seems to have started a couple of weeks ago.

**Comment by jayteajay** [comment]
> We are having the same issue. Tried the folder clearing suggested, but didn't help. Seems to have started a couple of weeks ago.

Turns out it was SentinelOne blocking it. No alerts/notifications that suggested it, but we whitelisted pyrevit and it started working fine again for all the computers

**Comment by ray75228** [comment]
Thanks Jay, very interesting.  Apparently our IT folks installed that recently and I didn't know about it.  Would you be willing to share how to whitelist pyrevit in SentinalOne?

**Comment by jmcouffin** [comment]
Good one @jayteajay 

Please close the issue if solved.
