### ISSUE TITLE
Unable to load pyRevit.

### ISSUE THREAD

**Issue by kidasse** [eirannejad/pyRevit#157]
Hello,
i have download the pyRevit 4.1 source code (zip) file from the releases and unzip it in a directory
on my disk, then i install whith the install_addin.bat file but when i launch Revit i got an error. 
I use Revit 2016 french. here are the screen capture image of the error message from Revit:
![pyrevit loading error](https://cloud.githubusercontent.com/assets/19168660/22927274/ab91927c-f2b0-11e6-8699-c9162e0b34dc.jpg)
and the message of the pyRevit console:
![pyrevit console info](https://cloud.githubusercontent.com/assets/19168660/22927318/dc5f1df2-f2b0-11e6-9146-b6c90529102f.jpg)
Can you tell me what i'm doing wrong?
Sorry, for my bad English language.
Thanks.

**Comment by eirannejad** [comment]
Hi. Thanks for reporting this and sorry about the bug. Sometimes I get these error with different Revit versions and languages.
I just pushed a new update so please reinstall pyRevit and then please open the config file (shown on the report) at `%appdata%/pyRevit/pyRevit_fessadik_config.ini` and set `filelogging = True` 
Then run Revit again and this time pyRevit will generate a full log of everything that is happening in the background and saved that log under `%appdata%/pyRevit/2016/` and is a file with `log` extension. Please send that log to me in an email so I can look into the error.

**Comment by kidasse** [comment]
I send the file at "eirannejad@gmail.com".
Thanks for your quick reply.

**Comment by eirannejad** [comment]
Okay. I just pushed an update that resolves the error. However!, you have downloaded the pyRevit in a zip file. This means that the git repository is not available and pyRevit can not determine its version. Either use the provided installer or `clone` the pyRevit repository to the desired folder. The installed pyRevit needs to have the `.git` folder to be able to determine its version and update itself later.

**Comment by kidasse** [comment]
Everything works fine. thank you very much.
Concerning the git repository, there are restrictions on the firewall of my company which prevents me from cloning the pyRevit repository on my computer. It is necessary that I see with the computer service for an authorization. For now I can not have the automatic update and there is this version problem, but I can still use this very useful toolbox. And thank you again for the speed with which you solved the problem and of course for this great tool.
