### ISSUE TITLE
Possible conflict with Dynamo in Revit 2023

### ISSUE THREAD

**Issue by pzyskowski42** [eirannejad/pyRevit#1573]
**Describe the bug**
It looks like version 4.8.11 had some impact on Dynamo for Revit 2023.  I had issues with pyRevit running on 2023 and used the pyRevit_4.8.11.22151_signed.exe installer to fix that issue.  However, after running a script, Dynamo would throw an error.  Upon reopening, Dynamo would be unresponsive when adding nodes, or opening a script.  The 3d graph environment had been modified, and the nodes would also be unusable.  

Reference issue from Dynamo Github: https://github.com/DynamoDS/Dynamo/issues/13120

After uninstalling pyRevit, Dynamo seems back to normal.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - pyRevit 4.8.11.22151
 - pyRevit Environment: I had to uninstall.
 - Revit: 23.0.11.19  20220503_1030(x64)

**Comment by eirannejad** [comment]
Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists
