### ISSUE TITLE
Match option does not pick/work with dimension styles.

### ISSUE THREAD

**Issue by vasesa** [eirannejad/pyRevit#1575]
**Describe the bug**
The Match command does not respond to dimensions - even tho it show' pick dimensions to match overrides:'

**Expected behavior**
Was trying to use 'match' to override dimension styles on a view ( make the red ones take the same graphic properties as the red ones) - see screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/109662025/179956006-5543eeed-4fdd-4f6d-9848-292c22932d44.png)

**Desktop (please complete the following information):**
 - OS: Windows
 -  pyRevit v4.8.10.22040
 - pyRevit Environment: 

P:\>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.10.22040+1743" | Path: "C:\Users\vanessa.barsan\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2021.1.6" | Engine: IPY277 (277) | Path: "C:\Users\vanessa.barsan\AppData\Roaming\pyRevit-Master"
master | Product: "2020.2.7" | Engine: IPY277 (277) | Path: "C:\Users\vanessa.barsan\AppData\Roaming\pyRevit-Master"
master | Product: "2019 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Users\vanessa.barsan\AppData\Roaming\pyRevit-Master"
master | Product: "2018.3.3 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\vanessa.barsan\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\vanessa.barsan\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021.1.6 | Version: 21.1.60.25 | Build: 20220123_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.7 | Version: 20.2.70.6 | Build: 20220112_1230(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019 First Customer Ship | Version: 19.0.0.405 | Build: 20180216_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
==> Running Revit Instances
PID: 16256 | 2021.1.6 | Version: 21.1.60.25 | Build: 20220123_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2021"
==> User Environment
Microsoft Windows 10 [Version 10.0.19044]

Admin Access: No
%APPDATA%: "C:\Users\vanessa.barsan\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.10.22040+1743

**Comment by dvdgnz** [comment]
The match command for dimensions matches the dimension text overrides.
Does the built-in Revit command achieve what you're after?
