### ISSUE TITLE
I have intalled pyRevit 4.8.10.22040, when I have starting Revit it's not loading. It is giving error as shown in the below snap. Please advice

### ISSUE THREAD

**Issue by MukundMogal** [eirannejad/pyRevit#1579]
**Describe the bug**
Replace these lines with your description. Be as specific as possible and list steps to reproduce the issue. If you have any suggestions for the solution please list that as well.

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

**To Reproduce**
![2022-07-24 11_50_57-Window](https://user-images.githubusercontent.com/109891515/180647751-a74a92d0-f176-480c-ab98-d35461ea5264.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - pyRevit Version [e.g. 22]
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

**Additional context**
![2022-07-24 11_51_11-Window1](https://user-images.githubusercontent.com/109891515/180647773-bf425a9f-0558-40a3-a75e-17927596fd06.png)

**Comment by merca321** [comment]
Hi there I have exactly the same issue, I urgently need to get Pyrevit working with Revit 2023 if possible! 

![pyrevit](https://user-images.githubusercontent.com/110046580/181052855-3e77482b-4f96-4051-a79a-c3c1b65cb0e8.JPG)

**Comment by dvdgnz** [comment]
For Revit 2023 you need a more updated version. see: https://github.com/eirannejad/pyRevit/issues/1561#issuecomment-1181847323

**Comment by eirannejad** [comment]
Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists
