### ISSUE TITLE
Pushbutton > script.py

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#158]
Hi @eirannejad !
I have been porting some old scripts to new format, and just realize I have to rename all scripts to
`script.py` regardless of the folder.
Is there any reason we you wouldn't allow a script to be called anything else?
Inside a xxx.pushbutton, there should be only one `.py` and one `.png`.
Seems to be like the dir parser should be able to just grab the .py file in there and make the button.
Maybe a warning/error if finds more than one...

The main reason for pointing this out, is that when working on scripts, one often has multiple scripts open in an editor. It can get confusing/dangerous to when you have +3-4 files open all labeled `script.py`

(removed 2nd part of question, figured it out)

**Comment by eirannejad** [comment]
@gtalarico 
Script names can be anything as long as they end in `script.py` for example `createNewHatch_script.py`
Other python scripts can be placed inside this folder for example tools can have their own configuration script that is a separate python file. See `Match` tool as an example
