### ISSUE TITLE
Pyrevit not loading with Microdesk BIMrx add-on

### ISSUE THREAD

**Issue by BennyDaBlade** [eirannejad/pyRevit#1580]
With the latest release of Microdesk's BIMrx Core, Pyrevit will no longer load/ run at the same time. I have to uninstall one or the other.

![Screenshot 2022-07-25](https://user-images.githubusercontent.com/109047557/181079081-f3f62774-fc0f-49ba-aaff-a7ccd6fcf4e4.JPG)

**Comment by Phyrexien** [comment]
Possibly having the same issue after the latest BIMrx release.

**Comment by carrsteven** [comment]
I am also having this issue with BIMrx installed.

**Comment by DavidWKoch** [comment]
I finally had time to test disabling the Microdesk BIMrx addins in Revit 2022, and when I did, pyRevit ran as expected.  Time to tell Microdesk there is an issue.

**Comment by BennyDaBlade** [comment]
Here is what I got back from Microdesk. I have tested and in works.
![pyrevit fix](https://user-images.githubusercontent.com/109047557/186695527-74e105a3-bafd-49b1-9e01-bb0775a7c262.JPG)

**Comment by jmcouffin** [comment]
Jiminy Cricket told me :

> ControlzEx.dll BIMrX is using v5.0.1.15 and pyrevit bin includes 3.0.2.4.

**Comment by jmcouffin** [comment]
Updated the ControlZeX.dll to V6.0 for .NET Framework v4.0 with #2011
