### ISSUE TITLE
Unable to access Windows Robocopy 

### ISSUE THREAD

**Issue by Wilionaire** [eirannejad/pyRevit#1581]
This might be a pretty rookie issue but I have created a simple script to run a Robocopy from Revit. There are probably system/pyRevit limitations i am missing, but it runs fine from the Windows CMD. Code below, FYI, folders are just test folders to help find the issue. 

`import os
import os.path as op
from subprocess import call

# Variables 
package_source = os.path.expanduser(os.sep.join(["~","Documents\Source"]))
package_dest   = os.path.expanduser(os.sep.join(["~", "Documents\Destination"]))

# Check paths and copy
if os.path.exists((package_source) and (package_dest)):
	call (["robocopy",package_source,package_dest,"/MIR","/z","/LOG:mylogfile"])
else:
	print ("Expected File Paths Do Not Exist, Please contact the BIM Manager")`

**Desktop (please complete the following information):**
 - OS: Windows 
 - pyRevit Version : 4.8.1
 - pyRevit Environment:

'==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.10.22040+1743" | Path: "C:\Users\will\AppData\Roaming\pyRevit-Master"
OCULUSmain | Deploy: "base" | Branch: "master" | Version: "4.8.11.22151+0454" | Path: "C:\pyRevit\OCULUSmain"
==> Attachments
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\will\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2021" | Engine: IPY277 (277) | Path: "C:\Users\will\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2020" | Engine: IPY277 (277) | Path: "C:\Users\will\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2019" | Engine: IPY277 (277) | Path: "C:\Users\will\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
OCULUS | Type: Unknown | Repo: "" | Installed: "C:\Users\will\Oculus\Oculus - Studio and Tools\02 Design Toolbox\02 Revit Toolbox\05 Add-Ins\02. Plug-ins\OCULUS.extension"
==> Default Extension Search Path
C:\Users\will\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\Users\will\Oculus\Oculus - Studio and Tools\02 Design Toolbox\02 Revit Toolbox\05 Add-Ins\02. Plug-ins
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
Autodesk Revit 2021 | Version: 21.1.70.21 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
Autodesk Revit 2020 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
Autodesk Revit 2019 | Version: 19.2.60.3 | Build: 20220224_1700(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages'

**Comment by eirannejad** [comment]
What's the error?
