### ISSUE TITLE
pyRevit v4.8.10.22040 not loading in Revit 2023

### ISSUE THREAD

**Issue by Fozibehr** [eirannejad/pyRevit#1582]
pyRevit c4.8.10.22040 not loading in my Revit 2023 v23.0.10.18

See attachement:
![Image 001](https://user-images.githubusercontent.com/59780562/182624708-9a3af2dd-ba89-4e37-9aaf-f4fc5326a919.jpg)

**Comment by Fozibehr** [comment]
Also to add to the above. I thought I'd remove pyRevit and re-install, but it won't complete the uninstall. I've attached the log file for that.

[MSIADF7.LOG](https://github.com/eirannejad/pyRevit/files/9252478/MSIADF7.LOG)

**Comment by muijsa** [comment]
Same issue here.  When will this been resolved?

**Comment by RetroTechX** [comment]
Need to get a secure installation so I can launch it with 2023 in the fall.

**Comment by mitchoatman** [comment]
There is an unofficial installer that will work with 2023 here:
https://github.com/eirannejad/pyRevit/actions/runs/2329416952

Have to be signed into github to download.  

Install it on top of previous builds and all versions of Revit will have Pyrevit tools.

I hope support for Pyrevit continues and official builds are released, till then it has been working.
there are other builds that are slightly newer than that link but they produce errors.

**Comment by BranchArch** [comment]
The link appears to have expired -- could someone please re-post? Love me some PyRevit on 2023...!

**Comment by Fozibehr** [comment]
Link good for 7 days from date of this post. I have it working with Revit v23

https://www.transfernow.net/dl/20220819gbHcmfPA

**Comment by BranchArch** [comment]
still not working on Revit 2023

**Comment by eirannejad** [comment]
Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists

**Comment by BranchArch** [comment]
Hello Ehsan -- thank you so much for fixing this...! Heroic!

Scott


*SCOTT BAILEY* | BA OAA
*BRANCH* ARCHITECTURE | 613.438.5355 <+16134385355>
www.branch-architecture.com

**Comment by BranchArch** [comment]
Thanks for the help -- I tried it and still no go... I added some comments
and the new error messages to the GitHub site

Regards,

Scott


*SCOTT BAILEY* | BA OAA
*BRANCH* ARCHITECTURE | 613.438.5355 <+16134385355>
www.branch-architecture.com
