### ISSUE TITLE
Keynote manager gets locked with orphaned .lock file 

### ISSUE THREAD

**Issue by IAXRdev** [eirannejad/pyRevit#1584]
Saw that there have been other reports of this that were closed previously. We are running PyRevit 4.8.10, but keep running into issues where teams will repeatedly hit the snag of the "Wait for unlock timeout" error on the Keynote Manager. Once it occurs the team is unable to run the Keynote Manager further. We have had folks delete the .lock file, and check the keynote .txt file for the lock line, and in some cases have the users download and reupload the file. Currently our keynote .txt file is placed on BIM 360, and per the closed Issue https://github.com/eirannejad/pyRevit/issues/967 I have deleted the ".lock" file but we are still getting the same "Wait for Unlock timeout" error. Any advice on a more permanent fix? We see to have some teams running into this multiple times a day.

**Comment by IAXRdev** [comment]
Anyone have any ideas on this?

**Comment by HollyK15** [comment]
We have this same issue, again repeatedly for some teams/users many times a day.  I have even seen this where only one person is editing the file.  It's seems to be tied to the "sticky .lock" issues described in #967 .  Deleting the .lock, Unlocking the txt in BIM 360, and then making sure those edits sync back in the Autodesk Docs folder usually "resolves" it for most cases.  However, I don't understand why it's happening in the first place.  We just upgraded to 4.8.12 hoping it would somehow resolve this, but we were able to replicate in our testing.

What are the triggers or pieces involved in the "Wait for Unlock Timeout" error?  Is there anything you can suggest that we can look at internally that may be triggering it on our side?
