### ISSUE TITLE
Print Sheets Timeline

### ISSUE THREAD

**Issue by Architectuur** [eirannejad/pyRevit#1585]
Is it possible to add a timeline to the print sheets tool? It would be great to know how far it is in the process of printing an entire set or how much longer it might take.

**Comment by alexdaversa** [comment]
The current implementation for one combined pdf uses the Revit SubmitPrint() function to send the print job and only returns once that function is complete--that is to say, it's out of pyRevit's hands once the sheet list and settings are given from the script to Revit.

For individual sheets, this seems possible, although in the past for both a combined set and individual sheets I have looked at the bottom left of the Revit window which displays the currently printing sheet during the print job.
