### ISSUE TITLE
Make Pattern tool not running in Revit 2022

### ISSUE THREAD

**Issue by DBVWarchitects** [eirannejad/pyRevit#1586]
When we try to use the pyRevit "Make Pattern" tool in Revit 2022, we get an error that begins with "IronPython Traceback" and states "System.MissingMemberException: 'Autodesk.Revit.DB' object has no attribute "DisplayUnitType'." We have tried using this tool on several computers, all Windows 10 or 11 Pro, and all of them yield this error when trying to use that tool in Revit 2022. For what it's worth, the same tool works consistently in Revit 2020.

**Comment by RPIDL** [comment]
I have the same issue. is there any solution yet?

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\Ricardo Pereira\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Modify.panel\edit1.stack\Patterns.splitpushbutton\Make Pattern.pushbutton\script.py", line 38, in <module>
AttributeError: 'Autodesk.Revit.DB' object has no attribute 'DisplayUnitType'


Script Executor Traceback:
System.MissingMemberException: 'Autodesk.Revit.DB' object has no attribute 'DisplayUnitType'
 at IronPython.Runtime.Binding.PythonGetMemberBinder.NamespaceTrackerDelegate.Target(CallSite site, Object self, CodeContext context)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by DBVWarchitects** [comment]
Yes: pyRevit version 4.8.10.22040 resolves the issue, so you should download that and upgrade to it.  Usually you can just install the new version over the old, but sometimes I found I had to uninstall the old version before installing the new to make the upgrade work.  (I had to upgrade over 40 computers.)

George Hasapidis
Information Systems Manager

DBVW Architects
111 Chestnut Street, Providence, RI 02903
www.dbvw.com<http://www.dbvw.com/> | 401.831.1240 x122

***@***.***
.

**Comment by RPIDL** [comment]
Thank you. I did try upgrade but couldn’t fix the issue.
Will do as you said.

Many thanks,
Ricardo

Kind Regards

Ricardo Pereira OA.ARB
Senior Associate – Bim Lead
***@***.******@***.***>
***@***.***
***@***.***
***@***.***
London +44(0)20 7248 1234<tel:+442072481234>
Prague  +42(0)72 0279 588<tel:+42602189223>
***@***.***
idl.group<http://www.idl.group/>
If you would like to be removed from our email news update list please click ***@***.***?subject=Unsubscribe&body=Please%20remove%20me%20from%20all%20future%20mailings%0D%0A%0D%0ARegards>

Read IDL Privacy Policy<http://www.idl.eu.com/IDL-Privacy-Policy-2018.pdf>

***@***.******@***.***<https://www.instagram.com/idl.group/>
Please note our new website.

**Comment by DBVWarchitects** [comment]
After you do the upgrade, check the version to see if the upgrade took:
***@***.***

Should look like this:
***@***.***

George Hasapidis
Information Systems Manager

.

**Comment by RPIDL** [comment]
Thank you.
Once I have completely uninstalled and installed a fresh version all worked fine.


Kind Regards

Ricardo Pereira OA.ARB
Senior Associate – Bim Lead
+44(0) 79 1805 2172
+44(0) 20 3744 9093 (DD)
***@***.******@***.***>
***@***.***
***@***.***
***@***.***
London +44(0)20 7248 1234<tel:+442072481234>
Prague  +42(0)72 0279 588<tel:+42602189223>
***@***.***
idl.group<http://www.idl.group/>
If you would like to be removed from our email news update list please click ***@***.***?subject=Unsubscribe&body=Please%20remove%20me%20from%20all%20future%20mailings%0D%0A%0D%0ARegards>

Read IDL Privacy Policy<http://www.idl.eu.com/IDL-Privacy-Policy-2018.pdf>

***@***.******@***.***<https://www.instagram.com/idl.group/>
Please note our new website.

**Comment by DBVWarchitects** [comment]
Great—glad to read it.

George


George Hasapidis
Information Systems Manager

DBVW Architects
111 Chestnut Street, Providence, RI 02903

***@***.***
.
