### ISSUE TITLE
Create Schedule from CSV File

### ISSUE THREAD

**Issue by Kuhndog444** [eirannejad/pyRevit#1588]
Hello,

First of all I wanted to say, pyRevit is AWESOME!!!

I haven't had a problem with anything I've used so far except for this issue I'm having:

I'm trying to create a Schedule from a CSV File. It works fine in Revit 2021 when there's only one (1) Column but as soon as there are more than one column, this error comes up::

![image](https://user-images.githubusercontent.com/66026477/184657610-63c7984d-2f76-47a8-bd49-22ce04ee67f1.png)

Different Parameter names work as well as long as it's only one column.

I tried to get it to work in Revit 2022 and had the same issue but with a different error:

![image](https://user-images.githubusercontent.com/66026477/184658466-d5a8938a-2591-4635-bd6c-a5697da7ae14.png)

I read through the issues here and you had sent another (Jariverag) to the pyRevit Forums for a similar issue, I looked through the pyRevit forums and couldn't find anything close to this issue.

I have attached my csv file below  for your reference:

[test csv.csv](https://github.com/eirannejad/pyRevit/files/9338117/test.csv.csv)

As you can see, the parameters exist in the project(s):

![image](https://user-images.githubusercontent.com/66026477/184664602-dd989947-700c-4477-8e04-28bf07c870a6.png)

Could you please help? Any help would be appreciated and would be excellent!

**Comment by jmcouffin** [comment]
@Kuhndog444 
first things first:
Looking at your csv there is an issue:
the first column must be the 'Key Name' as per the instruction of the tool
```
Key Name,Comments
1,asdf4
2,asdf5
3,asdf6
4,asdf7
5,asdf8
6,asdf9
7,asdf10
```
- All parameters must be created and assigned to the proper category
- also make sure you are running Revit in english, the tools is not regionalized


now to the interesting part -> Revit 2022+
Parameter API was largely remodeled in 2021 2022 and 2023
https://apidocs.co/apps/revit/2022.1/WhatsNew.htm#RevitAPIChanges2022-APIChanges
So the code in itself will not work

I did try to fix it with this [PR](https://github.com/eirannejad/pyRevit/pull/1607)
If you want to try it, just replace the 2 files of the PR in your %appdata%/pyrevit-Master folder and let me know if all goes well.
I tested it against 2020->2023 without issues

**Comment by eirannejad** [comment]
Thank you @jmcouffin for the PR. I made a few modifications and also fixed the function that was checking for parameters. Previously only project parameters were supported but not any parameter that shows up in the Revit Schedule parameter selector, is now accessible.

**Comment by jmcouffin** [comment]
Tested and approuved @eirannejad 😃 🚀 🎸

**Comment by jmcouffin** [comment]
@eirannejad are you usually closing issues with commits or keeping them as a backlog for next release notes?
