### ISSUE TITLE
Error Traceback not coming through

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#159]
Tried running some scripts that required rpw, and I was an error msg (never expected them to run).
After I installed rpw through the package manager (looking really good, btw!!),  worked as expected.
What surprised me, was the msgs I got when I ran the script without rpw.

Previously, I would get something like: `module rpw cannot be found`.

This time, I was getting the error. below. I am guessing "browser" has to do with the new console, but in any case, seems that the full traceback is not making it's way back, and it's running into other errors on the way.
![image](https://cloud.githubusercontent.com/assets/9513968/23281830/d1a5e876-f9ec-11e6-9d6e-45e2a8a90b08.png)

**Comment by eirannejad** [comment]
This usually happens if the user closes the window while the script is running...I'll look into it

**Comment by eirannejad** [comment]
Tested. Missing module errors are printed in output window
