### ISSUE TITLE
PyRevit Load Error

### ISSUE THREAD

**Issue by BranchArch** [eirannejad/pyRevit#1590]
I've been through the strings and tried some things, but I still have issues loading PyRevit into Revit 2023 on Windows 10. I've made a new user and I've relocated the pyrevit_config.ini file. 

Any other thoughts?

![IronRevit 1](https://user-images.githubusercontent.com/83076627/185174363-58352329-b10d-470d-9efd-c7d90363172a.JPG)

**Comment by BranchArch** [comment]
still no luck with the updated installer, although the errors are different
![Snip A](https://user-images.githubusercontent.com/83076627/185658735-d0fcb762-c0de-4464-9764-e3ce4415e474.png)
![Snip B](https://user-images.githubusercontent.com/83076627/185658760-a7acfd56-0405-4d7d-895a-5cfb5153ba58.png)
:

**Comment by eirannejad** [comment]
Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists
