### ISSUE TITLE
revit.serialize() should iterate the elements and seralize standart Python data types

### ISSUE THREAD

**Issue by ejs-ejs** [eirannejad/pyRevit#1591]
Current implementation of revit.serialize() does not iterate the data nor serializes the standard Python data types and working with complex data structures becomes messy.

I need to store and retrieve the following data for each grid line :
```
{
 'End': <Autodesk.Revit.DB.XYZ object at 0x000000000000140F [(x , y, z)]>, 
 'EndBubble': True, 
 'EndBubbleVisible': True, 
 'Name': '1', 
 'Start': <Autodesk.Revit.DB.XYZ object at 0x0000000000001410 [(x, y, z)]>, 
 'StartBubble': True, 
 'StartBubbleVisible': True
}
```

The code I was working on used pickle() to store the data. The code was working in the Revit 2019 and I think Revit 2020, but is messed up ns Revit 2021 and above.

**Comment by eirannejad** [comment]
Seems like you already implemented this under PR #1594. Closing
