### ISSUE TITLE
pyRevit conflict with Environment Revit addin

### ISSUE THREAD

**Issue by amagio** [eirannejad/pyRevit#1593]
We noticed that the pyRevit addin does not load when the Environment Revit addin is installed. Uninstalling the Environment Revit addin resolves the issue.

Link to Environment Revit addin: https://apps.autodesk.com/RVT/en/Detail/Index?id=8520754940993057579&appLang=en&os=Win64

Thanks!

**Comment by eirannejad** [comment]
Most probably a dll conflict. Do you see any errors on load time? Would you be able to send the pyRevit log files under `%APPDATA%/pyRevit/20XX`?
