### ISSUE TITLE
Cut grid on view

### ISSUE THREAD

**Issue by sechanbask** [eirannejad/pyRevit#1596]
Hi,

I would like to cut grid near on the bottom of the crop view

Because grid cuts viewport tittle 

![2022-08-19_14h50_54](https://user-images.githubusercontent.com/4959672/185623801-123e52ba-9451-44a8-b552-ae9777a19e85.png)

and it's very painful to reduce lengh of every grid on every section I have to made

**Comment by ejs-ejs** [comment]
I'm currently working on storing and restoring the grid and level positions in the plan, elevation and section views. I need to finish the project in a week and I think the code will be mature enough at this time to publish it.

**Comment by sechanbask** [comment]
awesome
