### ISSUE TITLE
Python hook causing problem with dynamo python node

### ISSUE THREAD

**Issue by chevellebro1** [eirannejad/pyRevit#1598]
**Describe the bug**
I added a hook in pyrevit on doc-opened. After adding this, my dynamo scripts in my extension stopped working. After further investigation I noticed my custom python nodes were not working correctly and getting an error for a python dll file could not be found. I closed Revit, removed hook and launched my extension with no error in the dynamo script. I’m not sure why a hook would cause this behavior?

**To Reproduce**
1. Load python hook on doc-opened
2. Open document and after hook runs, use an extension tool
3. Dynamo python error

**Expected behavior**
The dynamo script is running fine without the hook being run. Am I missing something in the hook file that needs to be added?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version: latest release
 -Dynamo 2.5

**Comment by eirannejad** [comment]
Do you know which engine you have connected pyRevit with? If you can run `pyrevit env` on command line and sharing the sanitized results here that'd be great
