### ISSUE TITLE
Overkill Command Not Working Correctly in Detail Item Family

### ISSUE THREAD

**Issue by eluvs** [eirannejad/pyRevit#1599]
I am currently running version 4.8.11 and sometimes when I use the overkill command in Revit 2021, all of the lines get all messed up to the point of it needing to be undone. This hasn't happened to all of my detail item families, but it has happened to enough that it's an issue. 

I am making new detail item families from CAD details and this has happened on almost half of the families.

**To Reproduce**
1. Import a CAD file into a Detail Item family.
2. Explode the file.
3. Let Guardian convert the lines from CAD lines to Revit lines.
4. Convert model lines to detail lines. (This happens to model and detail lines, but this is what I have been doing for all families)
5. Hit Overkill.

**Screenshots**
Before: 
<img width="846" alt="image" src="https://user-images.githubusercontent.com/34044878/186498423-1ba64c84-2ca0-4f02-9841-7725e31ab9af.png">

After:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/34044878/186498278-c3c800c2-ccd1-4589-8bac-5abda41a7651.png">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - pyRevit Version 4.8.11
 - pyRevit Environment: ```==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.11.22151+0307-wip" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
master | Product: "2022.1.2" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2021.1.5" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2020.2.3" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2019.2.2 Hotfix" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\elovell\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2022.1.2 | Version: 22.1.21.13 | Build: 20220123_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021.1.5 | Version: 21.1.50.27 | Build: 20211018_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.3 | Version: 20.2.30.42 | Build: 20200826_1250(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
PID: 25248 | 2021.1.6 | Version: 21.1.60.25 | Build: 20220123_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2021"
PID: 764 | 2021.1.5 | Version: 21.1.50.27 | Build: 20211018_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2021"
==> User Environment
Microsoft Windows 10 [Version 10.0.22000]
Executing User: GGLO\elovell
Active User: GGLO\elovell
Admin Access: No
%APPDATA%: "C:\Users\elovell\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.11.22151+0307-wip```

**Comment by jmcouffin** [comment]
> half of the families.
@eluvs 
could you share 2 CADs + 2 families
One that works, another one that does not so that I can try to reproduce and debug?

**Comment by eluvs** [comment]
I have attached a zip folder with the CAD and family files. The overkill command has not been run in either file, but I can confirm that it works in 1 family and not the other.
[Overkill Command Issue 1599.zip](https://github.com/eirannejad/pyRevit/files/9700797/Overkill.Command.Issue.1599.zip)

**Comment by jmcouffin** [comment]
@eluvs 
I did try a few things and could not get to fix it properly
While trying at first, using metric template, it worked fine.
Then I tried imperial template, and it did the same as illustrated in your screen capture.

I tried: 
- changing the `UnitSytem `of the document
- changing the `UnitType `for Length
- changing both
- adjusting the precision of the float numbers -> it did change the behaviour, but could not find the decimal sweet spot
- changed the float method multiplying the results by 304.5 (1 foot as Revit is coded in decimal feet)

my suggestion for the time being is using the Metric Template in the meantime, before someone else can tackle the issue

**Comment by eluvs** [comment]
Thanks! I will do that for now.
