### ISSUE TITLE
Error loading pyRevit in Revit 2023

### ISSUE THREAD

**Issue by neel-studio4** [eirannejad/pyRevit#1600]
I have downloaded the pyrevit-installers.zip from a recent update.
On extraction, I have pyRevit_4.8.12.22226_signed.exe which I installed. However after loading Revit 2023 I am unable to see the I receive an error for pyRevit.
Then I also installed pyRevit_4.8.12.22226_admin_signed.exe to see if there is any admin access which could have caused the error, but it still threw an error while loading Revit 2023.

Please see the error in the attached image.
![Pyrevit Error](https://user-images.githubusercontent.com/70375924/186680400-47e44681-44a6-4872-89bc-34fb7d79d735.png)

Kindly suggest.

**Comment by BranchArch** [comment]
Hi Neel -- I'm having the same issue... did you manage to resolve it?

**Comment by eirannejad** [comment]
Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists
