### ISSUE TITLE
Pyrevit not loading 

### ISSUE THREAD

**Issue by MukundMogal** [eirannejad/pyRevit#1602]
Hi,

I have installed pyRevit 4.8.10. However, when I am opening the Revit it's not loading. It gives an error message as below. Please advise. 

![image](https://user-images.githubusercontent.com/109891515/187903122-aa3d397c-3a27-49ba-ae52-5f39691d64e5.png)
![image](https://user-images.githubusercontent.com/109891515/187903181-aa6ce8e7-e383-4de4-9cc4-c925d5906db0.png)

**Comment by laryssacrd** [comment]
tambem estou com o mesmo problema

**Comment by eirannejad** [comment]
Please [try the latest release](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.12.22247%2B0031) and reopen this ticket if problem persists

**Comment by MukundMogal** [comment]
Hi, I have installed the latest release, however, it still shows the same error message.
