### ISSUE TITLE
avertissement sur REVIT ?

### ISSUE THREAD

**Issue by afrout97** [eirannejad/pyRevit#1604]
bonjour,

qui peut m'expliquer comment PYREVIT gère la visualisation des avertissement dans REVIT ?

**Comment by eirannejad** [comment]
Please provide more info.

**Comment by afrout97** [comment]
Bonjour,
je suis désolé pour le retard
la visualisation des avertissements sur REVIT est un peu difficile, c'est à dire quand je trouve un avertissement qui me signale deux objets en doublon, pour le voir dans une vue (plan, section, élévation ou vue isométrique), REVIT ne me passe jamais la bonne vue (voir image 2), en plus je ne peux pas sélectionner dans le projet,
![01](https://user-images.githubusercontent.com/112713654/188637555-96e94140-d888-4738-864a-7e7e605ff3fc.png)
![2](https://user-images.githubusercontent.com/112713654/188637564-89904b3d-a2c7-4bf8-b5ec-f814530e1b1b.png)
 un des deux objets pour appliquer une section BOX (voir image 1)

**Comment by BIMONE-OUTILS** [comment]
@afrout97 Préférable d'utiliser l'anglais si tu souhaites des réponses sur un logiciel tout en Anglais.
Bref. Ton problème n'a rien à voir avec pyRevit.
Si tu cliques sur afficher plusieurs fois il t'afficheras d'autres vues dans lesquelles ces éléments sont visibles.
MAIS
Sauf si tu connais la programmation: 
tu devrais utiliser Warchart d'archilizer pour gérer tes avertissements de manière plus sensible.
https://apps.autodesk.com/RVT/en/Detail/Index?id=5069841371205448504&appLang=en&os=Win64

S'il te plait ferme cette question.
Please do close this issue

**Comment by afrout97** [comment]
bonjour, merci pour ta réponse,
j'utilise Pyrevit anglais avec un REVIT français, c'est pour ça je communique avec vous en français.
j'avais pas de problème dès le début, j'avais une demande de démonstration ou d'explication sur la visualisation des avertissement sur Pyrevit, parce que j'ai vu d'autres plugin qui le font.
merci et bonne journée

**Comment by jmcouffin** [comment]
Pas de pb en soit.
si tu précises ce que tu cherches à faire, illustré et en anglais, tu peux poser ta question sur le forum de pyRevit https://discourse.pyrevitlabs.io/
mais je te conseille d'essayer Warchart, ça fera le travail
