### ISSUE TITLE
Error while opening Revit 2022 and Revit 2023

### ISSUE THREAD

**Issue by Arsany123** [eirannejad/pyRevit#1608]
once i launch Revit i have this error appears starting from Revit 2022 and Revit 2023.

i have attached the screenshot below. can you please advise me how to fix this issue.

![2022-09-06_17h40_52](https://user-images.githubusercontent.com/43368301/188680138-aab600cd-3eac-43c0-a70b-ea8a0d14676c.png)

thanks

**Comment by eirannejad** [comment]
Which pyRevit version? Would you mind running `pyrevit env` on command prompt and sharing results?

**Comment by AirWreckaStuff** [comment]
I'm also receiving similar errors, just installed pyRevit v4.8.12.22247
![image](https://user-images.githubusercontent.com/26884617/188702495-2c4b5157-abd9-48d1-9674-81f7d691291b.png)
Here is results from pyrevit env:
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\econcolino\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\me\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\me\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2021" | Engine: IPY277 (277) | Path: "C:\Users\me\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2020" | Engine: IPY277 (277) | Path: "C:\Users\me\AppData\Roaming\pyRevit-Master"
master | Product: "2019.2.6" | Engine: IPY277 (277) | Path: "C:\Users\me\AppData\Roaming\pyRevit-Master"
master | Product: "2018.3.3 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\me\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\econcolino\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.0.20.21 | Build: 20220726_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
Autodesk Revit 2021 | Version: 21.1.70.21 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
Autodesk Revit 2020 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.6 | Version: 19.2.60.3 | Build: 20220224_1700(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages

**Comment by Arsany123** [comment]
![image](https://user-images.githubusercontent.com/43368301/188801903-54a08bfd-65b9-45e1-b43d-b353e48de69c.png)

**Comment by Avinashhv** [comment]
Hi 

I was getting similar error and the reason it was happening for me was I had not uninstalled previous version of Pyrevit (4.8.8). I had both versions installed. I had to uninstall both versions and install fresh copy of latest version of Pyrevit for it to work . Hope that helps

**Comment by Arsany123** [comment]
Thanks a lot . it is working
