### ISSUE TITLE
pyRevit causing Revit to crash on loading (Revit 2021 and 2023)

### ISSUE THREAD

**Issue by obijuandunnobi** [eirannejad/pyRevit#1609]
We have an issue in our office where pyRevit is now causing all versions of Revit to crash on startup. Revit gets no further than the splash screen before it crashes without warnings. My assumption is that a Windows update has rolled out that has caused a conflict somewhere as I haven't updated any design software between when it was fine and stopped working. About half of our machines had the issue one week and by the next week it was affecting all of them. I've tried multiple builds of pyRevit too.

The journal file below shows pyRevit is the issue and indeed, disabling pyRevit allows Revit to boot normally. I've also tried disabling every add-in except for pyRevit and Revit still crashes.

Contents of the relevant section of the journal file below - this is the very end of the file. Is anyone able to make sense of what's going on? I haven't found any other reports of crashing from other users.  Full journal also attached.

Win 10 Pro.
Revit 2021.1.7
Revit 2023.0.1
pyRevit versions - I've tried:
4.8.10.22040
4.8.11.22151
4.8.12.22247
[pyRevit_Crash_20220906.txt](https://github.com/eirannejad/pyRevit/files/9500548/pyRevit_Crash_20220906.txt)

<code>

' 0:< API_ERROR { : Assembly version conflict in some references in pyRevitLoader.dll assembly
'Addin's module RevitAPI of version 22.0.0.0 conflicts with same preloaded module of version 21.0.0.0
'Addin's module RevitAPIUI of version 22.0.0.0 conflicts with same preloaded module of version 21.0.0.0 } 
' 0:< ::42:: Delta VM: Avail -13 -> 134210976 MB, Used +3 -> 539 MB; RAM: Avail -17 -> 20267 MB, Used +3 -> 776 MB, Peak +5 -> 778 MB 
' 0:< GUI Resource Usage GDI: Avail 9749, Used 251, User: Used 178 
' 0:< API_ERROR { : Assembly version conflict in some references in pyRevitRunner assembly
'Addin's module RevitAPIUI of version 22.0.0.0 conflicts with same preloaded module of version 21.0.0.0
'Addin's module RevitAPI of version 22.0.0.0 conflicts with same preloaded module of version 21.0.0.0 } 
' 0:< ::42:: Delta VM: Avail +42 -> 134211018 MB, Used +12 -> 552 MB, Peak +14 -> 556 MB; RAM: Avail -29 -> 20238 MB, Used +24 -> 801 MB, Peak +27 -> 806 MB 
' 0:< GUI Resource Usage GDI: Avail 9749, Used 251, User: Used 177 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.WindowsAPICodePack assembly
'Addin's module mscorlib of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Windows.Forms of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Core of version 3.5.0.0 conflicts with same preloaded module of version 4.0.0.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.WindowsAPICodePack.Shell assembly
'Addin's module mscorlib of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Windows.Forms of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module PresentationFramework of version 3.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module WindowsBase of version 3.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module PresentationCore of version 3.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Drawing of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Core of version 3.5.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module WindowsFormsIntegration of version 3.0.0.0 conflicts with same preloaded module of version 4.0.0.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in MadMilkman.Ini assembly
'Addin's module mscorlib of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0 } 
' 0:< ::42:: Delta VM: Avail -12 -> 134211006 MB, Used +8 -> 560 MB, Peak +3 -> 560 MB; RAM: Avail +3 -> 20242 MB, Used +10 -> 812 MB, Peak +6 -> 812 MB 
' 0:< GUI Resource Usage GDI: Avail 9749, Used 251, User: Used 177 
' 0:< API_ERROR { : Assembly version conflict in some references in System.Reflection.Metadata assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.2.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.2.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis.CSharp assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.2.0 } 
' 0:< ::42:: Delta VM: Avail -11 -> 134210996 MB, Used +2 -> 562 MB, Peak +2 -> 562 MB; RAM: Avail -4 -> 20239 MB, Used +4 -> 816 MB, Peak +4 -> 816 MB 
' 0:< GUI Resource Usage GDI: Avail 9749, Used 251, User: Used 177 
' 0:< API_ERROR { : Assembly version conflict in some references in pyRevitLabs.Common assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.2.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis.VisualBasic assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.2.0 } 

</code>

**Comment by lukekv** [comment]
I am having a similar issue.  I received a new desktop computer and am in the process of reinstalling programs on the new machine.  Previously I had pyRevit v4.8.10.22040+1743 installed running on IronPython 2.7.7 and working fine with Revit 2019.2.6

On the new machine with a clean install of Revit 2019.2.6 I installed pyRevit_4.8.12.22247.  This is causing Revit to crash on startup.  I've attached the log file.  I have tried installing pyRevit v4.8.10.22040 and pyRevit v4.8.9.21361+0320 but these seem to have the same issue.

I also tried opening Revit 2020 and the same error occurred.  One difference I noticed is that the installer for pyRevit v4.8.12.22247 created a folder named "pyRevit-Master" which does not exist on my old machine.  

Uninstalling pyRevit using add/remove programs fixes the issue and allows Revit to load.

Revit will crash before the splash screen and does not display any warnings or error messages.

[pyRevit_2019_172927bb7ed2dd94_PyRevitLabs.PyRevit.Runtime.log](https://github.com/eirannejad/pyRevit/files/9679217/pyRevit_2019_172927bb7ed2dd94_PyRevitLabs.PyRevit.Runtime.log)

**Comment by Duckspit** [comment]
I am having the same issues when I install the latest version of Pyrevit. I found an older thread that suggested whitelisting pyRevit with SentinalOne solved the issue but that has not helped:

https://github.com/eirannejad/pyRevit/issues/1569

I can use pyRevit 4.7.7 with Revit 2019 and 2021 with no crashes.

**Comment by lukekv** [comment]
@Duckspit thank you for referencing that previous issue.

I also tried whitelisting pyRevit on SentinalOne but that did not work for me.  I'm still having the same crash issue on all versions of Revit.

**Comment by sylsau** [comment]
pyRevit's latest version and pyRevit v4.8.8 installed as administrator for all users is also causing Revit 2022 fresh install to crash. I actually had a lot of trouble finding what made Revit crash, I even got as far as reinstalling the whole thing (silly me)...

Attached here is the corresponding Revit journal file. I haven't tried whitelisting it in SentinelOne though (but yes I do have SentinelOne recently installed on my machine).

[journal.0003.txt](https://github.com/eirannejad/pyRevit/files/10102497/journal.0003.txt)

**Comment by lukekv** [comment]
Update.
I submitted this thread to our IT support group along with the following.
https://github.com/eirannejad/pyRevit/issues/1444
https://github.com/eirannejad/pyRevit/issues/1491

They were able to resolve the issue. I believe it still had to do with SentinelOne but it was not sufficient to just whitelist the application. I did not perform the fix but the following was given when closing the support ticket - maybe it will help others.
Issue Description:

pyRevit Exclusion

Steps of Remediation:

Reviewed forum posts sent
Reviewed SentinelOne Exclusions
Modified exclusion to disable monitoring folders completely and added exclusion to specific group

**Comment by obijuandunnobi** [comment]
Thanks - also SentinelOne here.  I've had IT add all pyRevit folders I can find to exclusions but it still crashes.  Will add Revit itself and see if that solves the issue.

**Comment by tjxme** [comment]
> @lukekv - we've tried excluding all folders to with pyRevit from SentinelOne:
> 
> C:\ProgramData\pyRevit C:\Program Files\pyRevit-Master C:\ProgramData\Autodesk\Revit\Addins %AppData%\Autodesk\Revit\Addins C:\Program Files\Autodesk
> 
> But still we get crashes with pyRevit enabled. Are you able to check with your IT department to see if any further steps needed to be taken? I know we've only recently started using SentinelOne (around when I made this thread, not so coincidentally) so maybe our IT department is just missing something?
> 
> Thanks

do you get this fixed? i still have the same issue here

**Comment by obijuandunnobi** [comment]
Weirdly fixed on some machines but not others. Need to investigate the
exclusions further.
