### ISSUE TITLE
Export Pat file error

### ISSUE THREAD

**Issue by zawmin76** [eirannejad/pyRevit#1610]
I created pattern with pyRevit 4.8.12 on Revit 2019.2.6. It's work in project.
![image](https://user-images.githubusercontent.com/63436325/188778847-724927a6-6e94-459d-b5a8-824f9e24af0f.png)

I export PAT file and create pattern in new project. No "Model" Type patterns found.
![image](https://user-images.githubusercontent.com/63436325/188778148-2f7a260a-2ad5-4d46-9b21-010b6f7f3df8.png)
![image](https://user-images.githubusercontent.com/63436325/188778334-78d9b96b-d2fa-47b3-b3fa-06408c41afae.png)

In pat file, I found 2 periods within comma.
![image](https://user-images.githubusercontent.com/63436325/188778717-c72ad814-23b4-4c10-a0be-5ed101632f66.png)

[RS Perforated.txt](https://github.com/eirannejad/pyRevit/files/9502336/RS.Perforated.txt)

Regards,
Zaw

**Comment by Grahampuba** [comment]
seeing the same behavior with 4.8.12 in Revit 2020.2.9, exported .pat file is missing comma between fifth and sixth values

**Comment by alexdaversa** [comment]
Proposed fix in pr #1792

**Comment by jmcouffin** [comment]
Fixed by @alexdaversa in https://github.com/eirannejad/pyRevit/pull/1792
See wip release in the action section
