### ISSUE TITLE
Temporarily Isolate to recognize "Shaft Openings'

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#1611]
Sorry, can PyRevit Temporarily Isolate be coded to recognize "Shaft Openings'? Thanks

**Comment by jmcouffin** [comment]
? ☝️ 
@Robbo1234 either write something or close the issue

**Comment by jmcouffin** [comment]
Stale
Closing the issue

**Comment by Robbo1234** [comment]
Hi there,

Can we get PyRivt Isolate to recognize "Shaft Openings'?  Refer to the screenshot below. Thanks

![image](https://user-images.githubusercontent.com/8776947/216043124-b231d67f-2222-4721-b9cd-0cc3f0517c3c.png)

**Comment by jmcouffin** [comment]
have you tried shift+click on the tool?

**Comment by Robbo1234** [comment]
Yes, the shift+click is not available on the 'PyRevit Isolate' tool but it
is available on the 'PyRevit Pick' tool.

**Comment by jmcouffin** [comment]
> the shift+click is not available on the 'PyRevit Isolate' tool but it is available on the 'PyRevit Pick' tool.

It is available on the latest install for sure.
https://github.com/eirannejad/pyRevit/tree/master/extensions/pyRevitTools.extension/pyRevit.tab/Selection.panel/select.stack/Isolate.pushbutton

**Comment by jmcouffin** [comment]
Since November 2020 at worst

**Comment by Robbo1234** [comment]
Thanks, Jean, "Shaft Openings' is now in PyRevit Isolate. Rob
