### ISSUE TITLE
pyRevit will not show up in toolbar for Revit 2021.1.6

### ISSUE THREAD

**Issue by sfnordic** [eirannejad/pyRevit#1612]
**Describe the bug**
As a Revit 2021.1.6 user, I want to install pyRevit and use it in a collaborative project. The install has been successful with no errors. However, when I try and open Revit, I get an error message (see screenshot). There is no pyRevit in revit as expected.  We have successfully installed pyRevit for revit 2023, but we use multiple versions in the office. 

We have tried the suggested solution below but it did not work:
If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

**To Reproduce**
1. Install revit 2021.2.6
2. Install pyRevit
3. Restart computer
4. Open Revit 2021.2.6

**Expected behavior**
Revit to open without error message

**Screenshots**
![image](https://user-images.githubusercontent.com/113106212/189106662-f5dcbe19-8577-4f7e-9931-e888bc7c72dc.png)
![image](https://user-images.githubusercontent.com/113106212/189107337-4e6b8b78-2267-40fe-9902-886bf8b4f260.png)

**Desktop (please complete the following information):**
 - pyRevit Version [e.g. 22]
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

**Additional context**

**Comment by jmcouffin** [comment]
Hi @sfnordic, 
It looks like a conflict between two revit addins as it is revit version specific
you might want to try to temporarily disable all non autodesk addins except pyRevit for Revit 2021 and then see if it works.
If so, re-activate addins one by one (every time starting revit to identify which ones are note playing well together)

to activate/deactivate addins, you can use https://diroots.com/apps/diroots-app-manager/

**Comment by jmcouffin** [comment]
> We have already tried this. Do you have any other suggestions we might try?

Last issue I replied to, which looked pretty much like your involved an addin with either a conflict of version of ressources or a different version python being loaded before pyRevit. It is a pretty common pattern. See here https://github.com/eirannejad/pyRevit/issues/1614
So if you really tried to disable all addin except the pyRevit one, no, I have no other hint. Sorry.

**Comment by PiperBIM** [comment]
I was having the same issue with getting PyRevit load loading when I'd start Revit, I believe it was after I installed some other addins for revit. I found a solution somewhere on this forum but can't remember where. Basically the solution was to rename the PyRevit add in in the addins folder (C:\ProgramData\Autodesk\Revit\Addins\2021). I added a zero to the name of the pyrevit addin at the start of the name so it appears at the top of the addins list. Revit apparently loads addins in alphabetical order. This fixed the issue for me by loading PyRevit prior to any of my other addins.

**Comment by jmcouffin** [comment]
@PiperBIM that is indeed a good strategy
@sfnordic can you try this and report back?

**Comment by PiperBIM** [comment]
There is a possibility that this causes issues with BIM 360 if that is used. I am getting an issue where I can't access cloud models through BIM 360 after doing this & it might be due to this running during Revit start up prior to the BIM Collaborate addins, I'm guessing it shouldn't matter but I don't know enough to know for sure.

**Comment by jmcouffin** [comment]
> There is a possibility that this causes issues with BIM 360 if that is used. I am getting an issue where I can't access cloud models through BIM 360 after doing this & it might be due to this running during Revit start up prior to the BIM Collaborate addins, I'm guessing it shouldn't matter but I don't know enough to know for sure.

related https://thebuildingcoder.typepad.com/blog/2022/10/bim360-links-and-programming-add-ins.html#3
