### ISSUE TITLE
Print Order messed up

### ISSUE THREAD

**Issue by kslifter** [eirannejad/pyRevit#1613]
**Describe the bug**
I have run into my first issue with PyRevit in 2023. When I use the print feature everything looks like it should, but once it is done printing and I open the pdf the pages are in a completely random order. I am using bluebeam and in the bookmark section the bookmarks are in the correct order, but the pages are not. I do not get any error codes, it's just not printing in the correct order. 

**To Reproduce**
1. Print Sheets
2. Select correct sheet index
3. Select Combine into One PDF
4. Click Print

**Expected behavior**
I should print in the correct order

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 11
 - pyRevit Version 4.8.12
 - pyRevit Environment: 
 C:\Windows\System32>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\Ian\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\Ian\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\Ian\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
Prime | Type: Unknown | Repo: "" | Installed: "G:\Shared drives\PRIME DESIGN\STANDARDS\DYNAMO\Pyrevit\Pyrevit Toolbar\Prime.extension"
==> Default Extension Search Path
C:\Users\Ian\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
G:\Shared drives\PRIME DESIGN\STANDARDS\DYNAMO\Pyrevit\Pyrevit Toolbar
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.0.20.21 | Build: 20220726_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages

**Additional context**

**Comment by ngsshane** [comment]
I can confirm our office is experiencing the exact same issue as you have described. At the moment our workaround is to print sheets as individuals and combine them. Not ideal.

**Comment by kslifter** [comment]
@ngsshane 
Yeah, that is what we have been doing as well. I did download the diroots prosheets addin and that allows all the individual sheets to print at once. That way you don't have the popup with each sheet that is printed.  That has been nice.

**Comment by Robbo1234** [comment]
Hi there,

To avoid the popup appearing each time I print a individual print in a
batch print, I use the Free PDF Driver called PDFCrerator.

Download PDFCrerator.:
 https://download.pdfforge.org/download/pdfcreator/PDFCreator-stable
<https://download.pdfforge.org/download/pdfcreator/PDFCreator-stable>

Refer to screenshot of PDFCreator Settings (Step 3)  to avoid the popup
appearing each time I print a individual print in a batch print:
[image: image.png]

**Comment by ngsshane** [comment]
> 

hi @Robbo1234,

I also use PDF Creator.
What setting are you refering to? 
It looks like you tried to attach an image but it is not appearing for me.

Thanks!
