### ISSUE TITLE
PyRevit not loading after installing last verison

### ISSUE THREAD

**Issue by osdj-a** [eirannejad/pyRevit#1614]
**Describe the bug**
Currently installed the latest version of PyRevit not i get "PyRevitLoader - Error Loading pyRevit" error in Revit 2022. 
I´ve tried pyrevit attach master 277 --installed. Also uninstalling etc. 

**To Reproduce**

**Expected behavior**
To run 

**Screenshots**
![image](https://user-images.githubusercontent.com/113432373/189882985-4bc6edc2-b9fb-4a77-94e3-85380f741f99.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version [ 4.8.12
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

![image](https://user-images.githubusercontent.com/113432373/189883171-a22d408b-6a9e-4c32-a204-008281fdfd1a.png)

**Additional context**
Version before worked like a charm.

**Comment by jmcouffin** [comment]
Hi @osdj-a , Can you please check it it works with

`pyrevit attach master 2710 --installed --allusers`
It might have to do with the ironpython engine

If it still does not work, I would check these two articles:

1. https://www.notion.so/pyRevit-Is-Installed-But-Does-Not-Load-f6495adb56254e9e8021f8a68e3b2ab7 (probably not related)
2. https://www.notion.so/Can-Not-Uninstall-pyRevit-or-pyRevit-CLI-24978bb1aa3f4e419f61272bd1b19ffb

if nothing else works:

- Uninstall pyRevit and pyRevit CLI (if installed)
- delete or move every folder like %appdata%/pyrevit and %appdata%/pyrevit-master and c:/programdata/pyrevit
- restart
- re-install the latest release

**Comment by osdj-a** [comment]
> Hi @osdj-a , Can you please check it it works with
> 
> `pyrevit attach master 2710 --installed --allusers` It might have to do with the ironpython engine
> 
> If it still does not work, I would check these two articles:
> 
> 1. https://www.notion.so/pyRevit-Is-Installed-But-Does-Not-Load-f6495adb56254e9e8021f8a68e3b2ab7 (probably not related)
> 2. https://www.notion.so/Can-Not-Uninstall-pyRevit-or-pyRevit-CLI-24978bb1aa3f4e419f61272bd1b19ffb
> 
> if nothing else works:
> 
> * Uninstall pyRevit and pyRevit CLI (if installed)
> * delete or move every folder like %appdata%/pyrevit and %appdata%/pyrevit-master and c:/programdata/pyrevit
> * restart
> * re-install the latest release

Tried all of them but still have the same error

**Comment by jmcouffin** [comment]
@osdj-a 
Other possible solution (less probable), might be due to a dll interaction
try this: https://github.com/eirannejad/pyRevit/issues/1612#issuecomment-1246314521

**Comment by osdj-a** [comment]
> Tried but still, error. Are there anyway to completely wipe off pyRevit and retry an clean install?

**Comment by jmcouffin** [comment]
> * Uninstall pyRevit and pyRevit CLI (if installed)
> * delete or move every folder like %appdata%/pyrevit and %appdata%/pyrevit-master and c:/programdata/pyrevit
> * restart
> * re-install the latest release

@osdj-a 
besides what I mentioned earlier https://github.com/eirannejad/pyRevit/issues/1614#issuecomment-1246303832, there is the `pyrevit doctor` command to tries to reset registry keys.

The install is not so intrusive. The unistall process (hte regular one) usually does the job and leaves in %appdata% the pyrevit-master and pyrevit folders that you can just delete.
you could use an external tool to uninstall it as well, I used iobit uninstaller in the past with success in the past https://www.iobit.com/en/advanceduninstaller.php

**Comment by jmcouffin** [comment]
There are a lit of related issues on github and on the pyRevit forum but they tend to have different reasons. The most seen being dll incompatibility between a revit addin and pyrevit

**Comment by GiovannaGGS** [comment]
Hello I have the Revit 2021.1.4 and the pyrevit it doesn't work with this version. What could I do? 

Thank you

**Comment by osdj-a** [comment]
> There are a lit of related issues on github and on the pyRevit forum but they tend to have different reasons. The most seen being dll incompatibility between a revit addin and pyrevit

Nothing really seems to work. 
I know Ive had this problem before, I believe it had something to do with Python 2&3 / IronPython but cant really remmember.

**Comment by osdj-a** [comment]
Apperently I had an internal company add-in for Revit which had an older version of Python that loaded in before pyRevit. Worked by disable it.
