### ISSUE TITLE
PyRevit Ribbon Typo - Easy Fix

### ISSUE THREAD

**Issue by jclark-architect** [eirannejad/pyRevit#1617]
There is a simple typo in the PyRevit Drawing Set toolset. PyRevit > Drawing Set > Views > Open Referecing Sheet
This should be 'Open Referencing Sheet', not 'Open Referecing Sheet'.

It shouldn't take too much time to update the text value for this useful tool.

![image](https://user-images.githubusercontent.com/85770066/190491910-82a457e2-50a3-468d-938c-129e4592e1ff.png)

 - OS: Windows
 - pyRevit Version 4.8.12.22247+0031

**Comment by jmcouffin** [comment]
you can close the issue, thanks for the heads up @jclark-architect

**Comment by jclark-architect** [comment]
Awesome, thank you!!
