### ISSUE TITLE
Suggestion: Add option to pyRevit Setting to Auto-Close Loader console on startup

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#162]
Would be nice to always auto-close, except if an error is logged.

**Comment by eirannejad** [comment]
https://github.com/eirannejad/pyRevit/commit/16b2ca7312fa69afae0240b8743137c8480c9007
Implemented. Output window now has `this_script.output.self_destruct(seconds)`
Session manager uses this in combination with user config (for timeout in seconds) to close the output window if no errors has been reported by any of the modules.
