### ISSUE TITLE
PyRevit installed correct and shows up in toolbar but doesn't let me add folder in my Directory

### ISSUE THREAD

**Issue by 111Adrian** [eirannejad/pyRevit#1621]
PyRevit installed correct and shows up in toolbar but doesn't let me add folder in my Directory. I installed PyRevit 4.8.12.22247_signed. 

It also doesnt let me Disable Extensions. When I do update all files it goes through the cycle and then doesnt do anything. I have restarted Revit, uninstalled PyRevit. Re-installed PyRevit. Any help would be appreciated.

**Comment by jmcouffin** [comment]
> doesn't let me add folder in my Directory

Hi @111Adrian, 
Add what? in where?
you have the pyrevit toolbar with its tools in Revit?
they work?

Can you describe further the issue, maybe with screen captures and explaination of the things you are trying to achieve step by steps?

**Comment by 111Adrian** [comment]
Thank you for the prompt response. After two days of looking through forum
i found the solution. So sorry for the incomplete description. A solution
was found in may 7th 2020. Issue #885

**Comment by jmcouffin** [comment]
Fine, 
Please close the issue
