### ISSUE TITLE
I am not able to add a "Custom Button" using pyrevit path. 

### ISSUE THREAD

**Issue by S-Rafay-Ali-bukhari** [eirannejad/pyRevit#1622]
I followed all the instructions of Aussie BIM and other videos on custom node creation. I made all the folders with exact extensions however when I add path "using custom path in pyrevit" I am unable to see in my Revit ribbon panel.

**Comment by jmcouffin** [comment]
> I followed all the instructions of Aussie BIM and other videos on custom node creation. I made all the folders with exact extensions however when I add path "using custom path in pyrevit" I am unable to see in my Revit ribbon panel.

Hi,
@S-Rafay-Ali-bukhari 
your question is more suited for the forum https://discourse.pyrevitlabs.io/
and you should elaborate and illustrate and even share files if you want someone to be able to tackle with you the issue
