### ISSUE TITLE
Implementation of RevitAPIIFC.dll

### ISSUE THREAD

**Issue by jmcouffin** [eirannejad/pyRevit#1623]
This is a missing part in the pyRevit module, or at least I could not find it.
I would be happy to help but don't know enough of the structure of the RevitAPI.dll implementation to just add this one

**Comment by dvdgnz** [comment]
Would importing manually from the library work?
```
import clr
clr.AddReference("RevitAPIIFC.dll")
import RevitAPIIFC
```

**Comment by BIMONE-OUTILS** [comment]
It does
I just think it would be tidier as a part of the pyRevit lib

**Comment by jmcouffin** [comment]
It does
I just think it would be tidier as a part of the pyRevit lib
