### ISSUE TITLE
pyRevit_4.8.12.22247 not working for Revit 2023

### ISSUE THREAD

**Issue by zahowser** [eirannejad/pyRevit#1625]
**Describe the bug**
Installed Revit 2023.
Installed pyRevit_4.8.12.22247
pyRevit is not loading/present after opening Revit 2023.
It looks like the pyRevit loader screen appears when opening Revit, but it is so quick to close, I cannot screenshot it.
Revit does not crash.

I ran the below command in **pyrevit-doctor** in order to troublshoot/fix. Is that correct?
`pyrevit attach master 277 --installed`

**To Reproduce**
1. Open 'Revit 2023'

**Expected behavior**
pyRevit loader would appear as Revit 2023 launches.
pyRevit menu would be present in Revit 2023 after launch completes.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Revit 2023: 23.0.11.19; 20220503_1030(x64)
 - pyRevit Version 4.8.12.22247
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

```==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\zhowser\AppData\Roaming\pyRevit-Master"
==> Attachments
Unnamed-363FBF8 | Product: "2021.1.5" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
Unnamed-363FBF8 | Product: "2020 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
Unnamed-363FBF8 | Product: "2019.2 (Full Install)" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
Unnamed-363FBF8 | Product: "2017 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\zhowser\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.0.11.19 | Build: 20220503_1030(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2021.1.5 | Version: 21.1.50.27 | Build: 20211018_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020 First Customer Ship | Version: 20.0.0.377 | Build: 20190327_2315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2 (Full Install) | Version: 19.2.1.1 | Build: 20190108_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2017 First Customer Ship | Version: 17.0.416.0 | Build: 20160225_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19044]
Executing User: ART-TEAM\zhowser
Active User: ART-TEAM\zhowser
Admin Access: No
%APPDATA%: "C:\Users\zhowser\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.12.22247+0031```

**Comment by jmcouffin** [comment]
try 
`pyrevit attach master 2710 --installed --allusers`
restart revit
if still no show try
`pyrevit attach Unnamed-363FBF8 277 --installed --allusers`
restart revit

if it still does not work, uninstall completly and re install (might want to delete %appdata%/pyrevit and %appdata%/pyrevit-master folders

**Comment by dvdgnz** [comment]
> When I run `pyrevit attach master 2710 --installed --allusers` in cmd, it says this:
> 
> _Error: Access to the path 'C:\ProgramData\Autodesk\Revit\Addins\2017\pyRevit.addin' is denied._

Try running `pyrevit attach master 2710 --installed` without the allusers flag. It seems you don't have Admin rights on that machine.
If you can get admin rights, run the original command within a command prompt with admin privileges

**Comment by zahowser** [comment]
> > When I run `pyrevit attach master 2710 --installed --allusers` in cmd, it says this:
> > _Error: Access to the path 'C:\ProgramData\Autodesk\Revit\Addins\2017\pyRevit.addin' is denied._
> 
> Try running `pyrevit attach master 2710 --installed` without the allusers flag. It seems you don't have Admin rights on that machine. If you can get admin rights, run the original command within a command prompt with admin privileges

I ran the first command.
Opened Revit.
The error screen came up, which is progress.
https://imgur.com/a/LYVkrs9

I closed Revit.
I opened Revit.
The error screen came up, with a different error screen.
https://imgur.com/a/V0n8pLC

**Comment by zahowser** [comment]
Although I did not see them resolve it, my office's IT third-party IT consultant resolved the issue.
It did have something to do with Local Admin Rights.
Thank you all for the comments/feedback.
