### ISSUE TITLE
Unable to load other extension onto toolbal

### ISSUE THREAD

**Issue by Kuladeep561** [eirannejad/pyRevit#1626]
Hi everyone,

_Desclimer: I am not an expert in programming development. Learning now to be a one._

I have been developing some small scale dynamo script. Since Dynamo isn't flexible, I decided to take help from other programming languages. Since I prefer Python over C#, in the process, I came across this awesome software called "PyRevit". 

So, I followed the tutorials (https://www.youtube.com/watch?v=JkNMGk_aXsg&t=8s) to create my own toolbar. I tried adding the directory to PyRevit settings (as mentioned in the video), but it didn't show up. My first thought was that I made some mistakes. However, when I installed the tool (https://github.com/aussieBIMguru/pyRoovit) on my machine, it still does not appear in the revit2023 toolbar, whereas it appeared on the tutor's laptop.

### Source and credits: 
Tool: https://github.com/aussieBIMguru/pyRoovit
below you can find the settings:
![image](https://user-images.githubusercontent.com/84839368/191927574-b19f458e-500a-443a-9886-0cdfd4e8adab.png)

### Expected outcome:
![image](https://user-images.githubusercontent.com/84839368/191927813-548ff45d-a31d-48cd-a3ba-7e873b6d1881.png)

### System info:
Win 11, 64 bit
screenshot is from Revit 2023 student licence. Although I tried in my company laptop also still not working.
Pyrevit version:  latest

**Why I am not able to see the extension my toolbar. Should I have to change any settings?**

**Comment by jmcouffin** [comment]
what is in your roaming folder?

**Comment by Kuladeep561** [comment]
> what is in your roaming folder?

When I run the command i.e `pyrevit extend ui pyRoovit https://github.com/aussieBIMguru/pyRoovit.git --dest="C:\thePathWhereYouWantItInstalled" --branch=main` from `Readme.md` from the extension folder, I assume that the command may have automatically added the extension directory i.e `\pyRoovit.extension` to the settings menu.  Even so, it wasn't of any use.  Therefore, I added the entire directory, i.e. the `\roaming ` folder.

Later, I removed it and it still didn't work.

**Comment by jmcouffin** [comment]
Did you change this section of the command?
dest="C:\thePathWhereYouWantItInstalled"
This is the path where the folder 9f the extension is being cloned

Le ven. 23 sept. 2022, 14:25, Kuladeep561 ***@***.***> a
écrit :

**Comment by Kuladeep561** [comment]
> Did you change this section of the command? dest="C:\thePathWhereYouWantItInstalled" This is the path where the folder 9f the extension is being cloned Le ven. 23 sept. 2022, 14:25, Kuladeep561 ***@***.***> a écrit :

### Yes, I did change the path
This is the exact command line I have used `pyrevit extend ui pyRoovit https://github.com/aussieBIMguru/pyRoovit.git --dest="C:\Users\kulad\AppData\Roaming" --branch=main`

**Comment by jmcouffin** [comment]
please check if fixed and close

**Comment by Kuladeep561** [comment]
> 

Thank you so much @jmcouffin  for your prompt response and resolution. I have been struggling with it for a couple of weeks. 

_also thanks to @eirannejad for an awesome tool._

### I am closing the post now!!
