### ISSUE TITLE
Plug in installed on my machine but then doesn't appear in the Revit 2022 tab

### ISSUE THREAD

**Issue by beth489** [eirannejad/pyRevit#1627]
The Plug in installed on my machine fine but when I open Revit it then doesn't appear in the Revit 2022 tab as a plug in

Please can you clearly set out the steps we need to go through to get this plug in to appear within Revit so we can use it?

Many thanks

**Comment by jmcouffin** [comment]
try this
https://www.notion.so/pyRevit-Is-Installed-But-Does-Not-Load-f6495adb56254e9e8021f8a68e3b2ab7

**Comment by jmcouffin** [comment]
Since no further comment was sent i am closing the issue
