### ISSUE TITLE
Question: Usage Logging

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#163]
Hi Ehsan! Is there anything still in place to log script usage of users a file (ie: to a network)

**Comment by eirannejad** [comment]
Not really. I think I need to implement this again. Let me know if you have any suggestions on how it should work. I'd rather not write to a network location since it could slow things down

**Comment by gtalarico** [comment]
Some ideas... 

1. pyRevit Settings: A Log Usage toggle, defaults to false. If True user is asked for a folder path in which usage will be saved. If a log already exists at that location new uses will be "appended"
2. scripts: optional, a __logusage_ flag, defaults to False, let's script turn off usage logging.

3. Usage log storing this is the tougher one, for centralized logging. Here are some thoughts, keeping in mind I am focusing on my personal use case, which is a centralized usage logging for an office.
- Could externalcmd spin a thread at end of command independ of the main revit to append a line to file, assuming the file is on a network folder location and might have some latency?
- Usage can be dumped into a local file, and at startup, that usage is collected and appended to a network file if it's accessible, and the "buffer" local log file is emptied.
-Alternative: At startup local usage is collected and during startup dumped on a service, for example Airtable
In any case, a local buffer file + deferred central log strategy might be needed if you are concerned about latency.
To honest, I currently have a modified pyLoader.dll that writes to a network location, and I have not noticed any latency, but that could depend on network speeds.

**Comment by hdm-dt-fb** [comment]
If there was a way to redirect the logging to a different directory (if it isn't there already and I just missed it) we would appreciate it. For now we turned logs off over here, if I remember correctly they would by default write to AppData/Roaming, which is very restricted(tiny quota) in our environment. AppData/Local (or any other non-ActiveDirectory) would be ideal for us. 
I agree @gtalarico, pushing it/updates to a central network drive would be great for many purposes. 
The one that comes to my mind first is: Create more visibility how much time our teams save with these awesome pyRevit tools (probably a [bokeh](http://bokeh.pydata.org/en/latest/) graph in our case).

**Comment by eirannejad** [comment]
Okay. I think I have a plan for this.

- I'll add a section in the pyRevit settings for usage data collection. The user can activate/deactivate and set a file location (network or local) for the logs or provide information for a potential log daemon (ip and port)
- pyRevit will set the logger information on the compiled executor functions for each tool
- After each use, the executor will write usages info and results (successful or exception) to the log file or the logging daemon on an asynchronous call so it can return to Revit as quickly as possible.

How does this sound?

@McCulloughRT This might interest you as well.

**Comment by hdm-dt-fb** [comment]
sound great to me!! 👍 
(rvt3js seems pretty cool - thx for the link!)

**Comment by eirannejad** [comment]
Okay. I need to do a bit more work and usage log system will be complete. Here is a sneak peek of log data:

**Remote Usage Log**
User specified the usage log server url in pyRevit settings.
This is implemented and tested. I need to add url option to settings.
JSON data POSTed to http log server:
```json
{"date":"2017/03/21",
"time":"16:33:18:1140",
"username":"eirannejad",
"revit":"2017",
"revitbuild":"20160720_1515(x64)",
"pyrevit":"4.2:1cc603d",
"debug":"False",
"alternate":"False",
"name":"Settings",
"result":"0",
"source":"C:\\Users\\eirannejad\\AppData\\Roaming\\pyRevit\\pyRevit-v4\\pyRevit\\extensions\\pyRevitCore.extension\\pyRevit.tab\\pyRevit.panel\\Settings.pushbutton\\script.py"}
```
Result codes currently are:
``` csharp
public static class ExecutionErrorCodes
{
    public static int Succeeded = 0;
    public static int SysExited = 1;
    public static int ExecutionException = 2;
    public static int CompileException = 3;
    public static int UnknownException = 9;
}
```

**Local Log**
Similar data gets logged to local usage log file. I'm working on this.

Let me know of your thoughts

**Comment by hdm-dt-fb** [comment]
Looks awesome!! 
If I had a wish, I would love to have a field where I could optionally pass the amount of modified elements to (in case that is actually feasible from the *_script.py file with some variable), so this information could easily feed into a rough approximation how much time was saved and ultimately lead into some positive advertisement for pyRevit.

Example: 
I did a small script to check if doors are opening left or right (so like the standard configuration in the Family Symbol as the door was drawn, or the opposite, when the door instance got Mirrored [I want to feed that one back into pyRevit once I generalized it] ). So in this example it could be assumed, how much time a manual check for a single door by a user would take, and "compared" against how rapidly the script sets the data correctly instead.

What are your thoughts on this?

**Comment by eirannejad** [comment]
So I logged pyRevit usage under version 3 for almost 1.5 years and calculated the amount of time saved. Honestly I think each script should calculate the time saved value based on the model conditions and generally the task that they deal with.

What if I include a standard parameter (e.g. `__time_saved__`) that is accessible inside scripts and the scripts can set it at their completion (e.g. `__time_saved__ = '0:3:30' `), and the usage logger will include this value in the report. This way we'd potentially have a much more accurate time-saved value that has been calculated by the script itself that knows everything about the task.

Now that I'm thinking about this, I can make a that a class that has parameters like `time_saved`, `elements_modified`, `elements_created`, `elements_deleted`, etc. Then these information will be passed to the usage logger.

@gtalarico @hdm-dt-fb 
Thoughts?

**Comment by hdm-dt-fb** [comment]
Hah - that sounds way better!! 
This way we could add a __manual_task_time__ variable to our scripts and have it calculated at script completion.. very very nice!!

**Comment by eirannejad** [comment]
Exactly. Okay so I'll implement this then. I'll post details soon.

**Comment by eirannejad** [comment]
Okay here is the implementation detail:
`this_script` object now has a `results` property. This property is extremely flexible, meaning you can add any custom property you want to it (and as many) and it would include all these properties in the usage log.

For example:
`this_script.results.time_saved = '0:03:45'`

In this example, `time_saved` is not a property that I have defined in pyRevit. It is something that you as the script makers can assign a value to and then later read in your usage log files.

So my company might use:
`this_script.results.manual_time_saved = '0:03:45'`

while your company can use:
`this_script.results.time_saved = '0:03:45'`

For my company the usage log JSON data will include `manual_time_saved` with the value and for yours it would include `time_saved`...

You can also add other properties to this result object and add other values to it.

This system would make the usage log data very extensible.

**Comment by gtalarico** [comment]
sounds like a great idea.
@eirannejad shouldn't be hard. I do all my server stuff in flask, and I am not sure if it works in Iron, but we could always fall back to something lower like a Simple HTTP + Socket Server.
Are you thinking of a service running in the background, or 
a web-hosted server ?

**Comment by gtalarico** [comment]
Independent server would work, but takes more effort/resources to have it +
keep it running. But that could be step 1.
Step 2: We could have a centralized server, with user accounts, running on
a free heroku app.

With a simple API, it could collect logs for that user, and then either 1.
visualize with cool D3 charts, 2:  spit out a full jsons with historic
usage that can be consumed by something like power bi

**Comment by eirannejad** [comment]
@gtalarico 
Huh. Didn't know about Heroku. Can you share more details on how the setup would work?

**Comment by gtalarico** [comment]
1. Create a simple flask/django website on a free tier of heroku. Theses are fast enough, only down side is they sleep when idle. To prevent that, you can upgrade to a $7/ month basic server
2.: The same server running the website, would have an api end-point to receive the logs.
3. User logs in to `pyrevit-logger.com`, creates an account, and gets a TOKEN
3. user adds TOKEN token to pyrevit settings
4. pyRevit can gather logs locally, and at start up or when idle, 
makes a post request to something like `pyrevit-logger.com/api/logs/add` . The token is sent in the header along with the usage
5. The server receives usage as a json payload, and associates that to a user using the provided TOKEN
6. User is able to login and see all the usage that has been uploaded

Pretty simple, no!? :)

**Comment by eirannejad** [comment]
It's awesome. Okay. Is this simple to setup for you on a free tier so we can start testing later?

I'm done with the changes but need some general testing. I'm pushing this update end of next week since it includes a core IronPython update to 2.7.7 and I need everyone to upgrade their pyRevit's to the latest version so the new upgrader can handle the core update. Otherwise they need to reinstall.

**Comment by eirannejad** [comment]
Logging (file, server) is implemented and fully functional.
I'll test this during the course of next week and monitor for performance.
@gtalarico : I setup an account with Heroku to see how much I can get done. I know you're very busy so I don't want to add to your stress, but any help is appreciated.

**Comment by eirannejad** [comment]
Added tool for viewing local usage record files

![2017-03-28 15_34_37-pyrevit usage records viewer](https://cloud.githubusercontent.com/assets/8197916/24430639/6fb8a884-13cc-11e7-9dbc-5d7511656214.png)

**Comment by eirannejad** [comment]
@gtalarico Gui, I'm at loss. It's gonna take me so much time to figure out how to make a proper web app for heroku! I'm gonna close this issue for now as the core usage logging system is working really well. Basically the only remaining component is a web app that can collect the data, but I'll leave that to whoever wants to use the remote logging.

**Comment by gtalarico** [comment]
that sounds good.
I have added that to my open source back log, we can look at it at a later time
