### ISSUE TITLE
added pyRevitTags and doesn't work

### ISSUE THREAD

**Issue by studioearl** [eirannejad/pyRevit#1632]
**Describe the bug**
![image](https://user-images.githubusercontent.com/114871080/193462969-e5cc0684-4230-4938-94be-9f4509778048.png)

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/114871080/193462980-9d0ab947-6b49-4278-b7d0-ff451fae8311.png)
**Desktop (please complete the following information):**
 - 
![image](https://user-images.githubusercontent.com/114871080/193463095-b067d6a8-334b-4bc1-869b-12a2e9426860.png)

 - pyRevit Version 
 - 
![image](https://user-images.githubusercontent.com/114871080/193463026-9452dc5d-93dd-4aa7-a4a7-bc523e26a568.png)

 - pyRevit Environment: Open a command prompt and run the command below. 
C:\Users\Earl>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.8" | Path: "C:\Users\Earl\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\Earl\AppData\Roaming\pyRevit-Master"
master | Product: "2019.2.3" | Engine: IPY277 (277) | Path: "C:\Users\Earl\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Earl\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.0.20.21 | Build: 20220726_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2019.2.3 | Version: 19.2.30.41 | Build: 20210416_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
`pyrevit env`

**Additional context**

**Comment by jmcouffin** [comment]
related https://github.com/eirannejad/pyRevit/issues/1364

**Comment by jmcouffin** [comment]
fixed already
uninstall previous version and try the latest installer https://github.com/eirannejad/pyRevit/actions/runs/3175784126
Please close the issue if fixed

**Comment by studioearl** [comment]
I uninstalled and reinstalled, now whenever selecting any tag icon I get 
![image](https://user-images.githubusercontent.com/114871080/193955040-e57aa60b-51a6-450b-ba15-53f414825b2d.png)
 Io can't seem to find the Tag settings button. 

C:\Users\Earl>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\Earl\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\Earl\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\Earl\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Earl\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.0.20.21 | Build: 20220726_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2019.2.3 | Version: 19.2.30.41 | Build: 20210416_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages

**Comment by studioearl** [comment]
Thanks much. You all rock
