### ISSUE TITLE
Preflight Checks: Chart is undefined

### ISSUE THREAD

**Issue by bkman108** [eirannejad/pyRevit#1635]
**Describe the bug**
When clicking the Preflight Checks tool, a Script error pops up for Line 1 Char 78 indicating that 'Chart' is undefined.

**To Reproduce**
1. Go to the pyRevit tab then the Project palate
2. Click on the Preflight Checks tool
3. Select Model Checker
4. See Script error 
5. Click Yes to run report

**Expected behavior**
The model checker starts with out a pop up error

**Screenshots**
![2022-10-05 11_55_04-Window](https://user-images.githubusercontent.com/58609823/194116825-79fbbae5-1389-40c4-ae49-19ddf2b4e212.png)

**Desktop (please complete the following information):**
 - OS: [Window 10]
 - Revit Version 2021.1.7
 - pyRevit Version [4.8.12.22247]
 - pyRevit Environment: 
 ```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "%AppData%\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2021" | Engine: IPY277 (277) | Path: "%AppData%\pyRevit-Master"
master | Product: "2018.3.3 Security Fix" | Engine: IPY277 (277) | Path: "%AppData%\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\hmorales\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2021 | Version: 21.1.70.21 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

**Additional context**
I am able to continue running the script but I am unsure what the error caused in the report.

**Comment by jmcouffin** [comment]
Related https://github.com/eirannejad/pyRevit/issues/1176

**Comment by eirannejad** [comment]
Same as https://github.com/eirannejad/pyRevit/issues/1176
Closing this. Please track 1176
