### ISSUE TITLE
View Template /filter reports

### ISSUE THREAD

**Issue by studioearl** [eirannejad/pyRevit#1636]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Desire a tool (maybe added functionality to Find Used View Templates Filters. Is there anything that allows to get the same report but with what filter overrides are used in the template (like transparency, line  weight, line style, etc.)? Please point me in the direction of anything that does this or please add the feature if possible.  

**Describe alternatives you've considered**
I've looked online for plugins that accomplish this and scoured PyRevit's different tools to no avail yet, however, there are so many that it's hard to know if I missed it. 

**Additional context**

Thanks for your consideration, Earl

**Comment by jmcouffin** [comment]
@studioearl 
Erik Fritz did a video about it on its yt channel
He also has the kind of tools your are looking for 
https://github.com/ErikFrits/EF-Tools/tree/main/EF_Tools.tab/Views.panel/Column2.stack/ViewFilters.pulldown/ViewFiltersLegend.pushbutton
It's ef-tools extension is listed in the default extensions of the latest pyRevit release. You just have to install it from the extension window of pyrevit.

Instructions here https://github.com/ErikFrits/EF-Tools

You may also want to check the pychilizer extension from the archilizer team
