### ISSUE TITLE
2 security vendors and no sandboxes flagged this file as malicious

### ISSUE THREAD

**Issue by IvoLafeber** [eirannejad/pyRevit#1638]
I've scanned the file pyRevit_4.8.12.122247_signed with https://www.virustotal.com.   (07-oct-2022)

google and ikarus flagged the file als malicious.

**Comment by swannsonite** [comment]
Checked previous versions and they did not flag.
https://www.virustotal.com/gui/file/ada638ced8500848ab7c5b2769789c3c57ba079780b7516151c84897c9afc21f
https://www.virustotal.com/gui/file/84d6f271638445f8c949aaf6f07ff902e3d44242441ee427cb34573531daba3a

Google
Detected

Ikarus
Trojan-PSW.Agent

Yandex
Trojan.GenAsa!rN39O70SAog

**Comment by eirannejad** [comment]
Interesting. The installers are being built on isolated Github task runners. Are we positive the `.exe` files are not picking up viruses on your machines?

Using the direct download urls from github, I don't see the installer being flagged:
https://www.virustotal.com/gui/url/bcbea96fee544f7e9212e10448fe289b4f1eca9b50ef638062fe4defe10e09fb
https://www.virustotal.com/gui/url/33fe7c0290ca2a3683c4c9ac18437d4b8f81608709dba97fb6ac2c1c88d670ae
