### ISSUE TITLE
More color in Tab Coloring. 

### ISSUE THREAD

**Issue by studioearl** [eirannejad/pyRevit#1639]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
More color in Tab Coloring. Currently kind of harder to see.  See Prlx Apps- Tabbed Views + ( https://www.youtube.com/watch?v=2Pz-i-XHEAY ). Thanks again for all you do. 

**Describe alternatives you've considered**
Paying for/using Prlx's Tabbed View Plus. However only available in 2019 and earlier versions of Revit. Also, I would love to have fewer add-ins and I use PyRevit for so much. 

**Additional context**

**Comment by alexdaversa** [comment]
Have you edited the tab coloring options in pyRevit settings? Please be specific in what type of modification or options you would propose that are currently not available in the settings.
![tab color settings](https://user-images.githubusercontent.com/44062587/197210762-09698d15-9227-4e7e-a840-0271cd49ce3f.PNG)

**Comment by studioearl** [comment]
I haven't tried that yet, wasn't aware there were settings. I was as specific as I knew how to be. I'll check those out soon. Thanks

**Comment by studioearl** [comment]
OH MY I had a chance to try out the settings, this is amazing!.
