### ISSUE TITLE
Error on latest install: startuplogtimeout on config file

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#164]
![image](https://cloud.githubusercontent.com/assets/9513968/23715995/9a036c6c-03fc-11e7-9fad-21dd2e0caae8.png)

**Comment by eirannejad** [comment]
Upgrader added to startup tasks
https://github.com/eirannejad/pyRevit/commit/4026d7f450510dd325fe1a4281997f28abc07764

**Comment by eirannejad** [comment]
Fixed
