### ISSUE TITLE
Order Views missing ( or moved?)

### ISSUE THREAD

**Issue by studioearl** [eirannejad/pyRevit#1641]
**Describe the bug**
I can't find Order Views (used to be under sheets arrow, I believe). The tool that after started allowed one to click on viewports (on sheets) in order (starting with 1) and you'd hit esc after done and all viewports would be renumbered from one up. It was awesome and quick. has this been moved to renumber? I think I found it there. If so, it has added a couple steps, but could work. 

**Desktop (please complete the following information):**
 - OS: Win 10
 -  pyRevit Version [e.g. 22]
 - pyRevit Environment: 
 -==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\Earl\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\Earl\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\Earl\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Earl\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.0.20.21 | Build: 20220726_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2019.2.3 | Version: 19.2.30.41 | Build: 20210416_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages

**Additional context**

**Comment by jmcouffin** [comment]
@studioearl 
Still at the same spot last time I checked
https://github.com/eirannejad/pyRevit/tree/master/extensions/pyRevitTools.extension/pyRevit.tab/Drawing%20Set.panel/Sheets.pulldown/ReOrder%20Sheets.pushbutton
Drawing set - sheets pulldown - reorder sheets

**Comment by jmcouffin** [comment]
checked this morning on 4.12 
![image](https://user-images.githubusercontent.com/7872003/195033067-890bb4b1-73d6-40c6-9764-b628da94bda3.png)

**Comment by studioearl** [comment]
Not reorder sheets, but order views. See list below. I used to have a
shortcut in [ ]. Shortcut gone in keyboard shortcut and not in PyRevit (see
your screen shot). Also, although it takes a couple more clicks, it still
rocks, may be better under renumber. Thanks for being responsive. Earl

Here's the list I had for reference:
SHEETS

   1.
      1.

      Copy Viewports (Legends) To Other Sheets
      2.

      Move Viewports (Model, Detail) To Other Sheets
      3.

      Pin All Viewports
      4.

      Reorder Selected Viewports  (Front Vs Back)
      5.

      Copy Sheets To Open Documents
      6.

      Batch Sheet Maker
      7.

      Select Sheets (N The Properties; Not The Project Browser)
      8.

      Rename Selected Views
      9.

      List/Select Titleblocks On Sheets
      10.

      Set Crop Region To Selected Shape
      11.

      Open Selected View Ports
      12.

      Order View [OVIEW] - renumbers views on a sheet by selecting in order
      to complete select all views or hit esc after done moved to #
      reNumber
      13.

      Reorder Sheets
      14.

      Rename Pdf Sheets
      15.

      Decrement Selected Sheets
      16.

      Increment Selected Sheets


--
Earl Schrader
***@***.***
515-203-1628

**Comment by jmcouffin** [comment]
I don't get it. Sorry.
you mention a screenshot

you can try to find it going back in time in github with the <> symbol next to a file or folder

**Comment by alexdaversa** [comment]
It was moved to the Renumber tool under Modify

**Comment by alexdaversa** [comment]
It's now under the renumber tool when used on a sheet.

**Comment by bccarlso** [comment]
> It's now under the renumber tool when used on a sheet.

Thank you for pointing this out! I also thought it had been removed, but used it frequently.

**Comment by studioearl** [comment]
> > It's now under the renumber tool when used on a sheet.
> 
> Thank you for pointing this out! I also thought it had been removed, but used it frequently.

I know I was scared, glad it helped.
