### ISSUE TITLE
Traceback (most recent call last) error on fresh PyRevit install

### ISSUE THREAD

**Issue by Amnesiaest** [eirannejad/pyRevit#1643]
Hi!

I keep getting a traceback error when trying to get PyRevit working. The installer versions I used were "pyRevit_4.8.10.22040" and "pyRevit_4.8.12.22247" both give me the same errors. Tried restarting my computer and uninstalling then reinstalling Pyrevit but still get the same messages. Any tips?
Thanks in advance.

Here are screenshots of the error messages.
![err1](https://user-images.githubusercontent.com/115700179/195567541-a8b9e1f0-bdb0-469a-b0d2-2b0821ff5ae1.jpg)
![err2](https://user-images.githubusercontent.com/115700179/195566760-6368beff-99b0-46f7-8954-4347b843dc35.jpg)

**Comment by anitopi11x** [comment]
Same here for 2023

**Comment by Amnesiaest** [comment]
Hello again

I fixed the issue by navigating to "C:\ProgramData\Autodesk\Revit\Addins\2022" and renaming PyRevit.dll to 0PyRevit.dll

This case can now be closed.
