### ISSUE TITLE
Table view in locked database pages don't prevent the edition of individual pages' names

### ISSUE THREAD

**Issue by Kaldrin** [eirannejad/pyRevit#1644]
If you create a database page, set it to table view, and lock it, you can still edit the names of the pages referenced in the table just by clicking on them, which is odd, it's super easy to edit them by mistake which the lock feature should prevent.

`pyrevit attach master 277 --installed`

**To Reproduce**
1. Create a database page (Not inline)
2. Add a few pages to it
3. Set it to table view
4. Now you can edit the names of the references pages directly by clicking on their names in the table, it's convenient
5. Now lock the table view
6. You can still edit their names instead of just opening the pages

**Expected behavior**
We should not be able to edit names of pages referenced in a table view in this table view is locked

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/38406118/196929268-e9c8ab1e-ba4f-4cc9-9a4d-5894ebbedace.jpg)

`pyrevit env`

**Additional context**
Bug appears on Google Chrome, no idea if it appears elsewhere.

**Comment by jmcouffin** [comment]
This is an issue for the notion team, not the pyRevit repository
