### ISSUE TITLE
Cannot add custom extension

### ISSUE THREAD

**Issue by huytuong010101** [eirannejad/pyRevit#1647]
**Describe the bug**
I am following [this](https://www.notion.so/Create-Your-First-Command-2509b43e28bd498fba937f5c1be7f485) instruction but when I add the Directory and Click Reload, nothing appear

**Expected behavior**
- Revit add new extension

**Screenshots**
![image](https://user-images.githubusercontent.com/53045632/197716166-4b1a04b8-c4cd-4d52-9ca4-5c5b85270c7e.png)
![image](https://user-images.githubusercontent.com/53045632/197716366-07fc2501-cd9d-490d-8d2d-3702d4b0b148.png)

**Desktop (please complete the following information):**
 - OS: Window 10
 - pyRevit Version 4.8.12
 - pyRevit Environment: 
```
pyrevit v4.8.12.22247+0031
Missing authorization token. Set on GITHUBTOKEN env var
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\Administrator\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2021 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Users\Administrator\AppData\Roaming\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Administrator\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
==> Running Revit Instances
PID: 10712 | 2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2021"
==> User Environment
Microsoft Windows 10 [Version 10.0.19042]
Executing User: DESKTOP-0E07QF6\Administrator
Active User: DESKTOP-0E07QF6\Administrator
Admin Access: Yes
%APPDATA%: "C:\Users\Administrator\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.12.22247+0031
```

**Comment by jmcouffin** [comment]
Hi @huytuong010101, 
You may want to show your full extension path because I think your are pointing either 1 level to high or to low for the extension path
Have you tried pointing to the `\MyExtensions` folder?
you filepath for the extension path location should be the folder containing the .extension folder

**Comment by huytuong010101** [comment]
> 

 yess, the Filepath is the folder containing the .extension folder, but it still not work :(((

**Comment by eirannejad** [comment]
Would you mind sharing a screenshot of Settings window that shows the "Custom User Extension" list?
