### ISSUE TITLE
PyRevitLoader - Error Loading pyRevit

### ISSUE THREAD

**Issue by titanic-bagpipe** [eirannejad/pyRevit#1649]
**Describe the bug**
I have installed the latest pyRevit version and am receibing an error dialogue when I open Revit  each time, and pyRevit does not load. I have also tried using the command below that is suggested and this does not fix the problem.

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

**To Reproduce**

**Expected behavior**
I expected when i open Revit that pyRevit will load and I would be able to use it.

**Screenshots**
![image](https://user-images.githubusercontent.com/117099938/199043997-6eb331cd-7162-4837-8f63-50f53d0ef072.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - pyRevit Version [pyRevit 4.8.12.22247 Installer](https://github.com/eirannejad/pyRevit/releases/download/v4.8.12.22247%2B0031/pyRevit_4.8.12.22247_signed.exe)
 - pyRevit Environment: "C:\Users\jeff>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\jeff\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\jeff\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2021" | Engine: IPY277 (277) | Path: "C:\Users\jeff\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2020" | Engine: IPY277 (277) | Path: "C:\Users\jeff\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\jeff\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.0.11.19 | Build: 20220503_1030(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2021 | Version: 21.1.70.21 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
Autodesk Revit 2020 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages"

**Additional context**
My apologies if I have not done this correctly. I am new to this.

![Screenshot 2022-10-31 093839](https://user-images.githubusercontent.com/117099938/199048272-7f80e7ce-697e-4a1a-86c1-6db2824f72fe.png)

**Comment by rcurtis12** [comment]
Prevously pRevit was working okay. Working with our IT dept, I Reloaded pyRevit  and other programs after serious Windows user folder deletions. Installed newest ver. of pyRevit and received error messages almost same to this one (1649), (sim. 1451) on both Revit 2022 and Revit 2023.
Uninstalled pR & removed folders, installed  4.8.10 with same errors.
Uninstalled & reinstalled Revit 2022 with same errors. Reinstalled pR 4.8.12 with same errors. Please see below.

![pyRevit 1649Amain load error](https://user-images.githubusercontent.com/121730671/210152864-3a15cfef-9292-42cd-ac75-cfaa0ec4864f.png)

Ran suggested commands (attached, & env --debug)  with same results as above.

It does appear to be attached to Revit programs, but does not load.
c:\>pyrevit attached
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master"
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master"

Also note,
...
Debug: Checking pyRevit path "C:\Program Files\pyRevit-Master\bin\engines\IPY277\pyrevitlib\pyrevit"
Debug: Invalid pyRevit clone. | Path "C:\Program Files\pyRevit-Master\bin\engines\IPY277" is not a valid git pyRevit clone.
...
Autodesk Revit 2023 | Version: 23.1.10.4 | Build: 20221122_1550(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19044]
Executing User: PCHNET\rcurtis
Active User: PCHNET\rcurtis
Admin Access: No
%APPDATA%: "C:\Users\rcurtis\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.12.22247+0031

Please note, pRevit 4.8.12 works okay with Revit 2022.0.2 on another computer, will upgrade and check with 2022.1
Please advise, would really like to use these productivity tools at Architectural firm.

**Comment by kraftwerk15** [comment]
For a user, a similar NullReferenceException displayed after installing the latest build fresh to their user profile. I installed two versions, first the user profile version. When this did not function correctly, I uninstalled and deleted pyRevit folders in the appdata folder and then installed the admin version. Both versions will display this error message only to this user. After installing the Admin version and another person logs on to the same machine, the other person in their user profile can use pyRevit. Only the original user cannot use pyRevit.

![image](https://user-images.githubusercontent.com/30668448/213184891-e918446a-99a1-4ae6-901b-3cf5a574d8ac.png)

**Comment by rcurtis12** [comment]
Thank you for the insight, sorry for delayed response. Myself and our IT did the same thing few times uninstalling & removing additional folders and re-installing as admin with the same negative result, 
(I also unattached a newer Revit and same result.)

I wondered if it was an issue with a few of our Revit add-ins "Object reference not set to an instance of an object."
(see portion of printout from cd:\pyrevit env --debug)
.  .  .
Debug: Normalizing "C:\Program Files\Autodesk\eTransmit for Revit 2022\eTransmitForRevit.dll"
Debug: Normalized as "C:\Program Files\Autodesk\eTransmit for Revit 2022\eTransmitForRevit.dll"
Debug: Reading Revit "2022" manifest file "C:\ProgramData\Autodesk\Revit\Addins\2022\Autodesk.Revit.GenerativeDesign.addin"
Debug: Normalizing "GenerativeDesign\Autodesk.Revit.GenerativeDesign.Application.dll"
Debug: Path is not local. Skipping normalization "GenerativeDesign\Autodesk.Revit.GenerativeDesign.Application.dll"
Debug: Not pyRevit "2022" manifest file "C:\ProgramData\Autodesk\Revit\Addins\2022\Autodesk.Revit.GenerativeDesign.addin" | Object reference not set to an instance of an object.
.  .  .
Debug: Normalized as "C:\Program Files\Autodesk\Worksharing Monitor for Revit 2022\Autodesk.WorksharingMonitor.Application.dll"
Debug: Not pyRevit "2022" manifest file "C:\ProgramData\Autodesk\Revit\Addins\2022\Autodesk.WorksharingMonitor.Application.addin" | Object reference not set to an instance of an object.

I also included portion of referenced code:
pyRevit Loader.py, line 33:

sessionmgr.load_session()

sessionmgr.py, line 276:

    if EXEC_PARAMS.first_load:
        output_window = _setup_output()
    else:
        from pyrevit import script
        output_window = script.get_output()

sessionmgr.py, line 66 (64-83):
def _setup_output():
    # create output window and assign handle
    out_window = runtime.types.ScriptConsole()
    runtime_info = sessioninfo.get_runtime_info()
    out_window.AppVersion = '{}:{}:{}'.format(
        runtime_info.pyrevit_version,
        int(runtime_info.engine_version),
        runtime_info.host_version
        )

Thanks.
