### ISSUE TITLE
Error on loading first session

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#165]
![image](https://cloud.githubusercontent.com/assets/9513968/23716036/b9b0472e-03fc-11e7-972e-0b3e2aaa4354.png)

**Comment by eirannejad** [comment]
Did you update through pyRevit? pyRevit has an upgrade function that adds the new parameters to the config file. Check the config file and see if the parameter is there. See the commits below:

https://github.com/eirannejad/pyRevit/commit/cc1a65b8d03e92e7e48a33fd9d14bad570c2a48d

https://github.com/eirannejad/pyRevit/commit/cf3da92a94ab8ffb0b48412cc8cc54fb75a3dd03

**Comment by eirannejad** [comment]
Upgrader added to startup tasks
https://github.com/eirannejad/pyRevit/commit/4026d7f450510dd325fe1a4281997f28abc07764

**Comment by gtalarico** [comment]
This was a fresh install, first time running

**Comment by eirannejad** [comment]
Fresh install tested. Error corrected
