### ISSUE TITLE
Telemetry Server error with authentication

### ISSUE THREAD

**Issue by dvdgnz** [eirannejad/pyRevit#1651]
I have been using the Telemetry Server on a linux server with the server compiled from the Go source with no problems for over a year.

Today, I tried adding authentication to the mongoDB, and created user for the api server to connect to the running instance of the database.

After adding the user and password to the connection string for the REST server, any client request to POST a new command execution generates the following error:
`Nov 01 19:04:35 telemetry serverstart.sh[854]: [ server returned error on SASL authentication step: BSON field 'saslContinue.mechanism' is an unknown field. ] 2022-11-01T19:04:35.0359Z "DG_Odeh" 20220111_1110(x64):2711 (ironpython) [pyRevitCore.Settings] code=0 info=map[]`

After some Googling I found this page, which seems to suggest that the package being used by the server is outdated, since I am indeed running MongoDB 5.0.13:
https://www.mongodb.com/community/forums/t/error-connecting-to-db-server-returned-error-on-sasl-authentication-step-bson-field-saslcontinue-mechanism-is-an-unknown-field/163435

How difficult would it be to upgrade to a new driver for the database? Unfortunately I am not experienced with Go or I would take this on myself.

**Comment by dvdgnz** [comment]
I have spent some time figuring out enough Go to have a working version that uses the new Mongo driver.
I had to change the structure of the Go code to use modules to make it compile under my environment, so I don't want to make a PR if this would cause other problems, or change the way the source needs to be compiled.
@eirannejad if you want I can share what I have with you and let you choose how to move forward

**Comment by eirannejad** [comment]
@dvdgnz Yes please! A PR would be much appreciated. I usually pull into a review branch, make some changes and merge into develop to be released on next release.

**Comment by saurabhsjha** [comment]
![image](https://user-images.githubusercontent.com/16698814/228951071-a77e768a-7052-41a8-a1bd-0525673a2dde.png)
Is it the same problem or i am missing something else
