### ISSUE TITLE
Remove All Unsheeted Views Does not work in Revit 2023

### ISSUE THREAD

**Issue by sharkmullet** [eirannejad/pyRevit#1653]
**Describe the bug**
In 2023 we can now see if a view is sheeted on unsheeted. To remove all unsheeted views, we can do this in the project browser manually taking time. The Wipe command does not appear to work. After running it, Unsheeted drafting views remain in the project browser.

**To Reproduce**
Go to: Wipe > Wipe Model Components > Remove All Unsheeted Views (Drafting Views Only)

**Expected behavior**
All unsheeted drafting views be deleted

**Desktop (please complete the following information):**
 - OS: Windows 11
 - pyRevit Version 4.8.12.22247+0031
 - pyRevit Environment:
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2022 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\PC\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.0.20.21 | Build: 20220726_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022 First Customer Ship | Version: 22.0.2.392 | Build: 20210224_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages

**Additional context**

**Comment by Rocinante74** [comment]
I was going to look into this to fix, but I can't replicate the error. Could you verify this is still not working? Maybe re-install pyRevit or update Revit?

I'm on:
OS: Windows 11
pyRevit Version 4.8.12.22247+0031
Revit version 23.1.10.4 Build 20221122_1550(x64)

**Comment by thumDer** [comment]
Are you sure that all of your Drafting Views were closed before running the command? It took me a while to realize, that this tool skips open views.
