### ISSUE TITLE
Feature Request:  Load Additional Family Types

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#166]
I am wondering if it's possible to have a command that would load more family types from server of a selected element.

**Comment by eirannejad** [comment]
Hum. Would you explaining the workflow a bit more? What's the use case?

**Comment by thazell** [comment]
Say you load a catalog based family into your project and only load one or two types or you load a family without a catalog and purge out the unused family types.  Later on in the project you need to get those family types reloaded into the project.  The current workflow is either a) go find the family and load it in again, or b) find it in the project browser, right click and use the "reload family" command.  As an engineer we use it all the time, even with a family management tool like BIM List or Family browser.  It would be nice to have a "reload more types" as a keyboard shortcut. Is this something you do in your office?

**Comment by eirannejad** [comment]
Hum. Interesting. So the tool will probably need it's own custom settings for the users to be able to add folder addresses for the families right?

**Comment by thazell** [comment]
I'm not exactly sure, but I think this property might store the load location of a family.
http://www.revitapidocs.com/2016/4fc97a8e-a29f-8cdf-b567-cc8e95139742.htm

**Comment by eirannejad** [comment]
Added. See `Project > Family > Load Family Types`

**Comment by thazell** [comment]
Just tested it and it works amazingly well.  Thank you.  I think this is a winner tool. Since we hadn't upgraded to pyrevit4.2 yet the internal tool update didn't work and a full reinstall was required.  Not a problem, just fyi.

**Comment by eirannejad** [comment]
I apologize for the limitations of internal update tool. I'm constantly trying to make it better. This weekend I'm pushing a few more updates that includes some modifications to the update tool to make it more reliable.

I'm grad you find the family load tool useful. Let me know if you see any shortcomings or want more changes.

**Comment by thazell** [comment]
Since you asked here are some first things I noticed.  Both very minor:
1. Sort Order 
W8 ends up at the very end of the list because 8 is larger than 1.  
https://www.youtube.com/watch?v=PjEdcOsUL3k

2.  Keyboard Filters
Also Revit 2017 introduced keyboard filtered searches.  Are those difficult to implement?  Example you type 8 and the list only shows types that have an 8 in them.  You type W8 and it filters to just W8s.
![image](https://cloud.githubusercontent.com/assets/14113080/24203188/6a0948de-0eeb-11e7-81df-5850e9a1fa61.png)

**Comment by eirannejad** [comment]
Yeap. I knew about the sorting but imagine this tool is going to be used on
all family types with different naming patterns so it's really hard to make
it smart about sorting. I guess I can start implementing some known
patterns into it. Would you mind adding github issue for both items?

Thanks a bunch for the feedback
