### ISSUE TITLE
Adding line break option in the keynote manager. 

### ISSUE THREAD

**Issue by Daria7855** [eirannejad/pyRevit#1662]
Keynote text can not be put in multiple lines, an example of the function is line breaks in excel when clicking "alt+enter". So we are hoping that instead of a continuous line when clicking "alt+enter"(or any other key) we could have a new row so that it is easier to list. I did not identify any work around for this cases,  if you are clicking space and have the long keynote text, it will not work. Do you think this is something to be solved? Or maybe there is another way to start a new row?

This is an example of the desired outcome:
![image](https://user-images.githubusercontent.com/117165979/203113465-00319942-f9c8-4b80-aef0-101482dd2059.png)

**Comment by jmcouffin** [comment]
@Daria7855 you might want to fix the title of the issue and fill in the content/description of the issue.

**Comment by eirannejad** [comment]
See https://github.com/eirannejad/pyRevit/issues/718
