### ISSUE TITLE
Revit crash 

### ISSUE THREAD

**Issue by Bjarkenyg** [eirannejad/pyRevit#1666]
Revit refuses to start after installing Pyrevit, i have tried older versions but with same result.
Furthermore i have tried the solution below but to no avail.

Can someone help me ?

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - pyRevit Version [e.g. 22]
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

**Additional context**

**Comment by jmcouffin** [comment]
Hi @Bjarkenyg 
- What does the `pyrevit env` command line return?
- Have you tried to fiw the registry with the command line `pyrevit doctor`?
- Have you tried uninstalling + deleting folder in %appdata%/pyRevit and %appdata%/pyRevit-Master and then install as new?

**Comment by Bjarkenyg** [comment]
pyrevit env :

C:\Users\bn>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\bn\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\bn\AppData\Roaming\pyRevit-Master"
master | Product: "2022 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Users\bn\AppData\Roaming\pyRevit-Master"
master | Product: "2020.2.1 (New Install)" | Engine: IPY277 (277) | Path: "C:\Users\bn\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\bn\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.0.11.19 | Build: 20220503_1030(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022 First Customer Ship | Version: 22.0.2.392 | Build: 20210224_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2020.2.1 (New Install) | Version: 20.2.12.1 | Build: 20200210_1400(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
Error: Adgang nægtet
Run with "--debug" option to see debug messages

Have you tried to fiw the registry with the command line pyrevit doctor? Did not work 

Have you tried uninstalling + deleting folder in %appdata%/pyRevit and %appdata%/pyRevit-Master and then install as new? Did not work

Any more suggestions :-)

**Comment by jmcouffin** [comment]
you got the 'Adgang nægtet' refused access.
you may not have admin access to specific folders on your computer? check if you have write access here %appdata%/pyRevit and %appdata%/pyRevit-Master
I am guessing this is the issue
you can try uninstalling pyrevit and then installing with this installer 
![image](https://user-images.githubusercontent.com/7872003/203530768-e412bda6-bd94-4fea-865a-3601923786de.png)

**Comment by Bjarkenyg** [comment]
Hmm I've tried all of the above but still no luck.

I also called our network admin, and he said that I have full access on all of our folders.

**Comment by jmcouffin** [comment]
and no specific error popup at revit startup that would give a hint as of what's happening?

**Comment by Bjarkenyg** [comment]
no the program doesn't start at all and there are no error popups

**Comment by jmcouffin** [comment]
> no the program doesn't start at all and there are no error popups

you mean revit does not start?

**Comment by jmcouffin** [comment]
Wild guess.
Can you try the following in command line, it will assign your revit clone a different python engine?
`pyrevit attach master 2711 --installed --allusers`

**Comment by jmcouffin** [comment]
> no the program doesn't start at all and there are no error popups

mind attaching the end of your revit journal file to see if it registers an error?

**Comment by jmcouffin** [comment]
should be located C:\Users\ **YOURUSERNAME** \AppData\Local\Autodesk\Revit\Autodesk Revit **2023** \Journals

**Comment by Bjarkenyg** [comment]
this one ?

**Comment by jmcouffin** [comment]
from the journal, pyRevit seems to have a dll confliict with another addin,
usually, trying to get the faulty addin to load first does the trick _ and renaming the .addin file does that

in the version you are trying to solve it, try adding a 0 renaming the pyRevit.addin to 0pyrevit.addin
C:\ProgramData\Autodesk\Revit\Addins\202**X**
![image](https://user-images.githubusercontent.com/7872003/203746108-2be80127-8b44-4e07-814a-ac4164159b22.png)
That should change the loading sequence.

if that does not work, I don't know what else to investigate

**Comment by jmcouffin** [comment]
> ' 0:< API_ERROR { : Assembly version conflict in some references in pyRevitLabs.Common assembly
> 'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.5.0 } 
> ' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis.VisualBasic assembly
> 'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.5.0 } 

@eirannejad this seems to be the issue.

**Comment by Bjarkenyg** [comment]
no luck, still doesn't run :-(

**Comment by jmcouffin** [comment]
> no luck, still doesn't run :-(

last try: dactivating all addins except pyRevit and re-Activating them one by one to pinpoint the conflictual one
you can use diroots app manager to do that or just move the .addin files and folders from the folder C:\ProgramData\Autodesk\Revit\Addins\202**X**

**Comment by Bjarkenyg** [comment]
I removed all the other addins except Pyrevit, it still cant boot up

**Comment by jmcouffin** [comment]
> I removed all the other addins except Pyrevit, it still cant boot up

😩

**Comment by jmcouffin** [comment]
> I removed all the other addins except Pyrevit, it still cant boot up

whatever the revit version?

**Comment by Bjarkenyg** [comment]
I only tried 22 and 23, I'm not using older versions

**Comment by jmcouffin** [comment]
@Bjarkenyg 
you might want to try solutions from previous issues
https://github.com/eirannejad/pyRevit/issues?q=is%3Aissue+crash

a lot of them relates to either dll conflicts/hell or antivirus/firewall that blocks the addin

**Comment by Bjarkenyg** [comment]
hi again, I found at tread about SentinelOne blocking the program. I turned it off while installing the program and that did the trick.  Thank you for all your help.

**Comment by jmcouffin** [comment]
Excellent, 
please do close the issue
