### ISSUE TITLE
Extensions not working 

### ISSUE THREAD

**Issue by LiamCars** [eirannejad/pyRevit#1668]
**Describe the bug**
Hi, I have started to look into developing some extensions into revit and I get this message when trying to load in;

ERROR [pyrevit.loader.sessionmgr] Can not find command with unique name: pyrevitcore-pyrevit-pyrevit-tools-reload

any ideas? much appreciated, Liam

**Comment by jmcouffin** [comment]
can you share the code to be able to help you debug?

**Comment by LiamCars** [comment]
https://github.com/eirannejad/pyRevit/issues/265  - I think this is the same problem, It is just a case of loading some extensions in. How can I get to this "test cmd exec"? I can get to the developer tab.
Below are some screen shots of what happens.
![image](https://user-images.githubusercontent.com/86594628/203836190-9065b703-c7e9-463f-a032-e048fac61817.png)
![image](https://user-images.githubusercontent.com/86594628/203836309-d141e86f-ecd2-493b-bdcd-e83e5fe114ff.png)
![image](https://user-images.githubusercontent.com/86594628/203836387-3face1f0-b8a8-4f4c-8a8b-98cade106be3.png)
![image](https://user-images.githubusercontent.com/86594628/203836730-61e40aa3-0a87-4688-82b1-5c68254b2471.png)

**Comment by jmcouffin** [comment]
@LiamCars 
try removing the liamtools.extension from the path 
![image](https://user-images.githubusercontent.com/7872003/203931602-8f6bc979-42a8-42a4-b1c9-26942b555502.png)
your path should point to the folder containing the .extension folder, not pointing to the .extension folder itself

**Comment by LiamCars** [comment]
thanks I've tried that one, I get the following messages

File "genericpath.py", line 62, in getmtime
WindowsError: [Errno 2] [Errno 206] The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

**Comment by jmcouffin** [comment]
it points you to an error in the genericpath.py file line 62, length of the filepath. 

Nothing specific about pyRevit. You might want close this issue.

if you need help debugging, sharing the LiamTools.extension folder might be easier. And do that on the pyrevit forum here https://discourse.pyrevitlabs.io/

**Comment by LiamCars** [comment]
great thanks for your help
