### ISSUE TITLE
Endless loop when update to V4.2

### ISSUE THREAD

**Issue by Lemonlee8** [eirannejad/pyRevit#167]
I "pull" the latest pyRevit from the github, but pyRevit can not launch with a endless loop.The logging window was like this:
![image](https://cloud.githubusercontent.com/assets/7747035/23857566/b79cf9ec-0838-11e7-8db9-f8f1ed61cd29.png)

My  SHA-1 is: a7c7cca607026ba407bec2b1db4cf4ee9c0faa87...

Is there anything wrong or it's my misoperation? Thank you...Eirannejad

**Comment by eirannejad** [comment]
Just pushed an update. I think I broke the unicode logger again. Sorry!
Let me know if the new commit fixes this

**Comment by Lemonlee8** [comment]
Fix it...Very thanks for the prompt response!

**Comment by eirannejad** [comment]
Most welcome. I'll add a Chinese tool to my test tools so next time I can catch these errors
