### ISSUE TITLE
Rotate drafting pattern

### ISSUE THREAD

**Issue by keshavanarayan** [eirannejad/pyRevit#1671]
Hi @eirannejad,

Thank you for the great plugin.

It would be great to able to rotate drafting patterns. I don't know whether this has been done by somebody else. Any guidance on how to do this?

**Comment by jmcouffin** [comment]
Rotating a pattern on any surface using the tab command then the rotate tool is already a pretty easy process.

Also, when you create one and want a rotated version, you could just draw a new pattern on top of a rotated one and create a new one.

The use case and the actual process to make it happen is not really worth the (coding) effort.

**Comment by jmcouffin** [comment]
That is just my 2 cents

**Comment by keshavanarayan** [comment]
As far as I understand rotating drafting patterns (apart from straight line-based patterns) are not possible in Revit natively. I'm sure there must be a tool done by others in pyrevit. Just wanted to know if it's been done already. 


![image](https://user-images.githubusercontent.com/74804559/204465330-182f45b1-1a18-462a-a217-1efaad754a9d.png)

**Comment by jmcouffin** [comment]
yep, custom drafting ones,
but what you can do:
1. draw a filled region with the custom drafting pattern you want to rotate
2. export in cad that filled region
3. explode in cad and save
5. **import** back in revit
6. explode the cad
7. and then create the drafting pattern with the pyRevit command as you would do normally, and in pyRevit you have the choice of angle
![image](https://user-images.githubusercontent.com/7872003/204476802-23a22233-df7d-41f6-b4ec-61bf42dcbfa4.png)

It may feel circumvolated but it is dead simple.
and how many times would you do that in your professionnal career anyway? 😄

**Comment by jmcouffin** [comment]
Please close the issue if you feel it responds to your query

**Comment by keshavanarayan** [comment]
Thank you for the help. I was looking for a workaround without all the export and import. I still feel this is a nice feature to have. Is this possible with the revit API?

**Comment by jmcouffin** [comment]
I reiterate:
How many pattern will you process with this? 1? 2?
Is it worth anybody effort?
Frankly I doubt it

The creation itself is possible, but you may have to rotate your lines from the expected pattern before you create it with one of the contructor here https://apidocs.co/apps/revit/2022/7a9baad5-dfa8-712c-3736-87d0f7ce8053.htm

**Comment by jmcouffin** [comment]
Stale.
Closing the issue.
