### ISSUE TITLE
pyRevit v4.8.12.22247 not working Revit 2023

### ISSUE THREAD

**Issue by Oztroz** [eirannejad/pyRevit#1672]
pyRevit does not load when I start Revit 2023. I have downloaded the latest pyRevit both installers. I cant find the addin inside "C:\ProgramData\Autodesk\Revit\Addins"

I have tried this fix below but it does not work for me.
[https://www.notion.so/pyRevit-Is-Installed-But-Does-Not-Load-f6495adb56254e9e8021f8a68e3b2ab7](url)

 - OS: Windows 10
 - pyRevit v4.8.12.22247
 - pyRevit Environment: 

`C:\Users\Oztro>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\Oztro\AppData\Roaming\pyRevit-Master"
==> Attachments
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Oztro\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: DESKTOP-F5V0GA1\Oztro
Active User: DESKTOP-F5V0GA1\Oztro
Admin Access: No
%APPDATA%: "C:\Users\Oztro\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.12.22247+0031`

Thanks in advance.

**Comment by jmcouffin** [comment]
Try this in the command line and rerun pyRevit env and report. And see if it works after restarting Revit.

`pyrevit attach master 2711 --installed --allusers`

**Comment by Oztroz** [comment]
When i write "pyrevit attach master 2711 --installed --allusers" it just comes out blanc no text, nothing. 

`C:\Users\Oztro>pyrevit attach master 2711 --installed --allusers

C:\Users\Oztro>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\Oztro\AppData\Roaming\pyRevit-Master"
==> Attachments
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Oztro\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: DESKTOP-F5V0GA1\Oztro
Active User: DESKTOP-F5V0GA1\Oztro
Admin Access: No
%APPDATA%: "C:\Users\Oztro\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.12.22247+0031`

**Comment by jmcouffin** [comment]
Yep, first one is expected behaviour
Second is not.
Basically, pyRevit does not see your Revit installs therefore does not attach itself to anything.
If you really tried every steps listed in the link of your first post, i would refer you to other similar issues
.
I would try to uninstall then reinstall.
And also disabling any kind of firewall stuff like sentinel one which has been a common install failure point. Other than that i am clueless
