### ISSUE TITLE
View Ordering Tool Missing

### ISSUE THREAD

**Issue by JackieBalasubramanian** [eirannejad/pyRevit#1673]
**Describe the bug**
View Ordering tool missing recently. I cant find the tool for around 2 months. Revit 2022.

**Screenshots**
![image](https://user-images.githubusercontent.com/105915634/205093462-a7abcaba-43b5-412c-a9e6-f85201f54577.png)

**Comment by dvdgnz** [comment]
The tool is now under ReNumber. Run the tool while you are in a Sheet and you will be able to renumber vies
