### ISSUE TITLE
Revit Python Shell Doesn't work!!

### ISSUE THREAD

**Issue by MohamedNassar1** [eirannejad/pyRevit#1674]
**Can't find the Revit Python Shell**
in add-in tab I can't find the Revit python Shell icon.

Actually I can't see the Revit Python shell in Addin tab.

I don't know what's the problem but I delete the addin more than time and re-install it again butit doesn't work.

I had moved to "C:\Program Files (x86)\RevitPythonShell" i found Revit 2020 only i have also 2021 and 2023

![image](https://user-images.githubusercontent.com/82620204/205490591-085bfe85-f36b-4d24-bda5-31ea795868cd.png)

**Comment by jmcouffin** [comment]
@MohamedNassar1 
Revit python shell aka RPS and pyRevit are two different things /repo
If you have an issue with rps, file in an issue in this repo
https://github.com/architecture-building-systems/revitpythonshell

You seem to have installed pyRevit properly though and it is a great set of tools.

There's quite a few videos on yt to guide you with rps.
Latest videos being the ones from Erik Fritz.

**Comment by jmcouffin** [comment]
Please close this issue

**Comment by MohamedNassar1** [comment]
please, i have one more question. 
![WhatsApp Image 2022-12-17 at 19 12 03](https://user-images.githubusercontent.com/82620204/208248643-81b31bd7-41e6-420f-9ef7-e509070108b7.jpg)

Every time i open Revit i face this issue. i don't know why and what's wrong i have made?

**Comment by jmcouffin** [comment]
If you deactivate the Pyrevit dev extension, everything should be back in order.
I think it has to do with the config of one of the route server test button.
