### ISSUE TITLE
Purge Shared Parameter

### ISSUE THREAD

**Issue by hannabelka** [eirannejad/pyRevit#1676]
**Is your feature request related to a problem? Please describe.**
I can't delete a number of shared parameters from the company's template, main titleblock and Model Issue Sheet titleblock.

**Describe the solution you'd like**
I want to be able to purge shared parameters that were created by mistake. 

**Describe alternatives you've considered**
I have considered recreating the template and broken families

**Additional context**
n/a

**Comment by jmcouffin** [comment]
Hi @hannabelka 
Please explain a bit more, you want to: 

- remove specific shared param from families in batch? (opening each family in background to do that?)
- remove specific project shared param from your project?

**Comment by hannabelka** [comment]
I have created the parameters with specific company name prefixes, but they are not what I need them to be.
 So, according to Autodesk, If you delete a parameter and then create another parameter with the same name, Revit does not consider it to be the same parameter.
That's why I want to purge them so I cam use shared parameters names again.

**Comment by jmcouffin** [comment]
> I have created the parameters with specific company name prefixes, but they are not what I need them to be. So, according to Autodesk, If you delete a parameter and then create another parameter with the same name, Revit does not consider it to be the same parameter. That's why I want to purge them so I cam use shared parameters names again.

A bit more clear.
Can you answer my previous questions or phrase the exact steps you imagine the tool would help you with.

**Comment by Robbo1234** [comment]
This article might be worth reading:

Purge Shared Parameters From a Revit Model:
https://opendefinery.com/blog/purging-shared-parameters-in-revit/

**Comment by hannabelka** [comment]
Thank youxso much.
Worked!
Hurrah!

**Comment by Robbo1234** [comment]
That's great to hear.
