### ISSUE TITLE
pyRevitPlus: Align tools not working in Revit 2023

### ISSUE THREAD

**Issue by jmqrsq** [eirannejad/pyRevit#1680]
Hello. I am trying to utilize the Align tools in pyRevitPlus extenion. When I click the tool, it thinks for a minute but then never gets to the next step where you can select tags to align to the initial selected tag. Is this a known bug? If not, can it be fixed? TIA
JQ

**Comment by jmcouffin** [comment]
Maybe more suited for this repo https://github.com/gtalarico/pyrevitplus/issues
@jmqrsq
