### ISSUE TITLE
Bug in PDF from exported projects

### ISSUE THREAD

**Issue by danielchipolesch** [eirannejad/pyRevit#1681]
**Describe the bug**
The bug happens in the tasks that shows when we try to export the information of a project as a PDF file. In my case, when a tried export the informations of a specifically project from a project template, it appeared the tasks from all projects I have. In my see, it should show filtered by project.

**To Reproduce**
1. Create a new page from the "Project & tasks" template;
2. Create more than one project;
3. Create more than one task for each project;
4. Open a specifically project in "side peek mode". Let's pretend that you opened "project 1";
5. Export this project as a PDF;
6. It will show not only "project 1" tasks, as it should do, but all tasks from all projects.

**Expected behavior**
It should show only the specifically tasks from that project.

**Screenshots**
![Projeto](https://user-images.githubusercontent.com/58316637/207181715-97c8180a-61cf-4353-8920-69458060424e.png)
![Export](https://user-images.githubusercontent.com/58316637/207181742-2ce01134-8157-461d-b912-fa72a2656f98.png)
![Outros Projetos](https://user-images.githubusercontent.com/58316637/207181766-9a046f99-32e1-49e8-9198-b3088276f6f8.png)

Thank you! I hope I can contribute to this powerful tool

**Comment by jmcouffin** [comment]
@danielchipolesch wrong repo? you are in the pyRevit repository, not Notion

**Comment by dvdgnz** [comment]
why does this keep happening? 😒

**Comment by jmcouffin** [comment]
> why does this keep happening? 😒

I wish I knew!
But those are easy to close 🤭

**Comment by jmcouffin** [comment]
@danielchipolesch you are on the Pyrevit code repository...
Not Notion's
I will close the issue accordingly.
