### ISSUE TITLE
Delay linkbutton loading

### ISSUE THREAD

**Issue by onomou** [eirannejad/pyRevit#1682]
**Is your feature request related to a problem? Please describe.**
I created a linkbutton to launch RevitPythonShell non-modal.

This is the `linkbutton` code:
```yaml
title: "RPS"
tooltip: Run the non-modal RevitPythonShell
assembly: RevitPythonShell.dll
command_class: RevitCommands.NonModalConsoleCommand
```

 It works fine once Revit has loaded (using Reload from the pyRevit tab), but when first launching it throws this error:

```
ERROR [pyrevit.loader.uimaker] Can not find target assembly for <type_id '.linkbutton' name 'RevitPythonShell' @ 'C:\Users\s.williams\source\repos\pyAlliant\pyAlliantDev.extension\Alliant.tab\Dev.panel\RevitPythonShell.linkbutton'>
```

![2022-12-14 10 09 57 Revit_W5MRbfsMnF](https://user-images.githubusercontent.com/131693/207633632-080be7be-c21c-48a9-829f-6b3083318c0f.png)

**Describe the solution you'd like**
I would like to be able to delay loading a `linkbutton` until after the other add-ins have loaded. This error appears to be because pyRevit is loaded before RevitPythonShell.

**Describe alternatives you've considered**
Use a regular `pushbutton` with one of these:

 * Following The Building Coder's instructions: https://thebuildingcoder.typepad.com/blog/2013/10/programmatic-custom-add-in-external-command-launch.html
 * Revitalizer's solution using Reflection

**Additional context**
I am trying to collect buttons from other tabs -- built-in tools, regular add-ins, pyRevit extensions -- and put them on my own custom tab.

**Comment by eirannejad** [comment]
You have to make sure RevitPythonShell is loaded before pyRevit. Go to Revit addins folder and rename `pyRevit.addin` file to something line `ZZZ_pyRevit.addin` so it is alphabetically sorted last
