### ISSUE TITLE
Revit 2021 Load failed 

### ISSUE THREAD

**Issue by Ghazalythegreate** [eirannejad/pyRevit#1683]
**Describe the bug**
I'm trying to install Pyrevit for Revit 2021 and failed load message appears 
![image](https://user-images.githubusercontent.com/35693697/207843920-3632b1cb-f11e-4067-9712-2d60612bf47f.png)

**Comment by ZepengZha0** [comment]
path is to long,

**Comment by eirannejad** [comment]
You can fix the path too long limitation in Windows using this method. The Python3 installer also has a checkmark to fix this when installing python

https://techcommunity.microsoft.com/t5/onedrive-for-business/how-to-resolve-path-is-too-long-error-endless-abending-loop/m-p/3634467
