### ISSUE TITLE
Fix PyRevitLabs.* vs pyRevitLabs.* Namespaces

### ISSUE THREAD

**Issue by BarrieSharp** [eirannejad/pyRevit#1687]
I am using c# to prototype add-in scripts with PyRevit. It works well as a workflow but the issue is around case of the namespace.

Using Visual Studio, I have added "C:\Program Files\pyRevit-Master\bin\pyRevitLabs.PyRevit.dll" as a dependency and a using to provide intellisense:
`using pyRevitLabs.PyRevit.Runtime;`

The issue comes when I run the script, the using is incorrect. Following the documentation I see the using starts with an uppercase:
`using PyRevitLabs.PyRevit.Runtime;`

Changing to upper case means that the script runs properly but now Visual Studio is complaining that 'the type or namespace name 'pyRevitLabs' could not be found.'

Have I missed something basic or is this a quirk of how the script is consumed in a session?

**Comment by eirannejad** [comment]
@BarrieSharp `PyRevitLabs.PyRevit.Runtime` is a dynamically generated assembly that is created when Revit is being loaded and stored in pyRevit cache folder. It has dependencies on pre-compiled pyRevitLabs.* dlls inside the pyRevit `bin/` directory. I think you would need to add references to those dlls as well in Visual Studio e.g. `pyRevitLabs.Common.dll`

**Note to Developer:**

- [ ] Fix discrepancy in `pyRevitLabs` namespace naming between pre-compiled pyRevitLabs assemblies and the dynamically generated `pyRevitLabs.PyRevit.Runtime` assembly

**Comment by BarrieSharp** [comment]
> @BarrieSharp `PyRevitLabs.PyRevit.Runtime` is a dynamically generated assembly that is created when Revit is being loaded and stored in pyRevit cache folder. It has dependencies on pre-compiled pyRevitLabs.* dlls inside the pyRevit `bin/` directory. I think you would need to add references to those dlls as well in Visual Studio e.g. `pyRevitLabs.Common.dll`

@eirannejad, that's really useful to know. I took a copy of the cached version from `%AppData%\Roaming\pyRevit\2022` and added it as a reference in my project. It has stopped it from complaining though I appreciate it is a less than ideal solution. Hopefully it will be temporary if the pre-compiled namespace is updated.

I haven't needed to add `pyRevitLabs.Common.dll` yet but already had `pyRevitLabs.NLog` to help with debugging.

**Comment by eirannejad** [comment]
@BarrieSharp See this conversation as well https://github.com/eirannejad/pyRevit/issues/1697#issuecomment-1378099753
