### ISSUE TITLE
AI popup blockin Notion website access

### ISSUE THREAD

**Issue by LuizDLM** [eirannejad/pyRevit#1689]
I am writing to report a bug that I have encountered while trying to access the Notion website on Chroime. Specifically, since yesterday I have been unable to access the website because a popup about the AI feature appears and blocks any action:

![image](https://user-images.githubusercontent.com/77069408/209331760-c989ddb5-772c-45b8-8a74-8508f0c237a2.png)

I have tried accessing the website from different devices and browsers, but the issue persists. 

I would appreciate if you could look into this issue and provide a solution as soon as possible.

Thank you for your attention to this matter.

**Comment by jmcouffin** [comment]
@LuizDLM you are on the Pyrevit code repository...
Not Notion's
I will close the issue accordingly.
