### ISSUE TITLE
Not an Issue: Pick Detail Seems to Get Stuck as Default

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#169]
I am going to add this for logging purposes, but in the process of submitting this issue I solved the problem. **It is not a pyrevit issue:**

Issue:
Not sure this is actually a pyrevit issue and maybe you can explain what's happening, but it appears like I'm stuck in a "pick detail" mode.  Watch this video.  See how I can't select model elements unless I specifically state "pick model" in pyrevit. This only seems to effect the "box select" not indicidual selection.  Any thoughts?
http://autode.sk/2mnJQiY

Solution:
Items were "beyond" in the view depth.
![image](https://cloud.githubusercontent.com/assets/14113080/23905043/3d7f7d2a-08a0-11e7-85e7-a3260ad28abf.png)

**Comment by eirannejad** [comment]
huh interesting. Thanks for letting me know. I'll close the issue but will add this to my notes.
