### ISSUE TITLE
Modify line style of Spot Elevation leaders.

### ISSUE THREAD

**Issue by JMarshQPK** [eirannejad/pyRevit#1693]
**Is your feature request related to a problem? Please describe.**
Revit does not allow users to modify the leader line style of the spot elevation system family. Currently, a user can only change the lineweight, but my firm and others in the Autodesk forums would like the ability to make the leader a dashed line style on that particular element.

**Describe the solution you'd like**
If Revit API is able to access the leader line style of spot elevations, a simple dropdown menu under Edit Type with the project's line styles would be very useful.

**Describe alternatives you've considered**
There is a workaround involving aligning and locking a detail line to a model element then placing a spot elevation with leader turned off.

**Additional context**
Thanks for looking into this. It may not be possible, because the spot elevation is not a very accessible family as designed by Autodesk currently.

**Comment by jmcouffin** [comment]
@JMarshQPK 
something like this ?
![image](https://user-images.githubusercontent.com/7872003/210647791-312b3f90-5c62-4edf-8a01-0c45927990bc.png)
general rules of thumbs regarding what is possible or not through the ReviAPI

> if it is possible through the UI, it is most probably possible via the API

I managed to replace the continuous black 1 line of the spot elevation with a right click replacement per selected elements.

This is something relatively easy to code
There is a rather large body of code already available, you could add the 'dashed black' to the set of overrides in here: https://github.com/eirannejad/pyRevit/blob/master/extensions/pyRevitTools.extension/pyRevit.tab/Modify.panel/edit3.stack/Override.pulldown/Override%20VG.pushbutton/script.py

To go more in depth:
- you can watch Erik Fritz video https://www.youtube.com/watch?v=X4KFrDGch5E where he explains how to match ovverrides and how the [override graphics](https://apidocs.co/apps/revit/2022/dff43edf-d932-a037-e9a6-82d2374a903d.htm#) constructor works in Revit

- same within the dynamo environment https://www.youtube.com/watch?v=5-52iJQPXKE by Danny Bentley

**Comment by jmcouffin** [comment]
I felt up to the task tonight ;p 
https://github.com/eirannejad/pyRevit/pull/1694

you should find the installer to try it out here in 10 https://github.com/eirannejad/pyRevit/actions/runs/3841714989

1. Install this version of pyRevit
2. in revit, select your spot elevations
3. under pyRevit-> Modify panel -> Override pulldown -> Override VG and you will find a dash option
![image](https://user-images.githubusercontent.com/7872003/210652890-a684afb5-4443-43e6-b3c0-03e299b6b3c5.png)

**Comment by JMarshQPK** [comment]
Wow, this looks like exactly what I was looking for... and in the same day.
Thanks! I'll try this out!

**Comment by eirannejad** [comment]
@jmcouffin Thank you!!

**Comment by JMarshQPK** [comment]
Was this included in last weeks official release? I didn't see it in the release notes.

**Comment by jmcouffin** [comment]
Should be,
Under extensions/pyRevitTools.extension/pyRevit.tab/Modify.panel/edit3.stack/Override.pulldown/Override VG.pushbutton/script.py
