### ISSUE TITLE
Dynamic generated runtime assembly for C# Assembly Extension

### ISSUE THREAD

**Issue by JunfXiao** [eirannejad/pyRevit#1697]
Considering that the pyRevit Runtime assembly is compiled dynamically, it can cause many problems when compiling our plugins in one version of pyRevit and diestribute the compiled invoke button to users who use other versions. It would be nice if:
- PyRevit Runtime assembly has a permanent name, or a hard link to the original one, like: %appdata%\pyRevit\Cache\PyRevit.Runtime.dll instead of current one with signature.

- The CLRLoader could pass execParams as HashMap and search the param by name instead of type.
The reason is that in dynamic generated assemblies, type comparison will always be false in different devices with different versions.

https://github.com/eirannejad/pyRevit/blob/528940e1a3593f1ae5bd9bfd964d2f37fb9d45e1/pyrevitlib/pyrevit/runtime/CLREngine.cs#L276-L278

**Comment by eirannejad** [comment]
I'd like to know what part of the dynamically compiled runtime are you using in your assemblies?

**Comment by ForInfinity** [comment]
> I'd like to know what part of the dynamically compiled runtime are you using in your assemblies?
Hi,
It's PyRevitLabs.PyRevit.Runtime, which locates in `%appdata%\PyRevit`. It will be used in the c# class to load resources from the original extension directory.

**Comment by eirannejad** [comment]
Hahah I know. I wrote that 😅 I mean is there anything in the runtime that you are using in your own addin. I guess the question is why do you care if it is pre-compiled or not?

**Comment by ForInfinity** [comment]
> Hahah I know. I wrote that 😅 I mean is there anything in the runtime that you are using in your own addin. I guess the question is why do you care if it is pre-compiled or not?

Haha now I understand you. I'm trying to distribute my compiled assembly as a shared extension. If I use pyRevit version A when compiling, and the other uses pyRevit version B, the two pyRevit will have different runtime assembly filename with different signatures. This leads to the exception "the dependency file `pyRevit_2022_[digest]_PyRevitLab.dll` could not be found."

That's why I'm trying to find a way to solve this problem.

And I just thought out

**Comment by eirannejad** [comment]
How are you creating the buttons in the UI? What do they point to?

- You might know that you can [create C# scripts for pyRevit](https://www.notion.so/Create-Your-First-NET-Command-edce7dea66604c3ab059e73425a647c6) as well. The script [has access to ExecParams](https://www.notion.so/Anatomy-of-NET-C-VB-Scripts-1e1667f172fc4e9190eb5fa4c4687707) and can call a function in your compiled assembly and pass the necessary info.
- There are [also Invoke Bundles that can provide an assembly and a type](https://www.notion.so/pyRevit-Bundles-12323e3090904d9aa7cdc3d82095d3e3#4dfd090c06964b7ab6f4a54d2ee0038b) to pyRevit to call into when button is clicked. The benefit is the assembly can be replaced while Revit is running.

The reason pyRevit runtime gets compiled dynamically is to allow "reloading" pyRevit tools and runtime within the same Revit session. That's kind of integral to how pyRevit is designed.

**Comment by ForInfinity** [comment]
Hi Ehsan,

I use it in a invoke button, which contains a compiled assembly.

So clearly to say, it will cause problems between different pyRevit versions when I use the dynamically compiled runtime in compiling process of my assembly.

Regards
Junfeng
________________________________
发件人: Ehsan Iran-Nejad ***@***.***>
发送时间: 2023年1月11日 02:01
收件人: eirannejad/pyRevit ***@***.***>
抄送: Junfeng Xiao ***@***.***>; State change ***@***.***>
主题: Re: [eirannejad/pyRevit] Dynamic generated runtime assembly for C# Assembly Extension (Issue #1697)


How are you creating the buttons in the UI? What do they point to?

  *   You might know that you can create C# scripts for pyRevit<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.notion.so%2FCreate-Your-First-NET-Command-edce7dea66604c3ab059e73425a647c6&data=05%7C01%7C%7Ca4d97bb73f9d4d183de508daf36f6fc5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638089957185971610%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mGi7c9cCiDga%2BTbA1dvQzwZHoEOp5wEsSOQQ8WPAz8Y%3D&reserved=0> as well. The script has access to ExecParams<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.notion.so%2FAnatomy-of-NET-C-VB-Scripts-1e1667f172fc4e9190eb5fa4c4687707&data=05%7C01%7C%7Ca4d97bb73f9d4d183de508daf36f6fc5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638089957185971610%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=A6x%2FcrH%2B8K5R4INUXjdDOr7fcqAGRdIY6g%2FatR5CKXg%3D&reserved=0> and can call a function in your compiled assembly and pass the necessary info.
  *   There are also Invoke Bundles that can provide an assembly and a type<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.notion.so%2FpyRevit-Bundles-12323e3090904d9aa7cdc3d82095d3e3%234dfd090c06964b7ab6f4a54d2ee0038b&data=05%7C01%7C%7Ca4d97bb73f9d4d183de508daf36f6fc5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638089957185971610%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aK8abt%2B3p3DbDaUFPV4HTx68p6FiNcHAPSbFoVW5mkE%3D&reserved=0> to pyRevit to call into when button is clicked. The benefit is the assembly can be replaced while Revit is running.

The reason pyRevit runtime gets compiled dynamically is to allow "reloading" pyRevit tools and runtime within the same Revit session. That's kind of integral to how pyRevit is designed.

―

**Comment by jmcouffin** [comment]
may be fix by PR #1777 
See https://github.com/eirannejad/pyRevit/issues/1373#issuecomment-988564197

**Comment by eirannejad** [comment]
Fixed by https://github.com/eirannejad/pyRevit/pull/1797
