### ISSUE TITLE
pyRevit Approval for 508 Compliance

### ISSUE THREAD

**Issue by LoRue656Plus10** [eirannejad/pyRevit#1698]
Hello,

I work for the GSA (General Services Administration) Region 9 Design & Construction Division, based in San Francisco.  My team is working on our BIM program here and I would like to use pyRevit as one of our tools.  In order for pyRevit to be installed on our machines, I need to submit the .exe and a form (called VPAT) that details it's compliance with ADA (Section 508).    pyRevit does NOT need to be changed.  I just need an acknowledgement from someone, preferably Ehsan, that the attached pdf is more or less correct.  The attached VPAT form has been filled out already.  If someone could take a look and email me an acknowledgement at loren.routh@gsa.gov of the form, I would greatly appreciate it.  You can also reply to me through GitHub.

Looking forward to using pyRevit!

Best,

Loren Routh
Building Information Specialist
GSA / PBS
Technical Services Branch
Design and Construction Division
50 United Nations Plaza
San Francisco, CA  94102-4912
Cell:  415-971-6213

[VPAT2.4Rev508_pyRevit.pdf](https://github.com/eirannejad/pyRevit/files/10376320/VPAT2.4Rev508_pyRevit.pdf)

**Comment by jmcouffin** [comment]
@eirannejad

**Comment by eirannejad** [comment]
@LoRue656Plus10 My family name is misspelled `Iran-Najad` -> Correct `Iran-Nejad`

Does this create any sort of liability for us?

**Comment by eirannejad** [comment]
Emailed @LoRue656Plus10 directly. Closing this ticket.
