### ISSUE TITLE
Install for Non-Admin

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#170]
Had an issue today when I installed V4 on a user's computer that was not an admin.  The files were installed into the default user on the computer and .addin files didn't get copied.  I was able to manually copy those files to the user's %appdata% folder, but curious if I am doing something wrong during the install.

**Comment by eirannejad** [comment]
`.addin` files are copied using a bash script (since their contents need to be dynamically set per final install location). Might be that the non-admin can not run the batch scripts

**Comment by thazell** [comment]
Interesting.  However I thought it had something to do with the "user" that initiated the install.  (totally speaking outside of my expertise)  On my computer when I run the install and on other Admins when we run the install it installs into our %appdata% folder on his computer, it installed under the default user.  I'll write a little batch file that will copy the appdata folder for pyrevit into the user appdata and install the .addin file.  Not sure if this was a remote installation issue or just related to the admin privileges.  I'll test it out and get back to you.

**Comment by eirannejad** [comment]
It might be a remote installation issue. The installer reads the value of %appdata% so maybe check to see if it is correctly set to the user appdata and not the default user appdata, before installation.

**Comment by thazell** [comment]
@eirannejad not sure how to reopen this issue, but wondering if there is a setting in the installer that can help.  Here are more specifics that I now know. I think the key is typical users in our office don't have full privileges to their computers and require IT to make installations.

When we used goverlan or a remote install as mentioned above it installed into the default user on the computer. I was able to access the default user folder and manually copy the pyrevit folder and .addin files for the user from my install and it seemed to work.

When I installed it today locally on user 1's computer using admin 1's password.  It installed into admin 1's %appdata% folder rather than user 1's folder.   I can make a .bat file that will copy those folders from my install to the user's computer, but seems like something could be changed in the installer.  Any thoughts?

**Comment by eirannejad** [comment]
The setup defaults to the current users %appdata%. 
The installer has command prompt options:
`pyRevitSetup-v4.exe /VERYSILENT /DIR="C:\pyRevit"`
will install pyRevit in the `C:\pyRevit` directory

**Comment by thazell** [comment]
ah... that might work.  Let me see.

**Comment by thazell** [comment]
Can we update the default installer to put the .addin into: C:\ProgramData\Autodesk\Revit\Addins\ instead of %appdata%\Autodesk\Revit\Addins?

**Comment by eirannejad** [comment]
Copy the `install-addin.bat` from `pyRevit/release` folder and make adjustments to it as you wish. Run your modified script after the pyRevit setup and move the addin files to wherever you want them to be.

BTW,
Command line arguments are listed here.
http://www.jrsoftware.org/ishelp/index.php?topic=setupcmdline

**Comment by thazell** [comment]
Thx, Will do.

**Comment by thazell** [comment]
It's working I set up a .bat file that modifies everything.  Let me know if you want a copy
