### ISSUE TITLE
List all sheets a Legend (or Schedule) is on

### ISSUE THREAD

**Issue by RevitIRL** [eirannejad/pyRevit#1702]
**Is your feature request related to a problem? Please describe.**
I want to know the ramifications of editing a Legend (i.e. what sheets it will affect)

**Describe the solution you'd like**
With a Legend selected, use a command to see a list of sheets that it's on

**Describe alternatives you've considered**
The manual way of expanding all the Sheets (in the Project Browser), scanning down the list, and collapsing again. Or making my own command.

**Additional context**
Found what looks like a Visual Basic solution here (haven't tried to test it or convert it): https://forums.autodesk.com/t5/revit-api-forum/find-a-list-of-sheet-that-contain-a-legend-has-selected-by-user/td-p/7930135

**Comment by jmcouffin** [comment]
@RevitIRL added with #1707 
You should be able to doanload new installers here https://github.com/eirannejad/pyRevit/actions/runs/3948046854 in a bit

**Comment by RevitIRL** [comment]
please sort by Sheet Number (after Legend Name)

It's been working great and very helpful, but I usually am just interested in one legend, and then want to go down the list of sheets that it's on (to see if the change I'm making applies to all), and that's usually easier to do if the sheets are in order.

**Comment by jmcouffin** [comment]
Create a different issue and point to this one. 
I will see if I get the time and head space to do that. It should not be too much of a hassle
