### ISSUE TITLE
output.linkify crashes with non-list iterables of ElementId

### ISSUE THREAD

**Issue by sanzoghenzo** [eirannejad/pyRevit#1708]
**Describe the bug**

Using an iterable (for example a generator or a set)  of `ElementId`s as parameters of `output.linkify` results in an exception.
this is because [`linkmaker.make_link` only checks if the input parameter is a list](https://github.com/eirannejad/pyRevit/blob/master/pyrevitlib/pyrevit/output/linkmaker.py#L50), even though the list comprehension could work for all iterables.
Because of this, the `strids` variable is never initialized and the following lines throw the exception.

**To Reproduce**

run the following code (substitute the elements in the set with actual element ids)
```
from pyrevit import script
script.get_output().linkify({id1, id2, ...})
```

**Expected behavior**
`linkify` should create the link as it does with lists of `ElementId`s.

This is easily fixed in a pythonic way by replacing the `isinstance` calls with a `try/except TypeError` statement:

```
try:
    strids = [safe_strtype(x.IntegerValue) for x in element_ids]
except TypeError:
    strids = [safe_strtype(element_ids.IntegerValue)]
```

and maybe also add an `except AttributeError` to catch items that are not elementids and raise a more user firendly `ValueError("one or more of the provided items are not ElementIds")`

**Comment by jmcouffin** [comment]
@sanzoghenzo 
it makes sense to me, 
why not making a PR?

**Comment by sanzoghenzo** [comment]
> @sanzoghenzo it makes sense to me, why not making a PR?

Will do!
I was in a hurry at the end of the working day, amd today I was caught in other tasks... I hope to get to it ASAP
