### ISSUE TITLE
Sorting of Family Load Types

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#171]
Copied from Family Loader Issue:

1. Sort Order 
W8 ends up at the very end of the list because 8 is larger than 1.  
https://www.youtube.com/watch?v=PjEdcOsUL3k

**Comment by thazell** [comment]
I agree with your comment about this needs to work with all families and don't want to get too closed minded about the sorting...  What if the catalog order was not resorted?  How does that fit with other families? I think that's how Revit natively looks at the load family dialog

**Comment by eirannejad** [comment]
Implemented:
https://github.com/eirannejad/pyRevit/commit/3f36dbffab362c7aa6082dfca2c72104fe7ffb3e

This is how sorting works:
Any type name that does not have a number in it will be sorted alphabetically.
Any type name that has numbers in it will be sorted by the numbers from first to last. This means:
- `W8X12` will list before `W10X12`
- `W8X12` will list before `W8X14`
- `Table 36"` will list before `Table 48"`
