### ISSUE TITLE
pyChilizer issue

### ISSUE THREAD

**Issue by studioearl** [eirannejad/pyRevit#1710]
**Describe the bug**

Sorry if this isn't the place to report this, I tried reaching out to archilizer, no response, if you don't handle this, can you connect me with the people/place that can? 

Not sure if this is the right place to report this, but I  have a glitch with pychilizer's Room Data Sheets.  It not working regardless of template or project (tested it multiple time on Revit 2022) 

**To Reproduce**
1. Go to Pychilizer > Project > 
2. Click on Room Data Sheets.
3. select rooms 
4. click finish
5. select as needed (some times I didn't change anything) in the pop window and click OK
6. get error screen 

**Expected behavior**
I expected creation of interiors placed on sheet. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.8.12.22247+0031
 - pyRevit Environment: 
 - C:\Users\Earl>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\Earl\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\Earl\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\Earl\AppData\Roaming\pyRevit-Master"
master | Product: "2019.2.3" | Engine: IPY277 (277) | Path: "C:\Users\Earl\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Earl\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.0.20.21 | Build: 20220726_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2019.2.3 | Version: 19.2.30.41 | Build: 20210416_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages

**Additional context**
Error: 
﻿
ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:An internal error has occurred.
IronPython Traceback:
Traceback (most recent call last):
File "C:\Users\Earl\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\pyChilizer.tab\Project.panel\rooms.stack\Room Data Sheets.pushbutton\script.py", line 284, in <module>
File "C:\Users\Earl\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\lib\pychilizer\geo.py", line 274, in set_crop_to_bb
Exception: An internal error has occurred.

Script Executor Traceback:
Autodesk.Revit.Exceptions.InternalException: An internal error has occurred.
at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by jmcouffin** [comment]
routed here https://github.com/dnenov/pyChilizer/issues/18, consider adding a comment there to get the follow up notifications
@studioearl next time I am sure you will find the right spot for your issues ;)

**Comment by rastermadre** [comment]
@studioearl Hi, is it possible that the units of the 'Crop offset' are set to an impossible value? this can also happen when the room placement point is not in the room (overlapping a wall, for example) 
![image](https://user-images.githubusercontent.com/43077096/219452932-fc6be4a9-552a-4d62-a23b-69a4ccaf6e9d.png)

**Comment by studioearl** [comment]
Thanks for your response. Would you have any links to learn more about
those topics? or some info on how to check those? Earl
--
*Earl Schrader*
***@***.***  ***@***.***>
515-203-1628

**Comment by rastermadre** [comment]
Hi Earl, 

1. Check that the room placement point is located somewhere closer to the room center. The elevation marker will be placed in that point, so it needs to be somewhere 'inside the room'. The situation in the screenshot above is a rare case when the room placement point in not in the room. just drag it to recenter and that should do the trick. 
2. when using the RDS tool, please check that the Crop Offset value is reasonable. You can try with setting it to 0mm, and then increase to what suits your needs. 
![image](https://user-images.githubusercontent.com/43077096/219651879-d7561131-b26c-4ca0-adf5-616e28f82339.png)

Checking out this video might also help: 
https://www.youtube.com/watch?v=_9qIFpoQYB4&list=PLIA_9O64xF1osz1daPyM3l8ODDXDHeGpr&index=11&ab_channel=Archilizer

**Comment by studioearl** [comment]
Thanks, I'll check it out soon.
--
*Earl Schrader*
***@***.***  ***@***.***>
515-203-1628

**Comment by studioearl** [comment]
> Hi Earl,
> 
> 1. Check that the room placement point is located somewhere closer to the room center. The elevation marker will be placed in that point, so it needs to be somewhere 'inside the room'. The situation in the screenshot above is a rare case when the room placement point in not in the room. just drag it to recenter and that should do the trick.
> 2. when using the RDS tool, please check that the Crop Offset value is reasonable. You can try with setting it to 0mm, and then increase to what suits your needs. Please bear in mind that if your project is not metric, the value will be in feet.
>    ![image](https://user-images.githubusercontent.com/43077096/219651879-d7561131-b26c-4ca0-adf5-616e28f82339.png)
> 
> Checking out this video might also help: https://www.youtube.com/watch?v=_9qIFpoQYB4&list=PLIA_9O64xF1osz1daPyM3l8ODDXDHeGpr&index=11&ab_channel=Archilizer

I finally had time to check it out and got it to work and this rocks! Thanks for making this. I did have a couple of questions and wondering if there was more documentation with answers to these questions and more. please don't take these questions as critiques but only as how to get a better understanding, again this rocks.  
Can it create the view on an existing sheet? 
Is it possible to not create the RCP or floor plan? 
Can detail numbers be changed (like 1, 2, 3, 4 and not a, b, c, d)?
Can it create more than 1 room on a sheet if the sheet is much larger? 
Lastly, is there any way to send some funds for coffee to those responsible for creating this?
