### ISSUE TITLE
Pyrevit 4.8.12 working in Revit 2023 but some errors to "packages and tag extension" and pyRevit DevTools and pyRevit DevHooks

### ISSUE THREAD

**Issue by cdurks** [eirannejad/pyRevit#1711]
@eirannejad Would you be able to help me with this issue?
@jmcouffin I noticed that you commented on issue #1632 perhaps you have some insights as well

Having problems with errors using the pyRevit package and tag extension tools.
![image](https://user-images.githubusercontent.com/123483102/214348697-e4ac6703-7ec2-46fb-b960-a15313f4b3f8.png)

The extensions developing tools pyRevitDevTools, and pyRevitDevHooks are having problems as well.
![image](https://user-images.githubusercontent.com/123483102/214350184-01f7b96a-b1d7-4ea2-92ef-845081c0ba47.png)
![image](https://user-images.githubusercontent.com/123483102/214350250-d378c3f6-1352-4de7-97e2-31850d37eb6d.png)
![image](https://user-images.githubusercontent.com/123483102/214350211-6840ed9e-8374-482b-893d-65d1036b7f69.png)

As for the package and tag management tools… I followed the instructions on the pyRevit tutorial regarding using tags…
Set up project parameter “DOCTAG” for all categories

![image](https://user-images.githubusercontent.com/123483102/214347263-2ef7d23b-43dc-4186-bd7e-2c845986a81c.png)
Select Objects
 
![image](https://user-images.githubusercontent.com/123483102/214347315-2fa0a811-89ca-47b7-b790-9c3ef41bf284.png)

The packages and tags extension seems to work fine in Revit 2022 along with all the other tools that the pyrevit plug-in has to offer. 
 
![image](https://user-images.githubusercontent.com/123483102/214350895-28004308-1fe0-4de8-b58e-f25e0e676c2b.png)

But the pyRevitDevTools and pyRevitDevHooks seem to have problems in Revit 2022 in well.
![image](https://user-images.githubusercontent.com/123483102/214350344-9098a6eb-dce0-4b61-b66b-e1c572de933e.png)

I have tried different installations which include:
-	installed the latest version of pyrevit (4.8.12.22247+0031:277:2023.1.10)
-	installation for single user
-	installation for all users
-	installation with Pyrevit CLI installer for both options.
-	installed the ‘pyrevit doctor’ to clean out all the old versions from my computer registry etc. and reinstalled
-	followed the steps on another blog where another individual had the same problem. 
                   https://github.com/eirannejad/pyRevit/issues/1632      _added pyRevitTags and doesn't work #1632_

Additional Context:
I am running
 - OS: [WIndows 10 Pro Version 21H2 OS build 19044.2486  Windows Feature Experience Pack 120.2212.4190.0]
 - pyRevit Version [4.8.12.22247+0031:277:2023.1.10]

I Did just install Revit 2023 two days ago but all the other addins work fine, and I have also installed all the updates and hotfixes for Revit 2023. As mentioned, the other core tools for pyrevit work fine aswell. 

Please note that I am not a programmer or a coder. I work as an architectural technologist and utilize various plugins to help increase my productivity.  
Repairing this plugin extension for the new version of revit 2023 would be greatly appreciated. Thanks so much.

**Comment by jmcouffin** [comment]
- most of the tags extensions seems to work as expected on my side. 
But I did not activate the dev extension and that might be the reason of your issues. I would try deactivate the dev hooks and tools extensions first.

- The routes error has something to do with the fact you did not set it up.

- only error I get is the fact that building pads are visible whenever I try to create a 3D view for a specifing tag.

**Comment by bim2016** [comment]
just encountered the exact same issue, i only enabled pyRevitTags, i'm using Revit 2023.1 and pyRevit v4.8.12
![image](https://user-images.githubusercontent.com/47944543/216434118-b7ccaa7d-9dac-4bcb-99ba-05178fe5d840.png)

**Comment by jmcouffin** [comment]
@bim2016 try using the latest wip release or cloning the dev branch.
I cannot reproduce the issue but I remember it took me a while to understand how it works.
Ehsan has 2 videos about this extension that help

**Comment by jmcouffin** [comment]
@bim2016 and please try the steps mentioned ⬆️ 
I cannot reproduce this issue with the latest wip installers in the action tab of the repo

**Comment by bim2016** [comment]
thanks jmcouffin, works great after i installed 4.8.13.23031

**Comment by jmcouffin** [comment]
@bim2016 thanks for the feedback 
Glad it helped
