### ISSUE TITLE
 ERROR [pyrevit.loader.uimaker] UI error: Error adding slide out: Slideout panel is already added to the current panel.

### ISSUE THREAD

**Issue by anitopi11x** [eirannejad/pyRevit#1712]
![SNAG-0000](https://user-images.githubusercontent.com/83452947/214573029-715fc7b3-c91e-47ca-a32d-e89aa8744454.png)

**Comment by OlkKaa** [comment]
Joining with this. Every Revit launch

**Comment by jmcouffin** [comment]
You may want to try one of the WIP installers under the action tab in the repo
https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725

**Comment by jmcouffin** [comment]
No detailed added. 
Closing for now, feel free to reopen
