### ISSUE TITLE
View Renumbering tool

### ISSUE THREAD

**Issue by teflaherty67** [eirannejad/pyRevit#1713]
What happened to the view renumbering tool that used to be under Sheets? I could pick the views in the order I wanted them numbered on the sheets and it would automatically renumber them in the order I picked them.

**Comment by Robbo1234** [comment]
![image](https://user-images.githubusercontent.com/8776947/214605844-1408d403-17ac-4224-88f2-683d765caf54.png)

**Comment by teflaherty67** [comment]
What version do you have? This is the latest version; I just installed it.

![image](https://user-images.githubusercontent.com/67797311/214607438-bf170c50-ce40-495d-b256-b39c64b671d1.png)

**Comment by jmcouffin** [comment]
in the latest version it has been removed and added to the Renumber tool as per https://github.com/eirannejad/pyRevit/pull/1483
