### ISSUE TITLE
pyRevit fails to load

### ISSUE THREAD

**Issue by omullikin** [eirannejad/pyRevit#1717]
pyRevit was previously working fine, now I receive this error upon opening Revit 2020 and 2022 (see screenshots).

![IronPython_Error1](https://user-images.githubusercontent.com/124175714/216083056-d4efba3b-f207-49f4-a9f0-9d2b25d7dd41.jpg)

![IronPython_Error2](https://user-images.githubusercontent.com/124175714/216083099-0f04f834-5fb7-4afd-b3a3-0a5f6e516c59.jpg)

I have attempted many fixes such as reinstall, changing engine, updating IronPython manually. None of them have worked. Can't even get to pyRevit interface to try and fix through there - doesn't show up at all or load.

Any help would be greatly appreciated. Thank you in advance.

 - Windows 10
 - pyRevit Version 4.8.12.22247
 - pyRevit Environment:
``` ==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
Unknown | Product: "Autodesk Revit 2023" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2023\pyRevit.addin"
Unknown | Product: "Autodesk Revit 2022" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2022\pyRevit.addin"
Unknown | Product: "2020.2.6" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2020\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\omullikin\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.1.10.4 | Build: 20221122_1550(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2020.2.6 | Version: 20.2.60.15 | Build: 20211019_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages```

**Comment by jmcouffin** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/1706
See proposed solutions https://github.com/eirannejad/pyRevit/issues/1672
a very recurrent pattern in the past year or so is this https://github.com/eirannejad/pyRevit/issues/1666#issuecomment-1327442288 see also previous comment of this issue and try the proposed solutions

**Comment by omullikin** [comment]
> Similar to #1706 See proposed solutions #1672 a very recurrent pattern in the past year or so is this [#1666 (comment)](https://github.com/eirannejad/pyRevit/issues/1666#issuecomment-1327442288) see also previous comment of this issue and try the proposed solutions

I tried everything and adding the 0 in front of pyRevit.addin seems to have done the trick. I'm both happy and upset that it was something so simple...
