### ISSUE TITLE
Family Load Types: Keyboard Filters

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#172]
Keyboard Filters
Also Revit 2017 introduced keyboard filtered searches. Are those difficult to implement? Example you type 8 and the list only shows types that have an 8 in them. You type W8 and it filters to only show families that have the W8s in them.

**Comment by eirannejad** [comment]
Implemented:
https://github.com/eirannejad/pyRevit/commit/8ac12042c0ba0c6638fde12a704c90f5c72a4f2c
