### ISSUE TITLE
Filter and Sort menus won't open/display

### ISSUE THREAD

**Issue by mkritsch** [eirannejad/pyRevit#1723]
**Describe the bug**

**To Reproduce**
1. Go to https://uxcelerate.notion.site/uxcelerate/Meet-uxcelerate-6c2a9a916f62426aa45af411742d080c in a web browser
2. Hover over the Gallery to see the Filter and Sort buttons
3. Click Filter or Sort
4. See how Filter or Sort buttons attempt to display a menu, but only show a thin white box with a shadow.

**Expected behavior**
1. Filter and/or Sort options should display on the public web page.
2. They DO display as expected in the Notion desktop app
3. They DO display as expected when logged into Notion on the web

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [MacOS 13.0.1]
 - Browsers: Chrome, Firefox, Safari (latest versions)

**Screenshot**
<img width="325" alt="Screenshot 2023-02-04 at 2 44 28 PM" src="https://user-images.githubusercontent.com/28765567/216786814-716a196d-577d-4f20-b200-149e9a01ec26.png">

**Comment by jmcouffin** [comment]
Wrong place, this is not a Notion repository but pyRevit's
