### ISSUE TITLE
Standardize output of apostrophe and left single quotation mark ( ' vs ’ )

### ISSUE THREAD

**Issue by Ermanresu** [eirannejad/pyRevit#1727]
When typing ' (apostrophe, U+0027), it shows as a ’ (left single quotation mark, U+2018) in most places. This is true in pages, text properties, title properties, comment fields and likely more. But in relation and formula properties, it shows as an apostrophe, as it should. This is inconvenient when searching in the "link a page" field for relations with the year in the title, '23 vs ’23

I suggest that the apostrophe button shows an apostrophe in all of Notion. I am using Norwegian keyboard settings.

**Comment by jmcouffin** [comment]
wrong repo @Ermanresu 
This is not a repo for logging Notion issues even though google tends to point toward it.
