### ISSUE TITLE
Export Family Config Fails

### ISSUE THREAD

**Issue by DarkElephantDesignTech** [eirannejad/pyRevit#1732]
**Describe the bug**
Export Family Config fails with errors.

**To Reproduce**
1. Open a door family
2. Click on Family drop-down, then "Export Family Config"
3. Select location and parameters to export

**Expected behavior**
A YAML file generated with family parameters

**Screenshots**
![image](https://user-images.githubusercontent.com/31526019/218756315-85590ed2-44de-49a8-b5de-4765c28a23e3.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - pyRevit Version 4.8.12.22247
 - pyRevit Environment:
 `==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\ykaranfil\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\ykaranfil\AppData\Roaming\pyRevit-Master" | AllUsers
master | Product: "Autodesk Revit 2020" | Engine: IPY277 (277) | Path: "C:\Users\ykaranfil\AppData\Roaming\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\ykaranfil\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.0.20.21 | Build: 20220726_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2020 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages`
`pyrevit env`

Choosing different parameters doesn't seems to make a difference.

**Comment by jmcouffin** [comment]
@DarkElephantDesignTech revit 2023

**Comment by DarkElephantDesignTech** [comment]
> @DarkElephantDesignTech revit 2023

Correct, seems to work OK on Revit 2020.

**Comment by jmcouffin** [comment]
Fixed by 1793
Might require some extensive testing
