### ISSUE TITLE
Reloading dwg links resets or changes orientation of dwg

### ISSUE THREAD

**Issue by bodgeybodgeybodgey** [eirannejad/pyRevit#1734]
As per title.

**Comment by jmcouffin** [comment]
Never got this issue so far 
@bodgeybodgeybodgey specific Revit version?
Pinned links or unpinned?

**Comment by thumDer** [comment]
This is not related to pyrevit, this is a long known OOTB Revit bug.
https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Revit-Linked-CAD-position-and-orientation-is-reset-if-inserted-in-Scope-box-reoriented-view.html
https://www.revitforum.org/node/448886
