### ISSUE TITLE
Errors in Dynamo Python Script.

### ISSUE THREAD

**Issue by auron85** [eirannejad/pyRevit#1735]
When I add the path in "Custom Extension Directories" to my panel, after that Dynamo Python Script (CPython3) nodes stop working. When I change the Python2 engine, the script does not throw an error. When I remove the path and reload Revit everything works. Tried on three PCs (Wn10, Wn11) the result is the same. In my panel, there is one button on Dynamo Script.

**Steps:**
1. Install PyRevit;
2. I start Revit;
3. I go to the PyRevit settings;
4. I add the path "Custom Exstension Directories" and save.
5. Restart Revit;
6. I launch Dunamo and create a script;
7. I add a Python Script node and immediately see an error (see pic)

**Desktop:**
Windows 10 Pro 22H2 (19045.2604)
Revit 2023.1
pyRevit v4.8.12,
Revit 2023.1
Dynamo 2.16 + CPython 3.9.12

**Screenshots**

Screenshot of error **when** hosting Dynamo node Python Script **(CPython3)**
![Err1](https://user-images.githubusercontent.com/77568490/219362601-f38e22b9-0b73-4663-91fb-75f73eeb2900.JPG)

Class access test **with** Custom Extension Directories **(CPython3)**
![MyTestClass_CPython3_custom pan ON](https://user-images.githubusercontent.com/77568490/219363478-4444eecf-fb53-4f2e-b4b2-421a69ec091c.JPG)
Class access test **with** Custom Extension Directories **(Python2)**
![MyTestClass_Python2_custom pan ON](https://user-images.githubusercontent.com/77568490/219363744-7db76173-b9d7-4126-a9b4-5afc6844a335.JPG)

Class access test **without** Custom Extension Directories  **(CPython3)**
![MyTestClass_CPython3_custom pan OFF](https://user-images.githubusercontent.com/77568490/219365472-4e05e88b-8a8e-4100-9286-75f440ebb6ac.JPG)

Class access test **without** Custom Extension Directories  **(Python2)**
![MyTestClass_Python2_custom pan OFF](https://user-images.githubusercontent.com/77568490/219365891-abe4050d-e5c9-492f-a4ee-5a2ba8b5cf3b.JPG)

**pyrevit env**
![env](https://user-images.githubusercontent.com/77568490/219360841-2bfff90f-dce1-4c5b-8543-5d065e272106.JPG)

**Comment by sanzoghenzo** [comment]
Hi @auron85 , sorry for the late response.
Unfortunately your description lacks some information needed to help you:

- Which path do you add in the "Custom Extension directories"?
- is it a personal extension?
- What is inside it?
- Do you use python3 scripts or invoke DLL in your extension?
- Do you use hooks that run scripts automatically on startup or other events?
- What is the code you're trying to run in Dynamo? or does it happens even with a simple script such as `OUT=IN`?
