### ISSUE TITLE
Config Minify Revit UI doesn't work properly while Enabled

### ISSUE THREAD

**Issue by Drodericson** [eirannejad/pyRevit#1744]
**Describe the bug**
When you Shift+click on [Minify Revit UI] to open config while enabled, config can only hide additional ribbon tabs, it can't exclude tabs from being minified unless [Minify Revit UI] is disabled. So to change the minified tabs, you need to disable Minify, change the config, then enable it again. You should be able to change the config without having to disable and re-enable.

**To Reproduce**
1. Configure [Minify Revit UI]
2. Enable [Minify Revit UI]
3. Configure [Minify Revit UI] while enabled.
4. Note that any newly checked ribbon tabs will be hidden (correct), while any unchecked tabs will not be unhidden (incorrect)

**Expected behavior**
I expect any ribbon tabs checked/unchecked to be enabled/disabled, regardless of whether [Minify Revit UI] is enabled or not.

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - pyRevit v4.8.12.22247+0031
 - '''==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
Unknown | Product: "Autodesk Revit 2023" | Manifest: "C:\Users\Markus\AppData\Roaming\Autodesk\Revit\Addins\2023\pyRevit.addin"
Unknown | Product: "2022.1.1" | Manifest: "C:\Users\Markus\AppData\Roaming\Autodesk\Revit\Addins\2022\pyRevit.addin"
Unknown | Product: "2021.1.2" | Manifest: "C:\Users\Markus\AppData\Roaming\Autodesk\Revit\Addins\2021\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Markus\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.1.1.24 | Build: 20221114_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022.1.1 | Version: 22.1.10.541 | Build: 20211103_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021.1.2 | Version: 21.1.20.44 | Build: 20201109_1530(x64) | Language: 1033 | Path: "Revit 2021\"
==> Running Revit Instances
PID: 2640 | 2022.1.1 | Version: 22.1.10.541 | Build: 20211103_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2022"
PID: 28640 | 2022.1.1 | Version: 22.1.10.541 | Build: 20211103_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2022"
==> User Environment
Microsoft Windows 10 [Version 10.0.19044]
Executing User: Markus
Active User: Markus
Admin Access: Yes
%APPDATA%: "C:\Users\Markus\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v4.8
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.12.22247+0031'''

`pyrevit env`

**Additional context**
Let it also be noted that [Minify Revit UI] is disabled every time you open a new instance of Revit, or close and re-open your current instance of Revit. This seems like it may be related, but I am unsure.

**Comment by thumDer** [comment]
Regarding the state of the Minify tool on opening Revit our solution was to make an `app-init.py` hook in our extensions `hooks` directory (see: [hooks](https://pyrevitlabs.notion.site/Extension-Hooks-b771ecf65f6a45fe87ae12beab2a73a6#7b82529c00194adfacd9f6e1dffb5671)) with the following content:
```python
# -*- coding: UTF-8 -*-
"""ApplicationInitalized hook"""

from __future__ import print_function
from pyrevit import script, revit, EXEC_PARAMS
from pyrevit.loader import sessionmgr

from Autodesk.Revit import UI

logger = script.get_logger()

try:
    mifyui_id = UI.RevitCommandId.LookupCommandId(
        'CustomCtrl_%CustomCtrl_%pyRevit%Toggles%MinifyUI'
    )

    UI.UIApplication(__revit__).PostCommand(mifyui_id)
    logger.info('Successfully executed MinifyUI')

except:
    logger.error('Unhandled Exception', exc_info=1)

```

**Comment by Robbo1234** [comment]
Just wondering will this fix be rolled out in the next release of RyRevit? Thanks

**Comment by Robbo1234** [comment]
Any update on this? @eirannejad @jmcouffin 

Thanks

**Comment by VictorAB94** [comment]
> Regarding the state of the Minify tool on opening Revit our solution was to make an `app-init.py` hook in our extensions `hooks` directory (see: [hooks](https://pyrevitlabs.notion.site/Extension-Hooks-b771ecf65f6a45fe87ae12beab2a73a6#7b82529c00194adfacd9f6e1dffb5671)) with the following content:
> 
> ```python
> # -*- coding: UTF-8 -*-
> """ApplicationInitalized hook"""
> 
> from __future__ import print_function
> from pyrevit import script, revit, EXEC_PARAMS
> from pyrevit.loader import sessionmgr
> 
> from Autodesk.Revit import UI
> 
> logger = script.get_logger()
> 
> try:
>     mifyui_id = UI.RevitCommandId.LookupCommandId(
>         'CustomCtrl_%CustomCtrl_%pyRevit%Toggles%MinifyUI'
>     )
> 
>     UI.UIApplication(__revit__).PostCommand(mifyui_id)
>     logger.info('Successfully executed MinifyUI')
> 
> except:
>     logger.error('Unhandled Exception', exc_info=1)
> ```

Where do you paste this code? Would it be to boot automatically when starting the revit?

**Comment by thumDer** [comment]
check this out: https://pyrevitlabs.notion.site/Extension-Hooks-b771ecf65f6a45fe87ae12beab2a73a6
you'll need to put this in `your.extension/hooks/app-init.py`
it will turn on minify ui everytime you start revit

**Comment by VictorAB94** [comment]
> check this out: https://pyrevitlabs.notion.site/Extension-Hooks-b771ecf65f6a45fe87ae12beab2a73a6 you'll need to put this in `your.extension/hooks/app-init.py` it will turn on minify ui everytime you start revit

it worked, thank you very much. I know it's not the right place, but I'm customizing the toolbars of revit, I wanted to create a customized toolbars of the plugins that I have, the question is: How to make pyrevit execute a revit command or execute a shortcut?

# IMPORTS
from Autodesk.Revit.DB import *

# FUNCTIONS
***run a revit command, "creat wall" "plugin command"

**Comment by jmcouffin** [comment]
@VictorAB94 please do not piggy back on issues. Especially when it is not related.
It is already hard enough to follow everything.
You will find loads of answers on the forum, this one for example:
https://discourse.pyrevitlabs.io/t/open-revit-command-in-my-own-toolbar/1782/14

Look also on Jeremy tammick's  blog and in the docs to get a grasp of system postable commands vs external commands

**Comment by veryshinything** [comment]
Hi,

With pyRevit-Master moving to Program Files, is there a workaround for the app-init method when the user doesn't have permissions?

**Comment by tay0thman** [comment]
Issue resolved in the latest WIP
