### ISSUE TITLE
 Content Button Bundle - “Marker ●”

### ISSUE THREAD

**Issue by Manuel-486** [eirannejad/pyRevit#1745]
Hello.
I created a content button using a Revit family. Now after the name there is a ●. 
There are three files in my Druckknopfmelder.content folder.
a family with the extension _content.rfa.
a bundle.yaml with title, tooltip and author.
the third file is icon.png.
The button in revit also doesn’t show a shift-click option.
its like the isolate button in the pyrevit ribbon selection. There is a point behind the name but it shows no shift click option.

Jean-Marc from the pyrevit forum recommended that I open an issue about it. here the link
https://discourse.pyrevitlabs.io/t/content-button-bundle-marker/1468

Greets 
Manuel-486

![23-03-02_Content-Button-Marker](https://user-images.githubusercontent.com/126765811/222385524-2a3b014f-5ce6-471e-98ec-6be80ef19009.JPG)

**Comment by jmcouffin** [comment]
Tried it on my side, 
with or without a *other.rfa file, the behaviour is the same:
- dot next to the button
- on shift+click+button cannot find target

**Comment by jmcouffin** [comment]
Looked at it and tried to fix it in the components.py https://github.com/jmcouffin/pyRevit/blob/bda51630f74329335f4439eb20dbec269066c6b5/pyrevitlib/pyrevit/extensions/components.py#L158 and following
but to no avail

**Comment by jmcouffin** [comment]
Fixed by https://github.com/eirannejad/pyRevit/pull/1747
