### ISSUE TITLE
Content Button Bundle - Family name and placement

### ISSUE THREAD

**Issue by Manuel-486** [eirannejad/pyRevit#1746]
Hi.
I created a content button for the first time. It works but I have two problems or suggestions for improvement. 
The file is only recognized if "_content.rfa" is at the end. However, this ending is also in the family when it is inserted in Revit. 
![23-03-02_Content-Button-Family-Name](https://user-images.githubusercontent.com/126765811/222412071-06242214-af97-4271-a07e-e4bd62659848.JPG)
It would be nice if it wasn't at the end of the family name. 

The second problem is when I drag a family from the file explorer in revit 
I have the option to choose whether to place the family on a face or the work plane. 
![23-03-02_Content-Button-Place-Family](https://user-images.githubusercontent.com/126765811/222412164-08d27e77-b6a8-40fd-a8ed-937c980c63f2.JPG)
If I insert it via the content button, I don't have this option.
It stays in my toolbar and everything is greyed out and I can just drop the family.

Greets
Manuel-486

**Comment by jmcouffin** [comment]
I will close this one et refer to #1809 for future dev of this enhancement
