### ISSUE TITLE
Custom Extensions Directories Path enable toggle per Revit version

### ISSUE THREAD

**Issue by DrLicor** [eirannejad/pyRevit#1748]
It would be great to be able to select which Custom Extension Directories PyRevit should load per Revit version.
Right now we have issue that we decided to great a new Ribbon for Revit 2023 due to all the compatibility options between our 'old' scripts from 2021 and before.
However this creates an extra Ribbon in the top of Revit which we would like to get rid of. Right we do have a workaround with the minify UI tool, however this doesn't prevent PyRevit from loading our Ribbons. It also seems to not save the settings (is this the expected behaviour).
Although it's a small feature, it would be great to change this setting in between versions ;)

**Comment by jmcouffin** [comment]
Why not managing the version handling process in each script instead?
You could also attach a different clone of pyrevit to each version each including a specifing folder for each extension version

**Comment by DrLicor** [comment]
Thanks for the reply. That's what we have been doing in the past, which worked pretty well. Most of the scripts are Dynamo files, which makes it tricky but it was possible.
Due to the new Dynamo version, UI/UX overhaul it extermely hard to get it all working again. Saving a file in Dynamo for R2023 won't always be openable in Dynamo for R2021, even if it's only saved with no changes made :/

**Comment by veryshinything** [comment]
Hi,

I'd like to bring this up again and ask for the functionality once more.  With the 2025 .net update as an example, from the perspective of a dynamo scripter, I'm trying to plan new workaround.  Between the ironpython and .net updates together the scripts are becomes almost fully incompatible and it would be much easier if i could point 22-24 at one folder and 25 at another folder like I do with my package library.
