### ISSUE TITLE
ERROR: [pyrevit.loader.uimaker] - iteration over non-sequence of type NoneType

### ISSUE THREAD

**Issue by pabloderen** [eirannejad/pyRevit#175]
Happends when loading pyRevit window popup
Revit 2017.2 french locale

ERROR: [pyrevit.loader.uimaker] Error initializing smart button: <type_id '.smartbutton' name 'Toggle Revu Filename Popup' @ 'C:/Users/Pablo/extensions/pyRevitTools.extension/pyRevit.tab/Drawing Set.panel/Print.pulldown/Toggle Revu Filename Popup.smartbutton'> | iteration over non-sequence of type NoneType

**Comment by eirannejad** [comment]
@pabloderen This was resolved as part of https://github.com/eirannejad/pyRevit/issues/174.
Are you using the most recent pyRevit version?

**Comment by pabloderen** [comment]
fresh install and core updated by upgrade.bat and everything is working
