### ISSUE TITLE
Manage Keynotes causes "Wait for unlock timeout" error and locks keynote file

### ISSUE THREAD

**Issue by haroldmDR** [eirannejad/pyRevit#1750]
**Describe the bug**
One of our Revit users is getting a "Wait for unlock timeout." error, when attempting to use the Manage Keynotes tool from pyRevit. After exiting out of the error message, the keynote .txt file remains locked and has to be manually unlocked for other users to access using the same tool. I have the Revit journal log file during this time of this issue, but I am unsure where to safely share this (I have sanitized it but there is to much data to catch everything). Related issues to this bug report are #1725, #1584, and #967.
> I have seen a similar issue earlier last year when using pyRevit's Manage Keynotes tool in Revit 2021, but this was resolved with the pyRevit v4.8.10 update. This issue is currently not happening with any project still in Revit 2021 and the user having this issue has recently installed Revit 2022.

**To Reproduce**
1. Start Revit 2022.
2. Open workshared Revit file from BIM 360.
3. Click the Manage Keynotes tool from the pyRevit Tab (note the keynote .txt file is hosted in the same folder as the Revit file on BIM360)
4. Wait 10 second.
5. See "Wait for unlock timeout." error message.
6. Click "Ok".
7. Open the keynote .txt file folder on BIM360 using a Chrome browser.
8. View lock symbol next to the keynote .txt file.
9. Hover over lock symbol to view the username and the time when the Manage Keynotes tool was used.
10. Click the ellipsis next to the keynote .txt file.
11. Click "unlock".
12. Verify no existence of a .lock file.
13. Navigate to the keynote .txt file folder using windows File Explorer through the Autodesk Desktop Connector drive (Autodesk Docs).
14. Verify no existence of a .lock file.
15. Open the keynote .txt file.
16. Verify no additional text between row 3 '...@table(locks_table:"Locks Table")...' and row 4 '...@db(keynotesdb:"pyRevit Keynotes Manager DB")'.
17. Have another user follow the steps 1 through 3 above to verify it follows the expected behavior listed below.

**Expected behavior**
1. The Manage Keynotes editor opens and temporarily locks the keynote .txt file.
2. The user can edit the keynote file using the editor.
3. The Manage Keynotes editors is closed and keynote .txt file is unlocked.
4. Other users are able to follow steps 1 through 3 here.

**Desktop:**
 - OS: Window 10.0.19044.2604
 - pyRevit Version: 4.8.12.22247+0031
 - pyRevit Environment: 
```C:\Users\%USERNAME%>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\%USERNAME%\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\%USERNAME%\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\%USERNAME%\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2021" | Engine: IPY277 (277) | Path: "C:\Users\%USERNAME%\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2020" | Engine: IPY277 (277) | Path: "C:\Users\%USERNAME%\AppData\Roaming\pyRevit-Master"
master | Product: "2018.3.3 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\%USERNAME%\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\%USERNAME%\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.0.20.21 | Build: 20220726_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
Autodesk Revit 2021 | Version: 21.1.70.21 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
Autodesk Revit 2020 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

**Additional context**
This same issue has happened with another user in the same model with the same version settings, after their Revit file crashed unexpectedly when they were using the Manage Keynotes tool from pyRevit (the crash report of journal entry was not saved at this time). While troubleshooting, the following steps were taken:
1. A new copy of pyRevit was installed.
2. Autodesk Desktop Connector was updated. 
6. Verified that all Revit 2022 hot-fixes were installed. 
7. Installed the "Issues Addin v5.0.6 for Revit 2022" update.
8. Power cycled the computer
After following those steps, this user was able to use the Manage Keynotes tool from pyRevit as expected (see Expected behavior above). The user having the issue in this bug report followed the same troubleshooting steps but the issue (see Describe the bug above) keeps happening.

**Comment by haroldmDR** [comment]
> We are having the same issue. We've followed steps 1-17, but as soon as a user clicks Manage Keynotes the error pops up. Any further suggestions?

@BIMyaneff I'm just curious but, if you're working on a BIM 360 project, what version of desktop connector are you using? 
We are waiting to upgrade to version 16 to make sure older projects don't need BIM 360 teams.

**Comment by BIMyaneff** [comment]
It is an ACC BIM Collaborate Pro project. We all have Desktop Connector 15.8.0.1827. We do have one other project on BIM 360 though so cannot go to 16 yet.

**Comment by jabarig** [comment]
We recently ran into a similar issue in 2023, but a colleague solved it by deleting some of the pyRevit code at the top of the .txt file. After removing that code and reloading the keynote the "Manage Keynotes" tool works perfectly.

**Comment by spacedsnake** [comment]
We have been running into a couple slightly different issues with the keynote manager recently.  Wondering is it has to do with updated workflow that Bim360/Autodesk docs is using. 
1. Keynote file location on Bim360 seems to be getting locked in the Bim360 side and gets stuck. It seems like this is causing people to overwrite each other or keynote edits not being saved.   I need to dig into this a bit more with the team to figure out exactly the group workflow is to cause this problem.  When I test by myself I don't see any issues.
![image](https://github.com/eirannejad/pyRevit/assets/17059467/881254d2-09ff-47f8-ba95-6f120b83261f)

2. Revit is always throwing the updated resource notification when printing.  Not a big deal when printing through Rveit dialog as it just pops up once.  But if we print through Diroots is causes a lot of problems
<img width="293" alt="image" src="https://github.com/eirannejad/pyRevit/assets/17059467/638e0135-8147-40ab-b252-dea398731a96">
