### ISSUE TITLE
sort 'List Legends on Sheets' by Sheet Number (after Legend Name)

### ISSUE THREAD

**Issue by RevitIRL** [eirannejad/pyRevit#1759]
**Is your feature request related to a problem? Please describe.**
I want to know the ramifications of editing a Legend (i.e. what sheets it will affect)

**Describe the solution you'd like**
'List Legends on Sheets' has been working great and is very helpful, but I usually am just interested in one legend, and then want to go down the list of sheets that it's on (to see if the change I'm making applies to all), and that's usually easier to do if the sheets are in order.

**Describe alternatives you've considered**
Copy-paste results and sort somewhere else (Excel), or just not (for short lists).

**Additional context**
https://github.com/eirannejad/pyRevit/issues/1702

**Comment by jmcouffin** [comment]
Fixed by #1760 #1761 
Available in a bit here https://github.com/eirannejad/pyRevit/actions/runs/4424367759
