### ISSUE TITLE
Views of Elements - Idea for Improvement

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#176]
What do you think about having a pop-up that appears when a user runs the "Views of Elements Button".

Here is what I am thinking:
"Do you want to see all views or only views placed on a sheet?"
Two Buttons:  "Sheeted views only"    "All Views in Project"

**Comment by eirannejad** [comment]
Makes sense. I'll revise the script soon. Just to be clear we're talking about `Find Views Showing Selected Element` button under `Inspect` pulldown right?

**Comment by thazell** [comment]
My mistake, you are correct.

**Comment by thazell** [comment]
for our office, I updated this filter on line 33 
to only search views on sheets.  
views = filter(lambda x: ((x.ViewType != ViewType.DraftingView or x.ViewType != ViewType.ThreeD) and not x.IsTemplate and x.get_Parameter(BuiltInParameter.VIEWPORT_SHEET_NUMBER).HasValue),allviews)

**Comment by eirannejad** [comment]
Added `Inspect > Find Sheets Showing Selected Elements` reporting linkified list of sheets and views that show any of the selected elements

https://github.com/eirannejad/pyRevit/commit/6701ac3148b893b787c298cf62ca22c363253c07

![2017-05-12 15_39_07-find sheets showing selected element](https://cloud.githubusercontent.com/assets/8197916/26019304/46ce2e00-3729-11e7-8a5e-7e458ce839ec.png)

**Comment by thazell** [comment]
That's cool!  I haven't seen the linkified display before. Nice work!

**Comment by eirannejad** [comment]
Yeah that linkify makes my life so much easier. Glad you like it. Sorry again for the delay. Things been a little hectic here.

**Comment by eirannejad** [comment]
v4.5rc is available now:
http://eirannejad.github.io/pyRevit/pyrevit/update/2017/12/02/45rc.html
