### ISSUE TITLE
sort 'List Legends on Sheets' by Sheet Number (after Legend Name) [clarified]

### ISSUE THREAD

**Issue by RevitIRL** [eirannejad/pyRevit#1766]
**Is your feature request related to a problem? Please describe.**
I want to know the ramifications of editing a Legend (i.e. what sheets it will affect)

**Describe the solution you'd like**
'List Legends on Sheets' has been working great and is very helpful, but I usually am just interested in one legend, and then want to go down the list of sheets that it's on (to see if the change I'm making applies to all), and that's usually easier to do if the sheets are in order.

**Sorry, I guess I didn't communicate clearly in #1759, but the added "Sheets" option dialog isn't needed (and would be confusing) - see the 2nd attached screenshot. Sorting by Legend is shown in the 1st attached screenshot, but it appears to be sorting by Sheet ID after Legends (which is the order they were created - i.e. S230 was created last, so it sorts after S236) but I'd like it to sort by sheet number instead (for 2nd sort, not 1st sort) - red marks in 1st screenshot show what I mean.**

**Describe alternatives you've considered**
Copy-paste results and sort somewhere else (Excel), or just not (for short lists).

**Additional context**
https://github.com/eirannejad/pyRevit/issues/1702
https://github.com/eirannejad/pyRevit/issues/1759

![image](https://user-images.githubusercontent.com/20117305/226498104-4db94ddc-53d2-4d7c-9d04-83527664f135.png)
![image](https://user-images.githubusercontent.com/20117305/226498842-a150c3a1-c44a-44f0-bbd8-5e88bfa38742.png)

**Comment by jmcouffin** [comment]
fixed by #1768
