### ISSUE TITLE
Arrangement of the icons

### ISSUE THREAD

**Issue by ferilive** [eirannejad/pyRevit#1775]
**Describe the bug**
Why is the arrangement of the icons that I have made with pyRevit for my personal plugin not suitable for the Yaml files?
And every time I open Revit again, the layout gets messed up and I have to reload again.

**To Reproduce**
1. Go to 'pyRevit'
2. Click on 'Setting'
3. Click on  'Save Settings and Reload'
or
2. Click on 'Reload'

**Expected behavior**
The layout of the icons should be in accordance with Yaml files.

**Screenshots**
![image](https://user-images.githubusercontent.com/99180907/227871654-fe2d740a-44cb-4bfd-8b59-738fd8f396f6.png)
![image](https://user-images.githubusercontent.com/99180907/227874238-7bf633ce-b9fd-43b4-8a55-db90586cf940.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Enterprise, 22H2]
 - pyRevit Version [4.8.12.22247+0031]
 - pyRevit Environment:
 ```
 C:\Users\farzad.darash>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\farzad.darash\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\farzad.darash\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
Development Tools | Type: Unknown | Repo: "" | Installed: "H:\Dev_Tools_0.0.0\extensions\Development Tools.extension"
Help | Type: Unknown | Repo: "" | Installed: "H:\Feri_Tools_0.7.0\extensions\Help.extension"
Mains | Type: Unknown | Repo: "" | Installed: "H:\Feri_Tools_0.7.0\extensions\Mains.extension"
Views | Type: Unknown | Repo: "" | Installed: "H:\Feri_Tools_0.7.0\extensions\Views.extension"
Warning | Type: Unknown | Repo: "" | Installed: "H:\Feri_Tools_0.7.0\extensions\Warning.extension"
==> Default Extension Search Path
C:\Users\farzad.darash\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
H:\Feri_Tools_0.7.0\extensions
H:\Dev_Tools_0.0.0\extensions
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.1.10.4 | Build: 20221122_1550(x64) | Language: 1033 | Path: "C:\Programme\Autodesk\Revit 2023\"
==> Running Revit Instances
Error: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
```

**Additional context**
It should be mentioned that I developed the plugin over time and some scripts were added among the existing scripts and I also changed the Ymal files accordingly.

**Comment by jmcouffin** [comment]
Please, do provide the yaml file in question and a screen capture of folders names
It does work as expected, but you need to be careful with the syntax of the yaml

As an example, mine looks like:
```yaml
layout:
  - Infos
  - MàJ
  - Color
  - Contrôle Qualité
  - Familles
  - Paramètres
  - Pièces
  - Remplacer
  - Sous-projets
  - Vue
  - MEP
  - STM
  - Ville de Québec
  - PFT
  - test
```

while my folders are 
![image](https://user-images.githubusercontent.com/7872003/227888951-a07f73a4-6cbc-415b-8c96-593360bd73e8.png)

and you can see my toolbar follows the yaml, and not the alphabetical order.
![image](https://user-images.githubusercontent.com/7872003/227889304-ccd02a38-861b-4342-95e1-f080187b6f59.png)

you could check the yaml online with https://www.yamllint.com/

Also a note, sometimes the changes in the UI are not perfect after a reload, but restarting Revit will ensure you it shows as expected IF the yaml structure is fine

**Comment by ferilive** [comment]
I don't think the problem is with the ymal files; Because when I reload the pyRevit, the panels are arranged correctly based on the ymal files; But in case of completely closing the Revit or restarting the system; The order of the panels is messed up again.

...\extensions\:
![image](https://user-images.githubusercontent.com/99180907/227937379-0eb527ec-70cb-4fb5-847a-481c03fe1784.png)

...\extensions\Views.extension\X.tab:
![image](https://user-images.githubusercontent.com/99180907/227939065-c526e43b-c406-4556-80bd-16d21257258d.png)
```
layout:
  - Ansichtsvorlagen[beforeall:]
```

...\extensions\Mains.extension\X.tab:
![image](https://user-images.githubusercontent.com/99180907/227939569-03ae94d8-27a9-4094-a38c-de70400c7701.png)
```
layout:
  - Automatisierung und Skripte
  - Außenanlagen
  - Export
  - Brandschutzplanung
```

...\extensions\Warning.extension\X.tab:
![image](https://user-images.githubusercontent.com/99180907/227939753-e3d5bb89-6e08-4258-a951-5217e2727de7.png)
```
layout:
  - Warnungen[before:Hilfe]
```

...\extensions\Warning.extension\X.tab:
![image](https://user-images.githubusercontent.com/99180907/227939962-af2a604d-73fa-447b-bc94-ff77ca3e2255.png)
```
layout:
  - Hilfe[afterall:] 
```

**Comment by ferilive** [comment]
I don't think the problem is with the ymal files; Because when I reload the pyRevit, the panels are arranged correctly based on the ymal files; But in case of completely closing the Revit or restarting the system; The order of the panels is messed up again.

...\extensions\:
![image](https://user-images.githubusercontent.com/99180907/227937379-0eb527ec-70cb-4fb5-847a-481c03fe1784.png)

...\extensions\Views.extension\X.tab:
![image](https://user-images.githubusercontent.com/99180907/227939065-c526e43b-c406-4556-80bd-16d21257258d.png)
```
layout:
  - Ansichtsvorlagen[beforeall:]
```

...\extensions\Mains.extension\X.tab:
![image](https://user-images.githubusercontent.com/99180907/227939569-03ae94d8-27a9-4094-a38c-de70400c7701.png)
```
layout:
  - Automatisierung und Skripte
  - Außenanlagen
  - Export
  - Brandschutzplanung
```

...\extensions\Warning.extension\X.tab:
![image](https://user-images.githubusercontent.com/99180907/227939753-e3d5bb89-6e08-4258-a951-5217e2727de7.png)
```
layout:
  - Warnungen[before:Hilfe]
```

...\extensions\Warning.extension\X.tab:
![image](https://user-images.githubusercontent.com/99180907/227939962-af2a604d-73fa-447b-bc94-ff77ca3e2255.png)
```
layout:
  - Hilfe[afterall:] 
```

**Comment by ferilive** [comment]
I don't think the problem is with the ymal files; Because when I reload the pyRevit, the panels are arranged correctly based on the ymal files; But in case of completely closing the Revit or restarting the system; The order of the panels is messed up again.

...\extensions\:
![image](https://user-images.githubusercontent.com/99180907/227937379-0eb527ec-70cb-4fb5-847a-481c03fe1784.png)

...\extensions\Views.extension\X.tab:
![image](https://user-images.githubusercontent.com/99180907/227939065-c526e43b-c406-4556-80bd-16d21257258d.png)
```
layout:
  - Ansichtsvorlagen[beforeall:]
```

...\extensions\Mains.extension\X.tab:
![image](https://user-images.githubusercontent.com/99180907/227939569-03ae94d8-27a9-4094-a38c-de70400c7701.png)
```
layout:
  - Automatisierung und Skripte
  - Außenanlagen
  - Export
  - Brandschutzplanung
```

...\extensions\Warning.extension\X.tab:
![image](https://user-images.githubusercontent.com/99180907/227939753-e3d5bb89-6e08-4258-a951-5217e2727de7.png)
```
layout:
  - Warnungen[before:Hilfe]
```

...\extensions\Warning.extension\X.tab:
![image](https://user-images.githubusercontent.com/99180907/227939962-af2a604d-73fa-447b-bc94-ff77ca3e2255.png)
```
layout:
  - Hilfe[afterall:] 
```

**Comment by ferilive** [comment]
I don't think the problem is with the ymal files; Because when I reload the pyRevit, the panels are arranged correctly based on the ymal files; But in case of completely closing the Revit or restarting the system; The order of the panels is messed up again.

...\extensions\:
![image](https://user-images.githubusercontent.com/99180907/227937379-0eb527ec-70cb-4fb5-847a-481c03fe1784.png)

...\extensions\Views.extension\X.tab:
![image](https://user-images.githubusercontent.com/99180907/227939065-c526e43b-c406-4556-80bd-16d21257258d.png)
```
layout:
  - Ansichtsvorlagen[beforeall:]
```

...\extensions\Mains.extension\X.tab:
![image](https://user-images.githubusercontent.com/99180907/227939569-03ae94d8-27a9-4094-a38c-de70400c7701.png)
```
layout:
  - Automatisierung und Skripte
  - Außenanlagen
  - Export
  - Brandschutzplanung
```

...\extensions\Warning.extension\X.tab:
![image](https://user-images.githubusercontent.com/99180907/227939753-e3d5bb89-6e08-4258-a951-5217e2727de7.png)
```
layout:
  - Warnungen[before:Hilfe]
```

...\extensions\Warning.extension\X.tab:
![image](https://user-images.githubusercontent.com/99180907/227939962-af2a604d-73fa-447b-bc94-ff77ca3e2255.png)
```
layout:
  - Hilfe[afterall:] 
```

**Comment by alexdaversa** [comment]
Can you confirm if you have a yaml file in your extensions directory, and if not, can you confirm if making one listing the desired order of folders fixes the issue? If possible, it may work more consistently to include all of the tools in one extension, one tab, and multiple panels, with yaml specifying the order of the panels.

**Comment by jmcouffin** [comment]
@ferilive I will close this issue until further information is provided to understand if it is a bug or question of wrong usage of the features
