### ISSUE TITLE
Revit 2022 wont launch with PyRevit 4.8.12 installed, Revit 2023 crashes when 4.8.10 is installed, Can't run the Pattern Maker with 4.6.24. I have tried uninstall/ re-install with all versions. Can you make the 4.7 releases available so I can try to see if they work? Really all we ever use is the pattern maker. If you could package that as a add-in for Revit you could retire.

### ISSUE THREAD

**Issue by VimanaPrakaran** [eirannejad/pyRevit#1778]
**Describe the bug**
Replace these lines with your description. Be as specific as possible and list steps to reproduce the issue. If you have any suggestions for the solution please list that as well.

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - pyRevit Version [e.g. 22]
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

**Additional context**

**Comment by jmcouffin** [comment]
@VimanaPrakaran please submit a more carefully crafted issue
