### ISSUE TITLE
When removing / adding folders for additional scripts, if nothing selected, error thrown

### ISSUE THREAD

**Issue by grantdfoster** [eirannejad/pyRevit#178]
![image](https://cloud.githubusercontent.com/assets/18288572/24715734/8c77e8ac-19fa-11e7-81a9-623eea2f78f9.png)
![image](https://cloud.githubusercontent.com/assets/18288572/24715738/8ec90708-19fa-11e7-8bb8-5e273f0f6500.png)

**Comment by eirannejad** [comment]
Corrected: https://github.com/eirannejad/pyRevit/commit/65d01a0ccf9b808b3623268b35f0b11f9ffea02b
Thank you!!
