### ISSUE TITLE
Error on loading in Revit 2023

### ISSUE THREAD

**Issue by UbuESI** [eirannejad/pyRevit#1782]
**Describe the bug**
Just installed the latest PyRevit off GitHub. I had been running a previous version in Revit 2020-2022, but started using 2023, and it didn't show up. So I installed the latest.

No when I launch 2023, I get an error. Screenshot attached.

<img width="974" alt="PyRevit Error 2023" src="https://user-images.githubusercontent.com/129910240/229944053-71d3f0df-f662-4c0c-8450-6f1b34530ea6.png">

**Desktop (please complete the following information):**
 - OS: Win 10 - all normal updates (it's somewhat managed)
 - pyRevit Version 4.8.1
 - pyRevit Environment: 

"C:\Users\jeremy.lee>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\jeremy.lee\AppData\Roaming\pyRevit-Master"
==> Attachments
Unnamed-363FBF8 | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
Unnamed-363FBF8 | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
Unnamed-363FBF8 | Product: "Autodesk Revit 2021" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
Unnamed-363FBF8 | Product: "Autodesk Revit 2020" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\jeremy.lee\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.1.10.4 | Build: 20221122_1550(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
Autodesk Revit 2021 | Version: 21.1.21.45 | Build: 20201116_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
Autodesk Revit 2020 | Version: 20.2.80.2 | Build: 20220225_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages"

`pyrevit env`

**Additional context**
I launched 2022 and PyRevit seems to work there. It's just giving me this error in 2023.

**Comment by jmcouffin** [comment]
you can try attaching your pyrevit clone/instance properly with this command line:
`pyrevit attach master 2711 --installed --allusers`

**Comment by UbuESI** [comment]
Thanks! I get this when I run that command:

C:\Users\jeremy.lee>pyrevit attach master 2711 --installed --allusers
Error: Access to the path 'C:\ProgramData\Autodesk\Revit\Addins\2021\pyRevit.addin' is denied.
Run with "--debug" option to see debug messages

Is this a windows error, pyrevit issue, or the IT department locking me down?

**Comment by jmcouffin** [comment]
> Thanks! I get this when I run that command:
> 
> C:\Users\jeremy.lee>pyrevit attach master 2711 --installed --allusers Error: Access to the path 'C:\ProgramData\Autodesk\Revit\Addins\2021\pyRevit.addin' is denied. Run with "--debug" option to see debug messages
> 
> Is this a windows error, pyrevit issue, or the IT department locking me down?

Windows or IT I think.

**Comment by UbuESI** [comment]
Thanks. I'll see what IT has to say about this.

**Comment by jmcouffin** [comment]
Closing for now.
You can reopen if needed @UbuESI
