### ISSUE TITLE
Update to Revit 2024

### ISSUE THREAD

**Issue by Addamsovka** [eirannejad/pyRevit#1783]
**Update to a new Revit 2024**

**Comment by ty-pov** [comment]
makes me realise how much i use the plug in since updating to revit 2024, hopefully they update the plug in soon

**Comment by jmcouffin** [comment]
You can download the installers in this repo under the Actions tab>Select one of the latest Workflow and you will find the installers in the artifact section. Most of the tools do work in 2024:
https://github.com/eirannejad/pyRevit/suites/11989975393/artifacts/629413860

**Comment by jmcouffin** [comment]
check the WIP section of this doc for more step by step instructions

**Comment by jmcouffin** [comment]
https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725

**Comment by ty-pov** [comment]
I had previously uninstalled and re install  pyRevit as it doesn’t seem to be recognised with Revit 2024. When I opened Revit 2024 a notepad opened up saying error pyrevit with all this text

**Comment by jmcouffin** [comment]
check out the previous article link.
The actual releases of pyRevit are not working in 2024. Only the latest WIP versions do work
![image](https://user-images.githubusercontent.com/7872003/230011273-49b83b57-56be-45c0-8c47-53483e1be5cc.png)

**Comment by Addamsovka** [comment]
Thanks, in that case, we don't need to look at the pull request. I'll take it down. :)
