### ISSUE TITLE
PyRevit Error on startup

### ISSUE THREAD

**Issue by iOGARRO** [eirannejad/pyRevit#181]
ERROR: [pyrevit.loader.uimaker] Error initializing smart button: <type_id '.smartbutton' name 'Toggle Revu Filename Popup' @path | iteration over non-sequence of type NoneType

**Comment by gtalarico** [comment]
Sames as https://github.com/eirannejad/pyRevit/issues/175 
Are you on latest?

![image](https://cloud.githubusercontent.com/assets/9513968/24929542/5430d11e-1ed4-11e7-95c1-8277a90a4bf9.png)
ps: Hi Ivan!

**Comment by gtalarico** [comment]
@iOGARRO did the update resolve the error?

**Comment by iOGARRO** [comment]
@gtalarico yeah man issue resolved. Thanks for the follow up!
