### ISSUE TITLE
Pyrevit not working (RVT 2024)

### ISSUE THREAD

**Issue by Archixliam** [eirannejad/pyRevit#1810]
**Describe the bug**
I open Revit 2024 and an error pops up saying there is an error loading pyrevit. See below for screenshots.

**To Reproduce**
1. Open Revit

**Expected behavior**
I expected pyrevit to just be loaded in revit like it has in the past. maybe a dialog box the first couple of times revit loads after installing pyrevit.

**Screenshots**
![image](https://user-images.githubusercontent.com/132172207/235327746-02e6d7a5-1fb4-4530-9dbf-1443c327e5c1.png)
![image](https://user-images.githubusercontent.com/132172207/235327820-e9f46b2b-0565-4609-b5a5-06873fd329a3.png)

**Desktop**
 - OS: Windows 10
 - pyRevit Version: latest version downloaded on 30/04/2023
 - pyRevit Environment:
 '''C:\Users\liama>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\liama\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2024" | Engine: IPY277 (277) | Path: "C:\Users\liama\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\liama\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2024 | Version: 24.0.4.427 | Build: 20230308_1635(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages'''
![image](https://user-images.githubusercontent.com/132172207/235328028-1e140d86-c698-4acf-9986-89c481face22.png)

Please note I am not familiar with this type of stuff on PC. Just after a fix for pyrevit please.

**Comment by jmcouffin** [comment]
Please look for 'revit 2204' within closed issues. This question has been answered many times
