### ISSUE TITLE
Revit 2023 - Manage Tags extention not working

### ISSUE THREAD

**Issue by jkcam** [eirannejad/pyRevit#1811]
**Describe the bug**
When clicking on manage tags I get an error.  I have created the DOCTAG parameter.

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

**To Reproduce**
1. Go to pyrevit
2. Click on Manage Tags

**Expected behavior**
The tool should open up

**Screenshots**
![image](https://user-images.githubusercontent.com/104698895/235515390-30cd4a26-0ce4-40bb-af72-f31b72317cb9.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/104698895/235514791-29ace775-eaae-4fe9-b7db-3d75ed32f70d.png)
 - pyRevit Version [e.g. 22]

==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\jkcam\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\jkcam\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\jkcam\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2020" | Engine: IPY277 (277) | Path: "C:\Users\jkcam\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\jkcam\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.1.10.4 | Build: 20221122_1550(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
Autodesk Revit 2020 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages

**Additional context**
Works fine in 2022

**Comment by jmcouffin** [comment]
Related https://github.com/eirannejad/pyRevit/issues/1568
