### ISSUE TITLE
pyRevitLoader - Error Loading pyRevit (different from previously documented bugs?)

### ISSUE THREAD

**Issue by brianorser** [eirannejad/pyRevit#1819]
**Describe the bug**
I have installed pyRevit, and when I open Revit I receive the "pyRevitLoader - Error Loading pyRevit" message. The full error message is attached below, along with my "pyRevit env" report.

I have followed the various debugging solutions, including running "pyrevit attach master 277 --installed" and "pyrevit attach master 2711 --installed --allusers". "pyrevit attach master 2711 --installed --allusers" does seem to help, as it causes the addin to appear in the Revit addins directory. However, it does not solve the problem.

I also checked that I have user access for the appdata directories--they are in fact listed as read-only, but I have switched this attribute off. "Read only" does return however when I open the directory properties again. But I'm not sure this is the issue documented in the attached error message.

Thank you for your assistance. I really hope to resolve this.

**To Reproduce**
1. Install pyRevit
2. Open Revit
3. Receive Error message

**Expected behavior**
I expected to install pyRevit, open Revit, and run pyRevit.

**Screenshots**
![error message 1](https://github.com/eirannejad/pyRevit/assets/19655243/ecf12716-7fb4-4f2b-a2a3-fca1c1df7829)
![error message 2](https://github.com/eirannejad/pyRevit/assets/19655243/00ac5b11-7d33-437e-a2f6-e93478502fc8)
![pyrevit env](https://github.com/eirannejad/pyRevit/assets/19655243/70ead915-1170-4d9b-893a-84698500a7ca)

**Desktop (please complete the following information):**
Please see above screenshot

**Comment by jmcouffin** [comment]
The pyrevit version you installed is not compatible with Revit 2024.
See https://discourse.pyrevitlabs.io/t/pyrevit-support-for-2024/1665

**Comment by brianorser** [comment]
Hi @jmcouffin thank you for this clarification. I'm sorry I missed this obvious incompatibility.

Brian
