### ISSUE TITLE
Error accessing registry key value. | [Errno 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#182]
Posting this for a colleague - error while loading.  
User is on latest 9108de6
Looks like it might still be related to Bluebeam/ #174 ?

![image](https://cloud.githubusercontent.com/assets/9513968/24964068/3d56a618-1f6e-11e7-8ec6-ee2d22378095.png)

Bellow is the surrounding lines from a debug output:

```
DEBUG: [Reload] Checking subkey: 2016/Pushbutton PDF/PageSetup 
DEBUG: [Reload] Looking into subkey for key: 2016/Pushbutton PDF/PageSetup 
DEBUG: [Reload] 2016/Pushbutton PDF/PageSetup reg key has 0 subkeys and 0 values. 
DEBUG: [Reload] Checking subkey: 2016/Pushbutton PDF/TextStampEx 
DEBUG: [Reload] Looking into subkey for key: 2016/Pushbutton PDF/TextStampEx 
DEBUG: [Reload] 2016/Pushbutton PDF/TextStampEx reg key has 0 subkeys and 1 values. 
>>>>>>>>>>>>>>>>>>>>>>>>
ERROR: [Reload] Error accessing registry key value. | [Errno 2] The system cannot find the file specified
>>>>>>>>>>>>>>>>>>>>>>>>
DEBUG: [Reload] Prompt For FileName is Disabled... 
DEBUG: [pyrevit.coreutils.ribbon] Creating uri from: C:/Users/ryan.connolly/AppData/Roaming/pyRevit/pyRevit-v4/pyRevit/extensions/pyRevitTools.extension/pyRevit.tab/Drawing Set.panel/Print.pulldown/Toggle Revu Filename Popup.smartbutton/off.png 
DEBUG: [pyrevit.coreutils.ribbon] Creating 16x16 bitmap from: C:/Users/ryan.connolly/AppData/Roaming/pyRevit/pyRevit-v4/pyRevit/extensions/pyRevitTools.extension/pyRevit.tab/Drawing Set.panel/Print.pulldown/Toggle Revu Filename Popup.smartbutton/off.png 
```

**Comment by eirannejad** [comment]
Would you please verify that this key exists on his machine? The error means that the key exists but the `winreg.QueryValueEx` method can not find/read the value.

`HKCU/Software/Bluebeam Software/2016/Brewery/V45/Printer Driver/PromptForFileName`

**Comment by eirannejad** [comment]
@gtalarico Is this still a problem?

**Comment by gtalarico** [comment]
@eirannejad I don't have it on mine
I have sent my colleague I msg to check, I post back
![image](https://cloud.githubusercontent.com/assets/9513968/25208615/c7259036-2543-11e7-8b78-d11ec9d39043.png)

**Comment by Lwarrior88** [comment]
Hello, 
I encounter the same error while loading. 
How can i verify that this key exist on my machine?
I'm very new to coding and installing this addin was a complex process.

**Comment by gtalarico** [comment]
screenshot of registry:
![image](https://cloud.githubusercontent.com/assets/9513968/25394984/a04cba52-29ad-11e7-8221-0abdf300208d.png)
![image](https://cloud.githubusercontent.com/assets/9513968/25394987/a2b5e944-29ad-11e7-8dac-666e25887043.png)

**Comment by Lwarrior88** [comment]
I work in a office that use multiple Networks.  I'm assuming this can only be access by an Admin.???
This is all i see:
![bluebeam](https://cloud.githubusercontent.com/assets/28010719/25395451/0e3778bc-29af-11e7-9110-f16678e53ada.PNG)

**Comment by eirannejad** [comment]
@Lwarrior88 Screenshots that @gtalarico  shared are from windows registry editor (`regedit.exe`) not a folder structure. Would you be able to check your registry to see if you have this key?

`HKCU/Software/Bluebeam Software/2016/Brewery/V45/Printer Driver/PromptForFileName`

**Comment by Lwarrior88** [comment]
Where do i find this window registry editor?
I'm sorry im very new to this, please have some patience.

**Comment by gtalarico** [comment]
https://www.lifewire.com/how-to-open-registry-editor-2625150

**Comment by eirannejad** [comment]
Disabled error report. This could be a user access issue.
