### ISSUE TITLE
KeyError exception occurring in the PyRevit code

### ISSUE THREAD

**Issue by Zakarya1997** [eirannejad/pyRevit#1820]
I'm trying to install PyRevit version 4.8.12.22247 on Autodesk Revit 2023, but I'm encountering an error with the following traceback: KeyError or KeyNotFoundException. The error occurs in the pyRevitLabs.PythonNet module. I've verified that I have the correct version of Autodesk Revit (2023) installed, but I'm unsure if it is compatible with the specific version of PyRevit (4.8.12.22247) I'm trying to install. Additionally, there might be a possibility that it could be another type of error. I've also ensured that I have the latest Python and IronPython versions installed. How can I identify and resolve this error to successfully install PyRevit version 4.8.12.22247 while ensuring compatibility with Autodesk Revit 2023?

**Comment by jmcouffin** [comment]
Without seeing the log from 'pyrevit env' or the error itself it is kind of hard to guess.

Python or iron python do not need to be installed. 
The two sole components required are Revit and pyRevit

**Comment by Zakarya1997** [comment]
Thank you for your prompt response. I sincerely appreciate the clarification you provided regarding the installation requirements for Revit and pyRevit. It's reassuring to learn that Python or IronPython are not essential for the installation process.

In order to provide a better understanding of the issues I'm encountering, I have attached screenshots of the errors. I hope to provide a clearer understanding of the issue at hand. I am genuinely grateful for your help.

![Schermafbeelding 2023-05-21 220636](https://github.com/eirannejad/pyRevit/assets/80201522/6ae040a0-50ed-4087-8ea9-4c3bdda0eeae)

![Schermafbeelding 2023-05-21 221003](https://github.com/eirannejad/pyRevit/assets/80201522/a2b019bd-4b79-4087-ab8b-3744a8cac73a)

**Comment by jmcouffin** [comment]
Can you show the 'pyrevit env' log 
It seems you have the dev hooks extension enabled. I am wondering if you need it activated for now, starting up with pyrevit?

**Comment by Zakarya1997** [comment]
Yes, I disabled the dev hooks extension and it is indeed working now. I don't think I need it activated while starting up with pyrevit, at least for now. 

Thank you so much for resolving the issue I was facing
