### ISSUE TITLE
PyRevit will not show up in toolbars for Revit 2022

### ISSUE THREAD

**Issue by RiZ3Nola** [eirannejad/pyRevit#1822]
I know this is likely a common topic, that gets multiple threads. I apologize. I did not find a thread for 2022.
I have installed pyRevit, and restarted my computer, but the icon is not showing up. I am not very computer savvy, so I'm a little lost. Any assistance is appreciated.  

I saw in a previous similar post to run "pyrevit env" in the command prompt.  see below. 

C:\Users\zabal>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
Unknown | Product: "2021 First Customer Ship" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2021\pyRevit.addin"
Unknown | Product: "2020.2.6" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2020\pyRevit.addin"
Unknown | Product: "2019 First Customer Ship" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2019\pyRevit.addin"
Unknown | Product: "2018.3.3 Security Fix" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2018\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\zabal\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.6 | Version: 20.2.60.15 | Build: 20211019_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019 First Customer Ship | Version: 19.0.0.405 | Build: 20180216_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
==> Running Revit Instances
PID: 14800 | 2022 First Customer Ship | Version: 22.0.2.392 | Build: 20210224_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2022"
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: ZA-SURFACE-1\zabal
Active User: ZA-SURFACE-1\zabal
Admin Access: No
%APPDATA%: "C:\Users\zabal\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.12.22247+0031

**Comment by jmcouffin** [comment]
I suggest you uninstall, restart, re-install
It seems it does not detect your Revit 2022 installation

Please post the pyrevit env' log again after that

**Comment by jmcouffin** [comment]
You could also try to run 'pyrevit doctor's command before uninstall then try again 2022

**Comment by jmcouffin** [comment]
no reply
closing
