### ISSUE TITLE
Invoke Button - Error

### ISSUE THREAD

**Issue by aniketdikshit** [eirannejad/pyRevit#1824]
Hey Ehsan!
I am having issue with an invoke button in pyRevit 
I get this error when trying to use a class using invoke button through pyrevit for one specific class
![image](https://github.com/eirannejad/pyRevit/assets/83564064/beef5cc4-55e9-4630-9e51-95c737474651)

1.  All other command classes from this dll work fine
2. When I load this as a c# addin - it works fine
3. When I  load this as a c# addin and run it and then try to execute through the pyrevit invoke button  - It works fine for that Revit session
4. It doesn't stick between Revit sessions

**Desktop **
 - OS: Windows 10
 - pyRevit Version 4.8.12

`pyrevit env`
![image](https://github.com/eirannejad/pyRevit/assets/83564064/3e6e33a5-d815-4eb3-aca1-4b7d27e2a4ce)

Let me know what your thoughts are

**Comment by jmcouffin** [comment]
same as #1373 ?
may be fixed by PR #1777

**Comment by aniketdikshit** [comment]
I tried to make the changes mentioned in PR #1777  locally on my pyrevit\ computer - the error still persists though
