### ISSUE TITLE
forms.SelectFromList - Group Sorting

### ISSUE THREAD

**Issue by GerhardPaw** [eirannejad/pyRevit#1828]
The forms.SelectFromList does always sort the groups. This can not be avoided and prevents the ability of doing a custom sorting. The sorting does not always give a good result. Natural sort would be a better choice for sorting. See the following example.

![image](https://github.com/eirannejad/pyRevit/assets/97836426/c1fe7ef4-00d6-4e81-a46d-e005d5f29891)

Easy Solution:
Remove the sort() method from the function "_prepare_context()" of the forms.SelectFromList class.
This way the groups can be sorted as desired before calling the form and there is no sorting forced by the form.

Advanced Solution:
Add Arguments for "don´t sort", "sort" and "natural sort".

Additional information and a solution with natural sorting can be found here:

https://discourse.pyrevitlabs.io/t/forms-selectfromlist-natural-sort-groups-dictionary/1720

**Comment by jmcouffin** [comment]
@GerhardPaw would you mind making a PR to the develop branch with your solution?

**Comment by GerhardPaw** [comment]
Done!

**Comment by jmcouffin** [comment]
Fixed by #1905
