### ISSUE TITLE
Idea for Tool:  Section Placement on Sheet

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#183]
What do you think about a tool that allows you to do one of the following:

a. Add the current open section/detail/view to a sheet?
b. on Plan when you have selected a section, add the selected section to a sheet. 

I'm thinking either way a popup listing all the sheets would show up.

I think it will reduce work by keeping people from searching for the section in the Project Browser or the giant list of views when you selece "Add View to Sheet"

What do you think?

**Comment by eirannejad** [comment]
Good idea. I'll sit down and work this weekend to add this and #176

**Comment by hdm-dt-fb** [comment]
This is a nice one! 
For us, entering a sheet number instead of a full long sheet list would be great already.
@eirannejad  maybe there is a way to sneak in positioning according to an existing guide grid?

**Comment by eirannejad** [comment]
Resolved.

**Comment by thazell** [comment]
We are going to miss you Ehsan!

**Comment by eirannejad** [comment]
I'm not going anywhere :D
