### ISSUE TITLE
Config Manager (SCCM) application fail with error 324 detection issue 

### ISSUE THREAD

**Issue by Yaschoeman** [eirannejad/pyRevit#1831]
Hi All is anyone was ever able to install and deploy Pyrevit 4.8.12.22247 via SCCM, im getting 324 error. under detections method i have used File or Registry and none of them worked is anyone able to package the application?

**Comment by jmcouffin** [comment]
@Yaschoeman please check if any of those answer your issue https://github.com/eirannejad/pyRevit/issues?q=is%3Aissue+SCCM+

**Comment by Yaschoeman** [comment]
Hi @jmcouffin 
Sorry no it doesn't. my issue is here. picrures below.

![Screenshot 2023-05-29 112358](https://github.com/eirannejad/pyRevit/assets/134918046/021ede3f-883b-4eab-a95b-03cf13af82e2)
![Screenshot 2023-05-29 112638](https://github.com/eirannejad/pyRevit/assets/134918046/250355f2-380b-4659-90f0-f5432a689145)
![Screenshot 2023-05-29 112722](https://github.com/eirannejad/pyRevit/assets/134918046/fcf93f9a-8ee2-4c1c-a1f7-400b750a3254)

**Comment by jmcouffin** [comment]
Not really a pyRevit issue
try this https://www.systemcenterdudes.com/fix-sccm-error-0x87d00324-when-deploying-applications/

**Comment by Yaschoeman** [comment]
How can you close if the application doesn't work SCCM? i have over 1700 machine to deploy this app should a rather remove the app?

**Comment by jmcouffin** [comment]
Jean-Marc COUFFIN

**Comment by jmcouffin** [comment]
@Yaschoeman I closed the issue as it is not directly related to pyRevit itself.
Many have managed deployed pyRevit over the years.

The issue seems to be related with the installation detection in SCCM (as per linked article above) -> SCCM usage issue - SCCM support ticket.

**Comment by Yaschoeman** [comment]
Okay thanks but no thanks! that's why i asked the first question in the first place "anyone able to package the application" wanted to know if anyone was able to package but all or most application work yours not but its fine.

**Comment by jmcouffin** [comment]
you may want to check this as well @Yaschoeman

**Comment by jmcouffin** [comment]
https://pyrevitlabs.notion.site/pyRevit-For-Teams-ddc6c312d6f6488691eed2ec7704fd97

**Comment by jmcouffin** [comment]
@Yaschoeman 
wild guess
maybe that will help you with installation detection
It seems the installer tooltip gives you what windows really sees as version or file description/naming
![image](https://github.com/eirannejad/pyRevit/assets/7872003/255f962b-d0a0-4883-a631-74dfe414ffb9)

**Comment by Yaschoeman** [comment]
Hi,
I try most methods to install the application, file, registry for some reason it’s just not picking up the correct one not sure why but will keep trying until perhaps someone else out there will find another way and share with us.thanks

Sent from Yahoo Mail for iPhone


On Wednesday, May 31, 2023, 9:41 AM, Jean-Marc Couffin ***@***.***> wrote:




@Yaschoeman
wild guess
maybe that will help you with installation detection
It seems the installer tooltip gives you what windows really sees as version or file description/naming
