### ISSUE TITLE
PyRevit Synchronise

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#1832]
**Is your feature request related to a problem? Please describe.**

Best practice for synchronising in Revit would be as follows:
1. Reload Latest before you Synchronise with Central.
2. To speed up Synchronise with Central close hidden views and only have a generic drafting view open when synchronising.

**Describe the solution you'd like**
To speed up this process would it be possible to have a PyRevit Sync button that automates the following:

1. Reload the Latest
2. Open the default Starting View
3. Close Inactive (Views)
4. Save and Sync

![image](https://github.com/eirannejad/pyRevit/assets/8776947/ee69cdec-93ba-4794-af44-eec6351bcca9)

**Additional context**
Maybe one could Shift-Click to control what Revit commands you want to run when Synchronising with Central.

**Comment by jmcouffin** [comment]
something proposed by @alexdaversa is treating some features of your request https://github.com/eirannejad/pyRevit/pull/1692

**Comment by thumDer** [comment]
@jmcouffin this seems like exactly what we just started to implement, but haven't finished. we should blow the dust off.

**Comment by jmcouffin** [comment]
Care for a working session this week in the morning @thumDer to check it out?

**Comment by alexdaversa** [comment]
All, this feature seems complimentary to the feature I had developed, but probably separate. The autosave PR only periodically saves the local, but does not sync to central.

I could see this being implemented with two different approaches: one which uses the doc-syncing hook, and one which utilizes a toolbar button. Either approach seems viable, but if using the hooks approach, please provide a toggle to turn off this "enhanced sync" feature. I expect some users might be confused or upset that the tool closes open views. Look at my PR for an example of this.

**Comment by jmcouffin** [comment]
@alexdaversa yeah, 
I did not want to push your excellent PR right away exactly for that reason. 
I am still trying to figure out what would be the best approach for both features.
- Auto-sync must be optionnal and auto save as well.
- Closing all windows should be optional as well in both features
- Maybe reopening closed windows could be an option if there are not too many of them as it would be painful on complex models

**Comment by jmcouffin** [comment]
- closing or not closing, most probably, would need some testing. I still feel reopening might impact performance 
- automatic? Yes
  - there are a few examples of this on the building coder blog
  - i would be comfortable to have it in PYREVIT tools base set, but it will require extensive testing before releasing it, this is not something we would like breaking a Revit file
  - the config with it's own button or part of the settings. The activation should be a toggle button, so that user sees it's activated:
    - config in pushbutton or built-in settings 
    - toggle button to show activation state
    - hook to bypass sync for custom sync

**Comment by thumDer** [comment]
I have bad news. I wasn't able to initiate a new sync from the hook, after cancelling the original. Our custom sync function sometimes also throws the same Internal Error, which has no explanation in the API docs.

Here is my first experimental hook, if anybody has some time to play with it:
```python
from pyrevit import script, EXEC_PARAMS

from Autodesk.Revit.DB import TransactWithCentralOptions
from Autodesk.Revit.DB import SynchronizeWithCentralOptions
from Autodesk.Revit.DB import ICentralLockedCallback

logger = script.get_logger()
event_args = EXEC_PARAMS.event_args
doc = event_args.Document

comment_suffix = " pyRevit sync yo!"

class SyncLockCallback(ICentralLockedCallback):
    def ShouldWaitForLockAvailability(self):
        return False

options = event_args.Options
logger.info('Options:')
for attr in dir(options):
    if attr.startswith('__') or callable(getattr(options, attr)):
        continue
    logger.info('{}: {}'.format(attr, getattr(options, attr)))

if comment_suffix in options.Comment:
    script.exit()

logger.info('Cancelling...')
event_args.Cancel()
logger.info('Cancelled!')

twc_opts = TransactWithCentralOptions()
# twc_opts.SetLockCallback(SyncLockCallback())
# swc_opts = SynchronizeWithCentralOptions()
swc_opts = options
swc_opts.Comment += " pyRevit sync yo!"

doc.SynchronizeWithCentral(twc_opts, swc_opts)
```

**Comment by aniketdikshit** [comment]
I can take a gander at this - if nobody else is already doing it @jmcouffin @thumDer - Let me know :)

**Comment by aniketdikshit** [comment]
I was planning on making it a regular button as a one-off to start with :) - we eventually can add more complexity - currently following what @Robbo1234 pointed out as a 4 step process should be a good starting point

**Comment by nterranova** [comment]
Hey everyone, this might be a separate feature, but I wanted to support this effort however possible, and just kinda let you all know what I am hoping to do soon.

My team has recently requested a "sync queue" feature, especially for large projects. We've talked to other firms who have done this internally, but this just felt like a feature that should be available to everyone to be most effective. I haven't started on my own implementation yet, but if you want me to plug into this effort anywhere just let me know. Otherwise, I can get to a point where I can submit a PR and let you all take a look.

For reference, details of the ask are:

1. Ability to Join and Leave the queue
2. Store the queue in a cloud location so that multiple firms in the same model could join the same queue
3. Sync NOW option to jump the queue

There are of course other implications of these requests that we'll run into as the tool grows.

**Comment by aniketdikshit** [comment]
@jmcouffin @Robbo1234  I didn't know how to submit a PR for this repo and also couldn't  create a fun icon - but this is how the code stands 

1. this first gives a pop-up as to whether you want to close all inactive views 
2. then switch the active view to the first drafting view that it finds 
3. then saves - reloads latest - saves and syncs
4. 30%ish quicker sync 

feel free to put this code in a script.py and use it as is


also - if you place this code in the hooks folder in these Python files then this Sync can replace the command binding and would be the default sync for the users:
```
command-exec[ID_FILE_SAVE_TO_CENTRAL].py
command-exec[ID_FILE_SAVE_TO_CENTRAL_SHORTCUT].py
```



```
from Autodesk.Revit import DB, UI
from pyrevit import script

doc = __revit__.ActiveUIDocument.Document
uidoc = __revit__.ActiveUIDocument

def close_inactiveviews() :
    td = UI.TaskDialog('Better Sync')
    td.TitleAutoPrefix = False
    td.ExtraCheckBoxText = 'Close Inactive Open Views'
    td.MainInstruction = 'Synchronize the Active Document'
    td.MainContent  = 'Central File Path \n{} '.format(doc.PathName)
    td.CommonButtons = UI.TaskDialogCommonButtons.Cancel | UI.TaskDialogCommonButtons.Ok
    td.AllowCancellation = True
    result = td.Show()
    if result == UI.TaskDialogResult.Cancel or result == UI.TaskDialogResult.Close :
        script.exit()
    return td.WasExtraCheckBoxChecked()

'This gets the first drafting view to allow for quick syncing'
def get_first_draftingView() :
    all_views = (DB.FilteredElementCollector(doc).
                 OfClass(DB.View).
                 WhereElementIsNotElementType().
                 ToElements())
    for view in all_views :
        if view.ViewType == DB.ViewType.DraftingView :
            return view
            break


'This closes all views for the current document except the one that is passed through as input'
def close_views(view_list) :
    all_open_views = uidoc.GetOpenUIViews()
    for ui_view in all_open_views :
        doc_view = doc.GetElement(ui_view.ViewId)
        if doc_view.Name not in view_list :
            ui_view.Close()

def sync_document() :
    if doc.IsWorkshared and not doc.IsFamilyDocument and not doc.IsLinked :
        try:
            first_draftingview = get_first_draftingView()
            if uidoc.ActiveView.ViewType != DB.ViewType.DraftingView :
                uidoc.ActiveView = first_draftingview
        except :
            pass
        if close_inactiveviews() :
            close_views(doc.ActiveView.Name)

        transOptions = DB.TransactWithCentralOptions()
        syncOptions = DB.SynchronizeWithCentralOptions()
        relinquish_all = True
        relinquishOptions = DB.RelinquishOptions(relinquish_all)
        reloadLatestOptions = DB.ReloadLatestOptions()

        saveOptions = DB.SaveOptions()

        syncOptions.SetRelinquishOptions(relinquishOptions)
        syncOptions.Compact = True
        doc.Save(saveOptions)
        doc.ReloadLatest(reloadLatestOptions)
        doc.Save(saveOptions)
        doc.SynchronizeWithCentral(transOptions , syncOptions)

    else :
        UI.TaskDialog.Show("Error" , "Current Document is not Workshared")


if __name__ == "__main__" :
    sync_document()
```

**Comment by Robbo1234** [comment]
Thanks, Aniket

@jmcouffin <https://github.com/jmcouffin> can we incorporate this into a
PyRevit update? Thanks

**Comment by jmcouffin** [comment]
> Hey everyone, this might be a separate feature, but I wanted to support this effort however possible, and just kinda let you all know what I am hoping to do soon.
> 
> My team has recently requested a "sync queue" feature, especially for large projects. We've talked to other firms who have done this internally, but this just felt like a feature that should be available to everyone to be most effective. I haven't started on my own implementation yet, but if you want me to plug into this effort anywhere just let me know. Otherwise, I can get to a point where I can submit a PR and let you all take a look.
> 
> For reference, details of the ask are:
> 
> 1. Ability to Join and Leave the queue
> 2. Store the queue in a cloud location so that multiple firms in the same model could join the same queue
> 3. Sync NOW option to jump the queue
> 
> There are of course other implications of these requests that we'll run into as the tool grows.

This is interesting, but probably an entirely different feature (and a big one) You coul dcreate a new issue/feature request @nterranova

**Comment by jmcouffin** [comment]
first implementation #2008
should be available in a few minutes here https://github.com/eirannejad/pyRevit/actions/runs/6944599944
@Robbo1234 @aniketdikshit 

if you want to review @thumDer ?

**Comment by Robbo1234** [comment]
Thanks, Aniket and Jean-Marc for this new PyRevit feature. Rob
![image](https://github.com/eirannejad/pyRevit/assets/8776947/b5853ba2-f919-4d60-bdd8-14dc04023f68)

**Comment by jmcouffin** [comment]
> Thanks, Aniket and Jean-Marc for this new PyRevit feature. Rob

Try it and let us know how it goes

**Comment by Robbo1234** [comment]
Installed it yesterday and it works fine.

Rob

**Comment by thumDer** [comment]
Dang I've missed this one, sorry. I would be really interested if anyone else experiences random InternalExceptions on calling SynchronizeWithCentral() without any explanation. I'm about to make a pr on this to have an option to reopen all or the selected closed views.
