### ISSUE TITLE
Custom Extension Directory path not being saved

### ISSUE THREAD

**Issue by DJBuck** [eirannejad/pyRevit#1833]
**Describe the bug**
I'm trying to re-associate my previous custom tabs on a new work PC, but when I add the file path to the Custom Extension Directory, Save & Reload, no new tabs are created. I head back to the settings, and the path I have just added is gone.
Using Revit 2020 and 2023.
Also (unsure if it is related), I don't seem to be able to Enable the pyRevitDevTools extension pack? I don't know if I need to do this to enable my custom extensions?

**To Reproduce**
1. Add Custom Extension Directory folder path
2. Save & Reload
3. No new tabs created (I know the scripts/folders worked previously)
4. Back to settings, and the path I just added is no longer there

**Expected behavior**
The folder path entered into the Custom Extension Directory to create a new Tab within the Revit toolbar, failing that to maintain that folder path within the Settings

**Screenshots**
![image](https://github.com/eirannejad/pyRevit/assets/48869354/9027e85f-f3ee-4c4d-b3eb-381f9538440a)

**Desktop (please complete the following information):**
 - OS: Windows 11 (previously worked on Windows 10)
 - pyRevit Version 4.8.12
 - pyRevit Environment: ==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\Dan.buckingham\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\Dan.buckingham\AppData\Roaming\pyRevit-Master" | AllUsers
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\Dan.buckingham\AppData\Roaming\pyRevit-Master" | AllUsers
master | Product: "Autodesk Revit 2021" | Engine: IPY277 (277) | Path: "C:\Users\Dan.buckingham\AppData\Roaming\pyRevit-Master" | AllUsers
master | Product: "2020.2.1 (New Install)" | Engine: IPY277 (277) | Path: "C:\Users\Dan.buckingham\AppData\Roaming\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Dan.buckingham\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.0.11.19 | Build: 20220503_1030(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
Autodesk Revit 2021 | Version: 21.1.1.109 | Build: 20200715_1022(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.1 (New Install) | Version: 20.2.12.1 | Build: 20200210_1400(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
PID: 30492 | 2020.2.1 (New Install) | Version: 20.2.12.1 | Build: 20200210_1400(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2020"
==> User Environment
Microsoft Windows 10 [Version 10.0.22621]
Executing User: GLOBAL\dan.buckingham
Active User:
Admin Access: Yes
%APPDATA%: "C:\Users\Dan.buckingham\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.12.22247+0031

**Additional context**
This might not be a bug, just me doing something wrong, but I couldn't find any solutions online

**Comment by DJBuck** [comment]
As an update, I've tried the same process on Revit 2022 on a different PC (windows 10), and it works perfectly, which would lead me to believe the issue lies with Windows 11?

**Comment by jmcouffin** [comment]
@DJBuck Can you try installing one of the WIP version after uninstalling your 2.12 version of pyRevit?

**Comment by DJBuck** [comment]
> @DJBuck Can you try installing one of the WIP version after uninstalling your 2.12 version of pyRevit?

Apologies, how do I find these?

**Comment by jmcouffin** [comment]
instructions: https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725 (installers section)

**Comment by DJBuck** [comment]
Thank you, the latest WIP version works great, do I need to get all members of my team to uninstall pyRevit and install the WIP version?

**Comment by jmcouffin** [comment]
> Thank you, the latest WIP version works great, do I need to get all members of my team to uninstall pyRevit and install the WIP version?
Glad it worked!
I don't know your IT policies and all,but if you work with Revit 2023 and above, yes
