### ISSUE TITLE
PyRevit icons on the ribbon are barely visible when Revit 2024 dark theme enabled

### ISSUE THREAD

**Issue by shtirlitsDva** [eirannejad/pyRevit#1834]
**Describe the bug**
PyRevit icons on the ribbon are barely visible when Revit 2024 dark theme is enabled

**To Reproduce**
Install Revit 2024
Install PyRevit (I installed 9266f6a [develop](https://github.com/eirannejad/pyRevit/tree/develop))

**Expected behavior**
I expect the icons to be visible in Dark mode.

**Screenshots**
![image](https://github.com/eirannejad/pyRevit/assets/12258139/780048e1-1074-42fc-b235-8b1570b3de60)

**Desktop (please complete the following information):**
 - OS: Win 11 22H2
 - pyRevit Version 9266f6a Develop version
 - pyRevit Environment: 

´´´
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.13.23144+1030-wip" | Path: "C:\Users\MichailGolubjev\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2024" | Engine: IPY277 (277) | Path: "C:\Users\MichailGolubjev\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
DRIEXT | Type: Unknown | Repo: "" | Installed: "X:\AutoCAD DRI - Revit\pyRevitExtensions\DRIEXT.extension"
==> Default Extension Search Path
C:\Users\MichailGolubjev\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
X:\AutoCAD DRI - Revit\pyRevitExtensions
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2024 | Version: 24.0.5.432 | Build: 20230411_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
==> Running Revit Instances
Error: Objektreferencen er ikke indstillet til en forekomst af et objekt.
Run with "--debug" option to see debug messages
´´´

**Comment by jmcouffin** [comment]
@shtirlitsDva do you have a proposal to fix this?

**Comment by shtirlitsDva** [comment]
> 

I am sorry, no.

**Comment by jmcouffin** [comment]
I tried to recolor the icons for that specific purpose with this script.
The output is decent.
![image](https://github.com/eirannejad/pyRevit/assets/7872003/2ed0ae4d-25a6-4f2a-8abd-84e62beb9b24)

We would need to discuss it with  @eirannejad if there is a better way than recoloring all the icons:

```python
from PIL import Image, ImageDraw
import os

def grey_icons(input_path, output_path):
    image = Image.open(input_path).convert("RGBA")
    if input_path.endswith("icon.png"):
        new_image = Image.new("RGBA", image.size, (0, 0, 0, 0))
        draw = ImageDraw.Draw(new_image)
        greying_color = (243,243,243)
        for x in range(image.width):
            for y in range(image.height):
                r, g, b, a = image.getpixel((x, y))
                if a > 0:
                    draw.point((x, y), fill=greying_color + (a,))
        new_image.save(output_path)
    else:
        image.save(output_path)


def add_stroke(input_path, output_path, stroke_width=1):
    image = Image.open(input_path).convert("RGBA")
    new_image = Image.new("RGBA", image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(new_image)
    colored_pixels = image.convert("L").point(lambda x: 0 if x == 0 else 255, mode="1")
    new_image.paste(image, (0, 0), mask=image)
    for x in range(image.width):
        for y in range(image.height):
            if colored_pixels.getpixel((x, y)):
                for dx in range(-stroke_width, stroke_width + 1):
                    for dy in range(-stroke_width, stroke_width + 1):
                        if dx == 0 and dy == 0:
                            continue
                        nx, ny = x + dx, y + dy
                        if nx < 0 or ny < 0 or nx >= image.width or ny >= image.height or not colored_pixels.getpixel((nx, ny)):
                            draw.point((x, y), fill=(0, 0, 0))
    final_image = Image.alpha_composite(image, new_image)
    final_image.save(output_path)

input_directory = "C:\pyRevit\latest\latest\extensions\pyRevitTools.extension\pyRevit.tab"
output_directory = "C:\pyRevit\latest\latest\extensions\pyRevitTools.extension\pyRevit.tab"
stroke_width = 1


for root, dirs, files in os.walk(input_directory):
    for filename in files:
        if filename.endswith(".png"):
            input_path = os.path.join(root, filename)
            relative_path = os.path.relpath(input_path, input_directory)
            output_path = os.path.join(output_directory, relative_path)
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            grey_icons(input_path, output_path)
            add_stroke(output_path, output_path, stroke_width)

```

**Comment by dosymep** [comment]
@jmcouffin, 
I've created new icons to bundles.
Will pyrevit maybe use that names?
![image](https://github.com/eirannejad/pyRevit/assets/5417225/595ebc46-28b5-4e46-beee-bf10cb98083f)

**Comment by jmcouffin** [comment]
@dosymep can you elaborate on the usage of dark vs fatal, regular and warning?
There is no process implemented to match 2024 theme behaviour. How would you approach it?

**Comment by dosymep** [comment]
icon - default for light theme
icon.dark - for dark theme
icon.warning and icon.fatal - for my custom notifications

**Comment by jmcouffin** [comment]
use case missing is on and off toggle in dark theme

**Comment by dosymep** [comment]
I think need to use suffix dark for dark theme.
If you create images "on.png and off.png", you need to add dark suffix "on.dark.png and off.dark.png"

**Comment by LTusche** [comment]
Another useful solution could be, to invert the brightness while preserving the hue. Usually works great for icons.

**Comment by GertjanVDBVK** [comment]
I think it makes sense ot do both.
Use the .dark.png file if it is provided, otherwise , try a best guess by inverting the colors.

**Comment by jmcouffin** [comment]
@dosymep do you have the implementation for .dark somewhere already coded?

**Comment by dosymep** [comment]
@GertjanVDBVK, invert colors great idea, but I think bad to performance, cold start pyrevit will be so terrible

**Comment by jmcouffin** [comment]
Fixed by @dosymep by #1897 🍾 🙏 🎉 
![image](https://github.com/eirannejad/pyRevit/assets/7872003/784eea4f-d136-407e-b60a-549079140903)

- All icons got duplicated and converter to icon.dark.png with white color
- a utility script has been added under /extras/dark_mode/convert_icon_to_dark_mode.py to help batch convert icons for your own extensions

# How do I get this chhange?
- Install latest WIP version under Actions Tab in Github https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725#75400354a8d74c94ab9e2b35ae0cccf5

> Requires a Reload whenever you switch theme

**Comment by tjxme** [comment]
> Fixed by @dosymep by #1897 🍾 🙏 🎉 ![image](https://private-user-images.githubusercontent.com/7872003/261973727-784eea4f-d136-407e-b60a-549079140903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMDIzMzQsIm5iZiI6MTcxMzIwMjAzNCwicGF0aCI6Ii83ODcyMDAzLzI2MTk3MzcyNy03ODRlZWE0Zi1kMTM2LTQwN2UtYjYwYS01NDkwNzkxNDA5MDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTVUMTcyNzE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGY5YzBhOGM5N2U3NWUzM2FiZWExY2Q5YjYyMTNiNzA1ZjJjYWI0ZWIxMDU4OTM1NzkwYWQ4MGQxYWRhYWI5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Tmlw82ihR6lad4WdgEsPGMDHUOVqa13HWiNh2ssmr90)
> 
> * All icons got duplicated and converter to icon.dark.png with white color
> * a utility script has been added under /extras/dark_mode/convert_icon_to_dark_mode.py to help batch convert icons for your own extensions
> 
> # How do I get this change?
> * Install latest WIP version under Actions Tab in Github https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725#75400354a8d74c94ab9e2b35ae0cccf5
> 
> > Requires a Reload whenever you switch theme

sorry i dont find them under %appdata%/pyrevit folder. im using the non-admin version, what is the typical path??

**Comment by jmcouffin** [comment]
> > Fixed by @dosymep by #1897 🍾 🙏 🎉 ![image](https://private-user-images.githubusercontent.com/7872003/261973727-784eea4f-d136-407e-b60a-549079140903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMDIzMzQsIm5iZiI6MTcxMzIwMjAzNCwicGF0aCI6Ii83ODcyMDAzLzI2MTk3MzcyNy03ODRlZWE0Zi1kMTM2LTQwN2UtYjYwYS01NDkwNzkxNDA5MDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTVUMTcyNzE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGY5YzBhOGM5N2U3NWUzM2FiZWExY2Q5YjYyMTNiNzA1ZjJjYWI0ZWIxMDU4OTM1NzkwYWQ4MGQxYWRhYWI5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Tmlw82ihR6lad4WdgEsPGMDHUOVqa13HWiNh2ssmr90)
> > 
> > * All icons got duplicated and converter to icon.dark.png with white color
> > * a utility script has been added under /extras/dark_mode/convert_icon_to_dark_mode.py to help batch convert icons for your own extensions
> > 
> > # How do I get this change?
> > 
> > * Install latest WIP version under Actions Tab in Github https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725#75400354a8d74c94ab9e2b35ae0cccf5
> > 
> > > Requires a Reload whenever you switch theme
> 
> sorry i dont find them under %appdata%/pyrevit folder. im using the non-admin version, what is the typical path??

Please open a new issue and follow the issue guidelines

**Comment by tjxme** [comment]
> > > Fixed by @dosymep by #1897 🍾 🙏 🎉 ![image](https://private-user-images.githubusercontent.com/7872003/261973727-784eea4f-d136-407e-b60a-549079140903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMDIzMzQsIm5iZiI6MTcxMzIwMjAzNCwicGF0aCI6Ii83ODcyMDAzLzI2MTk3MzcyNy03ODRlZWE0Zi1kMTM2LTQwN2UtYjYwYS01NDkwNzkxNDA5MDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTVUMTcyNzE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGY5YzBhOGM5N2U3NWUzM2FiZWExY2Q5YjYyMTNiNzA1ZjJjYWI0ZWIxMDU4OTM1NzkwYWQ4MGQxYWRhYWI5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Tmlw82ihR6lad4WdgEsPGMDHUOVqa13HWiNh2ssmr90)
> > > 
> > > * All icons got duplicated and converter to icon.dark.png with white color
> > > * a utility script has been added under /extras/dark_mode/convert_icon_to_dark_mode.py to help batch convert icons for your own extensions
> > > 
> > > # How do I get this change?
> > > 
> > > * Install latest WIP version under Actions Tab in Github https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725#75400354a8d74c94ab9e2b35ae0cccf5
> > > 
> > > > Requires a Reload whenever you switch theme
> > 
> > 
> > sorry i dont find them under %appdata%/pyrevit folder. im using the non-admin version, what is the typical path??
> 
> Please open a new issue and follow the issue guidelines

my bad, apologize again. found them under our issue 
https://github.com/eirannejad/pyRevit/blob/develop/extras/dark_mode/convert_icon_to_dark_mode.py

**Comment by Denver-22** [comment]
[https://github.com/eirannejad/pyRevit/blob/develop/extras/dark_mode/convert_icon_to_dark_mode.py](url)
I think there is a mistake on line 38. Alpha channel should be the 4th argument?
`output.putpixel((x, y), (pixel[3], color[0], color[1], color[2]))`
Is that correct?
`output.putpixel((x, y), (color[0], color[1], color[2], pixel[3]))`

**Comment by jmcouffin** [comment]
> convert_icon_to_dark_mode.py

You are right, thanks
https://github.com/pyrevitlabs/pyRevit/commit/dc86688cd3395809ae82b4c1fd02f54d19c49702
