### ISSUE TITLE
Telemetry (app-closing): not send username 

### ISSUE THREAD

**Issue by dosymep** [eirannejad/pyRevit#1835]
![image](https://github.com/eirannejad/pyRevit/assets/5417225/900b9fd0-7c78-4911-8dde-a77fb60f3337)

**Comment by dosymep** [comment]
@jmcouffin, maybe there is a workaround?

**Comment by jmcouffin** [comment]
Parsing the journal file?

**Comment by dosymep** [comment]
maybe pyrevit has static resources with username

**Comment by eirannejad** [comment]
Ok added a default user to the telemetry system that gets setup at pyRevit launch
