### ISSUE TITLE
Can't open pyRevit in Revit 2023

### ISSUE THREAD

**Issue by tsorrell42** [eirannejad/pyRevit#1836]
Every time I open Revit 2023 I get the below error message. I just installed pyrevit today so I am not sure where to go. Let me know if you guyys need anymore details. 
![image](https://github.com/eirannejad/pyRevit/assets/136000829/1b0782fe-dbfb-4863-a4cd-449619b7e8d6)

![image](https://github.com/eirannejad/pyRevit/assets/136000829/6602fe4d-c100-4ce1-af0d-036e31e76e9f)

**Comment by jmcouffin** [comment]
can you run the `pyrevit env` command in the command line and copy paste the report here

**Comment by tsorrell42** [comment]
@jmcouffin Here ya go!

Microsoft Windows [Version 10.0.22621.1778]
(c) Microsoft Corporation. All rights reserved.

C:\Users\tstouffer>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\tstouffer\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2024" | Engine: IPY277 (277) | Path: "C:\Users\tstouffer\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\tstouffer\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\tstouffer\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2021" | Engine: IPY277 (277) | Path: "C:\Users\tstouffer\AppData\Roaming\pyRevit-Master"
master | Product: "2020.2.1 (New Install)" | Engine: IPY277 (277) | Path: "C:\Users\tstouffer\AppData\Roaming\pyRevit-Master"
master | Product: "2019.2.6" | Engine: IPY277 (277) | Path: "C:\Users\tstouffer\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\tstouffer\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2024 | Version: 24.0.20.20 | Build: 20230509_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
Autodesk Revit 2023 | Version: 23.1.20.70 | Build: 20230510_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
Autodesk Revit 2021 | Version: 21.1.70.21 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.1 (New Install) | Version: 20.2.12.1 | Build: 20200210_1400(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.6 | Version: 19.2.60.3 | Build: 20220224_1700(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages

**Comment by jmcouffin** [comment]
try the `pyrevit doctor` command maybe. It is supposed to act on the registry to fix installs issue.
Wild guess: It feels like there is an addin specifically installed in 2023 that interferes with pyRevit

you could also try and change the engine with the command:
`pyrevit attach master 2711 --installed`

**Comment by jmcouffin** [comment]
Could be related https://github.com/eirannejad/pyRevit/issues/1572

**Comment by tsorrell42** [comment]
I could see the addin causing the problem. I ahve one that has caused issues like that in the past

**Comment by tsorrell42** [comment]
Adding the A at the beginning as a solution from one of the other forums was a solution. I can use it now in revit 2023

**Comment by jmcouffin** [comment]
I will close it but mention it to Ehsan to see if there is a more consistent solution

**Comment by Agni-code** [comment]
> Adding the A at the beginning as a solution from one of the other forums was a solution. I can use it now in revit 2023

Adding the A where?

**Comment by jmcouffin** [comment]
> Adding the A where?
Renaming the pyrevit.addin file adding a character that will force Revit to load the addin before another problematic one.
I tend to prefer "0_pyrevit.addin" as there is a better chance that no other addins will be loaded before.
