### ISSUE TITLE
Updater and Installer Issues

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#184]
![image](https://cloud.githubusercontent.com/assets/14113080/25010945/aceb90d0-2039-11e7-91ec-62026b011cd5.png)
 

Revit was closed.

**Comment by eirannejad** [comment]
@thazell Have you made any changes to the scripts or the repository? The only other issue that I can think of is that if you've installed it in `%appdata% folder, maybe the server has synced back an older version.

**Comment by thazell** [comment]
We have installed it in %appdata%.  I'll try uninstalling and reinstalling on my comp

**Comment by eirannejad** [comment]
@thazell Did this get resolved?

**Comment by thazell** [comment]
Working on a reinstall right now and the new downloader appears to either be detected as a threat by symantec or have a threat that has leached onto the installer.  Not sure if I want to overwrite symantec without being certain.  (see images)
![image](https://cloud.githubusercontent.com/assets/14113080/25048922/16101788-210d-11e7-90f0-97e420c94ab2.png)

![image](https://cloud.githubusercontent.com/assets/14113080/25048925/1a968882-210d-11e7-8616-23aa5411cd74.png)

**Comment by eirannejad** [comment]
@thazell It's the same downloader as before. See the description for the `WS.Reputation.1` here:

https://www.symantec.com/security_response/writeup.jsp?docid=2010-051308-1854-99

Symantec is flagging this due to lack of history. This is not an actual threat.

**Comment by thazell** [comment]
@eirannejad thanks.  I was just reading up on it here: https://community.norton.com/en/forums/clarification-wsreputation1-detection

I need to run it by IT, however if it's the same installer, maybe the last one I downloaded wasn't flagged as such.  Not trying to be a pain here, just being mindful and cautious

**Comment by thazell** [comment]
Is there any dif. between this installer and the one I downloaded on 3-22?  I know they both will access the revised github.  Also, not sure, but is it possible to get a valid signature for pyRevitCloner (might be a stupid question but it's above my knowledge.)

![image](https://cloud.githubusercontent.com/assets/14113080/25049170/6554e49e-210e-11e7-997d-ee48745bdcc7.png)

**Comment by eirannejad** [comment]
Not sure how to provide signature. The source code for `pyRevitCloner` and `pyRevitUpdater` are here:

https://github.com/eirannejad/pyRevit/blob/master/release/pyRevitCloner/pyRevitCloner/Program.cs

https://github.com/eirannejad/pyRevit/blob/master/release/pyRevitCoreUpdater/pyRevitCoreUpdater/Program.cs

**Comment by thazell** [comment]
No worries, looks like the original issue has been resolved.

**Comment by thazell** [comment]
Thanks for linking the sourcecode.

**Comment by eirannejad** [comment]
Cool. I'll close this then.
