### ISSUE TITLE
Guard stack issues in large list forms

### ISSUE THREAD

**Issue by aussieBIMguru** [eirannejad/pyRevit#1840]
I've been encountering frequent crashing when forming selections in large lists using the form 'forms.SelectFromList'.

I have tried this using elements, custom class to show name/pass element and also just raw strings with same result regardless of the UI key/value types I provide.

The error relates to the guard stack, and crashes out of the model when cancelled or OK'd. I am aware any error relating to this is an indicator of running out of memory, so was wondering if this is either:

A. An issue with the form (e.g. memory leak)
B. A general limitation of the form in pyRevit
C. A general limitation of the form in WPF, generally

If it's just a matter of it being a windows/WPF limit, I'm happy with that as an answer/close out, just want to know what is the likely cause so I can build around or train around it for users as crashing out of sessions in big models is brutal. Generally all other tools/features have been great in large models such as progress bars and cancellation/script.exit() capability that pyRevit offers.

Steps to reproduce the behaviour:
1. Large model (1GB+)
2. Generate a list form with at least 200 elements
3. Shift select enough elements that it visually exceeds the UI (shift select)

In most cases, this will crash the model, but it's not entirely consistent.

I am using Windows 10, Revit 2023 and pyRevit 4.8.12.22247. My machine has 64GB (HP ZBook) and intel corevproi9 processor, so guessing it's potentially virtual memory related. Have tried manually assigning paging size for C and same issue persists (generally we run machines on auto).

I have tested this on current WIP build and have encountered similar issues.

**Comment by thumDer** [comment]
this seems like #1263 which was closed without ever being resolved. I have only been able to draw the conclusions you have, but never got any further.

**Comment by dosymep** [comment]
@thumDer 4.8.8, works with 300+ items

```
from pyrevit import forms  
form = forms.SelectFromList.show(  [i for i in range(400)],  multiselect=True )
```

<details>
    <summary>4.8.8 (Revit 2022)</summary>
    <img src="https://github.com/eirannejad/pyRevit/assets/5417225/781ebe18-b762-4cd5-bd64-32189821d68a">
</details>

**Comment by thumDer** [comment]
I will doublecheck it tomorrow, but the issue was not with creating the form with that much elements, but manually selecting more than 190 (like shift+click, and check)

**Comment by dosymep** [comment]
@thumDer, okay I understand, when user checks items with shift select revit crashes

**Comment by dosymep** [comment]
Each time the check is changed, the ```check_selected``` and ```uncheck_selected``` event handlers are called, they call each other and throws StackOwerflowException

https://github.com/eirannejad/pyRevit/blob/master/pyrevitlib/pyrevit/forms/__init__.py#L968
https://github.com/eirannejad/pyRevit/blob/master/pyrevitlib/pyrevit/forms/__init__.py#L972

**Comment by thumDer** [comment]
Yep, you're right, this explains it. Any ideas how to fix it?

**Comment by aussieBIMguru** [comment]
At the least glad to hear that this is potentially fixable in future, appreciate everyone looking into this to determine likely cause. Hopefully will be useful in future for diagnosing solutions. Strange that it appears to work for smaller selections but not larger ones, would have thought an overflow doesn't depend on scale.

**Comment by dosymep** [comment]
pseudocode:

check_selected
```
in_check = False

def check_selected(self, sender, args):    #pylint: disable=W0613
    """Mark selected checkboxes as checked."""
    try:
        if not in_check:
            in_check = True
            self._set_states(state=True, selected=True)
    finally:
        in_check = False
```

uncheck_selected
```
in_uncheck = False

def uncheck_selected(self, sender, args):    #pylint: disable=W0613
    """Mark selected checkboxes as unchecked."""
    try:
        if not in_uncheck:
            in_uncheck = True
            self._set_states(state=False, selected=True)
    finally:
        in_uncheck = False
```

**Comment by jmcouffin** [comment]
Checked it on a 3000 items set and selected half of it. 
it took a couple of seconds to check items but working as expected
thanks all

**Comment by jmcouffin** [comment]
latest wip installers are available under the github **actions** tab in the latest job

**Comment by aussieBIMguru** [comment]
Amazing, thanks so much for the help everyone! This was one of the last hurdles scaring my users away from pyRevit, so will go a long way where I work.
