### ISSUE TITLE
Packages and Tags failure

### ISSUE THREAD

**Issue by dabutts** [eirannejad/pyRevit#1843]
Running v4.8.12.22247+0031 in Revit 2023.1.2. Documenting the different toolsets and when attempt to run Manage Packages, only get the traceback dialog with a System.MissingMemberException error. Is there something in the process/use I'm missing? This was run over an architectural model and plan views.
![image001](https://github.com/eirannejad/pyRevit/assets/136599883/382fb5fa-dba8-45c3-b32e-b522863dc3d1)

thanks - David B.

**Comment by jmcouffin** [comment]
related #1839

**Comment by jmcouffin** [comment]
You are using an old release. The new official one is due before the end of the month but in the meantime you can try the WIP Installers which do provide a solution
