### ISSUE TITLE
notype

### ISSUE THREAD

**Issue by HungTr25846** [eirannejad/pyRevit#1846]
i don't know how to fix it. need some help

![Screenshot (2)](https://github.com/eirannejad/pyRevit/assets/136819268/5876b916-f2f5-48a2-a703-585a11f95599)

**Comment by jmcouffin** [comment]
- uninstall old version
- Use the latest wip installers (https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725)
