### ISSUE TITLE
failure after Hooks extension enabling

### ISSUE THREAD

**Issue by RichardPinka** [eirannejad/pyRevit#1847]
**Describe the bug**
By curiosity, i wantet to enable enxtension hooks. 
but error window appeared and still opened the new one ona after each another. 
The issue persists after I wanted to restart Revit. 
is there way to disable this addon within the code of PyRevit before starting Revit ? 

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

**To Reproduce**
1. enable the extension Hooks
2. See error

**Expected behavior**
.. extension will be somehow imported within Pyrevit

**Screenshots**
![image](https://github.com/eirannejad/pyRevit/assets/8267708/147da5c3-b15b-4da2-b16b-34819632619b)

**Desktop (please complete the following information):**
 - OS: windows 10 64bit
 - pyRevit Version pyRevit 4.8.12.22247 Installed
 - pyRevit Environment:  i cannot open revit without issuing such error windows ! :)

**Comment by jmcouffin** [comment]
- You enabled the devhooks extension right?
- `C:\Users\richa\desktop\` does this path exist on your machine?
- What is printing when you run the following in a python console?
```python
import os.path as op
import datetime
USER_DESKTOP = op.expandvars('%userprofile%\\desktop')
HOOK_LOGS = op.join(USER_DESKTOP, 'hooks.log')
print(HOOK_LOGS)
```

**Comment by jmcouffin** [comment]
Can you try uninstall pyrevit, and install one of the latest installer: https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725 under **actions**
And then try again the DevHooks Extension please

**Comment by RichardPinka** [comment]
hello, to your questions @jmcouffin 

1. You enabled the devhooks extension right?
yes

2. C:\Users\richa\desktop\ does this path exist on your machine?
yes

4. What is printing when you run the following in a python console?

here printscreen: 
![image](https://github.com/eirannejad/pyRevit/assets/8267708/f584a6bd-f57c-4d5c-8c7a-265e38556551)

**Comment by RichardPinka** [comment]
@jmcouffin   I am glad to help you by uninstalling and reainstalling , but .. what shall i install ? 
on the URL you sent me, there is not propper installation package. 
i do not know what you mean by "under actions"
sorry :)

could you send the exact link of installation file ?

**Comment by RichardPinka** [comment]
Dear Jean Marc, 
i installed version pyRevit_4.8.13.23170_admin_signed  
that i find it somehow 
but there is no plugin "Hooks"  .. did i missed something ? 
![image](https://github.com/eirannejad/pyRevit/assets/8267708/00cf8547-c8ca-4397-8f97-97b9e263b499)

**Comment by jmcouffin** [comment]
> but there is no plugin "Hooks" .. did i missed something ?
Yes, upon installation it asks you if you want the developer extension installed as well.

3. Weird. You could try to open the log file after the code snippet i provided you

**Comment by RichardPinka** [comment]
allright, i installed also developer extension.. and yes.. the problem persists (it remembered the "enable" state of the plugin and never-ending error window appeared again
![image](https://github.com/eirannejad/pyRevit/assets/8267708/8e8b2702-f6de-4269-a728-80433acf81a3)

**Comment by jmcouffin** [comment]
Hi Richard,
Glad you got things working.
For the two windows it is a different issue.
Probably an issue with one of the c# command. Could you open a different issue.

**Comment by jmcouffin** [comment]
And btw @RichardPinka , greetings from Zlín 😁
