### ISSUE TITLE
Matching View Titles in Copy Viewport State tool

### ISSUE THREAD

**Issue by kjanik11** [eirannejad/pyRevit#185]
Could the Copy States also align the view titles vertically on the sheet as the one selected on the target sheet with the same view title endpoints?  Before that it would also be good to check that the view titles are the same type and match them.

**Comment by eirannejad** [comment]
Did some research. Apparently Revit API does not expose functionality to adjust the placement of the viewport label.

**Comment by kjanik11** [comment]
Thanks for checking!  Maybe for another day.
