### ISSUE TITLE
How to deal with multiple Revit versions

### ISSUE THREAD

**Issue by Dre-Tas** [eirannejad/pyRevit#1853]
Hey guys!

Here at Woods Bagot we have our Wombat plugin that is a mix of script files (script.cs and .py) and a few DLLs that come from VS solutions and then invoked by a few .inovkebutton

To give you a very simple example, let's say that I need to create a `ParameterType` object. In Revit 2020 I'd need to use this line of code: `ParameterType parameterType = ParameterType.Text;` which would although fail in Revit 2023, as I now need to use `SpecTypeId.String.Text`

How can I deal with API changes between versions of Revit, from my VS solution?
I know I can use conditions in my .csproj (i.e. https://thebuildingcoder.typepad.com/blog/2018/06/multi-targeting-revit-versions-cad-terms-texture-maps.html#2) or I could use shared projects in VS (i.e. https://archi-lab.net/how-to-maintain-revit-plugins-for-multiple-versions-continued/), but I don't think this would be effective for pyRevit (as I'm not targeting Revit directly), would it?

What would be the best way to do this?

One thing I can think of, is creating 2 projects in my VS solution. Let's call them Wombat2020 and Wombat2023. And then, reference the Revit 2020 APIs in the Wombat2020 project and the Revit 2023 APIs in the Wombat2023 project. In this way I will be creating 2 distinct DLLs in the **lib** folder (_Wombat2020.dll_ and _Wombat2023.dll_) that reference 2 different APIs. Then I could use the revit version property in the bundle.yaml to enable/disable the commands that invoke the 2 libraries accordingly.
Although, this sounds a bit painful, especially if you have to change just one line of code in a command.
Is there a better way?

**Comment by jmcouffin** [comment]
@Dre-Tas not a pyrevit issue by itself, I will close this one if you don't mind and let you ask on the forum.
you would get more traction/replies on the pyrevit forum anyway https://discourse.pyrevitlabs.io/
