### ISSUE TITLE
Trying to register multiple dockable windows

### ISSUE THREAD

**Issue by Tariqshah457** [eirannejad/pyRevit#1858]
I was trying to register multiple dockable windows with a click of button. i can register one window. when i try to register second window the first one also stop working. it gives error that the dockable at the id is not register. When i register the dockable window and print is_registered it gives me false. My code is given below. 

##for 1st dockable window
`class DockableExample1(forms.WPFPanel):
    panel_title = "Button 1 - DOCKWINDOW"
    panel_id = "3110e336-f81c-4927-87da-4e0d30d4d64a"
    panel_source = op.join(op.dirname(__file__), "DockableExample1.xaml")

if not forms.is_registered_dockable_panel(DockableExample1):
    forms.register_dockable_panel(DockableExample1)
    forms.open_dockable_panel(DockableExample1)
else:
    forms.open_dockable_panel(DockableExample1)`

    
 ##for 2nd dockable window
`class DockableExample5(forms.WPFPanel):
    panel_title = "Button 5 - DOCKWINDOW"
    panel_id = "3110e336-f81c-4927-87da-4e0d30d4d64b"
    panel_source = op.join(op.dirname(__file__), "DockableExample5.xaml")

if not forms.is_registered_dockable_panel(DockableExample5):
    forms.register_dockable_panel(DockableExample5)
    forms.open_dockable_panel(DockableExample5)
else:
    forms.open_dockable_panel(DockableExample5)`

   Error:
  Exception: The requested dockable pane has not been created yet.
Parameter name: id

if i do the following it gives false and the above error
`if not forms.is_registered_dockable_panel(DockableExample5):
    forms.register_dockable_panel(DockableExample5)
    print(forms.is_registered_dockable_panel(DockableExample5)
    forms.open_dockable_panel(DockableExample5)`

**Comment by Tariqshah457** [comment]
Thanks a lot for your reply.
I have already tried to generate a GUID but it only accepts panel_id as a
string. I don't know how to extract the string value from the GUID. I tried
.ToString but it doesn't have that method.

**Comment by dosymep** [comment]
generate than copy to panel class
```
from System import Guid
print Guid.NewGuid()
```

![image](https://github.com/eirannejad/pyRevit/assets/5417225/169e27a7-16ab-4a22-a67a-ffb3925130a2)

**Comment by Tariqshah457** [comment]
yes it worked but now i am still getting the same error 

Exception: The requested dockable pane has not been created yet.
Parameter name: id

**Comment by dosymep** [comment]
Can you try this code?
```
if not forms.is_registered_dockable_panel(DockableExample5):
    forms.register_dockable_panel(DockableExample5)
else:
    forms.open_dockable_panel(DockableExample5)`
```

**Comment by Tariqshah457** [comment]
it doesn't show anything now but when i try the following it output **False**

```
if not forms.is_registered_dockable_panel(DockableExample1):
    forms.register_dockable_panel(DockableExample1)
    print(forms.is_registered_dockable_panel(DockableExample1))
else:
    forms.open_dockable_panel(DockableExample1)
```

**Comment by dosymep** [comment]
maybe problem is time when you register panels. I think panels needs register on startup, and then open after open document.

**Comment by FrancoTonutti** [comment]
DocakblePane must be registered in a zero-doc context, close open documents before registering it. If you do it from a pushbutton or similar you will have to add the following code at the beginning so that the button is available without open documents.

```python
__context__ = 'zero-doc'
```
If you register the panel in the startup.py file, just close any open documents and then reload pyrevit.
