### ISSUE TITLE
Legend component top view of floors - resizing issues

### ISSUE THREAD

**Issue by dbaldzhiev** [eirannejad/pyRevit#1859]
I am trying to use the new feature that sets the orientation of a legend component. Particualarly I am trying to use is for floors. Unfortunately when you set the orienation to top view of a legend component of a floor, it shows up as extremely long element, that can be resized only in one direction, not the other. Is there a fix for that behaviour?

**Comment by jmcouffin** [comment]
> I am trying to use the new feature that sets the orientation of a legend component. Particualarly I am trying to use is for floors. Unfortunately when you set the orienation to top view of a legend component of a floor, it shows up as extremely long element, that can be resized only in one direction, not the other. Is there a fix for that behaviour?

Not that I know, AFAIK this tools makes use of an undocumented feature of the Revit api, see the warning in the tooltip

**Comment by jmcouffin** [comment]
> Not all legend components support any type of view orientation !!!
