### ISSUE TITLE
Command List Useful to Others?

### ISSUE THREAD

**Issue by kjanik11** [eirannejad/pyRevit#186]
Below is a list of PyRevit commands cut from the Keyboardshortcuts file in Revit.  It might be of use to others and for documentation on the website.

Kevin

"Console"
"SyncViews" 
"Spy:Disable Site Designer Addin" 
"Spy:Find All Loaded Assemblies" 
"Spy:Get Central Path" 
"Spy:Get Sys Path" 
"Spy:List Elements"
"Spy:Open Current Project Central Log" 
"Spy:Open Current Session Journal"
"Spy:Open Journals Folder" 
"About" 
"Update" 
"Reload" 
"Extensions" 
"ScriptAnatomy"
"Blog" 
"Docs"
"Repo" 
"Icons8" 
"RegEx Tool" 
"Report Bugs" 
"Settings" 
"Pick:Pick"
"Pick:Pick Detail Elements"
"Pick:Pick Model Elements" 
"Isolate"
"Filter:Discard Grouped Elements" 
"Filter:Discard Pinned Elements" 
"Filter:Keep Elements Hosted On Linked Model" 
"Filter:Keep Painted Elements" 
"Select:Add Group Elements" 
"Select:Add Tagged Elements" 
"Select:Find And Select Entities Without Tags" 
"Select:List Selection as Clickable Links" 
"Select:Select All Clouds Of Specific Revision" 
"Select:Select All Clouds with Same Comment"
"Select:Select All Elements Of Same Family"
"Select:Select All Objects Of Selected Type" 
"Select:Select All Text Notes"
"Select:Select All Vertical Reveals" 
"Select:Select Similar Elements In Active View"
"Select:Select "
"MAppend" 
"MWrite" 
"MRead" 
"Copy State" 
"Paste State"
"Memory:MClear" 
"Memory:MDeduct" 
"Memory:Purge Memory Files" 
"Memory:Save Memory as Selection" 
"Sum Total"
"Analyse:Calculate Average Area" 
"Analyse:Find Range Of Roof Slopes" 
"Inspect:Compare Detail Views" 
"Inspect:Count Lines Of Selected Style" 
"Inspect:Find All Attached Constraints" 
"Inspect:Find Identical Room Numbers" 
"Inspect:Find Linked Elements" 
"Inspect:Find Referenced Views By Selected Elevation Tag"
"Inspect:Find Referencing Sheets" 
"Inspect:Find Views Showing Selected Element" 
"Inspect:Lines Per View Counter" 
"Inspect:List Elements of Selected Level(s)" 
"Inspect:Show Nested Group Structure" 
"Match ?" 
"Dimension:Add Plus Minus" 
"Dimension:Override Dim" 
"Dimension:Set to EQ" 
"Dimension:Set to VIF MFR" 
"Dimension:Set to VIF" 
"Draft:Bring To Front Selected" 
"Draft:Export View As Image" 
"Draft:Halftone Selected Elements In Active View" 
"Draft:Reset Element Graphic Overrides"
"Draft:Solid-Line Selected Elements In Active View"
"Draft:White-Out Selected Model Elements In Active View" 
"Text:Merge Paragraphs" 
"Text:Merge Text Notes" 
"Text:Remove Returns In Text" 
"Text:Text To Lower" 
"Text:Text To Sentence Case"
"Text:Text To Upper" 
"Edit:Change Element Type Safely"
"Edit:Flip Facing Selected Doors"
"Edit:Flip Hand Selected Doors"
"Edit:Flip Wall Location Line" 
"Edit:Flip Wall Orientation" 
"Edit:Make Pattern"
"Edit:Shake Filled Regions" 
"Edit:Swap Line Styles"
"Edit:Tag All Rooms in All Views"
"Edit:Tag All Spaces in All Views"
"Groups:Explode And Remove Selected Groups"
"Groups:Find All Groups Containing Selected Group" 
"Groups:Find All Groups With Text Notes"
"Site:Get Parking Count In Current View" 
"3D:Orient Section Box To Face" 
"3D:Orient View To Face" 
"Sheets:Add Selected Viewports To Selected Sheets" 
"Sheets:Move Selected Viewports To Selected Sheets" 
"Sheets:Batch Sheet Maker" 
"Sheets:Open Selected Viewport"
"Sheets:Rename All Sheets To UpperCase" 
"Sheets:Set Crop Region To Selected Shape" 
"Sheets:Decrement Selected Sheet Numbers" 
"Sheets:Increment Selected Sheet Numbers" 
"Sheets:Fix Unpurgable Viewport Types"
 
"Revision:Create Revised Sheet Set" 
"Revision:Find All Revised Sheets" 
"Revision:Find All Revision Clouds On Views" 
"Revision:Find All Sheets Missing Revision Number" 
"Revision:Find All Sheets With Selected Revision" 
"Revision:Generate Revision Report" 
"Revision:List Legends with Revision Clouds" 
"Revision:Remove Revision From Sheets" 
"Revision:Set Revision On All Sheets" 
"Revision:Turn Off All Revisions" 
"Legends:Copy Selected Legends As Detail Views To Open Documents" 
"Legends:Copy Selected Legends To Open Documents" 
"Legends:Duplicate Selected Detail Views As Legends"
"Legends:Duplicate Selected Legends As Detail Views" 
"Legends:Find Unused Keynotes" 
"Legends:Open Keynotes File" 
"Schedules:Export Schedule To Text On Desktop"
"Views:Change Selected View Names To UpperCase" 
"Views:Create Print Set From Selected Views"
"Views:Duplicate Selected Views With Detailing" 
"Views:Duplicate Selected Views Without Detailing" 
"Views:Find Referring Views" 
"Views:Find Sheeted But Unreferenced Views" 
"Views:Find Unreferenced Views" 
"Views:Find Unsheeted Views"
"Views:Find Used View Templates Filters" 
"Views:Find Views With Template" 
"Views:Find Views With Underlay" 
"Views:Open Referencing Sheet" 
"Views:Purge Unused Filters" 
"Views:Purge Unused View Templates"
"Views:Remove Empty Elevation Tags" 
"Views:Remove Underlay From Selected Views"
"Print:Print Linked Sheets" 
"Print:Print Ordered Sheet Index"
"Print:Rename PDF Sheets On Desktop"
"Print:Toggle Revu Filename Popup"
"Family:Convert Family To Face Host Based" 
"Family:Load Family Types"
"Family:Purge And Reset All Unused Family Parameters" 
"Family:Wipe All Family Parameters" 
"Family:Wipe Detail Item Categories"
"Links:Create Workset For Linked Element" 
"Links:Export All Raster Images To Desktop"
"Links:List DWGs in Current View" 
"Links:List DWGs" 
"Links:Reload CAD Links" 
"Links:Reload REVIT Links" 
"Links:Remove All Links"
 
"Team:Find Sheets With Elements Owned By Me"
"Team:Select Last Edited By Me In Current View" 
"Team:Select Owned By Me In Current View"
"Team:Who Created Active View" 
"Team:Who Created Selected Element"
"Team:Who Reloaded Keynotes Last"
"Wipe:Delete IMPORT Line Patterns"
"Wipe:Delete Site Designer Line Styles" 
"Wipe:Remove All Constraints Attached To Selected Obj" 
"Wipe:Wipe All Project Parameters"
"Wipe:Wipe Model Components" 
"Wipe:Wipe Render Materials"

**Comment by eirannejad** [comment]
Cool. I'll close this since it's searchable.
