### ISSUE TITLE
Crashes Revit 2021 @ Splash page

### ISSUE THREAD

**Issue by MattC79Github** [eirannejad/pyRevit#1860]
Installed current version of Pyrevit and when starting Revit 2021 splash page shows but then revit crashes.

![Pyrevit](https://github.com/eirannejad/pyRevit/assets/138702511/2243b173-c12c-4d3d-b194-fc0eabbb8ce2)

**Comment by jmcouffin** [comment]
most probably an addin conflict.
try use the[ diroots app manager](https://diroots.com/apps/diroots-app-manager/) to deactivate all Revit addins and then reactivacte them one at a time and try to start revit every time @MattC79Github

**Comment by MattC79Github** [comment]
When I uninstall Pyrevit I don't have an issue opening Revit. Why do I need to test each add in?

**Comment by jmcouffin** [comment]
It all boils down to the loading sequence of addins in Revit OR dlls hell
It can be one or the other that makes it crashing
If you deactivate all addins except pyrevit you should see Revit  + pyrevit working right away (99% of the cases), then you can work your way up.
What could help debugging is seeing the content of your revit journal file for your revit version that is crashing

**Comment by MattC79Github** [comment]
I downloaded Diroots turned everything off and still Revit won't open with pyrevit installed.
I thought I would take an additive approach instead

***@***.***

Matt Crowley
Architect

WDG ARCHITECTURE DALLAS, PLLC
2001 Bryan Street, Suite 3100
Dallas, TX  75201
ph 469.398.0686



www.wdgarch.com<http://www.wdgarch.com/>

[instagram]<https://www.instagram.com/wdgarch/>    [facebook] <https://www.facebook.com/WDGarchitecture/>     [linkedin] <https://www.linkedin.com/company/wdg-architecture/>

**Comment by jmcouffin** [comment]
💯 
I'd be interested in seeing that journal file.
That might say what is happening

**Comment by MattC79Github** [comment]
Sorry to ask this but I’ve tried googling it and looking in my C drive and I’m not finding my journal files. Where should I look to find these?

**Comment by jmcouffin** [comment]
https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Location-of-journal-files.html#:~:text=Journal%20files%20are%20stored%20in,Autodesk%20Revit%20%5CJournals

**Comment by MattC79Github** [comment]
Matt Crowley
Architect

WDG ARCHITECTURE DALLAS, PLLC
2001 Bryan Street, Suite 3100
Dallas, TX  75201
ph 469.398.0686



www.wdgarch.com<http://www.wdgarch.com/>

[instagram]<https://www.instagram.com/wdgarch/>    [facebook] <https://www.facebook.com/WDGarchitecture/>     [linkedin] <https://www.linkedin.com/company/wdg-architecture/>

**Comment by jmcouffin** [comment]
you may want to attach the file instead as the end (the meaningful part) is trimmed when too long of a text is pasted in github comments

**Comment by MattC79Github** [comment]
[journal.0164.worker1.log](https://github.com/eirannejad/pyRevit/files/11962553/journal.0164.worker1.log)
[journal.0164.txt](https://github.com/eirannejad/pyRevit/files/11962554/journal.0164.txt)
[journal.0163.txt](https://github.com/eirannejad/pyRevit/files/11962555/journal.0163.txt)
[journal.0163.worker1.log](https://github.com/eirannejad/pyRevit/files/11962556/journal.0163.worker1.log)

**Comment by jmcouffin** [comment]
okay, 
loads of stuff.
let's start with the obvious, your Revit 2021 version is an old one.
Can you update it?

**Comment by MattC79Github** [comment]
[journal.0165.worker1.log](https://github.com/eirannejad/pyRevit/files/11969070/journal.0165.worker1.log)
[journal.0166.txt](https://github.com/eirannejad/pyRevit/files/11969071/journal.0166.txt)
[journal.0166.worker1.log](https://github.com/eirannejad/pyRevit/files/11969072/journal.0166.worker1.log)
[journal.0165.txt](https://github.com/eirannejad/pyRevit/files/11969073/journal.0165.txt)
Updated and ran with crash. Journal file attached.

**Comment by jmcouffin** [comment]
It mentions conflicts of DLLs and assemblies. I am not in front of a computer to check it properly.
Would you mind running the command line `pyrevit env `and paste the result here

**Comment by MattC79Github** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

Loading personal and system profiles took 860ms.
PS C:\WINDOWS\system32> pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
Unknown | Product: "2023 First Customer Ship" | Manifest: "C:\Users\Matt.crowley\AppData\Roaming\Autodesk\Revit\Addins\2023\pyRevit.addin"
Unknown | Product: "Autodesk Revit 2021" | Manifest: "C:\Users\Matt.crowley\AppData\Roaming\Autodesk\Revit\Addins\2021\pyRevit.addin"
Unknown | Product: "2019.2.2 Hotfix" | Manifest: "C:\Users\Matt.crowley\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Matt.crowley\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2023 First Customer Ship | Version: 23.0.1.318 | Build: 20220304_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2021 | Version: 21.1.80.35 | Build: 20230515_0935(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: WDGDAL\Matt.Crowley
Active User: WDGDAL\Matt.Crowley
Admin Access: Yes
%APPDATA%: "C:\Users\Matt.crowley\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.13.23182+2215
PS C:\WINDOWS\system32>

**Comment by jmcouffin** [comment]
Would you mind uninstalling pyRevit,
Try the `pyrevit env` again (it should not work unless you installed pyRevit cli separately)
Re install pyRevit with latest release
And run `pyrevit env` and paste the output again

**Comment by jmcouffin** [comment]
Install pyRevit with the installer that does not have admin as a suffix.

**Comment by jmcouffin** [comment]
Another possible lead
https://github.com/eirannejad/pyRevit/issues/1609#issuecomment-1329239244

**Comment by jmcouffin** [comment]
https://github.com/eirannejad/pyRevit/issues/1055#issuecomment-869831278

**Comment by jmcouffin** [comment]
Any news?

**Comment by jmcouffin** [comment]
Related #1802
