### ISSUE TITLE
Silent install switch in 2024 release

### ISSUE THREAD

**Issue by aussieBIMguru** [eirannejad/pyRevit#1861]
According to my installer developer (using Intune), the silent install switch appears to result in no install occurring when run both in/out of Intune.

Historically we managed to silent install using the Install command \silent.

Just wanted to verify if this may have changed - we can keep troubleshooting internally for now.

Using installer on latest release:
pyRevit_4.8.13.23182_admin_signed.exe
Windows 11

**Comment by jmcouffin** [comment]
Not in front of a computer to try it but you could check the silent install arguments first
https://www.pdq.com/blog/install-silent-finding-silent-parameters/

**Comment by aussieBIMguru** [comment]
Thanks! It appears there is a silent/verysilent option, but my colleague seems to not be able to get them to work. I've got them try both Windows 10 and 11. Curious if anyone else has got silent install via MSI to work, if so it must be something on our end... will close issue in that case.

Previous WIP and formal installers seemed to work, so unsure if that's the case.

![install switchesd](https://github.com/eirannejad/pyRevit/assets/58870499/b115ddae-fc27-4c55-b9a0-10d62cbdf9e7)

**Comment by aussieBIMguru** [comment]
We found the verysilent switch worked, so might be an issue with the silent one only.

"pyRevit_4.8.13.exe" /VERYSILENT /SUPPRESSMSGBOXES

This worked for us.
