### ISSUE TITLE
Failed to save config file

### ISSUE THREAD

**Issue by thumDer** [eirannejad/pyRevit#1864]
**Describe the bug**
I understand that this is a long time known bug, and it still happens quite offen to our users. If multiple revit sessions are starting simulteanously, some of them fails to load pyrevit, because `pyRevit_config.ini` is locked by one of the others. We should fiugre out something to fix it. Related to #1280 

![kép](https://github.com/eirannejad/pyRevit/assets/54556708/ab021319-b1c3-4383-8395-f568e120ff8e)

**Comment by jmcouffin** [comment]
Great @thumDer 
I will try you fix tomorrow.
That has annoyed me for quite some time but never got the space to dig into it.

**Comment by jmcouffin** [comment]
Tested and approved
