### ISSUE TITLE
Pyrevit 2024 new version doesn't work on my revit 2024, how can i solve this?

### ISSUE THREAD

**Issue by Simo-Billy** [eirannejad/pyRevit#1867]
**Describe the bug**
I installed pyrevit last version 4.8.13.23182,  but however doesn't load on my revit 2024, it doesn't appear in ribbon bar and also if i try to work in command prompt with command "pyrevit attach" or "pyrevit clones" it doesn't work. 

When i try to attach master it's written that there aren't issue installed, so i try clones master but after cloning, when i go to installed version appear nothing, how can i solve?

 - OS: Win 11
 - pyRevit Version 4.8.13.23182
 - pyRevit Environment: 
C:\Users\Simone>pyrevit --debug
Debug: Arg processing failed. | Usage:
        pyrevit (-h | --help)
        pyrevit (-V | --version)
        pyrevit --usage
        pyrevit (wiki | blog | docs | source | youtube | support)
        pyrevit env [--json] [(-h | --help)] [--log=<log_file>]
        pyrevit update [--help] [--log=<log_file>]
        pyrevit clone (-h | --help)
        pyrevit clone <clone_name> <deployment_name> [--dest=<dest_path>] [--branch=<branch_name>] [--log=<log_file>]
        pyrevit clone <clone_name> --image=<image_url> [--dest=<dest_path>] [--log=<log_file>]
        pyrevit clone <clone_name> [--dest=<dest_path>] [--source=<repo_url>] [--branch=<branch_name>] [--log=<log_file>] [(--username=<username> --password=<password> | --token=<auth_token>)]
        pyrevit clones [(-h | --help)]
        pyrevit clones (info | open) <clone_name>
        pyrevit clones add this <clone_name> [--force] [--log=<log_file>]
        pyrevit clones add <clone_name> <clone_path> [--force] [--log=<log_file>]
        pyrevit clones forget (--all | <clone_name>) [--log=<log_file>]
        pyrevit clones rename <clone_name> <clone_new_name> [--log=<log_file>]
        pyrevit clones delete [(--all | <clone_name>)] [--clearconfigs] [--log=<log_file>]
        pyrevit clones branch <clone_name> [<branch_name>] [--log=<log_file>]
        pyrevit clones version <clone_name> [<tag_name>] [--log=<log_file>]
        pyrevit clones commit <clone_name> [<commit_hash>] [--log=<log_file>]
        pyrevit clones origin <clone_name> --reset [--log=<log_file>]
        pyrevit clones origin <clone_name> [<origin_url>] [--log=<log_file>]
        pyrevit clones update (--all | <clone_name>) [--log=<log_file>] [(--username=<username> --password=<password> | --token=<auth_token>)]
        pyrevit clones deployments <clone_name>
        pyrevit clones engines <clone_name>
        pyrevit attach (-h | --help)
        pyrevit attach <clone_name> (default | <engine_version>) (<revit_year> | --installed | --attached) [--allusers] [--log=<log_file>]
        pyrevit attached [<revit_year>] [(-h | --help)]
        pyrevit switch (-h | --help)
        pyrevit switch <clone_name> [<revit_year>]
        pyrevit detach (-h | --help)
        pyrevit detach (--all | <revit_year>) [--log=<log_file>]
        pyrevit extend (-h | --help)
        pyrevit extend <extension_name> [--dest=<dest_path>] [--branch=<branch_name>] [--log=<log_file>]
        pyrevit extend (ui | lib) <extension_name> <repo_url> [--dest=<dest_path>] [--branch=<branch_name>] [--log=<log_file>] [(--username=<username> --password=<password> | --token=<auth_token>)]
        pyrevit extensions [(-h | --help)]
        pyrevit extensions search <search_pattern>
        pyrevit extensions (info | help ) <extension_name>
        pyrevit extensions open <extension_name>
        pyrevit extensions open <clone_name> <extension_name>
        pyrevit extensions delete <extension_name> [--log=<log_file>]
        pyrevit extensions origin <extension_name> --reset [--log=<log_file>]
        pyrevit extensions origin <extension_name> [<origin_url>] [--log=<log_file>]
        pyrevit extensions paths [(-h | --help)]
        pyrevit extensions paths forget --all [--log=<log_file>]
        pyrevit extensions paths (add | forget) <extensions_path> [--log=<log_file>]
        pyrevit extensions (enable | disable) <extension_name> [--log=<log_file>]
        pyrevit extensions (enable | disable) <clone_name> <extension_name> [--log=<log_file>]
        pyrevit extensions sources [(-h | --help)]
        pyrevit extensions sources forget --all [--log=<log_file>]
        pyrevit extensions sources (add | forget) <source_json_or_url> [--log=<log_file>]
        pyrevit extensions update (--all | <extension_name>) [--log=<log_file>] [(--username=<username> --password=<password> | --token=<auth_token>)]
        pyrevit releases (-h | --help)
        pyrevit releases [--pre] [--notes]
        pyrevit releases latest [--pre] [--notes]
        pyrevit releases <search_pattern> [--pre] [--notes]
        pyrevit releases open latest [--pre]
        pyrevit releases open <search_pattern> [--pre]
        pyrevit releases download (installer | archive) <search_pattern> [--dest=<dest_path>] [--pre]
        pyrevit revits
        pyrevit revits (-h | --help)
        pyrevit revits [--installed] [--log=<log_file>]
        pyrevit revits --supported [--csv=<output_file>]
        pyrevit revits killall [<revit_year>] [--log=<log_file>]
        pyrevit revits fileinfo <file_or_dir_path> [--csv=<output_file>] [--rvt] [--rte] [--rfa] [--rft]
        pyrevit run (-h | --help)
        pyrevit run commands
        pyrevit run <script_or_command_name> [--revit=<revit_year>] [--purge] [--allowdialogs] [--import=<import_path>]        pyrevit run <script_or_command_name> --models=<model_list_file> --revit=<revit_year> [--purge] [--allowdialogs] [--import=<import_path>]
        pyrevit run <script_or_command_name> <model_file> [--revit=<revit_year>] [--purge] [--allowdialogs] [--import=<import_path>]
        pyrevit caches (-h | --help)
        pyrevit caches [bim360] clear (--all | <revit_year>) [--log=<log_file>]
        pyrevit config (-h | --help)
        pyrevit config --from=<template_config_path> [--log=<log_file>]
        pyrevit configs (-h | --help)
        pyrevit configs bincache [(enable | disable)] [--log=<log_file>]
        pyrevit configs checkupdates [(enable | disable)] [--log=<log_file>]
        pyrevit configs autoupdate [(enable | disable)] [--log=<log_file>]
        pyrevit configs rocketmode [(enable | disable)] [--log=<log_file>]
        pyrevit configs logs [(none | verbose | debug)] [--log=<log_file>]
        pyrevit configs filelogging [(enable | disable)] [--log=<log_file>]
        pyrevit configs startuptimeout [<timeout>] [--log=<log_file>]
        pyrevit configs loadbeta [(enable | disable)] [--log=<log_file>]
        pyrevit configs cpyversion [<cpy_version>] [--log=<log_file>]
        pyrevit configs usercanupdate [(yes | no)] [--log=<log_file>]
        pyrevit configs usercanextend [(yes | no)] [--log=<log_file>]
        pyrevit configs usercanconfig [(yes | no)] [--log=<log_file>]
        pyrevit configs colordocs [(enable | disable)] [--log=<log_file>]
        pyrevit configs tooltipdebuginfo [(enable | disable)] [--log=<log_file>]
        pyrevit configs routes [(-h | --help)]
        pyrevit configs routes [(enable | disable)] [--log=<log_file>]
        pyrevit configs routes port [<port_number>] [--log=<log_file>]
        pyrevit configs routes coreapi [(enable | disable)] [--log=<log_file>]
        pyrevit configs telemetry [(-h | --help)]
        pyrevit configs telemetry [(enable | disable)] [--log=<log_file>]
        pyrevit configs telemetry utc [(yes | no)] [--log=<log_file>]
        pyrevit configs telemetry (file | server) [<dest_path>] [--log=<log_file>]
        pyrevit configs telemetry hooks [(yes | no)] [--log=<log_file>]
        pyrevit configs apptelemetry [(enable | disable)] [--log=<log_file>]
        pyrevit configs apptelemetry flags [<flags>] [--log=<log_file>]
        pyrevit configs apptelemetry server [<server_path>] [--log=<log_file>]
        pyrevit configs outputcss [<css_path>] [--log=<log_file>]
        pyrevit configs seed [--lock] [--log=<log_file>]
        pyrevit configs <option_path> [(enable | disable)] [--log=<log_file>]
        pyrevit configs <option_path> [<option_value>] [--log=<log_file>]
    pyrevit doctor (-h | --help)
    pyrevit doctor [--list]
    pyrevit doctor <doctor_command> [--dryrun]
Usage: pyrevit COMMAND [OPTIONS]

Run 'pyrevit COMMAND --help' for more information on a command.

C:\Users\Simone>C:\Users\Simone\AppData\Roaming\pyRevit-MasterC:\Users\Simone\AppData\Roaming\pyRevit-Master

C:\Users\Simone>pyrevit clones
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.13.23182+2215" | Path: "C:\Users\Simone\AppData\Roaming\pyRevit-Master"

C:\Users\Simone>pyrevit attach master 277 --installed
Error: Riferimento a un oggetto non impostato su un'istanza di oggetto.
Run with "--debug" option to see debug messages

C:\Users\Simone>pyrevit clones add master "C:\Users\Simone\AppData\Roaming\pyRevit-Master"
Error: Clone with repo path "C:\Users\Simone\AppData\Roaming\pyRevit-Master" already exists.
Run with "--debug" option to see debug messages

**Comment by jmcouffin** [comment]
try `pyrevit attach master 2711 --installed --allusers` in the command line

**Comment by jmcouffin** [comment]
if that does not work I would try to uninstall it then reinstall it.

**Comment by jmcouffin** [comment]
@Simo-Billy any news?

**Comment by Simo-Billy** [comment]
nope, it doesn't work anymore, or i disinstall/re-install or also when i use new prompt directions like. why?

**Comment by jmcouffin** [comment]
> nope, it doesn't work anymore, or i disinstall/re-install or also when i use new prompt directions like. why?

Sorry, I don't understand your reply.
If uninstalling-reinstalling is a question, yes you should try that, and also clear the %appdata% pyrevit folders

After installing the latest version, please paste the results of the **`pyrevit env`** command here

**Comment by Simo-Billy** [comment]
after unistalling-reinstalling it always doesn't work :( 

this is pyrevit env:
C:\Users\Simone>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.13.23182+2215" | Path: "C:\Users\Simone\AppData\Roaming\pyRevit-Master"
==> Attachments
Error: Riferimento a un oggetto non impostato su un'istanza di oggetto.
Run with "--debug" option to see debug messages

**Comment by jmcouffin** [comment]
And running this
pyrevit attach master 2711 --installed --allusers
Does it throw an error?
And the 'pyrevit env' command after that spits the same error?

**Comment by Simo-Billy** [comment]
**C:\Users\Simone>pyrevit attach master 2711 --installed --allusers**
Error: Riferimento a un oggetto non impostato su un'istanza di oggetto.
Run with "--debug" option to see debug messages

**C:\Users\Simone>pyrevit env**
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.13.23182+2215" | Path: "C:\Users\Simone\AppData\Roaming\pyRevit-Master"
==> Attachments
Error: Riferimento a un oggetto non impostato su un'istanza di oggetto.
Run with "--debug" option to see debug messages

?? why ??

**Comment by jmcouffin** [comment]
@Simo-Billy any news?
