### ISSUE TITLE
Ironpython 3.4:  issue with enum when using its `None` member ?

### ISSUE THREAD

**Issue by CyrilWaechter** [eirannejad/pyRevit#1873]
**Describe the bug**
Apparently ironpython 3.4 has an issue with some Enum. It might be related to `None` member.
It affects apparently all script which using a `WPFWindow`.
```python
from pyrevit.forms import WPFWindow
```
It triggers an error here:
https://github.com/eirannejad/pyRevit/blob/6aa2c493231f4301125f2570dc5efd644691bbad/pyrevitlib/rpw/ui/forms/taskdialog.py#L140

**To Reproduce**
1. Use a script including following code:
```python
from Autodesk.Revit.UI import TaskDialogResult
TaskDialogResult.None
```
2. You should get an error message like:
```python
TaskDialogResult.None
                 ^
SyntaxError: invalid syntax
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - pyRevit Version 4.8.13

**Additional context**
I found no related issue in ironpython repository.

**Comment by dosymep** [comment]
Could you write this import and test?

```python
from Autodesk.Revit.UI import TaskDialogResult
```

**Comment by CyrilWaechter** [comment]
> Could you write this import and test?
> 
> ```python
> from Autodesk.Revit.UI import TaskDialogResult
> ```

It is what I did in steps `To reproduce`. Import works. Error is thrown when calling `None` member. (You can use revitpythonshell 2.0.1 to test, you get the same result)

**Comment by dosymep** [comment]
Okay, I see. I found solution in dynamo wiki.

https://github.com/DynamoDS/Dynamo/wiki/Work-in-progress-to-improve-Python-3-support#accessing-a-net-property-or-enum-named-none-fails-with-syntaxerror-not-planned

**Comment by CyrilWaechter** [comment]
Ah… Yes. Now I remember that I already encountered this issue on some of my CPython scripts. Thanks @dosymep 

It is an easy fix. As rpw have not been updated for more than 4 years maybe we should commit directly to pyRevit ?
Although I do not understand yet why using `WPFWindow` needs to be related to rpw at all.

**Comment by Cyril-Pop** [comment]
Hi,
for info instead of 
`self.dialog.DefaultButton = UI.TaskDialogResult.None `
you can also use 
`self.dialog.DefaultButton = UI.TaskDialogResult["None"]`

there is an IronPython3 doc about upgrading from ipy2 here
https://github.com/IronLanguages/ironpython3/blob/v3.4.0/Documentation/upgrading-from-ipy2.md#none-is-a-keyword

**Comment by nodatasheet** [comment]
there is also a method in coreutils for that: [get_enum_none](https://github.com/eirannejad/pyRevit/blob/6aa2c493231f4301125f2570dc5efd644691bbad/pyrevitlib/pyrevit/coreutils/__init__.py#L1177)

**Comment by jmcouffin** [comment]
@CyrilWaechter I did merge you PR but you may want to check if @nodatasheet link does the job

**Comment by CyrilWaechter** [comment]
> @CyrilWaechter I did merge you PR but you may want to check if @nodatasheet link does the job

The coreutils get_enum_none is using a loop and compare each value to None which is less efficient than a a dict call or whatever is used by standard ironpython function.

**Comment by jbf1212** [comment]
The fix that was pushed for this appears to create an issue when the tool is still being run with IronPython 2. You will get the following error:
TypeError: expected Array[Type], got str

Is the plan going forward to deprecate support for IronPython 2?

**Comment by CyrilWaechter** [comment]
> The fix that was pushed for this appears to create an issue when the tool is still being run with IronPython 2. You will get the following error: TypeError: expected Array[Type], got str
> 
> Is the plan going forward to deprecate support for IronPython 2?

The fix works with ironpython 2. Ironpython 2.7.10 is still default on my setup and it still works fine.

**Comment by jbf1212** [comment]
Okay, yea I'm seeing the issue on v 2.7.7. I'm not sure what pyRevit assumes the default version to be, but perhaps we can add a check here or something.

**Comment by CyrilWaechter** [comment]
> Okay, yea I'm seeing the issue on v 2.7.7. I'm not sure what pyRevit assumes the default version to be, but perhaps we can add a check here or something.

From what I remember ironpython 2.7.7 was maintained because it was shipped with Dynamo to ensure compatibility with Dynamo script. Dynamo have been shipping ironpython 2.7.9 from version 2.4.0 and ironpython2 evaluator is not shipped anymore from 2.13. If it is really an ironpython version issue I would vote to deprecate ironpython < 2.7.10.

2.7.7 was released in 2016… 8 years old. It’s time to update.

References:
* Dynamo release notes: https://github.com/DynamoDS/Dynamo/wiki/Release-Notes
* Ironpython website: https://ironpython.net/

**Comment by jmcouffin** [comment]
@CyrilWaechter what action do you suggest on the pyRevit repo side, if any?

**Comment by CyrilWaechter** [comment]
> @CyrilWaechter what action do you suggest on the pyRevit repo side, if any?

Remove older ironpython engines (At least < 2.7.9). I wonder if there is still a reason to ship multiple ironpython2 engines ? If not maybe it would worth even to ship only 2.7.12 which is the last version available.

On there might be a need to push ironpython engine update. Maybe:
* Step 1 (pyRevit release n): warn user that older engines will be deprecated and propose them to update
* Step 2 (pyRevit release n+1): remove deprecated engines

**Comment by dosymep** [comment]
@jmcouffin, Maybe good idea support only latest version IronPython2, IronPython3 and PythonNet

**Comment by jbf1212** [comment]
Thanks for the replies @CyrilWaechter - another thing we might consider is nudging people to use the pyrevit versions of some of the functionalities built into rpw. For example, the _taskdialog_ method in rpw and the _alert_ method in pyrevit are essentially the same thing. So rather than maintain both going forward, we may consider just sunsetting the rpw functions that have pyrevit equivalents.

**Comment by jmcouffin** [comment]
Now, the 2711 engine is the only one available for ipy2.
Older engines have been removed.
Closing for now
