### ISSUE TITLE
4.8.13 blocking Desktop Connector

### ISSUE THREAD

**Issue by Dre-Tas** [eirannejad/pyRevit#1879]
Hey guys!

We noticed this new bug introduced with pyRevit 4.8.13 that seems to be blocking/hiding Desktop Connector in Revit 2023 (doesn't happen in other versions, but we haven't tested Revit 2024).

All files linked into the current model get unlinked and there is no way to relink them, because when you go to Manage Links > Add or Insert Revit Link you're unable to see hub folders or any subfolders. Like in the screenshot:
![image](https://github.com/eirannejad/pyRevit/assets/36023527/d683e068-5941-43dc-a54d-5b29c6f5c72b)

We tried uninstalling pyRevit and it goes back to normal (you can see the folder icon in the new screenshot):
![image](https://github.com/eirannejad/pyRevit/assets/36023527/3d79c93f-3d3d-4f09-a792-eba28f09f8cc)

To make sure, we also tried installing pyRevit without Wombat (the extension we internally develop) and it still doesn't work, so we're sure this is a pyRevit issue.

**Comment by jmcouffin** [comment]
@Dre-Tas nothing related to the desktop connector has changed in the pyrevit code base between 4.8.12 and .13. Nothing that I can think of relates to that.
could you report back with a `pyrevit env` log, a journal file of your session, the list of the revit plugin installed and version of the desktop connector installed

**Comment by jmcouffin** [comment]
there are quite a few articles on the autodesk support website related to your issue:
https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Autodesk-Desktop-Connector-not-displaying-all-contents-of-folders.html

**Comment by Dre-Tas** [comment]
Hey @jmcouffin sorry for the delay. The guys I was waiting the info from were on holiday. They just got back to me.
![MicrosoftTeams-image (6)](https://github.com/eirannejad/pyRevit/assets/36023527/14a420cc-6078-480a-be3e-40ff00627402)

REVIT VERSION – 23.1.20.70

DESKTOP VERSION – 16.3.0.2035

As per the journal file, do you have an email address where I can send that?

**Comment by Dre-Tas** [comment]
@jmcouffin I don't see any PM in my inbox. Did you send it yet?

**Comment by jmcouffin** [comment]
Newtonsoft conflicting according to Andreas.
Recompiling the dll with new name can solve this dll hell
