### ISSUE TITLE
Idea for Tool: If Title on Sheet Null Copy View Name to Title on Sheet with Prefix

### ISSUE THREAD

**Issue by kjanik11** [eirannejad/pyRevit#188]
When copying make uppercase also. I try to get people to us Title on Sheet so View names can be named upper and lowercase and all View Titles on Sheet are uppercase.  Makes browser naming easier to read and more descriptive sometimes.  If a prefix character was added people would see the name might need to be adjusted.

**Comment by eirannejad** [comment]
Note: Create a generic tool to set `Title on Sheet` based on view name. Tool could use the `%field%` format the way batch renamers work so extract info from view name and apply in a new format to `Title on Sheet`

**Comment by eirannejad** [comment]
I'll update you when it's ready.

**Comment by eirannejad** [comment]
- [ ] Create Reformat function that gets the source string, source format, new format, and returns the reformatted string
- [ ] Collect elements that this tool can work on and properties
- [ ] Create user interface
- [ ] Create tool backend

**Comment by kjanik11** [comment]
Endangered,

What book on Python or web reference would we of the best benefit understanding how Python scripts are formatted and especially, I would call it a function reference to help me know how to create different types of variables, arrays or lists, loops, share variables from one function to another etc.? I learned LISP with the AutoCAD LISP Reference.  It had all the functions that were available and some examples which helped.

Kevin
_____________________________

**Comment by eirannejad** [comment]
I learned python from the python tutorials on their website and found it very useful:

https://docs.python.org/2.7/tutorial/index.html <https://docs.python.org/2.7/tutorial/index.html>

Hope this helps…

**Comment by eirannejad** [comment]
Cancelled. Started working on this but in nature, assigning Title on Sheet from View names is very specific to the company, project, user and the standards. I'm not sure that time-saved would justify the time spent on the tool.

I'm closing this for now but keep the conversation going. We'll reopen if we find a good solution/workflow.
