### ISSUE TITLE
search tool not working properly..

### ISSUE THREAD

**Issue by useromi** [eirannejad/pyRevit#1881]
**Describe the bug**
Search tool in the pyrevit not working properly sometimes it's not responding to given instructions. when it's not responding it also not gave a suggestion for tool when this search tool is active.

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

**To Reproduce**

**Expected behavior**
I need a quick suggestion and action when search command is active. it's not performing this search task. 

**Screenshots**
![image](https://github.com/eirannejad/pyRevit/assets/141024668/bb872944-f182-4705-bf78-64836c74abdb)

**Desktop (please complete the following information):**
 - OS: [Microsoft]
 - pyRevit Version [4.8.13]
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

**Additional context**

**Comment by sanzoghenzo** [comment]
Hi @useromi,
Can you please fill the info requested in the issue template? It will help us better understand your situation.

Also, try to run the search in debug mode (CTRL+click on the search button) and see if you find messages like "unique results" and other messages related to "search".

**Comment by useromi** [comment]
I think, I know the reason behind this problem. the search tool is case sensitive. it doesn't work when caps lock is on. it is working fine while caps lock is off.
