### ISSUE TITLE
incld pyRevit to minify ui and/or a way to place pyRevit (and extensions) tabs to Add-Ins tab 

### ISSUE THREAD

**Issue by studioearl** [eirannejad/pyRevit#1882]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
two things:
1) couldn't find this feature request/bug report on pyRevit notion site
2) can pyRevit and extensions be placed under the Add-Ins tab instead of having their own tab? or can pyRevit be added to the minify UI list? 

**Describe alternatives you've considered**
1) research
2) use the alt click to find the buttons and see if there was a directory for the Revit Add-Ins tab; couldn't figure a way. 

**Additional context**

**Comment by jmcouffin** [comment]
- How would it serve other users of the community?

- adding the pyRevit tab to the minifyUI Tool is an ouroboro situation: the minifyUI tool is part of the pyrevit tool, so you activate it, the pyRevit tab disappears as well as the ability to use the minifyUI tool 😄 

- the addins tab will probably be way to crowded if you move pyrevit there

- you could move things around, there are a few examples around here to move or place tools wherever you need: https://thebuildingcoder.typepad.com/blog/2014/06/room-editor-live-and-unofficial-custom-ribbon-button.html#4
https://thebuildingcoder.typepad.com/blog/2014/07/moving-an-external-command-button-within-the-ribbon.html

Quote:
> The Revit API officially does not support use of the Autodesk.Windows functionality, so you are on your own if you are making use of that.

- you could create your own clone or pyRevit and reorganize tools the way you want.
clone repo -> modify tools -> install this repo on the machines you want
Downside being you would need to redo it once in a while with new version of pyRevit to keep up to date, but probably not more than once a year
