### ISSUE TITLE
Make Patterns error message

### ISSUE THREAD

**Issue by Lwarrior88** [eirannejad/pyRevit#189]
Hello,

I get this message every time i try to make a patter.
![make pattern_pyrevit](https://cloud.githubusercontent.com/assets/28010719/25394137/6e8a871c-29ab-11e7-848c-4e7bcedc8a5a.PNG)

Could you please help me understand this.

**Comment by eirannejad** [comment]
@Lwarrior88 This means that pyRevit can not read its git repository to get the version. This error will happen on any tool that wants to read the version.

Did you install pyRevit using the installer? or other methods?

**Comment by eirannejad** [comment]
Make sure that pyRevit is installed using the installer or the git repository is manually cloned. Otherwise you'll see this error because pyRevit can not determine its version.
