### ISSUE TITLE
pyRevit not working on 2024 revit. it get crash everytime i install the latest version of pyRevit.

### ISSUE THREAD

**Issue by ashwinpr3009** [eirannejad/pyRevit#1901]
Please attach or send a screenshot of the 2024 Revit with pyRevit installed on your PC. Our IT guys doubt it will not work on any PC. we tried all we can to work but not getting the result.

**Comment by jmcouffin** [comment]
Can you elaborate a bit?
- version of pyRevit installed (WIP Installer or the Latest Release)
- a screen capture of the error
- the result of the pyrevit env command
- you journal file

**Comment by ashwinpr3009** [comment]
it is a sentinel issue, resolved now thanks
