### ISSUE TITLE
Keynotes and Collaboration with other team members

### ISSUE THREAD

**Issue by Jdivina24** [eirannejad/pyRevit#1903]
When trying to use Manage keynotes in my project it is saying another party is working in the keynote file when the other party was never in the keynote file.  The other parties would constantly save and relinquish Revit even though they haven’t touched keynotes in a while.  

**To Reproduce**
1. Use manage keynotes
2. Try and change a specific keynotes
3. See error

**Expected behavior**
The ability to change and update keynotes without an error someone else is using it.

**Desktop (please complete the following information):**
 
 - pyRevit Version 4.8.12

**Comment by jmcouffin** [comment]
Where is the keynote file located?

**Comment by Jdivina24** [comment]
> Where is the keynote file located?

@jmcouffin It is located on our server within the project. I may add that we have keynote manager installed on our machines. Not sure if that matters.

**Comment by jmcouffin** [comment]
by keynote manager, you mean the one from Revolution design? (and if so, are you using it as well on the same keynote file?)

Could you check if the file is locked (right click, properties)

**Comment by Jdivina24** [comment]
> by keynote manager, you mean the one from Revolution design? (and if so, are you using it as well on the same keynote file?)
> 
> Could you check if the file is locked (right click, properties)

Yes that is the one. We weren't using it on the same keynote file. But then pyRevit was causing that issue and now the PM had to switch back to Keynote Manager because of that.

I checked and it wasn't locked.

**Comment by jmcouffin** [comment]
related #1750 #1725 #1648 #1584

**Comment by jmcouffin** [comment]
@Jdivina24 Hard to help you debug without the exact same setup. 

Maybe that will help: https://pyrevitlabs.notion.site/Keynote-Manager-is-Stuck-24a420d1a57f45fc8bbb2147af6a7d4b

**Comment by jmcouffin** [comment]
maybe checking https://github.com/eirannejad/pyRevit/issues/1235

**Comment by Jdivina24** [comment]
> maybe checking #1235
So I've deleted the lock line within the txt file (# --------------------- @table(locks_table:"Locks Table") @sep("\t") @internal(yes) @tags(yes) @history(no) @encap(no) @headers(no) @key(lock_uuid) @uuid(lock_uuid:"") @text(lock_source:"") @text(lock_requester:"") @uuid(lock_conn_uuid:"") @text(lock_dbname:"") @text(lock_tablename:"") @text(lock_recordkey:"")

But everytime I try and sync it comes back on there.

Everytime I try and sync I get the error Other users have saved changes to the Revit file.
I've synced, they have synced and I still get the error making me unable to sync but now have to create a new local file from the most recent central file. This gets rid of the changes that I have made.

![image](https://github.com/eirannejad/pyRevit/assets/143040714/65a0a598-f6ea-45f3-ac2d-f9443324b652)

**Comment by jmcouffin** [comment]
It seems you are opening a detached Revit model and trying to save to a central one, or at least that is what the screen capture says

**Comment by Jdivina24** [comment]
> @Jdivina24 It seems you are opening a detached Revit model and trying to save to a central one, or at least that is what the screen capture says

Oh no I just didn't bother to rename it.

**Comment by jmcouffin** [comment]
@Jdivina24 you mean you have a team working from a central file named 'detached'? 😱

**Comment by Jdivina24** [comment]
> @Jdivina24 you mean you have a team working from a central file named 'detached'? 😱

No this was just a test file. I detached it so me and 1 other person can test out the issue they were having on the real project.

**Comment by jmcouffin** [comment]
Is keynote manager from rev design installed on both machines?
If so, could you disable it in both and try again the pyrevit one?
