### ISSUE TITLE
Revit 2023 shuts down while loading after installing pyRevit

### ISSUE THREAD

**Issue by Davelv426** [eirannejad/pyRevit#1906]
**Describe the bug**
pyRevit was installed, no installation error message was given.
When I try to launch Revit the initial Revit dialog box shows up and an empty Revit launch dialog bos shows for an instant and Revit shuts down.

When I uninstall pyRevit, I can launch Revit without any problem

I issued the command `pyrevit attach master 277 --installed` at the command line. I did not get any error messages.

**To Reproduce**
1. Install pyRevit
2. Launch Revit

**Expected behavior**
Revit briefly show launch dialog box then shuts down

**Screenshots**
Screen show shows how far Revit goes before shutting down.
 
![image](https://github.com/eirannejad/pyRevit/assets/127432946/56eef3a1-6381-4eb6-a274-25732f98eb7e)

**Desktop (please complete the following information):**
 - OS: Win 10 Pro
 - pyRevit Version : pyRevit_4.8.13.23182_signed
 - pyRevit Environment: 

C:\Windows\system32>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.13.23182+2215" | Path: "C:\Users\dmeza\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2023.1.1" | Engine: IPY277 (277) | Path: "C:\Users\dmeza\AppData\Roaming\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\dmeza\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2023.1.1 | Version: 23.1.10.4 | Build: 20221122_1550(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: BA-BUILDERS\dmeza
Active User: BA-BUILDERS\dmeza
Admin Access: Yes
%APPDATA%: "C:\Users\dmeza\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.13.23182+2215

**Comment by jmcouffin** [comment]
- Can you post the revit Journal?
- Could you also list the revit addins you have installed?
- and last thing, are you using **sentinel one**?

**Comment by Davelv426** [comment]
I installed pyRevit, and tried to launch Revit. Sorry if I added too much I'm not clear on which journal files would help.

The add ins I have are what came with Revit OTB.
Transmit a Model, and Convert RFA

We are using Sentinel One. I did see some thread discussing the issue being with Sentinel One but I never got any message that anything was being blocked.


[journal.0052.txt](https://github.com/eirannejad/pyRevit/files/12540177/journal.0052.txt)
[journal.0052.worker1.log](https://github.com/eirannejad/pyRevit/files/12540178/journal.0052.worker1.log)
[journal.0051.txt](https://github.com/eirannejad/pyRevit/files/12540179/journal.0051.txt)
[journal.0051.worker1.log](https://github.com/eirannejad/pyRevit/files/12540184/journal.0051.worker1.log)

**Comment by jmcouffin** [comment]
Ok, great.
Please explore the sentinel one issue first.
Very high probability that this is the issue

**Comment by Davelv426** [comment]
I now have our IT guys into looking into putting an exemption for pyRevit, I'll let you know how it goes.

**Comment by Davelv426** [comment]
Our IT guys couldn't find anything being blocked. They contacted SentinelOne customer support, they checked out workstation and SentinalOne on server, nothing shows as being blocked. I checked the SentinelOne UI and it doesn't show any activity either.

**Comment by jmcouffin** [comment]
Please check these 
- https://github.com/eirannejad/pyRevit/issues/1866
- https://github.com/eirannejad/pyRevit/issues/1751
I saw your name in this one ^
I really want to rule out S1 first. In most if not all cases of people using S1, pyRevit was blocked and caused similar issues.

**Comment by jmcouffin** [comment]
@Davelv426 any news?

**Comment by Davelv426** [comment]
Nothing new. Our IT dept opened a ticket to look into it.

Sent via the Samsung Galaxy S20 FE 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jmcouffin** [comment]
@Davelv426 should I close the issue?

**Comment by Davelv426** [comment]
Sorry it took so long to get back to you, I was on vacation. I think you can close it. They uninstalled/reinstalled SentialOne, had SO do some changes on their end and it is supposed to work now. Our IT guy called me and said he got it to work using his login, when I tried it, it didn't work. I’m assuming he has some fine tuning to do.

David Meza

Bay Area Builders, Inc.
3360 De La Cruz Blvd
Santa Clara, CA 95054
669-342-9200 cell
www.ba-builders.com<http://www.ba-builders.com/>

**Comment by jmcouffin** [comment]
no pb, I hope this will help others later whenever they are stuck in the sentinelOne/pyrevit interaction pit

**Comment by Paddy32** [comment]
Was this solved ? We have the same problem. PyRevit doesn't work.

**Comment by jmcouffin** [comment]
> Was this solved ? We have the same problem. PyRevit doesn't work.
@Paddy32 
plenty of references in this thread.
Please file in a new issue if the fixing steps stated in the issue template do not work.

**Comment by Davelv426** [comment]
It has for me, since pyRevit can’t get past SentinalOne security I can’t use pyRevit anymore.


David Meza

Bay Area Builders, Inc.
3360 De La Cruz Blvd
Santa Clara, CA 95054
669-342-9200 cell
www.ba-builders.com<https://urldefense.proofpoint.com/v2/url?u=https-3A__urldefense.com_v3_-5F-5Fhttp-3A_www.ba-2Dbuilders.com_-5F-5F-3B-21-21P4LiPV1inDXhLQ-210bbSbI6MkJtadzmifRupsL86EwqbktJkhw5N7IVT5EHXflwekjAwjFs9ADxz7ySU5AIzcysi8Uw18ShZ1z41rZlI6DYbjts-24&d=DwMGaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=PjEQ8m40O4STUa5EIpwO4ACJZO0R6rf7R1NKPKM6suo&m=yXWSsRU-QxdbjAZotLC45gGPicBzkOj1GwgMAxq2l3CwP0EXVYOsE_FdfQyM6D5r&s=AsCeQVMqWWORGEIrLJZFvU3PneafYRHqanEogp-gWec&e=>

**Comment by jmcouffin** [comment]
> It has for me, since pyRevit can’t get past SentinalOne security I can’t use pyRevit anymore.

@Davelv426 
Many pyRevit users and companies managed to adjust sentinel one security policies.

**Comment by jmcouffin** [comment]
see the sentinel one related section of this page 
https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7

**Comment by BIMGSE** [comment]
> > It has for me, since pyRevit can’t get past SentinalOne security I can’t use pyRevit anymore.
> 
> @Davelv426 Many pyRevit users and companies managed to adjust sentinel one security policies.

I can confirme this @Davelv426 we used to have this problem but it's possible to whitelist PyRevit in SentinelOne 👍
