### ISSUE TITLE
Unregister/Reload DockablePane

### ISSUE THREAD

**Issue by FrancoTonutti** [eirannejad/pyRevit#1907]
**Is your feature request related to a problem? Please describe.**
When I design a DockablePane, I need to restart Revit after each change for it to take effect, because if I try to reload pyrevit I get an error message that the DockablePane is already registered.

**Describe the solution you'd like**
I would like to have a method that allows me to unregister the DockablePane and then re-register it, so that any changes made to the .py and .xaml files are updated.

```python
# custom_pane.py
class MyCustomDockablePane(forms.WPFPanel):
    panel_title = "MyTitle"
    panel_id = "3a356476-8bae-4c08-9f91-960f0d3278d0"
    panel_source = op.join(op.dirname(__file__), "DockablePanel.xaml")

    def __init__(self):
        super(CatalogoDockablePanel, self).__init__()
        ...
```

Option 1:
```python
# startup.py
from pyrevit import forms
from custom_pane import MyCustomDockablePane

if not forms.is_registered_dockable_panel(MyCustomDockablePane):
    forms.register_dockable_panel(MyCustomDockablePane, False)
else:
    forms.unregister_dockable_panel(MyCustomDockablePane)
    forms.register_dockable_panel(MyCustomDockablePane, False)
```
Option 2:
```python
# startup.py
from pyrevit import forms
from custom_pane import MyCustomDockablePane

if not forms.is_registered_dockable_panel(MyCustomDockablePane):
    forms.register_dockable_panel(MyCustomDockablePane, False)
else:
    forms.reload_dockable_panel(MyCustomDockablePane)
```

**Describe alternatives you've considered**
I searched within the revit api if there is any way to remove the registered pane, but no success. Maybe it wasn't the right approach to get the changes reflected in revit without having to close and start it again.

**Comment by jmcouffin** [comment]
Last time I checked it was not possible.
But your question is more of a Revit api question, not a pyevit code base issue.
I suggest you ask on the Revit api forum on autodesk's website.
I will close this issue for now.
