### ISSUE TITLE
Error loading pyrevit in revit2022

### ISSUE THREAD

**Issue by Michgadu8** [eirannejad/pyRevit#1911]
Hi I am having a similar problem I problem that this on, I tried several times to unistalled and actually I was sucessful finally with 
Revounistaller as somebody suggested on some other chat then I installed again  using this one from the website 

![image](https://github.com/eirannejad/pyRevit/assets/136072516/4bcd5022-4184-4562-9311-d97b77c81966)

But when I open my Revit 2022 I still getting the same issue so I really don't understand what is wrong 
 
![Capture](https://github.com/eirannejad/pyRevit/assets/136072516/e81eb381-d529-43b4-974c-5bf34fe51199)

Thank you in advance, 
Michelle

**Comment by jmcouffin** [comment]
Can you post the `pyrevit env` command line report to get a better understanding of what is on hand?

**Comment by jmcouffin** [comment]
> Can you post the `pyrevit env` command line report to get a better understanding of what is on hand?

@Michgadu8 what you post is not exactly helping, I need ⬆️ to get a look at what and how pyrevit has been installed.

**Comment by Michgadu8** [comment]
@jmcouffin thank you very much for your quick answer what do you think it would be helpful should I explain you step by step what I did or what do you suggest?

**Comment by Michgadu8** [comment]
Where should I run it?

**Comment by jmcouffin** [comment]
in the windows command line:
https://www.freecodecamp.org/news/command-line-commands-cli-tutorial/
you can run the windows search tool and type cmd, and it will bring you there.

**Comment by jmcouffin** [comment]
can you try to attach your installation of pyrevit with another ipy engine, what I would like you to try is:
1. run the following command line: `pyrevit attach master 2711 --allusers --installed`
2. restart Revit and report here if anything changed.

- What other Revit plugins do you have installed?

**Comment by Michgadu8** [comment]
Ok, I copied like this might be not the right way 
![image](https://github.com/eirannejad/pyRevit/assets/136072516/c3e83ad5-7628-4073-adba-c505c3e6d185)

I have also 
1.- Dynamo 
2.-BIMCollab 
3.-HSBCAD
4.-DiRoots
5.-Dalux
And recently I  have install these 
6.-RevitLook up 
7.-RevitPythonShell 
8.-IronPython 
9.-PyCharm

**Comment by jmcouffin** [comment]
Have you run Revit again?

**Comment by Michgadu8** [comment]
yes no changes

**Comment by jmcouffin** [comment]
try to deactivate these with diroots one addin manager: 
- BIMCollab
- HSBCAD
- Dalux

and see if it runs

**Comment by jmcouffin** [comment]
I am trying to rule out dll conflicts with other revit addins

**Comment by Michgadu8** [comment]
now I open revit as an adm and now pyrevit is there thank you very much
