### ISSUE TITLE
solid pattern not generating

### ISSUE THREAD

**Issue by Evernil** [eirannejad/pyRevit#1912]
I've tried creating pattern using lines close together to form sold square followed by blank square then solid again. Pattern shows the initial lines but not the copied lines forming the solid. also tried with filled region which also didn't work. revit 2022.  what I want vs what I get 
![want vs get](https://github.com/eirannejad/pyRevit/assets/144252575/5bc30d54-cfed-4b5e-900e-7622416ffa1b)

**Comment by jmcouffin** [comment]
@Evernil did you copy the lines with the array tool (are those lines grouped)?
If yes, try ungroup them

**Comment by jmcouffin** [comment]
Could sent a test file?

**Comment by Evernil** [comment]
New to pyrevit how do I send a test file?
    On Wednesday, September 6, 2023 at 04:07:46 PM EDT, Jean-Marc Couffin ***@***.***> wrote:  
 
 


Could sent a test file?

**Comment by jmcouffin** [comment]
It works fine by me.
- array of 10 lines, ungrouped plus an extra line for the spacing.
- did a model and a drawing pattern

Sending a rvt file, you can just add the zip extension to the filename or sent a file sending provider link

![image](https://github.com/eirannejad/pyRevit/assets/7872003/4967f724-4fda-4050-aaa5-aa87b41d38ba)
[hatches.rvt.zip](https://github.com/eirannejad/pyRevit/files/12546215/hatches.rvt.zip)

**Comment by Evernil** [comment]
After doing the same thing over and over I started a new file and it seems to work.  Either old file was corrupt or I was doing model rather than detail and not realizing.  Sorry for the inconvenience.  Thanks for your help.
    On Thursday, September 7, 2023 at 03:56:12 AM EDT, Jean-Marc Couffin ***@***.***> wrote:  
 
 


It works fine by me.
   
   - array of 10 lines, ungrouped plus an extra line for the spacing.
   - did a model and a drawing pattern

Sending a rvt file, you can just add the zip extension to the filename or sent a file sending provider link


hatches.rvt.zip

**Comment by jmcouffin** [comment]
no worry.
That happens
