### ISSUE TITLE
Error loading pyrevit Revit 2022, 2021

### ISSUE THREAD

**Issue by jchandler13** [eirannejad/pyRevit#1914]
Hello,

I'm getting the "PyRevitLoader - Error Loading pyRevit" popup similar to what others describe in similar posts. This is happening in both '21 and '22. 
Win. 10, pyRevit_4.8.13.23182

I've run the: `pyrevit attach master 277 --installed` command to no avail
("Error: Can not find clone "master"
Run with "--debug" option to see debug messages")

pyrevit env results below:

"==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
Unknown | Product: "Autodesk Revit 2022" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2022\pyRevit.addin"
Unknown | Product: "Autodesk Revit 2021" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2021\pyRevit.addin"
Unknown | Product: "2020.2.7" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2020\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\[redacted]\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2022 | Version: 22.1.40.58 | Build: 20230505_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
Autodesk Revit 2021 | Version: 21.1.80.35 | Build: 20230515_0935(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.7 | Version: 20.2.70.6 | Build: 20220112_1230(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
Error: Access is denied
Run with "--debug" option to see debug messages"

**Comment by jmcouffin** [comment]
Can you try uninstalling and reinstalling as a first step?

**Comment by jchandler13** [comment]
Resolved. I'd previously tried this but apparently this time it worked. 

Feeling very silly, thanks for the help!

**Comment by jmcouffin** [comment]
No worry
