### ISSUE TITLE
Error loading pyRevit

### ISSUE THREAD

**Issue by cesarecaoduro** [eirannejad/pyRevit#1915]
**Describe the bug**
Not sure why this issue has been closed elsewhere. There are still issues when PyRevit conflicts with other add-ins. In this case is an internal set of add-ins developed inhouse. It is not clear what creates the conflict from the error.

**To Reproduce**
It happens as soon as you launch Revit

**Expected behavior**
A window error will pop up

**Screenshots**
![image](https://github.com/eirannejad/pyRevit/assets/26373891/29670266-038b-42bf-8c69-dbb1ed5a46f0)

**Desktop (please complete the following information):**
- Windows 10 Pro
- Revit 2023.1
- PyRevit 4.8.13.23182

**Comment by chttIE** [comment]
![image](https://github.com/eirannejad/pyRevit/assets/128715491/604c98c3-9100-45ee-b2b7-5646e332ced9)
Likewise...

**Comment by chttIE** [comment]
If you disable other plugins, pyrevit will start

**Comment by rayala30** [comment]
Is there no way to run pyRevit while having other plug-ins installed? I have had the same issue as the above from Revit 2022 - 2024.

**Comment by jmcouffin** [comment]
> Is there no way to run pyRevit while having other plug-ins installed? I have had the same issue as the above from Revit 2022 - 2024.

I have run pyrevit with dozens of plugins. Only a few plugins have newer or older dll dependencies that makes the debugging of this problem very hard and very specific. 
Changing the loading sequence of Revit addins have helped in the past. You can try append a '0' in front of the pyrevit.addin file.

**Comment by jmcouffin** [comment]
@cesarecaoduro

**Comment by chttIE** [comment]
> > Is there no way to run pyRevit while having other plug-ins installed? I have had the same issue as the above from Revit 2022 - 2024.
> 
> I have run pyrevit with dozens of plugins. Only a few plugins have newer or older dll dependencies that makes the debugging of this problem very hard and very specific. Changing the loading sequence of Revit addins have helped in the past. You can try append a '0' in front of the pyrevit.addin file.

its working, thx))

**Comment by rayala30** [comment]
> > Is there no way to run pyRevit while having other plug-ins installed? I have had the same issue as the above from Revit 2022 - 2024.
> 
> 
> 
> I have run pyrevit with dozens of plugins. Only a few plugins have newer or older dll dependencies that makes the debugging of this problem very hard and very specific. 
> 
> Changing the loading sequence of Revit addins have helped in the past. You can try append a '0' in front of the pyrevit.addin file.

Thank you it works now!
