### ISSUE TITLE
Getting the exceptions importing rpw.ui.forms

### ISSUE THREAD

**Issue by SwapnadipSaha** [eirannejad/pyRevit#1922]
[
![Capture](https://github.com/eirannejad/pyRevit/assets/80402984/8e9fd70b-0310-4b9e-8fe1-3463bf224eae)
](url)

Need a solution regarding importing rpw.ui.forms in revit  2023. Kindly help.

**Comment by jmcouffin** [comment]
@SwapnadipSaha this is an issue for the revit python wrapper or the revit python shell repo, not the pyrevit one
