### ISSUE TITLE
pyrevit for revit 2024 issue

### ISSUE THREAD

**Issue by dani0000000000** [eirannejad/pyRevit#1924]
**Describe the bug**
match override properties tool isn't working for revit 2024. I downloaded the latest version of pyrevit

**To Reproduce**

**Expected behavior**
if i set overrides by element, it should be able to copy them to another element

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - pyRevit Version [v4.8.13.23182](https://github.com/eirannejad/pyRevit/releases/tag/v4.8.13.23182%2B2215)
 - pyRevit Environment: 
 - ` C:\Users\User>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.13.23182+2215" | Path: "C:\Users\User\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2024.0.2" | Engine: IPY277 (277) | Path: "C:\Users\User\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\User\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2024.0.2 | Version: 24.0.20.20 | Build: 20230509_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
==> Running Revit Instances
PID: 11692 | 2024.0.2 | Version: 24.0.20.20 | Build: 20230509_0315(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2024"
==> User Environment
Microsoft Windows 10 [Version 10.0.22621]
Executing User: DANI\User
Active User: DANI\User
Admin Access: No
%APPDATA%: "C:\Users\User\AppData\Roaming"
Latest Installed .Net Framework: 4.8 `

`pyrevit env`

**Additional context**

**Comment by jmcouffin** [comment]
I just tried it, and it seems to work.

https://github.com/eirannejad/pyRevit/assets/7872003/bf1e8835-7ae7-4099-924d-6f385707c2bc

**Comment by dani0000000000** [comment]
yeah, tnx, it was my bad, in previous versions i think i was hitting esc and it was doing it, now i saw the finish button cause you moved your cursor off the screenshot. thank you!
