### ISSUE TITLE
Error message when i launch Revit

### ISSUE THREAD

**Issue by SkyloBoo** [eirannejad/pyRevit#1925]
**Describe the bug**
I tried to install this plugin on my computer, and the installation went well. However, when I launch Revit, I get an error message, and the plugin doesn't load correctly in Revit, so I can't use it.

I tried running the command 
`pyrevit attach master 277 --installed`
 but it didn't resolve my issue.

**Desktop:**
 - OS: Windows 10
 - pyRevit_4.8.13.23182_signed.exe
 
Same error message on Revit 2020 - Revit 2021 and Revit 2023
![2023-09-27_10h55](https://github.com/eirannejad/pyRevit/assets/146177820/08e4abbd-7be2-49e2-bd10-0edd417e9876)

Thank you in advance for your feedback.

**Comment by jmcouffin** [comment]
Copy paste from a previous issue:

> Very likely to be an incompatibility between pyRevit and some other installed addin
> Sometimes pyRevit or another addin will use a similar dll in a different version. Both trying to load these dissimilar versions, it ends up entering the dll hell forbidding one of the addin from loading.
> some of the solutions that have works in the past:
> 
> rename the pyrevi.addin file to 0_pyrevit.addin. It changes the loading sequence of addins.
> disable all addins and enable them progressively. That implies using something like diroots app manager and restarting revit everytime until you figure out the ones not behaving.
> see [https://github.com/eirannejad/pyRevit/issues?q=is%3Aissue+%22incompatible+with+the+array%22+ 1](https://github.com/eirannejad/pyRevit/issues?q=is%3Aissue+%22incompatible+with+the+array%22+)

**Comment by jmcouffin** [comment]
Try this https://www.notion.so/pyrevitlabs/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7?pvs=4#ee9590e3dd8d4920b8b09ecb3c42d993

**Comment by jmcouffin** [comment]
no reply, closing
