### ISSUE TITLE
pyrevitloader script parser ignore broken scripts?

### ISSUE THREAD

**Issue by hdm-dt-fb** [eirannejad/pyRevit#193]
hi @eirannejad, I was wondering if the pyrevitloader script parser could be adjusted so pyrevit will still load if there is a docstring breaking script?

example: 
we recently had a docstring describing a path to a family required by the pyrevit script. 
unfortunately it was done with (windows-path) backslashes.. 
this caused the parser to fail with the typical cryptic error message (as in screenshot below). 
so I thought it might be useful if the parser gracefully skips over a problematic script, not generating any button, but informing about the malformed script with its path in the well formatted nicer to look at pyrevit "boot screen"?

best, f

![image](https://cloud.githubusercontent.com/assets/25063748/25842146/42ed708a-34a3-11e7-9434-fe463a48b008.png)

**Comment by eirannejad** [comment]
@hdm-dt-fb Would you be able to share an example of the docstring code that breaks the loader?

**Comment by hdm-dt-fb** [comment]
sure, it was very similar to this:

```python
"""
Select an IFC link. The script will search through that link and will create 
accordingly sized void instances, based on the bounding box size of existing 
ProvisionForVoid from the IFC link. The Voids are set to the closest 
"Building Story" level. 
It will then cut intersecting walls and floors with the voids.
prerequisite: some_family.rfa
source: U:\some_path\SCRIPTING\RVT\RPS\201X\some_family.rfa
source updated 20170508
"""
```
as soon as I replaced the backslashes with regular slashes, all went back to normal. 

clearly the unescaped backslashes are a mistake on our side, but it would 
be great if pyRevit was still available regardless.  
I found that forgetting about the suffix "_script.py" is nicely caught by and notified 
by pyrevitloader, so if that could happen with the docstring parser pyRevit, that 
would be great.

**Comment by eirannejad** [comment]
Resolved. https://github.com/eirannejad/pyRevit/commit/12d27b907cf83f8efc9f87df5dfc0598fc5a7e97
pyRevit now reports this as a script read error so the user knows that they need to fix the script.

![01](https://cloud.githubusercontent.com/assets/8197916/25864922/0594e7c4-34a6-11e7-8e81-094ac53956db.png)

**Comment by hdm-dt-fb** [comment]
Awesome! Thanks a lot!!
