### ISSUE TITLE
Works on Revit 2020 but not on 2024

### ISSUE THREAD

**Issue by odyax** [eirannejad/pyRevit#1935]
![image](https://github.com/eirannejad/pyRevit/assets/135656147/a0e04618-dcee-45ac-96fc-89535ed4da8d)

This is the error I get when i start Revit 2024- and Pyrevit wouldn't load.

in Revit 2020 I don't experience the issue

**Comment by jmcouffin** [comment]
Please check these to see if it helps
https://github.com/eirannejad/pyRevit/issues?q=is%3Aissue+gettype+is%3Aclosed

**Comment by odyax** [comment]
Hello
Thanks for the reply- I have installed the latest version, not sure what
else I should do?

**Comment by jmcouffin** [comment]
There is a good chance this is related to addins incompatibilities, try this https://www.notion.so/pyrevitlabs/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7?pvs=4#ee9590e3dd8d4920b8b09ecb3c42d993

**Comment by melodiehaze** [comment]
Bonjour, 

je n'arrive pas à faire fonctionner Pyrevit sur revit 2024 , même après désinstallation et réinstallation.

J'ai ce message d'erreur:
![Message erreure suite](https://github.com/eirannejad/pyRevit/assets/154311409/cb4068ff-07e1-4b6f-9e31-d3f4608cc462)
![Message erreure](https://github.com/eirannejad/pyRevit/assets/154311409/f78c53f6-9bab-4344-89b6-61f1cd5dd1a7)
 


Pouvez-vous m'aider s'il vous plait?

**Comment by jmcouffin** [comment]
@melodiehaze stp ne pas s'agréger à un sujet/issue. Et encore moins en français. Le sujet est vieux et non actif, je vais le fermer.

Par ailleurs, note que ton message d'erreur est assez explicite: pyrevit-config.ini est en cours d'utilisation / ouvert par un autre programme: peut-être est il ouvert dans wordpad ou bien tu as lancé deux sessions de Revit en même temps (Revit accès le fichier en question pendant quelques secondes au moment du lancement de Revit puis le libère)

Si cela ne marche toujours pas essaie les étapes citées https://www.notion.so/pyrevitlabs/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7?pvs=4#ee9590e3dd8d4920b8b09ecb3c42d993
