### ISSUE TITLE
To get CPython for a higher verion

### ISSUE THREAD

**Issue by Lukeyone** [eirannejad/pyRevit#1937]
I have a problem with using some features that require me to have CPython 3.10 or 3.11. How can I implement these manually to use with pyRevit if that is even possible?

I would just like to have later versions of Python so that I can implement features which require higher version

If you allow us to implement these manually, that could solve the problem too

**Comment by jmcouffin** [comment]
Not possible at the moment within the pyrevit framework. 
- You could implement the cpython engine if you are literate enough in coding
- or you could run your piece of code using the subprocess module
https://github.com/eirannejad/pyRevit/issues/1731#issuecomment-1427268034
