### ISSUE TITLE
Increase available Revit categories for the "Find and Select Entities without Tags" function

### ISSUE THREAD

**Issue by LostinBIM** [eirannejad/pyRevit#1939]
Hi,

thanks for the work you all are doing with pyRevit.

**Is your feature request related to a problem? Please describe.**
I'm writing from a MEP designer point of view and this functionality could be quite useful for MEP designing too. You could more easily check e.g. if a valve on a vertical pipe is missing a tag. But the available Revit categories for this pyRevit function are quite limited.

**Describe the solution you'd like**
If it would be possible to add the categories for electrical, mechanical and piping to the function it would solve this conundrum. More accurately this would be the wanted list (I'm not including Electrical Equipment and Mechanical Equipment as these are already supported): Air Terminals, Communication Devices, Data Devices, Duct Accessories, Electrical Fixtures, Fire Alarm Devices, Lighting Devices, Lighting Fixtures, Nurse Call Devices, Pipe Accessories, Plumbing Equipment, Plumbing Fixtures, Security Devices, Sprinklers, Telephone Devices.

**Describe alternatives you've considered**
Using the "Tag All" or more accurately "Tag All Not Tagged" native Revit function this can be somewhat checked. But especially on bigger projects you'd need a keen eye or more to see all the added tags compared to the previous situation. And you most likely don't want the same kind of tag for all the different kinds of devices in that category.

**Comment by jmcouffin** [comment]
Fixed by #1944 

![image](https://github.com/eirannejad/pyRevit/assets/7872003/ddb2a3f9-e066-4bb0-93f9-714ef152bd72)

To try it out use WIP installers under the action tab of this repo
CI/CD takes 10/15mins before producing installers
Instructions at the bottom of this page
https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725
