### ISSUE TITLE
2018 Error

### ISSUE THREAD

**Issue by JarodSchultz** [eirannejad/pyRevit#194]
Hi,
I'm getting this message when starting up Revit 2018. Is the latest version ready for 2018?
![image](https://cloud.githubusercontent.com/assets/27864673/25869810/ee8682ea-34be-11e7-8e34-0e3de5b8aee8.png)

Thanks, Jarod

**Comment by eirannejad** [comment]
I have not tested pyRevit for 2018 as I don't have it installed. I'll get this resolved soon.

**Comment by JarodSchultz** [comment]
No Problem Ehsan! I just wanted to make sure I wasn't missing something...

Thanks, Jarod

**Comment by eirannejad** [comment]
Thanks for letting me know. I'll get this resolved as soon as I get 2018 here.

**Comment by Naattik** [comment]
Same problem here. Sorry Ehsan for spamming your PyRevit page with my issue comments. GitHub is easier,,, i had to type the error on DISQUS.. 

I was unable to activate from previous version, so I uninstalled and re-installed the add-in, did not load in 2018 and below error msg popped up.

PyRevitLoader - Error setting up PyRevitLoader

System.NullReferenceException:Object reference not set to an instance of an object.
at
PyRevitLoader.PyRevitLoaderApplication.ExecuteStartupS....
uiControlledApplication)
at
PyRevitLoader.PyRevitLoaderApplication.Autodesk.Revit....
application)

**Comment by eirannejad** [comment]
Resolved. Will be published with the next version

**Comment by eirannejad** [comment]
Will be published in 4.4 soon
