### ISSUE TITLE
enable Text option for Renumber

### ISSUE THREAD

**Issue by RevitIRL** [eirannejad/pyRevit#1941]
**Is your feature request related to a problem? Please describe.**
We model tilt-up and precast wall panels as a continuous wall with Window or Door openings for the joints. We then show boxed Text elements for the panel numbers (see screenshot below).

**Describe the solution you'd like**
I'd like to be able to "Renumber" [in the Modify panel] Text elements (by changing the contents, with an option to set the starting number).

**Describe alternatives you've considered**
We currently manually edit the Text.

**Additional context**
![image](https://github.com/eirannejad/pyRevit/assets/20117305/5361afa6-1fc4-4f0d-abdb-7acf42668191)

**Comment by jmcouffin** [comment]
There are many tools on the market to do just that. The first coming to mind are the one from jotools, renumber and the one from dirRoots.
Both are free.
