### ISSUE TITLE
Sum.pushputton\script.py

### ISSUE THREAD

**Issue by eprunty** [eirannejad/pyRevit#195]
Maybe here isn't the correct place for this but I edited line 80 to include square metres (for metric practices) as per below.

     print("TOTAL AREA OF ALL SELECTED ELEMENTS IS:\n{0} SQFT\n{1} ACRE\n{2} SQM".format(total, total / 43560, total/10.7639104))

**Comment by eirannejad** [comment]
Added your line to the script and pushed. Thanks for the feedback

**Comment by eprunty** [comment]
Thanks! This is by far the best Revit addin I've come across. Keep up the good work! 

PS I have 4 scripts that may be of use to the pyRevit extension (add/remove selected revisions on selected sheets for 'by project' and 'by sheet' revisions). Can I send them to you for review/inclusion?

**Comment by eirannejad** [comment]
Of course brother. It might take me a couple of days to add them but I'm always happy to get new ideas and tools and make pyRevit better for everyone 😁

**Comment by godoe** [comment]
Hi Ehsan. I've just started looking into your tools. Amazing job man! Not sure it's the right place for this since the issue is closed, but about the Sum script, could you include meters for Length parameter since the default Value is in feet?

Thanks!
Davide

**Comment by eirannejad** [comment]
Thanks a bunch pal.
I actually started rewriting this script yesterday after your feedback and hopefully will finish today and publish soon. I’ll keep you posted on this.

Thanks for the kind words :)

**Comment by eirannejad** [comment]
Resolved. Tool is improved now:
- It shows the parameters (instance and type) that are shared between all selected elements
- Calculates totals for all elements and also for each element type

https://github.com/eirannejad/pyRevit/commit/c497d2dc358b5a0f751376ad9def05703a9338c2
