### ISSUE TITLE
OnOpen

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#196]
Is it possible to have a script.py or folder of scripts run on startup?  I'm working on a workflow that can take Revit actions from outside of Revit? 
I am thinking of two options:  Revit Level commands that open/close documents or Document level commands that run once the document opens.

Here's something similar, but since the loader runs, I thought it might be simpler with pyrevit.
http://thebuildingcoder.typepad.com/blog/2013/06/auto-pdf-print-from-revit-2014.html

**Comment by eirannejad** [comment]
See how the `Sync Views` tool works.  See `Advanced Bundles` section on this page: http://eirannejad.github.io/pyRevit/howtoaddscriptsandtabs/

This is how the `Sync Views` tool sets up the document view change callback methods on startup.

Let me know if this method would be helpful.

**Comment by eirannejad** [comment]
@thazell  Is this resolved?

**Comment by thazell** [comment]
Thanks Ehsan, I'll let you know if I have further questions, thanks for closing.
