### ISSUE TITLE
Idea: improved copy update selcted viewports to selected sheet

### ISSUE THREAD

**Issue by ThubanPDX** [eirannejad/pyRevit#198]
Attempting to use this tool, its very finicky about selecting both the view-port and the selected sheet.  Would it be possible to update it with a window where you click on the selected sheets similar to the print tools?

**Comment by eirannejad** [comment]
Yeah I agree. It needs to be updated. Will do soon.

**Comment by eirannejad** [comment]
Resolved for v4.5rc

**Comment by eirannejad** [comment]
v4.5rc is available now:
http://eirannejad.github.io/pyRevit/pyrevit/update/2017/12/02/45rc.html
