### ISSUE TITLE
Imports work in Dynamo but not in PyRevit

### ISSUE THREAD

**Issue by Lupo-J** [eirannejad/pyRevit#1980]
Pyton modules which have been installed using pip and which work in dynaamo are not importing into pyRevit

e.g 
import pandas as pd
import feather
from shapely.geometry import Point, Polygon
from pathlib import Path  

These modules have all been installed and work in dynamo in Revit 2024 but don't import into PyRevit

**To Reproduce**
try importing the modules above

**Expected behavior**
modules available in Dynamo should import into PyRevit

**Screenshots**

CPython Traceback:
ModuleNotFoundError : No module named 'shapely.lib'
 File "\\...................\Zone.pushbutton\script.py", line 13, in <module>
from shapely.geometry import Point, Polygon
 File "C:\Users\...............\AppData\Local\python-3.9.12-embed-amd64\Lib\site-packages\shapely\__init__.py", line 27, in <module>
 from shapely.lib import GEOSException # NOQA

pyRevitLabs.PythonNet
at Python.Runtime.Runtime.CheckExceptionOccurred()
 at Python.Runtime.PyScope.Exec(String code, IntPtr _globals, IntPtr _locals)
 at Python.Runtime.PyScope.Exec(String code, PyDict locals)
 at PyRevitLabs.PyRevit.Runtime.CPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by Lupo-J** [comment]
I have the following paths appended
import sys
sys.path.append(r'C:\Users\USER\AppData\Roaming\pyRevit-Master\bin')
sys.path.append(r'C:\Users\USER\AppData\Local\python-3.9.12-embed-amd64')
sys.path.append(r'C:\Users\USER\AppData\Local\python-3.9.12-embed-amd64\Lib')
sys.path.append(r'C:\Users\USER\AppData\Local\python-3.9.12-embed-amd64\Lib\site-packages')

**Comment by jmcouffin** [comment]
@Lupo-J 
pyRevit does not support properly external library for python V3.9 and above by default, it is just not implemented. That being said, if you look here, in the issues in the repo, you will find explanation and examples of what is working. You should also have a look at the forum https://discourse.pyrevitlabs.io/

In terms of Cpython engines, the ones available are the following: https://github.com/eirannejad/pyRevit/tree/develop/bin/engines
So if you try to import modules from a 3.9.12 version, there is a pretty good chance that you will hit a wall at some point. 

Lots of people ended up bypassing this issue using subprocess module to run different versions of python outside the Revit/pyRevit ecosystem for whatever purpose they needed.

**Comment by Lupo-J** [comment]
The following video from Eiran helps to explain the introduction of CPhython to PyRevit - https://www.youtube.com/watch?v=PbdhVJRfca0
Revit 2024 installs Python 3.9.12 in the following directory
C:\Users\USER\AppData\Local\python-3.9.12-embed-amd64
It would appear from the notes accessed from the ? icon in a python script in Dynamo that it is unlikely that IronPython will be upgraded to Python 3.x and therefore for future development CPython would seem to be the best supported option.

Is it likely that we will see a version of PyRevit implemented in CPython3 in the near future?

**Comment by jmcouffin** [comment]
You can already use the listed CPython 3.85 and 3.78 engines, but their implementation is 'incomplete'
to install numpy and the like you need to do it with the matching python version and pythonpath environment variable
the video goes in quite a lot of details about it. and mentions that, while there are similarities, there are a lot of things that are not accessible in cpython like in pyrevit ironpython engines.

> Revit 2024 installs Python 3.9.12 in the following directory

Are you sure about this ⬆️ ? If the revit installer were to do that, it would do it under an Autodesk folder at the very least.

**Comment by Lupo-J** [comment]
Thanks Jean-Marc,

I am pretty sure that 3.9.12 is part of the Revit install as we have not specifically installed Python. I will check it with a test installation on another machine.

The problem we are facing seems to be that PyRevit is at 3.8.5 max and I expect this is why it does not recognise the modules added to the 3.9.12 installation directory. This is why the script runs in Dynamo and not in PyRevit.

Our intention is to iterate through some large data sets and in Iron Python this is taking many hours to complete. We hope that the direct access to the revit DB from PyRevit will speed the process significantly.

At present, I am looking at a full install of Python 3.8.5 with the associated modules for numpy pandas etc. and hope that this will allow us to process these large datasets.

**Comment by Lupo-J** [comment]
I have managed to get my script to run by installing the full version of python 3.8.5 with all the required modules (e.g. pandas etc.)

pyrevit is creating a much better environment for debugging the script as we can print() variables etc to check what problems may be as it develops.

Thanks for your help Jean-Marc

**Comment by s-github-2** [comment]
@Lupo-J  can you please share how you got 3.8.5 working? I installed python 3.8.5 also but getting errors on any script that uses python3 . for example  
#! python3
import pyrevit
I am on revit 2024 and latest pyrevit version v4.8.14.24016+1909

**Comment by s-github-2** [comment]
found this related https://discourse.pyrevitlabs.io/t/cpython-key-error-importing-pyrevit-module/1521
and it has 
from Autodesk.Revit.DB import * #Import Everything from DB (Good for beginners and development)
doc   = __revit__.ActiveUIDocument.Document
sys.path.append(r'C:\Users\user\AppData\Local\Programs\Python\Python38\Lib\site-packages') # adjust appropriately for your dir

these seem to be the main igredients to get cpython 3.8.5 finally working  and importing numpy
