### ISSUE TITLE
Assembly conflicts with Revit 2023 and pyRevit v4.8.13.23182+2215

### ISSUE THREAD

**Issue by perrylackowski** [eirannejad/pyRevit#1983]
**Describe the bug**
Just switched from Revit 2021 to Revit 2023, and Revit has randomly crashed a few times; I haven't been able to pin down the timing yet, although if it's going to crash, it seems to be within a minute of opening a project. The journal file errors are reminiscent of [this issue.](https://github.com/eirannejad/pyRevit/issues/1301) I have DiRootsOne, Axiom, BIM Interoperability Tools, and the Snoop extension installed.

Journal File Errors:
```' 0:< GUI Resource Usage GDI: Avail 9755, Used 245, User: Used 170 
' 0:< API_SUCCESS { Starting External Application: Office Importer For Revit, Class: OfficeRVT.ExtApp, Vendor : ADSK(Axiom and IntelliProp), Assembly: C:\Program Files\Axiom\Revit2023\OfficeRv\OfficeRv.dll,  Assembly Version: 5.7.1.4 } 
' 0:< API_ERROR { : Assembly version conflict in some references in pyRevitLoader.dll assembly
'Addin's module RevitAPI of version 22.0.0.0 conflicts with same preloaded module of version 23.0.0.0
'Addin's module RevitAPIUI of version 22.0.0.0 conflicts with same preloaded module of version 23.0.0.0 } 
' 0:< ::46:: Delta VM: Avail -13 -> 134178688 MB, Used +0 -> 361 MB; RAM: Avail -6 -> 51008 MB, Used +1 -> 564 MB, Peak +0 -> 564 MB 
' 0:< GUI Resource Usage GDI: Avail 9755, Used 245, User: Used 170 
' 0:< API_ERROR { : Assembly version conflict in some references in pyRevitRunner assembly
'Addin's module RevitAPIUI of version 22.0.0.0 conflicts with same preloaded module of version 23.0.0.0
'Addin's module RevitAPI of version 22.0.0.0 conflicts with same preloaded module of version 23.0.0.0 } 
' 0:< ::46:: Delta VM: Avail -15 -> 134178673 MB, Used +14 -> 375 MB, Peak +17 -> 379 MB; RAM: Avail -22 -> 50986 MB, Used +28 -> 592 MB, Peak +31 -> 595 MB 
' 0:< GUI Resource Usage GDI: Avail 9755, Used 245, User: Used 170 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.WindowsAPICodePack assembly
'Addin's module mscorlib of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Windows.Forms of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Core of version 3.5.0.0 conflicts with same preloaded module of version 4.0.0.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.WindowsAPICodePack.Shell assembly
'Addin's module mscorlib of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Windows.Forms of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module PresentationFramework of version 3.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module WindowsBase of version 3.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module PresentationCore of version 3.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Drawing of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Core of version 3.5.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module WindowsFormsIntegration of version 3.0.0.0 conflicts with same preloaded module of version 4.0.0.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in MadMilkman.Ini assembly
'Addin's module mscorlib of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0 } 
' 0:< ::46:: Delta VM: Avail -15 -> 134178659 MB, Used +4 -> 379 MB, Peak +1 -> 380 MB; RAM: Avail -8 -> 50978 MB, Used +6 -> 598 MB, Peak +3 -> 599 MB 
' 0:< GUI Resource Usage GDI: Avail 9755, Used 245, User: Used 170 
' 0:< API_ERROR { : Assembly version conflict in some references in System.Memory assembly
'Addin's module System.Numerics.Vectors of version 4.1.3.0 conflicts with same preloaded module of version 4.1.4.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in System.Reflection.Metadata assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.5.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.5.0 } 
' 0:< ::46:: Delta VM: Avail -11 -> 134178649 MB, Used +2 -> 382 MB, Peak +1 -> 382 MB; RAM: Avail -9 -> 50970 MB, Used +3 -> 602 MB, Peak +3 -> 602 MB 
' 0:< GUI Resource Usage GDI: Avail 9755, Used 245, User: Used 170 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis.CSharp assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.5.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in pyRevitLabs.Common assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.5.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis.VisualBasic assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.5.0 } 
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version v4.8.13.23182+2215
 - pyRevit Environment: 
 ```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.13.23182+2215" | Path: "C:\Users\perryl\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2024.0.1" | Engine: IPY277 (277) | Path: "C:\Users\perryl\AppData\Roaming\pyRevit-Master"
master | Product: "2023 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Users\perryl\AppData\Roaming\pyRevit-Master"
master | Product: "2022 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Users\perryl\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2021" | Engine: IPY277 (277) | Path: "C:\Users\perryl\AppData\Roaming\pyRevit-Master" 
master | Product: "2020.2.0" | Engine: IPY277 (277) | Path: "C:\Users\perryl\AppData\Roaming\pyRevit-Master"
master | Product: "2019.2.6" | Engine: IPY277 (277) | Path: "C:\Users\perryl\AppData\Roaming\pyRevit-Master"
master | Product: "2018.3.3 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\perryl\AppData\Roaming\pyRevit-Master"
master | Product: "2017.2.5 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\perryl\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
Dunham | Type: Unknown | Repo: "" | Installed: "U:\pyRevit Toolbars\Dunham.extension"
General_Functions | Type: Unknown | Repo: "" | Installed: "U:\pyRevit Toolbars\General_Functions.lib"
==> Default Extension Search Path
C:\Users\perryl\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
U:\pyRevit Toolbars
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2024.0.1 | Version: 24.0.5.432 | Build: 20230411_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
2023 First Customer Ship | Version: 23.0.1.318 | Build: 20220304_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022 First Customer Ship | Version: 22.0.2.392 | Build: 20210224_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
Autodesk Revit 2021 | Version: 21.1.90.15 | Build: 20230907_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.0 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.6 | Version: 19.2.60.3 | Build: 20220224_1700(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
2017.2.5 Security Fix | Version: 17.0.1169.0 | Build: 20190508_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
==> Running Revit Instances
PID: 31036 | 2023 First Customer Ship | Version: 23.0.1.318 | Build: 20220304_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2023"
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: DUNHAM\perryl
Active User: DUNHAM\perryl
Admin Access: No
%APPDATA%: "C:\Users\perryl\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.13.23182+2215
```

**Additional context**

**Comment by jmcouffin** [comment]
Not sure this is the same issue.
The dll assembly error is more if an information than a real warning. Even Autodesk plugins produce these types of warnings.
The very end of the journal file would be much more helpful.

The two most common issue associated with this are: 
- sentinelOne or another AV blocking revit and PyRevit
- the loading sequence of addins (because of an already loaded assembly)

For the latter, you can try deactivate all addins and activate then water Revit one at a time to figure out which one is the issue. Or prefix the PyRevit.addin file so that it is becoming the first loaded in the addins loading sequence.
-

**Comment by perrylackowski** [comment]
I can email you the journal file, but I don't feel comfortable posting it. Also how can I change the loading sequence? By renaming the file? And where is the PyRevit.addin file? I've tried looking some of the common add-ins folders and I'm not seeing it.

**Comment by jmcouffin** [comment]
@perrylackowski 

I took a look at the journal and log file, they did not give up anything as of why or what is causing the issue. 
It is not happening when pyRevit is loading itself. That much I can tell.

Changing the loading sequence is basically changing the name of the addin file so that it is listed first or last, adding a prefix
pyRevit.addin becoming 0_pyRevit.addin makes it load first, but I doubt that will help in your case, as there is no mention of crash related to the loading of pyrevit itself. The addin file for pyrevit is located here **%appdata%\Autodesk\Revit\Addins\2024** for revit 2024.

That being said, I would deactivate all plugin and try to reactivate them one at a time while restarting Revit every time. I know... boring. But that will help you pin down if it really is plugin related. Toe deactivate them, you can use the diRoots AppManager https://diroots.com/apps/diroots-app-manager/, there is a plugin tab that lets you deactivate plugins on the fly while revit is not running

![image](https://github.com/eirannejad/pyRevit/assets/7872003/dbb3b216-bea5-4e78-a65d-506364139eac)

Let me know how it goes, but to me, it seems unrelated to pyRevit, so I will close the issue and you can still comment on it with your feedback of how it went.

**Comment by perrylackowski** [comment]
Thanks for reviewing! I disabled pyRevit yesterday and the crashing
stopped. I'll try sequentially deactivating plugins when I'm back in the
office next Monday.

**Comment by jmcouffin** [comment]
> That being said, I would deactivate all plugin and try to reactivate them one at a time while restarting Revit every time. I know... boring. But that will help you pin down if it really is plugin related. Toe deactivate them, you can use the diRoots AppManager https://diroots.com/apps/diroots-app-manager/, there is a plugin tab that lets you deactivate plugins on the fly while revit is not running

@perrylackowski 
Have you tried ⬆️ ?

**Comment by jmcouffin** [comment]
Thanks to the addins manager from diRoots, can you provide the list of addins installed in the specific version of revit?
Deactivate all but pyrevit and see if it works?

**Comment by jmcouffin** [comment]
this seems to be the part where it crashed:

```
  ' 0:< Hosted window destroyed when docking to other window. 
........
    ' [Jrn.DockablePaneVisibility] Project Browser , System Browser , Properties Palette , MEP Fabrication Parts , PnID Modeler: 1 , 0 , 1 , 0 , 0
    'E 29-Oct-2023 14:46:43.514;   0:< 
    ' [Jrn.CloseRevitMainFrame] 
'C 29-Oct-2023 14:46:43.532;  DBG_WARN: pMainFrame shouldn't be NULL here: line 225 of E:\Ship\2023_px64\Source\API\RevitAPIUI\Objects\APIUIApplicationHandwritten.cpp. 
' 0:< ::61:: Delta VM: Avail -4 -> 134145386 MB, Used 737 MB, Peak +7 -> 750 MB; RAM: Avail -2 -> 50654 MB, Used +6 -> 847 MB, Peak +15 -> 861 MB 
' 0:< GUI Resource Usage GDI: Avail 9766, Used 234, User: Used 147 
'C 29-Oct-2023 14:46:45.331;  DBG_WARN: The retrieval of the main frame failed. 
'
'Expect a soft crash after this warning.
'
'ApplicationException is being thrown on behalf of the function <class System::IntPtr __clrcall Autodesk::Revit::UI::UIApplication::MainWindowHandle::get(void)>. Dump file: C:\Users\perryl\AppData\Local\Autodesk\Revit\Autodesk Revit 2023\Journals\journal.0017.0001.dmp: line 226 of E:\Ship\2023_px64\Source\API\RevitAPIUI\Objects\APIUIApplicationHandwritten.cpp. 
' 1:< ::61:: Delta VM: Avail +9 -> 134145395 MB, Used -8 -> 729 MB; RAM: Avail +290 -> 50944 MB, Used -8 -> 839 MB 
' 1:< GUI Resource Usage GDI: Avail 9776, Used 224, User: Used 134 
'C 29-Oct-2023 14:46:48.462;  Revit worker 1 closed cleanly 
'C 29-Oct-2023 14:46:48.465;  [00012dd0]QueueMinder stopped 
'C 29-Oct-2023 14:46:48.465;   1:< logging finished virtualization services  
'C 29-Oct-2023 14:46:48.465;   1:< logging finished worker services  
'C 29-Oct-2023 14:46:48.466;   1:< logging erased queues  
'  3.095784   1:<<<Terminating RevitWorker Processes 
'C 29-Oct-2023 14:46:48.467;  ->desktop ExitManagedInstance 
'C 29-Oct-2023 14:46:48.476;  <-desktop ExitManagedInstance 
'C 29-Oct-2023 14:46:48.476;  ->desktop ExitNativeInstance 
```

**Comment by perrylackowski** [comment]
> > That being said, I would deactivate all plugin and try to reactivate them one at a time while restarting Revit every time. I know... boring. But that will help you pin down if it really is plugin related. Toe deactivate them, you can use the diRoots AppManager https://diroots.com/apps/diroots-app-manager/, there is a plugin tab that lets you deactivate plugins on the fly while revit is not running
> 
> @perrylackowski Have you tried ⬆️ ?

IT just installed the add-in today, so I'll test this out. Based on the code segment you posted, it seems like it's tied to [this technical](https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Revit-crashes-with-a-Customer-Error-Report-after-closing-the-program.html) article. I'll see if I can get pyRevit working if I disable all my other add-ins.

**Comment by jmcouffin** [comment]
> it seems like it's tied to [this technical](https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Revit-crashes-with-a-Customer-Error-Report-after-closing-the-program.html) article.
The article hits the solution button with pretty large resolutions: update, update bios, disable all addins, 
What is missing is: buy new computer ;p

**Comment by perrylackowski** [comment]
> Thanks to the addins manager from diRoots, can you provide the list of addins installed in the specific version of revit? Deactivate all but pyrevit and see if it works?

I'm working to get administrator access since I can't disable the add-ins through the manager otherwise. Strangely, I'm not seeing pyRevit listed in the DiRoots App Manager.

I should mention, after reenabling pyRevit, the crashes are now occurring in Revit 2021 _and_ 2023. They persist even after I disable pyRevit again, and only stops crashing after restarting the PC.
And just for the record, these are the commands I have been using to enable/disable pyRevit:
Disable: pyrevit detach --all
Enable: pyrevit attach master 277 --installed

Here's a list of the add-ins I'm running in 2021:
![image](https://github.com/eirannejad/pyRevit/assets/102748073/956e03f4-f150-46aa-90f2-1879c81bb593)

and 2023:
![image](https://github.com/eirannejad/pyRevit/assets/102748073/9c5da751-87f7-45ad-8553-7d11519fadea)

**Comment by perrylackowski** [comment]
I disabled many of the add-ins I wasn't actively using and then restarted my machine. I have been working for a few hours now with no crashes, so it must be an app conflict with one of the following disabled add-ins. I'll try to remember to post here if I'm ever able to whittle it down to a specific app. And in other good news, pyRevit now shows up in the App Manager list after restarting. Thanks for the help @jmcouffin!
![image](https://github.com/eirannejad/pyRevit/assets/102748073/bed83bd8-e930-4be0-bb0b-79b6511d35b6)

**Comment by perrylackowski** [comment]
Closing some of the other add-ins seemed to help me. However, another team member experienced a pyRevit loading error when they first launched our new 2023 project, and I'm curious if you can tell if it's related:
![image](https://github.com/eirannejad/pyRevit/assets/102748073/24c83504-61b7-4612-8c3c-22b317718df3)

**Comment by jmcouffin** [comment]
The error message seems incomplete. Missing the beginning and the end.

**Comment by perrylackowski** [comment]
I thought that might be the case. I requested he try to screenshot the
entire thing if it reappears.

**Comment by xyz-Daniel-zyx** [comment]
I am experiencing some issues with PyRevit as well could it be that the wrong API version is referenced here?

part of journal file
'Addin's module RevitAPIUI of version 16.0.0.0 conflicts with same preloaded module of version 23.0.0.0 } 
' 0:< API_SUCCESS { Registering Idling event by application DAQS Assist (0a22ed25-690d-43c1-b048-30d315b74cc8). } 
' 0:< API_SUCCESS { Added pushbutton Id: 6422, name: DaqsAssist.Commands.ShowMainViewCommand, text:  Assist , class: DaqsAssist.Commands.ShowMainViewCommand, assembly: C:\ProgramData\Autodesk\Revit\Addins\2023\Daqs.Assist\Daqs.Assist.dll, parentId: CustomCtrl_%Add-Ins%DAQS } 
' 0:< API_SUCCESS { Registering Idling event by application DAQS Assist (0a22ed25-690d-43c1-b048-30d315b74cc8). } 
' 0:< API_SUCCESS { Registering ViewActivating event by application DAQS Assist (0a22ed25-690d-43c1-b048-30d315b74cc8). } 
' 0:< API_SUCCESS { Registering ViewActivated event by application DAQS Assist (0a22ed25-690d-43c1-b048-30d315b74cc8). } 
' 0:< API_SUCCESS { Registering DocumentSynchronizingWithCentral event by application DAQS Assist (0a22ed25-690d-43c1-b048-30d315b74cc8). } 
' 0:< API_SUCCESS { Registering DocumentSynchronizedWithCentral event by application DAQS Assist (0a22ed25-690d-43c1-b048-30d315b74cc8). } 
' 0:< API_SUCCESS { Starting External Application: DAQS Assist, Class: DaqsAssist.Application, Vendor : DAQS BV(DAQS Assist, https://daqs.io), Assembly: Daqs.Assist\Daqs.Assist.dll,  Assembly Version: 2023.0.0.0 } 
' 0:< API_SUCCESS { Replacing command id 'ID_VIEWS_FOR_A360' Executed implementation with implementation from application 'Views For A360' dll 'C:\ProgramData\Autodesk\Revit\Addins\2023\.\ExportViewSelectorAddin\ExportViewSelectorAddin.dll'. } 
' 0:< API_SUCCESS { API registering command Publish Settings Executed event by application Views For A360 (78bd1446-1817-4842-8075-591b0424acaa). } 
' 0:< API_SUCCESS { Replacing command id 'ID_VIEWS_FOR_A360' CanExecute implementation with implementation from application 'Views For A360' dll 'C:\ProgramData\Autodesk\Revit\Addins\2023\.\ExportViewSelectorAddin\ExportViewSelectorAddin.dll'. } 
' 0:< API_SUCCESS { API registering command Publish Settings CanExecute event by application Views For A360 (78bd1446-1817-4842-8075-591b0424acaa). } 
' 0:< API_SUCCESS { Starting External Application: Views For A360, Class: Autodesk.Revit.Addin.ExportViewSelector.ExportViewSelectorApp, Vendor : ADSK(Autodesk, www.autodesk.com), Assembly: .\ExportViewSelectorAddin\ExportViewSelectorAddin.dll,  Assembly Version: 23.1.30.97 } 
' 0:< API_ERROR { : Assembly version conflict in some references in pyRevitLoader.dll assembly
'Addin's module RevitAPI of version 22.0.0.0 conflicts with same preloaded module of version 23.0.0.0
'Addin's module RevitAPIUI of version 22.0.0.0 conflicts with same preloaded module of version 23.0.0.0 } 
' 0:< ::47:: Delta VM: Avail -13 -> 134178616 MB, Used +1 -> 378 MB, Peak +1 -> 379 MB; RAM: Avail -5 -> 19162 MB, Used +2 -> 582 MB, Peak +3 -> 584 MB 
' 0:< GUI Resource Usage GDI: Avail 9825, Used 175, User: Used 175 
' 0:< API_ERROR { : Assembly version conflict in some references in pyRevitRunner assembly
'Addin's module RevitAPIUI of version 22.0.0.0 conflicts with same preloaded module of version 23.0.0.0
'Addin's module RevitAPI of version 22.0.0.0 conflicts with same preloaded module of version 23.0.0.0 }
