### ISSUE TITLE
Wipe Data Scheme Not Working

### ISSUE THREAD

**Issue by jabarig** [eirannejad/pyRevit#1986]
**Describe the bug**
The Wipe Data Schema tool isn't working as expected on 2023. Instead of the schemas being wiped the console window pops up saying `'type' object has no attribute 'EraseSchemaAndAllEntities'`

**To Reproduce**
1. Go to Wipe
2. Click on Wipe Data Scheme
3. Select All or check a single schema
4. See error 'type' object has no attribute 'EraseSchemaAndAllEntities'

**Expected behavior**
All selected data schema are deleted

**Screenshots**
![image](https://github.com/eirannejad/pyRevit/assets/5063609/15e831b9-7542-4ff8-9e85-a337643ba2ec)

**Desktop (please complete the following information):**
 - OS: Windows 10, Revit 2023 version 23.1.30.97
 - pyRevit Version 4.8.12
 - pyRevit Environment:
```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\mysuserprofile\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\mysuserprofile\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\mysuserprofile\AppData\Roaming\pyRevit-Master" | AllUsers
master | Product: "Autodesk Revit 2021" | Engine: IPY277 (277) | Path: "C:\Users\mysuserprofile\AppData\Roaming\pyRevit-Master" | AllUsers
master | Product: "Autodesk Revit 2020" | Engine: IPY277 (277) | Path: "C:\Users\mysuserprofile\AppData\Roaming\pyRevit-Master" | AllUsers
master | Product: "2019.2.6" | Engine: IPY277 (277) | Path: "C:\Users\jmysuserprofile\AppData\Roaming\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\mysuserprofile\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.40.58 | Build: 20230505_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
Autodesk Revit 2021 | Version: 21.1.70.21 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
Autodesk Revit 2020 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.6 | Version: 19.2.60.3 | Build: 20220224_1700(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

**Additional context**
The Wipe Data Scheme command works as expected on Revit 2022, 2021 and 2020

**Comment by jmcouffin** [comment]
It has been fixed since version 4.12 of pyrevit.
Please use the latest wip installer under the actions tab of the GitHub repository

**Comment by tjxme** [comment]
@jmcouffin Hi, i only see 4.8 on the release.  can you redirect me to where the 4.12 is? i think revit 2024 changed their api so wipe data schema doesnot work anymore

**Comment by jmcouffin** [comment]
once logged in github at the end of this page, you will find the latest installers https://github.com/eirannejad/pyRevit/actions/runs/7506510785
