### ISSUE TITLE
Error loading pyRevit...

### ISSUE THREAD

**Issue by Miriapod** [eirannejad/pyRevit#1987]
I am having lots of trouble loading pyrevit on 2 pcs, i get this when oppening revit, i cant code or understand about it at all, i need a resolve so i can load it, it stays on my mind this issue, i would like to be able to run pyRevit... What can i do?

![Captură de ecran 2023-11-04 023507](https://github.com/eirannejad/pyRevit/assets/78919258/7a16851f-5e90-41b5-9217-203fb263e53e)

**Comment by Miriapod** [comment]
i installed the latest release a few times with no succes also

**Comment by jmcouffin** [comment]
Do you have sentinelOne installed?
Or another antivirus or firewall that could block revit/pyrevit

**Comment by Miriapod** [comment]
I do not have any of those. On another pc i get the same error but diffrent report, i will attach it here, could anyone figure this thing? am i the only one with this errors?
![Screenshot 2023-11-06 133204](https://github.com/eirannejad/pyRevit/assets/78919258/c76fdd82-debd-4a6f-abc6-199bf0a1db3a)

**Comment by Miriapod** [comment]
after reinstalling pyRevit on this new machine , i get again an error, diffrent this time 
![Screenshot 2023-11-06 134354](https://github.com/eirannejad/pyRevit/assets/78919258/3cd6a17a-16d2-426d-ae37-6309e4d33546)

**Comment by jmcouffin** [comment]
You are not: https://github.com/eirannejad/pyRevit/issues/1948

Would you please do me a favour and follow these instructions at least, that will help:
https://github.com/eirannejad/pyRevit/issues/new?assignees=&labels=&projects=&template=BUG_REPORT.md

And Try disabling all your revit addin to see if any of the addins installed are an issue

**Comment by jmcouffin** [comment]
I will delete this one then. Thanks @Miriapod
