### ISSUE TITLE
PyRevitLoader- Error Loading PyRevit in Revit 2022, 2023 and 2024

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#1991]
**Describe the bug**
Replace these lines with your description. Be as specific as possible and list steps to reproduce the issue. If you have any suggestions for the solution please list that as well.

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

**To Reproduce**
1. Startup to Revit
2. 'PyRevitLoader- Error Loading PyRevit' messages pops up
3. Revit opens without PyRevit

**Expected behavior**
Revit opens with PyRevit in Revit 2022, 2023 and 2024

note: PyRevit opens OK in Revit 2021

**Screenshots**
![image](https://github.com/eirannejad/pyRevit/assets/8776947/f9272509-7f27-4a37-9965-c3a460512895)
![image](https://github.com/eirannejad/pyRevit/assets/8776947/0d6695ad-9862-464e-b991-a49e48d24ff2)

**Desktop (please complete the following information):**
 - OS: [Windows 10 [Version 10.0.19045]
 - pyRevit Version [pyRevit_4.8.14.23310]
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

Microsoft Windows [Version 10.0.19045.3570]
(c) Microsoft Corporation. All rights reserved.

C:\Users\rob.cross>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.14.23310+1210-wip" | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2024" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2021" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2020" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2019" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
master | Product: "2018.3.3 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
master | Product: "2017.2.5 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
master | Product: "2016.1.9 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
master | Product: "2015 Release 2 (Subscription only release)" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
master | Product: "2014 Update Release 3" | Engine: IPY277 (277) | Path: "C:\Users\rob.cross\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\rob.cross\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2024 | Version: 24.1.10.25 | Build: 20230830_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
Autodesk Revit 2023 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.50.17 | Build: 20230915_1530(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
Autodesk Revit 2021 | Version: 21.1.90.15 | Build: 20230907_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
Autodesk Revit 2020 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
Autodesk Revit 2019 | Version: 19.2.60.3 | Build: 20220224_1700(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
2017.2.5 Security Fix | Version: 17.0.1169.0 | Build: 20190508_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
2016.1.9 Security Fix | Version: 16.0.1218.0 | Build: 20190508_0715(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016\"
2015 Release 2 (Subscription only release) | Version: 15.0.1103.0 | Build: 20140905_0730(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2015\"
2014 Update Release 3 | Version: 13.11.4 | Build: 20140709_2115(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2014\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: COADY\rcross
Active User: COADY\rcross
Admin Access: No
%APPDATA%: "C:\Users\rob.cross\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.14.23310+1210-wip

**Comment by Robbo1234** [comment]
Got it to work by uninstalling PyRevit & PyRevit CLI and IronPython-2.7.11

And then installing PyRevit & PyRevit CLI version 4.8.13.23182 and the PyRevit & PyRevit CLI version 4.8.14.23313

**Comment by dmb48OEI** [comment]
I'm having this issue and as far as I can tell, I have followed all the steps and it has not resolved the issue.
