### ISSUE TITLE
User editing keynotes can only edit one keynote key at a time before getting error

### ISSUE THREAD

**Issue by tc599** [eirannejad/pyRevit#1993]
Issue comes up when a user was editing keynote keys and is only able to edit one at a time before getting a Requested Lock error and his name appears next to the unedited keynote indicating he is editing it. He has to close the keynote manager for that to go away and so he can edit another keynote key. We tried in two different versions of pyRevit and get the same result.

**To Reproduce**
Open Keynote Manager
Select keynote and select edit keynote key button
Edit one keynote key
Attempt to repeat for another keynote and gets error, closes the error pop up and his name appears beside the unedited keynote indicating he is editing it.
Has to close the keynote manager to edit an additional keynote key

**Expected behavior**
Expectation would be to be able to edit more than one keynote key within the same session of having the keynote manager open

**Screenshots**
![image](https://github.com/eirannejad/pyRevit/assets/105459071/440eeb41-c3a3-4605-9b3a-190e20516126)
![image](https://github.com/eirannejad/pyRevit/assets/105459071/b4221419-80b0-45eb-8da6-103fb5d0c20c)
![image](https://github.com/eirannejad/pyRevit/assets/105459071/fbe07e9e-8ce1-4a28-8a2f-f27a4f3ad566)
![image](https://github.com/eirannejad/pyRevit/assets/105459071/782f9bf5-51e1-4f61-96a0-cb4949a35142)

**Desktop (please complete the following information):**
 - OS: Windows 10, 19045.3570; 64-bit
 - pyRevit Version both -  4.8.13 +2215 4.8.12 +0031

**Comment by jmcouffin** [comment]
Where is the keynote file located?
On ACC and accessed through the 'ACCdocs' path?

**Comment by tc599** [comment]
No, long story, our models are on Revit server in our own data center. Keynote file is saved in a network drive location and no locking issues for any other edits we make to the keynotes using the app. Users have full read/write permissions to that folder location. We can edit the keynote text without this locking pop up/issue, but as soon as we edit the keynote key it comes up.

**Comment by jmcouffin** [comment]
> No, long story, our models are on Revit server in our own data center. Keynote file is saved in a network drive location and no locking issues for any other edits we make to the keynotes using the app. Users have full read/write permissions to that folder location. We can edit the keynote text without this locking pop up/issue, but as soon as we edit the keynote key it comes up.

One specific user, right?
Not everyone.
If so, it is not a pyRevit issue, I guess. File locking is not orchestrated by pyRevit. More probably so by windows?

**Comment by tc599** [comment]
It is more than just one user. I also had the same issue as well. I would suspect windows also but only if there was other locking issues for editing other items.... If each user has full permissions to edit/write to the file then there should be no locking issues for one very specific command. As I mentioned, you can edit the text of the keynote with no issues, the keynote key is where this error pops up and we can only edit one key at a time, close out of the app and do another etc.

**Comment by jmcouffin** [comment]
Have a look at this https://pyrevitlabs.notion.site/Keynote-Manager-is-Stuck-24a420d1a57f45fc8bbb2147af6a7d4b

**Comment by tc599** [comment]
The lock and code in the .txt should just be temporary and should clear once a person finishes editing or adding the keynote in the app. That lock in the .txt is created so in the app you see that the person is actively editing and you don't overwrite each other. I wouldn't want to have to go into the .txt file each time a person is editing a keynote key and wipe this line of code.

The problem is that this temporary lock for this specific edit of the keynote key doesn't clear and the edit you attempt doesn't actually get written. So you are forced to close the keynote manager or click on Update Model, which closes the keynote manager. Then only when you reopen can you successfully edit the keynote key. Then close the app, reopen edit another keynote key. You can't edit more than one before you get the error. This is the only editing function I have found so far that requires this and the only one that we get a pop up warning for.

**Comment by jmcouffin** [comment]
I have fixed a few things and looked at the code of the tool in the past but I haven't touched it for quite a bit, so bare with me.
I also have no way to test it properly with someone on the other end of a revit file.

> The problem is that this temporary lock for this specific edit of the keynote key doesn't clear and the edit you attempt doesn't actually get written. So you are forced to close the keynote manager or click on Update Model, which closes the keynote manager. Then only when you reopen can you successfully edit the keynote key. Then close the app, reopen edit another keynote key. You can't edit more than one before you get the error. This is the only editing function I have found so far that requires this and the only one that we get a pop up warning for.

I got that



> The lock and code in the .txt should just be temporary and should clear once a person finishes editing or adding the keynote in the app. That lock in the .txt is created so in the app you see that the person is actively editing and you don't overwrite each other. I wouldn't want to have to go into the .txt file each time a person is editing a keynote key and wipe this line of code.

What I suggest before digging into the code too much: 
- rebuild the keynote file
- or clean all the locks when team is off
and test again.
It may be due to one time when Revit crashed in the middle of a keynote editing and did not properly clean itself.

**Comment by tc599** [comment]
Yes, good point re a Revit crash creating an issue. Will test that and update here if it works! Thank you kindly

**Comment by tc599** [comment]
Seems to do the trick - remove the lines of code that show up under the locks table code at the top of the .txt
