### ISSUE TITLE
pyRevit can not load pyc on Revit 2020

### ISSUE THREAD

**Issue by Trinity248** [eirannejad/pyRevit#2005]
First of all, many thanks for the team because of creating pyRevit

I try to apply pyc file to all the script.py & library for my team. The pyc folder will be stored on the server and can be call by other people to run selected tools. This worked well for Revit 2019, 2021, 2022, 2023 & 2024 but failed with 2020. All of them have the same pyc library.

This worked perfect on revit 2023
![Screenshot 2023-11-14 135100](https://github.com/eirannejad/pyRevit/assets/134942524/8503963b-d570-4640-b7bd-ee4040c01045)

But failed in 2020
![Screenshot 2023-11-14 135646](https://github.com/eirannejad/pyRevit/assets/134942524/2434fa8c-cec3-427f-96eb-468987b6ff2b)

This said that load the pyc successfully but can not call the module
They use the same pyc file

How can we make this work on Revit 2020
Could you please review this and give me some advice?

**Desktop (please complete the following information):**
 - OS: Window 11
 - pyRevit Version 4.8.13
 - pyRevit Environment: 
    Options:
        -h --help                Show this help
        -V --version             Show version
        --usage                  Print all usage patterns
        --verbose                Print info messages
        --debug                  Print docopt options and logger debug messages
        --log=<log_file>         Output log messages to external log file

    Management Commands:
        env                      Print environment information
        update                   Update remote resources used by this utility
        clones                   Manage pyRevit clones
        extensions               Manage pyRevit extensions
        attached                 Manage pyRevit attachments to installed Revit
        releases                 Info about pyRevit releases
        revits                   Manage installed Revits
        caches                   Manage pyRevit caches
        configs                  Manage pyRevit configurations

    Commands:
        clone                    Create a clone of pyRevit on this machine
        extend                   Create a clone of a third-party pyRevit extension on this machine
        attach                   Attach pyRevit clone to installed Revit
        switch                   Switch active pyRevit clone
        detach                   Detach pyRevit clone from installed Revit
        config                   Configure pyRevit for current user
        run                      Run python script in Revit
        doctor                   Fix potential or real problems

    Help Commands:
        wiki                     Open pyRevit Wiki
        blog                     Open pyRevit blog
        docs                     Open pyRevit docs
        source                   Open pyRevit source repo
        youtube                  Open pyRevit on YouTube
        support                  Open pyRevit support page

Run 'pyrevit COMMAND --help' for more information on a command.
`pyrevit env`

**Additional context**

**Comment by jmcouffin** [comment]
Answered on the forum.
Please avoid double posting
