### ISSUE TITLE
duplicate beam tag finder doesn't work

### ISSUE THREAD

**Issue by Nikos369** [eirannejad/pyRevit#2016]
**🙏 PLease use the search in the issue section before filing a new issue**
![image](https://github.com/eirannejad/pyRevit/assets/152983894/c42a8b80-54ba-4b4d-a8f6-0ca0ea5df1c3)
![chrome_A2macC7Ems](https://github.com/eirannejad/pyRevit/assets/152983894/c7f05839-2ea8-4627-861d-063c3de2fb23)

---

# 🐞 Describe the bug

Replace these lines with your description. Be as specific as possible and list steps to reproduce the issue. If you have any suggestions for the solution please list that as well.

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal / command line. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

👉 `pyrevit attach master 2711 --installed`

If it does not work, try to disable your revit addins, all of them. Then, one at a time, reactivate them and restart Revit to figure out which one is interacting badly with pyRevit and Report.

# ♻️ To Reproduce

# ⏲️ Expected behavior

# 🖼 Screenshots of the issue

# 🖥️ Hardware and Software Setup (please complete the following information):
 - pyRevit Version [e.g. 22]
 - pyRevit Environment: Open a command prompt 🖥 and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

👉 `pyrevit env`

# Additional context

**Comment by Nikos369** [comment]
It's an extension of pyrevit called pystructure that has this duplicate tag finder tool.

**Comment by jmcouffin** [comment]
ok, so this is not a pyrevit issue per say
you need to fill your issue on the owner of the extension repository:

https://github.com/sampy23/pyStruct.extension/issues/new
