### ISSUE TITLE
Case sensitivity in pyRevitTools Teams buttons 

### ISSUE THREAD

**Issue by jbf1212** [eirannejad/pyRevit#2018]
# 🐞 Describe the bug

In pyRevit.tab > Project.panel > ptools.stack > Team.pulldown all of the tools except for the 'Who Did That' tool do a string comparison of the element owner/editor and the username from the HOST_APP. I noticed that sometimes these strings are the same, but have different cases. So we need to make the string comparison ignore case like so: `if wti.Owner.lower() == HOST_APP.username.lower():`

**_I'm pushing a PR to fix the issue, but just figured I'd raise it here for tracking purposes._**

# ♻️ To Reproduce
I think this gets introduced mainly if somebody edits their Autodesk ID. So if I change my ID to JohnSmith-ABC, the username from the application might be johnsmith-ABC, but the Element Owner in Revit might be JohnSmith-ABC.

# ⏲️ Expected behavior
Tools should grab editors/owners as desired for the following tools: 

- Find Sheets With Elements Owned By Me
- Select Last Edited By Me In Current View
- Select Owned By Me In Current View

# 🖥️ Hardware and Software Setup (please complete the following information):
 - All pyRevit versions

**Comment by jmcouffin** [comment]
It makes sense ~john~ Jared.
Thanks.
Merged
