### ISSUE TITLE
LibGit2Sharp IO Exception

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#203]
Started getting this randomly got this in on of my computers. 
I have wiped pyRevit cleaned and uninstalled it twice... Out of ideas on how to fix it... :/
Any suggestions of what else to check?

![image](https://user-images.githubusercontent.com/9513968/27435832-4e8f2d66-572b-11e7-82d9-636373872fde.png)

![image](https://user-images.githubusercontent.com/9513968/27435866-6c9de8a6-572b-11e7-880c-1385f3c33a3e.png)

![image](https://user-images.githubusercontent.com/9513968/27435897-821d6576-572b-11e7-899e-fe72f5d8e7bb.png)

**Comment by eirannejad** [comment]
This is where the DLL is:

![2017-06-22 08_37_24-addin](https://user-images.githubusercontent.com/8197916/27442834-3101b534-5726-11e7-99e6-28a75b283d96.png)

The odd thing is that the `pyrevitlib/pyrevit/coreutils/git.py` module specifically loads this dll by `clr.AddReferenceToFileAndPath`. See if this module collects the correct dll address on that machine:

![2017-06-22 08_38_14-git py c__users_eirannejad_appdata_roaming_pyrevit_pyrevit-v4_pyrevit atom](https://user-images.githubusercontent.com/8197916/27442887-5ac09df4-5726-11e7-9f89-acf797e15c83.png)

**Comment by gtalarico** [comment]
Strange. Thanks for the info, I will check that location as well.

**Comment by gtalarico** [comment]
Weird:
![image](https://user-images.githubusercontent.com/9513968/27461954-40996ac2-578b-11e7-971f-7cd98d7fe110.png)

**Comment by gtalarico** [comment]
Did a full uninstall through the control panel, deleter %appdata% folder, and did a fresh re-install:
all good now.
Not sure how it happened, but I am happy it's back up!
