### ISSUE TITLE
pyRevitUpdater throwing error when editing element

### ISSUE THREAD

**Issue by TPJW** [eirannejad/pyRevit#2032]
**🙏 Please use the search in the issue section before filing a new issue**

---

# 🐞 Describe the bug

I get the below error (see screenshot) when I go to edit any element in my document(s), such as dragging a view, placing a grid, etc.. This has started occurring today & have had it occur in two separate (workshared) models in R21 & R23 (central model located on Revit server and ACC, respectively). Issue persisted after disabling all of my own add-ins/pyRevit extensions. 

# ♻️ To Reproduce
1. Open model
2. Edit any element

# ⏲️ Expected behavior
Element is able to be edited without error

# 🖼 Screenshots of the issue
![image](https://github.com/eirannejad/pyRevit/assets/148268400/dfcd9430-f8c0-49d1-8616-0aee59925166)
Select journal lines from the error:
![image](https://github.com/eirannejad/pyRevit/assets/148268400/30cac207-15f3-4c3c-9216-49dbe9678236)
![image](https://github.com/eirannejad/pyRevit/assets/148268400/96919477-9c46-400e-be10-c34fd93c9696)
**Note:** First six seconds were cut off in order to make it a gif, but this is an example of the error popping up where I went to move a  grid line once I open a document.
![ezgif-3-a40297f08f](https://github.com/eirannejad/pyRevit/assets/148268400/45aeba98-4949-48e3-a9ef-3f2b82b83051)

# 🖥️ Hardware and Software Setup (please complete the following information):
 - OS: Windows 11 Enterprise, Version 21H2, build 22000.2652
 - pyRevit Version: 4.8.13.23182+2215
 - pyRevit Environment: 

```
==> Registered Clones (full git repos)
master | Branch: "master" | Version: "4.8.13.23182+2215:6aa2c49" | Path: "C:\Users\[REDACTED]\AppData\Roaming\pyRevit\pyRevit\master"
==> Registered Clones (deployed from archive/image)
main | Deploy: "base" | Branch: "master" | Version: "4.8.13.23182+2215" | Path: "C:\pyRevit\main"
==> Attachments
main | Product: "Autodesk Revit 2023" | Engine: IPY2710 (2710) | Path: "C:\pyRevit\main"
main | Product: "Autodesk Revit 2022" | Engine: IPY2710 (2710) | Path: "C:\pyRevit\main"
main | Product: "2021.1.7" | Engine: IPY2710 (2710) | Path: "C:\pyRevit\main"
main | Product: "2020.2.0" | Engine: IPY2710 (2710) | Path: "C:\pyRevit\main"
==> Installed Extensions
[REDACTED]| Type: Unknown | Repo: "" | Installed: "H:\Revit\Dynamo\[REDACTED\[REDACTED\[REDACTED.extension"
[REDACTED]| Type: UIExtension | Repo: "https://github.com/TPJW/[REDACTED].git" | Installed: "C:\pyRevit\Extensions\[REDACTED].extension"
[REDACTED]| Type: UIExtension | Repo: "https://github.com/TPJW/[REDACTED]" | Installed: "C:\pyRevit\Extensions\[REDACTED].extension"
[REDACTED]| Type: UIExtension | Repo: "https://github.com/TPJW/[REDACTED].git" | Installed: "C:\pyRevit\Extensions\[REDACTED].extension"
==> Default Extension Search Path
C:\Users\[REDACTED]\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\pyRevit\Extensions
H:\Revit\Dynamo\[REDACTED]\[REDACTED]
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
C:\pyRevit\Extensions\[REDACTED].json
==> Installed Revits
Autodesk Revit 2023 | Version: 23.1.20.70 | Build: 20230510_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.40.58 | Build: 20230505_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"

2021.1.7 | Version: 21.1.70.21 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.0 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
```

# Additional context
My only guess as to what the issue may be is that the updater is trying to update the extensions/add-ins that I've created, which are all in private GitHub repositories, and is encountering the issue due to missing credentials. I don't know why the updater would be trying to run once a model is opened though.

**Comment by TPJW** [comment]
Got it! Seems that the issue was because had application telemetry enabled in the settings (without an destination server entered) as I was messing around/getting familiar with it last week. Turning application telemetry off & saving + reloading did the trick.

**Comment by jmcouffin** [comment]
Hit that exact same wall today 🤣
