### ISSUE TITLE
Pyrevit Not Loading after install in Revit 2024

### ISSUE THREAD

**Issue by jnedunuri** [eirannejad/pyRevit#2034]
Hi, I have tried several times to install the latest version of Pyrevit for Revit 2024. But it would load or show up in the interface. Please let me know. Thanks

**Comment by jmcouffin** [comment]
@jnedunuri please have a look and try the solutions here https://www.notion.so/pyrevitlabs/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7

**Comment by jmcouffin** [comment]
> Hi, I have tried several times to install the latest version of Pyrevit for Revit 2024. But it would load or show up in the interface. Please let me know. Thanks

Hard to propose you a real answer if you do not provide us with enough details like the ones asked in the issue template
https://github.com/eirannejad/pyRevit/issues/new?assignees=&labels=&projects=&template=BUG_REPORT.md

**Comment by jmcouffin** [comment]
any news?

**Comment by jmcouffin** [comment]
Can you show the result of the 'pyrevit env' command?

**Comment by jnedunuri** [comment]
***@***.***

This is what I get when I open my Revit

Jesse Nedunuri

REES
Architecture Planning Interior Design
1025 N. Stemmons Freeway, Suite 737 | Dallas, TX 75207
o 214 580 7182 |  rees.com<http://www.rees.com>

Message contents are confidential, proprietary property of REES and protected by copyright law. This message is intended solely for the addressee(s) identified above and REES makes no representation that this message is secure, error free or free from viruses.

**Comment by sweco-begertjanvdb** [comment]
Probably better to reply on github instead of through mail, I suspect you added an image?

**Comment by jnedunuri** [comment]
> Can you show the result of the 'pyrevit env' command?

I tried running but it closed immediately. Didn't get a chance to take a screenshot.

**Comment by jnedunuri** [comment]
> Ok , and can you also share the outputs of running the following commandsin command prompt? I want to know a bit more about the environment you're working with. `pyrevit env`

It won't run.

**Comment by jmcouffin** [comment]
Read this: https://github.com/eirannejad/pyRevit/issues/2035

the reply is almost always the same:
- Uninstall
- Remove %appdata%/pyrevit and %appdata%/pyrevit-master folder if any
- Move Revit addins to temp location
- install latest pyrevit
- start Revit once - close it
- bring revit addins to their original location

**Comment by jnedunuri** [comment]
Do I need to temporarily move all the “revit addins” folders in all my versions. Cause I have 2020, 2022 and 2024 version installed.


Jesse Nedunuri

REES
Architecture Planning Interior Design
1025 N. Stemmons Freeway, Suite 737 | Dallas, TX 75207
o 214 580 7182 |  rees.com<http://www.rees.com>

Message contents are confidential, proprietary property of REES and protected by copyright law. This message is intended solely for the addressee(s) identified above and REES makes no representation that this message is secure, error free or free from viruses.

**Comment by jmcouffin** [comment]
@jnedunuri if you want to be 100% sure to get it fixed on the first try: ultimately yes.

**Comment by jnedunuri** [comment]
I'll give it a shot. Thanks

**Comment by jnedunuri** [comment]
Works like a charm. Thank you.
