### ISSUE TITLE
Revit 2024.2.0.63: PyRevitLoader - Error Loading pyRevit

### ISSUE THREAD

**Issue by ClausPersson** [eirannejad/pyRevit#2035]
# 🐞 Describe the bug

pyRevit fails to load every time I start Revit. 
Tried to reinstall both py and Revit. Manually cleaning Windows-registry.
See attached image for error description.
Tried [https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7], no succes.

# ♻️ To Reproduce
1. Start Revit

# 🖥️ Hardware and Software Setup (please complete the following information):
pyRevit_4.8.13.23182_signed – also tried previous version
Same as my colleagues, where it works:
Windows 11 Business 22H2, 22621.2428
Revit 2024.2.0.63
AMD Ryzen 7 5800H with Radeon Graphics, 3.20 GHz
![2024-01-09 11_55_42-PyRevitLoader - Error Loading pyRevit](https://github.com/eirannejad/pyRevit/assets/156079322/85a5fe06-5602-4292-8714-f7b80501b215)

**Comment by marin-sandu** [comment]
I am getting the exact same error for more than a month now, in Revit versions 2024 and 2022. Reinstalled multiple times but still doesn't work.
I'm using the last released version of pyRevit.
I tried reinstalling the previous version so that it would work at least for Revit 2022 but I still received similar error messages.
I tried the link @jmcouffin provided but it didn't solve the issue.

**Comment by marin-sandu** [comment]
By the way, I also tried installing as admin and as regular user. The error log was a little different but same type of errors.

**Comment by sweco-begertjanvdb** [comment]
Can you  provide the output of `pyrevit env` just to make sure we're not missing anything?

**Comment by ClausPersson** [comment]
Sure, here it is:
C:\Users\cpe>pyrevit  env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.13.23182+2215" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2024" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2023.1.1" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2022 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\cpe\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2024 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
2023.1.1 | Version: 23.1.10.4 | Build: 20221122_1550(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022 First Customer Ship | Version: 22.0.2.392 | Build: 20210224_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
==> Running Revit Instances
Error: Objektreferencen er ikke indstillet til en forekomst af et objekt.
Run with "--debug" option to see debug messages

Error translated from Danish: Objectreference not set for an instance of an object.

Hope it helps :-)

Claus

**Comment by marin-sandu** [comment]
similar for me (hope I'm not spamming):
C:\Users\sandu.marin>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.13.23182+2215" | Path: "C:\Users\sandu.marin\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2024" | Engine: IPY277 (277) | Path: "C:\Users\sandu.marin\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\sandu.marin\AppData\Roaming\pyRevit-Master"
master | Product: "2020.2.0" | Engine: IPY277 (277) | Path: "C:\Users\sandu.marin\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\sandu.marin\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2024 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
Autodesk Revit 2022 | Version: 22.1.40.58 | Build: 20230505_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2020.2.0 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages

**Comment by jmcouffin** [comment]
please, uninstall and try installing latest release from yesterday.

**Comment by marin-sandu** [comment]
just refollowed the steps provided by @jmcouffin and installed the newest pyrevit (published yesterday) and it seems to work. Thanks!
P.S. I think the problem was one of my other addins after all, I didn't move them previously and before the problems with pyRevit started I did install a bunch of them.

**Comment by jmcouffin** [comment]
@ClausPersson nothing on your side?

**Comment by ClausPersson** [comment]
Issue solved.

**Comment by victorhugorevisado** [comment]
@ClausPersson . It worked. tks!
