### ISSUE TITLE
Problem with creating model pattern of diagonal direction by using "Make Pattern" tool

### ISSUE THREAD

**Issue by peter-topchiev** [eirannejad/pyRevit#2036]
# 🐞 Describe the bug

There is a difference between angles in result model pattern and sketch by using "Make Pattern" tool

Difference is not constant in different cases. It looks like mistake in calculations.

# ⏲️ Expected behavior

Expected result pattern totaly same as sketch

# 🖼 Screenshots of the issue
![image](https://github.com/eirannejad/pyRevit/assets/70806803/b184057e-48b8-46ce-98d8-db223a64b64b)

![image](https://github.com/eirannejad/pyRevit/assets/70806803/1e5cac18-2cd3-4405-bbac-9f8327204ac0)

**Comment by jmcouffin** [comment]
Without a dimensioned drawing, this is impossible to test.
Please provide a sample revit file with the two patterns (regular and with angle), with dimensions and filled region for me to test.

It could have to do with this ratio ANGLE_CORR_RATIO = 0.01 in https://github.com/eirannejad/pyRevit/blob/master/extensions/pyRevitTools.extension/pyRevit.tab/Modify.panel/edit1.stack/Patterns.splitpushbutton/Make%20Pattern.pushbutton/patmaker.py#L33

you could try different ratio editing the pyrevit file pointed 🔼 to see if this is related.

it could also be linked to the rounding done by Revit. Changing your units could give you proper results

**Comment by peter-topchiev** [comment]
Thank you for answer, here the file with my case

[2024.01.12_pyrevit_issue_RVT2023.zip](https://github.com/eirannejad/pyRevit/files/13921464/2024.01.12_pyrevit_issue_RVT2023.zip)

**Comment by peter-topchiev** [comment]
I've tried that, but it was not helpful(

> It could have to do with this ratio ANGLE_CORR_RATIO = 0.01 in

**Comment by jmcouffin** [comment]
Same issue here, 
It is most probably due to the rounding that occurs when creating the pattern
https://hatchkit.com.au/faq.php#Tip7
Scaling done the pattern improves the precision on the angle proportionaly

You may want to hard code the pattern by hand or take another approach (family, curtain walls) as I don't thing the wohle thing is entirely fixable. But I might be wrong.

**Comment by jmcouffin** [comment]
Shall I close this one as I doubt there is an efficient way to fix this @peter-topchiev ?
