### ISSUE TITLE
ERROR WITH NON-ASCII character (spanish character)

### ISSUE THREAD

**Issue by Juanita1345** [eirannejad/pyRevit#2037]
Hi, I created a toolbar that was working good, but now that I'm trying to run the script again I have the following error, showing that can't read an spanish character. The weird thing is that it was working before and I don't know why it seems that the enginee doesn't have that configuration anymore

Also, and may be related to it, the tool for download schedules doesn't work anymore either.

![Captura de pantalla 2024-01-11 173811](https://github.com/eirannejad/pyRevit/assets/105620717/29680daf-ac34-4e65-9c34-c293927fc6ea)

**Comment by jmcouffin** [comment]
When using languages with accents / non-ascii characters: french, spanish, german, ... , you need to declare the encoding at the beginning of your python script like so:

```pyhton
# -*- coding: utf-8 -*-
# then your code

```

It is a python 2 thing, most of the pyrevit stuff being in Iron Python, it is required.
In python 3 you can forget about it.

There is no "download schedules" tool that I know of. There is an "Export Schedules" but it works fine with ascii characters on my side.

**Comment by jmcouffin** [comment]
reference: https://stackoverflow.com/questions/4872007/who-originally-invented-this-type-of-syntax-coding-utf-8
