### ISSUE TITLE
clear schema does not work on Revit 2024

### ISSUE THREAD

**Issue by tjxme** [eirannejad/pyRevit#2039]
from the office document, the plugin schema API has been changed from revit 2024. 
Is there a way to get revit 2024 to support wipe schema option please please??

![image](https://github.com/eirannejad/pyRevit/assets/45146203/d02b3b1c-c311-483b-a158-f624541cbf0c)

**Comment by jmcouffin** [comment]
latest wip installers located in the actions tab of the GitHub repo (at the bottom of the page of any of the latest actions) to get the latest changes from the develop branch should fix it.

**Comment by jmcouffin** [comment]
In the latest release of the WIP Installers, everything is done by the book, but in my tests it seems that:
- every time the ListSchemas() method is called the schemas are recreated (empty)
- when, after the wipe command, I run the purge command I see the list of processed schema that can be purged.
- whenever I launch the wipe command again or save, close, open the document, these guys are back.

**Comment by jmcouffin** [comment]
https://thebuildingcoder.typepad.com/blog/2022/11/extensible-storage-schema-deletion.html#5

**Comment by jmcouffin** [comment]
https://github.com/eirannejad/pyRevit/blob/develop/extensions/pyRevitTools.extension/pyRevit.tab/Project.panel/Wipe.pulldown/Wipe%20Data%20Schema.pushbutton/script.py

**Comment by jmcouffin** [comment]
https://github.com/eirannejad/pyRevit/issues/2039#issuecomment-1893450015

It does not seem to solve the whole thing

**Comment by tjxme** [comment]
That's good, can I just replace the py file to the install folder?

**Comment by tjxme** [comment]
seems working when use it, but it kept coming back even after purging.

**Comment by jmcouffin** [comment]
> seems working when use it, but it kept coming back even after purging.

It does clear the content of the schema in my tests only

**Comment by tjxme** [comment]
so i see them as purgable item, however, after i selected them to purge, they are still there if i hit wipe schema. 

![image](https://github.com/eirannejad/pyRevit/assets/45146203/2641228a-dc24-4fdb-a0b2-28c076cb6408)
![image](https://github.com/eirannejad/pyRevit/assets/45146203/cd97a073-6317-4cb0-adcd-de760c6f352e)
![image](https://github.com/eirannejad/pyRevit/assets/45146203/7909242f-607e-4461-9665-f95416a7d2bd)
![image](https://github.com/eirannejad/pyRevit/assets/45146203/ac173e7c-0aeb-4846-9e69-3404f42f62a3)

**Comment by jmcouffin** [comment]
> so i see them as purgable item, however, after i selected them to purge, they are still there if i hit wipe schema.

Same here. No real solution for now, I think.
