### ISSUE TITLE
Calling Rhino.Inside from pyRevit possible?

### ISSUE THREAD

**Issue by ay-ex** [eirannejad/pyRevit#2040]
**Is your feature request related to a problem? Please describe.**
Some geometric operations in Revit are very hard or impossible to do.
E.g. boolean difference of elements with complex geometry. 
This was feasible via pulling the elements in question into rhino with 
rhino.inside.rvt, performing the geometric operation there and bringing 
the geometry back into rvt in a direct shape and apply the appropriate 
parameters.

**Describe the solution you'd like**
A small example or hint, on how to put my python logic into a pyRevit 
script, so the rvt user could conveniently trigger the action inside rvt 
(provided they have the required applications installed).

**Describe alternatives you've considered**
The logic can certainly be run from rhino script edit when it is started 
via rhino.inside, but this is surely not for the regular end user.

**Additional context**
Thank you so much for this awesome pyRevit framework!!

**Comment by sweco-begertjanvdb** [comment]
Isn't this a duplicate of #2020 ?

**Comment by ay-ex** [comment]
Ouch, I already had asked that? Sorry definitively a duplicate, will close and continue on #2020.
