### ISSUE TITLE
4.8.13.23182 Causing Revit 2024 to not open

### ISSUE THREAD

**Issue by scrowephalcon** [eirannejad/pyRevit#2052]
**🙏 Please use the search in the issue section before filing a new issue**

---

# 🐞 Describe the bug

When Pyrevit 4.8.13 OR 4.8.14 are installed all versions of revit open as expected and show the pyrevit tab, EXCEPT Revit 2024, which will not open passed the screen shot below and then just closes. When Pyrevit is uninstalled, Revit 2024 opens as expected

# ♻️ To Reproduce
1. Go to 'Revit 2024'
2. Click on 'Launch Application'
4. Revit 2024 shuts down

# ⏲️ Expected behavior
I expect Revit 2024  to open completely and not just shut down when the Revit 2024 screen shows

# 🖼 Screenshots of the issue
![image](https://github.com/eirannejad/pyRevit/assets/156962296/5f7eea35-3332-4eaf-85ab-068426993661)

# 🖥️ Hardware and Software Setup (please complete the following information):
 - OS: 19045.3930
 - pyRevit Version 14.8.13.23182
 - pyRevit Environment: 
 - ==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.14.24016+1909" | Path: "C:\Users\alyssa.iris\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "24.2" | Engine: IPY277 (277) | Path: "C:\Users\alyssa.iris\AppData\Roaming\pyRevit-Master"
master | Product: "23.1.3" | Engine: IPY277 (277) | Path: "C:\Users\alyssa.iris\AppData\Roaming\pyRevit-Master"
master | Product: "2022 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Users\alyssa.iris\AppData\Roaming\pyRevit-Master"
master | Product: "2021.1.9" | Engine: IPY277 (277) | Path: "C:\Users\alyssa.iris\AppData\Roaming\pyRevit-Master"
master | Product: "2020.2.9" | Engine: IPY277 (277) | Path: "C:\Users\alyssa.iris\AppData\Roaming\pyRevit-Master"
master | Product: "2019.2.6" | Engine: IPY277 (277) | Path: "C:\Users\alyssa.iris\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\alyssa.iris\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 1033 | Path: "C:\Users\alyssa.iris\OneDrive - Phalcon Ltd\Documents\Downloads\Revit 2024\"
23.1.3 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022 First Customer Ship | Version: 22.0.2.392 | Build: 20210224_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021.1.9 | Version: 21.1.90.15 | Build: 20230907_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.9 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.6 | Version: 19.2.60.3 | Build: 20220224_1700(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: MCPHEE\alyssa.iris
Active User:
Admin Access: No
%APPDATA%: "C:\Users\alyssa.iris\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.14.24016+1909.ee814ee2f686d23db8bb6ff80d8bb918ff9adc99

U:\>

👉 `pyrevit env`

# Additional context

**Comment by sweco-begertjanvdb** [comment]
could potentially be an interfering plugin. Are there any new or different plugins loaded in your revit 2024?

**Comment by jmcouffin** [comment]
Read this: https://github.com/eirannejad/pyRevit/issues/2035

the reply is almost always the same:

Uninstall
Remove %appdata%/pyrevit and %appdata%/pyrevit-master folder if any
Move Revit addins to temp location
install latest pyrevit
start Revit once - close it
bring revit addins to their original location

**Comment by scrowephalcon** [comment]
> could potentially be an interfering plugin. Are there any new or different plugins loaded in your revit 2024?

Only pyrevit

**Comment by scrowephalcon** [comment]
> Read this: #2035
> 
> the reply is almost always the same:
> 
> Uninstall Remove %appdata%/pyrevit and %appdata%/pyrevit-master folder if any Move Revit addins to temp location install latest pyrevit start Revit once - close it bring revit addins to their original location

Unfortunately as soon as I install pyrevit, 2024 will no longer open

**Comment by jmcouffin** [comment]
Try to use diroots app manager to disable remaining addins. Even though you don't have extra addins, Revit treat exporters and other functionalities as addins

**Comment by jmcouffin** [comment]
a good recap here of solutions here https://discourse.pyrevitlabs.io/t/new-release-error-dynamically-compiling-pyrevit-runtime/2621 , try to follow these
and wave 👋 if you did not manage in the end.
I will close it for now
