### ISSUE TITLE
Exception: Error dynamically compiling pyRevit runtime when installing "pyRevit_4.8.14.24016_signed.exe"

### ISSUE THREAD

**Issue by Ray-gurge** [eirannejad/pyRevit#2055]
I try to Install the last update of pyRevit "pyRevit_4.8.14.24016_signed.exe", was initially on "pyrevit-installers_4.8.11.22103"

first at Windows opening :
![Revit_pyrevit MAJ---](https://github.com/eirannejad/pyRevit/assets/157116326/087a3859-52b2-4f5f-ba59-4b544be5dbc8)

and at Revit 2023.1 opening
![Revit_pyrevit MAJ2](https://github.com/eirannejad/pyRevit/assets/157116326/5c3ff97a-d053-481d-9d72-685e1ae115d5)
... but it works with Revit 2020.2.9 !!

First time i've have problems with pyRevit
I followed the instructions from :
https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7
https://discourse.pyrevitlabs.io/t/error-message-loading-pyrevit-in-2023/948/2
...Uninstall, reinstall...
Can't work without pyRevit 

Thank's for reply

**Comment by jmcouffin** [comment]
as mentioned many times around, following precisely this, fixes the pb:
What seems to work in most cases:

1. **Uninstall pyRevit**
2. **Delete** C:\ProgramData and \%AppData%\ pyRevit folders
3. **Move all Revit addins** to a temporary location. Usual addins locations include:
    1. %AppData%\Autodesk\Revit\Addins\<year>
    2. %AppData%\Autodesk\ApplicationPlugins
    3. %ProgramData%\Autodesk\Revit\Addins\<year>
    4. %ProgramData%\Autodesk\ApplicationPlugins
4. [Reboot computer]
5. **Reinstall pyRevit**
6. Started **each version** of Revit confirming pyRevit successfully compiled at startup.
7. **Moved all Revit addin**s that were moved in step 3 back to their original location.
    1. you may want to add them one at a time and start a revit session everytime to figure out which ones are causing the issue.
    

also, your config file must tell that it uses the CustomTools extension but that it cannot find the folder where it is located.
Removing the pyrevit-config.ini file or the CustomTools extension should fix it

**Comment by Ray-gurge** [comment]
... Fixed!
Merci beaucoup!!

It was certainly some mishandling on my part (which one? never had this before) during the set up, and not a bug.

**Comment by ErikFrits** [comment]
I also had this issue, so I made a quick tutorial.
**Same steps that Jean-Marc has mentioned.**
https://www.youtube.com/watch?v=DY2lxPvFP9c
