### ISSUE TITLE
Error Message when trying to copy legends

### ISSUE THREAD

**Issue by charleswday** [eirannejad/pyRevit#206]
I am trying to duplicate legends am continue to receive an error message:

![error message](https://user-images.githubusercontent.com/29783807/27706124-55a8cbda-5cde-11e7-915a-2ea6ca0e6bd9.PNG)

How can I correct this?

**Comment by eirannejad** [comment]
Do you have the legend view selected in project browser?

**Comment by eirannejad** [comment]
Can not replicate error.
