### ISSUE TITLE
Colour Splasher legend filled regions

### ISSUE THREAD

**Issue by jhtacoma** [eirannejad/pyRevit#2066]
This bug occurs in both Revit 2023.1 and 2024.1., on Windows 10.

I just installed pyRevit_4.8.14.24016 and tried out the Colour Splasher. After colourizing the walls, I click "Create a Legend" and a legend is indeed created -- except that all the filled regions are somehow invisible.

If I select one of the filled regions, here's how it looks:

![image](https://github.com/eirannejad/pyRevit/assets/111752346/76b2ba7f-d9e6-48e1-990b-c854c4c5c1ef)

As you can see, no outlines show when the filled region is selected.  If I copy and paste one of those filled regions, it behaves the same way -- invisible (although now it doesn't have graphics overrides of course, because it's a copy).   Same if I create a new filled region (of same type "Solid Black" or a different type; doesn't matter)

If I Duplicate With Detailing the legend, the duplicate exhibits the same behaviour (all the filled regions are invisible).

If I copy any of the 'invisible' filled regions and paste them into a different, pre-existing legend, then the pasted version IS visible (as black of course -- no overrides).

Another strange effect is that these mysterious filled regions are still invisible even when selected. Normally, even fully invisible elements (such as a filled region that bounded by <Invisible lines> and whose transparency has been set to 100 in Graphic Overrides) show up while they are drag-selected.  But when I drag-select from bottom right to top left, as shown in this screenshot, you can see that while the Filter shows that the various filled regions are indeed selected, they remain invisible:

![image](https://github.com/eirannejad/pyRevit/assets/111752346/018c8940-6c0f-4b48-a058-85b963f9c3ca)

By comparison, here is an invisible filled region from a different legend that has also been drag-selected (you'll have to take my word for it that it's invisible if not selected!):

![image](https://github.com/eirannejad/pyRevit/assets/111752346/c5a892a6-c614-42ce-a42d-43c8bc8eff97)

So ... I hope that's useful information. I appreciate that Revit's innards are probably a little messy, and people generally don't enjoy troubleshooting. :(

Jamie

# 🖥️ RESULTS FROM 'pyrevit env':

Microsoft Windows [Version 10.0.19045.3930]
(c) Microsoft Corporation. All rights reserved.

C:\Users\j.hutchings>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.14.24016+1909" | Path: "C:\Users\j.hutchings\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2024" | Engine: IPY277 (277) | Path: "C:\Users\j.hutchings\AppData\Roaming\pyRevit-Master" | AllUsers
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\j.hutchings\AppData\Roaming\pyRevit-Master" | AllUsers
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\j.hutchings\AppData\Roaming\pyRevit-Master" | AllUsers
master | Product: "Autodesk Revit 2021" | Engine: IPY277 (277) | Path: "C:\Users\j.hutchings\AppData\Roaming\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\j.hutchings\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2024 | Version: 24.1.10.25 | Build: 20230830_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
Autodesk Revit 2023 | Version: 23.1.20.70 | Build: 20230510_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.40.58 | Build: 20230505_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
Autodesk Revit 2021 | Version: 21.1.1.109 | Build: 20200715_1022(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages

**Comment by jmcouffin** [comment]
Thanks for the detailed explanation, it is both rare and appreciated.
I do have the same setup on my work computer, except I use the latest Revit version (2024.2)
Never had this issue. To create the legend, I have to use a transaction and it also calls for the view regeneration. So that should suffice. 

It looks like a view regeneration bug.

I'd like you to try first:

1. Have you tried in another file? A sample file? Maybe start blank and draw a few wall, add a legend, ...
2. With another category?
3. With another parameter?
4. Closing the legend created, saving, closing the file and reopening.
5. No template on the view? Filled regions colour replacement, Filters?
6. Maybe restart the computer to ensure this is not a heisenbug :)

You see where I am going, I doubt this is an issue with the script itself.

**Comment by jmcouffin** [comment]
Also, would you care to try to activate/deactivate the graphic's card hardware acceleration between two other test (It requires restarting revit)

**Comment by jhtacoma** [comment]
Hello Jean-Marc,

Hm .. Well I got as far as your first suggestion -- trying it in another file -- and it worked properly!  Then I tried the first file again, and it was back to invisibility.  I don't have the time now to try a process of elimination to really find the issue, but if I can provide additional insight in the future, I will let you know (though I agree it doesn't make sense that it's in your code, but instead in the mysterious Revit/graphics-card/Windows world...)

If it's not too far off-topic, I might offer one suggestion regarding the colour splasher, and that is to provide a wider (or brighter) range of colours -- or is this something I can tweak myself in the ColorSplasher.pushbutton/script.py file?  I noticed that if more than 5 or 6 items are being differentiated by colour, it's easy for a couple of them to look pretty similar, probably due to having low brightness levels.  Even after clicking repeatedly to re-randomize the colours, I found that some confusion between the different colours was still likely.

In any case, thanks for adding this to PyRevit.  It will definitely be useful.

Jamie

**Comment by jmcouffin** [comment]
You could send me your file or part of it to investigate if you like.

I will close this issue for now.
Feel free to ping me to reopen once you get to the down of it.
I will add your suggestion to another issue with a few suggestions already, but yes, you could tweak the range of the randomness of colours.

Thanks Jamie

**Comment by jhtacoma** [comment]
Hello Jean-Marc,

I have a sample file that consistently reproduces the "invisible filled region" error in the Legend-view creation procedure.  It's a 20mb Revit 2024 file (I've deleted and purged as much as I can, and this is the smallest I can make it).  How can I get the file to you?  There's no rush to have a look - I don't need to solve this, it's more just for your curiosity.

Thanks,
Jamie

**Comment by jmcouffin** [comment]
@jhtacoma send it to jmcouffin a t gmail

**Comment by jmcouffin** [comment]
after testing: Invisible covering zone, definitely a bug in the file as when the original legend is deleted the bug disappear
