### ISSUE TITLE
Pick Icon Change

### ISSUE THREAD

**Issue by diveyj** [eirannejad/pyRevit#2090]
Can a change to the Pick icon be made?  It looks just like a white power hand gesture which will definitely offend some.  happy to provide some alternatives.  thx.

**Comment by jmcouffin** [comment]
Please, do provide alternatives.
You can even make a PR against the develop-4 branch and I will be happy to merge.

**Comment by jmcouffin** [comment]
> white power hand gesture
what sucks is that the icon actually use the proper sign from ASL
https://www.youtube.com/watch?v=e4YCKEFcVdU

**Comment by jmcouffin** [comment]
![icons8-hand-cursor-96](https://github.com/eirannejad/pyRevit/assets/7872003/f95df728-9ef2-450d-8a64-ae5d37441ad7)
this one could do

**Comment by sanzoghenzo** [comment]
from [ADL](https://www.adl.org/resources/hate-symbol/okay-hand-gesture):

> Because of the traditional meaning of the “okay” hand gesture, as well as other usages unrelated to white supremacy, particular care must be taken not to jump to conclusions about the intent behind someone who has used the gesture.

**Comment by diveyj** [comment]
Yeah, it does suck that this is even an issue, I just thought it might avoid any confusion.

DAVID IVEY
HOK
***@***.***
t +1 312 254 5345  m +1 847 494 3823

**Comment by diveyj** [comment]
That one is perfect


DAVID IVEY
HOK
***@***.***
t +1 312 254 5345  m +1 847 494 3823

**Comment by jmcouffin** [comment]
fixed by 2092
![icon](https://github.com/eirannejad/pyRevit/assets/7872003/08b87ef9-a8ee-4b02-88c4-b88ed3c27a49)
![icon dark](https://github.com/eirannejad/pyRevit/assets/7872003/c3001e4e-66a2-4a47-ac46-663a2cfaf362)

**Comment by diveyj** [comment]
Awesome!

DAVID IVEY
HOK
***@***.***
t +1 312 254 5345  m +1 847 494 3823
