### ISSUE TITLE
PyRevit + Dynamo Conflict?

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#210]
I have noticed some weird things happening in terms of pyrevit vs dynamo.

Lately, I think I have noticed one other thing.
Dynamo will open fine, BUT, if I use pyrevit, then try using dynamo after, Dynamo will not launch.
Restaring Revit and not using pyrevit before launching Dynamo will fix.

Pyrevit loads a newer version of IronPython + IronPython WPF and corresponding assemblies, and once those are loaded, Dynamo will try to used them instead. I have inspected the clr.References from within Dynamo, and noticed that they point to the DLLs inside the pyrevit folder. 

Just wondering if anyone else has had this issue? Are you able to launch dynamo after using pyrevit in the same session?

![image](https://user-images.githubusercontent.com/9513968/27934426-b348fc84-6273-11e7-8156-1220a09672fb.png)

**Comment by eirannejad** [comment]
Tested the stand-alone dynamo and it runs fine after pyRevit. Are you talking about the dynamo sketch runner inside Revit?

**Comment by gtalarico** [comment]
Regular dynamo inside of revit. 
Might be a problem on my end. 
I installed 1.3, and I can now open, but I can't use the python node:
https://github.com/DynamoDS/Dynamo/issues/8028
