### ISSUE TITLE
Extra characters on repeated Emojis

### ISSUE THREAD

**Issue by sanzoghenzo** [eirannejad/pyRevit#2104]
# 🐞 Describe the bug

Problem raised in [this forum discussion](https://discourse.pyrevitlabs.io/t/emojis-breaking-output-print-table/2667).

![image](https://github.com/eirannejad/pyRevit/assets/977953/e04e69bd-f287-41ef-9ff1-3b055e37e448)

Note that this is not strictly related to tables, but with repeated emojis and how the [`Emojize` c# method performs the substitutions](https://github.com/eirannejad/pyRevit/blob/6f72bb9b3b5389d281a2ad1eba2995e94be32d9b/dev/pyRevitLabs/pyRevitLabs.Emojis/Emojis.cs#L2650-L2670).

The regex `Match` finds all the shorthands, then for each of them it retrieves the icon and performs a  replace on the entire text with an html <img> tag with the shorthand as title.
The subsequent match of the same shorthand repeats the replace on the shorthand contained in the title, causing a recursion. that produces extra `">`s in the output.

The solution here is to take only the unique/distinct matches of the regex.

As I discussed in the linked topic, it may also be the case to drop the zip archive containing the icons and rely on fonts such as [Noto Color Emoji](https://fonts.google.com/noto/specimen/Noto+Color+Emoji) and unicode chars.

I'm already working to address both issues.

**Comment by jmcouffin** [comment]
Fixed by #2105 
Thanks @sanzoghenzo
