### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Michgadu8** [eirannejad/pyRevit#2106]
I am encountering an error when opening revit both versions I use 2022 and 2024, uninstall pyrevit and install iron python and then install them again and nothing same error.

Can you please give me some directions how to fix it?

![error 1](https://github.com/eirannejad/pyRevit/assets/136072516/b5bad3b5-83c0-4c1f-8c80-68ed360da3b0)
![error 2](https://github.com/eirannejad/pyRevit/assets/136072516/0d643b8c-a210-40b2-867f-5710d1856e6b)

**Comment by sanzoghenzo** [comment]
Unfortunately these two screenshots don't tell us anything, we need the first part of the error to better understand what is happening.

That being said, there's plenty of other issues here and discussions in the forum with the same problem, you should search for them and try to apply the suggested fixes.

Finally, you totally ignored the bug report template, which asked you to provide more thorough information than two screenshots.

Please help us to help you, we're just a bunch of hobbyists with limited time and resources.
