### ISSUE TITLE
Match Tool Stopped Working

### ISSUE THREAD

**Issue by Pyrevit-User** [eirannejad/pyRevit#2109]
The "Match" tool in Pyrevit has stopped working. I tried uninstalling Pyrevit and re-installing the latest version V.4.8.14, thinking that it could have been a glitch in the script that might get resolved by reinstalling latest. The issue still persists in the new version. This was the tool that enables a Revit user to match the graphic overrides of one source element with other elements easily and quickly, which was a big time saver. Can other users please check and advise on how to solve this issue?
Thank you!

**Comment by sanzoghenzo** [comment]
Hi @Pyrevit-User, you completely ignored te bug report template, in which there were instruction on how to correctly report any iussues. It is difficult to diagnose your problem without more detailed info, for example: 

- what do you mean by "Stopped working"? mothing happens when you click on the button? or it starts and then outputs an error? which error? 
- How can I reproduce the problem? what are the steps involved?
- What are the specs of your environment? (that's the `pyrevit env` part at the end of the template)

**Comment by Pyrevit-User** [comment]
Apologies about the template and sorry for missing it.
I'm only a user not a developer, so I'm not sure what terms like "mothing" and  "specs of environment" are. There is no error that pops when I use the match tool. After I click the match button, the screen gets in the orange mode and directs me to select the source element which I do, then to select the element(s) I want to match, which I also do. Then nothing happens! No matching and no error either.
Thank you!

**Comment by sanzoghenzo** [comment]
"mothing" was a typo, I meant "nothing" 😅 

So the tool runs but it doesn't actually do what is intended to do. This is much more useful than "stopped working" 😉 

Hold the CTRL keyboard key while clicking on the match tool; an output window with many debug messages will popup (and will slow down the loading of the tool, but this is normal).
Leave the window open and use the tool as you described; there may be new messages in the window.
Click on the floppy disk icon in the title bar to save the contents of the window to a file and upload it here.

Thanks in advance for you collaboration!

**Comment by Pyrevit-User** [comment]
Thank you for your guidance. I uploaded the file here to this message.
[Test.zip](https://github.com/eirannejad/pyRevit/files/14376739/Test.zip)

**Comment by sanzoghenzo** [comment]
Thanks, I thought this would be more verbose, here's the content:

```
DEBUG [pyrevit.revit.selection] Picking elements: Element message: multiple: False world: False
DEBUG [pyrevit.revit.selection] Picked elements are: [<Autodesk.Revit.DB.Reference object at 0x00000000000031B1 [Autodesk.Revit.DB.Reference]>]
DEBUG [pyrevit.revit.selection] Processed return elements are: [<Autodesk.Revit.DB.Wall object at 0x00000000000031B2 [Autodesk.Revit.DB.Wall]>]
DEBUG [pyrevit.revit.selection] Picking elements: Element message: multiple: True world: False 
```

From what I understand, the first selection goes well, but the second one (that allows multiple elements) seems to be interrupted.

Analyzing the source code, I see that the errors are swallowed by a [try/except block](https://github.com/eirannejad/pyRevit/blob/6f72bb9b3b5389d281a2ad1eba2995e94be32d9b/pyrevitlib/pyrevit/revit/selection.py#L150-L215), so it's hard to understand what's goincg on.

@jmcouffin do you have any ideas?

@Pyrevit-User how comfortable are you changing python source code? You can try this:

- Open the file `pyrevitlib/pyrevit/revit/selection.py` (from the pyRevit installation directory) with a text editor (Visual Studio code is my go to editor, but you could just use Notepad)
- replace the lines 214 and 215 with the following:

  ```
      except Exception as exc:
          mlogger.error("Unexpected error: %s", exc)
          return None
  ```

- save the file, then re-run the match tool while holding the CTRL key, and check the output messages. Hopefully you'll get more clues of what's happening.

**Comment by sanzoghenzo** [comment]
Are you sure you are on the latest version of the code?

These are the two lines to change:

https://github.com/eirannejad/pyRevit/blob/a946e0d4f5452fa072c566e5ea786518b9b8cb53/pyrevitlib/pyrevit/revit/selection.py#L214-L216

The're at the end of the `_pick_obj` function, and just before the `pick_element` function.

**Comment by sstantonTB** [comment]
Found the lines thanks, I was able to make the replacements and it now works but throws an error anyway.

`ERROR [pyrevit.revit.selection] Unexpected error: The user aborted the pick operation.`

**Comment by sanzoghenzo** [comment]
> We're on version 4.8.13.23182 if that helps explain the difference in file numbers.

Sorry,  I read this info only now 😅 
In the first post @Pyrevit-User mentioned an upgrade to 4.8.14 without any indication of a downgrade after that,  this is why I pointed you to those lines.

Does that message occurs right after you click on the element, or only after pressing any other key/button?

@jmcouffin any thoughts? Can you reproduce this?

**Comment by sstantonTB** [comment]
That was my fault, we were using a different machine when we tested the second time. I've updated them all to 4.8.14 now and found your lines in the correct location.  Error still stands though, in the new version.

**Comment by sanzoghenzo** [comment]
Do you click on "Finish" button that appears just under the ribbon bar?

The error message you pasted here occurs when you press the ESC key or the "Cancel" button, this is why the tool doesn't continue to match the elements.

**Comment by jmcouffin** [comment]
I will have a look on Monday.

**Comment by Pyrevit-User** [comment]
Thank you @sanzoghenzo Sanzo and @jmcouffin . It works fine now with no error message. Appreciating the help and wishing you a good week.
