### ISSUE TITLE
Idea: Close other open windows when a new one is created

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#211]
I can see a case where one might want more than one window open, but at least for me, 
when I run a new script, I am probably no longer interest in the previous session.

When writing/testing scripts, I often end up with dozens of open windows, as they fall to the background and new ones are created.

Suggestion:
1. Settings: Allow Multiple output window instances?
2. If NOT, when new output windows are launched, previous ones are closed

I would be happy to help implement if you think it's a valid use case
Thoughts?

**Comment by eirannejad** [comment]
pyRevit console has a self-destruct mode accessible as shown below:
``` python
from scriptutils import this_script
this_script.output.self_destruct( number_of_seconds )
```

But yes, I'm open to this feature very much. Let me know your thoughts on the implementation concepts. How would multiple console windows work? `output.new_console()`?

**Comment by gtalarico** [comment]
My original idea was not allow to create new windows from script, but that's an interesting idea as well :) 

My original suggestion, which I did not explain very well, was to have an toggle in the settings that define if more than one console window can be open at any time, meaning, previous windows would self destruct when a new one is created. 

I can send a sketch with more details later

**Comment by gtalarico** [comment]
![image](https://user-images.githubusercontent.com/9513968/27975121-4e3a7844-6337-11e7-8f2a-95a104a3a22f.png)

**Comment by eirannejad** [comment]
Okay I think I understood. So pyRevit setting that would tell pyRevit to close any previously open and orphaned window when opening an new console window. (orphaned window being a window that the python process for has been completed)

The option would look something like this:

- [X] Minimize the number of open consoles:
- - [X]  Close console windows for current command
- - [ ]  Close all orphaned console window

**Comment by eirannejad** [comment]
Resolved
Commands can now ask the pyRevit output window manager to close other output windows (previous windows of the same command or all output windows)
``` python
from scriptutils import this_script

# close pyRevit output windows of this command only
this_script.output.close_others()

# close all pyRevit output windows
this_script.output.close_others(all_open_outputs=True)
```

This line could be added to any script that cares about it's window clutter.


FYI:
pyRevit output window manager is under:

``` python
from pyrevit.coreutils.console.outputmgr import get_all_consoles

for out_wnd in get_all_consoles():
    print(out_wnd.get_title())
```
