### ISSUE TITLE
Quickstart section in README 

### ISSUE THREAD

**Issue by pjhfggij** [eirannejad/pyRevit#2113]
## Is your feature request related to a problem? Please describe

I'm seriously struggling to get started - and reloading revit each time takes forever.

## Describe the solution you'd like

Create a quickstart section with minimal examples for each bundle that just work™.

For example:

### nobutton bundle

1. Add a `custom location` in `pyRevit -> Settings`
2. Create a folder `lsieurbg.extension` in `custom location`.
3. Create a `serigubseigu.nobutton` in `lsieurbg.extension`.
4. Create `script.py` in `serigubseigu.nobutton`.

## Describe alternatives you've considered

Trial and error while questioning my life choices :)

**Comment by sanzoghenzo** [comment]
Hi @pjhfggij , thanks for the pointer, indeed finding the info needed to build a bundle that is not a pushbutton is not so straightforward.

But I must say that the steps you described are shared by all the commands and described in the [Create your first Command page](https://pyrevitlabs.notion.site/Create-Your-First-Command-2509b43e28bd498fba937f5c1be7f485) that is already linked in the readme file.

One thing that could (and should) be made is to add a link in that page to the [various bundle types available](https://pyrevitlabs.notion.site/pyRevit-Bundles-12323e3090904d9aa7cdc3d82095d3e3#5e111f1cb9f246deb3137067651d46cc)

@jmcouffin I don't have write permissions in the notion site, do you?

**Comment by pjhfggij** [comment]
I would just try to streamline this process. It took my 2 days to go through all the materials, but it essentially just boils down to creating this folder structure (which I don't think should be necessary just to run a simple script). I think that it deserves to be on the first page, because this is the first step user needs to take to get it anything to work.

**Comment by sanzoghenzo** [comment]
The folder structure is the first thing mentioned in the "Create your first command" page, which is the first link of the section [Get started developing for pyRevit](https://github.com/eirannejad/pyRevit?tab=readme-ov-file#get-started-developing-for-pyrevit). That page is also the second link in the [pinned QuickStart guide on the pyRevit Forums](https://discourse.pyrevitlabs.io/t/quickstart-in-the-realm-of-pyrevit-and-the-revit-api/2050).

**Comment by jmcouffin** [comment]
> One thing that could (and should) be made is to add a link in that page to the [various bundle types available](https://pyrevitlabs.notion.site/pyRevit-Bundles-12323e3090904d9aa7cdc3d82095d3e3#5e111f1cb9f246deb3137067651d46cc)

done
![image](https://github.com/eirannejad/pyRevit/assets/7872003/20720965-6a86-465d-89d7-dbd4e21e5da5)

**Comment by jmcouffin** [comment]
You can leverage the pyRevit Bundle creator extension to get you started extremely quickly.
![image](https://github.com/eirannejad/pyRevit/assets/7872003/657bca20-663b-4f88-80ec-14f4bdeaa86f)
