### ISSUE TITLE
Duplicate sheet tool

### ISSUE THREAD

**Issue by eirannejad** [eirannejad/pyRevit#212]
Tool specs:
- [ ] Must duplicate one or more sheets
- [ ] Must be smart about duplicating model vs detail views
- [ ] Must be smart about the sheet contents
- [ ] Must be smart about the sheet metadata including revisions
- [ ] Must provide options for the user to config tool behaviour

**Comment by jbenoit44** [comment]
Hi, amazing job you did with pyrevit.

I am running into an issue with this very feature: sheets are copied but not views. no error so far in the popup window, views are reported being copied. I use Revit 2019 and both projects are workshared.
Views doesnt exist in destination file, just a revit message saying a titleblock family is renamed to avoid conflicts.
﻿


_Copying Sheet(s) to Document: 18-0220_DEG8#2019_Studie påbygg_julienUMM6R

Copying Sheet: A42_3-00_01 - Snitt A-A, langsnitt



  Copying/updating Sheet: Snitt A-A, langsnitt



    Copying/updating view: Snitt A-A



Skipping revisions...



Copying Sheet: A42_3-00_02 - Snitt B-B, tverrsnitt og fasade mot nord i passasjen



  Copying/updating Sheet: Snitt B-B, tverrsnitt og fasade mot nord i passasjen



    Copying/updating view: Snitt B-B



Skipping revisions...



Copying Sheet: A42_3-00_03 - Snitt E-E, tverrsnitt og fasade mot sør i passasjen



  Copying/updating Sheet: Snitt E-E, tverrsnitt og fasade mot sør i passasjen



    Copying/updating view: Snitt E-E



Skipping revisions...




Copied 3 sheets to 1 documents._

**Comment by eirannejad** [comment]
@jbenoit44 Model views can not be copied at the moment as they are 3D cuts of the actual model. So in some sense it does not makes sense to copy them since they'll be blank in the target model. There is also complications with level associations as well. The solution is more complex and that's why I did not implement that when working on that tool.

Share your use case and ideas please tho. We'll implement it if it's a useful feature that could save a lot of time.

**Comment by tillbaum** [comment]
When dublicating a sheet. 
- Title Block(s) and legend views must be copied and inserted on the same spot. 
(Legend Views and Tables can easily be copied and inserted on the new sheet.)
- Sheet Nr must be increased. (increased until it hits a nr which can be used. )
- Sheet Name can be set to "old name"-copy. 

- Copying a Floor Plan/Elevation/Section is difficult because it must be duplicated first. (duplicated with Details, without details, as dependend View) 

copying just the sheet with titleblocks and all views which can already be inserted on multiple sheets (Legends, Tables) would be a good start.
Has this script already been coded up? 
Thx.

**Comment by tillbaum** [comment]
Hello, I would code this one up.

**Comment by dsellam** [comment]
I would love to see such feature in PyRevit !

**Comment by eirannejad** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/840

**Comment by Hmunsell** [comment]
Tillbaum, that would be fine, delete any views on the sheet, but keep any annotation that was added (guide grid settings, graphics scales, north arrows, etc...) in 2020 you should be able to keep any legends added to the sheet as well.

**Comment by tillbaum** [comment]
Legends and Schedules can be added to multiple sheets naturally. All other views (drafting, floorplan, section....) have to be duplicated. 
Here is my version. of the Dublicate sheet tool. 
It supports dublication of multiple TitleBlocks and legends
Thats all it does. 

Chosse a sheet and click the dublicate button.
It creates a new sheet with the same TitleBlocks and legends on the selected sheet and  places TitleBlocks and legends on the same coordinates. 
[dublicatesheet.pushbutton.zip](https://github.com/eirannejad/pyRevit/files/4270479/dublicatesheet.pushbutton.zip)

**Comment by cinkovic** [comment]
Hi there. 
I cannot emphasize enough how much we need a tool to copy sheets WITH VIEWS between Revit files.
Every large project is set up using multiple models. You also do detach copies to work on options and any work done needs to be transferred back to main project quickly. 

Do you think this feature can be added in?
Once again - this issue occurs regularly!

Many thanks,
M

**Comment by tillbaum** [comment]
Do you want to copy views between different Revit Projects?

**Comment by cinkovic** [comment]
> 
> 
> Do you want to copy sheets between different Revit Projects?

Yes I do.

**Comment by cinkovic** [comment]
Hey,

Thanks for a quick response.
Sorry I did not write back - your email ended up in the spam folder:(

Yes, preferably sheets containing model views (not schedules or legends).
We do work on multiple files ie facade model & internal model. We also do
design exercises in detached models that, when accepted, have to be copied
to the main central model.
Currently we have to recreate manually any sheets created in detached
models & having the possibility to copy it back would be a game changer.

Marcin

**Comment by tillbaum** [comment]
So do you copy your detached models manually back to your main model?

**Comment by tillbaum** [comment]
THis can be done with the revit api

**Comment by cinkovic** [comment]
Tillmann,
It's about sheets with views that need to be copied between models. There
are many reasons why we'd like to do it, the bigger project team, the more
reasons we have.
PyRevit does it for schedules and legends.
I want to do the same for whole sheets with plans (including callouts),
sections & elevations on them.
Do you think this is possible as well?
M

**Comment by tillbaum** [comment]
Technically yes, it can be done. But its a lot of work. (Don't know yet how much work it would mean for me.) 
Because you would have to copy the model and all the views (or create new ones) too.
Can you show me a vid, or a photodocumentation of the workflow. What you want to achieve?

**Comment by tillbaum** [comment]
I wanted to do something similar, copy model elements from one model to the other, so maybe I could do it,
but I also have a job - I have to take care of, so I don't know how much time I could afford.

**Comment by cinkovic** [comment]
Let me briefly describe what I want to achieve.
I have a project, a masterplan with a number of buildings. Each building
consists of a few models at our end (interiors, facade, basement) + we
detach models for some design studies. In addition we have coordination
drawings with multiple consultants that contribute with their models to the
project (structural, M&E, landscape etc).
I want to copy 'the work' from one model into the other and it may consist
of two parts: geometry and/or drawings.
You can copy model content manually (paste in place, copy monitor, bind).
This is therefore not what troubles me the most.

Simply speaking - you cannot copy drawings, like this one:
[image: image.png]
Bay study being only an example, in Revit terms this is a
section/elevation, probably with a view template. Annotations are a bonus
as you can copy them in place later.

I therefore want to focus on copying sheets with views.
I understand that it may be technically complicated. I have some limited
knowledge of python, less so with Revi API.
I don't know if that can be of any help, I would perhaps like to at least
understand where the complecticies are.

Regards,
Marcin

**Comment by tillbaum** [comment]
What do you mean with drawings? 2d geomentry like lines and text, dimensions and annotations?

General Tip: You can also link existing models into other models.

**Comment by tillbaum** [comment]
I cannot see the image you provided. You can send it to me via email: tillmbaumeister@gmail.com

**Comment by tillbaum** [comment]
Views on sheets are only pictures of your main 3D model.

 If you want to copy one view from one 3D model to the other, 
you would also have to copy the whole 3d Geometry which is displayed by your view. 

This would mean:
1. select all 3D geometry on your view and copy it to the second model. On same coordinates. 
2. create the same view (with same settings) in your second model. 
3. Create a sheet, and place the view on it. 

Another workaround would be to export the sheet including all view as a dwg. 
And import the dwg in the second model. Then you would have a 2D representation of the 3D Geometry of your first model.

**Comment by cinkovic** [comment]
I'll try to elaborate, but quickly: imagine that you have 3 models: one
that contains geometry only, second one with sheets only. Second one has
first one linked.
Third one is empty and the task is to copy into it selected sheets, say a
sheet with a floor plan, a sheet with an elevation, a sheet with a section
and one with callouts.
Each sheet has a drawing number, a drawing frame. Each view has a view
template + annotations.
Would it be possible?

**Comment by DuncanLithgow** [comment]
I believe this issue is about duplicating sheets between projects. Maybe the issue name could be changed to what I believe is the name of the tool "Copy Sheets between Open Documents".

( I'm looking for a way to duplicate Sheets in the same projects ... )

**Comment by alexdaversa** [comment]
@eirannejad is this new tool still applicable given 2022.1 released with a duplicate sheet tool? I think copying sheets with model geometry from one model to another is a separate issue.  My own opinion is that the copy model views from project to project tool would require too much customization each time it is used for it to be worth the time to code it.

**Comment by DuncanLithgow** [comment]
I think I agree with @alexdaversa that actions between models is a different tool and should be in a different place. The use case @cinkovic has described is still not clear to me and needs more precise language taking terms from the Revit interface. But please, in a different issue (or rename this one)

**Comment by NachoSupparo** [comment]
@cinkovic @tillbaum - Im having a similar issue, working on a large proyect with multiple teams and not being able to use cloud models. To merge sheet work between teams, Ideal workflow would be to transfer Model work with RVT linking and binding, and then being able to transfer views, detail and sheetwork with this tool.

Thank you and thank you again for the effort, time and dedication put in such an amazing Plugin.
