### ISSUE TITLE
"Get RVT Info" doesn't execute

### ISSUE THREAD

**Issue by svalenziano** [eirannejad/pyRevit#2122]
# 🐞 Describe the bug

PyRevit Get RVT Info doesn't execute for *some* .rfa files.  

In my experimentation, it appears that attempting to get version info from 2023 .rfa files throws the error.  2024 .rfa files work fine.  **Edit:** the same appears to be true for .rvt files: 2024 = fine, 2023 = error.

I believe this issue is similar to #1303 but with a different error message. 

# ♻️ To Reproduce

1. Go to 'Get RVT Info"
2. Select a Revit Model created in Revit 2023.  See below for a sample file:

[Door-Curtain-Wall-Double-Glass.zip](https://github.com/eirannejad/pyRevit/files/14463536/Door-Curtain-Wall-Double-Glass.zip)

# ⏲️ Expected behavior
https://pyrevitlabs.notion.site/Get-Revit-Model-Information-673e586c7f7d408898f07114ae4357c1

# 🖼 Screenshots of the issue
![image](https://github.com/eirannejad/pyRevit/assets/31014723/b1d9127d-66d4-49dd-b40f-2bea5310c81b)

# 🖥️ Hardware and Software Setup
- Windows 11 Pro 23H2
- pyRevit Version v4.8.14.24016
- pyRevit Environment:

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.13.23182+2215" | Path: "C:\Users\conne\AppData\Roaming\pyRevit-Master"
==> Attachments
Unnamed-363FBF8 | Product: "24.1" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
Unnamed-363FBF8 | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
AEDANpyRevit | Type: Unknown | Repo: "" | Installed: "G:\Shared drives\AEDAN\Project Files\1 Resources\Revit\pyRevit\AEDANpyRevit.extension"
==> Default Extension Search Path
C:\Users\conne\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
G:\Shared drives\AEDAN\Project Files\1 Resources\Revit\pyRevit
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
24.1 | Version: 24.1.0.66 | Build: 20230701_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
Autodesk Revit 2023 | Version: 23.0.11.19 | Build: 20220503_1030(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
==> Running Revit Instances
PID: 3044 | 24.1 | Version: 24.1.0.66 | Build: 20230701_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2024"
==> User Environment
Microsoft Windows 10 [Version 10.0.22631]
Executing User: SV-PRECISION\conne
Active User: SV-Precision\conne
Admin Access: No
%APPDATA%: "C:\Users\conne\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.14.24016+1909.ee814ee2f686d23db8bb6ff80d8bb918ff9adc99
```

# Additional context
Thanks for the awesome work :)

**Comment by jmcouffin** [comment]
Get wip installers from https://github.com/eirannejad/pyRevit/actions/runs/8139711027
