### ISSUE TITLE
[Bug]: invalid: /posts/<int:uiapp>

### ISSUE THREAD

**Issue by al-gi** [eirannejad/pyRevit#2138]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

Get this error when i reload

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
C:\Users\104615algi>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
Unknown | Product: "24.2" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2024\pyRevit.addin"
Unknown | Product: "23.1.3" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2023\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\104615algi\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\Users\104615algi\AppData\Roaming\RevitExtensions\LearningAPI.extension
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
23.1.3 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
==> Running Revit Instances
PID: 21508 | 24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2024"
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: N13\104615algi
Active User: N13\104615algi
Admin Access: No
%APPDATA%: "C:\Users\104615algi\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.7.2 v4.8 v4.X
Installed .Net-Core Target Packs: v8.0.100 v8.0.102
pyRevit CLI v4.8.14.24016+1909.ee814ee2f686d23db8bb6ff80d8bb918ff9adc99
```

### Additional context

![image](https://github.com/eirannejad/pyRevit/assets/60464629/6a8dc61b-1da9-47dd-bdce-c16bebb6eda0)

**Comment by jmcouffin** [comment]
The routes server is not configured, this is why you are getting this error.
Either configure it or disable dev extension.

**Comment by al-gi** [comment]
Do you have a link or something that can show me how to set up routes? @jmcouffin

**Comment by jmcouffin** [comment]
LMGTFY ;p 
https://www.youtube.com/watch?v=rUCM0pJz5Zw

and a good one with google translate ;p
https://zenn.dev/redtrechlab/articles/1e80a68594676d

**Comment by jmcouffin** [comment]
https://pyrevitlabs.notion.site/pyRevit-Routes-HTTP-API-79ef6d4a77b04aca9be6f4e46ffa728e

**Comment by al-gi** [comment]
Thanks! Thank you! I was just trying to follow this tutorial https://www.youtube.com/watch?v=fpHAZoujmnU
There, they say nothing about routes. @jmcouffin

**Comment by al-gi** [comment]
I have done the same as shown in the video here https://www.youtube.com/watch?v=fpHAZoujmnU, but it won't work. Now I get this:
![image](https://github.com/eirannejad/pyRevit/assets/60464629/621e7cf8-8d95-4eb4-b26b-8183b3303ffd)
![image](https://github.com/eirannejad/pyRevit/assets/60464629/9b86642d-6f7e-4c08-90ca-cf11945c212e)

**Comment by jmcouffin** [comment]
Can you share your code?

I think you need to change the GUID of your dockable panel

**Comment by jmcouffin** [comment]
reload won't work, you need to restart Revit

**Comment by al-gi** [comment]
[Test3.extension.zip](https://github.com/eirannejad/pyRevit/files/14496790/Test3.extension.zip)
[RVT2024Env.zip](https://github.com/eirannejad/pyRevit/files/14496794/RVT2024Env.zip)

**Comment by al-gi** [comment]
It comes after i have activated  and deactivate this:
![image](https://github.com/eirannejad/pyRevit/assets/60464629/3feb6837-af90-45ac-9e8a-702933f8bff1)
If my company is interested in paying you, would it be possible for you to set it up for me via TeamViewer or something?

**Comment by jmcouffin** [comment]
I just tried it quickly and got it to work on my machine in no time.
Sure, why not jmcouffin at gmail dot com @al-gi

**Comment by al-gi** [comment]
As I understand it, the links you sent seem to involve much more advanced operations than what I need to run the extensions I sent you. Is that correct? @jmcouffin

**Comment by al-gi** [comment]
How much will you charge to help me? I have sent you an email, have you received it?
