### ISSUE TITLE
[Bug]: PyRevit installed but not loading

### ISSUE THREAD

**Issue by bhoover01** [eirannejad/pyRevit#2141]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] Issues related to tools/scripts, I tried to run them in debug mode (CTRL+click on the button) and copy over the contents of the output window
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

When opening any version of Revit an error message appears that it cannot be loaded.

![image](https://github.com/eirannejad/pyRevit/assets/162496185/fa5bb232-9f96-4637-ac85-49de75bf8900)

### ♻️ To Reproduce

Open Revit and allow add ins to load and error message may appear.

### ⏲️ Expected behavior

For the add in to load.

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.14.24016+1909" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
master | Product: "23.1.3" | Engine: DEFAULT (2711) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2022.1.4" | Engine: DEFAULT (2711) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2021.1.7" | Engine: DEFAULT (2711) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2020.2.9" | Engine: DEFAULT (2711) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2019.2.3" | Engine: DEFAULT (2711) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\grant.bechtel\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
23.1.3 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022.1.4 | Version: 22.1.40.58 | Build: 20230505_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021.1.7 | Version: 21.1.70.21 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.9 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.3 | Version: 19.2.30.41 | Build: 20210416_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
PID: 28696 | 23.1.3 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2023"
==> User Environment
Microsoft Windows 10 [Version 10.0.22631]
Executing User: HW\grant.bechtel
Active User: HW\grant.bechtel
Admin Access: No
%APPDATA%: "C:\Users\grant.bechtel\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.14.24016+1909.ee814ee2f686d23db8bb6ff80d8bb918ff9adc99
```

### Additional context

Began a few days ago, uninstalled, reinstalled, updated to newest version, ran command pyrevit attach master 2711 --installed

**Comment by sanzoghenzo** [comment]
> * [x]  I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**

Just to be sure, did you follow everything in there? have you already tried to move the `.addin` files between uninstalling and reinstalling pyRevit?

**Comment by bhoover01** [comment]
I have gotten it working, thank you for your assistance!


BRADEN HOOVER Desktop Support Specialist

HOEFER WELKER hoeferwelker.com
O 214.445.4400 | D 214.445.4332
