### ISSUE TITLE
[Bug]: Cannot Load a Custom Toolbar from a CLoud storage

### ISSUE THREAD

**Issue by DaniPeritas** [eirannejad/pyRevit#2142]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] Issues related to tools/scripts, I tried to run them in debug mode (CTRL+click on the button) and copy over the contents of the output window
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

I have a custom toolbar loaded in pyRevit in Settings>Custom Extension Directories.
The toolbar is loading fine if the path specified for the toolbar is a physical drive (in my case a server).
Now we are moving away from the server and using the Autodesk Construction Cloud service to store all our data and the Toolbar should live in there to allow everyone access.

Unfortunately re-directing the path the cloud and hitting _Save Settings and Reload_, Pyrevit sends the following error and cannot load pyrevit core anymore:
![image](https://github.com/eirannejad/pyRevit/assets/138229380/96f4d3d4-be51-4210-a30f-54806af2a37f)

If Revit is then closed and re-opened pyrevit cannot be loaded anymore:
![image](https://github.com/eirannejad/pyRevit/assets/138229380/c8af09f4-4d01-4db1-a31e-05fdf1506c09)

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.14.24016+1909" | Path: "C:\Users\DanieleGalbusera\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "24.2" | Engine: IPY277 (277) | Path: "C:\Users\DanieleGalbusera\AppData\Roaming\pyRevit-Master"
master | Product: "23.1.3" | Engine: IPY277 (277) | Path: "C:\Users\DanieleGalbusera\AppData\Roaming\pyRevit-Master"
master | Product: "2022.1.5" | Engine: IPY277 (277) | Path: "C:\Users\DanieleGalbusera\AppData\Roaming\pyRevit-Master"
master | Product: "2021.1.9" | Engine: IPY277 (277) | Path: "C:\Users\DanieleGalbusera\AppData\Roaming\pyRevit-Master"
master | Product: "2020.2.1 (New Install)" | Engine: IPY277 (277) | Path: "C:\Users\DanieleGalbusera\AppData\Roaming\pyRevit-Master"
master | Product: "2019.2 (Full Install)" | Engine: IPY277 (277) | Path: "C:\Users\DanieleGalbusera\AppData\Roaming\pyRevit-Master"
master | Product: "2017 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Users\DanieleGalbusera\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
DynamoScripts | Type: Unknown | Repo: "" | Installed: "C:\Users\DanieleGalbusera\DC\ACCDocs\Peritas Consulting P-L\Structural Drafting Library\Project Files\6.4 Revit\6.4.4 Support\2.0 Toolbar\DynamoScripts.extension"
==> Default Extension Search Path
C:\Users\DanieleGalbusera\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\Users\DanieleGalbusera\DC\ACCDocs\Peritas Consulting P-L\Structural Drafting Library\Project Files\6.4 Revit\6.4.4 Support\2.0 Toolbar
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
23.1.3 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022.1.5 | Version: 22.1.50.17 | Build: 20230915_1530(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021.1.9 | Version: 21.1.90.15 | Build: 20230907_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.1 (New Install) | Version: 20.2.12.1 | Build: 20200210_1400(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2 (Full Install) | Version: 19.2.1.1 | Build: 20190108_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2017 First Customer Ship | Version: 17.0.416.0 | Build: 20160225_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
==> Running Revit Instances
PID: 13292 | 24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2024"
==> User Environment
Microsoft Windows 10 [Version 10.0.22631]
Executing User: AzureAD\DanieleGalbusera
Active User: AzureAD\DanieleGalbusera
Admin Access: No
%APPDATA%: "C:\Users\DanieleGalbusera\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.14.24016+1909.ee814ee2f686d23db8bb6ff80d8bb918ff9adc99
```

**Comment by sanzoghenzo** [comment]
Hi @DaniPeritas,

At my company we experienced similar problems with tools I've developed to perform batch operations; the thing that usually solved the proble is to make sure that the folder in which to operate is set to "Always keep on this device".
Just right click on the extension folder and you will find that item.

The error message feels strange, it seems that there is still a pyrevit process runnin that didn't properly release that ini file. Usually a reboot will solve that problem.

Let us know if the issue persist!

**Comment by DaniPeritas** [comment]
Hi @sanzoghenzo,

We actually tried that as well and rebooted the computer.
Unfortunately, that did not solve the issue:
![image](https://github.com/eirannejad/pyRevit/assets/138229380/178fb1b7-22d3-4059-a9a6-5bace0bba294)

**Comment by sanzoghenzo** [comment]
Well, it did solve the issue of the original issue; now, as you can see near the bottom of your picture, it complains about the paths being too long.

This is a windows limitation, not pyRevit's fault.
What is the full path of your extension? You may need to put it some folder up the tree...

**Comment by DaniPeritas** [comment]
You're Perfectly Right!!

Thank you so much @sanzoghenzo, really appreciate your help!
