### ISSUE TITLE
4.4 update not registering

### ISSUE THREAD

**Issue by natethegrate1** [eirannejad/pyRevit#215]
It seems the update went fine and all the tools updated but my hash value doesn't match your latest commit that I can tell. Also I keep getting the error that RevitPythonWrapper.lib cannot be updated. This is from the info window when the "update" button is clicked. Attached are some photos and the debug mode output..
![debug2](https://user-images.githubusercontent.com/11881415/28236740-2b4da426-692e-11e7-8157-52ab77119909.png)
![debug](https://user-images.githubusercontent.com/11881415/28236742-2b51b804-692e-11e7-90ae-c0eb5b693b35.png)
![debug3](https://user-images.githubusercontent.com/11881415/28236741-2b504622-692e-11e7-979d-d168a4a5a1e7.png)
[debug.txt](https://github.com/eirannejad/pyRevit/files/1150094/debug.txt)

**Comment by eirannejad** [comment]
I looked over the log and everything looks fine except for the `RevitPythonWrapper.lib`
- You can remove `RevitPythonWrapper.lib` now from the extensions (delete its folder completely). RPW is now included in pyRevit by default (it's under `pyrevit/pyrevitlib/rpw`).
- Then upgrade using the `upgrade.bat` tool. (That's what the warning message a the end saying)
- Otherwise you can always uninstall and reinstall which should be quick

I'll leave this open so please let me know if the issue was resolved. Thanks

**Comment by eirannejad** [comment]
@natethegrate1 Is this resolved?

**Comment by natethegrate1** [comment]
I guess technically it is solved. But the upgrade.bat is not quite working I think the way it is supposed to:
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\windows\system32>cd ../../Users\administrator.HRE\AppData\Roaming\pyRevit\pyR
evit-v4\pyRevit\release

C:\Users\administrator.HRE\AppData\Roaming\pyRevit\pyRevit-v4\pyRevit\release>up
grade.bat

Unhandled Exception: LibGit2Sharp.CheckoutConflictException: 160 conflicts preve
nt checkout
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in c:\Git\LibGit2Sharp-
2\LibGit2Sharp\Core\Ensure.cs:line 154
   at LibGit2Sharp.Core.Proxy.git_checkout_tree(RepositoryHandle repo, ObjectId
treeId, GitCheckoutOpts& opts) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Core\Proxy.
cs:line 306
   at LibGit2Sharp.Repository.CheckoutTree(Tree tree, IList`1 paths, IConvertabl
eToGitCheckoutOpts opts) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Repository.cs:lin
e 951
   at LibGit2Sharp.Repository.FastForwardMerge(AnnotatedCommitHandle annotatedCo
mmit, MergeOptions options) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Repository.cs:
line 1589
   at LibGit2Sharp.Repository.Merge(AnnotatedCommitHandle[] annotatedCommits, Si
gnature merger, MergeOptions options) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Repo
sitory.cs:line 1468
   at LibGit2Sharp.Repository.MergeFetchedRefs(Signature merger, MergeOptions op
tions) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Repository.cs:line 1252
   at LibGit2Sharp.Commands.Pull(Repository repository, Signature merger, PullOp
tions options) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Commands\Pull.cs:line 38
   at pyRevitCoreUpdater.Program.Main(String[] args) in C:\Users\eirannejad\AppD
ata\Roaming\pyRevit\pyRevit-v4\pyRevit\release\pyRevitCoreUpdater\pyRevitCoreUpd
ater\Program.cs:line 13
Successfully updated pyRevit core. You can close this window now.
Press any key to continue . . .

**Comment by eirannejad** [comment]
What happens if you run as admin?

**Comment by natethegrate1** [comment]
That is running as admin. I think it's all moot anyway cause I'm running v4.4 now

**Comment by eirannejad** [comment]
well okay. Sorry I couldn't help more. :/

**Comment by natethegrate1** [comment]
No biggie! I just wanted to post it for your info. The program works and I'm writing some custom buttons!
