### ISSUE TITLE
Remove readthedocs

### ISSUE THREAD

**Issue by eirannejad** [eirannejad/pyRevit#2152]
RE https://discourse.pyrevitlabs.io/t/random-proposals-for-pyrevit-5-but-not-only-5/2691
- [x] Reroute pyrevitlabs urls
- [x] make sure direct links in the repo is pointing to pyrevitlabs
- [x] remove readthedocs mentions in notion

**Comment by jmcouffin** [comment]
I checked, No mention of the pyrevit readthedocs in the repo

**Comment by jmcouffin** [comment]
Checked and fixed readthedocs links in Notion as well
your go @eirannejad !

**Comment by eirannejad** [comment]
Ok this is done

**Comment by eirannejad** [comment]
Ok this is done. The old docs is gone
