### ISSUE TITLE
SectionBox visibility tool error

### ISSUE THREAD

**Issue by aumaco** [eirannejad/pyRevit#218]
Using the SectionBox visibility tool.

[Image](http://imgur.com/a/n4HZl)

Windows 10 64bits
Revit 2017.2

**Comment by gtalarico** [comment]
`activeview` should be `active_view` and is a property of `rpw.revit`
https://github.com/gtalarico/revitpythonwrapper/blob/master/rpw/__revit.py#L105

**Comment by eirannejad** [comment]
Yeah this was with the older version of rpw. I'll fix asap.

**Comment by eirannejad** [comment]
Resolved.
