### ISSUE TITLE
Startup Tasks ExecuteScript Exception

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#221]
Just installed pyrevit on a new computer, got this on revit start:

![image](https://user-images.githubusercontent.com/9513968/28582462-7d03b12c-7133-11e7-9afd-00c29274b734.png)

**Comment by gtalarico** [comment]
This is the line:
https://github.com/eirannejad/pyRevit/blob/master/pyrevitlib/pyrevit/loader/sessionmgr.py#L203

**Comment by eirannejad** [comment]
Resolved:
https://github.com/eirannejad/pyRevit/commit/a7d365d514998f5f23ca0dddd1864a18feb279c4

**Comment by gtalarico** [comment]
Lighting Fast!

**Comment by eirannejad** [comment]
Works? It should work.

**Comment by gtalarico** [comment]
Worked

**Comment by eirannejad** [comment]
Super
