### ISSUE TITLE
Custom Extension not being found after latest update

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#222]
As of last week, I had a working deployment routine like this:
1. Install pyrevit.
2. bat file overwrites config init to add a new location to watch 
3. New location includes `extensions.json` with private repo info (private repo secrets inserted in config init)
4. pyrevit would find the `pywework.extension` (was visible in Extension Manager)
5. A startup file in `bootstrap.extension` (used bootstrap to avoid name collision with actual extension repo folder) would auto-run and ensure `pywework.extension` was installed automatically.

As of today (tested on 2 computers), step 4 is no longer working, meaning pyrevit is not finding and adding the custom extension to its registered packages.

See screenshot below
![image](https://user-images.githubusercontent.com/9513968/28633531-1ade8966-7202-11e7-8496-37ae3ae53713.png)

I am looking through this diff set to see if I can find the cause. Maybe related to authusers?
https://github.com/eirannejad/pyRevit/compare/556ee6f588dec67e9b1e6f74b9353c23fd1d9d84...master#diff-9430720d4d8560fbac74013f91f820b4

PS: on older versions pkg manager looked like this:
![image](https://user-images.githubusercontent.com/9513968/28633620-72190670-7202-11e7-99cd-f2510729b3b8.png)

**Comment by aumaco** [comment]
I can't find the extensions in one added folder or mannualy add in the extensions.json. Maybe is related ...

**Comment by eirannejad** [comment]
Looking into this right now. Sorry guys. :/

**Comment by eirannejad** [comment]
Okay this one is not completely my bad :P 
Your extension definition files are missing `enable` key. add it right after the `builtin`:
```
"builtin": "False",
"enable": "True",
```

Enable tells pyRevit if this package should be loaded by default or not (when the user is loading this for the first time and no configuration exists yet). For example pyRevit development package is disabled by default.

This has existed for a while but wasn't required. Through the `authuser` changes I made this one a required field to make things easier. The extension still loads in pyRevit but the extension manager fails since the `enable` key does not exist and fails to show that.

Please let  me know if this works otherwise we can probably make this optional again.

**Comment by gtalarico** [comment]
thanks for checking that @eirannejad 
I will try to add the enable.

also curious if that's not redundant with the user config.
seems to me user settings (same place that stores repo access info) should determine if an extension is enabled or not

![image](https://user-images.githubusercontent.com/9513968/28675732-af317ace-72b6-11e7-8ca1-7fbf28537f55.png)

**Comment by eirannejad** [comment]
One defines if the extension should load by default meaning when user has not set any preferences for loading or not

The setting in the configuration is set by the user. 

Example:
pyRevit Development extension is Enable=False meaning that is won't load by default. But the user can load it through the extension manager and that would be set inside the config file. Disabled=False

Sent from my cell phone
Please excuse the typos

**Comment by gtalarico** [comment]
Ok got it - disabled=False means _not disabled_ which is means is  enabled :)

IMHO, I think there responsibilities are being mixed. 
Seems to me that extensions.json should hold *stateless* info (where it is, where it does, etc)
And user init defines if it's state for the current user: installed? enabled, etc.
Maybe they are actually not, but having enabled/disabled on both the extension + user configs seems like they are sharing that responsibility, but I think I know what you mean



I think npm's package.json is a good example:
https://docs.npmjs.com/files/package.json

perhaps the "enabled" key kind of means:"

To control whether pyrevit dev is lodade or not, perhaps something like this:

extensions.json: (static info about what the extensions is/does:
name, url, author, version, etc +
"is-dev-tool": "True"
or
"is-in-beta":"True"

and then on the user settings:
"load-dev-tools": True / False

**Comment by eirannejad** [comment]
Uhm. That's exactly what I said I think. Maybe it wasn't clear enough.

`enable` in json file = This tool should load by default or not. This means that if you have a dev extension or beta extension or any extension that you don't want your users to have by default you can set this to False. This way when a user installs pyRevit (without having configuration pushed to them) and loads, that extension will not load.

`disabled` in config = Means that user has gone through the Extension manager and manually disabled/enabled the extension for her use.

Does this help? Are you suggesting renaming these?

**Comment by gtalarico** [comment]
Yes, Makes sense. 

My confusion come from not understanding that enable=True doesn't represent that state of the extension, but that's is enabled or disable by default. 
Yet the disable in the in the config file represents the state.

**Comment by eirannejad** [comment]
Cool. :D Sorry about the confusion.

**Comment by gtalarico** [comment]
Just for the record, adding the enable=True key to extension.json solved the issue 
Thanks for your help!
