### ISSUE TITLE
Is it possible to install a specific version of pyRevit with the. Installer? 

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#224]

**Comment by eirannejad** [comment]
Not at the moment. Installer always installs the head master branch. But it could be added to it since it can checkout a version tag after cloning. Is there a need or this?

**Comment by gtalarico** [comment]
### Use case
1. Shipped installer to a bunch of users at work.
2. If a user gets a new laptop, or a new employee starts, they will end up with a new version, different than what's deployed.
3. I would want those new users to be able to install the same version everyone else is on.

For proper deployment management, I generally want the users to stay a few steps behind top of the tip, so that I have time to test the update, and make sure our tools are stable before sending out an update to everyone (I currently can trigger an update through our extension).

[This issue for example](https://github.com/eirannejad/pyRevit/issues/221) changed an internal function signature (expected across version changes) But now my startup script worked for all old users, but not for _new_ users. Updating the startup script would break it for old users.

Another issue is rpw. If pyrevit updates rpw, I could also end up with some users on different rpw versions than others, meaning could break scripts.

Does that make sense?

I dont' really understand how the installer work, but if it was possible to pass a version tag or commit version to it `installer.exe --'4.4.0' or 'ff0033` would be ideal.
Another alternative I guess, is to maintain the stable copies i want someplace, I have our own installer to copy those into place.

**Comment by eirannejad** [comment]
Makes sense. I'll modify to add version specific installers.
As a temporary workaround, if you're using a batch script that installs pyRevit, it could checkout a different tag after installation. (But you know that already)

Are you disabling the Update button for users so they don't update to head as well?

**Comment by eirannejad** [comment]
Resolved:

![2017-08-05_19-16-31](https://user-images.githubusercontent.com/8197916/29000022-f24f3c48-7a12-11e7-9301-89b5babb7f7c.gif)
