### ISSUE TITLE
Remove Undelay does not work on Revit 2017.2

### ISSUE THREAD

**Issue by rbaggen** [eirannejad/pyRevit#226]
Hi,

I work with the Revit 2017.2 (17.0.1128.0 20170419_0315(x64) 2017.2.1 )
Is there a way you can fix this for me?

![image](https://user-images.githubusercontent.com/14872958/29120088-1ba14f02-7d09-11e7-900d-64749ace1825.png)

**Comment by hdm-dt-fb** [comment]
yes, the underlay works different in 2017. It could now be switched off via:
```python
element.SetUnderlayRange(ElementId(-1), ElementId(-1))
```

**Comment by eirannejad** [comment]
Resolved. Thanks @hdm-dt-fb for the fix and PR

**Comment by rbaggen** [comment]
Hi,

I changed the script ..
But does not work, getting the error:



Can you see what goes wrong?


import clr
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')


from Autodesk.Revit.UI import TaskDialog
from Autodesk.Revit.DB import Transaction
from Autodesk.Revit.DB import ElementId
from Autodesk.Revit.DB import BuiltInParameter, BuiltInCategory

doc = __revit__.ActiveUIDocument.Document
uidoc = __revit__.ActiveUIDocument

selection = uidoc.Selection
selection_ids = selection.GetElementIds()

if selection_ids.Count > 0:
t = Transaction(doc, 'Batch Set Underlay to None')
t.Start()

for element_id in selection_ids:
element = doc.GetElement(element_id)
if element.Category.Id.IntegerValue == int(BuiltInCategory.OST_Views) \
and (element.CanBePrinted):
p = element.get_Parameter(BuiltInParameter.VIEW_UNDERLAY_ID)
if p is not None:
element.SetUnderlayRange(ElementId(-1), ElementId(-1))

t.Commit()
else:
TaskDialog.Show('Remove Underlay', 'Select Views to Remove Underlay')

__window__.Close()

On 09 Aug, 2017, at 03:25 PM, hdm-dt-fb <notifications@github.com> wrote:

yes, the underlay works different in 2017. It could now be switched off via:
element.SetUnderlayRange(ElementId(-1), ElementId(-1))

**Comment by hdm-dt-fb** [comment]
This does not seem to be the latest version with the rvt-version check.
If you update pyRevit you should have it. 
If that is currently not possible for you, find the current version here:

https://github.com/eirannejad/pyRevit/blob/23001c05d6d6946db4288de31c53623f9ff004ae/extensions/pyRevitTools.extension/pyRevit.tab/Drawing%20Set.panel/views.stack3/Views.pulldown/Remove%20Underlay%20From%20Selected%20Views.pushbutton/script.py

As a hint for future code snippets:<br>If you paste them, put them in between triple back ticks, then formatting gets not lost.

**Comment by eirannejad** [comment]
@hdm-dt-fb Apparently he's replied in email so markdown is not supported. I didn't know that.
Thanks for the response btw

**Comment by hdm-dt-fb** [comment]
ouh I did not know that is possible.. yep you're welcome!

**Comment by rbaggen** [comment]
Thanks Guys, sorry for replying on the email. I'll test it soon.

**Comment by eirannejad** [comment]
@rbaggen No need for the apology man. We do reply in emails all the time. We just didn't know the formatting doesn't work from emails
Thanks for reporting the issue 👍
