### ISSUE TITLE
Conflicts Prevent Checkout

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#229]
I often have this while updating both internal extensions as well as pyrevit.
I am guessing this is caused because the local working tree would cause merge conflicts on a pull.

I think in most cases, this would be resolved by doing a force pull instead.
At least in my case, that would be desirable: if am hitting update, I likely don't care about local changes.

thoughts?

This was from tyring to update core today:
![image](https://user-images.githubusercontent.com/9513968/29228014-24c9afcc-7ea6-11e7-837b-71615fadda40.png)

**Comment by eirannejad** [comment]
Resolved. updater now force checksout the current head before pulling from remote

**Comment by gtalarico** [comment]
Amazing, as always. Thankyou @eirannejad!
