### ISSUE TITLE
Enhancements to print linked model sheets

### ISSUE THREAD

**Issue by eirannejad** [eirannejad/pyRevit#230]
- [ ] Being able to select multiple models
- [ ] Fix error with nested models (overlay attachments)
- [x] Print from index should also read sheets from linked models
- [x] Re #547, revise to omit models hosted on bim360

**Comment by DesignTechnology** [comment]
Hi Eriannejad

Been using py.revit for some time, love your work. 
I have an inquiry on printing sheets from a linked model, is this option not available for BIM 360 Models?

Thanks in Advance

**Comment by eirannejad** [comment]
Thank you! Not at the moment. BIM360 models reside in the could and the forge api is required to access or download those models.

**Comment by onila1987** [comment]
The combined option to print link revit models is not working. Single print comes out in different directions and requires rotation. You think we can add the option to print sheet index from link models?
