### ISSUE TITLE
Install for All Users

### ISSUE THREAD

**Issue by DavePlumb** [eirannejad/pyRevit#234]
Is there an install flag to install pyRevit for All Users?
At the moment, I'm installing to C:\ProgramData\pyRevit and the copying the .addIn to the Revit Addins folder.
Here's a snippet from the batch file I'm using (which is run as admin)

ECHO pyRevit
\\bwbr.com\echelon\software\Autodesk2018\RevitAddins\Installs\pyRevitSetup-v4.exe /SILENT /DIR=C:\ProgramData\pyRevit-v4
echo %date% %time% %COMPUTERNAME% %ERRORLEVEL% pyRevit >> %LOGFILE%
REM Make it avaiable for All Users
Copy \\bwbr.com\echelon\software\Autodesk2018\RevitAddins\Installs\pyRevit.addin C:\ProgramData\Autodesk\Revit\Addins\2018

However, when I do this, I get an error when I click on the "Settings" icon. Couldn't copy the text of that, so here's a screen shot.
![pyrevit](https://user-images.githubusercontent.com/18071127/30616545-29bc219c-9d58-11e7-9435-c99451b8d66e.JPG)

I'd prefer to figure out what I'm doing wrong, but if there's a place I can copy the pyRevit_config.ini file so it applies to all users, I could live with that.
I'm installing as admin, so I do not know the eventual user's AppData folder location.

Thanks in Advance

**Comment by eirannejad** [comment]
See these posts:
http://eirannejad.github.io/pyRevit/pyrevit/update/2017/07/04/pyrevitfourfour.html
http://eirannejad.github.io/pyRevit/pyrevit/update/2017/08/05/installerupdate.html

**Comment by Astra-arch** [comment]
Hi. I didn't get an "installation type" window (only instalation folder) during installation 4.7 version to Revit 2019.2 and got that error message (screenshot). Tried several times Uninstall/install. I need to install it for all users because of the current user name is in Cyrillic and it wouldn't work. 
I also tried manual installation using gitkrakken but there are no .bat files in the "release" folder
Any help?
![pr_loader](https://user-images.githubusercontent.com/33401629/53201131-4aa46d80-3634-11e9-88e0-b0ecaf73da42.jpg)

**Comment by eirannejad** [comment]
https://eirannejad.github.io/pyRevit/deploy/

**Comment by Astra-arch** [comment]
I'm a single user and oner and admin, I have no coding skills, and just want to use pyrevit. As i mentioned earlier using installer I got that error message.  I want to install pyrevit to "program data" folder not to "User/appdata"
How to fix that?

**Comment by fgmarchitects** [comment]
None of the links on this page are found for me.  I have the exact same issue.  I need to install pyrevit as the admin on 50 computers and have it available to anyone who signs into those computers (windows 10 pro).  Any advice/instructions would be greatly appreciated.

**Comment by eirannejad** [comment]
[See the new wiki](https://www.notion.so/pyrevitlabs/pyRevit-For-Teams-ddc6c312d6f6488691eed2ec7704fd97)

**Comment by fgmarchitects** [comment]
Thank you.  I was able to follow that and get it working.

Mike Caraker

FGM ARCHITECTS

D 618.624.3371
M 618.974.8682
________________________________
