### ISSUE TITLE
Linkify with Zoom

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#237]
I'm finding the Linkify tool really useful for finding the views of elements.  
Can there be a zoom to element option or a center element on screen?  Maybe this has already been added in newer releases.

I'm thinking maybe another adaptation called LinkifyZoom? 
LinkifyZoom(elid, zoomratio)

Where zoom ratio would be how far zoomed out the user wants?\
For example LinkifyZoome(elid, 2) would create a bounding box 200% larger than the element.  What do you think?

I've used uidoc.ShowElements(elid) in the past (it does a good job centering on the element, but doesn't have the zoom extents built in.)

Just dreaming a little, feel free to push back.  Thanks!

**Comment by eirannejad** [comment]
Definitely a good idea. I'm working on the pyRevit core changes currently so I can spend time on this right now but will keep it open for when I come back to revising tools for the new core. Feel free to tackle this before then though ;)

**Comment by eirannejad** [comment]
Resolved. Coming up in next version.

**Comment by eirannejad** [comment]
v4.5rc is available now:
http://eirannejad.github.io/pyRevit/pyrevit/update/2017/12/02/45rc.html
