### ISSUE TITLE
Unicode in Username causes loader to fail

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#245]
![image](https://user-images.githubusercontent.com/9513968/31956667-1b4eb250-b8ba-11e7-9ffa-ae3b103d32d6.png)

Posting this for a colleague

**Comment by eirannejad** [comment]
Is this really a pyRevit issue? Because pyRevit is not even loaded. This seems to be an issue with Revit not being able to resolve the unicode character in the file path. See the ugly replacement character in the prompt window.

I'll do some tests also.

**Comment by eirannejad** [comment]
Investigated. Seems like I need to write the addin manifest file in UTF-8 for Revit to be able to find the folder. Need to check to see how I can do this with the batch installer...

**Comment by eirannejad** [comment]
Resolved. Update and run the `%appdata%\...\pyRevit\release\install_addin.bat` to rewrite the manifest file.

**Comment by eirannejad** [comment]
@gtalarico Did that fix the issue?

**Comment by gtalarico** [comment]
Thanks for the fix @eirannejad 
Haven't been able to check as I need to manually replace the addin file or add the UTF encoding char.
(as we discussed the other day, I am trying to keep all users in the same version, so I will avoid updating the full pyrevit is )

**Comment by gtalarico** [comment]
ps: Feel free to close if you think the fix works, I can re-open if it doesnt't

**Comment by eirannejad** [comment]
I'll close for now but will add this to the test list for the installer.
