### ISSUE TITLE
The degree symbol °

### ISSUE THREAD

**Issue by frankhochban** [eirannejad/pyRevit#246]
Hi, 
I just started to work with your project. I see great potential here.
I was making a label for a windows form for data input for revit and I used the ALT+248 for the creation of the degree symbol in the .text property of the control.
self.label.text = '90 °'
With this addition the pushbutton to call the script stopped responding.  No crash or anything just an empty click.
I copied the code into the Interactive Python Shell in Revit and it runs and generates the degree sign in the label.
A very strange condition.  
Also the issue persists if the line in the script is commented out as well.  But delete the ° and all is well.

I figured I would let you know, and help any others that may come across this condition.
Cheers

**Comment by eirannejad** [comment]
Try adding:
`# -*- coding: utf-8 -*-`
as the first line in your script file.

**Comment by frankhochban** [comment]
Yes, adding that line of code fixes the issue.
I am using Notepad++ and encoding was set as UTF-8 format.

Thank you for your prompt reply
