### ISSUE TITLE
Tiny Request

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#255]
I think it's already possible, but I couldn't find the code.  I've seen color in the chart.js stuff, but can the pyrevit console printout have colors for different text? I'm trying to use basic RGB values for a legend.  The colors will vary every time the script is run based on HSV or RGB values.  All I have seen is 'red' where scripts have warnings or alerts.  Am I missing something?

**Comment by eirannejad** [comment]
You mean this? Setting color and fill on a data set?

``` python
set_b = chart.data.new_dataset('set_b')
set_b.data = [2, 29, 5, 5, 2, 3, 10]
set_b.set_color(0xFF, 0xCE, 0x56, 0.8)
set_b.fill = False
```

**Comment by eirannejad** [comment]
Wait you mean actual text output! Yes
``` python
# use output object to add a CSS style to browser DOM
style = """
.legendblue {
   color: Blue;
}

.legendred {
   color: Red;
}

.legendgreen {
   color: Green;
}
"""

output.add_style(style)

output.print_html('<div class="legendblue">Legend Text</div>')
output.print_html('<div class="legendred">Legend Red</div>')
output.print_html('<div class="legendgreen">Legend Green</div>')

```

![colouredoutput](https://user-images.githubusercontent.com/8197916/33295676-dc28c830-d38b-11e7-8605-aca8ef27d427.png)

**Comment by thazell** [comment]
Yes, that's what I am looking for.  I'm working on a color by parameter script and I want a legend for the display.  Here is my current output, which doesn't say much to the user.
![image](https://user-images.githubusercontent.com/14113080/33324707-5fbfb7f2-d41e-11e7-8445-bba0967aeaf1.png)
![image](https://user-images.githubusercontent.com/14113080/33324716-65dc4aec-d41e-11e7-9eab-1eb2748d07e6.png)

**Comment by eirannejad** [comment]
Awesome. I’m glad it helped.

**Comment by thazell** [comment]
Thanks a bunch for incorporating html into the output window.  Here's what my legend looks like now.  
![image](https://user-images.githubusercontent.com/14113080/33327167-da251ffe-d424-11e7-8e78-0c77f5c1189a.png)

Here's what I ended up doing based on your advice:
def printhtmlwithcolor(text,colorstring):
    this_script.output.print_html('<h1 style="background-color:' + colorstring + ';">' + text + '</h1>')

**Comment by eirannejad** [comment]
Looks good. There are also `.inject_script()` and `.inject_to_head()` methods available on the output object for inserting javascript and head elements respectively. Just in case.

pyRevit v4.5 allows for full output customization with a CSS file as well
