### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by sakernan** [eirannejad/pyRevit#256]
ERROR: [pyrevit.versionmgr] Can not create repo from directory: G:/pyRevit-4.5-rc | Path 'G:/pyRevit-4.5-rc' doesn't point at a valid Git repository or workdir.
ERROR: [pyrevit.versionmgr] Can not get pyRevit patch number. | 'NoneType' object has no attribute 'last_commit_hash'
ERROR: [pyrevit.versionmgr] Can not create repo from directory: G:/pyRevit-4.5-rc | Path 'G:/pyRevit-4.5-rc' doesn't point at a valid Git repository or workdir.
ERROR: [pyrevit.versionmgr] Can not get pyRevit patch number. | 'NoneType' object has no attribute 'last_commit_hash'
ERROR: [pyrevit.versionmgr] Can not create repo from directory: G:/pyRevit-4.5-rc | Path 'G:/pyRevit-4.5-rc' doesn't point at a valid Git repository or workdir.
ERROR: [pyrevit.versionmgr] Can not get pyRevit patch number. | 'NoneType' object has no attribute 'last_commit_hash'
ERROR: [pyrevit.versionmgr] Can not create repo from directory: G:/pyRevit-4.5-rc | Path 'G:/pyRevit-4.5-rc' doesn't point at a valid Git repository or workdir.
ERROR: [pyrevit.versionmgr] Can not get pyRevit patch number. | 'NoneType' object has no attribute 'last_commit_hash'
ERROR: [pyrevit.versionmgr] Can not create repo from directory: G:/pyRevit-4.5-rc | Path 'G:/pyRevit-4.5-rc' doesn't point at a valid Git repository or workdir.
ERROR: [pyrevit.versionmgr] Can not get pyRevit patch number. | 'NoneType' object has no attribute 'last_commit_hash'

**Comment by eirannejad** [comment]
Did you install using the 4.5-rc installer?

**Comment by eirannejad** [comment]
@sakernan Any updates on this? did this get resolved?

**Comment by sakernan** [comment]
I'm in china,So i can't use the installer~I download the source code to install, then the error appers.

**Comment by eirannejad** [comment]
@sakernan Watch this: https://www.youtube.com/watch?v=hrlkPRoUfXc&t=2s
You need to clone the pyRevit git repository on your machine. I'm explaining the process in this video.

**Comment by sakernan** [comment]
@eirannejad THX
