### ISSUE TITLE
Initializing error

### ISSUE THREAD

**Issue by aumaco** [eirannejad/pyRevit#257]
After install the last update 

![01](https://user-images.githubusercontent.com/22150163/33554778-39fa8e86-d8e5-11e7-801c-28bfdaf4fe1c.png)
![02](https://user-images.githubusercontent.com/22150163/33554779-3a1c7f14-d8e5-11e7-8a09-017c2a8f91fd.png)

**Comment by eirannejad** [comment]
Did you install using the new installer? Would you clean the %appdata%/pyRevit/2018 cache files and restart Revit 2018 and see if it works?

**Comment by jonszcz** [comment]
I'm having the same issue. Cleaning out the folder and restarting Revit didn't seem to help either. But it did leave a message in the log file that says, 
`2017-12-04 14:45:00,498 CRITICAL: [pyrevit.loader.basetypes] Can not find required reference assembly: System.Web`. 
Not sure if that's helpful though.

**Comment by aumaco** [comment]
Using the link from the last post.
[https://github.com/eirannejad/pyRevit/releases/download/v4.5-rc/pyRevitSetup-v45rc.exe](url)

I had the same problem when installing it on another computer.

**Comment by eirannejad** [comment]
Okay added the `System.Web` dll in there. Install again and test.

@jonszcz Thanks a lot for looking into the logs. I'll add better reporting to the runtime compiler.

**Comment by jonszcz** [comment]
@eirannejad That did the trick for me! Thanks so much for the help.

**Comment by eirannejad** [comment]
@jonszcz You're awesome. Thanks immensely for looking in to the log.

**A little story on why there is not better error reporting on the core C# compiler:** pyRevit compiles it's own C# core code on the fly. The code for the output window is inside that C# package. Hence when an error occurs with that compilation, there is no way it can report anything other than the giant message box in Revit and the backend log files.

**Comment by eirannejad** [comment]
@aumaco Augusto is the issue fixed for you as well?

**Comment by aumaco** [comment]
@eirannejad Yes, thank you!
