### ISSUE TITLE
revit could nor create new tab for custom revit extension

### ISSUE THREAD

**Issue by wta12** [eirannejad/pyRevit#258]
I tried to create new extension with folder tree as (add .extension folder) : 
`..\PyRevit_CustomExt\Custom00.extension\Test.tab\TestPanel.panel\Custom00.pushbutton`
But i don't see Test.tab created  after reload. it works if i replace to one of script in Pyrevit Folder.

**Comment by eirannejad** [comment]
Would you check the pyRevit configuration file under `%appdata%\pyRevit\pyRevit_config.ini`
Share the `userextensions` key value here please.

**Comment by wta12** [comment]
[core]
checkupdates = False
verbose = True
debug = False
filelogging = True
startuplogtimeout = 10
userextensions = ['D:\....\\PyRevit_CustomExt\\Custom00.extension']

**Comment by eirannejad** [comment]
What's the `..` in your path? Provide full path not relative and test again please. Also when adding a path in a python string you have to escape the separators as in `C:\\path\\to\\file`.

**Comment by wta12** [comment]
sorry, the comment dialog auto reduce a "\\"
`userextensions = ['D:\\Ng_khanh\\Script_env\\Revit_2017\\PyRevit_CustomExt\\Custom00.extension']`

**Comment by eirannejad** [comment]
Should be:
`userextensions = ['D:\\Ng_khanh\\Script_env\\Revit_2017\\PyRevit_CustomExt']`
pyRevit will find the `.extension` folders. This is because this way  you can have multiple extensions under the same parent folder and just add that to config.
