### ISSUE TITLE
Question: PyRevit Script reload

### ISSUE THREAD

**Issue by wta12** [eirannejad/pyRevit#260]
I wonder should i use "Reload" button at PyRevit Tab or just re-click extension push button to check how script works after modifying a script ?
Have any example for unit test for pyRevit Script ? i face with a lot Revit crashes even using try/except InvalidOperationException stack
Thank

**Comment by eirannejad** [comment]
You really shouldn't be using reload. pyRevit generally reloads itself when it needs to.
All the pyRevit buttons in the user interface know the location of their scripts. Every time you click on a button, it runs the current version of the script. There is no need to reload pyRevit.
