### ISSUE TITLE
Trying to use 4.5rc, but isn't loading into revit

### ISSUE THREAD

**Issue by joseph-kirkpatrick** [eirannejad/pyRevit#261]
I downloaded from the blog, everything went fine. When I open up revit it doesnt show or look different. For some reason the right files haven't loaded into the right place maybe? I'm not sure. As you can see i have a number of autodesk applications for work, I dont know if that would effect the instal?

HELPP
I don' have addons, I have addins? I don't know if that makes a difference or not?

![image](https://user-images.githubusercontent.com/32959656/33633092-a9c7f43a-d9dd-11e7-8c9a-31c6cf311750.png)

![image](https://user-images.githubusercontent.com/32959656/33632945-333a31c0-d9dd-11e7-89bb-71c73d49b762.png)

**Comment by eirannejad** [comment]
Not the correct folders. Go to `%appdata%/Autodesk/Revit/Addins`

Paste the contents of `pyRevit.addin` file here please.

**Comment by joseph-kirkpatrick** [comment]
Found the right folder, however i have years 2013-2018 listed, with the below pic, however its not loading the 4.5rc.


![image](https://user-images.githubusercontent.com/32959656/33633436-d6be52e4-d9de-11e7-9b85-c6ea47e61bfe.png)

**Comment by eirannejad** [comment]
Open the file in notepad and copy the contents here please.

**Comment by joseph-kirkpatrick** [comment]
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<RevitAddIns>
  <AddIn Type="Application">
    <Name>PyRevitLoader</Name>
    <Assembly>C:\pyRevitv4.5\pyRevit\pyrevitlib\pyrevit\loader\addin\PyRevitLoader.dll</Assembly>
    <AddInId>B39107C3-A1D7-47F4-A5A1-532DDF6EDB5D</AddInId>
    <FullClassName>PyRevitLoader.PyRevitLoaderApplication</FullClassName>
  <VendorId>eirannejad</VendorId>
  </AddIn>
</RevitAddIns>

**Comment by joseph-kirkpatrick** [comment]
When loading R18 the 4.5rc should be the loading one, yet this is what i'm seeing.

![image](https://user-images.githubusercontent.com/32959656/33633748-e3a313cc-d9df-11e7-9e9c-40160c84181a.png)

**Comment by joseph-kirkpatrick** [comment]
Just tried adding that into assembly, and now I got this:

![image](https://user-images.githubusercontent.com/32959656/33633922-777b6a18-d9e0-11e7-85b6-fd28dca90353.png)

R18 addin code

<?xml version="1.0" encoding="utf-8" standalone="no"?>
<RevitAddIns>
  <AddIn Type="Application">
    <Name>PyRevitLoader</Name>
    <Assembly>C:\pyRevitv4.5\pyRevit\pyrevitlib\pyrevit\loader\addin\277\PyRevitLoader.dll</Assembly>
    <AddInId>B39107C3-A1D7-47F4-A5A1-532DDF6EDB5D</AddInId>
    <FullClassName>PyRevitLoader.PyRevitLoaderApplication</FullClassName>
  <VendorId>eirannejad</VendorId>
  </AddIn>
</RevitAddIns>

**Comment by eirannejad** [comment]
@joseph-kirkpatrick I have no idea where you have actually installed pyRevit. So please check the installed location. The `pyRevitLoader.dll` is under `pyrevit\loader\addin\277\` path at wherever you have installed pyRevit. Make sure the path in the addin file points to that location.

**Comment by joseph-kirkpatrick** [comment]
I reinstalled it, but it didn't give me a location to install it, in programs and features I can see the application installed but that's it.

I downloaded the 4.5rc files as well, i've tried replacing the old with the new, but nothing. I keep getting the .dll error

**Comment by eirannejad** [comment]
Okay. Go to Programs and Features and make sure every pyRevit is uninstalled first. If the installer doesn't ask you for a path, it means that it is installing over the existing one. Reinstall after you have removed all existing pyRevits

I'm looking into the installer to see if I have messed up anything on my side.

**Comment by joseph-kirkpatrick** [comment]
So I had to get my co-worker to show me where he installed the files....

%appdata%/Autodesk/Revit/Addins
%appdata%/pyRevit


After hunting around it seems that when it installed, it did it in the 2nd location. Pretty sure thats the cause of the error. I just need to know which goes where.

**Comment by eirannejad** [comment]
Okay I fixed the installer to always ask for installation path whether pyRevit is installed or not. Download the installer again and use this one.

**Comment by joseph-kirkpatrick** [comment]
Shall do, unfortunately I don't have admin privlidges yet. So i'll now have to wait until tomorrow. I'll keep you posted! Thank you for being patient with me.

**Comment by eirannejad** [comment]
Absolutely Boss. Sorry about the installer confusion. I'm still learning as well. Keep me posted.

**Comment by joseph-kirkpatrick** [comment]
I don't know what you did to fix it, but that did it!!! Awesome job!

**Comment by eirannejad** [comment]
Perfect!
