### ISSUE TITLE
Checking internet connection through proxy

### ISSUE THREAD

**Issue by melnikovalex** [eirannejad/pyRevit#263]
Hello

In case if I'm working through proxy pyRevit updating fails with warning: **No internet access detected. Skipping update.**

I've found a place where it stucks. In `check_internet_connection` in a row `client = WebRequest.Create(url_to_open)` python throws an exception:
`The remote server returned an error: (407) Proxy Authentication Required.`

With my python and proxy experience it would look normal if not one thing. If I just skip internet checking, e.g. with replacing `can_update` function content to:
```
def can_access(url_to_open):
    return True
```
it will updates pyRevit and all installed extensions perfectly without any errors.

In addition, I tried to go back to urllib2 internet checking and it helped also.

What do you think, could it be fixed or it's a python+proxy issue?

Thank you

**Comment by eirannejad** [comment]
Awesome feedback. I had never tested this before. I'll add an exception check in there to return true if proxy is required or add proxy authentication info added in the pyRevit settings.

**Comment by eirannejad** [comment]
Resolved for v4.5 full. pyRevit internet connection checker now follows the default system proxy settings.

![2017-12-13 10_57_00-local area network lan settings](https://user-images.githubusercontent.com/8197916/33956808-93c3c048-dff4-11e7-8d29-2b93cf7eebc5.png)
