### ISSUE TITLE
pyRevit startup console errors

### ISSUE THREAD

**Issue by Stevenlimo** [eirannejad/pyRevit#269]
Hi Ehsan,

The following two error messages keep repeating in the pyRevit startup console windows, but they don't seem to affect the running of the pyRevit scripts. How can I resolve them: 

**ERROR: [pyrevit.versionmgr] Can not create repo from directory: C:/Users/stevenlimo/pyRevit-4.5 | Path 'C:/Users/stevenlimo/pyRevit-4.5' doesn't point at a valid Git repository or workdir.**

**ERROR: [pyrevit.versionmgr] Can not get pyRevit patch number. | 'NoneType' object has no attribute 'last_commit_hash'**

Thanks and Best Regards
Steven

**Comment by eirannejad** [comment]
How did you install pyRevit? using the provided installer?

**Comment by Stevenlimo** [comment]
The binary installer didn't work. So I installed it according to your Manual Installation guideline below: 
http://eirannejad.github.io/pyRevit/installation/

I downloaded it and clicked the install_addin.bat file. pyRevit is working fine with these startup errors, but it would be great if you can show me a way to resolve them manually.

pyRevit is by far the best addin. Thank you very much for sharing it with us. Six Stars!

**Comment by eirannejad** [comment]
Thanks for the kind words.
Okay so to get the git repository correctly on your machine, you need to `clone` the repo.
- Install git tool from https://git-scm.com/download/win
- Now you should have the git command accessible in windows command prompt.
- Then open a terminal, change directory to the location that you want to pyRevit to be cloned into
- then run `git clone https://github.com/eirannejad/pyRevit.git`
- When done, run the `release/install_addin.bat` to setup the manifest files for Revit

Watch video below for more info:
https://www.youtube.com/watch?v=hrlkPRoUfXc&index=2&list=PLc_1PNcpnV56sIy3rqeynN-wqZG6nMCur

**Comment by Stevenlimo** [comment]
Thank you man, it works!
