### ISSUE TITLE
Match - not wroking - IronPython Traceback

### ISSUE THREAD

**Issue by schlueter-de** [eirannejad/pyRevit#270]
Hi,

if i try to use the match tool a window pops up with a ironpython traceback text. 

nothing happens until i pick a line i want co match. 

> IronPython` Traceback:
> Traceback (most recent call last):
>  File "C:\ProgramData\pyRevit\pyRevit-v45\pyRevit\extensions\pyRevitTools.extension\pyRevit.tab\Modify.panel\Match.pushbutton\script.py", line 128, in 
>  File "C:\ProgramData\pyRevit\pyRevit-v45\pyRevit\extensions\pyRevitTools.extension\pyRevit.tab\Modify.panel\Match.pushbutton\script.py", line 89, in get_source_style
>  File "C:\ProgramData\pyRevit\pyRevit-v45\pyRevit\extensions\pyRevitTools.extension\pyRevit.tab\Modify.panel\Match.pushbutton\script.py", line 38, in setup_style_per_config
>  File "C:\ProgramData\pyRevit\pyRevit-v45\pyRevit\pyrevitlib\pyrevit\coreutils\configparser.py", line 46, in __getattr__
> AttributeError: Parameter does not exist in config file: halftone
> 
> 
> Script Executor Traceback:
> IronPython.Runtime.Exceptions.AttributeErrorException: Parameter does not exist in config file: halftone
>  bei Microsoft.Scripting.Runtime.LightExceptions.ThrowException(LightException lightEx)
>  bei Microsoft.Scripting.Runtime.LightExceptions.CheckAndThrow(Object value)
>  bei Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
>  bei Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
>  bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  bei Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
>  bei IronPython.Runtime.Method.MethodBinding`1.SelfTarget(CallSite site, CodeContext context, Object target, T0 arg0)
>  bei System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
>  bei IronPython.Runtime.PythonContext.Call(CodeContext context, Object func, Object arg0)
>  bei IronPython.Runtime.Types.GetMemberDelegates.SlotDict(CallSite site, Object self, CodeContext context)
>  bei System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
>  bei Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
>  bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  bei Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
>  bei System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
>  bei Microsoft.Scripting.Interpreter.DynamicInstruction`5.Run(InterpretedFrame frame)
>  bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  bei Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
>  bei System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
>  bei Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
>  bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  bei Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
>  bei IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
>  bei Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
>  bei PyRevitBaseClasses.ScriptExecutor.ExecuteScript(PyRevitCommandRuntime& pyrvtCmd)

My setup:
Windows 10 version 1703 (x64)
Revit 2017 Build 17.0.416.0 20160225_1515(x64) (German)

It looks different then in your youtube video. See screenshot if i click on "Match".
https://imgur.com/a/eTVze

Am i doing it wrong or is this some failur?

Thanks for help.

**Comment by eirannejad** [comment]
Hum no I think you're fine. It might have something to do with its configuration. Try shift+clicking on the tool to run its config window and save. Then the tool should be running fine.

However I don't understand why the orange prompt at the top of the screen is offset from the side. Are you running Revit inside a virtual machine or VDI client?

**Comment by schlueter-de** [comment]
Thanks for the quick reply. Shift+clicking and then saving did the job. Thanks. 

No we don't use a VDI or any other virtual machine but i figured out that the offset is related to a telefon UI. The UI is dockt on my left side of the screen and if i undock it everything looks perfect. Did a little video for better understanding.
https://imgur.com/a/0uNT3

Why don't you use the revit commandline?

**Comment by eirannejad** [comment]
Huh very interesting! So the telefon ui messes up the Revit window coordinates apparently. Good to know. Thanks for reporting this and the video.

Revit status bar is really hard to see for most people. I wanted something more prominent and flashy

I'll fix the match tool config issue.

**Comment by benchie1** [comment]
Good day sir, I have the same issue and also try to "Shift+Clicking". But still crashed. 
![Crashed PyRevit](https://github.com/eirannejad/pyRevit/assets/140126073/e80b28bf-4b0e-422c-a100-ce572d78bdf9)
