### ISSUE TITLE
Extension not appearning inside Extension Manager

### ISSUE THREAD

**Issue by SpencerMAQ** [eirannejad/pyRevit#271]
Hi Ehsan,

I've already finished all of your tutorials on youtube and this is one of the best extensions I've seen in revit so far. Props to the elegant design and code! :)

I have a minor issue. I've already followed the instructions in editing the JSON file so that the extension would appear inside the manager but it won't appear.

Here's my folder structure so far (https://github.com/SpencerMAQ/pyRevitSpencer). I've already tried it on two computers and it won't work.
![image](https://user-images.githubusercontent.com/25006084/34484177-ff0776ec-effd-11e7-9354-051c23d5a5f1.png)

**Comment by eirannejad** [comment]
You panel bundle needs to be be inside an `.extension` bundle. The root folder should contain:
```
corelibrary.lib
spencerCore.extension
extension.json
```
`extension.json` needs to sit beside the ui extension and lib extension bundles. Look at pyRevit/extensions folder for an example.
