### ISSUE TITLE
ImportError: No module named revitutils

### ISSUE THREAD

**Issue by darkstonevn** [eirannejad/pyRevit#275]
Hello,
When I ran the 3d Rotate in pyRevitMep, it showed up ImportError: No module named revitutils. 
Same problem with other extensions in pyRevitMep, it showed up ImportError: No module named scriptutils.userinput (scriptutils).
![image](https://user-images.githubusercontent.com/35190258/34708140-df98420a-f543-11e7-8012-a013eaf45b4c.png)
I'm using Revit 2017.2 - student version, Windows 10
Please help me with problem.
 Thanks alot

**Comment by eirannejad** [comment]
pyRevitMEP master branch has not updated for v4.5 yet. Please checkout the `release/v4.5-beta` branch from the repo: https://github.com/CyrilWaechter/pyRevitMEP

I'll add it back to the pyRevit v4.5 extensions as soon as its updated.

**Comment by Avinashhv** [comment]
Hi Ehsan,

I am new to pyrevit and I am going through some of your tutorial on creating custom tab. I have created a custom Tab called "HVAC Tool" and have copied the transition push buttion from pyRevitMEP tab. New transition in "HVAC Tool" is coming up with below importer error
![image](https://user-images.githubusercontent.com/51851499/186038090-ea3b8009-7945-4b0b-8500-28436629d5d9.png) 
 
"ImportError: No module named pyrevitmep.meputils"

![image](https://user-images.githubusercontent.com/51851499/186038308-9badbca2-eb71-469f-9e50-bcbb72d65547.png)

"CreateSectionFrom" is working fine.  I am running revit 2020 and pyRevit 4.8.8

![image](https://user-images.githubusercontent.com/51851499/186038470-4819894d-99b5-4a1d-81bf-7f0e030b7c88.png).

My initial goal is to consolidate regularly used tools into one tab and then in the future I would like to edit the Transition scrip so it can draw transitions between duct fittings and duct accessories. Any help would be much appreciated.

Thanks in advance
