### ISSUE TITLE
output.set_title() exception

### ISSUE THREAD

**Issue by melnikovalex** [eirannejad/pyRevit#276]
Hello Ehsan,

When I try to set output window title it returns an exception. In pyRevit v4.4 it worked correctly, the issue started from v4.5

```
File "C:\Users\Aleksey.Melnikov\AppData\Roaming\pyRevit\pyRevit-v45\pyRevit\pyrevitlib\pyrevit\output\__init__.py", line 173, in set_title
AttributeError: 'ScriptOutput' object has no attribute 'Text'
```

Thank you!

**Comment by eirannejad** [comment]
Just pushed a hotfix. Update and it should be good.
