### ISSUE TITLE
Slow load on 4.5

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#278]
Just updated to 4.5, load times are a bit out of control.

1. First load after a clean install took 770 seconds or nearly *13 minutes* (first revit boot after uninstalling pyrevit and installing new 4.5) - this includes our custom extensions

2. Second boot took slightly longer at 927 seconds or about *15 minutes*

3. For the 3rd test, I disabled our custom extensions. This lowered the boot time to 150seconds or *2.5 minutes* - a significant improvement, but that also means all of our tools are gone, and still a long time to wait for every revit start up.

Note these are all fresh loads and not reloads

@eirannejad Let me know if you have any steps I could go through to help find the cause or to profile the loading process.

### 99.9% of the loading time is on this line
(After this line clears it only takes another 1-2 seconds)
![image](https://user-images.githubusercontent.com/9513968/34885689-d01a7288-f78e-11e7-9071-c32617606031.png)

### First Load
![image](https://user-images.githubusercontent.com/9513968/34885660-b6045b3e-f78e-11e7-9020-d1e11288e6fe.png)

### Second Load
![image](https://user-images.githubusercontent.com/9513968/34886564-5ffa8ecc-f791-11e7-8d6c-76ca46721cb6.png)

### Third load, no custom extensions
![image](https://user-images.githubusercontent.com/9513968/34888705-45188de0-f799-11e7-896a-828fd14a86c2.png)

**Comment by eirannejad** [comment]
@gtalarico  on third load, why is the `userextensions` missing from config file? Would you please confirm if it's there an pyRevit is failing to read? It should be under `[core]` group.

**Comment by gtalarico** [comment]
@eirannejad fixed `userextension`, load time went down to 70 seconds.
What load times do you typically get?

![image](https://user-images.githubusercontent.com/9513968/34893135-eeb11524-f7a9-11e7-804b-f49390b63c5c.png)

**Comment by eirannejad** [comment]
@gtalarico worked hard on identifying the reason being the slow load and it was determined that it's the pyrevit file logger that is slowing down the load when the logger path is set to a network location. This issue persists even if the usage logging method is set to off.

pyrevit logger needs to be corrected so when the usage logging method is set to off, the file logger is not created/set with path.

**Comment by gtalarico** [comment]
Thanks for noting the solution here

**Comment by gtalarico** [comment]
Ps: is there a way to detect if a folder is on a network or mapped network drive? 
Could be useful for other in the future to have a warning to make performance troubleshooting easier

**Comment by eirannejad** [comment]
See `dletter_to_unc` and `unc_to_dletter` in `pyrevit.coreutils` init.

**Comment by eirannejad** [comment]
@gtalarico Would you please checkout `hotfix/issue278` and test? I made some modifications but it's best to test under your config since it's easier to see the slow load. On my machine the network logging doesn't really affect load time.

**Comment by gtalarico** [comment]
seems to be working here

![image](https://user-images.githubusercontent.com/9513968/35231709-743c65d0-ff67-11e7-8fff-68f371fa7260.png)

**Comment by eirannejad** [comment]
You’re awesome. Thank you Sir! I’ll merge soon.

**Comment by eirannejad** [comment]
Merged and closed
