### ISSUE TITLE
duplicate selected views

### ISSUE THREAD

**Issue by chiaoweiyu** [eirannejad/pyRevit#280]
Hi,

I'm trying to duplicate selected views, however, after I selected few views in the project browser, the icon of views wasn't able to click. I also tried to click on the icon first, then it didn't let me to select views in browser. 

Please advise :) Thank you!
![views](https://user-images.githubusercontent.com/35470561/34963509-c95bb95e-f9fd-11e7-9396-9be32918dd97.JPG)

**Comment by cridder** [comment]
i don't know why it wouldn't work.  but i recommend updating pyrevit to the new version as it works there.

**Comment by chiaoweiyu** [comment]
Hi @cridder  I have tried updating it. Not sure why would this happen, does that happen on you too?

**Comment by cridder** [comment]
you will probably have to do a complete uninstall as if you have a old version it won't upgrade.  it is covered here back in july or august.  http://eirannejad.github.io/pyRevit/

**Comment by chiaoweiyu** [comment]
Will do, thank you Chris

**Comment by chiaoweiyu** [comment]
@cridder  I uninstall and reinstall pyRevit which does the work! Thanks Chris, it's so helpful! It saves me up to 3 hours of duplicating the views

**Comment by eirannejad** [comment]
@cridder @chiaoweiyu 
Thank you so much @cridder  for the support 👍 

Closing this now.
