### ISSUE TITLE
Can not create repo from directory after manual install

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#281]
Ehsan, Since we are having issues with the installer for our firm I went ahead with the manual install by downloading the zip file and adding the .addin file.  We just rolled everything into V4.4  which I'm hoping to make all the necessary updates so we can move to 4.5 so if this issue has been resolved let me know, but since I didn't acutally use the git I'm getting the following error.  What can I do about it?

![image](https://user-images.githubusercontent.com/14113080/35112738-eecaef74-fc4c-11e7-94fa-d66df1b4eb8d.png)

**Comment by eirannejad** [comment]
When you download ZIP it does not include the git repo so pyRevit can not determine its version. I'll change this to warnings in the next fix so they don't show up as ERRORs. pyRevit should function normally even without the repo. you won't be able to use the update feature however since there is no repo to pull into.

**Comment by thazell** [comment]
Ok.  Thanks.  I was thinking it was something like that.  I was hoping I could just change a setting, but I'll download the .git for now to my PC instead of the ZIP.

**Comment by thazell** [comment]
whoa.  my pyrevit folder is now almost 800 mbs.

**Comment by eirannejad** [comment]
Yeah I know. Most of it is the repo that holds the history. I'm so busy with other stuff right now that haven't had the change to work on pyRevit's company-wide installer yet :/

**Comment by thazell** [comment]
No worries...  Eventually that will be great, but this works for us right now.  I've got a folder that gets copied to the users computer and I run the .addin file.
It will be nice when the installer works, but this works for now.  I'll be shot by IT when I tell them I want 800 mbs copied to everyone's computer :)

**Comment by eirannejad** [comment]
Okay you can close this then. I have the pyRevit installer as a separate project on my list. Thanks for helping out.
