### ISSUE TITLE
pyrevitgitsetvices crash when wrong directory is used

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#282]
git setvices Crashes when set to pyrevit install directory instead of pyrevit repo directory

* Proposed: 
1. handle and issue error message instead
2. Edit [Installation Doc](http://eirannejad.github.io/pyRevit/installation/) to say *pyrevit repo path* instead of *installation path* (is that corrrect?)

![image](https://user-images.githubusercontent.com/9513968/35232069-7d5950be-ff68-11e7-9a36-683dc8828348.png)

![image](https://user-images.githubusercontent.com/9513968/35231557-29d08f3a-ff67-11e7-9577-63a3d219c572.png)

**Comment by eirannejad** [comment]
- [ ] Correct the documentation
- [ ] Graciously handle the error in the tool
