### ISSUE TITLE
Error using pyRevit update tool 

### ISSUE THREAD

**Issue by eirannejad** [eirannejad/pyRevit#285]
On behalf of @tymokvo 

![image](https://user-images.githubusercontent.com/8197916/35349005-9ec88ba2-00ee-11e8-8f37-e11c97987c14.png)

![version](https://user-images.githubusercontent.com/8197916/35349043-bad99516-00ee-11e8-9b71-e88e0c6b3223.png)

**Comment by tymokvo** [comment]
yes, more github immortality

**Comment by eirannejad** [comment]
@tymokvo Hey would you checkout `hotfix/issue285` branch and test?
