### ISSUE TITLE
Problem when opening Revit - No module named wpf

### ISSUE THREAD

**Issue by wallman2565** [eirannejad/pyRevit#288]
Hi,

Apologies for my naivety here, have used pyRevit alot but after installing 4.5, I'm getting the following error upon opening Revit, and then the Pyrevit plugin doesn't show in the ribbon bar. Any help, much appreciated...

"ImportError: No module named wpf"

![pyrevit error](https://user-images.githubusercontent.com/35984207/35603848-2d8e102c-06a4-11e8-8f60-fb67d966501f.JPG)

**Comment by eirannejad** [comment]
This is very odd. Do you have IronPython installed on your machine separately? Is this happening on the first run after installation?

**Comment by wallman2565** [comment]
Ironpython was installed separately but still have the same issue after
uninstalling that.

Having asked around - it appears that PyRevit is clashing with our own
internal addins. We run ours off a startup script using Revitpythonshell
apparently. We are looking into a resolution, any insight you can add would
be much appreciated.

Thanks

**Comment by wallman2565** [comment]
To update: We have found a solution by installing ironpython separately
from a different location, now it all runs fine. Not sure why that works
but has solved the problem! - thanks for your help.

**Comment by eirannejad** [comment]
Haha you did all the work so Thank YOU!...Ya IronPython installs its DLLs in the GAC and registers those with the operating system. This helps with finding dependencies with applications that use IronPython but makes it very hard when using different IronPython versions on the same machine.

pyRevit runs on IronPython 2.7.7 but there is an option under pyRevit settings that pushed pyRevit to use IronPython 2.7.3 for Dynamo compatibility.

Have fun scripting
