### ISSUE TITLE
Increment sheet number doesn't work when project browser window detached from main window

### ISSUE THREAD

**Issue by tomekpiatek** [eirannejad/pyRevit#291]
When the project browser window has been detached form the main window (i.e. floating project browser) I am unable to use the "Increment sheet number" script. It appears to do nothing. 

It works fine if the project browser is reattached back to main app window, although I have to reselect the sheets.

**Comment by eirannejad** [comment]
Yeah Revit doesn’t report the selected items in project browser correctly if it’s detached. You gotta select them two times. I’m gonna keep this issue open and add a sheet selection popup list to it soon. Will update you when ready

**Comment by tomekpiatek** [comment]
Yes, I thought it was something to do with that. Revit misbehaves when project browser is detached but at least the misbehaviour is consistent.

While you're at it any chance you can make those boxes resizable and add multi-select?

**Comment by eirannejad** [comment]
Of course will do

**Comment by tomekpiatek** [comment]
I've made those into individual requests. Just trying to be a good github citizen ;-)
