### ISSUE TITLE
Please add ability to select multiple items

### ISSUE THREAD

**Issue by tomekpiatek** [eirannejad/pyRevit#293]
Many of the dialogs include list of items to be select as input. It would be very helpful if we were able to select multiple items following typical conventions:

- ctrl+click for disjointed ranges
- shift-click for contiguous range

**Comment by eirannejad** [comment]
Would you give me an example of this? The Sheet selector standard form is already either using checkboxes or has multiple selection with Shift/Ctrl

**Comment by tomekpiatek** [comment]
Rename Selected Sheets uses check boxes. I can tick individual boxes but I can't select a contiguous range(s) and toggle its status. I would like to be able to do that.

**Comment by eirannejad** [comment]
Oh humm. Got it. That’s how the WPF list operates by default. I’ll look into it though.

**Comment by eirannejad** [comment]
Updated checkbox standard form for multiselection
