### ISSUE TITLE
Reduce size of main branch

### ISSUE THREAD

**Issue by eirannejad** [eirannejad/pyRevit#294]
@gtalarico I'd love to hear your experience and ideas on this. I'm thinking recreating master and revising the installer to [check out a single branch only](https://stackoverflow.com/a/39343600/2350244).

**Comment by gtalarico** [comment]
Greta idea.
Might be good too to check only last commit (`--depth=1`)

**Comment by eirannejad** [comment]
Did some tests on this:

- The installer uses `Libgit2Sharp` module for git actions so it does not have to install larger git binary tool. However `Libgit2Sharp` does not have support for depth or single-branch cloning.
- Tried creating orphaned `release/` branches with zero history for each major release and cloning at setup. But the repo size is kept small, only when used with single-branch option.

Seems like best bet is to retire and archive master repo at next major release (4.6) and create a new repo. @gtalarico Maybe should do this at every major release (once every year?)

**Comment by eirannejad** [comment]
Redesigned deployment mechanism. This issue is resolved since pyRevit does not ship the complete git repo anymore. See updates on 4.6beta and the new distribution model

https://eirannejad.github.io/pyRevit/pyrevit/updates/2018/10/07/newdistrib.html
