### ISSUE TITLE
Visibility/Graphic Filters Management Needed

### ISSUE THREAD

**Issue by Stevenlimo** [eirannejad/pyRevit#298]
Hi Ehsan, 
Most of the time I have over 30 or more filters created for different services, and whenever I create a new one, I have to use this 'Up' or 'Down' button to move it to the filters of the same category/group across the long list. Can you give the VG filter an additional SORT function so new filter can be automatically grouped by name?  When trying to assign the same line type or color or transparency to the same group of filters, I have to click and edit each filter individually. This is not fun at all.  I wonder if you can create a script to manage this tedious workflow for the VG filter?

Many Thanks :)

**Comment by eirannejad** [comment]
@Stevenlimo Hey would you mind sending me a screenshot or filter naming convention that you have? If I make this tool I have to make it generic enough that others can also benefit from it. It helps if I can understand the problem area better. Thanks 👍

**Comment by Stevenlimo** [comment]
Yes sure, as you can see, the filter is not sorted by naming or number. If I want to create a new filter named '00-Insulation', then by default, the filter will appear on the second place on the top.  If I want to create a filtered named '52-VentPipe' below the filter '52-SoilVentPipe', then I have to use my mouse to click on the '52-SoilVentPipe' first, then when I add '52-VentPipe' filter, it will be inserted below '52-SoilVentPipe'. But this is not automatic as there is no sorting function on the filter interface. If I have a big list of filters, this workflow will really consume time, particularly when comes to assign values to these filters, we are not able to highlight multiple filters but we have to click on them one by one to assign values. That is not cool. It would be great if we have a pyRevit Script which we can manipulate the VG filter list like a spreed sheet or schedule where we are able to sort them in different orders and assign values individually and collectively. 

Many Thanks:)     

![image](https://user-images.githubusercontent.com/30794071/35926652-90c95332-0c20-11e8-97ba-fd8c596c9746.png)

**Comment by eirannejad** [comment]
Hmmm interesting 🧐

**Comment by tillbaum** [comment]
Maybe we need a filter manager as a  modeless dialog:

"A modeless palette showing filters (as checkboxes objects) applied to the active view.
Also some buttons for:

    updating the modeless dialog window to the current view (in case one switches the view)
    adding/ deleting filters
    moving them up/down.

A tool like this would save the process of pushing vv/vg-button, clicking the filter tab in the visibility Dlg, and doing the changes to filters there. But maybe this is too much work. "

**Comment by eirannejad** [comment]
@tillbaum I'm working on a modeless system for pyRevit. Will update you all soon

**Comment by eirannejad** [comment]
See comments on https://github.com/eirannejad/pyRevit/issues/655
