### ISSUE TITLE
 LINKED AND IMPORTED DWG FILES: ...((

### ISSUE THREAD

**Issue by che-30** [eirannejad/pyRevit#299]
﻿good afternoon, 
sorry for my english
got a problem
does not work((

LINKED AND IMPORTED DWG FILES:

By: Frederic Beaupere

LINKED DWGs:

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\user05\AppData\Roaming\pyRevit\pyRevit-v4\pyRevit\extensions\pyRevitTools.extension\pyRevit.tab\Project.panel\ptools.stack3\Links.pulldown\ListDWGs.pushbutton\ListDWGs_script.py", line 84, in 
 File "C:\Users\user05\AppData\Roaming\pyRevit\pyRevit-v4\pyRevit\extensions\pyRevitTools.extension\pyRevit.tab\Project.panel\ptools.stack3\Links.pulldown\ListDWGs.pushbutton\ListDWGs_script.py", line 55, in listdwgs
AttributeError: 'NoneType' object has no attribute 'AsString'

Script Executor Traceback:
System.MissingMemberException: 'NoneType' object has no attribute 'AsString'
 ? Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 ? Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 ? Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
 ? System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 ? Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 ? Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 ? Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 ? Microsoft.Scripting.Interpreter.FuncCallInstruction`4.Run(InterpretedFrame frame)
 ? Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 ? Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 ? System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 ? Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
 ? Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 ? Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 ? IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 ? Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
 ? PyRevitBaseClasses.ScriptExecutor.ExecuteScript(PyRevitCommandRuntime& pyrvtCmd)

**Comment by hdm-dt-fb** [comment]
hi @che-30 thank you for the post. so it seems there is a  "ImportInstance" that interestingly has no name (I am currently not sure what that could be - do you know by any chance the object that could cause this?), so in turn the AsString() does not work. I will have a look, maybe we could set a default name.. Not sure how to simulate an "ImportInstance" without name though.

**Comment by hdm-dt-fb** [comment]
apparently sat imports do not have a name. 
So I think setting a default name should do the trick.. will send a PR

**Comment by che-30** [comment]
hi! how can i understand that import instanse has no name? may be look up by J.Tammikk can help me? 
for example https://yadi.sk/d/br-SngP-3SMhQi

**Comment by hdm-dt-fb** [comment]
hi. yes the lookup tool should work great for that.

**Comment by che-30** [comment]
As string N1_N2_N3 - монтажные схемы - 05.02.2018_1_1742_1369.dwg
![default](https://user-images.githubusercontent.com/19819439/36155524-a21abd6e-10e5-11e8-9eb9-fe933fcaf357.png)

**Comment by che-30** [comment]
am i right? .dwg has name? or no?

**Comment by hdm-dt-fb** [comment]
yes, that looks like it should show name via AsString(). Maybe the special character set is the source of the problem. could you paste this line to the first line of the script and see if it runs?:
# -*- coding: UTF-8 -*-

**Comment by hdm-dt-fb** [comment]
ah sorry that got auto-formatted I meant this:
`# -*- coding: UTF-8 -*-`

**Comment by hdm-dt-fb** [comment]
we had some scripts that showed funky behavior on German Umlaut characters if the coding was not declared at the top line of the script..

**Comment by che-30** [comment]
You are right. The matter is language, but no dwg name.

**Comment by che-30** [comment]
User interface is the matter of its problem
﻿LINKED AND IMPORTED DWG FILES:
By: Frederic Beaupere
LINKED DWGs:
DWG name: N1_N2_N3 - монтажные схемы - 05.02.2018_1_1742_1369.dwg

•DWG created by:cherniaev


•DWG id: 2585


•DWG workset: Workset1

**Comment by che-30** [comment]
thanks!!!

**Comment by hdm-dt-fb** [comment]
@che-30 you're welcome! 
..as a side note: I was wrong on sat: they do not even have a ImportInstance. 
@eirannejad do you mind putting in that top line, 
`# -*- coding: UTF-8 -*-`
so I do not need to PR?

**Comment by eirannejad** [comment]
Will do soon

**Comment by hdm-dt-fb** [comment]
thank you so much!

**Comment by eirannejad** [comment]
Resolved:
https://github.com/eirannejad/pyRevit/commit/47ab86beb2c0582986794892dcb78ca5b06c05b4
