### ISSUE TITLE
Feature: Add number interpolation to batch sheet maker

### ISSUE THREAD

**Issue by tomekpiatek** [eirannejad/pyRevit#301]
I would like to be able to use a simple substitution variable and numeric interpolation in the batch sheet maker dialog. The dialog would need two extra inputs: 
 - start of range
 - end of range

Optionally, you could provide an input for "step".

With these in place I could then direct the tool to produce sheets where some symbol, say %i, is substituted with consecutive values of the range.

This feature would allow us to quickly make a whole lot of sheets in one go sheets. 

I still should be able to create sheets as is now.

**Comment by eirannejad** [comment]
Genius. I’ll incorporate this.

**Comment by tomekpiatek** [comment]
Sweet!

-t


___
[image: https://]about.me/tomek_piatek

**Comment by tomekpiatek** [comment]
For the next iteration you could provide a whole lot of substitution
variables. This is a relatively common approach in many tools that have
batch processing capabilities. Take a look at the excellent ImBatch
<http://www.highmotionsoftware.com/products/imbatch> batch image processor
to see how and what sort of string substitutions and interpolations they
offer. It's a pretty useful pattern.

-t


___
[image: https://]about.me/tomek_piatek

**Comment by eirannejad** [comment]
Now works with sheet ranges. Try (with tabs):
``` text
A100    SHEET NAME
A101    SHEET NAME
A102    SHEET NAME
A103:A110    SHEET NAME
A111-A115    SHEET NAME
A116a-A116c    SHEET NAME
A117-a:A117-c    SHEET NAME
S100,M100,E100,P100    GENERAL NOTES
```

**Comment by tomekpiatek** [comment]
Genius! Thanks.

-t


___
[image: https://]about.me/tomek_piatek

**Comment by tomekpiatek** [comment]
Hey,

It’s so great to see someone tackle this gaping hole in Revit. I can’t believe that this is not a part of Revit. Anyway, I have some feedback so where would be the best place to publish it?

cheers,
-tomek

---
Tomek Piatek

**Comment by eirannejad** [comment]
Thanks! Opening a new issue (feature request) or (bug) would be ideal
