### ISSUE TITLE
Script return Error in Pyrevit, but run in Python Shell

### ISSUE THREAD

**Issue by varunbose** [eirannejad/pyRevit#302]
Hi Ehsan,

Just a starter with Revit Python & Pyrevit.
When I tried some codes in Python Shell, it works, but when I added that script in the pyrevit extension, it gives error message.

Just started coding to insert family instance. ".OfClass(typeof(FamilySymbol))" is also not working in Pythonshell
Python Shell Error :  IronPython.Runtime.UnboundNameException: name 'typeof' is not defined

The below code works in Shell, but fail in Pyrevit.
Pyrevit Error :  IronPython.Runtime.UnboundNameException: name 'typeof' is not defined

```
"""Insert Family Instance"""
__author__ = 'Varun Bose'

import Autodesk.Revit.DB as DB

doc = __revit__.ActiveUIDocument.Document
uidoc = __revit__.ActiveUIDocument

familysymbl = DB.FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_DuctTerminal).ToElements()
for i in familysymbl:
	print i.Id
```

Please advise.

**Comment by eirannejad** [comment]
python does not have `typeof` keyword.  To check the type of a dotnot object use:
``` python
import clr
clr.GetClrType(object)
```

Here is the corrected script. `BuiltInCategory` is in `DB` namespace. This should work in pyRevit.

``` python
"""Insert Family Instance"""
__author__ = 'Varun Bose'

import Autodesk.Revit.DB as DB

doc = __revit__.ActiveUIDocument.Document
uidoc = __revit__.ActiveUIDocument

familysymbl = DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_DuctTerminal).ToElements()
for i in familysymbl:
    print(i.Id)
```

I'm closing this since this is not an issue but keep the conversation going please. I want to make sure the script works 👍

**Comment by varunbose** [comment]
Thanks Ehsan for the clarification. You are great with your tutorials.

Is there any site which explains these difference in dotnet & python or we have to go through the whole Doc pages of both.

**Comment by eirannejad** [comment]
python is a programming language. Dotnet is a framework (libraries of modules and methods for various tasks). Ironpython has dotnet bindings and can load dotnet libraries and talk to applications that are based on dotnet platform. Refer to [revitapidocs](http://revitapidocs.com) for Revit API (dotnet) and python website for python language tutorials and documentation.
