### ISSUE TITLE
User Access to Custom Extensions

### ISSUE THREAD

**Issue by AzubikeO** [eirannejad/pyRevit#303]
Hi - I am able to control the user access for other users other than myself. It remove pyrevitCore from my tabs regardless of whether my username is included in the json file or not. It only shows up when i remove the custom extension file. Am i doing something wrong?

**Comment by eirannejad** [comment]
@AzubikeO Why do you open an issue and close immediately? Has this been resolved?

**Comment by AzubikeO** [comment]
@eirannejad Well it was solved which is why i closed it. However, I just realized it was partially solved because the username doesn't recognize my autodesk username(email), but if I use the regular revit username. So i will reopen this.

**Comment by eirannejad** [comment]
Okay I'll look into it soon. Thanks for the feedback

**Comment by eirannejad** [comment]
Signing to Autodesk with your Autodesk ID, will cause Revit to correct the username in Revit settings to match the Autodesk ID. However the Autodesk ID email is different from the AutodeskID username. The username can be set in the Autodesk Account manager and is different from your sign in email address. The username listed in json extension file must be the username show in Revit settings.

This seems to be working correctly and I can see any errors or issues.
