### ISSUE TITLE
Bubble chart error

### ISSUE THREAD

**Issue by frodooon** [eirannejad/pyRevit#304]
Hello,
When trying to replicate the example for the bubble chart, I got the following error:
![image](https://user-images.githubusercontent.com/32676510/36303333-bd250784-1303-11e8-9a68-8481be1de098.png)

I exactly copy-pasted the example from steps 1 to 3, using

`chart = output.make_bubble_chart()`

Any idea?
Thanks!

**Comment by eirannejad** [comment]
@frodooon I kinda expected that people would know how to use `charts.js` module but I can see that I need to improve the documentation on this. Thanks for pointing it out. The Bubble chart needs a 3 dimentional data as a dictionary (x, y, radius). x and y are the two main graph vectors and the third is the radius of the bubble for that data point.

``` python
from pyrevit import script
output = script.get_output()
chart = output.make_bubble_chart()
set_a = chart.data.new_dataset('set_a')
set_a.data = [{'x': 1, 'y': 12, 'r': 33},
              {'x': 2, 'y': 9,  'r': 60},
              {'x': 3, 'y': 4,  'r': 34},
              {'x': 4, 'y': 22, 'r': 22}]
chart.draw()
```

Under pyRevit extensions, activate `pyRevitDev` extension, and run the `Test Charts` tool from `Unit Tests`. See if it successfully renders the charts.

**Comment by frodooon** [comment]
Hello,
I tried that and it worked fine, thank you! Don't take my case as a generality, I'm sure most of other people do know how to use chart.js ;)
Thanks a lot for taking the time to explain!

**Comment by eirannejad** [comment]
Awesome! Thanks a lot for the feedback
