### ISSUE TITLE
pyrevitgitservices crashes when installing on Windows 7

### ISSUE THREAD

**Issue by two9seven** [eirannejad/pyRevit#310]
Trying to install on windows 7. Getting errors when installing. pyrevitgitservices crashes. Here are the errors in order:

Pyrevitgitservices Crash error:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	pyrevitgitservices.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	59ff7f39
  Problem Signature 04:	LibGit2Sharp
  Problem Signature 05:	0.24.0.0
  Problem Signature 06:	594ae9a1
  Problem Signature 07:	a2b
  Problem Signature 08:	50
  Problem Signature 09:	LibGit2Sharp.LibGit2Sharp
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Next error:
Unable to execute file:
C:\programData\pyRevit\pyRevit-v45\pyrevit\release\uninstall_addin.bat at
CreateProcess failed; code 267
The Directory name is invalid

Thanks for any help you can provide.

**Comment by eirannejad** [comment]
@two9seven Have you seen this by any chance? Let me know if this resolved the issue.

http://eirannejad.github.io/pyRevit/pyrevit/installer/2018/03/01/githubtlschange.html

**Comment by two9seven** [comment]
Yep that was it. Problem resolved after installing Microsoft EasyFix. Thank you.
