### ISSUE TITLE
pyRevit with Revit 2018.2 not loading

### ISSUE THREAD

**Issue by schlueter-de** [eirannejad/pyRevit#318]
Hi,

Yesterday i installed Revit 2018.2 on all machines in our office. I installed pyRevit on 6 machines but i can't see the tool in the ribbons. Can you help? 

Tried it with the english and german client.
![2018-03-12_10h36_15](https://user-images.githubusercontent.com/26480934/37276128-360f71ee-25e1-11e8-9039-c21a46cdf6c1.jpg)
![2018-03-12_10h35_11](https://user-images.githubusercontent.com/26480934/37276133-39146b42-25e1-11e8-88e4-338338bcb17b.jpg)

Thanks
schlueter

**Comment by CyrilWaechter** [comment]
Hi,
Did you get the addin load message ?
If not can check if file `pyRevit.addin` is in one of the following folder :
- `%AppData%\Autodesk\Revit\Addins\2017`
- `%ProgramData%\Autodesk\Revit\Addins\2017`

If addin file is missing. You can try to launch `pyRevit\release\install_addin.bat` in your pyRevit installation folder.

**Comment by schlueter-de** [comment]
Hi CyrilWaechter,

there was no load message and there where no files in the folder. Maybe because i installed the addon with the adminprofil and not my userprofil?

But anyway, i launched the .bat with my userprofil and now its working. big thanks.

schlueter

**Comment by eirannejad** [comment]
Yeah I think it gets installed in the admin %appdata% since that what the .bat script uses to expand the target directory. I'm working on a proper installer for pyRevit that will be out soon and hopefully will resolve all these installation issues.
