### ISSUE TITLE
Revit 2013 - IOError: System.IO.IOException: Could not add reference to assembly Newtonsoft.Json

### ISSUE THREAD

**Issue by RevitIRL** [eirannejad/pyRevit#323]
See screenshots of window that comes up when launching Revit 2013. Clicking close allows Revit to complete launching. Other versions appear fine.

![r2013-1of2](https://user-images.githubusercontent.com/20117305/37793044-a3989f38-2db1-11e8-887c-0b219c776f07.png)
![r2013-2of2](https://user-images.githubusercontent.com/20117305/37793045-a3b779c6-2db1-11e8-9566-9acee1c15d51.png)

NOTE: I've had other issues with launching Revit when pyRevit is installed. With the previous pyRevit, it seemed to cause Revit 2017 to hang while launching (partially through the pyRevit loading) if Windows 10 had any pending updates. I'm still waiting to see if it happens with 4.5. Also, I seem to have an occasional problem with the Screencast add-in not being able to load.

![r2017-screencast](https://user-images.githubusercontent.com/20117305/37793543-1a629500-2db3-11e8-9e70-95b822137d06.png)

I'm not sure if either of these would be related to the above issue, but thought I'd share them JIC.

Note also that we only have one Revit 2013 project sticking around, so this isn't a high priority problem for us.

**Comment by eirannejad** [comment]
Okay good to know. pyRevit imports some standard dlls in Revit for easier use. I didn't know `Newtonsoft.Json` is not included with Revit. Thanks for the feedback

**Comment by RevitIRL** [comment]
I just did a search, and it's in 2015+ (& dynamo, & other locations) but not 2013 (or 2014 - I just checked another machine).

![c212 2013 15 16 17 18 -newtonsoft](https://user-images.githubusercontent.com/20117305/37795686-4dcdb324-2db9-11e8-8884-c9ef6aa50fff.png)

**Comment by eirannejad** [comment]
Resolved.
