### ISSUE TITLE
Revit 2017 on Windows 10 - sometimes hangs when loading

### ISSUE THREAD

**Issue by RevitIRL** [eirannejad/pyRevit#324]
Since getting a new (Win10) CPU (the previous was Win7), there are times when Revit 2017 will hang while launching:
![2018-03-28_r2017 stuck loading but no pending win updates](https://user-images.githubusercontent.com/20117305/38058197-b7eafa6e-327d-11e8-8e42-3ae63a765f29.png)
At first I thought it had something to do with a pending Windows update, but it seems those were just coincidences (I don't normally restart very often) as the above (and attached journals below) was with no updates pending. Restarting fixes the problem (so Revit will finish launching), but isn't always convenient. Other versions launch fine (even when 2017 doesn't).

[journal.0052.txt](https://github.com/eirannejad/pyRevit/files/1857897/journal.0052.txt)
[journal.0052.worker1.log](https://github.com/eirannejad/pyRevit/files/1857898/journal.0052.worker1.log)

**Comment by eirannejad** [comment]
Is **Check Updates At Startup** activated in your settings?

**Comment by lionelcamara** [comment]
No. I just checked and it's not.

**It just happened again, BTW, and this time it coincided with a pending Windows update again.**

While browsing through the settings, I noticed that there's checkboxes to disable pyRevit for each version. Since it's easy enough, I may just temporarily disable for 2017 in the future, if needed.

Until then, should I increase the Reporting Level to "Debug mode"? Is "File debug logging" the same thing? 
[pyRevit_2017_14112.log](https://github.com/eirannejad/pyRevit/files/1900941/pyRevit_2017_14112.log)
[pyRevit_2017_26804.log](https://github.com/eirannejad/pyRevit/files/1900942/pyRevit_2017_26804.log)

**Comment by RevitIRL** [comment]
For some reason I couldn't type in my browser after uploading the log files. I meant to explain that pyRevit_2017_26804.log has an 11:24 AM time (which is about when I couldn't launch Revit 2017 this morning), and pyRevit_2017_14112.log is from 2:35 PM (which is just recently, after a restart, and I checked the update setting as requested).

**Comment by eirannejad** [comment]
Okay thanks for the feedback. Don’t enable the debug or file logging for now. They’d dramatically increase the amount of reporting.

**Comment by lionelcamara** [comment]
OK. BTW, file logging was already checked (that's how I got the two log files from C:\Users\...\AppData\Roaming\pyRevit\2017\).

**Comment by RevitIRL** [comment]
Occurred again (without any pending Windows updates).

I tried unchecking "Revit 2017" in the pyRevit Settings (using R2018), but it doesn't "stick". I assume this is a permissions issue (since admin is needed to delete the file, but it never asks)?

**Comment by RevitIRL** [comment]
The funny thing is that Revit 2017 still hangs even after manually deleting "pyRevit.addin" (from "C:\ProgramData\Autodesk\Revit\Addins\2017\"). I don't see anything in "C:\ProgramData\Autodesk\ApplicationPlugins\", so now I'm beginning to wonder if it's even pyRevit-related... is there another load point for pyRevit?
I'm going to restart and see

**Comment by eirannejad** [comment]
Nope. `pyRevit.addin` is the only load point. Are you using a license server? It might be that.

**Comment by RevitIRL** [comment]
I actually determined that it was caused by Autodesk's "BIM 360 Glue" add-in instead! :)

**Comment by eirannejad** [comment]
@RevitIRL Thanks for the update!
