### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by chinh-trieutien** [eirannejad/pyRevit#325]
Can I create Slider like this, then how?? thank

![image](https://user-images.githubusercontent.com/8264004/38716365-8622e9bc-3f0a-11e8-842c-eb7c84dcb49d.png)

**Comment by eirannejad** [comment]
Please be more specific. Create a slider in pyRevit? You can use the WPF library to create your own window with sliders and handle the slider change event.

Closing since this is a not an error.
