### ISSUE TITLE
viewId cannot be added to the ViewSheet

### ISSUE THREAD

**Issue by simasrud** [eirannejad/pyRevit#326]
Hi, I am getting an error when trying to copy views from one sheet to another.
The error says that viewId cannot be added to the ViewSheet.

Any suggestions?
Thanks,
![viewid_error](https://user-images.githubusercontent.com/28701925/38884401-5e29010e-4224-11e8-9008-42df3da0248f.png)

**Comment by eirannejad** [comment]
What view types are you trying to copy? Remember model views can only be placed on one sheet. They can't be copied to other sheets.

**Comment by simasrud** [comment]
They are drafting views.

**Comment by simasrud** [comment]
It works when I copy legend, but once I try to copy a drafting view I get the error.

**Comment by simasrud** [comment]
Oh okay, my bad, you are right, both model views and drafting views can be placed only on one sheet, that's why we are not able to copy them. I am able to move them though.
Thanks again!

**Comment by eirannejad** [comment]
Most welcome. I'll add a prompt to the tool to inform user of the view types.
