### ISSUE TITLE
issue copying sheet from one populated model to another populated model

### ISSUE THREAD

**Issue by JPerey** [eirannejad/pyRevit#327]
Hello,

I am having a problem moving drafting views from a populated model to another populated model.

Things of note: 
- I have a legend in both models and only keep one sheet open usually when i am trying to copy - the page I want to copy and the sheet I want it to copy to. 

I have gotten errors due to ViewId's and sheet numbers but have found ways to fix those, but this error is what I'm stuck on right now. Any help would be greatly appreciated!

Thanks!

![pyrevit copy error 1 - copying one or more failed](https://user-images.githubusercontent.com/6946698/38885869-295a98a2-4229-11e8-8788-32d3eba5a3b0.PNG)

**Comment by JPerey** [comment]
I would love to help, but I'm a little confused on what would entail as an example model  to send you. I ask because I've created new models on my local network that copied sheets fine, but as soon as I try to copy sheets from my new model to my existing model ( or copy sheets from an existing model to another existing model) I would get this error. Also I am not sure if I can send my existing model to you as it is most likely too large and I'm not in a position to send it out.

**Comment by eirannejad** [comment]
And example model is a model that would help be replicate the error. This error does not happen for me and I need to somehow create the environment that causes the error to show up.

**Comment by JPerey** [comment]
Hi again Eirannejad,

I apologize for taking time to get back to you. I needed to wait for approval on creating an example model but was finally able to get the models done.  I have 2 example models that I can send you that replicate the error I'm getting. Specifically if you copy some of the control sheets from "42 ME Detached" to "22 ME Detached" models.

Unfortunately the file is too large to send over so I have added the models to my google drive and created a link to the files to download:

https://drive.google.com/file/d/1hZqyrbgjV3J1N70ouTYSSp3WXXDtwzRI/view?usp=sharing

Thank you for your help!

**Comment by JPerey** [comment]
Hello @eirannejad,
I was just wondering how this issue is going, and if you were able to recreate the error in my first post?

**Comment by JPerey** [comment]
Hello, 
I understand that you're busy, so just wondering if there was an update to this issue?

**Comment by eirannejad** [comment]
Sheet copy system revamped in 4.6. test again please and let me know if the errors still exist,
