### ISSUE TITLE
errormessage from genericcomps.py

### ISSUE THREAD

**Issue by epeter-** [eirannejad/pyRevit#330]
errormessage without linenumber in loaded script.

i receive an error from one of my scripts referring to line number 322 in genericcomps.py.
actually not everytime i reload pyrevit
and the scrip is working....#
it were helpful if genericcomps.py would add the linenumber of the found error in the  parsed file

**Comment by eirannejad** [comment]
What's the startup error message look like?

**Comment by epeter-** [comment]
![image](https://user-images.githubusercontent.com/6928491/39393559-f51c32de-4ac6-11e8-9350-73a34821257e.png)

**Comment by eirannejad** [comment]
Improved error reporting when preprocessing scripts on first load:

![2018-05-13 16_21_00-pyrevit](https://user-images.githubusercontent.com/8197916/39972750-4d7184e8-56ca-11e8-992c-8ec84391ce7d.png)
