### ISSUE TITLE
Line style in make pattern

### ISSUE THREAD

**Issue by amaberNOAB** [eirannejad/pyRevit#331]
Hi, 
I´m trying to make a pattern that contains both solid lines and dot dash-lines. When the patterns is created, there are only solid lines in the pattern, all the dot dash-lines becomes solid. 
Is this a setting-thing or a code-thing?
There´s no change in lines in the pattern when i change scale.
![capture](https://user-images.githubusercontent.com/36155594/39356598-b1ec941a-4a10-11e8-881c-4e9cbf212cf7.JPG)

Thanks!

**Comment by eirannejad** [comment]
Are you using Revit line types for the pattern? OR actually drawn the dashed line?

**Comment by amaberNOAB** [comment]
Used revit line type.

Hälsningar



Amanda Berneblad
3D/BIM-Projektör
Dir: +46 101418530 | Mob: +46 768354230
amanda.berneblad@norconsult.com

Norconsult AB, Box 8774, 402 76 Göteborg
Theres Svenssons gata 11, 417 55 Göteborg
Tel: +46 10 141 80 00 | Fax: +46 10 141 80 01
www.norconsult.se<http://<br/>www.norconsult.se>




On Fri, Apr 27, 2018 at 8:38 PM +0200, "Ehsan Iran-Nejad" <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you using Revit line types for the pattern? OR actually drawn the dashed line?

**Comment by eirannejad** [comment]
So yeah a the moment the pattern maker can not read the Revit line styles. Please draw the pattern usign line segments for now.
