### ISSUE TITLE
text tools

### ISSUE THREAD

**Issue by cridder** [eirannejad/pyRevit#333]
Hey anyway you can add the text tools back?  Merge notes, etc?  Like in 4.4 Thanks.

**Comment by eirannejad** [comment]
They're still there. Select text elements and use pyRevit > Modify > Override > Override Text and pick one of the options. I combined all these tools into one for faster load times and less small tools.

**Comment by cridder** [comment]
oh.  that is sneaky and awesome.  thanks.
