### ISSUE TITLE
Revit Parameter Manager

### ISSUE THREAD

**Issue by eirannejad** [eirannejad/pyRevit#335]
Re: PR #329 by @CyrilWaechter 

- [ ] Need to remove pyrevitmep module and move functionality to script level or pyrevit module.
- [ ] UI needs rework, tooltips and adjust for a more intuitive workflow
- [ ] Combine both tools into once "Parameter Manager". Make the distinction between what's project or shared inside the tool. Maybe by color coding.
- [ ] merge extra functionality from rsparam cli tool into these tools, allow for comparison and resolving merge conflicts

**Comment by CyrilWaechter** [comment]
I worked on SharedParameter manager part : https://youtu.be/Gfy2zRojZDg
* Added tooltips for buttons
* Direct modification (1 click)
* Multi line editing
* Default sort by name
