### ISSUE TITLE
Can't install last PyRevit version

### ISSUE THREAD

**Issue by rbaggen** [eirannejad/pyRevit#336]
I'm getting an error on installing PyRevit, see attachement.
I hope you can help me on this one.
I think it is a security issue... (Symantec)

![2018-05-14 13_40_27-clipboard](https://user-images.githubusercontent.com/14872958/39995416-668b48da-577c-11e8-86d1-bcf8e0d18f0a.png)

**Comment by rbaggen** [comment]
Ehsran,

Thanks for the mail, this one works super for me!!
Now I can use your tools again...!

Regards,

Rolph Baggen

On 14 May, 2018, at 06:50 PM, Ehsan Iran-Nejad <notifications@github.com> wrote:

It probably is. The installer uses git to be able to clone the pyRevit repo from github. See the link below as well: https://eirannejad.github.io/pyRevit/pyrevit/installer/2018/03/01/githubtlschange.html

**Comment by eirannejad** [comment]
Absolutely!  Thanks

Sent from my cell phone
Please excuse the typos
