### ISSUE TITLE
libgit2sharp update

### ISSUE THREAD

**Issue by melnikovalex** [eirannejad/pyRevit#338]
Hey Ehsan!

I am not sure that it will solve my issue, but I have tried to rebuilt pyrevitgitservices with newer libgit2sharp library (0.25) and it helped. 

I suppose my problem was linked with corporative network settings and with Github security changes. 

I wasn't able to install pyrevit with default installer - pyrevitgitservices threw an exception. Also when I was trying to install any extension there was an error

`ERROR: [__main__] Error installing package. | user cancelled certificate check: `

With this update, I was able to fix the error during pyRevit install. But I am not sure how to update libgit2sharp libraries correctly in pyRevit itself.

Could you update it please?

Best regards,
Alex

**Comment by eirannejad** [comment]
I did try to compile against v0.25 a while ago but was getting an error so switched back to 0.24. `pyrevitgitservices` is being replaced by another utility that has a lot more functionality for pyRevit support. I'll put it on the notes to use the latest libgit2sharp version. The dlls are under `./pyrevitlib/pyrevit/loader/addin`
