### ISSUE TITLE
Match for revit 2019

### ISSUE THREAD

**Issue by nestyle** [eirannejad/pyRevit#339]
Hi

Revit 2019 has foreground & background options in the element visibility override window.
The match command only picks up on foreground option.

![image](https://user-images.githubusercontent.com/19799521/40976687-34a986b8-6912-11e8-9a82-cffb7056eed6.png)

**Comment by eirannejad** [comment]
Resolved. Will be pushed with 4.6beta2 this weekend.

![2018-10-12 08_51_18-select options to match_](https://user-images.githubusercontent.com/8197916/46879877-01c5e800-cdfc-11e8-88d3-5f3b07bf457d.png)
