### ISSUE TITLE
Tracking modified time

### ISSUE THREAD

**Issue by Darkkrynn** [eirannejad/pyRevit#341]
Good morning. Good morning,

We use PyRevit regularly. And we also use the convenient "who should change what" function.

We would like to know if it is possible to have the day and/or time of the modification of the selected object. As you pointed out, this information did not exist at the time. They may have added.

If that possibility exists, I think it would be a plus to add it.
And sorry I posted in the wrong place.

Best regards
Krynn

![2018-06-06_01h26_35](https://user-images.githubusercontent.com/39972350/41069976-8dc47382-69f0-11e8-9149-11ba572bcd50.png)

**Comment by eirannejad** [comment]
It depends if revit keeps time stamp of changes. It didn't when I created that tool but I can take another look and see if maybe they have added that feature.

**Comment by hdm-dt-fb** [comment]
@eirannejad that would be great if they added it. I am curious to 
hear if they did that in one of the newer versions.

For a pilot project we used the pyRevit startup.py to hook into 
sync event to store element changes in a db, so we can see the 
last x changes of an element when by whom, but a Revit 
built-in functionality for element change time stamps would 
be quite helpful.

**Comment by eirannejad** [comment]
Looked into it. No changes has been made to this API and doesn't have timestamps: http://www.revitapidocs.com/2018.1/25b410b1-91f4-1147-12e1-f11aa39a1073.htm
