### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by chauhuh** [eirannejad/pyRevit#342]
From this page:

https://eirannejad.github.io/pyRevit/whatspyrevit/

This link is broken:

https://eirannejad.github.io/pyRevit/howtoaddscriptsandtabs

Thanks.

**Comment by eirannejad** [comment]
See these links:
http://pyrevit.readthedocs.io/en/latest/scriptanatomy.html
http://pyrevit.readthedocs.io/en/latest/creatingexts.html

I'll update the page ASAP.

**Comment by eirannejad** [comment]
Resolved.
