### ISSUE TITLE
How to add pyRevitMEP manual?

### ISSUE THREAD

**Issue by rbaggen** [eirannejad/pyRevit#343]
Hi Ehsan,

Can you tell me the steps to manual install pyRevitMEP?

**Comment by eirannejad** [comment]
Clone the pyRevitMEP to any place. Then go to pyRevit settings and add the extension folder to the list and reload pyRevit.

**Comment by rbaggen** [comment]
This does not work unfortunately?

**Comment by eirannejad** [comment]
How so? Please share where is the extension cloned and how did you add the directory to pyRevit settings. Please remember that the parent directory that holds the extension needs to be added not the `pyRevitMEP.extension` directory itself.

**Comment by rbaggen** [comment]
Thanks for the quick email. I hope the picture says enough?
I just added the folder in the settings.

**Comment by eirannejad** [comment]
Don't see any pictures.

**Comment by rbaggen** [comment]
Sorry again, I just replied you're email.

See pictures
![2018-06-15 20_28_07-pyrevit extension manager](https://user-images.githubusercontent.com/14872958/41483831-ef1e52f6-70da-11e8-8455-b39e8b9cc94b.png)
![2018-06-15 20_28_57-autodesk revit 2018 2 - floor plan_ 1 - mech - project1](https://user-images.githubusercontent.com/14872958/41483832-ef3a4eb6-70da-11e8-983c-592545d5e2bb.png)
![2018-06-15 20_29_10-pyrevit](https://user-images.githubusercontent.com/14872958/41483834-ef5e86f0-70da-11e8-86c1-dc9998879263.png)
![2018-06-15 20_29_29-gitkraken](https://user-images.githubusercontent.com/14872958/41483835-ef7af97a-70da-11e8-9698-98e94fe50ebc.png)

**Comment by eirannejad** [comment]
Oh okay. Rename the pyRevitMEP git repo (the one that has a subfolder named .git) to `pyRevitMEP.extension` and reload pyRevit.

**Comment by rbaggen** [comment]
Thanks a lot! This worked.
