### ISSUE TITLE
pyRevit Launch error

### ISSUE THREAD

**Issue by bunk1996** [eirannejad/pyRevit#352]
![capture](https://user-images.githubusercontent.com/41330842/42815957-efa2f048-89c0-11e8-8b0b-a89fcee81010.PNG)

Having installed pyRevit i'm getting this error when I launch Revit, any help with regards to how to fix this?

**Comment by eirannejad** [comment]
Did you get any errors in installation?
Do you have IronPython separately installed on your machine?
What's the Revit version and windows version?

**Comment by bunk1996** [comment]
There was an error window during installation.
IronPython is not separately installed
Revit 2018, Windows 7 SP1

**Comment by eirannejad** [comment]
The pyRevit has not been installed correctly. What was the installation error?
See these as well:
https://eirannejad.github.io/pyRevit/pyrevit/installer/2018/03/01/githubtlschange.html
https://eirannejad.github.io/pyRevit/installation/

**Comment by eirannejad** [comment]
I'm closing this for now since this is technically an installation issue. Feel free to open if you have more info
