### ISSUE TITLE
Revit Always Load not Sticking

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#353]
Any thoughts on what the issue here might be? (tail between my legs I haven't rolled out 4.5 to all users yet.)

It's only occurring on a few computers in our network (maybe 2 out of 100), but on some of the computers the users are getting this pop-up every time they load Revit 2018?

![imgpsh_mobile_save](https://user-images.githubusercontent.com/14113080/42884838-5afa4754-8a6d-11e8-8ae5-7892fd2a9b36.jpg)

They always click "Always Load".
My thought was that the addin file or dll file were being recreated every night and that was triggering it, but IT said that the scripts aren't running, so I'm unsure why it could be happening.

**Comment by thazell** [comment]
We have checked and the Dll is unblocked.  Next we are going to try to just replace all the files with a fresh set.

**Comment by eirannejad** [comment]
Revit stores this info in Windows registry under `HKEY_CURRENT_USER\Software\Autodesk\Revit\Autodesk Revit 2018\CodeSigning`. Make sure this info gets saved correctly there.

**Comment by thazell** [comment]
That's very interesting.  It's listed in the codesigning as B39107C3-A1D7-47F4-A5A1-532DDF6EDB5D which is the same as listed in the .addins file.

**Comment by eirannejad** [comment]
Yeah that's the App Id. But the fact that Revit can't determine that this addin has already been approved is very odd.

**Comment by eirannejad** [comment]
Were you able to find any resolutions to this?

**Comment by thazell** [comment]
I haven't confirmed we have a solution yet.

**Comment by thazell** [comment]
Just to confirm, it's still a problem after reinstalling on that PC, but it seems specific to a few select PC's (currently only one user is reporting the issue.)

**Comment by eirannejad** [comment]
Signed all pyRevit loaders so this issue should go away. Closing since it's not a direct pyRevit issue.
