### ISSUE TITLE
XML Parsing error

### ISSUE THREAD

**Issue by pmcmm** [eirannejad/pyRevit#354]
Hello there,

[XML files.zip](https://github.com/eirannejad/pyRevit/files/2208241/XML.files.zip)

I'm trying to work with gbXML files within pyRevit (link above) but I believe that there is a problem with the XML parsing functions. Everything works correctly for files with UTF8 parsing but I get the following error with UTF16:

```
import xml.etree.ElementTree as ET
path = 'C:\\BARC\\Project1.xml'
c = ET.parse(path)
print c

xmllib.Error: Syntax error at line 1: illegal data at start of file
```

I tried to solve this by forcing the parsing to UTF16, with no luck:
```
xmlp = ET.XMLParser(encoding="utf-16")
f = ET.parse(path,parser=xmlp)
```

Strangely, if I run the exact same code in Python GUI 2.7.7 both versions work perfectly, no problems at all, so there must be a problem with pyRevit standard library. Any idea how this can be solved?

![pyrevitss](https://user-images.githubusercontent.com/12100722/42922226-ee9c45ca-8b49-11e8-8a83-ce8af313c668.png)

**Comment by eirannejad** [comment]
Thanks for the attachment. I’ll lookin into it. You’re right there must be an issue with the xml module itself.

**Comment by eirannejad** [comment]
I get this error on `2.7.7` stand-alone as well. I think there must be an update to `2.7.10` that you're using. I'll put this on the list to update pyRevit to `2.7.10`

**Comment by pmcmm** [comment]
it works for me on the 2.7.7 stand-alone too. That is strange...

![pyrevit](https://user-images.githubusercontent.com/12100722/42924977-b34638fc-8b56-11e8-87f1-b413555cb6c8.png)

**Comment by eirannejad** [comment]
No. standard libraries are compressed into a zip file and included in the pyRevitLoader. I'll update the IronPython to 2.7.10 soon. Meanwhile you can read the file in utf-16 and save to a temp utf-8 to run the xml module.

**Comment by pmcmm** [comment]
yeah i will do that. Thanks a lot. Looking forward for the update!

**Comment by eirannejad** [comment]
Hey where did you get the 2.7.10 IronPython? The most recent I can download from the website is the 2.7.8
Did you compile from source yourself? I added the 2.7.8 engine to pyRevit development branch and tested and the xml error still exists

**Comment by pmcmm** [comment]
I believe that my printscreen shows the Python Shell, not the ironPython interface...

There must be a problem with the library of ironPython. It should be working already on version 2.7.7

**Comment by eirannejad** [comment]
Determined as IronPython bug. Tested 2.7.9 and 2.7.8 engines and they have the same issue for utf-16 xml files.
