### ISSUE TITLE
pyRevitloader error v4.5 

### ISSUE THREAD

**Issue by cmturner20** [eirannejad/pyRevit#356]
Hi, 

I am getting the following dialogue after installing v4.5 in Revit 2018.3 after which the pyrevit tools fail to load.  I initially thought it could have been missing some updated files, so we ran the update script, and then the install_addin script, so i believe everything should now be running the latest.  I have also applied the TLS patch as discussed in one of the installation articles.  We have tried manual installation also as per the youtube videos, which gives the same error.  We do have IronPython 2.7.3 installed on the same machine.  Any ideas what the cause could be?  

System Specs:
Windows 7 x64 SP1 
Revit 2018.3 

This is the dialogue:

![pyrevit45error](https://user-images.githubusercontent.com/41429022/42938794-d6a8338c-8b96-11e8-8b3a-f62675fb0776.jpg)

**Comment by eirannejad** [comment]
This is really odd. Try removing the stand-alone IronPython and see if it helps.

**Comment by cmturner20** [comment]
HI, i removed IronPython but unfortunately still the same happens.

**Comment by eirannejad** [comment]
Seems like it has troubles compiling the core C# code on the first run. Do the users have write/read access to the `%appdata%/pyRevit` directory?

**Comment by cmturner20** [comment]
Yeah, all authenticated users have full read/write to the pyrevit directory.  Even logged in as a local admin account gives the same result.


Carl Turner
IT & SYSTEM MANAGER | ASIA PACIFIC | ASSOCIATE PRINCIPAL
Populous is proud to be named Fast Company’s #1 most innovative company in live events.
POPULOUS
71 Boundary Street
Brisbane | QLD 4000 | Australia
Direct: +61 7 3838 7921 | Mobile: +61 406304596 | Main: +61 7 3838 7900 | Fax: +61 7 3839 9188
www.populous.com
TwitterFacebookVimeoWeibo
REGISTERED IN AUSTRALIA ACN 072 891 993

**Comment by eirannejad** [comment]
Honestly the only other issue I can think of is missing standard dotnet framework dlls. Would you be able to install Visual Studio (free edition) on the machine and test again? Visual studio installs a list of frameworks that might be the root cause of this. I've looked into the code and can't really think of anything that might be causing this. This is the first time I'm seeing the error :/

**Comment by cmturner20** [comment]
Still the same after installing .NET 4.7.2, and then all frameworks that come with the install of Visual Studio Community 2017.

One thing I have noticed, which I’m not sure if it would be the cause of the load error, is this add-in security warning:

[cid:image003.jpg@01D427F9.88C4DD10]

All our other plugins from the likes of V-Ray etc have a public CA (like GoDaddy etc).  We are clicking ‘Always Load’, just wondered if the two were connected.

Cheers,
Carl.


Carl Turner
IT & SYSTEM MANAGER | ASIA PACIFIC | ASSOCIATE PRINCIPAL
Populous is proud to be named Fast Company’s #1 most innovative company in live events.
POPULOUS
71 Boundary Street
Brisbane | QLD 4000 | Australia
Direct: +61 7 3838 7921 | Mobile: +61 406304596 | Main: +61 7 3838 7900 | Fax: +61 7 3839 9188
www.populous.com
TwitterFacebookVimeoWeibo
REGISTERED IN AUSTRALIA ACN 072 891 993

**Comment by eirannejad** [comment]
Hey any luck on getting pyRevit to load? I can't determine the root cause for this. The only thing I can think of is maybe somehow an antivirus os blocking the DLLs in `%appdata%/pyRevit`

**Comment by Coppolow** [comment]
Hi, Ehsan Iran-Nejad
I have got this problem too

System Specs:
![99](https://user-images.githubusercontent.com/43668782/46197719-40937280-c313-11e8-848f-78879c8949b0.png)

Windows 10 x64
Revit 2018.2

**Comment by eirannejad** [comment]
@Coppolow Seems like you have unicode characters in your user profile path right?

**Comment by eirannejad** [comment]
pyRevit has a new loader. Try 4.6beta installer and see if the error still exists

**Comment by nirlevie** [comment]
I'm having a similar problem (I think...)
![screenshot 2019-01-23 10 23 58](https://user-images.githubusercontent.com/26359990/51600677-2f4a2380-1f0b-11e9-85f6-47f7b21eed19.png)
