### ISSUE TITLE
Tool Load customizer (New Tool)

### ISSUE THREAD

**Issue by UpMoJo** [eirannejad/pyRevit#357]
I would like the ability to lighten the load and tool bar by customizing the tools that would be loaded.

Also, I thought PyRevit could copy legends from a sheet to selected sheets, am I mistaken?

**Comment by CyrilWaechter** [comment]
About your 2nd sentence. Yes you can copy legends (and any duplicable viewport) to multiple sheets by using
![image](https://user-images.githubusercontent.com/9622862/42960386-eaf9f40c-8b8b-11e8-8067-0d7fa4126384.png)

**Comment by UpMoJo** [comment]
It appears that is missing in my version.  Would you know why that would be?

[cid:image001.png@01D41F69.3ECAEB20]



[PGAL]<http://www.pgal.com/>    CRAIG UPTMOR

Senior Associate
[cid:image56a7dd.JPG@56bf4367.4bbae54d]
PGAL.COM<http://www.pgal.com/>
[Twitter]<https://twitter.com/PGALconnect>      [Facebook] <https://www.facebook.com/PGALconnect>       [LinkedIn] <https://www.linkedin.com/company/pgal>      [Instagram] <https://www.instagram.com/pgalconnect/>    [Youtube] <https://www.youtube.com/channel/UCHCMW44szUOhzMgYm9y2NLQ>

**Comment by CyrilWaechter** [comment]
We don't see your image. It looks like you answered the github email notification which apparently do not include images.
Please check you pyrevit version. eg. mine is currently 4.5:40280e7 : 
![image](https://user-images.githubusercontent.com/9622862/42966413-5bc9adba-8b9d-11e8-9cdc-e64bf0854adc.png) ![image](https://user-images.githubusercontent.com/9622862/42966439-7308d488-8b9d-11e8-9427-f079b00cc43f.png)

**Comment by UpMoJo** [comment]
v4.5:e661b45
It's different.  I'll go try to find your version.  Do you know anything about this version I have?  I have tried "Update" and that did not change anything.

**Comment by UpMoJo** [comment]
Downloaded new file from website and still don't have that tool. Interesting...

**Comment by eirannejad** [comment]
@UpMoJo This is very odd. Would you mind sending a screenshot of the pyRevit tab and specifically the Sheet pulldown? It does not makes sense that a single tool is missing :/

**Comment by UpMoJo** [comment]
I have found success.  I was looking in the "Legends" pull down versus the sheet pull down.  Your red arrow starting from that Tab confused me.  Thanks for the help.
Orginal suggestion can stand on it's own.

**Comment by eirannejad** [comment]
Sure thing. I’ll keep this open for the tool customizer tool.

**Comment by eirannejad** [comment]
Customization added for `Update`, `Extensions` and `Settings` tools in 4.6beta

**Comment by eirannejad** [comment]
Decided that pyRevit will not include a tool customizer interface. Users should customize the pyRevit deployment and include the tools they need. This also reduces the deployment size to users. Detailed description will be posted soon.

**Comment by UpMoJo** [comment]
Thanks, I hope customizing the deployment is fairly straight forward.



[PGAL]<http://www.pgal.com/>    CRAIG UPTMOR
Senior Associate
[cid:image3f50ea.JPG@321e5594.40a2ee58]
PGAL.COM<http://www.pgal.com/>
[Twitter]<https://twitter.com/PGALconnect>      [Facebook] <https://www.facebook.com/PGALconnect>       [LinkedIn] <https://www.linkedin.com/company/pgal>      [Instagram] <https://www.instagram.com/pgalconnect/>    [Youtube] <https://www.youtube.com/channel/UCHCMW44szUOhzMgYm9y2NLQ>

**Comment by eirannejad** [comment]
It is super simple. I’ll do a video soon
