### ISSUE TITLE
pyRevit Loader Error/ Attribute Error: _PyRevitRibbonTab obj has no attr. 'add_separator'

### ISSUE THREAD

**Issue by tillbaum** [eirannejad/pyRevit#361]
Hi, 
I have a AttributeError when I add my own extension: pyTiBa
I am doing this as described in your vids. Add a path in the Settings to my pytiba.extension folder, 
provide a json file in the same folder.
I don't know what the issue is. 
Thx

![pyrevit_loaderror_add_separator](https://user-images.githubusercontent.com/37901539/43359574-a0daf234-92a4-11e8-9349-59f24675e1e5.png)

**Comment by eirannejad** [comment]
I added a check in the code for this error. Update and see if it resolves the issue

**Comment by tillbaum** [comment]
Yes thats it. Really fast reply. Thanks very much. I am having this error since more than 1 month. Really annoying.
