### ISSUE TITLE
dimension override issue

### ISSUE THREAD

**Issue by Daryl360** [eirannejad/pyRevit#363]
could it be possible for there to be a way for me to create my own dimension overrides?

**Comment by thazell** [comment]
If you know a little python you can just duplicate the script and update the override value.
Are you wanting an input window that allows for overrides of many dimensions?

**Comment by Daryl360** [comment]
I'm new to Python, so I'm not sure how to do that. But I am wanting to create new override options besides the +/- and EQ ect.

**Comment by eirannejad** [comment]
What are the overrides that you want?

**Comment by Daryl360** [comment]
P.D (for panel dimensions) and R.O (for rough openings)

**Comment by eirannejad** [comment]
Resolved. More options added.

**Comment by Daryl360** [comment]
thank you!

**Comment by Daryl360** [comment]
do i just reload it or do i have to download the enhancement?

**Comment by eirannejad** [comment]
User pyRevit Update button. Let me know if you see errors. You can uninstall and reinstall if the normal update failed somehow.

**Comment by Daryl360** [comment]
I've used the update button, however the override dimension button still has only the same overrides. I'm gonna try reinstalling.

**Comment by Daryl360** [comment]
It worked!!! thanks alot!! Is it possible for the R.O and P.D ones to be available for below?

**Comment by eirannejad** [comment]
Added RO and PO below options
