### ISSUE TITLE
Problem with load PyRevit in Revit 2018.3

### ISSUE THREAD

**Issue by mgestwa** [eirannejad/pyRevit#364]
Hi,
I've installed PyRevit 4.5, but I have problem with load it in Revit. All times when I'm starting Revit a get this informations.
![1](https://user-images.githubusercontent.com/41877797/43423667-4aa25560-944d-11e8-991f-7c5995aae833.jpg)
![2](https://user-images.githubusercontent.com/41877797/43423679-50b076e4-944d-11e8-8979-8782afd2a1e5.jpg)
![3](https://user-images.githubusercontent.com/41877797/43423685-54d8b4ac-944d-11e8-8f36-6e370b5e7cae.jpg)

**Comment by eirannejad** [comment]
Hey reinstall and let me know if you still see this. This was a new bug that was introduced when I made some changes but I fixed it yesterday.

**Comment by mgestwa** [comment]
I did it yesterday and was ok, but today I have another problem.

```
INFO: [pyrevit.loader.sessioninfo] pyRevit version: 4.5:df417e6 -  with  in ['pdx', 'hio', 'rno']

INFO: [pyrevit.loader.sessioninfo] Host is Autodesk Revit 2018 (build: 20180423_1000(x64) id: 4580)

INFO: [pyrevit.loader.sessioninfo] Running on: 2.7.7 (IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (64-bit))

INFO: [pyrevit.loader.sessioninfo] Home Directory is: D:/PyRevit/pyRevit

INFO: [pyrevit.loader.sessioninfo] Session uuid is: 80890f07-94d8-11e8-8e2f-056331c82cb4

INFO: [pyrevit.loader.sessioninfo] Base assembly is: pyRevit_2018_3a7b1648e0e1e613_PyRevitBaseClasses

INFO: [pyrevit.loader.sessioninfo] Config file is: None

INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly parsed: pyRevitCore

INFO: [pyrevit.extensions.extensionmgr] Updating cache for ui_extension: pyRevitCore


ERROR: [pyrevit.userconfig] Can not save user config to: None | file name must be string, found NoneType

INFO: [pyrevit.extensions.extensionmgr] Skipping disabled ui extension: pyRevitDevTools


ERROR: [pyrevit.userconfig] Can not save user config to: None | file name must be string, found NoneType

INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly parsed: pyRevitTools

INFO: [pyrevit.extensions.extensionmgr] Updating cache for ui_extension: pyRevitTools


ERROR: [pyrevit.userconfig] Can not save user config to: None | file name must be string, found NoneType

INFO: [pyrevit.extensions.extensionmgr] Skipping disabled ui extension: pyRevitTutor
```

**Comment by eirannejad** [comment]
Hm this doesn't make any sense.
- Make sure users have write access to `%appdata%`.
- Make sure the file `%appdata%/pyRevit/pyRevit_config.ini` exists.
- Remove  `%appdata%/pyRevit/2018` directory (cache folder for pyRevit running in Revit 2018) and start Revit again

Let me know if this helps

**Comment by mgestwa** [comment]
I've deleted `pyRevit config.ini` and it has worked appropriately.

**Comment by eirannejad** [comment]
Nice! Glad it worked.
