### ISSUE TITLE
PyRevit in Revit 2016 - upgrade.bat file fails to load pyRevit

### ISSUE THREAD

**Issue by gmb99** [eirannejad/pyRevit#366]
Hi Ehsan,
When I try to use the upgrade.bat file it seems to install. When I open Revit, it fails to load PyRevit. My workaround has been to uninstall and then reinstall using the exe and check use latest update. Is there something I may be doing when running that bat file that would cause the program not to load? 

Thanks! Greg

**Comment by eirannejad** [comment]
Thanks Greg. What’s the load error? Would you be able to take a screenshot?

**Comment by eirannejad** [comment]
He needs to have a GitHub account and then we can @mention him in the issue tracker

**Comment by didyoureboot** [comment]
This is Kristian-I have just setup my account

**Comment by eirannejad** [comment]
Hey guys any updates on this? I'm changing the way the updater works so if you wait a bit, this issue will go away completely. :)

**Comment by eirannejad** [comment]
pyRevit's update and install mechanism is overhauled completely. See 4.6beta.
