### ISSUE TITLE
Method used to get User Desktop path fails for UNC paths

### ISSUE THREAD

**Issue by BrettBeckemeyer** [eirannejad/pyRevit#369]
The USER_DESKTOP variable set in `__init__.py` returns null when userprofile desktop is set to a UNC path. This causes several extensions to fail, most notably the Print extensions.

I'm using a workaround in our organization that modifies `__init__.py` (beginning at line 460):
```
USER_DESKTOP_PATH = op.expandvars('%userprofile%\\desktop')
if op.isdir(USER_DESKTOP_PATH):
	USER_DESKTOP = USER_DESKTOP_PATH
else:
	USER_DESKTOP = 'c:\Temp'
```

**Comment by BrettBeckemeyer** [comment]
I've also tried the method below, which relies on the winreg module. It works for me but I haven't tested across multiple platforms and setups.

`HKCU = ConnectRegistry(None,HKEY_CURRENT_USER)
regkey = OpenKey(HKCU, r'Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders')
USER_DESKTOP_PATH = QueryValueEx(regkey, 'Desktop')[0]`

**Comment by eirannejad** [comment]
So what is %userprofile% on your machine?

**Comment by eirannejad** [comment]
Added directory check for `USER_DESKTOP`. Fall back would be `USER_SYS_TEMP`. I believe that's guaranteed to be local.

**Comment by BrettBeckemeyer** [comment]
We use virtual machines and everything is run out of a single data center. So, our %USERPROFILE% is set to a convoluted UNC path that you can't really see unless you go into the registry.

**Comment by eirannejad** [comment]
I'm curious to see what kind of value the `%USERPROFILE%` holds.

**Comment by BrettBeckemeyer** [comment]
I poked around and %userprofile% works:
C:\Users\username

However, the Desktop shortcut under C:\Users\username redirects to:
\\cifs_svm01\persmgmt$\username\Desktop

So our Desktop (and a few other) folders have no local version or path.

Thanks for the update by the way. I'm a huge fan of pyRevit and I hope I can contribute!

**Comment by eirannejad** [comment]
Hmm very interesting. I'm building the desktop path using `%userprofile%/Desktop` and it's very interesting that it doesn't work.

Absolutely. Thanks for the error reports and feedback! :)
