### ISSUE TITLE
Replace Drafting View or Replace Sheet

### ISSUE THREAD

**Issue by chauhuh** [eirannejad/pyRevit#370]
I work with a lot of typical buildings that change their exterior wall types.

It would be great if there was a tool that could either replace one drafting view with another so that all of the section cuts do not need to be recreated.

Or, if there was a tool that could change multiple section cut  and view references across the plans to a different location.

Right now, I have multiple cuts layered on top of each other referencing all the possible design options, pun intended, and control what shows via filters.

Thanks.

**Comment by eirannejad** [comment]
Hmm I like this a lot! I think the first workflow (replacing views and updating existing references) is really helpful.
