### ISSUE TITLE
Windowed Selection for parts of objects only

### ISSUE THREAD

**Issue by chauhuh** [eirannejad/pyRevit#371]
Not sure how this would work. It would be nice to be able to multiple select the 'endpoints' of walls, lines, etc. of object so that you could group drag or stretch using a crossing window.

**Comment by eirannejad** [comment]
So Revit doesn't allow modifying the selection interface through the API. It also doesn't return subelements (end points) in document selection.

I don't know of any way to do this other than simplifying the selection and ask for start and end points of the drag vector maybe.

**Comment by chauhuh** [comment]
Well, we can't have everything now can we. Thanks for your informed response.

**Comment by eirannejad** [comment]
Haha ya I guess. Thanks for closing this.
