### ISSUE TITLE
Error with Find Sheeted Unreferenced Views

### ISSUE THREAD

**Issue by cellophane303** [eirannejad/pyRevit#372]
I'm getting an issue when trying to use the Find Sheeted but Unreferenced Views script.  It is pulling drafting views with problrms, but model views is throwing an error.  I opened the script to look at it but am not having any luck figuring out what's wrong.

![pyreviterror](https://user-images.githubusercontent.com/32309396/45568865-d6b39d00-b82b-11e8-9c7c-9843d224b28e.PNG)

Cheers!

**Comment by eirannejad** [comment]
Does it happen all the time? Would you tell me the steps to replicate the error? Or maybe an example of a model that this is happening on?

**Comment by cellophane303** [comment]
From what I can tell it happens all the time.  I tried it on a couple projects as well as a blank project created from the office template and a blank project created from the Construction template provided by Adesk.  It did however work fine on a blank project created using no template at all...   

And after a little more testing it appears the error has to do with 3D views being placed on sheets.  
https://www.screencast.com/t/Njn2CpAeZD

**Comment by eirannejad** [comment]
Okay I'll test it out. Thanks for reporting :)

**Comment by eirannejad** [comment]
Resolved. Thanks!
