### ISSUE TITLE
match nested families bug

### ISSUE THREAD

**Issue by chauhuh** [eirannejad/pyRevit#374]
benign bug

When using the tool on a family that may be nested such as a pile in a pile cap family the override will only apply to the top level element.

Thanks.

**Comment by eirannejad** [comment]
Sorry which tool is this for?

**Comment by chauhuh** [comment]
Sorry for not being clear. The match tool under modify (pyRevitToolspyRevitModifyMatch).

**Comment by eirannejad** [comment]
Resolved. will be pushed with 4.6beta 2 this weekend.
