### ISSUE TITLE
Batch sheet maker fails for sheets with dash in the sheet number

### ISSUE THREAD

**Issue by tomekpiatek** [eirannejad/pyRevit#375]
Trying to create sheets such as PD-001 fails with the error:

ERROR: [Batch Sheet Maker] Range start and end must have same length
ERROR: [Batch Sheet Maker] Aborted with errors.

**Comment by eirannejad** [comment]
Hmmm. Makes sense. Let me look into it.

**Comment by eirannejad** [comment]
Fixed. Range dividers revised to `--` and `::` to avoid conflict with possible single `-` and `:` in sheet numbers.
