### ISSUE TITLE
pyrevitgitservices stopped and unable to execute file

### ISSUE THREAD

**Issue by cridder** [eirannejad/pyRevit#376]
user is trying to install.  Probably the computer and a little of the user and network, etc

Thoughts!?

![3](https://user-images.githubusercontent.com/8334125/45833191-ee21d880-bcb8-11e8-9463-7f18c9dabc95.jpg)
![1](https://user-images.githubusercontent.com/8334125/45833192-ee21d880-bcb8-11e8-8f29-6eb93d68a6db.jpg)
![2](https://user-images.githubusercontent.com/8334125/45833193-ee21d880-bcb8-11e8-9afe-3c91ed6b2de6.jpg)

**Comment by eirannejad** [comment]
Could this be the fix? https://eirannejad.github.io/pyRevit/pyrevit/installer/2018/03/01/githubtlschange.html

**Comment by cridder** [comment]
cool.  thanks. i will forward to IT and see what they think.  later

**Comment by eirannejad** [comment]
New installer is coming soon. Hopefully these errors all go away!
