### ISSUE TITLE
Pick Detail Elements Behavior

### ISSUE THREAD

**Issue by chauhuh** [eirannejad/pyRevit#377]
Benign Bug?

Say I have a group of detail items that consist of lines, text, and some sub-groups of symbols (made of simple shapes). If I make a bounding box around everything the group is selected as expected. If I make a selection around some of the text nothing is selected, presumably because it is part of the group.

But if I make a selection around just of the nested groups it WILL select it. Not sure if this was intended behavior. I suppose it would be handy if the tool could work transparently or opaquely with groups.

Thanks.

**Comment by eirannejad** [comment]
No updates/responses. Closing for now.

**Comment by eirannejad** [comment]
Will revise as suggested.

**Comment by eirannejad** [comment]
Resolved. Group sub elements are not selected anymore.
