### ISSUE TITLE
Resolve issue finding the home directory on older RPS versions.

### ISSUE THREAD

**Issue by hienngocloveyou** [eirannejad/pyRevit#38]
Hi @eirannejad i have a issue with this tool, everything is ok, but the tool can not load button, maybe i miss some dll for this tool??

**Comment by eirannejad** [comment]
tell me more. What is the exact error you get??

**Comment by hienngocloveyou** [comment]
I just send email for you, can you check and please help me thanks !!

**Comment by eirannejad** [comment]
revised.
