### ISSUE TITLE
clear unused view filters kills revit

### ISSUE THREAD

**Issue by che-30** [eirannejad/pyRevit#382]
good afternoon!
the application crashes when launching the tool in the file with the Cyrillic filter names even when starting from the English-language interface

**Comment by che-30** [comment]
https://yadi.sk/d/DYuYZn2UtQLH2g

**Comment by eirannejad** [comment]
Resolved. https://github.com/eirannejad/pyRevit/commit/dedac93a709b2e0b6141cbed9192499732eb282c
