### ISSUE TITLE
Tag All Rooms in All Views fails

### ISSUE THREAD

**Issue by ponmy** [eirannejad/pyRevit#384]
Not sure what I'm doing wrong but any attempt to use "Tag All Rooms in All Views" results in an error.  I tried multiple projects, views, etc.

I tested "Tag All Spaces in All Views" and it works as expected.
[blank.pdf](https://github.com/eirannejad/pyRevit/files/2462571/blank.pdf)

**Comment by eirannejad** [comment]
Okay. Thanks for the report. Added error control and debug messages to the code. Will push this update with beta2 this weekend. Let me know if you need it before that.

**Comment by ponmy** [comment]
No rush.
