### ISSUE TITLE
Sum total

### ISSUE THREAD

**Issue by che-30** [eirannejad/pyRevit#386]
Hello! In the case of counting elements of the category "Parts" the command does not work. tested both EN and RUS interface
model 
https://yadi.sk/d/WFIY7UL7JBGwgA
IronPython Traceback
https://yadi.sk/d/qN_PD2voiY4t7Q

**Comment by eirannejad** [comment]
Okay. Reviewed the error. It's fixed in 4.6beta2 that I'll publish this weekend.
