### ISSUE TITLE
Print Ordered Sheet Index

### ISSUE THREAD

**Issue by alexdaversa** [eirannejad/pyRevit#387]
The logger.warning on line 133 of this tool's script.py is called for each placeholder sheet in the model. This loop through all sheets in the model & all sheets in the sheet index prints the warnings one line at a time, and delays the form from appearing for several minutes on large projects. On a project with 42 placeholder sheets and 20 architectural, nearly 4000 errors were generated.

It appears that at some point, this tool stopped functioning properly with placeholder sheets (the show non-printable and include non-printable buttons no longer work). I propose changing the logger.warning to logger.info until this tool can be re-evaluated.

I have tried this in the latest 4.5 and beta 4.6.

**Comment by eirannejad** [comment]
Thanks for the report. Will look into it soon.

**Comment by eirannejad** [comment]
Resolved. Will be pushed with next 4.6beta update this weekend
