### ISSUE TITLE
PyRevit Error while Loading. 

### ISSUE THREAD

**Issue by tussyswat** [eirannejad/pyRevit#391]
Hi. 
I just installed PyRevit and everytime I'm loading Revit I'm having a list of errors from the Python Console. 

here's a screenshot of the errors [](url)

![error-001](https://user-images.githubusercontent.com/1874901/47366739-4da24800-d6ac-11e8-8bfd-bd85932a4673.JPG)
![error-002](https://user-images.githubusercontent.com/1874901/47366740-4da24800-d6ac-11e8-8ece-2f15eb4367cf.JPG)

**Comment by eirannejad** [comment]
pyRevit is constantly being improved. Use the 4.6beta3 please. The installer and deployment mechanism has changed to avoid these errors.

https://github.com/eirannejad/pyRevit/releases
