### ISSUE TITLE
4.6-beta3 Installer errors while copying files from temp to install destination

### ISSUE THREAD

**Issue by tussyswat** [eirannejad/pyRevit#393]
I'm trying to install the new Beta version and it's giving me an error 

![pyerror](https://user-images.githubusercontent.com/1874901/47439824-0b940780-d77b-11e8-9e92-26ddc7c33b21.JPG)

**Comment by tussyswat** [comment]
after ignoring the error the install went through when loading two errors on the console I think its because of these elements missing during the install. 

![pyerror1](https://user-images.githubusercontent.com/1874901/47440205-b0aee000-d77b-11e8-9cb4-530f19473029.JPG)

**Comment by eirannejad** [comment]
The installer did not copy those two script files so the pyRevit runtime is notifying you that there are bundles with no scripts. I'm looking into why the installer failed. What's your complete install destination path?

**Comment by tussyswat** [comment]
yes 
I'm using windows 7 

The complete destination path it's the typical one 
I didn't specify any weird destination path. 

if you take a look at the first post there's a weird path calling a folder under your name 
it is that right ?

**Comment by eirannejad** [comment]
Hmm okay. Upon investigation it seems like the installer first copies the files into `%appdata%/Ehsan Iran-Nejad/install/BA0AC6E` directory as shown in your screenshot. Then copies from there to the final destination and somehow during this second copy process, fails to copy two files. Does it happen again if you uninstall and reinstall?

**Comment by eirannejad** [comment]
You might have an aggressive Antivirus maybe that removes the files while the installer is copying?

**Comment by eirannejad** [comment]
4.6.5 is out. Test with new version and open again if issue persists.
