### ISSUE TITLE
Error loading pyRevit: Missing set_ResizeBorderThickness method error

### ISSUE THREAD

**Issue by MikeRensing** [eirannejad/pyRevit#394]
I have installed the 4.6 beta 3 from the release section via the signed exe.  It installed fine, and the very first time Revit is run after installing runs fine.  Once I close out Revit and relaunch it, I get an error on launch and it fails to register the addin.  Attached is the screen shot of the error.

![pyrevitloader](https://user-images.githubusercontent.com/43816770/47517108-2d61bd00-d855-11e8-8d23-193f888016c5.PNG)

**Comment by eirannejad** [comment]
Hmm. Yea someone else also emailed about this yesterday. I'm looking into it. Sorry for the inconveniences.

**Comment by eirannejad** [comment]
Fascinating. No matter what do here in my VMs, I can't replicate the error.

**Comment by MikeRensing** [comment]
Do you have C:\Users\LeoW10 directory on your computer?  I don't and it appears to be looking for a file there.

**Comment by eirannejad** [comment]
Yes. Do you still see the error? The error window shows debug messages related to the source code and the line that the error happens on. It's not trying to find the file on your machine. It's telling me which source file has the error.

**Comment by MikeRensing** [comment]
I understand.  I just restarted Revit again, same error. It is odd that a repair will fix it again for the first run.

**Comment by oskyaqui** [comment]
Hi Ehsan,

My name is Oscar, I emailed you about the issue yesterday, here the information you requested, thanks a lot,

I run Windows 7 / Revit 2018.3

![image](https://user-images.githubusercontent.com/44623672/47806272-bc684c80-dd0f-11e8-8dc5-5cf8822e0717.png)

**Comment by eirannejad** [comment]
@oskyaqui Thanks for the info. I'll spend some quality time this weekend on this and hopefully will figure out a solution

**Comment by eirannejad** [comment]
Hey guys. Can one of you help me with resolving this issue?

Please replace this file:
`%APPDATA%\pyRevit-Master\pyrevitlib\pyrevit\__init__.py`

with the file inside this zip file:
[__init__.zip](https://github.com/eirannejad/pyRevit/files/2539725/__init__.zip)


then open a command prompt and run:
``` shell
pyrevit caches clear --all
```

Run your Revit multiple times and see if this fixes the issue. I'm guessing it's a dll binding issue.

**Comment by MikeRensing** [comment]
@eirannejad 
I downloaded and followed the instruction.  Same results.  First time it will work, subsequent times it breaks.
I can run the command to clear all caches just prior to launching Revit and it will work every time.

**Comment by eirannejad** [comment]
@MikeRensing See my post before yours. Would you be able to replace the specified file and test?

**Comment by eirannejad** [comment]
@MikeRensing Thanks. I'll dig deeper then.

**Comment by oskyaqui** [comment]
Hello, I tried multiple times but it did not solve the issue, even the first time I open Revit I got the same message, thanks,

**Comment by eirannejad** [comment]
One more test:
Replace:
`%APPDATA%\pyRevit-Master\pyrevitlib\pyrevit\loader\basetypes\scriptoutput.cs`

with:
[scriptoutput.zip](https://github.com/eirannejad/pyRevit/files/2540067/scriptoutput.zip)

Clear caches and test multiple runs.

Thank you for helping me test these. I really can't replicate the error on any of my machines or VMs

**Comment by MikeRensing** [comment]
@eirannejad 

That last fix worked for me.  Pyrevit launched successfully multiple times in a row.

**Comment by eirannejad** [comment]
So glad to hear that! :)

**Comment by oskyaqui** [comment]
Hello, 

It works for me too, thanks a lot!

Funny thing is I installed it in a colleague computer to test and never had the problem...

Thanks again,

**Comment by eirannejad** [comment]
Awesome. Closing this and will publish the change with 4.6.5 this weekend.
