### ISSUE TITLE
PyRevit 4.6.3 not launching in Revit 2017.2.3

### ISSUE THREAD

**Issue by wizkid-charizard** [eirannejad/pyRevit#396]
Hello,

I have installed previous versions on other machines and the installation always went well. This time with 4.6.3 when trying to install it from a scratch to a new workstation, the installation goes well, I can see PyRevit installed successfully in Control Panel, however when I launch Revit I don't get the pop-up to "Always Load" and I can't see the extra tab for PyRevit in Revit. Any suggestions how I can resolve this will be much appreciated. I have Windows 10 and Revit 2017.2.3. 
Thank you

**Comment by eirannejad** [comment]
Please open command prompt on your machine and run:
``` shell
pyrevit revits --installed
```
and paste the results here please.

**Comment by eirannejad** [comment]
4.6.5 is out. No response. Test with new version and open again if issue persists.
