### ISSUE TITLE
Is it possible to use pyRevit scripts to connect to Airtable?

### ISSUE THREAD

**Issue by bow-pow** [eirannejad/pyRevit#399]
Hi,
Maybe it's a dumb question but I was wondering is there a way we can use pyRevit to vommunicate with airtable?

I made a python script on 2.7.7 that Reads airtable and update it based on ecported revit schedule. To make it as a plugin I was giving pyRevit a try. The script has dependencies on airtable-python-wrapper and that's where things break down for the plugin. 
Is there a functionality/integration in pyRevit to use Airtable api for read and write? If not, then any plans in near future?
Thanks

**Comment by eirannejad** [comment]
You can use a python module to access airtable api
https://github.com/gtalarico/airtable-python-wrapper
