### ISSUE TITLE
Smart Join Tool

### ISSUE THREAD

**Issue by tahaij** [eirannejad/pyRevit#400]
dear all,
Is it even possible to have some kind of element join tools, to join unjoin objects based on selection and proximity using Pyrevit

**Comment by eirannejad** [comment]
What kind of object? Like a floor to an exterior wall type of join?

**Comment by tahaij** [comment]
object like wall to floor, Structural framing to floor & Wall only if they are intersecting, Wall with Structural Columns & Framing elements. Either through selection or visibility in view. I tried it doing though Dynamo but it joined everything with everything else and end result was a very unruly & slow model, on which it was impossible to work without getting Unjoin nag screen.

**Comment by tahaij** [comment]
I missed it thoank you for your Prompt response it was nice. :)

**Comment by tahaij** [comment]
Thank you For your prompt response it was very nice :)

**Comment by eirannejad** [comment]
I'll keep this open and will look into it.

**Comment by tahaij** [comment]
Thanks for taking this up, Attached is the dynamo node for join but, the missing element is the filters which me, with my limited knowledge, was not able to figure out
[JoinDynamoNodes.zip](https://github.com/eirannejad/pyRevit/files/2537262/JoinDynamoNodes.zip)
