### ISSUE TITLE
pyRevit 4.6.4 issues

### ISSUE THREAD

**Issue by cpercer** [eirannejad/pyRevit#401]
Hello,

I receive the following errors when opening Revit 2018.3:

![pyrevitpopup1](https://user-images.githubusercontent.com/44647473/47801441-368ed600-dcfc-11e8-876d-f1b6ab34edc9.JPG)
![pyrevitpopup2](https://user-images.githubusercontent.com/44647473/47801442-368ed600-dcfc-11e8-8116-ecce321d13c1.JPG)

**Comment by eirannejad** [comment]
:/

**Comment by pzyskowski42** [comment]
Similar issue here... Not the same message.  Revit 2019.1. Worked fine the day I installed.  Next day this.  Should I log it as a separate issue?
![pyrevit loader error](https://user-images.githubusercontent.com/44787108/48025570-d6d86680-e111-11e8-9dee-615952f1bc8c.jpg)

**Comment by eirannejad** [comment]
Resolved in 4.6.5
Please install and test.
