### ISSUE TITLE
utf-8 encoding

### ISSUE THREAD

**Issue by epeter-** [eirannejad/pyRevit#402]
version pyrevit 4.5 including all updates
my simplified code:
`# -*- coding: utf-8 -*-

excelFile = **"C:\\Öüöä.xlsx"**

excelWb = excel.Workbooks.Open(excelFile)

excelSheet = excelWb.Worksheets[1]
.....
`
causes an exception:
`File "C:\ProgramData\pyRevit\pyRevit-v45\pyRevit\pyrevitlib\pyrevit\coreutils\charts\__init__.py", line 178, in draw
 File "json\encoder.py", line 408, in _iterencode_dict
 File "json\encoder.py", line 390, in _iterencode_dict
File "json\encoder.py", line 47, in py_encode_basestring_ascii
 File "C:\ProgramData\pyRevit\pyRevit-v45\pyRevit\pyrevitlib\pyrevit\coreutils\charts\__init__.py", line 150, in _make_charts_script
 File "json\encoder.py", line 209, in encode
 File "json\encoder.py", line 443, in _iterencode
 File "json\encoder.py", line 434, in _iterencode
 File "json\encoder.py", line 408, in _iterencode_dict
 File "json\encoder.py", line 443, in _iterencode
 File "json\encoder.py", line 434, in _iterencode
UnicodeDecodeError: ('unknown', u'\xd6', 30, 31, '')`

so far so good.
trying to encode the filename like:
`excelFile = **"C:\\Öüöä.xlsx"**.encode(utf8)`

results in:
`EnvironmentError: System.Runtime.InteropServices.COMException (0x800A03EC): Sorry, we couldn't find **C:\????????.xlsx**. Is it possible it was moved, renamed or deleted?
 bei Microsoft.Scripting.ComInterop.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, UInt32 argErr, String message)`

along that problem i found out that parts of pyrevit (charts) need utf-8 encoding in an encoded script while others (output.table) encode according to the directive in the first line of script.

**Comment by eirannejad** [comment]
Whats this? What are the `**`?
`excelFile = **"C:\\Öüöä.xlsx"**.encode(utf8)`
Shouldn't it be:
`excelFile = "C:\\Öüöä.xlsx".encode('utf8')`

**Comment by eirannejad** [comment]
Tested and this works on python or IronPython versions > 2.7.3
``` python
'C:\\Öüöä.xlsx'.encode('utf8')
```

**Comment by epeter-** [comment]
Answering: the **"C:\\Öüöä.xlsx"**.encode('utf8') is just a forum formatting command for "bold" shouldn't be visible. -Sorry
Question: did your code in your test  find the respective file?
If yes that is interesting. I will check from my side too

**Comment by eirannejad** [comment]
Yes in my initial testing. Send me your example code so I can test.
