### ISSUE TITLE
Set __doc__ and __title__ in c# Script

### ISSUE THREAD

**Issue by Tomey77** [eirannejad/pyRevit#404]
Hi,

I was wondering if c# had something like the __doc__ and __title__ variables in python script. 
Would be great to add some more information for users to my c# scripts.

Thanks
Tim

**Comment by eirannejad** [comment]
Implemented and will be pushed with 4.6.5
Now you can define public class fields for pyrevit fields with same names:
`__context__` is not supported since C# commands support implementing `IExternalCommandAvailability`:

``` csharp
   public class CSharpTest: IExternalCommand
   {
      public const string __title__ = "My Custom Title";
      public const string __doc__ = "HelloWorld Testing tooltip";
      public const string __author__ = "{{author}}";
      public const string __helpurl__ = "{{docpath}}";
      public const string __min_revit_ver__ = "2018";
      public const string __max_revit_ver__ = "2018";
      public const bool __beta__ = false;

      public Autodesk.Revit.UI.Result Execute(ExternalCommandData revit,
         ref string message, ElementSet elements)
      {
         TaskDialog.Show("Revit", "Hello World!!!");
         return Autodesk.Revit.UI.Result.Succeeded;
      }
   }
```

**Comment by alitehami** [comment]
@eirannejad is there anyway currently to get access to the 'command_path' from a c# script?

**Comment by eirannejad** [comment]
Not at the moment. I'll add this to the list
