### ISSUE TITLE
Is it possible to install 4.6 to a specific user account or  all users?

### ISSUE THREAD

**Issue by two9seven** [eirannejad/pyRevit#408]
I work in a managed environment where users cannot install programs with out administrator privileges. Normally we install addins to the %programdata% location so they show up for non admins when an admin installs for them. Any ideas for a workaround?
Thanks, 
Donovan

**Comment by eirannejad** [comment]
pyRevit uses [Advanced Installer](https://www.advancedinstaller.com/). You can use the silent install options to install pyRevit wherever you want. After installation you can use [pyRevit CLI](https://www.youtube.com/watch?v=PMc02W-oAo4&t=1s) tool to configure the pyRevit environment. I'll do a video on these soon.
