### ISSUE TITLE
Command line argument for 4.5 installer to point to 4.5 release. 

### ISSUE THREAD

**Issue by two9seven** [eirannejad/pyRevit#409]
Is there a command line argument for the 4.5 installer to force the installation of the 4.5 release? I was able to manually point the installer here but I would like to script it for deployments. 
https://github.com/eirannejad/pyRevit/releases/tag/v4.5

Thanks, 
Donovan

**Comment by eirannejad** [comment]
pyRevit 4.5 is obsolete and not supported anymore. You'd need to clone the repo and checkout the 4.5 tag manually. Highly suggest staying updated with the changes and use the most recent version.

Also see: https://github.com/eirannejad/pyRevit/issues/408

**Comment by two9seven** [comment]
Thanks. In case anyone is interested here are the commands I used to install pyrevit 4.6.5 for my users. 
```
cmd pyRevit_4.6.5_signed.exe /q APPDIR="C:\Program Files\pyRevit_4.6.5"
cmd pyrevit attach master dynamosafe --installed --allusers 
```
Watch the CLI video too 
https://www.youtube.com/watch?v=PMc02W-oAo4&t=1s

**Comment by eirannejad** [comment]
@two9seven Thanks a bunch
I'll post a video on this soon. Sorry for troubles if any.
