### ISSUE TITLE
output names of groups which contain text elements to text file on desktop

### ISSUE THREAD

**Issue by ThubanPDX** [eirannejad/pyRevit#41]
Since the API cannot edit groups, when the select all text option is checked if it could spit out or in a separate command spit out the list of groups which need to be looked at into a text file on the desktop it would greatly speed up tracking down  spelling issues.

**Comment by eirannejad** [comment]
Groups_listAllGroupsWithTextNotes.py
The script lists all the groups with TextNote elements in the output window.
