### ISSUE TITLE
Add bulk changes to Package Manager

### ISSUE THREAD

**Issue by ponmy** [eirannejad/pyRevit#410]
Please consider adding the ability to multi-select and make bulk changes while using Package Manager tool.

**Comment by eirannejad** [comment]
Would you give me a use case example? the package manager automatically commits your sheets to the latest package. it also creates automatic "issued" commits for all other packages.

Do you want this to mass change sheets to update?

**Comment by ponmy** [comment]
All my sheets showed up as being created in the second phase when they really should have been created in the first phase.  I think this is because I created both parameters before I ran Manage Packages for the first time.  I found myself having to set each sheet as being created in the first phase and I thought it would have been nice to select all of them and change them all at once instead of individually.

The use case is for people like me who used the tool wrong and now need to correct things.

Now that I know better, I'll add just the first phase parameter, run the tool, then proceed to add additional parameters.

**Comment by ponmy** [comment]
Another use case would be if you wanted to add all the typical phase parameters to your template.  As you add sheets during the project they would always default to the latest and need to be changed.

If you are adding 50+ sheets during the project, as I often am, it would be nice to change them all at once.

The answer here is probably to not add all the parameters to my template. :)

**Comment by eirannejad** [comment]
Got it. Sorry about the inconvenience.

**Comment by ponmy** [comment]
No need to apologize.  I'm just brainstorming on how to make it slightly better.  It already totally rocks!

**Comment by eirannejad** [comment]
Extension manager now allows Enabling/Disabling multiple extensions at once. Will be pushed with 4.6.14
