### ISSUE TITLE
install addin bat file missing in 4.6.5?

### ISSUE THREAD

**Issue by bushclandan** [eirannejad/pyRevit#411]
after install with the installer, add-in tab is not present in revit.  no add-in file is created in addins folder.  there is no "release" folder under "pyRevit-Master" to run the batch file.

tried to create an pyRevit.addin file from a previous post but get a page full of errors at launch.  Perhaps the guid for the AddInId is wrong...

![pyrevit errors](https://user-images.githubusercontent.com/25707637/48108991-49793d00-e20b-11e8-8df7-7f0db0cb5a88.png)

**Comment by bushclandan** [comment]
More info:

Visual studio installed.

Control panel shows IronPython 2.7.3; Python 3.6.5 & 3.6.6 installed as well.

**Comment by eirannejad** [comment]
The deploy mechanism has changed. See videos below:
[pyRevit CLI](https://www.youtube.com/watch?v=PMc02W-oAo4)
[New Distribution Model](https://www.youtube.com/watch?v=VZdgrh_US68)
