### ISSUE TITLE
"Unrecoverable Error" on Loading (4.5.2 and 4.6.5) - System.AccessViolationException

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#413]
We are running into an issue with our pyrevit deployement which locks in version 4.5.2.
however, the same error occurs in the latest install, `4.6.5_signed`

![image](https://user-images.githubusercontent.com/9513968/48161179-f0131b80-e2a7-11e8-87f5-bbb874672707.png)

Our users are hitting fatal exception right after the "Load" Addin prompt. 
Users isolated the error to pyrevit by uninstalling all other revit extensions.

This error is happening to several (10+ users), but not all.
Here is what I know so far:

* Revit loads fine if pyrevit is not loaded (Click"Don't Load" in the unsigned addin prompt, or renaming the `.addin` file)
* the main `__init__.py` is running all the way to end (I added code to write to log file)
* Journal file logs the error, but contains nothing helpful (below)
* Running with Visual Studio Debugger attached shows the error listed below
* After removing our 4.5.2 install, and installing 4.6.5 fresh, the same error occurs.
* Pyrevit Loader windows never appears 
* `.dll` in `%appdata%\Roaming\pyRevit\2017` is never created
* on 4.6.5, .ini file only has clones entry, so file is never created

Any ideas for how to further troubleshoot or resolve this @eirannejad ?
What's the easiest way to get logging info from the loading process these days?

Thanks!

![image](https://user-images.githubusercontent.com/9513968/48159426-25693a80-e2a3-11e8-94d5-be67d712a009.png)

``` 
'Revit.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'IronPython.Modules.DynamicAssembly'. 
An unhandled exception of type 'System.AccessViolationException' occurred in IronPython.Modules.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

![image](https://user-images.githubusercontent.com/9513968/48159314-d91dfa80-e2a2-11e8-9371-eb89f91783ad.png)

![image](https://user-images.githubusercontent.com/9513968/48159344-ec30ca80-e2a2-11e8-89d4-616359821d22.png)

![image](https://user-images.githubusercontent.com/9513968/48159526-6eb98a00-e2a3-11e8-9ec2-b22c1629844b.png)

# Journal
[journal.0061.txt.copy.txt](https://github.com/eirannejad/pyRevit/files/2559192/journal.0061.txt.copy.txt)

# Update
Launched with VS + Symbols to get more info.
Memory Exception is happening inside `PyRevitLoader.py`
![image](https://user-images.githubusercontent.com/9513968/48161811-80059500-e2a9-11e8-93d8-d758bd892d68.png)

**Comment by eirannejad** [comment]
So let me get this right. You have been using 4.5.2 till now and this just started to happen??

**Comment by gtalarico** [comment]
> So let me get this right. You have been using 4.5.2 till now and this just started to happen??
Yes. We have a fork of the project that we deploy using a custom deployer tool.
A subset of our users started having this issue, the number has grown over the last 2 months to 10-20 users. 
I have not been able to pin down any patterns (computer type, revit build, etc)
Recently, I wiped 4.5.2 from a few computers, and installed 4.6.5 fresh, but the problems remains the same.

What's the easiest way to get logging info from the loading process these days?

**Comment by eirannejad** [comment]
Logging system is same as before. `filelogging = True` in config will write all logs to the file but they're all pyRevit load related.

This seems to be a memory access violation inside the IronPython module. To me it seems to be a CLR issue more that anything else since python is running inside the CLR environment and all memory accesses are managed by the CLR.

Is there any chance for virus affecting the dlls trying to inject something into memory? (sounds stupid I know). Does it work in isolated VM environment?

**Comment by nestyle** [comment]
I am also getting the unrecoverable error on 2019 with 4.6.5 installer.
To get pyrevit to load without an error I have to disable modplus plugin.
In the log below there is reference to a different user name.
"C:\Users\LeoW10\AppData\Roaming\pyRevit\pyRevit\dev\pyRevitLoader\Source\ScriptExecutor.cs"


**Journal File Error**
' 0:< TaskDialog "Traceback (most recent call last):
'  File "C:\Users\---\AppData\Roaming\pyRevit-Master\bin\engines\pyRevitLoader.py", line 32, in <module>
'  File "C:\Users\---\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\loader\sessionmgr.py", line 215, in load_session
'  File "C:\Users\---\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\loader\sessionmgr.py", line 64, in _setup_output
'TypeError: Value cannot be null.
'Parameter name: dp
'
'
'System.ArgumentNullException: Value cannot be null.
'Parameter name: dp
'   at Microsoft.Scripting.Interpreter.NewInstruction.Run(InterpretedFrame frame)
'   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
'   at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
'   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
'   at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
'   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
'   at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
'   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
'   at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
'   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
'   at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
'   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
'   at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
'   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
'   at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
'   at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
'   at Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
'   at PyRevitLoader.ScriptExecutor.ExecuteScript(String sourcePath) in C:\Users\LeoW10\AppData\Roaming\pyRevit\pyRevit\dev\pyRevitLoader\Source\ScriptExecutor.cs:line 70"
'CommonButtons : Close
'DefaultButton : Close 
' 0:< ::36:: Delta VM: Avail +2 -> 134215735 MB, Used 396 MB; RAM: Avail -15 -> 28414 MB, Used +3 -> 590 MB, Peak +3 -> 591 MB 
' 0:< GUI Resource Usage GDI: Avail 9772, Used 228, User: Used 210 
'H 08-Nov-2018 10:35:18.322;   0:< 
Jrn.Data "TaskDialogResult"  _
        , "Traceback (most recent call last):" & vbLf & "  File ""C:\Users\---\AppData\Roaming\pyRevit-Master\bin\engines\pyRevitLoader.py"", line 32, in <module>" & vbLf & "  File ""C:\Users\---\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\loader\sessionmgr.py"", line 215, in load_session" & vbLf & "  File ""C:\Users\---\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\loader\sessionmgr.py"", line 64, in _setup_output" & vbLf & "TypeError: Value cannot be null." & vbLf & "Parameter name: dp" & vbLf & "" & vbLf & "" & vbLf & "System.ArgumentNullException: Value cannot be null." & vbLf & "Parameter name: dp" & vbLf & "   at Microsoft.Scripting.Interpreter.NewInstruction.Run(InterpretedFrame frame)" & vbLf & "   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)" & vbLf & "   at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)" & vbLf & "   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)" & vbLf & "   at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)" & vbLf & "   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)" & vbLf & "   at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)" & vbLf & "   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)" & vbLf & "   at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)" & vbLf & "   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)" & vbLf & "   at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)" & vbLf & "   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)" & vbLf & "   at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)" & vbLf & "   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)" & vbLf & "   at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)" & vbLf & "   at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)" & vbLf & "   at Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)" & vbLf & "   at PyRevitLoader.ScriptExecutor.ExecuteScript(String sourcePath) in C:\Users\LeoW10\AppData\Roaming\pyRevit\pyRevit\dev\pyRevitLoader\Source\ScriptExecutor.cs:line 70",  _
         "Close", "IDCLOSE"
' 0:< API_SUCCESS { Starting External Application: PyRevitLoader, Class: PyRevitLoader.PyRevitLoaderApplication, Vendor : eirannejad(), Assembly: C:\Users\---\AppData\Roaming\pyRevit-Master\bin\engines\277\pyRevitLoader.dll }

**Comment by gtalarico** [comment]
@nestyle although you are also getting an *Unrecoverable Error*, it looks like a different error and cause. Your journal shows a full traceback and `System.ArgumentNullException`. 
Mine has Journal shows no error details and raises an `AccessViolationException`

**Comment by nestyle** [comment]
no probs

**Comment by eirannejad** [comment]
@gtalarico You're a rock star! Thanks for spending the time on this. pyRevit has been reconfigured to use the native Dotnet GUID module instead of python `uuid` module.

Updates will be pushed in 4.6.6 this week.
