### ISSUE TITLE
External Properties/Project Browser palettes disables ribbon

### ISSUE THREAD

**Issue by urbancamoman** [eirannejad/pyRevit#414]
Running Revit 2018.3.2. Installed pyRevit version 4.6.5

Working with the Properties and Project Browser palettes docked in the main window causes no issues to navigating through the ribbon. Once palettes are externalised from the main drawing window (on a second monitor for instance), ribbon becomes non-responsive to browsing through and most buttons become greyed out.

**Comment by urbancamoman** [comment]
Further behaviour info:

Seems if I double click another drawing in the Project Browser window and go to that view, ribbon becomes responsive again. However single clicking and just highlighting another drawing in the PB, suddenly ribbon become unresponsive.
Behaviour only seems to occur when working between PB and main drawing window. Clicking through Properties box doesnt seem to initiate it. Hope this helps.

**Comment by eirannejad** [comment]
This does not seem to be a pyRevit issue. Revit calls an **Availability** method on all buttons when user changes views (context changes). Please see if the same behavior happens on other panels.

**Comment by urbancamoman** [comment]
Can confirm the same behaviour happens with the MEP and P&ID panels. Not however with the System Browser panel.

**Comment by eirannejad** [comment]
Thanks!
