### ISSUE TITLE
Unable to install Extensions

### ISSUE THREAD

**Issue by ponmy** [eirannejad/pyRevit#415]
I'm not able to install any extensions:

![error](https://user-images.githubusercontent.com/43487371/48303552-a7867880-e4c8-11e8-87d0-77dffab397e0.gif)

**Comment by eirannejad** [comment]
Okay. Add a destination path to the user extensions in pyRevit settings. Then this will allow you to install extensions there. I’ll modify and add prompts and default paths to this.

**Comment by eirannejad** [comment]
- [ ] Define a default extensions directory under `%appdata%` for extensions installs
- [ ] Add the default path to the core

**Comment by che-30** [comment]
hey,
I'm not able to install any extensions:
+1
![image](https://user-images.githubusercontent.com/19819439/48486870-b5702c80-e82d-11e8-8862-a608c0eaf806.png)

**Comment by che-30** [comment]
![image](https://user-images.githubusercontent.com/19819439/48487048-23b4ef00-e82e-11e8-9277-11241d0ec3e9.png)

**Comment by eirannejad** [comment]
Resolved. Will be pushed with 4.6.7 next week.
Default third-party installation path is defined as `%appdata%/pyRevit/Extensions` now.
