### ISSUE TITLE
Missing pyRevit addin - Revit 2019, pyRevit 4.6.5

### ISSUE THREAD

**Issue by N1M49** [eirannejad/pyRevit#416]
Revit version: 19.0.0.405
Build number: 20180216_1515(x64)

After installing with the installer, the addin did not appear in Revit. 
I also tried the manual installation, but the install_addin.bat file is missing.

![capture](https://user-images.githubusercontent.com/24602853/48306698-55f5f080-e591-11e8-9d7e-68656f44cc77.PNG)

**Comment by eirannejad** [comment]
Okay seems like pyrevit finds your Revit correctly but the clone that you have made is not listed. Where did you install pyRevit under? By default it is installed under `%appdata%/pyRevit-Master`

Make sure it is there and please share the full path here so I can see if there is any special characters in the path.

**Comment by N1M49** [comment]
Yes, it's under %appdata%

Full path: 
C:\Users\Amin's PC\AppData\Roaming\pyRevit-Master

**Comment by eirannejad** [comment]
Oh lord. `'` in username??? 🗡 🤣

Okay. Thanks for reporting this. I'll take a look and will revise the code to be smart about this.

Meanwhile. Uninstall pyRevit and reinstall under a path that does not have special character in it. You can install under `%programfiles%`. Let me know if it works.

**Comment by sauravs142** [comment]
does the pyrevit installer works on revit 2019 version?
