### ISSUE TITLE
Installation Error \ release 4.6.5 on Revit 2019

### ISSUE THREAD

**Issue by bob13333** [eirannejad/pyRevit#417]
Hi, i tried installing your new release 4.6.5 but i get the error below:

[MSIF483.LOG](https://github.com/eirannejad/pyRevit/files/2569481/MSIF483.LOG)

**Comment by eirannejad** [comment]
Hm. I have no idea why this happens. Maybe antivirus is messing with the install?

**Comment by eirannejad** [comment]
Merged into: https://github.com/eirannejad/pyRevit/issues/421
