### ISSUE TITLE
View ordering Tool

### ISSUE THREAD

**Issue by jkcameron** [eirannejad/pyRevit#418]
It seems view ordering tool (renumbering tool) produces an error if there is a schedule on the sheet.  Sheets without schedules have no problems.

**Comment by Archithead** [comment]
I would also add that the tool appears not to work when a legend is on a sheet as well.

**Comment by eirannejad** [comment]
Resolved the issue with legends. Can not replicate the issue with Schedules. runs fine on my tests. Would you be able to share a file that has the issue? Thanks

**Comment by eirannejad** [comment]
Closing this for now. Updates will be pushed in 4.6.6 this weekend. Test and feel free to open the issue again if it persists.

**Comment by jkcameron** [comment]
thanks a lot man... maybe i was wrong about the cause... Unfortunately I'm unable to share the file with the problem.  I'll try and narrow it down more and get back to you.  Thanks for being so quick.  You are awesome.
