### ISSUE TITLE
Unable to install on Windows 10

### ISSUE THREAD

**Issue by superwba** [eirannejad/pyRevit#420]
Hi,

The PC has Revit 17,18 and 19 installed. When i try to install it fails and gives an error. Tried run as admin and compatabilty mode for W7 and W8.

Any ideas?

[MSIB50.LOG](https://github.com/eirannejad/pyRevit/files/2574546/MSIB50.LOG)

**Comment by eirannejad** [comment]
Merged into: https://github.com/eirannejad/pyRevit/issues/421
