### ISSUE TITLE
Installer Error

### ISSUE THREAD

**Issue by eirannejad** [eirannejad/pyRevit#421]
Users have been helped on these issues so they can continue work for the most part but installer logs need to be reviewed. Core issue is still unknown to me:

https://github.com/eirannejad/pyRevit/issues/420
https://github.com/eirannejad/pyRevit/issues/419
https://github.com/eirannejad/pyRevit/issues/417
https://github.com/eirannejad/pyRevit/issues/397
https://github.com/eirannejad/pyRevit/issues/407
https://github.com/eirannejad/pyRevit/issues/422

Logs:

[MSIB50.LOG](https://github.com/eirannejad/pyRevit/files/2577373/MSIB50.LOG)
[MSIE813.LOG](https://github.com/eirannejad/pyRevit/files/2577374/MSIE813.LOG)
[MSIF483.LOG](https://github.com/eirannejad/pyRevit/files/2577375/MSIF483.LOG)
[MSI56D5_20181107.LOG](https://github.com/eirannejad/pyRevit/files/2577392/MSI56D5_20181107.LOG)
[MSI543B.LOG](https://github.com/eirannejad/pyRevit/files/2577393/MSI543B.LOG)
[MSI43FB.LOG](https://github.com/eirannejad/pyRevit/files/2601072/MSI43FB.LOG)
[pyRevit.Failed.Instal.Log.v4.6.8.txt](https://github.com/eirannejad/pyRevit/files/2626529/pyRevit.Failed.Instal.Log.v4.6.8.txt)

**Comment by TyHearn** [comment]
Did Issue 397 ever get resolved? I'm having the same issue when trying to uninstall

**Comment by eirannejad** [comment]
No. I organized all here under a single issue since they're all basically the same, just represented differently.

**Comment by eirannejad** [comment]
Seems like `PROPERTY CHANGE: Adding FASTOEM property. Its value is 1.` is the issue. Disabling Fast Install option in Advanced Installer and will publish for testing.

**Comment by eirannejad** [comment]
Published 4.6.6 with a few attempts at resolving these issues:
- Default install path has been changed to `%PROGRAMFILES%/pyRevit-Master` to avoid having usernames in install path
- Fast installation method has been disabled on the installer which seemed to be the source for the fatal errors in installer logs

**Comment by varunbose** [comment]
Hi Eshan,

Installed 4.6.6_Signed on Win 10 (Revit 2018.3) fine.
But giving this error on opening Revit.  I think v4.6.6 still has the installer issue.

![image](https://user-images.githubusercontent.com/36495233/48811468-07f79e80-ed82-11e8-9b50-db69744d0136.png)

**Comment by varunbose** [comment]
Hi Eshan,

Found this thread in Stackoverflow claiming resolved this same issue.
[(https://stackoverflow.com/questions/52359277/revit-cannot-run-external-aplication-pyrevit)]

Don't know whether to try that Dependencies.exe
Some other fourms says .net framework conflict (for some other addins error).

Desperate to get this running on my colleagues machine to showoff my new scripts (which is running fine in my machine (Win 7, pyRevit 4.5, installed almost 8 months before))

**Comment by eirannejad** [comment]
Is `Q:` a network drive?

**Comment by varunbose** [comment]
Yes, But Q:\Program is only the folder of the installer file. Installed in c:Programs\Pyrevit-Master

**Comment by varunbose** [comment]
Its bit strange..
Un-installed pyrevit.
Copied the installer to C:
Installed 4.6.6_Signed (while installer in C:)
Same error and still shows Q:\Programs\pyMaster....dll. 

When tried to rename the folder in Q:\Program, Access denied. (Revit was closed)

**Comment by varunbose** [comment]
Hi Eshan,

Just noticed that you released 4.6.8. Thanks for that.
Installed fine on my machine where it had 4.5 working (Win 7 pro) (Today morning I pressed PyRevit update button and endup with pyRevit.loader error (4.5) after this. So downloaded 4.6.8 & works fine now).
Tried luck on my colleagues machine (Win 10), but same pyRevit Loader error. Guess Error 421 still not resolved.
Hope you will resolve this soon.

**Comment by varunbose** [comment]
Just an update.

After installing and cleaning the residue files for multiple times, pyRevit menu is working now. But noticed that it wasn't copying the Add-in file to "roaming folder". So when you fire up Revit after installation, there was no buttons. So I copied the add-in file from another machine & its working now.

So I guess 4.68 Installer is perfect.

Thanks..

**Comment by eirannejad** [comment]
Thanks for the update @varunbose and I apologize for the troubles. User environments are not as consistent as we all like them to be so there are issues at every major change that needs to be resolved. But I believe we're moving in the right direction with the new deployment method and the CLI tool.

Thanks!

**Comment by varunbose** [comment]
I have to watch the CLI tool video before deploying pyRevit in next machine..
Thanks a lot Eshan

**Comment by TyHearn** [comment]
Hi, When I try to install 4.6.8 it ends prematurely and I get this error log.
[MSI11BA.LOG](https://github.com/eirannejad/pyRevit/files/2629336/MSI11BA.LOG)

**Comment by eirannejad** [comment]
@DmytroSE Please open a command prompt, run `pyrevit env` and share the results. If Revit 2019 is not listed under installed Revits in command results, grab the Revit build code and exact version from the About menu and send me those as well so I build into the code.

**Comment by DmytroSE** [comment]
@eirannejad Thx for reply. Here it is
![error2](https://user-images.githubusercontent.com/45512632/49332263-cbfadf80-f5b2-11e8-8b84-1bdab64fe4a5.PNG)

I have created pyrevit.addin file by myself using video from pyrevit channel. Now it works fine.

**Comment by eirannejad** [comment]
Ya in the new installer I changed the default install location to outside of appdata. Seems like it’s helping

**Comment by eirannejad** [comment]
Fixed issue with pathnames with unicode and special characters. The new attached will be published with pyRevit 4.6.9 this week.
