### ISSUE TITLE
Add-in Assembly Not Found

### ISSUE THREAD

**Issue by TyHearn** [eirannejad/pyRevit#422]
Hi, 

I'm currently trying to install pyRevit on my colleagues computers. and keep getting this error.

![initialization error](https://user-images.githubusercontent.com/45016326/48440745-b5056200-e757-11e8-99c7-492813b0fe7e.jpg)

For some reason I was able to install it fine on my machine but when they try to start up Revit after installing it seems to be trying to reference back to my machine and fails.

Any ideas?

Not sure if this has anything to do with it, but, it created a pyRevit - Master folder in my AppData folder when i installed it

**Comment by eirannejad** [comment]
Which Revit version? Would you mind opening a command prompt and run `pyrevit env` and share results here?

**Comment by TyHearn** [comment]
2018.3

![command prompt](https://user-images.githubusercontent.com/45016326/48485111-f93f4380-e7e5-11e8-940a-7b72e9b24cdf.PNG)

**Comment by TyHearn** [comment]
Here is the command prompt screen from my colleagues computer

![image](https://user-images.githubusercontent.com/45016326/48487407-2b53a400-e7ec-11e8-8ff7-7917a4fb6d88.png)

**Comment by TyHearn** [comment]
Mine
C:\Users\ty\AppData\Roaming\pyRevit-Master

My colleagues
C:\Users\student\AppData\Roaming\pyRevit-Master

**Comment by eirannejad** [comment]
Add this path to your system paths:
`C:\Users\ty\AppData\Roaming\pyRevit-Master\bin`

Then you should be able to run `pyrevit` in command prompt.

Open command prompt and run these commands in order:

```shell
pyrevit clones add master "C:\Users\ty\AppData\Roaming\pyRevit-Master"
pyrevit attach master 277 --installed
```

Then run `pyrevit env` again and share the report please.

**Comment by TyHearn** [comment]
I will see if i can get my IT people to do this for me. I don't have access to do this myself..

I'n the mean time i'm having a side issue on another colleagues computer who deleted there pyRevit folder instead of using the uninstall wizard and now can't reinstall or uninstall.

**Comment by TyHearn** [comment]
I got this error when I tried to install 4.6.6
[MSI43FB.LOG](https://github.com/eirannejad/pyRevit/files/2595401/MSI43FB.LOG)

**Comment by eirannejad** [comment]
Hmm. Another installer issue. I'm closing and merging this with https://github.com/eirannejad/pyRevit/issues/421
