### ISSUE TITLE
No Imaginign component suitable to complete this operation was found

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#424]
What does this error mean?
I get it with the attached PNG.  It does create a small button successfully, which is how it is displayed in my toolbar:
![icon](https://user-images.githubusercontent.com/14113080/48496502-18e36580-e800-11e8-93a1-84760d241857.png)
![image](https://user-images.githubusercontent.com/14113080/48496512-20a30a00-e800-11e8-95b6-a4f2393f25e9.png)

**Comment by eirannejad** [comment]
Image is too large. Use max 96x96px

**Comment by eirannejad** [comment]
- [ ] Revise to show a better error message or actually resize large images

**Comment by thazell** [comment]
Thanks for the quick answer!

**Comment by eirannejad** [comment]
Resolved issue. pyRevit now accepts icons of all sizes but will show a warning if larger than 96x96.

![2018-11-18 11_57_35-reload](https://user-images.githubusercontent.com/8197916/48677393-3c245280-eb29-11e8-9528-04463a789f21.png)

Will be pushed with 4.6.7 next week

**Comment by thazell** [comment]
WHAT?!?!?!  You rock!
