### ISSUE TITLE
Cloned PyRevit Manualy no Addins showing on Revit 2017 

### ISSUE THREAD

**Issue by Hazen12345** [eirannejad/pyRevit#425]
New to all this I think Files are missing From Release Folder.

**Comment by eirannejad** [comment]
You need to attach pyrevit after manually cloning

https://github.com/eirannejad/pyRevitLabs/blob/master/README_CLI.md#attaching-pyrevit-to-installed-revits

**Comment by Hazen12345** [comment]
Hello eirannejad, no idea what to do with the code should run it thru command.

Reason for manual install PyRevit was messing up Dynamo.

Thanks;

James

**Comment by Hazen12345** [comment]
Eirannejad these Files are missing from what you show on the Manual install Video what am I doing wrong?

[cid:image001.png@01D47CBF.1DE3E7A0] [cid:image002.png@01D47CBF.1DE3E7A0]

**Comment by eirannejad** [comment]
Yes. Open a command and run:
`pyrevit attach <your-clone-name> dynamosafe --installed`

**Comment by Hazen12345** [comment]
Thx. My Clone is in C drive but cmd is showing U drive!
