### ISSUE TITLE
pyRevit Seed Config File

### ISSUE THREAD

**Issue by mcterry1337** [eirannejad/pyRevit#427]
I was trying to follow the instructions from the seed config file set up instructions below:
https://eirannejad.github.io/pyRevit/pyrevit/update/2017/10/14/configupdate.html

But I don't have a pyRevit folder in the programdata folder. Is there anywhere else this file is being pulled from?

**Comment by eirannejad** [comment]
Make one and place the file there.
OR
the newer method is to use the pyRevit CLI tool:
https://github.com/eirannejad/pyRevitLabs/blob/master/README_CLI.md#configuring-pyrevit
