### ISSUE TITLE
 Load Error with 4.6+ (System Type Initialization Excemption - MahApps.Metro...)

### ISSUE THREAD

**Issue by Brainarda** [eirannejad/pyRevit#428]
Windows 10 - pyRevit fails to load only for Revit 2017, and gives me this error.
Uninstalled and re-installed pyRevit, same error:

![pyrevit error 2017](https://user-images.githubusercontent.com/45105089/48639113-7ce46600-e987-11e8-8318-62e895fa3ba8.png)
![py revit 2](https://user-images.githubusercontent.com/45105089/48639126-81108380-e987-11e8-8d67-eb1eb943dd49.png)

**Comment by eirannejad** [comment]
Would you please replace these files with the ones inside the attached ZIP file and let me know if it resolves the load issue?
`C:\Users\ana\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\labs.py`
`C:\Users\ana\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\loader\sessionmgr.py`

[issue428.zip](https://github.com/eirannejad/pyRevit/files/2593126/issue428.zip)

**Comment by Brainarda** [comment]
Replaced files. Issue was not resolved, unfortunately.

![2018 11 19 pyrevit](https://user-images.githubusercontent.com/45105089/48726467-4b1c0b00-ebe4-11e8-902b-b65f582ab2a5.png)

**Comment by eirannejad** [comment]
Does this DLL even exist on your installation?
`..\pyRevit-Master\bin\System.Windows.Interactivity.dll`

**Comment by Brainarda** [comment]
No, it doesn't...

**Comment by eirannejad** [comment]
Okay this is a serious issue meaning that the installer has not copied this file over or you have an antivirus that might have deleted the file. I'm not sure what your system configuration is. I can show you an alternative method to get pyRevit on your system but I'd rather figure out how to make the installer work for you,

**Comment by eirannejad** [comment]
@Brainarda Any updates on my comment above? Were you able to investigate if the installer copies the `..\pyRevit-Master\bin\System.Windows.Interactivity.dll` correctly at installation? Or an antivirus might be deleting the file maybe?

**Comment by eirannejad** [comment]
Revised loading DLL resolver and installer. Will be published in 4.6.9 this weekend.
Please test and re-open the issue if it persists.

**Comment by Brainarda** [comment]
Hello Ehsan,

Just installed pyRevit 4.6.21 and I am getting Load Errors; all versions or Revit.
I would appreciate some direction on getting me back online 😊

Thank you,

Ana

[cid:image001.png@01D50E75.1AE55FA0]
