### ISSUE TITLE
PyRevit 4.6.6. installer error 

### ISSUE THREAD

**Issue by adasko2018** [eirannejad/pyRevit#430]
Hi, there is a problem within pyRevit Installer because there is no more pyRevitLoader.dll file in pyrevitlib/pyrevit/.... . What has happened to this file?

**Comment by eirannejad** [comment]
All binary files including `pyRevitLoader.dll` have been moved to `bin/`. Engines are under `bin/engines/2xx`

Open a command prompt and use pyrevit cli to attach pyrevit to your installed revits

`pyrevit attach master 277 --installed`

**Comment by adasko2018** [comment]
Thank you, I've found it.

Maybe it's a good idea to update the instructions on this website: https://pyrevit.readthedocs.io/en/latest/articles/core/loaderaddon.html?highlight=pyrevit%20loader
