### ISSUE TITLE
pyRevit 4.6.7 Settings

### ISSUE THREAD

**Issue by epeter-** [eirannejad/pyRevit#434]
When pushing the Settings button i receive 
![image](https://user-images.githubusercontent.com/6928491/48969461-24ecd580-efff-11e8-998a-fa442f96c94a.png)
most probably caused by missing admin privileges.

**Comment by eirannejad** [comment]
Woooooops! Left some test code in there apparently. Will fix right away and will publish 4.6.8 in the next hour. Sorry for the trouble.

**Comment by eirannejad** [comment]
Resolved. Please accept my apologies again.
https://github.com/eirannejad/pyRevit/releases/tag/v4.6.8
