### ISSUE TITLE
pyApex TextNotes2csv

### ISSUE THREAD

**Issue by epeter-** [eirannejad/pyRevit#438]
found following missing:
![image](https://user-images.githubusercontent.com/6928491/48971802-fc74d380-f01e-11e8-8fd2-4ff552e148af.png)

**Comment by eirannejad** [comment]
pyApex was created and maintained by someone else. It's not part of pyRevit's original repo. Please report all issues to the [pyApex repo](https://github.com/apex-project/pyApex)
