### ISSUE TITLE
pyrevit 4.6.8 Run as Administrator

### ISSUE THREAD

**Issue by edvinbarcic** [eirannejad/pyRevit#439]
I'm having an issue where I can install pyRevit on a PC with administrator rights, but it doesn't show for a regular user until Revit is Run as Administrator. How can I bypass this, so we keep our Admin rights intact, and allow pyRevit for regular users?

**Comment by BJozi** [comment]
Could you elaborate on where I run this command? 

I to had to install it using admin right and can see the files in program files but it's not loading in revit.

**Comment by edvinbarcic** [comment]
In cmd.exe. Just type that entire line "pyrevit attach master 277 --installed --allusers" and it should work. You might have to run CMD as administrator. Not sure. In any case, it works for us now.

**Comment by eirannejad** [comment]
@BJozi Any updates? Did the command solve your issue?

**Comment by BJozi** [comment]
@eirannejad I got our IT guy to do it yesterday and it worked perfectly, thank you. I was sure I posted yesterday but must not have.
