### ISSUE TITLE
Error during opening a file

### ISSUE THREAD

**Issue by xenuPL** [eirannejad/pyRevit#441]
### Issue Description

Hello, everytime I open a model in revit (2017,2018,2019) error occures. It's probably due to a VPN or sth is blocked in my company

![image](https://user-images.githubusercontent.com/8247376/49207854-70fc9900-f3b6-11e8-868a-22ad5874a091.png)

### Environment

==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)
Name: "master" | Deploy: "basepublic" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
Autodesk Revit 2016 Update 7 for R2 | Clone: "master" | Engine: "277"
Autodesk Revit 2017.2.3 | Clone: "master" | Engine: "277"
Autodesk Revit 2018.3 | Clone: "master" | Engine: "277"
Autodesk Revit 2019.1 | Clone: "master" | Engine: "277"
==> Installed UI Extensions
Name: "pyRevitMEP" | Repo: "" | Installed: "C:\pyRevit\pyRevitMEP.extension"
==> Installed Library Extensions
==> Extension Search Paths
C:\pyRevit
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2016 Update 7 for R2 | Version: 16.0.1185.0 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016\"
Autodesk Revit 2017.2.3 | Version: 17.0.1150.0 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
Autodesk Revit 2018.3 | Version: 18.3.0.81 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
Autodesk Revit 2019.1 | Version: 19.1.0.112 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
PID: 20016 | Autodesk Revit 2019.1 | Version: 19.1.0.112 | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2019"

**Comment by eirannejad** [comment]
This doesn't seem to be pyRevit related. pyRevit doesn't use any remote API's. It only checks for the internet connection when updating. Try uninstalling pyRevit and see if the error goes away. The prompt window doesn't even have a title which is odd.

**Comment by xenuPL** [comment]
So it's probably because of our extenstions based on google api in Revit and slow connection via VPN. Nevertheless everything besides this error works flawlessly, so thanks for answer! Cheers
