### ISSUE TITLE
pyrevit 4.6.8 install finish but no pyrevit in revit 2016/2018/2017/2019

### ISSUE THREAD

**Issue by wingtong168** [eirannejad/pyRevit#445]
### Issue Description

pyrevit 4.6.8 install finish but no pyrevit in revit 2016/2018/2017/2019 which are the only revit versions I have loaded. Anyone else? Please help. Thanks.

### Environment

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)
==> Attachments
==> Installed UI Extensions
==> Installed Library Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2016 Update 8 for R2 (2016.1.8) | Version: 16.0.1205.0 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016\"
Autodesk Revit 2017.2.3 | Version: 17.0.1150.0 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
Autodesk Revit 2018.3 | Version: 18.3.0.81 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
Autodesk Revit 2019.1 | Version: 19.1.0.112 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
```

**Comment by eirannejad** [comment]
Why do you keep typing pyRevit 3.6.8? It’s 4.6.8. Are you using an older version?

What’s your install path? For some reason the installer could not register thr installed clone.

**Comment by wingtong168** [comment]
ok, my bad. 4.6.8.  Tried using the default install folder, same issue.  Tried uninstalling and installing into my c:\shared\_pyrevit folder, same issue.  I'm actually installing for my users which had same issue so I tried installing on my machine, still same issue.  We use Windows 10, all windows updates up to date.

**Comment by eirannejad** [comment]
Okay run these commands (one by one / use your installed path) in terminal and see if this fixes the issue
```
pyrevit clones add master "C:\shared_pyrevit"
pyrevit attach master 277 --installed
```

**Comment by wingtong168** [comment]
That seems to have done the trick!  Any reason those "extra" command lines are needed, if you can share, just curious.  Thanks.

**Comment by eirannejad** [comment]
They are not needed. Installer runs these commands when copies pyRevit contents to the destination folder. Not sure why it doesn't work on your system. It might be user access rights for the installer to run the commands.

**Comment by wingtong168** [comment]
Ok, thanks.  User access rights are probably right.  Back in 4.5 (I think that's the last version we installed), installing onto default folder did not work even though I ran the installer with admin account.  But when I installed onto a user-created folder (full access for everyone), it worked.  That's why I tried installing 4.6.8 onto a user-created folder this time too, though not as lucky as in 4.5.   In any case it seems to be loading now, thanks again!

**Comment by eirannejad** [comment]
Found source of error. pyRevit installer runs as admin of some user machines depending on the local user rights, installs pyRevit correctly but registers under the admin `%appdata%` instead of the currently logged-in user.

**Comment by waracana** [comment]
Hi, how are you?
I discovered your add-in last year. Unfortunately my hard drive failed and I had to do the usual. So I've lost PyRevit. Then I came here and I have the same issue as described above. I don't know much about programming, coding or anything like that, so I've tried to revert to a previous version of the add-in but can't find an executable file. I'm running windows 10, Revit 2018. You said "run these commands"..is that in iron python console? How is this done? Thanks!

**Comment by eirannejad** [comment]
@waracana Get the new releases from here: https://github.com/eirannejad/pyRevit/releases
All older releases are retired as I'm a single developer and can't set aside enough time to maintain multiple versions at the same time.

Please see my responses above. The fix is coming in 4.6.9 before end of the year.

**Comment by waracana** [comment]
eirannejad thanks, yes that's the version I was having issues with, thanks for your help and for creating this set of tools, it's a wonderful asset. I'll wait until version 4.6.9 comes out. Thanks again!

**Comment by eirannejad** [comment]
Installer has been updated to not require admin right to add pyrevit CLI path to the system path. This was the main culprit that would make the installer run under admin user and therefore config the attachments to Revits for that user. New installer will be available with 4.6.9 and will be published this weekend. Please re-open the issue if it persists.

**Comment by Hazen12345** [comment]
eirannejad   this realy helped me! I already installed manually after watching your great deployment tutorial and attached to Revit. I have the Gitkraken cloned version working with the using the cloned master command! How to I switch the master to override the initial install should I use the switch command?

**Comment by Hazen12345** [comment]
Ok got it use pyrevit clones forget command!

**Comment by lionelcamara** [comment]
I just downloaded the 4.6.19 installer and had the same problem (though maybe a different cause, since the two commands given above don't fix it). After getting the results below, I ran both with the "--debug" option, as suggested, but the results are long so attaching as a text file:

```
C:\Users\lionel>pyrevit clones add master "C:\Users\lionel\AppData\Roaming\pyRev
it-Master"
Error: clone with repo path "C:\Users\lionel\AppData\Roaming\pyRevit-Master" alr
eady exists.
Run with "--debug" option to see debug messages

C:\Users\lionel>pyrevit attach master 277 --installed
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```
[2019-03-30_C191_cmd results.txt](https://github.com/eirannejad/pyRevit/files/3025681/2019-03-30_C191_cmd.results.txt)

**Comment by lionelcamara** [comment]
tried `pyrevit clones forget --all` then the first command completed without error, but still get:
```
C:\Users\lionel>pyrevit attach master 277 --installed
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

**Comment by foxy6800** [comment]
Is it possible to install the latest version without admin rights? Thanks

**Comment by eirannejad** [comment]
@foxy6800 Yes. The installer does not need admin rights

**Comment by foxy6800** [comment]
Hello and thanks for your reply. I tried it (on work laptop) and it comes up asking for admin credentials. I guess i have to contact my IT admin and ask them to install it for me. Also tried doing a manual install and in release folder there are no batch files, aip files which i don't know how to use :(

**Comment by foxy6800** [comment]
Correction , its .NET Core Runtime that needs admin right

**Comment by Sparrowitis** [comment]
I installed PyRevit 4.7.1 (in AppData default file) but it does not appear in Revit LT 2019 ribbon. Any ideas?

**Comment by eirannejad** [comment]
@Sparrowitis As far as I know Revit LT does not load adding

**Comment by Sparrowitis** [comment]
Oh, apologies. I must have misunderstood a previous statement:
"But I think since you already have pyRevit, the Revit LT is capable of loading addons." from
https://github.com/architecture-building-systems/revitpythonshell/issues/79

**Comment by polllex** [comment]
Hi,
I have been trying to install pyRevit 4.7-beta4 for Revit 2020 the past two hours without much success. The videos seem to be old, the links show an error. Where can I please read or watch how to install the latest version? I don`t find anything in the release folder. I have installed pyRevit.CLI_0.16.0.0_signed and PyRevit doesn`t load in Revit. Please help, some time ago I used PyRevit and installation seemed much simpler can we get PyRevit installer for dummies...
