### ISSUE TITLE
_layout is not working

### ISSUE THREAD

**Issue by rick5087** [eirannejad/pyRevit#446]
### Issue Description

When i add the _layout to order my scripts, it is not ordering it. Am i missing something?

**Comment by thazell** [comment]
Can you post an image of the folder and the contents of your _layout file

**Comment by eirannejad** [comment]
@rick5087 Is this still outstanding? Please provide more info.

**Comment by rick5087** [comment]
It is working now! I had to restart revit, not only reload

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: Ehsan Iran-Nejad <notifications@github.com>
Verzonden: donderdag, december 6, 2018 6:23 PM
Aan: eirannejad/pyRevit
CC: rick5087; Mention
Onderwerp: Re: [eirannejad/pyRevit] _layout is not working (#446)


@rick5087<https://github.com/rick5087> Is this still outstanding? Please provide more info.

**Comment by chauhuh** [comment]
I have encountered the same problem. Can confirm that restarting Revit fixes it.

```
C-Channel Section
C-Channel Side
C-Channel Top
-----
WF Section
WF Side
WF Top
```

**Comment by chauhuh** [comment]
This issue still persists in 4.8.8. Maybe we could add a footnote in the bundle layout doc.

Thanks.

**Comment by eirannejad** [comment]
Says at the top of this page. 
https://www.notion.so/Bundle-Layout-39f1491439d44343896fe0adc4270129#44b1c6324ad7486a8c3c20934a69a095
