### ISSUE TITLE
Improvement: Don't create Panel if all commands are hidden by __beta__ flag

### ISSUE THREAD

**Issue by deddolo** [eirannejad/pyRevit#449]
Not an issue, but an improvement. If all the command in a panel are flagged as beta and pyRevit is not loading them then the containing panel should not be created an left empty.

I will look into fixing this when I have time, but maybe it's an easy fix if you know where to look :)

**Comment by eirannejad** [comment]
Implemented. Will push with 4.6.9 this weekend.

**Comment by deddolo** [comment]
awesome. thank you
