### ISSUE TITLE
Enhancement Idea: Alternately select sheets in Project Browser

### ISSUE THREAD

**Issue by BrettBeckemeyer** [eirannejad/pyRevit#452]
For several of the tools that require selecting sheets, I've found that sometimes it is more efficient for users to select sheets in the Project Browser. I tweaked the code on my personal install to implement this and several other users in my company have requested this functionality too.

This works best as an optional - if nothing is selected or if the selection is not entirely comprised of ViewSheets, then it runs normally using the select_sheets form.

![image](https://user-images.githubusercontent.com/37711373/50096898-53189c00-01de-11e9-9a99-8d81a40a82e5.png)

The tools that this applies to include:
- Increment / Decrement Sheet Numbers
- Set / Remove Revision on Sheets

**Comment by eirannejad** [comment]
All the tools that deal with sheets used to require sheet selection from the Project Browser. But depending on whether the browser is separated from the Revit window or not, the selection report was very inconsistent. So I implemented a sheet selection prompt with a filter field to allow search and selection in a consistent manner. I'll bring back the selection from project browser once these inconsistencies are resolved in Revit API.

**Comment by RevitIRL** [comment]
Is there an Idea post to fix the API issue?
