### ISSUE TITLE
Analyse: Calculate Average Areas

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#454]
Hi Eshan,

Suggestion for Analyse: Calculate Average Areas

Can this pyRevit tool pick up the Project Units Settings because currently it's out putting in square feet instead of square meters plus it would be great if it listed all the rooms found with their areas. Refer to screen shot.

Thanks
Rob
![image](https://user-images.githubusercontent.com/8776947/50298397-f552b100-0476-11e9-980f-23067a279b00.png)

**Comment by eirannejad** [comment]
It definitely can.

**Comment by eirannejad** [comment]
Implemented and will be pushed with 4.6.9 this weekend.

![2018-12-20 22_20_43-window](https://user-images.githubusercontent.com/8197916/50327852-95273380-04a5-11e9-8a68-f335654c9ef0.png)

**Comment by Robbo1234** [comment]
Eshan, that's it!  

Thanks

**Comment by Robbo1234** [comment]
Hi Ehsan,

It would be good if you could also list the Room Number and Floor plus maybe the Room volume.

![image](https://user-images.githubusercontent.com/8776947/50647183-d9b7d200-0f6f-11e9-9b90-6566ead4bdca.png)

**Comment by eirannejad** [comment]
Done.

**Comment by Robbo1234** [comment]
Hi Eshan,

Similar to the above, can we add roof areas to Analyse-Find Range of Roofs Slopes.
Useful for rainwater outlet calculations.

![image](https://user-images.githubusercontent.com/8776947/50685257-5f8b5a00-1010-11e9-9a14-31e5e394ccf7.png)

Thanks
Rob

**Comment by Robbo1234** [comment]
Eshan,,

It would good if you could select what Revit Element to Analyse in Current View or Entire Project.

i.e. Ceiling: Level/Room/Height/Area

![image](https://user-images.githubusercontent.com/8776947/50686279-9d8a7d00-1014-11e9-84c6-4b672ad4a1d4.png)

**Comment by eirannejad** [comment]
Good idea. Would you please submit this as a feature request.

Thanks

**Comment by Robbo1234** [comment]
Ehsan,

I noticed that pyRevit calculates "Not Place" Revit rooms which effects the average area results.  Refer to screen shot below. 

1. pyRevit to ignore "Not Place"  Revit rooms? 
2. Display results areas in both Arce and Hectors.

![image](https://user-images.githubusercontent.com/8776947/50778061-fc5e2980-1294-11e9-85a6-a94813e15540.png)

Thanks

Rob

**Comment by eirannejad** [comment]
Resolved

![2019-01-07 09_09_36-calculate average area](https://user-images.githubusercontent.com/8197916/50782143-13ccf080-125c-11e9-9c01-1b38d3528a94.png)

**Comment by Robbo1234** [comment]
Thanks

Can the final area output be in both Acres and Hectares?
