### ISSUE TITLE
pyRevit 4.6.8 and 4.6.9 Installation problem

### ISSUE THREAD

**Issue by DanailMomchilov** [eirannejad/pyRevit#457]
Hello,

right before Christmass I have tried to install pyRevit 4.6.8 version, using the standart installer, but it did not work. Not only it did not appear on the Revit menu, but it also completely wiped out the previous version I had installed, that was already working - 4.5 and I could never install that one again. I just saw the new release - pyRevit 4.6.9, but the same thing happened. I again used the standart installer and after completing installation It did not appear on the menu once again, while still not being able to run or reinstall the previous working version - 4.5. Maybe I am the one doing something wrong, but in any case I would be more than happy to get a little opinion on how to install this great product properly.

Thanks in advance!

**Comment by eirannejad** [comment]
@DanailMomchilov Please open command prompt and run `pyrevit env` and share results here.

**Comment by DanailMomchilov** [comment]
Hi there, It actually worked out and I have it installed already. Don't really know what was the problem and how it worked out... Thanks anyway, it seems OK now! 

By the way, could it be because I was trying to install it, running the setup as administrator on my PC at work? Once I tried to reinstall it from my local user, it worked out... Seems like a weird reason though.

Cheers!

**Comment by eirannejad** [comment]
Good. Take a look at deployment guide for more info: https://eirannejad.github.io/pyRevit/deploy/
