### ISSUE TITLE
Keynote Manager - Add New Keynotes in All Categories

### ISSUE THREAD

**Issue by DanBoghean** [eirannejad/pyRevit#459]
**Describe the solution you'd like**
Currently, you can only add a new keynote when a Division is selected. You can not currently add it when All Categories is selected. You can, however, duplicate a keynote and then change the contents and key, so that is definitely a way to do it. I was just wondering if it was possible to add the keynote from the All Categories selection, as I can see people getting annoyed they have to go to the division to add a keynote.

**Describe alternatives you've considered**
The alternative of duplicating a keynote can definitely work as well, just thought it would be nice to be able to add if possible.

**Comment by eirannejad** [comment]
Great. I'll add this for 4.6.10 this weekend.

**Comment by DanBoghean** [comment]
Awesome! Thank you for the quick turn around!

**Comment by eirannejad** [comment]
Implemented and will be published with 4.6.10
