### ISSUE TITLE
How to define __file__ property?

### ISSUE THREAD

**Issue by boesiii** [eirannejad/pyRevit#46]
Hello,

Near the beginning of your readme you say "(with __file__ property defined)" in the Setup Process section but how do you define the __file__ property?

**Comment by eirannejad** [comment]
The creator of RevitPythonShell has added a feature to the addin that everytime it's running a script from a .py file, it defines a variable within the python environment that is named `__file__`
The python script will have access to this parameter to find out its own file name and current directory.

However the compiled version of the RevitPythonShell that is available on the github page hasn't been updated with this feature.

**Comment by eirannejad** [comment]
I've written the startup script to use the `__file__` property if available. Otherwise it'll read the RPS settings file for the startup script.
`
def findHomeDirectory():
	try:
		#getting home directory from __file__ provided by RPS
		folder = os.path.dirname( __file__ )
		if folder.lower().endswith('.dll'):
			# nope - RpsAddin
			return os.path.dirname( folder )
		else:
			return folder
	except:
		settingFolder = Path.Combine( Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "RevitPythonShell" + revitVersion )
		settingsFile = Path.Combine( settingFolder, "RevitPythonShell.xml" )
		xdoc = XDocument.Load( settingsFile )
		return op.dirname( xdoc.Root.Element("StartupScript").Attribute("src").Value )
`

**Comment by boesiii** [comment]
I downloaded the pyRevit scripts and placed in folder "c:\pyrevit" and added the __RPS__userSetup.py startup script to RPS but the pyRevit ribbon is empty.  Should it be populated with your scripts?

**Comment by boesiii** [comment]
Also when the startup script runs it is saying my "Home Directory" is empty.

**Comment by eirannejad** [comment]
Yes. Because the script is unable to find the `__file__` property it can't determine it's home directory. I suggest editing the `def findHomeDirectory():` to return the folder address on  your drive.
