### ISSUE TITLE
Keynote Manager - Window resets every time

### ISSUE THREAD

**Issue by DanBoghean** [eirannejad/pyRevit#460]
**Describe the bug**
I believe per the video you released that the Keynote Manager should remember the location that it was in after it is closed, but it resets itself every time to the center of the screen. I currently only have one monitor, so I can't test if it works with multiple monitors or not.

**To Reproduce**
1. Go to pyRevit tab
2. Click on Keynote Manager
3. Move the window to the side and resize it
4. Close the window using the Refresh Model button
5. Open Keynote Manager again, and it resets to the center of the screen in its original size

**Expected behavior**
I believe it is supposed to remember the size, location, and the division that it is on. If that is not correct, please ignore this.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.6.9

**Comment by eirannejad** [comment]
Resolved. Will be pushed with 4.6.10
