### ISSUE TITLE
PyRevit User Interface Suggestions

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#462]
Hi Eshan,

User Interface suggestions:

1. With so many PyRevit tools it might be a good ideal to introduce a tool coding system.
2. It would great if a user could press the F1 Function Key to launch online Help or YouTube tutorial.
3. Can will add some colour to the PyRivet Addin icon?
4. Add horizontal line to Tool headings.
5. Revit users should be able to control what tools are actually displayed on their Revit Tab. i.e. Display only users favorite tools.

Thanks

Rob

![image](https://user-images.githubusercontent.com/8776947/50687518-7da98800-1019-11e9-8f2d-b9d6dd5defda.png)

**Comment by eirannejad** [comment]
@Robbo1234 My name is `Ehsan` not `Eshan`
1. What is a tool coding system
2. You can define a help url link in your script as `__helpurl__ = "<url>"` and the help on F1 option will be activated on that tool. Most pyRevit tools don't have this at the moment so please use the tooltips.
3. No
4. Can't
5. Maybe in the future if I have time

**Comment by Robbo1234** [comment]
Thanks Ehsan for getting back.

1. Numerical, similar to KiwiCodes-Bonus Tools.

![image](https://user-images.githubusercontent.com/8776947/50700596-d93c3b80-1042-11e9-997e-220448becbbf.png)

**Comment by eirannejad** [comment]
I don't like to clutter the interface with all these numbers everywhere. I doesn't seem to be that valuable of a feature if it's only for easier reference.

**Comment by Robbo1234** [comment]
Bonus Tools have 133 Revit addins, so you can see why they've added the numbers prefix.
btw it useful for Revit Shortcuts  i.e. BT39 = 39 Align Sheets

**Comment by eirannejad** [comment]
So when you think "**I want to align sheets**", then you have to remember to press `BT39`?? That doesn't sound intuitive. How about `BTAS` ? Is't that more descriptive than `BT39`?

**Comment by winterweken** [comment]
> Can we bring back the pyRevit colour icons?
> 
> ![image](https://user-images.githubusercontent.com/8776947/50841032-bd46db80-135b-11e9-914d-7a14f7473cf5.png)

Robbo1234 - A lot of these 'issues' / 'requests' can be easily changed on your end with little effort. You should familiarize yourself with the documentation and I think you would see just how easy these things are to implement for your own installations/deployments.

**Comment by Antonj123** [comment]
winterweken i have been looking everywhere to learn how to change the icons to icons8.
Can you suggest a tutorial?
