### ISSUE TITLE
Conversion Failed (Manage Keynote)

### ISSUE THREAD

**Issue by danselkaz** [eirannejad/pyRevit#463]
Conversion Failed when launching the Manage Keynote function

**Screenshots**
![image](https://user-images.githubusercontent.com/34090753/50696381-92007b80-103f-11e9-9dcd-a2cbba3ebca7.png)

 - pyRevit 4.6.9
 - Revit 2019 (French)

**Additional context**
I have also some errors at Revit Launch since 4.6.9 installation

[pyRevit.html.pdf](https://github.com/eirannejad/pyRevit/files/2727545/pyRevit.html.pdf)

**Comment by danselkaz** [comment]
I try to open a Desktop copy of the RevitKeynotes_FRA.txt in an empty project file, and here is the error message : 
![image](https://user-images.githubusercontent.com/34090753/50697466-95e1cd00-1042-11e9-84d4-4ad4e700005a.png)

**Comment by eirannejad** [comment]
@danselkaz Would you please send me the original keynote file and also add translations for the French prompts in your comments? I can't read French, sorry.

**Comment by eirannejad** [comment]
You can also start with a fresh empty text file and import your existing keynotes.

**Comment by danselkaz** [comment]
Hello, 

Here is the file for Keynote in French
[RevitKeynotes_FRA - Copie.txt](https://github.com/eirannejad/pyRevit/files/2732202/RevitKeynotes_FRA.-.Copie.txt)

" L'accès au chemin d'accès ...... est refusé "
Means : "Access to the ..... filepath is rejected"

" Fin de la trace de la pile d'exception interne " is untranslatable
Google says something like : "end of the internal exception stack trace"

The weird thing is that , in this file, I don't have the Keynote manager window that can permits to load an other file (like an empty one).

When I click on "Manage keynotes" it opens the windows that says, "Existing keynote file needs to be converted to a format .....Are you sure you ant to convert ?

I click "Convert" and then the error message with a single "OK" button to validate and close the command.

**Comment by eirannejad** [comment]
@danselkaz Are you sure you have write access to that file?

**Comment by eirannejad** [comment]
@danselkaz Any updates?

**Comment by danselkaz** [comment]
I'm out of the office until week 4, I will try to edit the file when I'm back and tell you.

Nevertheless, I remember having tried with a copy of the file in the desktop and it doesn't work, but maybe that was not exactly the same error message. So I'll check this out also

Thank you

**Comment by danselkaz** [comment]
It seems that the file was on Read Only status... I don't understand why it was like this in my instalation but .. .problem solved
