### ISSUE TITLE
Analysis tool improvements

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#464]
It would good if you could select the Revit Element/s to Analyse in Current View or Entire Project.

i.e. Ceiling: Level/Room/Height/Area

![image](https://user-images.githubusercontent.com/8776947/50702004-8022d680-1047-11e9-9cd2-d95dc557f139.png)

**Comment by eirannejad** [comment]
The screenshot you have is from the Pick Elements tool. How does this relate to Analyse tools?

**Comment by Robbo1234** [comment]
I was thinking when you launch the Analyse tool, a dialog similar to the
Pick Elements tool would appear and then one just selects the Revit Element
to be analysed.

**Comment by eirannejad** [comment]
There is no generic Analyse tool? Which tool are you specifically talking about? What kind of Analysis is the selection for?

**Comment by Robbo1234** [comment]
I was thinking the user could have a option of launching the Analyse Room
Average Areas, Analyse Roof Slopes and Analyse Ceilings Heights (future
requested tool) from a single analysis tool button.

Analyse Revit Element future options could be as follows:

Find Revit Ceilings heights below certain height.

Find Revit Doors widths below a certain width.

**Comment by Robbo1234** [comment]
It would be great if PyRevit could incorporate model code compliance checks similar what Solibri software offers.

For example:
-Clearance in Revit front to doors and windows.
-Stair riser and trend minimum requirements.
-Handrail minimum height requirements.

Refer screen shot below:
![image](https://user-images.githubusercontent.com/8776947/50837142-d9924a80-1352-11e9-8f40-ef14dc52450b.png)

Refer to video:
https://www.solibri.com/download-solibri-model-checker-trial/step=2

**Comment by eirannejad** [comment]
Tools will be combined on a case-by-case basis in the future depending on the functionality.
