### ISSUE TITLE
Manage Keynotes- Add spell check and keynote tag used count.

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#465]
- [ ] Add Spell Check button
- [x] Add used keynote count information (maybe an extra column?)

![image](https://user-images.githubusercontent.com/8776947/50702870-21129100-104a-11e9-8e90-a38aa7a76c8f.png)

**Comment by eirannejad** [comment]
Implemented used count
![2019-01-04 10_31_20-manage keynotes beta - use for testing only](https://user-images.githubusercontent.com/8197916/50704415-205b0a00-100c-11e9-8d5d-6edea264e1db.png)

**Comment by Robbo1234** [comment]
Super!

**Comment by eirannejad** [comment]
Could possibly use Grammar.com api for spell checking 
https://www.programmableweb.com/api/stands4-grammar
https://www.grammar.com/grammar_api.php

**Comment by eirannejad** [comment]
Spellcheck highlighting added in 4.6.16

![2019-02-26 09_33_33-edit keynote](https://user-images.githubusercontent.com/8197916/53433624-9abf5f00-39a9-11e9-8bd1-3b96f7c41bb0.png)
