### ISSUE TITLE
Install Package Bug

### ISSUE THREAD

**Issue by armorsu** [eirannejad/pyRevit#466]
**Describe the bug**
When I click "Install Package" in pyRevit Extension Manager, I saw the error message.

**To Reproduce**
1. Go to 'Extension'
2. Select Extension Name. For example, 'pyRevitPlus'
3. Click on 'Install Package'
4. Click on 'Install to C:\Users\User\AppData\Roaming\pyRevit\Extensions'
5. See error

**Expected behavior**
Installed Status shows "Yes".

**Screenshots**
![image](https://user-images.githubusercontent.com/1240676/50744501-f8b3ae00-1266-11e9-9601-f23a141e703f.png)

**Desktop (please complete the following information):**
 - OS: MS Windows 7 64bit Korean Version
 - pyRevit Version: 4.6.9
 - pyRevit Environment: 
﻿
```
INFO: [pyrevit.extensions.extpackages] Installing PyRevitPlus to C:\Users\User\AppData\Roaming\pyRevit\Extensions\PyRevitPlus.extension 


ERROR: [Extensions] Error installing package. | failed to send request: . 


Traceback: 
 File "C:/Users/User/AppData/Roaming/pyRevit-Master/extensions/pyRevitCore.extension/pyRevit.tab/pyRevit.panel/Extensions.smartbutton/script.py", line 336, in install_ext_pkg 
 extpkgs.install(self.selected_pkg.ext_pkg, 
`pyrevit env`
```
**Additional context**
Maybe the company Firewall is related to the problem.

**Comment by eirannejad** [comment]
@armorsu It is most likely your internet connection / firewall. The package installer is pulling the package git repo from github and needs to establish a secure connection on https first.

**Comment by eirannejad** [comment]
@armorsu Any updates?

**Comment by armorsu** [comment]
Could you tell me the IP and Port information about Extension downloads for firewall exceptions?

**Comment by eirannejad** [comment]
@armorsu Open all ports necessary for HTTPS communication. The target website is github.com

**Comment by eirannejad** [comment]
No response. Assuming the issue was resolved. Open again if sure this is a pyRevit issue and not a firewall block
