### ISSUE TITLE
Wipe Tools Improvements

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#469]
"Add Remove All Reference Planes (Unnamed)"

But  exclude Reference Planes that are hosting Revit items.

![image](https://user-images.githubusercontent.com/8776947/50821034-0bd98300-1326-11e9-922e-059d630d1790.png)

**Comment by Robbo1234** [comment]
Add SubCategories Item quantities column to Wipe SubCategories. 

Refer to screen shot.

![image](https://user-images.githubusercontent.com/8776947/50839505-5e339780-1358-11e9-9efa-1499b1752943.png)

**Comment by Robbo1234** [comment]
Add removed Revit Constraints only on opened Revit views.

Refer to screen shot.

![image](https://user-images.githubusercontent.com/8776947/50839773-ec0f8280-1358-11e9-9a5d-ff2af84206e5.png)

**Comment by Robbo1234** [comment]
Add Wipe unused Detail Items and Family Types because the standard purge doesn't purge these items.

**Comment by eirannejad** [comment]
Implemented purging unnamed reference planes
Could not figure out a way to find elements hosted on a reference plane
Reference planes are 3d objects, deleting them based on view will affect other views as well.

**Comment by Robbo1234** [comment]
Similar to Wipe Unused View Templates, can we add the following Wipe tools:

- Wipe unused Legends
- Wipe unused Schedule

Thanks

**Comment by eirannejad** [comment]
@Robbo1234 Moved your request to #506. You're **not** making my life easier by burying feature requests in closed issue threads.
