### ISSUE TITLE
Find Linked Elements: List the Family Category and Family Type Name

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#470]
List the Family Category and Family Type Name

![image](https://user-images.githubusercontent.com/8776947/50823696-77beea00-132c-11e9-9b9a-85f53bf21dee.png)

**Comment by eirannejad** [comment]
Implemented. Will be pushed with 4.6.14

![2019-02-01 13_44_05-find linked elements](https://user-images.githubusercontent.com/8197916/52151304-7d57d900-2627-11e9-8ff6-4e7724735cc6.png)
