### ISSUE TITLE
Add Copy Sheet Placeholders to Open Documents similar to pyRevit Copy Sheet to Open Documents.

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#472]
Add Copy Sheet Placeholders to Open Documents similar to pyRevit Copy Sheet to Open Documents.

![image](https://user-images.githubusercontent.com/8776947/50841520-cf754980-135c-11e9-94e1-b39b38f2be1d.png)

**Comment by eirannejad** [comment]
Added option to control whether the Placeholders should be copied as Placeholders or sheets. Will be pushed with v4.6.13

![2019-01-21 20_49_54-window](https://user-images.githubusercontent.com/8197916/51513171-43ccd580-1dbe-11e9-9d67-44698ed7878e.png)

**Comment by Robbo1234** [comment]
Thanks Ehsan.
