### ISSUE TITLE
Ability to have a newline in a pulldown bundle.

### ISSUE THREAD

**Issue by martinservold** [eirannejad/pyRevit#474]
I'd like a way to wrap text on a pulldown bundle (hopefully would work for pulldown/ splitbutton/ splitpushbutton)

My suggestion to accomplish this would be:

Have a special group of characters (My suggestion is "___". Three underscores) that prompts a new line during extension building/reload.

This special character group could live in the folder name 
EX: Folder name is: (Place Views___on Sheets.pulldown)

OR

This special character group could live in the _layout file 
EX: Folder name is: (Place Views on Sheets.pulldown) but in the _layout file you call for: (Place Views ___on Sheets) and it will recognize the difference and put in a newline.

**Comment by eirannejad** [comment]
Interesting. Suggesting implementation using tags in `_layout` file:

Example:
This would be the modified layout file for `Pick.splitpushbutton` tool:
```
[title:Pick\nElements]
Pick
Pick Detail Elements
Pick Model Elements
```

This conforms to the already existing standard of using location tags in `_layout` file. e.g. pyRevitTags extension uses the tags to position its panel in pyRevit tab `Packages & Tags[before:Modify]`

**Comment by martinservold** [comment]
That probably a better way to handle it than my suggestion.

**Comment by eirannejad** [comment]
Implemented slightly differently than suggested above.

Final implementation allows use to define the `title` **layout directive** inside layout file. For setting the title of a pulldown button for example, the layout file of the parent panel should be modified.

Example: This is the layout file of the `pyRevit > Drawing Set` panel setting the title for the `Sheets` pulldown button:

```
Sheets[title:Sheet\nTools]
Revision
Keynotes
views
-----
Print
```

pyRevit processes these directives on load time and will set the button title to the new value:

![2019-01-21 16_40_06-window](https://user-images.githubusercontent.com/8197916/51505433-3e11c880-1d9b-11e9-9119-70a260c1373d.png)
