### ISSUE TITLE
`openpyxl` module!

### ISSUE THREAD

**Issue by chinh-trieutien** [eirannejad/pyRevit#477]
I dont know if this is bug of pyRevit or not but I ran following code with python interpreter with no problem but when i put it in pyRevit it return error.

I already put `openpyxl` to my project to keep the `module` alway with the code in order to keep track of `module's version`.

The sub library i use was created with `virtualenv`

![image](https://user-images.githubusercontent.com/8264004/51106676-0c3eb600-181f-11e9-9eab-7cfb52925658.png)

![image](https://user-images.githubusercontent.com/8264004/51106642-f204d800-181e-11e9-81cf-149681a874df.png)

**Comment by chinh-trieutien** [comment]
I guess cause of pyRevit can not read completely the Python's module??

Is there anyway to do it, somehow I can handle both data and formating of excel with pyRevit?

**Comment by chinh-trieutien** [comment]
Just figure out it cause the IronPython. Is there any way else to use `openpyxl`.

`xlrd` is not support to get format from `*.xlsx`

![image](https://user-images.githubusercontent.com/8264004/51109029-80308c80-1826-11e9-8316-3d3ddc559781.png)

**Comment by varunbose** [comment]
> Just figure out it cause the IronPython. Is there any way else to use `openpyxl`.
> 
> `xlrd` is not support to get format from `*.xlsx`
> 
> ![image](https://user-images.githubusercontent.com/8264004/51109029-80308c80-1826-11e9-8316-3d3ddc559781.png)

Hi Chinh, 
Do you mind sharing the idea "How to use open openpyxl" in Pyrevit.
I got stuck without knowing how to read/write Xlsx file.
Please advise.
Thanks
VBK

**Comment by eirannejad** [comment]
pyRevit includes `xlrd` and `xlsxwriter` for Excel reading and writing.

**Comment by varunbose** [comment]
Hi Ehsan,
xlsxwriter can't write to an existing excel file..
I am trying to write to a template file. Any example will be much appreciate.
Thanks,
VBK

**Comment by eirannejad** [comment]
@varunbose I haven't tested the xlsxwriter extensively. How about reading the existing files making changes, and then overwrite it?
