### ISSUE TITLE
Make Pattern hangs in Detail View

### ISSUE THREAD

**Issue by DavePlumb** [eirannejad/pyRevit#482]
One of my users has been using pyRevit to Make Patterns for quite a while, but today wasn't able to complete the command, and we couldn't close Revit.
Turns out she was trying to Make a Pattern from a **_Detail_** View instead of a _Drafting_ View.
Clearly user error, but the reason I'm posting a bug report is that this hung up Revit and we had to use Task Manager to kill Revit completely.
We had the pattern lines drawn in a Detail View (created from a Callout on a Section if that matters)
Selected the lines, started the Make Pattern tool, gave it a name, and when wed click on the Creat Pattern button, the normal orange pop up window never displayed.
At that point, we couldn't close pyRevit and couldn't get back into the Revit UI
This first happened with PyRevit 4.4. I then upgraded to the current version 4.6 and the same thing happens.
Again, this is clearly user error, but it is a nasty error which caused lost work

**Comment by eirannejad** [comment]
Awesome thanks for the report. I'll test and will get it fixed for .12 release.

**Comment by eirannejad** [comment]
Resolved. Will be pushed with 4.6.12
