### ISSUE TITLE
Insert family symbol from library tool

### ISSUE THREAD

**Issue by chauhuh** [eirannejad/pyRevit#483]
I need help using temporary Transactions in Revit via Python. I can't seem to extract data from the transaction after the Rollback. Not sure if this is the appropriate place to ask. If not please let me know.

This is for a pyRevit add-in that will insert a specific family. I've tried using pyRevit's DryTransactions, SubTransactions, and GroupTransactions but none of them seem to be working for me.

```
fam_symbol = None

t = Transaction(doc, 'loadfamily')
t.Start()
     success, fam_symbol = doc.LoadFamilySymbol.Overloads.Functions[1](fam_doc_path, fam_symbol_name)
     doc.Regenerate()
     fam_symbol = fam_symbol.Name
t.RollBack()
```
I would expect fam_symbol to now contain the family symbol but it doesn't. If I test it from within the Transaction it works, but after the rollback the information is gone.

**Comment by eirannejad** [comment]
First of all what is this for? `.Overloads.Functions[1](fam_doc_path, fam_symbol_name)`
What's wrong with `doc.LoadFamilySymbol(fam_doc_path, fam_symbol_name)`

You're rolling back changes. So the loaded symbol is going away. Grab the info before you roll back.

Send emails for questions or use [StackOverflow with pyRevit or Revit tag](https://stackoverflow.com/questions/tagged/pyrevit)

**Comment by chauhuh** [comment]
doc.LoadFamilySymbol(fam_doc_path, fam_symbol_name) only returned the bool and I needed the family symbol.

How do I 'grab' the info? I though that declaring the fam_symbol outside of the transaction and then setting it with fam_symbol = fam_symbol.Name would 'grab' it. But I seem to be fumbling here.

Essentially, I want a family symbol from an external file and this was the only way I could think to do it.

Your help is appreciated.

**Comment by eirannejad** [comment]
You can [open the family model using the API ](https://www.apidocs.co/apps/revit/2019/11420983-6d0d-0022-e24c-2361c4e42fba.htm)and read or modify the content. Loading/Unloading a family in another model just to grab info is hacky.
