### ISSUE TITLE
Won't install for Revit 2019.2

### ISSUE THREAD

**Issue by eluvs** [eirannejad/pyRevit#484]
I just tried to install this on my computer after installing the Revit 2019.2 update and it won't install. It works fine for the machines that it was installed on in 2019.1.

`pyrevit 4.6.11--installed`

**Comment by eirannejad** [comment]
Being tested. Will be pushed with 4.6.12 this weekend. You can manually copy the `pyRevit.addin` manifest file to 2019 folder and run it

**Comment by JarodSchultz** [comment]
Still having issues getting PyRevit to install on my 2019.2, just tried it using your 4.6.17 release. Installs fine in my 2018.3 version...

![image](https://user-images.githubusercontent.com/27864673/53994013-38273b00-40ee-11e9-9c16-3cb9d8e0fb7a.png)

**Comment by eirannejad** [comment]
Sorry I think I forgot to push that change to this release. Will double check and make sure it's included in 4.6.18

**Comment by eirannejad** [comment]
Okay definitely resolved and will be pushed with 4.6.18

**Comment by JarodSchultz** [comment]
Thanks!
