### ISSUE TITLE
pyRevit cannot make system calls

### ISSUE THREAD

**Issue by amastrobera** [eirannejad/pyRevit#486]
I am trying to call a python script from a pyRevit button. **Is this possible?**

... I tried the pythonic:
```
>>> from subprocess import Popen, PIPE
>>> p = Popen([bin_path, exec_path, export_dir, output_path], stdin=PIPE, stdout=PIPE, stderr=PIPE)
>>> output, err = p.communicate(b"input data that is passed to subprocess' stdin")
>>> rc = p.returncode
>>> print("output: %s, ret: %d" % (output, rc))
output: , ret: 1
```
Which fails. Note, this *does succeed* if I run it from command line. 

.... and also the c# from IronPython
```
>>> import System
>>> info = System.Diagnostics.ProcessStartInfo(bin_path)
>>> info.Arguments = "'" + python_script_path + "' '" + arg_1 + "' '" + arg_2 + "'"
>>> p = System.Diagnostics.Process.Start(info)
>>> p.HasExited
True
>>> p.ExitCode
﻿2
```
And this fails too. I had found some advice on [this post](https://stackoverflow.com/questions/810521/how-to-run-os-shell-commands-in-ironpython-mono) for that.

**Comment by eirannejad** [comment]
Tested this and it works completely fine. There seems to be an issue with your command string. pyRevit uses Popen for some tasks and they work fine. This is not a pyRevit issue.

``` python
import System
info = System.Diagnostics.ProcessStartInfo(r'C:\Users\eirannejad\Desktop\gits\pyRevitDev\bin\pyrevit.exe')
info.Arguments = "env"
p = System.Diagnostics.Process.Start(info)
```
Example of where pyRevit uses Popen successfully:

``` python
def show_file_in_explorer(file_path):
    """Show file in Windows Explorer."""
    import subprocess
    subprocess.Popen(r'explorer /select,"{}"'
                     .format(os.path.normpath(file_path)))
```

In the first example you're directing both io streams to PIPE -> stdin=PIPE, stdout=PIPE,`. This means that anything sent to stdout (output) will be fed into stdin (input) as well. 

You can use [run_process from pyRevit coreutils](https://pyrevit.readthedocs.io/en/latest/pyrevit/coreutils/init.html#pyrevit.coreutils.run_process) to run a shell process silently. Here is the source for that function.

``` python
def run_process(proc, cwd=''):
    """Run shell process silently.

    Args:
        proc (str): process executive name
        cwd (str): current working directory

    Exmaple:
        >>> run_process('notepad.exe', 'c:/')
    """
    import subprocess
    return subprocess.Popen(proc,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                            cwd=cwd, shell=True)
```

**Comment by amastrobera** [comment]
Thanks for checking this out promptly. It was a problem of my windows. Anaconda had not installed correctly a library and the program failed (without reporting a meaningful error). Normally it works like it did for you.

**Comment by InquisitiveAS** [comment]
Thanks a lot, @eirannejad for this . If anyone was wondering how to run external python files for proc, in the above example for run_process, call the function as run_process(["python", "yourpythonprogramforpyrevit.py"], "C:\\...)
