### ISSUE TITLE
CLI Attach doesn't work, if installed with installer

### ISSUE THREAD

**Issue by melnikovalex** [eirannejad/pyRevit#488]
**Describe the bug**
Hey Ehsan, I was testing deployment process for v4.6 and got a question. Am I right, that now to add .addin file to Revit/xxxx/Addins folder we should use `pyrevit attach ...` command?

So I am not sure how can I use it in case if pyrevit was installed with the installer and how can I create this addin (except doing it by hands)? 

It could be related to this issue https://github.com/eirannejad/pyRevit/issues/421#issuecomment-443422406

**To Reproduce**
I think in my case the problem could be that I run the installer from **admin** user (to be able to install .NET Framework ). That's why the installer offers to install it to admin appdata (I change this path to my appdata). PyRevit was installed, but .addin file wasn't created.

Then was trying to do it with CLI, but unsuccessfully. Maybe I doing something wrong here?
```
C:\Users\aleksei.melnikov\AppData\Roaming\pyRevit-Master\bin>pyrevit attach main latest --installed
Error: Can not find clone "main"
Run with "--debug" option to see debug messages

C:\Users\aleksei.melnikov\AppData\Roaming\pyRevit-Master\bin>pyrevit clones
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)

%C:\Users\aleksei.melnikov\AppData\Roaming\pyRevit-Master\bin>pyrevit attach main latest --installed
Error: Can not find clone "main"
Run with "--debug" option to see debug messages

C:\Users\aleksei.melnikov\AppData\Roaming\pyRevit-Master\bin>pyrevit attach main latest --installed --debug
<clone_name> = main
attach = True
--installed = True
latest = True
Debug: Active Keyword: attach
Debug: Active Keyword: latest
Debug: Try getting config as dict "environment:clones"
Debug: Try getting config "environment:clones" ?? {}
Debug: Updating config "environment:clones = {}"
Debug: Saving config file "C:\Users\aleksei.melnikov\AppData\Roaming\pyRevit\pyRevit_config.ini"
Error: Can not find clone "main" (pyRevitLabs.Common.pyRevitException)
   bei pyRevitLabs.TargetApps.Revit.PyRevit.GetRegisteredClone(String cloneNameOrRepoPath)
   bei pyRevitManager.Views.pyRevitCLI.ExecuteCommand(IDictionary`2 arguments, IEnumerable`1 activeKeys) in C:\Users\LeoW10\Desktop\gits\pyRevit\dev\pyRevitLabs\pyRevitManager\CLI.cs:Zeile 564.
   bei pyRevitManager.Views.pyRevitCLI.ProcessArguments(String[] args) in C:\Users\LeoW10\Desktop\gits\pyRevit\dev\pyRevitLabs\pyRevitManager\CLI.cs:Zeile 207.
```

**Expected behavior**
I was expecting that .addin file will be created with installer

**Desktop:**
 - OS: Windows 8.1 Pro
 - pyRevit Version: CLI v0.6.0.0, installer v4.6.12
 - pyRevit Environment: 
```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)
==> Attachments
Error: pyRevit is attached to Revit 2018 but can not determine the clone and eng
ine
==> Installed UI Extensions
Name: "HWPy" | Repo: "" | Installed: "T:\Melnikov\02_WIP\HWPy.extension"
==> Installed Library Extensions
==> Extension Search Paths
T:\Melnikov\02_WIP
T:\Melnikov\02_WIP\HWPy.extension
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2018.3.1 | Version: 18.3.1.2 | Language: 1033 | Path: "C:\Program
 Files\Autodesk\Revit 2018\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 8.1 [Version 6.3.9600]
Executing User: HWPNET\aleksei.melnikov
Active User: HWPNET\aleksei.melnikov
Adming Access: No
%APPDATA%: "C:\Users\aleksei.melnikov\AppData\Roaming"
Latest Installed .Net Framework: "4.7.2"
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.X
pyRevit CLI 0.6.0.0
```

**Additional context**
As a solution I can install .NET stuff with admin rights first, and then run pyRevit installer as current user. But anyway was I'm curious if can I use CLI for this purpose, e.g. if I delete .addin and want to recreate it.

Thank you for the updates and allt the new tools. There are so many new features. But sorry, if I maybe couldn't follow all of them.

**Comment by eirannejad** [comment]
Ya the clone on your machine is not registered for whatever reason. Try:

`pyrevit clones add main <pyrevit clone path>`

On my machine for example:

`pyrevit clones add main "C:\pyRevit-Master"`

**Comment by melnikovalex** [comment]
Thank you! 

That is what I missed. I should have added clone, before attaching it.

I think it's pretty normal that I wasn't registerd automatically, as it was installed for other user.
Issue solved!
