### ISSUE TITLE
PyRevit Uninstall not working

### ISSUE THREAD

**Issue by martinservold** [eirannejad/pyRevit#491]
Program did not load in revit upon install from the .exe (no .addin files were created in %appdata%\Autodesk\Revit\Addins) 

Tried to uninstall by rerunning the .exe and choosing remove. Window says ended prematurely.
Tried to uninstall by going to Window's Add/Remove Programs, It will display a progress bar and not give error, but wont uninstall the program. (I think it's just hiding the error)
Tried to manually remove the ProgramData/Appdata/Temp files to manually remove program. Still appears in the remove programs list and trying to install with the .exe wont give the option to remove anymore but will produce the same error dialog.

![capture](https://user-images.githubusercontent.com/44454303/51630612-d927b100-1f07-11e9-99f4-e56047f41955.PNG)

Attached log for reference:
[MSIE273.LOG](https://github.com/eirannejad/pyRevit/files/2788805/MSIE273.LOG)

 - OS: [WIN 10]
 - pyRevit Version [4.6.12]
 - pyRevit Environment: 

![image](https://user-images.githubusercontent.com/44454303/51631137-25272580-1f09-11e9-9ce3-e36e2c0db65c.png)

**Comment by martinservold** [comment]
Also, repair option returns the same error.

**Comment by eirannejad** [comment]
Open Registry Editor (`regedit.exe`), navigate to the key below and find the pyRevit sub key and delete. this would remove it from the uninstall window. You can delete the installation files manually. pyRevit doesn't write anything outside of that

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall`

**Comment by martinservold** [comment]
I had to go through the entire registry and remove anything associated to pyrevit (not just that directive), but I got it to install again without erroring. It still did not create .addin files for me, but after creating my own it loaded fine.

**Comment by eirannejad** [comment]
@martinservold Sorry for the inconvenience. The installer is heavily tied to the pyRevit cli command and sometime bugs happen. It's a work in progress and will get better over time.
