### ISSUE TITLE
pyRevit Search tool doesn't pick up Revit Addins that have numbers in the Revit command

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#493]
**Describe the bug**
I noticed in prRevit v4.6.12 that PyRevit Search tool doesn't pick up to Revit addins that have numbers in the Revit command.

Refer to screen shot.
![image](https://user-images.githubusercontent.com/8776947/51678512-7e0fc000-1fd4-11e9-8ebe-8fc1ff59cf77.png)

Thanking you in advance

Rob

**Comment by eirannejad** [comment]
pyRevit search doesn't pick up Revit commands that are not builtin. Only those commands support the PostableCommand API and could be requested to run from a third-party addon.

https://www.apidocs.co/apps/revit/2019/f6ccdc1b-6ac3-9c49-d0bb-8a7d1877eab0.htm
