### ISSUE TITLE
Print Ordered Sheet Index - Random Sheet Rotation

### ISSUE THREAD

**Issue by Cslaten78** [eirannejad/pyRevit#494]
The Print Ordered Sheet Index Tool is a life saver.  I was wondering if anyone else has had the following issue when printing to PDF (I use Bluebeam).  
The sheets seem to randomly rotate between landscape and portrait.  The prints are fine, but it's annoying to go through a 400 sheet PDF and rotate certain sheets to the correct orientation.  It appears to do this at random and happens when printing sheets individually and combined.  
Is this a known issue or could it be user error?
Thanks for such helpful tools!

![image](https://user-images.githubusercontent.com/47009515/51704404-fda68a80-1fe6-11e9-9c44-79ee37175798.png)

**Desktop (please complete the following information):**
 - OS:Windows 10 Pro
 - pyRevit v4.6.12

```
U:\>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)
Name: "master" | Deploy: "basepublic" | Path: "C:\Users\cslaten\AppData\Roaming\pyRevit-Master"
==> Attachments
Autodesk Revit 2017.2.3 | Clone: "master" | Engine: "277"
Autodesk Revit 2018.3.2 | Clone: "master" | Engine: "277"
Autodesk Revit 2019 First Customer Ship | Clone: "master" | Engine: "277"
==> Installed UI Extensions
==> Installed Library Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2017.2.3 | Version: 17.0.1150.0 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
Autodesk Revit 2018.3.2 | Version: 18.3.2.7 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
Autodesk Revit 2019 First Customer Ship | Version: 19.0.0.405 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
PID: 6464 | Autodesk Revit 2018.3.2 | Version: 18.3.2.7 | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2018"
==> User Environment
Microsoft Windows 10 [Version 10.0.17134]
Executing User: PPA\cslaten
Active User: PPA\cslaten
Adming Access: No
%APPDATA%: "C:\Users\cslaten\AppData\Roaming"
Latest Installed .Net Framework: "4.7.2"
Error: Could not find a part of the path 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework'.
Run with "--debug" option to see debug messages
```

**Comment by eirannejad** [comment]
This is happening with the new bluebeam driver. Not a pyRevit issue. Please confirm this happens from native print window as well.

**Comment by Cslaten78** [comment]
I have not been able to replicate this using the native Revit print tool.

**Comment by eirannejad** [comment]
That's odd. pyRevit uses Revit's internal print engine. I have the same issue here whether I use pyRevit print or not. Thanks for the reporting

**Comment by Cslaten78** [comment]
I'm running a few more tests printing a large set in both native revit and pyrevit using combined and individual sheets.  Obviously it will take a while, but I'll report any findings that come out of it.

**Comment by Cslaten78** [comment]
Testing shows that the rotation issue is only happening when I print using the pyRevit tool.  I printed the same sheet set for all 4 print runs.  The rotated sheets are not consistent between the two pyRevit prints.

For your reference, I'm using Bluebeam  Revu x64 CAD, Version 2018.
Let me know if you would like me to try anything else.

**Comment by eirannejad** [comment]
I have only seen this happening with the Bluebeam driver. Can not replicate this issue on any driver on my machine. I strongly believe this is a driver issue / API bug, since pyRevit is using the Revit API to request a print on a sheet. There is no configuration on the pyRevit side on sheet size or orientation.

Closing this unless there is more info that helps with replicating the error.
