### ISSUE TITLE
Custom field delimiter

### ISSUE THREAD

**Issue by crycx** [eirannejad/pyRevit#496]
Hello again,

Is it possible to implement a feature, where you can set a custom field delimiter. For now i have to go and change scrypt.py (in picture)

![image](https://user-images.githubusercontent.com/24211869/51775089-2faa1080-20fd-11e9-9940-324cba46a757.png)

Thanks in advance. 👍

**Comment by eirannejad** [comment]
Where is this at? Which tool?

**Comment by crycx** [comment]
![image](https://user-images.githubusercontent.com/24211869/51775281-e4443200-20fd-11e9-9a1f-3d0140ac1cc6.png)

**Comment by eirannejad** [comment]
What's the use case for a `;` as delimiter? After all [CSV](https://en.wikipedia.org/wiki/Comma-separated_values) is `Comma`-separated

**Comment by crycx** [comment]
Its based on regional settings. And i have to use ; for excel to automatically show columns.

**Comment by eirannejad** [comment]
@crycx Tested. Fascinating. I didn't know excel overrides the CSV with list separator from window regional settings. Very interesting...

**Comment by crycx** [comment]
@eirannejad Glad to inform.

**Comment by eirannejad** [comment]
Implemented. Will be pushed with 4.6.14
