### ISSUE TITLE
Match to work on Material Painted surfaces.

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#498]
**Is your feature request related to a problem? Please describe.**
Revit's Match Type Properties tool unfortunately doesn't match painted surfaces.

**Describe the solution you'd like**
Add Materiel Paint tick box to Select Options to Match. (Refer to screen shot)

**Additional context**
![image](https://user-images.githubusercontent.com/8776947/51899012-0c57bd80-23aa-11e9-9959-11503498fb2c.png)

Thanking you in advance
Rob

**Comment by eirannejad** [comment]
How do you propose matching painted surfaces on object with varying geometry?

**Comment by Robbo1234** [comment]
Can one not select the Paint material by a mouse click over the Painted
area, similar to Photoshop Paint Bucket color picker (eye dropper)?

**Comment by eirannejad** [comment]
Not as far as I know. Matching materials should technically use Revit API to ask user to select a surface and not an full element. So it could be a separate tool.

**Comment by Robbo1234** [comment]
Paint bucket/color picker functionality would be a great addition to Revit.

**Comment by eirannejad** [comment]
Implemented. Will be pushed with 4.6.14
![2019-02-01_14-12-39](https://user-images.githubusercontent.com/8197916/52152517-7a5ee780-262b-11e9-8b67-cbf1d4f9a69e.gif)

**Comment by Robbo1234** [comment]
That's brilliant Ehsan!
