### ISSUE TITLE
Network based extension error

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#499]
**Describe the bug**
When a network location is not accessible, the following two errors appeared.  Is there a way I can update the INI to skip the network location extension if it is not found?  It does load pyrevit and local extensions even after the error (as expected).  The only issue is the warnings, particularly the first one scares typical users.

**Expected behavior**
There should be a way of skipping network locations that couldn't be found without the error messages. In our office we roll a "refresh" in an extension that lives on people's local computers and that allows for users to try to access the network extension at a later time if they weren't able to access the network at time of original load.

**Screenshots**
![image](https://user-images.githubusercontent.com/14113080/51919666-eb936600-23b1-11e9-90bc-cb9a7747d4c9.png)
![image](https://user-images.githubusercontent.com/14113080/51919676-f1894700-23b1-11e9-90d8-d1a2506c4b03.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.6

**Additional context**

**Comment by eirannejad** [comment]
**Patch:** Replace line 145 in `pyrevitlib/pyrevit/userconfig.py` with `return [x for x in dir_list if op.exists(x)]` so it only returns the directories that exist

I'll push this in .14 release

**Comment by thazell** [comment]
awesome!!! Thanks!
