### ISSUE TITLE
Usage of "/" in Schedule names

### ISSUE THREAD

**Issue by crycx** [eirannejad/pyRevit#500]
**Is your feature request related to a problem? Please describe.**
I have some schedules that have a name like "Fasteners`/`Extras". Do use the Schedules to CSV I need to manually rename all schedules that have `/` in them

**Describe the solution you'd like**
Maybe its possible to check the schedule name and replace the` /` with ´&´ or `_`

**Describe alternatives you've considered**
Alternative is to continue to change the schedule name.

I really like and appreciate your schedules to CSV app.

**Comment by eirannejad** [comment]
Which pyRevit version are you using? 4.6.13 removes all special characters from export file names

**Comment by eirannejad** [comment]
Closing this. Feel free to open again if issue came back.
