### ISSUE TITLE
replace text

### ISSUE THREAD

**Issue by che-30** [eirannejad/pyRevit#501]
Replacing text from pyApex does not work: when I select elements and try to control them (sorry for my English), a message appears that nothing
![2019-01-30_17-36-49](https://user-images.githubusercontent.com/19819439/51989038-36e36c80-24b7-11e9-898a-fc89eb2f3149.png)
![2019-01-30_17-36-28](https://user-images.githubusercontent.com/19819439/51989040-36e36c80-24b7-11e9-8bd0-d06ddd5936ce.png)
![2019-01-30_17-35-38](https://user-images.githubusercontent.com/19819439/51989041-377c0300-24b7-11e9-90dc-0a17ef100150.png)

 is selected. Tried on both - eng and rus version of revit 2018

![2019-01-30_1854](https://user-images.githubusercontent.com/19819439/51993907-c2adc680-24c0-11e9-913f-c6f2274578ab.png)

**Comment by eirannejad** [comment]
Please report this on the issue tracker for pyApex project. https://github.com/apex-project/pyApex
pyApex is an extension for pyRevit. This is the issue tracker for pyRevit iteself
