### ISSUE TITLE
linkbutton for builtin tools

### ISSUE THREAD

**Issue by chauhuh** [eirannejad/pyRevit#503]
I'm trying to make a linkbutton that can reference built-in tools. Is this possible? I'm not sure how to look up the existing assembly and commandclass required by the linkbutton.

**Comment by eirannejad** [comment]
No. Builtin tools don't have class and assembly names. That's the interface designed for thirdparty functions. Builtin tools are called using [PostCommand](https://www.apidocs.co/apps/revit/2019/b0df464d-1733-ea9e-ac40-399fa9c9a037.htm) method

pyRevit search can run the builtin tools
