### ISSUE TITLE
Manage Kenotes - str object has no attribute items

### ISSUE THREAD

**Issue by lank2027** [eirannejad/pyRevit#504]
Receive warning stating `'str' object has not attribute 'items'` when clicking update model or try to place a keynote within the manager. I have tried multiple keynote files and get the same warning.

Windows 10
Revit 2019.2
pyRevit 4.6.13
pyRevit Environment:  v.0.9.0.0

**Comment by eirannejad** [comment]
Please share the full error report.

**Comment by lank2027** [comment]
**To Reproduce**
Steps to reproduce the behavior:
1. Open keynote manager to modify keynotes. 
2. Click on "Update model" or double click to "Place"
3. See error 'str' object has not attribute 'items'

**Expected behavior**
No error.

**Screenshots**

![image](https://user-images.githubusercontent.com/47336341/52237553-aa51f900-287e-11e9-9575-4457f85a48fb.png)


 - OS: [Window10]
 - pyRevit Version [4.6.13]
 - pyRevit Environment:
 ==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.6.13" | Path: "C:\Users\DCurran\AppData\Roaming\pyRevit-Master"
==> Attachments
Autodesk Revit 2016 Update 8 for R2 (2016.1.8) | Clone: "master" | Engine: "277"
Autodesk Revit 2019.2 (Update) | Clone: "master" | Engine: "277"
==> Installed UI Extensions
==> Installed Library Extensions
==> Default Extension Search Path
C:\Users\DCurran\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2016 Update 8 for R2 (2016.1.8) | Version: 16.0.1205.0 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016\"
Autodesk Revit 2019.2 (Update) | Version: 19.2.0.65 | Language: 1033 | Path: "C:\Program Files\AutodeskRevit 2019\"
==> Running Revit Instances
PID: 16332 | Autodesk Revit 2019.2 (Update) | Version: 19.2.0.65 | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> User Environment
Microsoft Windows 10 [Version 10.0.17763]
Executing User: GRAPHITE\dcurran
Active User: GRAPHITE\dcurran
Adming Access: No
%APPDATA%: "C:\Users\DCurran\AppData\Roaming"
Latest Installed .Net Framework: "4.7.2"
No .Net Target Packs are installed.
pyRevit CLI 0.9.0.0

`pyrevit env`

Let me know if I need to provide any other info.
Thanks for the help. This addin is awesome! Cheers

**Comment by eirannejad** [comment]
@lank2027 Please delete the the `Keynotesconfig` section from your pyRevit config file under `%appdata%/pyRevit/pyrevit_config.ini`

It looks similar to this. Delete all five lines. Save and lunch Revit and the tool again.

```ini
[Keynotesconfig]
last_window_geom = {}
last_postcmd_idx = {}
last_category = {}
last_search_term = {}

```

**Comment by lank2027** [comment]
Ehsan, that worked. Thank you Sir.
