### ISSUE TITLE
Find and Select Entities without Tags

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#507]
**Describe the bug**
When I'm in a Revit Ceiling View and select "Find and Select Entities without Tags" it doesn't pick up Revit Ceilings for some reason

**To Reproduce**
1. Go to pyRevit Select
2. Click on "Find and Select Entities without Tags" 
3. Option for Revit Ceilings is missing as per Screen shot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/8776947/52293337-76560100-296e-11e9-983f-e3a1d7d524bd.png)

**Desktop (please complete the following information):**
 - OS: Window 8
- pyRevit Version v4.6.14
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

**Comment by eirannejad** [comment]
Implemented. Will be pushed with 4.6.15
