### ISSUE TITLE
user_config: non-ASCII chars produce critical error

### ISSUE THREAD

**Issue by melnikovalex** [eirannejad/pyRevit#511]
**Describe the bug**
Hi Ehsan! I think I found a critical issue, which seems not to be wrapped with exception in pyRevit code. There are two parts.

1. It's impossible to write non-ASCII string using `script.get_config()` and `save_config()`

2. When I tried to reproduce it I've got my `pyRevit_config.ini` file cleaned (0 bytes)

**To Reproduce**
There is a code of a script.py to produce the issue:
```
# -*- coding: utf-8 -*-
from pyrevit import script
logger = script.get_logger()
_config = script.get_config()

_config.test_string1 = "s"
try:
    _config.test_string3 = u"ы"
except Exception as exc:
    logger.error(exc)

script.save_config()

```

After run I am getting Error in pyRevit log and content of ini file is being cleaned:

`ERROR: [pyrevit.userconfig] Can not save user config to: C:\Users\Alex\AppData\Roaming\pyRevit\pyRevit_config.ini | ('unknown', '\x00', 0, 1, "'ascii' codec can't encode character '\\u44B' in position 976")`

**Expected behavior**
It would be great to have a possibility to write non-Ascii chars (e.g. Cyrillic) to config. 

Maybe there is a workaround to convert endoding before save but I couldn't find any solution yet.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home (Russian)
 - pyRevit Version: CLI v0.6.0.0, installer v4.6.12
 - pyRevit Environment (before run): 
```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)
Name: "master" | Deploy: "basepublic" | Path: "C:\pyRevit-Master"
==> Attachments
Autodesk Revit 2017.2 | Clone: "master" | Engine: "279"
Autodesk Revit 2018.2 | Clone: "master" | Engine: "279"
Autodesk Revit 2019 Update for Trial Build | Clone: "master" | Engine: "277"
==> Installed UI Extensions
==> Installed Library Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2017.2 | Version: 17.0.1117.0 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
Autodesk Revit 2018.2 | Version: 18.2.0.51 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
Autodesk Revit 2019 Update for Trial Build | Version: 19.0.1.1 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
PID: 8384 | Autodesk Revit 2017.2 | Version: 17.0.1117.0 | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2017"
PID: 8408 | Autodesk Revit 2018.2 | Version: 18.2.0.51 | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2018"
==> User Environment
Microsoft Windows 10 [Version 10.0.17134]
Executing User: ALEX-NB\Alex
Active User: ALEX-NB\Alex
Adming Access: No
%APPDATA%: "C:\Users\Alex\AppData\Roaming"
Latest Installed .Net Framework: "4.7.2"
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.X
pyRevit CLI 0.6.0.0
```

Thank you!

**Comment by melnikovalex** [comment]
Sorry for panic! It was old pyRevit

**Comment by eirannejad** [comment]
@melnikovalex No worries! :)
