### ISSUE TITLE
Find and Select Entities without Tags doesn't highlight Revit Doors that are not tagged.

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#512]
**Describe the bug**
Find and Select Entities without Tags doesn't highlight Revit Doors that are not tagged.

**To Reproduce**
1. Go to pyRevit Select
2. Click on Find and Select Entities without Tags
3. Choose Doors plus I noticed that it doesn't pick up Revit items that are in the Revit view such as the following:
- Columns
- Floors
- Furniture
- Plumbing Fixtures 
- Stairs
4. prRevit Dialog pops up "All door have associated tags" (which is incorrect) refer to screen shot

**Screenshots**
![image](https://user-images.githubusercontent.com/8776947/52342456-59243f80-2a0d-11e9-85ba-1d46997e98a5.png)

**Desktop (please complete the following information):**
 - OS: Window 8
 - pyRevit Version pyRevitv4.6.14

**Additional context**
Find and Select Entities without Tags work fine for Walls in the same Revit view.

**Comment by eirannejad** [comment]
This tool was completely reworked under issue #507
Changes will be pushed under 4.6.15

**Comment by Robbo1234** [comment]
Ehsan,

I just tested pyRevit 4.6.15 and I noticed that it doesn't pick up Revit Furniture and Casework items. Refer to screen shot.

![image](https://user-images.githubusercontent.com/8776947/52558562-9eb88200-2dea-11e9-925b-812625dcb207.png)
