### ISSUE TITLE
pyRevit search box is hard to select

### ISSUE THREAD

**Issue by DuncanLithgow** [eirannejad/pyRevit#513]
**Describe the bug**
pyRevit search has such a small spot to place the cursor that I wrote a whole bug report about it not working and hanging Revit! (I didn't submit it)

**To Reproduce**
1 Start the pyRevit tool, the dialogue appears center screen, but is hard to select. Failing to select it appears to hang revit (nothing can be selected)

**Expected behavior**
pyRevit search should be easy to select or give a hint on where to click, or just say 'start typing'

**Screenshots**
-

**Desktop (please complete the following information):**
 - Win10
 - pyRevit Version 4.6.8
 - pyRevit Environment: 
```
Microsoft Windows [Version 10.0.16299.904]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\duli>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)
Name: "master" | Deploy: "basepublic" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
Autodesk Revit 2017.2.2 | Clone: "master" | Engine: "277"
Autodesk Revit 2018.3.2 | Clone: "master" | Engine: "277"
==> Installed UI Extensions
==> Installed Library Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2017.2.2 | Version: 17.0.1146.0 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
Autodesk Revit 2018.3.2 | Version: 18.3.2.7 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
Autodesk Revit 2019 First Customer Ship | Version: 19.0.0.405 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
PID: 15448 | Autodesk Revit 2018.3.2 | Version: 18.3.2.7 | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2018"
```

**Additional context**

**Comment by eirannejad** [comment]
I have never seen this issue before. pyRevit search tool opens the window and you can just type without the need to click anywhere. The search textbox has focus.

I need more info:
Are you using your own pyRevit extensions?
Do you have issues with any other pyRevit windows?
Can you upgrade to 4.6.14 and test again?

**Comment by eirannejad** [comment]
@DuncanLithgow Any updates?

**Comment by DuncanLithgow** [comment]
Hi Ehsan
As I understand it pyRevit is behaving as you intended.

But, being able to type without selecting the text box is not how the Revit works - so it didn't occur to me until I notices it in a different function in pyRevit.

I'm inclined to think that extensions to software should mimic the behavior of the software they extend.

**Comment by eirannejad** [comment]
Revised the hint to inform user they can type to search.

![2019-02-14 13_12_38-autodesk revit 2019 2 - kfiletext rvt - floor plan_ level 1](https://user-images.githubusercontent.com/8197916/52817982-4c7d9800-305a-11e9-90e2-cf270004f320.png)
