### ISSUE TITLE
PyRevit Copy State- Add Copy View Properties i.e. View Template, Scope box, View Range, Color Scheme, Underlay

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#514]
**Is your feature request related to a problem? Please describe.**
It would be a fast way of copy Views Properties settings such as View Template, Scope Box, View Range, Color Scheme, Underlay, Depth Clipping from one Revit view to another Revit view without having to create and setup loads of Revit View Templates.

**Describe the solution you'd like**
When you click on PyRevit Copy State you will be offered these extra Copt State options: (refer to screen shot)
- View Template
- Scope Box
- View Range
- Color Scheme
- Underlay
- Depth Clipping
- Phase

**Additional context**
![image](https://user-images.githubusercontent.com/8776947/52349470-87f6e180-2a1e-11e9-8223-4cf50129c116.png)

**Comment by gusx2m** [comment]
@eirannejad - I need to Copy View Range's! Is this possible with PyRevit (or any other way)?

**Comment by Up-Mojo** [comment]
@eirannejad - Kindly requesting a way to compare view templates.  Copy state and paste to excel or word would work if it's doable.
