### ISSUE TITLE
userconfig

### ISSUE THREAD

**Issue by michaelmontagne** [eirannejad/pyRevit#518]
I think there is a bug in pyrevitlib\pyrevit\userconfig.py
I get a message saying "expected string got List" when saving settings.  Behavior was consistent on multiple installations 4.6.14.
I changed the function referenced to this and fixed it.  Not sure if I did the right thing though.

   def set_thirdparty_ext_root_dirs(self, path_list):
        """Updates list of external extension directories in config file

        Args:
            path_list (list[str]): list of external extension paths
        """
        **for path in path_list:
            if not op.exists(path):**
                raise PyRevitException("Path does not exist.")
        try:
            self.core.userextensions = \
                [op.normpath(x) for x in path_list]
        except Exception as write_err:
            mlogger.error('Error setting list of user extension folders. | %s',
                          write_err)

**Comment by eirannejad** [comment]
See this please. https://github.com/eirannejad/pyRevit/issues/508

Delete the config file and restart Revit.
