### ISSUE TITLE
clones removed by CLI

### ISSUE THREAD

**Issue by michaelmontagne** [eirannejad/pyRevit#519]
pyRevit 4.6.14
CLI 0.3.0

I still have the issue of clones being removed from pyRevit_config.ini.  I previously believed it was opening Revit that removed the "clones" settings but now I believe it is invoking the CLI.  Repeatedly opening Revit does not change the setting but if I run "pyrevit clones"  or pyrevit attached" from the command line, the settings are changed to:
[environment]
clones = {}

**Comment by eirannejad** [comment]
Your CLI is very old. Try with the new CLI tool. pyRevit ships with the most recent so I'm not sure why you're still using the v0.3.0

Test and update this thread please.
https://github.com/eirannejad/pyRevit/releases/tag/cli-v0.9.0.0

**Comment by eirannejad** [comment]
Resolved and will be pushed with new CLI version soon.
