### ISSUE TITLE
Printing ordered sheet list doesn't print sheet list/schedule on sheet

### ISSUE THREAD

**Issue by n8mulder** [eirannejad/pyRevit#520]
**Describe the bug**
When I use the 'print ordered sheets' feature the PDFs are created as expected but any sheets lists on a sheet do not. See screenshots below.

**To Reproduce**
1. Go to pyRevit and select Print dropdown
2. Click on 'Print Ordered Sheets'
3. Make desired selections
4. PDFs are created in order as expected
5. However, sheet list schedules that are on a sheet do not pdf/print, only the sheet title.

**Expected behavior**
I would expect a sheet list schedule, if on a sheet, to print/pdf

**Screenshots**
Sheet in Revit
![image](https://user-images.githubusercontent.com/37081033/52443199-b6da8980-2aea-11e9-8adf-201ce97f6bcf.png)

Sheet in PDF after using print ordered sheets
![image](https://user-images.githubusercontent.com/37081033/52443392-2b152d00-2aeb-11e9-9d9a-b6f0d23d6b91.png)

**Desktop:**
 - OS: [W10 64]
 - pyRevit Version [4.6.14]
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

```==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.6.14" | Path: "C:\Users\nmulder\AppData\Roaming\pyRevit-Master"
==> Attachments
Autodesk Revit 2016 Update 7 for R2 | Clone: "master" | Engine: "277"
Autodesk Revit 2017.2.4 | Clone: "master" | Engine: "277"
Autodesk Revit 2018.3.2 | Clone: "master" | Engine: "277"
Autodesk Revit 2019.2 (Update) | Clone: "master" | Engine: "277"
==> Installed UI Extensions
==> Installed Library Extensions
==> Default Extension Search Path
C:\Users\nmulder\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2016 Update 7 for R2 | Version: 16.0.1185.0 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016\"
Autodesk Revit 2017.2.4 | Version: 17.0.1158.0 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
Autodesk Revit 2018.3.2 | Version: 18.3.2.7 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
Autodesk Revit 2019.2 (Update) | Version: 19.2.0.65 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
PID: 6896 | Autodesk Revit 2018.3.2 | Version: 18.3.2.7 | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2018"
PID: 18636 | Autodesk Revit 2017.2.4 | Version: 17.0.1158.0 | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> User Environment
Microsoft Windows 10 [Version 10.0.17134]
Executing User: SAFIRROSETTI\nmulder
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages```

**Comment by eirannejad** [comment]
Huh! Is that the same sheet list used to print the sheets in the tool?

**Comment by n8mulder** [comment]
I too thought that might be the issue but in my testing so far it does not
discriminate; if it is a sheet list schedule it does not plot. I have not
tested with other category schedules.

**Comment by eirannejad** [comment]
@n8mulder See my update comment above.

**Comment by n8mulder** [comment]
Well duh, I guess that explains it:
![image](https://user-images.githubusercontent.com/37081033/52501097-2ad96800-2ba5-11e9-9fd2-6be2051d227b.png)

When I read in the hovertip that it inserts 'invisible characters at the start of sheet names' I took that to mean it was ordering them outside of Revit. Reading it more closely, and the Shift-Click instructions, now makes more sense. So basically filtering by sheet name is not an option to allow for this tool to work?

I'm new to pyRevit and Python...having fun exploring all the tools and possibilities! Thanks!

**Comment by eirannejad** [comment]
How about editing the filter to use "Contains" and "Does not Contain"?

**Comment by n8mulder** [comment]
Yes, that works, the sheet list printed on sheet. We are a multi-discipline firm so it remains to be seen if 'contains/does not contain' is precise enough...seems like it should be in most cases. Thanks for the help troubleshooting!

**Comment by eirannejad** [comment]
**Dev Note:** At the moment there are no workarounds for pushing Revit to print and merge sheets in order, other than modifying the sheets numbers for proper sorting.
A note has been added to the tooltip to notify the user about this particular issue.

Closing this until Revit API has a better printing mechanism.
