### ISSUE TITLE
Manage Keynotes: Update Keynote

### ISSUE THREAD

**Issue by braab1** [eirannejad/pyRevit#522]
Manage Keynotes: when editing keynotes, finalizing the edit by selecting "update keynote" yields the following error message: "Record does not exist in table 'keynotes'." The edited keynote is not updated and is then locked for editing by my username, but I cannot go back and re-edit.

![image](https://user-images.githubusercontent.com/47532661/52575802-dd4f3c00-2dec-11e9-9466-6b1b6a78d049.png)

**Comment by alexdaversa** [comment]
This seems to be a bug specifically in keynotes without a parent.

**Comment by eirannejad** [comment]
@alexdaversa How are you creating a keynote with no parent??

**Comment by alexdaversa** [comment]
@eirannejad the keynotes were imported from a working keynote file used on a previous project. The import worked successfully, but editing keynotes without a parent resulted in the same error message as in the screenshot as above.

**Comment by alexdaversa** [comment]
@eirannejad We worked around the issue by adding a parent to all keynotes manually before adding them to Revit using the Manage Keynotes tool--but wouldn't at least one keynote in the list not have a parent?

**Comment by eirannejad** [comment]
@alexdaversa Any keynote with not Parent is a "Category". Move those to the `@table(categories...` table

**Comment by eirannejad** [comment]
Can not replicate the error using the import keynotes tool. The import assumes any keynote without a parent is actually a category and works fine.

The only explanation is that a special character is used for the keynote parent.

**Comment by alexdaversa** [comment]
[00_RevitKeynotes_Imperial_532_old.txt](https://github.com/eirannejad/pyRevit/files/2889948/00_RevitKeynotes_Imperial_532_old.txt)
This is the keynote file in question that caused the error message. I'm not suggesting that the plugin should be updated to deal with this sort of poorly formatted file--rather, we (as a firm) should work from a known well-formatted base file to avoid these issues.

**Comment by eirannejad** [comment]
@alexdaversa Okay thanks a lot for this. The issue was something else completely and I fixed it. The problem was the GUI would allow you to edit a category when in `ALL CATEGORIES` listing mode using the edit keynote button.
