### ISSUE TITLE
Fix pyRevit asking for attachment from CLI configs. It should already know that.

### ISSUE THREAD

**Issue by Denver-22** [eirannejad/pyRevit#526]
![pyrevit47_1](https://user-images.githubusercontent.com/44049465/52947127-e741e380-3386-11e9-8f3d-f96f04dc87ab.png)
![pyrevit47_2](https://user-images.githubusercontent.com/44049465/52947139-edd05b00-3386-11e9-9773-617e3a35fd59.png)

But pyrevit 4.6 works fine under the same conditions.

**Comment by eirannejad** [comment]
would you share the `pyrevit env` results please.

**Comment by Denver-22** [comment]
I installed pyRevit manually from a zip archive.
So now I installed the CLI from pyRevit.CLI_0.9.0.0_signed.exe to run it from cmd.
The result is as follows:
```
C:\Users\user>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)
==> Attachments
Error: pyRevit is attached to Revit 2017 but can not determine the clone and engine
Error: pyRevit is attached to Revit 2018 but can not determine the clone and engine
==> Installed UI Extensions
==> Installed Library Extensions
==> Default Extension Search Path
C:\Users\user\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2017.2.3 | Version: 17.0.1150.0 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
Autodesk Revit 2018.3.1 | Version: 18.3.1.2 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.16299]
Executing User: VAFINDAMIR\user
Active User: VAFINDAMIR\user
Adming Access: No
%APPDATA%: "C:\Users\user\AppData\Roaming"
Latest Installed .Net Framework: "4.7.1"
No .Net Target Packs are installed.
pyRevit CLI 0.9.0.0
```
It most likely will not give you information.

On the PC installed Revit 2015, 2017, 2018.
PyRevit 4.6.15 works successfully on all versions (installed and configured manually). And 4.7beta gives an error (tested for 2015 and 2018).
By the way, I got the same error on Revit 2018.3.

If I can help with anything else, I'm ready.

**Comment by eirannejad** [comment]
Hey. See there are no clones listed after the `==> Registered Clones (deployed from archive)` line. That's why it'd failing the load. I have made some changes to the load process that might need to fix.

Anyway,
Register you're 47beta clone first

`pyrevit clones add 47beta /path/to/your/clone/location`

And then re-attach it

`pyrevit attach 47beta 277 --installed`

**Comment by Denver-22** [comment]
I want to report on the situation:
I added clones:
```
pyrevit clones add 46 "c: \ pyRevit \ pyRevit-v46"
pyrevit clones add 47 "c: \ pyRevit \ pyRevit-v47"
```
They appeared in the `% AppData% \ pyRevit \ pyRevit_config.ini` file.
Command
`pyrevit attach 47 277 --installed 2018`
does not work.
Command
`pyrevit attach 47 277 --installed`
only works for Revit 2017 and 2018 (**2015 ignored**).
And pyRevit.addin is installed in `% AppData% \ Autodesk \ Revit \ Addins \`. And my manually added file was in `% ProgramData% \ Autodesk \ Revit \ Addins \` (and I didn’t immediately understand where the problem was). But I deleted my file and pyRevit 4.7beta successfully loaded into Revit 2018 (along with all the built-in and additional extensions).

The question is as follows:
CLI is a tool for more convenient work with pyRevit clones. But I can do the same thing manually (as it seemed to me).
In particular, I manually changed `pyRevit46.addin` to `pyRevit47.addin` in `% ProgramData% \ Autodesk \ Revit \ Addins \`. And therefore he believed that the registration of clones is not required.
In addition, I checked the contents of the `pyRevit.addin` file created in the CLI - it is identical to my `pyRevit47.addin` file. And now it's a mystery to me why one file works and the other doesn't.
I decided to test: put my `pyRevit47.addin` file in `% AppData% \ Autodesk \ Revit \ Addins \ 2018`. PyRevit 4.7 has started. But this method did not work for Revit 2015 (see above on: `pyrevit attach 47 277 --installed`).

**Comment by Denver-22** [comment]
I want to report on the situation:
I added clones:
```
pyrevit clones add 46 "c: \ pyRevit \ pyRevit-v46"
pyrevit clones add 47 "c: \ pyRevit \ pyRevit-v47"
```
They appeared in the `% AppData% \ pyRevit \ pyRevit_config.ini` file.
Command
`pyrevit attach 47 277 --installed 2018`
does not work.
Command
`pyrevit attach 47 277 --installed`
only works for Revit 2017 and 2018 (**2015 ignored**).
And pyRevit.addin is installed in `% AppData% \ Autodesk \ Revit \ Addins \`. And my manually added file was in `% ProgramData% \ Autodesk \ Revit \ Addins \` (and I didn’t immediately understand where the problem was). But I deleted my file and pyRevit 4.7beta successfully loaded into Revit 2018 (along with all the built-in and additional extensions).

The question is as follows:
CLI is a tool for more convenient work with pyRevit clones. But I can do the same thing manually (as it seemed to me).
In particular, I manually changed `pyRevit46.addin` to `pyRevit47.addin` in `% ProgramData% \ Autodesk \ Revit \ Addins \`. And therefore he believed that the registration of clones is not required.
In addition, I checked the contents of the `pyRevit.addin` file created in the CLI - it is identical to my `pyRevit47.addin` file. And now it's a mystery to me why one file works and the other doesn't.
I decided to test: put my pyRevit47.addin file in % AppData% \ Autodesk \ Revit \ Addins \ 2018. PyRevit 4.7 has started. But this method did not work for Revit 2015 (see above on: `pyrevit attach 47 277 --installed`).

**Comment by Denver-22** [comment]
Some more tests. Commands:
```
pyrevit attach 47 277 --installed 2015
pyrevit attach 47 277 --installed
```
Do not add pyRevit.addin to Revit 2015.

And the question is:
Does the attach command just create `pyRevit.addin` in the right folder or write information to another file? In `%AppData%\pyRevit\pyRevit_config.ini` this information is not displayed ...

**Comment by eirannejad** [comment]
Hold on. Revit 2015 is not listed on the `pyrevit env` either. What's the build code for your Revit 2015?

**Comment by Denver-22** [comment]
Revit 2015 Update Release 14 - 20160512_0715(x64)

**Comment by eirannejad** [comment]
Hmm odd. I have the build number in the code.
Please run `pyrevit revits --installed --debug` and share the results. You can direct the output to a text file using redirection `pyrevit revits --installed --debug > textfile.txt`

**Comment by Denver-22** [comment]
[pyrevit_revits.txt](https://github.com/eirannejad/pyRevit/files/2883493/pyrevit_revits.txt)

I forgot to say that the command
`pyrevit attach 47 277 --installed 2015`
(and with any version of Revit does not work.
Works only:
`pyrevit attach 47 277 --installed`
As already wrote earlier - with Revit 2017 and 2018 (without 2015).
Attached file made based on 0.12.0, previously was 0.9.0. The result is the same.

**Comment by eirannejad** [comment]
The command `pyrevit attach 47 277 --installed 2015` is not formatted correctly. See CLI help
It should be `pyrevit attach 47 277 2015` if you're trying to attach to Revit 2015.

I can see that the CLI tool can not see your Revit 2015 installation. I'll work on fixing that.

Meanwhile you can copy the `pyrevit.addin` file from `%appdata%/Autodesk/Revit/Addons/2017` to the `2015` directory and it will load pyRevit in 2015.

**Comment by eirannejad** [comment]
Fixed. Will be issued with next version this weekend.

**Comment by Denver-22** [comment]
`pyrevit attach 47 277 2015` - It worked!
But when I launch Revit 2015, the error reappears, which I showed in the first message.
So the initial problem is not in the CLI. After all, essentially the same pyRevit.addin I manually added the desired folder.
I will wait for the release of the new version. Thanks for participating and for pyRevit! ))

**Comment by eirannejad** [comment]
Yes. I have resolved the issue and will publish the changes this weekend with the new version.
