### ISSUE TITLE
Manage Keynotes

### ISSUE THREAD

**Issue by DTatRamsa** [eirannejad/pyRevit#527]
Hi,

Just wanted to ask if / when the official release for Manage Keynotes functionality is planned to come through. Our firm is tired of using keynote manager from revolution design and really like what we're seeing from even the beta version and am eagerly waiting for the official release so that we can deploy to our team members.

**Comment by eirannejad** [comment]
Great question. I have been waiting to get feedback from teams that are using this keynote manager so I can resolve major issues if any before publishing the first stable version.

Have you ran tests on actual teams with multiple people? Any issues?

**Comment by DTatRamsa** [comment]
Hi Ehsan,

We are looking to do a test run with one or two of the design projects – we will get in touch with you if we run into any issues throughout the next few weeks / months.


Timothy Yang
Design Technology Support Specialist
Robert A.M. Stern Architects, LLP
One Park Avenue, New York, New York 10016
Phone: 212 967 5100
t.yang@ramsa.com
www.ramsa.com<http://www.ramsa.com/>



The information contained in this communication and any enclosures or attachments may be confidential and/or proprietary. It is intended only for the recipient or recipients named above. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication or its contents or attachments is strictly prohibited. If you have received this communication in error, please immediately advise the sender and delete the original and any copies from your computer system.

**Comment by eirannejad** [comment]
@DTatRamsa Awesome. Keep me posted on the schedule and results. :) I' meager to publish the first stable version.
