### ISSUE TITLE
install

### ISSUE THREAD

**Issue by Astra-arch** [eirannejad/pyRevit#528]
**Describe the bug**
Replace these lines with your description. Be as specific as possible and list steps to reproduce the issue. If you have any suggestions for the solution please list that as well.

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - pyRevit Version [e.g. 22]
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

**Additional context**

**Comment by eirannejad** [comment]
What kind of issue report is this? There is nothing here that tells me whats the issue!
