### ISSUE TITLE
Keynote Manager Feedback

### ISSUE THREAD

**Issue by tomekpiatek** [eirannejad/pyRevit#529]
First of all thanks for adding this feature. It's something that is sorely missing in Revit. OK, now quick feedback from a very quick first impression look at the Keynote Manager.

* Showing all keynotes in light grey is very confusing as it makes the notes look disabled or unavailable. Greying out items is the usual convention for showing that something is disabled. Notes should appear as being available. Placed notes have a tag next to them so that's enough to show that they have been placed.
* Notes window should not be modal and it should be possible to place multiple notes. This is the exact problem with Revit's native implementation. When we work with keynotes it's typically in a batch fashion where once you've drawn your detail you go into "annotation mode" (mentally) and you want to keep placing notes. As you place the notes you often need to adjust notes that are already there. Having the window be modal makes this impossible and it is frustrating having to invoke the Keynote Manager every single time for every note.

Those are the two big ones for now. I'll append more feedback here as I field test the tool.

**Comment by n8mulder** [comment]
I agree with @tomekpiatek, this is a great tool - thank you!  We are just beginning to test on projects but it looks very promising, even in beta.  As @tomekpiatek's second bullet suggests, modal functionality would be very nice.

I have a question and some feedback:

1. Not all features/buttons are active. Is this documented somewhere I missed?
![image](https://user-images.githubusercontent.com/37081033/53347157-210e6f00-38de-11e9-9275-fb90f50c5297.png)

2. We are a multidiscipline firm that usually works in a single model. We keep our keynotes separate by using a prefix. As it is now, it doesn't handle alphanumeric sorting how I would expect/prefer.
![image](https://user-images.githubusercontent.com/37081033/53347247-4e5b1d00-38de-11e9-9243-8776c1bd5d31.png)

**Comment by eirannejad** [comment]
@tomekpiatek @n8mulder 
Thanks a lot for the great suggestions.
Keynote (used/unused) styling corrected and published in v4.6.16 plus other improvements
Keynote alphanumeric sorting by key is added and will be published with 4.6.17

Unfortunately the non-model keynote manager is a little trouble right now. I have had completed testing on it and left it to be a future feature. The adding keynote to the model is a hacky solution at the moment since Revit API does not have a proper method for adding keynotes.

@n8mulder 
Disabled buttons are reserved buttons for upcoming features.

**Comment by tomekpiatek** [comment]
I figured that the keynote adding was a bit of a workaround. There are other systems out there that also do it in a funny way. My ideal workflow would be to drag a keynote from a list of keynotes to an element in the model. That would trigger Revit’s keynote placement mechanism, with or without a leader.

Thanks for being so good with our feedback and taking in all on board. You’re doing some really good work.

-t

---
Tomek Piatek

**Comment by aaronbergmann** [comment]
Is the "add child keynote" button meant to be disabled in 4.6.16?

Thanks.

**Comment by eirannejad** [comment]
@aaronbergmann No. The button gets activated when you're not in `----ALL CATEGORIES----` mode. Select any of the categories and then you can add sub keynotes to selected keynote
