### ISSUE TITLE
Problem with Find Views Showing Selected Elements

### ISSUE THREAD

**Issue by eluvs** [eirannejad/pyRevit#530]
When I run the "Find Views Showing Selected Elements" command, it searches through every view and says that 0 are found in every view. Even if I have the view open in which it is selected, it still says that 0 were found.

pyRevit v4.6.16
![annotation 2019-02-25 150046](https://user-images.githubusercontent.com/34044878/53374768-3a2f1400-390e-11e9-9ac9-7779eb51f733.jpg)
![annotation 2019-02-25 150215](https://user-images.githubusercontent.com/34044878/53374821-60ed4a80-390e-11e9-9e9f-9a8b543a03ac.jpg)

**Comment by eirannejad** [comment]
Resolved and will be issued with 4.6.17 this weekend
