### ISSUE TITLE
Copy VG filters

### ISSUE THREAD

**Issue by grzechu2004** [eirannejad/pyRevit#532]
**Describe the bug**
"Copy VG filters" (which is a part of pyApex addin) doesn't work with the newest version of pyRevit (4.6.13). I had to downgrade to 4.5 to make it work.
It says that there is an error in one of line of code.

I would be grateful for resolving the issue.

**Comment by eirannejad** [comment]
Submitted changed to pyApex maintainer

**Comment by eirannejad** [comment]
Closing this on pyRevit side

**Comment by Robbo1234** [comment]
Ehsan,

Can Copy VG filters be added to PyRevit?

**Comment by eirannejad** [comment]
That's a question for @melnikovalex

**Comment by Robbo1234** [comment]
Ehsan,

When I go to Enable pyApex extension I get this error (refer to below) 
nb: pyApex does not load on Revit ribbon even if it is Enabled in the pyRevit Extension Manager. Refer to screenshot.

![image](https://user-images.githubusercontent.com/8776947/53587110-728a5880-3b81-11e9-8723-5518f6f73e2e.png)

INFO: [Reload] Reloading....
INFO: [pyrevit.loader.sessioninfo] pyRevit version: 4.6.16 - </> with :growing_heart: in ['pdx', 'hio', 'rno']
INFO: [pyrevit.loader.sessioninfo] pyRevit Rocket Mode enabled. :rocket:
INFO: [pyrevit.loader.sessioninfo] Host is Autodesk Revit 2017 (build: 20171027_0315(x64) id: 22904)
INFO: [pyrevit.loader.sessioninfo] Running on: 2.7.7 (IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (64-bit))
INFO: [pyrevit.loader.sessioninfo] User is: robcross
INFO: [pyrevit.loader.sessioninfo] Home Directory is: C:\Users\rob.cross\AppData\Roaming\pyRevit-Master
INFO: [pyrevit.loader.sessioninfo] Session uuid is: 289d237b-b733-4169-b59a-c79aa8981d22
INFO: [pyrevit.loader.sessioninfo] Base assembly is: pyRevit_2017_0c75797972778602_PyRevitBaseClasses
INFO: [pyrevit.loader.sessioninfo] Config file is (User): C:\Users\rob.cross\AppData\Roaming\pyRevit\pyRevit_config.ini
INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly loaded from cache: pyRevitCore
INFO: [pyrevit.extensions.extensionmgr] Skipping disabled ui extension: pyRevitTags
INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly loaded from cache: pyRevitTools
INFO: [pyrevit.extensions.extensionmgr] Skipping disabled ui extension: pyRevitTutor
INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly loaded from cache: pyApex
INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly loaded from cache: pyL_R
INFO: [pyrevit.extensions.extensionmgr] Skipping disabled ui extension: PyRevitPlus
INFO: [pyrevit.loader.sessionmgr] Extension assembly created: pyRevitCore
INFO: [pyrevit.loader.sessionmgr] Extension assembly created: pyRevitTools
INFO: [pyrevit.loader.sessionmgr] Extension assembly created: pyApex
ERROR: [pyrevit.loader.basetypes.typemaker] Error creating python types for: <type_id '.pushbutton' name 'ColourCoding' @ 'C:\Users\rob.cross\AppData\Roaming\pyRevit\Extensions\pyL_R.extension\pyL_R.tab\Structural Utilities.panel\ColourCoding.pushbutton'> | Duplicate type name within an assembly.
ERROR: [pyrevit.loader.basetypes.typemaker] Error creating python types for: <type_id '.pushbutton' name 'PickStructural' @ 'C:\Users\rob.cross\AppData\Roaming\pyRevit\Extensions\pyL_R.extension\pyL_R.tab\Structural Utilities.panel\PickStructural.splitpushbutton\PickStructural.pushbutton'> | Duplicate type name within an assembly.
INFO: [pyrevit.loader.sessionmgr] Extension assembly created: pyL_R
INFO: [pyrevit.loader.sessionmgr] UI created for extension: pyRevitCore
INFO: [pyrevit.loader.sessionmgr] UI created for extension: pyRevitTools
ERROR: [pyrevit.loader.uimaker] UI error: Can not create tab: Too many tabs have been created by the API. Instead, you may add your Ribbon Panels to the Add-Ins tab.
INFO: [pyrevit.loader.sessionmgr] UI created for extension: pyApex
INFO: [pyrevit.loader.sessionmgr] UI created for extension: pyL_R
INFO: [pyrevit.loader.sessionmgr] Load time: 4.81999206543 seconds :thumbs_up:

**Comment by melnikovalex** [comment]
> Ehsan, Can Copy VG filters be added to PyRevit?

@Robbo1234 @eirannejad now each of extension is being developed a certain developer or a company, am I right? I think this division makes easier addressing of questions and providing this support, update the tools.

The only reason I can see is that CopyVGfilters the most popular button on pyApex panel. If the idea is to give access to this tool to more people, I do not mind moving it.

If we do that then I have a question to Ehsan. Are there any plans to separate pyRevitTools extension from the main installer? and to distribute it as a separated extension but enabled by default?

I am asking because now, to fix some of pyApex tool I just have to commit changes, and all the users can receive them with Update button or with auto update. 

At the moment, in case if this script located in pyRevitTools, users have to wait for admins to install a new version of pyRevit, aren't they?

**Comment by eirannejad** [comment]
@melnikovalex @Robbo1234
Honestly for me it's better to keep the tools where they are. I have really tried to the make getting the extensions as easy as possible for everyone. The last challenge is that maybe not everyone wants all the tools in an extension. I'm working on a tool that will let you pick and choose and customize the pyRevit deployment. This feature will be shipped with 4.7

So in the meantime let's not make any changes. My $0.02

**Comment by eirannejad** [comment]
@melnikovalex Would you mind taking care or @Robbo1234 issue report?

**Comment by Robbo1234** [comment]
Thanks
