### ISSUE TITLE
Clean up Empty Tags

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#533]
**Is your feature request related to a problem? Please describe.**
This tool will find empty tags''?' in your Revit model for you the delete or fix.

**Describe the solution you'd like**
Click PyRevit Empty Tag which will open up an PyRevit dialog box giving you a option to find Empty Tags in the Current View or Model.

**Describe alternatives you've considered**
Ref: http://dp-stuff.org/downloads/find-and-delete-empty-tags-revit-python-script/

**Additional context**
![image](https://user-images.githubusercontent.com/8776947/53510942-0d6a3080-3ab7-11e9-93cc-ff5732943162.png)

**Comment by eirannejad** [comment]
Added and will be pushed with 4.6.18

**Comment by Robbo1234** [comment]
Thanks

**Comment by Robbo1234** [comment]
Is there a way to find instead of wipe Empty Revit Tags i.e.  '?'

Thanks
