### ISSUE TITLE
Add open folder to PyRevit Get Central Path

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#534]
**Is your feature request related to a problem? Please describe.**
Not really a problem but more of a time saving feature.

**Describe the solution you'd like**
Click on PyRevit Get Central and it opens the folder that contains the Revit Central model.

**Additional context**
![image](https://user-images.githubusercontent.com/8776947/53560453-4997a280-3b44-11e9-9d75-ba2aaf11be99.png)

Thanks

Rob

**Comment by eirannejad** [comment]
Implemented and will be published with 4.6.17
Shift-clicking the button opens the folder now.

**Comment by Robbo1234** [comment]
Thanks Ehsan
