### ISSUE TITLE
Startup.py Library Access

### ISSUE THREAD

**Issue by martinservold** [eirannejad/pyRevit#535]
I could not get my startup.py scripts to access imported libraries. Not sure if it's a sequencing thing, or some other problem. I've tried both the 'lib' folder in the extension folder and making a seperate iron python library extension with no luck at actually accessing them. This happens both inside and outside of an event handler. I'm still running v4.5 at the moment so apologies if this has already been solved.

**Comment by eirannejad** [comment]
No. Great catch. Will fix soon.

**Comment by eirannejad** [comment]
Meanwhile you can add the library paths manually to you `sys.path` so the imports would work.

**Comment by martinservold** [comment]
Wouldn't I have to edit the sys.path of all users that are going to use this startup script? If so that doesn't seem like much of a solution as I have 100+ users across 4 offices.

As a side note to the issue,
I found a way to do it without external packages by editing your pyrevit.forms code. The issues was to auto-close/timeout a dialog after x seconds, if you'd wish to incorporate this into your official code i can send over my edits.

**Comment by eirannejad** [comment]
No. Edit the sys path in startup script
```python
import sys
sys.path.append(r'path/to/your/module/folder')

import your_module
```

**Comment by martinservold** [comment]
Didn't know you could do that. Kudos

**Comment by eirannejad** [comment]
I’d love to get your edits as well. Thanks a lot

**Comment by martinservold** [comment]
### Annotated changes:
![image](https://user-images.githubusercontent.com/44454303/53610935-111ab780-3b8a-11e9-83ac-3aba0cd02ea0.png)

### Full code
`
class TemplateUserInputWindow(WPFWindow):
    """Base class for pyRevit user input standard forms.

    Args:
        context (any): window context element(s)
        title (str): window title
        width (int): window width
        height (int): window height
        autoclose (int): close window after x seconds
        **kwargs: other arguments to be passed to :func:`_setup`
    """

    xaml_source = 'BaseWindow.xaml'

    def __init__(self, context, title, width, height, autoclose, **kwargs):
        """Initialize user input window."""
        WPFWindow.__init__(self,
                           op.join(op.dirname(__file__), self.xaml_source))
        self.Title = title
        self.Width = width
        self.Height = height

        self._context = context
        self.response = None
        self.PreviewKeyDown += self.handle_input_key
        if autoclose > 0:
            self.timerLimit = autoclose
            self.timer = 0
            from System.Windows.Forms import Timer
            timerFunc = Timer()
            timerFunc.Interval = 1000
            timerFunc.Tick += self.auto_close
            timerFunc.Start()

        self._setup(**kwargs)

    def auto_close(self, sender, args):
        """Handle keyboard input."""
        self.timer += 1
        if self.timer >= self.timerLimit:
            try:
                self.Close()
                sender.Stop()
            except:
                pass

    def _setup(self, **kwargs):
        """Private method to be overriden by subclasses for window setup."""
        pass

    def handle_input_key(self, sender, args):
        """Handle keyboard input."""
        if args.Key == framework.Windows.Input.Key.Escape:
            self.Close()

    @classmethod
    def show(cls, context,
             title='MEGA Tools',
             width=DEFAULT_INPUTWINDOW_WIDTH,
             height=DEFAULT_INPUTWINDOW_HEIGHT,
             autoclose=0,
             **kwargs):
        """Show user input window.

        Args:
            context (any): window context element(s)
            title (type): window title
            width (type): window width
            height (type): window height
            autoclose (int): close window after x seconds
            **kwargs (type): other arguments to be passed to window
        """
        dlg = cls(context, title, width, height, autoclose, **kwargs)
        dlg.ShowDialog()
        return dlg.response
`

**Comment by eirannejad** [comment]
Thanks a lot

**Comment by eirannejad** [comment]
Added extension `lib` and main paths to the sys path for the `startup.py` inside the extension.

Will be pushed with 4.6.18
