### ISSUE TITLE
Installation Issues with 4.6.11 and onward

### ISSUE THREAD

**Issue by DTatRamsa** [eirannejad/pyRevit#536]
Hi Ehsan, we have users who are installing the latest version of the pyrevit software who are encountering some issues. We have profiles for our IT team members who are authorized to install software and regular members - with previous installers, there weren't any issues with having pyrevit run from the appdata / roaming folder location and have pyrevit load in, but with the latest releases the (4.6.11 and onward) 1) pyrevit does not load with startup, and 2) is not populated as an addin by revit. We've been able to get around the issue by directing the installer to deploy to the user's appdata location while under the IT team's windows login and copying the pyrevit.addin to the user's revit/addins location, but is there a way to fix this behavior / can we adjust the installer to deploy correctly moving forward? This is the solution we've been able to push through so far. 

I can send the documentation of the via private email if what I explained above doesn't make sense - let me know at t.yang@ramsa.com please!

**Comment by eirannejad** [comment]
Hey @DTatRamsa . Take a look at this page please. https://eirannejad.github.io/pyRevit/deploy/

pyRevit has a powerful cli tool that is desinged to manage and customize pyRevit distribution in teams.

Let me know if this helps.

**Comment by eirannejad** [comment]
Has this been resolved?

**Comment by eirannejad** [comment]
No updates received. Closing for now.

**Comment by DTatRamsa** [comment]
Sorry for the lack of updates, been having a terribly busy week – I’ll be back in touch with you when I have any updates!


Timothy Yang
Design Technology Support Specialist
Robert A.M. Stern Architects, LLP
One Park Avenue, New York, New York 10016
Phone: 212 967 5100
t.yang@ramsa.com
www.ramsa.com<http://www.ramsa.com/>



The information contained in this communication and any enclosures or attachments may be confidential and/or proprietary. It is intended only for the recipient or recipients named above. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication or its contents or attachments is strictly prohibited. If you have received this communication in error, please immediately advise the sender and delete the original and any copies from your computer system.
