### ISSUE TITLE
Add support for user groups

### ISSUE THREAD

**Issue by martinservold** [eirannejad/pyRevit#537]
Similar setup to beta/non-beta where only certain tools load but have the ability to define multiple groups in one spot and have a variable __usergroups__ = 'All' by default it would be 'All'.
In my current setup I would set up 'All', 'Bim', 'Dev', 'Base', and 'Adv'.
It would be nice if the groups could be set up hierarchical so that I could specify 'Base' and it would also load for 'Adv'. So a user would belong to only one group.

**Comment by eirannejad** [comment]
pyRevit already includes `authgroups` option in `extension.json` definition. Sorry for the lack of documentation on this but the docs are getting better slowly.

`authgroups` is a list of Windows security group Ids (SSID). In active directory environments, user access to various resources is controlled using SSIDs. You can use the same mechanism to control access to various pyRevit extensions.

Add a line similar to this to your `extension.json` definition.

``` json
{
    "authgroups": ["S-1-5-32-559", "S-1-5-21-3106616158-3581391655-863375417-15708"]
}
```
