### ISSUE TITLE
pyRevit blocking Autodesk Point Layout installation

### ISSUE THREAD

**Issue by TGDan** [eirannejad/pyRevit#538]
I was recently trying to install Autodesk points layout in Revit 2018.3 (18.3.2.7
20181011_1500(x64) 2018.3.2).  For some reason, it would not install. APL would run on ACAD and Navisworks. I contacted Autodesk and a tech helped go through the logs and could not find an issue. It was suggested to remove pyRevit. 
Once I removed pyRevit I could complete the install and run APL on Revit. It looks like there is something in py Revit preventing some plugins from installing. I have experienced the same behavior in Navisworks with different plugins before but this is new to Revit.

"ErrorError (must be addressed in order to continue)
      The type initializer for '<module>' threw an exception
          Error1"

Windows 10 Enterprise V 1709 OS build 16299.967
Thanks,
Dan

**Comment by eirannejad** [comment]
Sorry I think I forgot to push that change to this release. Will double check and make sure it's included in 4.6.18

**Comment by eirannejad** [comment]
@TGDan You did not follow the instructions on the issue template and this makes my work harder.

pyRevit __does not__ intentionally prevent any other add-ins from loading. There are differences between the libraries used by pyRevit and other add-ins that is the root cause most of the time.

I apologize for the inconvenience but I need more information on the error so I can dig deeper.

**Comment by Shayneham** [comment]
@eirannejad Just took a look from the Point Layout side, it seems to be an issue with the following function  pyRevitLabs.TargetApps.Revit.PyRevitBindings.CurrentDomain_AssemblyResolve.  Ill PM you a stacktrace.

**Comment by eirannejad** [comment]
Confirmed the issue and the fact that is caused by the assembly resolver in pyRevit. It only happens in Revit 2018 and below. Revit 2019 somehow has a better assembly resolution I guess.

**Comment by eirannejad** [comment]
@Shayneham Thanks a lot! This is bug help. I'll look into it.

**Comment by eirannejad** [comment]
Confirmed the pyRevit internal binding resolver was the root cause. Making it only respond to requests coming from pyRevit assemblies resolved both #525 and issues listed on this thread.

The commit about is for 4.7 on develop branch. I'll back port this change to 4.6 and will publish with 4.6.18

**Comment by eirannejad** [comment]
@Shayneham Thanks a lot for support on this and help in finding the root cause.
