### ISSUE TITLE
Update, Extensions and Settings buttons not appearing

### ISSUE THREAD

**Issue by alfonsomonedero** [eirannejad/pyRevit#541]
**Describe the bug**
I am installing Pyrevit for all Revit users in my office and in some of them I see all buttons and in others Update, Extensions and Settings buttons are missing, among others. 

I have installed the latest version 4.6.18 from https://eirannejad.github.io/pyRevit/pyrevit/updates/2019/03/09/4618.html

**Expected behavior**
I expect to see Update, Extensions and Settings buttons to modify and add custom tabs

![Capture](https://user-images.githubusercontent.com/43339587/54222459-61c8d380-44ed-11e9-8dbe-14fb0dda7f62.JPG)

**Screenshots**

![L_2D7B tmp](https://user-images.githubusercontent.com/43339587/54222520-7c9b4800-44ed-11e9-9705-e7cfc6d45273.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - pyRevit 4.6.18

**Additional context**
Are there different set ups for PyRevit where one has full capability and others are capped?
I just update to latest version and still the same

**Comment by eirannejad** [comment]
Check the configurations on user machines. These options should be disabled:
```ini
[core]
usercanupdate = false
usercanextend = false
usercanconfig = false
```

**Comment by muhsenbd** [comment]
C6cgcgczs3
