### ISSUE TITLE
PyRevit Conflict with Dynamo Custom Node e.g. Clockwork

### ISSUE THREAD

**Issue by zachitect** [eirannejad/pyRevit#542]
Hi PyRevit Team,

Just found a conflict with Dynamo custom node.
I've been using Clockwork ver. 2.1.2 for Dynamo 2.0.2, in particular a node called Element.Cut.Geometry.

After installing PyRevit, I found that the Python component inside that custom node (editing mode with yellow BG) is missing. And it came back after uninstalling PyRevit.

I suspect there might be something wrong with IronPython? Conflicting?

Hope that helps.

Cheers,

Zach

**Comment by eirannejad** [comment]
Have you tried changing the pyRevit engine (in settings) to 2.7.3 to match Dynamo?

**Comment by eirannejad** [comment]
@zachitect Did this get resolved with switching the engine?

**Comment by zachitect** [comment]
Oh hi, thanks for your quick response.

I was trying to replicate the issue, and somehow couldn't. It is working well with dynamo even if I switch the engine to the latest (supposedly not supporting dynamo?)
So it looks like I'm not able to isolate the cause of it.

I'll definitely report back if similar issue ever reoccurs again. Thanks!

**Comment by eirannejad** [comment]
Awesome. Closing this for now. Feel free to open again when you have more info on the error.
