### ISSUE TITLE
List and Select Empty Tags for Review

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#544]
To assist with reviewing a model/s, would it be possible to Select the models Empty Tags plus also list the Empty Tags in the Empty Tags Select Views dialog similar to the way PyRevit Manage Keynotes dialog counts used keynotes. Refer to screen shot below:

![image](https://user-images.githubusercontent.com/8776947/54441810-68e22280-4735-11e9-9927-481f0a3c04b3.png)

Thanking you in advance

Rob

**Comment by eirannejad** [comment]
Collecting empty tags from each view is an intensive process since many of these views are not loaded in memory and need to be rendered. There are easier ways but I don't think this specific use case justified customization.

**Comment by Robbo1234** [comment]
That's fine butit would be great to be able to selects all the empty "?" tags in the current view, so one can actually see what tags that are going to be removed or fixed, similar to PyRevit Find and Select Entities Without Tags. Refer to screen shot below:

![image](https://user-images.githubusercontent.com/8776947/55178989-71e3e280-517e-11e9-98d6-88f1bd13b8e2.png)

**Comment by eirannejad** [comment]
Okay makes sense.

**Comment by eirannejad** [comment]
- [ ] Improve output window to allow asking user a confirmation question before proceeding.

**Comment by Robbo1234** [comment]
Just noticed that PyRevit Find and Select Entities Without Tags doesn't pick up Revit Elements which are contained within Revit Groups.

Can this be fixed?

Rob

**Comment by jmcouffin** [comment]
**Closing**
Issue older than a year. 
Thanks for pointing it out. 
If you feel it is still relevant, feel free to reopen the issue
