### ISSUE TITLE
Keynote types switched

### ISSUE THREAD

**Issue by need4mospd** [eirannejad/pyRevit#545]
With the Element Keynote button checked, it places a Material keynote and vice-versa.

![KeynoteBug](https://user-images.githubusercontent.com/46454815/54442907-84393780-470d-11e9-921d-83e3e60e1a29.png)

Revit 2019.2

**Comment by eirannejad** [comment]
Woops!

**Comment by eirannejad** [comment]
Fixed and will be issued with 4.6.19 this weekend
