### ISSUE TITLE
Modify Sheet Reorder Tool to include more digits

### ISSUE THREAD

**Issue by cpercer** [eirannejad/pyRevit#546]
**Is your feature request related to a problem? Please describe.**
When using the sheet reorder tool I am limited to a single digit for values 1-9, two digits for values 10-99, three digits for values 100-999, etc.

**Describe the solution you'd like**
I use the shared parameter to append my sheet naming when printing.  I would like to be able to have extra digits, e.g. 001, 002, etc.  The number of extra digits would be user specifiable.

**Describe alternatives you've considered**
The only alternative is to manually rename the files after printing

**Additional context**
None

**Comment by eirannejad** [comment]
I'm not fully understanding the problem. The sheet reorder tool uses 4 digits always.

![2019-03-22 08_12_30-Window](https://user-images.githubusercontent.com/8197916/54832877-46db2980-4c7a-11e9-942f-bb01ef7b9c2d.png)

And why renaming files? Seems like you are talking about the the **Print Sheets in Order** tool

**Comment by cpercer** [comment]
Thanks for responding Eshan.

My Reorder sheets tool seems to operate differently.
![Sheet Reorder Tool](https://user-images.githubusercontent.com/44647473/54839855-bd3b5400-4c99-11e9-903c-90a1b09975e6.JPG)


I set up my parameter according to the instructions provided by this video:  https://www.youtube.com/watch?v=WlRmNdVRZiI

![Sheet Order Parameter](https://user-images.githubusercontent.com/44647473/54839938-df34d680-4c99-11e9-86e3-7bd062e90469.JPG)

Also, in the video, the tool seems to display the same behavior as I describe.

I use RTV tools to plot/export sheets which allows me to append my sheet names with the Sheet Index Order parameter.

![RTV Tools](https://user-images.githubusercontent.com/44647473/54840087-27ec8f80-4c9a-11e9-9d20-9f4cc01147dc.JPG)

Since our file hosting service uses 3 digits to organize files, I want to be able to use the Sheet Index Order parameter to append the plot/export name, e.g. 006 04- A-110 SITE PLAN.pdf

**Comment by eirannejad** [comment]
Okay this needs a revision to the tool to allow user to customize index ranges

**Comment by jmcouffin** [comment]
**Closing**
Issue older than a year. 
Thanks for pointing it out. 
If you feel it is still relevant, feel free to reopen the issue
