### ISSUE TITLE
Create specific workset for imported model

### ISSUE THREAD

**Issue by CHBIV007** [eirannejad/pyRevit#55]
got a requests:

- After you link a file in Revit, then select it, I want to create a workset that matches the name, then assign that link to the newly created workset

**Comment by eirannejad** [comment]
Sure. I'll add this soon

**Comment by CHBIV007** [comment]
Awesome! keep up the good work! YOU ROCK!!

**Comment by eirannejad** [comment]
added: Links_createWorksetForLinkedElement.py
