### ISSUE TITLE
Installation 4.6.8

### ISSUE THREAD

**Issue by cbradt27** [eirannejad/pyRevit#550]
Good day!  I am relatively new to your program and have watched the tutorials several times.  I still cannot seem to install an older version of the software.  I have tried cloning and downloading (zip) the files, but I don't see the *.BAT files associated to apply the add-in.  Looking for any assistance you can provide.  Thank you in advance.
![PyRevit](https://user-images.githubusercontent.com/48923935/54999103-eadc1200-4fa5-11e9-965c-66be84a1a8b1.PNG)

**Comment by eirannejad** [comment]
@cbradt27 Some of the views are pretty old at this point. Take a look at the deployment guide and let me know if this helps
https://eirannejad.github.io/pyRevit/deploy/

**Comment by cbradt27** [comment]
Thank you.  I looked at this guide and it does not help me in understanding what is needed to install the 4.6.8 program properly.

I am not familiar enough and am told that the project team needs to use version 4.6.8 or else it doesn’t work properly with their current set of scripts.  Maybe this is incorrect information at this point, but I am uncertain and see no documentation stating clearly otherwise.

Any other information would be great.

Regards,

Christopher Bradt
AEC Solution Specialist

[cid:image003.png@01CCECC2.0ED21000]
STV Incorporated
205 West Welsh Drive
Douglassville, PA  19518
W:     610.385.8393
M:     610.858.1235
christopher.bradt@stvinc.com<mailto:christopher.bradt@stvinc.com>

**Comment by eirannejad** [comment]
Okay sounds fair. Gimme me a little time and I'll test that version and will write a few instructions here for you.

**Comment by cbradt27** [comment]
Thank you so much for taking the time!

**Comment by eirannejad** [comment]
@cbradt27 
- [ ] Download the [4.6.8 zip archive](https://github.com/eirannejad/pyRevit/releases/tag/v4.6.8) and extract to desired location (`$installpath` herein)
- [ ] Download and install the [pyRevit cli utility](https://github.com/eirannejad/pyRevit/releases/tag/cli-v0.9.7.0)
- [ ] Open a command prompt and run commands below ony by one (# lines are comments)
```shell
# confirm cli version
pyrevit --version
# should print v0.9.7

# add the downloaded clone to list of clones
pyrevit clones add master468 $installpath

# attach the pyrevit clone to installed revits
pyrevit attach master468 277 --installed
```

Open any installed Revit now and pyRevit v4.6.8 should load

**Comment by cbradt27** [comment]
Thank you for the instruction.  Seemed to work until I launched Revit.

[cid:image001.png@01D4E3F4.509CB680]

Regards,

Christopher Bradt
AEC Solution Specialist

[cid:image003.png@01CCECC2.0ED21000]
STV Incorporated
205 West Welsh Drive
Douglassville, PA  19518
W:     610.385.8393
M:     610.858.1235
christopher.bradt@stvinc.com<mailto:christopher.bradt@stvinc.com>

**Comment by eirannejad** [comment]
@cbradt27 I'd really appreciat if you can reply in the github issue tracker and not thru email. Emails leave a lot of extrac content on the conversation and attachments don't carry over propertly.

**Comment by cbradt27** [comment]
My apologies.  Thank you again for taking the time and the instruction.  These were my results.

![PYREVIT error](https://user-images.githubusercontent.com/48923935/55079548-c5690a00-5072-11e9-8961-412f5d16dd45.PNG)

**Comment by eirannejad** [comment]
Please open a command prompt and run `pyrevit env` and paste the results here.

**Comment by cbradt27** [comment]
![PYREVIT error1](https://user-images.githubusercontent.com/48923935/55179762-8912d800-515e-11e9-8a3f-2d891d1015fd.PNG)

**Comment by eirannejad** [comment]
[Args Files.zip](https://github.com/eirannejad/pyRevit/files/3019552/Args.Files.zip)

Extract and throw this into the clone directory and rerun the `pyrevit env` command please.

**Comment by cbradt27** [comment]
ugh...sorry, but still no go.
![PYREVIT error3](https://user-images.githubusercontent.com/48923935/55182023-456e9d00-5163-11e9-935a-631de1f3409e.PNG)
![PYREVIT error2](https://user-images.githubusercontent.com/48923935/55182034-499aba80-5163-11e9-82c0-565913a1a3f4.PNG)

**Comment by cbradt27** [comment]
I will try a complete reinstall and let you know the outcome.  Also can you provide me the instructions to install for All users and not in the specific user profile?  

I will follow these steps:

- Download the 4.6.8 zip archive and extract to desired location, C:\PyRevit-Master 
- Download and install the pyRevit cli utility
- Open a command prompt and run commands below one by one (# lines are comments)

# confirm cli version
pyrevit --version
# should print v0.9.7

# add the downloaded clone to list of clones
pyrevit clones add master468 C:\PyRevit-Master

# attach the pyrevit clone to installed revits
pyrevit attach master468 277 --installed

I will verify the arg file is present and then run the "pyrevit env"

So how is this supposed to work when I do update PyRevit?  Is this a complete reinstall or does your new executable take care of all that?

Thanks again, Happy Friday!

**Comment by cbradt27** [comment]
I am able to get it working!  Thank you for all your time, I know you a busy man!

With much appreciation!

Chris

**Comment by eirannejad** [comment]
The installer takes care of all these steps. The challenge is that you want an older version which is not supported anymore (because it's just me for now and is hard to maintain many versions even for larger teams)

**Comment by cbradt27** [comment]
Totally understand.  Thank you again for your responses and patience.  Good luck!
