### ISSUE TITLE
Convert Line Style tool crashes Revit

### ISSUE THREAD

**Issue by lank2027** [eirannejad/pyRevit#551]
Hi Ehsan,

Ran into a bug when trying to use the Convert Line Style tool. Let me know if you would like me to provide any other information.

Cheers,
David

**Describe the bug**
When selecting the Convert Line Styles tool Revit generates an unrecoverable error and crashes. See screen shot below.

**To Reproduce**
1. Go to 'PyRevit Edit'
2. Click on 'Convert Line Styles'
3.  Revit Unrecoverable error

**Screenshots**
![image](https://user-images.githubusercontent.com/47336341/55017444-f9c6c280-4fad-11e9-9563-3117bbcdf872.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - pyRevit Version [4.6.19]

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.6.19" | Path: "C:\Users\DCurran\AppData\Roaming\pyRevit-Master"
==> Attachments
Autodesk Revit 2016 Update 8 for R2 (2016.1.8) | Clone: "master" | Engine: "279"
Autodesk Revit 2019.2.1 | Clone: "master" | Engine: "279"
==> Installed UI Extensions
==> Installed Library Extensions
==> Default Extension Search Path
C:\Users\DCurran\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2014 Update Release 3 | Version: 13.11.4 | Build: 20140709_2115(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2014"
Autodesk Revit 2016 Update 8 for R2 (2016.1.8) | Version: 16.0.1205.0 | Build: 20170117_1200(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016"
Autodesk Revit 2019.2.1 | Version: 19.2.10.7 | Build: 20190225_1515(x64) | Language: 1033 | Path: "C:\Program Files\AutodeskRevit 2019"
==> Running Revit Instances
PID: 8584 | Autodesk Revit 2019.2.1 | Version: 19.2.10.7 | Build: 20190225_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> User Environment
Microsoft Windows 10 [Version 10.0.17763]
Executing User: *\dcurran
Active User: *\dcurran
Adming Access: No
%APPDATA%: "C:\Users\DCurran\AppData\Roaming"
Latest Installed .Net Framework: "4.7.2"
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.X
pyRevit CLI 0.9.7.0
```

**Comment by eirannejad** [comment]
@lank2027 I'll run more tests. Is there a way you can share the model that has the error? Does it happen on any model? You can send a link to my email.

**Comment by lank2027** [comment]
It occurs on every model I have opened including when I create a new project using the Revit default template file. I have sent a link to your email allowing you to download one of our models for your review. 

I have not tried it on another machine in the office but will do so. 

I have numerous addins installed as you can see in the screen shot in my original post. Do you think there might be a conflict one of them? If so I can start uninstalling them one by one to identify which one is causing the issue.

Thx.

**Comment by eirannejad** [comment]
Okay. I might have messed up something in there. Will run some tests.

**Comment by eirannejad** [comment]
@lank2027 This doesn't crash on my machine. Would you be able to help me investigate this? Do you/can you have Visual Studio installed on your machine that has this error?

**Comment by lank2027** [comment]
Yes, I am able to help out and have VS installed on my machine.

**Comment by eirannejad** [comment]
Okay run Visual Studio and Revit. Then in VS, got to `Debug > Attach to Process` and attach to `Revit.exe`. Click on the tool and VS should give you information about where the crash occurs and descriptions. I'd like to kow the description and a screenshot of the **Call Stack** panel.

**Comment by lank2027** [comment]
Here is a screen shot of VS.
![image](https://user-images.githubusercontent.com/47336341/55183258-a9399b80-514c-11e9-931e-a369b378138d.png)

**Comment by eirannejad** [comment]
Okay. Alt click on the button and replace the `script.py` with the one inside this zip file and see if that fixes the issue.

[script.zip](https://github.com/eirannejad/pyRevit/files/3019772/script.zip)

**Comment by lank2027** [comment]
That did it!

What was the issue?

**Comment by eirannejad** [comment]
Me sucking at testing in general hahahahaha. I had a mistyped property name in there.

This is the issue https://github.com/eirannejad/pyRevit/commit/fdd21b69e958ad96f3fd02c00140651227aeb493

**Comment by GastonBC** [comment]
I'm having the same problem but it only happens when I select an item from the left list and then close the window. I can make a new issue if needed.
I just updated pyRevit to the latest version by the way
