### ISSUE TITLE
ReValue "*" wildcard instead of "{name}"

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#554]
**Is your feature request related to a problem? Please describe.**
Some users can find it like writing code when having to type {name} .

**Describe the solution you'd like**
Instead of having to type "{name}" wildcard one could simply type "*" instead plus maybe one could consider incorporating an familiar Microsoft Word "Find and Replace" functionality.

![image](https://user-images.githubusercontent.com/8776947/55064643-407df080-5072-11e9-94c8-feb8c1a74a92.png)

**Comment by eirannejad** [comment]
What if there are multiple values in a name?
`A300 - FLOOR PLAN LEVEL 01`
`{s} - {n} 0{l}`

**Comment by Robbo1234** [comment]
The same way one uses "Find and Replace" functionality in Microsoft Excel to modify data.
i.e. Match Case, Match entire cell contents.

**Comment by eirannejad** [comment]
This tool is more advanced than a simple Find/Replace and uses regular expressions. Making changes with a Find/Replace tool usually takes many steps to get all the parts right. You also can't re-arrange the naming components.

See this example. Multiple Find/Replace steps are required to rename these components whereas the tool can make the change in one step.

![2019-03-28 09_37_11-ReValue](https://user-images.githubusercontent.com/8197916/55175761-29f09b80-513d-11e9-8df2-44ee19874a25.png)

If you have a specific use case that would be better resolved with a Find/Replace method, I would love to hear about it. I understand the suggestion that you are providing, but unless there is a use case that this tool is failing on or a naming pattern that it can not reformat, there is no reason to add a different renaming method.

**Comment by Robbo1234** [comment]
That's fine Ehsan, your tool is excellent, just that I'm use to using MS
Excel for renaming Revit families/types and then pumping that data back
into Revit.

Replacing {name} with {*} is a good a improvement plus is {level} bringing
in the actual Revit level parameter in your screen shot?
Being able to combine multiple parameter data in the New Format would be a
great feature.

**Comment by eirannejad** [comment]
`{level}` is a field that is grabbing the `1` from `Drafting 1` and `2` from `Drafting 2`. "Original Format" field describes the existing format of the names and creates `{x}` parameters to be used in renaming. You can call `{level}` anything else and it works the same.

**Comment by Robbo1234** [comment]
FYI:
DiRoot tutorial on their free Revit plugin called FamilyReviser:
https://www.youtube.com/watch?v=GUPDvWgyxZ0&t=8
![image](https://user-images.githubusercontent.com/8776947/55238257-f476ab80-522b-11e9-8def-c55d3c1819d7.png)

**Comment by Robbo1234** [comment]
Can PyRevit ReValue rename new Revit Lines Styles?

Can't seem to select all the new Lines Styles using PyRevit Select Element Type and when I manually select them, it just states Detail Lines. (refer to screenshot)

![image](https://user-images.githubusercontent.com/8776947/56978203-e7bcde80-6b6e-11e9-89e9-4436b0617991.png)
