### ISSUE TITLE
script.get_logger() from fileConfig like the python's logging lib does

### ISSUE THREAD

**Issue by amastrobera** [eirannejad/pyRevit#555]
Dear Ehsan, 

I would like to share a logging config among plugins. I want to write my `logging.conf` file somewhere and make all modules/buttons use that when I load it with `script.get_logger()`. Is there a way to do something like that ? 

If not, I suggest this development inside your `coreutils.logger` wrapper of the python logger -> `logging.config.fileConfig("file path")`: [like this](https://docs.python.org/2/howto/logging.html).

**Comment by eirannejad** [comment]
For any advanced and customized logging mechanism, I'd suggest developing your own logging module and logger. You can use `coreutils.appdata` to get a temporary files for logging and storage purposes. See [Using Temporary Files](https://pyrevit.readthedocs.io/en/latest/articles/scriptanatomy.html#using-temporary-files) on documentation
