### ISSUE TITLE
PyRevit Select Element Types doesn't select Revit Fill Patterns or Revit Materials

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#557]
**Describe the bug**
Hi Ehsan

I was testing PyRevit v4.6.19 Select Element Types and  ReValue in Revit 2016 and I noticed that it doesn't select Revit Fill Patterns for some for reason, as per your How to pyRevit: Taming Parameter Values tutorial:

https://youtu.be/-JDgiP3gK9Y

btw, can Pyrevit v4.6.19 Select Element Types select Revit Materials to enable me to use ReValue 

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

**To Reproduce**
1. Go to PyRevit Select Element Type
2. Click on Fill Patterns
3.  PyRevit ReValue is  grayed out  

**Expected behavior**
PyRevit ReValue shouldn't be grayed out after using PyRevit Select Element Type

**Screenshots**
I've emailed to the workflow video.

![image](https://user-images.githubusercontent.com/8776947/55154928-ee120200-514d-11e9-9b3e-24590530f9df.png)

**Comment by Robbo1234** [comment]
Ehsan,

I also notice that PyRevit Select Element Types doesn't select Revit Linestyles.

**Comment by eirannejad** [comment]
Fixed and implemented. Thanks for catching this.
