### ISSUE TITLE
PyRevit find Referencing Sheets - Click on listed Sheets i.d results to open Revit Sheet

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#558]
**Is your feature request related to a problem? Please describe.**
Time saving navigation improvement.

**Describe the solution you'd like**
I would like if PyRevit Find Referencing Sheets could output the Revit Sheet I.D. similar to PyRevit Find Range of Slopes and then to be able to click on the Sheet I.D. to open that Revit Sheet view, instead of having to go and navigate the Revit Project Browser.

Refer to screen shot:
![image](https://user-images.githubusercontent.com/8776947/55159213-739aaf80-5158-11e9-9c3d-3656d2ef3f36.png)

**Comment by eirannejad** [comment]
Implemeted and will be pushed with 4.6.20

**Comment by Robbo1234** [comment]
Thanks
