### ISSUE TITLE
unittest module inside a pyRevit button

### ISSUE THREAD

**Issue by amastrobera** [eirannejad/pyRevit#559]
Dear Ehsan,

I tried to create a set of unit tests and put them into a `UnitTest.pushbutton` in pyRevit/extensions. My code is simple but not all works. I struggle to make the revit window log the error to its console in case a test fails. Can you tell me how you would do it ? 

```
import unittest 

class TestClass(unittest.TestCase):
    def test_number_one(self):
        self.assertTrue(True, "alright") # msg correctly not printed, because test passes
        print("test 1 passed") # this (or a logger.info(...) will be written 
        self.assertTrue(False, "this is all wrong") # this msg is not written at error time
        print("test 2 failed") # this or a logger will also not be written

suite = unittest.TestLoader().loadTestsFromTestCase(TestClass)
unittest.TextTestRunner(verbosity=2).run(suite)

```

**Comment by eirannejad** [comment]
@amastrobera pyRevit output window is more complex than the normal standard streams. pyRevit has an internal unittesting system that is **under construction** but you can use it if you wish or look into the code on how it handles the output.

First of all each test needs to have its own test case function:
```python
class TestClass(unittest.TestCase):
    def test_number_one(self):
        self.assertTrue(True, "alright")

    def test_number_two(self):
        self.assertTrue(False, "this is all wrong")
```

You can temporarily use the `pyrevit.unittests` module as show in script below but be aware that for 4.7 version the implementation might change slightly.

Here is your updated script and output:

```python
import unittest
from pyrevit.unittests._testrunner import OutputWriter, PyRevitTestRunner, RESULT_TEST_SUITE_START

# do not change this
# create the test suite class and hand it to this function and it will run the tests
# and uses the html printer to nicely print the results
def run_suite_tests(test_suite):
    test_runner = PyRevitTestRunner()
    # run the test suite
    OutputWriter()\
        .write(RESULT_TEST_SUITE_START.format(suite=test_suite.__class__.__name__))
    return test_runner.run(test_suite)

class TestClass(unittest.TestCase):
    def test_number_one(self):
        self.assertTrue(True, "alright")

    def test_number_two(self):
        self.assertTrue(False, "this is all wrong")

suite = unittest.TestLoader().loadTestsFromTestCase(TestClass)
# unittest.TextTestRunner(verbosity=2).run(suite)
run_suite_tests(suite)
```

This is how the output window looks when tests are done.

![2019-03-28 10_43_02-Get Extension Hashes](https://user-images.githubusercontent.com/8197916/55180600-1e09d700-5147-11e9-84ab-8af6aa1fb928.png)

**Comment by amastrobera** [comment]
thanks a lot. I am now wondering how to print that msg "this is all wrong" from the `self.assertTrue` that fails. Do I have to create my own `PyRevitTestResult` class and override its `addError` function ?

**Comment by ollyhensby** [comment]
Just to add as I am also looking at unit testing within pyRevit. 

The imports from pyrevit are not from "_testrunner" any more but from "runner". So the updated imports look like this:

```python
import unittest
from pyrevit.unittests.runner import OutputWriter, PyRevitTestRunner, RESULT_TEST_SUITE_START
```

Cheers!
