### ISSUE TITLE
Copy Sheets to Open Documents to bypass duplicating groups and Families warnings

### ISSUE THREAD

**Issue by iavoo** [eirannejad/pyRevit#560]
Would like to request tool 'Copy Sheets to Open Documents' to have a check box to suppress all warnings revit pops notifying  something like `Type "Arrow Head-small" has been renamed to "Arrow Head-small 10" to avoid conflicts with the existing Element.`  - that I see tens of times for groups and families

**Comment by jmcouffin** [comment]
**Closing**
Issue older than a year. 
Thanks for pointing it out. 
If you feel it is still relevant, feel free to reopen the issue
