### ISSUE TITLE
opening and closing rvt files

### ISSUE THREAD

**Issue by amastrobera** [eirannejad/pyRevit#561]
Dear Ehsan, 

I managed to open files programmatically with a code of this type :

```
from Autodesk import Revit
from Autodesk.Revit import DB, UI

docptr = __revit__.OpenAndActivateDocument(rvt_file_path)

# do some operations with what is now the __revit__.ActiveUIDocument

docptr.Document.Close(False) # close without (with) saving does nothing
```

But I cannot close them. **Is there a way to close a tab / rvt file** ?

**Comment by eirannejad** [comment]
If you want to open a model for batch processing through the API, you need to open the model **headless** meaning there is no need to have a UIDocument (returned from `OpenAndActivateDocument`)

If you close a UIdocument through API, you will get a `The active document may not be closed from the API` exception

Use [OpenDocumentFile](https://www.apidocs.co/apps/revit/2019/5716f206-98ee-0490-4c6c-f0cdd6644190.htm) method instead

```python
doc = __revit__.Application.OpenDocumentFile(rvt_file_path)
doc.Close()
```
