### ISSUE TITLE
PyRevitTestResult to print error when test fails or gives error

### ISSUE THREAD

**Issue by amastrobera** [eirannejad/pyRevit#562]
Hello Ehsan, 

(as you probably already know) `PyRevitTestResult` is not printing the error msg when a test fails or has an error. 

```
self.assertTrue(False, "this will not be printed out, but it should")
```

1. My solution for you would be this 

*_testrunner.py*
```
RESULT_DIV_FAIL = '<div class="unittest unittestfail">' \
                  ':cross_mark: FAILED {test} - {des}' \
                  '</div>'

RESULT_DIV_ERROR = '<div class="unittest unittesterror">' \
                   ':heavy_large_circle: ERROR {test} - {des}' \
                   '</div>'
```

... followed by this code inside of `class PyRevitTestResult`
```
    def addError(self, test, err):
        super(AvpRevitTestResult, self).addError(test, err)
        mlogger.debug(DEBUG_FAIL_RESULT)
        self.writer.write(RESULT_DIV_ERROR
                          .format(test=self.getDescription(test), des=err[1]))

    def addFailure(self, test, err):
        super(AvpRevitTestResult, self).addFailure(test, err)
        mlogger.debug(DEBUG_FAIL_RESULT)
        self.writer.write(RESULT_DIV_FAIL
                          .format(test=self.getDescription(test), des=err[1]))
```
printing just err[1] is fine because `err = sys.exc_info()`, which handles its exceptions and always returns at least an empty tuple (None, None, None). 

2. It would also be nice to add the line number of the error.

**Comment by eirannejad** [comment]
Oh thanks. Ya the unittesting is still in its infancy, I'll get to work on it more and improve it for 4.7 final. Thanks a lot for sharing this. I'll revise the code.

**Comment by jmcouffin** [comment]
**Closing**
Issue older than a year. 
Thanks for pointing it out. 
If you feel it is still relevant, feel free to reopen the issue
