### ISSUE TITLE
tabular output for "List DWGs"

### ISSUE THREAD

**Issue by lionelcamara** [eirannejad/pyRevit#563]
**Describe the solution you'd like**
I'm not familiar with all of the capabilities of pyRevit, so not sure if a table display for output is readily available or not, but it would be nice if the output from "List DWGs" was given in table form. Right now, the "LINKED AND IMPORTED DWG FILES:" window displays a long bulleted list with lots of line spacing. It would be nice to see a more-compact schedule-like table.

Even with 12 DWGs, it's still useable as-is, of course, but a more compact display would make an awesome tool even "awesomer". :)

**Comment by RevitIRL** [comment]
and/or a *.csv export option (so it can be sorted, etc. in Excel)
