### ISSUE TITLE
Wipe tools for Unpurgable Dimensions

### ISSUE THREAD

**Issue by rwduffy** [eirannejad/pyRevit#565]
Similar to Wipe Unpurgable Viewport Types, can you add the following Wipe tools
* Wipe Unpurgable Dimension Types

**Comment by eirannejad** [comment]
Are there any? Would you mind sharing an example?

**Comment by rwduffy** [comment]
A dim style is used somewhere in the project.  I want to select the style and merge them with the correct one and be able to purge the old ones.  A dim style can be hidden to the naked eye when editing lets say a model in place element or even filled regions so trying to select all in the model will not find those.

**Comment by jmcouffin** [comment]
**Closing**
Issue older than a year. 
Thanks for pointing it out. 
If you feel it is still relevant, feel free to reopen the issue
