### ISSUE TITLE
pyRevit 4.6.19 Not Opening in Revit 2017.2

### ISSUE THREAD

**Issue by wqlevine** [eirannejad/pyRevit#566]
**Describe the bug**
pyRevit installed with no errors, but when opening in Revit 2017.2 it throws an IronPython Traceback error.

**To Reproduce**
1. 'Open Revit 2017.2'
4. See error (screenshot below)

**Expected behavior**
Revit 2017.2 to open with pyRevit toolbar enabled.

**Screenshots**
![pyRevit Error](https://user-images.githubusercontent.com/49001872/55409106-62261e80-552f-11e9-9123-6bfe4c325766.png)

```
 - OS: [Windows 10 Version 1803]
 - pyRevit Version 4.6.19
 - pyRevit Environment:
'C:\Users\jwilliams>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.6.19" | Path: "C:\Users\jwilliams\AppData\Roaming\pyRevit-Master"
==> Attachments
Autodesk Revit 2016 Update 7 for R2 | Clone: "master" | Engine: "277"
Autodesk Revit 2017.2 | Clone: "master" | Engine: "277"
Autodesk Revit 2019.1 | Clone: "master" | Engine: "277"
==> Installed UI Extensions
==> Installed Library Extensions
==> Default Extension Search Path
C:\Users\jwilliams\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2016 Update 7 for R2 | Version: 16.0.1185.0 | Build: 20161004_0715(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016"
Autodesk Revit 2017.2 | Version: 17.0.1117.0 | Build: 20170118_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
Autodesk Revit 2019.1 | Version: 19.1.0.112 | Build: 20180806_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.17134]
Executing User: BERGMEYER\jwilliams
Active User: BERGMEYER\jwilliams
Adming Access: No
%APPDATA%: "C:\Users\jwilliams\AppData\Roaming"
Latest Installed .Net Framework: "4.7.2"
No .Net Target Packs are installed.
pyRevit CLI 0.9.7.0`'
```

**Additional context**
Other machines on our network with the same OS and same versions of Revit seem to run this version fine, but don't have this issue.

**Comment by eirannejad** [comment]
Similar issues had been reported before and it was due to conflicts with other addons using the `Mahapps` module. What other third-party addons do you have installed?

**Comment by wqlevine** [comment]
We have Dynamo, Avail, KCL Tools, Enscape, CGS Tools, and BlueBeam. Screenshot attached.
![image](https://user-images.githubusercontent.com/49001872/55421578-85f55e80-5547-11e9-888f-77e94db5fc22.png)

**Comment by wqlevine** [comment]
I did a search using windows explorer on my C;/ Drive and found that an outdated version of Avail was causing compatibility issues. Updating Avail to the newest version solved the Traceback Error when trying t use pyRevit. Thanks @eirannejad for pinning this down to MahApps!

**Comment by eirannejad** [comment]
Thanks for looking into this. Glad it got resolved.
