### ISSUE TITLE
PyRevit Add Views to Sheets: Place Revit Schedule views

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#568]
**Is your feature request related to a problem? Please describe.**
To be able to place Revit Schedule Views onto Sheets.

**Describe the solution you'd like**
Have Revit Schedules appear in the PyRevit Add Views to Sheets>Select Views dialog box.

**Additional context**
![image](https://user-images.githubusercontent.com/8776947/55473580-f2836280-5606-11e9-92d5-070b349208fa.png)

**Comment by cphubb** [comment]
I can see schedules in the list of views to add to sheets and can select them. Schedules do not end up on sheets selected. V4.8.8
