### ISSUE TITLE
does not open pyRevit

### ISSUE THREAD

**Issue by Nastya1010** [eirannejad/pyRevit#572]
Hello! Help me please! I installed PyRevit, but it showed me an error. Here's a screenshot.
![Снимок](https://user-images.githubusercontent.com/48768461/55641970-3f6e6100-57e0-11e9-8c4c-f1c3d1684f85.JPG)

**Comment by eirannejad** [comment]
What's your pyRevit full install path?

**Comment by Nastya1010** [comment]
I can't find the installation path. I deleted all the files pyRevit. I downloaded again, but he writes that this program is already installed...I don't know what to do now.

**Comment by eirannejad** [comment]
Get pyRevit installed please and let me know if `pyrevit` command works in command prompt. I'll help figuring out the bug. Keep it installed until we resolve this issue.

**Comment by karpukhina** [comment]
hello! i have the same error((((( i don't know what to do

**Comment by eirannejad** [comment]
Seems like you both have unicode characters in your usernames. Would you mind opening a command prompt, run `pyrevit env` and share the results here?

**Comment by eirannejad** [comment]
@karpukhina @Nastya1010 Any updates?

**Comment by karpukhina** [comment]
![image](https://user-images.githubusercontent.com/49637139/57197979-2e974380-6f76-11e9-88e6-32eaeb2391d6.png)

![image](https://user-images.githubusercontent.com/49637139/57197981-3ce55f80-6f76-11e9-9b2c-48ad76a7afda.png)

nothing changes

**Comment by eirannejad** [comment]
No. Run `pyrevit env` in command prompt. It will give a report. Share that report here please.

**Comment by karpukhina** [comment]
oh, sorry)
![image](https://user-images.githubusercontent.com/49637139/57198014-bd0bc500-6f76-11e9-8032-ddd26292efd7.png)

**Comment by eirannejad** [comment]
Okay this seems to be an issue with the unicode characters in %appdata% path. Uninstall pyRevit and clean install again under a path that does not have your name in it e.g. `C:\pyRevit-Master`.

**Comment by karpukhina** [comment]
did not help, all the same

**Comment by eirannejad** [comment]
hmm. Okay let me look into this deeper. Thanks for the report

**Comment by karpukhina** [comment]
thank you

**Comment by eirannejad** [comment]
Resolved and will be pushed with 4.6.24

**Comment by iumepock** [comment]
Hey

I'm sorry if I broke any protocols posting here, but I thought that's about the same issue. I just installed pyRevit new release and got this error in Revit 2013:

![image](https://user-images.githubusercontent.com/51762855/60439996-3841ce00-9bea-11e9-854b-980ef2990ef2.png)

![image](https://user-images.githubusercontent.com/51762855/60440007-3d9f1880-9bea-11e9-8fe0-038b4f5398df.png)
