### ISSUE TITLE
"pyRevitLoader.dll" does not exist - can't load, uninstall or repair

### ISSUE THREAD

**Issue by MatthewJohnsonVMDO** [eirannejad/pyRevit#573]
**Describe the bug**
I've tried to install PyRevit 4.6.18 on several computers in my office.  For some it works perfectly, others complete the installer OK but then get the error "Failed to initialize the add-in "PyRevitLoader" because the assembly C:\Users\username\AppData...\pyRevitLoader.dll" does not exist."  When I try to uninstall pyRevit (to reinstall, try 4.6.19, or whatever), the uninstaller crashes.  None of the PyRevit commands are recognized by Command Prompt.  

I'm pretty mystified.  I'm attaching the log from the installer crash, please let me know if there's any other pertinent info I've left out.  

![pyrevit 1](https://user-images.githubusercontent.com/47393355/55731275-eec95480-59e7-11e9-896d-d67f6882d8eb.png)
![pyrevit 3](https://user-images.githubusercontent.com/47393355/55731361-14eef480-59e8-11e9-826b-453140c16ca5.png)
![pyrevit 2](https://user-images.githubusercontent.com/47393355/55731362-15878b00-59e8-11e9-94fe-6187080e9a0b.png)

[MSI7FDB.LOG](https://github.com/eirannejad/pyRevit/files/3054724/MSI7FDB.LOG)

**Comment by eirannejad** [comment]
Install the pyRevit normally again. Then test if `pyrevit` command works in the prompt. Don't uninstall. Let me know of the results. I'll help out getting the error fixed.

Read this in the meantime: https://eirannejad.github.io/pyRevit/deploy/

**Comment by MatthewJohnsonVMDO** [comment]
When I run the installer I don't get the option to install, only repair, modify or remove.  Trying any of those three results in the "ended prematurely" error I screenshotted above.  Do I need to go into the registry and manually remove pyRevit first?  I'm hesitant to mess around in my registry but will if I have to.

**Comment by MatthewJohnsonVMDO** [comment]
The pyrevit command isn't recognized by Command Prompt right now.

Reopening - closed by accident.

**Comment by eirannejad** [comment]
Yes. Please cleanup the keys from registry under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall`

I apologize for the inconvenience. I purchased a license for a better installer maker to avoid these issues but it is really hard to get everything right on all machine conditions.

**Comment by MatthewJohnsonVMDO** [comment]
First of all, you have nothing to apologize for!  This is still an amazing tool being provided for free.  

After some difficulty I got PyRevit fully purged from the registry and reinstalled.  Now that it's installed again, PyRevit works perfectly for that user.  Not sure what caused the initial problem or if it will reappear.  Here are the results of the pyrevit command:

![pyrevit 1](https://user-images.githubusercontent.com/47393355/55908939-bfae1100-5ba8-11e9-901b-2ab92b813db5.jpg)

**Comment by eirannejad** [comment]
Okay good. Now lets run these command and share results
`pyrevit clones`
`pyrevit revits --installed`

**Comment by MatthewJohnsonVMDO** [comment]
Here you go:
![pyrevit 1](https://user-images.githubusercontent.com/47393355/55910484-8a0b2700-5bac-11e9-9a96-19977a72a6bc.png)

![pyrevit 2](https://user-images.githubusercontent.com/47393355/55910490-8d9eae00-5bac-11e9-9285-4d964e37eef6.png)

**Comment by MatthewJohnsonVMDO** [comment]
if it helps, I went through the same process on a second computer in my office.  The registry keys were different, here's the result of the pyrevit command after reinstalling on the second computer:

![pyrevit sarah](https://user-images.githubusercontent.com/47393355/55910732-1b7a9900-5bad-11e9-974e-d92e3a9d9689.jpg)

**Comment by MatthewJohnsonVMDO** [comment]
Another update if it helps - for all computers experiencing this issue, manually removing PyRevit and reinstalling will get everything working, but when the computer is restarted it's back to square one.

**Comment by eirannejad** [comment]
@MatthewJohnsonVMDO To be honest this doesn't seem to be a pyRevit installer issue. Seems like the installed does its job correctly, and gets pyrevit installed on your machine in correct directory. But then after a restart Revit can not find the loader dll. Something is deleting or maching changes to the installed pyRevit files between restarts. Are your machines controlled by system admin? Is there a startup script or group policy that is making changes to machines?

**Comment by MatthewJohnsonVMDO** [comment]
We do have startup scripts.  I'll talk to the IT folks at my office and report back here as soon as I hear somethin.

**Comment by MatthewJohnsonVMDO** [comment]
Finally got to the bottom of this with my office IT guy.  We think this was a problem with corrupted Windows 7 profiles, and as you guessed not anything to do with PyRevit.  It seems that a permission issue was causing the content of the engine folders to either be deleted or not fully saved for the bad profiles - very weird.  

Anyway thanks for your attention, and sorry for the false error report!

**Comment by eirannejad** [comment]
@MatthewJohnsonVMDO No worries mate. All challenges are welcome :D

**Comment by Michgadu8** [comment]
Hi I am having a similar problem I problem that this on, I tried several times to unistalled and actually I was sucessful finally with 
Revounistaller as somebody suggested on some other chat then I installed again  using this one from the website 

![image](https://github.com/eirannejad/pyRevit/assets/136072516/4bcd5022-4184-4562-9311-d97b77c81966)

But when I open my Revit 2022 I still getting the same issue so I really don't understand what is wrong
 
![Capture](https://github.com/eirannejad/pyRevit/assets/136072516/e81eb381-d529-43b4-974c-5bf34fe51199)

Thank you in advance, 
Michelle
