### ISSUE TITLE
INSTALLATION 4.6.19 Completed but no addin created.

### ISSUE THREAD

**Issue by Majordad101** [eirannejad/pyRevit#574]
**Describe the bug**
Installed the version - 4.6.19.  All processes appeared correct.

I checked the revit addin folder, both the shared and personal folders and the pyrevit.addin was not created in both cases.  I checked the versions of Revit to check if it was the number of addins that may have had the impact of denying access to the ribbon bar.

I am the Administrator and the only user on the laptop. So I tried an installation with a new user and the option of installation for the current user did not appear.  I have another laptop and the installation has been perfect.

I have had an issue with Dynamo 1.3.4 and 2.2 when earlier versions  of pyRevit were loaded.  The Nodes in Dynamo disappeared, and the connectors were all that was visible.  I tested the Nvidia Card/drivers and settings to integrated gpu.  so uninstalled pyrevit.

**Screenshots**
If applicable, add screenshots to help explain your problem.  Until I get the installation resolved, I cannot test the graphics issue again.

**Desktop (please complete the following information):**
 - OS: Win 7 Pro
 - pyRevit Version 4.6.19

**Comment by eirannejad** [comment]
Would you please confirm that pyRevit is installed inside '%appdata%/pyRevit` directory?

**Comment by Majordad101** [comment]
Ehsan,

There are two folders in %appdata%
pyRevit
[image: image.png]


pyRevit-Master
[image: image.png]
The main .dlls etc is in the pyrevit-Master folder.

Many thanks,

Regards

*Pierre Venter*
Pr.Arch B.Arch (Natal)
12 Surbiton Road, Kingston Upon Thames, KT12HX, UK
UK. mobile +44(0)74-1572-3110

**Comment by eirannejad** [comment]
@Majordad101 Hey. I'd really appreciate if you can respond on the issue tracker and not through email. The attachments don't get throught and it has a lot of unnecessary contents and signature with it. Thanks!

**Comment by Majordad101** [comment]
There are two folders in %appdata%.

pyRevit
![2019-04-09_16-51-21](https://user-images.githubusercontent.com/6433222/55859650-632c0100-5b6a-11e9-816c-956e5cd84a55.png)

pyRevit-Master
![2019-04-09_19-51-30](https://user-images.githubusercontent.com/6433222/55859638-5e674d00-5b6a-11e9-8bfd-73a62ed3b432.png)

The main .dlls etc are in the pyrevit-Master folder.  
I have previously cleared out all Registry Entries including previous versions.
My apologies for the response via email.  I didn't think!

**Comment by eirannejad** [comment]
Okay open a command prompt and run `pyrevit attach master 277 --installed`. This would create the `.addin` manifest files to attach pyrevit to installed Revits. Let me know if you see any errors.

**Comment by Majordad101** [comment]
Ehsan,  
Many thanks for the solution.  I had a check on the error i raised and the used the --debug to see there were remnants of the Revit 2015 installation.  I cleared the registry and re-ran the cmd line.  And the .addin files were created.

This was the result of loading revit, and the error raised.  I am stumped.  You have been very tolerant and I thank you for your concern.

![image](https://user-images.githubusercontent.com/6433222/55905478-ecbeeb80-5bc9-11e9-8c66-250f2d4b84e7.png)

**Comment by eirannejad** [comment]
Okay we got it loading. So this error is similar to #442 
pyRevit uses Mahapps module for the metro style UI componens and seems like this creates conflicts with other addons using a different version of this library.

Would you mind investigating and check what other addons you have installed?

**Comment by Majordad101** [comment]
Ehsan,
I loaded into revit, with the error.  I closed Revit.  Opened it again.  Viola!  It required the first load and then worked. great/  Its related to the loading of pyRevit but Revit 2017, had issues with loading a script and running it on ver 1.3.4 .  Repeated on 2018 and no problem on Dynamo ver 1.3.4.  The issue I have had previously was a graphic issue when connectors were visible but, not the nodes.  That appears to have been resolved.  The add-ins count has caused issues with previous versions but pyRevit menu tab was fine.
It has resolved my issues.  So, I am very grateful for your efforts with pyRevit.  Its a brilliant application.  Regards Pierre

**Comment by Majordad101** [comment]
Would you like a list of the addons I have installed?

BIM360Glue
Communicator
CTC-BIM-Batch-Suite 
ExportViewSelector 
revit_exporter2017 
Tools4BimDock 
0_Enscape
Autodesk.Collaborate 
Autodesk.eTransmitApplication
Autodesk.RevitDBLink
Autodesk.RevitMEPSpaceNamingUtility.a...
Avail.Browser.2017
BIM360GlueRevitAddin
BIT.lO.CIassificationManager
BIT.20.ModelChecker
BIT.30.COBieExtension. addin
bluebeamAddin2018
Communicator
Dynamo
ExportViewSelectorApp. addin
FormltConverter
IdeateSoftwarelSW
IdeateSticky
Insight
KMPIus
nwexportrevit
PIG
RTVTools_2017
XrevT ransmit

**Comment by BJozi** [comment]
I'm having the same issue, where it was installed in the administrator account but no other users have the add-in.

I tried running the above command in cmd, does this only work as administrator? The arror I get is below

`'pyrevit' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by Majordad101** [comment]
@BJozi Have you opened the command in the folder containing the pyrevit exe.  Change to the bin folder and check that pyrevit is there.

**Comment by BJozi** [comment]
@Majordad101 Could you elaborate on that, where is the folder I should be able to find pyrevit.exe (assuming you don't mean the installer)?

**Comment by Majordad101** [comment]
If youre using the default settings.  The path is %appdata%
C:\Users\[USERNAME]\AppData\Roaming\pyRevit-Master\bin. to find pyrevit.exe

**Comment by BJozi** [comment]
It's missing from the roaming folder under my user account. We installed it while logged into admin, I'll ask to login and look for it under that account and run the command.

**Comment by Majordad101** [comment]
I have an operating system.  @eirannejad , thanks for the valuable input. Do I close the topic?
