### ISSUE TITLE
System.IO.FileLoadException:Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0

### ISSUE THREAD

**Issue by RainFuneral** [eirannejad/pyRevit#578]
**Describe the bug**
Hello, recently I have found two errors that are all related to the Newtonsoft.Json.dll. 

The first one is when loading the pyRevit 4.7.0 in Revit 2017, it gives the error like below:
![Screen Shot 2019-04-24 at 12 15 19 PM](https://user-images.githubusercontent.com/8878041/56639241-c6f21600-66a2-11e9-9d7b-5a2c38f3e39c.png)

The second one is after I switch to pyRevit 4.6.19, it can be successfully loaded but when i click setting, it gives the same error (System.IO.FileLoadException:Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0).

After some search, I found out that pyRevit always load the Newtonsoft.json.dll(version 6) , which is inside the Revit folder instead of pyRevit/bin/Newtonsoft.json.dll (version 12). 

So I just replaced the versions 6 with version 12 and it all works. But I am not sure if it is ok to do that, cause some components from Revit itself may needs the version 6. 

```
**Desktop (please complete the following information):**
 - OS: windows 10
 - pyRevit 4.7.0/4.6.19
 - pyRevit Environment: 

C:\Users\Revit>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)
47beta | Deploy: "basepublic" | Branch: "release/4.7-beta" | Version: "4.7.0-beta" | Path: "C:\Users\Revit\AppData\Roaming\pyRevit-47Beta"
==> Attachments
Autodesk Revit 2017 First Customer Ship | Clone: "47beta" | Engine: "277"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Revit\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2017 First Customer Ship | Version: 17.0.416.0 | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
==> Running Revit Instances
PID: 2776 | Autodesk Revit 2017 First Customer Ship | Version: 17.0.416.0 | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> User Environment
Microsoft Windows 10 [Version 10.0.17763]
Executing User: DESKTOP-RV2DMVO\Revit
Active User: DESKTOP-RV2DMVO\Revit
Adming Access: No
%APPDATA%: "C:\Users\Revit\AppData\Roaming"
Latest Installed .Net Framework: "4.7.2"
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.12.0.0
```

Thanks,
LL

**Comment by eirannejad** [comment]
Thanks for the info. Yeah these dll resolution overlaps are causing everyone a major headache with many Revit addons. Even Autodesk fixed the version of Dynamo per Revit version so they don't have to deal with these issues. I'm looking at better solutions or removing the dependency. Will do something about this for 4.7 final.

**Comment by eirannejad** [comment]
Recompiled Newtonsoft.Json (12.0.1) recompile to pyRevitLabs.Json (.NET 4.7.1)
This removes the conflict between pyRevit and other addons using a different version of Newtonsoft.Json
