### ISSUE TITLE
"Elapsed Time" and "Percentage of Completion" in progress bar

### ISSUE THREAD

**Issue by martinservold** [eirannejad/pyRevit#580]
Add a display for time elapsed in the title for the progress bar.
My thoughts for adding this are either:
`pb.update_progress(time={seconds})` or 
`with forms.WarningBar(show_time=True)`
With the time formatted to secs/mins/hours

**Comment by martinservold** [comment]
A third option is `with forms.WarningBar(title='...{time}')`

**Comment by martinservold** [comment]
Tacking on to this, `...{percentage}` would be useful as well.

**Comment by eirannejad** [comment]
Closing this. `forms.ProgressBar` has `title` property that is set to `'{value}/{max_value}'` by default but can be customized to create any format as long as it has `{value}` and `{max_value}` formatters
