### ISSUE TITLE
requests lib while using ipy 2.7.7

### ISSUE THREAD

**Issue by simplynail** [eirannejad/pyRevit#584]
Is it possible to use 'requests' http lib with standard RevitPythonShell compatibile IronPython interpreter (2.7.7)?

**To Reproduce**
running
`import requests`

gives following error:
```
Script Executor Traceback:
System.MissingMemberException: 'module' object has no attribute '_getframe'
```
this looks like problem with Frame for IronPython:
https://github.com/IronLanguages/ironpython2/issues/232

has anyone been able to run `requests` in iPy 2.7.7? When I change engine to 2.7.8 there's no problem, lib gets imported and i.e. it's version number ("2.13") can be retrieved

**Desktop (please complete the following information):**
 - OS: [e.g. Windows10]
 - pyRevit Version [e.g. 4.6.19]
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`:
```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.6.19" | Path: "C:\Users\simplynail\AppData\Roaming\pyRevit-Master"
==> Attachments
Autodesk Revit 2016 Update 7 for R2 | Clone: "master" | Engine: "277"
Autodesk Revit 2017.2.4 | Clone: "master" | Engine: "277"
==> Installed UI Extensions
==> Installed Library Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2016 Update 7 for R2 | Version: 16.0.1185.0 | Build: 20161004_0715(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016"
Autodesk Revit 2017.2.4 | Version: 17.0.1158.0 | Build: 20181011_1645(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> Running Revit Instances
PID: 8344 | Autodesk Revit 2017.2.4 | Version: 17.0.1158.0 | Build: 20181011_1645(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> User Environment
Microsoft Windows 10 [Version 10.0.17134]
Latest Installed .Net Framework: "4.7.2"
Installed .Net Target Packs: v4.5.1
pyRevit CLI 0.9.7.0
```

**Comment by eirannejad** [comment]
pyRevit runs in rocket mode by default which uses a light version of the Ironpython engine. Set `__fullframeengine__=True` in your pyRevit script and reload pyRevit. Scripts using `requests` should run normally after.

**Comment by simplynail** [comment]
thanks! this seems to work!
Out of interest - is there any specific reasons why requests in pyrevit is 2.13 and NOT the last one that had python 2 support (2.21)?
Could I somehow easily prepare `requests` newer pack that would support IronPythonShell version 2.7.7?

**Comment by eirannejad** [comment]
The provided version is the only tested version that works with IronPython but the newer versions might be compatible as well. I haven't tested those. Feel free to test and send a pull request if works.

**Comment by ollyhensby** [comment]
> pyRevit runs in rocket mode by default which uses a light version of the Ironpython engine. Set `__fullframeengine__=True` in your pyRevit script and reload pyRevit. Scripts using `requests` should run normally after.
> 
> See [here](https://github.com/eirannejad/pyRevit/blob/master/extensions/pyRevitDevTools.extension/pyRevitDev.tab/Debug.panel/Unit%20Tests.pulldown/Test%20FullFrame%20Engine.pushbutton/script.py)

Hi, I know this issue was closed a while ago but I am trying to use `__fullframeengine__ = True` in a pyRevit script so I can import `requests`.

It says in the docs this is possible: https://pyrevitlabs.notion.site/Anatomy-of-IronPython-Scripts-f11d0099667f46a28d29b028dd99ccaf#f14d37d830ba45178834b1ac50679678

But I am getting this error when I try: `AttributeError: 'module' object has no attribute '_getframe'`. 

IronPython: 2.7.7
pyRevit: 4.8.13

Any ideas how to resolve this?

Example script:

```python
import requests

__fullframeengine__ = True

response = requests.get("https://catfact.ninja/fact?max_length=10")
print(response.json())
```

**Comment by ollyhensby** [comment]
Ignore my comment, I changed the engine to IronPython 2.7.11 and it worked
