### ISSUE TITLE
PyRevit Set Crop Region to Selected Shape

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#585]
Just tested the PyRevit Set Crop Region to Selected Shape and I noticed the following:

1. It didn't apply the Crop Region to the curve. (refer to screenshot)
2. It didn't crop the Room Tags/Grids on the plan view. (refer to screenshot)
3. It applied a Crop Region offset for some reason. (refer to screenshot)

btw, is there a way to reset the PyRevit Crop Region?

![image](https://user-images.githubusercontent.com/8776947/56977778-e212c900-6b6d-11e9-9a05-5d69bd8b7b48.png)

**Comment by eirannejad** [comment]
Crop regions can not have curves. I'll modify the script to approximate the curve using smaller lines.

- [ ] Approximate curves in crop region using smaller lines

The crop region pyRevit makes is no different than normal crop regions. Reset as usual using reset crop tool.

![2019-05-01 08_31_41-Autodesk Revit 2019 2 -  Project1 - Floor Plan_ Level 1](https://user-images.githubusercontent.com/8197916/57025338-b3d3ce80-6beb-11e9-8939-a3700994d251.png)

**Comment by eirannejad** [comment]
@Robbo1234 I'm not sure why the offset happens. Would you send me an example model that causes the issue? It runs fine on my tests both for Imperial and Metric models.

**Comment by Robbo1234** [comment]
@eirannejad 

Refer to sheet A102-Plans in the attached Revit 2017.2 model.

![image](https://user-images.githubusercontent.com/8776947/57026070-bdcbf080-6c30-11e9-9d1b-5f027ea7e1d7.png)


[Test-PyTRevit-Set-Crop-Region -To-Selected-Elements-rac_basic_sample_project.zip](https://github.com/eirannejad/pyRevit/files/3135017/Test-PyTRevit-Set-Crop-Region.-To-Selected-Elements-rac_basic_sample_project.zip)

**Comment by Robbo1234** [comment]
@eirannejad 

I went to Reset the Cropped Region and noticed this dashed line which looks like an annotation crop.

Refe screen-shot.

![image](https://user-images.githubusercontent.com/8776947/57026951-ee148e80-6c32-11e9-9f5d-bd4e2343862a.png)

**Comment by Robbo1234** [comment]
FYi, i got this error this morning when running PyRevit Set Crop Region to Selected Shape using the latest version of PyRevit 4.8.0.0

![image](https://user-images.githubusercontent.com/8776947/90139245-0220c880-dd70-11ea-91b9-ba4004058096.png)
