### ISSUE TITLE
Installer ends prematurely 

### ISSUE THREAD

**Issue by NICHOLASJACOBSON** [eirannejad/pyRevit#586]
Hey I am getting a recurring issue with installation in 2019. 2018 always loaded with out issue. 

[MSI8EC6.LOG](https://github.com/eirannejad/pyRevit/files/3133042/MSI8EC6.LOG)

**Comment by eirannejad** [comment]
@NICHOLASJACOBSON The template bug report is there for a reason. Please provide the information asked for in the template issue.
pyRevit doesn't have separate versions for Revit 2018 and 2019. Does it load correctly on 2018?

**Comment by NICHOLASJACOBSON** [comment]
Thanks @eirannejad  It appears now, since my last CPU image, that Pyrevit no longer installs in 2018 either. I'm sorry but I do not know what is or where to find the 'template issue'. Can you help me understand this?

**Comment by eirannejad** [comment]
- pyRevit installs globally on your machine. It doesn't install on 2018 or 2019 or any specific Revit version. Once installed it attaches itself to all available Revit versions

Open a command prmpt and run `pyrevit env` and share the results here please.

Thanks!

**Comment by NICHOLASJACOBSON** [comment]
'pyrevit' is not recognized as an internal or external command,
operable program or batch file.

**Comment by NICHOLASJACOBSON** [comment]
It seems that many in my office are having the same issue since our last image. We have dropped all permissions and still get the same issue.

**Comment by eirannejad** [comment]
Just published 4.6.21. Please test and see if the changes has resolved this issue
https://github.com/eirannejad/pyRevit/releases/tag/v4.6.21

**Comment by eirannejad** [comment]
No response

**Comment by PreFabBIM** [comment]
Hi I'm sorry to add to this thread. I know there are a few threads on this issue and read through them.

I have this same issue. When I was using Revit 2017, Pyrevit was working fine. Then I installed Revit 2018 and it didn't have the Pyrevit app loaded. I know you mentioned there's no Pyrevit for every version of Revit but it appears to me that installing a new version of Revit won't pull the app onto the new version's interface, nor does it appear to load. Can you provide some direction?

**Comment by PreFabBIM** [comment]
Here's my error log file. Thanks for any insight.

[PyRevit v.4.6.23 Error Log.txt](https://github.com/eirannejad/pyRevit/files/3307452/PyRevit.v.4.6.23.Error.Log.txt)
