### ISSUE TITLE
CPython and Cyrillic strings

### ISSUE THREAD

**Issue by DmytroSE** [eirannejad/pyRevit#589]
Hello! Is it possible to use CPython and Cyrillic strings? My first two lines in script are
```
 #! python3  
 # -*- coding: UTF-8 -*-
```
but now i am facing this error
![image](https://user-images.githubusercontent.com/45512632/57170460-b0bc2680-6e15-11e9-8552-cb23d348d61b.png)

**Comment by eirannejad** [comment]
Hmm. Interesting! Okay I'll run some tests. Thanks for the report

**Comment by eirannejad** [comment]
This seems to be related to the execution engine on pythonnet https://github.com/pythonnet/pythonnet/issues/818

**Comment by eirannejad** [comment]
Resolved and will be pushed with 4.7
