### ISSUE TITLE
PyRevit Wipe Tool- Remove Unsheeted Views

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#592]
**Describe the bug**
Ran the PyRevit  Remove Unreferenced Views and I notice it also removed views place on sheets.

**To Reproduce**
1. Go to 'PyRevit Wipe'
2. Click on Wipe model Component
3. Scroll down to and tick any of the Remove Unreferenced Views remove Reference Views'
4. Click Wipe Model
5. 'PyRevit Wipe' removes  Unreferenced Views and aswell as Reference Views.

**Expected behavior**
 'PyRevit Wipe' should only remove Unreferenced Views and retain Reference Views i.e views placed on sheets.

**Screenshots**
![image](https://user-images.githubusercontent.com/8776947/57457736-f9d20780-7267-11e9-9555-51b952db6a36.png)

*Desktop (please complete the following information):**
 - OS: Windows 7
 - pyRevit Version v4.6.19

**Comment by Robbo1234** [comment]
Just noticed a typo.

![image](https://user-images.githubusercontent.com/8776947/57458407-33efd900-7269-11e9-9e82-343f24337669.png)

**Comment by eirannejad** [comment]
The views on the sheet, how were they referenced?

**Comment by Robbo1234** [comment]
They were manually placed on Revit sheets.

**Comment by Robbo1234** [comment]
I'm looking to remove all Revit Views that are not placed on Revit Sheets.

**Comment by eirannejad** [comment]
That's "unsheeted" views. The views that you have on your sheets are correctly being deleted since they are not referenced by any other view.

**Comment by Robbo1234** [comment]
My understanding of Revit Reference Views is that when Revit View is placed
on a Revit Sheet then it becomes referenced. i.e. it gets a view number and
a sheet number (referenced)

Can PyRevit Wipe remove Revit Views that are not placed on Revit Sheets?

**Comment by eirannejad** [comment]
Added that to list of improvements

**Comment by Robbo1234** [comment]
Thanks, Ehsan

**Comment by alexdaversa** [comment]
@eirannejad Looks like this was added, right? Sorry to revive an old issue thread, but I think you can close this one out.
![image](https://user-images.githubusercontent.com/44062587/99724605-de150780-2a81-11eb-92e5-717e5c69743c.png)

**Comment by eirannejad** [comment]
I think so :D Ok closing but feel free to open again if needed
