### ISSUE TITLE
Attach debugger to pyrevit process when creating extension scripts

### ISSUE THREAD

**Issue by buckettt** [eirannejad/pyRevit#593]
**Is your feature request related to a problem? Please describe.**
When creating custom scripts and extensions the current debugging process is tactically placed print statements and inspection of the logs. This can make the process longer than necessary when compared to using more typical debugging methods.

**Describe the solution you'd like**
The ability to attach a debugger to the pyrevit script process. Alternatively launch the process from an IDE (Visual Studio Code). This could allow easier inspection of variables and the inclusion of breakpoints to efficiently debug and develop new scripts.

**Describe alternatives you've considered**

**Additional context**

**Comment by eirannejad** [comment]
@buckettt Please fill in the questions above. The title doesn't tell me much

**Comment by buckettt** [comment]
@eirannejad Apologies I thought I had filled it in...

Is your feature request related to a problem? Please describe.
When creating custom scripts and extensions the current debugging process is tactically placed print statements and inspection of the logs. This can make the process longer than necessary when compared to using more typical debugging methods.

Describe the solution you'd like
The ability to attach a debugger to the pyrevit script process. Alternatively launch the process from an IDE (Visual Studio Code). This could allow easier inspection of variables and the inclusion of breakpoints to efficiently debug and develop new scripts.

**Comment by eirannejad** [comment]
Implemented in 4.8.1

**Comment by Kormaican** [comment]
(Please redirect me if I'm out of place here)

Looking for the PyRevit debugger. From this it seems like there is a debugger implemented, _but I have been having trouble finding anywhere that describes how to use it. Any suggestions?_ 

Most of the forums I find talk about using print statements or such, so hoping for something that would allow me to set _breakpoints_ in my code. Maybe that's not the kind of debugger this is, but if someone could redirect me where to look. 

For reference, I have a decent amount of coding experience, just haven't had the time to go hunting through the entire repository file by file.

**Comment by sanzoghenzo** [comment]
> Looking for the PyRevit debugger. From this it seems like there is a debugger implemented, _but I have been having trouble finding anywhere that describes how to use it. Any suggestions?_

You have to add the following line where you want to start the debug:

```python
import pdb; pdb.set_trace()
```

This is just the standard, built-in way to debug python code; it will open up an output window with some useful buttons.

To learn how to use it, follow one of the guide you can find with google.

I encountered an issue a while ago (you can see it [here](https://github.com/eirannejad/pyRevit/issues/1818)), so be aware that using the debugger can cause some crash that is unrelated to your script.
