### ISSUE TITLE
OpenMcdf.dll Flagged By Antivirus

### ISSUE THREAD

**Issue by IM-BILL-DING** [eirannejad/pyRevit#597]
Hello, my antivirus software flagged pyrevit because of the OpenMcdf.dll file, as that file has been used to infiltrate systems, as noted here:
https://github.com/outflanknl/EvilClippy

**Comment by eirannejad** [comment]
Thanks for the information. [OpenMCDF](https://github.com/ironfede/openmcdf) is a legitimate module. If a hacker decided to use this funcitonality in his attack, that's not the module's fault. The module is used to read Microsoft's OLE file structure that Revit files are written in.

**Comment by eirannejad** [comment]
Similar to #599

**Comment by Dynastywar** [comment]
There is a different version of OpenMCDF that does not flag as being spyware/grayware.  Is it possible to update PyRevit with this version?
http://openmcdf.sourceforge.net/
https://sourceforge.net/projects/openmcdf/

**Comment by eirannejad** [comment]
@Dynastywar Let me pull and test. Thanks for the link

**Comment by eirannejad** [comment]
@Dynastywar so this is what I'm currently using. Not sure where is the "safe" version
https://github.com/ironfede/openmcdf

**Comment by Dynastywar** [comment]
Very strange.
The file from the 2nd link gives a .zip file.  Inside of the zip, OpenMcdf 2.0 > bin > OpenMcdf > openMcdf.dll is a file that is 57,344 bytes instead of the 60,928 bytes in the project.
Definitely different files and versions floating around.

**Comment by eirannejad** [comment]
The one from https://sourceforge.net/projects/openmcdf/ is an older version it seems

**Comment by eirannejad** [comment]
Closing this. Can not find anything that specifies there is anything wrong with openmcdf module. Add exceptions to Antivirus to skip this dll.
