### ISSUE TITLE
Sweet crash on Application Loading

### ISSUE THREAD

**Issue by kraftwerk15** [eirannejad/pyRevit#598]
**Describe the bug**
If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

Note: Tried above with no success.

**To Reproduce**
1.) Install pyRevit. Installation does complete correctly. Also, I uninstalled and then reinstalled to get the below error.
2.) Get Error.

**Expected behavior**
Functioning pyRevit. 

**Screenshots**
See below.

**Desktop (please complete the following information):**
 - OS: Windows 10 10.0.17763
 - pyRevit Version 4.6.19
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

**Additional context**
Leaving the bug report for your use. I'll try running through all of this again tomorrow.

![pyRevitCrash](https://user-images.githubusercontent.com/30668448/57890019-0ae8be80-77fc-11e9-9e2d-29087ba0ad52.png)

**Comment by eirannejad** [comment]
This is a conflict between the version of MahApps metro that pyRevit uses versus the version that other addons use. It's been reported a couple of time before and it came back again here https://github.com/eirannejad/pyRevit/issues/594

I'm closing this here so please follow the conversation on issue #594

I'll be providing a test installer soon to see if the solution that I came up with actually solves the issue

Thanks for the report!

**Comment by eirannejad** [comment]
Merged with https://github.com/eirannejad/pyRevit/issues/594
