### ISSUE TITLE
Error installing/loading Pyrevit Malware detected while installing

### ISSUE THREAD

**Issue by murets84** [eirannejad/pyRevit#599]
Hello,
Since a couple of days I am experiencing errors while loading pyrevit.
I tried reinstalling it. While re installing it there is this antivirus pop-up ( see Error_4 image)
I am not able to drag and drop images. So here i leave a link for a wetransfer that contains the images:

https://we.tl/t-GFmrtaZTfw

Thanks in advance for your help

**Comment by eirannejad** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/597

Your antivirus has deleted a pyRevit dependency (OpenMcdf.dll). Add an exclusion in your antivirus please
