### ISSUE TITLE
Match - Painted face

### ISSUE THREAD

**Issue by jkcameron** [eirannejad/pyRevit#600]
You had a previous feature request to add "Painted surface" to the match button functionality.

"Match to work on Material Painted surfaces. #498"

In another post you stated that this feature was implemented and pushed but for some reason I still am not able to enable this.  In the example you show hovering over the Match button showing a roll down for painted surface.  Was this feature in fact added?

Thanks so much for all your work.

**Comment by eirannejad** [comment]
![2019-05-17 08_58_53-Autodesk Revit 2019 2 -  Project1 - Floor Plan_ Level 1](https://user-images.githubusercontent.com/8197916/57940738-049d2580-7882-11e9-8e7c-e1e8f4927d8a.png)
