### ISSUE TITLE
Error after install "Object reference not set to an instance of an object" when opening revit

### ISSUE THREAD

**Issue by wtwnei** [eirannejad/pyRevit#603]
I installed the program with no issues. It did need to install ".net core runtime 2.0.7 (x64) as part of the install.  
I then tried opening revit versions 2018, 2019, 2020 and received the error above.
I did try running the command `pyrevit attach master 277 --installed` at the command line and powershell and it made no difference.
I also confirmed that my version of nlog.dll was correct:
![image](https://user-images.githubusercontent.com/50836600/58030334-5cd76000-7aec-11e9-884f-3f3fb803b9eb.png)

Here is a snippet of the error:
![image](https://user-images.githubusercontent.com/50836600/58030571-c5bed800-7aec-11e9-8f8d-d60e2beb798b.png)

 - Windows 10
 - pyRevit Version 4.6.21_signed
 - pyRevit Environment: 

![image](https://user-images.githubusercontent.com/50836600/58030860-55648680-7aed-11e9-8982-037d250ebaf7.png)

**Comment by eirannejad** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/603
Closing this here. Follow the conversation on 601

**Comment by wtwnei** [comment]
Thank you, that worked!
-Nancy

[WTW Logo.45]<http://www.wtwarchitects.com/index_flash.html>  NANCY E. INNES | BIM MANAGER
WTW ARCHITECTS | TIMBER COURT | 127 ANDERSON STREET | PITTSBURGH, PA 15212
NINNES@WTWARCH.COM<mailto:NINNES@WTWARCH.COM> | WTWARCHITECTS.COM<http://www.wtwarchitects.com/> | 412-315-3469

[Facebook-Windows-8-logo-EMAIL]<https://www.facebook.com/WTWArchitects/>  [LinkedIn-flat-logo-2_EMAIL] <https://www.linkedin.com/company/4292254?trk=tyah&trkInfo=clickedVertical:company,entityType:entityHistoryName,clickedEntityId:company_company_company_4292254,idx:0>

**Comment by eirannejad** [comment]
@wtwnei YESSSSS! Thanks!
