### ISSUE TITLE
4.6.22 error loading

### ISSUE THREAD

**Issue by need4mospd** [eirannejad/pyRevit#605]
**Describe the bug**
The latest update fixed my machine. However, another user isn't having much luck.

**Screenshots**
![Error1](https://user-images.githubusercontent.com/46454815/58045315-b8631700-7b07-11e9-890b-db57a5d6af73.png)
![Error2](https://user-images.githubusercontent.com/46454815/58045317-bac57100-7b07-11e9-881e-a988493a98d4.png)

**Desktop (please complete the following information):**
 - OS: Windows 7(I know...)
 - pyRevit Version 4.6.22
 - pyRevit Environment: Can't access user's machine at the moment, will update if necessary.

**Comment by eirannejad** [comment]
Hmmm I kinda need the `pyrevit env` report. Seems like for some reason pyRevit can not find its cpython engines

**Comment by shafeeque166** [comment]
![Py error-1](https://user-images.githubusercontent.com/50824366/58076729-a3dc5880-7bb3-11e9-91d2-bcc39c2ddbf2.jpg)
![Py error-2](https://user-images.githubusercontent.com/50824366/58076731-a63eb280-7bb3-11e9-95fd-ac0a36d166a7.jpg)

Am also facing same issue how can i load pyrevit ?

**Comment by need4mospd** [comment]
Here's the env report:

`C:\Users\jamesf>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.6.22" | Path: "C:
\Users\jamesf\AppData\Roaming\pyRevit-Master"
==> Attachments
Unnamed | Product: "Autodesk Revit 2019.2.1" | Engine: 277 | Path: "J:\_BIM Soft
ware\pyRevitKirksey" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2019\pyRe
vit.addin"
Unnamed | Product: "Autodesk Revit 2018.3.1" | Engine: 277 | Path: "J:\_BIM Soft
ware\pyRevitKirksey" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2018\pyRe
vit.addin"
master | Product: "Autodesk Revit 2017.2.2" | Engine: 277 | Path: "C:\Users\jame
sf\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\jamesf\AppData\Roaming\
Autodesk\Revit\Addins\2017\pyRevit.addin"
master | Product: "Autodesk Revit 2015 Release 2 Update Release 14  (Subscriptio
n only release)" | Engine: 277 | Path: "C:\Users\jamesf\AppData\Roaming\pyRevit-
Master" | Manifest: "C:\Users\jamesf\AppData\Roaming\Autodesk\Revit\Addins\2015\
pyRevit.addin"
master | Product: "Autodesk Revit 2015 Update Release 14" | Engine: 277 | Path:
"C:\Users\jamesf\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\jamesf\Ap
pData\Roaming\Autodesk\Revit\Addins\2015\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\jamesf\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2019.2.1 | Version: 19.2.10.7 | Build: 20190225_1515(x64) | Langu
age: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
Autodesk Revit 2018.3.1 | Version: 18.3.1.2 | Build: 20180423_1000(x64) | Langua
ge: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018"
Autodesk Revit 2017.2.2 | Version: 17.0.1146.0 | Build: 20170816_0615(x64) | Lan
guage: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
Autodesk Revit 2015 Release 2 Update Release 14  (Subscription only release) | V
ersion: 15.0.1259.0 | Build: 20160512_0715(x64) | Language: 1033 | Path: "C:\Pro
gram Files\Autodesk\Revit Architecture 2015"
Autodesk Revit 2015 Update Release 14 | Version: 15.0.421.0 | Build: 20160512_15
15(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2015"
==> Running Revit Instances
PID: 7564 | Autodesk Revit 2019.2.1 | Version: 19.2.10.7 | Build: 20190225_1515(
x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> User Environment
Microsoft Windows 7 [Version 6.1.7601]
Executing User: KIRKSEY\jamesf
Active User: KIRKSEY\jamesf
Adming Access: No
%APPDATA%: "C:\Users\jamesf\AppData\Roaming"
Latest Installed .Net Framework: 4.7.1
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.10.0.0
`

**Comment by eirannejad** [comment]
Okay please check as see if these files and folders exist
`C:\Users\jamesf\AppData\Roaming\pyRevit-Master\bin\engines\368`
`C:\Users\jamesf\AppData\Roaming\pyRevit-Master\bin\engines\372`
`C:\Users\jamesf\AppData\Roaming\pyRevit-Master\pyRevitfile`

Send me screenshots if possible please

**Comment by need4mospd** [comment]
Looks like they all exist:

![Folder372](https://user-images.githubusercontent.com/46454815/58111530-40542a00-7bb7-11e9-8400-c2cca46fa891.png)
![Folder368](https://user-images.githubusercontent.com/46454815/58111532-40542a00-7bb7-11e9-8d29-250c13543f8a.png)
![pyRevitfile](https://user-images.githubusercontent.com/46454815/58111533-40542a00-7bb7-11e9-8fb7-10e0fa115731.png)

**Comment by eirannejad** [comment]
@need4mospd Hey I build a few safeguards against this issue but the only times that I can replicate it is when the `pyRevitfile` file inside the pyRevit installed path is missing. I also noticed that the attachment to Revit 2019 and 18 says unnamed. This means

```
=> Attachments
Unnamed | Product: "Autodesk Revit 2019.2.1" | Engine: 277 | Path: "J:\_BIM Soft
ware\pyRevitKirksey" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2019\pyRe
vit.addin"
```

Seems like you have a pyrevit clone that is not registered. It is probably missing the files below:

```
J:\_BIM Software\pyRevitKirksey\pyRevitfile
J:\_BIM Software\pyRevitKirksey\.pyrevitargs
```

**Comment by need4mospd** [comment]
Yeah, it turns out it was an old version I had done a half-ass attempt at deploying to this user a while ago. Once I realized that, I was able to clear out the old stuff manually and everything installs with no issues! I appreciate your help in troubleshooting this!
