### ISSUE TITLE
No module named pyrevit

### ISSUE THREAD

**Issue by sajusathish** [eirannejad/pyRevit#606]
Hi,
Firstly iam new to github and rps so kindly bear with me ,when i try to copy paste the script in tools by alt+clicking and run in rps it says no module named py revit.
 Tried to apped the path to sys path but i find your modules in different folders in programme files .

Can you please let me know how to import your package ( like forms scripts..etc) into rps.
Thanks.

**Comment by eirannejad** [comment]
Hey. You need to add the `pyrevitlib` directory to the sys paths in RPS configurations

![2019-05-20 20_49_20-Configure RevitPythonShell](https://user-images.githubusercontent.com/8197916/58067086-e749af00-7b40-11e9-80fe-96453d1a3640.png)

**Comment by sajusathish** [comment]
@eirannejad  
Thank you so much it worked
