### ISSUE TITLE
Can't install pyRevit 4.6.22 

### ISSUE THREAD

**Issue by AsselinThomas** [eirannejad/pyRevit#607]
**Describe the bug**
Hi! After a mistake, I couldn't install pyRevit on my computer. Indeed, I tried to uninstall/reinstall pyRevit 4.6.20 and then go to 4.6.22 but it would never finish the installation. 

When I try to update to 4.6.22, i get this error : 
<img width="366" alt="Capture2" src="https://user-images.githubusercontent.com/50858470/58137517-e6666980-7c75-11e9-8391-9758374effae.PNG">
And when I try to install 4.6.20 back i get this: 

<img width="368" alt="Capture1" src="https://user-images.githubusercontent.com/50858470/58137543-fa11d000-7c75-11e9-8d14-8d20c4e5622e.PNG">

I've tried to clean the register, uninstall/install revit, RPS and start all over but nothing. I can't even use the pyrevit env on the cmd prompt as it tells me that "'pyrevit' is not recognized as an internal or external command, operable program or batch file." 

Any idea? Thank you very much for your help.

**Comment by eirannejad** [comment]
The entries for pyRevit are messed up in the windows registry due to failed install/uninstalls.

Open registry editor (`regedit.exe`) and search for pyRevit under these keys and delete the subkeys.

`Computer\HKEY_CURRENT_USER\Software\Caphyon\Advanced Installer`
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall`

I will add an option into the cli to be able to fix these install issues.

**Comment by AsselinThomas** [comment]
Hi, thanks for the answer. Unfortunately, I've tried that already, and after looking through these specific keys, I still can't install pyRevit.

**Comment by eirannejad** [comment]
@AsselinThomas Okay let me build a doctor command into the pyrevit CLI this weekend to search and fix these registry issues with the installer. Sorry for the troubles. I adopted "Advanced Installer" thinking as a very popular installer it would solve the install issues on windows. oh well.

Please test and makes sure you can install [pyRevit CLI](https://github.com/eirannejad/pyRevit/releases/tag/cli-v0.10.0.0) independently

**Comment by eirannejad** [comment]
@AsselinThomas hey quick question. Do you have the pre .22 pyRevit still installed on your machine? Seems like for some reason they `pyrevit.exe` utility gets removed in installs and that breaks the uninstaller that wants to cleanup after the install.

**Comment by eirannejad** [comment]
@AsselinThomas Would you mind checking under this key as well
`Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall`

It is similar to the one listed above but is for local user.  You'll probably see a couple of pyRevit keys listed there. Deleting those will remove the entry in "Programs and Features". So the new installed doesn't need to uninstall the older first (which makes the installer break)

**Comment by AsselinThomas** [comment]
@eirannejad I just installed installed pyRevit CLI independently and successfully. 

I have no previous version still installed (at leaste that i can see) on my machine. I've uninstalled and deleted everything that has to do with pyRevit, so that's why I am confused

And I checked under Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall and I couldn't find anything related to pyRevit, as I have already cleaned through the whole register thanks to the "Find" tool.

Thanks a lot for the help, I hope it'll be fixed soon, I really need this to work for my job

**Comment by eirannejad** [comment]
@AsselinThomas Okay one last thing I can do is that we can setup a screen-share for sometime tomorrow and I can take a look and hopefully fix it. The information will help me build the fix into the tool as well. Email me please with the time slots that work for you and will get it setup.

**Comment by eirannejad** [comment]
@AsselinThomas The only entry that I could find inside the registry is under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Installer\Folders`

Value is `C:\Users\s439722\AppData\Roaming\Microsoft\Installer\{2FA86D06-A1A1-4908-BEB9-877B62D28D75}\`

The `{2FA86D06-A1A1-4908-BEB9-877B62D28D75}` is product id for v4.6.20

**Comment by AsselinThomas** [comment]
@eirannejad Thanks for the answer. I've found and deleted it, but still won't install pyRevit. Do you think I should reset my computer? There's not much on it, it's a work computer recently acquired.

**Comment by eirannejad** [comment]
@AsselinThomas I guess that would fix the issue. I'm terribly sorry for the trouble :/

**Comment by AsselinThomas** [comment]
@eirannejad Don't worry about that! Thanks anyway for all the help :)

**Comment by miabink** [comment]
Hi there! I'm having the same issue of not being able to install new version because it can't seem to find the old files to delete. Is there, hopefully, a workaround besides resetting the computer?

![PYREVIT FAIL ](https://user-images.githubusercontent.com/60527928/73581260-7089e300-443d-11ea-8ddd-eac89d109219.JPG)

Thanks for any help!
