### ISSUE TITLE
pyRevit v4.6.22 - Installation on Roaming Profile/Failure to run on Network Revit

### ISSUE THREAD

**Issue by AlexWatkiss** [eirannejad/pyRevit#608]
Hi Ehsan,

I am having an issue with installing PyRevit onto my workplace computer. Our IT manager in the office has tried installing to multiple locations on our system including the main server, C drive and our roaming profiles within the office.

The program appears to unpackage and install to the location with no issues. However, when we start up Revit unfortunately it does not ask us to load the PyRevit add-in. I have previously installed this version on my home computer last night with no issues. But no luck at work even with administrator privileges and our IT manager attempting to install on my machine.

Our default installation path appears as follows:

\\AA-FS01\RP-RDF$\a.watkiss\AppData\Roaming\pyRevit-Master\

Any help you could offer would be greatly appreciated.

Kind regards,

Alex

**Comment by eirannejad** [comment]
When you started this issue, there were directions on how to get these issues fixed. Did you get a chance to test them?

**Comment by eirannejad** [comment]
I need more info on this error please. Screenshots, `pyrevit env` report, ...

**Comment by eirannejad** [comment]
No response
