### ISSUE TITLE
Keynote Manager Delete Category

### ISSUE THREAD

**Issue by kraftwerk15** [eirannejad/pyRevit#609]
**Describe the bug**
Trying out the Manage Keynote browser. It appears that Delete Category is not bound to anything. The button is accessible (not disabled) to the user, but does not display or note this is a full-production feature or should be available in beta.

Running 4.6.19

https://github.com/eirannejad/pyRevit/blob/28f9d352746b9f72d71a5091d777373b18fd686f/extensions/pyRevitTools.extension/pyRevit.tab/Drawing%20Set.panel/Keynotes.pushbutton/script.py#L795

**To Reproduce**
1. Open Keynote Manager
2. Click on Delete Category
3. Category is not deleted

**Expected behavior**
A Category to be deleted.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Running 4.6.19

**Solution**
If a full production feature that needs further testing, disabling the button informs the user that the category cannot be deleted and must be manually deleted. Thanks

![image](https://user-images.githubusercontent.com/30668448/58191040-647d3d00-7c83-11e9-8674-7d5e6e19e916.png)

**Comment by eirannejad** [comment]
Thanks for the great bug report.

**Comment by eirannejad** [comment]
Resolved and will be pushed with 4.6.23
