### ISSUE TITLE
Schedule export on non-english Revit

### ISSUE THREAD

**Issue by bobbieqc** [eirannejad/pyRevit#611]
export schedule in revit french version do not work

**Comment by eirannejad** [comment]
Error reports? Screenshots?

**Comment by bobbieqc** [comment]
![image](https://user-images.githubusercontent.com/37275193/58295280-5e2eb400-7d9c-11e9-81f0-ca700bdcce23.png)

**Comment by eirannejad** [comment]
Which pyRevit version?

**Comment by bobbieqc** [comment]
4.6.22

**Comment by bobbieqc** [comment]
i use the french version of revit.

**Comment by bobbieqc** [comment]
Maybe it is the way i selecte the schedule what is the rigth way to do it?

**Comment by bobbieqc** [comment]
Must be related to parameter name

**Comment by eirannejad** [comment]
Resolved and will push with v4.6.23
