### ISSUE TITLE
PyRevit plugin interface dynamic image

### ISSUE THREAD

**Issue by alisofi123** [eirannejad/pyRevit#615]
Hello guys,
I have a question related to the plugin interface. I am currently using the Flexform option to display my interface. 
Any other options where I can insert a dynamic image in the interface? like in the below image:

![reinforcement_of_columns](https://user-images.githubusercontent.com/46194284/58556639-2785ed00-8225-11e9-997c-5e2f88b0bd61.png)

**Comment by eirannejad** [comment]
@gtalarico Flexform is in `rpw` right?

**Comment by alisofi123** [comment]
Yes it is in rpw sorry I didn't mention that!

**Comment by eirannejad** [comment]
Not sure about `Flexform` but if you are using WPF, you can assign a name to the `<image>` element e.g. `x:Name="myimage"` and then assign a BitmapImage object to its `Source` property:

```xaml
<Image x:Name="myimage" Width="100" Height="50" />
```
```python
from pyrevit import forms

# inside window wrapper class
self.myimage.Source = forms.utils.bitmap_from_file(image_file_path)
```

**Comment by eirannejad** [comment]
Closing this since it is not an issue. You can continue the conversation tho.
