### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by cridder** [eirannejad/pyRevit#616]
**Describe the bug**
Hit update button.  log informed that it was unable to update run in debug mode.  
`' INFO: [pyrevit.versionmgr.updater] Can not update repo: pyRevit (Run in debug to see why) '`  
cridder_20190530_update_error_1 log attached.

Hit update button with ctrl. cridder_20190530_update_error_2 log attached.
```
' DEBUG: [pyrevit.extensions.parser] Parsing directory for extensions of type: <class 'pyrevit.extensions.components.Extension'>
DEBUG: [pyrevit.extensions.parser] Searching directory: C:\Users\chris.ridder\Dropbox (TEECOM)\TEECOM Revit Tools\pyRevit for components of type: [<class 'pyrevit.extensions.components.Extension'>]
DEBUG: [pyrevit.extensions.parser] Skipping _get_component. Name can not start with . or _: C:\Users\chris.ridder\Dropbox (TEECOM)\TEECOM Revit Tools\pyRevit\.git
DEBUG: [pyrevit.extensions.parser] Skipping _get_component. Name can not start with . or _: C:\Users\chris.ridder\Dropbox (TEECOM)\TEECOM Revit Tools\pyRevit\.gitignore
DEBUG: [pyrevit.extensions.parser] Skipping _get_component. Name can not start with . or _: C:\Users\chris.ridder\Dropbox (TEECOM)\TEECOM Revit Tools\pyRevit\.vscode
DEBUG: [pyrevit.extensions.parser] Testing _get_component(s) on: C:\Users\chris.ridder\Dropbox (TEECOM)\TEECOM Revit Tools\pyRevit\docs
DEBUG: [pyrevit.extensions.parser] Testing sub_directory C:\Users\chris.ridder\Dropbox (TEECOM)\TEECOM Revit Tools\pyRevit\docs for <class 'pyrevit.extensions.components.Extension'>
DEBUG: [pyrevit.extensions.parser] Can not create component of type: <class 'pyrevit.extensions.components.Extension'> from: C:\Users\chris.ridder\Dropbox (TEECOM)\TEECOM Revit Tools\pyRevit\docs '
```

[cridder_20190530_update_error_1.txt](https://github.com/eirannejad/pyRevit/files/3237935/cridder_20190530_update_error_1.txt)
[cridder_20190530_update_error_2.txt](https://github.com/eirannejad/pyRevit/files/3237936/cridder_20190530_update_error_2.txt)

**Expected behavior**
Expect a successful update

**Desktop (please complete the following information):**
 - OS: [W10]
 - pyRevit Version [4.6.19]
 - pyRevit Environment: Cant find on how to do open a cmd prompt :(

**Comment by eirannejad** [comment]
@cridder only full git clones of pyRevit can be updated using the update tool. Use new installers to install new versions of pyRevit or if you are managing the installations using the CLI tool, you can `pyrevit clones update` your local clone to a newer version
