### ISSUE TITLE
Select Dependants by Level

### ISSUE THREAD

**Issue by jkcameron** [eirannejad/pyRevit#620]
Is there a way to show the objects linked to a specific level?  A levels dependencies basically.  When I delete a level I would like to know what objects will be deleted with it.  The OOTB Revit Warnings will tell you specifics regarding which views will be deleted but not objects.  I'm sure there was a way to do this but I'm having trouble.  Apologies in advance if this has already been covered but my searches came up nothing.

**Comment by eirannejad** [comment]
Try using

![2019-06-03 09_17_37-Window](https://user-images.githubusercontent.com/8197916/58817376-72ff1900-85e0-11e9-9c54-0c66c13e95e5.png)

It fake-deletes the level and grabs and prints a list of all other dependent and deleted elements.

**Comment by jkcameron** [comment]
Dang... I'm so sorry... I should have researched more.  Thanks so much man.   Pyrevit is by far the best thing that has happened to Revit since its release.  I know I speak for everyone at my office.... your hard work is much appreciated.

**Comment by eirannejad** [comment]
@jkcameron Thank you so much :)

**Comment by thazell** [comment]
Small recommendation:  rename "Find Linked Elements" to "Find Referenced Elements", since most users think of linked elements being in a linked model.  There might be a better term than reference, perhaps hosted (but that has it's own meaning as well)

**Comment by eirannejad** [comment]
@thazell done.
