### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by reynolt** [eirannejad/pyRevit#622]
I have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load. I tried running the recommended commands, and read through every other issue reported related to this and still couldn't find a solution. 

When I run `pyrevit attach master 277 --installed` I get the error: "Object reference not set to an instance of an object."

I also get the same message when I tried running "pyrevit env" 

I am looking for a Dynamo compatible version so I also tried "pyrevit attach master dynamosafe" and received the same object reference message.

I've tried running about every variation possible and still cannot get pyRevit to load.

**Comment by eirannejad** [comment]
Would you please run `pyrevit attach master 277 --installed --debug` and send me the full report? You can redirect the output to a file by addin ` > somefile.log` at the end of the command

**Comment by reynolt** [comment]
Hi Ehsan, i put in the text file below

[pyrevit debug.txt](https://github.com/eirannejad/pyRevit/files/3266791/pyrevit.debug.txt)

**Comment by eirannejad** [comment]
Are you using the latest CLI? Seems like you havea Revit 2013 on your machine with version `12.11.10090`. Correct? Would you be able to grab the build number and Revit version name e.g. "2013 Update Release 2" from your machine?

**Comment by reynolt** [comment]
Yes, I have it installed for an old project deep in CA. If I uninstalled 2013 do you think that would solve the problem? I'm looking to use pyrevit in 2018 and 2019. 

the build number is: 20130531_2115(x64)
Update Release 3

**Comment by eirannejad** [comment]
Would you mind confirming which pyRevit version are you trying to install?

**Comment by reynolt** [comment]
Yes, I tried 4.6.23 and then 4.6.22 to see if that would work. These reports I've sent are from 4.6.23

**Comment by eirannejad** [comment]
Resolved and will be pushed with 4.6.24

**Comment by reynolt** [comment]
Great thank you!
