### ISSUE TITLE
Error loading pyRevit

### ISSUE THREAD

**Issue by Misacsson** [eirannejad/pyRevit#625]
**Describe the bug**
I get this error straight afterwards installation when starting Revit.
Revit 2019. Error:

![image](https://user-images.githubusercontent.com/38316811/59438141-35c23480-8df3-11e9-8f8b-3f1683d98448.png)

**To Reproduce**
1. Start Revit

**Expected behavior**
-

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.6.23
 - pyRevit Environment: 
```
Autodesk Revit 2020.0.1 | Version: 20.0.1.2 | Build: 20190412_1200(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
Autodesk Revit 2019.2.1 | Version: 19.2.10.7 | Build: 20190225_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
Autodesk Revit 2018.3.1 | Version: 18.3.1.2 | Build: 20180423_1000(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018"
Autodesk Revit 2017.1.1 | Version: 17.0.1099.0 | Build: 20161117_1200(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
Autodesk Revit 2016 Update 7 for R2 | Version: 16.0.1185.0 | Build: 20161004_0715(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016"
Autodesk Revit 2015 Update Release 14 | Version: 15.0.421.0 | Build: 20160512_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2015"
```

**Additional context**
-

**Comment by eirannejad** [comment]
Would you mind scrolling to the top of the error window and screenshot the message? This screenshot is showing the bottom part only.

**Comment by Misacsson** [comment]
Here's the top of the error:
![image](https://user-images.githubusercontent.com/38316811/59508299-bf363d00-8ead-11e9-8722-fcd2a963b6ea.png)

**Comment by eirannejad** [comment]
Hmm. Okay what does that `WindowsError: [Errno 22]` line says?

**Comment by Misacsson** [comment]
It sais something similar to "The client is missing a necessary privelege"

Den fre 14 juni 2019 kl 18:18 skrev Ehsan Iran-Nejad <
notifications@github.com>:

**Comment by Misacsson** [comment]
@eirannejad Do you know any solution to this problem? I'm really starting to miss pyRevit among my addins :)

**Comment by eirannejad** [comment]
Not really. I can not replicate the issue. Seems like system can not access one or more than one of the files under `pyrevitlib\pyrevit\loader\basetypes`

Go to your config.ini file under `%appdata%/pyRevit` and turn on the `filelogging = true`
Then open a console and run `pyrevit caches clear --all`
Then run Revit 2019, and after the error happened
Then look under %appdata%/pyRevit/2019` and share the `pyRevit_2019_**_runtime.log` file here.

**Comment by Misacsson** [comment]
Hi!

Seemed to be a problem at our company, was solved by running Revit one time
with admin rights.
Afterwards pyRevit works as intended :)
/Marcus

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfritt.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Den ons 26 juni 2019 kl 00:10 skrev Ehsan Iran-Nejad <
notifications@github.com>:

**Comment by eirannejad** [comment]
Thanks for the update.

**Comment by Misacsson** [comment]
Hi! For us the solution was running Revit as admin.

/Marcus Isacsson (via mobilen)

________________________________

**Comment by Misacsson** [comment]
Hi again!


Just wanted you to know that McAfee just detected pyrevit-autocomplete as a
threat:

[image: image.png]

Guess it's a mistake though?
/Marcus

Den tors 13 juni 2019 kl 18:59 skrev Ehsan Iran-Nejad <
notifications@github.com>:
