### ISSUE TITLE
Standalone

### ISSUE THREAD

**Issue by sajusathish** [eirannejad/pyRevit#626]
Hi ,I have recently started using pyrevit a couple of weeks ago and Iam totally amazed by your efforts hats off.
Btw, I also tried to get some information about creating a standalone exe file from the script i have created.
Does Pyrevit have any such tool that can copy the psckages used including pyrevit package with or without the pyrevit tools and convert into an exe so that it can be run as a standalone.!

**Comment by eirannejad** [comment]
No. pyRevit runs inside Revit environment and external binaries can not have access to Revit runtime,
