### ISSUE TITLE
Geometry tutorial with RPS

### ISSUE THREAD

**Issue by sajusathish** [eirannejad/pyRevit#627]
Hi,
I am not sure if this is the place for this question but can I ask to publish a tutorial on YouTube about geometry handling with RPS I have seen the basic tutorials in YouTube and felt that it would be better and easier to understand how to work with geometric elements stuffs like exploding a geometry ect..I would say similar to filter element collector video.
Could you please do it when ever you find time ,I think it would be of great use to me.

**Comment by eirannejad** [comment]
Closing since this is a question/request and not an issue. Keeping the conversation open.
