### ISSUE TITLE
sqlalchemy library import errors

### ISSUE THREAD

**Issue by buckettt** [eirannejad/pyRevit#630]
**Describe the bug**
importing sqlalchemy found in site-packages and creating and engine (using sqlalchemy.create_engine) throws an import error meaning sql connections cannot be made.

**To Reproduce**
Example script:
```
from sqlalchemy import create_engine
my_connection = create_engine('mysql+mysqlconnector://XXX:YYY@ZZZ:####/QQQQ')
```

**Expected behavior**
Expect a sql connection to occue

**Screenshots**
![image](https://user-images.githubusercontent.com/10283687/59671102-fd38a700-91b4-11e9-9517-e2c442c5279f.png)

**Additional Information**
Running the same script on my anaconda 3.6 environment works fine with sqlalchemy installed in the relevant place.

**Comment by buckettt** [comment]
Ironpython is not listed as a support platform.

https://docs.sqlalchemy.org/en/13/intro.html#supported-platforms

**Comment by eirannejad** [comment]
Ya I get a series of other errors.
- [ ] Test sqlalchemy compatibility

**Comment by buckettt** [comment]
I was able to get it working using pymysql (additional library requires installation.)

```
from sqlalchemy import create_engine
my_connection = create_engine('mysql+pymysql://XXX:YYY@ZZZ:####/QQQQ')
```

However, queries could only be called using the raw MYSQL queries.
e.g.: 

```
cnx = my_connection.raw_connection()
cursor = cnx.cursor()
query = "SELECT * FROM my_table"
cursor.execute(query)
```

The ORM and mysql expression language don't work. so this will fail:
```
with my_connection.connect() as con:
    meta = MetaData(my_connection)
    rows = Table('my_table', meta, autoload=True)  
    stm = select([rows])
    rs = con.execute(stm) 
```

**Comment by eirannejad** [comment]
pyRevit 4.8-beta has Ironpython 2.7.10 engine. Would you mind testing this with the newer ironpython?
