### ISSUE TITLE
Multiple Forms in one

### ISSUE THREAD

**Issue by sajusathish** [eirannejad/pyRevit#631]
Is there any way to allow user to make multiple input to pyrevit forms 
for instance a form asking Name,age,sex,qualification with four ask for string module
instead of having four forms that keeps to pop up.!

**Comment by eirannejad** [comment]
A lot of pyRevit tools have customized forms. You have two options:

- Create your own custom form using XAML (use Visual Studio) / This is how most of pyRevit custom windows are created.
- Use raw quick and flex forms (https://revitpythonwrapper.readthedocs.io/en/latest/ui.html)

**Comment by eirannejad** [comment]
Closing since this is a question. Feel free to continue the discussion.

**Comment by sajusathish** [comment]
Hi Iam trying the first option,
I also noticed that py revit documentation has a chaper for wpf forms.
I copied the example file and run it in RPS and it returned an error saying "Cannot create unknown type 'Window'."
here is the code:

 ```
from pyrevit import forms
 layout = '<Window ShowInTaskbar="False" ResizeMode="NoResize" ' \
          'WindowStartupLocation="CenterScreen" ' \
          'HorizontalContentAlignment="Center">' \
          '</Window>'
 w = forms.WPFWindow(layout, literal_string=True)
 w.show()

```
what I am I missing here? 
also Is it true that if i replace the XAML code with my new formcode created with VS it works.
Thanks.
