### ISSUE TITLE
PyRevitLoader - Error Loading pyRevit

### ISSUE THREAD

**Issue by srschmidt1333** [eirannejad/pyRevit#632]
I am getting the following error when trying to open Revit 2019 after downloading the newest version of pyRevit. I have tried to uninstall-reinstall and restarting my computer. What do I need to do to get this to run properly?
![Screenshot (38)](https://user-images.githubusercontent.com/52050135/59875271-8d195500-935d-11e9-8607-5a5b2f5cdd3a.png)

**Comment by eirannejad** [comment]
What other admins do you have installed on Revit?

**Comment by eirannejad** [comment]
Any updates?

**Comment by two9seven** [comment]
This happening to me too. What do you mean by admins?

**Comment by anhkhoacg** [comment]
this happen to me as well. I has symantec antivirus in my machine is this the issue?

**Comment by eirannejad** [comment]
@two9seven Sorry fixed the comment. I mean other Addons. pyRevit seems to be conflicting with another add-on that is using MahApps.Metro for the GUI

@two9seven @anhkhoacg @srschmidt1333 I'd really appreciate if you can update to the [most recent pyRevit version](https://ein.sh/pyRevit/pyrevit/updates/2019/06/30/4624.html) and see if the new updates has solved the issue.

**Comment by anhkhoacg** [comment]
@eirannejad    Problem solved. I removed all previous versions and reinstalled ver 4.6.24 and it worked.

**Comment by two9seven** [comment]
I also solved the issue by using the CLI on the specific users profile. I normally deploy through a script and I noticed that no clones were attached for the users environment. Not sure why that is. It may have been installed by a different administrator. I did not need to upgrade.
