### ISSUE TITLE
No module named '_tkinter'

### ISSUE THREAD

**Issue by rick5087** [eirannejad/pyRevit#633]
I am using CPython to import other libraries. It is working for numpy and another one, but not for tkinter. 

Any idea why?

![image](https://user-images.githubusercontent.com/45624978/60015889-dda5f080-9684-11e9-8237-ed25f1817b64.png)
![image](https://user-images.githubusercontent.com/45624978/60015901-e991b280-9684-11e9-83c8-cd800e3137e9.png)

**Comment by eirannejad** [comment]
tkinter is not included with embedded cpython.
