### ISSUE TITLE
Import pyrevit

### ISSUE THREAD

**Issue by rick5087** [eirannejad/pyRevit#634]
is there a way to import pyrevit using the Cpython as well?

![image](https://user-images.githubusercontent.com/45624978/60019321-e18a4080-968d-11e9-8e87-3441418ec904.png)
![image](https://user-images.githubusercontent.com/45624978/60019345-ef3fc600-968d-11e9-8a69-d64e95627879.png)

**Comment by eirannejad** [comment]
The pyrevit modules is written for IronPython and is not compatible with cpython. At the moment pyRevit Cpython support is experimental unitll the pyRevit core has been modified to support both IronPython and cpython. It's primarily there to allow you to use cpython scientific modules like numpy and scipy.
