### ISSUE TITLE
pyRevit Not Fully Installed

### ISSUE THREAD

**Issue by Firefies** [eirannejad/pyRevit#635]
Hello,

I was told there was a new version of pyRevit out there.  I downloaded it and installed it.
However, there is no changes to what was already installed on my computer.  Supposedly,
there is a new match paint tool to the new version.  I did not see that new feature after the installation.
I am working on Revit 2019 at the moment.  Please, advise what I did wrong. 

My computer:
![image](https://user-images.githubusercontent.com/52181334/60057929-36808380-969b-11e9-8db5-b43dcb9ac5dd.png)

Co-worker's computer"
![image](https://user-images.githubusercontent.com/52181334/60057949-4b5d1700-969b-11e9-93c2-6cf7b880d0c0.png)

Thank you,

Steve

**Comment by eirannejad** [comment]
Huh. Alt+Click the button and it takes you to the bundle folder. Shwo me what is under `Match.splitpushbutton` and inside the `_layout` file

**Comment by Firefies** [comment]
Hello Ehsan,

Please, lead me to where the bundle folder.  I have clicked Alt+click button and nothing happened.


Thank you,

steve tran
[Pfeiffer - email signature LA]
www.pfeifferpartners.com<http://www.pfeifferpartners.com/>  stran@pfeifferpartners.com<mailto:stran@pfeifferpartners.com>
[https://c1.staticflickr.com/3/2387/1868745769_7b7944522e.jpg]

**Comment by eirannejad** [comment]
See under `extensions\pyRevitTools.extension\pyRevit.tab\Modify.panel\Match.splitpushbutton` inside installed pyRevit directory

**Comment by Firefies** [comment]
[cid:image004.jpg@01D52B6A.51535080]




Thank you,

steve tran
[Pfeiffer - email signature LA]
www.pfeifferpartners.com<http://www.pfeifferpartners.com/>  stran@pfeifferpartners.com<mailto:stran@pfeifferpartners.com>
[https://c1.staticflickr.com/3/2387/1868745769_7b7944522e.jpg]

**Comment by eirannejad** [comment]
@Firefies Did it get fixed? Please repond on the github website instead of email replies. Attached images don't show up when repolying from email and there is a lot of extra unnecessary content.

**Comment by Firefies** [comment]
Ehsan,

No.  It has not been resolved or fixed.
[cid:image001.png@01D52C0D.8DD7E130]
ST

**Comment by eirannejad** [comment]
I need more info. See my comments above.

**Comment by Firefies** [comment]
Hello Ehsan,
See attached:
![image](https://user-images.githubusercontent.com/52181334/60212917-41f8b980-9817-11e9-8f3b-978b1d0e3252.png)

**Comment by Firefies** [comment]
Is that what you were requesting for?

**Comment by Firefies** [comment]
![image](https://user-images.githubusercontent.com/52181334/60215977-b6cef200-981d-11e9-8900-75008d57e02d.png)

**Comment by eirannejad** [comment]
It says your pyRevit version is 4.6.8?!! Have you installed the new version yet?

**Comment by Firefies** [comment]
Yes.  I have unloaded the old version and loaded the new version.  Now, the app is not even work for Revit 2019.  The addin icon is not even there for the user to access it.  See attached snap shot.
![image](https://user-images.githubusercontent.com/52181334/60273328-c21c2f00-98aa-11e9-9147-ce89c012078b.png)

**Comment by Firefies** [comment]
Here is the latest version downloaded.  See snapshot.
![image](https://user-images.githubusercontent.com/52181334/60273538-32c34b80-98ab-11e9-9091-d08a6c7c187e.png)

**Comment by Firefies** [comment]
Have just reloaded it again and the latest version does not work with Revit 2019 or the new window 10 security updates.

**Comment by Firefies** [comment]
Please, advise.  Thank you!!

**Comment by eirannejad** [comment]
Open a command prompt and run `pyrevit env` and share the results please.

**Comment by Firefies** [comment]
See below.
![image](https://user-images.githubusercontent.com/52181334/60389892-5fc85780-9a7f-11e9-809c-146760c51e7b.png)

**Comment by Firefies** [comment]
Hello,

Any luck finding the resolution to pyRevit in Revit 2019, yet?  

Thank you,

**Comment by eirannejad** [comment]
Does this still happen with [the new version](https://ein.sh/pyRevit/pyrevit/updates/2019/06/30/4624.html)?

**Comment by Firefies** [comment]
Hello Eshan,

Yes.  The new version worked.


Thank you,

steve tran
