### ISSUE TITLE
PDF Sheet Size

### ISSUE THREAD

**Issue by sechanbask** [eirannejad/pyRevit#636]
Hello,

I'm always frustrated when I would like to print PDF with PDFCreator. With Revit, I have to selected the paper size for every sheet.

Is it possible to create PDF with the same paper size as the sheet title blocks ?

I know addons exists, but I haven't try it:

https://apps.autodesk.com/RVT/en/Detail/Index?id=1103644254488841539&appLang=en&os=Win64
https://apps.autodesk.com/RVT/en/Detail/Index?id=6577851751871133246&appLang=en&os=Win64

You can see here a great GUI : 
![original_930824ea-16a1-4134-ae41-e48a2ed8a6a6_](https://user-images.githubusercontent.com/4959672/60082759-b4449d80-9734-11e9-8113-6092e2f469d8.png)

**Comment by eirannejad** [comment]
I'm not following. Revit uses the sheet size defined in its native print window

![2019-06-25 14_34_54-Print Setup](https://user-images.githubusercontent.com/8197916/60135383-6a6caf00-9756-11e9-9af2-5cfe22d27d9f.png)

**Comment by eirannejad** [comment]
Closing since this is a question/request and not an issue. Keeping the conversation open.

**Comment by sechanbask** [comment]
Hello,

You can print PDF with the good size one by one. But on a big project I have 10 sheets size 914x1200, 15 sheets size 914x1350, 2 sheets size 914x2000. So imagine the time I waste to print some PDF on second floor 914x1200 zone 2 914x2500 zone 2, third floor 914x1350. And time I waste to rename every file.


We can not publish it in one run.

There is several workaround with dynamo script  but I never make it working. You can read this thread to understand the usefullness.


https://forum.dynamobim.com/t/batch-pdf-with-multiple-sheet-sizes/11629/14

http://www.bimrvt.cz/perfect-tools-plugin/print-pdf-custom-paper-revit?utm_source=autodesk&utm_medium=forumidea&utm_campaign=multipleprinting

https://forums.autodesk.com/t5/revit-ideas/printing-multiple-sheets-with-different-sizes-to-pdf/idi-p/7428289

https://forum.dynamobim.com/t/customized-pdf-creation-using-ghostscript-dynamo-and-python/11736

**Comment by leonardorudolfocardoso** [comment]
Same issue here.

**Comment by sechanbask** [comment]
Do you think is possible to developp it ?

**Comment by eirannejad** [comment]
How's this?

Got it to work in single page print mode with variable "Print Settings" per sheet. Automatically picks the appropriate print settings based on the sheet title block size. Needs fine tuning tho but it works.

![2019-10-15_17-43-45](https://user-images.githubusercontent.com/8197916/66879591-a0d37180-ef73-11e9-9f34-a7dbcb6e1579.gif)

**Comment by dsellam** [comment]
Exactly the same workaround that I use with Dynamo. Great !

**Comment by sechanbask** [comment]
It is wonderful !! When do you think It will be available ?

Does it works with pdfcreator ? I d'rather keep my virtual print pdfcreator.

Is it possible to name PDF from shared parameters I have filled into the sheet, during printing ?

How can my compagny donate to help the project ?

**Comment by Robbo1234** [comment]
> How can my compagny donate to help the project ?


Refer to 
https://www.patreon.com/pyrevit
https://www.notion.so/Support-on-Patreon-cdf92ba547154f7a85d32b526dc5e59b

This doesn't need much explaining. Some say money doesn't buy happiness. Some believe it buys crazy-a** happiness. You decide.

"If pyRevit has helped you save money, then consider your financial support an investment towards your future savings. As the pyRevit project gets better, hopefully you will save more, give back more, help the project get even better, save even more, give back even more, ... you get the idea.

- There is no required monthly minimum for supported contributions. The $ number shown on the linked support platform(s), are the current monthly total of all $ amounts provided by active supporters 
- There are no supporter levels, and no supported-specific content or tools. You are all equal to us and will get the same "

**Comment by Robbo1234** [comment]
> Is it possible to name PDF from shared parameters I have filled into the sheet, during printing ?

This PDF Rename using parameter data functionality is vital in projects nowadays, and would greatly assist projects.

**Comment by sechanbask** [comment]
Hello,

Can this thread be moved to "pull requests" as open ?
