### ISSUE TITLE
WPF example file error

### ISSUE THREAD

**Issue by sajusathish** [eirannejad/pyRevit#638]
Hi I am new to WPF and wanted to explore the example file in the pyrevit documentation.
I have just copied the script that uses content and literal_string to create forms and I received the following error, am I missing something?

![image](https://user-images.githubusercontent.com/39821809/60266518-d17c9600-9905-11e9-950f-7fa2e8363959.png)

thanks.

**Comment by eirannejad** [comment]
Watch a tutorial on WPF first. WPF is similar to XML and the namespaces must be defined otherwise the processor can not find the types. Your script is failing because the namespace that contains the type `Window` is not provided. See below:

```xaml
<Window
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    ShowInTaskbar="False" ResizeMode="NoResize"
    WindowStartupLocation="CenterScreen"
    HorizontalContentAlignment="Center">
</Window>
```
