### ISSUE TITLE
pyRevit fails on uninstall

### ISSUE THREAD

**Issue by dangrmous** [eirannejad/pyRevit#639]
I am following up on filing this.  My husband works as a software engineer so I am borrowing his GitHub account to try to resolve the uninstall issues.  I noticed that you released  https://ein.sh/pyRevit/pyrevit/updates/2019/05/27/4623.html  which is 4.6.23 version after you released 4.7.0-beta.  
I believe I installed the 4.7.0-BETA version. 

Attaching my Log file for your reference.  I work at LRS architects, our IT department won't help with 3rd party app issues.  I followed all the advice in your YouTube video and still get the error. 
I hope you can help me.  These tools save me so much time. 

Thank you ! Please reply to the email address below
 - Michelle
gunger.mneidiger@gmail.com

[MDN LOG MSI8497.tmp.LOG](https://github.com/eirannejad/pyRevit/files/3337107/MDN.LOG.MSI8497.tmp.LOG)

geoff unger michelle neidiger   
1 week ago
Hi - I followed your advice and still get the error pyrevit is installed and so can not  re-install Pyrevit.
1

pyRevit
1 day ago
File an issue on the github issue tracke please

**Comment by eirannejad** [comment]
Hey/. Give me a little more detail. Are you trying to uninstall pyRevit and it fails?
