### ISSUE TITLE
shutdown.py to run when Revit is shutting down

### ISSUE THREAD

**Issue by bxiaww** [eirannejad/pyRevit#640]
'startup.py' is already supported in pyrevit, which can be executed while Revit is opening. I am wonder if there is a 'shutdown.py' to do the same thing when Revit is shutting down?

**Comment by eirannejad** [comment]
Not at the moment. But great suggestion.

**Comment by eirannejad** [comment]
The new pyRevit hooks system provides a handler for `app-closing` event. Try the 4.7-beta2. See the release notes for pyRevit hooks
