### ISSUE TITLE
Context for groups

### ISSUE THREAD

**Issue by sajusathish** [eirannejad/pyRevit#645]
I have created a filter tool that can filter elements by types after filtering by category and it works good but Its no longer useful when I editing a group 

I couldn't find any __context__ option  for groups  
Is this a feature to be added in future or its already there some where and I am missing it?

**Comment by eirannejad** [comment]
I'm not user when Autodesk is planning to provide group editing context. At the moment you can not edit groups from API. The onyl time that a group can ve edited is when there is only one instance of the group in the model.

You can still read and select the groups members though
