### ISSUE TITLE
Pyrevit not mapping on other Users Computers from Successful Cloned Master

### ISSUE THREAD

**Issue by Hazen12345** [eirannejad/pyRevit#647]
**Describe the bug**
Pulled CLI 13.0
Pulled Cloned Master 4.6.24 from GitKraken Master
Works on my PC
4.6.23 is still showing all Other PC's

1. Manually installed CLI 13.0 on other Computers'
2. Re Mapped Clone 
3. Re mapped engine 277 and tried 279
4.Re Started other Users PC and started Revit still showing 4.6.23 not latest update
**Expected behavior**
Should show Pyrevit Version 4.6.24 on All Commuters.

**Desktop (please complete the following information):**
 - OS: Windows 10 - pyRevit Version 4.6.24

**Comment by eirannejad** [comment]
Share your configuration script please. I need to see if you have correctly cloned and attached the new version

**Comment by Hazen12345** [comment]
Ok how do I do the Configuration Script

I mapped as usual, but have to sometimes go to each computer to manually
reattach Pyrevit to the Master, but works fine when I pull from GitKraken why doesn't the master Pull and CLI pick up automatically?

**Comment by Hazen12345** [comment]
If there was an error message I would post it, the clone was working on 4.6.23 on my computer, but I have to manually install the knew CLII then go to each computer and attach the pyrevit attach master 277 –-installed or 279 on all the other computers!

Here is the Mapped clone when I try to remap I am told already mapped
Pyrevit clones add master “K:\000-CAD-Folder\Revit\ADG Pyrevit II\pyRevit” 

Thais is the clone I made on our Server!

**Comment by Hazen12345** [comment]
Ok Re-mapped Pyrevit clones add master “K:\000-CAD-Folder\Revit\ADG Pyrevit II\pyRevit”
Looked at the Clone and no sign of updating from the Pulled Master 4.6.24 yet its gives me the merged
Successfully. When I open Pyrevit about its showing 4.6.24 something going on in GitKraken  the master is not updating when I pull is there a setting I am don't have correct when pulling updates? 

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS U:\> pyrevit env
==> Registered Clones (full git repos)
master | Branch: "master" | Version: "4.6.23:e0c0d06" | Path: "K:\000-CAD-Folder\Revit\ADG Pyrevit II\pyRevit"
==> Registered Clones (deployed from archive/image)
==> Attachments
master | Product: "Autodesk Revit 2018.3.2" | Engine: 0 | Path: "K:\000-CAD-Folder\Revit\ADG Pyrevit II\pyRevit" | Manifest: "C:\Users\livij001\AppData\Roaming\Autodesk\Revit\Addins\2018\pyRevit.addin"
master | Product: "Autodesk Revit 2017 First Customer Ship" | Engine: 0 | Path: "K:\000-CAD-Folder\Revit\ADG Pyrevit II\pyRevit" | Manifest: "C:\Users\livij001\AppData\Roaming\Autodesk\Revit\Addins\2017\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\livij001\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2018.3.2 | Version: 18.3.2.7 | Build: 20181011_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018"
Autodesk Revit 2017 First Customer Ship | Version: 17.0.416.0 | Build: 20160225_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> Running Revit Instances
PID: 13792 | Autodesk Revit 2017 First Customer Ship | Version: 17.0.416.0 | Build: 20160225_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> User Environment
Microsoft Windows 10 [Version 10.0.17763]
Executing User: ADGI\livij001
Active User: ADGI\livij001
Adming Access: No
%APPDATA%: "C:\Users\livij001\AppData\Roaming"
Latest Installed .Net Framework: 4.7.2
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.X
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.13.0.0
PS U:\>

**Comment by eirannejad** [comment]
Doesn't seem like that pyRevit is attached correctly. `Engine: 0` should say `Engine: 277` by default.

Run `pyrevit attach master 277 --installed` and get the `pyrevit env` report again.

**Comment by Hazen12345** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS U:\> pyrevit attach master 277 --installed
Error: Can not find clone "master"
Run with "--debug" option to see debug messages
PS U:\> pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
Unknown | Product: "Autodesk Revit 2018.3.2" | Manifest: "C:\Users\livij001\AppData\Roaming\Autodesk\Revit\Addins\2018\pyRevit.addin"
Unknown | Product: "Autodesk Revit 2017 First Customer Ship" | Manifest: "C:\Users\livij001\AppData\Roaming\Autodesk\Revit\Addins\2017\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\livij001\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2018.3.2 | Version: 18.3.2.7 | Build: 20181011_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018"
Autodesk Revit 2017 First Customer Ship | Version: 17.0.416.0 | Build: 20160225_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> Running Revit Instances
PID: 13400 | Autodesk Revit 2017 First Customer Ship | Version: 17.0.416.0 | Build: 20160225_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> User Environment
Microsoft Windows 10 [Version 10.0.17763]
Executing User: ADGI\livij001
Active User: ADGI\livij001
Adming Access: No
%APPDATA%: "C:\Users\livij001\AppData\Roaming"
Latest Installed .Net Framework: 4.7.2
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.X
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.13.0.0
PS U:\>

**Comment by eirannejad** [comment]
@Hazen12345 What happened to your `master` clone? If it is still on your machine, add it first using `pyrevit clones add master <path>`

**Comment by Hazen12345** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS U:\> Pyrevit clones add master "K:\000-CAD-Folder\Revit\ADG Pyrevit II\pyRevit"
PS U:\> pyrevit attach master 277 --installed
PS U:\> pyrevit env
==> Registered Clones (full git repos)
master | Branch: "master" | Version: "4.6.23:e0c0d06" | Path: "K:\000-CAD-Folder\Revit\ADG Pyrevit II\pyRevit"
==> Registered Clones (deployed from archive/image)
==> Attachments
master | Product: "Autodesk Revit 2018.3.2" | Engine: 277 | Path: "K:\000-CAD-Folder\Revit\ADG Pyrevit II\pyRevit" | Manifest: "C:\Users\livij001\AppData\Roaming\Autodesk\Revit\Addins\2018\pyRevit.addin"
master | Product: "Autodesk Revit 2017 First Customer Ship" | Engine: 277 | Path: "K:\000-CAD-Folder\Revit\ADG Pyrevit II\pyRevit" | Manifest: "C:\Users\livij001\AppData\Roaming\Autodesk\Revit\Addins\2017\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\livij001\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2018.3.2 | Version: 18.3.2.7 | Build: 20181011_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018"
Autodesk Revit 2017 First Customer Ship | Version: 17.0.416.0 | Build: 20160225_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> Running Revit Instances
PID: 13400 | Autodesk Revit 2017 First Customer Ship | Version: 17.0.416.0 | Build: 20160225_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> User Environment
Microsoft Windows 10 [Version 10.0.17763]
Executing User: ADGI\livij001
Active User: ADGI\livij001
Adming Access: No
%APPDATA%: "C:\Users\livij001\AppData\Roaming"
Latest Installed .Net Framework: 4.7.2
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.X
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.13.0.0
PS U:\>

**Comment by Hazen12345** [comment]
but I am showing 4.6.24 on my machine

**Comment by eirannejad** [comment]
@Hazen12345 So does it work now? Seems like your master is `Version: "4.6.23:e0c0d06"`

**Comment by Hazen12345** [comment]
No that's the problem when I pull from the Master its telling Pull Successful no merge Necessary, but doesn't update to the Clone yet Pyrevit on my Machine 4.6.24, but on other Machines are still 4.6.23 and looking at the clone folders are not updated is there a setting in GitKraken that's wrong or I can re-clone
and map all the computers I just tried again no folders are updated on Network !

**Comment by eirannejad** [comment]
@Hazen12345 Dude I have a hard time understanding what you are saying. Use proper sentences that ends with a period please. Your comment is just a large blob of text that needs deciphering IMHO...

What I'm gathering is:
- You have cloned the complete pyRevit git repo
- You are running `git pull` and it is telling you that the repo is up-to-date?
- You have other clones on other machines and somehow expect them to be updated automatically?

**Comment by Hazen12345** [comment]
Yes Correct
Yes Correct
No the other Machines are mapped to the same clone on the Network.
I update by re-mapping each computer, the same procedure as I did earlier after I update the latest CLI on each computer!

**Comment by eirannejad** [comment]
Then all machines should load from the same clone. Send me a `pyrevit env` log from one of these machines that is not working please

**Comment by Hazen12345** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS Microsoft.PowerShell.Core\FileSystem::\\ADGSRV3\homedrs\groba001> pyrevit env
==> Registered Clones (full git repos)
master | Branch: "master" | Version: "4.6.23:e0c0d06" | Path: "K:\000-CAD-Folder\Revit\ADG Pyrevit II\pyRevit"
==> Registered Clones (deployed from archive/image)
==> Attachments
master | Product: "Autodesk Revit 2018.3.2" | Engine: 279 | Path: "K:\000-CAD-Folder\Revit\ADG Pyrevit II\pyRevit" | Manifest: "C:\Users\groba001\AppData\Roaming\Autodesk\Revit\Addins\2018\pyRevit.addin"
master | Product: "Autodesk Revit 2017 First Customer Ship" | Engine: 279 | Path: "K:\000-CAD-Folder\Revit\ADG Pyrevit II\pyRevit" | Manifest: "C:\Users\groba001\AppData\Roaming\Autodesk\Revit\Addins\2017\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\groba001\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2018.3.2 | Version: 18.3.2.7 | Build: 20181011_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018"
Autodesk Revit 2017 First Customer Ship | Version: 17.0.416.0 | Build: 20160225_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> Running Revit Instances
PID: 9168 | Autodesk Revit 2018.3.2 | Version: 18.3.2.7 | Build: 20181011_1500(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2018"
==> User Environment
Microsoft Windows 10 [Version 10.0.17134]
Executing User: ADGI\groba001
Active User: ADGI\groba001
Adming Access: No
%APPDATA%: "C:\Users\groba001\AppData\Roaming"
Latest Installed .Net Framework: 4.7.2
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.13.0.0
PS Microsoft.PowerShell.Core\FileSystem::\\ADGSRV3\homedrs\groba001>

**Comment by Hazen12345** [comment]
I also tried Engine 277 on his computer!

**Comment by Hazen12345** [comment]
Think I need to re clone

**Comment by Hazen12345** [comment]
ok re cloned its working now
