### ISSUE TITLE
Does _layout file not support Chinese?

### ISSUE THREAD

**Issue by lcwewei** [eirannejad/pyRevit#649]
I want to use Chinese in the _layout file, but the Chinese part cannot be displayed in the menu

**Comment by eirannejad** [comment]
Would you mind sending an example? Is the tool name in chinese as well?

**Comment by lcwewei** [comment]
Thank you very much for your reply. This is one of my test cases. The _layout file contains Chinese layout.The menu can't appear in revit, it can appear in English.

**Comment by lcwewei** [comment]
[建筑规划.panel.zip](https://github.com/eirannejad/pyRevit/files/3395920/panel.zip)

**Comment by eirannejad** [comment]
Fixed and will be issued with 4.6.25
Save your `_layout` file in UTF-8 and it will work in the updated version.

![2019-07-24 12_20_22-Autodesk Revit 2019 2 -  Project1 - Floor Plan_ Level 1](https://user-images.githubusercontent.com/8197916/61822166-d30a8280-ae0d-11e9-8477-7611191b55c1.png)

`_layout` file contents
```text
管道翻弯
测试
```

**Comment by lcwewei** [comment]
Dear Ehsan iran-nejad:
Thank you very much for solving this problem. I am looking forward to your new version
