### ISSUE TITLE
Modeless Workspace Palette

### ISSUE THREAD

**Issue by tillbaum** [eirannejad/pyRevit#650]
There has been a blog post by Jeremy Tammik on how Launching a textnote command with  a certain type already selected can be achieved.

Having some command buttons with the most used line stiles, text note types, 
dimension types  and filled region types on an external modeless window would be 
useful.

**Comment by eirannejad** [comment]
Makes sense. Something like a palette with patterns, line, text, dimension types and other 2D components.

**Comment by tillbaum** [comment]
Ehsan, I have finished this now. I created palettes for TextNotes, LineStyles, () 
Can I add this to the pyrevit script library? Also can I add my extension to pyrevit?

**Comment by eirannejad** [comment]
Of course. Check out https://www.notion.so/pyrevitlabs/Share-Your-Extensions-48ff84d4eae846f4aa9567fca32ff4fe

**Comment by eirannejad** [comment]
Waiting for PR. Please reference this issue when a PR is available
