### ISSUE TITLE
Revit 2020 Loading Error

### ISSUE THREAD

**Issue by Archithead** [eirannejad/pyRevit#651]
I'm having an issue where pyRevit seems not to be loading correctly on my machine. I'm currently running Revit 20.0.1.2 and just downloaded pyRevit 4.6.24 this morning and attempted to install. This error goes way beyond my programming intelligence. Any help would be appreciated. Thank you.

![pyRevit Error P1](https://user-images.githubusercontent.com/33132396/61379403-77705000-a875-11e9-8ebf-b56080ec50cc.jpg)
![pyRevit Error P2](https://user-images.githubusercontent.com/33132396/61379405-77705000-a875-11e9-97e2-1b45f05498ff.jpg)

**Comment by eirannejad** [comment]
Would you please confirm the dll `pyRevitLabs.MahAppsMetro.dll` exists inside the installed pyRevit? Default installed location is `%APPDATA%/pyRevit-Master/bin`

**Comment by Archithead** [comment]
Thank you for the quick reply. It appears it does.

[image: image.png]

**Comment by Archithead** [comment]
Hi Ehsan,

Any thoughts on what might be happening here? I'd love to get this up and running. 

Best,
Michael

**Comment by eirannejad** [comment]
@Archithead Not sure to be honest. Please open a command prompt and run `pyrevit env` and share the report here.

**Comment by Archithead** [comment]
Bummer. Here's the report.

C:\Users\micha>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.6.24" | Path: "C:\Users\micha\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2020.0.1" | Engine: 277 | Path: "C:\Users\micha\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\micha\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
master | Product: "Autodesk Revit 2018.3.1" | Engine: 277 | Path: "C:\Users\micha\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\micha\AppData\Roaming\Autodesk\Revit\Addins\2018\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\micha\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2020.0.1 | Version: 20.0.1.2 | Build: 20190412_1200(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
Autodesk Revit 2018.3.1 | Version: 18.3.1.2 | Build: 20180423_1000(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018"
==> Running Revit Instances
PID: 11088 | Autodesk Revit 2020.0.1 | Version: 20.0.1.2 | Build: 20190412_1200(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2020"
==> User Environment
Microsoft Windows 10 [Version 10.0.17134]
Executing User: BIANCHI-001\micha
Active User: BIANCHI-001\micha
Adming Access: No
%APPDATA%: "C:\Users\micha\AppData\Roaming"
Latest Installed .Net Framework: 4.7.2
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.13.0.0

C:\Users\micha>

**Comment by eirannejad** [comment]
Does it run correctly under 2018?

Close your Revits, open a command prompt and run `pyrevit caches clear 2020`
Then launch 2020 again and see if it works

**Comment by Archithead** [comment]
It does not run correctly on 2018 either. I'm all up to date on both versions. Clearing the cache didn't have an effect. I'll try to uninstall and reinstall and see what happens. Perplexing...

**Comment by Archithead** [comment]
Hi Ehsan,

It appears I had to beat it into submission and all appears to be working. Rooted out all of the old files and registry entries. Persistent little buggers. I still have 4.6.5 stuck in my control panel uninstaller, but it's not uninstalling. Not sure. Not really that important, frankly. Just annoying for an ocd person like me. Thanks again for your prompt responses and for creating such a fab applicaiton! 

Cheers!
Michael

**Comment by eirannejad** [comment]
@Archithead Thanks a lot for the update. I'm working on a `pyrevit doctor` command option for the CLI to specifically fix some of these registry issues.
