### ISSUE TITLE
Packages and Tags Extension Install

### ISSUE THREAD

**Issue by lnuqul** [eirannejad/pyRevit#652]
I just installed pyRevit and enables the Packages and Tags install, but I can't figure out how to configure Tags tools or find the Tags Settings buttons per the error in the image.
Any help?

![Annotation 2019-07-17 143004](https://user-images.githubusercontent.com/53020610/61413060-64727580-a89f-11e9-8f83-286f78abb6b4.png)

**Comment by eirannejad** [comment]
See here https://ein.sh/pyRevit/pyrevit/updates/2018/11/04/pkgsandtags.html
