### ISSUE TITLE
error loading  pyrevit

### ISSUE THREAD

**Issue by invinsableman** [eirannejad/pyRevit#653]
I cannot load Pyrevit after I download and install it. the location I installed was not the default :C![TIM图片20190718233553](https://user-images.githubusercontent.com/49676772/61471130-cc66b000-a9b4-11e9-9eb8-9239b5a84d53.png)
the system error says that An attempt was made to access an element whose type was incompatible with the array.
,

**Comment by invinsableman** [comment]
Anybody ever met the same questions?

**Comment by eirannejad** [comment]
What other addons are you using? Rhino.Inside?

**Comment by invinsableman** [comment]
you mean Rhinoceros? No, I 've got many local add-ins for structural analysis and construction drawing, and also Fuzor, Twinmotion, and some addins for Advancesteel,Tekla.I don't know which one caused this problem,  and I don't know what can I do to solve the matters like this :The type was incompatible with the array, maybe search in the file in which my taskdialog shows?

**Comment by eirannejad** [comment]
Try disabling all other addons and only running pyRevit to see if this error still happens. Most probably this is a conflict with an existing addon

**Comment by invinsableman** [comment]
thanks , let me take a try

**Comment by restipangan** [comment]
hi sir, i have the same issue...is this fixed?

**Comment by eirannejad** [comment]
No. I can not replicate the issue on my side. Try the 4.7beta 2 and see if the error still occurs

**Comment by invinsableman** [comment]
ok, I will take a try.

**Comment by eirannejad** [comment]
No more info received. Closing for now.
