### ISSUE TITLE
Modeless Palette showing all filters applied to active view,  

### ISSUE THREAD

**Issue by tillbaum** [eirannejad/pyRevit#655]
A modeless palette showing filters (as checkboxes objects) applied to the active view would be a nice tool. 
Also some buttons for:
- updating the modeless dialog window to the current view (in case one switches the view)
- adding/ deleting filters 
- moving them up/down. 

A tool like this would save the process of pushing vv/vg-button, clicking the filter tab in the visibility Dlg, and doing the changes to filters there.  But maybe this is too much work.

**Comment by eirannejad** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/298

Closing this here.
