### ISSUE TITLE
Printing forces a reload keynotes message

### ISSUE THREAD

**Issue by need4mospd** [eirannejad/pyRevit#657]
![pyRevitKeynotes](https://user-images.githubusercontent.com/46454815/62171604-250f4480-b2f5-11e9-910f-588cc44cb1b6.png)

If you've edited the notes with the pyRevit Manage Keynotes tool, this message will pop up every time you print, for every sheet. Batch print 100 sheets, see 100 messages. Of course, reloading the notes as the message indicates will fix it, but it would be nice if the user didn't have to reload manually.

**Comment by eirannejad** [comment]
This happens even if you edit the keynotes manually. Standard Revit behaviour
