### ISSUE TITLE
python loader without UI

### ISSUE THREAD

**Issue by jhoogeboom** [eirannejad/pyRevit#658]
**Is your feature request related to a problem? Please describe.**
The design automation api in forge does not support the UI module of Revit. https://forge.autodesk.com/en/docs/design-automation/v3/tutorials/revit/step1-convert-addin/
I'm interested in exploring using the pyRevitLoader to execute a python script in that environment.

**Describe the solution you'd like**
A loader that does not use the UI, but only executes a script on startup so I can use it in the Forge environment.

**Describe alternatives you've considered**
Not using python in the Forge context haha. Otherwise, someone else also made just a loader a while back (https://github.com/cridder/revitpythonloader). But yours seem much better up to date with engine versions.

**Additional context**

**Comment by eirannejad** [comment]
Oh this is very interesting. Let me collect more info on how the design automation API works and I'll get back with you.

**Comment by jhoogeboom** [comment]
very cool! Let me know if I can help with anything. Jeremy Tammik has been posting some useful bits around the approach of an add-in that can be used both in Revit directly and forge (https://thebuildingcoder.typepad.com/blog/2019/02/preparing-a-revit-add-in-for-design-automation.html) and also the folks from Autodesk have been building some tooling around this (https://github.com/Autodesk-Forge/design.automation-csharp-revit.local.debug.tool) more on the C# side of things.

**Comment by mlimotte** [comment]
I would love to see this functionality because I have a similar need. 
Is there any update?
