### ISSUE TITLE
Crash on Make Pattern tool

### ISSUE THREAD

**Issue by eirannejad** [eirannejad/pyRevit#664]
Reported by email:

Crash on **Make Pattern** tool

![Ошибка созд штриховки](https://user-images.githubusercontent.com/8197916/62674832-0d6d3700-b959-11e9-9052-f111a79d7b6b.jpg)

![Окно создания штрих](https://user-images.githubusercontent.com/8197916/62674834-10682780-b959-11e9-971b-5cf966b07f5a.jpg)

**Comment by mwo-aec** [comment]
@eirannejad one of my folks are having this issue where Revit crashed when she tried to create a pattern - trying to find out more on what she did before it crashed.
At this point, she is trying to make a pattern however the "Create Pattern" box is greyed out now. Is there any log files she can collect.
![pyRevit Make Pattern](https://user-images.githubusercontent.com/54068359/62943307-73830f80-bdda-11e9-9617-03bd6b80b951.jpg)

**Comment by eirannejad** [comment]
@mwo-aec You need to select the lines before running the command. See the video (F1 while hovering over the button)

**Comment by mwo-aec** [comment]
Thanks for the response,
The process followed is:

  1.  Select lines for hatch
  2.  Activate command; input required names & settings
  3.  Select “Create Pattern”
     *   First time it crashed
     *   Every time there after command is greyed out.


Regards,

MACHIEL ODENDAAL | Team Lead: Arch | T: 010 595 2500 | www.modena-aec.co.za<http://www.modena-aec.co.za/> | disclaimer<http://www.modena.co.za/disclaimer/>

**Comment by eirannejad** [comment]
@mwo-aec I need more context. Send me sample model and pattern that is causing the crash. It works in my tests but there is something about your context that is making it crash and I need to be able to replicate that.

**Comment by mwo-aec** [comment]
Hi Ehsan,

The hatch patterns didn’t want to create in plan views, however when my client went and created the hatch in a legend view it worked fine.
For now, they are happy and I don’t think we will get a file at the time it was giving the issues.

Will keep an out on this to see if it happens again. Thanks.


Regards,

MACHIEL ODENDAAL | Team Lead: Arch | T: 010 595 2500 | www.modena-aec.co.za<http://www.modena-aec.co.za/> | disclaimer<http://www.modena.co.za/disclaimer/>
