### ISSUE TITLE
Copy Sheet does not position View Titles to match source sheet

### ISSUE THREAD

**Issue by jrostar** [eirannejad/pyRevit#666]
**Is your feature request related to a problem? Please describe.**
When the copy sheet tool is used, the views are placed on the sheet but the View Titles are not positioned in the same way as they were positioned in the source sheet

**Describe the solution you'd like**
I would like the View Titles to be positioned to match the source

**Comment by eirannejad** [comment]
@jrostar Revit API has not exposed functionality to adjust View Title bounds and position.
