### ISSUE TITLE
Show extensions from "sources" in Extensions window

### ISSUE THREAD

**Issue by melnikovalex** [eirannejad/pyRevit#668]
**Is your feature request related to a problem? Please describe.**
Hey Ehsan. 

I've just noticed that extensions, which are listed in custom `extensions.json` file which I'd set as `[environment] source=` option in INI aren't visible in Extensions UI in Revit.

**Describe the solution you'd like**
It would be nice to see the list of these extra-extensions in this UI. 

Especially useful for organisations. In cases when certain extension shouldn't be installed for all users, so user could choose among extensions accessible in the organisatiobn

**Comment by eirannejad** [comment]
This makes sense.

**Comment by jmcouffin** [comment]
**Closing**
Issue older than a year.
Thanks for pointing it out.
If you feel it is still relevant, feel free to reopen the issue
