### ISSUE TITLE
PyRevit Manage Keynotes tool shows index was outside bounds

### ISSUE THREAD

**Issue by bihanw** [eirannejad/pyRevit#669]
**Describe the bug**
Replace these lines with your description. Be as specific as possible and list steps to reproduce the issue. If you have any suggestions for the solution please list that as well.

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/48359995/63040409-04b1bf00-be8b-11e9-9073-9576c1e6b757.png)

**Desktop (please complete the following information):**
 - pyRevit Version [e.g. 22]
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

**Additional context**

**Comment by Hazen12345** [comment]
or pyrevit attach master 279 --installed sometimes 277 doesn't work and 279 does!

**Comment by eirannejad** [comment]
No context or info on how to reproduce the error

**Comment by garuarqtec** [comment]
Hello Eirannejad,
We are having the same problem here.
OS: Windows 7
PyRevit:4.7.4
![Capture](https://user-images.githubusercontent.com/46724658/71265546-5341ff00-233e-11ea-8fcf-53218c89f74d.JPG)

**Comment by garuarqtec** [comment]
Keynote file attached for your perusal.

Many thanks

[379_RevitKeynotes_KCA_191311.txt](https://github.com/eirannejad/pyRevit/files/3988976/379_RevitKeynotes_KCA_191311.txt)

**Comment by garuarqtec** [comment]
Hello eirannejad ,
I have found that if I remove the header and convert it again it carry on working fine.
