### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by che-30** [eirannejad/pyRevit#679]
ERROR: [pyrevit.loader.uimaker] Error creating stack | Can not create stack of 4. Stack can only have 2 or 3 items. 

Traceback: 
 File "C:\Users\cherniaev\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\loader\uimaker.py", line 435, in _produce_ui_stacks 
 parent_ui_panel.close_stack()

**Comment by eirannejad** [comment]
You have 4 bundles in a .stack3 or .stack2 it seems

**Comment by che-30** [comment]
I'm sorry, I didn’t understand what kind of bandles it was

**Comment by eirannejad** [comment]
`.stack3` can only have 3 buttons and `.stack2` can have 2 only. Seems like you have more than 3 buttons in your stack

**Comment by che-30** [comment]
sorry, still didn’t understand :(
at least a picture...maybe the picture will help?

**Comment by sergeykahn** [comment]
I'm getting this same error, and the above explanation doesn't make sense to me. The interesting thing is that I have several computers running the same version of pyRevit and same extensions, but only one of them is getting this error. How can this be resolved? I've tried uninstalling and reinstalling pyRevit but that hasn't worked. Running the latest version.

**Comment by sanzoghenzo** [comment]
Hi @sergeykahn , please open a new issue and provide all the info requested, from your message we have absolutely no info to work on. Pyrevit am revit versions?
