### ISSUE TITLE
Error Conerting Wall-base Revit Family into a Face-base Revit Family 

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#681]
**Is your feature request related to a problem? Please describe.**
I got this error when trying to convert a Wall-base Revit Family into a Face-base Revit Family using pyRevit Convert Family to Face Host Based.

**Describe the solution you'd like**
To convert a Wall-base family into a Face-base Family.

**Additional context**
Refer to screenshot:
![image](https://user-images.githubusercontent.com/8776947/64186356-9a2ae800-ce66-11e9-99e8-a4b4bf856da2.png)

**Comment by eirannejad** [comment]
Added check into the tool

![2019-11-21 11_38_37-Convert Family To Face Host Based](https://user-images.githubusercontent.com/8197916/69371041-eb6f9a00-0c53-11ea-9f9b-09bbf639968e.png)
