### ISSUE TITLE
Issue with naming of PDFs

### ISSUE THREAD

**Issue by trebhahn** [eirannejad/pyRevit#688]
If I use Revit's Print function, I get a different output name than if I use PyRevit Print Ordered Sheet Index. I use the same PDF printer for both.

Output from Revit Print Function:
FP-001 - FIRE PROTECTION - SITE PLAN, LEGENDS, SYMBOLS, ABBREVIATIONS, INDEX.PDF

Output from PyRevit Print Ordered Sheet Index:
FP001  FIRE PROTECTION  SITE PLAN LEGENDS SYMBOLS ABBREVIATIONS INDEX.PDF

I dont see anywhere that would be causing this. Does PyRevit strip out punctuation? (Hyphens and commas specifically?)

Thanks for any advice. I am completely lost when it comes to programming, so not sure if this is a bug or just the way it works.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise - 1809
 - pyRevit Version 4.6.23
 - pyRevit Environment: 

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.6.23" | Path: "C:\Users\trebhahn\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2019.2.1" | Engine: 277 | Path: "C:\Users\trebhahn\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\trebhahn\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
master | Product: "Autodesk Revit 2018.3.3 Security Fix" | Engine: 277 | Path: "C:\Users\trebhahn\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\trebhahn\AppData\Roaming\Autodesk\Revit\Addins\2018\pyRevit.addin"
master | Product: "Autodesk Revit 2017.2.5 Security Fix" | Engine: 277 | Path: "C:\Users\trebhahn\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\trebhahn\AppData\Roaming\Autodesk\Revit\Addins\2017\pyRevit.addin"
master | Product: "Revit 2016" | Engine: 277 | Path: "C:\Users\trebhahn\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\trebhahn\AppData\Roaming\Autodesk\Revit\Addins\2016\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\trebhahn\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2019.2.1 | Version: 19.2.10.7 | Build: 20190225_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
Autodesk Revit 2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018"
Autodesk Revit 2017.2.5 Security Fix | Version: 17.0.1169.0 | Build: 20190508_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
Revit 2016 | Version: 16.0.1218.0 | Build: 20190508_0715(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016"
==> Running Revit Instances
PID: 15892 | Autodesk Revit 2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2018"
==> User Environment
Microsoft Windows 10 [Version 10.0.17763]
Executing User: AEIENG\trebhahn
Active User: AEIENG\trebhahn
Adming Access: No
%APPDATA%: "C:\Users\trebhahn\AppData\Roaming"
Latest Installed .Net Framework: 4.7.2
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.11.0.0
```

**Comment by eprunty** [comment]
Would it be possible to configure the output filenames based on Revit parameters / a combination of values ? 

This would be very helpful as we typically have to use different conventions on different projects:
Sheet Number + ".pdf"
Sheet Number + "_" +  Sheet Name + ".pdf"
Sheet Number + "_" +  Current Revision + ".pdf"
Sheet Number + "_" + Sheet Name+ "-" +  Current Revision + "-" + Status + ".pdf"

Another idea (which is beyond my python / API abilities) would be for the Print Setting to be automatically selected based on a matching Sheet parameter value. There are nearly always a number of different sheet sizes in large print runs and this would speed the printing process up a lot!
