### ISSUE TITLE
 Draw drafting lines over edges of selected elements

### ISSUE THREAD

**Issue by ThubanPDX** [eirannejad/pyRevit#69]

**Comment by eirannejad** [comment]
Hum. This is a tough one!

**Comment by frederic-beaupere** [comment]
The base functionality (find cut surface/lines on view per object ) would be a useful one. 
(@gtalarico maybe something for the rpw?) 
I once tried to calculate the construction area on a floor plan from element cut surface - unfortunately I was not successful on that one. (I know I can subtract area_plan_area - rooms_area to get there as well [which made this attempt less urgent/necessary], but only if the the area boundaries were updated.)
