### ISSUE TITLE
Copy state doesn't work for Crop Region of 3d Views

### ISSUE THREAD

**Issue by dsellam** [eirannejad/pyRevit#690]
**Describe the bug**
When Pasting a Crop region State of a 3d View, window showing : 
﻿
ERROR [Paste State] CAN NOT FIND ANY CROP REGION SETTINGS IN MEMORY

**To Reproduce**

1. Take a Sheet with multiple Cropped 3D view placed on it
2. Select one view with Crop region
3. Click on Copy State / Crop Region
4. [No message appears]
5. Click on an other View with an other Crop Region
6. Click on Paste State / Crop Region
7. Error Message

**Expected behavior**
Consistance between the crop regions of multiple 3D views

**Screenshots**

**Desktop :**
- Windows 10
- Revit 2019.2
- pyRevit Version 4.7-beta2:277:2019.2

**Comment by eirannejad** [comment]
Fixed and will be published with next release
