### ISSUE TITLE
CPython objects passed to Revit cause halt

### ISSUE THREAD

**Issue by eirannejad** [eirannejad/pyRevit#692]
**Describe the bug**
CPython engine is unstable when an object that is created in cpython scope is passed to Revit API. Seems like Revit gets stuck when trying to garbage collect the passed object(?!)

The script below, will halt Revit after a couple of executions. The script does not cause any halts when `rebars = select_objects()`  is used. (Uncomment the `rebars = select_objects()` line and comment out the `rebars = select_objects_by_category('Walls')` to change the test)

The issue seems to be related to passing an instance of `CategoriesFilter` to Revit API. Note that this might be related to #686 

```python
from pyrevit import EXEC_PARAMS
from pyrevit import revit, UI

class CategoriesFilter(UI.Selection.ISelectionFilter):
    __namespace__ = EXEC_PARAMS.exec_id

    def __init__(self, names):
        self.names = names

    def AllowElement(self, element):
        return element.Category.Name in self.names

    def AllowReference(self, refer, point):
        return False


def select_objects_by_category(*names):
    references = \
        revit.uidoc.Selection.PickObjects(
            UI.Selection.ObjectType.Element,
            CategoriesFilter(names),
            'Pick {}'.format(', '.join(names))
            )
    return [revit.doc.GetElement(reference) for reference in references]


def select_objects():
    references = \
        revit.uidoc.Selection.PickObjects(UI.Selection.ObjectType.Element)
    return [revit.doc.GetElement(reference) for reference in references]


def main():
    # rebars = select_objects()
    rebars = select_objects_by_category('Walls')
    print(rebars)


main()
```

**Comment by eirannejad** [comment]
@htlcnn

**Comment by htlcnn** [comment]
It might be related to an open issue of pythonnet
https://github.com/pythonnet/pythonnet/issues/520

**Comment by htlcnn** [comment]
I ran the script and had this failure even when I'm not using CategoriesFilter. It happened after a few runs.

![image](https://user-images.githubusercontent.com/931924/64922941-e8dd6800-d7fe-11e9-81b8-0ea8e86acb27.png)

**Comment by jmcouffin** [comment]
**Closing**
Issue older than a year.
Thanks for pointing it out.
If you feel it is still relevant, feel free to reopen the issue
