### ISSUE TITLE
Issue when loading pyRevit while Revit is running

### ISSUE THREAD

**Issue by dbaldacchino** [eirannejad/pyRevit#693]
**Describe the bug**
Installed using the executable. The .addin manifest is placed in the user profile location and everything runs fine when opening Revit. We customize addin loading via a custom addin where we remove the original .addin manifest and drop it in the user profile if the user enables the addin. When doing this, I'm getting the following error with the latest version (4.7.1-beta2).

![image](https://user-images.githubusercontent.com/4656191/64925670-c543fe80-d7b9-11e9-84a8-a050e5cf6f97.png)

**To Reproduce**
1. With Revit closed, remove the .addin manifest from %appdata%\Autodesk\Revit\Addins\20xx
2. Open Revit
3. Drop the .addin manifest back in %appdata%\Autodesk\Revit\Addins\20xx

Note that if I now leave the .addin manifest as is, then close and re-open Revit, pyRevit will load with no issues.

**Expected behavior**
pyRevit should load without issues

**Screenshots**
Please see above.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - pyRevit Version 4.7.1-beta2

**Comment by eirannejad** [comment]
That's odd. Do you have the `bin/engines/368` and `bin/engines/372` directories in the install path?

**Comment by eirannejad** [comment]
I'll test this out today. So this issue happened when hot-loading pyRevit while Revit is running.

**Comment by dbaldacchino** [comment]
Hi @eirannejad , yes they are present and yes, when hot-loading pyRevit while Revit is running.

![image](https://user-images.githubusercontent.com/4656191/64926932-579fce80-d7c9-11e9-88e7-782d123b2560.png)

**Comment by eirannejad** [comment]
Released 4.7 beta 3 with improvements. Hopefully it fixes this issue. Please test when you get a chance

**Comment by CuongVTC** [comment]
I used the above method but it still failed
Revit 2019.2
pyRevit_4.7.2 beta 3
see more https://imgur.com/TpjHW97

**Comment by eirannejad** [comment]
Would you check please to see if Nett.dll is inside the bin/ path in the installed pyRevit?

**Comment by eirannejad** [comment]
Also why is there a need to hot load pyRevit like this?!

**Comment by CuongVTC** [comment]
> Also why is there a need to hot load pyRevit like this?!
Because it failed if I didn't do that. So let's try it
https://i.imgur.com/098RjPa.png

**Comment by eirannejad** [comment]
So odd.

**Comment by htlcnn** [comment]
@CuongVTC Try uninstalling pyRevit and install it again

**Comment by CuongVTC** [comment]
@htlcnn thanks,
I have reinstalled it several times

**Comment by dbaldacchino** [comment]
> Also why is there a need to hot load pyRevit like this?!

We have been doing this with all our addins for the last 3 years. Users have the option to load for the current session only or always. Only a couple fail and have to be set to "always" (the .addin manifest has to be in place before Revit starts or the addin fails to load properly). We do this for two prime reasons: loading speed when launching Revit and stability in general. We have tons of addins and it was slowing loading times considerably, especially on Citrix. Considering addins are only used occasionally, we needed a more "on-demand" process for loading them. This also gave us an entry point to see which addins are the most popular (we log loading data and visualize on a web portal). The second factor is stability: we were running into several issues where some addins caused file corruptions or instability, so by limiting what loads automatically when users are working, reduced the instance of these issues. Thanks.

**Comment by dbaldacchino** [comment]
BTW beta3 resolved the issue @eirannejad :) Thanks a ton as always!

**Comment by eirannejad** [comment]
@CuongVTC I can not replicate the issue here on my machine. Not sure why this is happening. It's got something to do with the assembly resolution not being able to find Nett.dll 

Maybe conflict with another addon

**Comment by eirannejad** [comment]
@dbaldacchino Awesome! Phewww!
