### ISSUE TITLE
Ability to Remove Certain Parameters / Values when using 'Wipe All Family Parameters'

### ISSUE THREAD

**Issue by kraftwerk15** [eirannejad/pyRevit#694]
**Is your feature request related to a problem? Please describe.**
The Wipe All Family Parameters is a good starting point, but is hindered by being able to be an "all or nothing" button. Let's 'spice it up' and give the end user the ability to select which parameters they want to delete instead of forcing a tool that deletes all of them.

**Describe the solution you'd like**
I have not observed other push buttons with this feature, but a type of UI that would list out the Parameters and Values that would be removed (before actually deleting of course) and the giving the end user a radio group for each parameter with the option to either delete the Parameter altogether, delete the Value from the Parameter, or skip the Parameter entirely. Skip entirely should probably be the default.

This could be placed out to another button nested under the Family group on the ribbon. The existing button could be left for those that want to blow away everything (which is still useful), but another button for the end user to walk through every parameter would be nice.

**Describe alternatives you've considered**
Really don't think there is one. I know CTC has a paid feature that may be an alternative.

**Additional context**

**Comment by eirannejad** [comment]
Updated. Will be pushed with 4.7 final

![2019-09-30 16_13_08-Select Parameters](https://user-images.githubusercontent.com/8197916/65923354-7b543e80-e39d-11e9-9f3b-22baddb0c140.png)
