### ISSUE TITLE
pyRevit 4.7.2 beta3 Load Error

### ISSUE THREAD

**Issue by archibank** [eirannejad/pyRevit#695]
**Describe the bug**
Load Error after installing pyRevit 4.7.2 beta3... (non-admin)
Previous version 4.6.24 works fine...
uninstalled and reinstalled both versions, same results. v4.6.24(works), v4.7.2(error)

![pyRevit 4 7 2 beta3 Load Error](https://user-images.githubusercontent.com/55449858/65053873-46260600-d932-11e9-968c-edaef39161d7.JPG)

 - OS: Windows
 - pyRevit Version 4.7.2_beta3
 - pyRevit Environment: 

```
C:\Users\arthur.banks>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)
==> Attachments
==> Installed UI Extensions
==> Installed Library Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
==> Running Revit Instances
Error: Value cannot be null.
Parameter name: path3
Run with "--debug" option to see debug messages
```

**Comment by eirannejad** [comment]
Run `pyrevit env --debug` please and send the full log so I can see what the error is on `pyrevit env`. It doesn't seem like your pyRevit clone is registred correctly. What's the install path for pyRevit?

**Comment by archibank** [comment]
install path is: C:\Users\arthur.banks\AppData\Roaming\pyRevit-Master
'''
C:\Users\arthur.banks>pyrevit env --debug
env = True
Debug: Active Keyword: env
==> Registered Clones (full git repos)
Debug: Try getting config as dict "environment:clones"
Debug: Try getting config "environment:clones" ?? {}
Debug: Updating config "environment:clones = {}"
Debug: Saving config file "C:\Users\arthur.banks\AppData\Roaming\pyRevit\pyRevit_config.ini"
==> Registered Clones (deployed from archive)
==> Attachments
Debug: Try getting config as list "core:userextensions"
Debug: Try getting config "core:userextensions" ??
Debug: Updating config "core:userextensions = []"
Debug: Saving config file "C:\Users\arthur.banks\AppData\Roaming\pyRevit\pyRevit_config.ini"
==> Installed UI Extensions
==> Installed Library Extensions
==> Extension Search Paths
Debug: Try getting config as list "core:userextensions"
Debug: Try getting config "core:userextensions" ??
Debug: Updating config "core:userextensions = []"
Debug: Saving config file "C:\Users\arthur.banks\AppData\Roaming\pyRevit\pyRevit_config.ini"
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
Debug: Try getting config as list "environment:sources"
Debug: Try getting config "environment:sources" ??
Debug: Config is not set. Returning default value ""
==> Installed Revits
==> Running Revit Instances
Error: Value cannot be null.
Parameter name: path3 (System.ArgumentNullException)
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at pyRevitLabs.TargetApps.Revit.RevitProduct.get_InstallLocation()
   at pyRevitLabs.TargetApps.Revit.RevitProduct.ToString()
   at pyRevitLabs.TargetApps.Revit.RevitProcess.ToString()
   at System.IO.TextWriter.WriteLine(Object value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(Object value)
   at System.Console.WriteLine(Object value)
   at Colorful.Console.WriteLine(Object value)
   at pyRevitManager.Views.pyRevitCLI.PrintRunningRevits() in C:\Users\LeoW10\Desktop\gits\pyRevitLabs\pyRevitLabs\pyRevitManager\CLI.cs:line 1322
   at pyRevitManager.Views.pyRevitCLI.ExecuteCommand(IDictionary`2 arguments, IEnumerable`1 activeKeys) in C:\Users\LeoW10\Desktop\gits\pyRevitLabs\pyRevitLabs\pyRevitManager\CLI.cs:line 247
   at pyRevitManager.Views.pyRevitCLI.ProcessArguments(String[] args) in C:\Users\LeoW10\Desktop\gits\pyRevitLabs\pyRevitLabs\pyRevitManager\CLI.cs:line 196
'''

**Comment by eirannejad** [comment]
Okay. Which CLI version are you using? run `pyrevit --version`

Add the installed clone using
`pyrevit clones add master "C:\Users\arthur.banks\AppData\Roaming\pyRevit-Master"`

Then run the `pyrevit env` again and verify `master` is listed under `==> Registered Clones (deployed from archive)`

Now reattach the clone to the installed Revits using 
`pyrevit attach master 277 --installed`

**Comment by archibank** [comment]
PS C:\Users\arthur.banks> pyrevit --version
pyrevit v0.2.10.0

I tried to install CLI 0.15.0, but I need Admin rights for the installer...

I added the installed clone and reattached the clone, but receive a load error when starting Revit...
when i check for the clone again (pyrevit env), it doesn't show up...
here is the before and after... the load error is different however.

before Revit open:
![image](https://user-images.githubusercontent.com/55449858/65072693-0887a400-d957-11e9-8caf-105085120712.png)


after Revit open:
![image](https://user-images.githubusercontent.com/55449858/65073048-aaa78c00-d957-11e9-9bb5-19a0b0f4d300.png)


pyRevit load error:
![image](https://user-images.githubusercontent.com/55449858/65071983-8b0f6400-d955-11e9-83ab-503108f48cdc.png)

**Comment by eirannejad** [comment]
Uninstall the really really old pyrevit CLI you have. pyRevit public installation includes the CLI under the `bin/` directory. Add the path of the pyRevit `bin/` to your environment PATH so you can run `pyrevit` from the command line. Otherwise `cd` to the bin path and run using `./pyrevit.exe`

**Comment by archibank** [comment]
Changing the directory to the installed pyRevit bin/ folder works for the CLI...
but I'm still getting a Load Error. Looks like the same error...

pyRevit env:
![image](https://user-images.githubusercontent.com/55449858/65075941-80f16380-d95d-11e9-80d8-c479b27a7057.png)



Load Error:
![image](https://user-images.githubusercontent.com/55449858/65075435-8601e300-d95c-11e9-903c-bef73d2606d9.png)

**Comment by archibank** [comment]
I've attached the beta4 clone, but I'm still receiving a loading error.
master still works though...

![image](https://user-images.githubusercontent.com/55449858/65913746-04677780-e396-11e9-8829-f81f4c39a9d0.png)

**Comment by eirannejad** [comment]
Thanks @archibank
