### ISSUE TITLE
Keyboard shortcuts not available when loading from Custom Extension Directory

### ISSUE THREAD

**Issue by BrettBeckemeyer** [eirannejad/pyRevit#697]
**Describe the bug**
I have a custom created pyRevit extension. Previously, I had loaded the extension by creating a new "extensions.json" specific to my extension and adding this new .json as an extension search path via the CLI tool. This worked and I was able to also access any of the commands in the custom extension through Revit's keyboard shortcut dialog.

However, I recently changed the extension loading method to using the "Custom Extension Directory" option in the Settings. The extension now loads and performs like before; but the commands are no longer available via the keyboard shortcut dialog.

The same behavior happens with a third-party extension I downloaded.

**To Reproduce**
1. Add extension via "Custom Extension Directory" method in Settings
2. Go to File - Options - User Interface - Keyboard Settings
3. Sort by Paths and scroll down to the name of the extension

**Expected behavior**
Commands of other pyRevit extensions are listed under Keyboard Settings and I would expect extensions loaded via the Custom Extension Directory to also be listed.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 7
 - pyRevit Version 4.6.24
- pyRevit Environment: 

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\bbeckemeyer>pyrevit env
==> Registered Clones (full git repos)
master | Branch: "master" | Version: "4.6.24:76d18d6" | Path: "C:\Users\bbeckeme
yer\AppData\Roaming\pyRevit\pyRevit\master"
==> Registered Clones (deployed from archive/image)
main | Deploy: "base" | Branch: "master" | Version: "4.6.24" | Path: "C:\Users\b
beckemeyer\AppData\Roaming\pyRevit\pyRevitCopy\main"
==> Attachments
main | Product: "Autodesk Revit 2019.2.1" | Engine: 273 | Path: "C:\Users\bbecke
meyer\AppData\Roaming\pyRevit\pyRevitCopy\main" | Manifest: "C:\Users\bbeckemeye
r\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
main | Product: "Autodesk Revit 2018.3.3 Security Fix" | Engine: 273 | Path: "C:
\Users\bbeckemeyer\AppData\Roaming\pyRevit\pyRevitCopy\main" | Manifest: "C:\Use
rs\bbeckemeyer\AppData\Roaming\Autodesk\Revit\Addins\2018\pyRevit.addin"
==> Installed Extensions
pyApex | Type: UIExtension | Repo: "https://github.com/apex-project/pyApex.git"
| Installed: "C:\Users\bbeckemeyer\AppData\Roaming\pyRevit\Extensions\pyApex.ext
ension"
pyCD | Type: UIExtension | Repo: "" | Installed: "\\cd-ddrd02\Library\Computatio
n and Scripting\Revit\Revit API\pyRevit_extensions\pyCD.extension"
pyL_R v0.1 | Type: UIExtension | Repo: "" | Installed: "\\cd-ddrd02\Library\Comp
utation and Scripting\Revit\Revit API\pyRevit_extensions\pyL_R.extension"
PyRevitMEP | Type: UIExtension | Repo: "https://github.com/CyrilWaechter/pyRevit
MEP.git" | Installed: "C:\Users\bbeckemeyer\AppData\Roaming\pyRevit\Extensions\P
yRevitMEP.extension"
PyRevitPlus | Type: UIExtension | Repo: "https://github.com/gtalarico/pyrevitplu
s.git" | Installed: "C:\Users\bbeckemeyer\AppData\Roaming\pyRevit\Extensions\PyR
evitPlus.extension"
pyRevitTemplates | Type: UIExtension | Repo: "" | Installed: "\\cd-ddrd02\Librar
y\Computation and Scripting\Revit\Revit API\pyRevit_extensions\pyRevitTemplates.
extension"
pyrric | Type: UIExtension | Repo: "https://github.com/BrettBeckemeyer/pyrric.gi
t" | Installed: "C:\Users\bbeckemeyer\AppData\Roaming\pyRevit\Extensions\pyrric.
extension"
==> Default Extension Search Path
C:\Users\bbeckemeyer\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\Users\bbeckemeyer\AppData\Roaming\pyRevit\Extensions
\\cd-ddrd02\Library\Computation and Scripting\Revit\Revit API\pyRevit_extensions

==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
\\cd-ddrd02\Library\Computation and Scripting\Revit\Revit API\pyRevit_pyrric_ext
ension\extensions.json
==> Installed Revits
Autodesk Revit 2019.2.1 | Version: 19.2.10.7 | Build: 20190225_1515(x64) | Langu
age: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
Autodesk Revit 2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515
(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018"
Autodesk Revit 2017.2.5 Security Fix | Version: 17.0.1169.0 | Build: 20190508_03
15(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
Autodesk Revit 2016 Update 8 for R2 (2016.1.8) | Version: 16.0.1205.0 | Build: 2
0170117_1200(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016
"
==> Running Revit Instances
PID: 56592 | Autodesk Revit 2018.3.3 Security Fix | Version: 18.3.3.18 | Build:
20190510_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2018"
==> User Environment
Microsoft Windows 7 [Version 6.1.7601]
Executing User: CANNONDESIGN\bbeckemeyer
Active User: CANNONDESIGN\bbeckemeyer
Adming Access: Yes
%APPDATA%: "C:\Users\bbeckemeyer\AppData\Roaming"
Latest Installed .Net Framework: 4.7.1
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.13.0.0
```

**Comment by eirannejad** [comment]
pyRevit treats all the extensions the same. pyRevit internal tools are build the exact same way you are building your own extensions. There is no distinctiion between extensions loaded from builtin paths and custom extension paths.

What is the name of your extension Tab? The paths in the keyboard shortcut menu is not "directory" paths. They are GUI paths to get to the tool. Find the tab name for your own extension

**Comment by BrettBeckemeyer** [comment]
That is what is strange. I have two extensions loaded from the custom extensions path. Both are extensions I previously loaded through the JSON file. Both previously showed up in the keyboard shortcut menu. Now that I have them loaded through the custom extensions path neither one shows up in the shortcut menu.

My extension is "pyCD" and the other one is "pyL-R".

**Comment by BrettBeckemeyer** [comment]
Ok, it also seems to only be affecting my Revit 2018 and not 2019. Perhaps something has gone wrong with my 2018 install.

**Comment by BrettBeckemeyer** [comment]
As of this morning, the options are back on the Keyboard Shortcuts dialog. I did a restart last night and that seems to have fixed this.
