### ISSUE TITLE
UTF8 Bundles(yaml file)

### ISSUE THREAD

**Issue by DmytroSE** [eirannejad/pyRevit#698]
Hi! I tried to create bundles with UTF-8 text and sort it with bundle.yaml file. But here what i have.
Am i doing something wrong or it is not implemented yet?
![report2](https://user-images.githubusercontent.com/45512632/65234209-d30cc300-dadc-11e9-8c70-d7ea429855f5.PNG)
![report1](https://user-images.githubusercontent.com/45512632/65234223-d6a04a00-dadc-11e9-8104-06d558a2dda0.PNG)

**Comment by eirannejad** [comment]
No you are fine. I somehow missed testing this . Sorry pal. Will issue the fix with beta4 this weekend.

**Comment by eirannejad** [comment]
Fixed and will be published with beta4
