### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by jeremytammik** [eirannejad/pyRevit#70]
is there any documentation available at all for this? installation, running and usage instructions? an overview of the functionality provided? thank you!

**Comment by eirannejad** [comment]
Jeremy,
The readme file on the front page has all the documentation. Most of the scripts have `__doc__` parameter defined that shows up as a tooltip on the buttons. I'm working on creating an installer for this library to make the setup easier. I'll keep you posted on this. Thank you for all your hard work. You helped me a lot in creating this library.

**Comment by jeremytammik** [comment]
ehsan, thank you very much for your explanation and appreciation. oh yes, sorry, i apparently looked at some subfolder page in the repo and did not notice that it was not the main entry point. cheers.

**Comment by eirannejad** [comment]
Sure thing. Let me know what do you think of this library.

**Comment by jeremytammik** [comment]
just from looking at it, it looks fantastic! unfortunatly, i do not have time to dive in deeper myself. i will happily mention it on The Building Coder blog, though, if you would like me to. could you provide a short write-up describing it? you should be able to extract something suitable from the readme and doc strings. thank you!

**Comment by eirannejad** [comment]
Sure thing. How short? single paragraph or longer?

**Comment by jeremytammik** [comment]
as long or short as you like. one paragraph is fine, in that case i will ad it as a note. a huge exhaustive explanation with samples and tutorials and everything is also fine. in that case, i would publish it as a full independent post. looking forward to seeing what you come up with  :-)  have fun.

**Comment by jeremytammik** [comment]
by the way, the reason i noticed this at all was the comment by Maltezc in this revit api discussion forum thread: http://forums.autodesk.com/t5/revit-api/revitlookup-for-revit-2016-is-here/m-p/5600976. would you like to answer it and explain the relationship between revitlookup and pyrevit, if there is any, or compare the two and their respective use cases? that could also provide an possible entry point for a blog post description...

**Comment by eirannejad** [comment]
Nice!! I'm super excited now!! I'll go for the long version highlighting some of the most useful tools! Let me know what format would be the easiest for you otherwise I'll send an html page with photos on the side. Thanks so much again.

**Comment by eirannejad** [comment]
Sure I'll answer the blog post.

**Comment by jeremytammik** [comment]
better than html would be markup. it is much easier to write. for example, look at and compare yesterday's blog post on The Building Coder in MD versus HTML:

https://raw.githubusercontent.com/jeremytammik/tbc/gh-pages/a/1420_forge_devcon.md

https://raw.githubusercontent.com/jeremytammik/tbc/gh-pages/a/1420_forge_devcon.html

**Comment by eirannejad** [comment]
So much better. Markup it is!

**Comment by eirannejad** [comment]
Jeremy,
I've written the blog post and I'm working on the graphics. I'll send it all to you soon.

**Comment by jeremytammik** [comment]
cool  :-)

**Comment by eirannejad** [comment]
Just emailed you the markdown file. Let me know what you think :)

**Comment by jeremytammik** [comment]
looks great! working on it now. here is one systematic typo error: pallete is wrong, it is palette.

**Comment by eirannejad** [comment]
Okay so please make all the changes that you like and I'll merge your pull request. Otherwise github is gonna give me the 'Can't Automatically Merge' error that I'm not sure how to properly resolve.

**Comment by eirannejad** [comment]
Thanks for the `palette` correction btw. English is my second language which I'm sure you've guessed by now :))) I'm running a spell check on the master branch readme.md as well.

**Comment by jeremytammik** [comment]
np, your english is great. finished now, scheduled for publication in ca. 50 minutes  :-)

**Comment by eirannejad** [comment]
Thanks so much Jeremy! I'm super excited! We'll be in touch 😃

**Comment by jeremytammik** [comment]
you can preview here: http://jeremytammik.github.io/tbc/a/1425_pyrevit.html

**Comment by eirannejad** [comment]
OMG this is awesome Jeremy. I don't know how to thank you for being so kind! I'm really looking forward to the feedback I can get on pyRevit to make it better. Anyways you're great! Thanks again!

**Comment by jeremytammik** [comment]
my pleasure entirely. thank you for all the work you put into this!

**Comment by Meikii** [comment]
Hi Dear Jeremy And Dear Ehsan ...and Thank you so much for this effort on such a great tool ...pyRevit is a perfect package for doing wonderful things ...with your permission i dive into your Code ...
Thanks again ...both of you are great help to this topic 
Dametun Garm :D
