### ISSUE TITLE
deploying pyRevit across an organisation with a custom extension path

### ISSUE THREAD

**Issue by jagostinhoCT** [eirannejad/pyRevit#700]
Hello,

I am trying to find how can one create a pyRevit deployment with a custom extension path on a network folder.

I found this [cached webpage](https://webcache.googleusercontent.com/search?q=cache:GKI-WFz5CyYJ:https://eirannejad.github.io/pyRevit/pyrevit/update/2017/10/14/configupdate.html+&cd=1&hl=en&ct=clnk&gl=uk) relating to a seed config file. But I could not find a pyRevit folder under %programdata%.

Could IT just copy a portion of the ini file to the %programdata% folder just as below? The problem I found with %appdata% is that it uses a "c:\Users\[username]\..." type of path that can only exist once the users starts Revit for the first time, am I right?

Or is there a better way of doing it?
Thank you
J

**Comment by eirannejad** [comment]
See [pyRevit Wiki](https://www.notion.so/pyrevitlabs/pyRevit-bd907d6292ed4ce997c46e84b6ef67a0), specifically [pyRevit for Teams](https://www.notion.so/pyrevitlabs/pyRevit-For-Teams-ddc6c312d6f6488691eed2ec7704fd97)
