### ISSUE TITLE
Keynote Manager Needs Keynote-Edit-KEY Button

### ISSUE THREAD

**Issue by Hazen12345** [eirannejad/pyRevit#701]
Ehsan please can you look at adding some tools to the Keynote Manager, I mentioned this earlier.

Keynote Edit Key button, a toggle move up and down order button would be fantastic, the same as the family parameter properties name order buttons.

Thanks!

**Comment by eirannejad** [comment]
There is an Keynote Edit button already(!?)

**Comment by Hazen12345** [comment]
Sorry could a Keynote spell check be added also?

**Comment by cftrevizo** [comment]
...could you make it Editable to reassign the "Category" (move up/down Categories) the keynote belongs to instead of having to recreate the keynote. Should this be a new Entry, or could it tag along with this capability?

**Comment by DanBoghean** [comment]
Just wondering if the Edit Key is on the near-future timeline. We're looking at various Keynote Manager options for our firm, but the Edit Key is critical as we need to change the key numbers regularly. 

Thank you!

**Comment by eirannejad** [comment]
New Keynote Manager Features:
- [ ] Edit Keynote and Category Key
- [ ] Move Keynotes

**Comment by Architectuur** [comment]
Can I upvote the addition of the edit key function? This would be incredibly helpful.

**Comment by eirannejad** [comment]
Implemented and will be published with next release
