### ISSUE TITLE
pyRevit Sum Total suggestion

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#703]
**Describe the solution you'd like**
I would like pyRevit Sum Total to itemised the Revit Elements used in Sum Total calculation. 
This would be helpful when complying an area report plus it would assist the Revit user to select those Revit element/s in the model by clicking on the listed Revit element id. Refer to screenshot:

![image](https://user-images.githubusercontent.com/8776947/66040481-6f888980-e50f-11e9-8d0e-862e4e93d340.png)

**Comment by eirannejad** [comment]
Fixed and will be published with next release. The sum total now shows a breakdown of input values

![Revit_U8apr58lfM](https://user-images.githubusercontent.com/8197916/77773664-28cfa400-7007-11ea-8259-2d144ea4ed3c.png)
