### ISSUE TITLE
Wipe All Family Parameters "Cancel" button is not operable

### ISSUE THREAD

**Issue by kraftwerk15** [eirannejad/pyRevit#704]
**Describe the bug**
Wipe All Family Parameters contains a Cancel button, but it does not stop the process. It is the same as hitting the continue button.

**Version**
pyRevit v4.6.22

**To Reproduce**
1. Go to Family > Wipe All Family Parameters
2. Click on 'the button'
3. Dialog displays to "make sure to save work" etc.
4. Press "Cancel", but the process runs anyways.

**Expected behavior**
The process to abandon, but the process continues.

**Screenshots**
![image](https://user-images.githubusercontent.com/30668448/66134128-6d7d0400-e5bd-11e9-85c1-aa8ec326a67c.png)

![image](https://user-images.githubusercontent.com/30668448/66134145-77066c00-e5bd-11e9-9c4d-fb2b971f90f4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.6.22

**Additional context**

**Comment by eirannejad** [comment]
The wipe family parameter tools are completely redesigned in the newer pyRevit versions. Try 4.7-beta4
