### ISSUE TITLE
Keynote Manager Conversion takes a long time

### ISSUE THREAD

**Issue by DanBoghean** [eirannejad/pyRevit#705]
**Describe the bug**
When running Keynote Manager, it prompts you to convert the existing keynote file to work with the Keynote Manger. When I click Convert, it takes about 10 minutes to convert the keynote file. Is this the typical time it should be taking?

**To Reproduce**
1. Go to Manage Keynotes
2. Click on Convert
3. Wait.

**Expected behavior**
I'm expecting it to not take as long, but if that's the case, it's just something I need to make sure to let teams know when they are first converting keynotes. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.7-beta4

**Comment by eirannejad** [comment]
Hey. Would you be able to share the keynote file?

**Comment by DanBoghean** [comment]
Yes, I will shoot it over on Monday as I am heading out of town and don't
have access to my work computer.

**Comment by DanBoghean** [comment]
This is the keynote file I was trying it on: https://a360.co/2LWREZr

**Comment by eirannejad** [comment]
Okay so made the keynote manager backend a bit smarter about the transaction locks. This should speed things up but then again you have 5300 keynotes in that file so it's still gonna be a bit slower that others. Will push with 4.7 final

**Comment by DanBoghean** [comment]
Awesome. Thanks for taking a look. I figured it would take a while with the amount of keynotes that are currently in the file.
