### ISSUE TITLE
Do not show log.deprecated in "Warnings only" mode

### ISSUE THREAD

**Issue by melnikovalex** [eirannejad/pyRevit#706]
Hi Ehsan! 

Testing a new beta (release/4.7.3-beta4). Looks great except couple of thinks. Here is one of them.

I find it excessive to show `deprecated` messages when "Warnings only" mode is enabled. 

Developers, who can fix those issues usually have "info" mode. 

All the other users can do nothing with it except updating to the new version (if you're not in organisation). 

In case on my organisation now I am getting further scenarios:
A:
1. I am arranging pyRevit update. So one day it is getting installed for all the users in org.
2. All the users are getting dozens of "deprecated" messages on Revit start. As the result, I am getting dozens of emails.
3. Next day users get updated ".extension"  and calm down.

B:
1. I do the changes into ".extension", push changes into local git.
2. If pyRevit update wasn't installed yet, next day user loose all the buttons in "stacks".
3. Update is getting installed and peace comes.

Considering the case of pyApex extension update. 

I am sure there are people who're still using it with older version and do not want to worry about pyRevit updates.
But one day I decided to change all "_layouts" to `.yaml` and `stack3` to `stacks` they (those ones who have "Autoupdate" enabled) are forced to install the update, because the half of the scripts would be lost.

So I would better wait until 4.8/4.9 before doing those changes into pyApex.

**Describe the solution you'd like**
1. To show "log.deprecated" messages only in "info" mode.

2. Support old "stack3" and "_layout" during couple major releases more to give users time to update.

**Comment by eirannejad** [comment]
Makes sense. Will make adjustments for 4.7 final.

**Comment by eirannejad** [comment]
Resolved. Deprecate messages will now show up if the logging is set to "None"
