### ISSUE TITLE
Call other pyRevit bundle from current bundle

### ISSUE THREAD

**Issue by htlcnn** [eirannejad/pyRevit#708]
Hi,
I'm making a pushbutton bundle (**bundle 1)** that requires some configurations to be pre-set. I make a separated bundle (**bundle 2**) to set and save config.
Is there any method to automatically fire up **bundle 2** from inside **bundle 1**?

**Comment by eirannejad** [comment]
Hey. So for configuring a tool, you can drop a second script (`config.py`) inside the same bundle and pyRevit will show a black dot on the pushbutton title. 
shift-clicking on the tool will run the configurations for that bundle. See pyRevit Match tool.

To run another bundle from inside a script, you need the unique id of the bundle (shown on the tooltip or the Shift+Win-Click menu):

```python
from pyrevit.loader import sessionmgr

bundle_id = "pyrevittools-pyrevit-selection-select-select-listselectionasclickablelinks"

sessionmgr.execute_command(bundle_id)
```
