### ISSUE TITLE
Toolbars inside of a master toolbar selector

### ISSUE THREAD

**Issue by AlexVilaOrtega** [eirannejad/pyRevit#711]
Hi Ehsan,

I have many small buttons done in C#, Dynamo and Python,  I am thinking to integrate the tools in PyRevit using your setup, the problem is that right now i have them in 8 tabs with many buttons each. the different plugin I am using and testing are pushing my buttons beyond the edge of the screen...

I like to know if is possible to create a selector that can swap the toolbars under the the same tab, maybe a first section with different disciplines and the toolbars using the rest of the space.

Maybe like office, contextual toolbars? were buttons are not shown if are not active?

Thanks for considering it.

**Comment by eirannejad** [comment]
I can provide an option for panels in the bundle metadata file to set the panels to collapsed by default

```yaml
collapsed: true
```

![2019-10-08_09-43-26](https://user-images.githubusercontent.com/8197916/66415326-338e7200-e9b0-11e9-8c18-2c4b1c6ba2bd.gif)

**Comment by AlexVilaOrtega** [comment]
Looks good! Main functions on the toolbar and discipline toolbars.

Alex

**Comment by eirannejad** [comment]
Implemented and will be pushed with 4.7 final.

**Comment by AlexVilaOrtega** [comment]
Great! Looking forward to start using it!
Thanks

Alex
