### ISSUE TITLE
PyRevitLoader - Error Laoding pyRevit

### ISSUE THREAD

**Issue by kierangilman** [eirannejad/pyRevit#715]
Hi,

First time using of pyRevit, Gone to load revit and keep getting the following error messages. Ive noticed this error only happens on a user profile, however loads completely fine for an administrator account.

The files it mentions, have been located in windows explorer, and the paths it mentions. to note we does user folder re-directions for our users

get the following when using pyrevit env

Microsoft Windows [Version 10.0.17134.1006]
(c) 2018 Microsoft Corporation. All rights reserved.

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.6.24" | Path: "\\local\User\ManchesterAccounts\kgilman\Application Data\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2019.2 (Full Install)" | Engine: 277 | Path: "\\local\User\ManchesterAccounts\kgilman\Application Data\pyRevit-Master" | Manifest: "\\local\User\ManchesterAccounts\kgilman\Application Data\Autodesk\Revit\Addins\2019\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
\\local\User\ManchesterAccounts\kgilman\Application Data\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2019.2 (Full Install) | Version: 19.2.1.1 | Build: 20190108_1515(x64) | Language: 1033 | Path: "D:\Program Files\Autodesk\Revit 2019"
==> Running Revit Instances
PID: 22720 | Autodesk Revit 2019.2 (Full Install) | Version: 19.2.1.1 | Build: 20190108_1515(x64) | Language: 0 | Path: ""
==> User Environment
Microsoft Windows 10 [Version 10.0.17134]
Executing User: \kgilman
Active User: \kgilman
Adming Access: No
%APPDATA%: "\\local\User\ManchesterAccounts\kgilman\Application Data"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.7.1 v4.X
Installed .Net-Core Target Packs: v2.1.202 v2.1.503
pyRevit CLI 0.13.0.0
```

[C:\Users\kgilman>]([url]([url](url
![2019-10-08 15_00_38-PyRevitLoader - Error Loading pyRevit-01](https://user-images.githubusercontent.com/56308101/66403668-dfe74d00-e9de-11e9-82cf-58c43d6ac002.png)
![2019-10-08 15_01_13-PyRevitLoader - Error Loading pyRevit-2](https://user-images.githubusercontent.com/56308101/66403669-e07fe380-e9de-11e9-846f-939ab811104a.png)
![2019-10-08 15_01_52-PyRevitLoader - Error Loading pyRevit-3](https://user-images.githubusercontent.com/56308101/66403670-e07fe380-e9de-11e9-83df-a2a6543e7c2c.png)

Thanks

Kieran

**Comment by eirannejad** [comment]
Seems like you have network-based user profiles. Install pyRevit on a different location on your local machine and not a network location.
