### ISSUE TITLE
_inc_or_dec_string increments "9" as "0" instead of "10"

### ISSUE THREAD

**Issue by melnikovalex** [eirannejad/pyRevit#716]
**Describe the bug**
Hey Ehsan!

There is a reaaally small bug which can lead to larger problems (already can cause a loop in "ReNumber").

For some reason `coreutils._inc_or_dec_string(str_id=9, shift=1)` returns `0` instead of `10`. With further dozens it works correctly.

I was trying to find a quick solution, but afraid to break something else. 

Could you have a look, please?

**Comment by eirannejad** [comment]
Ya. So the `coreutils._inc_or_dec_string` purpose was designed to increment strings like `A110a` to `A110b` and such. It doesn't add characters to the string under current implementation. But you are absolutely right. I need to fix this.

**Comment by eirannejad** [comment]
Resolved and will be pushed with 4.7 final
