### ISSUE TITLE
Keynote Manager - Text over multiple lines

### ISSUE THREAD

**Issue by leepatt** [eirannejad/pyRevit#718]
Thanks Ehsan for such an amazing piece of software.

Im really enjoying the Keynote Manager, but would love to have more control over the layout of the keynote text. 

Would it be possible to drop down a line with ctrl + enter or shift + enter?

**Comment by leepatt** [comment]
Great! thanks

**Comment by eirannejad** [comment]
Checked. Not possible with current implementation.
