### ISSUE TITLE
False Positive As A Virus

### ISSUE THREAD

**Issue by mcterry1337** [eirannejad/pyRevit#720]
A file in the installer for both pyrevit and pyrevitcli is turning up as a false positive as a virus by my company's anti virus program, F-Secure. My IT department is having trouble white listing the file.  Just seeing if there is anything that can be done on the installer side to make it not trigger the false positive.

![image](https://user-images.githubusercontent.com/33162085/66609511-1c957e80-eb6e-11e9-8a24-e0c993c1f6b1.png)

**Comment by eirannejad** [comment]
Not as far as I know. This is pyRevit telemetry server, written and compiled in Go and included in the pyRevit distribution. Best solution is to add an exception to the antivirus applications. You can also distribute pyRevit internally and remove the telemetry server.
