### ISSUE TITLE
Backward compatibility of 4.6 pyrevit methods

### ISSUE THREAD

**Issue by melnikovalex** [eirannejad/pyRevit#721]
**Is your feature request related to a problem? Please describe.**
Hey Ehsan!

I've noticed that there are some naming changes in 4.7, for instance:

- `revit.activeview` -> `active_view`
- `revit.db.query.get_elements_by_category` -> `get_elements_by_categories`

First, it would be great to have some list of all such changes. It would really help to update extensions.

Then there can be an issue I described in #706 . I would love to support older pyRevit version (4.6) in pyApex, so they still could use pyApex extension.

**Describe the solution you'd like**
Would it be possible to provide backward compatibility for couple of versions? With showing `deprecated` message as it was done with `stack` folders

I see it like that:
```
import warnings 
# do not sure if it supported in IronPython, 
#  but it should mark method as deprecated e.g. in pyCharm

def deprecated(message):
    def deprecated_decorator(func):
        logger.deprecated(message)
        return func
    return deprecated_decorator

@deprecated("'activeview' is deprecated. Use 'active_view'")
def activeview(doc):
    warnings.warn("'activeview' is deprecated. Use 'active_view'", DeprecationWarning)
    return active_view(doc)
```

**Describe alternatives you've considered**
I can see one alternative solution which won't work with current versions (4.6 + 4.7), but it can help to avoid such issues during next major updates.

The solution is to add `pyrevit_version_required` into the extension somehow. And to not allow to install/update the extenion into earlier pyRevit versions.

What do you think?

**Comment by eirannejad** [comment]
@melnikovalex Hey. So most of these were published as part of the [4.7 release notes](https://github.com/eirannejad/pyRevit/releases/tag/v4.7.1-beta2)

Showing deprecated messages is a considered 'best practices' for deprecating API. It provides the developers with guidelines on how to fix breaking changes, and the opportunity to find and fix all these before distributing to users. Normally you'd want to download and test the new versions (especially beta versions) before letting the users update.

As far as backwards compatibility, it's really hard for me as a single developer to support more than one version of pyRevit, especially with the current pace of changes towards 5.0

For 4.8, one of the main tasks is to rework the extensions engine and add more options like the one you mentioned (`pyrevit_version_required`)

Lemme see how I can adjust the logger to hide the messages if logging is set to None in the pyRevit configs
