### ISSUE TITLE
Print order sheet index - empty list

### ISSUE THREAD

**Issue by Konrad-X-PLAN** [eirannejad/pyRevit#723]
In "Print order sheet index" window the list of sheets is empty in Revit 2015 and 2019. It works in 2020.
![Przechwytywanie12](https://user-images.githubusercontent.com/56676003/66997708-43eecd00-f0d3-11e9-8f40-8f78a4cc8aae.JPG)

**Desktop:**
 - OS: Windows 10
 - pyRevit v4.7-beta 4
 - pyRevit Environment: 
`==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7-beta4" | Path: "C:\ProgramData\Autodesk\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2020" | Engine: 277 | Path: "C:\ProgramData\Autodesk\pyRevit-Master" | Manifest: "C:\Users\kayse\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
master | Product: "2020 First Customer Ship" | Engine: 277 | Path: "C:\ProgramData\Autodesk\pyRevit-Master" | Manifest: "C:\Users\kayse\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
master | Product: "2019.2.1" | Engine: 277 | Path: "C:\ProgramData\Autodesk\pyRevit-Master" | Manifest: "C:\Users\kayse\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
master | Product: "2015 Update Release 3" | Engine: 277 | Path: "C:\ProgramData\Autodesk\pyRevit-Master" | Manifest: "C:\Users\kayse\AppData\Roaming\Autodesk\Revit\Addins\2015\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\kayse\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2020 | Version: 20.1.1.1 | Build: 20190731_1515(x64) | Language: 1033 | Path: "D:\Program Files\Autodesk\Revit LT 2020"
2020 First Customer Ship | Version: 20.0.0.377 | Build: 20190327_2315(x64) | Language: 1033 | Path: "D:\Program Files\Autodesk\Revit 2020"
2019.2.1 | Version: 19.2.10.7 | Build: 20190225_1515(x64) | Language: 1033 | Path: "D:\Program Files\Autodesk\Revit 2019"
2015 Update Release 3 | Version: 15.0.207.0 | Build: 20140606_1530(x64) | Language: 1033 | Path: "D:\Program Files\Autodesk\Revit 2015"
==> Running Revit Instances
PID: 9428 | 2019.2.1 | Version: 19.2.10.7 | Build: 20190225_1515(x64) | Language: 0 | Path: ""
==> User Environment
Microsoft Windows 10 [Version 10.0.18362]
Executing User: KONRAD-DELL-G5\kayse
Active User: KONRAD-DELL-G5\kayse
Admin Access: No
%APPDATA%: "C:\Users\kayse\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.16.0.0`

**Comment by eirannejad** [comment]
Thanks for the catch. The bug is related to the schedule configuration, showing the sheet number on the last column. Fixed for 4.7 final release.

**Comment by Konrad-X-PLAN** [comment]
This version 4.7 final has been released already?

**Comment by eirannejad** [comment]
Nope. Coming in two weeks max

**Comment by Konrad-X-PLAN** [comment]
Thank you. Good luck!
