### ISSUE TITLE
Suggestions for pyRevit Print Sheets from Schedules

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#724]
**Is your feature request related to a problem? Please describe.**
Sometimes Revit users do not want to print actually print the entire set of drawings contained within a Revit schedule plus they would also like to be able to rename the prints outputs using predefined Revit parameters.

**Describe the solution you'd like**

**Suggestion 1:**
To be able to override Print by Schedule by manually selecting Sheets plus to also have a Sheet Count displaying the number of Sheets selected.

**Suggestion 2:**
Rename Print outputs using Revit parameters.

**Suggestion 3:**
Include a Sheet revision column.

**Refer to screenshot below:**

![image](https://user-images.githubusercontent.com/8776947/67017433-b4a4e200-f0f1-11e9-9ff6-fc9cf1c29e26.png)

**Describe alternatives you've considered**
Currently using the Revit Xporter Addin for these functionalities but this add-in doesn't print sheets from schedules.

**Comment by eirannejad** [comment]
Implemented Sheet Revision Column and print selected only. The PDF naming is more complex and I'll leave it for later since there is already a way to do that

![2019-10-17 15_04_39-Print Sheets from Schedule](https://user-images.githubusercontent.com/8197916/67051295-8e7e4280-f0ef-11e9-84c7-ce03dd85d039.png)

**Comment by Robbo1234** [comment]
Thanks, Ehsan

**Comment by Robbo1234** [comment]
The icing on the cake would be being able to rename the printed PDF from a combination of Revit Sheet parameters.
Refer to this graphic showing the BS1192 file naming convention:

![image](https://user-images.githubusercontent.com/8776947/67775107-59121700-fa56-11e9-9d76-fb654452b4db.png)

**Comment by eirannejad** [comment]
Is there any add-ons that provides this level of name formatting currently?

**Comment by Robbo1234** [comment]
Ehsan,

RTV Xporter addin https://www.rtvtools.com/rtv-xporter/ , refer to my screenshot in my original post when I'm using RTV Xporter to assemble the File-Name using both Project and Shared Parameters.

**Comment by eirannejad** [comment]
@Robbo1234 Did you test out the new print page with the naming formatters?

**Comment by Robbo1234** [comment]
Yes, Ehsan it works fine. 

Thanks

Rob

**Comment by Robbo1234** [comment]
@eirannejad Could we add a checkbox option to print multiple formats simultaneously (PDF, DWFx, IFC, and DWG)?

Additionally, it would be helpful if the Sheet Index (Schedules) could detect sheets in linked models when "Include elements in links" is selected.

![Image](https://github.com/user-attachments/assets/3c2cb39e-88a2-48f1-9bda-f7a83160a42f)
