### ISSUE TITLE
Set Workset1 current on open

### ISSUE THREAD

**Issue by cridder** [eirannejad/pyRevit#725]
In a workshared file the current workset is set by last user who syncs before a local is created.

Requesting a function that sets the current Workset to 'Workset1' if it exists when a model is opened.

Thanks.

**Comment by eirannejad** [comment]
You can use the new [pyRevit hooks](https://www.notion.so/pyrevitlabs/Create-Your-First-Hook-0214eee855fc43cead1e6f30f586a04e), (specifically `doc-opened`) to set the active workset when a model is opened. This gives you flexibility to set it the way you want it in your org.
