### ISSUE TITLE
Endpoint security detection

### ISSUE THREAD

**Issue by jrdesy** [eirannejad/pyRevit#727]
Hi Ehsan

Noticed this detection by Eset endpoint security

Endpoint version is 7.1.2053.0
pyrevit version is 4.6.24

![endpoint_LI](https://user-images.githubusercontent.com/47362411/67492665-c41db100-f644-11e9-8784-d4e3e8eb8920.jpg)

Love pyrevit, thank you for your work and help.
Can't wait for contribute new tool feature.

JR

**Comment by jrdesy** [comment]
I recently re-watched this video
https://www.youtube.com/watch?v=hrlkPRoUfXc
I get the same warning for pyrevit-autocomplete.exe from Symantec.

![symantec](https://user-images.githubusercontent.com/47362411/67691423-f39a2980-f974-11e9-91d7-7ec5acd38cc9.PNG)

My concern is Eset identifying it as a Trojan variant and then deleting it.
Will it break anything?

**Comment by eirannejad** [comment]
Thanks for the update. Antivirus apps usually flag .exe files that are unknown.

#### Running antivirus on the installer files for version 4.7. All clean
![2019-10-28 15_15_06-Manual Scan started on 10_28_2019 3_14_31 PM](https://user-images.githubusercontent.com/8197916/67722283-f78a7380-f995-11e9-9f77-b13e5ddf46b5.png)

#### Running antivirus on the installer files for version 4.6.24 All clean
![2019-10-28 15_19_40-Manual Scan started on 10_28_2019 3_18_56 PM](https://user-images.githubusercontent.com/8197916/67722458-6071eb80-f996-11e9-8949-b91ca82df991.png)
