### ISSUE TITLE
Error Loading PyRevit

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#729]
A Revit 2019 users is getting this error when his launches Revit. Refer to the screenshot below.

![image](https://user-images.githubusercontent.com/8776947/67559581-217f3400-f711-11e9-8959-547e9a03117c.png)

**Comment by eirannejad** [comment]
Would you please check and see if `Xceed.Wpf.AvalonDock.dll` is inside the Revit 2019 directory? And maybe get the version also while you're at it?

**Comment by 4Maciek** [comment]
I als have some issues with loading pyRevit. Don't have a clue if it is the same situation.

![image](https://user-images.githubusercontent.com/57176563/67850477-c0889f00-fb08-11e9-9dbe-0aee41180ffd.png)

**Comment by 4Maciek** [comment]
Thank you for your help. It is working now. :)
