### ISSUE TITLE
Dyn files don't run as they do from Dynamo

### ISSUE THREAD

**Issue by Tyree** [eirannejad/pyRevit#733]
Running pyRevit v4.6.23 on Revit 2019.2.
From what I've read, there are some issues with getting dyn files with user interaction to run, but the dyn file I am testing with requires no user interaction, but still doesn't work.

I click the button for it in the pyRevit ribbon, I get the spinning blue wheel like it's working, but it doesn't do what it's supposed to. If I run the same script from Dynamo, it works fine.

The script just adds a sheet number to some note blocks. Not fancy at all compared to some of the other scripts I'd like to get working.

I have other dyn scripts using Data Shapes UI for user interaction. It'd be so sick to get those working via the pyRevit ribbon. Like dream-come-true stuff right there. :-D

Any help is appreciated!

Thanks!
Matt

**Comment by Tyree** [comment]
Ah, the automatic fixed it! Even the Data-Shapes UI seems to work. Excellent!

Seriously. This is so nice. We are ecstatic to be able to have custom tools that appear native within Revit.

THANK YOU

**Comment by eirannejad** [comment]
@Tyree You are most welcome and thanks for the kind words.
