### ISSUE TITLE
nobutton doesn't show up in search

### ISSUE THREAD

**Issue by Tyree** [eirannejad/pyRevit#735]
Trying to figure out the .nobutton bundles. I set one up, from what I can tell, just like your test bundles under Dev tools, but when I search the bundle isn't found.

Is there a naming convention I need to follow or something?

Doesn't look like you're listing them in a _layout file or anything.

Thanks!

**Comment by eirannejad** [comment]
Search meaning using the pyRevit 'Search' tool?

**Comment by Tyree** [comment]
Correct. That's the only way to get to nobuttons, right?

**Comment by eirannejad** [comment]
Ya. Which pyRevit version? Do you see the exisitng `.nobutton` tools in dev extensions in the search?

**Comment by Tyree** [comment]
4.6.23 on Revit 2019.2
I do see the test .nobutton tools when I search.
Maybe it has something to do with my other issue not being able to enable my custom extension?

**Comment by eirannejad** [comment]
The search tool had a bug that I fixed a while ago. It might be that. Would you be able to test with 4.7-beta4?

**Comment by Tyree** [comment]
Sure. Can I do that via the Revit GUI or do I need to manually download the master?

**Comment by Tyree** [comment]
Search does work on beta. But, I get this error when loading Revit:
![beta_errors](https://user-images.githubusercontent.com/5395363/67799344-8ca37000-fa5b-11e9-89d1-0965adf0ce81.PNG)

**Comment by eirannejad** [comment]
They're okay. You are loading a newer version so it's informing you about deprecate api that needs change on your side. The error at the bottom is intentional and is a test. It only shows when the dev extension is loaded which is not public.

**Comment by Tyree** [comment]
Gotcha. So, with the deprecation of _layout, am I safe to use the yaml files even with 4.6.23? Everyone in the office will be on 4.6.23, so I want what I do to work for them. Should I just stick with _layout?

**Comment by eirannejad** [comment]
I'm the single maintainer on this project so never had the time to maintain multiple major versions. 4.7 final is coming this weekend. Last 4.6 version is 4.6.24 and has some bug fixes but that's the final 4.6. It's better to stay on the most recent always. You can also dig in and fix the issue and send me PRs and I'll be happy to review and merge and up the 4.6 version but I'd rather have users move to 4.7 as soon as they can. bundle files are a 4.7 concept so keep the _layout files for backward compatibility.

**Comment by eirannejad** [comment]
@Tyree RE the response above, I'm closing this issue since its solved in v4.7. Keep the conversation going tho. I'd be happy to support in any way I can.

**Comment by Tyree** [comment]
Alright. We'll move to 4.7. Is there an exe for installing that? I upgraded mine by copying the files from the repository. I assume there will be an exe available when 4.7 final comes out?

**Comment by eirannejad** [comment]
Look at the Assets under each [Release](https://github.com/eirannejad/pyRevit/releases)

**Comment by Tyree** [comment]
Sorry. I'm a github novice. :-D
Thanks for all the help and for all your hard work on pyRevit. I've had pyRevit for a while, but had never done much with it. Once I started digging into it, wow! And now adding our own Dynamo tools to it??? Incredible. Kudos!!!
