### ISSUE TITLE
Import Family Config does not tag reporting parameters

### ISSUE THREAD

**Issue by jmcouffin** [eirannejad/pyRevit#738]
**Describe the bug**
While importing Family Config, it states it cannot do it for reporting parameters

**Expected behavior**
either managing applying it to reporting parameters or filter these out and report on these

**Screenshots**
![image](https://user-images.githubusercontent.com/7872003/68128107-637d5680-ff17-11e9-8de0-77af740865fa.png)

**Desktop (please complete the following information):**
 - OS: Win10 Pro
 - pyRevit Version Latest Release

**Comment by eirannejad** [comment]
Please share the config file you are trying to import or describe steps to replicate.

**Comment by jmcouffin** [comment]
sorry, won't be lazy next time!

**steps**

1.  adding shared parameters (as instances) in a RFA file
2. setting a shared parameter instance to Reporting value
3. export config file with pyrevit family export config tool
4. creating a new family (door) from a basic template, 
5. importing the previously saved config file containing one or more reporting parameter

**config file**
[exportConfig_withAndWithoutReportingParam.zip](https://github.com/eirannejad/pyRevit/files/3807882/exportConfig_withAndWithoutReportingParam.zip)

**error message**
> ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:Cannot set the value of a reporting parameter.
> 
> IronPython Traceback:
> Traceback (most recent call last):
>  File "C:\Users\JEAN-MARC\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Project.panel\ptools.stack\Family.pulldown\Import Family Config.pushbutton\script.py", line 362, in <module>
>  File "C:\Users\JEAN-MARC\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Project.panel\ptools.stack\Family.pulldown\Import Family Config.pushbutton\script.py", line 328, in ensure_types
>  File "C:\Users\JEAN-MARC\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Project.panel\ptools.stack\Family.pulldown\Import Family Config.pushbutton\script.py", line 192, in set_fparam_value
> Exception: Cannot set the value of a reporting parameter.
> 
> 
> Script Executor Traceback:
> Autodesk.Revit.Exceptions.InvalidOperationException: Cannot set the value of a reporting parameter.
>  à Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
>  à Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
>  à Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  à Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
>  à IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
>  à PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by eirannejad** [comment]
Resolved and will be published with the next release.
