### ISSUE TITLE
Extensions vs extension behaviour and Git

### ISSUE THREAD

**Issue by jmcouffin** [eirannejad/pyRevit#742]
Not sure if a bug or something I don't get. Sorry about that/

I tried oud the extension capability in pyRevit and everything is fine. once I try to implement the behaviour having the extensions loaded on a git, there is something I don't quite get:

extensions.json pointing @ two extensions: myFirst.extension folder and the second one both having a proper organisation and content. (myFirst.tab, myFirstpanel, myFirst.pushbutton, script.py, icon.py, etc)

if I point to the github local folder everything is fine but if i point to a different folder that contains the extensions.json file only, it does not get properly the content of the git.

If I work with each folder.extension containing an extension.json file plus the folders mentionned before it is working (locally).

Thinking about deploying properly for my team, what is the proper process?

what I am guessing but what is not working should be:

setting up the pyrevit config ini to point to the shared folder (or copying that content for every user locally) that would contain the extensions.json pointing to the right git for my team

inside this git, having : (extension.json, myFirst.tab, myFirstpanel, myFirst.pushbutton, script.py, icon.py, etc) and so one for all subsequent extensions

all in all, what is the proper way to organize things: what should be on the git, what should be set up on my team members computers?

If you have an example of a git brach that works with a two extensions setup, I will be happy to try it.

**Comment by eirannejad** [comment]
This is really hard to understand from reading the description. Would you mind sending a few screenshots of the directory structure?

**Comment by jmcouffin** [comment]
yeah sorry. I will try to make myself much more clear.

actually no! I got one of these 'ah ah!' moment. Finally.

What I could not get was the relation between the extension.name folder and what needed to be on the git, the structure folder

so here starts the story ;p

----

so the proper process in my own words:

1. in the settings

2. set a folder 

3. It should contain your extensions.json file with proper code in it pointing to your extension and its github:

```
{
    "extensions": [{
            "builtin": "True",
            "default_enabled": "True",
            "type": "extension",
            "rocket_mode_compatible": "True",
            "name": "extensionNameCanBeWhatever",
            "description": "my first company extension",
            "author": "Your Name",
            "author_profile": "https://yourProfile.com",
            "url": "https://github.com/UserNAme/pyRevit_Extensions_whatever.git",
            "website": "https://badassWebsiteOfYouOwn.com",
            "image": "",
            "dependencies": []
        }
    ]
}
```
![image](https://user-images.githubusercontent.com/7872003/68337871-b30f7e00-00e1-11ea-9dfb-007de54c4839.png)

4. your local git folder and remote one should look something like this: 

![image](https://user-images.githubusercontent.com/7872003/68338048-fb2ea080-00e1-11ea-8d9b-8136b3200323.png)

### _not with the  folder foo.extension/bar.tab/etc. but starting at bar.tab/etc._ that is what caused me to not get why it was not working

![image](https://user-images.githubusercontent.com/7872003/68338647-42696100-00e3-11ea-9bea-a7d1072431af.png)

5. After that, in the extensions menu you will be able to install your extension

![image](https://user-images.githubusercontent.com/7872003/68338659-49906f00-00e3-11ea-90d0-05d2edac685c.png)

6. upon using the update button, pyrevit will grab instantly any changes in your git.




----
I will let the reply I started typing with all my questions for references, I might not be the only one going in circles before figuring it out.
----


1.  **what worked**

- pointing to my local git repository  with this inside:
![image](https://user-images.githubusercontent.com/7872003/68335496-db48ae00-00dc-11ea-835f-bd84a7f2cd2b.png)

my cloud git looks like this
![image](https://user-images.githubusercontent.com/7872003/68335540-f0254180-00dc-11ea-971a-c06a11a53aab.png)
so basically it does not update anything. It just validates whate is local.

2.  **what did work but defeat the purpose**
- second options that works but does not make sense as it double the function having extensions.json at root pointing at the two extensions and inside each extension having the extension.json describing its own extension.

![image](https://user-images.githubusercontent.com/7872003/68335726-4eeabb00-00dd-11ea-81a1-73cced712a95.png)

3.  **what did not work**

- what does not work also is adding the data of my extensions to the Extensions.json inside the py-master forlder

![image](https://user-images.githubusercontent.com/7872003/68336471-c40ac000-00de-11ea-9fa9-96b3ee9e77d6.png)

### ** restating my question**

- what is the proper worflow to distribute your extensions hosted on a single github to your team?

subsequent questions

- where should the config file (config.ini) point? and what should this folder contain? extensions.json or myName.extension folder and its content or the local github content or something else? for it to work by syncing with the git.
- what should be the proper structure of the github files and folder?
- using extensions.json and then myName.extension/extension.json is doubling the task right?

**Comment by jmcouffin** [comment]
That might help for the documentation: 
![image](https://user-images.githubusercontent.com/7872003/68340342-8dd13e80-00e6-11ea-889a-63a67702c203.png)

**Comment by eirannejad** [comment]
Oka sweet. I'll update the wiki docs to make it more clear.
