### ISSUE TITLE
Sum Total: Weight

### ISSUE THREAD

**Issue by RevitMatt** [eirannejad/pyRevit#743]
Hi,

I would like to have a option for Weight under the "Sum Total" tool. 

When I use the sum total tool on a selected a wall panel or assembly, I would like an option of total weight of that wall panel or wall assembly, including all layers in the wall panel or wall assembly. 
A bonus would be if you could also subtract any openings in the wall from the total calculated weight.

I have tried to make schedules to convey this information, and I am able to get the weight of each individual layer in the wall, such as sheathing, studs, EPS, but I cant get a total weight of all materials in a single wall or wall assembly. 

If you could add this for me it would be greatly appreciated, if not, thanks anyway.

Cheers,

Matt

**Comment by eirannejad** [comment]
Is there a builtin Weight property?

**Comment by RevitMatt** [comment]
There is a density (kg/m³) option for each layer in the materials browser

**Comment by david939david** [comment]
@RevitMatt Just thinking - if you can get weight of every element in assembly, maybe you could get what you want by "Add calculated parameter" in schedule "Fields"?
