### ISSUE TITLE
pyrevit-cli will not clone from zip archive

### ISSUE THREAD

**Issue by two9seven** [eirannejad/pyRevit#744]
I have installed pyrevit-cli and I am trying to clone from a zip archive on my network. I have downloaded https://github.com/eirannejad/pyRevit/tree/v4.7.4-final.zip and I try the command: 

pyrevit clone mytest base --source="c:\programdata\pyrevit-4.7.4-final.zip

But all I get is the help docs. 

What am I doing wrong?

**Comment by eirannejad** [comment]
`pyrevit clone mytest base --image="c:\programdata\pyrevit-4.7.4-final.zip"`

That's what the help docs say :D

```
Usage:
    pyrevit clone <clone_name> <deployment_name> [--dest=<dest_path>] [--branch=<branch_name>] [--log=<log_file>]
    pyrevit clone <clone_name> --image=<image_url> [--dest=<dest_path>] [--log=<log_file>]
    pyrevit clone <clone_name> [--dest=<dest_path>] [--source=<repo_url>] [--branch=<branch_name>] [--log=<log_file>]

    Arguments & Options:
        <clone_name>             Name of this new clone
        <deployment_name>        Deployment configuration to deploy from
        --dest=<dest_path>       Clone destination directory
        --source=<image_url>     Clone source image url or path
        --source=<repo_url>      Clone source git repo url
        --image=<image_path>     Clone from a custom image (.zip archive)
        --branch=<branch_name>   Branch to clone from
```

**Comment by two9seven** [comment]
FYI in the Manage pyRevit clones page here: 
https://www.notion.so/Manage-pyRevit-clones-e9f789f9431346b482021f2a87a6dabf

Its says:

### Installing Custom Clones

You can also use the clone command to install your own pyRevit clones from any git url. This is done by providing `--source=<repo_url>` or `--source=<archive_url>` depending on if you’re cloning from a git repo or an archive.

`$ pyrevit clone mypyrevit --source="https://www.github.com/my-pyrevit.git" --dest="C:\pyRevit\mypyrevit" --branch=develop`

Or install from a ZIP archive using `<deployment_name>`:

`$ pyrevit clone mypyrevit base --source="\\network\my-pyrevit.ZIP" --dest="C:\pyRevit\mypyrevit"
`

According to this, you can use the deployment name with a zip archive.

**Comment by eirannejad** [comment]
@melnikovalex Hey all these active PRs were accidentally closed when I deleted the beta4 branhc yesterday. I'm working to bring them back. I think I need to recreate the branch maybe. Will test today.
