### ISSUE TITLE
Install Error - Threat Found

### ISSUE THREAD

**Issue by oooarch** [eirannejad/pyRevit#747]
**Describe the bug**
During the install process my antivirus software (bitdefender) picks up and deletes two threats and the installation cannot be completed.
pyrevit-autocomplete.exe
pyrevit-toast.exe

**To Reproduce**
1. Run install package
2. Antivirus found  threats during extract process and deletes 2 files
3. Cannot complete installation

**Expected behavior**
Complete installation

**Screenshots**
![image](https://user-images.githubusercontent.com/36985429/68527663-511d6700-02e1-11ea-8b09-95b2b90cc0ca.png)
![image](https://user-images.githubusercontent.com/36985429/68527665-62ff0a00-02e1-11ea-9662-3f92701f1cfb.png)

**Desktop (please complete the following information):**
 - OS: Window 10 v 1903
 - pyRevit Version 4.7.4

**Comment by eirannejad** [comment]
Thanks for the feedback. Seems like many antiviruses mark these two binaries as potentially harmful. Not sure why. I use Symantec and have never had any issues.

**Comment by JohnFNordmark** [comment]
We get the same error. We run Bitdefender.
Any workaround, other than disable the virus protection?

**Comment by eirannejad** [comment]
Nothing as of now. I can not replicate this issue. Both of these binaries are compiled using Go and are faily new. I'm assuming these are false positives but need to verify

**Comment by jneilliii** [comment]
Same issue here with Cisco AMP for Endpoints.  The detection is seen as `Gen:Variant.Razy.569148` for the autocomplete.  The full VirusTotal report can be seen [here](https://www.virustotal.com/gui/file/9cc5a31085e13f9fb885e2b467152949fd63d1047ba3666685fba22ed1dacd13/detection).

**Comment by pippomu** [comment]
Same issue here with Bitdefender antivirus. Solved disabling protection temporarily.

**Comment by jorisvdmeulen** [comment]
Yup BitDefender removes pyrevit-autocomplete.exe pyrevit-toast.exe during install.

Some machines give a popup error: can't find toast.exe ... allowing me to ignore this and finish the install. Some other machines don't give me the popup and are therefor forever stuck on the install (rollback is the only option).

BitDefender is run as policy thing. So I can't temp. disable it.

Is copying pyrevit folders to another machine an option? Or does the install affect regedit as well?

**Comment by JohnFNordmark** [comment]
Our IT department made an exeption for these files in the settings for Bitdefender. After that we could install PyRevit.
