### ISSUE TITLE
Revit 'Selection Box' doesn't work with linkify

### ISSUE THREAD

**Issue by melnikovalex** [eirannejad/pyRevit#748]
**Describe the bug**
Hey Ehsan, 
maybe it is not a pyRevit issue. But it disturbs me since long ago already. It limits the ways of usage of `linkify`.

If you selected an element by clicking `linkfy` you cannot see it in 3d using 'Selection Box' (BX) in Revit. Instead of showing 3d it just resets current view to previous zoom state and makes selection empty

If you deselect an element after that and select it again, and only then click BX, it works. But if there are more elements you want to see in 3d it makes no sense to re-select them.

**Screenshots**
![linkify](https://user-images.githubusercontent.com/1159403/68582814-eeac9e00-047b-11ea-961b-65d20e2391a4.gif)

on the screenshot there is 4.6.18, but 4.7.4 has the same problem

**Desktop (please complete the following information):**
 - OS: Win 10
 - pyRevit Version 4.6.18, 4.7.4
 - pyRevit Environment: 
```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.4" | Path: "D:\Users\aleksei.melnikov\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2019.2.1" | Engine: 277 | Path: "D:\Users\aleksei.melnikov\AppData\Roaming\pyRevit-Master" | Manifest: "D:\Users\aleksei.melnikov\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
D:\Users\aleksei.melnikov\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2019.2.1 | Version: 19.2.10.7 | Build: 20190225_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.18362]
Executing User: HWPNET\aleksei.melnikov
Active User: HWPNET\aleksei.melnikov
Admin Access: No
%APPDATA%: "D:\Users\aleksei.melnikov\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.17.0.0
```

`pyrevit env`

**Additional context**
Btw. since 4.7 output window cannot be narrower than ~500px anymore. 'Show as clickable links` tool wants the window to be 300px and it looks not so nice in 4.7.

Thank you!

**Comment by eirannejad** [comment]
Ya I can replicate the bug. Seems to be Revit related though. I made a few changes and tested with no luck. Seems like Revit doesn't realize the view has been updated but an external event.

**Comment by melnikovalex** [comment]
@eirannejad one strange thing I've also noticed. If you push `esc` after you selected several elements using `linkify`, Revit is somehow able to recover original view state. So it looks like linkify is working in some kind of temporary mode

**Comment by eirannejad** [comment]
@melnikovalex Ya that's how it felt like to me as well. The thing is that the linkify handler, puts the view into [Temporary Isolate](https://github.com/eirannejad/pyRevit/blob/b6c5bfdef28bdce4c83d01796933d427cac19d93/pyrevitlib/pyrevit/runtime/ScriptConsoleUtils.cs#L99) to isolate the selected object, then it [Zooms to Fit](https://github.com/eirannejad/pyRevit/blob/b6c5bfdef28bdce4c83d01796933d427cac19d93/pyrevitlib/pyrevit/runtime/ScriptConsoleUtils.cs#L110) to fit the object in screen, and [then turns off the temporary override](https://github.com/eirannejad/pyRevit/blob/b6c5bfdef28bdce4c83d01796933d427cac19d93/pyrevitlib/pyrevit/runtime/ScriptConsoleUtils.cs#L113). But it seems like Revit is missing something there and the view is not fully reset?!

**Comment by melnikovalex** [comment]
@eirannejad Would it be better with `UIDocument.ShowElements` ?

**Comment by eirannejad** [comment]
@melnikovalex :rolling-eyes-emoji: Where was this method before!!! hahahaaa. I'm switching to this. Works very well.

**Comment by eirannejad** [comment]
Thanks @melnikovalex . Resolved and works well now,
