### ISSUE TITLE
PyRevit prevents CTC HIVE (20.0.0) from opening - Revit 2020 (2)

### ISSUE THREAD

**Issue by jonasth87** [eirannejad/pyRevit#752]
Hi Ehsan,

I have exactly the same issue as #667 .

**Describe the bug**
Revit 2020 opens, pyrevit loads without issues. When the user launches CTC HIVE, a window opens CTC HIVE trys to run, then Revit crash.

**To Reproduce**

Open Revit.
Go to CTC software tab
Click on HIVE
See Revit Crash

**Expected behavior**
I expected to be able to run pyrevit and CTC HIVE at the same time.

Desktop:

OS: Windows 10
pyRevit Version 4.7.4

pyRevit Environment:
```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.4" | Path: "C:\Users\thalamas\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2020.1 Update" | Engine: 277 | Path: "C:\Users\thalamas\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\thalamas\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
master | Product: "2019 Update for Trial Build" | Engine: 277 | Path: "C:\Users\thalamas\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\thalamas\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
master | Product: "2017 First Customer Ship" | Engine: 277 | Path: "C:\Users\thalamas\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\thalamas\AppData\Roaming\Autodesk\Revit\Addins\2017\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\thalamas\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2020.1 Update | Version: 20.1.0.81 | Build: 20190725_1135(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
2019 Update for Trial Build | Version: 19.0.1.1 | Build: 20180328_1600(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
2017 First Customer Ship | Version: 17.0.416.0 | Build: 20160225_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> Running Revit Instances
PID: 8672 | 2020.1 Update | Version: 20.1.0.81 | Build: 20190725_1135(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2020"
==> User Environment
Microsoft Windows 10 [Version 10.0.18362]
Executing User: ETP\thalamas
Active User: ETP\thalamas
Admin Access: No
%APPDATA%: "C:\Users\thalamas\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.17.0.0
```

I attached the Revit crash Journal ( we can see the CEFsharp issues spotted above, and the pyRevit debug )

Thank you Ehsan for your amazing work. Hope you can find a solution.

Jonasth87

[pyrevit.debug.Jonasth87.txt](https://github.com/eirannejad/pyRevit/files/3842443/pyrevit.debug.Jonasth87.txt)
[Revit.crash.journal.jonasth87.txt](https://github.com/eirannejad/pyRevit/files/3842468/Revit.crash.journal.jonasth87.txt)

**Comment by eirannejad** [comment]
pyRevit doesn't use CefSharp so I doubt that's the issue. Rename `pyrevit.addin` file to `Zpyrevit.addin` to push it to load as the last adding after CTC HIVE and see if Revit loads.

**Comment by jonasth87** [comment]
Thanks for your answer, unfortunately that doesn't change anything. Revit is still crashing with the same journal.

**Comment by empowers** [comment]
I have been talking to ATG and CTC. They sent this for me to try. It didn't work but maybe it would work for others. 
From ATG Tech Support: 
First, make sure the pyrevit.addin file is saved here:  C:\ProgramData\Autodesk\Revit\Addins\2020

Next, edit the pyrevit.addin file to contain the file path back to the .dll files. The path should be this: C:\Users\%username%\AppData\Roaming\pyRevit-Master\bin\engines\277\pyRevitLoader.dll

Finally, remove the system.windows.interactivity.dll from the CommonRevit folder, located here:  C:\ProgramData\CTC\CommonRevit
