### ISSUE TITLE
set print settings error

### ISSUE THREAD

**Issue by Thomas84** [eirannejad/pyRevit#755]
**Describe the bug**
I wanted to try the new print tool.
I have used Revit 2020.1 opened as english version, using the rac_basic_sample_project.rvt
Created a plan schedule (I couldn't find an example for the "Sheet Index Schedule")
As soon as I click on "Set Print Settings" I got an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/5624034/68874484-8e2e9280-0701-11ea-95ac-364f5b312060.png)

**Desktop (please complete the following information):**
 - OS: win10
 - pyRevit Version 4.7.4:277:2020.1
 - pyRevit Environment: ==> Registered Clones (full git repos)

```
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.4" | Path: "C:\Users\thomas.vogt\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2020" | Engine: 277 | Path: "C:\Users\thomas.vogt\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\thomas.vogt\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
master | Product: "2019.2 (Update)" | Engine: 277 | Path: "C:\Users\thomas.vogt\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\thomas.vogt\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
master | Product: "2018.3.2" | Engine: 277 | Path: "C:\Users\thomas.vogt\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\thomas.vogt\AppData\Roaming\Autodesk\Revit\Addins\2018\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\thomas.vogt\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2020 | Version: 20.1.1.1 | Build: 20190731_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
2019.2 (Update) | Version: 19.2.0.65 | Build: 20181217_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
2018.3.2 | Version: 18.3.2.7 | Build: 20181011_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018"
==> Running Revit Instances
Error: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
```

Html error file:
[pyRevit_setPrintSettings.zip](https://github.com/eirannejad/pyRevit/files/3847489/pyRevit_setPrintSettings.zip)

**Comment by eirannejad** [comment]
Would you mind sending me a snapshot of the Revit about window that has the version and build number? For Revit `20.1.1.1`

**Comment by eirannejad** [comment]
Thanks for the error. I can replicate this and am looking into it.

**Comment by Thomas84** [comment]
> Would you mind sending me a snapshot of the Revit about window that has the version and build number? For Revit `20.1.1.1`

![image](https://user-images.githubusercontent.com/5624034/68881257-1a928280-070d-11ea-8cf7-ae3781300ee2.png)

**Comment by eirannejad** [comment]
Resolved.

@Thomas84 Seems like this is a language-specific Revit release. I don't see it here in my north-america autodesk account. Do you have a link to the release notes? [similar to this ](https://help.autodesk.com/view/RVT/2020/ENU/?guid=RevitReleaseNotes_2020updates_2020_1_html)

**Comment by Thomas84** [comment]
> Resolved.
> 
> @Thomas84 Seems like this is a language-specific Revit release. I don't see it here in my north-america autodesk account. Do you have a link to the release notes? [similar to this ](https://help.autodesk.com/view/RVT/2020/ENU/?guid=RevitReleaseNotes_2020updates_2020_1_html)

maybe this one: https://up.autodesk.com/2020/RVT/Advance_Steel_Extension_for_Revit_2020_Hotfix_1_ReleaseNotes.htm 
but I'm not sure

**Comment by eirannejad** [comment]
Nope. I have that installed but it didn't increase my version number
