### ISSUE TITLE
Run Dynamo files without having to set them to automatic run

### ISSUE THREAD

**Issue by jmcouffin** [eirannejad/pyRevit#756]
Having to set a dynamo script to Automatic Run is very annoying when debugging and having to go back to dynamo to edit it, You hve to set it back to manual if you don't want to go in circles with infinite loops depending on your script.

Obviously I can edit it in a text editor and change it back to manual everytime I need to check the dynamo script in Dynamo

**Proposed solution*
Keep the script intact in manual and implement a way to set it to Automatic before running the script itself in pyrevit. That could be something low tech such as a text substitution script that runs before launching the script itself and run again after completion.

**Comment by eirannejad** [comment]
There are two different dynamo file formats. The legacy ones are in XML and the new files are stored in JSON. If a text substitution is used to modify the source file, it needs to be compatible with both dynamo file versions. Let me see if maybe there is a switch on dynamo itself.

**Comment by jmcouffin** [comment]
This is file dependant from what I have seen. When I look at the dynamo config file, it only shows `  <OpenFileInManualExecutionMode>true</OpenFileInManualExecutionMode>`
But that does not help as I think it is overriden by the file setup itself.

- In 1.2 /1.3, the option is in the file header:

`<Workspace Version="1.2.0.2831" X="1591.6913656997" Y="663.348725037616" zoom="0.828948783544117" Name="Home" Description="" **RunType="Manual"** RunPeriod="1000" HasRunWithoutCrash="True">`

- In 2.x it is located in the views section: 


```
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.1.5055",
      "RunType": "Manual",
      "RunPeriod": "1000"
```

the difference in syntax is just: 

> : 

for a 

> =

**Comment by htlcnn** [comment]
@jmcouffin xml is different from json. You need different python libs to parse them. Thanks for pointing out the settings.

**Comment by eirannejad** [comment]
@jmcouffin I'm testing the Dynamo test script that I have in pyRevit and it runs fine both in Automatic and Manual mode. What's an example of a script that does not run in pyRevit if it is set to Manual?

**Comment by jmcouffin** [comment]
you could try these two: 
[2Scripts.zip](https://github.com/eirannejad/pyRevit/files/3876437/2Scripts.zip)

**Comment by eirannejad** [comment]
Oka confirmed this is related to https://github.com/eirannejad/pyRevit/issues/570

Added a new option to `bundle.yaml` engine options especifically for dynamo

```yaml
engine:
  automate: false
```

For dynamo scripts containing GUI, the `automate` engine option must be `false`

Indirectly related to this issue, other dynamo journal options have also been implemented as engine options. See below and [Journal Keys](https://github.com/DynamoDS/DynamoRevit/blob/3aa28a7e1ba560aebb4a060de0f36beb6975c105/src/DynamoRevit/DynamoRevit.cs#L118) on dynamo source for more info

```yaml
engine:
  dynamo_path: String
  dynamo_path_check_existing: Boolean
  dynamo_force_manual_run: Boolean
  dynamo_model_nodes_info: String
```
