### ISSUE TITLE
pyRevit CLI 'pyrevit releases' not working

### ISSUE THREAD

**Issue by jrostar** [eirannejad/pyRevit#758]
**Describe the bug**
pyRevit CLI 0.17 installed. When I try command 'pyrevit releases' I get the following message:

`Error: The remote server returned an error: (403) Forbidden.
Run with "--debug" option to see debug messages`

When I add the --debug option, I get the attached CMD Screenshot

![image](https://user-images.githubusercontent.com/5134621/69489565-998b6780-0e3f-11ea-9fb4-59116eee7904.png)

**Comment by eirannejad** [comment]
Huh. For some reason Github API is returning an error. Okay I'll test. This definitely used to work. Maybe something changed on github side.

**Comment by eirannejad** [comment]
Resolved the bug. Will publish with next version
