### ISSUE TITLE
PyRevitLoader error in Revit 2017

### ISSUE THREAD

**Issue by jagostinhoCT** [eirannejad/pyRevit#762]
![pyRevit Loader Error Revit 2017](https://user-images.githubusercontent.com/43812310/69954803-1a0f2f80-14f4-11ea-8922-8b35c43afe57.png)

**Comment by eirannejad** [comment]
Seems like this is an issue with pyRevit being installed inside the OneDrive path. Does it work if it is on your local drive?

**Comment by jagostinhoCT** [comment]
It is working now, still using the OneDrive path.
Not sure what happened.
Thank you for your help. Apologies for the trouble.
