### ISSUE TITLE
pyrevit.readthedocs.io needs to be fixed, deprecated or redirected to notion

### ISSUE THREAD

**Issue by tatlin** [eirannejad/pyRevit#764]
**Describe the bug**

https://pyrevit.readthedocs.io/ is still a live website but has no content anymore

I was searching for some pyRevit CLI docs to teach someone how to develop against it. Google search took me to this blank website https://pyrevit.readthedocs.io/ (no content anymore)

I recall things were being transitioned to notion, is that still the case for auto-generated dev docs? It would be better to redirect to the new content location if we are using notion for everything now

https://www.notion.so/Developer-Docs-2c88f3ecccde422d9504e20b6b9e04f8

**Comment by eirannejad** [comment]
The auto-generated dev docs will still https://pyrevit.readthedocs.io/ are still gonna be available as the documentation for the python core. The new [pyRevit Wiki (notion) points to any auto-generated](https://www.notion.so/pyrevitlabs/pyRevit-Python-Module-0c0e118ba8984a308399e470a39c45cd )documentation outside the Wiki

I'll take a look a the repo and will cleanup these docs for clarity.

- [ ] Cleanup https://pyrevit.readthedocs.io/. Point back to Wiki

**Comment by tatlin** [comment]
there is something wrong with the autogenned content then. the structure is appearing correctly in readthedocs but there is no content on each page (at least for me using Chome on Win10). see image:

![image](https://user-images.githubusercontent.com/1142008/70148562-6ed9b400-1674-11ea-8c53-cc43ddb1802e.png)

**Comment by eirannejad** [comment]
Woops. Yeap. This is odd. Okay will fix this

**Comment by sanzoghenzo** [comment]
Hi,
I found that there's a working documentation hosted at https://pyrevit1.readthedocs.io/en/latest/# (notice the `1` after `pyrevit` in the subdomain).
I don't know if it's just a typo in some CI automation or somebody else published it.

**Comment by eirannejad** [comment]
Fixed. Resuming doc updates for pyRevit
