### ISSUE TITLE
.NET Core Update

### ISSUE THREAD

**Issue by eirannejad** [eirannejad/pyRevit#765]
.NET Core 2 has been flagged as end of life by microsoft.

https://dotnet.microsoft.com/download/dotnet-core

pyRevit labs dependencies need to be updated to use .net core 3

**Comment by adamrees89** [comment]
Microsoft is now recommending version 3.1

**Comment by eirannejad** [comment]
pyRevit's dependency on .net core is for the libgitsharp DLL and that has not been upgraded to .net core 3 yet. This will be automatically taken care of sometime in the future when libgitsharp upgrades. Closing for now.
