### ISSUE TITLE
Could not add reference to assembly ProtoGeometry

### ISSUE THREAD

**Issue by AliSafieddine** [eirannejad/pyRevit#766]
**Describe the bug**
I am experiencing this note error lately, It was working well but today i ran my scripts and I am facing thins problem out of no where! I tried to uninstall ironpython and installing the newer one but with no success.

![1](https://user-images.githubusercontent.com/46194284/70438641-f1a8a780-1a96-11ea-8b72-57432e34c96f.PNG)

![2](https://user-images.githubusercontent.com/46194284/70438660-f79e8880-1a96-11ea-88ec-a203149c0ec7.PNG)

Thank you

**Comment by eirannejad** [comment]
Not sure what's the issue. Make sure IronPython can find the ProtoGeometry dll. Add the path to the system paths (`sys.path`) and then attempt to load using `clr` module

**Comment by AliSafieddine** [comment]
can you please guide me how to do that and where to find the protoGeometry dll file?
thank you

**Comment by AliSafieddine** [comment]
Actually non of the clr.AddRefrence libraries is working. I think I have a major issue here where the script is not reading the library from IronPython. your help is highly appreciated!

**Comment by htlcnn** [comment]
@AliSafieddine for ProtoGeometry or any of Dynamo's dll, you should run Dynamo/Dynamo Player BEFORE running any pyRevit command. Please read the discussion in this issue: #385

**Comment by htlcnn** [comment]
@AliSafieddine issue https://github.com/eirannejad/pyRevit/issues/385 has a solution. This issue can be closed now.

**Comment by kuldeep3618x** [comment]
@eirannejad @AliSafieddine  Solved Dynamo compatiblity issues with pyRevit. 
**Option 1:**
 - Uninstall Dynamo 2,0  and pyRevit works fine

**Option 2:** 
- Have Dynamo version 1.3.4 along with Dynamo 2.00 or above installed on your machine.  Before running pyRevit Addin, on a new Revit window open Dynamo version 1.3.4 and close it. 
- Now you can run pyRevit scripts with ease.

**Comment by eirannejad** [comment]
So I guess you can rename `pyRevit.addin` manifest file to `ZZpyRevit.addin` so it loads after all other addons
