### ISSUE TITLE
List family size Creator not taking letters with accents properly

### ISSUE THREAD

**Issue by jmcouffin** [eirannejad/pyRevit#773]
**Describe the bug**
![image](https://user-images.githubusercontent.com/7872003/70806862-86bfdf00-1dbc-11ea-9e3d-8594a833010c.png)

**To Reproduce**
1. load attached family in project (rename .txt for .rfa)
2. use List Family Size Creator

**Expected behavior**
Attached family should be listed with the following name: TEST_AN_TITRE DÉTAIL.rfa

**Desktop (please complete the following information):**
 - OS: Win10 pro
 - pyRevit Version 4.7

[TEST_AN_TITRE DÉTAIL.txt](https://github.com/eirannejad/pyRevit/files/3961211/TEST_AN_TITRE.DETAIL.txt)

**Comment by eirannejad** [comment]
So in python when you are printing a tuple, you are actually printing a "Representation" of the tuple.

```python
s = ('Unicode String 中文; ', 0, 12)
print(s)
```

This prints

```
(u'Unicode String \u4e2d\u6587; ', 0, 12)
```

**Comment by jmcouffin** [comment]
is there a simple way to print it with the proper characters instead of the "Representation"?

**Comment by eirannejad** [comment]
You could do something like this.

```python
s = ('Unicode String 中文; ', 0, 12)

print('(' + ', '.join(str(x) for x in s) + ')')
```
