### ISSUE TITLE
pyRevit Addin not loaded - Revit 2020.2

### ISSUE THREAD

**Issue by TheBIMsider** [eirannejad/pyRevit#774]
**Describe the bug**
I have pyRevit 4.7.4 installed and the below has happened to me

"If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`"

The outcome was:
![2019-12-16_11-29-42](https://user-images.githubusercontent.com/37883693/70933074-7136f900-1ff8-11ea-8a0a-997dc850022a.png)

I followed the FAQ as well and below is what you see on my machine when I run "pyrevit env"
![2019-12-16_11-34-12](https://user-images.githubusercontent.com/37883693/70933117-8f045e00-1ff8-11ea-8345-151fe71a1dc0.png)

**Desktop:**
 - OS: Windows 10 (version 1903)
 - pyRevit Version: 4.7.4

When I ran the debug the attach .txt is what was reported

[pyRevit_4.7.4_Bug_report_CStorms.txt](https://github.com/eirannejad/pyRevit/files/3969627/pyRevit_4.7.4_Bug_report_CStorms.txt)

I have had previous versions of pyRevit installed without issue, as recent as the last stable version of 4.6

I also have Revit 2019.2.2 and 2018.3.3 installed the addin does not appear in those versions either

Carl

**Comment by clarkc** [comment]
I am having this exact issue. I even uninstalled the 4.7.4 and tried to revert back to 4.6.24 and nothing is appearing in my Revit. We are running versions 2018/2019/2020 on our machines.

**Comment by eirannejad** [comment]
@TheBIMsider Would you mind running `pyrevit update` and then `pyrevit revits --supported` to see if Revit 2020.2 will be listed?

**Comment by TheBIMsider** [comment]
Hello @eirannejad 

I did all you asked above and still no luck. So then I tried the original FAQ answer 

_pyrevit attach master 277 --installed_ (after doing all of your steps above)

and that fixed it, all is good now

Thanks!

**Comment by eirannejad** [comment]
Added the `2020.2.1.1` info to the host info file in pyRevit repo.

`pyrevit update` should pull this new updated file to `%appdata%/pyRevit/Cache` and pyRevit will know about this Revit version from now on.

**Comment by rockerape** [comment]
had the similar issues on my 2020.2.3 and `pyrevit attach master 277 --installed` work like a charm. thanks
