### ISSUE TITLE
pyRevit 4.7.4 Installer Failed

### ISSUE THREAD

**Issue by AmandaLunger** [eirannejad/pyRevit#775]
Hi there,

I am having trouble installing pyRevit 4.7.4 with the installer. When I attempt to run the installer, I get a message that the pyRevit Setup Wizard ended prematurely. Here is the log:

[MSI3C65.tmp.LOG](https://github.com/eirannejad/pyRevit/files/3975317/MSI3C65.tmp.LOG)

**Comment by eirannejad** [comment]
Resolved and will be pushed with next release
