### ISSUE TITLE
Freeze a View into a Drafting View

### ISSUE THREAD

**Issue by dsellam** [eirannejad/pyRevit#776]
**Is your feature request related to a problem? Please describe.**
When Drafting, we sometimes wants to make a few drawings quickly with five options in 2D only

**Describe the solution you'd like**
Select a view - Freeze -> get a drafting view with the same

**Describe alternatives you've considered**
found this : https://www.linkedin.com/pulse/replicating-freeze-drawings-dynamo-python-gabriel-nones-newman/

and this : 
https://forums.autodesk.com/t5/revit-architecture-forum/revit-2018-extensions-freeze-drawings/td-p/7327038

**Additional context**

**Comment by Siversmith** [comment]
There used to be a Revit command like this. For some reason it was removed very quickly. You can actually download it again and then apply it to your current Revit. Although I wouldn't really use it as it essentially gives you an autocad block within in Revit. 

https://forums.autodesk.com/t5/revit-architecture-forum/revit-2018-extensions-freeze-drawings/td-p/7327038
