### ISSUE TITLE
Installer 4.7.4 stuck

### ISSUE THREAD

**Issue by Randombluescreen** [eirannejad/pyRevit#778]
Hi everyone

Here's my problem: when i try to install pyrevit from the installer, in the extraction phase, It remains stuck at "extracting files from archive" with the completion bar full. I checked the relative folder in %temp% and the Its dimension remains at 25.9 MB. 
![image](https://user-images.githubusercontent.com/59050314/71165716-a68a5380-2251-11ea-839d-c7a416ca1bbd.png)
There's no error, no logs, nothing.
I already run the installer with administrator privileges.

Thank you.

**Comment by pippomu** [comment]
Hi @Randombluescreen , i had same problem.
I solved installing on a **different folder** than the default one.
**IMPORTANT:** if requested by destination folder, run installer as administrator.

**Comment by Randombluescreen** [comment]
Thanks @pippomu .
I found another way: if you start windows in safe mode, and enable the installation service with this cmd line
`rem enable windows installer in safe mode
REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\SafeBoot\Minimal\MSIServer" /VE /T REG_SZ /F /D "Service"
rem enable windows installer in safe mode with networking
REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\SafeBoot\Network\MSIServer" /VE /T REG_SZ /F /D "Service"
net start msiserver`
the installation works fine.

I'm closing the issue.
