### ISSUE TITLE
"authusers" in extensions.json not working

### ISSUE THREAD

**Issue by ariccb** [eirannejad/pyRevit#780]
**Describe the bug**
I watched this youtube video of yours: [https://www.youtube.com/watch?v=v8d5FA-7suw](url)
and tried to set up my extensions.json file to only allow me to see the pyRevitCore extension, but it only hid it no matter what i put in for username. I used my autodesk A360 username. 

Now that pyRevitCore is hidden from me, closing and restarting Revit doens't bring it up again, even after changing default enabled to "True", and deleting the "authusers" line of code in the json file.

`pyrevit attach master 277 --installed`

**Expected behavior**
I expected that the pyRevitCore functionality would be visible to only me.

**Screenshots**
![image](https://user-images.githubusercontent.com/48956351/71202071-a9d50d80-2258-11ea-818f-6cca2481ca8f.png)
![image](https://user-images.githubusercontent.com/48956351/71202128-c3765500-2258-11ea-8eab-4f2fadc57f8b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version [e.g. 22]
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

**Additional context**

**Comment by eirannejad** [comment]
I can not replicate this issue. `authusers` are working as intended. Check your pyRevit config file under `%APPDATA%/pyRevit` and make sure the `pyRevitCore` extension is not disabled

```ini
[pyRevitCore.extension]
disabled = false
```
