### ISSUE TITLE
When I use function name of "prints sheet", {rev_number} does not adjusted per sheet.

### ISSUE THREAD

**Issue by DevENG-GS** [eirannejad/pyRevit#781]
**Describe the bug**
When I use function name of "prints sheet", {rev_number} does not adjusted per sheet.
It may be call a sequence of the revision table on view tap

**To Reproduce**
Just when I using {rev_number}

**Desktop (please complete the following information):**
 - OS: Win10
 - pyRevit Version 2.7

**Additional context**
Print rev_number need to change rev. number on the sheet.

**Comment by eirannejad** [comment]
Let me make sur eI'm understanding this correctly. So when you add `{rev_number}` to a custom naming pattern in the **Print Sheets** tool, it does not use the actual lastest Revision Number on each sheet? What does it output then?

**Comment by DevENG-GS** [comment]
Look at these pictures for correct understanding.
Generally, revision number meaning of the each sheet's revisions number.

But, pyRevit display revision sequence in "Sheet Issues/Revisions".
I don't know it is intended or not.

If I ware you, when the print sheet using, call a revision number as per sheet.
Because that is more helpful.


![Sequence of Revision Settings](https://user-images.githubusercontent.com/45479794/71329125-61716480-2564-11ea-83bc-3061a47963a0.png)
![Print Sheet Capture - PyRevit](https://user-images.githubusercontent.com/45479794/71329126-61716480-2564-11ea-8a46-8ffada5f9fc7.png)
![Sample Case - Sheet101](https://user-images.githubusercontent.com/45479794/71329127-6209fb00-2564-11ea-873e-af13de6ad576.png)
![Sample Case - Sheet102](https://user-images.githubusercontent.com/45479794/71329128-6209fb00-2564-11ea-815f-e18a7ade6788.png)
![Sample Case - Sheet103](https://user-images.githubusercontent.com/45479794/71329129-6209fb00-2564-11ea-9385-5d57884c3f0a.png)
![Sample Case - Sheet104](https://user-images.githubusercontent.com/45479794/71329130-6209fb00-2564-11ea-9c8d-07576701b423.png)

**Comment by deddolo** [comment]
Is Revision numbering per sheet what you're after? If you haven't tried already, you can switch Revit revision numbering from a per-project to per-sheet basis.

**Comment by eirannejad** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/841

**Comment by eirannejad** [comment]
Fixed and will be published with next release
