### ISSUE TITLE
Print from sheet from sheet index shows filtered sections

### ISSUE THREAD

**Issue by AmandaLunger** [eirannejad/pyRevit#787]
**Describe the bug**
When using the pyRevit Print Sheets tool, sections that are filtered out in the view's view template end up on the PDF. The sections appear to be filtered out when viewed in Revit or printed to PDF with Revit's native print process, but when printed with pyRevit they show up in the PDF.

**To Reproduce**
1. Create a floor plan and section views
2. Place the floor plan on one sheet and the sections on another sheet 
3. Create a filter in the floor plan view template that filters out sections based on sheet number, and filter out the section views.
4. Create a sheet list that includes both the floor plan sheet and the sections sheet
5. Use the pyRevit Print Sheets command, and select the sheet list you created, and select 'Combine Into One PDF'. 

**Expected behavior**
The section callouts that were filtered out of the floor plan when viewed in Revit should appear in the printed PDF. It seems that only filters that operate by Sheet Number are overriden. Filters by Family or Family and Type seem to work fine. Also, this behavior only occurs when the sheet with the section views is also being printed. If the section view sheet is filtered out of the sheet list used to print, the plan sheet prints as expected. This behavior only seems to happen when Combine Into One PDF is selected.

**Screenshots**
plan as viewed within revit, with section views filtered out: 
![image](https://user-images.githubusercontent.com/58994763/71742671-64e3d600-2e17-11ea-89df-522f0e3d37ec.png)

plan as viewed within Bluebeam, with section views shown:
![image](https://user-images.githubusercontent.com/58994763/71742738-9197ed80-2e17-11ea-8572-d915018d4dd7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - pyRevit Version 4.7.4
 - pyRevit Environment:

```
C:\Users\amandal>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
main | Deploy: "base" | Branch: "master" | Version: "4.7.4" | Path: "C:\pyRevit"
==> Attachments
main | Product: "2020.1 Update" | Engine: 277 | Path: "C:\pyRevit" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2020\pyRevit.addin"
main | Product: "2019.2 (Update)" | Engine: 277 | Path: "C:\pyRevit" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2019\pyRevit.addin"
main | Product: "2018.3.1" | Engine: 277 | Path: "C:\pyRevit" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2018\pyRevit.addin"
main | Product: "2017.2.3" | Engine: 277 | Path: "C:\pyRevit" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2017\pyRevit.addin"
main | Product: "2015 Update Release 14" | Engine: 277 | Path: "C:\pyRevit" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2015\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\amandal\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2020.1 Update | Version: 20.1.0.81 | Build: 20190725_1135(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
2019.2 (Update) | Version: 19.2.0.65 | Build: 20181217_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
2018.3.1 | Version: 18.3.1.2 | Build: 20180423_1000(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018"
2017.2.3 | Version: 17.0.1150.0 | Build: 20171027_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
2015 Update Release 14 | Version: 15.0.421.0 | Build: 20160512_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit Architecture 2015"
==> Running Revit Instances
PID: 17132 | 2019.2 (Update) | Version: 19.2.0.65 | Build: 20181217_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> User Environment
Microsoft Windows 10 [Version 10.0.18363]
Executing User: NT\amandal
Active User: NT\amandal
Admin Access: No
%APPDATA%: "C:\Users\amandal\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.17.0.0
```

**Comment by eirannejad** [comment]
I have a hunch you are filtering the sections based on their sheet range .pyRevit uses Revit's native printing engine so the end results are identical. However, pyRevit print adds non-printable characters to the start of sheet numbers to force Revit to sort them correctly when printing. I think your section filters are filtering content that "Starts with" a specific string. Since pyRevit changes the sheet number slightly for sorting, it will fail the filter.

Try changing to fiter to something less rigid for example a "Contains" filter would be better.
