### ISSUE TITLE
Failing First CPython Command example: "object does not implement IExternalEventHandler"

### ISSUE THREAD

**Issue by mbaicad** [eirannejad/pyRevit#788]
I'm just getting started using pyRevit with Revit2020 and wanted to try the CPython example from [here](https://www.notion.so/Create-Your-First-CPython-Command-b8a7718c554645d1a18454c0b363e3c9).

However, I'm getting a `TypeError : object does not implement IExternalEventHandler` trying to import revit in the python script.
The same error occurs on a minimal:
```
#! python3
from pyrevit import revit
```

Any ideas on how to fix this error?

**Comment by eirannejad** [comment]
The `pyrevit` python module is not fully compatible with Cpython yet and has a few bugs. You can access the Revit instance using the builtin variables however. 

See https://www.notion.so/pyrevitlabs/Python-Runtime-Variables-1ae28b25faca48ff8c291d68e8010541

**Comment by mbaicad** [comment]
Thanks for the hint.
Just wanted to try the example but somehow the builtin variables behave differently than the access methods (in IronPython). I tried the following:

```
for element in revit.get_selection():
    print(element)
```
and
```
for element in __elements__:
    print(element)
```

These got me different results running in the same script, so the same objects should selected in Revit.

The second code actually runs in CPython as well yielding the same output as in IronPython.

Refering to https://www.notion.so/pyrevitlabs/Python-Runtime-Variables-1ae28b25faca48ff8c291d68e8010541, I'd have expected all outputs to be the same.

P.S.: Is there any timeline when the full compatibility with CPython will be ready?

**Comment by eirannejad** [comment]
No timeline as of yet. Extending pyRevit core over Cpython is going to be quite a challenge. Imma close this for now but will keep you posted on improvements
