### ISSUE TITLE
Hooks: Run script after command

### ISSUE THREAD

**Issue by alexdaversa** [eirannejad/pyRevit#789]
Is there a way to run a script after a (specific) command has executed? Say if I want to use a script to modify sheet parameters directly after a new sheet is created. It looks like the API and the hooks documentation only provide a way to either run a script before the new sheet command or to override the entire new sheet command, both of which are unhelpful.

Or would using view-activated work? Seems like it would cause performance issues since it happens so frequently but I would have to test it out...

**Comment by eirannejad** [comment]
Currently there is no event from Revit that is fired after a command is executed hence there is no hook implementation for that. You can however use the `journal-updated` hook to detect command executions from the Journal content
