### ISSUE TITLE
Manage Tags 'create' options

### ISSUE THREAD

**Issue by andymp2000** [eirannejad/pyRevit#790]
**Describe the bug**
When selecting either 'create tag 3D view' or 'Create tag filters, I get the error

![image](https://user-images.githubusercontent.com/36314709/72158189-8e6da600-33b1-11ea-8cb9-9ffaa9d688ee.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.7.4

**Comment by eirannejad** [comment]
This was due to API depracation in Revit 2020. I added a fix and will publish with 4.7.5  soon
