### ISSUE TITLE
Tab Coloring Toggle on at Start

### ISSUE THREAD

**Issue by nrosatiaz** [eirannejad/pyRevit#791]
Is there a way to set the Tab Coloring toggle to be set to 'on' when you open a model.

Scenario:
I open my model and the Tab Coloring button is on.

![image](https://user-images.githubusercontent.com/51798827/72170807-899ff680-339f-11ea-9b0c-48f0e0c0e69a.png)

**Comment by eirannejad** [comment]
Yes see the pyRevit settings under UI/UX:

![Revit_TBBVQrEb8a](https://user-images.githubusercontent.com/8197916/73089661-002c1080-3ed7-11ea-8da5-cf130152e100.png)

**Comment by nrosatiaz** [comment]
Perfect. Thank you

Nick



Sent via the Samsung Galaxy S® 5 ACTIVE™, an AT&T 4G LTE smartphone


-------- Original message --------
