### ISSUE TITLE
ListElementOfSelectedLevel

### ISSUE THREAD

**Issue by JPAR58** [eirannejad/pyRevit#794]
**Describe the bug**
ListElementOfSelectedLevel returns NameError: name 'output" is not defined

`pyrevit attach master 277 --installed`

**To Reproduce**
1. Go to 'Analysis'
2. Click on 'Analyse'
3. Scroll down to 'List Element Of Selected Level(s)'

**Expected behavior**
Show list of elements in selected layer(s)

**Screenshots**

![ListElementOfSelectedLevel error](https://user-images.githubusercontent.com/59892616/72378424-5632d400-36df-11ea-807c-4a2dcedf6d18.png)

**Desktop (please complete the following information):**
 - OS: [Win 7]
 - pyRevit Version [4.7.4]
 - pyRevit Environment:

> Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.4" | Path: "C:\
Users\jep\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2020" | Engine: 277 | Path: "C:\Users\jep\AppD
ata\Roaming\pyRevit-Master" | Manifest: "C:\Users\jep\AppData\Roaming\Autodesk\R
evit\Addins\2020\pyRevit.addin"
master | Product: "2019.2.2 Hotfix" | Engine: 277 | Path: "C:\Users\jep\AppData\
Roaming\pyRevit-Master" | Manifest: "C:\Users\jep\AppData\Roaming\Autodesk\Revit
\Addins\2019\pyRevit.addin"
master | Product: "2018.3.2" | Engine: 277 | Path: "C:\Users\jep\AppData\Roaming
\pyRevit-Master" | Manifest: "C:\Users\jep\AppData\Roaming\Autodesk\Revit\Addins
\2018\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\jep\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2020 | Version: 20.2.1.1 | Build: 20191106_1200(x64) | Language:
1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 10
33 | Path: "C:\Program Files\Autodesk\Revit 2019"
2018.3.2 | Version: 18.3.2.7 | Build: 20181011_1500(x64) | Language: 1033 | Path
: "C:\Program Files\Autodesk\Revit 2018"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

**Additional context**

**Comment by alexdaversa** [comment]
Hi JPAR58,

I ran into this a few weeks ago and sent in a pull request which has been merged--that is to say the issue will be fixed in the next release. See https://github.com/eirannejad/pyRevit/pull/754 The code is also shown below with one additional line (output):

```
__contact__ = 'https://github.com/frederic-beaupere'
__credits__ = 'http://eirannejad.github.io/pyRevit/credits/'

output = script.get_output()

all_elements = DB.FilteredElementCollector(revit.doc)\
                 .WhereElementIsNotElementType()\
```
https://github.com/eirannejad/pyRevit/pull/754/commits/b1e29e25ca6901b41d5be49246ab12dbaf86925a

**Comment by eirannejad** [comment]
I'll publish the 4.7.5 version soon with this fix

**Comment by JPAR58** [comment]
Thanks. (I added the line per  #754<https://github.com/eirannejad/pyRevit/pull/754>. It worked)
Looking forward to 4.7.5!


James Parrish  /  Project Manager BIM Coordinator
[MM_logo_2014_FM_Black - PNG]
214 N. Duke Street     Lancaster, PA 17602     T/ 717.393.3211  Ext 122     marottamain.com<http://www.marottamain.com/>
