### ISSUE TITLE
Keynote Manager Compatibility with BIM360

### ISSUE THREAD

**Issue by Siversmith** [eirannejad/pyRevit#795]
Good day, we currently have our keynotes saved on to our server in order to use Pyrevit's keynote manager.

We would prefer to actually have this living on BIM 360 but Pyrevit doesn't seem talk with BIM360. 

We have tested everything we are aware of and looked here if any others had similar issues but have yet to find anything related to this.

**Comment by eirannejad** [comment]
Keynote manager is designed to primarily work with the external text files. The issue is that BIM360 cost lots of money and I haven't been able to test the keynote manager on BIM360.

Let me know if you can provide a shared model that I can use to test

**Comment by Siversmith** [comment]
Will have to see with my company about something like that. The PyRevit tool set is really useful for many different reasons.

**Comment by Siversmith** [comment]
I have spoken to my line manager and it is currently being discussed. Hopefully will get an answer about this soon.

**Comment by Dsperry3** [comment]
![2020-03-06 08_55_22-Window](https://user-images.githubusercontent.com/60263995/76094507-5eddb300-5f88-11ea-9bc2-cd78051741ab.jpg)
I would be interested in hearing the outcome of this.  We utilize BIM360 as well and I promote putting the keynote file with the model.  I would like to utilize the keynote manager and realize the file can reside on a local store and be fine but would prefer to have it on BIM360.

**Comment by Siversmith** [comment]
Still no response on my side with regards to this. I would love to be able to give a testing space for this but I don't have the rights to give access to our BIM360.

**Comment by Architectuur** [comment]
Any update on this? Would love to have the option to use the keynote manager on BIM360.

**Comment by eirannejad** [comment]
I got the keynote file access issue resolved. Keynote manager can now read the keynote text file that is synchronized using the Autodesk Desktop Connector. I have learned that this is the way the keynote text file is supposed to be linked to the models.

Who wants to help me test?

**Comment by Architectuur** [comment]
I have a BIM360 project that I could test this in. Let me know what you need.

**Comment by eirannejad** [comment]
@Architectuur Thanks. I'll upload an installer here later today so you can install and test

**Comment by Dsperry3** [comment]
I have several BIM360 projects I could try and test in.  It will take getting IT involved for me since I do not have admin rights to my machine but should be able to make it work.

**Comment by eirannejad** [comment]
Okay let's do an in-place fix to avoid messing with the admin issues. Download the two files from here and replace (make backups of the originals first) the existing ones in the installation directory. The paths listed here are inside the installation directory so if your pyRevit is installed under `%APPDATA%/pyRevit-Master` then the full path of `api.py` would be `%APPDATA%/pyRevit-Master/
pyrevitlib/pyrevit/api.py`

- `pyrevitlib/pyrevit/api.py`
- `pyrevitlib/pyrevit/revit/db/query.py`

[Replacement Files.zip](https://github.com/eirannejad/pyRevit/files/5272058/Replacement.Files.zip)

**Comment by Architectuur** [comment]
![image](https://user-images.githubusercontent.com/69218770/94073630-0a2f4780-fdb5-11ea-9e65-72d8b61b2d5a.png)
![image](https://user-images.githubusercontent.com/69218770/94073666-16b3a000-fdb5-11ea-88b4-ee29c3c94640.png)

**Comment by eirannejad** [comment]
@Architectuur Okay great. The "Download" progress bar seems to be more of a sync process. It seems like the keynote file stays updated and saves the changes.

**Comment by Architectuur** [comment]
@eirannejad Correct, the changes are saved. 
I have not tested with other users yet. I will let you know if issues come up with that. 

Is there something more I can send you to help fix the conversion issue?

Great work, thank you for implementing this!

Any chance you want to add the edit key function when you roll this out? ;)

**Comment by eirannejad** [comment]
Yeah I'm planning to add that now that I need to make change to the underlying code. Please test away and let me know if you see other major issues.

**Comment by Dsperry3** [comment]
Thanks @eirannejad but I have a new machine and need a full install of pyRevit before I can test.  Currently working on a fast deadline but will try to get to this next week.

**Comment by Siversmith** [comment]
Hi there, currently testing it within Revit2019. It has linked fine but when I open it I get this error.

**Comment by Siversmith** [comment]
Currently testing this. I get this error when I open it from the BIM360: file. 

"This Element does not represent an external file."

**Comment by eirannejad** [comment]
@Siversmith Did you replace the two files uploaded here?

**Comment by Siversmith** [comment]
@eirannejad no I didn't. Went ahead and did so after you mentioned it. Once done it gives me another error. I tried to change my pathing for it within the standard process and I can't seem to access bim360 and can only do so within pyRevit. I am thinking that Revit 2019 is the issue and not pyRevit. I would need to test it out on another project that has 2020 or 2021.

**Comment by eirannejad** [comment]
@Siversmith I'm assuming you have the Autodesk Desktop Connector installed as well right? It'd be great of you can share screenshots of the errors as well

**Comment by Dsperry3** [comment]
probably want to make sure your Autodesk Desktop Connector is up to date...  It does not automatically update and has been a problem when not everyone on a team has the most current version.....   currently 14.1.0.1074

**Comment by eirannejad** [comment]
I also might have figured out a way to circumvent the ADC's issue of not keeping files always updated. Will publish a new round of fixes soon with this for more testing

**Comment by Siversmith** [comment]
My connector is definitely up to date. I still think it is a 2019 issue. Haven't been able to open a project yet for 2020 or 2021 yet to see if it is.

**Comment by eirannejad** [comment]
Implemented and will be pushed with the next version for testing

**Comment by apsis0215** [comment]
@eirannejad  @Siversmith  Would desktop connector work? Use that to Sync Pyrevit with the BIM 360 so others can use that file? or is PyRevit locking out the File?

**Comment by eirannejad** [comment]
@apsis0215 if the Revit model is linking to a keynote text file in the ADC drive, pyRevit considers that BIM360 and uses the ADC API to sync the file. It does not create locks for that file, instead when a user opens keynote manager with the BIM360 keynote file, pyRevit will ask ADC to lock the file on the server. Locks get free'd when the keynote manager is closed
