### ISSUE TITLE
pyRevit 4.7.4 does not load on Revit 2020.2

### ISSUE THREAD

**Issue by cpercer** [eirannejad/pyRevit#796]
**Describe the bug**

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

Ran with same results as pyRevit env, see screenshot below

**Desktop (please complete the following information):**
 - OS: Windows 7
 - pyRevit Version 4.7.4
 - pyRevit Environment: 

![pyRevit env](https://user-images.githubusercontent.com/44647473/72543307-299bcb00-384b-11ea-9c32-b9f4e5c4082a.JPG)

**Additional context**
Last working version was 4.6.24

**Comment by eirannejad** [comment]
Seems like the `pyRevitLabs.TargetApps.Revit.dll` is missing from the pyRevit binaries. Try installing pyRevit again. Usually this fixed the issue.

**Comment by cpercer** [comment]
Issue is resolved with repair.
