### ISSUE TITLE
tooltip for 'Who did that??' is incomplete

### ISSUE THREAD

**Issue by RevitIRL** [eirannejad/pyRevit#798]
**Describe the bug**
not sure if this should be filed as a bug or feature request...

pyRevit > [Project] > Team > Who did that??

tooltip shows "Report the username of whoever reloaded the keynotes last."

but there are two other options: "Who Created Active View?" and "Who Created Selected Element?"

**To Reproduce**
hover over button: pyRevit > [Project] > Team > Who did that??

**Expected behavior**
a more complete description of what the tool can do

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Win10
 - pyRevit Version v4.5:6c7a348
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

**Additional context**

**Comment by eirannejad** [comment]
Thanks for the issue report. Fixed and will be published with 4.7.5
