### ISSUE TITLE
pyRevit is running a dynamo script on its own?

### ISSUE THREAD

**Issue by Tyree** [eirannejad/pyRevit#799]
I've been using pyRevit to set up a ribbon with some custom dynamo scripts. It works great.

I just set up a Dynamo script that allows me to change titleblocks on sheets without opening the sheets. The script works great if I run it manually, but I get strange behavior when I use pyRevit to run it.

The Dynamo script uses Data-Shapes UI. When run, a box pops up and let's the user check any sheets to change the titleblock on and then gives a list of titleblocks loaded in the file to choose from. Click the submit button and it changes the titleblock. That much works fine.

Then the UI pops back up on its own. Weird.

Then I realized if I change the titleblock manually by just clicking on it and changing its type, the Dynamo UI pops up again.

So, I'm assuming since the script is set to automatic, it just keeps running itself again each time the titleblocks in the Revit file change.

I'm not sure if this is even something pyRevit can solve. Just curious if this issue has been dealt with before.

Thanks!
Matt

**Comment by eirannejad** [comment]
So pyRevit asks the running Dynamo to execute the script. This issue sounds similar to [this](https://github.com/eirannejad/pyRevit/issues/756#issuecomment-557319215). Read the thread as it might have useful information for dynamo bundles.

See if turning off the engine:automate will fix the issue please.

```yaml
engine:
  automate: false
```

**Comment by Tyree** [comment]
No luck with adding the:
```
engine:
  automate: false
```
 I'll look at that thread and see if it can help.

**Comment by eirannejad** [comment]
Need example to test. Open the issue when a test dynamo file is available
