### ISSUE TITLE
Highlight/Updated marker to clear after set number of days

### ISSUE THREAD

**Issue by jorisvdmeulen** [eirannejad/pyRevit#800]
**Currently** 
in bundle.yaml we can use `highlight: updated` or `highlight: new` for that matter. Which seems to be active forever. 

**Describe the solution you'd like**
I'd like to see the orange dot disappear after hovering over the specific button, or having used that button once, or after two weeks.

**Describe alternatives you've considered**
`hightlight: new, 10` where 10 is the number of days to stay active.

**In action**
1. I hover over new function: after Revit restart orange dot is gone.
2. I use the button (kinda redundant I realise) Revit restart: dot is gone
3. I don't use / hover of the function, and after 10 days, the dot is gone.

**Comment by eirannejad** [comment]
Great suggestion. I like it a lot. The current behavious is the way the UIAutomation API behaves. Let me think of a reasonable way to implement this.

**Comment by jorisvdmeulen** [comment]
Thinking about creating some sort of cookies as seperate file in user folder?

**Comment by eirannejad** [comment]
Yeah probably. Some cookie file under `%APPDATA%/pyRevit` that remembers user states and choices.

**Comment by jmcouffin** [comment]
**Closing**
Issue older than a year.
Thanks for pointing it out.
If you feel it is still relevant, feel free to reopen the issue
