### ISSUE TITLE
Malware detection in installer

### ISSUE THREAD

**Issue by martinservold** [eirannejad/pyRevit#804]
We use ESET Antivirus.

Using the latest 4.7.4 installer from git hub, ESET said pyRevit contained a version of the Win64/Kryptik.BQT Trojan.
“The Malwarebytes research team has determined that Trojan.Agent Kryptik is a Trojan Clicker. Typically these are used to perform online actions in order to boost hit-counts.”
Here’s a snap of the ESET console showing the file deletions:

![ESET 1](https://user-images.githubusercontent.com/44454303/73093582-73685f00-3ea4-11ea-98d1-0c2857a27e1f.png)

Here’s a closer look at the file paths where you can see the pyRevit filenames:

![ESET 2](https://user-images.githubusercontent.com/44454303/73093591-76634f80-3ea4-11ea-90a9-b9b0b868d5ed.png)

Pyrevit seemed to install correctly even though the files were quarantined.

Do you have any knowledge of this issue?

**Comment by eirannejad** [comment]
There are various antivirus applications that mark some of the binaries or dlls as having some kind of virus. I run an antivirus check on the binaries before creating a release. These issues are not consistent and depends are which antivirus is being used.

In your specific case, `pyrevit-autocomplete` is a utility for auto-completing command-line options when using the pyRevit CLI. This should not affect the normal operations of pyRevit.

I'm gonna close this issue but you can continue the discussion
