### ISSUE TITLE
Error writing cache for: <type_id '.extension' name 'pyRevitCore'

### ISSUE THREAD

**Issue by MMueller-1996** [eirannejad/pyRevit#807]
Greetings,

I recently installed pyRevit and got an Error Message (see below) this is how i got to it:
1. Install Revit 2019
2. Install pyRevit 4.7.4
3. Start Revit 2019
4. Configure pyRevit Settings (I set debug Options with the debug window and ASCII output) 
5. Restart Revit
6. Error message

To clarify:
Now This error persists every time i open Revit. pyRevit is not accessable anymore.

Expected behavior:
pyRevit loads like it did the first time.

![Error Message](https://user-images.githubusercontent.com/60429339/73355358-4945e100-4298-11ea-9bd6-266fa7469116.png)

Enviroment:
![pyrevit env](https://user-images.githubusercontent.com/60429339/73355377-51058580-4298-11ea-81dc-ca8e288ca8da.png)

Additional context:
I already tryed resolving this issue by reinstalling pyRevit, as well as clearing the cache with "caches clear --all". This didnt work though. However i found something that could be helpful: When I typed "pyrevit -V" in the prompt, i get the CLI Version as well as a message that my Remoteserver (i m operating on a virtual PC) gives an Error 403. Then it also alsk me to run "--debug". So I did. Here you see the result (maybe it is helpful?):
![pyrevit --debug1](https://user-images.githubusercontent.com/60429339/73355804-3da6ea00-4299-11ea-853c-7d4282a43a8b.png)
![pyrevit --debug2](https://user-images.githubusercontent.com/60429339/73355821-47c8e880-4299-11ea-99ca-d0db0e331572.png)

**Comment by eirannejad** [comment]
`pyrevit -v` tries to access github to check whether you have the most recent version or not. I don't think that is the issue. Seems like the issue is related to pyRevit caching extension info

Run the command below and test

```
pyrevit caches clear --all
pyrevit configs bincache enable
```

**Comment by MMueller-1996** [comment]
Dear eirannejad,

that actually worked! I already executed the first command before, but the 2nd command "pyrevit configs bincache enable" seems to have made the "magic" happen. 
Almost boring how easy it actually was.

Have a nice day!

**Comment by eirannejad** [comment]
Resolved and will be pushed with next release
