### ISSUE TITLE
How to get bundle metadata from sessionmgr?

### ISSUE THREAD

**Issue by htlcnn** [eirannejad/pyRevit#808]
Hi @eirannejad,
I'm using `pyrevit.sessionmgr.find_all_commands()` to get all pyRevit commands of type `PyRevitExternalCommandType`. I want to access bundle metadata such as `__title__`, `__author__`,... from this object. Is it possible? Is there any method to get all bundle metadata?
Thanks.

**Comment by eirannejad** [comment]
There is `pyrevit.extensions.extensionmgr.get_command_from_path()` that parses the path for a command. It will return a command object e.g. `pyrevit.extensions.components.PushButton`. You can read the metadata from this object. See `pyrevit.extensions.genericcomps.GenericUICommand`
