### ISSUE TITLE
pyRevit - Dynamo Script Startup

### ISSUE THREAD

**Issue by JAMA-KB1989** [eirannejad/pyRevit#809]
Hello Ehsan / Other pyRevit Reps,

I know that you currently have a startup.py extension for python scripts / executions on the startup.  Do you happen to have a startup.dyn script extension option?

And if not, what would a startup.py python code look like to run a dynamo script after initial startup?  If you could let me know, I would greatly appreciate it.

Sincerely,
Kevin

**Comment by eirannejad** [comment]
Due to complexities of running Dynamo script (it is completely dependent on the Dynamo runtime) this feature has bot been implemented yet.

**Comment by jmcouffin** [comment]
**Closing**
Issue older than a year.
Thanks for pointing it out.
If you feel it is still relevant, feel free to reopen the issue
