### ISSUE TITLE
PYREVIT-AUTOCOMPLETE.EXE as Malware

### ISSUE THREAD

**Issue by jsancheztemb** [eirannejad/pyRevit#813]
Malwarebytes detects it as a Malware
[PYREVIT-AUTOCOMPLETE.txt](https://github.com/eirannejad/pyRevit/files/4133905/PYREVIT-AUTOCOMPLETE.txt)

**Comment by eirannejad** [comment]
Yes. Some antivirus software mark these binaries as containing malware. I'm testing the build before creating a release an nothing shows up on my machine.
