### ISSUE TITLE
How can I run a script from another script in pyrevit? 

### ISSUE THREAD

**Issue by tillbaum** [eirannejad/pyRevit#814]
Hey Ehsan, 
How can  I run a script from another script in pyrevit.  

I think I have seen this explained in an earlier version of the docs, but I can't find this in current one.
Thank you.

**Comment by htlcnn** [comment]
#708

**Comment by tillbaum** [comment]
Thank You

**Comment by tillbaum** [comment]
But Another Thing regarding this issue:  
I cannot use the -- supprocess.call("python some_script.py") -- because this would try to run the script with the python engine installed on the main windows system. ([Error 8] %1 is not a valid Win 32 application)
How can I access the python engine that runs inside pyrevit.  Is this even possible?

**Comment by htlcnn** [comment]
Simply append your path to sys.path, then import it. No need to use
subprocess.

**Comment by tillbaum** [comment]
Yes, this works, but only once. 
I am running a modeless Dialog with buttons. Upon a ButtonClick I want to run another Script opening up a Modeless Dialog. 
So when I import The Script via the ButtonClick. The Script is loaded into memory and the Modeless Dialog shows up. If I press the button again the Script is not imported again. It doesn's show up. 
So I need to put this importing of the script into a new Process (maybe the multiprocess module). Something like this.  THank you though for your help.

**Comment by eirannejad** [comment]
You can

```python
from pyrevit.loader import sesssionmgr
sessionmgr.execute_command('pyrevitcore-pyrevit-pyrevit-tools-reload')
```

Get the command id from the **Shift+Windows+Click** menu on the button

**Comment by tillbaum** [comment]
It works like a charm. pyrevit is unbelievable.
