### ISSUE TITLE
The copy State and paste State commands in pyrevit are not valid in the elevation view

### ISSUE THREAD

**Issue by lcwewei** [eirannejad/pyRevit#815]
Dear Ehsan iran-nejad：
       I used revit2018 and pyrevit4.74. I operate in the elevation view, select copy State, click crop Region, then select this view or other elevation view, select paste State, click crop Region, and the following error appears. See the attachment.In flat view there is no such problem.

**Comment by lcwewei** [comment]
![text_report_error](https://user-images.githubusercontent.com/16218099/73518116-69aca180-4438-11ea-8dba-d88c7b77f06d.jpg)

**Comment by mmcgowen23** [comment]
@lcwewei Did you ever figure out the issue? I am having the same problem.
