### ISSUE TITLE
[question] removed "ScriptOutputManager" class from pyrevit.coreutils.loadertypes

### ISSUE THREAD

**Issue by amastrobera** [eirannejad/pyRevit#816]
Dear Ehsan, 

I used to have pyrevit 4.6, and inside a plugin I used `ScriptOutputManager.CloseActiveOutputWindows()` to deactivate other windows  while openining my owns (`System.Windows.Forms`) or do another operation.

I see that class does not exist anymore in pyrevit 4.7.4. Did you replace it by something else ?

**Comment by eirannejad** [comment]
Use this https://github.com/eirannejad/pyRevit/blob/d2eb8ee7cf5aeba0c6f6b24b5c53f4c6fdffb847/pyrevitlib/pyrevit/output/__init__.py#L300

```python
from pyrevit import script
output = script.get_output()
output.close_others(all_open_outputs=True)
```

**Comment by amastrobera** [comment]
thank you Ehsan, that worked :)
