### ISSUE TITLE
Impossible to convert SAT

### ISSUE THREAD

**Issue by Randombluescreen** [eirannejad/pyRevit#817]
Everytime i try to convert an ACIS SAT, It always gives me the message that cannot covert It because is not an ACIS SAT or more elements are selected. I even tried with a SAT file exported from Revit.

**Comment by eirannejad** [comment]
Would you be able to share an example SAT or the actual error report?

**Comment by Randombluescreen** [comment]
![image](https://user-images.githubusercontent.com/59050314/73590290-19d5e500-44e1-11ea-8f18-1da2a88db795.png)

[Fam1.zip](https://github.com/eirannejad/pyRevit/files/4142398/Fam1.zip)

Here's an example of a SAT file. I made this with revit 2019. I even tried SATs from other softwares like solidworks or rhino, the result doesn't change.

**Comment by eirannejad** [comment]
Fixed and will be published with next release
