### ISSUE TITLE
Python to .dll

### ISSUE THREAD

**Issue by kuldeep3618x** [eirannejad/pyRevit#819]
Need help in converting a python script to a dll file, to be distributed to all users.
Please suggest the best possible way forward.

**Comment by eirannejad** [comment]
See these test scripts please.
https://github.com/eirannejad/pyRevit/tree/master/extensions/pyRevitDevTools.extension/pyRevitDev.tab/Debug.panel/Engine%20Tests.pulldown/Test%20IronPython%20Compile.pushbutton
