### ISSUE TITLE
Installing pyRevit and custom extension with pyRevit CLI is not working.

### ISSUE THREAD

**Issue by MulticonsultBergenVVS** [eirannejad/pyRevit#820]
First, I install pyRevit with my extension using these lines:

```
pyrevit detach --all
pyrevit clones forget --all
pyrevit clones delete --all --clearconfigs
pyrevit clone master  --dest="C:\Programdata\pyRevit"
pyrevit extend ui MultiTool https://username:password@github.com/MulticonsultBergenVVS/MultiGIT.git" --dest="C:\ProgramData\pyRevit\Extensions"
pyrevit configs seed
pyrevit configs logs verbose
pyrevit configs checkupdates enable
pyrevit configs autoupdate enable
pyrevit configs rocketmode enable
pyrevit configs filelogging disable
pyrevit configs loadbeta disable
pyrevit configs usercanupdate yes
pyrevit configs usercanextend yes
pyrevit configs usercanconfig yes
pyrevit configs colordocs enable
pyrevit attach master latest --installed --allusers
```

Then I check the env:
![image](https://user-images.githubusercontent.com/44774905/73920004-e3271280-48c4-11ea-87b9-54137e22f78b.png)
This shows my extension being installed and it shows the search path where pyRevit should look for my extension.
When I boot Revit, pyRevit is there, but my extension is not, nor is there any debug-window shown.
In pyRevit-settings, there is no search path, so I change this to the same from the env-window.
![image](https://user-images.githubusercontent.com/44774905/73920620-0f8f5e80-48c6-11ea-8a49-300669a37cc4.png)

I save and reload which produces this error:
![image](https://user-images.githubusercontent.com/44774905/73920643-1a49f380-48c6-11ea-80ed-53316e0dabc3.png)

What am I doing wrong here?

**Comment by eirannejad** [comment]
Fixed and will be published with next release
