### ISSUE TITLE
Enable/Disable Extensions from CLI

### ISSUE THREAD

**Issue by Dre-Tas** [eirannejad/pyRevit#821]
I'm trying to programmatically enable/disable extensions from the CLI unsuccessfully.

With the `pyrevit extensions` command I can see my 2 extensions are installed. If I try to get the info of those extensions the CLI says it cannot find the extension.
If I try with the command `pyrevit extensions enable Wombat` (same for `disable`) no errors pop up but also nothing really happens.
![image](https://user-images.githubusercontent.com/36023527/74008444-f5907180-49d4-11ea-8e28-f22efd2de484.png)

I then tried to do it manually from the GUI (within Revit) and again, I click the button and nothing happens.

Afraid it's the .ini file under ProgramData that pushes back some settings.
![image](https://user-images.githubusercontent.com/36023527/74008078-1e643700-49d4-11ea-98b7-ee738f5dd5c9.png)

If I get rid of the ini file I can do it manually from the GUI, but still not with the CLI.
It is actually not even clear if I have to use the CLI command while Revit is closed, or if I have to do it while it's open.

In general I would like to be able to create a button within my extension that automatically disables one extension and enables the other one. To do that I was thinking to do that calling some CLI commands.
The expected behaviour would have been that, with Revit open, I run the `pyrevit extensions enable Wombat` and that extension appears in Revit.

Am I doing something wrong?

**Comment by eirannejad** [comment]
Resolved and will be pushed with next release
