### ISSUE TITLE
output.print_html use of variables

### ISSUE THREAD

**Issue by epeter-** [eirannejad/pyRevit#822]
i was wondering how variables in print_html are available?

my example (i am failing with) is a variable x in a html  
`<td> x </td>`
statement.
what syntax for x  is available?
tx

**Comment by htlcnn** [comment]
Have a look into:
https://github.com/eirannejad/pyRevit/blob/4afd56ccb4d77e4e0228b8e64d80d1f541bc791e/pyrevitlib/pyrevit/output/__init__.py#L461
and
https://github.com/eirannejad/pyRevit/blob/4afd56ccb4d77e4e0228b8e64d80d1f541bc791e/pyrevitlib/pyrevit/coreutils/__init__.py#L472

It just escapes `< >` and `print`
