### ISSUE TITLE
Telemetry build needs dependencies

### ISSUE THREAD

**Issue by pabloderen** [eirannejad/pyRevit#824]
**Describe the bug**
[Documentation](https://www.notion.so/Telemetry-System-992d72659457447f86b79cf1c9034541#a196100768f840d8b11dfce98f6458cb) establish that Telemetry server doesn't need any dependency but I couldn't build without an extra step to add a s missing auxiliary go library.

Extra step:
`git config --global http.https://pkg.re.followRedirects true`

**To Reproduce**
1. On a linux terminal execute: 
`go build main.go`

**Screenshots**
```
user@####:~/pyRevit/dev/pyRevitTelemetryServer$ go build main.go
cli/logger.go:6:2: cannot find package "pkg.re/essentialkaos/ek.v10/fmtc" in any of:
        /usr/lib/go-1.10/src/pkg.re/essentialkaos/ek.v10/fmtc (from $GOROOT)
        /home/ubuntu/go/src/pkg.re/essentialkaos/ek.v10/fmtc (from $GOPATH)
```

**Desktop:**
 Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

**Solution**
Add step to documentation

**Comment by eirannejad** [comment]
Telemetry build needs dependencies. Telemetry binary does not and that's what the documentation says basically. If server is windows, you can just copy the binary instead of rebuilding it. For macOS and Linux it needs to be built.

I'll update the docs to make this clear. Thanks for the feedback.

**Comment by eirannejad** [comment]
- [ ] Update docs with info on how to build telemetry server https://www.notion.so/pyrevitlabs/Building-Telemetry-Server-5249bdbe4c654edda4751c1853e63823
