### ISSUE TITLE
numpy cannot be imported

### ISSUE THREAD

**Issue by amastrobera** [eirannejad/pyRevit#830]
Dear Ehsan, 

I have install the pyRevit 4.7.4 on Revit 2020, and I try to use CPython libraries. 

I have tried to install them with Anaconda2. 

My environment variables seem well set.
```
PATH=C:\Users\angelo\Anaconda2
PYTHONPATH=C:\Users\angelo\Anaconda2\Lib\site-packages
``` 
While pyRevit settings have 
```
Core Settings -> Active Engine: IronPython 277 (compatible with RPS)
                           Active CPython Engine: CPython 372
```

My test_script.py contains this code 
```
#! python2

logger.debug("importing numpy")
import numpy

logger.debug("done")  
```

The result was 
```
DEBUG - importing numpy 

IronPython Traceback:
Traceback (most recent call last):
 File "xxx\pyRevit\extensions\pyRevit.extension\pyRevit.tab\xxx.panel\xxx.pushbutton\test_script.py", line 4, in <module>
ImportError: No module named numpy

Script Executor Traceback:
IronPython.Runtime.Exceptions.ImportException: No module named numpy
 at Microsoft.Scripting.Runtime.LightExceptions.ThrowException(LightException lightEx)
 at Microsoft.Scripting.Runtime.LightExceptions.CheckAndThrow(Object value)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

I have tried to tweak Active Engine and Active CPython Engine, but the result is always the same. 

I have tried Anaconda3 / python3 instead. Same.

I have tried with PIP2/ PIP3 , same. 

**can you explain me how to do, or point me in the right direction ?**

**Comment by eirannejad** [comment]
`numpy` does not work with IronPython as it has C binaries so it only works with CPython (First line of your script must be `#! python3`

Try adding the package path manually and see if it works:

```python
import sys
sys.path.append(r'C:\Users\angelo\Anaconda2\Lib\site-packages')

# now you can import numpy
import numpy as np
```

**Comment by eirannejad** [comment]
I've closed the issue since this is not a bug, but continue the discussion here and I'll help as much as I can :)

**Comment by bdschust18** [comment]
Good day,

I recently am having similar issues.  I installed Python 3.8 with the latest Anaconda package, so I am running Python 3.8.8.  
The Pandas version with that package is 1.2.5 and the NumPy version is 1.20.1.  
I downgraded Numpy to 1.18.1, which in turn downgraded my Pandas to 1.2.4.  
I set the PYTHONPATH variable to "C:\ProgramData\Anaconda3\lib\site-packages
I did not change anything with the "Path" variable and none of those seem to point to anything Python related.  

The script I am trying to run is below:

---------------------------------------------------------------------------
#! python3
# Create Sheets

import sys
sys.path.append(r"C:\ProgramData\Anaconda3\lib\site-packages")

import pandas as pd

myfile = r"C:\Users\bsch\Documents\REVIT Files\sheet_creation.xlsm"
df = pd.read_excel(myfile, sheet_name = 'Create_sheets')
print(df)
-----------------------------------------------------------------------------

I get the "Importing the numpy c-extensions failed" error.  I have tried uninstalling Numpy and Pandas and reinstalling through PIP and downgrading to Numpy 1.18.1, but I get the same error.

Is this an issue with the "Path" variable or with the Anaconda3 installation?
