### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by martinservold** [eirannejad/pyRevit#831]
With seemingly random scripts and different users, revit will occasionally crash, only occasionally showing an the recovery file error message. This happens when you click on a pyrevit generated button before any UI displays (if any is present in the script).
I ran the script in question for the most recent crash 10+ times on my own computer to verify it was functioning as intended.

 - OS: Windows 10
 - pyRevit Version 4.5 and 4.7.4 via a server hosted clone.

Attached is a log file (with the exception highlighted) and the script (cannot upload .py file) that attempted to run.
[script.txt](https://github.com/eirannejad/pyRevit/files/4233431/script.txt)
[journal.0058.docx](https://github.com/eirannejad/pyRevit/files/4234188/journal.0058.docx)

Do you have any suggestions on what to look for or debug?

**Comment by Siversmith** [comment]
Wouldn't it be wiser to have everyone running on the latest version of PyRevit in order to ensure that errors are minimized across all computers?

**Comment by martinservold** [comment]
Everyone is currently updated to 4.7.4, I just meant the issue existed in 4.5 and has continued to exist into 4.7.4.

**Comment by eirannejad** [comment]
> This happens when you click on a pyrevit generated button before any UI displays (if any is present in the script).

Please be more specific. Does this happen on all commands or specific commands?

**Comment by martinservold** [comment]
I know of at least 5 scripts that this has happened on:
Rename PDFs,
Sync Views (pulled directly from pyrevit and put in our extension, this one would actually run for a while before crashing),
Add Schedule Parameters to Family, 
Show Clash Spheres,
Create Print Set from Revision.
And for sure there are a few more that haven't reported their crashes back to us.
I'll follow up with some of the users and see if the script in question had run successfully in that session of Revit prior to it crashing. 

These are some of our most used scripts, so there may be a reporting bias.

But on talking with some more people, crashes are happening at times where pyrevit is not directly involved:
Synchronizing,
Annotate>Detail Line,
Idling (while away from computer),
When connecting to a laptop dock.

Happens in all Revit versions that we regularly use,
on both server hosted models and cloud hosted models.
It's hard to predict exactly when it's going to happen though.

It's possible this is an un-handled exception within Revit's code somewhere, but I can't rule out pyrevit as the culprit either and I'm not sure how to tell the difference between the two.

**Comment by eirannejad** [comment]
Closing this as it is not specific. Let's report issues on a case by case basic and provide context and error messages that can help debugging the issue
