### ISSUE TITLE
How to embed wpf with IronPython engine?

### ISSUE THREAD

**Issue by htlcnn** [eirannejad/pyRevit#832]
Hi @eirannejad,
I'm trying to create an IronPython engine in AutoCAD, using the simplest method like here: https://github.com/Autodesk/civilconnection/blob/master/Src/CivilPython/CivilPython/CivilPython.cs#L46-L47
I added embedded python stdlib like you did here: https://github.com/eirannejad/pyRevit/blob/develop/dev/pyRevitLoader/Source/ScriptExecutor.cs#L136-L146
when I add these lines into my script:
```python
import wpf
```
it said
```
File "wpf.py", line 11, in <module>
ImportError: No module named _wpf
```
I tried appending my path with
```python
import clr
import sys
sys.path.append(r'C:\Program Files (x86)\IronPython 2.7\Platforms\Net40')
clr.AddReference('IronPython.Wpf')
import wpf
```
but I still had that Exception.
Could you please share some tricks you did to be able to import wpf in pyRevit?
Thanks a lot!

**Comment by eirannejad** [comment]
There is a couple of DLLs that are shipped with IronPython. You need to include and load all of the m. The `IronPython.Wpf` dll includes the `wpf` module code.

![Screen Shot 2020-02-28 at 07 55 05](https://user-images.githubusercontent.com/8197916/75563738-b2d41f00-59ff-11ea-91f1-ad6d7eda752c.png)

**Comment by htlcnn** [comment]
I did it by `clr.AddReference("IronPython.Wpf")`, but still got the same Exception. I also double checked the source C# project that create IronPython engine. It referenced `IronPython.Wpf.dll`
Am I missing anything?

**Comment by eirannejad** [comment]
Is the DLL shipped with the add-on as well?

**Comment by htlcnn** [comment]
No. I'll try shipping it. Thanks.

**Comment by htlcnn** [comment]
I added these lines in my `.cs` file:
```csharp
ipy.LoadAssembly(Assembly.LoadFrom(string.Format(@"{0}\IronPython.dll", GetAssemblyPath())));
ipy.LoadAssembly(Assembly.LoadFrom(string.Format(@"{0}\IronPython.Modules.dll", GetAssemblyPath())));
ipy.LoadAssembly(Assembly.LoadFrom(string.Format(@"{0}\IronPython.SQLite.dll", GetAssemblyPath())));
ipy.LoadAssembly(Assembly.LoadFrom(string.Format(@"{0}\IronPython.Wpf.dll", GetAssemblyPath())));
ipy.LoadAssembly(Assembly.LoadFrom(string.Format(@"{0}\Microsoft.Dynamic.dll", GetAssemblyPath())));
ipy.LoadAssembly(Assembly.LoadFrom(string.Format(@"{0}\Microsoft.Scripting.dll", GetAssemblyPath())));
```

Here the script to test importing wpf. `lib.pprint` is my tool to print to AutoCAD command line:
```python
# -*- coding: utf-8 -*-
import sys
import os
sys.path.append(os.path.dirname(__file__))
from lib import pprint, caddoc, editor
pprint(sys.path)
import clr
for r in clr.References:
    pprint(r)
import wpf
pprint('ok')
```

Here's the output:
```
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Acmgd, Version=22.0.0.0, Culture=neutral, PublicKeyToken=null
Acdbmgd, Version=22.0.0.0, Culture=neutral, PublicKeyToken=null
accoremgd, Version=22.0.0.0, Culture=neutral, PublicKeyToken=null
acdbmgdbrep, Version=22.0.0.0, Culture=neutral, PublicKeyToken=null
IronPython, Version=2.7.0.40, Culture=neutral, PublicKeyToken=7f709c5b713576e1
IronPython.Modules, Version=2.7.0.40, Culture=neutral, PublicKeyToken=7f709c5b713576e1
IronPython.SQLite, Version=2.7.0.40, Culture=neutral, PublicKeyToken=7f709c5b713576e1
IronPython.Wpf, Version=2.7.0.40, Culture=neutral, PublicKeyToken=7f709c5b713576e1
Microsoft.Dynamic, Version=1.1.0.20, Culture=neutral, PublicKeyToken=7f709c5b713576e1
Microsoft.Scripting, Version=1.1.0.20, Culture=neutral, PublicKeyToken=7f709c5b713576e1
PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
```
I assume the dlls were loaded into current engine, but the exception still thrown:
![image](https://user-images.githubusercontent.com/931924/75732337-ce536880-5d24-11ea-9a29-3630af6a90ac.png)

The only thing I did additionally was to embed `python_279_lib.zip` into current engine.

**Comment by htlcnn** [comment]
Sorry for not searching. I've found answer in your code base. Thanks.
https://github.com/eirannejad/pyRevit/blob/23b58850070b549ca1128c414ec8eb018d0dfc13/pyrevitlib/rpw/ui/forms/resources.py#L36-L48

**Comment by eirannejad** [comment]
😆 You're awesome. I didn't even remember this. It's from a long time ago

**Comment by htlcnn** [comment]
TIL it's always good to comment your code.
