### ISSUE TITLE
Get rid of Bundle Name, Class Name and Assembly Name from tooltip

### ISSUE THREAD

**Issue by Dre-Tas** [eirannejad/pyRevit#834]
All our users are complaining that the tooltip gets really messy and confusing due to the presence of the Bundle Name, Class Name and Assembly Name info.

Is there a way to prevent that from showing up as they don't really need to see that?

Thanks!

**Comment by eirannejad** [comment]
I can add an option to the settings to turn off these extra tooltip information. This is fairly easy to implement so will ship with the next version.

**Comment by Dre-Tas** [comment]
Great! Keep me up to date ;)

**Comment by eirannejad** [comment]
Implemented and will be shipped with next release. pyRevit settings / UX now has an option to add debug info to tooltips. It will be off by default.

![Screen Shot 2020-03-12 at 16 21 32](https://user-images.githubusercontent.com/8197916/76576027-23f2e800-647e-11ea-8def-69114c67cdca.png)

**Comment by Dre-Tas** [comment]
Beautiful, thanks!
