### ISSUE TITLE
Can Pyrevit4.74 support DynamicModelUpdate?

### ISSUE THREAD

**Issue by lcwewei** [eirannejad/pyRevit#835]
Dear Ehsan Iran-Nejad:
       I wonder how to implement the UpdaterData interface in pyrevit?

**Comment by htlcnn** [comment]
Please follow example in Revit Developers Guide. Wherr did you get stucked?

**Comment by eirannejad** [comment]
New **Updaters** can only be added by IExternalApplication so I think you need to create a separate add-on for that. Besides these kind of applications are more appropriate as a separate C# add-on I think.

**Comment by lcwewei** [comment]
Thank you very much.I know it can be created through C#, but I am not familiar with C#, so I hope it can be implemented through pyrevit.
