### ISSUE TITLE
pyRevit does not load

### ISSUE THREAD

**Issue by threexe** [eirannejad/pyRevit#836]
**Describe the bug**
Replace these lines with your description. Be as specific as possible and list steps to reproduce the issue. If you have any suggestions for the solution please list that as well.

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

**To Reproduce**
1. Open Revit

**Expected behavior**
Revit Open - PyRevit to load

**Screenshots**
![PyRevit Error 1](https://user-images.githubusercontent.com/61331314/75301448-ae391c00-57ef-11ea-89a2-89d78d0485ef.JPG)
![PyRevit Error](https://user-images.githubusercontent.com/61331314/75301450-aed1b280-57ef-11ea-851b-c3130b5e6dce.JPG)

**Desktop (please complete the following information):**
 - pyRevit Version [e.g. 22]
 - pyRevit Environment: 

![image](https://user-images.githubusercontent.com/61331314/75301415-9cf00f80-57ef-11ea-856c-c1d9b8f4b3fb.png)

**Additional context**
I noticed that the error loading information is different than another chain that deals with basefiles missing. I did notice that my error message is different. I posted in that chain as well. Please note that while I know Revit and know how to build buildings, anything that involves a command prompt and going into my user profile is out of my comfort zone. (so please instruct as simply as possible). 

Best, 

Emily

**Comment by eirannejad** [comment]
Open a command prompt and run the command below. Then launch Revit again

```shell
pyrevit configs bincache enable
```

**Comment by threexe** [comment]
you are wonderful! Thank you.
