### ISSUE TITLE
PyRevit won't launch dynamo Script With UI nodes

### ISSUE THREAD

**Issue by dsellam** [eirannejad/pyRevit#837]
Hello,

I have a script that works when using dynamo that is not launched when clicking on the pyrevit button.

Script is in this extension : 
[pyENIA.extension.zip](https://github.com/eirannejad/pyRevit/files/4260787/pyENIA.extension.zip)

pyENIA.extension\eniAddons.tab\Feuilles.panel\Dupliquer une feuille.pushbutton

![image](https://user-images.githubusercontent.com/53033999/75432125-3af9ec00-594e-11ea-8556-b59daee0441b.png)

 + Revit 2019.2

**Comment by eirannejad** [comment]
Can not extract the attached ZIP file. Would you mind reuploading?

**Comment by dsellam** [comment]
[eniAddons.tab.zip](https://github.com/eirannejad/pyRevit/files/4274531/eniAddons.tab.zip)

Hope this will work better

**Comment by GertjanVDBVK** [comment]
Just out of curiosity, do the other dynamo scripts work?
I can't seem to get pyrevit to run a script, not even one with a single python node that shows a pop-up a messagebox.

**Comment by dsellam** [comment]
The others doesn't have UI. But I tried this Test script that doesn't show the dialog box as well 
[script Test UI.zip](https://github.com/eirannejad/pyRevit/files/4323699/script.Test.UI.zip)

**Comment by jmcouffin** [comment]
> The others doesn't have UI. But I tried this Test script that doesn't show the dialog box as well
> [script Test UI.zip](https://github.com/eirannejad/pyRevit/files/4323699/script.Test.UI.zip)

Try setting the script to run 'Automatic'
That might do the trick
![image](https://user-images.githubusercontent.com/7872003/81411996-73365b80-9143-11ea-91aa-4b79ddafc4f9.png)

you can set that either editing the script in notepad or in dynamo

**Comment by dsellam** [comment]
It works with RunType : Automatic - good to know
