### ISSUE TITLE
pyRevit_4.7.4_signed.exe /extract option does not work

### ISSUE THREAD

**Issue by amastrobera** [eirannejad/pyRevit#839]
Hi Ehsan, 

I install from command line. As you can see I typed `/?` to know my options. 

`/extract "angelo-directory"` should let me choose the directory where to put things that normally go under `C:\Users\angelo/AppData/Roaming/pyRevit-Master`. When I run the program with this option, the files are just not created. 

If I don't use the `/extract` option at all, the installation succeeds. Is it a bug ? 

![image](https://user-images.githubusercontent.com/41054415/75471836-a1046480-598a-11ea-9036-8b08d3cf4f31.png)

**Comment by eirannejad** [comment]
Expand the `%userprofile%` to an actual path. Also see the command format on the help window. This is what I tested and works
```shell
pyRevit_4.7.4_signed.exe /extract:"C:\Test"
```

This is however, NOT the preferred installation method. See [pyRevit for Teams](https://www.notion.so/pyRevit-For-Teams-ddc6c312d6f6488691eed2ec7704fd97)
