### ISSUE TITLE
REMOVE ALL REVISION EXCEPT SELECTED

### ISSUE THREAD

**Issue by CHBIV007** [eirannejad/pyRevit#84]
HAVE THEM ALL LISTED WITH CHECK BOXES, THE ONES YOU CHECK IT WILL DELETE OUT OF MODEL.

**Comment by eirannejad** [comment]
Remove as in Delete all revisions or hide the cloud and tags?

**Comment by eirannejad** [comment]
I think this really should be done through the main Revisions window. This task changes the Revision numbers and the user needs to decide how to combine the revisions.
