### ISSUE TITLE
Sheet Setup recommendation

### ISSUE THREAD

**Issue by Hmunsell** [eirannejad/pyRevit#840]
in the Batch Sheet Maker, you can only use the default sheet creation from Revit to create blank sheets. Our office has pre-setup "starter" sheets in our template. these sheets have GuideGrid, Graphic Scales, North Arrows, Sheet Notes, Legends, etc... preplaced for different sheet types. it would be nice to have a option to select a existing sheet to copy to create new sheets.  example: use the A101 sheet and make 5 copies (A102, A103, A104, etc...).

**Comment by eirannejad** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/212

**Comment by tillbaum** [comment]
[dublicatesheet.pushbutton.zip](https://github.com/eirannejad/pyRevit/files/4270471/dublicatesheet.pushbutton.zip)
