### ISSUE TITLE
Revision sequence problem

### ISSUE THREAD

**Issue by houkvanlake** [eirannejad/pyRevit#841]
Hi,
I have a few issues I would like to share: 

when setting up the naming format of the print sheets template, I am having issues with one particular tag, the {rev_number}. In my project logic, this tag should appear as a letter (A,B,C...) according to the sequence I have set up on the revision options. However the plugin is not able to recognise the letter and displays only the number of the revision in digits. Is there a workaround for this?

My second request has to do with the {rev_date}. I woud like this tag to have multiple options to be displayed including variable date format, example: 18/01/2020, 200118, 01.18.20 
This is a personal request and would be happy to see it.

Another request has to do with the naming format list, by default 3 are appearing that are impossible to remove and when I create a new one and close Pyrevit, once reopened it's never by default selected.

Thank you very much for your help

**Comment by eirannejad** [comment]
Great. I'll take a look and will get this fixed. Thanks for the report

**Comment by eirannejad** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/781
Closing this. Follow the referenced issue please.

**Comment by DevENG-GS** [comment]
Thank you^^
Best wishes,
