### ISSUE TITLE
PyRevit does not load

### ISSUE THREAD

**Issue by tdemuynck** [eirannejad/pyRevit#842]
When starting revit 2020, I get an error message "PyRevitLoader- Error Loading pyRevit". Revit 2019 does not show this behaviour.

Have tried the below command, does not fix the problem
`pyrevit attach master 277 --installed`

![image](https://user-images.githubusercontent.com/54833917/75787224-af75c600-5d66-11ea-9a8c-4c559ac38379.png)

![image](https://user-images.githubusercontent.com/54833917/75787465-11cec680-5d67-11ea-84c8-c916a8c3bd34.png)

![image](https://user-images.githubusercontent.com/54833917/75787583-3165ef00-5d67-11ea-96d1-2e9ee87dd5bb.png)

**To Reproduce**
1. start revit 2020

**Expected behavior**
PyRevit to be loaded

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.7.4
 - pyRevit Environment: Open a command prompt and run the command below. 
"==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.4" | Path: "C:\Users\demuynckt\AppData\Roaming\pyRevit-Master"
Error: Could not load file or assembly 'pyRevitLabs.TargetApps.Revit, Version=0.17.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
Run with "--debug" option to see debug messages"
`pyrevit env`

**Additional context**

**Comment by Sionnach-Rua** [comment]
did you switch your active engine to the Dynamo compatible one?  I believe that's part of what caused the same error to appear for me in 2020, but make the one that was happening in 2019 go away

**Comment by tdemuynck** [comment]
I have just installed the update of revit 2020.2.1, uninstalled pyrevit and reinstalled and now it works...
Thanks for your reply (y)
