### ISSUE TITLE
PyRevit does not load

### ISSUE THREAD

**Issue by cader83** [eirannejad/pyRevit#843]
**Describe the bug**
The pyrevit is not running after installation.

Have tried the below command, does not fix the problem
pyrevit attach master 277 --installed

**Screenshots**
![image](https://user-images.githubusercontent.com/26705457/75887645-2b414280-5e3b-11ea-9771-ca0d406a8a18.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.7.4
 - pyRevit Environment: 

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.4" | Path: "C:\Users\rasit.ayaz\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2019.2.2 Hotfix" | Engine: 277 | Path: "C:\Users\rasit.ayaz\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\rasit.ayaz\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
master | Product: "2018.0.3" | Engine: 277 | Path: "C:\Users\rasit.ayaz\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\rasit.ayaz\AppData\Roaming\Autodesk\Revit\Addins\2018\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\rasit.ayaz\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
2018.0.3 | Version: 18.0.3.6 | Build: 20181015_0930(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018"
==> Running Revit Instances
PID: 1580 | 2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> User Environment
Microsoft Windows 10 [Version 10.0.17763]
Executing User: RONESANS\rasit.ayaz
Active User: RONESANS\rasit.ayaz
Admin Access: No
%APPDATA%: "C:\Users\rasit.ayaz\AppData\Roaming"
Latest Installed .Net Framework: 4.7.2
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.17.0.0
```

**Comment by pabloderen** [comment]
Same happen to me after the installation of the update 2019.2.2 Hotfix, but after closing the error window pyRevit is working as it usual.

**Comment by eirannejad** [comment]
Try this in command prompt
```
pyrevit caches clear --all
pyrevit attach master 277 --installed
```

**Comment by cader83** [comment]
No effect.
error is same
![image](https://user-images.githubusercontent.com/26705457/76302670-7511a900-62d1-11ea-89dd-0bd3c6b5805c.png)

**Comment by eirannejad** [comment]
Then this could be a potential conflict with another addon that uses the same GUI framework. Would you be able to use this tool to temporarily disable all other addons except for pyRevit to see if it loads by itself?

https://www.rhino3d.com/inside/revit/beta/reference/toubleshooting#search-for-conflicting-plugins

**Comment by cader83** [comment]
Ok i will test.
Also as the clarrification: version 4.6.24 works normally, without any errors.

**Comment by cader83** [comment]
all addons disabled (except Autodesk, becouse of I have no adminaccess)
error is still exist
![image](https://user-images.githubusercontent.com/26705457/76756994-d76a1e00-6797-11ea-88d5-5c708e72d7c1.png)
![image](https://user-images.githubusercontent.com/26705457/76757032-e81a9400-6797-11ea-97d0-61855bad5d99.png)

**Comment by eirannejad** [comment]
Hmm. I'm baffled.

**Comment by eirannejad** [comment]
Version 4.8-beta2 is out. I'd appreciate if you can test and see if it loads

**Comment by cader83** [comment]
> Version 4.8-beta2 is out. I'd appreciate if you can test and see if it loads

I tested versıon 4.8.2. it works without errors. Thanks!
