### ISSUE TITLE
Pyrevit 4.7.4 doesnt load

### ISSUE THREAD

**Issue by guilhermemirandaa1** [eirannejad/pyRevit#844]
just installed pyrevit and tried to use in Revit 2019 but it doenst load
got those errors

![error 01](https://user-images.githubusercontent.com/61834433/75985901-62702c00-5eed-11ea-89c2-0f03ad826b8a.png)
![error 02](https://user-images.githubusercontent.com/61834433/75985903-6308c280-5eed-11ea-9b85-90fdec2096eb.png)

**Comment by pabloderen** [comment]
Duplicate of #842 ?

**Comment by eirannejad** [comment]
Seems like you are trying to load pyRevit from a network location. That's not gonna work. pyRevit needs to compile a series of resources on runtime
