### ISSUE TITLE
Cannot create pattern using filled region based on <solid fill> pattern

### ISSUE THREAD

**Issue by two9seven** [eirannejad/pyRevit#847]
**Describe the bug**

When attempting to create a new pattern based the selection of a solid filled region I receive the error below and no pattern is created. 

```
ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:name cannot include prohibited characters. 
Parameter name: name


ERROR [patmaker] Error creating pattern element. | name cannot include prohibited characters. 
Parameter name: name

```

**To Reproduce**
1. Create filled region using the <solid fill> pattern
2. Use pyrevit pattern tool to create detail pattern.
2. See error

**Expected behavior**
a new pattern based on the solid fill should be created. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version [e.g. 22]
 - pyRevit Environment: 
```==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.4" | Path: "C:\Users\Donovan\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2019.2.2 Hotfix" | Engine: 277 | Path: "C:\Users\Donovan\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\Donovan\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
master | Product: "2017.0.4" | Engine: 277 | Path: "C:\Users\Donovan\AppData\Roaming\pyRevit-Master" | Manifest: 
==> Installed Extensions
==> Default Extension Search Path

==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
2017.0.4 | Version: 17.0.511.0 | Build: 20181011_1545(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> Running Revit Instances
PID: 146944 | 2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> User Environment
Microsoft Windows 10 [Version 10.0.18363]
Admin Access: No
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.17.0.0
```

**Comment by Siversmith** [comment]
Someone else had a similar problem to this. The first problem is that your making a solid fill pattern that pyrevit wont do. Mostly because you don't need to do so. Simply create this using your standard revit tool to do so. When your creating a solid pattern which may have different colours or something this is all done within revit.

**Comment by two9seven** [comment]
My goal is to make a pattern that is partially solid. I am playing around with cut fills in walls. I want to make a "dashed" looking fill. I was hoping that the name of the solid fill was the issue in that it contains "<" symbols. If it's just not possible we can close this issue. Thanks.

**Comment by eirannejad** [comment]
Solid patterns are internal patterns in Revit. They are not and can't be defined using pattern definitions. Make a hatched pattern with lines super close to each other so it renders as solid on the scale of your drawing
