### ISSUE TITLE
Telemetry Client doesn't send information from custom doc-open hook

### ISSUE THREAD

**Issue by pabloderen** [eirannejad/pyRevit#848]
**Describe the bug**
I'm trying to send a json as string to Telemetry when the event **DocumentOpened** is trigger.
The script runs and returns a result print with all the information I'm sending but I don't receive any POST from the local telemetry on my Telemetry server (using a mongodb).

**DocumentOpened** event is being posted using the option to send events. I can see the entry being shown on Telemetry Server log.

If I trigger the script using a button it also posts the information to my db. I can also see the entry being shown on Telemetry Server log.

So the hook is working, posting to Telemetry is working but can make them both work together.

**To Reproduce**
1. Create a hook to doc-opened.py with
```
results = script.get_results()
results .message = {"test":2}
```
2. Reload pyRevit and open a new file
3. Check db for new documents
4. See error, no documents were inserted after event

**Expected behavior**
Once the user opens a document, the hook to DocumentOpened sets a value to script.get_results() and Telemetry sends the information to the Telemetry server.

**Desktop (please complete the following information):**

```master | Product: "2019.2.2 Hotfix" | Engine: 277 | Path: "C:\Users\pdere\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\pdere\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\pdere\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> Running Revit Instances
PID: 47024 | 2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> User Environment
Microsoft Windows 10 [Version 10.0.18363]
Executing User: DESKTOP-42ITQ1A\pdere
Active User: DESKTOP-42ITQ1A\pdere
Admin Access: No
%APPDATA%: "C:\Users\pdere\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.6.2 v4.7 v4.7.2 v4.8 v4.X
Installed .Net-Core Target Packs: v3.1.101
pyRevit CLI 0.17.0.0
```

**Additional context**
Where I can find the local Telemetry log to see what fails on the client side?

**Comment by eirannejad** [comment]
The [**Script**](https://www.notion.so/pyrevitlabs/Telemetry-System-992d72659457447f86b79cf1c9034541#0dd5fe5e952e497fab50055670655549) telemetry logs and [**Application Event**](https://www.notion.so/pyrevitlabs/Telemetry-System-992d72659457447f86b79cf1c9034541#b66fa2d28ee44f3dbdf42f9bb76f4a75) telemetry logs have different schemas. Under current implementation, the Application Event telemetry logs do not include a `commandresults` field and therefore, any value set on the `script.results` is ignored.

I'm making this report as Enhancement to add this feature in future releases

**Comment by pabloderen** [comment]
I'm not using the application event Telemetry log. I'm using an event hook to run a script that uses Script telemetry log.

**Comment by eirannejad** [comment]
That's what I meant. **DocumentOpened** is an Application Event. Your **Event** script, is being executed when **DocumentOpened** happens. Event scripts are different from normal scripts. I have marked this as an enhancement so the `commandresults` functionality can be added to Event scripts as well.

**Comment by pabloderen** [comment]
Make sense. You were clear the first I misunderstood.
