### ISSUE TITLE
Why can't vscode implement pyrevit auto completion

### ISSUE THREAD

**Issue by lcwewei** [eirannejad/pyRevit#849]
I added the following statement in the setting. Json file of vscode. RPW library can achieve automatic completion.
"{
    "python.jediEnabled": false,
    "python.linting.enabled": true,
    "python.linting.pylintEnabled": true,
    "python.linting.flake8Enabled": false,

    "python.pythonPath": "C:\\Python27\\python.exe",
    "window.zoomLevel": 0,
    "files.defaultLanguage": "python",
    "python.autoComplete.addBrackets": true,
    "editor.renderWhitespace": "all",
    "editor.renderControlCharacters": true,
    "python.autoComplete.typeshedPaths": [
        "Autodesk.Revit.DB"
        "Autodesk.Revit.UI"
    ],
    "python.autoComplete.extraPaths": [
        "C:\\stubs.min",
        "D:\\pyRevit-Master\\pyrevitlib\\pyrevit",
        "D:\\pyRevit-Master\\pyrevitlib"
    ],
    "editor.tokenColorCustomizations": {
        "comments": "#82e0aa", // 注释
        "keywords": "#0a0", // 关键字
        "variables": "#f00", // 变量名
        "strings": "#e2d75dbd", // 字符串
        "functions": "#5b99fcc9", // 函数名
        "numbers": "#AE81FF" // 数字
      },
      // 选中高亮的颜色
         "workbench.colorCustomizations": {
          "editor.selectionBackground": "#aa0000"
    },
    "code-runner.clearPreviousOutput": true,
    "code-runner.defaultLanguage": "python",
    "debug.allowBreakpointsEverywhere": true,

}"

**Comment by eirannejad** [comment]
Because pyRevit runs on IronPython which can read dotnet DLLs. The python you use with VSCode is a CPython. What you need to make autocompletion work is **Python Stubs** which are header-like python files that have type, property and method information for the target API

**Comment by lcwewei** [comment]
Thank you very much. Are there any plans to implement the pyrevit_stub file?

**Comment by eirannejad** [comment]
You mean pyRevit itself or for Revit API?

**Comment by lcwewei** [comment]
I mean pyrevit itself, the Revit API already has Stub files in VScode to implement automatic completion.

**Comment by eirannejad** [comment]
Ya probbaly. Low priority right now to be honest since the pyRevit API is still evolving

**Comment by lcwewei** [comment]
好的，非常期待。

**Comment by lcwewei** [comment]
Ok, I'm looking forward to it.

**Comment by htlcnn** [comment]
`pyrevit` is a python module. It means VS Code can autocomplete all of its members. Just modify your autocomplete.extraPath:
```
"python.autoComplete.extraPaths": [
    "D:\\pyRevit-Master\\pyrevitlib",
]
```
then `from pyrevit import ...`, VS Code will autocomplete for you.

**Comment by lcwewei** [comment]
I have done so, the RPW module in the D:\ pyrevit-master \pyrevitlib directory can achieve automatic completion, but the pyRevit module can't, have you tried and succeeded?

**Comment by htlcnn** [comment]
It works for me
![image](https://user-images.githubusercontent.com/931924/76482576-1ec67680-6447-11ea-9a28-2ec8cf24e5b4.png)

**Comment by lcwewei** [comment]
This step is possible, but the second part cannot be completed automatically.
![01](https://user-images.githubusercontent.com/16218099/76482958-b9778300-6450-11ea-9530-3d885aa287b9.png)
![2](https://user-images.githubusercontent.com/16218099/76482969-bbd9dd00-6450-11ea-9b7e-3ca1c5fc4ada.png)

**Comment by htlcnn** [comment]
![image](https://user-images.githubusercontent.com/931924/76485601-8d0f3700-644f-11ea-89f9-2a445af6237f.png)
Did you try installing Python Language Server for VS Code?

**Comment by lcwewei** [comment]
Thank you very much. It's ok now

**Comment by nterranova-fsb** [comment]
@lcwewei what did you do to make this work? I cannot for the life of me get it to recognize the methods inside any pyRevit module

**Comment by baptistelechat** [comment]
Hi, I had the same problem. Here is an extract of my settings.json. Hopefully it helps you 😉

```
{
  "python.languageServer.version": "Microsoft",
  "python.linting.enabled": true,
  "python.autoComplete.extraPaths": [
    "C:\\Users\\ASUS\\AppData\\Roaming\\pyRevit-Master\\pyrevitlib",
    "C:\\Users\\ASUS\\AppData\\Roaming\\ironpython-stubs\\release\\stubs.min",
  ],
  "python.jediEnabled": false,
  "python.languageServer": "Default",
  "python.defaultInterpreterPath": "C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python39\\python.exe",
  "python.analysis.extraPaths": [
    "C:\\Users\\ASUS\\AppData\\Roaming\\pyRevit-Master\\pyrevitlib",
    "C:\\Users\\ASUS\\AppData\\Roaming\\ironpython-stubs\\release\\stubs.min",
  ]
}
```

**Comment by Lionel-Lim** [comment]
Hi, @nterranova-fsb and @baptistelechat.

I could managed the issue by putting double backslash at the end of the path.
`C:\\Users\\ASUS\\AppData\\Roaming\\pyRevit-Master\\pyrevitlib**\\**`

**Comment by emilaz** [comment]
Apparently, it's not enough anymore to only add `python.autoComplete.extraPaths`, you also need to add 

```
"python.analysis.extraPaths": [
    "C:\\path\\to\\pyRevit-Master\\pyrevitlib"
  ]
```

At least that fixed it for me.

**Comment by RichardPinka** [comment]
Hello there.. I already installed this , and VS Code requires it from me again and again.  Why ? 
![image](https://github.com/user-attachments/assets/b795137d-4a71-42a0-8bd9-7818e50c0ef2)

**Comment by baptistelechat** [comment]
Hi @RichardPinka, I'm the developer of this VSCode extension.

This error is due to the fact that the extension does not detect the presence of the pyRevit-Master folder or the pyRevit folder in %APPDATA% (C:\Users\[yourUsername]\AppData\Roaming).

These 2 folders are created when pyRevit is installed on your computer. I need them to reference pyRevit stubs in your VSCode configuration and define the “python.analysis.extraPaths” and “python.autoComplete.extraPaths” properties. 

This extension is still in the testing phase, so it is possible that some bugs may surface. You can create a Github Issue on the repo if you want to give me more details 😉 : 

https://github.com/baptistelechat/pyrevit-with-vscode
