### ISSUE TITLE
pyRevit not visible in Revit 2019

### ISSUE THREAD

**Issue by imsujan** [eirannejad/pyRevit#850]
Hi, I'm using pyRevit 4.7.4. I get this error message while starting Revit 2019 and Tabs are not visible from pyRevit.
It is working fine in Revit 2017 and 2018

My pyRevit Install location is 
C:\Users\Sujan\AppData\Roaming\pyRevit-Master

![image](https://user-images.githubusercontent.com/39112057/76297062-4dc1d880-62df-11ea-98c2-383aa8625847.png)

**Comment by eirannejad** [comment]
Seem like you have too many tabs in Revit. How many addons have you added?!

**Comment by imsujan** [comment]
Hi @eirannejad thank you so much for your response. I have too many add-ins installed. I moved every add-in in Archive folders and now it is showing up in Revit. But why I have problem Revit 2019  with the same number of Add-ins
