### ISSUE TITLE
Toolchain to adjust dimension numbers and texts

### ISSUE THREAD

**Issue by eirannejad** [eirannejad/pyRevit#851]
[From a user email]

We often annotate within the building itself, this means that sometimes the numbers above the DI are not in the right place. Now if I have 6 houses next to eachother I currently need to adjust all the DI's manually to put the numbers below it (or a bit to the left/right) on every single instance.
I was thinking if I could select 6 DI lines and then give a command which moves all of them at the same time it would same me a lot of work.

I was thinking it might be nice to have two functions in this feature. 1: Move all DI numbers by X in direction Y. And 2: a "flip face" like function which puts the numbers below the DI line. The second would be the one I would probably use the most, but I can imagine others wanting the first option also.

**Comment by djdarkstream** [comment]
Is there any progress being made for this new feature (especially the flip facing one)?
