### ISSUE TITLE
Error when calling command from hook

### ISSUE THREAD

**Issue by alexdaversa** [eirannejad/pyRevit#856]
I'm attempting to call another command from the doc-opened hook. The command itself is rather trivial, to unhide text notes with a certain type. The hook is pretty basic:

```
#show internal notes when document is opened

from pyrevit import EXEC_PARAMS
from pyrevit.loader import sessionmgr

sessionmgr.execute_command('pykss-pykss-tools-internalnotes-showinternalnotes')
```

I'm getting the following error that I can't seem to debug myself:

```
File "C:\pyKSS.extension\hooks\doc-opened.py", line 7, in <module>
File "C:\Users\adaversa\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\loader\sessionmgr.py", line 543, in execute_command
File "C:\Users\adaversa\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\loader\sessionmgr.py", line 519, in execute_command_cls
SystemError: Object reference not set to an instance of an object.
```

Any help would be appreciated.

**Comment by eirannejad** [comment]
Not supported and not a good way to architect your code. Organize the functionality that you need inside a python module in your extension

```
your.extension
└── lib/
    └── yourmodule
        └── __init__.py
```

Then import this module in your command and hook scripts.

```
import yourmodule as ym

ym.functionality()
```

Always try to separate the user interface (command and hook scripts) from code and modularize as much as possible so code can be reused

**Comment by alexdaversa** [comment]
Thanks for getting back to me! I had been referencing issue #814 for how to go about this, but I'm guessing calling from a hook is different. To be clear, I have a pushbutton so that a user can manually show text notes of a certain type, and would like those same notes to show when opening a file.

I did not get the module import to work for my hook though it still works for my pushbutton. Is there anything specific I have to do that's different from a typical script for it to work in a hook?

Specifically, I'm getting 

```
Exception: The input argument "document" of function `anonymous-namespace'::FilteredElementCollector_constructor or one item in the collection is null at line 326 of file d:\ship\2019_px64\source\revit\revitdbapi\gensrc\APIFilteredElementCollectorProxy.cpp.
Parameter name: document
```
when trying to collect the sheets in the opened document
`
sheets = DB.FilteredElementCollector(revit.doc).OfCategory(DB.BuiltInCategory.OST_Sheets).WhereElementIsNotElementType().ToElements()
`

**Comment by alexdaversa** [comment]
Hi @eirannejad,

I've gotten it now to the point where although my code isn't clean (I've been trying a lot of different things) the error message is:
```
File "C:\Users\adaversa\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\revit\db\transaction.py", line 40, in __init__
AttributeError: 'NoneType' object has no attribute 'IsModifiable'
```

It looks like I'm having trouble getting the active document when doc-opened executes. I am currently using per the anatomy of hook scripts page:
`doc = EXEC_PARAMS.event_args.Document`

**Comment by eirannejad** [comment]
I'm gonna take a look at this right now. Hold on

**Comment by eirannejad** [comment]
Okay I tested the `doc-opened` event and it works fine. Would you mind sharing your event script? I need to understand why you are not getting a `DB.Document` object from `.event_args.Document`

**Comment by alexdaversa** [comment]
Ehsan, thank you so much for looking into this! I coped the code from my module into the event script itself. It works perfectly as a pushbutton with `curdoc = revit.doc` but not in the event.

```
#show internal notes when document is opened

from System.Collections.Generic import *
from Autodesk.Revit.DB import *
from pyrevit import revit, DB, UI
from pyrevit import script
from pyrevit import forms
from pyrevit import EXEC_PARAMS
import internalnotes

curdoc = EXEC_PARAMS.event_args.Document

##### IMPORTS
from System.Collections.Generic import *
from Autodesk.Revit.DB import *

from pyrevit.framework import List
from pyrevit import revit, DB, UI
from pyrevit import forms
from pyrevit import script

##### FUNCTIONS
def FilteredText(notes,familytype):
	filteredNotes = []
	for note in notes:
		if note.Name == familytype:
			filteredNotes.append(note)
	return filteredNotes

def FilteredViews(notes,sheets,views):
	filtered_views = set()
	for note in notes:
		for sheet in sheets:
			if note.OwnerViewId == sheet.Id:
				filtered_views.add(sheet)
		for view in views:
			if note.OwnerViewId == view.Id:
				filtered_views.add(view)
	return filtered_views

##### MAIN
	familytype = "xxINTERNALNOTES"
	sheets = DB.FilteredElementCollector(curdoc).OfCategory(DB.BuiltInCategory.OST_Sheets).WhereElementIsNotElementType().ToElements()
	views = DB.FilteredElementCollector(curdoc).OfCategory(DB.BuiltInCategory.OST_Views).WhereElementIsNotElementType().ToElements()
	notes = DB.FilteredElementCollector(curdoc).OfCategory(DB.BuiltInCategory.OST_TextNotes).WhereElementIsNotElementType().ToElements()
	notes = FilteredText(notes,familytype)
	sheets = FilteredViews(notes,sheets,views)
	with revit.Transaction('Show Internal Notes'):
		for sheet in sheets:
			for note in notes:
				if note.IsHidden(sheet):
					sheet.UnhideElements(List[ElementId]([note.Id]))
```

**Comment by eirannejad** [comment]
Why are the lines after `#### MAIN` indented?! The seem to be part of the `FilteredViews` function body

**Comment by eirannejad** [comment]
Uh buddy. `revit.Transaction('Show Internal Notes')` needs a document. It should be:

`with revit.Transaction(curdoc, 'Show Internal Notes')`

**Comment by alexdaversa** [comment]
You're right they should not be indented (and aren't, in my script).

And...wow, I was really hoping it wasn't a total amateur mistake. I didn't think transaction needed a doc passed to it, is that only for hooks?

Sorry for bothering you with this...I will try to clean up my tool as best I can and share it with the community if there it seems useful.

Thank you again!!

**Comment by eirannejad** [comment]
Haha no worries! It happens to all of us
