### ISSUE TITLE
Problems with Cpython

### ISSUE THREAD

**Issue by wobubuxiangxin** [eirannejad/pyRevit#857]
Hello, everyone. I just studied pyrevit. I failed to test Cpython engine after I installed Cpython according to the video. I don't know how to deal with this problem. I hope you can help me.

![Open report error](https://user-images.githubusercontent.com/30747191/76770111-63039f00-67d8-11ea-97b7-8407f66d7f79.jpg)
![Test report error](https://user-images.githubusercontent.com/30747191/76770126-6565f900-67d8-11ea-8e16-c028131a3aca.jpg)
![Picture 1](https://user-images.githubusercontent.com/30747191/76770141-68f98000-67d8-11ea-8198-d85feb5b652c.jpg)
![Picture 2](https://user-images.githubusercontent.com/30747191/76770152-6ac34380-67d8-11ea-88fc-108cc3d8757e.jpg)

**Comment by eirannejad** [comment]
Did you install the x64 bit python 3.7?

**Comment by wobubuxiangxin** [comment]
Hello my friend！I'm sure i install the x64 bit python 3.7，In picture 3, I checked Python's information.

**Comment by eirannejad** [comment]
The only thing I can think of is that `pip` is not associated with your python 3.7 installation.

Check `pip --version`. It tells you where it installs the packages:

```
pip 20.0.2 from c:\users\ehsan\appdata\local\programs\python\python37\lib\site-packages\pip (python 3.7)
```

**Comment by wobubuxiangxin** [comment]
Hello, I changed the path again, but it still failed. I ran python.exe directly and found that numpy package can be called. Cannot interact with pyrevit.
![12](https://user-images.githubusercontent.com/30747191/76947002-f0adce80-693f-11ea-871c-0969ef03bae8.jpg)
![12](https://user-images.githubusercontent.com/30747191/76947014-f60b1900-693f-11ea-9daf-e9c54624b278.jpg)

**Comment by htlcnn** [comment]
Your installed Python is at `%APPDATA%`, not at `%PROGRAMFILES%`. I can see your PYTHONPATH does not contain `%APPDATA%`

**Comment by wobubuxiangxin** [comment]
Hello, I've changed the file path to% localappdata%, but it still doesn't work
![QQ截图20200318203331](https://user-images.githubusercontent.com/30747191/76961275-0d560080-6958-11ea-997a-56b1fff7b45d.png)

**Comment by wobubuxiangxin** [comment]
![343](https://user-images.githubusercontent.com/30747191/76961697-c4eb1280-6958-11ea-849a-f1e662d4f263.jpg)

**Comment by wobubuxiangxin** [comment]
Hello, I've changed the file path to% localappdata%, but it still doesn't work.
![343](https://user-images.githubusercontent.com/30747191/76961873-214e3200-6959-11ea-9a17-a62c71061e32.jpg)

**Comment by htlcnn** [comment]
Did you restart your PC after changing paths? If it does not work after you restart your PC, try to uninstall Python and reinstall it for all users (install to c:\program files)

**Comment by wobubuxiangxin** [comment]
I used to install python (ZIP format) to C: \ program files, but it didn't work.

**Comment by htlcnn** [comment]
Please use executable installer so it would set PATHs for you.

**Comment by wobubuxiangxin** [comment]
Neither exe nor zip can be used to interact with pyrevit.

**Comment by eirannejad** [comment]
Okay let's try something else. Let's manually add the `site-packages` path to the script and see if numpy can get imported.

```python
#! python3
import sys

sys.path.append(r'<add the python path here>')

import numpy
```

**Comment by wobubuxiangxin** [comment]
Still can't, even version number can't be detected. 
![1234](https://user-images.githubusercontent.com/30747191/77158352-1a046100-6ade-11ea-966d-866cd0953c05.jpg)

**Comment by wobubuxiangxin** [comment]
All of a sudden, I succeeded (I didn't do anything). I restarted the software and tried to run it again. I found it couldn't work again. I don't know what's going on?
![213](https://user-images.githubusercontent.com/30747191/77158765-ed9d1480-6ade-11ea-99db-f360ff7ff63a.jpg)

**Comment by wobubuxiangxin** [comment]
I turned on two revits to run at the same time, and found that they can't run one after another.
![1233](https://user-images.githubusercontent.com/30747191/77159159-ca269980-6adf-11ea-8917-905d686991f1.jpg)

**Comment by eirannejad** [comment]
Huh!

**Comment by wobubuxiangxin** [comment]
There is another problem. In Python 3, you can call libraries such as' numpy 'and' Panda ', but the built-in functions don't work, such as' range'. How can I solve this problem?

**Comment by rika8aga** [comment]
Excuse me, can I write about this issue here? Same issue, but can't find a solution
