### ISSUE TITLE
batch setup not working on 64-bit windows 10

### ISSUE THREAD

**Issue by epeter-** [eirannejad/pyRevit#86]
![image](https://cloud.githubusercontent.com/assets/6928491/15099168/9b3956a2-154e-11e6-858d-d2a7ca5f8b2f.png)
![image](https://cloud.githubusercontent.com/assets/6928491/15099173/b3d9a93c-154e-11e6-8f30-684577ae1b9c.png)

**Comment by eirannejad** [comment]
Hi epeter, this is an error related to the git package that is being used to download the pyRevit repositories. I need to look into this and resolve.

**Comment by epeter-** [comment]
no problem. do you have a description for a manual setup method?
best peter
Am 08.05.2016 um 18:59 schrieb Ehsan Iran-Nejad:
>
> Hi epeter, this is an error related to the git package that is being 
> used to download the pyRevit repositories. I need to look into this 
> and resolve.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/eirannejad/pyRevit/issues/86#issuecomment-217732930>
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by eirannejad** [comment]
Sure. Just download the repository and unzip. Then go to RevitPythonShell preferences and set the Startup Script to the `__init__.py` in pyRevit folder.

**Comment by eirannejad** [comment]
I just tested this under x64 Windows 10 and it works. Would you please translate the error message for me?

**Comment by eirannejad** [comment]
Can not replicate the error under x64 Windows 10 English

**Comment by epeter-** [comment]
sorry for late reply
the error occurs in the german localisation.
the 1st error message Procedure entry point not found 
"Engine_load_builtin_engine" in dll ...\git}mingw32\bin\libssh2-1.dll
the 2nd error message Procedure entry point not found 
"CONF_modules_free" in dll ...\git\mingw32\bin\libcurl-4.dll

best
peter
Am 10.05.2016 um 17:32 schrieb Ehsan Iran-Nejad:
>
> Can not replicate the error under x64 Windows 10 English
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/eirannejad/pyRevit/issues/86#issuecomment-218195373>
>
sorry for late reply!
the error occurs in the german loalisation.

t found "Engine_load_build


Procedure entry point not found "Engine_load_build



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by epeter-** [comment]
hi, i manually installed the package.
maybe you publish on github how to manually setup.
if you want me to do that. it were a pleasure....
best peter

---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by eirannejad** [comment]
I'm working on it but by You're more than welcome to make changes to the readme and send me a pull request.
