### ISSUE TITLE
External event template

### ISSUE THREAD

**Issue by lcwewei** [eirannejad/pyRevit#862]
How does python write a generic external event template?To achieve better interaction in a modeless window, such as creating a wall, first selecting the wall type through a window control, and then clicking two points on the screen to create the wall.The following is the template in C#.

https://blog.csdn.net/niuge8905/article/details/79767671

**Comment by eirannejad** [comment]
You can define the external event handler like this:

```python
class MyCustomExternalEventHandler(UI.IExternalEventHandler):
    name = 'MyCustomExternalEventHandler'

    def Execute(self, uiapp):
        """This method is called to handle the external event."""
        pass

    def GetName(self):
        """String identification of the event handler."""
        return self.name
```

and when ready to fire it up, you can:

```python
extevent_hndlr = MyCustomExternalEventHandler()
extevent = UI.ExternalEvent.Create(extevent_hndlr)

extevent.Raise()
```

**Comment by lcwewei** [comment]
I wrote a plugin to create a wall decoration layer. It needs to run in a modeless window and create external events in your way.
But the plug-in I wrote to test removing objects in the same way didn't have any problems.

[create.zip](https://github.com/eirannejad/pyRevit/files/4408155/create.zip)
[test.zip](https://github.com/eirannejad/pyRevit/files/4408187/test.zip)
