### ISSUE TITLE
Importing pyodbc module on pyrevit

### ISSUE THREAD

**Issue by lucaslimavieira** [eirannejad/pyRevit#863]
Hi, I am really new at programming and I am using the pyrevit tool. I need to connect my script to an access database. When I run the script on visual studio code, it works, but not when I run it on pyrevit. It shows this error: ImportError: No module named pyodbc. I have already installed this library on Python, but it seems it needs to be installed on pyRevit as well. How can I do that? Thank you very much.

**Comment by eirannejad** [comment]
See this https://stackoverflow.com/a/25664308/2350244
