### ISSUE TITLE
pyRevit 4.7.5 Installed but missing from Revit Tab

### ISSUE THREAD

**Issue by neeewbeee** [eirannejad/pyRevit#864]
Hi, I'm new to programming and pyRevit, I installed pyRevit 4.7.5 using the .exe file and it is not showing up in the Revit Tab. 
Windows 10 Pro v1909 OSbuild18363.752
Revit 2019.2
pyRevit default install location
Please see images below. Thanks your help in advanced!
![1](https://user-images.githubusercontent.com/62711286/77670443-71258e00-6f43-11ea-8c1a-cde4cd349ee2.PNG)
![2](https://user-images.githubusercontent.com/62711286/77670449-72ef5180-6f43-11ea-9e47-e15e3f61a4ff.PNG)
![3](https://user-images.githubusercontent.com/62711286/77670451-74207e80-6f43-11ea-8369-0049a5a05442.PNG)
![4](https://user-images.githubusercontent.com/62711286/77670452-7551ab80-6f43-11ea-927d-a3f174632e2c.PNG)
![5](https://user-images.githubusercontent.com/62711286/77671551-07a67f00-6f45-11ea-8948-7b59bda46c87.PNG)

**Comment by eirannejad** [comment]
Try running `pyrevit revits --installed -- debug` and send me all the output. You can send the output to a file using `pyrevit revits --installed --debug > ~\Desktop\output.log` (Run in Powershell). This will save all the output to a file named `output.log` on your desktop. Upload the file here.

**Comment by neeewbeee** [comment]
[output.log](https://github.com/eirannejad/pyRevit/files/4406089/output.log)
Thanks for your help!

**Comment by eirannejad** [comment]
I can see the crash:

```
Debug: Analysing registered app: Revit 2017
Debug: App is a Revit product: Revit 2017 
Error: Object reference not set to an instance of an object. (System.NullReferenceException)
   at pyRevitLabs.TargetApps.Revit.RevitProduct.ListInstalledProducts()
   at pyRevitCLI.PyRevitCLIRevitCmds.PrintLocalRevits(Boolean running)
   at pyRevitCLI.PyRevitCLI.ProcessArguments()
   at pyRevitCLI.PyRevitCLI.Main(String[] args)
```

You seem to have a Revit 2017 installation info left in your windows registry. IS that Revit still installed?

**Comment by neeewbeee** [comment]
No-Revit 2017. I only have Revit 2018 & 2019 installed.

**Comment by neeewbeee** [comment]
how do I clear our the 2017 registry to get pyrevit to work? Thanks!

**Comment by eirannejad** [comment]
The uninstall keys are under:
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\`

Use REGEDIT to browse to this key and find the related Revit 2017 key:

![Screen Shot 2020-04-07 at 09 55 45](https://user-images.githubusercontent.com/8197916/78697776-2ea27080-78b6-11ea-9c10-d84502200480.png)

Then export the key to a separate file, and delete the existing in registry:

![Screen Shot 2020-04-07 at 09 55 52](https://user-images.githubusercontent.com/8197916/78697807-3c57f600-78b6-11ea-88ec-d0aa6598a73a.png)

Please send me that exported key file so I can add to my machine and debug :)
