### ISSUE TITLE
Hooks Not Working

### ISSUE THREAD

**Issue by tpjma** [eirannejad/pyRevit#865]
I am unable to get my hooks to work when I re-path my extension to a location on the server. I have created my own extension which has been added to pyRevit through the Custom Extensions Directories feature. 

I am expecting a simple print popup on document startup / creation using the doc-created.py / doc-opened.py hooks. These were working on my desktop without issue, however when I re-path to the same folder copied onto the server the ribbon buttons still work as expected, however the hooks do not seem to load.

**Comment by eirannejad** [comment]
I can't replicate the issue on my machine. Open a command prompt and run ` pyrevit caches clear --all` to clear the caches and run Revit again. Do you see any errors being spit out from the hooks?

**Comment by eirannejad** [comment]
not enough info
