### ISSUE TITLE
Revit 2020 'Create Modifier Filters'

### ISSUE THREAD

**Issue by yourBim2020** [eirannejad/pyRevit#866]
In Revit 2020 when trying to Create Modifier Filters it gives the error "expected ElementFilter,got List[FilterRule].  

Works in Revit 2018 still. 

Revit Version:
20.0.0.377
20190327_2315(x64)

PyRevit 4.7.5  (error also occured in 4.7.4)

Error happens in win 7 and 10.

**Comment by eirannejad** [comment]
Fixed and will be published with next release
