### ISSUE TITLE
Could not load file or assembly 'pyRevitLabs.TargetApps.Revit, Version=0.17.0.0

### ISSUE THREAD

**Issue by michaelmontagne** [eirannejad/pyRevit#868]
installed pyrevit 4.7.5 from install file.  All windows updates installed.
Tried to attach using pyrevit attach master --installed --allusers
Got this:
Error: Could not load file or assembly 'pyRevitLabs.TargetApps.Revit, Version=0.17.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
Run with "--debug" option to see debug messages

[output.log](https://github.com/eirannejad/pyRevit/files/4406763/output.log)

**Comment by eirannejad** [comment]
Try reinstalling again (don't need to uninstall). Seems like on some machines, the installed missed a few files or antivirus apps delete a few of the DLLs

**Comment by michaelmontagne** [comment]
Tried many times.  May just copy a working folder from another installation.  Could that possibly work?


Mike Montagne | IT Director, associate | he / him / his | opsis architecture LLP | o:503.525.9511 d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com>

Opsis remains committed to our clients and projects and will continue working throughout the COVID-19 emergency through remote locations and tools. Due to our office closure, please use cell phones or email as the primary contact and note that we will conduct meetings online wherever possible. Updates to our office status or policies will be posted here<https://www.opsisarch.com/blog/media/opsis-covid-19-update/>.

________________________________

**Comment by eirannejad** [comment]
Ya definitely. But gotta figure out what is it that is deleting this DLL I guess.
