### ISSUE TITLE
Wipe all family parameters not working

### ISSUE THREAD

**Issue by giovanniconsiglio** [eirannejad/pyRevit#869]
**Describe the bug**
Wipe All Family Parameters does nothing. After I save the family and run the command "Wipe All Family Parameters" in the family environment, first a dialog appers (Make sure your models are saved and synced, Hit OK to continue..." but when I click "ok" nothing happens.

**To Reproduce**
1. Go to Family > Wipe All Family Parameters
2. Click on 'the button'
3. Dialog displays to "make sure your models are saved and synced, Hit Ok to continue"
4. Click Ok
5. Nothing happens

**Expected behavior**
I expect to be able to see which parameters are unused inside the family and to select which ones I want to purge.

**Screenshots**

![image](https://user-images.githubusercontent.com/37558888/77995425-0eaa0480-732c-11ea-8c31-d023a3043922.png)

**Desktop:**
 - OS: Windows 10
 - pyRevit Version 4.7.5

**Comment by eirannejad** [comment]
Works on my machine. Seems like the tool can not find any "deletable" parameter in your family file. Share the family if you don't mind so I can test
