### ISSUE TITLE
The modeless window is running the plug-in

### ISSUE THREAD

**Issue by lcwewei** [eirannejad/pyRevit#870]
I wrote a plugin to create a wall decoration layer. It needs to run in a modeless window and create external events in your way.
But the plug-in I wrote to test removing objects in the same way didn't have any problems.

revit 2019
[test.zip](https://github.com/eirannejad/pyRevit/files/4408213/test.zip)
[create.zip](https://github.com/eirannejad/pyRevit/files/4408214/create.zip)

**Comment by eirannejad** [comment]
See this template for best practices in creating non-modal GUI on Revit
https://github.com/mitevpi/revit-wpf-template
