### ISSUE TITLE
PyRevitLoader error after installing IronPython

### ISSUE THREAD

**Issue by jaredholloway94** [eirannejad/pyRevit#872]
**Describe the bug**
I had (have) pyRevit installed for Revit 2020. Working great. Loving it.
Then I installed IronPython 2.7.7 to set up a venv in VS, so I could build a WPF GUI on top of IronPython, for use in a pyRevit addin:
![image](https://user-images.githubusercontent.com/41764450/78715593-3c221f80-78e3-11ea-85a0-c2383299caab.png)

Then next time I opened Revit, I got this error on startup:
![image](https://user-images.githubusercontent.com/41764450/78715729-6ecc1800-78e3-11ea-93a4-394936495e69.png)

Is there a different way I need to install IronPython 2.7.7, or some system environment variables I need to change to avoid conflicting with pyRevit?
Thanks

**To Reproduce**
1. Install latest version of pyRevit
2. Install IronPython separately, from its own installer
3. Try to open Revit

**Expected behavior**
No conflict between pyRevit and a separate installation of IronPython.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - pyRevit 4.7.5
 - pyRevit Environment: 
```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.5" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
master | Product: "2020.2 (Update)" | Engine: 277 | Path: "C:\Program Files\pyRevit-Master" | Manifest: "C:\Users\Jared\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
==> Installed Extensions
RSEC | Type: Unknown | Repo: "" | Installed: "C:\Users\Jared\Documents\GitHub\RSEC Extensions\RSEC.extension"
==> Default Extension Search Path
C:\Users\Jared\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\Users\Jared\Documents\GitHub\RSEC Extensions
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2020.2 (Update) | Version: 20.2.0.48 | Build: 20191031_1115(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.18362]
Executing User: [redacted machine name]\Jared
Active User: [redacted machine name]\Jared
Admin Access: Yes
%APPDATA%: "C:\Users\Jared\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.7.2 v4.X
Installed .Net-Core Target Packs: v3.1.201
pyRevit CLI 0.21.0.0
```

**Additional context**

**Comment by aaronbergmann** [comment]
I experienced the same issue. I was using IronPython 273. I have changed it to 279, and it's resolved. I did not install IronPython separately.

**Comment by EduardLouis** [comment]
The same issue for me when I use engine 273. Works fine on the latest engine.
![image](https://user-images.githubusercontent.com/10221704/79980703-3106ec00-84ac-11ea-9e37-59f0aaa0d315.png)

**Comment by legend-oe** [comment]
I also had error "No module named wpf" in Revit 2021 (Windows 7).
I have installed IronPython (2.7.10) in Program Files.

This method help for me:
1. Open C:\Users\ [USER NAME] \AppData\Roaming\Autodesk\Revit\Addins\2021\pyRevit.addin
2. Change engines folder 273 to 279
`<Assembly>C:\Users\home\AppData\Roaming\pyRevit-Master\bin\engines\279\pyRevitLoader.dll</Assembly>`
3. Start Revit
