### ISSUE TITLE
button to turn on/off PyRevit loading at the start

### ISSUE THREAD

**Issue by AlexVilaOrtega** [eirannejad/pyRevit#873]
I am using RTVXporter to publish multiple documents from multiple different files. RTVxporter is capable to launch multiple Revit sessions and run batch process during the night.

During that process all sessions are launching a PyRevit plugin that take an extra 15 seconds to load, after the 3rd consecutive Revit opening PyRevit crashes or got confused generating error messages...
Can be possible to Activate/deactivate PyRevit trough the toolbar to close Revit and not have PyRevit loaded for every session?

Thanks Mate, I admire your work.
AV

**Comment by thazell** [comment]
Have you tried something like this?
Do the following to disable add-ins: 

1. Close Revit.
2. Locate the addin in one of these folders: 
C:\ProgramData\Autodesk\Revit\Addins\
%appdata%\Autodesk\Revit\Addins\
3. Temporarily rename the .addin.  
Example: 
Old Name: pyRevit.addin
New Name:  pyRevit.addinoff
4. Launch Revit. A

Alternate locations that add-ins could be loaded from:
C:\ProgramData\Autodesk\ApplicationPlugins. This location can be used for add-ins that span multiple products/versions. 
C:\Program Files\Autodesk\Revit [Version]\AddIns. This location is generally used for Internal Add-ins, but some older add-ins may still try to load into this location. 

Borrowed and modified from https://knowledge.autodesk.com/support/revit-products/learn-explore/caas/sfdcarticles/sfdcarticles/How-to-Disable-Add-Ins-for-Revit-Products.html

**Comment by eirannejad** [comment]
Make a batch script, PS script, or a Windows shortcut to the commands below:

Detach (Disable) pyRevit:
`pyrevit detach --all`

Attach (Enable) pyRevit:
`pyrevit attached master 277 --installed`

**Comment by AlexVilaOrtega** [comment]
Thanks, That will work... I can add it as start macro at the start of RTVexporter
