### ISSUE TITLE
The problem of calling modules in Cpython！

### ISSUE THREAD

**Issue by wobubuxiangxin** [eirannejad/pyRevit#874]
Hello everyone, I have been troubled by a problem recently. That is, I can't call the pyrevit module in Cpython, even if I add a path. 
      The error message "Cpython traceback:AttributeError : 'RuntimeType' object has no attribute 'Assembly' ”

**Comment by htlcnn** [comment]
pyrevit module is written to work with IronPython. It uses many .NET assemblies. Some don't work with CPython. You could install pythonnet to your CPython and try again.

**Comment by wobubuxiangxin** [comment]
After PIP installs pythonnet, there will still be an error when calling the pyrevit module.

**Comment by eirannejad** [comment]
CPython that is shipped with pyRevit already includes pythonnet and can import CLR assemblies, however, the `pyrevit` python module is still not ready to be fully imported into CPython since it has been written for IronPython and many fixes is necessary to make it work under Cpython
