### ISSUE TITLE
Do not report errors in obtaining parameters

### ISSUE THREAD

**Issue by lcwewei** [eirannejad/pyRevit#876]
When I executed the code, the element did not get the parameter value, but pryrevit did not report an error,Seems to have this bug in getting all the parameters:
wall=uidoc.Selection.PickObject(ObjectType.Element,'select wall')
height=wall.get_Parameter(BuiltInParameter.WALL_HEIGHT_TYPE).AsDouble()
[test.zip](https://github.com/eirannejad/pyRevit/files/4467724/test.zip)

**Comment by lcwewei** [comment]
pyrevit 4.75
revit chinese 2019

**Comment by eirannejad** [comment]
pyRevit only reports errors when an exception is thrown from the executing code.
