### ISSUE TITLE
rpw import issue CPython

### ISSUE THREAD

**Issue by vengelhard** [eirannejad/pyRevit#879]
When running these two lines for importing rpw with CPython I get the error message below.
```
#! python3
from rpw import db
```
I have pyRevit v4.7.5 installed using CPython 3.7.2 / IronPython 2.7.7. 
The error only appears when using CPython but not with IronPython. I'd be happy to use db.Transaction with CPython. Hope there's some way.

![RPW_Import](https://user-images.githubusercontent.com/60828374/79359412-df59e100-7f42-11ea-9f81-986398830c23.PNG)

**Comment by thazell** [comment]
I don't think the rpw library is developed to work with CPython

**Comment by eirannejad** [comment]
@vengelhard `rpw` had been originally written to work with IronPython. It needs major modifications to make it work with CPython. This is definitely in the pipeline.

**Comment by vengelhard** [comment]
Thanks for the info. Good to hear it's a future target.
