### ISSUE TITLE
Generate Revision Report

### ISSUE THREAD

**Issue by Arikado24** [eirannejad/pyRevit#881]
**Is your feature request related to a problem? Please describe.**
When creating a Revision Report, the report will only pull from revisions clouds that are created directly on the sheet, and not any that have been created inside any views. 

It is our standard practice to create revisions clouds in the view, since the views can often move around and we wanted the clouds to stay with the information. 

**Describe the solution you'd like**
If possible, I'd like the revision report to include references to clouds that were created in the views. 

**Describe alternatives you've considered**
Well... I could transfer my clouds to the sheet instead of the views... but that would go against our office standards. 

If there were a way to create a schedule within Revit that pulls from Revision Clouds and their comment field, that would also be an option. 

**Additional context**
That's all from me. Thanks for the time and the amazing plug-in!

**Comment by datcomputerguy** [comment]
I'd love this as well.
Also the ability to create a list of the sheet name and then each revision and show the comments for each revision cloud would be nice so I could generate a report of all the changes I have made.

**Comment by archibank** [comment]
I've created this script for my firm, but need to some cleaning up it... I'm not a programmer so the code is pretty messy, but it works... I think Ehsan would want to some cleaning up of it too... You can select one or many revisions, from a selection window...
![Revision Coments output](https://user-images.githubusercontent.com/55449858/81434633-154a4980-912c-11ea-9b87-ecc63af4413a.jpg)

**Comment by DuncanLithgow** [comment]
@archibank that's looks a lot like what I was going to ask for! How do we share scripts for pyRevit?

What I was specifically looking for is the ability to select thing like 'Ignore issued revisions sequences' 'Ignore hidden revision clouds' 'Ignore hidden revisions tags' and so on. Sounds like this is the sort of thing you've implemented. I'd love to try it.

**Comment by ivanzep** [comment]
@archibank can you share your script? 
Thanks
