### ISSUE TITLE
pyrevit 4.7.6 make pattern issue

### ISSUE THREAD

**Issue by brzesiak** [eirannejad/pyRevit#882]
Hi,
i have problem with pyrevit on revit 2020 
I cant make any pattern based on single lines

I tried with 4.7.6 version and 4.6.24 -shows me the same issue

![image](https://user-images.githubusercontent.com/64070954/79847526-253dfb80-83c0-11ea-88fe-2b3b8be834ab.png)

**Comment by eirannejad** [comment]
Similar to #871 that had been closed. OK I'll take another look. Please send me any example files if possible.

**Comment by eirannejad** [comment]
Follow conversation on #871

**Comment by brzesiak** [comment]
https://we.tl/t-m3EOTSoEBl thank you
