### ISSUE TITLE
Tool to Clear BIM360 Collaboration Cache

### ISSUE THREAD

**Issue by eirannejad** [eirannejad/pyRevit#883]
Cache is stored under
`%LOCALAPPDATA%\Autodesk\Revit\Autodesk Revit 20XX\CollaborationCache`

**Comment by IMVVVVVIP** [comment]
> Cache is stored under
> `%LOCALAPPDATA%\Autodesk\Revit\Autodesk Revit 20XX\CollaborationCache`

**Comment by eirannejad** [comment]
Fixed and will be published with next release
