### ISSUE TITLE
Revit 2019 Crashes on startup after installing pyrevit 4.7.6

### ISSUE THREAD

**Issue by mmcgowen23** [eirannejad/pyRevit#884]
Revit 2019 Crashes on startup after installing pyrevit 4.7.6.. Revit opens originally but during startup Revit disappears as if it failed but no errors show up. I was still running the 4.7 beta prior to this with no issues. I uninstalled pyrevit and Revit opens as normal. I also downloaded 4.7.5 pyrevit and it seems to work fine just not the latest release.

**Comment by eirannejad** [comment]
Does it show any errors?

**Comment by mmcgowen23** [comment]
No it never pulls up the pyrevit startup window before revit closes.

**Comment by eirannejad** [comment]
would you mind clearing the caches maybe in command line `pyrevit caches clear --all` and try, Is this isolated to 2019?

**Comment by mmcgowen23** [comment]
I cleared cache but still not working. As far as I know its just 2019.2.2 but its also the only version we have in office so I haven't checked another version. 

Here is the info from loading on 4.7.5...not sure what might be helpful to you in this since this is working fine. 
INFO [pyrevit.loader.sessioninfo] pyRevit version: 4.7.5 - </> with  in ['pdx', 'hio', 'rno'] 
INFO [pyrevit.loader.sessioninfo] pyRevit Rocket Mode enabled.  
INFO [pyrevit.loader.sessioninfo] Host is Autodesk Revit 2019.2 (build: 20190808_0900(x64) id: 2540) 
INFO [pyrevit.loader.sessioninfo] Running on: 2.7.9 (IronPython 2.7.9 (2.7.9.0) on .NET 4.0.30319.42000 (64-bit)) 
INFO [pyrevit.loader.sessioninfo] Home Directory is: C:\Users\matt\AppData\Roaming\pyRevit-Master 
INFO [pyrevit.loader.sessioninfo] Session uuid is: 23db783b-068f-454a-82c1-d6c90cef55be 
INFO [pyrevit.loader.sessioninfo] Runtime assembly is: pyRevit_2019_b04e22df67e17b37_PyRevitLabs.PyRevit.Runtime 
INFO [pyrevit.loader.sessioninfo] Config file is (User): C:\Users\matt\AppData\Roaming\pyRevit\pyRevit_config.ini

**Comment by mmcgowen23** [comment]
Sorry also as a side question, does the copy/paste state for crop region work with section/elevation views now?

**Comment by eirannejad** [comment]
Ok. Take a look at the instructions on this page and send me the log file please
https://www.notion.so/pyrevitlabs/Collecting-Debug-Log-61941fa7782844e98e416e66ac39e4cf

**Comment by mmcgowen23** [comment]
[pyRevit_2019_13460_runtime.log](https://github.com/eirannejad/pyRevit/files/4732694/pyRevit_2019_13460_runtime.log)

Sorry for the delay

**Comment by mmcgowen23** [comment]
@ashwinpr3009 You can try sending him the debug log by following the instructions on this link.

https://www.notion.so/pyrevitlabs/Collecting-Debug-Log-61941fa7782844e98e416e66ac39e4cf

It is pretty easy to do and then for the mean time I went back to using 4.7.5. until the issue is resolved.

**Comment by ashwinpr3009** [comment]
i installed pyRevit 4.7.5 on revit 2019 it installed without any issue, now i am trying to create an new custom extension with a python file in it, push button is created but not working it gives a dialogue box says "cannot find target file. Maybe deleted?" i am a very new user to pyRevit so confused and got stuck here. Please help me

**Comment by n8mulder** [comment]
Hello. This issue is happening to one of our users on all versions of Revit when 4.7.6 is installed. Here is log from Revit 2020.
[pyRevit_2020_20968_runtime.log](https://github.com/eirannejad/pyRevit/files/4799500/pyRevit_2020_20968_runtime.log)

**Comment by karim070505** [comment]
Similar issue I am facing for Revit 2020, Revit opens originally after opening a project revit crashes. I have no issue for Revit 2019 and 2018.

**Comment by eirannejad** [comment]
Hmm. This is odd. The debug logs don't show anything about the error. They just suddenly stop. Let me think and see what I can do. Could anyone of you potentially let me remote in to the machine with error and take a look at why it is failing?

**Comment by n8mulder** [comment]
Hello,

I'd be up for that. I've been using 4.7.6 without issue pretty much since
it was released. However, this morning I installed a Bluebeam update and
now I am suffering the same issue. I've downgraded to 4.7.5 to keep working
for the time being.

Thanks!

Nathan

**Comment by eirannejad** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/942

**Comment by eirannejad** [comment]
Hey. So v4.8 is out. Would you mind testing and see if Revit loads? I'm hoping the internal compiler changes would solve this issue

**Comment by n8mulder** [comment]
I gave 4.8 a try but Revit did not load (20 and 19).

**Comment by eirannejad** [comment]
Okay I'd appreciate any error reports. Go under `%APPDATA%/pyRevit` and for 2019 and 2020, find the `*runtime*.log` file inside these folders and send them to me please

**Comment by n8mulder** [comment]
Files attached.

**Comment by eirannejad** [comment]
@n8mulder Would you mind replying to this on the github thread? Replying from email does not bring the attachments

**Comment by n8mulder** [comment]
[pyRevit_2018_c79cd9fdf5f913c0_PyRevitLabs.PyRevit.Runtime.log](https://github.com/eirannejad/pyRevit/files/5099584/pyRevit_2018_c79cd9fdf5f913c0_PyRevitLabs.PyRevit.Runtime.log)
[pyRevit_2019_c79cd9fdf5f913c0_PyRevitLabs.PyRevit.Runtime.log](https://github.com/eirannejad/pyRevit/files/5099585/pyRevit_2019_c79cd9fdf5f913c0_PyRevitLabs.PyRevit.Runtime.log)
[pyRevit_2020_c79cd9fdf5f913c0_PyRevitLabs.PyRevit.Runtime.log](https://github.com/eirannejad/pyRevit/files/5099587/pyRevit_2020_c79cd9fdf5f913c0_PyRevitLabs.PyRevit.Runtime.log)
[pyRevit_2021_c79cd9fdf5f913c0_PyRevitLabs.PyRevit.Runtime.log](https://github.com/eirannejad/pyRevit/files/5099588/pyRevit_2021_c79cd9fdf5f913c0_PyRevitLabs.PyRevit.Runtime.log)

**Comment by eirannejad** [comment]
Okay these logs are all okay. Seems like the runtime is not the issue. When you say, does not load, does it show any errors? or just crashes Revit on load time?

**Comment by n8mulder** [comment]
It does not show any errors. I see the Revit splash screen for 10-20 sec
and then it just closes. I think before the pyRevit screen would normally
appear.

**Comment by ashwinpr3009** [comment]
i tried to install pyRevit version pyRevit v4.7.6 on Revit 2021 it got crash, and this happened before also to me on Revit 2019.
here is my runtime log below
[pyRevit_2021_18860_runtime.log](https://github.com/eirannejad/pyRevit/files/5136632/pyRevit_2021_18860_runtime.log)
[pyRevit_2021_18860_runtime.log](https://github.com/eirannejad/pyRevit/files/5136636/pyRevit_2021_18860_runtime.log)


[pyRevit_2021_18860_runtime.log](https://github.com/eirannejad/pyRevit/files/5136627/pyRevit_2021_18860_runtime.log)

**Comment by eirannejad** [comment]
How about the 4.8.2 version?

**Comment by ashwinpr3009** [comment]
actually i did not try 4.8.2, will try now and let you know
well i am trying to install pyRevit on revit 2019.2 were we have our own inhouse addins and also trying on fresh  Revit2021 where there is no addons. i will share both the image.
![image](https://user-images.githubusercontent.com/65967391/91652948-f2fa8400-eaac-11ea-95ec-5087237ed17c.png)
![image](https://user-images.githubusercontent.com/65967391/91652966-1cb3ab00-eaad-11ea-9228-98aa6f7abf17.png)
the pyRevit which is visible on the tab is lower version4.7.5

**Comment by eirannejad** [comment]
Focusing on making v4.8 more reliable so closing this issue for now. I'm thinking of opening pinned issues for these typical problems. Will link that when done.
