### ISSUE TITLE
cannot add extensions (previous failed cli installation)

### ISSUE THREAD

**Issue by sanzoghenzo** [eirannejad/pyRevit#885]
Hi,
first of all many many thanks for this wonderful project! I can't find the words to tell how much I like it...

**Describe the bug**

I don't know if it's a proper bug because I've messed up things a little...
The final result is that pyRevit loads in my Italian Revit version 2020.2, but I can't add my extension or enable the predefined extensions (ie pyRevitTutor).

The settings form works, but if I save and reload nothing changes, and if I re-open the settings there's no added extensions folder and the pyRevitTutor is still disabled.

I tried to uninstall and reinstall pyrevit a couples of times, but nothing changed.
I previously tried to deploy pyrevit via cli, but I incurred in an error and uninstalled it.

the curious thing is that if I delete `%APPDATA%\pyRevit\pyRevit_config.ini", the environment section is being recreated with the clone I specified in the long gone pyrevit cli installation

```ini
[environment]
clones = {"sws":"C:\\pyRevit\\sws\\sws"}
```

Things get stranger when I use the pyrevit cli

```cmd
PS > pyrevit clones --debug

clones = True
Debug: Checking for all: wiki 
Debug: Missing: wiki 
Debug: Checking for all: blog
Debug: Missing: blog
Debug: Checking for all: docs
Debug: Missing: docs
Debug: Checking for all: source
Debug: Missing: source
Debug: Checking for all: youtube
Debug: Missing: youtube
Debug: Checking for all: support
Debug: Missing: support
Debug: Checking for all: env
Debug: Missing: env
Debug: Checking for all: update
Debug: Missing: update
Debug: Checking for all: clone
Debug: Missing: clone
Debug: Checking for all: clones
Debug: Checking for all: info
Debug: Missing: info
Debug: Checking for all: open
Debug: Missing: open
Debug: Checking for all: add
Debug: Missing: add
Debug: Checking for all: forget
Debug: Missing: forget
Debug: Checking for all: rename 
Debug: Missing: rename 
Debug: Checking for all: delete
Debug: Missing: delete
Debug: Checking for all: branch
Debug: Missing: branch
Debug: Checking for all: version
Debug: Missing: version
Debug: Checking for all: commit
Debug: Missing: commit
Debug: Checking for all: origin
Debug: Missing: origin
Debug: Checking for all: deployments
Debug: Missing: deployments
Debug: Checking for all: engines
Debug: Missing: engines
Debug: Checking for all: update
Debug: Missing: update
==> Registered Clones (full git repos)
Debug: Try getting config as dict "environment:clones" 
Debug: Try getting config "environment:clones"
Debug: Config "environment:clones" = "{"sws":"C:\\pyRevit\\sws\\sws"}"
Debug: Normalized as "C:\pyRevit\sws\sws" 
Debug: Updating config "environment:clones = {}" 
Debug: Saving config file "C:\Users\sanzo\AppData\Roaming\pyRevit\pyRevit_config.ini" 
==> Registered Clones (deployed from archive/image)
```

And then reload pyRevit (either restarting revit or using the button), "clones" repopulates with the non existing clone entry.

**To Reproduce**

I don't think it's easily reproducible, but here's what I did:

- installed Revit 2020.2 (two times since the first one gave me an error);
- installed pyRevit CLI to test the deployment;
- incurred in an error (can't remember what error), so decided to uninstall it to make things easier and stick to a local pyRevit install;
- installed pyRevit 4.7.6;
- Started Revit, pyRevit correctly appeaded;
- Added my extensions folder to the Custom Extension Directories, saved and reloaded;
- my tab didn't show up.

**Expected behavior**

My extension tab should show up.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 1909 64-bit
 - pyRevit Version 4.7.6
 - pyRevit Environment: 

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
Unknown | Product: "Autodesk Revit 2020" | Manifest: "C:\Users\sanzo\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\sanzo\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2020 | Version: 20.2.12.1 | Build: 20200210_1400(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
==> Running Revit Instances
Error: Riferimento a un oggetto non impostato su un'istanza di oggetto.
Run with "--debug" option to see debug messages
```

**EDIT**: I've added the Revit entry to my `pyrevit-hosts.json` (PR soon to be submitted), here's the remainder of `pyrevit env`:

```
==> Installed Revits
2020.2.1 (New Install) | Version: 20.2.12.1 | Build: 20200210_1400(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
==> Running Revit Instances
PID: 13984 | 2020.2.1 (New Install) | Version: 20.2.12.1 | Build: 20200210_1400(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2020"
==> User Environment
Microsoft Windows 10 [Version 10.0.18363]
Executing User: SANZOLAPTOP\sanzo
Active User: SANZOLAPTOP\sanzo
Admin Access: No
%APPDATA%: "C:\Users\sanzo\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.7 v4.7.2 v4.X
Installed .Net-Core Target Packs: v2.2.401 v3.1.201
pyRevit CLI 0.25.0.0
```

**Additional context**
Here's the log for when I ctrl+click the reload button: 
[ClonesProblemLog.html.txt](https://github.com/eirannejad/pyRevit/files/4540397/ClonesProblemLog.html.txt)

It seems that the re-population of the clones is prior to the reloading phase (it keeps finding and removing the sws clone)

**Comment by sanzoghenzo** [comment]
Ok, I solved it; I needed to delete the file "C:\ProgramData\pyRevit\pyRevit_config.ini" that was still there.

pyrevit looks at this file first, then parses it and removes the invalid clones.
Is that a feature of a bug?

**Comment by eirannejad** [comment]
@sanzoghenzo Yes the config file under `%PROGRAMDATA%` is the admin config and takes over the local user config under the `%APPDATA%`

See here to learn more about how the configs work
https://www.notion.so/pyRevit-Configuration-32d915aa7b3f4005bc9d5757e2d1f672

**Comment by sanzoghenzo** [comment]
Thanks @eirannejad, I overlooked that.

In the docs it's stated that

> pyRevit will use this config file as the seed on the first run

But in my case it was on every run, not only the first.

Also:

> All the future changes to the configs are written to the main config file and not the seed. The seed is used only to bootstrap the main config.

I should have mentioned that before: in my tries, i `pyrevit clones delete --all` and `pyrevit clones forget --all`, so I think the main config file should have overridden the seed file, but then again, the seed file changed the clones config every time.

I'm ok with that (but it needs to be better specified in the docs), and I'm aware that my was an edge case, but I suggest that invalid seed files should not lock user configuration. Or at least display a warning that the seed is invalid and can cause troubles.

Consider it a "lowest priority issue", if I have some spare time I can try to investigate it further and come up with a PR.

Thanks for your time

**Comment by eirannejad** [comment]
Uh you are absolutely right. I added a fix so pyrevit would use the seed file to bootstrap only if a user config file does not already exist.

**Comment by thazell** [comment]
Thanks for resolving this @eirannejad we have been totally stumped with this exact issue.
Is there a way to update the seed file through the CLI?
