### ISSUE TITLE
Error after installing CLI 0.25.0.0

### ISSUE THREAD

**Issue by risaku80** [eirannejad/pyRevit#886]
Hello, I am receiving this error when trying any command after installing pyRevit CLI 0.25.0.0

![image](https://user-images.githubusercontent.com/8203446/80398095-1f935a80-8885-11ea-9df0-22cd047f4151.png)

**Comment by eirannejad** [comment]
Is this happening when loading pyRevit?! Would you mind taking a screenshot of the pyRevit about window?

**Comment by risaku80** [comment]
This issue is taken care of
