### ISSUE TITLE
pyrevit tab does not show up

### ISSUE THREAD

**Issue by sharkmullet** [eirannejad/pyRevit#890]
I have Revit 2017 installed with PyRevit.  I just installed Revit and Revit LT 2021 versions.  The PyRevit tab doesn't show up in the 2021 versions.  Can I not have PyRevit installed in both 2017 and 2021?

**Comment by eirannejad** [comment]
I don't think Revit LT loads third-party addons

**Comment by sharkmullet** [comment]
Ok, but it is also not loading in full Revit 2021

Tyler F. Wallace | AIA, LEED® AP BD+C

*TFWA*

www.tfw-a.com

**Comment by eirannejad** [comment]
Okay then. Please open a command prompt, run `pyrevit env` and share the results here so I can take a look.

**Comment by sharkmullet** [comment]
Here it is:

C:\Users\tyler>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.6" | Path:
"C:\Users\tyler\AppData\Roaming\pyRevit-Master"
==> Attachments
Unnamed-72DBEF6 | Product: "2017.2.3" | Engine: 277 | Path:
"C:\ProgramData\pyRevit\pyRevit-v45\pyRevit" | Manifest:
"C:\ProgramData\Autodesk\Revit\Addins\2017\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\tyler\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64)
| Language: 1033 | Path: "C:\Program Files\Autodesk\Revit LT 2021"
2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64)
| Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021"
2017.2.3 | Version: 17.0.1150.0 | Build: 20171027_0315(x64) | Language:
1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.18362]
Executing User: THINKPAD\Tyler
Active User: THINKPAD\Tyler
Admin Access: No
%APPDATA%: "C:\Users\tyler\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.25.0.0

**Comment by eirannejad** [comment]
Seems like you have another installation of pyRevit under `C:\ProgramData\pyRevit\pyRevit-v45\pyRevit`

Open a command prompt and run:

`pyrevit attach master 277 --installed`

This should attach pyRevit to all your installed Revit versions. If you see any more errors send me a `pyrevit env` again so I can see the changes

**Comment by sharkmullet** [comment]
Ok great.  This will not disable my revit 2017 pyrevit will it?

**Comment by eirannejad** [comment]
It will. Use this command instead for Revit 2021

`pyrevit attach master 277 2021`

this will attach to 2021 only

Or run these:
```
pyrevit clones add oldpyrevit "C:\ProgramData\pyRevit\pyRevit-v45\pyRevit"
pyrevit attach master 277 --installed
pyrevit attach oldpyrevit 277 2017
```

**Comment by sharkmullet** [comment]
I ran the first one.  It works!  Thank you

**Comment by sharkmullet** [comment]
Can I re-open this?  I cannot print, the dialog looks like below.  Should there be a list of drawings?  The index is not empty.  I tried repairing pyrevit with a fresh download, but it removed the tab again.  After running the CMD from before, it loads, but I still cannot print.  I need to have pyrevit 2021 & 2017 because I have projects in both, but if I can't I will update the 2017 version.
 
![Annotation 2020-05-14 153510](https://user-images.githubusercontent.com/2855537/81994721-56939b00-95fd-11ea-8617-eb8c607b58cd.jpg)

**Comment by Rocky-EA** [comment]
I have the same issue. I installed the latest in Revit 2021 and it does not show as a tab in the menu bar. I tried the instruction above and still not show. Is there another way to make it work and show up in Revit 2021? 
I uninstalled and deleted the pyrevit folder. And installed fresh.
I also tried installing it in the main C folder & created PyRevit folder.
Any suggestion, is much appreciated.
Thanks.

**Comment by eirannejad** [comment]
@sharkmullet Would you mind exporting your sheet index to a text file and share that here? (Export using the Revit export to CSV option)

**Comment by eirannejad** [comment]
@Rocky-EA Would you mind running `pyrevit env` in your command line and share the report please?

**Comment by Rocky-EA** [comment]
@eirannejad I found out that for some reason I'm missing "pyrevit.addin" in the C:\Users\name\AppData\Roaming\Autodesk\Revit\Addins\2021 folder. I copied one from my other laptop and use that. I just modified the drive letter & name.
But it works in pyRevit_4.7.6, which is what the laptop has. So I used that install for now. The 4.8 beta3, I'm getting errors. So I uninstalled that and installed 4.7.6. I'm afraid to install 4.8 as it might mess up my system and couldnt make pyrevit work.
I'm a BIM manager and have zero programming knowledge.

**Comment by eirannejad** [comment]
@Rocky-EA You can use the `pyrevit attach` option of the pyRevit CLI to create the necessary `.addin` files and attach pyRevit to your installed Revit versions

See this for more info on the CLI: https://www.notion.so/pyRevit-CLI-c50de95259114db795db5bd3f19f8e2a

**Comment by Rocky-EA** [comment]
> @Rocky-EA You can use the `pyrevit attach` option of the pyRevit CLI to create the necessary `.addin` files and attach pyRevit to your installed Revit versions
> 
> See this for more info on the CLI: https://www.notion.so/pyRevit-CLI-c50de95259114db795db5bd3f19f8e2a

Thank you so much. Just want to express my sincere appreciation.

**Comment by eirannejad** [comment]
@Rocky-EA @sharkmullet So [I just updated the hosts file information (has information about all revit versions) on the repo](https://github.com/eirannejad/pyRevit/blob/4319ff011c36f24b26b2394d6862e685e566f26b/bin/pyrevit-hosts.json#L1353). Please open a command prompt and run `pyrevit update`. This will grab the most recent versions of these info files and places them under `%APPDATA%/pyRevit/Cache`. Then you can run `pyrevit revits --installed` to list the installed Revits. If it shows the correct Revit versions listed, then it is finding the data correctly.

Now you can re-attach pyRevit to all installed Revit versions using `pyrevit attach master 277 --installed`

Let me know if this works.

**Comment by Fozibehr** [comment]
And like magic pyRevit has returned to my Revit. Thank you for your assistance.

**Comment by sharkmullet** [comment]
I just put together another computer, and I am apologize if I am doing user error, but I can't get it to load again.

Here is my "pyrevit env"

> C:\Users\tyler>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
==> Installed Extensions
==> Default Extension Search Path
C:\Users\tyler\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2021 | Version: 21.1.20.44 | Build: 20201109_1530(x64) | Language: 1033 | Path: "Revit 2021\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages

C:\Users\tyler>

**Comment by sharkmullet** [comment]
and here is another error

> C:\Users\tyler>pyrevit attach master 277 2021
Error: Can not find clone "master"
Run with "--debug" option to see debug messages

C:\Users\tyler>

**Comment by delarquitecto** [comment]
my issue is similar w revit 2020--pyRevit not showing up:


C:\Users\Greg Wartak>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Greg Wartak\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2020.2.1 (New Install) | Version: 20.2.12.1 | Build: 20200210_1400(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2018 First Customer Ship | Version: 18.0.0.420 | Build: 20170223_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
2017 First Customer Ship | Version: 17.0.416.0 | Build: 20160225_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
==> Running Revit Instances
PID: 19568 | 2020.2.1 (New Install) | Version: 20.2.12.1 | Build: 20200210_1400(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2020"
==> User Environment
Microsoft Windows 10 [Version 10.0.19041]
Executing User: LAPTOP-GREGOR\Greg Wartak
Active User: LAPTOP-GREGOR\Greg Wartak
Admin Access: No
%APPDATA%: "C:\Users\Greg Wartak\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.6.0

C:\Users\Greg Wartak>

**Comment by delarquitecto** [comment]
Could anyone help me understand why it is not showing up?

**Comment by eirannejad** [comment]
It's not attached. See this please https://www.notion.so/pyrevitlabs/pyRevit-Is-Installed-But-Does-Not-Load-f6495adb56254e9e8021f8a68e3b2ab7

**Comment by delarquitecto** [comment]
brilliant! it worked! thank you eirannejad
