### ISSUE TITLE
Save Print Settings

### ISSUE THREAD

**Issue by RBroersen** [eirannejad/pyRevit#891]
Is it possible to save the Print Setting in Print Sheets?
For some reason it does not recognise my Paper Sizes automatically and now we have to manually change the settings each time.
Maybe by adding a (shared) parameter in a project linked to Sheets?
Greetings, René Broersen

**Comment by eirannejad** [comment]
Hmm. Great idea. Lemme think of a good way to implement this

**Comment by eirannejad** [comment]
Fixed and will be published with next release
