### ISSUE TITLE
CPython: updated lib-scripts are not used

### ISSUE THREAD

**Issue by mbaicad** [eirannejad/pyRevit#895]
I am having some weird behavior when using the CPython Engine instead of the IronPython one:

Changing a module in the bundle-lib while having Revit up and running, does not lead to changes (as would be expected) on the next execution of some script using the lib-module.

However, changing the script (pushbutton) itself does result in a change executing the script.

Any idea why this might happen?

**Comment by eirannejad** [comment]
pyRevit caches the executing engine to speed up the tool (Rocket mode). This means that the modules that are already imported, will not be re-imported. However during tool development, you can CTRL+ALT+SHIFT click on the tool and this would force pyRevit to clear the cache.

See [# CTRL-ALT-SHIFT-Click: Reload Engine](https://www.notion.so/Button-Click-Modes-c829c5a60ddb4c3e819bc93dfbc3c98b#1f2b31b04bca4cacab0f7cb4d035f396)

**Comment by mbaicad** [comment]
Thanks for the feedback. I actually stumbled upon the Rocket mode by myself and disabled it for development.

However, now I'm getting the following error:
![grafik](https://user-images.githubusercontent.com/59603430/82188356-0d3d9700-98ee-11ea-96fd-54911184b976.png)

With pyRevit v4.7.6 and CPython 3.6.8
