### ISSUE TITLE
Sync Views Not Working pyRevit v4.7.6

### ISSUE THREAD

**Issue by PhillipA2010** [eirannejad/pyRevit#897]
**Describe the bug**
Hi,

I recently installed pyRevit v4.7.6 and noticed that the "Sync Views" does not work. I am able to toggle the icon on but it does not sync the views. Any help would be greatly appreciated because I would use that feature a lot.

Thank you

**Expected behavior**
I expected to be able to sync plan views in Revit using the "Sync Views" toggle

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version v4.7.6

**Comment by TengahMR** [comment]
I can confirm that Sync Views is not working in 4.7.6

**Comment by eirannejad** [comment]
Fixed and will be published with the next release. You can grab the modified script and replace with existing in 4.7.6 to make if work for now.

https://github.com/eirannejad/pyRevit/blob/ed0e2496a532e93c9e4512a20ee1c97382c9f3eb/extensions/pyRevitTools.extension/pyRevit.tab/Toggles.panel/toggles2.stack/Sync%20Views.smartbutton/script.py

**Comment by PhillipA2010** [comment]
The modified script that you provided worked successfully. 

Thank you!
