### ISSUE TITLE
Make Pattern Error - Revit 2020

### ISSUE THREAD

**Issue by EastopArch** [eirannejad/pyRevit#898]
Hi and thank you for making this plugin.

**Error Message Below**
﻿ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.AttributeError'>:'FilledRegionType' object has no attribute 'FillPatternId'

ERROR [patmaker] Error creating pattern element. | 'FilledRegionType' object has no attribute 'FillPatternId'

Installed Revit: 2020
Installed pyrevit: 4.7.6

**To Reproduce**
Steps to reproduce the behaviour:
Followed instructions to create Pattern.

**Expected behavior**
No Pattern and error message.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 1903
 - pyRevit Version 4.7.6

**Comment by eirannejad** [comment]
Fixed and will be published with next release https://github.com/eirannejad/pyRevit/issues/871

**Comment by kvodavis** [comment]
Hi! I'm having the same issue  - error reads as below:  (Downloaded new PyRevit today and using with Revit2021)
*and agree, thanks for the great pattern making software!*

ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.AttributeError'>:'FilledRegionType' object has no attribute 'FillPatternId'

ERROR [patmaker] Error creating pattern element. | 'FilledRegionType' object has no attribute 'FillPatternId'

**Comment by eirannejad** [comment]
Okay. I promise I resolved it this time. I had missed an instance of the API change :/

**Comment by EastopArch** [comment]
Thanks so much and thank you for putting in the time to create such a good plugin. Autodesk should really get people like yourselves on the books.

 

Thanks again,

 

Liam

 

LIAM EASTOP

 

 <http://www.eastop.com.au/> 

 

LEVEL 1 / 297 – 301 NAPIER ST. FITZROY

0438 598 473 / (03) 9134 6689

 <http://www.eastop.com.au/> EASTOP.COM.AU

 <https://www.instagram.com/eastop_architects/> @EASTOP_ARCHITECTS

 

This email and any attachments may be confidential and also privileged. If you are not the intended recipient please notify the sender and delete all copies of this transmission immediately, along with any attachments. You should not copy it or use it for any purpose, nor disclose its contents to any other person.

**Comment by fabianunotm** [comment]
Hello Ehsan ... thank you for this wonderful complement, greetings from Ecuador

I have revit 2022 and the make pattern option works, how do I solve it?
