### ISSUE TITLE
Install\Uninstall issue in non-admin corporate environment

### ISSUE THREAD

**Issue by TassieTrooper** [eirannejad/pyRevit#899]
**Describe the bug**
Non-admin users can install the program but then are not able to remove the program as it needs administrative rights, yet when administrative credentials are entered in the UAC elevation prompt the uninstall fails.

**To Reproduce**
*Domain Joined Computer and logged in with standard, non-admin user account:

1. Install 'pyRevit_4.7.6_Signed' using standard, logged in user
2. Open Settings->Apps
3. Scroll down to 'pyRevit'
4. Click on 'pyRevit'
5. Click 'Uninstall'
6. Enter administrative credentials
7. pyRevit remains installed.

Additional:
1. Login to PC using administrator account
2. Open Settings->Apps
3. Cannot uninstall pyRevit via this logged in account as pyRevit is not in the list of installed applications.

**Expected behavior**
pyRevit should uninstall via Apps after the UAC admin credentials have been entered.
pyRevit should be visible in 'Apps' for all users, and then uninstall as per above.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10 1903/1909
 - pyRevit Version 4.7.6

**Additional context**
We are tying to install this application silently via remote push with elevated credentials/admin account - via SCCM\LanSweeper - with the command line of 'pyRevit_4.7.6_Signed.exe /exenoui /exenoupdates /quiet' , yet it fails as it cannot be installed via secure desktop because it expects to be installed with the local user context\session within %AppData%\Roaming\pyRevitMaster.

Please see if you can alter the bootstrapper\installer to make this installer friendly in a Windows Domains and standard, non-admin users.

**Comment by TassieTrooper** [comment]
Hi. Hope you are well. Any progress with this? if you want assistance with the testing on our system let me know.

**Comment by eirannejad** [comment]
The internal powershell scripts that were part of the pyRevit installer have been removed. The next installer does not require any priviledges to install. Fixed and will be published with next release
