### ISSUE TITLE
adding a second language - best way?

### ISSUE THREAD

**Issue by Thomas84** [eirannejad/pyRevit#90]
hi all!
I try to use the python addin with a german template. Some scripts need an adjustment (e.g. to change the categories, the Tool names, etc. ). What do you think is a good way to implement a second language? It would be great, if I can still use the downloadUpdates function. 
I think to replace everything with a german verion of the scripts is not so clever =)
Any suggestions?

Thanks, Thomas

**Comment by eirannejad** [comment]
Interesting. I need to look into adding locale features to this. Let me do some research.

**Comment by eirannejad** [comment]
Thomas,
I looked in to this. Seems like the best way is to use a *.resx resource file similar to what's being used in Visual Studio for localization. But this means for every prompt and print, there needs to be a string resource. Unfortunately at this time, this adds a lot of overhead and complexity to the scripts. I like the scripts to be simple so everyone can study and learn how to program Revit with IronPython.

However you're more than welcome to add language checks (check for the Revit's language to print the correct string) using `__revit__.Application.Language` to the scripts as you wish and send me a pull request.

Thanks!
