### ISSUE TITLE
Lost Convert Family to Face Hosted in 4.7.6

### ISSUE THREAD

**Issue by eluvs** [eirannejad/pyRevit#900]
Ever since installing pyRevit 4.7.6 I have lost the ability to change any wall hosted family to a face hosted family. I change the family to every single type and just get the error that it is not supported by Revit API. To fix the issue I went back to 4.7.4 since I knew it worked in that version. I am not sure if this problem occurs in 4.7.5 as well, but I know it is for 4.7.6.

**Comment by eluvs** [comment]
I tried 4.7.5 and couldn't use the tool on an Electrical Fixture family.

**Comment by eirannejad** [comment]
Revit API only allows converting certain families to face-hosted

**Comment by eluvs** [comment]
What are the types of families that Revit allows you to convert? I tried to use the tool to convert a lighting fixture, but it still didn't work. I ended up having to use the method that Paul Aubin goes through in this LinkedIn Learning video https://bit.ly/3vayIKc

**Comment by eirannejad** [comment]
There is not a list but you can check (the tool uses this to check) using `DB.FamilyUtils.FamilyCanConvertToFaceHostBased()` whether a family can be converted or not

**Comment by eluvs** [comment]
Thank you very much. This is helpful
Eric Lovell
