### ISSUE TITLE
Non-existence of file "install_addin.bat" on the latest version of pyRevit

### ISSUE THREAD

**Issue by Janiry** [eirannejad/pyRevit#902]
Please help. I'm planning to install this latest pyRevit version to my Revit 2020.2 using windows cmd.

**Comment by eirannejad** [comment]
See this please
https://www.notion.so/Install-pyRevit-98ca4359920a42c3af5c12a7c99a196d

Some of the videos on the youtube channel are very old. Refer to this wiki for all info regarding pyRevit

https://www.notion.so/pyRevit-bd907d6292ed4ce997c46e84b6ef67a0
