### ISSUE TITLE
No pyRevit Dev after I installed pyRevit

### ISSUE THREAD

**Issue by kunjapranavi** [eirannejad/pyRevit#904]
**Describe the bug**
Hi I installed pyRevit 4.7.6 for Revit 2020 but after Installation I don't see pyRevitDev extension as I wanted to use Cpython Command. I check to enable it but I don't find it there. I mean I don't find pyRevitDev  at all even in the repository.

**Comment by eirannejad** [comment]
pyRevitDev extension does not ship with pyRevit by default. Make a clone of the pyRevit repo to access the development extensions
