### ISSUE TITLE
CPython engine errors

### ISSUE THREAD

**Issue by DmytroSE** [eirannejad/pyRevit#905]
Hi! I am trying to use CPython 372 engine, but scripts often have errors. I just need to know if there is someone else with the same problems or just me. Reinstalled PyRevit many times.
Here are all situations i faced:
1. First click on Cpython script, after Revit startup, always shows this error:
![image](https://user-images.githubusercontent.com/45512632/82822280-2e822280-9eae-11ea-9909-93fc6e1cce68.png)
But next try is successful. 

Next, if I reload pyrevit and run same script:
#for example:
```
#! python3
# # -*- coding: utf-8 -*-
a = 1 +1
print(a)

```
2. Often CPython fails to print() something and a message appears:
![image](https://user-images.githubusercontent.com/45512632/82822435-74d78180-9eae-11ea-90c1-6244f1affeaa.png)
Need to restart revit.

3. Or the script refuses to load in any case, only revit restart helps:
![image](https://user-images.githubusercontent.com/45512632/82822610-bcf6a400-9eae-11ea-9226-08cc21ee1db2.png)

4. End the last thing, i want to use the most, are site-packages. But adding PYTHONPATH is not helping. ModuleNotFoundError appears:
![image](https://user-images.githubusercontent.com/45512632/82823066-8bcaa380-9eaf-11ea-885d-745f8f39be88.png)

Additional information:
![image](https://user-images.githubusercontent.com/45512632/82823118-a866db80-9eaf-11ea-81a7-27ad2f5587ae.png)

![image](https://user-images.githubusercontent.com/45512632/82823139-b61c6100-9eaf-11ea-9c87-1d92064cb2ad.png)

![image](https://user-images.githubusercontent.com/45512632/82824358-dbaa6a00-9eb1-11ea-99bb-009c6837f954.png)

```
 C:\Users\Mitya>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.6" | Path: "C:\Users\Mitya\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2020.2 (Full Install)" | Engine: 277 | Path: "C:\Users\Mitya\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\Mitya\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
master | Product: "2019.1" | Engine: 277 | Path: "C:\Users\Mitya\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\Mitya\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
==> Installed Extensions
ArkhoGroupExtension | Type: Unknown | Repo: "" | Installed: "D:\дима\python\Arkho Group Extension\ArkhoGroupExtension.extension"
BimApi | Type: Unknown | Repo: "" | Installed: "D:\Blog Data\Copy View With Detailing\BimApi.extension"
Lessons | Type: Unknown | Repo: "" | Installed: "D:\PyRevitExtenion\Lessons.extension"
==> Default Extension Search Path
C:\Users\Mitya\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
D:\PyRevitExtenion
D:\дима\python\Arkho Group Extension
D:\Blog Data\Copy View With Detailing
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2020.2 (Full Install) | Version: 20.2.1.1 | Build: 20191106_1200(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
2019.1 | Version: 19.1.0.112 | Build: 20180806_1515(x64) | Language: 1033 | Path: "D:\Programes\Autodesk\Revit 2019"
==> Running Revit Instances
PID: 15140 | 2019.1 | Version: 19.1.0.112 | Build: 20180806_1515(x64) | Language: 0 | Path: ""
==> User Environment
Microsoft Windows 10 [Version 10.0.18362]
Executing User: MITYA\Mitya
Active User: MITYA\Mitya
Admin Access: No
%APPDATA%: "C:\Users\Mitya\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.25.0.0 
```

**Comment by eirannejad** [comment]
Let's test something. Close Revits, open a command prompt and run `pyrevit caches clear --all`
Let me know if this made any change

**Comment by DmytroSE** [comment]
Only restarting Windows helps. So I managed to find dependencies. Please, check out the short video:
https://youtu.be/-FDW5hzbixE
00:00 - 00:44 -  Shows all errors.
00:44 - 01:05  -  My methode how to make it work.  After windows restart: DevTools -> EngineTest -> any other script 
On another PC I have the same situation

**Comment by eirannejad** [comment]
new cpython is being implemented
