### ISSUE TITLE
Hide line style category using CPython produces AttributeError

### ISSUE THREAD

**Issue by vengelhard** [eirannejad/pyRevit#906]
**Describe the bug**
When trying to hide a line style category in a view plan, the program raises an AttributeError when using CPython (see screenshot below). The complaint says that the `Category` object does not have an attribute `Visible` which is not the case - see Revit doc links below. Everything works correctly using the IronPython interpreter. 

Revit Docs:
[LineStyle Property of DetailLine object](https://www.revitapidocs.com/2019/691e64a2-e5ea-b619-4362-1a2c17e23b2f.htm)
[Visible Property of Category object](https://www.revitapidocs.com/2019/863e37ff-4415-5d39-d371-36c3284812d7.htm)

The code snippet below will be part of a script where CPython is needed so it would be very helpful to have it working in there.

**To Reproduce**

Revit 2019.2, pyRevit 4.7.6, CPython 3.7.2.

1. Create a pyRevit script using the sample code below.
2. Create a PlanView (that is not based on a view template) and draw a DetailLine of specific LineStyle.
3. Click on the button of the tool and select a DetailLine. 

```
#! python3
from Autodesk.Revit import DB
from Autodesk.Revit import UI
from Autodesk.Revit.UI.Selection import ObjectType

uidoc = __revit__.ActiveUIDocument
doc = uidoc.Document
active = doc.ActiveView

msg = "Pick a DB.DetailLine object"
selected_object = uidoc.Selection.PickObject(ObjectType.Element, msg)
el = doc.GetElement(selected_object.ElementId)
line_style_cat = el.LineStyle.GraphicsStyleCategory

trans = DB.Transaction(doc, "Hide Line")
trans.Start()
try: 
    line_style_cat.Visible[active] = False
except Exception as er:
    print(str(er))
    trans.RollBack()
else:
    trans.Commit()
```

**Expected behavior**
The line style category of the selected detail line should be hidden in the active view.

**Screenshots**
![image](https://user-images.githubusercontent.com/60828374/82917732-1543a980-9f74-11ea-954d-a0cd30f04b66.png)

**Comment by eirannejad** [comment]
Seems like cpython has an issue with the indexer property `.Visible`
Change the line to 
```
line_style_cat.set_Visible(active, False)
```
