### ISSUE TITLE
Pyrevit does not show up on any versions of Revit

### ISSUE THREAD

**Issue by kendinh216** [eirannejad/pyRevit#908]
**Describe the bug**

I had run the command below but the Attachment section is still blank.
`pyrevit attach master 277 --installed`

**To Reproduce**

**Expected behavior**
Pyrevit to show up in Revit

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.6.16
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`
C:\Windows\system32>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.6.16" | Path: "C:\Users\kyu\AppData\Roaming\pyRevit-Master"
==> Attachments
==> Installed UI Extensions
==> Installed Library Extensions
==> Default Extension Search Path
C:\Users\kyu\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.18363]
Executing User: GS\kyu
Active User: GS\kyu
Adming Access: Yes
%APPDATA%: "C:\Users\kyu\AppData\Roaming"
Latest Installed .Net Framework: ""
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.7 v4.7.2 v4.X
pyRevit CLI 0.9.0.0

**Comment by eirannejad** [comment]
Uhm you have a super super old version of pyRevit. Would you mind trying the most recent one?
