### ISSUE TITLE
pyrevit installation error

### ISSUE THREAD

**Issue by YLYLYL-wq** [eirannejad/pyRevit#909]
Hi, I downloaded the 'pyRevit_4.7.4_signed' from GitHub and failed to intall it. Please see attached pics and log. Please let me know why is that.

![WeChat Image_20200530201332](https://user-images.githubusercontent.com/66166438/83327915-24975f80-a2b2-11ea-91fb-a56ede885cd5.png)
![WeChat Image_202005302013321](https://user-images.githubusercontent.com/66166438/83327917-28c37d00-a2b2-11ea-9d2d-6c0a2074a553.png)
![WeChat Image_202005302013322](https://user-images.githubusercontent.com/66166438/83327925-2cef9a80-a2b2-11ea-9faa-a222f3294347.png)
![WeChat Image_202005302013323](https://user-images.githubusercontent.com/66166438/83327930-30832180-a2b2-11ea-9002-31e26d0b5dd5.png)
![WeChat Image_202005302013324](https://user-images.githubusercontent.com/66166438/83327931-337e1200-a2b2-11ea-97e3-ba48b39ec338.png)
[Microsoft_.NET_Core_Runtime_-_2.0.7_(x64)_20200530195844.log](https://github.com/eirannejad/pyRevit/files/4705595/Microsoft_.NET_Core_Runtime_-_2.0.7_.x64._20200530195844.log)

**Comment by eirannejad** [comment]
That's the Microsoft .net core runtime setup that is failing. Try to install that independently and then install pyRevit. 

https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-2.1.105-windows-x64-installer
