### ISSUE TITLE
Error determining current attached clone

### ISSUE THREAD

**Issue by zahmadsaleem** [eirannejad/pyRevit#910]
**Describe the bug**
Pyrevit > Setting always thow up :
`ERROR [Settings] Error determining current attached clone.`
also, engines dropdown is empty

**To Reproduce**
1. Installation (from an admin account)
```
pyrevit clone prcore corex --dest="c:\pyrevit"
pyrevit attach prcore 277 --installed --allusers
```
2 . Open revit (non admin user)
3. Pyrevit > Settings

**Screenshots**
![image](https://user-images.githubusercontent.com/11913101/83487223-4407d580-a4c8-11ea-8d4c-d849314e1706.png)
![image](https://user-images.githubusercontent.com/11913101/83487287-66015800-a4c8-11ea-9d3b-ab3590728a42.png)

**Possible Fix**
I did some digging and found out this
https://github.com/eirannejad/pyRevit/blob/c068953a0fdd5489561b3f74e5d9290de3fdd5db/dev/pyRevitLabs/pyRevitLabs.PyRevit/PyRevitAttachments.cs#L132

Its being called here, when clicking settings
https://github.com/eirannejad/pyRevit/blob/c068953a0fdd5489561b3f74e5d9290de3fdd5db/pyrevitlib/pyrevit/userconfig.py#L614

changing this line, fixed the issue
`return PyRevit.PyRevitAttachments.GetAttached(int(HOST_APP.version),allUsers = True)`

Not sure if this is actually an issue or if I'm the only one facing this. Any feedback would be helpful
Thanks

**Comment by eirannejad** [comment]
Sweet. Thanks a lot for catching the bug. I'll fix in the code 👍

**Comment by eirannejad** [comment]
Fixed and will be published with next release
