### ISSUE TITLE
Install Issues; Installer Default Location 

### ISSUE THREAD

**Issue by jmac-sDC** [eirannejad/pyRevit#914]
Helping a coworker install pyRevit she received the following issue, after installing and while booting Revit 2019. After closing the dialogue box, there was no ribbon window or indication that pyRevit installed. 

![pyRevit_install error_01](https://user-images.githubusercontent.com/66434645/83787812-90cae800-a651-11ea-8ea3-104301f67f70.png)

After this, we ran the debugger built in the install, but received the same error code. After that, we re-installed and I manually changed the install location to point towards her Autodesk Plug-in folder on her C: drive. That resolved the error above and allowed for the pyRevit ribbon to show-up and the tools to work as expected. When booting Revit though, the following screen appears:

![pyRevit_install error_02](https://user-images.githubusercontent.com/66434645/83787973-d2f42980-a651-11ea-956f-8e66fa57ff2c.png)

This isn't something I've seen on other instances of pyRevit. I expected it just loads Revit as normal after the install is complete and Revit has been booted up for the first time after. 

 - OS: [Microsoft 10]
 - pyRevit Version [4.7.6]

**Comment by eirannejad** [comment]
Okay I need a bit more info on this. Would you mind running `pyrevit env` on the command prompt and send me the results?

**Comment by jmac-sDC** [comment]
[cid:image003.png@01D63A8C.5CBC8720]

Let me know if this helps.

James Mackey
Architect

studiotrope Design Collective
2942 Welton Street
Denver, CO 80205
303-308-1144 main
720.506.3542 direct
jmac@studiotrope.com<mailto:jmac@studiotrope.com>
www.studiotrope.com<http://www.studiotrope.com/>
SBE Certified since 2005<http://studiotrope.com/the-collective/>
Registered with SBA for Federal Contracts<http://studiotrope.com/the-collective/>

news:
Restroom renovation at Boulder’s Main Public Library is an innovation highlight for the city<http://www.transformgov.org/articles/innovation%E2%80%A6-what>

**Comment by eirannejad** [comment]
@jmac-sDC Hey bud, the attachments don't come thru emails. Please respond on the github issue thread. Thanks!

**Comment by jmac-sDC** [comment]
Here we go, sorry about that! 
![pyRevit_install error_03](https://user-images.githubusercontent.com/66434645/83888465-13fa4580-a707-11ea-8899-60b9fb71e729.png)

**Comment by eirannejad** [comment]
Huh seems like the installation is missing the `pyRevitLabs.Nlog.dll`, Would you mind checking the install location and make sure the dll is there?

**Comment by jmac-sDC** [comment]
Sorry this hung out for so long. The .dll does not appear to exist in the install location. 

![screenshot_pyrevit](https://user-images.githubusercontent.com/66434645/89324893-3b0cbf00-d645-11ea-803d-0723c9a277f7.png)

**Comment by eirannejad** [comment]
Wow!!!! pyRevit seems to be installed directly inside the Revit roaming directory! This is a bad installation!! Did someone else install pyRevit on your machines?

**Comment by jmac-sDC** [comment]
Nope, it's been so long I can't say how it ended up there either. 

I assume the thing to do would be uninstall and re-install a clean copy?

**Comment by eirannejad** [comment]
Try the uninstaller and see if it cleans up this directory. You can always reinstall in the default or other location
