### ISSUE TITLE
cannot print

### ISSUE THREAD

**Issue by sharkmullet** [eirannejad/pyRevit#915]
I am unable to print.  No drawings show up in the list, see attached screenshot.  This happens to me on two computers.  One with Revit 2017 & 2021, the other with only Revit 2021.  The error is in 2021

![81994721-56939b00-95fd-11ea-8617-eb8c607b58cd](https://user-images.githubusercontent.com/2855537/84091218-a66d4400-a9a8-11ea-8bec-e6269d013890.jpg)

Microsoft Windows [Version 10.0.18362.836]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\tyler>previt env
'previt' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\tyler>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.6" | Path: "C:\Users\tyler\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2021 First Customer Ship" | Engine: 277 | Path: "C:\Users\tyler\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\tyler\AppData\Roaming\Autodesk\Revit\Addins\2021\pyRevit.addin"
master | Product: "2021 First Customer Ship" | Engine: 277 | Path: "C:\Users\tyler\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\tyler\AppData\Roaming\Autodesk\Revit\Addins\2021\pyRevit.addin"
Unnamed-72DBEF6 | Product: "2017.2.3" | Engine: 277 | Path: "C:\ProgramData\pyRevit\pyRevit-v45\pyRevit" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2017\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\tyler\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit LT 2021"
2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021"
2017.2.3 | Version: 17.0.1150.0 | Build: 20171027_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> Running Revit Instances
PID: 8728 | 2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2021"
PID: 30084 | 2017.2.3 | Version: 17.0.1150.0 | Build: 20171027_0315(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> User Environment
Microsoft Windows 10 [Version 10.0.18362]
Executing User: THINKPAD\Tyler
Active User: THINKPAD\Tyler
Admin Access: No
%APPDATA%: "C:\Users\tyler\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.25.0.0

**Comment by eirannejad** [comment]
See this https://github.com/eirannejad/pyRevit/issues/887
It's already been fixed and will be released with next version. There is a patch on the other issue thread so you can fix it in place before the next release

**Comment by sharkmullet** [comment]
thank you!
