### ISSUE TITLE
Pin script to specific engine version

### ISSUE THREAD

**Issue by sanzoghenzo** [eirannejad/pyRevit#916]
**Is your feature request related to a problem? Please describe.**

I'm using xlrd to read an excel file that has unicode chars (ie "å", "ä" and so on).
After some troubleshooting (and StackOverflow searches), I found out that I have to use the IronPython engine 2.7.9 in order to read the excel without any error (maybe 2.7.8 works too, but I didn't tested).
The problem is, I have to deploy the script to my colleagues, and some of them are using pyrevitlib inside RevitPythonShell, so:
- I have to remind everyone to switch to 2.7.9 to use the new script
- RPS users needs to constantly switch the engine between 2.7.7 and 2.7.9 (and restart Revit to do so).

**Describe the solution you'd like**

As for CPython script, it would be great if I can specify the (min/max/exact) engine version required to run the script somewhere in the script itself or in the bundle.yaml .

**Describe alternatives you've considered**

RPS compatibility could be addressed on the RPS side by upgrading to the latest IronPython engine; I didn't file any issue there yet, though

**Additional context**

The core problem for me (or better, what I deducted) is that IronPython 2.7.7 xml.etree.ElementTree doesn't handle unicode characters correctly.
I still have to understand IronPython and python engines fully, so I don't know if ElementTree/xml parsers are already inside the DLL and/or if it can be replaced by installing a newer version in site-packages.
Looking at xlrd code, it treats IronPython differently from CPython and only tries to import `xml.etree.ElementTree` (`xlrd\xlsx.py`line 29-30).

**Comment by eirannejad** [comment]
So I'm going to mark this as "On hold" since you can not load multiple IronPython or CPython engines into the Revit memory simultaneously. That's why the Settings window has a version selector.

that said, would you mind attaching an example excel file and script so maybe I can modify the `xlrd` module in place to make it work with 2.7.7?

**Comment by sanzoghenzo** [comment]
Thanks for the info, I suspected that, but still I was hoping for some dark magic :)

And thanks for taking the time to look into it!

The test is as simple as it gets: 

- an excel with german chars in the first cell [test.xlsx](https://github.com/eirannejad/pyRevit/files/4763229/test.xlsx)
- this two lines of code:
    ```python
    import xlrd

    workbook = xlrd.open_workbook("test.xlsx")
    ```

It will throw the error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sanzo\AppData\Roaming\pyRevit-Master\site-packages\xlrd\__init__.py", line 135, in open_workbook
  File "C:\Users\sanzo\AppData\Roaming\pyRevit-Master\site-packages\xlrd\xlsx.py", line 828, in open_workbook_2007_xml
  File "C:\Users\sanzo\AppData\Roaming\pyRevit-Master\site-packages\xlrd\xlsx.py", line 450, in process_stream_findall
  File "xml\etree\ElementTree.py", line 1182, in parse
  File "xml\etree\ElementTree.py", line 656, in parse
  File "xml\etree\SimpleXMLTreeBuilder.py", line 84, in feed
  File "xmllib.py", line 172, in feed
  File "xmllib.py", line 268, in goahead
  File "xmllib.py", line 795, in syntax_error
xmllib.Error: Syntax error at line 2: illegal character in content
```

**Comment by sanzoghenzo** [comment]
I solved this specific problem by adding an xmllib.Error catcher to warn the user to switch the engine.

It would be wonderful if such a check could be performed directly by pyrevit, so that if the (min/max) required engine version declared in the yaml/script does not match the current engine, a warning is displayed, or the button is disabled.
