### ISSUE TITLE
Problems with Cpython scripts, reload doesn't help, but restarting revit does

### ISSUE THREAD

**Issue by dagz214** [eirannejad/pyRevit#917]
**Describe the bug**
Hi,
I'm working on an extension, and due to the extensive use of strings in RTL languages i'm using Cpython (unicode is better supported in python 3).
A problem  I came across is that changing one of the modules that script.py is relied upon. Running script.py results in an error like the one on the attached screenshot.
If I reload pyrevit, it doesn't seem to help, but restarting revit solves the problem.

**To Reproduce**
1. Create a script in cpython that uses a module (the module loads a csv file to a class, if relevant)
2. During a session update the modules script
3. try to run the script

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/58767064/84118700-052fcd80-aa3c-11ea-95ba-d19c65302981.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version 4.7.6
 - pyRevit Environment: 
```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.6" | Path: "C:\Users\dan56\AppData\Roaming\pyRevit-Master"
==> Attachments
Unnamed-39C13CF | Product: "2021 First Customer Ship" | Engine: 277 | Path: "C:\Users\dan56\source\repos\pyRevit" | Manifest: "C:\Users\dan56\AppData\Roaming\Autodesk\Revit\Addins\2021\pyRevitDev.addin"
master | Product: "2020 First Customer Ship" | Engine: 277 | Path: "C:\Users\dan56\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\dan56\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
==> Installed Extensions
MyFirstExtension | Type: Unknown | Repo: "" | Installed: "D:\Green_Extensions\MyFirstExtension.extension"
pyApex | Type: UIExtension | Repo: "https://github.com/apex-project/pyApex.git" | Installed: "D:\Green_Extensions\pyApex.extension"
pyGreen | Type: Unknown | Repo: "" | Installed: "C:\Users\dan56\source\repos\pyGreen\pyGreen.extension"
PyRevitMEP | Type: UIExtension | Repo: "https://github.com/CyrilWaechter/pyRevitMEP.git" | Installed: "D:\Green_Extensions\PyRevitMEP.extension"
PyRevitPlus | Type: UIExtension | Repo: "https://github.com/gtalarico/pyrevitplus.git" | Installed: "D:\Green_Extensions\PyRevitPlus.extension"
Tags | Type: UIExtension | Repo: "" | Installed: "C:\Users\dan56\source\repos\pyGreen\Tags.extension"
Testing | Type: Unknown | Repo: "" | Installed: "C:\Users\dan56\source\repos\pyGreen\Testing.extension"
trdb | Type: Unknown | Repo: "" | Installed: "C:\Users\dan56\source\repos\pyGreen\trdb.extension"
==> Default Extension Search Path
C:\Users\dan56\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
D:\Green_Extensions
C:\Users\dan56\source\repos\pyGreen
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021"
2020 First Customer Ship | Version: 20.0.0.377 | Build: 20190327_2315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
==> Running Revit Instances
PID: 30032 | 2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2021"
==> User Environment
Microsoft Windows 10 [Version 10.0.17134]
Executing User: LAPTOP-KTFOGH5Q\dan56
Active User: LAPTOP-KTFOGH5Q\dan56
Admin Access: No
%APPDATA%: "C:\Users\dan56\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.7 v4.7.1 v4.7.2 v4.8 v4.X
Installed .Net-Core Target Packs: v2.1.805 v3.1.101
pyRevit CLI 0.25.0.0
```

**Additional context**
Since I'm not an active member, It is a chance to mention I extremely appreciate the wonderful work @eirannejad and the rest of his team are doing.

**Comment by eirannejad** [comment]
Thanks a lot for the kind words:

- Try CTRL+ALT+SHIFT clicking on the tool. This key combination, tells pyRevit to dump the cached engine and start a new one. See if that resolves the issue
- CPython engine in Revit is very experimental at this point. I'd advise staying away from it as much as you can because of the bugs and limitations. There are workflows to make unicode work better in IronPython. I might be able to help if you can share examples where a unicode functionality is not available in IronPython

**Comment by dagz214** [comment]
Hi, thanks for the reply.
Using the CTRL+ALT+SHIFT click didn't seem to help. 
Reverting back to iron python., I found on some pre written classes that makes working with unicode a bit simpler.
