### ISSUE TITLE
Install custom extension from zip-file

### ISSUE THREAD

**Issue by kollyboi** [eirannejad/pyRevit#920]
I wanted to install pyRevit plus my custom extension from a zip file on the server. For this I want to create a bat-file which everyone in the company can run to install this combo by running one file. I do have my custom extension on github, but I don't want users to know the password on my site by reading the bat-file. The pyRevit-CLI tool has the option --image when cloning pyRevit, but not while adding an extension. What I want is something like this:
```
pyrevit detach --all
pyrevit clones forget --all
pyrevit clones delete --all --clearconfigs
pyrevit clone master  --dest="C:\Programdata\pyRevit"
pyrevit extend ui MultiTool --image="\\server\O617\617033\MultiTool-master.zip" --dest="C:\ProgramData\pyRevit\Extensions"
pyrevit configs logs verbose
pyrevit configs checkupdates enable
pyrevit configs autoupdate enable
pyrevit configs rocketmode enable
pyrevit configs filelogging disable
pyrevit configs loadbeta disable
pyrevit configs usercanupdate yes
pyrevit configs usercanextend yes
pyrevit configs usercanconfig yes
pyrevit configs colordocs enable
pyrevit attach master latest --installed --allusers
```
Is this possible? Am I missing something?

**Comment by eirannejad** [comment]
You are absolutely right. Partly because you don't really need a special command to install an extension as a zip, although I can implement this into the pyrevit CLI

[Just copy and extract the zip file](https://superuser.com/questions/1314420/how-to-unzip-a-file-using-the-cmd) and then use the command below to add the parent directory to extension search paths. Make sure the extension directory follows the `name.extension` format

`pyrevit extensions paths add <extensions_path>`

**Comment by MulticonsultBergenVVS** [comment]
Thank you for your reply.
I was hoping, by implementing the `extend ui` command, the update function would look for the zip-file and check the version. This way, I can just download the github-zip to our server when I have updated my master and users could update via pyRevit.
Does that make sense?

**Comment by eirannejad** [comment]
Notes for later:
- [ ] Depends on the future rework of the extension and update api
- [ ] Update system should be able to detect the source of an extension (as zip) and re-download and update

**Comment by jmcouffin** [comment]
**Closing**
Issue older than a year.
Thanks for pointing it out.
If you feel it is still relevant, feel free to reopen the issue
