### ISSUE TITLE
pyRevit 4.6.24 does not load in Revit 2018

### ISSUE THREAD

**Issue by SihaoC** [eirannejad/pyRevit#926]
**Describe the bug**
Replace these lines with your description. Be as specific as possible and list steps to reproduce the issue. If you have any suggestions for the solution please list that as well.

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

`pyrevit attach master 277 --installed`

hi, followed the command, but it shows errors as :
"this is not an internal or external command, nor bat or exe..." failed. 

Could you help me? I have been struggled for hours today. 

Thanks,
S

**Comment by SihaoC** [comment]
i also downloaded the source zip file, i couldnt find "If addin file is missing. You can try to launch pyRevit\release\install_addin.bat in your pyRevit installation folder." in the folder.. 
Please help.

**Comment by SihaoC** [comment]
at the beginning, i went with the newest release, it doesn't work, i immigrated to this older version looked like working for other users of revit 2018... however, not for me

**Comment by SihaoC** [comment]
i ran pyrevit env, it gives (System.NullReferenceException) error

**Comment by eirannejad** [comment]
v4.6 is old and not supported anymore. Please use the latest pyRevit https://github.com/eirannejad/pyRevit/releases/tag/v4.7.6
