### ISSUE TITLE
Typo in one of the `Select` scripts

### ISSUE THREAD

**Issue by zahmadsaleem** [eirannejad/pyRevit#928]
**Describe the bug**
https://github.com/eirannejad/pyRevit/blob/c068953a0fdd5489561b3f74e5d9290de3fdd5db/extensions/pyRevitTools.extension/pyRevit.tab/Selection.panel/select.stack/Select.pulldown/Select%20Similar%20Elements%20In%20Active%20View.pushbutton/script.py#L12

throws this error
`unexpected keyword argument 'exit_script'`

**To Reproduce**
use this tool : **Selection Panel::Select Pulldown::Select Similar Elements In Active View**

----
I believe `exit_script` should be `exitscript` based on this
https://github.com/eirannejad/pyRevit/blob/c068953a0fdd5489561b3f74e5d9290de3fdd5db/pyrevitlib/pyrevit/forms/__init__.py#L2719

**Comment by eirannejad** [comment]
Fixed and will be published in next release. Thank you!
