### ISSUE TITLE
Exception when implementing logger

### ISSUE THREAD

**Issue by Dre-Tas** [eirannejad/pyRevit#933]
We're trying to implement a logger in one of our tools that is hosted by pyRevit but we're having some trouble.
We tried with both _log4net_ and _serilog_ (which I believe both use Reflection to gather info on the environment) and with both we get the error: `Exception has been thrown by the target of an invocation`.
This is the error message I get if I put the definition of the logger in the entry point of my tool

![image](https://user-images.githubusercontent.com/36023527/86568034-98164600-bfaf-11ea-882e-bd598e678caf.png)

As you can see from the screengrab, it is the pyRevitLoader to catch the exception.
I also tried to move the code that creates the logger somewhere else (not the entry point) to see if I was getting the error, but in that case I get the UI of my tool correctly but then it freezes and does nothing, not even throwing the error.

Here is the code I use to create the logger (straight from Serilog's docs):
```
var log = new LoggerConfiguration()
    .WriteTo.File(@"C:\temp\log.txt")
    .CreateLogger();
```

PS I'm very sure it's that bit of code to throw the error as if I remove it all works fine

----------------------------
 - OS: Windows 10
 - pyRevit Version: 4.7.6

**Comment by eirannejad** [comment]
I haven't tested pyRevit with other python loggers but pyRevit provides a logger for all the scripts:
```
from pyrevit import script

logger = script.get_logger()
```

This is the python builtin [logging](https://docs.python.org/2.7/library/logging.html) functionality being used in pyRevit. For quickly writing messages to a file, use:

```
logger.dev_log("some message")
```

This will create a log file on the user desktop with the command name and writes the message into it. You can also setup a file handler and add to the logger.

**Comment by Dre-Tas** [comment]
Serilog (https://github.com/serilog/serilog) and log4net are actually loggers for the .NET framework and we're using it for logging a pretty complex C# tool.

Did you ever come across a similar error?

**Comment by Dre-Tas** [comment]
UPDATE: Another unintelligible piece of the puzzle has been added to the mystery 😄 
I found out that if I first run my tool via Revit's External Tools (Add-Ins > External Tools > Add-In Manager) it will work correctly without any issues and I can then run the same tool from pyRevit too. The same tool that wasn't running from pyRevit directly.

I'm not sure if it's easy to understand, so let me try to recap what I tried: try to run my tool from pyRevit and get the error message posted in my original message. Then try to run my tool (same dll in the same location as for pyRevit) from Revit's External Tools / Add-In Manager: runs correctly. Now try again to run the tool from pyRevit: now runs correctly.
Every time that I restart Revit I have to do the same workaround as above to get pyRevit to run my tool.

I'm afraid that when I deploy this tool to other people they'll have the same issue and I can't tell them to do that workaround every time.

@eirannejad can you think why this would be happening?

Cheers!

**Comment by zahmadsaleem** [comment]
> Serilog (https://github.com/serilog/serilog) and log4net are actually loggers for the .NET framework and we're using it for logging a pretty complex C# tool.
> 
> Did you ever come across a similar error?

Since its a c# tool, with slight modification you could try debugging it natively as an external command using visual studio debugger. Cannot really tell if the error is because of anything related to pyrevit.. since it breaks right during invocation.

**Comment by Dre-Tas** [comment]
Thanks @zahmadsaleem for your reply!

As I was saying in my message above, if I run it "natively" in Revit (add-in manager) it works without any issues. So if I try to debug it through VS nothing happens (the program doesn't break).

I'm thinking that the problem is with pyRevit when it tries to invoke Serilog's dll. It loads correctly a bunch of other external dlls so I'm wondering why it breaks with Serilog. Maybe it has to do with Reflection?

Did anyone have the same problem with any external dll?

**Comment by sanchez** [comment]
It is quite possible that when you are running your tool natively the dll dependencies are being added to the Revit runtime and therefore after you run native the pyrevit side of things work. Because the pyrevit tool can just scan for the already loaded dependencies and not try and load them itself

**Comment by jmcouffin** [comment]
**Closing**
Issue older than a year. 
Thanks for pointing it out. 
If you feel it is still relevant, feel free to reopen the issue
