### ISSUE TITLE
i have script exception for session 4 in pyrevit tutorials 

### ISSUE THREAD

**Issue by fahdattar** [eirannejad/pyRevit#935]
Hi Ehsan;
thanks you very much for your useful Videos and i really enjoy the subject and your teaching method.
i'm new in scripting and i know it might be silly issue but i searched more and more but i can't solve,
 here is my script and exception;

```python
from Autodesk.Revit.DB import *


doc = __revit__.ActiveUIDocument.Document
sheet_cl = FilteredElementCollector(doc)
sheet_cl.OfCategory(BuiltInCategory.OST_Sheets) \
		.WhereElementIsNotElementType()\
		.ToElements()
t = Transaction(doc,"Changing the Parameter")
t.Start()
for sheet in sheet_cl:
	pro_par = sheet.LookupParameter('Custom')
    	if pro_par:
			pro_par.Set("Fahd")
t.Commit()

wall_id_cl = FilteredElementCollector(doc)
wall_id_cl.OfCategory(BuiltInCategory.OST_Walls)
wall_id_cl.WhereElementIsNotElementType()
wall_id_cl.ToElementIds()
r = Transaction(doc,"Deleting all walls")
r.Start()
for wall_id in wall_id_cl:
	doc.Delete(wall_id)
r.Commit()
```

and exception is 
![exception]
(https://user-images.githubusercontent.com/67733059/86888805-7928c880-c103-11ea-8bcd-14e5cf2a84f1.PNG)

thnaks in advance

**Comment by eirannejad** [comment]
Are you using the non-modal RevitPythonShell window?

**Comment by fahdattar** [comment]
Actually after several time of searching , i begin to try everything possible so i tired both (non model & interactive
(interactive)
![image](https://user-images.githubusercontent.com/67733059/86988070-133e4e80-c1a0-11ea-913f-db20f826fbd1.png)
(non-model)

![image](https://user-images.githubusercontent.com/67733059/86987923-ce1a1c80-c19f-11ea-9b12-976651ad1321.png)

**Comment by tmsz** [comment]
@fahdattar Try splitting this script into two. The code you wrote was feeding `doc.Delete` with elements not with their Ids.

```python
doc = __revit__.ActiveUIDocument.Document

walls_ids = FilteredElementCollector(doc) \
    .OfCategory(BuiltInCategory.OST_Walls) \
    .WhereElementIsNotElementType() \
    .ToElementIds()

t = Transaction(doc, "Deleting walls")
t.Start()
try:
    doc.Delete(walls_ids)
    t.Commit()
except Exception as e:
    print(e)
    t.RollBack()
```

```python
doc = __revit__.ActiveUIDocument.Document

sheets = FilteredElementCollector(doc) \
    .OfCategory(BuiltInCategory.OST_Sheets) \
    .WhereElementIsNotElementType() \
    .ToElements()

t = Transaction(doc, "Changing parameters")
t.Start()
for sheet in sheets:
    drawn_by_parameter = sheet.LookupParameter('Drawn By')
    if drawn_by_parameter:
        try:
            drawn_by_parameter.Set("Fahd")
        except Exception as e:
            print(e)
t.Commit()
```
