### ISSUE TITLE
Installer fails if PowerShell script execution is restricted by Group Policy

### ISSUE THREAD

**Issue by chputnam** [eirannejad/pyRevit#936]
The pyRevit 4.7.6 installer fails if PowerShell script execution is restricted by Group Policy.

In such an environment, the PowerShell script that is part of the installer fails with an error recorded in the MSI log:

"Property(S): POWERSHELL_EXECUTION_LOG = File C:\Users\cputnam\AppData\Local\Temp\pssF5FE.ps1 cannot be loaded. The file 
C:\Users\cputnam\AppData\Local\Temp\pssF5FE.ps1 is not digitally signed. You cannot run this script on the current 
system. For more information about running scripts and setting execution policy, see about_Execution_Policies at 
https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess"

In general, you cannot assume that you can run a PowerShell script on an arbitrary computer, particularly an unsigned script.

Possible resolution:

I don't see anything special about the script that the installer runs - it just invokes pyrevit several times and creates .pyrevitargs with static content. There is no reason you couldn't do the same thing with a series of custom actions that directly invoke pyrevit.

**Comment by chputnam** [comment]
To clarify, the installer appears to complete successfully because it throws away the above-noted error and continues as script execution were successful.

**Comment by eirannejad** [comment]
Great tip! Installer was setup a long time ago and a powershell script seemed easier at the time. I check the "Launch File" custom action and updated the installer to use this custom action type instead.
