### ISSUE TITLE
ERROR [patmaker] Error creating pattern element. | 'FilledRegionType' object has no attribute 'FillPatternId'

### ISSUE THREAD

**Issue by DavePlumb** [eirannejad/pyRevit#939]
Using version 4.7.4
**To Reproduce**
I selected the red lines in the attached image.
Then I ran the Make Pattern tool & selected the lower left and upper right corners of the "box" & got the error message in the Title and shown in the other attached image
![pyRevit Pattern](https://user-images.githubusercontent.com/18071127/87593271-d0eda380-c6b0-11ea-98e4-d3443b036561.PNG)
![PyRevit Error](https://user-images.githubusercontent.com/18071127/87593272-d1863a00-c6b0-11ea-8e28-fd8a335f5f08.PNG)

How to correct?

**Comment by eirannejad** [comment]
Fixed and will be published with next release https://github.com/eirannejad/pyRevit/issues/871

**Comment by brzesiak** [comment]
Hi, i have still the same problem on 4.7.6. version

**Comment by brzesiak** [comment]
Also when im making small, very easy pattern it comes with warning below:
![image](https://user-images.githubusercontent.com/64070954/90767275-36a30000-e2ed-11ea-83c8-7af0bc62cd1e.png)
And comes down with lots of lines, and nothing happened next.
![image](https://user-images.githubusercontent.com/64070954/90767319-4ae6fd00-e2ed-11ea-8778-a10313fc39ba.png)
and there is no pattern at all

**Comment by brzesiak** [comment]
https://we.tl/t-m3EOTSoEBl thats my pattern

**Comment by eirannejad** [comment]
Odd. I opened the model in Revit 2020 and created the pattern with no issues both for detail and model:

![Screen Shot 2020-08-20 at 08 37 12](https://user-images.githubusercontent.com/8197916/90793349-7b647200-e2c0-11ea-87bc-b8949659df48.png)

[default_pattern.rvt.zip](https://github.com/eirannejad/pyRevit/files/5104024/default_pattern.rvt.zip)

**Comment by brzesiak** [comment]
Big thanks for this file
I dont know why it doesnt work still

**Comment by brzesiak** [comment]
With 4.8.2 beta version works perfectly!!!
