### ISSUE TITLE
PyRevit Installation Issues

### ISSUE THREAD

**Issue by ipa0** [eirannejad/pyRevit#940]
We've installed Pyrevit on the image to be deployed across our machines. However, we get the following error message when opening Revit.

<img width="1440" alt="Screenshot 2020-07-16 at 14 37 23" src="https://user-images.githubusercontent.com/5084632/87680535-74a08780-c775-11ea-9a7e-55252ae6e5f1.png">
<img width="1440" alt="Screenshot 2020-07-16 at 14 37 28" src="https://user-images.githubusercontent.com/5084632/87680546-7702e180-c775-11ea-9cde-5b7401c79716.png">

We have Windows 10 machines that are Domain joined.
 
We have User Account Control set on the default level which doesn’t allow users to install applications. I have tested disabling this and it doesn’t help with running the pyRevit plugin, plus we would not want to disable it anyway.
 
In our testing we have noted that the pyRevit plugin loads when the user is a member of either the ‘Power users’ or ‘Administrators’ groups. For security reasons we do not want them to be a member of those groups.
 
We would need to know what is pyRevit trying to do when it gets activated when Revit is open. Is it trying to load certain files, or copy or create files? Any pointers may help.

pyRevit Version: 4.7.60
pyRevit Environment: as per screenshots

**Comment by ipa0** [comment]
pyrevit env:
<img width="979" alt="Screenshot 2020-07-16 at 14 44 42" src="https://user-images.githubusercontent.com/5084632/87681780-f349f480-c776-11ea-81f3-7005de975867.png">

**Comment by ipa0** [comment]
+:
On our set up Users have full control of the following folders

C:\Autodesk
C:\ProgramData\Autodesk
C:\Program Files (x86)\Autodesk
C:\Program Files\Autodesk
C:\Program Files\Common Files\Autodesk Shared
C:\Program Files (x86)\Common Files\Autodesk Shared
C:\ProgramData\pyRevit

are there others that pyrevit needs to get to/ write to?
​

**Comment by eirannejad** [comment]
This seems to be unrelated to pyRevit itself and seems like a [user access issue](https://validedge.com/required-privilege-not-held-client/). 

Yes. Please make sure that these folders are also accessible
```
%TEMP%
%APPDATA%\pyRevit
%USERPROFILE%\desktop
```
