### ISSUE TITLE
Automatic detection of help files

### ISSUE THREAD

**Issue by coditect** [eirannejad/pyRevit#941]
The project I'm working on stores the help file for each command in its bundle folder.  I'm currently using the `__selfinit__` function to look up the help file so I don't have to hard-code its path into `bundle.yaml`:

```python
def __selfinit__(component, button, __rvt__):
    help_paths = glob.glob(os.path.join(component.directory, "*help.*"))
    if len(help_paths) > 0:
        button.set_contexthelp(help_paths[0])
    return True
```

This technique only works for smart buttons implemented in Python, though.  It would be great if pyRevit could look for a help file in any type of command bundle (just like it does for script and content files) and use its path as the command's contextual help URL. 

A less excitig alternative would be to make the bundle path available as a template variable to use in `bundle.yaml` so one could reference local files like this:
```yaml
help_url: {{directory}}\help.html
```

**Comment by eirannejad** [comment]
Fixed and will be published with next release
pyRevit bundles now support `*help.*` files. When hitting F1 on the keyboard while hovering over the button, Revit will ask the OS to open the help file with the default application e.g. default browser for `*help.html` files

**Comment by coditect** [comment]
Thanks, Ehsan!
