### ISSUE TITLE
Print sheets features

### ISSUE THREAD

**Issue by RichardPinka** [eirannejad/pyRevit#943]
Hello, 
i am trying to use Print sheets feature, 
first thing i encountered (and do not know whether is bug or missing feature ) is, that when you open print sheets window, 
you see "Sheet index (Schedule)" list of sheets which is not able to change it to any of other created groups of sheets (sheet lists) in model. I would expect that, Yes, You could select the proper list of sheets you want to print out ? 
(as picture below, "Sheet index (Schedule)"  you can select from the drop down menu only "sheet list" , nothing else) 
![image](https://user-images.githubusercontent.com/8267708/87873908-aa3baf80-c9c5-11ea-8473-d2f5080b5626.png)

afterwards, also i would like to see that the printer automatically defines  height and widht of the sheet because each sheet 
could have its own, different individual dimensions, so I will see how it is working. 
Anyway, I thank You very much for developing such strong tool for revit users. 

EDIT:   Ok, I tested, and it printed whole list of sheets but with the preset sheet dimensions of the first sheet. But Each sheet is different dimensions and thus the prints are useless. 
I do not know cultural habbits within sheet dimension managements with same dimensions per sheet in the list sheet - is this in general normal for architects ? (i am MEP engineer). 

- could be good to tell printer not to ask me each and every time where to store the pdf file and confirm its name (to make something reasonable on desktop while sheets will be printed in background)

**Comment by eirannejad** [comment]
- You can use the <Variable Sheet Size> for printing sheets with various sizes
- Whether PDF printer asks for a filename or not is a feature of the PDF writer and not Revit or pyRevit
- Sheet Index list only lists schedules that are listing sheets and nothing else
