### ISSUE TITLE
PyRevit  Revalue Find and Replace Funcation

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#944]
**Is your feature request related to a problem? Please describe.**
I would like if PyRevit Revalue could be used like Find and Replace in Microsoft Word/Excel. i.e. I would like the PyRevit Revalue to replace spaces in the Revit Family name with a hyphen "-". Refer to screenshot below..

![image](https://user-images.githubusercontent.com/8776947/88061739-d25f1600-cb5f-11ea-86d8-eafbe697637e.png)

Thanking you in advance

Rob

**Comment by eirannejad** [comment]
Fixed and will be published with next release

**Comment by Robbo1234** [comment]
Thanks Ehsan

![image](https://user-images.githubusercontent.com/8776947/89778027-b0c0d100-db04-11ea-94c3-e29f02cedc3e.png)

**Comment by eirannejad** [comment]
@Robbo1234 Of course :)

**Comment by Robbo1234** [comment]
I can't get PyRevit Revalue to remove "spaces" " ." and "/"  from  Revit Sheet names.

![image](https://user-images.githubusercontent.com/8776947/90131420-03e48f00-dd64-11ea-9e09-0645654b1fad.png)

**Comment by eirannejad** [comment]
The find-replacer supports regex. Use `\s` for a single space. [You can play with regex here](https://regexr.com)

**Comment by Robbo1234** [comment]
Thanks Ehsan, but it doesn't replace single spaces with no spaces
similar to MS Excel find and replace functionality.

[image: image.png]

**Comment by Robbo1234** [comment]
Thanks Ehsan, but it doesn't replace single spaces with no spaces
similar to MS Excel find and replace functionality.

![image](https://user-images.githubusercontent.com/8776947/90229496-e967ef80-de0f-11ea-82b6-9368cb8ab47c.png)

**Comment by eirannejad** [comment]
Oh got it

**Comment by eirannejad** [comment]
Hey I don't see any issues here. I typed `\s` in the first box and a single space in the second box and it works

![Screen Shot 2020-09-27 at 11 55 04](https://user-images.githubusercontent.com/8197916/94373155-61386380-00b8-11eb-9df9-b82f9b9d883f.png)

**Comment by eirannejad** [comment]
Fixed and will be published with next release
