### ISSUE TITLE
PyRevit 4.7.6. - Sync Views not working

### ISSUE THREAD

**Issue by BMOLI** [eirannejad/pyRevit#946]
Sync Views isn't working in the latest PyRevit version, tried on multiple PC's and the problem persists - downgrading to 4.7.4 in the meantime.

**To Reproduce;
1. Go to PyRevit Toolbar
2. Click on Sync Views

**Expected behavior:
Sync Views isn't working in the latest PyRevit version, tried on multiple PC's and the problem persists - downgrading to 4.7.4 in the meantime.

**Desktop:
 - OS: WINDOWS 10
 - PyRevit Version 4.7.6.

**Comment by eirannejad** [comment]
Already fixed and will be published soon
https://github.com/eirannejad/pyRevit/issues/897

**Comment by BMOLI** [comment]
Awesome,

Thank you!


Regards,

Brian Oliveira
