### ISSUE TITLE
IUpdater with pyRevitDevHooks.extension

### ISSUE THREAD

**Issue by kente678** [eirannejad/pyRevit#947]
Hi Ehsan,

Thak you very much for your magnifique pyRevit.
I'm trying to use IUpdater with pyRevitDevHooks.extension, 
but  it doesn't work.
Is there any way  to use IUpdater with pyRevitDevHooks.extension?

thnaks in advance

**Comment by eirannejad** [comment]
You don't need hooks to use `IUpdater`. They're actually in conflict with each other. You can use a `startup.py` in your own extension to register you `IUpdater` handler on Revit startup. Revit will call this function on any document change automatically. See https://www.notion.so/pyrevitlabs/Extension-Startup-Script-605ce7b1831d41d88741bc9a9eee42a7

**Comment by kente678** [comment]
Thank you for your reply!
I was so impressed with the ease of HookExtension,
So I was wondering if I could somehow use it with the IUpdater.
I tried IUpdater with startup.py and it worked perfectly!
