### ISSUE TITLE
Additional information to telemetry data

### ISSUE THREAD

**Issue by cesarecaoduro** [eirannejad/pyRevit#948]
Is there a way to include more custom information to existing telemetry events like Document_Opened.
The idea is that we would like to attach for example some Project Information Shared parameter to track additional details about the model itself like ProjectName, ClientName, etc.

Is it already possibile? If yes how?

Thanks!

**Comment by eirannejad** [comment]
Ya of course. Are these shared parameters assigned to the **Project Information** category? That way I can easily query those and send to the telemetry server as well.

**Comment by cesarecaoduro** [comment]
In this specific scenario yes, but it may be interesting to have the opportunity to attach other types of parameters attached to other categories. I think as a starting point the Project information are probably the easiest ones.
In other scenarios we have a "welcome" view where we have other information related to the project or model revision that we would like to store in our audits.

**Comment by eirannejad** [comment]
Okay so for anything more advanced I'd suggest using [pyRevit hooks](https://www.notion.so/pyrevitlabs/Create-Your-First-Hook-0214eee855fc43cead1e6f30f586a04e). You can create scripts that get executed on Revit events (e.g. ViewActivated or DocumentOpened) and you can gather any type of info you want. Hooks provide the ultimate flexibility

**Comment by IMVVVVVIP** [comment]
the APPis very gond

**Comment by IMVVVVVIP** [comment]
the app is very good

**Comment by cesarecaoduro** [comment]
> Okay so for anything more advanced I'd suggest using [pyRevit hooks](https://www.notion.so/pyrevitlabs/Create-Your-First-Hook-0214eee855fc43cead1e6f30f586a04e). You can create scripts that get executed on Revit events (e.g. ViewActivated or DocumentOpened) and you can gather any type of info you want. Hooks provide the ultimate flexibility

Ok, I will have a look into hooks.
