### ISSUE TITLE
pyRevit 4.7.6 not loading in Revit 2019

### ISSUE THREAD

**Issue by jenb1** [eirannejad/pyRevit#949]
Hi,

The installation of pyRevit completed, however pyRevit will not load in Revit 2019. It is working fine in Revit 2020.

If you have installed pyRevit, and the installation completed with no errors but pyRevit doesn't load, please run the command below in terminal. This should fix the issue on your machine, however, please continue filing the issue with instructions below.

Error message is attached

![pyRevit Error](https://user-images.githubusercontent.com/31036325/89003221-8cb20280-d342-11ea-9f4a-e4ccd5903171.png)

 - OS: Windows 10
 - pyRevit Version 4.7.6

**Comment by eirannejad** [comment]
This is very odd. Would you mind running the command below in a terminal:
`pyrevit attach master 277 --installed`

The error says it can not find `find_loaded_asm` function that is used on the line 10 of the `../pyrevit/loader/__init__.py`. However pyRevit 4.7.6 doesn't have any references to this function in that file. Seems like this is an older pyRevit version??

**Comment by eirannejad** [comment]
Closing this until more info is available
