### ISSUE TITLE
Where is the local cpython version installed that is shipped with pyrevit?

### ISSUE THREAD

**Issue by tillbaum** [eirannejad/pyRevit#950]
Hi Ehsan, 

can you tell me the path to the local cpython version, that is shipped with pyrevit? 

I want to pip install pywin32-package and others to the cpythonversion.
I looked in the ...appdata/pyrevit-master dir, but could not find it. 
If its not too much trouble. 
Thank you.

**Comment by eirannejad** [comment]
pyRevit contains the "Embedded" distribution of python under `bin/engines/368` and `bin/engines/372` inside the pyRevit install path. There is no `python.exe` in this.

However, install the 3.6.8 or 3.7.2 python (64bin) on your machine, pip install whatever package you need and make sure the `PYTHONPATH` environment variable is set to the correct location of `site_packages` that pip installs to. This is all Cpython conventions no specifically pyRevit.

When running a cpython script in pyRevit (e.g. with 3.7.2 engine), the Cpython runtime will find the installed packages in the  `PYTHONPATH` directory.

take a look at the alert notes here: https://www.notion.so/pyrevitlabs/Create-Your-First-CPython-Command-b8a7718c554645d1a18454c0b363e3c9

**Comment by tillbaum** [comment]
Thank Ehsan, 
one other question, I ve seen hat the pywin32 package is automatically included in the cpython 3.7.5 version.
Is it possible to ship pyrevit with this version? Maybe in a future release?

**Comment by eirannejad** [comment]
Yup will definitely update to the latest cpython versions 3.6 - 3.8
