### ISSUE TITLE
"Remove Empty Tags" Error

### ISSUE THREAD

**Issue by bls05** [eirannejad/pyRevit#955]
**To Reproduce**
1. Go to '**Views**'
2. Click on '**Remove Empty Tags**'
3. See error below

> ERROR: [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:An internal error has occurred.
> 
> 
> IronPython Traceback:
> Traceback (most recent call last):
>  File "C:\Users\bschumacher\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\views.stack3\Views.pulldown\Remove Empty Tags.pushbutton\script.py", line 29, in 
> Exception: An internal error has occurred.
> 
> 
> Script Executor Traceback:
> Autodesk.Revit.Exceptions.InternalException: An internal error has occurred.
>  at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
>  at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>  at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
>  at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
>  at PyRevitBaseClasses.ScriptExecutor.ExecuteScript(PyRevitCommandRuntime& pyrvtCmd)
> 

**Expected behavior**
It should remove tags with no label value from the open view

**Screenshots**
![2020-08-05_15-38-03](https://user-images.githubusercontent.com/60901429/89456338-ba77bc80-d731-11ea-96ef-d2d57d21d201.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - pyRevit Version 4.6.24:277:2017 
- pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

C:\Users\bschumacher>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.6.24" | Path: "C:\Users\bschumacher\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2017.2.5 Security Fix" | Engine: 277 | Path: "C:\Users\bschumacher\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\bschumacher\AppData\Roaming\Autodesk\Revit\Addins\2017\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\bschumacher\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2017.2.5 Security Fix | Version: 17.0.1169.0 | Build: 20190508_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> Running Revit Instances
PID: 20564 | Autodesk Revit 2017.2.5 Security Fix | Version: 17.0.1169.0 | Build: 20190508_0315(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> User Environment
Microsoft Windows 10 [Version 10.0.17134]
Executing User: MAXUSGROUP\bschumacher
Active User: MAXUSGROUP\bschumacher
Adming Access: No
%APPDATA%: "C:\Users\bschumacher\AppData\Roaming"
Latest Installed .Net Framework: 4.7.2
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.13.0.0

C:\Users\bschumacher>

**Comment by eirannejad** [comment]
This is an internal Revit error and not a pyRevit issue. You are also using an old version of pyRevit
