### ISSUE TITLE
Make PY Revit the first Ribbon Tab

### ISSUE THREAD

**Issue by MarkAckerley** [eirannejad/pyRevit#957]
Apologies, this is pretty unlikely to be possible...

Wouldn't it be great if PyRevit was the first thing you clicked on?

We can cntrl click drag the order of tabs in Revit, but that order isn't stored for future use.

Given the access Xceed has given to View Tabs, I wonder if it is possible...?  But I can't find enough under the hood to see...  

It doesn't appear to be possible with the regular API or Autodesk Windows dlls.

Thanks for all the great work.

Mark

**Comment by eirannejad** [comment]
It is possible using the Xceed hack but it's generally a bad practice to mess with the layout of the host app.
