### ISSUE TITLE
Failure to load

### ISSUE THREAD

**Issue by TonyBird1981** [eirannejad/pyRevit#961]
On opening pyrevit fails to load with the following error 
![image](https://user-images.githubusercontent.com/44781004/89784692-fedbd180-db10-11ea-9eb1-adffdba73c11.png)
digging further in you can see the following error 
![pyreviterror](https://user-images.githubusercontent.com/44781004/89784727-11eea180-db11-11ea-8c46-a23e7f4fbc46.png)
Which appears to be similar to an old issue regarding a different dll (https://github.com/eirannejad/pyRevit/issues/323)

error occurs in both Revit 2019 and Revit 2021, currently I don't have any other versions installed but I can install and test although I see no reason that there would be a different result.
OS windows 10 Ver 1909

Any help would be appreciated 

Tony

**Comment by eirannejad** [comment]
Would you mind checking if `Nett.dll` is inside the `bin/` directory on the pyRevit installation?

**Comment by TonyBird1981** [comment]
Hi Ehsan 

It is indeed in the bin folder

Regards

Tony

42-43 Gloucester Crescent
London
NW1 7PE
T +44 (0) 20 7267 5161
maxfordham.com
@maxfordhamLLP

Max Fordham LLP is a Limited Liability Partnership. Registered in England 
and Wales Number OC300026
Registered office 42-43 Gloucester Crescent, London, NW1 7PE

We're Net Zero Carbon!
We're proud to be the first consultancy to be verified as Net Zero Carbon, 
in accordance with the UKGBC Net Zero Carbon Building Framework. But it's 
not enough! 
To find out why, click here.

Record Win at the CIBSE Building Performance Awards 2020
The Engine Shed - 'Building Performance Champion' | Agar Grove Estate - 
'Residential Project of the Year' | The Engine Shed - 'Public Use Project 
of the Year'
Read more about our recent CIBSE Award wins here.

**Comment by eirannejad** [comment]
Okay this seems to be a dll conflict with other addons installed on Revit. Would you mind taking a look at the [steps described here ](https://www.rhino3d.com/inside/revit/beta/reference/toubleshooting#search-for-conflicting-plugins)to isolate the conflicting addon?

**Comment by TonyBird1981** [comment]
Hi So I've downloaded the tool and disabled all addons except the pyRevit 
loader and I get the same error message 

Regards

Tony

42-43 Gloucester Crescent
London
NW1 7PE
T +44 (0) 20 7267 5161
maxfordham.com
@maxfordhamLLP

Max Fordham LLP is a Limited Liability Partnership. Registered in England 
and Wales Number OC300026
Registered office 42-43 Gloucester Crescent, London, NW1 7PE

We're Net Zero Carbon!
We're proud to be the first consultancy to be verified as Net Zero Carbon, 
in accordance with the UKGBC Net Zero Carbon Building Framework. But it's 
not enough! 
To find out why, click here.

Record Win at the CIBSE Building Performance Awards 2020
The Engine Shed - 'Building Performance Champion' | Agar Grove Estate - 
'Residential Project of the Year' | The Engine Shed - 'Public Use Project 
of the Year'
Read more about our recent CIBSE Award wins here.

**Comment by eirannejad** [comment]
v4.8.5 is published. Would you mind testing this? If it didn't work try attaching pyRevit using the custom IronPython engine `pyrevit attach master default --installed`
