### ISSUE TITLE
CLI pyrevit run model loading errors

### ISSUE THREAD

**Issue by yschindel** [eirannejad/pyRevit#963]
Hi,

first of all thank you very much for developing pyRevit!

I am developing an automated evaluation of all our offices´s rvt models for which I'm using the "pyrevit run" function to pass all models to the python script that is doing the checkup.

Now have encountered an error that stops the script:

> ==> Execution Log
> IronPython Traceback:
> Traceback (most recent call last):
>   File "F:\910_EDV\910_REVIT\Model Health Monitor\ModelHealthAutoRun.py", line 72, in <module>
> AttributeError: 'NoneType' object has no attribute 'Document'

This is the code from line 72;

```
for model in __models__:
        uidoc = HOST_APP.uiapp.OpenAndActivateDocument(model)
        doc = uidoc.Document
```

From the output files the script is generating I can tell, that it is succesfully opening some models but eventually fails.
As far as I understand the error, at some point there is no model beeing passed to the script.
My observations so far:
- Depending on how many model paths I que up in the .txt the models that fail to load change.
- The first model in the .txt file always loads.
- Providing the same set of models, the failing models stay the same, no matter the order.
- Providing only typically failing models all but the last one load.
- The failing models are not the largest files nor are they the smallest.

This is the journal file:

> ' pyrevitrunner generated journal
> ' 0:< 'C 2020-08-10T07:14:06Z;
> Dim Jrn
> Set Jrn = CrsJournalScript
> Jrn.Directive "DebugMode", "PerformAutomaticActionInErrorDialog", 1
> Jrn.Directive "DebugMode", "PermissiveJournal", 1
> Jrn.RibbonEvent "TabActivated:Add-Ins"
> Jrn.RibbonEvent "Execute external command:CustomCtrl_%CustomCtrl_%Add-Ins%pyRevitRunner%PyRevitRunnerCommand:PyRevitRunner.PyRevitRunnerCommand"
> Jrn.Data "APIStringStringMapJournalData"  _
>     , 4 _
>     , "ScriptSource" , "F:\910_EDV\910_REVIT\Model Health Monitor\ModelHealthAutoRun.py" _
>     , "SearchPaths" , "" _
>     , "Models" , "F:/476_FREIHAM_12/20_CAD/00_AKTUELL/01_ZENTRALMODELL/476_ZENTRALMODELL_MK2(2).rvt;F:/477_FREIHAM_34/20_CAD/00_AKTUELL/01_ZENTRALMODELL/477_ZENTRALMODELL_MK2(3).rvt;F:/477_FREIHAM_34/20_CAD/00_AKTUELL/01_ZENTRALMODELL/477_ZENTRALMODELL_MK2(4).rvt;F:/478_AM_BONNESHOF/20_CAD/00_AKTUELL/01_ZENTRALMODELL/478_BONNESHOF.rvt" _
>     , "LogFile" , "C:\Users\YSCHIN~1\AppData\Local\Temp\67454157-dead-4bd0-9b86-b344af3af69e\PyRevitRunner_67454157-dead-4bd0-9b86-b344af3af69e.log"
> Jrn.Command "SystemMenu" , "Quit the application; prompts to save projects , ID_APP_EXIT"
> Jrn.Data "TaskDialogResult" , "Do you want to save changes to Untitled?", "No", "IDNO"

This is the LogFile:

> 
> IronPython Traceback:
> Traceback (most recent call last):
>   File "F:\910_EDV\910_REVIT\Model Health Monitor\ModelHealthAutoRun.py", line 72, in <module>
> AttributeError: 'NoneType' object has no attribute 'Document'
> 
> 
> Script Executor Traceback:
> System.MissingMemberException: 'NoneType' object has no attribute 'Document'
>    bei Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
>    bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>    bei Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
>    bei System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
>    bei IronPython.Runtime.Binding.PythonGetMemberBinder.FastPropertyGet`1.GetProperty(CallSite site, TSelfType target, CodeContext context)
>    bei Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
>    bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>    bei Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
>    bei IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
>    bei Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
>    bei PyRevitLoader.ScriptExecutor.ExecuteScript(String sourcePath, IEnumerable`1 sysPaths, String logFilePath, IDictionary`2 variables)

My troubleshooting so far:

I changed the file loading within my script to this:

```
for model in __models__:
        uidoc = HOST_APP.app.OpenDocumentFile(model)
        doc = uidoc.Document
```

From what I can tell by the API Docs the return of both OpenDocumentFile and OpenAndActivateDocument method should be the same.
With this approach HOST_APP.app.OpenDocumentFile(model) works fine for every model, 
but with OpenDocumentFile uidoc.Document fails every time.

This makes me think, that the pyrevit run command is working fine but my script is somehow blocking some of the next files from beeing loaded.

So I gues my questions are:
- Is it a good idea to try a different opening method and where can i find information about the different retuns?
- what could be blocking the models from beeing loaded?
- since I am quite new to python and the revit API I could easily be missing something obvious.

Thank you for your time and help!

All the best,
Yskert

**Comment by yschindel** [comment]
Sorry, classic fail on my side:

```
for model in __models__:
        doc = HOST_APP.app.OpenDocumentFile(model)
```

This is all it takes.
As far as I understand the revit API Docs are wrong regarding the return of OpenAndActivateDocument.

But maybe this is still of value for the pyrevit run documentation.

**Comment by eirannejad** [comment]
They're not wrong. Remember your script is being run by the pyRevitRunner by using the Revit Journal Playback mechanism. Aome of the Revit UI API are not accessible during this mode.
