### ISSUE TITLE
Loading Information from Excel for Multiple References/Queries

### ISSUE THREAD

**Issue by kuldeep3618x** [eirannejad/pyRevit#965]
A method where I can store data from Excel for all  calculations/computations.

Currently I am selecting excel, everytime I need to perform an analysis.

I am an attaching an image for your reference.

![Uploading reference.jpg…]()

**Comment by eirannejad** [comment]
I need more info. Please explain if this is an issue or request for a new feature. Attachment is not properly attached either

**Comment by kuldeep3618x** [comment]
![reference](https://user-images.githubusercontent.com/59068105/89921960-089e2b80-dc1c-11ea-8ef8-5759ff4c6aab.jpg)

**Comment by kuldeep3618x** [comment]
Please have a look

**Comment by kuldeep3618x** [comment]
Its a request,,,not an issue,I want to understand the way forward, for storing Excel Data for checking all these parameters,

**Comment by kuldeep3618x** [comment]
Thank you Sir, once again for your quick response.
