### ISSUE TITLE
pyRevit Keynote manager keeps loading forever and then times out..

### ISSUE THREAD

**Issue by jashwanthl** [eirannejad/pyRevit#967]
**Describe the bug**
For many users in our firm the pyRevit keynote manager when clicked starts a never ending loading screen and then eventually timesout or had to be forced stop(when users waited over 30 minutes). All the other tools still work for these users and some of them have new high performance laptops... The tool does work perfectly for some of us but we've spent hours trying to isolate the differences/problems between the computers that the keynote manager tool works and with the ones that the tool doesn't and came up with nothing. We also tried to see if uninstalling all the other addins would work but it still went into an unending load loop for these users.
We also tried installing the newest release (the pyRevit 4.8 *thank you) but it did not resolve this issue.

**To Reproduce**
Click on the keynote manager tool on the pyrevit ribbon.

**Expected behavior**
The keynote manager UI to pop up. But it doesn't even show the initial alert/form to convert the keynote text file to a pyRevit one.

**Screenshots**
It's just a loading screen

**Desktop (please complete the following information):**
 - OS: Windows
 - pyRevit Version 4.7.6 and 4.8
 - pyRevit Environment: 
 ``` ==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.0" | Path: "C:\Users\vineyae\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2021 First Customer Ship" | Engine: 277 | Path: "C:\Users\vineyae\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\vineyae\AppData\Roaming\Autodesk\Revit\Addins\2021\pyRevit.addin"
master | Product: "2020.2.2" | Engine: 277 | Path: "C:\Users\vineyae\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\vineyae\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
master | Product: "2019.2.2 Hotfix" | Engine: 277 | Path: "C:\Users\vineyae\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\vineyae\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
master | Product: "2018.3.3 Security Fix" | Engine: 277 | Path: "C:\Users\vineyae\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\vineyae\AppData\Roaming\Autodesk\Revit\Addins\2018\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\vineyae\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021"
2020.2.2 | Version: 20.2.20.31 | Build: 20200426_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018"
==> Running Revit Instances
PID: 12608 | 2020.2.2 | Version: 20.2.20.31 | Build: 20200426_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2020"
==> User Environment
Microsoft Windows 10 [Version 10.0.19041]
Executing User: NASH\vineyae
Active User: NASH\vineyae
Admin Access: No
%APPDATA%: "C:\Users\vineyae\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.0.0




**Additional context**
We greatly appreciate all the tools that you have open sourced and I convinced entire teams to use the pyRevit keynote manager. Everybody loved the tool(from the youtube video) but can't figure out why it doesn't work on their machines...
Any help is greatly appreciated

**Comment by jashwanthl** [comment]
An Update from our tests :
When Revit 2020 was updated to version 20.2.20, it started throwing the timeout error. The keynote manager was working for these users before updating and it still works in other versions of Revit.
![BF5E8F6](https://user-images.githubusercontent.com/65972331/90058018-2ff20880-dcaf-11ea-8a9a-51052313bdbc.PNG)

**Comment by eirannejad** [comment]
@jashwanthl Keynote manager creates a lock file (in the same path as the keynote text file with the same name and `.lock` extension) to tell other Revit instances that it is writing data to the keynote file. This way multiple users won't overwrite each others changes. When the `*.lock` file exists, the keynote manager will wait for 10 seconds to see if the lock goes away or not. It will return the "Wait for unlock timeout" error if it does not.

With this background, I have a few questions:
- Is the keynote file shared over the network? (shared network drive) In that case is there anything different between the working and none-working machines in the way the drives are mapped?
- Is there a sticky `.lock` file stuck in the folder? One possibility might be if keynote manager crashed, it might leave a hanging `.lock` file

**Comment by jashwanthl** [comment]
@eirannejad Thank you for looking into the problem. The answer to your questions:

- Yes the keynote file is shared over the network and the production group has the same permissions to that folder as the admin group. It initially worked for me (as an admin) but then received the timeout error eventually.

- Yes the lock file still exists in the folder...

**Comment by eirannejad** [comment]
@jashwanthl Okay so we figured out the issue is due to sticky `.lock` files. There is either a bug or this happens when pyRevit keynote manager crashes. Do you get any crash reports like that from your users? I'd love to know if the keynote manager crashes so I can fix that issue and hopefully resolve the sticky `.lock` file issue as well

**Comment by eirannejad** [comment]
Okay I'll close this for now then. Feel free to open again with more error reports :)

**Comment by JLee415** [comment]
Hello - We understand that when somebody is editing the notes it "locks" the .txt file on BIM360 and when they are done editing it unlocks the .txt file. But our current issue is when you add a note it is saying "user is editing..." which we cannot seem to clear it out.. 

![image](https://user-images.githubusercontent.com/83681718/117597348-3dcba180-b0fa-11eb-8725-8dfa7f861bed.png)

**Comment by cloghmani3182** [comment]
I am currently encountering the same issue as JLee415.  Did anyone figure out a solution?

**Comment by PAYAM2000** [comment]
This seems to still be an issue. any solution to this? We have been unlocking the text file on BIM360 and deleting the .lock file, but the issue doesn't get resolved. our workaround has been deleting the file and uploading a copy of the keynote file back on BIM360 again, it's a pain and I am hoping for a better solution!

**Comment by kkkhsdjs** [comment]
@eirannejad Hi! We are working on BIM360 with several staff, and we ran into the same problem --> how can we find the original keynotes.txt file? it currently doesn't exist in the BIM folder and also not on my computer.
