### ISSUE TITLE
Rename Sheets - Camelcase and remove spaces

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#970]
**Is your feature request related to a problem? Please describe.**
Some projects that I work on have a BIM requirement to have the Sheet Name to be in Camelcase with no spaces.
p.s. one might also consider adding a Titlecase option.

**Describe the solution you'd like**

Add a extra button (refer to screenshot)

![image](https://user-images.githubusercontent.com/8776947/90130374-45743a80-dd62-11ea-985d-ca1aaffa73e4.png)

**Comment by eirannejad** [comment]
Fixed and will be published with next release
