### ISSUE TITLE
Question regarding color/font size/font style in output window in pyrevit

### ISSUE THREAD

**Issue by kuldeep3618x** [eirannejad/pyRevit#972]
Please help regarding formatting any output printed statement in pyrevit.

Please explain with a simple example, how can we go ahead with formatting 'Hello World' in color/bold  in a certain font style.

**Comment by eirannejad** [comment]
Please see
https://www.notion.so/pyrevitlabs/Effective-Output-43baf34d2ca247ada8e040bcb86613a2

**Comment by kuldeep3618x** [comment]
I was able to create tabular data perfectly.Thanks
