### ISSUE TITLE
Error Loading PyRevit

### ISSUE THREAD

**Issue by dankor1** [eirannejad/pyRevit#974]
I downloaded and tried to install PyRevit onto Revit 2021 and got the following error:
![image](https://user-images.githubusercontent.com/69662263/90211265-91db7b00-de33-11ea-9c08-7d26b8ef3e06.png)

However, PyRevit did load correctly into Revit 2020 though.

**Comment by eirannejad** [comment]
Already resolved. I'll publish the new installer by Monday. It's an API change issue with Revit 2021.0 but it works with 2021.1

**Comment by dankor1** [comment]
Great. Thanks for that.

Warm regards,

*Dan Korman*

Director



9/120 CAMBRIDGE ST COLLINGWOOD VIC 3066

P (+613) 9417 0386          M 0403 332 555

WWW.DANKOR.COM.AU
