### ISSUE TITLE
PyRevit Health Check

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#975]
It would be great if PyRevit could execute a Revit model health check report. 

This Revit model health check report could contain the following suggested model checks.

Revit Warnings Count
Inplace Family Count
Linked Revit Model Count
Linked Dwg Count
Imported Dwg Count
Model File Size
Workset Count
Shared Coordinates
Purgeable Items Count
Details Items Count
Duplicated Room, Door, Window Numbers
etc.....

Thanks

Rob

**Comment by davidvadkerti** [comment]
I have similar tool called [ModelChecker](https://www.youtube.com/watch?v=c7Q3IYmRFlM) in my extension [CustomTools](https://bitbucket.org/davidvadkerti/customtools/src/master/).

If you are interested I could adapt it for public use (since it is custom made for use in our company) and create PR.

**Comment by Robbo1234** [comment]
Thanks, David, that would be brilliant.

**Comment by eirannejad** [comment]
@Robbo1234 Could this be closed now that we have the model check script?

**Comment by Robbo1234** [comment]
Work away, Ehsan and thanks again for everyone's great work.  Rob
