### ISSUE TITLE
PyRevit Isolate missing some Revit items in view 

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#976]
In the latest version of PyRevit 4.8.0.0 I noticed that PyRevit Isolate is not picking up a number of Revit items in the view. 

i.e Walls, Furniture, Plumbing Fixtures Columns, Curtain Walling (Refer to screenshot)

![image](https://user-images.githubusercontent.com/8776947/90260160-08cc4000-de43-11ea-9af2-4df2a91b4b6c.png)

**Comment by eirannejad** [comment]
I added the categories you listed here to the tool (the list is fixed) but the tools needs to be reworked completely to be smart about available categories and tags in a view. I'll switch this to enhancement
