### ISSUE TITLE
add wipe reference planes (maybe options for reference planes with/without hosted elements)

### ISSUE THREAD

**Issue by eirannejad** [eirannejad/pyRevit#98]

**Comment by eirannejad** [comment]
Added wipe reference planes to wipe model tool

**Comment by MitchBIM** [comment]
@eirannejad is there a way to remove all reference planes that don't have subcategories, associated dimensions or dependent elements?

**Comment by Robbo1234** [comment]
fyi, you can do this using Bonus tools "28_Reference_Plane_List"
http://www.kiwicodes-support.com/28_Reference_Plane_List

**Comment by MitchBIM** [comment]
Thanks for the response @Robbo1234. The tool you're referring to only does unnamed reference planes and allows you to locate per view. I'm really after something that can detect if a reference plane has a subcategory, if an element has been aligned and locked, if a dimension is associated to it or has a name assigned.

**Comment by Robbo1234** [comment]
MitchBIM, Bonus tools "28_Reference_Plane_List" detects named and un-named reference planes in the current view/selection or the entire project plus is detects if any dimensions are associated with the reference plane. (refer to screenshot). 
![image](https://user-images.githubusercontent.com/8776947/60957670-efca9480-a2fc-11e9-95e2-3dc0cd3f7a0c.png)

**Comment by MitchBIM** [comment]
@Robbo1234 thanks for that. So the only thing it's missing is the ability to identify if it's on a subcategory. I'd still love to see this in the PyRevit wipe tools.

**Comment by Robbo1234** [comment]
btw, there is another Bonus Tool called "128 Relationships" which checks the relationship before deleting an Element. (refer to screenshot)

![image](https://user-images.githubusercontent.com/8776947/61043887-4902f880-a3cf-11e9-9df2-6cdf31448555.png)
