### ISSUE TITLE
Ability to use third party python packages

### ISSUE THREAD

**Issue by tanabahh** [eirannejad/pyRevit#980]
**What I want**
Be able to connect any free python libraries.
**How I can do this now**
I only found a way to connect https://www.youtube.com/watch?v=Z3sFomss6Ks&list=PLc_1PNcpnV57OIsHFkc-zLFynurA6_jJR&index=5 but it's still not what I need.

Is there some other way to connect dependencies with the ability to update it, etc. For example, if I need to use something from pypi.

**Comment by eirannejad** [comment]
You can install the packages you need using `pip` and add the path to `sys.path` in your python script before importing the packages

**Comment by tanabahh** [comment]
Yes, thanks for the answer, but this solution is suitable for developers. I am interested in the other side of the question more. As a developer, I made my own extencion and would like to share it with users who are not developers. How could I share extencion using third party libraries with them? Considering that they are ordinary users, who cannot use pip, but just want to use my extension.

**Comment by eirannejad** [comment]
Read this page: https://www.notion.so/pyrevitlabs/Extension-Bundles-10df16fe826040bc9dbd9e83bb4248e6
- Extensions and bundles can have a `lib/` directory inside them
- There are also Library Extensions that are designed to ship python libraries to be used by other extensions

**Comment by sanzoghenzo** [comment]
Hi @eirannejad ,
I have the same need, I would like to add openpyxl for my python3 scripts.

I copied the openpyxl source package to a `.lib` extension, but obviously when I try to `import openpyxl` it complains about missing dependencies.

Should I add all the dependencies manually or is there a better way to achieve this?
