### ISSUE TITLE
Scaling Bounding Box Method for walls in Revit

### ISSUE THREAD

**Issue by kuldeep3618x** [eirannejad/pyRevit#986]
I am trying to select a list of Walls and getting filtered information from neighboring rooms. Revit seems to consider joined walls as extents to the Rooms and collecting more rooms than required.

I create bounding box for the walls and am trying to scale/reduce along X-co-ordinates.

So my question is what is the command line for scaling Bounding Boxes.
Please see the sample code below.

`    
 # Modifying/Scaling Bounding Box for Walls
         for h in wall_host:
             a = h.BoundingBox[activeV]
    
             min_bound_val = a.Min
             max_bound_val = a.Max
             cent = (max_bound_val + min_bound_val)/2
             center_pt = Point.ByCoordinates(cent.X,cent.Y,cent.Z)
    
             pl1 = Plane.ByOriginNormal(center_pt, Vector.ZAxis())
             min1 = min_bound_val.scale(pl1,1,0,0)
             max1 = max_bound_val.scale(pl1,1,0,0)
             testBB = BoundingBox.ByCornersCoordinateSystem(min1, max1, cent)
    
        print(testBB)    
 

`

**Comment by eirannejad** [comment]
There is no command line(?!). Just scale it in any direction you want
