### ISSUE TITLE
List which Titleblocks are on which sheets

### ISSUE THREAD

**Issue by Teflon98** [eirannejad/pyRevit#990]
The "Select Titleblocks on Sheets" tool is good for selecting the titleblock families on multiple sheets but there's no good way of knowing which family is already on which sheet. This is especially true when there are different families on the sheets.

I'm looking for a tool that produces a table/dialog that lists the sheet number, the titleblock family and the family type.  It would be even better to have a schedule that you can pull-down and choose a new family/type.

I created a Dynamo file (with some help), that outputs to an Excel sheet.
![Capture](https://user-images.githubusercontent.com/42452689/91887829-4c071b00-ec59-11ea-8044-c632942d7a32.png)

**Comment by Teflon98** [comment]
I just realized that the image I had posted was essentially blank and/or useless.

So sorry for that, and I am thrilled of possibly seeing a new tool.

Keep up the amazing work!

**Comment by alexdaversa** [comment]
You should be able to click the ID to select the titleblock you want to change. Adding a dropdown menu is a good bit above my current skill level but hopefully this tool is useful to you nonetheless.
