### ISSUE TITLE
Installation cannot obtain sufficient privileges to modify security permissions

### ISSUE THREAD

**Issue by alexberd** [eirannejad/pyRevit#991]
When installing I receive the error below.
![image](https://user-images.githubusercontent.com/4086522/92013786-23a91a80-ed46-11ea-92eb-842e318e76f7.png)

Please find below also the log file created during the installation.
 
[MSI4401.LOG](https://github.com/eirannejad/pyRevit/files/5163721/MSI4401.LOG)

Any advice will be really appreciated.

Many thanks,
Alex

**Comment by eirannejad** [comment]
It might be related to the powershell scripts that the installer needs to run. Your use might not have the necessary privileges. Try the newer 4.8.2 installer and see if that works

https://github.com/eirannejad/pyRevit/releases/tag/v4.8.2
