### ISSUE TITLE
Remove all (Core) py Revit Buttons

### ISSUE THREAD

**Issue by apsis0215** [eirannejad/pyRevit#997]
**Is your feature request related to a problem? Please describe.**
Treat CORE py Revit Buttons / menus like other buttons (Is there a way to do this now & Pick and choose which to remove and keep?)

**Describe the solution you'd like**
Treat like normal button structure pyRevit.tab\drawing set.panel, etc.

**Describe alternatives you've considered**
Have not found ways to edit the core tools yet : )

**Additional context**

**Comment by eirannejad** [comment]
You need to modify the built-in pyRevit extensions. Learn more about the pyRevit bundles and extensions here:
Extensions: https://www.notion.so/Extension-Bundles-10df16fe826040bc9dbd9e83bb4248e6
Bundles: https://www.notion.so/pyRevit-Bundles-12323e3090904d9aa7cdc3d82095d3e3

**Comment by apsis0215** [comment]
ty
