### ISSUE TITLE
Error when importing requests,flask and selenium

### ISSUE THREAD

**Issue by ifatBR** [eirannejad/pyRevit#999]
Hi Eiran,
I have a script that gets some info from the cluod, It uses the modules requests, selenium and flask.
When I run it from visual basic code it works fine.

But when I try running it as a pyRevit command, I get errors.
Is there something else I need to do to use these modules in a pyRevit command?

Attaching a snippet of the error I get:
![image](https://user-images.githubusercontent.com/51540582/93052790-73091800-f66f-11ea-9a96-717815899256.png)

Best,
Ifat.

**Comment by eirannejad** [comment]
Take a look at the **IronPython Engine Configurations** section on [this page](https://www.notion.so/pyrevitlabs/Anatomy-of-IronPython-Scripts-f11d0099667f46a28d29b028dd99ccaf#f14d37d830ba45178834b1ac50679678)

You need to set this global variable on top of your script:
```python
__fullframeengine__ = True
```

**Comment by ifatBR** [comment]
Thank you for the quick reply.
Best,
Ifat.

בתאריך יום ג׳, 15 בספט׳ 2020, 8:30, מאת Ehsan Iran-Nejad ‏<
notifications@github.com>:
